FO: fix getTotalWeight Notice
PrestaShop/PrestaShop pull request #10254
Opened 2018-09-03 12:46 UTC by GuillaumeKadolis

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 

getTotalWeight function (Cart.php) can return "Notice: Undefined index: " if $products is null and $this->id is null to 

getTotalWeight call updateProductWeight with null

```
if (!isset(self::$_totalWeight[$this->id])) {
    $this->updateProductWeight($this->id);
 }
```

but updateProductWeight return self::$_totalWeight[$productId] with $productId = 0 ($productId = (int) $productId);

so we retrun self::$_totalWeight[0] but into getTotalWeight we return self::$_totalWeight[$this->id];
self::$_totalWeight[null] != self::$_totalWeight[0]

it's possible to solve this by changing return line

2018-09-03 14:40 UTC, Quetzacoalt91 requested changes
Hi @GuillaumeKadolis,

As you said in your comment, `self::$_totalWeight[$this->id]` is always defined, here thanks to `$this->updateProductWeight($this->id);`.

I guess it would be better to see how to reproduce this error. If there is a place in the core where we call the method without ID or product list, this must be fixed.

Also, if the value is only stored in the key `0` because of the int cast, why don't you add the same action on the return line?

```php
return self::$_totalWeight[(int) $this->id];
```

Let us know if it removes the notice.

2018-09-03 14:56 UTC, GuillaumeKadolis commented
oh it's a cleaner solution thx, i changed my PR

2018-09-03 15:02 UTC, Quetzacoalt91 approved these changes

2018-09-04 09:08 UTC, merged

2018-09-04 09:08 UTC, Quetzacoalt91 commented
Thank you @GuillaumeKadolis