Move module instantiation methods in ModuleRepository
PrestaShop/PrestaShop pull request #10273
Opened 2018-09-04 13:43 UTC by Quetzacoalt91

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Methods instantiating Module objects were found in the Module class. They are moved in `ModuleRepository` before release.
| Type?         |  improvement
| Category?     | CO
| BC breaks?    | Nope, methods haven't been released yet.
| Deprecations? | Nope
| Fixed ticket? | /
| How to test?  | Page "module positions" still works.

2018-09-04 13:45 UTC, PierreRambaud commented on src/Core/Addon/Module/ModuleRepository.php
> +     * @return \Module instance
`@return LegacyModule`

2018-09-04 13:47 UTC, PierreRambaud commented on src/Core/Addon/Module/ModuleRepository.php
> +        return LegacyModule::getInstanceById((int) $moduleId);
@mickaelandrieu Wdyt about using `LegacyModule` outside `Adapter`?

2018-09-20 13:45 UTC, eternoendless requested changes

2018-09-20 13:45 UTC, eternoendless commented on src/Core/Addon/Module/ModuleRepository.php
> +        return LegacyModule::getInstanceById((int) $moduleId);
You can't use LegacyModule in the core namespace.

2018-09-20 13:58 UTC, mickaelandrieu commented on src/Core/Addon/Module/ModuleRepository.php
>      public function getInstanceByName($name)
this was wrong because developer mostly didn't understood what is Adapter strategy ;'(

2018-09-20 14:11 UTC, Quetzacoalt91 commented
Won't be merged. Closing.

2018-09-20 14:11 UTC, closed without merging