Small improvements for Webservice list
PrestaShop/PrestaShop pull request #10311
Opened 2018-09-06 11:08 UTC by tomas862

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | I added small improvements regarding file naming, missing dockblocks and other stuff regarding code quality. This PR is related with https://github.com/PrestaShop/PrestaShop/pull/10208 comments made by @sarjon.  
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | Page can be reached via admin-dev/index.php/configure/advanced/webservice/ and these changes impacts list only. It should work the same as it was in https://github.com/PrestaShop/PrestaShop/pull/10208

2018-09-07 13:51 UTC, mickaelandrieu commented on src/PrestaShopBundle/Resources/config/services/core/grid.yml
> +    prestashop.core.grid.query_builder.webservice_key:
should be prestashop.core.grid.query.webservice_key_query_builder

2018-09-07 13:56 UTC, mickaelandrieu approved these changes

2018-09-07 13:57 UTC, mickaelandrieu requested changes
small update of service name expected

2018-09-10 16:03 UTC, mickaelandrieu commented
Hello @tomas862,

sorry for the delay, would you mind to rebase so I can add the "waiting for QA" label?

Thanks

2018-09-10 16:03 UTC, mickaelandrieu approved these changes

2018-09-11 11:49 UTC, mickaelandrieu submitted a review, later dismissed

2018-09-11 11:50 UTC, mickaelandrieu commented
Hello, let's validate this by QA.

Once it's ok, I'll build assets again.

Mickaël

2018-09-11 11:53 UTC, tomas862 commented
Hello @mickaelandrieu  - I can rebase this Pull request this evening, thanks for review :)

2018-09-11 13:52 UTC, mickaelandrieu commented
Hello @tomas862, let's wait for QA approval first :)

2018-09-12 13:45 UTC, mickaelandrieu approved these changes

2018-09-12 14:15 UTC, mickaelandrieu commented
Good job @tomas862!

2018-09-12 14:15 UTC, merged