[wip] Document faceted search
PrestaShop/PrestaShop pull request #10406
Opened 2018-09-12 14:48 UTC by mickaelandrieu

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Added PHPDocs + minor refactoring
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Facet search in Front office should work as before.

2018-09-17 16:22 UTC, jolelievre commented on src/Core/Product/Search/ProductSearchResult.php
> +     */
`@return FacetCollection`

2018-09-17 16:22 UTC, jolelievre commented on src/Core/Product/Search/SortOrder.php
> +                $direction
possible to have a more specific Exception? `SearchException` ?

2018-09-17 16:22 UTC, jolelievre commented on src/Core/Product/Search/URLFragmentSerializer.php
> +     */
public methods should be placed before private ones

2018-09-17 16:22 UTC, jolelievre commented on src/Core/Product/Search/SortOrder.php
> +     * @return string
what is the purpose of returning a string here (`$this->direction`) ? whereas all other setters return `$this` which more useful to cascade setters

2018-09-20 06:47 UTC, mickaelandrieu commented on src/Core/Product/Search/SortOrder.php
> +     * @return string
I don't know but I can't break the public API :/

2018-10-11 10:10 UTC, mickaelandrieu commented on src/Core/Product/Search/SortOrder.php
> +                $direction
I'm not supposed to change the public API => it's a BC

2018-10-11 10:29 UTC, mickaelandrieu commented
Comments addressed, please review :)

Thanks @jolelievre :)

2018-10-29 21:11 UTC, mickaelandrieu commented
Tests are still failing but I can't figure out how to reproduce it locally, can someone take a look? @jolelievre maybe?

2018-10-30 08:53 UTC, jolelievre commented
ouh I am far from being an expert on the E2E tests ^^ just to be sure did you rebase your branche with recent changes on these tests? but I think they are pended with the 1.7.5>develop PR

2018-10-30 13:29 UTC, mickaelandrieu commented
yes, it's rebase from "16 hours ago" :+1:

2019-02-13 16:02 UTC, eternoendless requested changes
> Reviewed 7 of 24 files at r1, 9 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10406)* status: all files reviewed, 7 unresolved discussions (waiting on @jolelievre and @mickaelandrieu)

___
*[src/Core/Product/Search/SortOrderFactory.php, line 34 at r2](https://reviewable.io/reviews/prestashop/prestashop/10406#-LYbTnUA961Vplo_ksKa:-LYbTnUA961Vplo_ksKb:b-uukar5) ([raw file](https://github.com/prestashop/prestashop/blob/d4d0bbceba86e6c86ce04716317634b94d1e4f0f/src/Core/Product/Search/SortOrderFactory.php#L34)):*
> ```PHP
>  * This class is not a factory but a provider of default Sort Orders.
>  *
>  * @deprecated since 1.7.5 and to be removed in 1.8: use SortOrdersCollection:getDefaults instead.
> ```

We'll need to update this to 1.7.6
___
*[src/Core/Product/Search/SortOrderFactory.php, line 44 at r2](https://reviewable.io/reviews/prestashop/prestashop/10406#-LYbTrdVEd2rOeZrJy1C:-LYbTrdVEd2rOeZrJy1D:bbqep6w) ([raw file](https://github.com/prestashop/prestashop/blob/d4d0bbceba86e6c86ce04716317634b94d1e4f0f/src/Core/Product/Search/SortOrderFactory.php#L44)):*
> ```PHP
> 
>     public function __construct(TranslatorInterface $translator)
>     {
> ```

We should issue a deprecation notice here.
___
*[src/Core/Product/Search/SortOrderFactory.php, line 55 at r2](https://reviewable.io/reviews/prestashop/prestashop/10406#-LYb_vA539iTUegmiL-V:-LYb_vA539iTUegmiL-W:b-6nup9z) ([raw file](https://github.com/prestashop/prestashop/blob/d4d0bbceba86e6c86ce04716317634b94d1e4f0f/src/Core/Product/Search/SortOrderFactory.php#L55)):*
> ```PHP
>     public function getDefaultSortOrders()
>     {
>         return [
> ```

You could use the replacement class here to avoid duplicate code.
___
*[tests/Unit/Core/Product/Search/FacetTest.php, line 148 at r2](https://reviewable.io/reviews/prestashop/prestashop/10406#-LYbUzA62Mc_vduEjlH7:-LYbUzA62Mc_vduEjlH8:bgdw2pn) ([raw file](https://github.com/prestashop/prestashop/blob/d4d0bbceba86e6c86ce04716317634b94d1e4f0f/tests/Unit/Core/Product/Search/FacetTest.php#L148)):*
> ```PHP
>         $this->assertInstanceOf(Facet::class, $this->facet->setProperty('product_name', 'Nice cupcake'));
>         $this->assertSame('Nice cupcake', $this->facet->getProperty('product_name'));
>     }
> ```

Not sure that there's value in testing getters and setters. There's an interesting discussion about it here: https://stackoverflow.com/questions/6197370/should-unit-tests-be-written-for-getter-and-setters/


<!-- Sent from Reviewable.io -->

2019-02-13 16:02 UTC, eternoendless commented
I'm ok for merging all the comments as they are!

2019-02-21 14:10 UTC, mickaelandrieu commented
> I'm ok for merging all the comments as they are!

I will update my pull request: thanks for your review @eternoendless :+1:

2019-02-21 14:14 UTC, mickaelandrieu commented
> Not sure that there's value in testing getters and setters. There's an interesting discussion about it here: https://stackoverflow.com/questions/6197370/should-unit-tests-be-written-for-getter-and-setters/

You can't guess how many times a getter/setter is misused or introduce a bug. Also, having to have to write tests for them force any developer to think about the existence of these getter/setter: are they required or even useful?

Finally, they are really easy and fast to create and to execute. And as SOLID requires that a class should have 1 and only 1 reason to change: these tests don't need to be maintained, am I right? :angel:

2019-02-21 15:00 UTC, mickaelandrieu commented on src/Core/Product/Search/SortOrderFactory.php
> +        return SortOrdersCollection::getDefaults();
oups, it's not a static function, to be modified

2019-02-26 17:41 UTC, eternoendless submitted a review, later dismissed
> Reviewed 11 of 19 files at r3, 2 of 3 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10406)* status: all files reviewed, 5 unresolved discussions (waiting on @jolelievre and @mickaelandrieu)



<!-- Sent from Reviewable.io -->

2019-02-27 14:38 UTC, marionf commented
@mickaelandrieu When I click on a category, all filters are selected

![capture d ecran_1097](https://user-images.githubusercontent.com/13449658/53498034-c9bafb00-3aa5-11e9-9d96-1245d49ef72a.png)

2019-03-04 13:56 UTC, marionf commented
@mickaelandrieu 

I have a second page 1 with your PR

![capture d ecran_1110](https://user-images.githubusercontent.com/13449658/53737752-ade09c00-3e8d-11e9-9a8f-8ff667d103af.png)

2019-03-11 17:19 UTC, PierreRambaud approved these changes

2019-03-11 17:20 UTC, merged

2019-03-11 17:20 UTC, PierreRambaud commented
Thanks @mickaelandrieu