Add TranslatableType
PrestaShop/PrestaShop pull request #10704
Opened 2018-09-25 15:31 UTC by sarjon

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Extracted some changes from https://github.com/PrestaShop/PrestaShop/pull/10408
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | Review code and see screenshot below.

This is how it looks when used in form:

![translatable_type](https://user-images.githubusercontent.com/15143151/46025173-fc288c80-c0f0-11e8-884a-8a6c3af762e2.png)

2018-09-25 15:31 UTC, sarjon commented
@matks can you review?

2018-09-26 12:56 UTC, matks submitted a review, later dismissed

2018-09-26 12:57 UTC, matks commented
@sarjon 👍 

That was a great candidate for PR splitting 😉 

I'm sorry you need to rebase in order to make Travis build pass as Travis build have been fixed by https://github.com/PrestaShop/PrestaShop/pull/10716

2018-09-26 13:15 UTC, PierreRambaud commented
No need to rebase :)

2018-09-26 13:15 UTC, sarjon commented
> No need to rebase :)

already did. :D

2018-09-26 13:17 UTC, matks commented
@PierreRambaud yes indeed :)
sorry for the mistake @sarjon we only needed to relaunch travis build

2018-09-27 14:15 UTC, jolelievre requested changes
I don't understand the purpose of this new type, what is the difference with TranslateType or TranslateTextType?
is the purpose to have a generic TranslatableType in which you can inject any other FormType?

2018-09-27 14:32 UTC, sarjon commented
> I don't understand the purpose of this new type

@jolelievre as far as i know `TranslateType` is used in Product page and changing it could break it. Another issue is that `TranslateType` uses tabs instead of dropdowns to select language, for example: https://prnt.sc/kzfbbi

regarding `TranslateTextType` it should be depracated in favor of this new type as you can do the same (and even more) with it.

2018-09-27 15:03 UTC, jolelievre commented
Ok, I didn't know `TranslateType` was displayed with tabs, I figured it was like `TranslateTextType`
The you're right we should deprecate the former type, which means adding a throw a deprecation notice and add the appropriate annotation
And of course replace it everywhere it's been used so far

2018-09-27 15:04 UTC, jolelievre approved these changes

2018-09-27 15:08 UTC, jolelievre submitted a review, later dismissed
We should deprecate the form `TranslateTextType` by:
- adding a @deprecated annotation on it
- add this code in the constructor 
```php
@trigger_error('The '.__NAMESPACE__.'\TranslateTextType class is deprecated since version 1.7.6 and will be removed in 1.8. Use the '.__NAMESPACE__.'\TranslatableType class instead.', E_USER_DEPRECATED);
```
- switch the two types everywhere

2018-09-28 06:52 UTC, sarjon commented
@jolelievre done.

2018-09-28 07:58 UTC, jolelievre commented on src/PrestaShopBundle/Form/Admin/Type/TranslateTextType.php
> + * @deprecated The since version 1.7.6 and will be removed in 1.8. Use the TranslatableType instead.
just a little typo problem here

2018-09-28 08:08 UTC, sarjon commented on src/PrestaShopBundle/Form/Admin/Type/TranslateTextType.php
> + * @deprecated The since version 1.7.6 and will be removed in 1.8. Use the TranslatableType instead.
:man_facepalming: thanks, done.

2018-09-28 11:34 UTC, sarjon commented
@jolelievre @matks is it possible to merge it today? ^^

2018-09-28 15:07 UTC, matks commented
@sarjon I am surprised you were able to replace the usage of `TranslateType` so easily 😮 

Are you confident ? It looks "too nice" to be true ^^ ?

2018-09-30 09:03 UTC, sarjon commented
@matks yup, i tried to make it as simple as possible, but it would be nice to have QA validate it. :)

2018-10-01 13:08 UTC, matks approved these changes

2018-10-02 10:29 UTC, jolelievre approved these changes
nice job @sarjon

2018-10-03 14:56 UTC, merged

2018-10-03 14:56 UTC, Quetzacoalt91 commented
Thank you @sarjon