Fix sorting issue in the SQL Manager page
PrestaShop/PrestaShop pull request #10991
Opened 2018-10-12 14:26 UTC by khouloudbelguith

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | It is impossible to sort by SQL query in the SQL Manager page
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #10990
| How to test?  | Go to BO => Database / SQL Manager page => Create at least 2 SQL Query => After that, try to apply a sort on SQL Query with the icon

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/10991)

2018-10-12 14:57 UTC, marionf commented
@khouloudbelguith 
This is not a regression of 1.7.5.0, can you do it on develop branch please ?

2018-10-17 10:39 UTC, Quetzacoalt91 commented
Hmm, I'm not sure this fix is the best we could find.

This is not the first I see about the SQL columns in a table filtering, and instead of modifying all the occurrences which could trigger errors, I would rather make a global change.

In your case:

```sql
SELECT SQL_CALC_FOUND_ROWS  a.*  FROM `ps_request_sql` a     WHERE 1    ORDER BY sql DESC  LIMIT 0, 50;
```

Doesn't work. But

```sql
SELECT SQL_CALC_FOUND_ROWS  a.*  FROM `ps_request_sql` a     WHERE 1    ORDER BY a.sql DESC  LIMIT 0, 50;
```

works, thanks to your change, and

```sql
SELECT SQL_CALC_FOUND_ROWS  a.*  FROM `ps_request_sql` a     WHERE 1    ORDER BY `sql` DESC  LIMIT 0, 50;
```

works as well. It seems that applying quotes around the column names would make the SQL requests working in all case, without modifying the controller.

2018-10-17 14:59 UTC, jolelievre submitted a review, later dismissed
nice job! @khouloudbelguith

2018-10-17 17:35 UTC, Quetzacoalt91 requested changes
Sorry my last message was unclear but I requested changes.

2018-10-17 18:08 UTC, jolelievre commented
@Quetzacoalt91 I see your point, so I am not a pro of AdminController but it seems the change should be made here in this case:

https://github.com/PrestaShop/PrestaShop/blob/d0313c0881f957f9fab42bf2bb1a4e15df7081f0/classes/controller/AdminController.php#L3378

```php
        if (preg_match('/[.!]/', $orderBy)) {
            $orderBySplit = preg_split('/[.!]/', $orderBy);
            $orderBy = bqSQL($orderBySplit[0]) . '.`' . bqSQL($orderBySplit[1]) . '`';
        } elseif ($orderBy) {
            $orderBy = bqSQL($orderBy);
        }
```
becomes:
```php
        if (preg_match('/[.!]/', $orderBy)) {
            $orderBySplit = preg_split('/[.!]/', $orderBy);
            $orderBy = bqSQL($orderBySplit[0]) . '.`' . bqSQL($orderBySplit[1]) . '`';
        } elseif ($orderBy) {
            $orderBy = bqSQL('`' . $orderBy . '`');
        }
```

2018-10-17 18:12 UTC, Quetzacoalt91 commented
Almost, by looking at the existing code, a better solution would be

```php
            $orderBy = '`' . bqSQL($orderBy) . '`';
```

2018-10-17 18:57 UTC, jolelievre commented
that's what I thought initially, but in the previous condition the quote are integrated inside the bqSQL call:

```php
$orderBy = bqSQL($orderBySplit[0]) . '.`' . bqSQL($orderBySplit[1]) . '`';
```

weird?

2018-10-18 08:51 UTC, khouloudbelguith commented
Hi @Quetzacoalt91, @jolelievre, thanks for your review.
@Quetzacoalt91 Done, I made new changes & it works perfectly.

2018-10-18 08:53 UTC, jolelievre requested changes

2018-10-18 08:53 UTC, jolelievre commented on controllers/admin/AdminRequestSqlController.php
> +            'sql' => array('title' => $this->trans('SQL query', array(), 'Admin.Advparameters.Feature')),
I think that with the other modification in AdminController, this one is no longer useful

2018-10-18 08:57 UTC, Quetzacoalt91 approved these changes

2018-10-18 09:21 UTC, jolelievre commented
great! thank you @khouloudbelguith ^^

2018-10-18 09:21 UTC, jolelievre approved these changes

2018-10-18 10:00 UTC, merged

2018-10-18 10:00 UTC, PierreRambaud commented
Thanks @khouloudbelguith