create, edit, delete, exchange rate currency
PrestaShop/PrestaShop pull request #11069
Opened 2018-10-18 15:43 UTC by ansar21mallouli

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Create, edit, delete and live exchange rates currency
| Type?         | new feature
| Category?     |  TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | TEST_PATH=full/11_international/1_localization/3_currency npm run specific-test -- --URL=URLFrontOffice

2018-10-18 15:54 UTC, fatmaBouchekoua requested changes
Almost good ! Only one change.

2018-10-18 15:54 UTC, fatmaBouchekoua commented on tests/E2E/test/campaigns/common_scenarios/currency.js
> +      if (successMessage) {
You can use only the message parameter

2018-10-18 16:34 UTC, ansar21mallouli commented
@fatmaBouchekoua : Done.

2018-10-20 07:40 UTC, saymouMb submitted a review, later dismissed

2018-10-25 07:45 UTC, fatmaBouchekoua submitted a review, later dismissed

2018-10-25 14:39 UTC, marionf commented
@ansar21mallouli

I don't know why but there are some steps that take a lot of time:

1) Check the sort of currencies by iso code: 
- should click on sort by ASC icon
- should click on sort by desc icon

2) Check the sort of currencies by exchange rate
- should click on sort by ASC icon
- should click on sort by desc icon

3) delete currency
- should click on delete action from dropdown

Can we do it faster ?

2018-10-25 15:30 UTC, ansar21mallouli commented
@marionf 
For me the launch of the entire test sequence (create, edit, delete and exchange rate currency) takes 2 minutes.
The steps that you specify in your last comment take a few time to be executed.
In your case, how long it takes for you to execute all steps ?

2018-10-25 15:54 UTC, marionf commented
The entire sequence takes 13 minutes for me :hushed:

I made a screenrecord: https://drive.google.com/file/d/1hXFH5ssW70lc7aT68Qzzs-V2eH2zqfpS/view?usp=sharing

2018-10-25 16:21 UTC, ansar21mallouli commented
@marionf 
To run the test you need a fresh installation with English language & French country.

2018-10-25 16:38 UTC, marionf commented
All right, it's better like this :)
Thank you @ansar21mallouli

2018-10-26 16:57 UTC, fatmaBouchekoua submitted a review, later dismissed

2018-10-30 07:50 UTC, fatmaBouchekoua submitted a review, later dismissed

2018-10-30 07:51 UTC, fatmaBouchekoua commented
@mbadrani this PR is ready to be merged

2018-11-01 14:12 UTC, fatmaBouchekoua approved these changes

2018-12-03 10:36 UTC, closed without merging