avoid glitch on checkbox click
PrestaShop/PrestaShop pull request #11071
Opened 2018-10-18 16:38 UTC by jolelievre

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop / 1.7.5.x / 1.6.1.x
| Description?  | change in the product grid, in position mode, the mousedown target to the proper column to avoid glitch on checkbox click (the mousedown on the whole row didn't make sense anyway)
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/10319
| How to test?  |

2018-10-18 19:51 UTC, PierreRambaud commented on admin-dev/themes/default/js/bundle/product/catalog.js
> +	    const trParent = $(this).closest('tr');
No need to use const here, you never reuse the variable.
Watch out with indentation, sometimes 2, 4 and even 6 :)

2018-10-19 08:24 UTC, jolelievre commented
thanks @PierreRambaud I used a var, and I autoindented the whole file because it was messy :P

2018-10-19 12:18 UTC, eternoendless requested changes
Rules for indentation is 2 spaces for Javacript files. See [code conventions](https://devdocs.prestashop.com/1.7/development/coding-standards/#javascript-code-conventions).

Also, please fill out the table properly.

2018-10-19 13:11 UTC, jolelievre commented
my bad, I didn't pay attention to the branch, I changed the autoindent rules, so it's two spaces now

2018-10-19 14:24 UTC, eternoendless approved these changes
LGTM

2018-10-19 16:15 UTC, merged

2018-10-19 16:15 UTC, PierreRambaud commented
Thanks @jolelievre