Fix Search customer in specific group
PrestaShop/PrestaShop pull request #11085
Opened 2018-10-19 14:12 UTC by khouloudbelguith

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Navigate to a customer group which has more than one customer, then try to search with a name. On click "Search" you have to redirect to list of groups ...not having search results. Going back to the list of customers in the same group, search filter works OK, reset button same work.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #9825 
| How to test?  | Navigate to a customer group which has more than one customer, then try to search with a name. On click "Search" => Ok ( Same test with reset)

2018-12-10 02:12 UTC, mickaelandrieu commented
Hello @khouloudbelguith,

you can fix the coding style by executing this command and commit the updated files:

```
./vendor/bin/php-cs-fixer fix
```

Mickaël

2018-12-17 15:07 UTC, khouloudbelguith commented
Hi @mickaelandrieu,

Thanks for your review!
Done.

2019-07-09 10:25 UTC, jolelievre submitted a review, later dismissed
Thank you @khouloudbelguith

2019-07-09 16:11 UTC, PierreRambaud commented on controllers/admin/AdminGroupsController.php
> +            if (Tools::getIsset('submitFilter')) {
Why not also check for `Tools::getIsset('id_group')`?

2019-07-09 16:13 UTC, PierreRambaud commented on controllers/admin/AdminGroupsController.php
> +            if (Tools::getIsset('submitFilter')) {
And should it be?
```suggestion
            if (Tools::isSubmit('submitFilter')) {
```

2019-07-12 13:12 UTC, PierreRambaud requested changes
See my comment

2019-08-02 16:19 UTC, khouloudbelguith commented
Hi @PierreRambaud, @marionf this PR is replaced by this https://github.com/PrestaShop/PrestaShop/pull/14977

Thanks!

2019-08-02 16:19 UTC, closed without merging