CO: fix multishop bug fetching deliverable countries
PrestaShop/PrestaShop pull request #11128
Opened 2018-10-23 16:45 UTC by fire2

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | This fixes a bug where countries that have no carriers associated in current shop but have carriers in a different shop are returned incorrectly.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | 1) Create shared country between 2 shops.<br />2) Create different zones per shop that contain this country.<br />3) Create a carrier on shop 1 for the zone created.<br />4) Call the getDeliveredCountries function in Carrier.php from a shop 2 context (which has no carrier for the new country, thus the new country is not a "delivered country" --> it will be returned in the list of delivered countries because the carriers are not shop-joined in the query.

2018-12-10 02:08 UTC, mickaelandrieu commented
Hello,

this is the right fix to apply.

Thank you :+1: 

```
diff --git a/classes/Carrier.php b/classes/Carrier.php
index 0e135c383e..edf3a581fa 100644
--- a/classes/Carrier.php
+++ b/classes/Carrier.php
@@ -624,7 +624,7 @@ class CarrierCore extends ObjectModel
                        LEFT JOIN `' . _DB_PREFIX_ . 'country_lang` cl ON (c.`id_country` = cl.`id_country` AND cl.`id_lang` = ' . (int) $id_lang . ')
                        INNER JOIN (`' . _DB_PREFIX_ . 'carrier_zone` cz INNER JOIN `' . _DB_PREFIX_ . 'carrier` cr ON ( cr.id_carrier = cz.id_carrier AND cr.deleted = 0 ' .
             ($active_carriers ? 'AND cr.active = 1) ' : ') ') .
-                       Shop::addSqlAssociation('carrier', 'cr') . '
+            Shop::addSqlAssociation('carrier', 'cr') . '
                        LEFT JOIN `' . _DB_PREFIX_ . 'zone` zz ON cz.id_zone = zz.id_zone) ON zz.`id_zone` = c.`id_zone`
                        WHERE 1
                        ' . ($active_countries ? 'AND c.active = 1' : '') . '
```

2019-07-11 16:40 UTC, PierreRambaud commented on classes/Carrier.php
> + 			Shop::addSqlAssociation('carrier', 'cr') . '
```suggestion
            Shop::addSqlAssociation('carrier', 'cr') . '
```

2019-07-11 16:40 UTC, PierreRambaud requested changes
See my comment

2019-07-11 23:33 UTC, fire2 commented
> See my comment

Thank you, I committed the suggestion.

2019-07-12 08:28 UTC, PierreRambaud commented
Still error with PrettyCI. You need to rebase your branch with latest changes on develop branch.

2021-03-02 16:18 UTC, PierreRambaud commented
Hi @fire2 ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2021-03-02 16:18 UTC, closed without merging

2021-03-02 16:20 UTC, fire2 commented
This is still a bug in PS 1.6. It just wasn't accepted because of some wrong indentation.