Prevent unnecessary Order objects from being created in Admin Orders
PrestaShop/PrestaShop pull request #11235
Opened 2018-11-02 08:36 UTC by mnastalski

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Every order loaded into the backend's order list creates a new `Order` object to retrieve its' `id_currency`. This results in n+1 queries being executed (with 50 orders that's 50 extra queries). This PR aims to remove that behavior, by using `$tr`'s `id_currency` value instead.
| Type?         | improvement / refacto
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | Open the orders list in backend office.

2018-11-19 17:22 UTC, Quetzacoalt91 requested changes
Nice idea, I would however suggest a change to prevent compatibility issues wth modules which could use this method:

```php
    public static function setOrderCurrency($echo, $tr)
    {
        if (!empty($tr['id_currency'])) {
            $idCurrency = (int) $tr['id_currency'];
        } else {
            $order = new Order($tr['id_order']);
            $idCurrency = (int) $order->id_currency;
        }

        return Tools::displayPrice($echo, $idCurrency);
    }
```

By doing this, we add your performance improvement, but keep the backward compatibility with modules which only send the order id.

2018-11-19 22:37 UTC, mnastalski commented
@Quetzacoalt91 Sounds great, updated

2018-11-20 08:54 UTC, Quetzacoalt91 approved these changes

2018-11-20 16:40 UTC, merged

2018-11-20 16:40 UTC, Quetzacoalt91 commented
Thank you @mnastalski