Improve birthdate validation
PrestaShop/PrestaShop pull request #11470
Opened 2018-11-22 10:11 UTC by zessx

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Birthdate validation use some useless code, which could be improved
| Type?         | refacto
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | See following code

```php
function testBirthDate($strDate, $expected) 
{
	$date = date('Y-m-d', strtotime($strDate));
	$isBirthDate = Validate::isBirthDate($date);
	$success = $isBirthDate === $expected;
	printf(
		'[%s]: is%s a valid birthdate (test %s)<br>',
		$date,
		$isBirthDate ? '' : ' not',
		$success ? 'successful' : 'failed'
	);
}

testBirthDate('now', true); // Assuming current date is valid, which makes no sense both ways
testBirthDate('-1 day', true);
testBirthDate('+1 day', false);
testBirthDate('-1 month', true);
testBirthDate('-1 month -1 day', true);
testBirthDate('-1 month +1 day', true);
testBirthDate('+1 month', false);
testBirthDate('+1 month -1 day', false);
testBirthDate('+1 month +1 day', false);
testBirthDate('-1 year', true);
testBirthDate('-1 year -1 day', true);
testBirthDate('-1 year +1 day', true);
testBirthDate('-1 year -1 month', true);
testBirthDate('-1 year -1 month -1 day', true);
testBirthDate('-1 year -1 month +1 day', true);
testBirthDate('-1 year +1 month', true);
testBirthDate('-1 year +1 month -1 day', true);
testBirthDate('-1 year +1 month +1 day', true);
testBirthDate('+1 year', false);
testBirthDate('+1 year -1 day', false);
testBirthDate('+1 year +1 day', false);
testBirthDate('+1 year -1 month', false);
testBirthDate('+1 year -1 month -1 day', false);
testBirthDate('+1 year -1 month +1 day', false);
testBirthDate('+1 year +1 month', false);
testBirthDate('+1 year +1 month -1 day', false);
testBirthDate('+1 year +1 month +1 day', false);

/* output:
[2018-11-22]: is a valid birthdate (test successful)
[2018-11-21]: is a valid birthdate (test successful)
[2018-11-23]: is not a valid birthdate (test successful)
[2018-10-22]: is a valid birthdate (test successful)
[2018-10-21]: is a valid birthdate (test successful)
[2018-10-23]: is a valid birthdate (test successful)
[2018-12-22]: is not a valid birthdate (test successful)
[2018-12-21]: is not a valid birthdate (test successful)
[2018-12-23]: is not a valid birthdate (test successful)
[2017-11-22]: is a valid birthdate (test successful)
[2017-11-21]: is a valid birthdate (test successful)
[2017-11-23]: is a valid birthdate (test successful)
[2017-10-22]: is a valid birthdate (test successful)
[2017-10-21]: is a valid birthdate (test successful)
[2017-10-23]: is a valid birthdate (test successful)
[2017-12-22]: is a valid birthdate (test successful)
[2017-12-21]: is a valid birthdate (test successful)
[2017-12-23]: is a valid birthdate (test successful)
[2019-11-22]: is not a valid birthdate (test successful)
[2019-11-21]: is not a valid birthdate (test successful)
[2019-11-23]: is not a valid birthdate (test successful)
[2019-10-22]: is not a valid birthdate (test successful)
[2019-10-21]: is not a valid birthdate (test successful)
[2019-10-23]: is not a valid birthdate (test successful)
[2019-12-22]: is not a valid birthdate (test successful)
[2019-12-21]: is not a valid birthdate (test successful)
[2019-12-23]: is not a valid birthdate (test successful)
*/
```

2018-11-22 10:23 UTC, PierreRambaud commented on classes/Validate.php
> +            return strtotime($date) < time();
There is a problem with strtotime, it only parse any English textual datetime. This is why there is this complex regex ^^

2018-11-22 10:25 UTC, PierreRambaud requested changes
You must check with other date format.

2018-11-22 13:37 UTC, zessx commented on classes/Validate.php
> +            return strtotime($date) < time();
At this point, we already passed the regex test, to ensure we're using an English-format date. Therefore there is no problem to use the `$date` variable.

2018-11-22 14:11 UTC, PierreRambaud commented on classes/Validate.php
> +            return strtotime($date) < time();
Woot my bad, miss reading the regex :/

But it should be better to use something like:
```php
$d = DateTime::createFromFormat($date, 'Y-m-d');
if (false === $d) {
  return false;
}
return $d->getTimestamp() < time();
```
What do you think?

2018-11-22 14:31 UTC, zessx commented on classes/Validate.php
> +            return strtotime($date) < time();
I totally agree with this!

2018-11-22 15:19 UTC, PierreRambaud commented on classes/Validate.php
> +            return strtotime($date) < time();
Update your pull request, and we will be glad to merge it! :)

2019-01-23 15:08 UTC, zessx commented
Sorry, I've been busy and totally forgot this PR.  
Updated, with `DateTime` usage.

2019-01-23 15:12 UTC, PierreRambaud submitted a review, later dismissed

2019-01-23 15:31 UTC, mbadrani commented
@PierreRambaud do you have an idea on how to test this except looking at the code?

2019-01-23 16:32 UTC, PierreRambaud commented
Create an account and make sure all tests that @zessx created are still valid :)
Example:
-1 year -1 day => 2018/01/22 (if we are the 2019/01/23)
+1 year +1 month +1 day => 2020/02/24

2019-01-28 15:53 UTC, Quetzacoalt91 commented
The provided cases could be added in the existing tests:

```php
    public function isBirthDateProvider()
    {
        return array(
            array(true, '1991-04-19'),
            array(true, '2015-03-22'),
            array(true, '1945-07-25'),
            array(false, '2020-03-19'),
            array(false, '1991-03-33'), // <- nope
            array(false, '1991-15-19'),
            array(true, date('Y-m-d', strtotime('now'))), 
            array(true, date('Y-m-d', strtotime('-1 day'))),
            array(false, date('Y-m-d', strtotime('+1 day'))),
            array(true, date('Y-m-d', strtotime('-1 month'))),
            array(true, date('Y-m-d', strtotime('-1 month -1 day'))),
            array(true, date('Y-m-d', strtotime('-1 month +1 day'))),
            array(false, date('Y-m-d', strtotime('+1 month'))),
            array(false, date('Y-m-d', strtotime('+1 month -1 day'))),
            array(false, date('Y-m-d', strtotime('+1 month +1 day'))),
            array(true, date('Y-m-d', strtotime('-1 year'))),
            array(true, date('Y-m-d', strtotime('-1 year -1 day'))),
            array(true, date('Y-m-d', strtotime('-1 year +1 day'))),
            array(true, date('Y-m-d', strtotime('-1 year -1 month'))),
            array(true, date('Y-m-d', strtotime('-1 year -1 month -1 day'))),
            array(true, date('Y-m-d', strtotime('-1 year -1 month +1 day'))),
            array(true, date('Y-m-d', strtotime('-1 year +1 month'))),
            array(true, date('Y-m-d', strtotime('-1 year +1 month -1 day'))),
            array(true, date('Y-m-d', strtotime('-1 year +1 month +1 day'))),
            array(false, date('Y-m-d', strtotime('+1 year'))),
            array(false, date('Y-m-d', strtotime('+1 year -1 day'))),
            array(false, date('Y-m-d', strtotime('+1 year +1 day'))),
            array(false, date('Y-m-d', strtotime('+1 year -1 month'))),
            array(false, date('Y-m-d', strtotime('+1 year -1 month -1 day'))),
            array(false, date('Y-m-d', strtotime('+1 year -1 month +1 day'))),
            array(false, date('Y-m-d', strtotime('+1 year +1 month'))),
            array(false, date('Y-m-d', strtotime('+1 year +1 month -1 day'))),
            array(false, date('Y-m-d', strtotime('+1 year +1 month +1 day'))),
        );
    }
```

But did anybody saw the existing tests are now broken because of the changes? It seems some check have been removed.

2019-01-29 16:39 UTC, zessx commented
@Quetzacoalt91 Thanks for your message. The use of `DateTime` indeed remove the regex check, which was ensuring we're not using fake dates as `1991-03-33`.

I revert to the previous commit, which passes all the tests.

2019-01-29 18:51 UTC, PierreRambaud commented
@zessx @Quetzacoalt91 Tests were failing because of another issue (Addons api). The datetime approach is better because of strtotime can change with timezone :/

2019-01-30 11:38 UTC, Quetzacoalt91 commented
@PierreRambaud, in https://travis-ci.org/PrestaShop/PrestaShop/jobs/483444309 we can see the actual error:

```
There was 1 failure:
1) LegacyTests\Unit\Classes\ValidateCoreTest::testIsBirthDate with data set #4 (false, '1991-03-33')
Failed asserting that true matches expected false.
/home/travis/build/PrestaShop/PrestaShop/tests-legacy/Unit/Classes/ValidateCoreTest.php:66
```

The latest commit seems to fix this regression, and I allowed myself to add the cases given by this PR.

2019-01-30 18:45 UTC, PierreRambaud commented
Holy f**k, I'm a little bit tired --'.

This is the correct way to test if a date is valid :smile: 

```php
$d = DateTime::createFromFormat($date, 'Y-m-d');
if (!empty(DateTime::getLastErrors()['warning_count']) || false === $d) {
  return false;
}

return $d->getTimestamp() < time();
```

2019-01-31 08:29 UTC, Quetzacoalt91 commented
Looks like the codebase does definitely not want your check with `Datetime`, all tests are broken. :)

2019-01-31 11:27 UTC, PierreRambaud commented
Oops, should be ok now.

2019-01-31 12:02 UTC, Quetzacoalt91 submitted a review, later dismissed

2019-02-05 10:10 UTC, marionf commented
Hello @zessx 

I can create an account with these dates: 
1991-03-33, in the customer account 1991-04-02 is saved
1991-15-19, in the customer account 1992-03-19 is saved

https://drive.google.com/file/d/12TV1qGlxS4dioaM493dyC59rXlBBvOJt/view?usp=sharing

2019-02-07 10:41 UTC, PierreRambaud approved these changes

2019-02-07 10:41 UTC, merged

2019-02-07 10:41 UTC, PierreRambaud commented
Thanks @zessx