Introduce Domain tests using behat
PrestaShop/PrestaShop pull request #11560
Opened 2018-11-29 11:22 UTC by matks

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Introduce new domain tests structure, setup, scripts
| Type?         | refacto
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/issues/10733
| How to test?  | Travis tests should be green and include the new unit test

⚠️ This needs to add a new Travis build.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/11560)

2018-11-29 13:42 UTC, matks commented
@Quetzacoalt91 I prepared this PR to work with a new build on Travis, but this is just a suggestion, it can change if you think it's not a good idea.

2018-11-29 14:09 UTC, Quetzacoalt91 commented
If you think that is justified, go for it. This will obviously require more time to the whole process to complete (env preparation), but I understood you wanted to reduce it by optimizing the existing tests. :)
Keep in mind you have to update the `.travis.yml` file to add the `integration` step to the matrix.

2018-12-03 10:32 UTC, matks commented
@Quetzacoalt91 The idea is to replace existing tests by new tests with a better run strategy (this will provide better performances) but this will happen in a long time 😅 

Maybe it's better for me to make these Integration tests run after the unit tests then ? We keep then the split "unit test" = "now browser" and "e2e test" = "with a browser"

2018-12-10 01:32 UTC, mickaelandrieu commented
ping @eternoendless, I think the pull request is right but this is not what we need to validate here.

Do you want to introduce Behat in 1.7.x or not? I think this is the right moment to decide :+1:

2018-12-10 16:54 UTC, matks commented
https://github.com/PrestaShop/PrestaShop/pull/11560/commits/16977c0ca3afe919b00e8af322f0c6b237c896e8 introduces a Command test and the required behat hooks to reset the database as the Command modifies the database.

2 database reset hooks are available:
- `@database-light-reset` : scenarios tagged like this will perform their mysql into a `START TRANSACTION ... ROLLBACK` statement so database is not modified during the test
- `@database-hard-reset` : scenarios tagged like this will see the database reset at the end of the scenario using the time-consuming `DatabaseCreator::restoreTestDB()` function

So the light reset is faster, however it comes with a known limitation:

Since Command Handlers use ObjectModels, it's the legacy core `\Db` class that is being used so the connection used to start/rollback the SQL transaction is the one from `\Db`

**This means all queries must be performed through this connection.**

Example of a failing usecase:
1) scenario starts: we execute `START TRANSACTION` on PDO connection from `\Db` class
2) data are inserted into the database through the PDO connection of `\Db`
3) a COUNT query is performed using PDO connection of Doctrine in Symfony code
4) scenario ends: `ROLLBACK` performed through `\Db` connection

Here, step 3) result is wrong because. To be right, it must be performed through the PDO connection of  `Db` too.

2018-12-12 09:20 UTC, matks commented
As discussed with @eternoendless and @PierreRambaud yesterday, we will avoid using traits and use abstract contexts instead

2019-01-09 10:17 UTC, tomlev requested changes

2019-01-09 10:17 UTC, tomlev commented on composer.json
> +        "integration-domain-tests": [
this could be named "behavior-driven-tests", since we will use it for unit/integration/e2e tests

2019-01-09 10:17 UTC, tomlev commented on tests/Integration/Domain/features/bootstrap/FeatureContext.php
> +
no namespace here ?

2019-01-09 10:17 UTC, tomlev commented on tests/Integration/Domain/behat.yml
> +# nothing yet here
what about naming this folder "behavior" or something more descriptive ?

2019-01-09 16:15 UTC, eternoendless commented
Replaced by #12090

2019-01-09 16:15 UTC, closed without merging