Fix email processing in AdminCustomerThreadsController.php
PrestaShop/PrestaShop pull request #11586
Opened 2018-12-02 03:58 UTC by tymzap

Processing customer service message with `Tools::nl2br` when HTML emails are disabled is senseless, will thrown `<br/>` strings into the email text. This is quick fix for that.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Process message content by Tools::nl2br only if HTML emails are enabled. It just changes configuration value and perform process on message content if needed. 
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Send an answer with line breaks to a customer when only txt emails are enabled. <br/> string would be thrown into the mail text.

2018-12-04 23:53 UTC, mickaelandrieu requested changes
Some code to be linted

2018-12-04 23:53 UTC, mickaelandrieu commented on controllers/admin/AdminCustomerThreadsController.php
> +                    if (Configuration::get('PS_MAIL_TYPE') != Mail::TYPE_TEXT)
where are the curly braces? 👍

2018-12-04 23:59 UTC, mickaelandrieu commented
Hi @tymzap,

we almost never accept "quick fixes" because most of the time they create more issues than they solve.

2 issues here:

* You don't check for type and value, this means that if the configuration key equals "2" this will works. But let's imagine we update this code, using ``MAIL::TYPE_HTML`` instead. So your condition will works if the configuration key is 1, "1" or ... false. This may not be what we expect here, but we won't have any chance to figure out.

* about the curly braces,  it's difficult to figure when stopping the condition to check and if someone add something after, it will break the code.

Once you'll have fixed these issues, we can check for QA: thanks for your help!

2019-03-18 21:07 UTC, tymzap commented
Thanks, I think that's better now.

2020-08-19 16:42 UTC, matks commented
Hi @tymzap I am sorry this PR got stale.

I just looked at current version of the code on `develop` branch, the issue you wanted to fix is not there anymore. So this PR is unfortunately not needed anymore.

Thank you for your contribution.

2020-08-19 16:42 UTC, closed without merging