[WIP] Introduce dev tool: services graph visualizer
PrestaShop/PrestaShop pull request #11612
Opened 2018-12-04 17:34 UTC by matks

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Introduce a dev tool able to extract and display the Symfony services graph being used by a controller
| Type?         | new feature
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | New feature only available for devs

2018-12-04 17:38 UTC, matks commented
## Known issues

- https://github.com/PrestaShop/PrestaShop/pull/11612/files#diff-be8eb857f87cfff8499ff11beeaa2f35R35 hard dependency to http://www.webgraphviz.com/viz.js JS lib
- https://github.com/PrestaShop/PrestaShop/pull/11612/files#diff-bcd56a42c9b4c0f2ad64305ba5941271R40 CustomGraphvizDumper is a copy-paste of https://github.com/symfony/dependency-injection/blob/master/Dumper/GraphvizDumper.php just for this: https://github.com/PrestaShop/PrestaShop/pull/11612/files#diff-bcd56a42c9b4c0f2ad64305ba5941271R168
- only works with `$this->get('...');` statements in the controller https://github.com/PrestaShop/PrestaShop/pull/11612/files#diff-4563d0abb690a677bbe22ed84956cfa2R72

## Can be improved

- only target a given Controller action instead of the whole Controller
- better display (colors, sizing)
- better handling of not-services dependencies https://github.com/PrestaShop/PrestaShop/pull/11612/files#diff-4563d0abb690a677bbe22ed84956cfa2R158

2018-12-04 17:52 UTC, mickaelandrieu reviewed
Great feature! I have a lot of ideas to enrich and use it.

Good job @matks !

2018-12-04 17:52 UTC, mickaelandrieu commented on src/PrestaShopBundle/Resources/views/Dev/graph.html.twig
> +<div>
can we use a Symfony form for that?

2018-12-04 17:52 UTC, mickaelandrieu commented on src/PrestaShopBundle/Controller/Dev/ServicesGraphDumper.php
> +            $serviceId = (string)$argument;
you don't need to cast, the id is already casted in Reference constructor

2018-12-04 17:52 UTC, mickaelandrieu commented on src/PrestaShopBundle/Controller/Dev/ServicesGraphVisualizerController.php
> +namespace PrestaShopBundle\Controller\Dev;
thinking about it, if it's only available for people connected into the back office: it needs to be put into `Admin` namespace. How about `PrestaShopBundle\Controller\Admin\Dev` ?

2018-12-04 17:52 UTC, mickaelandrieu commented on src/PrestaShopBundle/Controller/Dev/ServicesGraphVisualizerController.php
> +class ServicesGraphVisualizerController extends Controller
needs some love regarding CS and PHPDocs

2018-12-11 11:08 UTC, jolelievre requested changes
this is awesome! this can really help for the migration if you look at a page as an example

extra idea: we could add a link between this feature and the symfony dev toolbar
https://symfony.com/doc/3.4/profiler/data_collector.html

2018-12-11 11:08 UTC, jolelievre commented on src/Core/Dev/ServicesGraph/ServicesGraphDumper.php
> +        $this->containerBuilder = $containerBuilder;
why not directly:

```
$this->containerBuilder = this->getPrestaShopContainerBuilder();
```

2018-12-11 11:08 UTC, jolelievre commented on src/Core/Dev/ServicesGraph/ServicesGraphDumper.php
> +            $this->tagDefinitionRecursivelyForGraphExploration($definition, $i);
the tag is added twice: in `tagDefinitionRecursivelyForGraphExploration` and at the end of `tagDefinitionArgumentRecursively` (should be handled inside the `else`)
also is it logic to tag a service if it hasn't been found?

2019-03-10 21:32 UTC, matks commented
Attempted to use main PS layout for the page, but this POC uses a higher jquery version 😭. Workaround that might actually turn even better: put this graph into the SF debug bar.

In SF debug bar, I can map what controller & action has been used. It should make the parsing even easier.

2020-02-28 21:55 UTC, matks commented
I cant find time to continue this project. I close this PR and might make it a side-project instead.

2020-02-28 21:55 UTC, closed without merging