Escape implicit backslashes
PrestaShop/PrestaShop pull request #11665
Opened 2018-12-08 18:35 UTC by MathiasReker

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Escape implicit backslashes
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  | /

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/11665)

2018-12-10 00:52 UTC, mickaelandrieu commented
Sadly, I'm not really good at string/regex stuff :lollipop:,

but we have @PierreRambaud who is really good at :+1:

2018-12-10 09:41 UTC, PierreRambaud commented on classes/Tools.php
> +	<FilesMatch \"\\.(ttf|ttc|otf|eot|woff|woff2|svg)$\">
Nope, otherwise a file named `thisiseot` will match. You need to revert this.

2018-12-10 09:41 UTC, PierreRambaud commented on classes/Translate.php
> +        $string = preg_replace("/\\\\*'/", "\\'", $string);
Backslashes were already escape

2018-12-10 09:41 UTC, PierreRambaud commented on classes/Translate.php
> +        $string = preg_replace("/\\\\*'/", "\\'", $string);
Backslashes were already escape

2018-12-10 09:47 UTC, PierreRambaud commented on admin-dev/filemanager/include/utils.php
> +        $str = preg_replace("/[^a-zA-Z0-9\\.\\[\\]_| -]/", '', $str);
Can you provide example of data?
You break the `[`, `.`, `]` and the `\` escapes.

2018-12-10 09:59 UTC, PierreRambaud commented on classes/Translate.php
> +        $string = preg_replace("/\\\\*'/", "\\'", $string);
Same here can you provide example?

2018-12-10 10:05 UTC, PierreRambaud commented on classes/db/DbPDO.php
> +        $replace = array('\\\\', '\\0', '\\n', '\\r', '\\Z', "\\'", '\"');
`\'`was already ok. Same for Z :)

2018-12-10 10:06 UTC, PierreRambaud commented on install-dev/upgrade/php/update_customer_default_group.php
> +    $pattern = "/define\\('_PS_DEFAULT_CUSTOMER_GROUP_', (\\d)\\);/";
Nope you break the regex

2018-12-10 10:06 UTC, PierreRambaud commented on tools/build/Library/ReleaseCreator.php
> +        $cmd = "cd {$argTempProjectPath} \\
You break the cli command.

2018-12-10 10:07 UTC, PierreRambaud requested changes
We can approve since you maybe add a script to replace single `\`  by `\\` :/

2018-12-11 13:41 UTC, MathiasReker commented
Sorry, @PierreRambaud. My script is apparently bugged. Should I close this PR

2018-12-11 13:41 UTC, closed without merging

2018-12-11 13:42 UTC, MathiasReker commented
If some changed should stay, please let me know.

2018-12-11 15:20 UTC, PierreRambaud commented
No problem @MathiasReker We really appreciate what you are doing for this project :smile: 
And hope you find the time to sleep :wink: