Fix classnames
PrestaShop/PrestaShop pull request #11668
Opened 2018-12-08 18:45 UTC by MathiasReker

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Classnames could be improved.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | /
| Deprecations? | /
| Fixed ticket? | /
| How to test?  | /

Misspelled filenames:

`tests-legacy\resources\modules\cronjobs\cronjobs.php` => `tests-legacy\resources\modules\cronjobs\CronJobs.php`

`install-dev\classes\datas.php` => `install-dev\classes\Datas.php`

2018-12-10 00:28 UTC, mickaelandrieu requested changes
2 more fixes to be done, then LGTM

2018-12-10 00:28 UTC, mickaelandrieu commented on install-dev/index_cli.php
> +require_once _PS_INSTALL_PATH_ . 'classes/Datas.php';
How about `session.php` and `exception.php`?

The names of the files are inconsistent with the classes inside

2018-12-10 08:25 UTC, MathiasReker commented on install-dev/index_cli.php
> +require_once _PS_INSTALL_PATH_ . 'classes/Datas.php';
Sure :)

2018-12-10 08:48 UTC, PierreRambaud commented on install-dev/index_cli.php
> +require_once _PS_INSTALL_PATH_ . 'classes/Datas.php';
@mickaelandrieu It's a BC if you rename files :/

2018-12-10 09:17 UTC, MathiasReker commented on install-dev/index_cli.php
> +require_once _PS_INSTALL_PATH_ . 'classes/Datas.php';
@PierreRambaud Agree, but does anyone override install files?

2018-12-10 10:18 UTC, PierreRambaud commented on install-dev/index_cli.php
> +require_once _PS_INSTALL_PATH_ . 'classes/Datas.php';
We don't know, but we can't add BC in 1.7.6.

2018-12-11 23:39 UTC, MathiasReker commented
Fix BC

2018-12-12 21:45 UTC, MathiasReker commented
Wdyt?

2018-12-13 09:51 UTC, PierreRambaud commented on src/PrestaShopBundle/Install/Simplexml.php
> +class Simplexml extends \SimpleXMLElement
Hum, changing this class can break something :/ More if this classe is not loaded with the autoloader.

2018-12-13 10:02 UTC, MathiasReker commented
@PierreRambaud Should I better close this PR again, to be safe?

2018-12-13 10:27 UTC, PierreRambaud commented
@MathiasReker I think :/ Really sorry

2018-12-13 10:31 UTC, MathiasReker commented
No problem :)

2018-12-13 10:32 UTC, closed without merging