Use of self
PrestaShop/PrestaShop pull request #11730
Opened 2018-12-12 00:44 UTC by MathiasReker

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Inside class or interface element self should be preferred to the class name itself.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | /
| How to test?  | /

2018-12-12 07:55 UTC, PierreRambaud submitted a review, later dismissed
@PrestaShop/prestashop-core-developers No need QA.

2018-12-12 09:31 UTC, jolelievre commented on var/SymfonyRequirements.php
> +    public function addCollection(self $collection)
I wouldn't touch to this file as it will change with Symfony upgrade

2018-12-12 09:36 UTC, jolelievre submitted a review, later dismissed

2018-12-12 09:36 UTC, jolelievre commented on src/Core/Localization/DataLayer/CurrencyDataLayerInterface.php
> +    public function setLowerLayer(self $lowerLayer);
As this is an interface I think it's better to keep the explicit Interface in the prototype

2018-12-12 09:36 UTC, jolelievre commented on src/Core/Localization/DataLayer/LocaleDataLayerInterface.php
> +    public function setLowerLayer(self $lowerLayer);
As this is an interface I think it's better to keep the explicit Interface in the prototype

2018-12-12 09:37 UTC, jolelievre requested changes
oups I clicked the wrong options, this needs a few changes

2018-12-12 12:24 UTC, MathiasReker commented
Thanks

2018-12-12 16:21 UTC, jolelievre submitted a review, later dismissed

2018-12-12 16:22 UTC, jolelievre commented
@PierreRambaud is it ok for you?

2018-12-13 09:46 UTC, PierreRambaud commented on src/Core/Localization/CLDR/LocaleData.php
> +    public function overrideWith(self $localeData)
Keep LocaleData

2018-12-13 09:46 UTC, PierreRambaud commented on src/Core/Localization/CLDR/NumberSymbolsData.php
> +    public function overrideWith(self $symbolsData)
keep NumberSymfolsData

2018-12-13 09:47 UTC, PierreRambaud commented on src/Core/Localization/Currency/CurrencyCollection.php
> +    public function addCollection(self $collection)
Keep CurrencyCollection

2018-12-13 09:48 UTC, PierreRambaud requested changes
Need to change methods signatures

2018-12-13 14:56 UTC, PierreRambaud approved these changes

2018-12-13 15:47 UTC, jolelievre commented
@PierreRambaud just out of curiosity, when do you consider `self` acceptable in some signatures rather than others?

2018-12-14 13:02 UTC, MathiasReker commented
Ready to get merged I think :)

2018-12-14 13:15 UTC, PierreRambaud commented on src/Core/Cart/AmountImmutable.php
> +    public function add(self $amount)
Need change

2018-12-14 13:16 UTC, PierreRambaud commented on src/Core/Cart/AmountImmutable.php
> +    public function sub(self $amount)
Need change

2018-12-14 13:16 UTC, PierreRambaud commented on src/Core/Domain/Category/ValueObject/CategoryId.php
> +    public function isEqual(self $categoryId)
Need change

2018-12-14 13:16 UTC, PierreRambaud commented on src/Core/Domain/Category/ValueObject/CategoryStatus.php
> +    public function isEqualTo(self $status)
Need change

2018-12-14 13:17 UTC, PierreRambaud commented on tools/build/Library/InstallUnpacker/classes/VersionNumber.php
> +    public function compare(self $otherNumber)
Need change

2018-12-14 13:17 UTC, PierreRambaud requested changes
Need change

2018-12-14 13:23 UTC, MathiasReker commented
@PierreRambaud solved

2018-12-18 09:50 UTC, MathiasReker commented
Ready to get merged? :)

2018-12-18 10:28 UTC, jolelievre submitted a review, later dismissed
Seems good to me, another approval from @PrestaShop/prestashop-core-developers before merging please

2018-12-18 11:15 UTC, eternoendless requested changes
This will break the overrides system.

All classes inside the `classes` directory should not use `self`.

Non overridable classes should use `static` instead of `self`.

2018-12-18 11:29 UTC, MathiasReker commented
I'm not sure which classes are not overridable?

2018-12-18 12:29 UTC, eternoendless commented
Just use `static` everywhere and you'll be safe.

2018-12-19 10:57 UTC, MathiasReker commented
I think it is OK now

2018-12-19 14:06 UTC, jolelievre submitted a review, later dismissed
@MathiasReker you need to use static everywhere instead of self, this is required to allow classes override with late static binding, more info here: https://www.leaseweb.com/labs/2014/04/static-versus-self-php/

2018-12-19 14:08 UTC, jolelievre commented
You can also rename the PR "Use of static instead of ClassName"

2018-12-19 15:17 UTC, MathiasReker commented
@jolelievre thanks for clarifying. I changed most of self to static. I let two places be self, because self was already used in same classes.

2018-12-19 15:20 UTC, jolelievre commented
> @jolelievre thanks for clarifying. I changed most of self to static. I let two places be self, because self was already used in same class.

It was probably an error to use self in the first place, @eternoendless wdyt? should we replace all `self` with `static` ?

2018-12-19 15:23 UTC, MathiasReker commented
@jolelievre would you like to use static instead of self for for the whole project?

2018-12-19 15:32 UTC, jolelievre commented
I'm not sure, I just discovered the difference between the two, so I'd prefer to have @eternoendless ' opinion

2018-12-19 15:46 UTC, Quetzacoalt91 commented
Be careful, I wonder how it works when an override exists for these class.

2018-12-19 17:46 UTC, MathiasReker commented
Conflicts solved.

2018-12-20 16:10 UTC, eternoendless commented
> Be careful, I wonder how it works when an override exists for these class.

An override is a child class that extends a core class: `Product extends ProductCore`.

Unless there's a mistake in the code, `ProductCore` should never be referenced directly, except when extending it. Instead, we always use it as `Product`.

The late static binding feature means that if we call `Product::doSomething()` statically, and `doSomething()` calls `static::doOtherThing()`, then PHP will call the implementation of `doOtherThing()` from the child class instead of the parent class.

This means that using `static` should be safe for overrides as long as we never call `ProductCore` directly.

2018-12-20 16:58 UTC, eternoendless commented
I rebased and squashed all commits from this branch. 

@MathiasReker in the future please rebase instead of merging develop into your branch. This keeps the branch history cleaner. If you don't know how to do it, [here's how](http://build.prestashop.com/howtos/misc/rebasing-your-git-branch/).

The squashing is optional, it depends if there are many things done in your PR. If it's mostly about changes required by the team, then it's better to squash those changes into a single commit.

2018-12-20 16:58 UTC, eternoendless submitted a review, later dismissed

2019-01-10 14:16 UTC, MathiasReker commented
all good now?

2019-03-26 08:32 UTC, PierreRambaud approved these changes

2019-03-26 08:33 UTC, PierreRambaud commented
LGTM wait for someone else to review

2019-03-29 16:25 UTC, eternoendless reviewed
LGTM

2019-03-29 16:48 UTC, merged

2019-03-29 16:48 UTC, PierreRambaud commented
Thanks @MathiasReker