CO: Fix bug when X-Forwarded-Host HTTP header has more than one host
PrestaShop/PrestaShop pull request #11810
Opened 2018-12-18 15:07 UTC by olivier-monaco

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Allow multiple values in X-Forwarded-Host header
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no

The HTTP header X-Forwarded-Host is not a standard header but come conventions are used by servers. For instance, Apache can include more than one host in this header.

See. https://httpd.apache.org/docs/current/en/mod/mod_proxy.html#x-headers

"Be careful when using these headers on the origin server, since they will contain more than one (comma-separated) value if the original request already contained one of these headers"

2018-12-19 17:06 UTC, mickaelandrieu approved these changes

2018-12-19 17:07 UTC, mickaelandrieu reviewed
Hmmm, as your fix is good I'm not sure we should handle this use case as this HTTP header should accept one and only one host => https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host

WDYT?

2018-12-19 17:19 UTC, PierreRambaud commented on classes/Tools.php
> +            $host = trim(array_pop(explode(',', $_SERVER['HTTP_X_FORWARDED_HOST'])));
why array_pop instead of the first one?

2018-12-19 17:23 UTC, PierreRambaud commented on classes/Tools.php
> +            $host = trim(array_pop(explode(',', $_SERVER['HTTP_X_FORWARDED_HOST'])));
And why explode with `,`? Because there is no RFC about having multiple values in this field.

2018-12-19 17:23 UTC, PierreRambaud commented
@mickaelandrieu Because some LB like F5 can be configured to have multiple values in this header.

2018-12-19 17:24 UTC, PierreRambaud requested changes
need feedback

2018-12-19 17:59 UTC, olivier-monaco commented
@mickaelandrieu and @PierreRambaud, as said in the description:
> The HTTP header X-Forwarded-Host is not a standard header but some conventions are used by servers. For instance, Apache can include more than one host in this header.
>
> See. https://httpd.apache.org/docs/current/en/mod/mod_proxy.html#x-headers
>
> "Be careful when using these headers on the origin server, since they will contain more than one (comma-separated) value if the original request already contained one of these headers"

So, this header is and will never be a standardized one. No RFC exists for this header. Mozilla says something, Apache other.

And I use array_pop because we had problem why an infrastructure where the client IP was the last. But this may not be the good way for other... In fact, PrestaShop must not use the X-Forwarded-for header because it cas be easily forged. This must be the job of the web server which must set REMOTE_ADDR using the X-Forwarded-For header is, and only is, it's safe to do...

So keeping the current code or using my PR is a security hole. But using my PR, it works for more hosting services.

2019-01-09 17:00 UTC, Quetzacoalt91 commented
As far as I understand from this discussion and how the other project handled it (i.e https://code.djangoproject.com/ticket/6880), a valid solution would be to stop using this server attribute instead?

2019-01-09 18:48 UTC, olivier-monaco commented
In fact the good way to handle this server attribute depend on the hosting environment. If you stop using this server attribute, you may break working installation. So you can do this only for major version.

I think the good way is to offer an configuration item to allow different scenarios. By default you keep the current way for 1.7 and may change the default way for the next major.

2019-01-10 08:33 UTC, PierreRambaud commented
Agreed with @Quetzacoalt91 but maybe we can use a feature flag like they did: https://github.com/django/django/commit/893cea211a
https://docs.djangoproject.com/en/2.1/ref/settings/#std:setting-USE_X_FORWARDED_HOST

2020-05-06 09:44 UTC, PierreRambaud commented
Hi @olivier-monaco ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2020-05-06 09:44 UTC, closed without merging

2020-05-06 14:15 UTC, olivier-monaco commented
Hi @PierreRambaud,

You had no news from me because your comment does not really need an answer. PrestaShop use a non-standardized header in a non-conventional way (in the mean not like major products use it). So removing the support for this header is a choice. But keeping it need to be more "standard" with this non-standard header ;).