Default carrier name was displayed as 0
PrestaShop/PrestaShop pull request #12140
Opened 2019-01-14 06:17 UTC by Gitdyr

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | In the back office order details the carrier name was displayed as "0" if the default carrier was used
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? |
| How to test?  | Install a shop from scratch and create an order where the default carrier is selected (the one bearing the shop's name)

2019-01-14 08:16 UTC, PierreRambaud commented
I could not reproduce your bug. Are you sure there is a `0` stored in database? 
If it is a data problem which can not be retrieve by sql request, I think it must be changed in PHP (instead of SQL request).

2019-01-14 21:45 UTC, Gitdyr commented
Yes, there is a 0 in the database.

Notice the method replaceZeroByShopName() in classes/Cart.php that fixes the problem in the cart.

2019-01-15 09:29 UTC, Quetzacoalt91 commented
Well, even if this sound less optimized, I would rather see it as a for loop, applying the method on the `carrier_name` of each line.

This would make the code easier to read, and will avoid some potential security issues by applying a PHP variable in the SQL request.

Thanks

2019-01-16 22:10 UTC, Gitdyr commented
Updated pull request.

2019-01-17 13:35 UTC, Quetzacoalt91 requested changes

2019-01-17 13:35 UTC, Quetzacoalt91 commented on classes/order/Order.php
> +            }
Prefer using directly the existing code.

```php
$row['carrier_name'] = Cart::replaceZeroByShopName($row['carrier_name'], null);
```

2019-01-20 11:09 UTC, Gitdyr commented
Updated pull request.

2019-01-21 09:04 UTC, PierreRambaud submitted a review, later dismissed
LGTM, wdyt @Quetzacoalt91 ?

2019-01-21 09:36 UTC, Quetzacoalt91 submitted a review, later dismissed

2019-01-21 17:17 UTC, PierreRambaud approved these changes

2019-01-22 08:48 UTC, merged

2019-01-22 08:48 UTC, PierreRambaud commented
Thanks @Gitdyr