Improve version
PrestaShop/PrestaShop pull request #12251
Opened 2019-01-21 19:09 UTC by eternoendless

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Improve Version significantly in order for future-proofing. Read below.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | A little (read below)
| Deprecations? | no
| Fixed ticket? | Maybe?
| How to test?  | Unit tested, should not have too big of an impact

# What's new

- Versions "1.7.5.0" and "7.5.0" are now considered equal. This effectively means that "1.7" is equal to "7" (instead of "17") regarding major version.
- It is now possible to have versions like "1.7.6.0-dev+nightly.20190131"
- `Version::buildFromString()` supports both legacy style versions (1.7.6.0) and semver style versions (7.6.0).
	- If you want the legacy version, you call `$version->getVersion()` (no BC here)
	- If you want the semver version, you call `$version->getSemVersion()`

Note: The constructor looks kind of wonky now, but I had to keep it like that in order to avoid breaking changes. I suggest using the static factory cited above only.

# What's changed (BC)

- `AppKernel::MAJOR_VERSION` is now "7" instead of "17".
- "1.2.4" is no longer greater than "1.2.3.4" (the latter is now interpreted now as "2.3.4") 🤯

2019-01-22 11:08 UTC, PierreRambaud commented on src/Core/Foundation/Version.php
> +            'getReleaseVersion() is deprecated since version 1.7.6.0 Use getPatchVersion() instead.',
since 7.6.0 instead?

2019-01-22 11:20 UTC, PierreRambaud commented on tests/Unit/Core/Foundation/VersionTest.php
> +    public function getCompareGreater()
Can you add tests for `compare` to make sure `version_compare` is working properly with `.7.7.0-dev+nightly.20190526`, `1.7.7.0-beta.1+build.156`, `1.7.6.0+test.build` for example.

2019-01-24 08:35 UTC, PierreRambaud requested changes
See comments

2019-03-01 09:19 UTC, eternoendless commented on src/Core/Foundation/Version.php
> +            'getReleaseVersion() is deprecated since version 1.7.6.0 Use getPatchVersion() instead.',
Officially versions are still 1.x.x.x

2019-03-04 14:08 UTC, PierreRambaud commented
Waiting for rebase

2019-03-04 15:07 UTC, eternoendless commented
Rebased 👍

2019-03-05 09:36 UTC, PierreRambaud submitted a review, later dismissed

2019-03-08 09:01 UTC, PierreRambaud approved these changes

2019-03-08 09:01 UTC, merged

2019-03-08 09:01 UTC, PierreRambaud commented
Thanks @eternoendless