Fix help sidebar when adding/editing language
PrestaShop/PrestaShop pull request #12668
Opened 2019-02-22 09:12 UTC by sarjon

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | In add/edit language pages, help sidebar was not loading properly, this PR fixes it.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | Sidebar help should load properly in Language add/edit pages.

2019-02-22 16:49 UTC, PierreRambaud commented on src/PrestaShopBundle/Controller/Admin/Improve/International/LanguageController.php
> +            'help_link' => $this->generateSidebarLink($request->attributes->get('_legacy_controller')),
enableSidebar should be add here?

2019-02-22 16:50 UTC, PierreRambaud commented on src/PrestaShopBundle/Controller/Admin/Improve/International/LanguageController.php
> +            'help_link' => $this->generateSidebarLink($request->attributes->get('_legacy_controller')),
enableSidebar should be add here?

2019-02-22 16:57 UTC, PierreRambaud requested changes
Add `enableSidebar` in render parameters instead. Be consistent with others controllers

2019-02-25 07:29 UTC, sarjon commented
@PierreRambaud done. :+1:

2019-02-25 08:34 UTC, PierreRambaud approved these changes

2019-02-25 08:34 UTC, PierreRambaud commented
If you have the time to create a pull request to change the few templates that use `set enableSliderbar`?

2019-02-25 15:53 UTC, sarjon commented
@matks is it ready for merge?

2019-02-25 16:35 UTC, merged

2019-02-25 16:35 UTC, PierreRambaud commented
Of course it is :smile: