Fix bug on block social in footer
PrestaShop/PrestaShop pull request #12891
Opened 2019-03-12 15:29 UTC by YeLnatSs

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | All icons on one line. new design for mobile
| Type?         | bug fix 
| Category?     | FO 
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | Fixes #12798 
| How to test?  | On Homepage scroll down to newsletter.

2019-03-12 16:02 UTC, PierreRambaud commented on themes/classic/_dev/css/components/footer.scss
> +  ul{
missing space before `{`

2019-03-14 09:15 UTC, YeLnatSs commented on themes/classic/_dev/css/components/footer.scss
> +  ul{
space added

2019-03-14 16:02 UTC, eternoendless commented
@YeLnatSs please remember to always compile your assets **in a separate commit**, so that when there are merge conflicts you can simply rebase, drop the commit including the compiled assets, compile them again, and force push them.

2019-05-14 12:23 UTC, jolelievre submitted a review, later dismissed
Seems good, thanks @YeLnatSs

2019-05-15 06:39 UTC, sarahdib commented
Hello @YeLnatSs the problem is solved on desktop version but not on mobile version 
<img width="379" alt="Capture d’écran 2019-05-15 à 08 38 26" src="https://user-images.githubusercontent.com/3034677/57753606-ddf9b600-76ec-11e9-8b4d-3d6ae745a3cf.png">

2019-05-15 07:59 UTC, YeLnatSs commented
Hello @sarahdib, the problem is solved. Mobile view was made following @NadiaCamard's advice.
I can work on it again if you want to.

2019-05-15 13:13 UTC, sarahdib commented
@YeLnatSs I saw with @TristanLDD and he said that is ok with two line :)

2019-05-15 13:20 UTC, YeLnatSs commented
@sarahdib Okay 😉

2019-05-15 14:03 UTC, PierreRambaud commented
Can you please rebase and target the 1.7.6.x branch instead, the issue was tagger for the 1.7.6?

2019-05-15 14:03 UTC, PierreRambaud requested changes
Waiting for rebase

2019-05-15 14:05 UTC, YeLnatSs commented
@PierreRambaud Okay no problem, I'm going to rebase it

2019-05-16 10:10 UTC, PierreRambaud approved these changes

2019-05-16 10:11 UTC, merged

2019-05-16 10:11 UTC, PierreRambaud commented
Thanks @YeLnatSs