Fix redirection when we are in a directory
PrestaShop/PrestaShop pull request #12920
Opened 2019-03-14 11:09 UTC by SebBareyre

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix redirection when we are in a directory (module route for example)
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | Try to access to a module route in directory structure that need to be logged in

2019-03-29 14:30 UTC, mickaelandrieu submitted a review, later dismissed

2019-03-29 15:18 UTC, PierreRambaud commented on classes/controller/FrontController.php
> +            Tools::redirect('/index.php?controller=authentication' . ($this->authRedirection ? '&back=' . $this->authRedirection : ''));
What happened if your prestashop is under a subdirectory like `http://website.com/shop`

2019-03-29 15:32 UTC, PierreRambaud commented
Need information before waiting for QA

2019-03-29 15:34 UTC, Quetzacoalt91 requested changes
Unfortunately, this change is in my opinion invalid.

I made a test from a ModuleFrontController which requires a customer to be logged in.
The URL generated on `develop` is:

```
http://[::1]/PrestaShop/fr/connexion
```

while with this PR we get
```
http://[::1]/PrestaShop/fr/index.php?controller==authentication
```

I unfortunately cannot reproduce the issue and this change brings another one. I'm not in favor in merging this PR. 


If you still have an issue on your side, could you consider this?

```php
            $request = [];
            if ($this->authRedirection) {
                $request['back'] = $this->authRedirection;
            }
            Tools::redirect($link->getPageLink('authentication', $useSSL, null, $request));
```

2019-04-17 11:36 UTC, SebBareyre reviewed
Here a fix of my PR

2021-03-02 16:52 UTC, PierreRambaud requested changes
I still didn't manage to reproduce the issue, can you please create a reproducible issue?

2021-07-16 13:03 UTC, PierreRambaud commented
Hi @SebBareyre ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2021-07-16 13:03 UTC, closed without merging