[WIP] Fallback on l() function in modules when calling trans() on legacy domains
PrestaShop/PrestaShop pull request #13059
Opened 2019-03-26 15:49 UTC by mickaelandrieu

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | See #13039
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | #13039 but probably most of the issues related to the translations management with #11321
| How to test?  | Look at the test, and install the "translations" module provided.

2019-03-26 18:47 UTC, mickaelandrieu commented on tests/Resources/modules/translations/README.md
> +This module is used to test the External Module Legacy System Provider, it contains 5 translations:
needs to be updated accordingly

2019-03-26 18:49 UTC, mickaelandrieu commented on tests/Resources/modules/translations/src/Controller/Admin/ExempleController.php
> +    public function indexAction()
needs a PHPUnit test to check the url content or to enable mink extension and http features of Behat, wdyt @matks ?

2019-03-26 18:49 UTC, mickaelandrieu commented on tests/Resources/modules/translations/src/Controller/Admin/ExempleController.php
> +        return $this->render('@Modules/masterclass/views/admin/index.html.twig', [
needs to be updated to translations

2019-03-26 18:49 UTC, mickaelandrieu commented on tests/Resources/modules/translations/views/admin/index.html.twig
> +{% endblock %}
"watch out EOL!" would say @PierreRambaud 👼

2019-03-28 14:18 UTC, mickaelandrieu commented on tests/Integration/Behaviour/Features/Context/LocaleFeatureContext.php
> +        Context::getContext()->getTranslator()->setLocale($locale);
not enough as we have 2 different translators in the application

2019-03-28 14:19 UTC, mickaelandrieu commented on tests/Integration/Behaviour/Features/Context/TranslationFeatureContext.php
> +        throw new PendingException();
needs to use the Translation service from the Symfony container this time

2019-03-28 14:59 UTC, mickaelandrieu commented on tests/Resources/modules/translations/views/admin/index.html.twig
> +{% endblock %}
fixed

2019-03-29 14:26 UTC, mickaelandrieu commented on src/PrestaShopBundle/Translation/Loader/LegacyFileTranslationLoader.php
> +        throw new \Exception('plop?');
of course, I need to use a specific exception here :)

2019-03-29 15:07 UTC, mickaelandrieu commented on src/PrestaShopBundle/Translation/Loader/LegacyFileTranslationLoader.php
> +    private function getModuleNameFromDomain($domain)
miss PHPDocs

2019-04-01 18:06 UTC, mickaelandrieu commented on src/Core/Translation/Util/ModuleDomainConverter.php
> +                levenshtein($guessedDomain, $domain) < 2
not required anymore

2019-04-01 18:08 UTC, mickaelandrieu commented on src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php
> +        if ($sourceFile === false) {
could replace the false on l.172

2019-04-01 18:22 UTC, mickaelandrieu commented
Hello, @matks I need to set the locale at Application/Kernel level: how I can do it in Behat?

Manual tests are working at controller level so, Twig should work too.

If we don't have workarounds for it, I'll drop Behat tests in favor of Symfony functional tests.

2019-04-03 09:56 UTC, mickaelandrieu commented on tests/Resources/modules/translations/src/Controller/Admin/ExempleController.php
> +    public function indexAction()
not needed at Behat tests pass: solved

2019-04-03 10:09 UTC, tomlev requested changes
> Reviewed 5 of 15 files at r1, 12 of 13 files at r2, 1 of 4 files at r3, 2 of 3 files at r4, 6 of 13 files at r5, 3 of 5 files at r7, 4 of 5 files at r8, 6 of 6 files at r10.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13059)* status: all files reviewed, 14 unresolved discussions (waiting on @mickaelandrieu)

___
*[tests/Integration/Behaviour/Features/Context/AbstractPrestaShopFeatureContext.php, line 40 at r10](https://reviewable.io/reviews/prestashop/prestashop/13059#-LbXcqBJ22mcRJxiCzVh:-LbXcqBJ22mcRJxiCzVi:bg3krn) ([raw file](https://github.com/prestashop/prestashop/blob/d673688795e3781e13feb5feeb550953453f3ae6/tests/Integration/Behaviour/Features/Context/AbstractPrestaShopFeatureContext.php#L40)):*
> ```PHP
> abstract class AbstractPrestaShopFeatureContext implements BehatContext
> {
>     const MODULES_DIRECTORY = __DIR__ . '/../../../../Resources/modules';
> ```

you should use a constant for root here, relative path is not maintainable enough 
___
*[tests/Integration/Behaviour/Features/Context/TranslationFeatureContext.php, line 46 at r10](https://reviewable.io/reviews/prestashop/prestashop/13059#-LbXdhW-EH67w80VP1xf:-LbXdhW-EH67w80VP1xg:b6mqlde) ([raw file](https://github.com/prestashop/prestashop/blob/d673688795e3781e13feb5feeb550953453f3ae6/tests/Integration/Behaviour/Features/Context/TranslationFeatureContext.php#L46)):*
> ```PHP
>      * @BeforeSuite
>      */
>     public static function prepare($scope)
> ```

useless if you use CommonFeatureContext in your test suite: CommonFeatureContext::prepare will be loaded before each of your suites since this is declared as "@BeforeSuite" (without tag)
___
*[tests/Integration/Behaviour/Features/Context/TranslationFeatureContext.php, line 54 at r10](https://reviewable.io/reviews/prestashop/prestashop/13059#-LbXe1cfBTXBIzJaaJpM:-LbXe1cfBTXBIzJaaJpN:b-x8e2ua) ([raw file](https://github.com/prestashop/prestashop/blob/d673688795e3781e13feb5feeb550953453f3ae6/tests/Integration/Behaviour/Features/Context/TranslationFeatureContext.php#L54)):*
> ```PHP
> 
>     /**
>      * @Given I have a legacy translation for :translation in locale :locale in the module :module
> ```

I... means user makes some action (When)
if it is a check it has to be "... should..."
if it is a precondition it could be '"there is" or something like that
___
*[tests/Integration/Behaviour/Features/Context/TranslationFeatureContext.php, line 76 at r10](https://reviewable.io/reviews/prestashop/prestashop/13059#-LbXeZFm0xAqKkpjPtup:-LbXeZFm0xAqKkpjPtuq:bbmkwha) ([raw file](https://github.com/prestashop/prestashop/blob/d673688795e3781e13feb5feeb550953453f3ae6/tests/Integration/Behaviour/Features/Context/TranslationFeatureContext.php#L76)):*
> ```PHP
> 
>     /**
>      * @Then the Module translated version of :key using domain :domain should be :value using locale :locale
> ```

why Module with cap ?


<!-- Sent from Reviewable.io -->

2019-04-03 12:20 UTC, mickaelandrieu reviewed
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13059)* status: all files reviewed, 14 unresolved discussions (waiting on @given and @tomlev)

___
*[tests/Integration/Behaviour/Features/Context/AbstractPrestaShopFeatureContext.php, line 40 at r10](https://reviewable.io/reviews/prestashop/prestashop/13059#-LbXcqBJ22mcRJxiCzVh:-LbY7Sv1BJAl_uNSKwyg:bve33t9) ([raw file](https://github.com/prestashop/prestashop/blob/d673688795e3781e13feb5feeb550953453f3ae6/tests/Integration/Behaviour/Features/Context/AbstractPrestaShopFeatureContext.php#L40)):*
<details><summary><i>Previously, tomlev (Thomas LEVIANDIER) wrote…</i></summary><blockquote>

you should use a constant for root here, relative path is not maintainable enough 
</blockquote></details>

what do you suggest? I'm not sure to understand what we could do to improve that :/
___
*[tests/Integration/Behaviour/Features/Context/LocaleFeatureContext.php, line 38 at r2](https://reviewable.io/reviews/prestashop/prestashop/13059#-LaugKDR5kcMvVaAToLO-r2-38:-LbY7_rz9oNOdW7XOSep:b-tegsej) ([raw file](https://github.com/prestashop/prestashop/blob/018182278f7a2178135db18e839124fc3012f59f/tests/Integration/Behaviour/Features/Context/LocaleFeatureContext.php#L38)):*
<details><summary><i>Previously, mickaelandrieu (Mickaël Andrieu) wrote…</i></summary><blockquote>

not enough as we have 2 different translators in the application
</blockquote></details>

tests pass so I guess it does
___
*[tests/Integration/Behaviour/Features/Context/TranslationFeatureContext.php, line 46 at r10](https://reviewable.io/reviews/prestashop/prestashop/13059#-LbXdhW-EH67w80VP1xf:-LbY7dII0Jmb_yRuF-Hh:bo3nqzq) ([raw file](https://github.com/prestashop/prestashop/blob/d673688795e3781e13feb5feeb550953453f3ae6/tests/Integration/Behaviour/Features/Context/TranslationFeatureContext.php#L46)):*
<details><summary><i>Previously, tomlev (Thomas LEVIANDIER) wrote…</i></summary><blockquote>

useless if you use CommonFeatureContext in your test suite: CommonFeatureContext::prepare will be loaded before each of your suites since this is declared as "@BeforeSuite" (without tag)
</blockquote></details>

it was what i did at first step, but I was unable to access the container in my assertions: maybe did I miss an extra operation? Can you poc something?
___
*[tests/Integration/Behaviour/Features/Context/TranslationFeatureContext.php, line 54 at r10](https://reviewable.io/reviews/prestashop/prestashop/13059#-LbXe1cfBTXBIzJaaJpM:-LbY7oEfEAiNBq2rSbtt:b-l2xj85) ([raw file](https://github.com/prestashop/prestashop/blob/d673688795e3781e13feb5feeb550953453f3ae6/tests/Integration/Behaviour/Features/Context/TranslationFeatureContext.php#L54)):*
<details><summary><i>Previously, tomlev (Thomas LEVIANDIER) wrote…</i></summary><blockquote>

I... means user makes some action (When)
if it is a check it has to be "... should..."
if it is a precondition it could be '"there is" or something like that
</blockquote></details>

is it good if I replace it by "@Given There is a legacy translation for :translation in :locale for the module :module" ?
___
*[tests/Integration/Behaviour/Features/Context/TranslationFeatureContext.php, line 76 at r10](https://reviewable.io/reviews/prestashop/prestashop/13059#-LbXeZFm0xAqKkpjPtup:-LbY7y-y2_x-GXlW688l:b9ra5sw) ([raw file](https://github.com/prestashop/prestashop/blob/d673688795e3781e13feb5feeb550953453f3ae6/tests/Integration/Behaviour/Features/Context/TranslationFeatureContext.php#L76)):*
<details><summary><i>Previously, tomlev (Thomas LEVIANDIER) wrote…</i></summary><blockquote>

why Module with cap ?
</blockquote></details>

you're right (it was for consistency with Twig), I'll remove it.


<!-- Sent from Reviewable.io -->

2019-04-04 02:45 UTC, mickaelandrieu commented
Only E2E tests are failing, but as I'm unable to reproduce it on local because the docker image is broken I can't fix it.

I assign @mbadrani to add more docs on how I can launch the E2E test suite.

2019-04-05 14:46 UTC, eternoendless commented
This PR makes changes to files unrelated to the original issue, but which will be useful later. I squashed all commits from this branch, reverted unrelated files, and pushed it in this PR: https://github.com/PrestaShop/PrestaShop/pull/13221

2019-04-05 16:53 UTC, mickaelandrieu commented on src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php
> -            && substr_count($domain, '.') === 1
this check is required because the first condition is met by 2 domains as stated in the PHPDocs

2019-04-05 17:12 UTC, mickaelandrieu commented
> This PR makes changes to files unrelated to the original issue, but which will be useful later. I squashed all commits from this branch, reverted unrelated files, and pushed it in this PR: #13221

Ok, I'll rebase my PR once yours is merged!

2019-05-05 01:52 UTC, closed without merging