Not required select and disabled option
PrestaShop/PrestaShop pull request #13451
Opened 2019-04-17 10:31 UTC by EvoWebFrance

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | When a select is not required, remove the "disabled" attribute of the empty option.
| Type?         | improvement
| Category?     | FO 
| BC breaks?    | no
| Deprecations? |no
| Fixed ticket? | 
| How to test?  | Create a form with a select not required select input

2019-05-01 09:49 UTC, Quetzacoalt91 commented
Hi @EvoWebFrance,

What need are you solving here? After a quick check, having a disabled option on a non-required select won't prevent the form to be sent.

2019-05-03 09:36 UTC, EvoWebFrance commented
Hello,
I use this select-box in a form of an additionnal part of the "my account" panel.
In this form, sometimes a customer can choose an on option of the select-box and sometimes not (in my case, an option for a specific delivery of a module I develloped). I should be able to do this because the select box is not required.
As the "Disabled" attribute is permanent in the first choice of the select-box, the customer can't choose it after having choosen an another option.

Thank you and sorry for my bad english

2020-01-02 21:55 UTC, matks commented
@NeOMakinG I think you handled a similar bug recently 🤔can you check ?

2020-01-03 14:25 UTC, NeOMakinG commented
I don't remember handling a similar thing, but it looks fine for me, ofc if the field is not required you should be able to choose the "non-selected" option

2020-01-03 14:26 UTC, NeOMakinG approved these changes

2020-01-03 14:27 UTC, NeOMakinG requested changes

2020-01-03 14:27 UTC, NeOMakinG commented on themes/classic/templates/_partials/form-fields.tpl
> +            <option value {if $field.required}disabled{/if} selected>{l s='-- please choose --' d='Shop.Forms.Labels'}</option>
```suggestion
            <option value {if $field.required}disabled {/if}selected>{l s='-- please choose --' d='Shop.Forms.Labels'}</option>
```

2020-01-03 14:29 UTC, NeOMakinG commented on themes/classic/templates/_partials/form-fields.tpl
> +            <option value {if $field.required}disabled{/if} selected>{l s='-- please choose --' d='Shop.Forms.Labels'}</option>
Could you please commit that before I send it to QA ? @EvoWebFrance

2020-01-10 15:06 UTC, NeOMakinG approved these changes

2020-02-07 15:23 UTC, matks commented
@EvoWebFrance PrettyCI complains because PHP CS Fixer found codestyle issues in your PR. Can you handle them ? You can by running `php vendor/bin/php-cs-fixer fix`

2020-04-20 08:59 UTC, Progi1984 commented
@EvoWebFrance Thank you for your contribution. Could you target the `develop` branch ?

2020-04-20 09:00 UTC, Progi1984 commented
Hello @EvoWebFrance, thanks for your contribution, would you mind to rebase your pull request? Thanks

2021-03-02 16:55 UTC, PierreRambaud commented
Hi @EvoWebFrance ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2021-03-02 16:55 UTC, closed without merging