Set null values when trying to retrieve the non-existing default shop
PrestaShop/PrestaShop pull request #13471
Opened 2019-04-18 10:52 UTC by Quetzacoalt91

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Fixes an issue while switching on a new language not existing locally, during the installation process
| Type?         | bug fix
| Category?     | IN
| BC breaks?    | Nope
| Deprecations? | Nope
| Fixed ticket? | Fixes #13401
| How to test?  | When reaching the installer, switch on a language not yet installed on your filesystem (you may need to remove content in app/Resources/translations)

2019-04-18 11:21 UTC, tomlev submitted a review, later dismissed

2019-04-18 19:13 UTC, tomlev submitted a review, later dismissed

2019-04-23 15:02 UTC, matks commented
@Quetzacoalt91 Shouldn't this PR target `1.7.6.x` branch ?

2019-04-24 14:50 UTC, Quetzacoalt91 commented
Indeed. Base branch has been updated

2019-04-26 14:21 UTC, jolelievre requested changes
Hi, with the changes from https://github.com/PrestaShop/PrestaShop/pull/13547
You should rebase this PR with the changes in `Language::installEmailsLanguagePack` and use `true` as third parameter to force overwriting files.
(As the former method did by extracting the archive over existing files)

2019-04-26 14:53 UTC, Quetzacoalt91 commented
Done, thanks!

2019-04-26 14:54 UTC, jolelievre submitted a review, later dismissed

2019-04-26 15:01 UTC, Quetzacoalt91 commented
Done by @jolelievre

2019-04-30 15:28 UTC, jolelievre commented
Can someone from @PrestaShop/prestashop-core-developers approve this one please ^^

2019-04-30 15:31 UTC, PierreRambaud approved these changes

2019-04-30 15:57 UTC, merged

2019-04-30 15:57 UTC, jolelievre commented
Thanks @Quetzacoalt91