Adding zones for: Austria, Switzerland, Denkmark, Netherlands, Thaila…
PrestaShop/PrestaShop pull request #13636
Opened 2019-05-02 14:10 UTC by manfield

Adding zones for: Austria, Switzerland, Denkmark, Netherlands, Thailand (the last one mandatory for Paypal Payments API)

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Added missing states for some countries
| Type?         |  improvement 
| Category?     |  CO 
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| How to test?  | Just import localization package from these conf file

2019-09-27 14:35 UTC, Progi1984 commented
@manfield Hi. Thank you for your contribution. Please, could you revert your changes on the indentation ? Thanks.

2019-09-30 07:29 UTC, Progi1984 requested changes

2019-09-30 07:29 UTC, Progi1984 commented on localization/at.xml
> +	<state name="Burgenland" iso_code="AT-1" country="AT" zone="Europe" tax_behavior="0" />
@manfield Could you indent state tags 2 spaces ? Please.

2019-09-30 07:29 UTC, Progi1984 commented on localization/dk.xml
> +	<state name="Hovedstaden" iso_code="DK-84" country="DK" zone="Europe" tax_behavior="0" />
@manfield Could you indent state tags 2 spaces ? Please.

2019-09-30 07:29 UTC, Progi1984 commented on localization/nl.xml
> +	<state name="Drenthe" iso_code="NL-DR" country="NL" zone="Europe" tax_behavior="0" />
@manfield Could you indent state tags 2 spaces ? Please.

2019-09-30 07:30 UTC, Progi1984 commented
@LouiseBonnard I need your review for this PR. Thanks :)

2019-09-30 07:58 UTC, manfield commented
Sorry for indentation issues.

2019-09-30 07:59 UTC, Progi1984 submitted a review, later dismissed

2019-09-30 08:59 UTC, LouiseBonnard commented
Hello, it seems alright to me, although I'm not certain about the double names regarding the Suiss zones. Wouldn't it be better to write German-speaking zones in German and French-speaking zones in French?

Also, I'll send this PR to the translating community so that we can double-check it with native people from those countries. :-)

2019-09-30 09:51 UTC, bulldesign commented
The Danish zones/regions are correct 👍

2019-09-30 12:20 UTC, LouiseBonnard commented
I got a feedback from a Danish translator who said Denmark uses the International System of Units so units should be:

`<units>
    <unit type="weight" value="kg"/>
    <unit type="volume" value="L"/>
    <unit type="short_distance" value="cm"/>
    <unit type="base_distance" value="m"/>
    <unit type="long_distance" value="km"/>
  </units>`

And this has been confirmed by Marilou here at PrestaShop. ;-)

2019-09-30 15:03 UTC, mark-app commented
For NL 

More changes: The low tax is changed on 01-01-2019 from 6% to 9%.

Line 11:

<tax id="2" name="BTW NL 6%" rate="6"/>

Change to:

<tax id="2" name="BTW NL 9%" rate="9"/>

Line 68:

<taxRulesGroup name="NL Reduced Rate (6%)">

Change to:

<taxRulesGroup name="NL Reduced Rate (9%)">

line 97:

<taxRulesGroup name="NL Foodstuff Rate (6%)">

Change to:

<taxRulesGroup name="NL Foodstuff Rate (9%)">

Line 126:

<taxRulesGroup name="NL Books Rate (6%)">

Change to:

<taxRulesGroup name="NL Books Rate (9%)">


States should be:

<states>
    <state name="Drenthe" iso_code="NL-DR" country="NL" zone="Europe" tax_behavior="0" />
    <state name="Flevoland" iso_code="NL-FL" country="NL" zone="Europe" tax_behavior="0" />
    <state name="Friesland" iso_code="NL-FR" country="NL" zone="Europe" tax_behavior="0" />
    <state name="Gelderland" iso_code="NL-GE" country="NL" zone="Europe" tax_behavior="0" />
    <state name="Groningen" iso_code="NL-GR" country="NL" zone="Europe" tax_behavior="0" />
    <state name="Limburg" iso_code="NL-LI" country="NL" zone="Europe" tax_behavior="0" />
    <state name="Noord-Brabant" iso_code="NL-NB" country="NL" zone="Europe" tax_behavior="0" />
    <state name="Noord-Holland" iso_code="NL-NH" country="NL" zone="Europe" tax_behavior="0" />
    <state name="Overijssel" iso_code="NL-OV" country="NL" zone="Europe" tax_behavior="0" />
    <state name="Utrecht" iso_code="NL-UT" country="NL" zone="Europe" tax_behavior="0" />
    <state name="Zeeland" iso_code="NL-ZE" country="NL" zone="Europe" tax_behavior="0" />
    <state name="Zuid-Holland" iso_code="NL-ZH" country="NL" zone="Europe" tax_behavior="0" />
  </states>

2019-10-18 09:12 UTC, Progi1984 commented on localization/au.xml
> +    <state name="Australian Capital Territory" iso_code="ACT" country="AU" zone="Oceania" tax_behavior="0" />
@manfield Could you revert your spaces changes in this file ?

2019-10-18 09:18 UTC, PierreRambaud commented on localization/au.xml
> +    <state name="Australian Capital Territory" iso_code="ACT" country="AU" zone="Oceania" tax_behavior="0" />
Yes, sadly, these files use tabs :/

2019-10-18 09:44 UTC, manfield commented on localization/au.xml
> +    <state name="Australian Capital Territory" iso_code="ACT" country="AU" zone="Oceania" tax_behavior="0" />
Damn! yes sure. I'll do

2019-10-18 10:16 UTC, manfield commented on localization/au.xml
> +    <state name="Australian Capital Territory" iso_code="ACT" country="AU" zone="Oceania" tax_behavior="0" />
I checked all localization files and there's no coherence among them (even for the ones I did not touch)
Some are tab indented, some space indented.
I could fix all files to make them coherent.
Just tell me what should be the final indention paradigm (tab/space, how many spaces for the second option).

Thanks

2019-10-18 12:01 UTC, Progi1984 commented on localization/au.xml
> +    <state name="Australian Capital Territory" iso_code="ACT" country="AU" zone="Oceania" tax_behavior="0" />
@manfield It is in discussion #15977

2019-10-18 12:06 UTC, Progi1984 commented on localization/au.xml
> +    <state name="Australian Capital Territory" iso_code="ACT" country="AU" zone="Oceania" tax_behavior="0" />
@manfield It's not the purpose of this PR. Could you revert your spaces changes in this file ? And after decision, if you want to normalize XML files, you could open a specific PR. Thanks :heart_eyes_cat:

2019-10-18 14:27 UTC, Progi1984 approved these changes

2019-10-18 15:20 UTC, Robin-Fischer-PS commented
Hello,

It's okay for me, QA approved :wink:

2019-10-18 15:26 UTC, merged

2019-10-18 15:26 UTC, PierreRambaud commented
Thanks @manfield and everyone