Fix tests customer
PrestaShop/PrestaShop pull request #13680
Opened 2019-05-06 10:20 UTC by boubkerbribri

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Fix tests customer, add close welcome module and copy test from high to full 
| Type?         | refacto
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | TEST_PATH=full/09_customer/* npm run specific-test -- --URL=SHOP_URL

2019-05-08 10:12 UTC, Quetzacoalt91 requested changes

2019-05-08 10:12 UTC, Quetzacoalt91 commented on tests/E2E/test/campaigns/full/09_customer/customer_settings/2_create_customer_in_FO.js
> +const {AccessPageFO} = require('../../../../selectors/FO/access_page');
Please avoid duplicating code.

2019-05-09 08:22 UTC, boubkerbribri commented on tests/E2E/test/campaigns/full/09_customer/customer_settings/2_create_customer_in_FO.js
> +const {AccessPageFO} = require('../../../../selectors/FO/access_page');
Ok, we will do it in another PR

2019-05-09 11:30 UTC, Quetzacoalt91 approved these changes

2019-05-09 11:30 UTC, merged