Update form.tpl
PrestaShop/PrestaShop pull request #13792
Opened 2019-05-15 08:58 UTC by BlackKerio

fix 'id' button submit if name 'id' is specified

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       |  1.7.6.x 
| Description?  | This is a bug into form.tpl. It doesn't appear into Prestashop, but into modules.<br>If a module add several switch button in a same form (On / Off), HTML id is broken because form.tpl add a number just after the id. <br>For example:<br>1.submitTruncateCatalog,<br>2.submitTruncateSales_1, (_1 was added)<br>3.module_form_submit_btn_2, (_2 was added)<br>4.submitTruncateClient_3, (_3 was added)<br>5.module_form_submit_btn_4, (_4 was added)<br>This is a problem because the module cannot know what will be the id with function like this:<br>$("#submitTruncateCatalog").click(function(){<br>if ($('#checkTruncateCatalog_on').attr('checked') != "checked")<br>{<br>   alert(' ... ');<br>   return false;<br>}<br>if (confirm(' ... '))<br>   return true;<br>return false;<br>});<br>My proposal allows module’s developer to keep control on his id. <br>
| Type?         | improvement 
| Category?     | BO 
| BC breaks?    | Does it break backward compatibility? yes
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | 
| How to test?  | With module Prestashop pscleaner

2019-05-15 12:56 UTC, mickaelandrieu approved these changes

2019-05-15 12:57 UTC, mickaelandrieu commented
Hello,

would you mind to provide a demo module so the QA team can validate your contribution?

Thanks

2019-05-16 10:08 UTC, BlackKerio commented
As I mentioned in the description how to test ... Example is the prestashop pscleaner https://github.com/PrestaShop/pscleaner module, which is unfortunately not in the Marketplace

2019-05-22 16:53 UTC, jolelievre requested changes
Hi @BlackKerio,

indeed this added counter can be a problem. However I don't think you can ignore it just because a specific id was set on this button, there is still the risk that two modules (or even one module itself) add the same id more than once. In which case the `_1` is important as duplicated ids are forbidden.

So to manage this correctly you should have a counter by id si you would have ids like:

1.submitTruncateCatalog,
2.submitTruncateSales
3.module_form_submit_btn
4.submitTruncateClient
5.module_form_submit_btn_1
6. submitTruncateCatalog_1

It might be complicated to manage with smarty but I think this would be the best behavior.

However, there is another problem with this fix, it could cause a BC break for modules which are expecting this suffix (even though the whole id's offsets can change if you install a new module). So I'm a bit worried about changing this feature..

2019-08-28 10:08 UTC, BlackKerio commented
But this error is already causing the module to malfunction, and that is just your Prestashop pscleaner module. The programmer defined the name id and the template with its own intelligence changed its names.
Sorry but I do not think that the programmer's error (using two identical IDs) to correct the template. I don't want to ignore the addition of the counter, I just modified it to work logically on an ID that can be duplicated. In the current situation is not at all possible to work with a specific id, because the name always changes ?!

2021-10-25 09:58 UTC, PierreRambaud commented
> But this error is already causing the module to malfunction, and that is just your Prestashop pscleaner module. The programmer defined the name id and the template with its own intelligence changed its names. Sorry but I do not think that the programmer's error (using two identical IDs) to correct the template. I don't want to ignore the addition of the counter, I just modified it to work logically on an ID that can be duplicated. In the current situation is not at all possible to work with a specific id, because the name always changes ?!

Hi @BlackKerio 
Are you able to provide us a little module in order to test it?

2021-11-26 20:42 UTC, matks commented
Hello, it seems this PR is now stale.

I close this PR, following our [review guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/) "Pull Requests may be closed after 30 days of inactivity".

If however you are still interested in it, please ping us 😉  we can reopen.

Thank you for your contribution.

2021-11-26 20:42 UTC, closed without merging