Update defines.inc.php
PrestaShop/PrestaShop pull request #13972
Opened 2019-05-25 07:12 UTC by FlorentinGarnier

'_PS_DISPLAY_COMPATIBILITY_WARNING_' set to false in default configuration but to true in debug mode to avoid abusive filling of message type "backward compatibility" in ps_log table in production

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop / 1.7.6.x / 1.6.1.x
| Description?  | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc.
| Type?         | bug fix / improvement / new feature / refacto / critical
| Category?     | FO / BO / CO / IN / WS / TE
| BC breaks?    | Does it break backward compatibility? yes/no
| Deprecations? | Does it deprecate an existing feature? yes/no
| Fixed ticket? | (optional) If this PR fixes an [Issue](https://github.com/PrestaShop/PrestaShop/issues), please write "Fixes #[issue number]" here.
| How to test?  | Please indicate how to best verify that this PR is correct.

2019-05-25 10:07 UTC, PierreRambaud requested changes
I'm not in favor of merging this PR.
We must display by default all warning about compatibility.
If you don't want to show them, you can disable it just after an installation :wink:

2019-05-25 10:29 UTC, FlorentinGarnier commented
I have proposed this PR because this message concern modules developer and not shop administrator IMHO and have performance issues. 

> Le 25 mai 2019 à 12:08, GoT <notifications@github.com> a écrit :
> 
> @PierreRambaud requested changes on this pull request.
> 
> I'm not in favor of merging this PR.
> We must display by default all warning about compatibility.
> If you don't want to show them, you can disable it just after an installation 😉
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-05-25 11:10 UTC, PierreRambaud commented
Modules developpers should update the code to be compliant with latest version as much as possible.

2019-05-25 17:00 UTC, Matt75 commented
Could this be a enabled only on Debug Mode ?
I think most of developers work with Debug Mode enabled 🤔

2019-05-25 17:22 UTC, PierreRambaud commented
As these variables can be change with configuration, if you're running in production mode, you're able to change the configuration value 🤔

2019-05-27 09:13 UTC, Matt75 commented
Yes but who is aware about that ?

Personally I don't know existence of this functionality...

Is it documented somewhere ?

I have this activated on production since years with 1.7, I disable that when I read this issue... (Now its enabled only in Debug Mode in my case)

If we don't change code, we have to improve docs instead 👍

2019-05-27 09:15 UTC, FlorentinGarnier commented
I have tested to define this const only in debug mode it seems to have no side effects

2019-05-27 09:21 UTC, Matt75 commented on config/defines.inc.php
> -    define('_PS_DISPLAY_COMPATIBILITY_WARNING_', false);
Maybe this line must be stay here, what's append if this constant is undefined ?

2019-05-27 09:21 UTC, PierreRambaud commented
his kind of warning is really important in production (it's the sysadmin that speaks). 
What happened if you disable this configuration by default, and if you install a new module using  deprecated functions, you'll not be noticed.
After few months, you upgrade to the latest prestashop version, functions are now removed, and you crash your shop without knowing what happened.

I maintain that it must be activated by default, it's not related to the debug mode.

But adding a button in the BO like the debug mode is a good idea.

2019-05-27 09:22 UTC, Matt75 commented
Argument is good, so we should improve docs instead of change code 👍

2019-06-05 08:23 UTC, Quetzacoalt91 commented
Following the discussion it seems this pull-request won't be accepted as-is, so I'm closing it.

Anyone is welcomed to open a new one on the [documentation repository](https://github.com/PrestaShop/docs).

2019-06-05 08:23 UTC, closed without merging