php unit no expectation annotation
PrestaShop/PrestaShop pull request #14231
Opened 2019-06-16 22:40 UTC by MathiasReker

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  /
| Type?         | improvement
| Category?     | TE
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | /
| How to test?  | /

2019-06-17 07:13 UTC, PierreRambaud commented on tests-legacy/Unit/Core/Localization/CLDR/CurrencyTest.php
> +        $this->setExpectedException(\PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException::class);
Use namespace everywhere please :)

2019-06-21 11:33 UTC, MathiasReker commented on tests-legacy/Unit/Core/Localization/CLDR/CurrencyTest.php
> +        $this->setExpectedException(\PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException::class);
Fixed

2019-07-12 14:38 UTC, PierreRambaud commented on tests-legacy/Unit/Core/Localization/CLDR/CurrencyTest.php
>      /**
Can you remove the comment when not needed?

2019-07-12 14:39 UTC, PierreRambaud commented on tests-legacy/Unit/Core/Localization/CLDR/LocaleTest.php
>       *
Remove extra line here please

2019-07-12 14:39 UTC, PierreRambaud commented on tests-legacy/Unit/Core/Localization/CLDR/LocaleTest.php
>       *
Remove extra line here please

2019-07-12 14:39 UTC, PierreRambaud commented on tests-legacy/Unit/Core/Localization/CLDR/LocaleTest.php
>       *
Remove extra line here please

2019-07-12 14:39 UTC, PierreRambaud commented on tests-legacy/Unit/Core/Localization/CLDR/LocaleTest.php
>       *
Remove extra line here please

2019-07-12 14:39 UTC, PierreRambaud commented on tests-legacy/Unit/Core/Localization/Currency/CurrencyTest.php
>       *
Remove extra line here please

2019-07-12 14:39 UTC, PierreRambaud commented on tests-legacy/Unit/Core/Localization/Currency/CurrencyTest.php
>       *
Remove extra line here please

2019-07-12 14:39 UTC, PierreRambaud commented on tests-legacy/Unit/Core/Localization/Currency/RepositoryTest.php
>       *
Remove extra line here please

2019-07-12 14:39 UTC, PierreRambaud commented on tests-legacy/Unit/Core/Localization/Locale/LocaleTest.php
>       *
Remove extra line here please

2019-07-12 14:39 UTC, PierreRambaud commented on tests-legacy/Unit/Core/Localization/Locale/LocaleTest.php
>       *
Remove extra line here please

2019-07-12 14:40 UTC, PierreRambaud requested changes
See comments

2019-07-12 15:16 UTC, MathiasReker commented
Fixed.

2019-07-12 15:57 UTC, PierreRambaud approved these changes

2019-07-12 15:59 UTC, PierreRambaud commented on tests/Unit/Adapter/MailTemplate/MailTemplateTwigRendererTest.php
> +        $this->setExpectedException(\PrestaShop\PrestaShop\Core\Exception\FileNotFoundException::class);
use namespace please :)

2019-07-12 15:59 UTC, PierreRambaud commented on tests/Unit/Core/Data/AbstractTypedCollectionTest.php
> +        $this->setExpectedException(TypeException::class, 'Invalid element type Tests\\Unit\\Core\\Data\\InvalidCollectionTestElement, expected Tests\\Unit\\Core\\Data\\CollectionTestElement');
Not sure double backslaces are needed in this file.

2019-07-12 16:00 UTC, PierreRambaud requested changes
Forget little things :)

2019-07-12 16:40 UTC, MathiasReker commented
Fixed

2019-07-12 19:35 UTC, PierreRambaud commented
Test are broken: https://travis-ci.org/PrestaShop/PrestaShop/jobs/557935139#L827

2019-07-15 07:34 UTC, PierreRambaud approved these changes

2019-07-15 07:34 UTC, merged

2019-07-15 07:34 UTC, PierreRambaud commented
Tests are ok, Thanks @MathiasReker