[WIP] Migration of products list display only
PrestaShop/PrestaShop pull request #14267
Opened 2019-06-18 12:37 UTC by tomas862

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR migrates product list according to our standarts - in this part it only migrates the display related things and not a single action. To access it for now a temporary url is created **admin-dev/index.php/sell/catalog/products/v2/**
| Type?         | new feature
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/issues/10631
| How to test?  | I'll write different test cases and what to test since this page is not going to be migrated all within single PR as it might get too huge. There might be more so we should not miss any

2019-07-01 13:39 UTC, tomas862 commented
Hi @colinegin ! 

I have a few questions regarding product list migration:

1. In current list when bulk enabling, disabling, duplicating or removing the loading pop-up appears - do we need this in the new list as well? Other migrated lists don't have such functionality.
2. Does "Filter by categories" dropdown is required in new product list as well? If so, then it should look the same?
![Screenshot (4)](https://user-images.githubusercontent.com/17051250/60440983-b8822680-9c1e-11e9-91d0-71da044743ef.png)

2019-07-05 10:39 UTC, MatShir commented
Hi @tomas862,

> 1. In current list when bulk enabling, disabling, duplicating or removing the loading pop-up appears - do we need this in the new list as well? Other migrated lists don't have such functionality.

If we **can't guarantee** a massive operation like for more than 100 products without loading time, we should keep it. 

> 2. Does "Filter by categories" dropdown is required in new product list as well? If so, then it should look the same?



>    ![Screenshot (4)](https://user-images.githubusercontent.com/17051250/60440983-b8822680-9c1e-11e9-91d0-71da044743ef.png)

The category filter is a requirement for big shops. What do you think of the UX @TristanLDD ?

> 3. Is this huge icon is needed when there are no products?
> 
> ![Screenshot (5)](https://user-images.githubusercontent.com/17051250/60513834-d748f180-9ce0-11e9-94d0-06232750aa4c.png)

 @TristanLDD can we find some nice fresh design? I don't find any empty state for it.

> currently on new list the default visibility is
> 
> ![Screenshot (6)](https://user-images.githubusercontent.com/17051250/60513859-e62fa400-9ce0-11e9-996b-762661ea4f89.png)


> 4. Related with 2nd question - after we click filter categories the position column appears in product list but its totally different of the usual one we have already implemented - you need to click first, then re-order products and submit the result. Should we apply this or keep the one we already have for all migrated lists

+1 for the new drag and drop system, we should have the same behaviours as you said

> 
> it is right now:
> ![download](https://user-images.githubusercontent.com/17051250/60703087-8405b780-9f09-11e9-873c-485f4800bce8.png)
> 
> everywhere else on migrated lists:
> ![cropped](https://user-images.githubusercontent.com/17051250/60703272-0b532b00-9f0a-11e9-82e9-e916cde26222.png)

I flag the PR "Waiting for UX" to notice @TristanLDD for the UX recommendation :)

2019-07-08 12:31 UTC, colinegin commented
Hello @tomas862 ,

You will find the recommended empty state for the product listing here : [](https://invis.io/5FRLCBENAS4#/358670592_Catalog)
Let us know if there's any other element missing !

2019-08-20 15:19 UTC, matks commented
@tomas862 Is this PR still in WIP or can I review ? or maybe an early review is needed ?

2019-08-23 07:31 UTC, tomas862 commented
hi @matks - it could be wise to review it and merge it after QA approval - its not like 100 percent finished. Some parts are missing - I'll state them in "How to test" section so QA will be aware which parts will be included.

to fully finish it some side PR's ned to be resolved first:

* https://github.com/PrestaShop/PrestaShop/pull/14619
* https://github.com/PrestaShop/PrestaShop/pull/14528
* https://github.com/PrestaShop/PrestaShop/pull/14542 - this one will allow to handle bulk actions in asynch way . At the time of writing this message it still lacks some dialog loading pop-up functionality.

2019-08-26 10:37 UTC, LouiseBonnard commented
Hellooo! One small thing that could be nice, I don't know if this PR can handle this part: when you select a filter ('Stationery', for instance), a new column appears called 'Position' and it allows users to reorder their products. 'Reorder' in the sense of organizing them the way you want. Yet, the term is often misunderstood during translation and it is sometimes turned into 'Order again'. 

<img width="1525" alt="Capture d’écran 2019-08-26 à 12 25 40" src="https://user-images.githubusercontent.com/32565890/63684753-eb4f3200-c7fd-11e9-8c21-f93bba2c0396.png">

Could it be possible to change this wording and write it 'Rearrange' (which is, I think, more suitable to the notion of position) or 'Reorganize' instead of 'Reorder'? I hope it will allow a better understanding and a more accurate translation later.

cf. @marionf, @sarahdib

2020-01-24 08:41 UTC, tomas862 commented
> Hellooo! One small thing that could be nice, I don't know if this PR can handle this part: when you select a filter ('Stationery', for instance), a new column appears called 'Position' and it allows users to reorder their products. 'Reorder' in the sense of organizing them the way you want. Yet, the term is often misunderstood during translation and it is sometimes turned into 'Order again'.
> 
> <img alt="Capture d’écran 2019-08-26 à 12 25 40" width="1525" src="https://user-images.githubusercontent.com/32565890/63684753-eb4f3200-c7fd-11e9-8c21-f93bba2c0396.png">
> 
> Could it be possible to change this wording and write it 'Rearrange' (which is, I think, more suitable to the notion of position) or 'Reorganize' instead of 'Reorder'? I hope it will allow a better understanding and a more accurate translation later.
> 
> cf. @marionf, @sarahdib

yes , this feature will be needed for sure but at the moment I dont want to expand this PR any more since it is easier to review from the developers perspective. 

so this PR only migrates:

1. Products display
2. List filters
3. Empty state
4. Bulk actions

PR is ready for review! :tada:

2020-01-30 13:41 UTC, LouiseBonnard commented on src/Core/Grid/Definition/Factory/ProductGridDefinitionFactory.php
> +                            'placeholder' => $this->trans('Search ref.', [], 'Admin.Catalog.Help'),
```suggestion
                            'placeholder' => $this->trans('Search reference', [], 'Admin.Actions'),
```

2020-01-30 13:41 UTC, LouiseBonnard commented on src/Core/Grid/Definition/Factory/ProductGridDefinitionFactory.php
> +                            'placeholder' => $this->trans('Search category', [], 'Admin.Catalog.Help'),
```suggestion
                            'placeholder' => $this->trans('Search category', [], 'Admin.Actions'),
```

2020-01-30 13:41 UTC, LouiseBonnard commented on src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/EmptyState/product.html.twig
> +    {{ "Let's start building your catalog!"|trans({}, 'Admin.Catalog.Feature') }}
It is not the same wording in the Empty States document [here](https://docs.google.com/document/d/1e_yu6f3Eq1c430k-a2QA9WLZwbwRSPsIeM_jhp09Jdg/edit#heading=h.xsydpo7gxkar), but it suits me fine this way as well - just make sure you use the right quote marks. And also, I'd write _Let's build your catalog!_ instead.

2020-01-30 13:41 UTC, LouiseBonnard commented on src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/EmptyState/product.html.twig
> +    {{ 'Building your catalog is the key step; present your brand here and make visitors feel like shopping on your store. Our advice? Pay extra attention to your product photography, neat pictures c
```suggestion
    {{ 'Building your catalog is the key step; present your brand here and make visitors feel like shopping on your store. Our advice? Pay extra attention to your product's images, neat pictures could increase your conversion rate by 35%!'|trans({}, 'Admin.Catalog.Feature') }}
```

2020-01-30 13:41 UTC, LouiseBonnard commented on src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/EmptyState/product.html.twig
> +      {{ 'Learn how to manage your catalog'|trans({}, 'Admin.Catalog.Feature') }}
```suggestion
      {{ 'Learn how to manage your catalog'|trans({}, 'Admin.Actions') }}
```

2020-01-30 13:41 UTC, LouiseBonnard commented on src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/EmptyState/product.html.twig
> +      {{ 'Add your first product'|trans({}, 'Admin.Catalog.Feature') }}
```suggestion
      {{ 'Add your first product'|trans({}, 'Admin.Actions') }}
```

2020-01-30 13:41 UTC, LouiseBonnard commented on src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/EmptyState/product.html.twig
> +      {{ 'Import a list of products (filetypes: %fileTypes%).'|trans({'%fileTypes%' : fileTypes|join(', ')}, 'Admin.Catalog.Feature') }}
```suggestion
      {{ 'Import a list of products (filetypes: %fileTypes%).'|trans({'%fileTypes%' : fileTypes|join(', ')}, 'Admin.Actions') }}
```

2020-01-30 13:43 UTC, LouiseBonnard commented on src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/EmptyState/product.html.twig
> +    {{ 'Building your catalog is the key step; present your brand here and make visitors feel like shopping on your store. Our advice? Pay extra attention to your product photography, neat pictures c
In the end, it looks more consistent with the terminology of the page, see below:

<img width="920" alt="Capture d’écran 2020-01-30 à 14 41 55" src="https://user-images.githubusercontent.com/32565890/73454652-cb083e00-436e-11ea-9050-bf419980eb63.png">

2020-02-19 13:23 UTC, NeOMakinG requested changes
Some minor changes for the front-end part

2020-02-19 13:23 UTC, NeOMakinG commented on admin-dev/themes/new-theme/js/pages/product/index.js
> + * 2007-2019 PrestaShop and Contributors
Please update license header :)

2020-02-19 13:23 UTC, NeOMakinG commented on admin-dev/themes/new-theme/js/pages/product/index.js
> +  from '../../components/grid/extension/filters-submit-button-enabler-extension';
Isn't there a path from webpack ? I think so, should be something like 
```suggestion
  from '@components/grid/extension/filters-submit-button-enabler-extension';
```

2020-02-19 13:23 UTC, NeOMakinG commented on src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/EmptyState/product.html.twig
> + * 2007-2019 PrestaShop and Contributors
Update license header please :)

2020-02-19 13:23 UTC, NeOMakinG commented on src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Actions/Row/preview_product.html.twig
> + * @copyright 2007-2019 PrestaShop SA and Contributors
here too

2020-02-19 13:23 UTC, NeOMakinG commented on src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/EmptyState/product.html.twig
> + * @copyright 2007-2019 PrestaShop SA and Contributors
here too

2020-02-19 13:23 UTC, NeOMakinG commented on src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/EmptyState/product.html.twig
> +</div>
Is this fine ? Git doesn't understand the syntax at all 😮

2020-02-19 13:23 UTC, NeOMakinG commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/index.html.twig
> + * @copyright 2007-2019 PrestaShop SA and Contributors
License header, at the top too

2021-03-02 17:05 UTC, PierreRambaud commented
Hi @tomas862 ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2021-03-02 17:05 UTC, closed without merging