[WIP] Migration of Sell > Catalog > Attributes&Features > Features > Feature Values add/edit form
PrestaShop/PrestaShop pull request #14476
Opened 2019-07-04 07:04 UTC by rokaszygmantas

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Migrates the feature value add/edit form.
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/issues/10510
| How to test?  | Compare to legacy controller.

2019-09-09 14:26 UTC, matks commented
@rokaszygmantas is it ready for review or still in WIP ?

2019-09-09 15:13 UTC, rokaszygmantas commented
@matks still WIP

2019-11-08 10:43 UTC, rokaszygmantas commented
@matks no longer WIP :)

2019-12-11 10:31 UTC, jolelievre requested changes
Lots of comments but it's mainly about adding strong typing

2019-12-11 10:31 UTC, jolelievre commented on src/Core/Domain/Feature/FeatureValue/Command/AddFeatureValueCommand.php
> +     * @return array
Add comment here `Localized values indexed by language id` (or locale if it's indexed by locale)

2019-12-11 10:31 UTC, jolelievre commented on src/Core/Domain/Feature/FeatureValue/Command/EditFeatureValueCommand.php
> +     * @param array $localizedValues
Add comment here `Localized values indexed by language id` (or locale if it's indexed by locale)

2019-12-11 10:31 UTC, jolelievre commented on src/Core/Domain/Feature/FeatureValue/QueryResult/EditableFeatureValue.php
> +    public function getValue()
Add comment here `Localized values indexed by language id` (or locale if it's indexed by locale)
Also rename this getter to  `getLocalizedValues` which instantly gives an hint to what it contains

2019-12-11 10:31 UTC, jolelievre commented on src/Core/Domain/Language/FeatureValueId.php
> +    public function __construct($featureValueId)
Use strong typing `int` then you can remove the `is_int` test

2019-12-11 10:31 UTC, jolelievre commented on src/Adapter/Feature/FeatureValue/CommandHandler/AddFeatureValueHandler.php
> +    public function handle(AddFeatureValueCommand $command)
```suggestion
    public function handle(AddFeatureValueCommand $command) :FeatureId
```

2019-12-11 10:31 UTC, jolelievre commented on src/Adapter/Feature/FeatureValue/CommandHandler/AddFeatureValueHandler.php
> +    private function assertFeatureExists(FeatureId $featureId)
```suggestion
    private function assertFeatureExists(FeatureId $featureId) :void
```

2019-12-11 10:31 UTC, jolelievre commented on src/Adapter/Feature/FeatureValue/CommandHandler/EditFeatureValueHandler.php
> +    public function handle(EditFeatureValueCommand $command)
```suggestion
    public function handle(EditFeatureValueCommand $command) :void
```

2019-12-11 10:31 UTC, jolelievre commented on src/Adapter/Feature/FeatureValue/CommandHandler/EditFeatureValueHandler.php
> +    private function assertFeatureExists(FeatureId $featureId)
```suggestion
    private function assertFeatureExists(FeatureId $featureId) :void
```

2019-12-11 10:31 UTC, jolelievre commented on src/Adapter/Feature/FeatureValue/QueryHandler/GetFeatureValueForEditingHandler.php
> +    public function handle(GetFeatureValueForEditing $query)
```suggestion
    public function handle(GetFeatureValueForEditing $query) :EditableFeatureValue
```

2019-12-11 10:31 UTC, jolelievre commented on src/Core/Domain/Feature/Exception/FeatureNotFoundException.php
> +    public function getFeatureId()
```suggestion
    public function getFeatureId() :FeatureId
```

2019-12-11 10:31 UTC, jolelievre commented on src/Core/Domain/Feature/Exception/FeatureNotFoundException.php
> +    public function __construct(FeatureId $featureId, $message = '', $code = 0, $previous = null)
```suggestion
    public function __construct(FeatureId $featureId, string $message = '', int $code = 0, Exception $previous = null)
```

2019-12-11 10:31 UTC, jolelievre commented on src/Core/Domain/Feature/FeatureValue/Command/AddFeatureValueCommand.php
> +    public function __construct($featureId, array $localizedValues)
```suggestion
    public function __construct(FeatureId $featureId, array $localizedValues)
```

2019-12-11 10:31 UTC, jolelievre commented on src/Core/Domain/Feature/FeatureValue/Command/AddFeatureValueCommand.php
> +    public function getFeatureId()
```suggestion
    public function getFeatureId() :FeatureId
```

2019-12-11 10:31 UTC, jolelievre commented on src/Core/Domain/Feature/FeatureValue/Command/AddFeatureValueCommand.php
> +    public function getLocalizedValues()
```suggestion
    public function getLocalizedValues() :array
```

2019-12-11 10:31 UTC, jolelievre commented on src/Core/Domain/Feature/FeatureValue/Command/EditFeatureValueCommand.php
> +    public function __construct($featureValueId)
```suggestion
    public function __construct(int $featureValueId)
```

2019-12-11 10:31 UTC, jolelievre commented on src/Core/Domain/Feature/FeatureValue/Command/EditFeatureValueCommand.php
> +    public function getFeatureValueId()
```suggestion
    public function getFeatureValueId() :FeatureId
```

2019-12-11 10:31 UTC, jolelievre commented on src/Core/Domain/Feature/FeatureValue/Command/EditFeatureValueCommand.php
> +    public function getLocalizedValues()
```suggestion
    public function getLocalizedValues() :array
```

2019-12-11 10:31 UTC, jolelievre commented on src/Core/Domain/Feature/FeatureValue/Command/EditFeatureValueCommand.php
> +    public function setLocalizedValues(array $localizedValues)
```suggestion
    public function setLocalizedValues(array $localizedValues) :self
```

2019-12-11 10:31 UTC, jolelievre commented on src/Core/Domain/Feature/FeatureValue/Command/EditFeatureValueCommand.php
> +    public function getFeatureId()
```suggestion
    public function getFeatureId() :FeatureId
```

2019-12-11 10:31 UTC, jolelievre commented on src/Core/Domain/Feature/FeatureValue/Command/EditFeatureValueCommand.php
> +    public function setFeatureId($featureId)
```suggestion
    public function setFeatureId(int $featureId)
```

2019-12-11 10:31 UTC, jolelievre commented on src/Core/Domain/Feature/FeatureValue/CommandHandler/AddFeatureValueHandlerInterface.php
> +    public function handle(AddFeatureValueCommand $command);
```suggestion
    public function handle(AddFeatureValueCommand $command) :FeatureValueId;
```

2019-12-11 10:31 UTC, jolelievre commented on src/Core/Domain/Feature/FeatureValue/CommandHandler/EditFeatureValueHandlerInterface.php
> +    public function handle(EditFeatureValueCommand $command);
```suggestion
    public function handle(EditFeatureValueCommand $command) :void;
```

2019-12-11 10:31 UTC, jolelievre commented on src/Core/Domain/Feature/FeatureValue/Exception/CannotAddFeatureValueException.php
> +    public function getFeatureId()
```suggestion
    public function getFeatureId() :FeatureId
```

2019-12-11 10:31 UTC, jolelievre commented on src/Core/Domain/Feature/FeatureValue/Exception/CannotAddFeatureValueException.php
> +    public function __construct(FeatureId $featureId, $message = '', $code = 0, $previous = null)
```suggestion
    public function __construct(FeatureId $featureId, string $message = '', int $code = 0, Exception $previous = null)
```

2019-12-11 10:31 UTC, jolelievre commented on src/Core/Domain/Feature/FeatureValue/Query/GetFeatureValueForEditing.php
> +    public function __construct($featureValueId)
```suggestion
    public function __construct(FeatureValueId  $featureValueId)
```

2019-12-11 10:31 UTC, jolelievre commented on src/Core/Domain/Feature/FeatureValue/Query/GetFeatureValueForEditing.php
> +    public function getFeatureValueId()
```suggestion
    public function getFeatureValueId(): FeatureValueId
```

2019-12-11 10:31 UTC, jolelievre commented on src/Core/Domain/Feature/FeatureValue/QueryHandler/GetFeatureValueForEditingHandlerInterface.php
> +    public function handle(GetFeatureValueForEditing $query);
```suggestion
    public function handle(GetFeatureValueForEditing $query) :EditableFeatureValue;
```

2019-12-11 10:31 UTC, jolelievre commented on src/Core/Domain/Feature/FeatureValue/QueryResult/EditableFeatureValue.php
> +    public function getFeatureValueId()
```suggestion
    public function getFeatureValueId() :FeatureValueId
```

2019-12-11 10:31 UTC, jolelievre commented on src/Core/Domain/Feature/FeatureValue/QueryResult/EditableFeatureValue.php
> +    public function getFeatureId()
```suggestion
    public function getFeatureId() :FeatureId
```

2019-12-11 10:31 UTC, jolelievre commented on src/Core/Domain/Feature/FeatureValue/QueryResult/EditableFeatureValue.php
> +    public function getValue()
```suggestion
    public function getValue() :array
```

2019-12-11 10:31 UTC, jolelievre commented on src/Core/Domain/Language/FeatureValueId.php
> +    public function getValue()
```suggestion
    public function getValue() :int
```

2019-12-11 10:31 UTC, jolelievre commented on src/Core/Form/ChoiceProvider/FeatureChoiceProvider.php
> +    public function getChoices()
```suggestion
    public function getChoices() :array
```

2019-12-11 10:31 UTC, jolelievre commented on src/PrestaShopBundle/Controller/Admin/Sell/Catalog/FeatureValueController.php
> +    public function createAction(Request $request, $featureId)
```suggestion
    public function createAction(Request $request, int $featureId)
```

2019-12-11 10:31 UTC, jolelievre commented on src/PrestaShopBundle/Controller/Admin/Sell/Catalog/FeatureValueController.php
> +    public function editAction(Request $request, $featureId, $featureValueId)
```suggestion
    public function editAction(Request $request, int $featureId, int $featureValueId)
```

2019-12-11 10:31 UTC, jolelievre commented on src/PrestaShopBundle/Controller/Admin/Sell/Catalog/FeatureValueController.php
> +            $handlerResult = $formHandler->handle($form);
Can you add a PHPDoc for `$handlerResult` type please

2019-12-11 10:31 UTC, jolelievre commented on src/PrestaShopBundle/Controller/Admin/Sell/Catalog/FeatureValueController.php
> +            $editableFeatureValue = $this->getQueryBus()->handle(
Can you add a PHPDoc for `$editableFeatureValue` please

2019-12-11 10:31 UTC, jolelievre commented on src/PrestaShopBundle/Controller/Admin/Sell/Catalog/FeatureValueController.php
> +            $handlerResult = $formHandler->handleFor($featureValueId, $form);
Add PHPDoc here as well please

2019-12-11 10:31 UTC, jolelievre commented on src/PrestaShopBundle/Controller/Admin/Sell/Catalog/FeatureValueController.php
> +    private function renderEditForm(array $parameters = [])
```suggestion
    private function renderEditForm(array $parameters = []) :Response
```

2019-12-11 10:31 UTC, jolelievre commented on src/PrestaShopBundle/Controller/Admin/Sell/Catalog/FeatureValueController.php
> +    private function getErrorMessages()
```suggestion
    private function getErrorMessages() :array
```

2019-12-11 10:31 UTC, jolelievre commented on src/PrestaShopBundle/Controller/Admin/Sell/Catalog/FeatureValueController.php
> +    private function isFeatureEnabled()
```suggestion
    private function isFeatureEnabled() :bool
```

2019-12-11 10:31 UTC, jolelievre commented on src/PrestaShopBundle/Form/Admin/Sell/Catalog/FeatureValueType.php
> +            'type' => TextType::class,
Fix the indentation here please

2019-12-11 10:31 UTC, jolelievre commented on src/PrestaShopBundle/Form/Admin/Sell/Catalog/FeatureValueType.php
> +                        'type' => 'generic_name',
Use `TypedRegex::TYPE_GENERIC_NAME`

2019-12-11 10:31 UTC, jolelievre commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Features/FeatureValues/create.html.twig
> +{#    @todo when features form is merged #}
Can you indicate which PR it is please

2019-12-11 10:31 UTC, jolelievre commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Features/FeatureValues/edit.html.twig
> +    {% include '@PrestaShop/Admin/Sell/Catalog/Features/Blocks/disabled_feature_warning.html.twig' %}
Isn't it related to the Feature PR as well?

2019-12-11 10:31 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Scenario/Feature/feature_management.feature
> +    And feature value "feature_value_1" value should be "My feature value"
Could you add a test about feature value edition please

2019-12-11 10:31 UTC, jolelievre requested changes
Lots of comments but it's mainly about adding strong typing

2019-12-12 16:38 UTC, LouiseBonnard commented on src/PrestaShopBundle/Controller/Admin/Sell/Catalog/FeatureValueController.php
> +        $invalidFeatureMessage = $this->trans('Invalid feature selected', 'Admin.Catalog.Feature');
How can the feature be invalid? Isn't it selected with a dropdown list?

2019-12-12 16:38 UTC, LouiseBonnard commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Features/FeatureValues/create.html.twig
> +{% set layoutTitle = 'Add a new feature value'|trans({}, 'Admin.Catalog.Feature') %}
<img width="144" alt="Capture d’écran 2019-12-12 à 17 35 43" src="https://user-images.githubusercontent.com/32565890/70730758-dc858000-1d05-11ea-896e-7d9d4a939bd2.png">

2019-12-12 16:38 UTC, LouiseBonnard commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Features/FeatureValues/create.html.twig
> +{% set layoutTitle = 'Add a new feature value'|trans({}, 'Admin.Catalog.Feature') %}
Are we talking about this CTA? If yes, the article should be removed to stay consistent with the other pages. ;-)

2020-01-23 14:42 UTC, matks commented
This PR needs a rebase (for `develop`) and needs to handle @jolelievre feedbacks 😊

2020-08-03 07:26 UTC, LouiseBonnard commented
Hi there, this PR is on hold since last January so I've added _[On pause]_ in its title and the _WIP_ label. Feel free to remove it when you get back to it. :-)

2021-08-04 07:46 UTC, matks commented
@rokaszygmantas I close this PR as it currently appears in our backlog of PRs and until I (or someone else) find some time to finish it, it won't move 😞  .

But when someone can finally resume work on this topic, she/he will be able to use this PR as a base.

2021-08-04 07:46 UTC, closed without merging