Fix unclosed div element
PrestaShop/PrestaShop pull request #14738
Opened 2019-07-18 12:39 UTC by sarjon

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fixes unclosed <div> element in Themes & Logos template.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | Not needed.

2019-07-18 12:53 UTC, PierreRambaud approved these changes

2019-07-18 12:54 UTC, PierreRambaud commented
Can you target 1.7.6.x please.

2019-07-18 12:54 UTC, PierreRambaud requested changes
My bad, target 1.7.6.x please.

2019-07-22 11:35 UTC, sarjon commented
New PR https://github.com/PrestaShop/PrestaShop/pull/14805

2019-07-22 11:35 UTC, closed without merging