Fixed {firstname} typo in order customer comment mail
PrestaShop/PrestaShop pull request #14907
Opened 2019-07-30 05:00 UTC by dheerajwebkul

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc.
| Type?         | bug fix
| Category?     | FO 
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/issues/14906
| How to test?  | Just got to FO order details page and send a message to admin for the order. Admin can see this error in the mail.

2019-07-30 07:13 UTC, Progi1984 approved these changes

2019-07-30 07:15 UTC, PierreRambaud approved these changes

2019-07-31 16:21 UTC, marionf commented
Hello @dheerajwebkul 
As the issue is a regression of 1.7.6.0 could you please rebase your PR on 1.7.6.x branch ?

2019-07-31 17:33 UTC, jolelievre approved these changes
Thank you @dheerajwebkul 
Nice catch!

2019-07-31 17:37 UTC, jolelievre requested changes
As @marionf pointed out, this change will be integrated in the coming 1.7.6.1.
So could you rebase and target 1.7.6.x branch. If you are not used to rebase you may create a new branch and PR with 1.7.6.X branch as your starting point.

2019-08-01 04:20 UTC, dheerajwebkul commented
Hello @marionf ,

I have created a new PR for 1.7.6.x.

https://github.com/PrestaShop/PrestaShop/pull/14945

You can review and close this PR

Thanks,

2019-08-01 07:05 UTC, closed without merging