PrestaShop#14958 : add duplicate prices
PrestaShop/PrestaShop pull request #14959
Opened 2019-08-01 15:38 UTC by 202-ecommerce

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | add the duplication of a product price in multishop when the product has a different price in each shops
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #14958 .
| How to test?  | Steps to reproduce the behavior:

Set a multishop with 2 shops (or more). For instance:
Create a product in context all shop
On each shop set a different price for the product
Finally on products board, select the previous product and click on duplicate product on all shop context.

2019-08-01 15:46 UTC, matthieu-rolland requested changes
Thank you for this PR, I made a minor comment, could you check it out?

2019-08-01 15:46 UTC, matthieu-rolland commented on classes/Product.php
> +    public static function duplicatePrices($id_product_old, $id_product_new)
Hello, thanx a lot for your contribution !

Could you please add a proper phpdoc including a short description of the method ?

2019-08-05 11:31 UTC, 202-ecommerce commented
Hi @matthieu-rolland ,
I just added the PHPDoc as you asked and validated the PrettyCI

2019-08-06 13:27 UTC, matthieu-rolland submitted a review, later dismissed

2019-08-06 13:31 UTC, matthieu-rolland commented
thanx @202-ecommerce ! your fix will be tested by the QA before we can merge it.

2019-08-06 16:01 UTC, khouloudbelguith commented
Hi @202-ecommerce,

The `Price per unit (tax excl.) ` is not duplicated, if we duplicate a product, it remains to `0`.
![image](https://user-images.githubusercontent.com/16067358/62555933-c5241b00-b86b-11e9-9421-a526e88f09b9.png)
Thanks!

2019-08-08 11:41 UTC, 202-ecommerce commented
Hi @khouloudbelguith ,
Just made the fix for the Price per unit

2019-08-08 12:11 UTC, khouloudbelguith commented
@202-ecommerce, thanks!
Waiting for a review.

2019-08-21 08:23 UTC, matthieu-rolland approved these changes
LGTM

2019-08-26 08:45 UTC, merged