Fix missing invoice logo
PrestaShop/PrestaShop pull request #15109
Opened 2019-08-14 09:44 UTC by MathiasReker

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.1
| Description?  | Logo on invoice was missing if SSL was activated in BO. Use URI instead of URL fix the issue.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/issues/15088
| How to test?  | Enable SSL in BO. Then generate an invoice. Without this PR the logo is missing. With this PR the logo is showed.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/15089)

2019-08-14 09:47 UTC, MathiasReker commented
@matthieu-rolland I am not familiar using the CDN server, will you have a look on this way to fix it?

2019-08-19 08:28 UTC, PierreRambaud commented on classes/pdf/HTMLTemplate.php
> +            'logo_path' => $logo_path,
Because of `img_ps_dir` you only need to do this:
```suggestion
            'logo_path' => _PS_IMG_ . $logo,
```

2019-08-19 08:29 UTC, PierreRambaud requested changes
Follow my comment.

2019-08-19 08:29 UTC, PierreRambaud commented
Nice catch @MathiasReker :wink:

2019-08-19 08:34 UTC, MathiasReker commented
> 
> 
> Nice catch @MathiasReker 😉

I though so, but @matthieu-rolland said that it does not work with CDN

2019-08-19 09:26 UTC, matthieu-rolland commented
yes @MathiasReker , I was afraid removing the getMediaServer server method would keep users from using their cdn for this logo, it was safer to ask a review from someone who knew better about this. ;)

2019-08-19 09:43 UTC, PierreRambaud commented
I will check another time and come back to you. I need to test one more thing :)

2019-08-19 10:01 UTC, PierreRambaud commented
After checking, I confirm there is no problem.
You're probably using a selfsigned certificate, and the TCPDF can't retrieve your image over the network because of verify_peer parameter.
Without ssl the logo_path is `http://ps-develop.localhost/img/logo.png`, and with `https://ps-develop.localhost/img/logo.png`, without the certificate verification, I'm not able to see the image. With, everything is ok.

2019-08-19 10:20 UTC, PierreRambaud commented
If you want to try with https, you can change the `logo_path` with 
`https://www.prestashop.com/sites/all/themes/prestashop/images/logo_ps_second.svg` for example, you will see everything is ok. I also tried with a proper https configuration.

2019-08-19 10:37 UTC, MathiasReker commented
So this PR can be closed, since there is not problem in production?

2019-08-19 10:49 UTC, PierreRambaud commented
Closed because of self signed certificate (Not working with TCPDF).

2019-08-19 10:49 UTC, closed without merging