Updated prestashop/ps_emailsubscription to 2.5.0
PrestaShop/PrestaShop pull request #15354
Opened 2019-09-02 09:56 UTC by Progi1984

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Updated prestashop/ps_emailsubscription to 2.5.0
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #9907 
| How to test?  |

2019-09-02 11:44 UTC, matthieu-rolland submitted a review, later dismissed
Thanx @Progi1984 !

2019-09-02 12:27 UTC, PierreRambaud requested changes
composer.json needs to be updated too.

2019-09-02 13:01 UTC, Progi1984 commented
@PierreRambaud Why ? Composer.json is correct :
```
        "prestashop/ps_contactinfo": "^3",
        "prestashop/ps_emailsubscription": "^2",
        "prestashop/ps_facetedsearch": "^3",
```

2019-09-02 13:28 UTC, PierreRambaud commented
Not really, PrestaShop not working if we use the current version of our modules :)

2019-09-02 14:53 UTC, Progi1984 commented
@PierreRambaud It's why we update the composer.lock. Composer install will base on this file.

2019-09-02 15:03 UTC, PierreRambaud commented
@Progi1984 But the first thing you check when you want to know which version you're using is the composer.json.
If the app isn't working anymore with an old version of a module, we must also update the composer.json. Otherwise it's like having ">0" everywhere and only trust the composer.lock.

2019-09-04 12:47 UTC, Progi1984 commented
@PierreRambaud @matthieu-rolland It should be better :)

2019-09-04 12:49 UTC, PierreRambaud commented on composer.json
> +        "prestashop/ps_facetedsearch": "^3.2",
```suggestion
        "prestashop/ps_facetedsearch": "^3.2.1",
```
The 3.2.0 introduces many bugs :)

2019-09-04 12:53 UTC, Progi1984 commented on composer.json
> +        "prestashop/ps_facetedsearch": "^3.2",
:ok_hand:

2019-09-04 12:53 UTC, Progi1984 commented
@PierreRambaud Corrected

2019-09-04 14:53 UTC, PierreRambaud approved these changes

2019-09-04 18:17 UTC, pierreloicq commented
Hi,
I am unsure how it relates to this PR, but at the moment, the upgrade proposed for ps_emailsubscription on 1.7.6.1 lead to something buggy on classic theme: e-mail is not saved in the db, and there is no "well received" message.
Thanks

2019-09-05 07:30 UTC, Progi1984 commented
@pierreloicq Which version of ps_emailsubscription do you have ?

2019-09-05 08:27 UTC, pierreloicq commented
2.3 provided with PS 1.7.61. was working fine, then I upgraded to 2.5 which is buggy

2019-09-05 09:46 UTC, sarahdib commented
Hello @pierreloicq 

Thank you for your feed back. 

I just test (twice) the module email_subscription and it's working for me the email is saved and I receive the email for confirmation.

In the module configuration did you enable the option "send a confirmation email" ?

Have a nice day :)

2019-09-05 10:27 UTC, pierreloicq commented
@sarahdib No I did not enable it(I was talking about the message in green that appears below the e-mail box after you submit). But if I activated it, I receive nothing. 
Actually I have an error popping up when I go on the module config page : 
```
Notice on line 74 in file C:\\Program Files (x86)\\Ampps\\www\\presta17\\src\\Adapter\\Routing\\LegacyHelperLinkBuilder.php
[8] Undefined index: id_merged
```

2019-09-05 12:14 UTC, Progi1984 commented
@pierreloicq Thanks for your feedback. Could you create a specific issue for this ? Thanks.

2019-09-05 14:12 UTC, pierreloicq commented
Here it is
https://github.com/PrestaShop/PrestaShop/issues/15425

2019-09-05 16:12 UTC, matks commented
Thank you @Progi1984

2019-09-05 16:12 UTC, merged