Refuse empty customer first and last names - thanks @Azouz-Jribi
PrestaShop/PrestaShop pull request #15616
Opened 2019-09-19 14:10 UTC by matks

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Refuse empty customer first and last names. Port of https://github.com/PrestaShop/PrestaShop/pull/8430
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-7423comment. 
| How to test?  | Try to register a new customer on the FO with first name " " and last name " " (empty spaces).

2019-09-19 14:12 UTC, matthieu-rolland submitted a review, later dismissed
LGTM

2019-09-19 14:44 UTC, rdy4ever commented
I've made a PR to trim unnecessary white spaces from form fileds: #15537
This could also avoid this situation client-side as it would just delete the single withe spaces on blur event.

2019-09-20 13:09 UTC, PierreRambaud commented on src/Core/ConstraintValidator/CustomerNameValidator.php
> +        $cleanedName = trim($name);
Please update `PATTERN_NAME` instead with:
```
    const PATTERN_NAME = '/^(?!\s*$)(?:[^0-9!<>,;?=+()\/\\\\@#"°*`{}_^$%:¤\[\]|\.。]|[。\.](?:\s|$))*$/u';
```

2019-09-20 13:10 UTC, PierreRambaud requested changes
PATTERN_NAME must be updated

2019-09-20 13:10 UTC, matks commented
> PATTERN_NAME must be updated

<img src="http://golem13.fr/wp-content/uploads/2018/12/pereAnakin.jpg">

2019-09-30 16:00 UTC, PierreRambaud commented on src/Core/ConstraintValidator/CustomerNameValidator.php
> +    const PATTERN_NAME = '/^(?!\s*$)(?:[^0-9!<>,;?=+()\/\\\\@#"°*`{}_^$%:¤\[\]|\.。]|[。\.](?:\s|$))*$/u';
:heart:

2019-09-30 16:00 UTC, PierreRambaud approved these changes

2019-10-01 14:12 UTC, matks commented
Thanks for QA and review

2019-10-01 14:12 UTC, merged