Update Egyptian tax rates
PrestaShop/PrestaShop pull request #16182
Opened 2019-10-29 15:35 UTC by LouiseBonnard

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Update localization packs data, update tax rates - following the Avalara information [here](https://www.avalara.com/vatlive/en/vat-rates/international-vat-and-gst-rates.html)
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | It is part of this [EPIC](https://github.com/PrestaShop/PrestaShop/issues/15829).

2019-10-29 15:38 UTC, Progi1984 submitted a review, later dismissed

2019-10-30 10:40 UTC, sarahdib commented
@LouiseBonnard 
Same problem than Ecuadorian 
<img width="1071" alt="Capture d’écran 2019-10-30 à 11 08 40" src="https://user-images.githubusercontent.com/3034677/67851119-0134e800-fb0a-11e9-916f-72f8f887d415.png">
<img width="1231" alt="Capture d’écran 2019-10-30 à 11 39 13" src="https://user-images.githubusercontent.com/3034677/67851120-0134e800-fb0a-11e9-9e23-4efef394eee7.png">

2019-10-30 11:07 UTC, eternoendless requested changes

2019-10-30 11:07 UTC, eternoendless commented on localization/eg.xml
> +
Missing closing tag for the tax rules group:

```suggestion
    </taxRulesGroup>
```

2019-10-30 11:10 UTC, eternoendless approved these changes
Looks good now

2019-10-30 12:53 UTC, merged