Update Ecuadorian tax rates
PrestaShop/PrestaShop pull request #16181
Opened 2019-10-29 15:30 UTC by LouiseBonnard

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Update localization packs data, update tax rates - following the Avalara information [here](https://www.avalara.com/vatlive/en/vat-rates/international-vat-and-gst-rates.html)
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | It is part of this [EPIC](https://github.com/PrestaShop/PrestaShop/issues/15829).

2019-10-29 15:33 UTC, matthieu-rolland submitted a review, later dismissed
lgtm

2019-10-30 10:25 UTC, sarahdib commented
@LouiseBonnard there is a problem when we try to upgrade the pack Ecuadorian and when we install PS with Ecuadorian country there is an error in the BO

<img width="1071" alt="Capture d’écran 2019-10-30 à 11 08 40" src="https://user-images.githubusercontent.com/3034677/67850001-d2b60d80-fb07-11e9-8e76-7b253c4b8bfe.png">
<img width="1254" alt="Capture d’écran 2019-10-30 à 11 18 52" src="https://user-images.githubusercontent.com/3034677/67850002-d2b60d80-fb07-11e9-86fe-fc3720b0b7ec.png">

2019-10-30 11:08 UTC, eternoendless requested changes

2019-10-30 11:08 UTC, eternoendless commented on localization/ec.xml
> +
Missing closing tag:

```suggestion
		</taxRulesGroup>
```

2019-10-30 11:10 UTC, eternoendless approved these changes
Looks good now

2019-10-30 15:39 UTC, merged