Return of hook profiling
PrestaShop/PrestaShop pull request #16231
Opened 2019-10-31 14:19 UTC by StanislovasRamanauskas

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop / 1.7.6.x / 1.6.1.x
| Description?  | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc.
| Type?         | bug fix / improvement / new feature / refacto / critical
| Category?     | FO / BO / CO / IN / WS / TE
| BC breaks?    | Does it break backward compatibility? yes/no
| Deprecations? | Does it deprecate an existing feature? yes/no
| Fixed ticket? | [Issue](https://github.com/PrestaShop/PrestaShop/issues), please write "Fixes #[issue number]" here.
| How to test?  | Please indicate how to best verify that this PR is correct.

2019-10-31 23:07 UTC, mickaelandrieu commented
Hi @StanislovasRamanauskas, why not use the Hook profiler provided in the current debug toolbar ?

2019-11-01 00:43 UTC, kpodemski commented
> Hi @StanislovasRamanauskas, why not use the Hook profiler provided in the current debug toolbar ?

because you don't have symfony profiler on front-office @mickaelandrieu :)

2019-11-01 17:17 UTC, mickaelandrieu commented
> because you don't have symfony profiler on front-office @mickaelandrieu :)

I always forgot that !

2019-11-03 09:40 UTC, sarjon commented on install-dev/upgrade/sql/1.7.0.0.sql
> -DROP TABLE IF EXISTS `PREFIX_modules_perfs`;
Table was dropped in 1.7.0.0, you don't need to remove it from here, but create it once again in `1.7.7.0.sql` file.

2019-11-03 09:42 UTC, StanislovasRamanauskas commented
> Hi @StanislovasRamanauskas, why not use the Hook profiler provided in the current debug toolbar ?
@mickaelandrieu hook debugging is important feature for improving module speed. Also, not all hook profiling functionality was removed from 1.7.0.0 version. Till now PS had empty hook list in profiling and that is confusing. 
![Screenshot from 2019-11-03 10-35-10](https://user-images.githubusercontent.com/38095299/68082529-909e0c00-fe26-11e9-805d-203a4c57040f.jpg)

2020-01-29 14:30 UTC, kpodemski commented
@PrestaShop/prestashop-core-developers LGTM!

2020-01-30 11:19 UTC, eternoendless requested changes
I think this could be useful for some uses, but I think the implementation needs to be improved. For example, I'd rather see the whole profiling logic in a class of its own:

```php
function doSomething(...$params) {
  if ($this->profiler->shouldProfile()) {
    return $this->profiler->interceptDoSomething(...$params); // does the thing with profiling
  }

  return $this->doTheThing(...$params); // does the thing without profiling
}
```

or even better, use strategy pattern:

```php
public function doSomething(...$params)
{
  $this->thingExecutor->doTheThing(...$params);
}
```

In the latter case you just need to inject a different `thingExecutor` depending if you want to profile the thing or not.

Also, does it worth it adding this when you can use Blackfire.io?

2020-01-30 11:19 UTC, eternoendless commented on classes/Hook.php
> +                Module::$_log_modules_perfs_session = mt_rand();
Looking at the code, it looks that the session ID is random and lasts for exactly one run. In that case, why bother to save results on the database?

2020-04-09 19:35 UTC, mickaelandrieu commented
Hi @StanislovasRamanauskas,

would you mind to contribute this to the [Developer Tools](https://github.com/friends-of-presta/developer_tools) module ?

I will take this code anyway, but I prefer to let you the attribution of this code 👍, the way I see it this won't be shipped in 1.7.7 so we won't have this in the Core before 2021...

2020-08-24 08:33 UTC, PierreRambaud commented
Closed in favor of #20673
Thanks for your work, it helps us a lot :wink:

2020-08-24 08:33 UTC, closed without merging