Fix category checkbox redirect (Backport #16159)
PrestaShop/PrestaShop pull request #16265
Opened 2019-11-04 16:24 UTC by atomiix

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Prevent click action on identifier type table cells that have a checkbox 
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #16119
| How to test?  | see #16119

2019-11-04 16:26 UTC, matks submitted a review, later dismissed

2019-11-04 16:27 UTC, matthieu-rolland submitted a review, later dismissed
looks fine to me

2019-11-04 16:38 UTC, PierreRambaud commented on admin-dev/themes/new-theme/js/components/grid/extension/link-row-action-extension.js
> +        const clickableCells = $('td.data-type, td.identifier-type:not(:has(.md-checkbox)), td.badge-type, td.position-type', $parentRow)
What about radio? text? etc :thinking: Are we sure, `.md-checkbox` is enough? what if a thrid part module use a custom css class?

Could we test something more generic?
```suggestion
        const clickableCells = $('td.data-type, td.identifier-type:not(:has(input)), td.badge-type, td.position-type', $parentRow)
```

2019-11-05 08:51 UTC, PierreRambaud requested changes
Forget to add this comment :roll_eyes:

2019-11-05 09:51 UTC, PierreRambaud approved these changes

2019-11-05 17:25 UTC, matks commented
Thank you @atomiix

2019-11-05 17:38 UTC, eternoendless commented
[Tests are green](https://travis-ci.com/PrestaShop/PrestaShop/builds/135001226) but not reported to the PR, merging.

2019-11-05 17:39 UTC, merged