PassVsprintfValidator: Add separate regex for arguments only
PrestaShop/PrestaShop pull request #16359
Opened 2019-11-11 17:54 UTC by jnvsor

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fixes a bug preventing the saving of translations containing a `%%` literal
| Type?         | bug fix
| Category?     | BO/LO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Attempt a translation containing a literal `%%` - it will not be saved (Despite a green popup)

2019-11-15 10:07 UTC, Progi1984 commented
@jnvsor Thank you for your contribution. Could you open an issue for describing the bug ? Thanks

2019-11-15 10:25 UTC, jnvsor commented
@Progi1984 Added a bug report

2020-01-16 15:05 UTC, PierreRambaud requested changes
Hi and sorry for the delay,
why not updating the ̀regexSprintfParams` property?

2020-01-16 16:07 UTC, jnvsor commented
Because you still want `isSprintfString` to return true if the only argument is a `%%`, otherwise you might break existing strings

2020-01-17 09:48 UTC, PierreRambaud commented
@jnvsor This could be done with a single regex :thinking:

2020-01-18 18:27 UTC, jnvsor commented
> This could be done with a single regex

By using capture groups? I presume there was a performance reason not to, given that someone went to the effort of making the groups in this regex non-capturing in the first place.

The options as I see them are:

1. Have one regex that matches `%%` and ignore bug #16421
2. Have one regex that doesn't match `%%` and break existing translation strings with `%%` in them (Though given the existence of #16421 there may not be many of these)
3. Have two regexes
4. Use capture groups to distinguish between matches and argument counts (Would need more creative testing)

2020-01-20 10:07 UTC, PierreRambaud commented
@jnvsor We should be able to use each characters we want :thinking: 
Having two regexes = two to maintain.
let's continue the discussion in the issue :)

2020-09-15 16:13 UTC, matks commented
@PierreRambaud Any update :) ?

2020-09-16 09:39 UTC, PierreRambaud commented
> @PierreRambaud Any update :) ?

Waiting for a feedback, this solution is not clean IMHO

2021-08-11 16:33 UTC, matks commented
Hello, it seems this PR has no activity since 2020.

I close this PR, following our [review guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/) "Pull Requests may be closed after 30 days of inactivity".

If however you are still interested in it, please ping us 😉  we can reopen.

Thank you for your contribution.

2021-08-11 16:33 UTC, closed without merging