Add webservice to OrderCartRule with endpoint order_cart_rules
PrestaShop/PrestaShop pull request #16710
Opened 2019-12-05 14:56 UTC by Daxtermania

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop / 1.7.6.x / 1.6.1.x
| Description?  | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc.
| Type?         | bug fix / improvement / new feature / refacto / critical
| Category?     | FO / BO / CO / IN / WS / TE
| BC breaks?    | Does it break backward compatibility? yes/no
| Deprecations? | Does it deprecate an existing feature? yes/no
| Fixed ticket? | [Issue](https://github.com/PrestaShop/PrestaShop/issues), please write "Fixes #[issue number]" here.
| How to test?  | Please indicate how to best verify that this PR is correct.

2020-01-15 19:11 UTC, Daxtermania reviewed
All is correct

2020-01-16 08:40 UTC, PierreRambaud commented on classes/webservice/WebserviceRequest.php
> +            'order_histories' => array('description' => 'The Order histories','class' => 'OrderHistory'),
Please don't change all lines. Make sure to edit only the needed one. Here, you break the Php-cs-fixer test :)

2020-01-17 09:10 UTC, PierreRambaud approved these changes

2020-01-17 09:11 UTC, PierreRambaud requested changes
Could you move it to line 310?

2020-01-17 10:09 UTC, Daxtermania commented
> Could you move it to line 310?

Ready! Thx!

2020-01-17 13:07 UTC, PierreRambaud submitted a review, later dismissed

2020-02-06 16:49 UTC, Daxtermania commented
What is the problem?

2020-02-07 09:49 UTC, Progi1984 commented
@Daxtermania Your PR need to pass QA tests before being merged. Could you rebase your PR for fixing the conflicting file ? Thanks

2020-02-07 09:49 UTC, Progi1984 submitted a review, later dismissed

2020-03-09 13:01 UTC, Daxtermania commented
All OK?

2020-03-10 14:25 UTC, Progi1984 approved these changes

2020-03-12 18:00 UTC, PierreRambaud approved these changes

2020-03-23 12:25 UTC, Daxtermania commented
All OK?

2020-03-25 14:35 UTC, PierreRambaud commented
@Daxtermania See @Progi1984's comment :wink: 

> @Daxtermania Your PR need to pass QA tests before being merged. Could you rebase your PR for fixing the conflicting file ? Thanks

2020-04-02 14:51 UTC, SD1982 commented
The order_cart_rules webservices is correctly added by this PR. Thanks @Daxtermania

2020-04-02 14:58 UTC, merged

2020-04-02 14:58 UTC, Progi1984 commented
Thanks @Daxtermania

2020-11-17 09:13 UTC, bodi000 commented
Hello,
Is there any reason for not pushing this to 1.7.6 for example? Thanks

2020-11-19 21:20 UTC, Uebix commented
@PierreRambaud , @SD1982 please change the target 1.7.8.0, it is too far.
This is a regression fix, is impossible to wait for 1.7.8.
Is there any reason for not pushing this in the next release?
I know that 1.7.7.0 is in RC but this bugfix can be ready for 1.7.7.1 (for example).

2020-11-23 16:51 UTC, Progi1984 commented
@Uebix @bodi000 FYI, we are currently the stable version of 1770. So as the bug is not critical or major, it will be fixed in the next release.

2021-03-12 13:31 UTC, adrielalonso commented
good evening. When do you plan to release version 1.7.8? I also need to access order_cart_rule through the api
Thanks

2021-07-16 16:12 UTC, chattago2002 commented
Hi. Is there the possibility to reintroduce the access to order_cart_rule through the api in the next release (1.7.7.6)?
PS 1.7.8.0 is too far for who needs to have this data for webservice usage.
Thanks

2021-07-17 20:29 UTC, matks commented
> Hi. Is there the possibility to reintroduce the access to order_cart_rule through the api in the next release (1.7.7.6)?
> PS 1.7.8.0 is too far for who needs to have this data for webservice usage.
> Thanks

I'm sorry, no, this would be against our patch strategy.

You can apply the changes on your shop to benefit from the bugfix, but if there is a 1.7.7.6 release it will not contain this bugfix.

2021-07-20 16:17 UTC, chattago2002 commented
> > Hi. Is there the possibility to reintroduce the access to order_cart_rule through the api in the next release (1.7.7.6)?
> > PS 1.7.8.0 is too far for who needs to have this data for webservice usage.
> > Thanks
> 
> I'm sorry, no, this would be against our patch strategy.
> 
> You can apply the changes on your shop to benefit from the bugfix, but if there is a 1.7.7.6 release it will not contain this bugfix.

Ok, I will try on my own