Can't export data more than filters limits
PrestaShop/PrestaShop pull request #16742
Opened 2019-12-09 10:46 UTC by PierreRambaud

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Customers, manufacturers, suppliers and Categories can't be export over the default limit.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #16328 
| How to test?  | Follow ticket instruction, and repeat with Categories, manufacturers and suppliers.

2019-12-09 12:14 UTC, jolelievre requested changes

2019-12-09 12:14 UTC, jolelievre commented on src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php
> +        $filters = new CategoryFilters(['limit' => null] + CategoryFilters::getDefaults());
By doing that you ignore all previously set filters in the grid, so the export action will simply return all the categories all the time (regardless of your current filtering) I'd recommend rebuild an object filter based on the provided values:
```php
$filters = new CategoryFilters($filters->all() + ['limit' => null], $filters->getFilterId());
```

2019-12-19 09:45 UTC, Progi1984 approved these changes

2019-12-30 14:15 UTC, sarahdib commented
@jolelievre it's ok for you ?

2019-12-30 14:26 UTC, jolelievre approved these changes

2019-12-30 14:26 UTC, jolelievre commented
@sarahdib yep all good

2020-01-08 09:44 UTC, sarahdib commented
@PierreRambaud It's fixed for all except for supplier

2020-01-08 16:02 UTC, PierreRambaud commented
@sarahdib The supplier has not been migrated yet :sweat_smile: This is why it's not working yet

2020-01-08 16:18 UTC, merged

2020-01-08 16:19 UTC, Progi1984 commented
Thanks @PierreRambaud