Minor bug fix for Cache class
PrestaShop/PrestaShop pull request #16819
Opened 2019-12-15 14:59 UTC by zapper

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | When APC cache and debug mode enabled you get a notice that says "Undefined index 'count' in array". This fix adds additional check if index 'count' is defined in array. Problem arises  because function 'updateQueryCacheStatistics' in line 358 is called before function 'updateTableToQueryMap' in line 360.
| Type?         | bug fix 
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | [Issue] "Fixes #16779".
| How to test?  | Enable APC cache and debug mode, check if there any notices about undefined index 'count' in array.

2019-12-16 09:02 UTC, Progi1984 commented
@zapper Thank you for your contribution. Could you fix errors on `[Pretty CI](https://github.com/PrestaShop/PrestaShop/pull/16819/checks?check_run_id=349447571)`, please ? Thanks

2019-12-16 09:03 UTC, Progi1984 submitted a review, later dismissed

2019-12-16 11:30 UTC, Progi1984 submitted a review, later dismissed

2019-12-16 12:39 UTC, PierreRambaud commented on classes/cache/Cache.php
> +                    if (isset($this->sql_tables_cached[$table][$key], $this->sql_tables_cached[$table][$key]['count'])) {
```suggestion
                    if (isset($this->sql_tables_cached[$table][$key]['count'])) {
```

2019-12-16 12:39 UTC, PierreRambaud requested changes
Make it easier :)

2019-12-16 14:20 UTC, zapper commented
> Make it easier :)

Good point :)

2019-12-16 14:21 UTC, PierreRambaud approved these changes

2019-12-18 10:10 UTC, khouloudbelguith commented
Hi @zapper,

I did not manage to reproduce the issue with the develop branch.
https://drive.google.com/file/d/1ZvJMDqJCzOoYYgOir3ubvdEzt9x38-k5/view
It is OK.

Thanks to check & feedback.

2019-12-22 17:34 UTC, zapper commented
> Hi @zapper,
> 
> I did not manage to reproduce the issue with the develop branch.
> https://drive.google.com/file/d/1ZvJMDqJCzOoYYgOir3ubvdEzt9x38-k5/view
> It is OK.
> 
> Thanks to check & feedback.

Try to navigate through front office, category, product page. My bad, I forgot to mention that this issue occurs in front office.

2019-12-23 10:43 UTC, khouloudbelguith commented
@zapper, thanks for your feedback.
With develop branch, I only Have this error
`VM1139 theme.js:1 Uncaught TypeError: Cannot read property 'top' of undefined`
I don't think, it is the same issue
https://drive.google.com/file/d/1VxcGDs_Wi7V_BWjTReLk3s_Dny2TBy7q/view
Thanks to check & feedback.

2020-01-08 10:02 UTC, PierreRambaud commented
@khouloudbelguith It's not the same error and seems to not be related to this pull request.

2020-01-08 10:09 UTC, khouloudbelguith commented
Hi @PierreRambaud,

The problem, that the issue is not reproduced on the develop branch.
I'm waiting for the @zapper's response.
Thanks!

2020-01-22 09:29 UTC, sarahdib commented
Hello

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!

2020-01-22 09:29 UTC, closed without merging