Functional Tests -  Add prefix verification for delivery slip file
PrestaShop/PrestaShop pull request #16960
Opened 2019-12-30 14:24 UTC by nesrineabdmouleh

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add prefix verification for delivery slip file
| Type?         | refactor
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | TEST_PATH="functional/BO/orders/deliverySlips/02_deliverySlipOptions/01_deliverySlipPrefix.js" URL_FO=yourShopURL npm run specific-test

2019-12-30 14:41 UTC, boubkerbribri reviewed
thank you @nesrineabdmouleh

2019-12-30 14:41 UTC, boubkerbribri commented on tests/puppeteer/campaigns/functional/BO/orders/deliverySlips/02_deliverySlipOptions/01_deliverySlipPrefix.js
> +const OrdersPage = require('@pages/BO/orders/index');
FYI no need for index, you can call it like this
```js
const OrdersPage = require('@pages/BO/orders');
```

2019-12-30 14:41 UTC, boubkerbribri commented on tests/puppeteer/campaigns/functional/BO/orders/deliverySlips/02_deliverySlipOptions/01_deliverySlipPrefix.js
> +      await this.pageObjects.boBasePage.closeSfToolBar();
Can you delete this please, no need to do it two times.

2019-12-31 08:55 UTC, NeOMakinG requested changes

2019-12-31 08:55 UTC, NeOMakinG commented on tests/puppeteer/campaigns/functional/BO/orders/deliverySlips/02_deliverySlipOptions/01_deliverySlipPrefix.js
> +  });
```suggestion
  });
  
```

2019-12-31 08:55 UTC, NeOMakinG commented on tests/puppeteer/campaigns/functional/BO/orders/deliverySlips/02_deliverySlipOptions/01_deliverySlipPrefix.js
> +      );
```suggestion
      );
      
```

2019-12-31 08:55 UTC, NeOMakinG commented on tests/puppeteer/campaigns/functional/BO/orders/deliverySlips/02_deliverySlipOptions/01_deliverySlipPrefix.js
> +      );
```suggestion
      );
      
```

2019-12-31 08:55 UTC, NeOMakinG commented on tests/puppeteer/campaigns/functional/BO/orders/deliverySlips/02_deliverySlipOptions/01_deliverySlipPrefix.js
> +      );
```suggestion
      );
      
```

2019-12-31 10:13 UTC, NeOMakinG approved these changes

2019-12-31 10:32 UTC, merged