email subject doesn't support html entities
PrestaShop/PrestaShop pull request #17073
Opened 2020-01-08 17:16 UTC by jf-viguier

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Tools::safeOutput html entities encode subject that produce a buggy subject with special caracters.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/issues/16847
| How to test?  | Add a special character in Shop name and send an email.

2020-01-08 17:40 UTC, jf-viguier commented
PrettyCI failed please restart it or tell me what ?

2020-01-09 08:57 UTC, Progi1984 commented
@jf-viguier Prettry CI is now :green_heart:

2020-01-09 09:00 UTC, Progi1984 submitted a review, later dismissed

2020-01-09 10:04 UTC, PierreRambaud approved these changes

2020-01-09 10:04 UTC, PierreRambaud submitted a review, later dismissed

2020-01-15 14:05 UTC, jolelievre requested changes
Based on the changes in https://github.com/PrestaShop/PrestaShop/pull/16500 I guess you should make the same modif on line 508 as well?

2020-01-15 14:19 UTC, PierreRambaud commented
@jolelievre Not necessary, subject isn't working as message content.

2020-01-15 14:27 UTC, jolelievre approved these changes

2020-01-15 14:28 UTC, jolelievre commented
> @jolelievre Not necessary, subject isn't working as message content.

Oh yeah, I guess

2020-01-16 10:06 UTC, jf-viguier commented
> @jolelievre Not necessary, subject isn't working as message content.

Yes indeed, check smtp rfc : subject is an smtp header, message content can be in html if appropriate mime type but not the subject. It has to be encoded according to RFC 1342 : the mail library already do the job.

2020-01-27 10:24 UTC, Progi1984 commented
After validation of the QA, we need to backport the fix in 1.7.6.x branch.

2020-01-31 13:42 UTC, Progi1984 approved these changes

2020-02-04 16:35 UTC, Robin-Fischer-PS commented
Hi :) It's QA :heavy_check_mark: ! Tested also on Multistore.

2020-02-04 16:40 UTC, matks commented
Thank you @jf-viguier

2020-02-04 16:40 UTC, merged