Do not allow negative amount in order payment block
PrestaShop/PrestaShop pull request #17241
Opened 2020-01-20 10:05 UTC by atomiix

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Do not allow negative amount in order payment
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #16582
| How to test?  | In the migrated order/view page, try to add a payment with a negative amount, an error should be displayed and the payment should not be added

2020-01-20 10:10 UTC, PierreRambaud commented on src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
> +        } elseif (!$form->isValid()) {
```php
       if ($form->isSubmitted()) {
            if (!$form->isValid()) {
                foreach ($form->getErrors(true) as $error) {
                    $this->addFlash('error', $error->getMessage());
                }
            } else {
                $data = $form->getData();

                try {
                    $this->getCommandBus()->handle(
                        new AddPaymentCommand(
                            $orderId,
                            $data['date'],
                            $data['payment_method'],
                            $data['amount'],
                            $data['id_currency'],
                            $data['id_invoice'],
                            $data['transaction_id']
                        )
                    );

                    $this->addFlash('success', $this->trans('Successful update.', 'Admin.Notifications.Success'));
                } catch (Exception $e) {
                    $this->addFlash('error', $this->getErrorMessageForException($e, $this->getErrorMessages($e)));
                }
            }
        }

2020-01-20 10:15 UTC, matks commented
Can you turn on the test we disabled until this bug is fixed ? 😄this will help validating the feature

https://github.com/tdavidsonas88/PrestaShop/commit/ea4251123a6c43eaf53b9a1fb13006751b434765

2020-01-21 13:29 UTC, jolelievre approved these changes
Thanks @atomiix

2020-01-21 13:54 UTC, PierreRambaud submitted a review, later dismissed

2020-01-21 14:28 UTC, jolelievre requested changes
Sorry I missed the behat test part ^^ Please add:
- a check for negative amount in the handler (or the command via ValueObject maybe easier) which throws an exception
- reactivate the behat test and add a line to check that the appropriate exception has been thrown

2020-01-27 10:10 UTC, matthieu-rolland submitted a review, later dismissed
@jolelievre 's feedback has been dealt with properly, LGTM for me 👍

2020-01-27 10:16 UTC, PierreRambaud submitted a review, later dismissed

2020-01-29 14:38 UTC, jolelievre commented on src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
> +                'The amount should be greater than 0.',
```suggestion
                'The amount of a payment should be strictly positive.',
```

Suggestion @LouiseBonnard what do you think?

2020-01-29 14:38 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/Domain/OrderPaymentFeatureContext.php
> +            $this->lastException = $exception;
Be careful you removed an expected behaviour (with Property Order->total_paid_real is not valid), although the way it was managed was weird
You need to find the related behat test and fix/refacto it By catching the `PrestaShopException` exception and maybe only store it when the message matches so that other use cases correctly fail

2020-01-29 14:45 UTC, jolelievre submitted a review, later dismissed

2020-01-29 15:01 UTC, LouiseBonnard commented on src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
> +                'The amount should be greater than 0.',
It sounds a bit authoritarian. Why changing the wording, isn't it clear enough?

If you want to emphasize the mandatory side of it, I would write _Invalid value: the payment must be a positive amount._, what do you think?

2020-01-29 16:42 UTC, Robin-Fischer-PS commented
Hi @atomiix ! Could you resolve the conflict on this PR ? Thanks !

2020-01-30 11:07 UTC, jolelievre commented on src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
> +                'The amount should be greater than 0.',
It's not the mandatory side that I wanted to emphasize, but more having a less "technical" message I just though "positive amount" is maybe more understandable than "greater to 0"

2020-01-30 11:11 UTC, LouiseBonnard commented on src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
> +                'The amount should be greater than 0.',
I agree, thanks @jolelievre. I still suggest _Invalid value: the payment must be a positive amount._ in this case, it looks clearer.

2020-01-30 13:26 UTC, jolelievre approved these changes
Nice @atomiix

2020-01-30 13:52 UTC, PierreRambaud approved these changes

2020-02-03 08:27 UTC, merged

2020-02-03 08:27 UTC, Progi1984 commented
Thanks @atomiix

2021-04-21 23:09 UTC, djbuch commented
This is completely wrong... The majority of e-commercant we are helping are typing negative amounts in case of reimbursement... This should be rolled back as soon as possible.

2021-04-22 07:12 UTC, matks commented
Hi @djbuch there are 4 possible ways to refund an order:

You can see the details in https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/back-office/orders/orders/Order%20Page%20View.md#merchandise-return-has-to-be-enabled-if-the-merchant-want-to-use-the-standard-refund-partial-refund-and-return-product-feature

Why not use them rather than typing a negative amount in a "payment" field?

2021-04-22 07:18 UTC, djbuch commented
Because those use cases only create the OrderSlip if the Invoice has already been created or cancel a product, but it won't change the payment.

But imagine a workflow were the invoice is created when the Order is already sent out.
Then the seller sees he has not enough of one product, so he cancels the product or lowers the quantity, the order total is so decreased, and he will have an error in the payment section, saying that there was too much paid.

So when he really makes the reimbursement to the buyer with his bank system, he could note this in here with a negative amount to keep track of financial mouvement for this order.

2021-04-22 07:31 UTC, matks commented
@djbuch So if I understand correctly, here is a valid scenario

1. I buy 4 boxes of Sugar, each costs 15€ => my order is 60€. I pay 60€. No shipping fees. No VAT, it's B2B.
2. I receive my invoice (it mentions 60€).
3. Merchant finds out OH NO! he has only 3 boxes
4. Merchant wants to modify the order, he modifies the quantity to 3. Order total decreases to 45€.
5. But I already paid 60€ ! So this order is in "overdue" status.
6. What you want to do is "Merchant sends a 15€ check to me, and marks the order as 'paid' (not overdue)" in the Back Office because now the amount I have paid and the amount of my order are equal

Is that a good scenario ?

@MatShir @marionf what do you think about this usecase?

@djbuch I still think that adding negative amount payments is not a good solution 😅  but maybe there is a scenario that is not handled by PrestaShop, indeed. Let's see what Product Team can say.

2021-04-22 07:34 UTC, djbuch commented
@matks Yes this is a valide use case.

Maybe the negative could be checked agains total payments no becoming negative. But a reimbursement is indeed a negative payment.

2021-08-31 09:45 UTC, matks commented
AFAIK Product team is actually in the process of getting some law compliance people so that they can tell us what can be done or what cannot be done in order to comply with the law.

2022-11-22 14:25 UTC, PrestaEdit commented
The main issue there is not that you disallow to add the negative price on the Back Office, but that the model have been change (it's a BC break, as far I know) on a minor version (1.7.7) and you are now not allowed to make a refund with a specific transaction ID and set the negative amount using the ObjectModel related, so.