Fix https://github.com/PrestaShop/PrestaShop/issues/17290
PrestaShop/PrestaShop pull request #17294
Opened 2020-01-22 10:45 UTC by idnovate

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Refresh cart summary when adding a voucher
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #17290
| How to test?  | Check bug description

2020-01-24 10:44 UTC, Progi1984 commented
@idnovate Thank you for your contribution. We have a problem with this PR : he doesn't pass sanity test on Travis on PHP 7.2  (https://travis-ci.com/PrestaShop/PrestaShop/jobs/278305360#L798).

2020-01-27 13:55 UTC, Progi1984 commented
@idnovate I rebase your PR with the latest version of develop. Now it pass Travis ;)

2020-01-27 13:55 UTC, Progi1984 submitted a review, later dismissed

2020-01-27 14:19 UTC, PierreRambaud commented on themes/classic/templates/checkout/_partials/cart-summary-products.tpl
> +    <p>{$cart.summary_string}</p>
use two spaces for indentation please

2020-01-27 14:19 UTC, PierreRambaud commented on themes/classic/templates/checkout/_partials/cart-summary-products.tpl
> +            <li class="media">{include file='checkout/_partials/cart-summary-product-line.tpl' product=$product}</li>
As I said for #17296 wrong indentation in this file.

2020-01-27 14:19 UTC, PierreRambaud requested changes
Problem with indentation

2020-01-27 15:38 UTC, Progi1984 submitted a review, later dismissed

2020-01-27 15:38 UTC, PierreRambaud commented on themes/classic/templates/checkout/_partials/cart-summary-products.tpl
> +     </ul>
```suggestion
      </ul>
```

2020-01-27 15:48 UTC, Progi1984 approved these changes

2020-01-28 14:18 UTC, PierreRambaud approved these changes

2020-01-30 14:57 UTC, khouloudbelguith commented
Hi @idnovate,

Issue not fixed using your PR
I attached a screen record
https://drive.google.com/file/d/1XpjvTSzwTqUSsdvjnVCqvfHZND27zmJC/view
Thanks to check & feedback.

2020-01-30 15:25 UTC, idnovate commented
> Hi @idnovate,
> 
> Issue not fixed using your PR
> I attached a screen record
> https://drive.google.com/file/d/1XpjvTSzwTqUSsdvjnVCqvfHZND27zmJC/view
> Thanks to check & feedback.

- Have you cleared cache and force compilation?
- Could you please check if you have any JS error?
- Could you please check if you have field `cart_summary_products` in the response, and if it's not empty?

Thanks!

2020-01-30 15:31 UTC, khouloudbelguith commented
@idnovate,
>Have you cleared cache and force compilation?

Yes!
>Could you please check if you have any JS error?

No, there is no error.
I attached a screen record
https://drive.google.com/file/d/1enqLAv1RIBOuBNqMacLM7s0_DalRuId9/view

Thanks!

2020-01-30 15:41 UTC, idnovate commented
> @idnovate,
> 
> > Have you cleared cache and force compilation?
> 
> Yes!
> 
> > Could you please check if you have any JS error?
> 
> No, there is no error.
> I attached a screen record
> https://drive.google.com/file/d/1enqLAv1RIBOuBNqMacLM7s0_DalRuId9/view
> 
> Thanks!

Great, and for the last point, could you please record "Network" tab and check the response?

2020-01-31 08:10 UTC, khouloudbelguith commented
@idnovate, here's the screen record
https://drive.google.com/file/d/18lp37Eqcc4W45lCk-OiAvB5D4XHtq329/view

Thanks!

2020-01-31 08:20 UTC, idnovate commented
> @idnovate, here's the screen record
> https://drive.google.com/file/d/18lp37Eqcc4W45lCk-OiAvB5D4XHtq329/view
> 
> Thanks!

Thanks for helping me to debug why it's not working for you!

The response is OK. The issue seems to be then in file `themes/_core/js/cart.js`. Could you please check if you have this line?

`$('.cart-summary-products').replaceWith(resp.cart_summary_products);`

Please note that you need to generate the final JS, I don't know how to do it! :sweat: To test it I directly edit the generated JS.

2020-01-31 09:21 UTC, khouloudbelguith commented
Hi @idnovate,

Yes!
![image](https://user-images.githubusercontent.com/16067358/73527474-68b54900-4413-11ea-9300-50e1f0471bcd.png)

Thanks!

2020-01-31 09:30 UTC, idnovate commented
Then the problem is this:

> Please note that you need to generate the final JS, I don't know how to do it! 😓 To test it I directly edit the generated JS.

This JS is not added in the front, but `/themes/core.js` that include this JS. With webpack?

2020-01-31 11:25 UTC, khouloudbelguith commented
@idnovate, I will check & feedback.

Thanks!

2020-01-31 16:02 UTC, khouloudbelguith commented
Hi @idnovate,

It is OK!
https://drive.google.com/file/d/1VJtKiVVpqSqPa4gDyWc9dX_SCb62_tJv/view

Thanks!

2020-01-31 16:12 UTC, matks commented
Thank you @idnovate

2020-01-31 16:12 UTC, merged