Add displayProductPriceBlock hook
PrestaShop/PrestaShop pull request #17296
Opened 2020-01-22 11:17 UTC by idnovate

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Added new hook to display information in the checkout summary. This hook is used everytime that product price is displayed but in this template
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Create a module and hook it to `displayProductPriceBlock`. Then display any information.

2020-01-27 10:39 UTC, matthieu-rolland reviewed
LGTM for me, codewise, but no issue has been created for this, I would like the opinion of other core developers before validating this PR ?

@PrestaShop/prestashop-core-developers what do you think?

2020-01-27 10:48 UTC, PierreRambaud commented on themes/classic/templates/checkout/_partials/cart-summary-products.tpl
> +    <p>{$cart.summary_string}</p>
Could you use two spaces for indentation please? :)

2020-01-27 10:48 UTC, PierreRambaud commented on themes/classic/templates/checkout/_partials/cart-summary-products.tpl
> +    <div class="collapse" id="cart-summary-product-list">
wrong indent here

2020-01-27 10:48 UTC, PierreRambaud commented on themes/classic/templates/checkout/_partials/cart-summary-products.tpl
> +            <li class="media">{include file='checkout/_partials/cart-summary-product-line.tpl' product=$product}</li>
wrong indent here

2020-01-27 10:48 UTC, PierreRambaud requested changes
Little indentation problem, and everything's ok for me

2020-01-27 10:54 UTC, idnovate commented
> Little indentation problem, and everything's ok for me

Done

2020-01-27 10:57 UTC, matthieu-rolland submitted a review, later dismissed
lgtm, thank you @idnovate 👍

2020-01-27 11:10 UTC, PierreRambaud commented on themes/classic/templates/checkout/_partials/cart-summary-products.tpl
> +  <div class="collapse" id="cart-summary-product-list">
need one more indentation level :)

2020-01-27 11:13 UTC, idnovate commented on themes/classic/templates/checkout/_partials/cart-summary-products.tpl
> +  <div class="collapse" id="cart-summary-product-list">
You are right!

2020-01-27 11:14 UTC, PierreRambaud submitted a review, later dismissed

2020-01-27 13:12 UTC, matthieu-rolland submitted a review, later dismissed

2020-02-05 14:51 UTC, matks submitted a review, later dismissed

2020-02-05 14:51 UTC, matks commented
@idnovate Can you provide a test module for QA team ? If you have not enough time, I can do it 😉

2020-02-05 15:15 UTC, idnovate commented
Please install attached module to test it.

![image](https://user-images.githubusercontent.com/15104724/73854317-a3174f80-4832-11ea-9772-0d8b8cb454b8.png)

[dummymodule.zip](https://github.com/PrestaShop/PrestaShop/files/4160243/dummymodule.zip)

2020-02-05 15:38 UTC, matks commented
Great ! Then I pass the PR to QA team 😄

2020-03-16 09:31 UTC, SD1982 commented
Hi @idnovate could you please resolve the conflicting files ?

2020-03-16 09:59 UTC, idnovate commented
> Hi @idnovate could you please resolve the conflicting files ?

Done :thumbsup:

2020-03-16 10:02 UTC, Progi1984 approved these changes

2020-03-22 10:15 UTC, PierreRambaud approved these changes

2020-04-03 09:37 UTC, matks approved these changes

2020-04-08 17:28 UTC, khouloudbelguith commented
Hi @idnovate,

Thanks, it is OK.
With PR:
![image](https://user-images.githubusercontent.com/16067358/78814504-03f80b00-79cf-11ea-81c2-353b2bbda089.png)

Without PR:
![image](https://user-images.githubusercontent.com/16067358/78814546-17a37180-79cf-11ea-89e6-f1accdaff756.png)

Thanks!

2020-04-09 06:26 UTC, merged

2020-04-09 06:26 UTC, Progi1984 commented
Thanks @idnovate