Fix supplier form
PrestaShop/PrestaShop pull request #17305
Opened 2020-01-22 15:40 UTC by zuk3975

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Supplier form had DNI field which wasn't suppose to be there according to legacy behavior. Also supplier missed handling of postcode field. Fixed.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | #17268
| How to test?  | Open supplier form and see that there is no DNI field and post code field should be saved correctly.

2020-01-22 15:55 UTC, matks commented
@marionf Apparently, we added "DNI" and "postcode" inputs to Supplier page when we migrated it. Probably because it seems to make sense 😄.

It seems it was a bad idea but ... is it ? Can you tell us what you think ?

2020-01-22 15:58 UTC, PierreRambaud commented
Supplier has address, it must contain a DNI if needed :sweat_smile:

2020-01-23 07:01 UTC, zuk3975 commented
Hmm i was migrating suppliers myself. I just added it by mistake, comparing to legacy it doesnt have dni. Ofcourse i can add the field back and implement its handling, its not so hard.

2020-01-23 09:09 UTC, marionf commented
@matks the zip code was already there in legacy and make sense as it's an address
However the DNI wasn't there in legacy and not seems logical to have it for a supplier

2020-01-23 09:12 UTC, PierreRambaud commented
@marionf the DNI is something mandatory for some country :thinking:

2020-01-23 09:15 UTC, marionf commented
The DNI is the id card ? Not sure a supplier have an id card ?

2020-01-23 10:00 UTC, zuk3975 commented
> The DNI is the id card ? Not sure a supplier have an id card ?

cmon guys, so, could you tell if it is required or not for sure :smile:  ?

2020-01-23 10:24 UTC, PierreRambaud commented
@marionf We need confirmation since DNI can be mandatory each time we have an address form.

2020-01-23 10:37 UTC, zuk3975 commented
> @marionf We need confirmation since DNI can be mandatory each time we have an address form.

It doesn't depend from country required field options nor addresses->requiredFields options (at least according to legacy behaviour)

2020-01-24 09:30 UTC, marionf commented
> @marionf the DNI is something mandatory for some countries 

Yes, for a physical person but I don't see the interest of a DNI field for a supplier as it's not a physical person
Unless I am missing something :thinking:

2020-01-27 17:24 UTC, matks commented
So ... no DNI ? It's approved ?

2020-01-28 14:42 UTC, PierreRambaud submitted a review, later dismissed
She said, remove DNI :tada:

2020-01-31 14:48 UTC, matks submitted a review, later dismissed

2020-02-06 14:14 UTC, Robin-Fischer-PS commented
Hi @zuk3975 !

I've an exception when adding a new supplier (call to "getDni" method).
![pr17305 getdni error](https://user-images.githubusercontent.com/55688534/73944556-17b1c300-48f3-11ea-9cd2-2db93e119655.png)

2020-02-12 11:28 UTC, zuk3975 commented
> Hi @zuk3975 !
> 
> I've an exception when adding a new supplier (call to "getDni" method).
> ![pr17305 getdni error](https://user-images.githubusercontent.com/55688534/73944556-17b1c300-48f3-11ea-9cd2-2db93e119655.png)

Sorry for such dumb mistake :(, Fixed.

2020-02-12 12:42 UTC, matks submitted a review, later dismissed

2020-02-12 12:44 UTC, Progi1984 submitted a review, later dismissed

2020-02-12 12:46 UTC, PierreRambaud submitted a review, later dismissed

2020-02-12 13:09 UTC, Robin-Fischer-PS commented
Hi @marionf @zuk3975 ! It seems like DNI field was needed for some country, like Spain : It is now impossible to add a supplier address in Spain, because there is an error, I suppose it's because, in address format, DNI in always required in Spain.
The error : 
![pr17305 spain dni](https://user-images.githubusercontent.com/55688534/74337739-2b50a400-4da1-11ea-83b2-f6fef0c163fc.png)
The default format address in Spain (DNI cannot be removed from it) : 
![pr17305 spain format address](https://user-images.githubusercontent.com/55688534/74337817-54713480-4da1-11ea-9be3-bb6e7c414a5a.png)

2020-02-12 13:17 UTC, marionf commented
@zuk3975 

I thought the DNI field wasn't on the legacy page, but it was for some countries, my mistake I am sorry
So, we have to keep the same behavior as legacy page:
Display DNI field for countries where it's mandatory ("Do you need a tax identification number" set to Yes)

2020-02-12 14:28 UTC, PierreRambaud commented
@marionf Told you :tada: :tada: :tada: :tada: :joy_cat:

2020-02-13 08:29 UTC, Progi1984 submitted a review, later dismissed

2020-02-13 10:58 UTC, zuk3975 commented
@Robin-Fischer-PS,
Reverted the commits. Because its associated with major issue of AddressFormat-Country settigns relation, I did not implement dynamic DNI field rendering, but instead DNI field is always shown as non-required field.

Will create an issue for 1.7.8 to fix addresses and include this page too.
For 1.7.7 Its good to go.

2020-02-13 11:47 UTC, zuk3975 commented
Related issue: https://github.com/PrestaShop/PrestaShop/issues/17647

2020-02-13 14:12 UTC, PierreRambaud commented
The description and the title of this pull request must be updated

2020-02-14 09:28 UTC, zuk3975 commented
> The description and the title of this pull request must be updated

done

2020-02-19 13:39 UTC, Progi1984 submitted a review, later dismissed

2020-02-19 14:22 UTC, jolelievre submitted a review, later dismissed

2020-02-20 09:51 UTC, Robin-Fischer-PS commented
Hi ! It's now OK, DNI and Zip code are saved when filled ! QA :heavy_check_mark: 

![pr17305 proof](https://user-images.githubusercontent.com/55688534/74922038-ee069a80-53ce-11ea-8a53-e25fb94453c4.png)

Thanks @zuk3975

2020-02-20 11:31 UTC, rokaszygmantas requested changes

2020-02-20 11:31 UTC, rokaszygmantas commented on src/Core/Domain/Supplier/QueryResult/EditableSupplier.php
> +     * @return array|null ?array
strange docblock

2020-02-20 11:35 UTC, zuk3975 commented on src/Core/Domain/Supplier/QueryResult/EditableSupplier.php
> +     * @return array|null ?array
done

2020-02-20 11:36 UTC, rokaszygmantas approved these changes

2020-02-20 11:37 UTC, Progi1984 approved these changes

2020-02-20 12:16 UTC, merged