fix pelago/emogrifier version spech in composer.json
PrestaShop/PrestaShop pull request #17554
Opened 2020-02-07 13:57 UTC by davideapvd

I think the composer.json package version should be forced to be 2.1.1 or this bug could happen, see https://github.com/PrestaShop/PrestaShop/issues/16017

composer upgrade will bring 2.2.0

2020-02-11 15:08 UTC, PierreRambaud requested changes
We already target the 2.2.0: https://github.com/PrestaShop/PrestaShop/blob/develop/composer.lock#L3538

2020-05-25 08:57 UTC, Progi1984 commented
Ping @davideapvd

2020-05-25 09:25 UTC, drc0 commented
sorry but I don't know how composer pulled the wrong version there. I'm unable to test this right now.

2020-05-25 09:34 UTC, Progi1984 commented
@drc0 @davideapvd Do you want we close this PR ?

2020-05-25 09:41 UTC, drc0 commented
yes please, let see if anyone else have this problem in the future.

2020-05-25 09:55 UTC, closed without merging