Order price font size
PrestaShop/PrestaShop pull request #17568
Opened 2020-02-07 17:46 UTC by atomiix

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | The font size of the price for a paid order was too small. The font color for some default order status was not white as expected. This PR fixes it.
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #17551
| How to test?  | In the migrated Order list pages, the price for a paid order should have the same font size as a price for a non-paid order. Every migrated status colors should have white

2020-02-11 09:47 UTC, Progi1984 approved these changes

2020-02-11 09:49 UTC, Progi1984 commented on admin-dev/themes/default/template/helpers/list/list_content.tpl
> +					<span class="label color_field" style="background-color:{$tr[$params.color]};color:{if Tools::getBrightness($tr[$params.color]) < 130}white{else}#383838{/if}">
```suggestion
					<span class="label color_field" style="background-color:{$tr[$params.color]};color:{if Tools::getBrightness($tr[$params.color]) < constant('PrestaShop\PrestaShop\Core\Util\ColorBrightnessCalculator::BRIGHT_COLOR_MIN')}white{else}#383838{/if}">
```

2020-02-11 09:49 UTC, Progi1984 commented on src/Core/Util/ColorBrightnessCalculator.php
> +    const BRIGHT_COLOR_MIN = 130;
```suggestion
    public const BRIGHT_COLOR_MIN = 130;
```

2020-02-11 09:50 UTC, Progi1984 requested changes
Please some changes

2020-02-17 16:37 UTC, PierreRambaud commented on classes/Tools.php
> +        return (new ColorBrightnessCalculator())->isBright($hex);
Could you add a way to don't reinstanciate `ColorBrightnessCalculator` each time this function is called please :)

2020-02-17 16:37 UTC, PierreRambaud commented on src/Core/Util/ColorBrightnessCalculator.php
> +    private const BRIGHT_COLOR_MIN = 130;
Don't make it private. It's a BC :thinking:

2020-02-18 10:06 UTC, Progi1984 submitted a review, later dismissed

2020-02-19 09:43 UTC, NeOMakinG submitted a review, later dismissed

2020-02-19 09:50 UTC, NeOMakinG approved these changes

2020-02-19 11:56 UTC, Progi1984 approved these changes

2020-02-20 10:53 UTC, SD1982 commented
This Pr correctly increase the order price font size : 

**Before :** 
![Order price font size #17568 before PR](https://user-images.githubusercontent.com/40635814/74927211-7a1cc000-53d7-11ea-81bc-a60b6e895188.png)

**After :** 
![Order price font size #17568 after PR](https://user-images.githubusercontent.com/40635814/74927242-86a11880-53d7-11ea-85e2-9cd17ec92966.png)

Thanks @atomiix

2020-02-20 13:13 UTC, NeOMakinG commented
And what about the white color ?

2020-02-20 14:25 UTC, atomiix commented
@NeOMakinG looks like labels have white text on the "After" screenshot 😄

2020-02-20 14:43 UTC, NeOMakinG commented
Yes but there one @atomiix  

```
#34219E -> #34209E (Awaiting payment)
#2ECC71 -> #01B887 (Accepted payment)
```

But well we can merge but the QA seems not fully done as he looked only for the font-size change 🤓

2020-02-20 15:46 UTC, SD1982 commented
@NeOMakinG  , @atomiix 

> And what about the white color ? @SD1982

The white color for status label font size was a part of this PR : 

![Order price font size #17568 PR description](https://user-images.githubusercontent.com/40635814/74949991-c6c7c180-53fe-11ea-913f-414cd3e15510.png)

And the color change of the labels has also been verified 

But thank you anyway for notifying me I therefore take the opportunity to make a double check on this PR !

2020-02-20 16:01 UTC, merged