Fixed Exception for not defined variables when editing a product quantity in an order
PrestaShop/PrestaShop pull request #17641
Opened 2020-02-13 10:18 UTC by Progi1984

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Fixed Exception for not defined variables when editing a product quantity in an order
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #17618
| How to test?  | Steps to reproduce the behavior:<br>1. Go to the migrated order listing<br>2. View an order in "awaiting payment"<br>3. Edit the product quantity<br>4. Click on Save<br>5. **Before:** See 500 error in the Synfony console<br>5. **After:** No more error

2020-02-13 11:22 UTC, matthieu-rolland submitted a review, later dismissed
LGTM 👍 
I restarted the sanity test that failed, if it fails again we'll have to investigate...

(there's also a pretty CI issue)

2020-02-13 13:53 UTC, PierreRambaud requested changes
Waiting for PrettyCi fixes

2020-02-13 15:30 UTC, atomiix submitted a review, later dismissed

2020-02-13 16:57 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/Domain/OrderRefundFeatureContext.php
> +use PrestaShop\PrestaShop\Core\Domain\Order\Exception\InvalidOrderStateException;
Already fixed by https://github.com/PrestaShop/PrestaShop/pull/17643 You should rebase

2020-02-13 17:06 UTC, jolelievre approved these changes
Thanks @Progi1984

2020-02-14 08:32 UTC, PierreRambaud approved these changes

2020-02-17 09:55 UTC, SD1982 commented
I tried to reproduce the bug described in [# 17618](https://github.com/PrestaShop/PrestaShop/issues/17618) before applying the pull request but I was not able to do it. 

See here : https://drive.google.com/file/d/1BVbuYv5hlRVnbimMQCbUgKfnW_wp_eOr/view?usp=sharing

Can you verify that the bug is still present for you ?

2020-02-17 11:14 UTC, Progi1984 commented
@SD1982 You have the error in your video. Check the symfony Console 

![image](https://user-images.githubusercontent.com/1533248/74649003-03858580-517f-11ea-8f82-1dba84e519b2.png)

2020-02-17 11:44 UTC, marionf commented
@SD1982 

Sorry I can't try to reproduce the issue #17618 because I have another error before, when I click to view an order

![capture d'écran_2347](https://user-images.githubusercontent.com/13449658/74651010-35005000-5183-11ea-8825-b15b9ae62a7b.png)

2020-02-17 13:11 UTC, SD1982 commented
Sorry my bad !! I did not expect the error to only appear in the debug bar of symfony.
So I was finally able to reproduce the bug and I also confirm that the pull request correctly fix the bug. Thanks @Progi1984

2020-02-17 13:14 UTC, matks commented
Thank you @Progi1984

2020-02-17 13:14 UTC, merged