Refactoring applyPercentageDiscount() in CartRow class
PrestaShop/PrestaShop pull request #17687
Opened 2020-02-16 17:58 UTC by arouiadib

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       |  1.7.7.x 
| Description?  | This PR tries to optimize some few lines of code by rewriting `applyPercentageDiscount()` `in CartRow` class, allowing code reuse  in the processing of cheapest product.
| Type?         |  refacto
| Category?     |  CO 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes nothing.
| How to test?  | Nothing to test.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/17686)

2020-02-17 09:55 UTC, Progi1984 submitted a review, later dismissed

2020-02-17 10:05 UTC, atomiix submitted a review, later dismissed

2020-02-17 10:29 UTC, SD1982 commented
Ping @atomiix , @Progi1984  How can we test this PR ?

2020-02-17 10:38 UTC, atomiix commented
@SD1982 I think you can try to add a discount in Catalog > Discount > Add new cart rule. In the action tab, add a discount (in %) on the cheapest product. Then on the FO, try different scenarios on the cart and see if amounts are correct.

2020-02-17 13:38 UTC, SD1982 commented
Hello @arouiadib  
there is one error in this PR:

![Refactoring applyPercentageDiscount() in CartRow class #17687 after PR](https://user-images.githubusercontent.com/40635814/74658697-1bff9b00-5193-11ea-9874-7109ca8bdd94.png)


I applied a reduction of 50% on the cheapest article (1) whose price (2) is 14.28 € the reduction applied (3) is therefore 7.14 €. However in (4) the sum is calculated on the amount of the basket which is not good. The overall calculation is good, it's just the display in (4) which is incorrect. Can you review this point on your PR ?

2020-02-17 13:52 UTC, PierreRambaud requested changes
It's related to the CartRuleCalculator, it needs behat tests.

2020-02-17 21:40 UTC, arouiadib commented
Thank you very much @SD1982 for your time. 

The issue you are mentioning is a separate issue: ["The promo value is not correct in the cart summary & checkout summary"](https://github.com/PrestaShop/PrestaShop/issues/16842). I have created two PRs for that issue:

* [ PR1 : a possible quick fix.](https://github.com/PrestaShop/PrestaShop/pull/17502)
* [ PR2 : a possibly better fix](https://github.com/PrestaShop/PrestaShop/pull/17578)

I hope you guys confirm to me that PR1 is the bad approach, so that I close it. The second one needs behat tests (confirmed by @PierreRambaud ).

But this current PR, it needs no behat tests imho. It adds no functionality and it breaks no current tests. It just rewrite some few lines so that code is reused. The rewritten function has very limited and restrained dependency with existing code. And this same function is still needed in other places ( for example: to fix the promo value issue using PR2).

Sorry if I am long. I thank you very much guys for your quick feedbacks, time and support.

2021-07-16 13:18 UTC, PierreRambaud commented
Hi @arouiadib 
Is this PR still in Work In Progress?

2021-07-16 16:30 UTC, arouiadib commented
@PierreRambaud ,apprenrently not, but it is an old PR. I need  to check today  its status again.
I will be feedbacking. Thanks

2021-08-05 07:12 UTC, Progi1984 commented on src/Core/Cart/CartRow.php
> +    public function applyPercentageDiscount($percent, $onUnitPrice = false)
```suggestion
    public function applyPercentageDiscount($percent, bool $onUnitPrice = false)
```

2021-08-05 07:12 UTC, Progi1984 commented on src/Core/Cart/CartRow.php
> +        $priceUsed = (bool) $onUnitPrice ? $this->initialUnitPrice : $this->finalTotalPrice;
```suggestion
        $priceUsed = $onUnitPrice ? $this->initialUnitPrice : $this->finalTotalPrice;
```

2021-08-05 07:16 UTC, Progi1984 reviewed
Two small feedbacks but it's good job.

2021-08-06 07:23 UTC, Progi1984 approved these changes

2021-11-08 17:06 UTC, PierreRambaud commented
Hi @arouiadib ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.
As I said above, since it touches the CartCalculator system it requires unit tests and/or integration tests.

Thanks!

2021-11-08 17:06 UTC, closed without merging