Update product.js
PrestaShop/PrestaShop pull request #17800
Opened 2020-02-24 13:55 UTC by knbmedia

Why not a comma for product-variants like other lines?

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop / 1.7.7.x / 1.7.6.x
| Description?  | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc.
| Type?         | bug fix / improvement / new feature / refacto / critical
| Category?     | FO / BO / CO / IN / WS / TE
| BC breaks?    | Does it break backward compatibility? yes/no
| Deprecations? | Does it deprecate an existing feature? yes/no
| Fixed ticket? | [Issue](https://github.com/PrestaShop/PrestaShop/issues), please write "Fixes #[issue number]" here.
| How to test?  | Please indicate how to best verify that this PR is correct.

2020-02-24 14:01 UTC, PierreRambaud requested changes
Please add a proper title and description :wink:

2020-02-24 17:02 UTC, PululuK commented
Hi @knbmedia 

Check here please : 
https://github.com/PrestaShop/PrestaShop/pull/17457/files
https://github.com/PrestaShop/PrestaShop/pull/17701/files

Looks like everyone's working on this ...

2020-05-22 08:46 UTC, Progi1984 commented
@knbmedia Some news ? Or Do we close your PR ?

2020-05-25 09:54 UTC, NeOMakinG commented
https://github.com/PrestaShop/PrestaShop/blob/develop/themes/_core/js/product.js#L197

Looks like this has been fixed on develop (maybe by merging 1.7.6.x to it)

Closing the PR as it's not needed anymore. Thanks for your contribution anyway.

2020-05-25 09:54 UTC, closed without merging