Add Kurdish Locale to legacy-to-standard-locales.json
PrestaShop/PrestaShop pull request #17832
Opened 2020-02-25 19:42 UTC by SalarNazar

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop / 1.7.7.x / 1.7.6.x
| Description?  | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc.
| Type?         | bug fix / improvement / new feature / refacto / critical
| Category?     | FO / BO / CO / IN / WS / TE
| BC breaks?    | Does it break backward compatibility? yes/no
| Deprecations? | Does it deprecate an existing feature? yes/no
| Fixed ticket? | [Issue](https://github.com/PrestaShop/PrestaShop/issues), please write "Fixes #[issue number]" here.
| How to test?  | Please indicate how to best verify that this PR is correct.

2020-02-26 03:20 UTC, arouiadib requested changes
It seems ok to me, I only suggest linking this PR to this one #17826 ;-). Thanks

2020-02-26 10:52 UTC, PierreRambaud commented
Hi @SalarNazar and thanks for your contribution.
Can you please complete the description of your pull request?
Kinds regards

2020-03-16 10:31 UTC, Progi1984 approved these changes

2020-03-16 10:49 UTC, Progi1984 commented
Moved in #17826

2020-03-16 10:49 UTC, closed without merging