BO: Fix shipping price tax issue on order creation page
PrestaShop/PrestaShop pull request #17853
Opened 2020-02-26 17:21 UTC by matthieu-rolland

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | On order creation page, the total shipping price must be displayed without taxes, not tax included.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #17773
| How to test?  | Steps to reproduce the behavior:<br><br>- Go to Create Order migrated page<br>- Add a product, and a shipping (not free)<br>- See Summary : Shipping must be displayed without tax (tax exl.)

2020-02-27 09:16 UTC, matthieu-rolland commented
To sum up, this PR does two things:

1/ Add a new **totalShippingWithoutTaxes** to the CartSummary class. (there was only the total shipping price tax included before that).

2/ Use that value in create order page, in the order summary.

2020-02-27 10:13 UTC, matks submitted a review, later dismissed

2020-02-27 10:53 UTC, atomiix submitted a review, later dismissed

2020-03-11 10:50 UTC, nesrineabdmouleh commented
Hello @matthieu-rolland,

See Shipping : Shipping is displayed tax excl.
![image](https://user-images.githubusercontent.com/24647495/76409213-61784800-638e-11ea-98c4-592c74909349.png)

Thanks,

2020-03-17 10:31 UTC, matthieu-rolland commented
> Hello @matthieu-rolland,
> 
> See Shipping : Shipping is displayed tax excl.
> ![image](https://user-images.githubusercontent.com/24647495/76409213-61784800-638e-11ea-98c4-592c74909349.png)
> 
> Thanks,

thank you @nesrineabdmouleh ! it should be good now 👍

2020-03-17 16:34 UTC, matks commented on admin-dev/themes/new-theme/js/pages/order/create/summary-renderer.js
> +    console.log(cartSummary);
You pushed too fast 😄

2020-03-17 16:35 UTC, matks requested changes
See comment, `console.log()` to remove

2020-03-18 07:58 UTC, Progi1984 reviewed
OK. But look at @matks comment.

2020-03-24 09:39 UTC, matks submitted a review, later dismissed

2020-03-24 09:40 UTC, NeOMakinG submitted a review, later dismissed

2020-03-24 09:59 UTC, PierreRambaud submitted a review, later dismissed

2020-03-25 12:56 UTC, jolelievre approved these changes

2020-03-25 13:02 UTC, Progi1984 approved these changes

2020-03-25 13:30 UTC, Robin-Fischer-PS commented
Thanks @matthieu-rolland :)

2020-03-25 13:37 UTC, merged

2020-03-25 13:37 UTC, Progi1984 commented
Thanks @matthieu-rolland