Fix/17317
PrestaShop/PrestaShop pull request #17943
Opened 2020-03-03 13:59 UTC by MarkALeonard

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Show all images for a product and select the current combination image instead of only showing combination images. Also updates catalog product miniature to use new  catalogCover image so that all sizes and legend are available. Removes need to call Product::getCover() and $link->getImageLink() from the template.
| Type?         | bug fix / improvement
| Category?     | FO 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #17317
| How to test?  | Add additional images to a product. Select specific images for a combination. View the product in FO, all product images should be shown. Change a combination and the combination image should be selected in the thumbnails and shown as the main image. On the catalog listing the selected cover should be displayed and the correct alt atrribute assigned.

2020-03-10 14:13 UTC, Progi1984 submitted a review, later dismissed

2020-03-10 15:15 UTC, NeOMakinG submitted a review, later dismissed
Front looks fine for me

2020-03-16 08:26 UTC, PierreRambaud commented on src/Adapter/Presenter/Product/ProductLazyArray.php
> +                    if (isset($image['cover']) && null !== $image['cover']) {
```suggestion
                    if (isset($image['cover'])) {
```
It's the same thing

2020-03-16 08:27 UTC, PierreRambaud commented on src/Adapter/Presenter/Product/ProductLazyArray.php
> +                if (isset($image['cover']) && null !== $image['cover']) {
```suggestion
                if (isset($image['cover'])]) {
```

2020-03-16 08:28 UTC, PierreRambaud requested changes
Little thing for performance

2020-03-18 09:56 UTC, Progi1984 approved these changes

2020-03-18 12:40 UTC, NeOMakinG approved these changes

2020-03-25 08:24 UTC, PierreRambaud approved these changes

2020-04-03 09:37 UTC, matks approved these changes

2020-04-09 13:57 UTC, khouloudbelguith commented
Hi @MarkALeonard,

This PR is OK but we need to confirm this behavior from our Product team.
Ping @PrestaShop/prestashop-product-team what do you think?

**Without PR**
We have this behavior
![image](https://user-images.githubusercontent.com/16067358/78902310-ea5fcd80-7a79-11ea-96b9-bd317f3f2cd9.png)

**With PR**, we have all images are displayed
![image](https://user-images.githubusercontent.com/16067358/78902248-d320e000-7a79-11ea-9193-a1c206c76619.png)

**With this PR**, if we have more than one picture selected to a combination, we cannot distinguish which the second image for the combination selected
`For example, in the BO`
![image](https://user-images.githubusercontent.com/16067358/78902787-8ab5f200-7a7a-11ea-9f15-360438c8dc91.png)

`In the FO`
![image](https://user-images.githubusercontent.com/16067358/78902845-9ef9ef00-7a7a-11ea-855f-5e23bad550b9.png)

Waiting for PM validation.

Thanks!

2020-04-15 14:18 UTC, colinegin commented
Hello @MarkALeonard , thank you for your PR.
To be honest, I find it a bit weird for the user experience. It means that when looking at the different photos available for the product, it will automatically change the selected combination ? What if the combination is not available ? The photo is not displayed ? 
Wdyt @TristanLDD @prestascott ?

2020-04-20 08:51 UTC, prestascott commented
@MarkALeonard Thank you for your PR,

In my opinion, images are shown depending on the combination. I agree with @colinegin, we can't show 2 images with different colors of t-shirts (black and white) when a specific combination is selected (white t-shirt). Selecting colors shouldn't be done in the image gallery but only on the color section. In order to know which image appears, we need to keep the indication when the image is selected like we currently have in the FO.

2020-08-19 09:44 UTC, matks commented
It looks like this PR got stale following UX feedback. I consequently close it. Feel free to open it again if you come back 😉

2020-08-19 09:44 UTC, closed without merging

2020-10-12 17:16 UTC, theodiablo commented
This is exactly what I was looking for thanks a lot!

I am switching from Woocommerce, and this was the default dehaviour.

I think that when you have multiple photo per each variation, this feature might not be necessary, but if you only have one picture, you might want to display all images to fill a little the screen and show that there is more than one photo.

It would be awesome if this could be part of the core...

2025-09-04 15:01 UTC, vulpeep commented
> Here are two screenshots of a t-shirt product page from Mango website

On the Mango website, this is justified by the fact that they provide several photos of the item from different angles for each colour. Moreover, clothing brands like Mango, H\&M, Zara, Bershka display the product photo in full size right away, without a thumbnails block, which doesn't match the standard Prestashop UI. In my shop, when there's only one photo per colour, a thumbnails block with just one icon looks ridiculous. That's why I'd like to be able to show all combinations in the thumbnails. It doesn't have to be the default logic - a toggle would do.

- **Aliexpress** displays images of all combinations straight away.
- **Ebay** displays images of all combinations straight away. Additionally, when a corresponding thumbnail is selected, the product variant switches automatically.
- **Uniqlo** displays several general images for all combinations plus one image for the specifically selected combination.