Add HTML IDs and classes to View Customer BO page
PrestaShop/PrestaShop pull request #17965
Opened 2020-03-04 10:40 UTC by matks

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Add IDs to help testing team to create puppeeter tests
| Type?         | improvement
| Category?     | TE
| BC breaks?    | yes / no
| Deprecations? | yes / no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/17838
| How to test?  | I dont know, I guess no need for QA ?

2020-03-04 11:06 UTC, Progi1984 submitted a review, later dismissed

2020-03-04 13:50 UTC, PierreRambaud submitted a review, later dismissed

2020-03-04 14:02 UTC, NeOMakinG requested changes
Sorry ❤️

2020-03-04 14:02 UTC, NeOMakinG commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig
> +<div id="customer-addresses-card" class="card">
Is that ID necessary ? I mean is that component an unique component or it could be used anywhere else on the BO ?

2020-03-04 14:02 UTC, NeOMakinG commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig
>              <tr>
```suggestion
<tr class="customer-address">
```

So we can still construct our SCSS file using 

```
.customer-address {
  & &-company {}

  & &-name {}
  ...
}
```

Is the use of a table needed there ? That looks weird as it avoid this component being a reusable one (I know it's not related to the PR)

2020-03-04 14:02 UTC, NeOMakinG commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/bought_products.html.twig
>            <tr>
```suggestion
          <tr class="customer-bought-product">
```

2020-03-04 14:02 UTC, NeOMakinG commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/carts.html.twig
>            <tr>
```suggestion
          <tr class="customer-cart">
```

2020-03-04 14:02 UTC, NeOMakinG commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/carts.html.twig
> +<div id="customer-carts-card" class="card">
Are there many carts or only one ? If only one, then it should be :
```suggestion
<div id="customer-cart-card" class="card">
```

Also is this ID needed ? That could be a reusable component (if we extract the style from order_view stylesheet)

2020-03-04 14:02 UTC, NeOMakinG commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/discounts.html.twig
>            <tr>
```suggestion
          <tr class="customer-discount">
```

2020-03-04 14:02 UTC, NeOMakinG commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/groups.html.twig
>            <tr>
```suggestion
          <tr class="customer-group">
```

2020-03-04 14:02 UTC, NeOMakinG commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/last_connections.html.twig
>            <tr>
```suggestion
          <tr class="customer-last-connection">
```

2020-03-04 14:02 UTC, NeOMakinG commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/messages.html.twig
>          <tr>
```suggestion
        <tr class="customer-message">
```

2020-03-04 14:02 UTC, NeOMakinG commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/orders.html.twig
>                  <tr>
```suggestion
                <tr class="customer-order">
```

2020-03-04 14:02 UTC, NeOMakinG commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/personal_information.html.twig
> +<div id="customer-personal-informations-card" class="card">
```suggestion
<div id="customer-personal-informations-card" class="customer card">
```

so we can construct the stylesheet like :

```
.customer {
  & &-social-title {}

  & &-birthday {}

  ...
}
```

2020-03-04 14:02 UTC, NeOMakinG commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/personal_information.html.twig
>          </div>
Pretty sure all these IDs are unecessary, prefer using classes as they are properties of the `.customer` component

2020-03-04 14:02 UTC, NeOMakinG commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/sent_emails.html.twig
>            <tr>
```suggestion
          <tr class="customer-sent-email">
```

2020-03-04 14:02 UTC, NeOMakinG commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/viewed_products.html.twig
>              <tr>
```suggestion
            <tr class="customer-viewed-product">
```

2020-03-04 14:02 UTC, NeOMakinG commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/viewed_products.html.twig
>                  <a href="{{ product.productUrl }}">
I think we should add some consistency on our integration workflow, I would love to have a class on every childs like :

```suggestion
                <a href="{{ product.productUrl }}" class="customer-viewed-product-link">
```

2020-03-04 14:37 UTC, matks commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig
> +<div id="customer-addresses-card" class="card">
I put that ID here in order to allow QA team to target this div in puppeeter tests.
I guess I can put a class instead 🤔

2020-03-04 14:38 UTC, matks commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig
>              <tr>
Indeed it will go in another PR, but what would you put instead of a table ?

2020-03-04 14:38 UTC, matks commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/carts.html.twig
> +<div id="customer-carts-card" class="card">
Again I put that ID here in order to allow QA team to target this div in puppeeter tests.
I guess I can put a class instead 🤔

2020-03-04 19:19 UTC, NeOMakinG commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig
>              <tr>
Well don't mind, we'll check it out later, just think about the class (it's not related to that PR at all, that's a refacto)

2020-03-04 19:20 UTC, NeOMakinG commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/carts.html.twig
> +<div id="customer-carts-card" class="card">
You can still let it if that component is unique tbh

2020-03-13 15:27 UTC, matks commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/personal_information.html.twig
>          </div>
So
`<div id="customer-guest-status" class="row mb-1">`
should become
`<div class="customer-data customer-guest-status row mb-1">`

Is that right ?

2020-03-13 15:28 UTC, matks commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/carts.html.twig
> +<div id="customer-carts-card" class="card">
So
`<div id="customer-cart-card" class="card">`
⏬ 
`<div class="customer-cart-card card">`

OK ?

2020-03-13 16:20 UTC, NeOMakinG commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/personal_information.html.twig
>          </div>
Yes

2020-03-19 12:30 UTC, PierreRambaud commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/personal_information.html.twig
>          </div>
Prefer classes because these are block, and can be inject many times in the same page.

2020-03-23 13:28 UTC, matks commented
@NeOMakinG @PierreRambaud converted all IDs into classes, tried to make classes hierarchy meaningful for tables

2020-03-23 14:00 UTC, NeOMakinG approved these changes
I think that's way better

2020-03-27 10:46 UTC, matthieu-rolland approved these changes

2020-03-27 10:49 UTC, merged