Remove unused result in for statement
PrestaShop/PrestaShop pull request #17987
Opened 2020-03-04 22:22 UTC by Arman-Hosseini

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Remove unused result in for statement
| Type?         | refacto
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -

2020-03-05 09:39 UTC, Progi1984 commented
Thanks @Arman-Hosseini ! Could you target your PR to the develop branch ? Thanks

2020-03-11 09:53 UTC, matthieu-rolland approved these changes
@Progi1984   I think that since there will be an 1.7.6.5 anyway it's fine to do it on 1.7.6.x, it will be merged to 1.7.7 and develop eventually, what do you think?

2020-03-11 14:23 UTC, Progi1984 approved these changes

2020-03-11 14:28 UTC, PierreRambaud requested changes
AFAIK, it's not a regression, please target the develop branch

2020-03-11 15:44 UTC, closed without merging