Check if $field['value'] is set before display it
PrestaShop/PrestaShop pull request #18006
Opened 2020-03-05 17:17 UTC by Klemart3D

Update for https://github.com/PrestaShop/PrestaShop/pull/12213
To fix #12056

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Check if $field['value'] is set before display it
| Type?         | bug fix
| Category?     | WS
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #12213 
| How to test?  | Check API with NULL values in place of empty values into database. eg: try api/customers/1 URL with a "website" or "company" value set to NULL into DB in place of empty field.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/12213)

2020-03-10 16:26 UTC, Progi1984 submitted a review, later dismissed

2020-03-13 08:41 UTC, PierreRambaud commented on classes/webservice/WebserviceOutputXML.php
> +            if (!empty($field['value'])) {
```suggestion
            if (array_key_exists('value', $field)) {
```

2020-03-13 08:42 UTC, PierreRambaud requested changes
Do not use empty, the value can be false, 0, null

2020-03-13 08:48 UTC, Klemart3D commented
> Do not use empty, the value can be false, 0, null
@PierreRambaud It was your suggestion:
https://github.com/PrestaShop/PrestaShop/pull/12213/files/2e87ccdc94a1228acdf9042c843b33a36f377343#r249060236

2020-03-13 10:38 UTC, PierreRambaud commented
> > Do not use empty, the value can be false, 0, null
> 
> @PierreRambaud It was your suggestion:
> https://github.com/PrestaShop/PrestaShop/pull/12213/files/2e87ccdc94a1228acdf9042c843b33a36f377343#r249060236

Lol :sweat_smile: I read it too fast last time and don't check the original behaviour. My bad :/

2020-03-13 10:41 UTC, PierreRambaud approved these changes

2020-03-13 10:44 UTC, Progi1984 approved these changes

2020-04-03 09:40 UTC, matks approved these changes

2020-04-20 18:45 UTC, khouloudbelguith commented
Hi @Klemart3D,

Your PR is OK :heavy_check_mark: 
But, in the develop branch, I can't reproduce the issue.

Ping @PrestaShop/prestashop-core-developers can we accept this PR? 

Thanks!

2020-04-21 08:47 UTC, PierreRambaud commented
@khouloudbelguith Yes, only to be consistent with the whole method content :)

2020-04-21 09:53 UTC, merged

2020-04-21 09:54 UTC, matks commented
Thank you @Klemart3D