Modify the quantity input type from text type to number type
PrestaShop/PrestaShop pull request #18254
Opened 2020-03-21 16:56 UTC by arouiadib

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | This PR is a suggestion of the use of HTML5 number input type instead of text input type for quantity input. This input type has some advantages for front and back validation as discussed [here.](https://github.com/PrestaShop/PrestaShop/pull/18200)
| Type?         | bug fix / improvement / new feature / refacto / critical
| Category?     | BO 
| BC breaks?    |no
| Deprecations? | no
| Fixed ticket? |  Fixes nothing, but will help fixing another issue number 18031
| How to test?  | Go to migrated order view page and add a product to order.

2020-03-21 18:16 UTC, Arman-Hosseini approved these changes

2020-03-23 08:24 UTC, NeOMakinG approved these changes

2020-03-24 17:04 UTC, PierreRambaud requested changes
The type Number must be used in the FormType and not in the template :thinking:

2020-03-24 20:42 UTC, arouiadib commented
Hello @PierreRambaud , the `numberType` is already used in form building, but I don't know why it is not enough to make it work.  When adding it here in template, it works! This is similar to other situation (add discount in order view). I need some time to inspect more about this question because I don't understand what is happening! Thank you very much for raising this point.

2020-03-25 10:34 UTC, PierreRambaud commented
@arouiadib Thanks to you for helping us :wink:

2020-03-25 21:57 UTC, arouiadib commented
I close this PR because its only purpose was to test a server-side validation while the front-end one doesn't exist. No longer useful.

2020-03-25 21:57 UTC, closed without merging