Update Product.php
PrestaShop/PrestaShop pull request #18343
Opened 2020-03-27 13:26 UTC by jcvoyeux

Add product_carriers in webservices

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop / 1.7.7.x
| Description?  | Add specific product_carriers in webservice products
| Type?         | improvement
| Category?     | WS 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #{18277}.
| How to test?  | https:/yoursite/api/products/aidproduct

2020-03-27 13:30 UTC, PierreRambaud commented
Hi and thanks for your contribution.
Before beginning the review, you need to add a proper title, good description, fill the table correctly, fix the CI (using php-cs-fixer) ;)

Kind regards

2020-03-27 13:31 UTC, PierreRambaud requested changes
See comment

2020-03-27 13:44 UTC, jcvoyeux commented
Hello,

I see there was a conflict.
I resolved it but could you verify everything is OK ?
Thank you

Take care of you 😉

________________________________
De : GoT <notifications@github.com>
Envoyé : vendredi 27 mars 2020 14:31
À : PrestaShop/PrestaShop <PrestaShop@noreply.github.com>
Cc : jcvoyeux <jcvoyeux@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [PrestaShop/PrestaShop] Update Product.php (#18343)


@PierreRambaud requested changes on this pull request.

See comment

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/PrestaShop/PrestaShop/pull/18343#pullrequestreview-382857356>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ALVWS35ZU3ZHVQFFVDJWB33RJSTCZANCNFSM4LVAEFCQ>.

2020-03-30 15:12 UTC, Progi1984 commented on classes/Product.php
> +            ],
```suggestion
            'carriers' => [
        		'resource' => 'carrier',
                'getter' => 'getWsCarriers',
                'setter' => 'setWsCarriers',
                'fields' => [
                    'id' => ['required' => true],
                    'id_shop' => ['required' => true],
                ],
            ],
```

2020-03-30 15:12 UTC, Progi1984 commented on classes/Product.php
> +    ];
```suggestion
    ];
```

2020-03-30 15:13 UTC, Progi1984 commented on classes/Product.php
> +	* Get the liste of specific carriers for a product
```suggestion
	* Get the list of specific carriers for a product
```

2020-03-30 15:13 UTC, Progi1984 commented on classes/Product.php
> +	* Don't know if I must limit to the default shop ?? (AND pc.id_shop = ' . (int) $this->id_shop_default)
```suggestion
	* Don't know if I must limit to the default shop ?? (AND pc.id_shop = ' . (int) $this->id_shop_default)
```

Think MultiShop ;)

2020-03-30 15:14 UTC, Progi1984 commented on classes/Product.php
> +	* Don't know if I must limit to the default shop ?? (pc.id_shop = ' . (int) $this->id_shop_default)
Think MultiShop

2020-03-30 15:14 UTC, Progi1984 commented on classes/Product.php
> +	* Delete old carrieres
```suggestion
	* Delete old carriers
```

2020-03-30 15:14 UTC, Progi1984 commented on classes/Product.php
> +	* For each carrierr
```suggestion
	* For each carrier
```

2020-03-30 15:15 UTC, Progi1984 commented on classes/Product.php
> +		Db::getInstance()->execute('DELETE FROM `' . _DB_PREFIX_ . 'product_carrier`
```suggestion
		Db::getInstance()->execute(
		    'DELETE FROM `' . _DB_PREFIX_ . 'product_carrier`
```

2020-03-30 15:29 UTC, jcvoyeux commented
Must I do something ?
Message "Process completed with exit code 8" ??

2020-03-31 06:56 UTC, Progi1984 commented
@jcvoyeux You can try in local with this command line : `./vendor/bin/php-cs-fixer fix --dry-run --diff`

2020-05-26 14:00 UTC, colinegin commented
Hello @jcvoyeux ,

Are you able to fix your PR according to @Progi1984 's comments ?

2021-01-21 14:43 UTC, PierreRambaud commented
Hi @jcvoyeux ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2021-01-21 14:43 UTC, closed without merging