Avoid timeout in image regeneration
PrestaShop/PrestaShop pull request #18405
Opened 2020-04-01 06:51 UTC by JBWModules

In my XAMPP test system ini_set returns false and ini_get returns 0 even though the values are set (permission issue). This is causing unneccessary timeout on image regeneration after 4 seconds

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop / 1.7.7.x
| Description?  | In my XAMPP test system ini_set returns false and ini_get returns 0 even though the values are set (permission issue). This is causing unneccessary timeout on image regeneration after 4 seconds
| Type?         | bug fix / improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #{issue number here}.
| How to test?  | Please indicate how to best verify that this PR is correct.

2020-04-01 09:55 UTC, matthieu-rolland commented
Hi @JBWModules, thank you for your contribution

It seems that your modification is not passing our PHP coding Standards test, could you please run this command from the root of your prestashop?

``` php ./vendor/bin/php-cs-fixer fix controllers/admin/AdminImagesController.php```

and push the modification please?

2020-04-01 09:56 UTC, matthieu-rolland requested changes
Hi @JBWModules, thank you for your contribution

It seems that your modification is not passing our PHP coding Standards test, could you please run this command from the root of your prestashop?

``` php ./vendor/bin/php-cs-fixer fix controllers/admin/AdminImagesController.php```

and push the modification please?

2020-04-07 06:48 UTC, Progi1984 commented
@JBWModules  Thank you for your contribution. :hugs: 

Could you explain in an issue your initial bug for this PR (or may be link to an issue) ?
Could you give us a scenario which permits to test the bug before and after this PR ?

Thanks :+1:

2020-04-07 07:07 UTC, JBWModules commented
> 
> 
> @JBWModules Thank you for your contribution. 🤗
> 
> Could you explain in an issue your initial bug for this PR (or may be link to an issue) ?
> Could you give us a scenario which permits to test the bug before and after this PR ?
> 
> Thanks 👍

As described there might by scenarios (e.g. in my XAMPP env) where ini_set returns false and ini_get returns 0 - in this case the image regeneration will time out after 4 seconds (see coding)

2020-04-07 07:12 UTC, Progi1984 commented
> > @JBWModules Thank you for your contribution. hugs
> > Could you explain in an issue your initial bug for this PR (or may be link to an issue) ?
> > Could you give us a scenario which permits to test the bug before and after this PR ?
> > Thanks +1
> 
> As described there might by scenarios (e.g. in my XAMPP env) where ini_set returns false and ini_get returns 0 - in this case the image regeneration will time out after 4 seconds (see coding)

@JBWModules Please create a separate issue. That permits to our @PrestaShop/prestashop-product-team to prioritize issues in versions. Thanks :)

2021-01-21 14:33 UTC, PierreRambaud commented
Hi @JBWModules ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2021-01-21 14:33 UTC, closed without merging