Add link to good first issue label
PrestaShop/PrestaShop pull request #18501
Opened 2020-04-07 14:22 UTC by LouiseBonnard

In the _Contributing_ section of the RM:

- add a link to our **good first issues** to be picked
- update to **75** the number of translation projects on Crowdin

2020-04-07 14:26 UTC, Progi1984 approved these changes

2020-04-07 19:29 UTC, arouiadib approved these changes

2020-04-08 07:42 UTC, NeOMakinG approved these changes

2020-04-08 08:35 UTC, PierreRambaud requested changes
Please complete the description as usual

2020-04-20 14:07 UTC, PierreRambaud approved these changes

2020-04-22 07:53 UTC, merged

2020-04-22 07:53 UTC, Progi1984 commented
Thank you @LouiseBonnard