Show confirmation modal before deleting order messages
PrestaShop/PrestaShop pull request #18641
Opened 2020-04-15 13:32 UTC by zuk3975

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Add confirmation modal to be shown before deleting order messages in Customer Service > Order messages. Add in both bulk and single row action. Technically it modifies SubmitRowAction same as already modified SubmitBulkAction to allow optional params for Modal.
| Type?         | bug fix 
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | #18415 
| How to test?  | Go to Customer services > Order messages and try to delete order message in single row and bulk actions. You should see following modals to confirm your action. If you press Delete, your action should be processed, else it should not delete your selection. ![Screenshot from 2020-04-15 16-26-14](https://user-images.githubusercontent.com/31609858/79342828-4cb34500-7f36-11ea-973e-d52119ccf5c0.png)![Screenshot from 2020-04-15 16-26-36](https://user-images.githubusercontent.com/31609858/79342833-4de47200-7f36-11ea-8ad7-f6a530a7787a.png)

2020-04-15 14:00 UTC, Progi1984 commented on admin-dev/themes/new-theme/js/pages/order_message/index.js
> +import SubmitBulkActionExtension from '../../components/grid/extension/submit-bulk-action-extension';
```suggestion
import SubmitBulkActionExtension from '@components/grid/extension/submit-bulk-action-extension';
```

2020-04-15 14:02 UTC, jolelievre requested changes
Hi @zuk3975 
Sorry but the modal on row action is not in the scope of 177, it's considered a new feature and was not ready before feature freeze. So only modal on bulk action are integrated in 177

The integration for 178 of the row action has stared though, it's based on a similar trait as `BulkDeleteActionTrait` to easily add the action and only update the grid definition

2020-04-15 14:02 UTC, jolelievre commented on src/Core/Grid/Definition/Factory/OrderMessageGridDefinitionFactory.php
> +                        'modal_options' => new ModalOptions([
You should use the `BulkDeleteActionTrait::buildBulkDeleteAction` here, it's easier and more consistent with other definitions

2020-04-16 06:36 UTC, zuk3975 commented
> Hi @zuk3975
> Sorry but the modal on row action is not in the scope of 177, it's considered a new feature and was not ready before feature freeze. So only modal on bulk action are integrated in 177
> 
> The integration for 178 of the row action has stared though, it's based on a similar trait as `BulkDeleteActionTrait` to easily add the action and only update the grid definition

ok, I've reverted my changes for single row. 
Also resolved all other feedbacks.

2020-04-16 08:34 UTC, Progi1984 approved these changes

2020-04-16 10:48 UTC, jolelievre approved these changes

2020-04-16 12:37 UTC, SD1982 commented
This PR correctly add the order message bulk delete confirmation modal. Thanks @zuk3975

2020-04-16 12:45 UTC, merged

2020-04-16 12:45 UTC, Progi1984 commented
Thanks @zuk3975