Changelog for 1.7.6.5
PrestaShop/PrestaShop pull request #18659
Opened 2020-04-16 08:01 UTC by sowbiba

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Changelog for 1.7.6.5
| Type?         | improvement
| Category?     | CO

2020-04-16 08:03 UTC, eternoendless commented on docs/CHANGELOG.txt
> +    - #18013: Add PululuK as a contributor (by @LouiseBonnard)
This line can be deleted I think

2020-04-16 08:03 UTC, PierreRambaud requested changes
We need to update dependencies first

2020-04-16 08:17 UTC, Progi1984 submitted a review, later dismissed

2020-04-17 10:01 UTC, sowbiba commented on docs/CHANGELOG.txt
> +  - Security fix:
I will add the CVE in front of each fix

2020-04-17 11:43 UTC, jolelievre submitted a review, later dismissed

2020-04-17 11:47 UTC, PierreRambaud submitted a review, later dismissed

2020-04-17 11:54 UTC, Progi1984 submitted a review, later dismissed

2020-04-17 12:48 UTC, Progi1984 approved these changes

2020-04-17 13:06 UTC, jolelievre approved these changes

2020-04-17 13:50 UTC, eternoendless approved these changes

2020-04-17 13:50 UTC, merged

2020-04-17 13:50 UTC, eternoendless commented
Thank you @sowbiba