Update Changelog and Contributors for beta 177
PrestaShop/PrestaShop pull request #18854
Opened 2020-04-27 17:35 UTC by jolelievre

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Update Changelog and Contributors for beta 177
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Part of #18647
| How to test?  | ~

2020-04-29 12:59 UTC, NeOMakinG submitted a review, later dismissed

2020-05-12 15:55 UTC, eternoendless requested changes
Please apply my change, then squash your commits (so we can tag it)

2020-05-12 15:55 UTC, eternoendless commented on docs/CHANGELOG.txt
> +#   v1.7.7.0-beta.1 - (2020-04-27)
```suggestion
#   v1.7.7.0-beta.1 - (2020-05-12)
```

2020-05-13 08:32 UTC, eternoendless approved these changes

2020-05-13 09:02 UTC, eternoendless commented
Thanks @jolelievre

2020-05-13 09:03 UTC, merged