FO: Refresh checkout hook
PrestaShop/PrestaShop pull request #18911
Opened 2020-04-30 11:12 UTC by idnovate

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Refresh `displayCheckoutSummaryTop` hook when any action is done in the checkout, like adding/removing a voucher
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Develop a module hooked at displayCheckoutSummaryTop. Display current timestamp, for example. Apply a voucher. This area should be updated with a new timestamp.

2020-04-30 14:34 UTC, Progi1984 commented on controllers/front/CartController.php
> +            'hook_checkout_summary_top' => Hook::exec('displayCheckoutSummaryTop')
```suggestion
            'hook_checkout_summary_top' => Hook::exec('displayCheckoutSummaryTop'),
```

2020-04-30 14:35 UTC, Progi1984 approved these changes

2020-05-04 12:35 UTC, PierreRambaud approved these changes

2020-05-20 11:48 UTC, SD1982 commented
Hello @idnovate Can you please  provide us  a compatible module so that we can test your PR ?

2020-05-20 12:06 UTC, idnovate commented
[displaycheckoutsummarytop.zip](https://github.com/PrestaShop/PrestaShop/files/4656692/displaycheckoutsummarytop.zip)

2020-06-09 08:10 UTC, SD1982 commented
Hi @idnovate  I have an error when trying to install the module that you provided me : 
https://drive.google.com/file/d/1yl7-jpy6ljmKu8loULfCeqmf347IVdEN/view?usp=sharing

Can you check this please ?

2020-06-09 09:05 UTC, idnovate commented
My apologies, it was a case sensitive problem.

[displaycheckoutsummarytop.zip](https://github.com/PrestaShop/PrestaShop/files/4751091/displaycheckoutsummarytop.zip)

2020-06-09 12:17 UTC, SD1982 commented
Hi @idnovate  The time stamp is correctly updated for the first applied discount but if we apply a second voucher it's not updated 
https://drive.google.com/file/d/1GfapdvsBWPDKmIfJoSuFmY0JzwAN_8U7/view?usp=sharing

2020-06-09 14:34 UTC, idnovate commented
Ok I see! The problem is that `<div class="hook_checkout_summary_top"> https://github.com/PrestaShop/PrestaShop/pull/18911/files#diff-463a9f63ea088495dd06250ef7cbaec6R27 is lost when executing JS https://github.com/PrestaShop/PrestaShop/pull/18911/files#diff-cc1024c22d27236739edaef574de3d9bR61 with the new content. 
Then when a new request is done, JS doesn't find the selector and is not replaced again, only once.

The solution would be to create a new file like https://github.com/PrestaShop/PrestaShop/blob/b2a7e9e448b22ec174fcb0e907b4276b6f9abcf9/themes/classic/templates/checkout/_partials/cart-summary.tpl#L42-L44 with this content:

```
<div class="hook_checkout_summary_top">
    {hook h='displayCheckoutSummaryTop'}
</div>
```

Is it ok if I name this file as `checkout/_partials/cart-hook-checkout-summary-top.tpl`?

2020-06-09 15:17 UTC, SD1982 commented
> Is it ok if I name this file as `checkout/_partials/cart-hook-checkout-summary-top.tpl`?

@PrestaShop/prestashop-core-developers What do you think ?

2020-06-12 13:06 UTC, matthieu-rolland commented
@idnovate I would not necessarily mention "hook" in the template name, `cart-checkout-summary-top.tpl` should be fine, do you agree @Progi1984 , @PierreRambaud  ?

2020-06-12 13:16 UTC, PierreRambaud requested changes
Just notice the class name should be `checkout-summary-top`, my bad, could you change it please?

2020-06-15 10:35 UTC, idnovate commented
@PierreRambaud 

All partial templates and block names start with `cart` but hook is called `displayCheckoutSummaryTop`.

What do you think about `cart-summary-top`?

2020-06-15 13:46 UTC, PierreRambaud commented
> @PierreRambaud
> 
> All partial templates and block names start with `cart` but hook is called `displayCheckoutSummaryTop`.
> 
> What do you think about `cart-summary-top`?

Let's go for `cart-summary-top` :+1:

2020-06-15 15:01 UTC, idnovate commented
https://github.com/PrestaShop/PrestaShop/pull/19762

2020-06-15 15:01 UTC, closed without merging