BO Product Controller: Virtual product download link will not download the active file.
PrestaShop/PrestaShop pull request #18972
Opened 2020-05-05 08:05 UTC by MLE-Coding

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | The bug is at the backoffice products detail page at virtual products. You edit a virtual product and add a new download file to this product, you are able to download this file (see screenshot) ![image](https://user-images.githubusercontent.com/63242596/81045831-5259d600-8eb7-11ea-859a-3b8b24f6da80.png)
but if there are more than one file downloads available for this product. this download link will only get the first file and not the active one.
| Type?         | bug fix 
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Add a virtual product. Add a File Download to this product. add another file download to this product to replace the first one. Try to download the file with the link. you will get the first download file and not the last (active) download.

2020-05-06 13:05 UTC, Progi1984 commented on src/PrestaShopBundle/Controller/Admin/VirtualProductController.php
> +                'active' => 1
```suggestion
                'active' => 1,
```

2020-05-06 13:07 UTC, Progi1984 approved these changes

2020-05-20 09:11 UTC, matthieu-rolland requested changes
Thank you for your contribution @MLE-Coding :)

I see no problem with your solution, but could you please create an issue explaining the bug:  https://github.com/PrestaShop/PrestaShop/issues/new?template=bug_report.md

And then link the issue in the description of the PR, so that our product team can follow its evolution, this is part of our process, thank you ! ;)

2020-05-26 06:36 UTC, Progi1984 commented
Ping @MLE-Coding

2020-06-04 06:56 UTC, MLE-Coding commented
Issue to this pull request: https://github.com/PrestaShop/PrestaShop/issues/19553

2020-06-12 13:08 UTC, matthieu-rolland approved these changes

2020-06-12 13:09 UTC, matthieu-rolland commented
thank you for making the issue and linking your PR @MLE-Coding, your PR can now be tested by the QA team 👍

2020-06-15 11:50 UTC, SD1982 commented
Hi @MLE-Coding I have tried to reproduce the issue you describe here #19553 but I have not been able to reproduce.
https://drive.google.com/file/d/1BOEbYXFYgagmLMxHLSXvlR-AowpNXecP/view?usp=sharing

2020-06-15 12:01 UTC, MLE-Coding commented
Hi, yea you have done the steps right. But please try to download the product **from the backoffice** products page (in your video at 1:33). You will get the first pdf file instead of the last.

2020-06-16 06:16 UTC, Progi1984 commented
> Hi @MLE-Coding I have tried to reproduce the issue you describe here #19553 but I have not been able to reproduce.
> https://drive.google.com/file/d/1BOEbYXFYgagmLMxHLSXvlR-AowpNXecP/view?usp=sharing

The scenario has not been followed.

You : Remove the file
Scenario : Add a second file and disable the first

2020-06-16 09:03 UTC, SD1982 commented
Hi @Progi1984 and @MLE-Coding 

@Progi1984 
> The scenario has not been followed.
> 
> You : Remove the file
> Scenario : Add a second file and disable the first

Yes i know but in this part of a virtual product creation it's not possible to add another file without deleting the first one and @MLE-Coding confirm that i have correctly reproduce the scénario 

> Hi, yea you have done the steps right. 

@MLE-Coding 
> But please try to download the product **from the backoffice** products page (in your video at 1:33). You will get the first pdf file instead of the last.

Yes i have tried in this way too but even in this way i can't reproduce : 
https://drive.google.com/file/d/1o71Z_eox70BrtKOifRYBKwyYE8waMMp_/view?usp=sharing 

Did i miss something ?

2020-06-16 09:07 UTC, MLE-Coding commented
Oh ok, I'm sorry. 
Maybe this bug occurs only in my shop installation. I have to checkt this.
So we can close this issue.

2020-06-17 05:55 UTC, Progi1984 commented
@MLE-Coding & @SD1982 I reopen because I have  reproduced the problem as @florine2623 asked me it

2020-06-17 06:27 UTC, Progi1984 commented
@MLE-Coding & @SD1982 Sorry. I have made an error ;)

2020-06-17 06:27 UTC, closed without merging