Separated Symfony cache per HTTP_HOST
PrestaShop/PrestaShop pull request #19018
Opened 2020-05-06 18:57 UTC by Flower7C3

When multistore is active and different stores has same translation key with different value it should show different value fore each store.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop / 1.7.7.0
| Description?  | See in #15346.
| Type?         | bug fix / improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #15346.
| How to test?  | Enable multistore and modify translations.

2020-05-07 06:52 UTC, Progi1984 approved these changes

2020-05-07 09:24 UTC, PierreRambaud requested changes
There is problem when mutlishop is active with same host name and different virtual path. :thinking:

2020-05-07 10:07 UTC, Flower7C3 commented
@PierreRambaud do You know how to detect mutlishop virtual path in `defines.inc.php` file?

2020-05-07 10:20 UTC, PierreRambaud commented
> @PierreRambaud do You know how to detect mutlishop virtual path in `defines.inc.php` file?

I think the cache directory is correct, the problem must be fixed elsewhere :thinking:

2020-05-26 06:35 UTC, Progi1984 commented
Ping @Flower7C3

2020-05-26 07:23 UTC, Flower7C3 commented
@Progi1984 sorry, now I have no idea how to fix it elsewhere.

2020-09-15 16:16 UTC, matks commented
Hi, [following our review guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/) "Pull Requests may be closed after 30 days of inactivity following a request for modifications".

Unfortunately it seems we failed to find a proper way to address the issue 😢  so I close the PR

Please note this does not mean it's a final "won't merge" 😉 if you come back we can reopen it

Thank you for the contribution

2020-09-15 16:16 UTC, closed without merging