avoid showing 0 in Quantity field when minimal_quantity =0
PrestaShop/PrestaShop pull request #19116
Opened 2020-05-13 15:44 UTC by taoufiqaitali

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  |  when minimal_quantity =0 it show 0 in quantity field on product page, but add product to cart when you click, this fix, will show 1 when minimal quantity =0
| Type?         | bug fix 
| Category?     | FO 
| BC breaks?    | no
| Deprecations? | no
| How to test?  | edit product, set minimal quantity = 0, then go to product page on front you should see 0 in quantity field

![image](https://user-images.githubusercontent.com/22837086/81834499-86c13800-9530-11ea-9bf1-ca11e9d372bf.png)
![image](https://user-images.githubusercontent.com/22837086/81834572-a193ac80-9530-11ea-93f4-8f0d58edcb4b.png)

2020-05-13 16:29 UTC, PierreRambaud commented
Hi and thanks for your pull request.

Could you please create an issue?

Kind regards

2020-05-20 11:03 UTC, taoufiqaitali commented
> Hi and thanks for your pull request.
> 
> Could you please create an issue?
> 
> Kind regards

issue created #19233

2020-05-20 12:28 UTC, NeOMakinG requested changes
Hello, thanks for your contribution, I submit 2-3 easy changes in order to keep consistency in our codebase regarding indentation and code spacing!

Thanks

2020-05-20 12:28 UTC, NeOMakinG commented on themes/classic/templates/catalog/_partials/product-add-to-cart.tpl
> +
```suggestion
            {else}
              value="1"
              min="1"
            {/if}
            class="input-group"
```

2020-05-20 12:28 UTC, NeOMakinG commented on themes/classic/templates/catalog/_partials/product-add-to-cart.tpl
>              min="{$product.minimal_quantity}"
```suggestion
              min="{$product.minimal_quantity}"
```

2020-05-20 12:28 UTC, NeOMakinG commented on themes/classic/templates/catalog/_partials/product-add-to-cart.tpl
>              value="{$product.quantity_wanted}"
```suggestion
              value="{$product.quantity_wanted}"
```

2020-05-22 06:50 UTC, Progi1984 approved these changes

2020-05-22 08:42 UTC, PierreRambaud approved these changes

2020-05-22 14:33 UTC, taoufiqaitali commented
> Hello, thanks for your contribution, I submit 2-3 easy changes in order to keep consistency in our codebase regarding indentation and code spacing!
> 
> Thanks

@NeOMakinG can you check and approve,thanks

2020-05-27 00:36 UTC, kpodemski commented
Maybe it would be better to make proper changes here:
https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Presenter/Product/ProductLazyArray.php#L727

?

globally, not just on product page

2020-05-27 07:39 UTC, NeOMakinG approved these changes
As my team approved, unblocking the PR

but @PrestaShop/prestashop-core-developers wdyt of the last comment?

2020-05-27 09:17 UTC, taoufiqaitali commented
> Maybe it would be better to make proper changes here:
> https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Presenter/Product/ProductLazyArray.php#L727
> 
> ?
> 
> globally, not just on product page

@kpodemski  if we do it globaly maybe it will affect some other functionalities like this condition that enable or disable add to cart 
![image](https://user-images.githubusercontent.com/22837086/83001090-27b8f400-a003-11ea-868b-0678b8044c43.png)

2020-06-03 08:09 UTC, kpodemski commented
@taoufiqaitali i understand, but lets be honest, minimal quantity should never be below 0, this condition is invalid, or rather not precise enough

2020-06-04 08:50 UTC, merged

2020-06-04 08:50 UTC, Progi1984 commented
Thanks @taoufiqaitali