Add breadcrumb to Stores & Supplier front controllers
PrestaShop/PrestaShop pull request #19195
Opened 2020-05-18 17:14 UTC by nprokopenko202

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop / 1.7.7.x
| Description?  | Add missing breadcrumbs in Stores and Suppliers pages in Front-office
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #17131.

2020-05-18 17:18 UTC, Matt75 commented
Welcome 😉

2020-05-18 17:45 UTC, Matt75 requested changes
Make php-cs-fixer 🟢

2020-05-18 17:45 UTC, Matt75 commented on controllers/front/SitemapController.php
> +            'url' => $this->context->link->getPageLink('sitemap', true)
```suggestion
            'url' => $this->context->link->getPageLink('sitemap', true),
```

2020-05-18 17:45 UTC, Matt75 commented on controllers/front/StoresController.php
> +            'url' => $this->context->link->getPageLink('stores', true)
```suggestion
            'url' => $this->context->link->getPageLink('stores', true),
```

2020-05-18 17:45 UTC, Matt75 commented on controllers/front/StoresController.php
> +
```suggestion

```

2020-05-18 18:06 UTC, Matt75 requested changes

2020-05-18 18:06 UTC, Matt75 commented on controllers/front/StoresController.php
> +        return $breadcrumb;
```suggestion
        ];

        return $breadcrumb;
```

2020-05-18 18:14 UTC, Matt75 approved these changes

2020-05-18 18:15 UTC, nprokopenko202 commented
Hello, @Matt75 Thanks a lot!

2020-05-19 06:33 UTC, Progi1984 commented
@ Thank you for your contribution. :hugs: 

Could you give us a scenario which permits to test the bug before and after this PR ?

Thanks :+1:

2020-05-19 06:35 UTC, Progi1984 approved these changes

2020-05-19 06:38 UTC, clotaire202 commented
> @ Thank you for your contribution. hugs
> 
> Could you give us a scenario which permits to test the bug before and after this PR ?
> 
> Thanks +1

It partially fix #17131

So go to page :
* /index.php?controller=stores > Now there is a breadcrumb
* /index.php?controller=sitemap > Now there is a breadcrumb

2020-05-19 06:42 UTC, Progi1984 commented
Thnaks @clotaire202  / @nprokopenko202

2020-05-19 08:31 UTC, PierreRambaud approved these changes

2020-05-20 09:05 UTC, matthieu-rolland approved these changes

2020-05-20 10:28 UTC, SD1982 commented
LGTM Thanks @nprokopenko202

2020-05-20 12:15 UTC, merged

2020-05-20 12:15 UTC, Progi1984 commented
Thanks @nprokopenko202