add caching on Theme Yaml parsing
PrestaShop/PrestaShop pull request #19231
Opened 2020-05-20 10:29 UTC by Kioob

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop / 1.7.7.x
| Description?  | add caching on Theme Yaml parsing
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #{issue number here}.
| How to test?  | with xhprof / blackfireIO, no more Yaml classes loaded (once in cache)

2020-05-20 13:10 UTC, matks commented
@Kioob Hi ! So if I understand correctly, you use the built-in cache from YamlParser ? Which is why this code is enough to get performance gains ?

Also could you please run PHP-CS-Fixer 😉else our CI is not happy

2020-05-20 13:28 UTC, Progi1984 commented on src/Core/Addon/Theme/Theme.php
>  use AbstractAssetManager;
```suggestion
use AbstractAssetManager;
use Configuration;
```

2020-05-20 13:29 UTC, Progi1984 commented on src/Core/Addon/Theme/Theme.php
> +            $yamlParser = new YamlParser((new \Configuration())->get('_PS_CACHE_DIR_'));
```suggestion
            $yamlParser = new YamlParser((new\Configuration())->get('_PS_CACHE_DIR_'));
```

2020-05-20 13:31 UTC, Progi1984 commented on src/Core/Addon/Theme/Theme.php
> -use Symfony\Component\Yaml\Yaml;
```suggestion
use PrestaShop\PrestaShop\Core\Util\File\YamlParser;
use Shudrum\Component\ArrayFinder\ArrayFinder;
```

2020-05-20 14:17 UTC, Kioob commented
> @Kioob Hi ! So if I understand correctly, you use the built-in cache from YamlParser ? Which is why this code is enough to get performance gains ?

Yes. You already have a working built-in cache. I suppose this Yaml file was forgotten.


> Also could you please run PHP-CS-Fixer winkelse our CI is not happy

Sorry ! I'm not a Prestashop developer, neither a developer.

Thanks @Progi1984 for fixes.

2020-05-20 15:42 UTC, matks commented
@Kioob did the fixes for you 😊since you're not a PHP developer

Travis is happy now ❤️

2020-05-20 15:42 UTC, matks approved these changes

2020-05-22 06:35 UTC, Progi1984 submitted a review, later dismissed

2020-05-22 06:40 UTC, matks commented
@Progi1984 I think this PR should be validated by a developer, because QA does not have profiling tools. Wdyt ?

2020-05-22 06:41 UTC, Progi1984 commented
If @PrestaShop/prestashop-qa valid this, I'm OK ;)

2020-05-25 09:27 UTC, SimonGrn commented
Yes, we'll leave this one out for you guys, we don't have BlackFire or any profiling tool for that matter.
Thanks !

2020-06-08 08:51 UTC, SD1982 commented
> If @PrestaShop/prestashop-qa valid this, I'm OK ;)

Hi @PrestaShop/prestashop-core-developers It's OK for us we let you manage this PR ! 
Thank you !

2020-06-09 07:16 UTC, Progi1984 commented
@matks You have the "GO !" ;)

2020-06-17 13:53 UTC, matthieu-rolland submitted a review, later dismissed

2020-06-17 14:06 UTC, matks commented
I need to find enough time to setup Blackfire 😅 

If anybody wants to "play" with Blackfire: be my guest

To validate this PR we would need 2 snapshots of Blackfire: one before and one after

2020-06-26 09:01 UTC, matks commented
I am trying to use Blackfire to validate this PR but my calls do not appear in the graph.

Mmmm ... it might mean the resources optimization is so small it does not appear 😄 because so much bigger resource consumption happens around

2020-06-26 09:10 UTC, matks commented
> I am trying to use Blackfire to validate this PR but my calls do not appear in the graph.
> 
> Mmmm ... it might mean the resources optimization is so small it does not appear 😄 because so much bigger resource consumption happens around

@Kioob how much theme did you have on the shop to see a significiant resource over consumption ? With 10 themes, I cant see anything popping up on Blackfire and I think it's because Blackfire considers it insignificant so it does not display it

2020-09-21 08:55 UTC, matks approved these changes, later dismissed

2020-09-21 08:56 UTC, matks commented
@PierreRambaud Although I cannot observe the performance boost because it is not significant enough, I think the PR is mergeable. Wdyt ?

2020-09-21 09:32 UTC, PierreRambaud commented
> @PierreRambaud Although I cannot observe the performance boost because it is not significant enough, I think the PR is mergeable. Wdyt ?

:+1: Yes

2020-09-21 12:41 UTC, Progi1984 commented
> @PierreRambaud Although I cannot observe the performance boost because it is not significant enough, I think the PR is mergeable. Wdyt ?

:+1: Yes

2020-09-21 12:46 UTC, matks commented
So I dived into the code and found that this YAML file parsing happens _when there is a child theme using parents configuration_.

So in current implementation, if we have 10 children themes on the disk and they all use Classic as parent, this will load the YAML configuration file of Classic Theme 10 times.

This PR puts this config file in cache to avoid that.

I'll need to QA this behavior.

2020-10-07 12:54 UTC, SD1982 commented
Hi @matks we let you continue the QA on this one :+1:

2021-01-07 14:44 UTC, sowbiba commented
I take the Dev QA for this one

2021-01-11 11:52 UTC, sowbiba commented
I created 20 child themes extending classic theme. Here is the screenshot of Blackfire profiling when I go to 
/improve/design/themes/ on branch 1.7.7.x

![Capture d’écran de 2021-01-11 11-44-36](https://user-images.githubusercontent.com/7426640/104179231-6de08d80-5403-11eb-92af-3dee1b237248.png)

2021-01-11 12:43 UTC, sowbiba commented
With @Kioob improvement

![Capture d’écran de 2021-01-11 12-42-00](https://user-images.githubusercontent.com/7426640/104183892-8bfdbc00-540a-11eb-93a3-1722ec469cc9.png)

Approximatively the same memory usage but significative time improvement

2021-01-11 13:00 UTC, PierreRambaud requested changes
I just see you targeted the 1.7.7.x branch, are you able to rebase it on the develop branch please?

2021-01-11 13:01 UTC, sowbiba commented
Hi @Kioob 
Well done
As there is no regression related to your improvement, it will be for the next minor
Please target and rebase develop

2021-01-21 14:46 UTC, PierreRambaud approved these changes
PR has been rebased and already tested :)

2021-01-21 16:06 UTC, Progi1984 approved these changes

2021-01-21 16:20 UTC, merged

2021-01-21 16:21 UTC, PierreRambaud commented
Thank you @Kioob