Disable payment button if term checkbox is unchecked
PrestaShop/PrestaShop pull request #19438
Opened 2020-05-28 09:39 UTC by NeOMakinG

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Binary payment button was enabled while terms checkbox was unchecked, it's a problem
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #19161.
| How to test?  | Install the module example provided by @Matt75 in #19161, and then go to checkout page, select binary, the "Pay binary" button shouldn't be clickable

2020-05-28 09:42 UTC, Progi1984 commented on themes/_core/js/checkout-payment.js
> +      $(paymentOption + ' button').attr('disabled', !show);
```suggestion
      $(`${paymentOption} button`).attr('disabled', !show);
```

2020-05-28 09:42 UTC, Progi1984 reviewed
A small change

2020-05-28 09:47 UTC, Matt75 requested changes

2020-05-28 09:47 UTC, Matt75 commented on themes/_core/js/checkout-payment.js
> +      $(paymentOption + ' button').attr('disabled', !show);
https://github.com/PrestaShop/PrestaShop/issues/19161#issuecomment-629316433

2020-05-28 09:52 UTC, Matt75 submitted a review, later dismissed

2020-05-28 10:10 UTC, Progi1984 submitted a review, later dismissed

2020-05-28 15:03 UTC, PierreRambaud submitted a review, later dismissed

2020-05-29 13:58 UTC, Robin-Fischer-PS commented
Hi @NeOMakinG !

Now, even when terms are checked, the "Pay" button is still disabled, so I cannot pay with Binary : 

![screencapture-localhost-psdevelop-develop-fr-commande-2020-05-29-15_57_53](https://user-images.githubusercontent.com/55688534/83267966-3e0ead80-a1c5-11ea-8d16-f0a9487887d6.png)

2020-06-01 08:52 UTC, Matt75 requested changes

2020-06-01 08:52 UTC, Matt75 commented on themes/_core/js/checkout-payment.js
> +      console.log(show);
```suggestion

```

2020-06-01 08:54 UTC, NeOMakinG commented on themes/_core/js/checkout-payment.js
> +      console.log(show);
wow

2020-06-01 08:55 UTC, NeOMakinG commented on themes/_core/js/checkout-payment.js
> +      console.log(show);
You didn't see anything 🤫

2020-06-01 08:57 UTC, Matt75 approved these changes

2020-06-01 09:29 UTC, PierreRambaud approved these changes

2020-06-02 06:28 UTC, Progi1984 approved these changes

2020-06-02 10:11 UTC, merged

2020-06-02 10:11 UTC, Progi1984 commented
Thanks @NeOMakinG