Update modules (contactform/ps_imageslider/ps_sharebuttons/ps_themecusto/statspersonalinfos)
PrestaShop/PrestaShop pull request #19556
Opened 2020-06-04 07:27 UTC by Progi1984

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Update modules (contactform/ps_imageslider/ps_sharebuttons/ps_themecusto/statspersonalinfos)
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #19446
| How to test?  | Check if modules contactform, ps_imageslider, ps_sharebuttons, ps_themecusto, statspersonalinfos are well installed, are up-to-date and they have no errors at use.

2020-06-04 07:30 UTC, matthieu-rolland approved these changes

2020-06-04 08:14 UTC, PierreRambaud requested changes
Themecusto is not updated :thinking:

2020-06-04 09:51 UTC, Progi1984 commented
@PierreRambaud ps_themecusto is already at the good version (1.2.0) in `composer.lock`.

2020-06-04 09:52 UTC, PierreRambaud approved these changes

2020-06-04 12:12 UTC, NeOMakinG approved these changes

2020-06-05 12:26 UTC, merged

2020-06-05 12:26 UTC, Progi1984 commented
Thanks @sarahdib