Test install with localhost if 127.0.0.1 fails
PrestaShop/PrestaShop pull request #19714
Opened 2020-06-11 14:36 UTC by ksaandev

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Some webhosting dont route 127.0.0.1 but use localhost instead. This PR attempts to check if localhost works 127.0.01 fails and tells user if it works.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | On localhost, configure your vhost to refuse 127.0.01 but accept localhost. Try to install prestashop, when you click on "test my database settings" it should tell you message 'Database can be reached if you use localhost for server name instead of 127.0.0.1'

2020-06-11 14:53 UTC, PierreRambaud requested changes
I'm sorry but this error comes from a missing MySQL configuration and it's not related to PrestaShop. 

You need to check `bind-address` in the `my.cnf`, many hosts provider allow you to change this value.

Furthermore, your pull request does not take account ipv6.

2020-06-11 15:07 UTC, matks commented
Changed category from "CO" (Core) to "IN" (Installer)

2020-06-11 16:17 UTC, ksaandev commented
CI says something weird can you check ?

2020-06-11 16:18 UTC, ksaandev commented
> I'm sorry but this error comes from a missing MySQL configuration and it's not related to PrestaShop.
> 
> You need to check `bind-address` in the `my.cnf`, many hosts provider allow you to change this value.
> 
> Furthermore, your pull request does not take account ipv6.

Not every hosting provider allow to modify this T_T

2020-06-13 13:32 UTC, ksaandev commented
> I'm sorry but this error comes from a missing MySQL configuration and it's not related to PrestaShop.

So if I understand you don't want to merge PR ?

2020-06-15 08:22 UTC, PierreRambaud commented
> > I'm sorry but this error comes from a missing MySQL configuration and it's not related to PrestaShop.
> > You need to check `bind-address` in the `my.cnf`, many hosts provider allow you to change this value.
> > Furthermore, your pull request does not take account ipv6.
> 
> Not every hosting provider allow to modify this T_T

Even if not all hosts provider provides a way to change the bind-address, they always send MySQL information to properly connect to your database (such as host, login and password).

2020-06-15 10:09 UTC, Junebyun commented
@LouiseBonnard wording approved :)

2020-06-15 14:29 UTC, ksaandev commented
> > > I'm sorry but this error comes from a missing MySQL configuration and it's not related to PrestaShop.
> > > You need to check `bind-address` in the `my.cnf`, many hosts provider allow you to change this value.
> > > Furthermore, your pull request does not take account ipv6.
> > 
> > 
> > Not every hosting provider allow to modify this T_T
> 
> Even if not all hosts provider provides a way to change the bind-address, they always send MySQL information to properly connect to your database (such as host, login and password).

Alright, I close my PR. have a nice day :)

2020-06-15 14:29 UTC, closed without merging