Change buttons in modal bulk of module page to avoid black color and …
PrestaShop/PrestaShop pull request #19814
Opened 2020-06-17 09:36 UTC by NeOMakinG

…keep consistency

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Buttons had black colors instead of white and cancel button didn't have the same style than other modals on this page
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #9699.
| How to test?  | Go on module page, select some module, do a bulk action and see if buttons are same as other modals on the page (without black color)

2020-06-17 12:33 UTC, PierreRambaud commented
Why targeting the 1.7.6.x branch? :thinking:

2020-06-17 12:36 UTC, NeOMakinG commented
@PierreRambaud the issue was on 1.7.6 :(

But after discussing about this with Coline, since there are some things to merge to 1.7.7.x on this branch, it looks like it's not a problem ? Also, I modified a BC on another PR on 1.7.6 that will need to be merged on 1.7.7 because @Progi1984 asked me to target 1.7.6

2020-06-17 12:42 UTC, PierreRambaud commented
I said that because of the issue content :sweat_smile: :
![image](https://user-images.githubusercontent.com/1462701/84899331-d0a9ba80-b0a8-11ea-9c88-f1be6406dddc.png)

2020-06-17 12:46 UTC, NeOMakinG commented
Grr 😄

2020-06-18 08:09 UTC, Junebyun approved these changes

2020-06-18 13:41 UTC, atomiix approved these changes

2020-06-18 13:50 UTC, PierreRambaud requested changes
The issue targets the 1.7.8.0 milestone :thinking:

2020-06-18 13:52 UTC, atomiix commented
@PierreRambaud Not anymore, @colinegin changed it yesterday

2020-06-18 14:01 UTC, PierreRambaud approved these changes
Let it go!

2020-06-23 09:49 UTC, Robin-Fischer-PS commented
Thanks @NeOMakinG , it's OK now 

![pr color bulk module](https://user-images.githubusercontent.com/55688534/85389380-a001cf00-b547-11ea-9d2d-00c50253570e.png)

QA :heavy_check_mark:

2020-06-23 12:03 UTC, merged

2020-06-23 12:03 UTC, Progi1984 commented
Thanks @NeOMakinG & @Robin-Fischer-PS