When new webservice key is created, add log
PrestaShop/PrestaShop pull request #19831
Opened 2020-06-17 20:25 UTC by ksaandev

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | I add a call to PrestaShopLogger in webservice key creation so it's logged. I think for security it's important BO Admin can know who create keys. Keys can provide access to critical data.
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Create a new Webservice Key then go in Logs page and see latest log which says "Webservice key created by employee Ksaan Ami (ksaan.ami@gmail.com)"

2020-06-18 07:31 UTC, NeOMakinG submitted a review, later dismissed
Good thing I think, approving for the feature :)

2020-06-18 07:34 UTC, matks submitted a review, later dismissed
Indeed it's an important event to be logged

However ... we should then start logging also webservice keys updates and deletes, right ? 😄 

Let's no make the scope of this PR bigger, but this is something we could add in the future 😊

2020-06-18 07:56 UTC, Progi1984 submitted a review, later dismissed

2020-06-18 08:05 UTC, Junebyun submitted a review, later dismissed

2020-06-18 08:36 UTC, Junebyun commented
Hey guys, just to check: will this text be shown like a **notification** (shortly shown on a banner) or like a **text block** in the page (text which will be permanently there if you go to the Logs page)? 

Could you show me a screenshot of how it will be shown?

Because if it turns out to be a permanent text in the Logs page I'd rather put the domain as _Feature_ instead of _Notifications_.

2020-06-18 09:21 UTC, ksaandev commented
> Let's no make the scope of this PR bigger, but this is something we could add in the future 😊

I can do it in another PR :)

2020-06-18 09:23 UTC, ksaandev commented
> Hey guys, just to check: will the text _"Webservice key created by employee..."_ be shown like a **notification** (shortly shown on a banner) or like a **text block** in the page (text which will be permanently there if you go to the Logs page)?

No, it's different. It will appear as one item of the logs list.

The Logs page show multiple logs which are like registry items. You can add as many as you want, it's things you want to register and be able to search, sort, list later when you want to understand what happened in the past.

So it will not be a banner, it will not be a block of text. It will be one item that appears inside the list displayed in the Logs page.

2020-06-18 10:29 UTC, Junebyun commented on classes/webservice/WebserviceKey.php
> +                    'Admin.Advparameters.Notification'
```suggestion
                    'Webservice key created by employee %s %s (%s)',
                    [
                        Context::getContext()->employee->firstname,
                        Context::getContext()->employee->lastname,
                        Context::getContext()->employee->email,
                    ],
                    'Admin.Advparameters.Feature'
```

2020-06-18 10:31 UTC, Junebyun commented
> > Hey guys, just to check: will the text _"Webservice key created by employee..."_ be shown like a **notification** (shortly shown on a banner) or like a **text block** in the page (text which will be permanently there if you go to the Logs page)?
> 
> No, it's different. It will appear as one item of the logs list.
> 
> The Logs page show multiple logs which are like registry items. You can add as many as you want, it's things you want to register and be able to search, sort, list later when you want to understand what happened in the past.
> 
> So it will not be a banner, it will not be a block of text. It will be one item that appears inside the list displayed in the Logs page.

Thank you for your explanation, it's very clear to me now! :)
I would suggest _Admin.Advparameters.Feature_ for its domain then.

2020-06-18 13:09 UTC, matks submitted a review, later dismissed

2020-06-18 13:11 UTC, Junebyun submitted a review, later dismissed

2020-06-18 15:19 UTC, PierreRambaud commented on classes/webservice/WebserviceKey.php
> +                    ],
```suggestion
                Context::getContext()->getTranslator()->trans(
                    'Webservice key created by employee "%d" %s %s (%s)',
                    [
                        Context::getContext()->employee->id,
                        Context::getContext()->employee->firstname,
                        Context::getContext()->employee->lastname,
                        Context::getContext()->employee->email,
                    ],
```

2020-06-18 15:19 UTC, PierreRambaud requested changes
Should be better to also add the id, employee are able to change their firstname, lastname and email before running the key creation.

2020-06-19 06:22 UTC, Progi1984 commented on classes/webservice/WebserviceKey.php
> +                    ],
I approve.

2020-06-23 05:10 UTC, ksaandev commented on classes/webservice/WebserviceKey.php
> +                    ],
Thank you ! done

2020-06-23 07:34 UTC, matks approved these changes

2020-06-23 10:33 UTC, LouiseBonnard approved these changes

2020-06-23 12:17 UTC, Junebyun approved these changes

2020-06-24 07:38 UTC, SD1982 commented
HI @ksaandev some changes have been requested by @PierreRambaud can you check this please ?

2020-06-24 07:56 UTC, PierreRambaud approved these changes

2020-06-24 07:59 UTC, SD1982 commented
Oups sorry @ksaandev  my bad it's good for the requested changes !

2020-06-24 08:53 UTC, SD1982 commented
LGTM the log is correctly added ! Thanks @ksaandev !!

2020-06-24 09:27 UTC, merged

2020-06-24 09:27 UTC, PierreRambaud commented
Thanks @ksaandev

2020-06-24 12:17 UTC, ksaandev commented
> LGTM the log is correctly added ! Thanks @ksaandev !!

😄 thank you guys it's so cool to see PRs merged very fast