Feature/attribute group actions
PrestaShop/PrestaShop pull request #19838
Opened 2020-06-18 09:50 UTC by JevgenijVisockij

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop / 1.7.7.x
| Description?  | Add modal actions to attribute and attribute actions
| Type?         | refacto
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #10511.
| How to test?  | Attributes and attribute group deletion (bulk and single) should have modals

2020-06-18 10:04 UTC, PululuK requested changes

2020-06-18 10:04 UTC, PululuK commented on src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/attribute.yml
> +  methods: DELETE
Avoid Break Changes, use ` [POST, DELETE]`

2020-06-18 13:05 UTC, PierreRambaud commented on src/Core/Grid/Definition/Factory/AttributeGridDefinitionFactory.php
> +declare(strict_types=1);
It's a BC break, you can't add it, this file exists in 1.7.7.x

2020-06-18 13:05 UTC, PierreRambaud commented on src/Core/Grid/Definition/Factory/AttributeGroupGridDefinitionFactory.php
> +declare(strict_types=1);
same here

2020-06-25 15:21 UTC, matks submitted a review, later dismissed

2020-06-25 20:39 UTC, PierreRambaud submitted a review, later dismissed

2020-07-10 13:05 UTC, khouloudbelguith commented
Hi @JevgenijVisockij,

The Modal is well displayed.
When I try to delete an item => an exception is displayed
![image](https://user-images.githubusercontent.com/16067358/87157548-b84f4900-c2be-11ea-93c3-b51011ed5237.png)
https://drive.google.com/file/d/11S8Z4l83Vri-m2pGLB34Q8fDFQw8fGwk/view?usp=sharing

Thanks!

2020-07-10 13:09 UTC, JevgenijVisockij commented
> Hi @JevgenijVisockij,
> 
> The Modal is well displayed.
> When I try to delete an item => an exception is displayed
> ![image](https://user-images.githubusercontent.com/16067358/87157548-b84f4900-c2be-11ea-93c3-b51011ed5237.png)
> https://drive.google.com/file/d/11S8Z4l83Vri-m2pGLB34Q8fDFQw8fGwk/view?usp=sharing
> 
> Thanks!

Thanks! Will check that immideatly!

2020-07-10 13:19 UTC, JevgenijVisockij commented
Solved the exception issue.

2020-07-17 13:42 UTC, matks approved these changes

2020-07-17 16:40 UTC, PierreRambaud approved these changes

2020-07-20 08:49 UTC, khouloudbelguith commented
Hi @JevgenijVisockij,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1WUo4CnkxxRfmjjCh5NVv0Ug2mf1H4kZM/view?usp=sharing

Thanks!

2020-07-20 08:50 UTC, merged

2020-07-20 08:50 UTC, Progi1984 commented
Thanks @JevgenijVisockij & @khouloudbelguith