CO : Add the theme name to the compile_id
PrestaShop/PrestaShop pull request #20033
Opened 2020-07-02 14:10 UTC by djbuch

In order to avoid collisions between different themes (in multishop mode), we have to specify the theme name in the compile id.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | In order to avoid collisions between different themes (in multishop mode), we have to specify the theme name in the compile id. Otherwise we were loading compiled templates from other themes in the current theme randomly
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Create a multi shop with different themes but sames modules activated. The compiled templates will be loaded from different themes if we do not set the compile ID.

2020-07-06 10:05 UTC, PierreRambaud approved these changes

2020-07-06 10:10 UTC, Progi1984 submitted a review, later dismissed

2020-08-18 14:01 UTC, eternoendless commented
Wouldn't this lead to collisions if two shops use the same theme? Maybe it should use the shop id instead?

2020-08-19 07:57 UTC, PierreRambaud commented on config/smarty.config.inc.php
> +$smarty->setCompileId(_THEME_NAME_);
```suggestion
$smarty->setCompileId(Context::getContext()->shop->id . '-' . _THEME_NAME_);
```
@eternoendless is right, it doesn't concern the multishop, combined to the theme name is more efficient

2020-08-19 07:58 UTC, PierreRambaud requested changes
See comments

2020-09-07 09:27 UTC, PierreRambaud approved these changes

2020-09-08 07:33 UTC, matthieu-rolland approved these changes

2020-09-08 13:22 UTC, Progi1984 approved these changes

2020-09-21 09:24 UTC, ngodefroy commented
currently blocked by https://github.com/PrestaShop/PrestaShop/issues/21066

2020-09-21 13:02 UTC, ngodefroy commented
Hello @djbuch 

I still had mixed themes together in my case.

here is how I tested it:

In multistore, created different shops, added virtual url to each ones.
After that, I checked the different links which all redirected to different themes.
As you can see, One of my theme was mixed with the classic one:

On the right, is the original theme.
On the left, is the mixed theme I get with I switched from classic to the new theme virtual url.
<img width="1423" alt="Capture d’écran 2020-09-21 à 14 55 05" src="https://user-images.githubusercontent.com/69145330/93769647-62cadd00-fc1b-11ea-9f5f-ccb30322cd1e.png">

Thank you

2020-11-18 10:43 UTC, SimonGrn commented
Hello,

there is no issue linked with this PR. Please create an issue.

2020-11-19 08:23 UTC, SD1982 commented
HI @djbuch I also still have mixed template with your PR

**I have this result:**
![image](https://user-images.githubusercontent.com/40635814/99639986-9e7df980-2a48-11eb-8f8f-c994f8a411f4.png)

**It's a mix between this template**
![image](https://user-images.githubusercontent.com/40635814/99640034-afc70600-2a48-11eb-89c4-a8981ddc6ff0.png)

**And this one:**
![image](https://user-images.githubusercontent.com/40635814/99640102-c2413f80-2a48-11eb-9f87-bafdcee9ffb6.png)

2021-01-11 15:08 UTC, SD1982 commented
Hi @djbuch as we got no answer in 30 days we close the PR [following our rules](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests) but if you come back we'll be happy to reopen it 
Have a nice day

2021-01-11 15:08 UTC, closed without merging

2021-01-11 21:07 UTC, hadjedjvincent commented
> Hi @djbuch as we got no answer in 30 days we close the PR [following our rules](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests) but if you come back we'll be happy to reopen it
> Have a nice day

Issue is available here : https://github.com/PrestaShop/PrestaShop/issues/20301