[BO] Color picker doesn't recognize html color name on page load
PrestaShop/PrestaShop pull request #20148
Opened 2020-07-10 23:19 UTC by PululuK

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | In BO, the color picker allows to pick a color, but also to write an HTML color name, like "blue" or "red" for example. When we type "red", the color automatically switches to red, this is working, and the value"red" is properly saved when we push the form. But if you go back, in edit mode, the field will have the value "red", which is correct, but the color will remain black, it seems like the colorpicker doesn't update the color on page load when it is an HTML color name, it works fine with hexa codes. by @matthieu-rolland 
| Type?         | bug fix 
| Category?     | FO 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/20108
| How to test?  | See https://github.com/PrestaShop/PrestaShop/issues/20108 by @matthieu-rolland .

2020-07-10 23:19 UTC, PululuK commented
ping @NeOMakinG

2020-07-11 02:20 UTC, arouiadib commented
+1 for the quality of the description of the PR.
Just a question I always ask myself but never found opportunity to ask someone else.

Is it allowed to modify such file in the context of PS project? 
I see in the beginning:

```
/*
  mColorPicker
  Version: 1.0 r34
  Copyright (c) 2010 Meta100 LLC.
  http://www.meta100.com/
  Licensed under the MIT license
  http://www.opensource.org/licenses/mit-license.php
*/

```

Thanks in advance for information

2020-07-11 07:46 UTC, PululuK commented
> +1 for the quality of the description of the PR.
> Just a question I always ask myself but never found opportunity to ask someone else.
> 
> Is it allowed to modify such file in the context of PS project?
> I see in the beginning:
> 
> ```
> /*
>   mColorPicker
>   Version: 1.0 r34
>   Copyright (c) 2010 Meta100 LLC.
>   http://www.meta100.com/
>   Licensed under the MIT license
>   http://www.opensource.org/licenses/mit-license.php
> */
> ```
> 
> Thanks in advance for information

Hi @arouiadib,
I think it's legitimate
See please : https://opensource.org/licenses/MIT
@matks @ttoine do you want to add something ?
Thanks

2020-07-13 08:38 UTC, NeOMakinG submitted a review, later dismissed
Looks fine for me @PululuK, does the fact that you update it on keyup doesn't cause any errors when the color isn't completely written ?

2020-07-13 09:45 UTC, PierreRambaud commented on js/jquery/plugins/jquery.colorpicker.js
> + $.fn.mColorPicker.setTextColor = function(element) {
```suggestion
  $.fn.mColorPicker.setTextColor = function(element) {
```

2020-07-13 09:46 UTC, PierreRambaud commented on js/jquery/plugins/jquery.colorpicker.js
> +  };
```suggestion
    try {
      element.css({
        'background-color': element.val()
      }).css({
        'color': $.fn.mColorPicker.textColor(element.css('background-color'))
      }).trigger('change');
    } catch (r) {}
    };
```

2020-07-13 09:46 UTC, PierreRambaud requested changes
Nice catch, but sorry indentation is broken :sweat_smile:

2020-07-13 09:48 UTC, PierreRambaud commented on js/jquery/plugins/jquery.colorpicker.js
> +    };
```suggestion
  };
```
Oups adding unneeded spaces, my bad ^^

2020-07-13 11:57 UTC, NeOMakinG approved these changes

2020-07-13 12:49 UTC, PierreRambaud approved these changes

2020-07-13 14:04 UTC, NeOMakinG commented
Simple question @PululuK, is it possible to set the color on ready but outside the source file ? I think yes, but not sure

2020-07-13 14:08 UTC, eternoendless commented
This lib has been updated since r34 as well https://github.com/meta100/mColorPicker/blob/master/javascripts/mColorPicker.js

2020-07-13 14:20 UTC, khouloudbelguith commented
Hi @PululuK,

It is ok :heavy_check_mark: https://drive.google.com/file/d/1Ti5_tSWlT9A9ItNTniQsJYqewLUbqqxh/view?usp=sharing
Thanks!

2020-07-13 14:21 UTC, PululuK commented
> Simple question @PululuK, is it possible to set the color on ready but outside the source file ? I think yes, but not sure


Hi @NeOMakinG ,

Yes I think it's possible, maybe here :
admin-dev/themes/default/template/helpers/form/form.tpl
admin-dev/themes/default/template/helpers/options/options.tpl

But this file has already been modified by the Prestashop team
https://github.com/PrestaShop/PrestaShop/blob/develop/js/jquery/plugins/jquery.colorpicker.js

2020-07-13 15:24 UTC, merged

2020-07-13 15:32 UTC, matthieu-rolland commented
thanks @PululuK !

2020-07-13 15:36 UTC, PululuK commented
@matthieu-rolland  @eternoendless  @NeOMakinG 
If you want to update this library I can open a new PR for this, but I think it could be BC for some modules for example.
WDYF ?