Fix order history font-size and contrast
PrestaShop/PrestaShop pull request #20233
Opened 2020-07-19 17:15 UTC by davidglezz

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Order history page has different global font-size
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #19144
| How to test?  | Go to Order details and check that header font size is the same as other pages.

Before:
![Anotación 2020-07-19 182343](https://user-images.githubusercontent.com/194784/87880682-ee45a900-c9f3-11ea-8c2e-33eaf9d00b4e.png)

After:
![Anotación 2020-07-19 190419](https://user-images.githubusercontent.com/194784/87880684-f1409980-c9f3-11ea-8879-8d5ee333cfe9.png)

2020-07-19 17:47 UTC, NeOMakinG submitted a review, later dismissed

2020-07-20 07:49 UTC, Progi1984 submitted a review, later dismissed

2020-07-20 07:50 UTC, Progi1984 commented
Need an UX validation : please @TristanLDD :)

2020-08-20 07:29 UTC, matks commented
UX validation was provided 🎉 

I dont think we need QA validation, do we ? 🤔

2020-08-20 07:29 UTC, matks approved these changes, later dismissed

2020-08-20 07:36 UTC, NeOMakinG commented
@davidglezz there is a conflict on your PR, can you rebase ? we're gonna approve asap after it :)

2020-08-20 09:10 UTC, davidglezz commented
Done. Next time I'll try to do a rebase like matks says in https://dev.to/mathieuks/what-it-means-to-rebase-a-pull-request-submitted-on-github-5717

2020-08-20 09:39 UTC, matthieu-rolland approved these changes, later dismissed

2020-08-20 09:40 UTC, eternoendless requested changes, later dismissed
Please rebase and squash your commits, merge commits may introduce merge errors that are invisible in github

2020-08-24 18:22 UTC, davidglezz commented
done!

2020-08-25 08:04 UTC, NeOMakinG approved these changes

2020-08-26 17:25 UTC, PierreRambaud approved these changes

2020-09-03 15:10 UTC, ngodefroy commented
Hello @davidglezz,
I still have the issue:
![Capture d’écran 2020-09-03 à 17 09 44](https://user-images.githubusercontent.com/69145330/92133087-44d23f80-ee08-11ea-8886-f9713f9eb3c9.png)

2020-09-03 15:14 UTC, davidglezz commented
@ngodefroy ng have you recompiled the assets?

2020-09-04 11:30 UTC, ngodefroy commented
> @ngodefroy have you recompiled the assets?

I actually did :s 
I don't see the contrast difference as your screenshot is.

2020-09-12 16:21 UTC, davidglezz commented
Maybe an error with docker image.

Now, you need to install the dependencies manually

```
docker-compose exec prestashop-git bash

npm run watch
>>> webpack: not found

THEN

npm install
npm run watch

```

![fix](https://user-images.githubusercontent.com/194784/92999796-2107ab80-f524-11ea-9ff8-4c8569a5b29a.gif)

2020-09-18 15:33 UTC, ngodefroy commented
Hello, @matks  or can somebody from dev team take this PR?
I can't reproduce after fresh install - and after concerting with QA, they told me to avoid adding by myself the following commands lines:

docker-compose exec prestashop-git bash
cd /var/www/html/themes/classic/_dev
npm run watch
>>> webpack: not found

THEN

npm install
npm run watch

Thank you

2020-09-21 13:40 UTC, Progi1984 commented
Ping @PrestaShop/prestashop-core-developers : cf message from @ngodefroy

2020-09-22 14:43 UTC, PierreRambaud commented
> Maybe an error with docker image. @ngodefroy
> 
> Now, you need to install the dependencies manually
> 
> ```
> docker-compose exec prestashop-git bash
> cd /var/www/html/themes/classic/_dev
> npm run watch
> >>> webpack: not found
> 
> THEN
> 
> npm install
> npm run watch
> ```
> 
> ![fix](https://user-images.githubusercontent.com/194784/92999796-2107ab80-f524-11ea-9ff8-4c8569a5b29a.gif)

Dependencies are already installed manually since tests by QA are from source and not from a zip :sweat_smile: 

@ngodefroy You must recompile assets after having merged this pull request. Did you do that?

2020-09-22 15:22 UTC, ngodefroy commented
Did a fresh install, recompiled assets, I get it now ! 
<img width="1193" alt="Capture d’écran 2020-09-22 à 17 22 26" src="https://user-images.githubusercontent.com/69145330/93902721-3042e200-fcf8-11ea-86ed-975a4e56b4b1.png">


Thank you @davidglezz & @PierreRambaud :)

2020-09-23 07:00 UTC, merged

2020-09-23 07:01 UTC, Progi1984 commented
Thanks @davidglezz & @ngodefroy