fix bug alert
PrestaShop/PrestaShop pull request #20320
Opened 2020-07-24 11:51 UTC by jimmydupre

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | this notification is visible on back even is empty with array(null).
| Type?         | bug fix 
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? |
| How to test?  | this notification is visible before modification. I just change one line. <br>I test this bug with any simaltion {$error = array('test')} before line 34.

2020-07-31 18:19 UTC, PierreRambaud commented on admin-dev/themes/default/template/layout.tpl
> +{if count($error)}
```suggestion
{if !empty($error)}
```

2020-08-03 07:50 UTC, NeOMakinG submitted a review, later dismissed
Should be fine I think

2020-08-03 22:04 UTC, davidglezz requested changes

2020-08-03 22:04 UTC, davidglezz commented on admin-dev/themes/default/template/layout.tpl
> +{if count($error)}
I think it's better:
```suggestion
{if !empty($error)}
```

If `$error` was not defined or it is not array, it could give error.

2020-08-04 06:59 UTC, davidglezz approved these changes

2020-09-09 12:28 UTC, Progi1984 approved these changes

2020-09-09 17:25 UTC, atomiix approved these changes

2020-09-10 08:17 UTC, matthieu-rolland approved these changes

2020-09-10 16:05 UTC, matthieu-rolland commented
Hi @jimmydupre, I tested your PR, and indeed before that we would display an empty error message if for some reason the `$error` variable had let's say `false` as a value. 

Thank you for your contribution :+1:

2020-09-10 16:05 UTC, merged