Carrier field in invoice must not be displayed if order is virtual
PrestaShop/PrestaShop pull request #20637
Opened 2020-08-18 18:41 UTC by Amit-Kumar-Tiwari-Webkul

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  |The Carrier field in the invoice must not be displayed if an order is virtual i.e if all products of an order are virtual.
https://prnt.sc/u1sfdh
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #20636 
| How to test?  | Go to the front end and add one or more than one virtual product in the cart. Make a successful order. Now go to the back-office and download invoice for that order. Since the order contains all virtual products that mean no shipping is required but the string is appealing https://prnt.sc/u1sfdh that is incorrect.

2020-08-19 07:50 UTC, NeOMakinG approved these changes
lgtm

2020-08-19 07:51 UTC, NeOMakinG requested changes

2020-08-19 07:51 UTC, NeOMakinG commented on pdf/invoice.tpl
> +{/if}
Need some indentation there I think

2020-08-19 08:01 UTC, PierreRambaud commented on pdf/invoice.tpl
> +{if isset($is_virtual_order) && $is_virtual_order}
```suggestion
  {if !empty($is_virtual_order)}
```
And you need to increase the indentation of the if content.

2020-08-19 09:08 UTC, matthieu-rolland reviewed
You have some feedback on indentation, otherwise your fix looks goot to me 👍

2020-08-21 08:05 UTC, NeOMakinG submitted a review, later dismissed

2020-08-24 08:09 UTC, atomiix approved these changes, later dismissed

2020-08-24 14:04 UTC, PierreRambaud commented on pdf/invoice.tpl
> +    <td colspan="6" class="left">
```suggestion
  {if isset($is_virtual_order) && $is_virtual_order}
    <tr>
      <td colspan="6" class="left">
```

2020-08-24 14:04 UTC, PierreRambaud commented on pdf/invoice.tpl
> +  </tr>
```suggestion
      </td>
      <td colspan="1">&nbsp;</td>
    </tr>
```

2020-08-24 14:04 UTC, PierreRambaud commented on pdf/invoice.tpl
> +      {$shipping_tab}
```suggestion
        {$shipping_tab}
```

2020-08-24 14:05 UTC, PierreRambaud approved these changes, later dismissed
I added comments, but the indentation is broken everywhere in this file. So it's ok for me :+1:

2020-08-31 07:43 UTC, Amit-Kumar-Tiwari-Webkul commented
HI, Any  Update from QA team

2020-09-01 14:00 UTC, khouloudbelguith commented
Hi @Amit-Kumar-Tiwari-Webkul,

I found some issues:

Steps to reproduce the issue:
1. add a virtual product to the cart
2. checkout
3. go to BO > Orders > last order created
4. generate Invoice

=>The Invoice is NOK
Before, I have this
![image](https://user-images.githubusercontent.com/16067358/91859870-3b5fa080-ec6b-11ea-93b3-97d444440c36.png)

After **with PR**
![image](https://user-images.githubusercontent.com/16067358/91859951-53372480-ec6b-11ea-9f5a-cecfcbe708b9.png)

I found another issue
Steps to reproduce the issue:
1. add a virtual product to the cart, add another standard product to the cart
2. checkout
3. go to BO > Orders > last order created
4. generate Invoice

=> see the error, the carrier is not displayed => it shouldn't
![image](https://user-images.githubusercontent.com/16067358/91860292-ca6cb880-ec6b-11ea-8063-16dce9b8bd77.png)
PS: same issue if you have a standard product only => the carrier is not displayed anymore.

Thanks!

2020-09-02 06:47 UTC, Amit-Kumar-Tiwari-Webkul commented
@khouloudbelguith , sorry! It's my bad. I am changing some code for fixes.
But the payment method (https://prnt.sc/ua21qi ) is not disappearing from our side testing because there was no change in the payment method code. I have tested it on the ps version1.7.6.7.

2020-09-02 07:05 UTC, Amit-Kumar-Tiwari-Webkul commented
@khouloudbelguith ,
After fixes, I have tested both cases, In both cases PR is working
**Case1 :** 1) add a virtual product to the cart
2) checkout
3_ go to BO > Orders > last order created
4) generate Invoice
Result: https://prnt.sc/ua2e7n  -> OK
**case-2:** 
1 ) add a virtual product to the cart, 
2)  add another standard product to the cart
3) checkout
4) go to BO > Orders > last order created
5) generate Invoice
Result : https://prnt.sc/ua2ffc -> OK

2020-09-28 11:30 UTC, Amit-Kumar-Tiwari-Webkul commented
@khouloudbelguith, Hi any update on this PR?

2020-09-28 11:47 UTC, khouloudbelguith commented
HI @Amit-Kumar-Tiwari-Webkul,

This PR should be reviewed by our developers first :slightly_smiling_face: 

Thanks!

2020-09-28 15:37 UTC, atomiix approved these changes
I'm approving this PR but it would be nice if you could [squash your commits](https://www.internalpointers.com/post/squash-commits-into-one-git) ;)

2020-09-29 13:06 UTC, Progi1984 approved these changes

2020-10-07 11:20 UTC, khouloudbelguith commented
Hi @Amit-Kumar-Tiwari-Webkul,

I found an issue.
Steps to reproduce the issue:
1. add a standard product to the cart
2. checkout
3. go to BO > Orders > last order created
4. generate Invoice

=> see the error, the carrier is not well displayed => it shouldn't
![image](https://user-images.githubusercontent.com/16067358/95324058-7030ca00-089f-11eb-8bf9-196e59f8bf33.png)

Before
![image](https://user-images.githubusercontent.com/16067358/95324338-e0d7e680-089f-11eb-9603-15bbbdd773ba.png)

Thanks!

2020-11-04 10:55 UTC, Progi1984 commented
@Amit-Kumar-Tiwari-Webkul Coud you fix error (given by @khouloudbelguith) ? Thanks

2020-11-05 07:09 UTC, Amit-Kumar-Tiwari-Webkul commented
@Progi1984 , I am unable to produce this issue (given by @khouloudbelguith ).
I have tested it on ps1.7.6.8 and ps 1.7.7.0 and working fine https://prnt.sc/ua2ffc
also, I just added a condition on line https://github.com/PrestaShop/PrestaShop/blob/a007e16bc60b87dc0a174224ae9e7ebb59d9352b/pdf/invoice.tpl#L101
do not know how it may cause a design issue?

2020-11-05 08:17 UTC, khouloudbelguith commented
Hi @Amit-Kumar-Tiwari-Webkul,

In your screenshot, you have two products ordered (standard product + virtual product).
Thanks to check only with one standard product to see if you can reproduce the issue.

Thanks!

2020-11-05 10:00 UTC, Amit-Kumar-Tiwari-Webkul commented
@khouloudbelguith , I have tested it with one standard product.
1) If an order contains virtual products => https://prnt.sc/vdwkps (OK)
2) If an order contains standard products => https://prnt.sc/vdwjeu (OK)
but did not get any issue.
Thanks,

2020-11-05 11:55 UTC, khouloudbelguith commented
Hi @Amit-Kumar-Tiwari-Webkul,

I tried again, the same issue.
Steps to reproduce:

1. Fresh Install PS English language/ France country
2. Upload an Indian pack
3. Go to FO > Add demo_8 to the cart (select ₹ as a currency)
4. Continue checkout
5. Select a United states country (no taxes)
6. Place the Order
7. Change the status of the order to Payment accepted
8. Download the invoice
9. See error
![image](https://user-images.githubusercontent.com/16067358/98238055-1edf2d80-1f66-11eb-8358-58b5b71bea6b.png)

Thanks!

2021-01-21 14:52 UTC, PierreRambaud commented
Hi @Amit-Kumar-Tiwari-Webkul ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2021-01-21 14:52 UTC, closed without merging