Remove available_date from presented product if in the past
PrestaShop/PrestaShop pull request #20660
Opened 2020-08-20 14:10 UTC by awitkutarahil

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Remove available_date from presented product if in the past
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/20659
| How to test?  | Check out the issue

2020-08-20 15:02 UTC, NeOMakinG approved these changes, later dismissed
Looks fine to me

2020-08-21 09:17 UTC, matthieu-rolland submitted a review, later dismissed

2020-08-21 09:19 UTC, matthieu-rolland approved these changes

2020-08-21 09:21 UTC, matthieu-rolland requested changes

2020-08-21 09:21 UTC, matthieu-rolland commented on src/Adapter/Presenter/Product/ProductLazyArray.php
> +            }
hello @awitkutarahil, thank you for your contribution :)

  Here it seems that if `'0000-00-00' == $product['available_date']` then `$product['available_date']` will be set to null anyway in the second condition (since it will be inferior to current date), therefore this first condition seems unnecessary, what do you think ?

2020-08-21 12:16 UTC, NeOMakinG commented on src/Adapter/Presenter/Product/ProductLazyArray.php
> +            }
Nice catch, you should be right

2020-08-21 12:25 UTC, awitkutarahil commented on src/Adapter/Presenter/Product/ProductLazyArray.php
> +            }
@matthieu-rolland Clever indeed. I have removed the unnecessary condition.

2020-08-21 13:10 UTC, NeOMakinG submitted a review, later dismissed

2020-08-21 14:23 UTC, matthieu-rolland submitted a review, later dismissed

2020-08-24 14:13 UTC, PierreRambaud commented on src/Adapter/Presenter/Product/ProductLazyArray.php
> +            if ($date < new \DateTime()) {
```suggestion
            $date = new DateTime($product['available_date']);
            if ($date < new DateTime()) {
```

2020-08-24 14:13 UTC, PierreRambaud requested changes
Could you please use namespace instead :)

2020-08-26 08:27 UTC, awitkutarahil commented
> Could you please use namespace instead :)

This is done 😉

2020-08-27 12:44 UTC, PierreRambaud approved these changes

2020-08-27 13:43 UTC, atomiix approved these changes

2020-09-02 13:15 UTC, khouloudbelguith commented
Hi @awitkutarahil,

It is ok :heavy_check_mark: 
https://www.awesomescreenshot.com/video/825094?key=575dba2a7b15f56180ca217c96786c98

Thanks!

2020-09-02 13:35 UTC, merged

2021-11-23 16:56 UTC, AldeaG commented
How can I implement this in a Prestashop 1.7.7.0 without update the whole Prestashop?