Not updating the unit_price_ration when unit_price has not been submi…
PrestaShop/PrestaShop pull request #20680
Opened 2020-08-23 18:18 UTC by artaban

Fixes #20679

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop / 1.7.7.x
| Description?  | Fix of the #20679 
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | yes / no
| Deprecations? | yes / no
| Fixed ticket? | Fixes #20679
| How to test?  | See issue description..

2020-08-24 08:17 UTC, matthieu-rolland approved these changes, later dismissed
Hi @artaban , thanks for your contribution ! 

I aprove your modification, but this PR should not been sent to the QA team until the issue you created is reproduced by one of our testers. So wait and see ;)

2020-08-24 14:01 UTC, PierreRambaud requested changes
Hi and thanks for your contribution. This pull request must target the develop branch instead, could you please rebase it?

2020-08-25 10:19 UTC, artaban commented
I've tried my best ;)
Guess it is alway good idea to create branch for the PR.. The rebasing is much cleaned then (I've pushed my changes directly to the 1.7.6.x branch)

2020-08-27 08:28 UTC, PierreRambaud commented on classes/Product.php
> +            if ($this->unit_price != null) {
```suggestion
            if ($this->unit_price !== null) {
```
Should it be this?

2020-09-01 13:29 UTC, PierreRambaud approved these changes

2020-09-01 14:41 UTC, Progi1984 approved these changes

2020-09-03 08:48 UTC, khouloudbelguith commented
Hi @artaban,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1CdrBepowiwH0azrYpeTG3sJ1qkdVKSh-/view?usp=sharing

Thanks!

PS: about the issue of changing price => it is ab old issue reported here: https://github.com/PrestaShop/PrestaShop/issues/12078

2020-09-03 08:50 UTC, merged

2020-09-03 08:50 UTC, PierreRambaud commented
Thanks @artaban