Update Mobiledetect library
PrestaShop/PrestaShop pull request #20891
Opened 2020-09-08 09:04 UTC by PululuK

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Missing some devices Example : [`Android SM-T510`](https://www.samsung.com/be_fr/tablets/galaxy-tab-a-10-1-t510/SM-T510NZKDLUX/)  .
| Type?         | bug fix 
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | N/A.
| How to test?  | See 👇🏾.

The following code must display `2` in [`Android SM-T510`](https://www.samsung.com/be_fr/tablets/galaxy-tab-a-10-1-t510/SM-T510NZKDLUX/) devices  [See](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Context.php#L123)
```php
echo Context::getContext()->getDevice();
```

2020-09-08 09:16 UTC, PierreRambaud requested changes
Good idea, but the composer.lock must be updated, otherwise we are still in 2.8.33 :)

2020-09-08 09:19 UTC, PululuK commented
> Good idea, but the composer.lock must be updated, otherwise we are still in 2.8.33 :)

Can you do it please ? If not, I will do it later.

2020-09-08 09:22 UTC, PierreRambaud commented
> > Good idea, but the composer.lock must be updated, otherwise we are still in 2.8.33 :)
> 
> @PierreRambaud Can you do it please ? If not, I will do it later.

Not sure I will have the time to do it today :sweat:

2020-09-08 09:25 UTC, PululuK commented
> Not sure I will have the time to do it today sweat

I will do it later ... thank you anyway !

2020-09-08 09:55 UTC, PululuK commented
@PierreRambaud  @Progi1984   I just looked ... on [`composer.lock`](https://github.com/PrestaShop/PrestaShop/blob/develop/composer.lock#L3189) the version seems to be good 🤔  ?

2020-09-08 12:22 UTC, PierreRambaud commented
> @PierreRambaud @Progi1984 I just looked ... on [`composer.lock`](https://github.com/PrestaShop/PrestaShop/blob/develop/composer.lock#L3189) the version seems to be already good  ?

Yes, my bad, I was checking an outdated develop branch :disappointed:

2020-09-08 12:22 UTC, PierreRambaud approved these changes, later dismissed

2020-09-08 12:23 UTC, Progi1984 approved these changes, later dismissed

2020-09-10 14:29 UTC, SD1982 commented
Hi @PululuK can you create an issue an associate it to this PR ?

2020-09-10 14:44 UTC, PululuK commented
> Hi @PululuK can you create an issue an associate it to this PR ?

Done https://github.com/PrestaShop/PrestaShop/issues/20937 ! Sorry man.

2020-09-11 10:05 UTC, khouloudbelguith commented
Hi @PululuK,

I have an issue related to your PR.
When I run `composer install`
I have a warning 
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
As discussed with @Progi1984 & @matks 
I tried with this

2020-09-11 10:07 UTC, matks commented
@PululuK Although the composer.lock version is already good, I think Composer computes a hash of its configuration to acknowledge whether composer.lock and composer.json are synchronized. This is why @khouloudbelguith has the warning
```
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
```

To get rid of the warning, you can run `composer update nothing`

It will update composer.lock `content-hash` and Composer will be happy after that

2020-09-11 10:09 UTC, jolelievre commented
Or maybe `composer update mobiledetect/mobiledetectlib --no-dev` so that the dependency is updated in the lock file

2020-09-11 12:32 UTC, PululuK commented
> Or maybe `composer update mobiledetect/mobiledetectlib --no-dev` so that the dependency is updated in the lock file

Hi @jolelievre 
Can you do it please ?

2020-09-18 13:51 UTC, matks commented
> > Or maybe `composer update mobiledetect/mobiledetectlib --no-dev` so that the dependency is updated in the lock file
> 
> Hi @jolelievre @matks
> Can you do it please ?

Here's a gift 🎁 https://github.com/PrestaShop/PrestaShop/pull/20891/commits/cace7dae7add6185ed231dffd1c197bfb271532a

2020-09-18 13:53 UTC, matks approved these changes

2020-09-18 13:56 UTC, PululuK commented
> Here's a gift  

Thank you @matks !

2020-09-18 14:43 UTC, PierreRambaud approved these changes

2020-09-18 14:44 UTC, PierreRambaud commented
Not sure QA is needed here because it's just a dependency update :thinking:

2020-09-18 14:55 UTC, merged

2020-09-18 14:55 UTC, matks commented
> Not sure QA is needed here because it's just a dependency update 🤔

Agreed !

Thank you @PululuK