Fix message on Module Manager when post_max_size limitation is reached
PrestaShop/PrestaShop pull request #21013
Opened 2020-09-16 12:17 UTC by Matt75

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | When uploaded file exceeds the post_max_size directive in php.ini, the $_POST and $_FILES superglobals are empty. https://www.php.net/manual/en/ini.core.php#ini.post-max-size So null value is received instead of a file and default message for this constraint is `This value should not be null`.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/issues/21009
| How to test?  | Follow scenario in linked issue, this PR replace default message by existing wording `The uploaded file exceeds the post_max_size directive in php.ini` located in domain `Admin.Notifications.Error`

2020-09-17 13:06 UTC, PierreRambaud requested changes
Hi, with your fix, if I send a request without file, I receive "The uploaded file exceeds ...", so I receive an error.
It's more a problem with the system than with the application itself :/

2020-09-18 13:27 UTC, PierreRambaud approved these changes
Nice work, as always :+1:

2020-09-21 08:47 UTC, atomiix approved these changes

2020-09-21 09:47 UTC, NeOMakinG approved these changes

2020-09-24 10:13 UTC, ngodefroy commented
currently blocked by issue: https://github.com/PrestaShop/PrestaShop/issues/20852

2020-09-25 12:27 UTC, ngodefroy commented
Hello @Matt75 ,

Im currently blocked when trying to add a module:
<img width="1233" alt="Capture d’écran 2020-09-25 à 14 26 55" src="https://user-images.githubusercontent.com/69145330/94267008-29f07800-ff3b-11ea-95fe-d9d7a1c6c0ac.png">
Could reproduce on develop branch to.

2020-10-13 14:38 UTC, ngodefroy commented
Hello @Matt75 

I edited the php.ini and set the post_max_size to 1:
![Capture d’écran 2020-10-13 à 16 37 34](https://user-images.githubusercontent.com/69145330/95875537-67923500-0d72-11eb-83d6-7fcea9f3a0e7.png)
Then I tried to upload a module but I had this issue even without your PR:
![Capture d’écran 2020-10-13 à 16 38 14](https://user-images.githubusercontent.com/69145330/95875625-7ed12280-0d72-11eb-9a0c-3bdfcd8dc339.png)

Did I get anything wrong?

Thank you

2020-10-13 14:47 UTC, PierreRambaud commented
> currently blocked by issue: #20852
> 
> <img alt="Capture d’écran 2020-09-25 à 14 27 54" width="1216" src="https://user-images.githubusercontent.com/69145330/94267097-4e4c5480-ff3b-11ea-8ca6-563ff7d5c145.png">

It looks like you have an error behind the HTTP request :thinking:

2020-11-04 16:15 UTC, RomainBocheux commented
LGTM,

Thanks @Matt75

2020-11-04 16:28 UTC, merged

2020-11-04 16:28 UTC, matks commented
Thank you @Matt75 for the PR and @RomainBocheux for the QA!