CO: fixed Link::getCategoryObject array param
PrestaShop/PrestaShop pull request #21094
Opened 2020-09-21 17:44 UTC by gfilippakis

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fixed array parameter processing in Link::getCategoryObject method.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | Context::getContext->link->getCategoryLink(array('id_category' => Category::getRootCategory()->id));

2020-09-22 07:45 UTC, Progi1984 approved these changes, later dismissed

2020-09-22 14:40 UTC, PierreRambaud approved these changes, later dismissed

2020-09-22 14:40 UTC, PierreRambaud commented
Not sure QA is needed here, it can be done by dev only.

2020-09-23 08:29 UTC, Progi1984 commented
@PrestaShop/qa-functional Ok for the QA by a dev ?

2020-09-23 09:53 UTC, SimonGrn commented
There is no linked issue.
We are okay for a dev only QA on this one.

2020-09-24 10:14 UTC, jolelievre commented
Hi @gfilippakis,

I tested your PR, it works fine to get back the correct object and its fields (rewrite, meta fields and so on) because as you spotted the array input wasn't handled correctly. However to be consistent I think you should also fix the `Category::getCategoryLink` code, the part where it gets the ID from the input:

```php
        if (!is_object($category)) {
            $params['id'] = $category;
        } else {
            $params['id'] = $category->id;
        }
```

It should handle the array just like it does in `getCategoryObject`, because with the example you provided we end up with:

```php
$params = [
    'id' => [
        'id_category' => 2,
    ]
]
```

when we would expect `$params = ['id' => 2]`

So it does work in the because the Dispatcher::createLink is able to fallback and takes the first value from the array, but it's almost out of luck. It would be more stable and more consistent to correctly retrieve the ID from the array input.

Other than that I test your fix and it works correctly:
Before url was `http://local.prestashop-develop/en/2-root` (correct ID wrong rewrite)
With you fix: `http://local.prestashop-develop/en/2-home` (all is good)

2020-09-24 10:15 UTC, jolelievre requested changes
Please also fix the `Link::getCategoryLink` function on Line 440, as explained in my comment.

2020-09-24 10:26 UTC, jolelievre commented
I also created the issue regarding this bug with steps to test and reproduce the bug 😉

2020-09-24 11:04 UTC, gfilippakis commented
> 
> 
> Hi @gfilippakis,
> 
> I tested your PR, it works fine to get back the correct object and its fields (rewrite, meta fields and so on) because as you spotted the array input wasn't handled correctly. However to be consistent I think you should also fix the `Category::getCategoryLink` code, the part where it gets the ID from the input:
> 
> ```
>         if (!is_object($category)) {
>             $params['id'] = $category;
>         } else {
>             $params['id'] = $category->id;
>         }
> ```
> 
> It should handle the array just like it does in `getCategoryObject`, because with the example you provided we end up with:
> 
> ```
> $params = [
>     'id' => [
>         'id_category' => 2,
>     ]
> ]
> ```
> 
> when we would expect `$params = ['id' => 2]`
> 
> So it does work in the because the Dispatcher::createLink is able to fallback and takes the first value from the array, but it's almost out of luck. It would be more stable and more consistent to correctly retrieve the ID from the array input.
> 
> Other than that I test your fix and it works correctly:
> Before url was `http://local.prestashop-develop/en/2-root` (correct ID wrong rewrite)
> With you fix: `http://local.prestashop-develop/en/2-home` (all is good)


Feel free to modify other methods as you deem appropriate. The bug was just too obvious to let it be.

Link class is still a mess in 1.7, so there are many ways to improve it. 
Since we're allowing different types for the $category parameter in Category::getCategoryLink, I would prefer:
```
if (Validate::isLoadedObject($category)) {
    $params['id'] = $category->id;
} elseif (is_array($category) && isset($category['id_category'])) {
    $params['id'] = $category['id_category'];
} elseif (is_integer($category)) {
    $params['id'] = $category;
}
```
for more strict type and value checking.

2020-10-12 10:39 UTC, jolelievre commented
I just pushed the improvement for `Link::getCategoryLink` This PR will need to be re-approved and then tested by a dev from @PrestaShop/prestashop-core-developers

2020-10-13 14:16 UTC, PierreRambaud commented on classes/Link.php
> +        } elseif (is_array($category) && isset($category['id_category'])) {
```suggestion
        } elseif (isset($category['id_category'])) {
```

2020-10-13 14:16 UTC, PierreRambaud commented on classes/Link.php
>              if (is_array($category) && isset($category['id_category'])) {
```suggestion
            if (isset($category['id_category'])) {
```

2020-10-13 14:17 UTC, PierreRambaud submitted a review, later dismissed

2020-10-21 08:09 UTC, sowbiba approved these changes, later dismissed

2020-10-21 08:44 UTC, Progi1984 commented
@boubkerbribri Have you got an idea why sanity tests crash : https://travis-ci.com/github/PrestaShop/PrestaShop/jobs/398861047#L1013 ?

2020-10-21 09:40 UTC, boubkerbribri commented
> @boubkerbribri Have you got an idea why sanity tests crash : https://travis-ci.com/github/PrestaShop/PrestaShop/jobs/398861047#L1013 ?

I will check this but we have the same error it all sanity tests and it means that something has changed (or gone wrong)

2020-10-21 09:55 UTC, boubkerbribri commented
@Progi1984 I found the error Why the sanity tests failed.

We have an exception when accessing the front office.

![image](https://user-images.githubusercontent.com/48441421/96704272-30380f80-1394-11eb-95c6-5de16c901328.png)


@gfilippakis Can you check the FO and fix the error please

2020-10-21 09:56 UTC, Progi1984 commented
Thanks @boubkerbribri :)

2020-10-21 10:53 UTC, gfilippakis commented
> 
> 
> @Progi1984 I found the error Why the sanity tests failed.
> 
> We have an exception when accessing the front office.
> 
> ![image](https://user-images.githubusercontent.com/48441421/96704272-30380f80-1394-11eb-95c6-5de16c901328.png)
> 
> @gfilippakis Can you check the FO and fix the error please

You should ask @jolelievre to fix his code since he added ctype_digit without really paying attention to the relevant note in [ctype_digit](https://www.php.net/manual/en/function.ctype-digit.php) .

2020-10-21 11:52 UTC, jolelievre commented
My bad I didn't check the FO indeed, I'm gonna look at it although I'm surprised why `ctype_digit` would be a bad choice it's supposed to tell if a string is composed of integers no?

2020-10-21 18:40 UTC, jolelievre commented
Hi @gfilippakis 

I just fixed it, I didn't expect ctype_digit (or even PHP) to be this strict for once ^^
So if the input was of type `int` it simply returned `false` I'll remember this one!

2020-10-22 09:05 UTC, Progi1984 approved these changes, later dismissed

2020-11-04 11:08 UTC, sowbiba submitted a review, later dismissed

2020-11-05 10:42 UTC, Progi1984 commented
@PrestaShop/qa-functional OK for QA Dev ?

2020-11-05 10:46 UTC, khouloudbelguith commented
Hi @Progi1984,

>@PrestaShop/qa-functional OK for QA Dev ?

Yes, Thank you!

2020-11-19 16:37 UTC, PierreRambaud approved these changes

2020-11-19 16:49 UTC, jolelievre approved these changes

2020-11-19 18:11 UTC, merged

2023-10-03 14:52 UTC, matosagencia reviewed
`// Set available keywords
        $params = [];
if ($category instanceof Category) {
    $params['id'] = $category->id;
} elseif (is_array($category) && isset($category['id_category'])) {
    $params['id'] = $category['id_category'];
} elseif (is_int($category) || ctype_digit($category)) {
    $params['id'] = (int) $category;
} else {
    throw new \InvalidArgumentException('Invalid category parameter');
}`

i change this because in my case i have the module pssitemap that send the values but the code link.php cannot identify if is an array correctly.