[WIP] Refactor UpdateProductSeoHandler to use ProductRepository
PrestaShop/PrestaShop pull request #21345
Opened 2020-10-07 15:11 UTC by zuk3975

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Part of product page migration. Refactor UpdateProductSeoHandler to use extra layer of domain services instead of handling domain logic 
| Type?         | refacto
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | part of #14776
| How to test?  | CI :heavy_check_mark:

2020-10-13 06:55 UTC, zuk3975 commented
rr travis

2020-11-17 16:44 UTC, matks commented on src/Adapter/Product/Update/ProductSeoInfoFiller.php
> +    public function fillRedirectOption(Product $product, RedirectOption $redirectOption): array
Suggestion:
```suggestion
    public function injectRedirectOptionIntoProduct(Product $product, RedirectOption $redirectOption): array
```

2020-11-17 16:44 UTC, matks submitted a review, later dismissed
Good for me 👍  added 1 suggestion

2020-11-17 16:52 UTC, zuk3975 commented on src/Adapter/Product/Update/ProductSeoInfoFiller.php
> +    public function fillRedirectOption(Product $product, RedirectOption $redirectOption): array
hmm sounds strange for me :thinking:

2020-11-17 16:52 UTC, zuk3975 commented
> Good for me  added 1 suggestion

So are you good with that {}InfoFiller pattern?
because that was what mainly holded this and one other PR where it was introduced.

2020-11-18 10:15 UTC, zuk3975 commented on src/Adapter/Product/Update/ProductSeoInfoFiller.php
> +    public function fillRedirectOption(Product $product, RedirectOption $redirectOption): array
This discussion was moved to slack. This is what we decided.
So the initial concern was the confusion related to name `it was unclear whether the Product or the RedirectOption is being filled`.
So if we rename the class to `ProductSeoPropertiesFiller` and the method `fillWithRedirectOption` it becomes much clearer!

2020-11-18 13:37 UTC, sowbiba submitted a review, later dismissed
LGTM

2020-11-19 10:54 UTC, Progi1984 requested changes
Please add unit tests

2020-11-23 10:42 UTC, zuk3975 commented
TODO - failing to to some caching related to ps_facetedsearch module.
Fixed in #21103

2020-11-23 14:40 UTC, Progi1984 approved these changes

2020-11-24 09:35 UTC, matks approved these changes

2020-11-24 09:35 UTC, matks commented
Thank you @zuk3975

2020-11-24 09:35 UTC, merged