[Improvement][Webservice] Enable key by hosts name or IP
PrestaShop/PrestaShop pull request #21494
Opened 2020-10-18 23:08 UTC by PululuK

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Improve the security of Web Services. In some cases a key is not enough to secure access to the API. It would be interesting to have the possibility of limiting accesses by IP address or Domain name.
| Type?         | improvement 
| Category?     | WS 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/21493
| How to test?  | See https://github.com/PrestaShop/PrestaShop/issues/21493

2020-10-19 09:53 UTC, Progi1984 commented on classes/webservice/WebserviceKey.php
> +    public static function getWebServiceObjectFromKey($auth_key)
```suggestion
    public static function getWebServiceObjectFromKey(string $auth_key): ?WebserviceKey
```

2020-10-19 09:54 UTC, Progi1984 commented on classes/webservice/WebserviceRequest.php
> +    protected function checkHostAllowed($key)
```suggestion
    protected function checkHostAllowed(string $key): bool
```

2020-10-19 09:54 UTC, Progi1984 commented on classes/webservice/WebserviceRequest.php
> +     * @return bool
```suggestion
     * Check if client hostname/ip is allowed.
     *
     * @param string $key
     *
     * @return bool
```

2020-10-19 09:55 UTC, Progi1984 commented on src/Core/Domain/Webservice/Command/AddWebserviceKeyCommand.php
> +    public function getHostsAllowed()
```suggestion
    public function getHostsAllowed(): string
```

2020-10-19 09:55 UTC, Progi1984 commented on src/Core/Domain/Webservice/Command/AddWebserviceKeyCommand.php
> +    public function getHostsCheck()
```suggestion
    public function getHostsCheck(): bool
```

2020-10-19 09:55 UTC, Progi1984 commented on src/Adapter/Webservice/CommandHandler/EditWebserviceKeyHandler.php
> +        $webserviceKey->hosts_check = (bool) $command->getHostsCheck();
```suggestion
        $webserviceKey->hosts_check = $command->getHostsCheck();
```

2020-10-19 09:55 UTC, Progi1984 commented on src/Adapter/Webservice/CommandHandler/AddWebserviceKeyHandler.php
> +        $webserviceKey->hosts_check = (bool) $command->getHostsCheck();
```suggestion
        $webserviceKey->hosts_check = $command->getHostsCheck();
```

2020-10-19 09:56 UTC, Progi1984 commented on src/Core/Domain/Webservice/Command/EditWebserviceKeyCommand.php
> +    public function getHostsAllowed()
```suggestion
    public function getHostsAllowed(): ?string
```

2020-10-19 09:56 UTC, Progi1984 commented on src/Core/Domain/Webservice/Command/EditWebserviceKeyCommand.php
> +    public function setHostsAllowed($hosts_allowed)
```suggestion
    public function setHostsAllowed(string $hosts_allowed): self
```

2020-10-19 09:57 UTC, Progi1984 commented on src/Core/Domain/Webservice/Command/EditWebserviceKeyCommand.php
> +    public function getHostsCheck()
```suggestion
    public function getHostsCheck(): ?bool
```

2020-10-19 09:57 UTC, Progi1984 commented on src/Core/Domain/Webservice/Command/EditWebserviceKeyCommand.php
> +    public function setHostsCheck($hosts_check)
```suggestion
    public function setHostsCheck(bool $hosts_check): self
```

2020-10-19 09:58 UTC, Progi1984 commented on src/Core/Domain/Webservice/QueryResult/EditableWebserviceKey.php
> +        string $hosts_allowed = null,
```suggestion
        string $hosts_allowed = '',
```

2020-10-19 09:58 UTC, Progi1984 commented on src/Core/Domain/Webservice/QueryResult/EditableWebserviceKey.php
> +    public function getHostsAllowed()
```suggestion
    public function getHostsAllowed(): string
```

2020-10-19 09:58 UTC, Progi1984 commented on src/Core/Domain/Webservice/QueryResult/EditableWebserviceKey.php
> +     * @return string|null
```suggestion
     * @return string
```

2020-10-19 09:58 UTC, Progi1984 commented on src/Core/Domain/Webservice/QueryResult/EditableWebserviceKey.php
> +     * @return bool|null
```suggestion
     * @return bool
```

2020-10-19 09:58 UTC, Progi1984 commented on src/Core/Domain/Webservice/QueryResult/EditableWebserviceKey.php
> +    public function getHostsCheck()
```suggestion
    public function getHostsCheck(): bool
```

2020-10-19 10:00 UTC, Progi1984 commented on src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Webservice/WebserviceKeyType.php
> +                    'placeholder' => 'www.prestashop.com, 42.24.4.2,127.0.0.1,99.98.97.96',
```suggestion
                    'placeholder' => 'www.prestashop.com, 42.24.4.2, 127.0.0.1, 99.98.97.96',
```

2020-10-19 10:00 UTC, Progi1984 commented on src/Core/Domain/Webservice/Command/AddWebserviceKeyCommand.php
> +        string $hosts_allowed = null,
```suggestion
        string $hosts_allowed = '',
```

2020-10-19 10:03 UTC, Progi1984 commented on src/Core/Domain/Webservice/Command/EditWebserviceKeyCommand.php
> +    private $hosts_check;
```suggestion
    /**
     * @var string
     */
    private $hosts_allowed = '';

    /**
     * @var bool
     */
    private $hosts_check = false;
```

2020-10-19 10:03 UTC, Progi1984 commented on src/Core/Domain/Webservice/Command/EditWebserviceKeyCommand.php
> +    }
```suggestion
    /**
     * @return string
     */
    public function getHostsAllowed(): string
    {
        return $this->hosts_allowed;
    }
```

2020-10-19 10:04 UTC, Progi1984 commented on src/Core/Domain/Webservice/Command/EditWebserviceKeyCommand.php
> +    }
```suggestion
    /**
     * @return bool
     */
    public function getHostsCheck(): bool
    {
        return $this->hosts_check;
    }
```

2020-10-19 10:04 UTC, Progi1984 reviewed
Some Type Hints

2020-10-19 10:14 UTC, PululuK commented
> Some Type Hints

Thank you very much @Progi1984

2020-10-19 11:33 UTC, Progi1984 approved these changes, later dismissed

2020-10-27 10:31 UTC, Julievrz commented
Hello @PululuK 😄 Are you done with the wording of this PR? I saw on the issue that it was said that it could be good to have a wording displayed above "Enable hosts check" to explain the feature. I would be happy to help you with this but I would need more information as it is a more technical feature...

2020-10-31 19:45 UTC, kpodemski commented
Hey @PululuK it's still `WIP`?

2020-10-31 19:46 UTC, PululuK commented
> Hey @PululuK it's still `WIP`?

Yes ! Sorry I forgot to add WIP tag

2020-11-01 00:03 UTC, PululuK commented
> Hey @PululuK it's still `WIP`?

@kpodemski ready for reviews 🧐

2020-11-02 13:04 UTC, Progi1984 commented on classes/webservice/WebserviceRequest.php
> +                        $this->setError(503, 'No permission for this host authentication', 666);
:imp:

2020-11-02 13:05 UTC, Progi1984 commented on src/Adapter/Webservice/WebserviceKeyHostsCheckModifier.php
> +namespace PrestaShop\PrestaShop\Adapter\Webservice;
```suggestion
 */
 
declare(strict_types=1);

namespace PrestaShop\PrestaShop\Adapter\Webservice;
```

2020-11-02 13:07 UTC, Progi1984 reviewed
A small feedback but it's ok

2020-11-02 13:08 UTC, Progi1984 approved these changes

2020-11-16 14:08 UTC, PierreRambaud requested changes
Discussion in progress in the issue.

2020-11-27 10:33 UTC, Julievrz commented
@MatShir Is this PR closed too?

2020-11-27 10:35 UTC, PululuK commented
> @MatShir Is this PR closed too?

Yes @Julievrz

2020-11-27 10:35 UTC, closed without merging