Move product canonical url from tpl to controller
PrestaShop/PrestaShop pull request #21729
Opened 2020-11-03 10:06 UTC by micka-fdz

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR moves product canonical url on ProductController.
| Type?         | improvement / bug fix
| Category?     | FO
| BC breaks?    | -
| Deprecations? | -
| Fixed ticket? | Fixes #21152
| How to test?  | Go to product page and see canonical url in `<head>` section.

Original PR: #21154

2020-11-04 09:59 UTC, Progi1984 commented on controllers/front/ProductController.php
> +    public function getCanonicalUrl()
```suggestion
    public function getCanonicalUrl(): string
```

2020-11-04 09:59 UTC, Progi1984 reviewed
A small change for improving typing

2020-11-09 11:00 UTC, NeOMakinG approved these changes, later dismissed

2020-11-09 15:49 UTC, Progi1984 submitted a review, later dismissed

2020-11-12 13:37 UTC, PierreRambaud commented on controllers/front/ProductController.php
> +        $product = $this->context->smarty->getTemplateVars('product');
```suggestion
        $product = $this->context->smarty->getTemplateVars('product');
        if (!($product instanceof Product)) {
            return;
        }
```

Make sure the var has the good type. We should never trust and array nor an stdClass.

2020-11-12 13:37 UTC, PierreRambaud requested changes
One little thing

2020-11-13 15:32 UTC, SD1982 commented
HI @micka-fdz it seems there is an error with travis can you please check to fix it ?

2020-11-19 09:16 UTC, Progi1984 approved these changes, later dismissed

2020-11-19 09:46 UTC, PierreRambaud approved these changes, later dismissed

2020-11-19 09:51 UTC, Progi1984 commented
@SD1982 It's good.

2020-11-19 10:54 UTC, NeOMakinG approved these changes, later dismissed

2020-12-11 09:59 UTC, SD1982 commented
Hi @micka-fdz I don't see the cannonical url with or without your PR
I have the followings results 
- Classic theme  without PR => canonical url correctly displayed on product page
- Child theme without PR =>  canonical url is not displayed on product page
- Child theme with PR =>  canonical url is not displayed on product page
- Classic theme with PR =>  canonical url is not displayed on product page

I used this zip for the child theme => [childtheme-example.zip](https://github.com/PrestaShop/PrestaShop/files/5678440/childtheme-example.zip)

These results are also confirmed by @khouloudbelguith !!

2020-12-11 11:47 UTC, micka-fdz commented
Hi @SD1982, indeed I've just tested again and it doesn't work anymore.

Apparently, this is because of the addition of @PierreRambaud's condition. Where is the mistake?
https://github.com/PrestaShop/PrestaShop/blob/c5606039779ebbda5193922793a3b849ffdcac9a/controllers/front/ProductController.php#L90-L92

2020-12-11 14:56 UTC, PierreRambaud commented
> Hi @SD1982, indeed I've just tested again and it doesn't work anymore.
> 
> Apparently, this is because of the addition of @PierreRambaud's condition. Where is the mistake?
> https://github.com/PrestaShop/PrestaShop/blob/c5606039779ebbda5193922793a3b849ffdcac9a/controllers/front/ProductController.php#L90-L92

Yes the type is not Product but ProductLazyArray, I fixed it.

2020-12-11 14:57 UTC, PierreRambaud approved these changes

2020-12-11 14:57 UTC, PierreRambaud commented
And also fix the method name which is `getCanonicalURL` instead of `getCanonicalUrl`

2020-12-11 14:58 UTC, PululuK approved these changes

2020-12-16 09:49 UTC, SD1982 commented
LGTM now Thanks @micka-fdz !!

2020-12-16 09:52 UTC, merged

2020-12-16 09:52 UTC, Progi1984 commented
Thanks @micka-fdz & @SD1982