Fix order detail total amount update when rounding is per item
PrestaShop/PrestaShop pull request #21988
Opened 2020-11-18 16:38 UTC by matthieu-rolland

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | In the `OrderAmountUpdater` service, the `total_price_tax_incl` amount per order detail was not calculated correctly
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21717
| How to test?  | See steps in issue #21717

2020-11-19 10:18 UTC, Progi1984 reviewed
Need a test (behat or unit) please

2020-11-19 10:23 UTC, matthieu-rolland commented
> Need a test (behat or unit) please

yep it's coming !

2020-11-24 08:38 UTC, Progi1984 submitted a review, later dismissed

2020-11-24 11:12 UTC, atomiix commented on tests/Integration/Behaviour/Features/Scenario/Order/order_shipping.feature
> +  Scenario: In rounding per item mode, I use and address without taxes (no order_detail_tax created), then I change to a country with taxes all is correctly computed
```suggestion
  Scenario: In rounding per item mode, I use an address without taxes (no order_detail_tax created), then I change to a country with taxes all is correctly computed
```

2020-11-24 14:30 UTC, matks approved these changes

2020-11-25 09:16 UTC, Progi1984 approved these changes

2020-12-01 09:52 UTC, SD1982 commented
LGTM Thanks @matthieu-rolland !!

2020-12-01 09:55 UTC, Progi1984 requested changes
## DONT MERGE BEFORE 177X RELEASE

2020-12-03 09:00 UTC, Progi1984 approved these changes

2020-12-03 09:03 UTC, merged

2020-12-03 09:03 UTC, Progi1984 commented
Thanks @matthieu-rolland & @SD1982