Changelog v1.7.7.0
PrestaShop/PrestaShop pull request #22064
Opened 2020-11-23 17:25 UTC by jolelievre

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Update Changelog v1.7.7.0
| Type?         | new feature
| Category?     | PM
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | ~
| How to test?  | ~

2020-11-23 17:31 UTC, matks approved these changes

2020-11-23 17:33 UTC, matks submitted a review, later dismissed
I block this PR to make sure nobody merges it by mistake

2020-11-23 17:39 UTC, eternoendless commented on docs/CHANGELOG.txt
> +    - #21158:  Bump version to 1.7.6.8 in the installer (by @PierreRambaud)
You can remove this one

2020-11-24 08:23 UTC, Progi1984 submitted a review, later dismissed

2020-11-26 17:42 UTC, eternoendless requested changes
LGTM, but do not merge yet!

2020-11-30 09:29 UTC, eternoendless submitted a review, later dismissed
LGTM, wait for validation

2020-12-02 15:44 UTC, Progi1984 approved these changes

2020-12-02 15:45 UTC, atomiix approved these changes

2020-12-02 15:45 UTC, merged

2020-12-02 15:45 UTC, NeOMakinG approved these changes

2020-12-02 16:04 UTC, eternoendless commented
<img src="https://media.giphy.com/media/26h0pHNtHKjmDo4WQ/giphy.gif">

2020-12-02 16:17 UTC, PululuK commented
<img src="https://media.giphy.com/media/wT2aY2Gikd3MY/source.gif">