Fix employee filter for the Logs page
PrestaShop/PrestaShop pull request #22099
Opened 2020-11-25 14:12 UTC by atomiix

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Because of bad allowed filter list it was impossible to filter Logs by employees. This PR fixes it.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #22078 
| How to test?  | Please see #22078

2020-11-25 14:20 UTC, PululuK commented
See please https://github.com/PrestaShop/PrestaShop/pull/21075  **Bugs fix** section

2020-11-25 14:20 UTC, Progi1984 approved these changes

2020-11-25 15:12 UTC, atomiix commented
@PululuK we're not targeting the same branch so I think we can keep both our PRs but thanks for informing us that your PR fixes that issue too 👍

2020-11-25 15:33 UTC, PululuK commented
> @PululuK we're not targeting the same branch so I think we can keep both our PRs but thanks for informing us that your PR fixes that issue too 

You are right, sorry !
But IMO, wee need to use a `LogQueryBuilder` instead of `LogRepository` 😔
It's not your fault, and it's outside the scope of your PR, so it is Ok for me !

2020-11-30 08:06 UTC, matthieu-rolland approved these changes

2020-12-01 10:01 UTC, khouloudbelguith commented
Hi @atomiix,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1HVPQSmn49NzLoXljiXXqlPkZxCybW71A/view?usp=sharing

Thanks!

2020-12-01 10:06 UTC, Progi1984 requested changes
## DONT MERGE BEFORE 177X RELEASE

2020-12-03 08:59 UTC, Progi1984 approved these changes

2020-12-03 09:01 UTC, PululuK approved these changes

2020-12-03 09:06 UTC, merged

2020-12-03 09:06 UTC, Progi1984 commented
Thanks @atomiix & @khouloudbelguith