Fix product selections when creating/updating tags
PrestaShop/PrestaShop pull request #22101
Opened 2020-11-25 14:38 UTC by atomiix

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | In the Tag page, multiple select options must be all selected before the form is submit in order to be sent by the browser and since we updated jQuery, this selection should be done using `prop` instead of `attr`.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #22092
| How to test?  | Please see #22092

2020-11-25 14:46 UTC, NeOMakinG approved these changes, later dismissed

2020-11-25 14:47 UTC, PululuK submitted a review, later dismissed

2020-11-26 14:07 UTC, khouloudbelguith commented
Hi @atomiix,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1RscO61kz3DlRWo9v49K1FIrJZQw-SeXx/view?usp=sharing

Thanks!

2020-11-26 14:11 UTC, Progi1984 commented
## DO NOT MERGE BEFORE THE RELEASE OF 1.7.7.0

2020-11-26 17:23 UTC, PierreRambaud requested changes, later dismissed
Don't merge before the release of 1770

2020-12-03 09:08 UTC, Progi1984 commented
@atomiix Could you rebase your PR :) ?

2020-12-03 09:22 UTC, atomiix commented
@Progi1984 you meant changing the base branch right? Because I don't think I need to rebase as there is no conflict.

2020-12-03 09:24 UTC, Progi1984 approved these changes

2020-12-03 09:26 UTC, PululuK approved these changes

2020-12-03 09:57 UTC, merged

2020-12-03 09:57 UTC, Progi1984 commented
Thanks @atomiix & @khouloudbelguith