Fix database creation doc url in install process
PrestaShop/PrestaShop pull request #22147
Opened 2020-11-27 22:39 UTC by PululuK

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | This change fixes minor code issues I found while working on another bug.
| Type?         |  improvement 
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | N/A.
| How to test?  | N/A.

2020-11-29 17:39 UTC, Arman-Hosseini approved these changes

2020-11-29 22:18 UTC, matks commented on app/Resources/translations/default/Install.xlf
> +        <source><![CDATA[To use PrestaShop, you must <a href="https://devdocs.prestashop.com/1.7/basics/installation/localhost/#creating-a-database-for-your-shop" target="_blank">create a database</a
Indeed this link is old but I think the right link is rather https://doc.prestashop.com/display/PS17/Installing+PrestaShop#InstallingPrestaShop-Creatingadatabaseforyourshop

devdocs.prestashop.com is the developer documentation while doc.prestashop.com is the user (merchant) documentation. The installer aims for users I believe 🤔 (@LouiseBonnard please tell me if I got it wrong)

2020-11-30 08:12 UTC, Progi1984 requested changes
@PululuK Could you extract the link from the translated string ? (sprint use)

2021-08-04 08:27 UTC, matks commented
Hello @PululuK what do we do about this PR 😉  ?

2021-11-08 15:13 UTC, PierreRambaud commented
Hi @PululuK ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2021-11-08 15:13 UTC, closed without merging