When refreshing an order, display shipping price if needed
PrestaShop/PrestaShop pull request #22171
Opened 2020-12-01 14:28 UTC by Progi1984

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       |  1.7.7.x
| Description?  | When refreshing an order, display shipping price if needed
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #22071
| How to test?  | Cf. #22071

2020-12-01 16:33 UTC, NeOMakinG requested changes

2020-12-01 16:33 UTC, NeOMakinG commented on admin-dev/themes/new-theme/js/pages/order/view/order-prices-refresher.js
> +      console.log($(OrderViewPageMap.orderShippingTotalContainer));
```suggestion
```

2020-12-03 15:57 UTC, matthieu-rolland reviewed
Apparently, it's breaking a sanity test...

2020-12-04 15:51 UTC, NeOMakinG commented
> Apparently, it's breaking a sanity test...

Looks unrelated

2020-12-10 09:21 UTC, atomiix submitted a review, later dismissed

2020-12-10 09:26 UTC, NeOMakinG submitted a review, later dismissed

2020-12-10 11:57 UTC, khouloudbelguith commented
Hi @Progi1984,

I have an error following these steps:

1. Create an order from the FO with two different products
2. In the Shipping steps " choose a carrier with fees (not free)"
3. In BO > Orders > last order created page
4. Delete a product
5. see the error
6. The shipping is not displayed(it is removed)
![image](https://user-images.githubusercontent.com/16067358/101768652-2609d600-3ae6-11eb-858f-52cbfdc2ac3c.png)
7. Reload the page => ok
![image](https://user-images.githubusercontent.com/16067358/101769420-38384400-3ae7-11eb-8228-2309c256bcb9.png)


I have an issue also following these steps:

1. Create an order from the FO with only one product (not a virtual product)
2. In the Shipping steps " choose a carrier with fees (not free)"
3. In BO > Orders > last order created page > Delete the product and refresh: The order is empty
4. Add a new virtual product (`demo_19`) to the order
5. See error => the Shipping is displayed (price => ok)
![image](https://user-images.githubusercontent.com/16067358/101769184-e0014200-3ae6-11eb-9088-97c16fb339fc.png)
6. Reload the page => ok
![image](https://user-images.githubusercontent.com/16067358/101769247-f909f300-3ae6-11eb-9926-272a45e8dce9.png)


Thanks!

2020-12-14 14:53 UTC, atomiix approved these changes

2020-12-14 15:15 UTC, PierreRambaud approved these changes

2020-12-15 11:08 UTC, khouloudbelguith commented
Hi @Progi1984,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1bIPWZLMr7iY_C89ewzocZd0RY-10Ecpo/view?usp=sharing

Thanks!

2020-12-15 12:28 UTC, merged

2020-12-15 12:28 UTC, Progi1984 commented
Thanks @khouloudbelguith