Backport UI tests
PrestaShop/PrestaShop pull request #22172
Opened 2020-12-01 14:33 UTC by boubkerbribri

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | BackPort tests that exist on develop on 1.7.7.x
| Type?         | refacto
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | Nightly should be green

2020-12-01 14:52 UTC, Progi1984 requested changes
## DONT MERGE BEFORE RELEASE 1770

2020-12-01 14:56 UTC, SimonGrn approved these changes

2020-12-03 09:31 UTC, Progi1984 approved these changes

2020-12-03 10:50 UTC, PierreRambaud approved these changes

2020-12-03 10:56 UTC, merged