Fix numeric_iso_code in the upgrade to 1.7.7.1
PrestaShop/PrestaShop pull request #22214
Opened 2020-12-03 12:32 UTC by atomiix

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Since 1.7.7.0, currency's `numeric_iso_code` should be 3 characters long. This PR aims to update older `numeric_iso_code` that were 2 characters long by prepending them with a '0' during the upgrade process.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #22208
| How to test?  | 1. Install a 1.7.6 shop<br>2. Add the DZD currency<br>3. Either make a 1.7.7.1 build with this PR and upgrade to it or Checkout the 1.7.7.x branch with this PR, update `_PS_INSTALL_VERSION_` in `install-dev/install_version` to `1.7.7.1` and run `php install-dev/upgrade/upgrade.php`<br>4. You should be able to edit/delete the DZD currency without any error

2020-12-03 15:50 UTC, matthieu-rolland submitted a review, later dismissed

2020-12-03 17:03 UTC, eternoendless approved these changes, later dismissed

2020-12-04 09:19 UTC, PierreRambaud commented on install-dev/upgrade/sql/1.7.7.1.sql
> +UPDATE `PREFIX_currency` SET numeric_iso_code = CONCAT('0', numeric_iso_code) WHERE LENGTH(numeric_iso_code) = 2;
```suggestion
UPDATE `PREFIX_currency` SET numeric_iso_code = LPAD(numeric_iso_code, 3, '0') WHERE LENGTH(numeric_iso_code) != 3;
```
What about numeric_iso_code before 10 :trollface:

2020-12-04 09:20 UTC, PierreRambaud requested changes
One thing we missed

2020-12-04 09:25 UTC, PierreRambaud approved these changes

2020-12-04 15:08 UTC, jolelievre approved these changes

2020-12-08 15:38 UTC, SD1982 commented
LGTM !!
Versions tested ( multiple time):
from 1.7.6.9 => php 7.1 , mysql 5.7
from 1.7.6.9 => php 7.1 , mariadb 10.1
from 1.7.6.5 => php 7.1 , mysql 5.7

Thanks @atomiix !!

2020-12-08 16:07 UTC, merged

2020-12-08 16:07 UTC, Progi1984 commented
Thanks @atomiix & @SD1982