Update OrderHistory.php
PrestaShop/PrestaShop pull request #22219
Opened 2020-12-03 13:53 UTC by timactive

Move this hook after the quantity has updated.
Permit to have the quantity reserved, available, physiq  actualized
We develop a module for a client and i wish to have physical quantity value actualized after hook Strange to have the hook call actionOrderStatusPostUpdate before the process has completed.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch       | develop / 1.7.7.x
| Description  | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type         | improvement
| Category     | CO
| BC breaks    | no
| Deprecations | no
| Fixed ticket | Fixes #22218
| How to test  | Go to your order change status of order

2020-12-04 10:45 UTC, PierreRambaud requested changes
Hi and thanks for your contribution, Please take time to properly complete the table in your message :wink:

2020-12-04 11:17 UTC, matthieu-rolland reviewed
Thank you for your contribution @timactive !

Code wise the fix is OK, but the product team has been tagged in the issue, we'll wait for their feedback before approving anything ;)

2020-12-04 17:20 UTC, timactive commented
@PierreRambaud i update the description in table, i think look good
@matthieu-rolland  ok

Thks

2020-12-07 09:29 UTC, Progi1984 commented
@timactive Thanks ! Could add a scenario for testing, please ?

2020-12-07 09:42 UTC, timactive commented
@Progi1984 Updated. Let me know.

2020-12-07 09:52 UTC, Progi1984 commented
@timactive Could you provide a module or an example with ps_qualityassurance like in #20207 for testing hooks ?

2020-12-07 10:54 UTC, timactive commented
Thanks @Progi1984 nice work, I will do it in my free time.

2021-03-25 14:14 UTC, marionf commented
Hello @timactive 

As requested by @MatShir we need some informations about this PR :)

https://github.com/PrestaShop/PrestaShop/issues/22218#issuecomment-759169480

Should we have a hook before and after actually. I can see many use cases to have the need to have before and after. And I'm afraid that it could be considered as BC since this hook has here for a long time, isn't it?
WDYT?

2021-09-21 08:30 UTC, matks commented
Hello everyone looks like this PR is now stale.

I close this PR, following our [review guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/) "Pull Requests may be closed after 30 days of inactivity".

**If however you are still interested in it, please ping us :) we can reopen.**

Thank you for your contribution.

2021-09-21 08:30 UTC, closed without merging