Allow displaying html in customization summary
PrestaShop/PrestaShop pull request #22227
Opened 2020-12-03 18:00 UTC by unlocomqx

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Allow modules to display a html summary of the customization in the admin order/carts page
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #22220 
| How to test?  | Repro step described in issue

- Customization are already sanitized when saved by the customer
- Modules using the hook `displayCustomization` may return html so we need to display the customization value as is

2020-12-04 10:31 UTC, NeOMakinG commented
@PierreRambaud what do you think about this?

2020-12-04 10:36 UTC, PierreRambaud requested changes
I'm not in favor of this change, it leads to XSS injection.
If your module needs this change, it's up to it to change blocks and do the job.

2020-12-04 10:40 UTC, unlocomqx commented
@PierreRambaud The customization is already sanitized on save btw, wouldn't that be enough protection?

2020-12-07 13:08 UTC, PierreRambaud commented
> @PierreRambaud The customization is already sanitized on save btw, wouldn't that be enough protection?

We should be able to save whatever we want in customization.
For example in the fixtures, we have a customizable Mug, Imho I should be able to add "I <3 U mom" or "I love <html>" and it shouldn't be sanitized. This is the reason why I'm against adding `raw`.

2020-12-07 13:10 UTC, unlocomqx commented
@PierreRambaud It makes sense, thank you
I will find another way then,
Cheers

2020-12-07 13:10 UTC, closed without merging