Test checkbox field value before set to false
PrestaShop/PrestaShop pull request #22285
Opened 2020-12-08 11:54 UTC by micka-fdz

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | -
| Deprecations? | -
| Fixed ticket? | Fixes #9739
| How to test?  | Try to use `setValue(1)` on custom checkbox field to check it(see https://devdocs.prestashop.com/1.7/modules/concepts/forms/)

All credits to @tfayolle for this correction. Thanks to him.

2020-12-08 13:25 UTC, matks approved these changes
Hi! the code looks good but would it be possible to provide a small module example? The QA team will need something they can work with to validate there is no regression.

2020-12-08 13:40 UTC, micka-fdz commented
Hi @matks. We can quickly test this PR with `ps_emailsubscription` module.

1. Open `modules/ps_emailsubscription/ps_emailsubscription.php`
2. Search `->setType('checkbox')` (line 989)
3. Add `->setValue(1)` on new line
4. Check on registration page that newsletter checkbox is checked by default

2020-12-09 08:11 UTC, Progi1984 approved these changes

2020-12-09 10:07 UTC, matthieu-rolland approved these changes

2020-12-09 16:55 UTC, PierreRambaud requested changes
I think there is another problem with this `setValue`. We are not setting a value here, we are just defined if the input is checked or not, the value doesn't change :thinking:

2020-12-09 17:02 UTC, PierreRambaud approved these changes

2020-12-09 17:03 UTC, PierreRambaud commented
Ok, the whole Form field behavior is totally broken. They used `$field.availableValues.placeholder` or `$field.availableValues.comment`, there is no way to check if the value is properly checked, used only by its value :scream:

2020-12-09 17:09 UTC, merged

2020-12-09 17:09 UTC, PierreRambaud commented
Thank you @micka-fdz

2024-11-04 14:22 UTC, imballo commented
It is broken. It does not change the value if it start as checked.
To make it work we must check if it is a submitCreate.

                if (Tools::isSubmit('submitCreate')){
                    $field->setValue(false);
                } elseif (empty($field->getValue())) {
                    $field->setValue(false);
                }