Get rid of empty string of redirect type from database structure [product page migration]
PrestaShop/PrestaShop pull request #22378
Opened 2020-12-11 18:10 UTC by zuk3975

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Related to PR - https://github.com/PrestaShop/PrestaShop/pull/20473. We did get rid of empty string as redirect_type everywhere in code, this PR takes care of sql upgrade and sql structure. We didn't discuss it yet, it is also an option to leave it unchanged to avoid BC breaks and maybe remove it in some later versions :man_shrugging: 
| Type?         | refacto
| Category?     | BO
| BC breaks?    | yes
| Deprecations? | no
| Fixed ticket? | part of #14776
| How to test?  | Needs to perform version upgrade from to from 1.7.7 to 1.7.8

**BC BREAKS**
removes EVAL `''` from product.redirect_type

2020-12-14 08:33 UTC, Progi1984 approved these changes

2020-12-14 08:47 UTC, Progi1984 requested changes
Travis is completely broken.

2020-12-14 15:23 UTC, PierreRambaud commented on install-dev/data/db_structure.sql
>    ) NOT NULL DEFAULT '',
You need to change the DEFAULT here too

2020-12-14 15:23 UTC, PierreRambaud requested changes
The update script is not the same as the db_structure

2020-12-15 08:26 UTC, Progi1984 approved these changes, later dismissed

2020-12-16 09:27 UTC, matthieu-rolland approved these changes, later dismissed

2020-12-16 16:24 UTC, PierreRambaud approved these changes, later dismissed

2020-12-22 10:27 UTC, SD1982 commented
Hi @zuk3975 I have thiis error during the upgrade process

`[INTERNAL] /var/www/html/ps177PR2/app/AppKernel.php line 39 - ParseError: syntax error, unexpected ';' #0 /var/www/html/ps177PR2/modules/autoupgrade/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/html/p...') #1 [internal function]: Composer\Autoload\ClassLoader->loadClass('AppKernel') #2 /var/www/html/ps177PR2/config/autoload.php(28): spl_autoload_call('AppKernel') #3 /var/www/html/ps177PR2/modules/autoupgrade/classes/UpgradeContainer.php(545): require_once('/var/www/html/p...') #4 /var/www/html/ps177PR2/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(73): PrestaShop\Module\AutoUpgrade\UpgradeContainer->initPrestaShopAutoloader() #5 /var/www/html/ps177PR2/admin-dev/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->init() #6 {main}`

It's probably related to the confliciting file can you check to fix the confilct please ?

2020-12-24 14:38 UTC, PierreRambaud commented
> Hi @zuk3975 I have thiis error during the upgrade process
> 
> `[INTERNAL] /var/www/html/ps177PR2/app/AppKernel.php line 39 - ParseError: syntax error, unexpected ';' #0 /var/www/html/ps177PR2/modules/autoupgrade/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/html/p...') #1 [internal function]: Composer\Autoload\ClassLoader->loadClass('AppKernel') #2 /var/www/html/ps177PR2/config/autoload.php(28): spl_autoload_call('AppKernel') #3 /var/www/html/ps177PR2/modules/autoupgrade/classes/UpgradeContainer.php(545): require_once('/var/www/html/p...') #4 /var/www/html/ps177PR2/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(73): PrestaShop\Module\AutoUpgrade\UpgradeContainer->initPrestaShopAutoloader() #5 /var/www/html/ps177PR2/admin-dev/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->init() #6 {main}`
> 
> It's probably related to the confliciting file can you check to fix the confilct please ?

I confirm it's related to the conflict :sweat:

2021-01-04 10:34 UTC, PierreRambaud approved these changes

2021-01-04 17:36 UTC, atomiix approved these changes

2021-01-05 14:58 UTC, SD1982 commented
Hi @zuk3975 I still have an error during the upgrade process
`[INTERNAL] /var/www/html/ps177/app/AppKernel.php line 39 - ParseError: syntax error, unexpected ';' #0 /var/www/html/ps177/modules/autoupgrade/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/html/p...') #1 [internal function]: Composer\Autoload\ClassLoader->loadClass('AppKernel') #2 /var/www/html/ps177/config/autoload.php(28): spl_autoload_call('AppKernel') #3 /var/www/html/ps177/modules/autoupgrade/classes/UpgradeContainer.php(545): require_once('/var/www/html/p...') #4 /var/www/html/ps177/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(73): PrestaShop\Module\AutoUpgrade\UpgradeContainer->initPrestaShopAutoloader() #5 /var/www/html/ps177/admin-dev/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->init() #6 {main}`

![image](https://user-images.githubusercontent.com/40635814/103661162-bf55cc00-4f6e-11eb-80c4-08389e39bbda.png)

2021-01-05 15:03 UTC, PierreRambaud commented
> Hi @zuk3975 I still have an error during the upgrade process
> `[INTERNAL] /var/www/html/ps177/app/AppKernel.php line 39 - ParseError: syntax error, unexpected ';' #0 /var/www/html/ps177/modules/autoupgrade/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/html/p...') #1 [internal function]: Composer\Autoload\ClassLoader->loadClass('AppKernel') #2 /var/www/html/ps177/config/autoload.php(28): spl_autoload_call('AppKernel') #3 /var/www/html/ps177/modules/autoupgrade/classes/UpgradeContainer.php(545): require_once('/var/www/html/p...') #4 /var/www/html/ps177/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(73): PrestaShop\Module\AutoUpgrade\UpgradeContainer->initPrestaShopAutoloader() #5 /var/www/html/ps177/admin-dev/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->init() #6 {main}`
> 
> ![image](https://user-images.githubusercontent.com/40635814/103661162-bf55cc00-4f6e-11eb-80c4-08389e39bbda.png)

Did you fetch the right branch without conflicts? Because I don't see how it could be related to this PR :sweat_smile:

2021-01-06 07:49 UTC, SD1982 commented
Yes I think I tested with the right branch but if in doubt I will redo the whole procedure from the beginning just to be sure

2021-01-06 09:56 UTC, SD1982 commented
I restarted the process from the beginning and I still have the same error
Step followed:
- install the PR on develop
- create a build
- install 1.7.7.1 branch
- try to upgrade

2021-01-06 12:55 UTC, zuk3975 commented
I've successfully upgraded using CLI script ( `install-dev/upgrade/upgrade.php`). 
I don't know how to provoke 1click module upgrade from UI :man_shrugging:

2021-01-06 13:24 UTC, matks commented
> I've successfully upgraded using CLI script ( `install-dev/upgrade/upgrade.php`).
> I don't know how to provoke 1click module upgrade from UI 🤷‍♂️
> ![Screenshot from 2021-01-06 14-56-02](https://user-images.githubusercontent.com/31609858/103770849-5d10d000-502f-11eb-950b-b6b226a32c49.png)

See https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/use-autoupgrade-module/ 😄

2021-01-06 15:03 UTC, jolelievre approved these changes
I think this BC break is acceptable

2021-01-07 09:01 UTC, Progi1984 approved these changes

2021-01-12 13:29 UTC, SD1982 commented
Hi @zuk3975 I don't know why but I still have the error during the upgrade procedure so it's @khouloudbelguith  who performed the PR test and everything seems ok
Thank you @zuk3975 !!

2021-01-12 13:30 UTC, merged

2021-01-12 13:30 UTC, PierreRambaud commented
Thank you @zuk3975