Improve multiple choice table : Add option to keep table heads fixed
PrestaShop/PrestaShop pull request #22462
Opened 2020-12-16 21:53 UTC by PululuK

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | When we have very large tables, we have to scroll to see the last options, except that the headers are no longer visible, so it becomes difficult to know how to choose an option. For more details see https://github.com/PrestaShop/PrestaShop/issues/22461
| Type?         | improvement
| Category?     | BO / CO 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/22461
| How to test?  | See https://github.com/PrestaShop/PrestaShop/issues/22461

2020-12-16 22:45 UTC, kpodemski commented
This is really useful! Good job @PululuK

2020-12-16 22:45 UTC, kpodemski approved these changes, later dismissed

2020-12-17 09:00 UTC, matthieu-rolland reviewed
Very nice ! 
We'll just wait for product team feedback before sending the PR to QA 👍

2020-12-23 14:44 UTC, PierreRambaud approved these changes, later dismissed
I approve but if @NeOMakinG can have a look about css :)

2020-12-23 15:34 UTC, NeOMakinG submitted a review, later dismissed

2020-12-23 16:39 UTC, kpodemski approved these changes, later dismissed

2020-12-24 09:21 UTC, Progi1984 requested changes
Sorry @PululuK : could you rebase your PR and remove your merge commit, please ?

2020-12-24 11:04 UTC, Progi1984 submitted a review, later dismissed

2020-12-24 13:13 UTC, NeOMakinG approved these changes, later dismissed

2020-12-24 15:13 UTC, PierreRambaud submitted a review, later dismissed

2021-01-04 16:36 UTC, SD1982 commented
Hi @PululuK I still have the "scroll" off the header in the webservice form ( set to "true" )
https://drive.google.com/file/d/1AlM0e5WEWDpQXnPXKGrXjVV09ne-wAm5/view?usp=sharing
It's ok with the "country restrictions" ,  "currency restrictions", "group restrictions" tab in "payment preferences" ( not tested "carriers restrictions")

2021-01-04 17:19 UTC, PululuK commented
> Hi @PululuK I still have the "scroll" off the header in the webservice form ( set to "true" )
> https://drive.google.com/file/d/1AlM0e5WEWDpQXnPXKGrXjVV09ne-wAm5/view?usp=sharing
> It's ok with the "country restrictions" , "currency restrictions", "group restrictions" tab in "payment preferences" ( not tested "carriers restrictions")

Done ! Thank you @SD1982  and sorry

2021-01-05 08:45 UTC, NeOMakinG approved these changes

2021-01-05 09:33 UTC, SD1982 commented
LGTM now !!
**Tested:**
All the "payment preferences" form
And the "web service" form
Try with with both "true and false" possibility for the "header_fixed" option 
**"header_fixed" set to false**
https://drive.google.com/file/d/1HIRoCpJh_GbOjsIYD63KG2rNwHjtlMqp/view?usp=sharing
**"header_fixed"  set to true**
https://drive.google.com/file/d/1sWJWNSinbeb9HiWdeFLpTw9g_ObzLCXt/view?usp=sharing

Thanks @PululuK !!

2021-01-05 09:48 UTC, PierreRambaud approved these changes

2021-01-05 09:48 UTC, merged

2021-01-05 09:48 UTC, PierreRambaud commented
Thank you @PululuK