Handle case where product location is a boolean
PrestaShop/PrestaShop pull request #22542
Opened 2020-12-22 14:19 UTC by atomiix

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | In multistore context, prodcut location can return a boolean. That was not handle when searching for a product when creating an order in the BO. This PR fixes it.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #22460
| How to test?      | See #22460
| Possible impacts? | Nothing more than the original ticket

2020-12-22 14:39 UTC, Progi1984 approved these changes, later dismissed

2020-12-22 14:40 UTC, PululuK submitted a review, later dismissed

2020-12-22 15:56 UTC, jolelievre requested changes

2020-12-22 15:56 UTC, jolelievre commented on src/Adapter/Product/QueryHandler/SearchProductsHandler.php
> +            $product->location ?: '',
I think this should be fixed in `Product::loadStockData` instead It will fix more use cases

2020-12-22 17:18 UTC, jolelievre approved these changes

2020-12-22 17:22 UTC, matks approved these changes

2020-12-23 10:19 UTC, khouloudbelguith commented
Hi @atomiix,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1IntDdKJd8gJs7jiRJpcKGqVd4W4YZIBz/view?usp=sharing

Thanks!

2020-12-23 14:38 UTC, Progi1984 requested changes
## DONT MERGE BEFORE RELEASE 1.7.7.1

2021-01-12 09:33 UTC, Progi1984 approved these changes

2021-01-12 10:07 UTC, merged