fix multi carrier not displayed
PrestaShop/PrestaShop pull request #22583
Opened 2020-12-24 10:57 UTC by JeromeFarin

2020-12-24 14:50 UTC, PierreRambaud commented on classes/checkout/CheckoutDeliveryStep.php
> +                $isModule = true;
```suggestion
                $isModule = true;
                break;
```
No need to continue if you found it :)

2020-12-24 15:32 UTC, PierreRambaud requested changes
Please fill the description and create an issue

2021-02-08 16:28 UTC, hibatallahAouadni commented
I think this PR may fix this issue #15369 (as mentioned by @JeromeFarin)

2021-02-09 08:20 UTC, PierreRambaud commented
Hi,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2021-02-09 08:20 UTC, closed without merging

2021-09-17 07:43 UTC, MultiplicaliaIT commented on classes/Cart.php
> +                        $multi_carriers = $new_multi_carriers;
This code I think it have an error.

$multi_carriers = $new_multi_carriers should go after the second foreach is closed

2023-05-12 09:36 UTC, Codencode commented
Hi everyone,
why were these changes not taken into consideration?
They fix a problem mentioned in various issues #15369, #15491

2023-05-12 15:39 UTC, kpodemski commented
Hi @Codencode 

Yes, it's a complex subject because this PR only touches some parts of the multi-shipping feature. It requires changes in BO, Front office, and emails.