Fix missing itemListElement on single nav element (like homepage)
PrestaShop/PrestaShop pull request #22607
Opened 2020-12-28 12:30 UTC by MisterDuval

This error occurs on Google search console which asks for a itemListElement but this breadcrumb is only one item, and can be removed.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 1.7.7.x
| Description?      | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?             | bug fix / improvement / new feature / refacto / critical
| Category?         | FO / BO / CO / IN / WS / TE / LO / ME / PM
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| Fixed ticket?     | Fixes #{issue number here}.
| How to test?      | Please indicate how to best verify that this PR is correct.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

2020-12-28 18:45 UTC, Arman-Hosseini approved these changes, later dismissed
LGTM

2020-12-30 14:50 UTC, PierreRambaud requested changes
Could you please create an issue, a link to a forum is not what we need :)
You also need to fix the indentation in your code.
Thanks for your contribution

2020-12-30 15:45 UTC, MisterDuval commented
Hi Pierre, that's fixed.

2020-12-30 16:06 UTC, PierreRambaud approved these changes

2020-12-30 16:06 UTC, PierreRambaud commented
> Hi Pierre, that's fixed.

That's perfect :heart:

2020-12-31 09:49 UTC, matthieu-rolland approved these changes

2020-12-31 09:51 UTC, matthieu-rolland commented
thank you @MisterDuval , your PR is sent to QA 👍

2020-12-31 10:02 UTC, PululuK approved these changes

2021-01-04 09:10 UTC, NeOMakinG approved these changes

2021-01-06 13:51 UTC, khouloudbelguith commented
Hi!

This PR cannot be tested.
The issue should be validated first.
Ping @PrestaShop/product-team

Thanks!

2021-01-07 10:35 UTC, marionf commented
I remove the waiting for PM label as the issue is a bug and not an improvement
We need to reproduce the issue first
Let me know after if a PM opinion is needed ;)

2021-01-12 16:29 UTC, khouloudbelguith commented
Hi @MisterDuval,

After testing this PR, there is only one issue fixed (the home page)
**Without PR**
![image](https://user-images.githubusercontent.com/16067358/104342465-276e5a00-54fb-11eb-9a1b-4c1a5c2031b5.png)
**With PR**
![image](https://user-images.githubusercontent.com/16067358/104342760-77e5b780-54fb-11eb-812e-6fe0fe4aeb1c.png)

So, this PR is only fixing this issue?
PS: with 1771, we have this result
![image](https://user-images.githubusercontent.com/16067358/104342942-a95e8300-54fb-11eb-9838-5bdf32df735f.png)

Thanks you

2021-01-26 14:32 UTC, marionf commented
The issue https://github.com/PrestaShop/PrestaShop/issues/22416 has been fixed by https://github.com/PrestaShop/PrestaShop/pull/22417, I think we can close this PR @PrestaShop/prestashop-contributors ?

2021-01-26 15:23 UTC, PierreRambaud commented
I'm closing it, feel free to reopen if you think it's still relevant.

2021-01-26 15:23 UTC, closed without merging