Delete UI upgrade test
PrestaShop/PrestaShop pull request #22656
Opened 2021-01-04 14:57 UTC by boubkerbribri

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Delete unused test for upgrade (Testing upgrade will be done in another repo)
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | no tests needed
| Possible impacts? | No impacts

2021-01-04 14:58 UTC, Progi1984 requested changes
WAIT FOR 1771 RELEASE

2021-01-05 15:03 UTC, PierreRambaud approved these changes

2021-01-12 10:08 UTC, Progi1984 approved these changes

2021-01-12 13:08 UTC, merged

2021-01-12 13:08 UTC, Progi1984 commented
Thanks @boubkerbribri