Fix nightly 1.7.7.x - 05/01/2021
PrestaShop/PrestaShop pull request #22678
Opened 2021-01-05 14:46 UTC by nesrineabdmouleh

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Fix enable/disable merchandise return test
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | no
| Possible impacts? | TEST_PATH="functional/BO/05_customerService/03_merchandiseReturns/01_activateMerchandiseReturn.js" URL_FO=yourShopURL  npm run specific-test

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/22678)

2021-01-05 14:58 UTC, Progi1984 approved these changes

2021-01-05 15:02 UTC, boubkerbribri approved these changes

2021-01-05 15:03 UTC, Progi1984 requested changes, later dismissed
WAITING FOR 1771 RELEASE

2021-01-05 15:30 UTC, SimonGrn approved these changes

2021-01-12 14:25 UTC, PierreRambaud approved these changes

2021-01-12 14:25 UTC, merged

2021-01-12 14:25 UTC, PierreRambaud commented
Thank you @nesrineabdmouleh