PerfectScrollBar needs available element
PrestaShop/PrestaShop pull request #22673
Opened 2021-01-05 10:29 UTC by PierreRambaud

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Make sure the selector exists before creating PerfectScrollBar elements
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #22590 
| How to test?      | Follow ticket instruction.
| Possible impacts? | N/A.

2021-01-05 11:07 UTC, atomiix approved these changes

2021-01-05 13:25 UTC, NeOMakinG approved these changes
Is the navbar working if the element is not there?

2021-01-05 14:19 UTC, Progi1984 approved these changes

2021-01-05 18:24 UTC, matthieu-rolland approved these changes

2021-01-06 09:59 UTC, khouloudbelguith commented
Hi @PierreRambaud,

It is ok :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/16067358/103755459-28405100-500e-11eb-8b6b-c5fb8fb1a256.png)

Thank you!

2021-01-06 10:00 UTC, Progi1984 requested changes
WAIT FOR 1771 RELEASE

2021-01-12 13:08 UTC, Progi1984 approved these changes

2021-01-12 13:27 UTC, merged