Create Order - Cart details modal - Fix refresh for cart total
PrestaShop/PrestaShop pull request #22685
Opened 2021-01-06 11:23 UTC by sowbiba

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Fix missing source attribute for the KPIHelper to fix JS error. Do not show the refresh button
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #22105 
| How to test?  | In BO > Orders > Add new Order page > Search a customer > choose it > Open the details for a cart > You will see the amount of the cart and no *Refresh* button<br><br>In Orders > Shopping carts > choose a cart and hit View > You will see the total amount of the cart and no *Refresh* button

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/22249)

2021-01-06 12:05 UTC, Progi1984 commented on src/Adapter/Kpi/ShoppingCartTotalKpi.php
```suggestion
$helper->source = Context::getContext()->link->getAdminLink('AdminStats') . '&ajax=1&action=getKpi&kpi=shopping_cart_total&cartId=' . $cart->id;
```

2021-01-06 13:01 UTC, Progi1984 requested changes, later dismissed
DONT MERGE BEFORE 1771 RELEASE

2021-01-08 16:15 UTC, matks approved these changes

2021-01-12 13:14 UTC, PierreRambaud approved these changes

2021-01-12 13:28 UTC, merged