Remove module-related sql upgrade query
PrestaShop/PrestaShop pull request #22682
Opened 2021-01-06 09:53 UTC by atomiix

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Because during the upgrade process of 1.7.6.2 we try to upgrade a table belongings to a module, that can throw errors when that module is not present during the process.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Partially 22668
| How to test?      | Upgrade from 1.6.1.24 to a version >= 1.7.6.2 with the autoupgrade module, you should not have the following warning: ![Capture d’écran 2021-01-06 à 10 52 03](https://user-images.githubusercontent.com/2168836/103754955-596c5180-500d-11eb-8433-2fec7935bd28.png)
| Possible impacts? | /

2021-01-06 10:17 UTC, matks submitted a review, later dismissed

2021-01-06 10:18 UTC, Progi1984 submitted a review, later dismissed

2021-01-06 10:21 UTC, matthieu-rolland approved these changes, later dismissed

2021-01-06 10:33 UTC, PierreRambaud submitted a review, later dismissed

2021-01-06 11:07 UTC, jolelievre submitted a review, later dismissed

2021-01-06 11:27 UTC, sowbiba submitted a review, later dismissed

2021-01-06 12:07 UTC, Arman-Hosseini submitted a review, later dismissed

2021-01-06 13:52 UTC, SD1982 commented
The upgrade seems good for now I don't have the warning anymore 
**before**
![image](https://user-images.githubusercontent.com/40635814/103775607-9268ee00-502e-11eb-80b8-863e08e82c7c.png)
**after**
![image](https://user-images.githubusercontent.com/40635814/103775635-a280cd80-502e-11eb-865e-71e8fe1b5589.png)

but i'm currently blocked by #22668 I will retest this PR when the issue is fixed and merged

2021-01-07 10:34 UTC, Progi1984 commented
I change the milestone

2021-01-12 06:53 UTC, kpodemski commented on install-dev/upgrade/php/delete_hook.php
> +            if ($moduleInstance instanceof  Module) {
```suggestion
            if ($moduleInstance instanceof Module) {
```

2021-01-12 06:57 UTC, kpodemski approved these changes, later dismissed

2021-01-12 10:35 UTC, Progi1984 submitted a review, later dismissed

2021-02-01 08:47 UTC, Progi1984 approved these changes

2021-02-01 09:49 UTC, PierreRambaud approved these changes

2021-02-03 21:27 UTC, matks approved these changes

2021-02-12 10:58 UTC, Progi1984 commented
Will be in 1773.

2021-02-12 10:58 UTC, Progi1984 requested changes, later dismissed
## WAIT FOR 1772 RELEASE

2021-02-12 12:11 UTC, merged