Fix installation carrier delay Error for Persian Language
PrestaShop/PrestaShop pull request #22735
Opened 2021-01-08 10:13 UTC by matks

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | IN: Fix installation - carrier delay empty (Error for Persian Language). On the installation process in Persian (Farsi) language, one error happened about carrier->delay is empty and installation with demo data can't be succeeded. This is a backport of PR https://github.com/PrestaShop/PrestaShop/pull/22564 by @AliShareei 
| Type?             | bug fix
| Category?         | IN 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | #22657
| How to test?      | Just install PrestaShop with Persian (Farsi) language
| Possible impacts? | Installation process.

<img width="960" alt="image_2020-12-24_13-47-09" src="https://user-images.githubusercontent.com/9982451/103082647-d2bc7b00-45ef-11eb-8090-5d732484a541.png">

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/22564)

2021-01-08 10:14 UTC, AliShareei commented
@matks Thanks.

2021-01-08 10:52 UTC, Arman-Hosseini approved these changes

2021-01-08 16:55 UTC, matthieu-rolland approved these changes

2021-01-11 08:20 UTC, Progi1984 approved these changes

2021-01-11 09:54 UTC, khouloudbelguith commented
Hi @matks,

It is ok :heavy_check_mark: 
I tried with PS install `English` language & `France` country => ok
I tried with PS install `Persian` language & `France` country => ok
![image](https://user-images.githubusercontent.com/16067358/104166503-3372f280-53fb-11eb-85da-bde9cf72fb0b.png)
In the FO, All enabled carriers are well displayed
![image](https://user-images.githubusercontent.com/16067358/104166615-5b625600-53fb-11eb-8d03-3c4b51454531.png)

Thank you!

2021-01-11 09:58 UTC, Progi1984 requested changes
DONT MERGE BEFORE 1771 RELEASE

2021-01-12 10:24 UTC, Progi1984 approved these changes

2021-01-12 10:35 UTC, merged

2021-01-12 10:36 UTC, Progi1984 commented
Thanks @matks & @khouloudbelguith & @AliShareei & @Arman-Hosseini