Improve TypedRegexValidator->getPattern()
PrestaShop/PrestaShop pull request #22887
Opened 2021-01-19 09:09 UTC by davidglezz

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | The problem with the previous getPattern() implementation is that it first creates an array with all the regexes (which involves multiple calls to other functions) and then looks for the required one in the array. The most natural and fast way is to use a switch.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | there is unit test for this?
| Possible impacts? | None

2021-01-19 10:24 UTC, PierreRambaud requested changes, later dismissed
CI is broken because of git merge commit :wink:

2021-01-19 13:43 UTC, matks commented
> CI is broken because of git merge commit 😉

Idea for improvement: output helpful message with a link to the devdocs 🎉

2021-01-20 08:50 UTC, davidglezz commented
Rebase done!

2021-01-20 10:25 UTC, Progi1984 reviewed
@davidglezz Do you think that you can some unit test for this class ? :pray: Thanks

2021-01-20 11:04 UTC, davidglezz commented
@Progi1984 The function that I modify is private, it is indirectly tested in https://github.com/PrestaShop/PrestaShop/blob/develop/tests/Unit/Core/ConstraintValidator/TypedRegexValidatorTest.php
is it correct?
wdyt?

2021-01-21 10:54 UTC, Progi1984 commented
> @Progi1984 The function that I modify is private, it is indirectly tested in https://github.com/PrestaShop/PrestaShop/blob/develop/tests/Unit/Core/ConstraintValidator/TypedRegexValidatorTest.php
> is it correct?
> wdyt?

Correct. (and sorry).

2021-01-21 10:55 UTC, Progi1984 approved these changes

2021-01-22 10:13 UTC, matthieu-rolland approved these changes

2021-01-22 10:17 UTC, PierreRambaud approved these changes

2021-01-22 10:17 UTC, merged

2021-01-22 10:18 UTC, PierreRambaud commented
Thank you @davidglezz 
It doesn't require QA, tests are green :)