Add html validation to radio buttons on category tree
PrestaShop/PrestaShop pull request #22942
Opened 2021-01-22 08:54 UTC by NeOMakinG

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Category trees are not blocking the submit form if required
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #19612.
| How to test?      | See issue, btw, it doesn't fix the material checkbox one, that should be done using JavaScript inside the UIKit, with an helper class in order to create the control
| Possible impacts? | Every radio trees

2021-01-22 10:19 UTC, matks approved these changes, later dismissed
Code seems good but could you please make it a little more clear what is fixed, what is not, and how QA can validate this PR 😉

2021-01-25 09:34 UTC, matthieu-rolland submitted a review, later dismissed

2021-01-25 16:27 UTC, khouloudbelguith commented
Hi @NeOMakinG,

I have only one issue in the category page when multistore enabled.
Steps to reproduce the issue:
1. Enable Multistore Context
2. Create a new shop
3. Go to BO > Catalog > Categories page
4. Add a new root category > Save 
5. At this step, you are in the Root category list 
![image](https://user-images.githubusercontent.com/16067358/105733633-0dd50580-5f32-11eb-961e-f2b79ab88481.png)
6. Add a new category > the Parent category is not selected
7. Set only the Name & save
8. See the error => nothing happens

I attached a screen record
https://drive.google.com/file/d/11PXqvCzvJq0lrAcG4DW0eRn97kjfoUFE/view?usp=sharing

**Without PR**
When I click save => I have an alert displayed
![image](https://user-images.githubusercontent.com/16067358/105734051-7fad4f00-5f32-11eb-86fa-e879ae4b2eb1.png)

Thank you!

2021-01-25 20:25 UTC, NeOMakinG commented
@khouloudbelguith 

Thanks for testing, this error isn't related at all, it's just because the form doesn't submit as you didn't fill the category tree, btw I shouldn't block these fields as they can't be fixed only by doing this, I need to go further on this PR.

2021-02-08 14:14 UTC, NeOMakinG commented
@khouloudbelguith could you test again ? I checkout the PR and it looks like I can't reproduce your behavior at all !

2021-02-08 14:59 UTC, NeOMakinG commented
I added the "required" little asterisk and fixed this problem on UIKit side : https://github.com/PrestaShop/prestashop-ui-kit/pull/137

It's testable with this PR as well

2021-02-08 15:27 UTC, PierreRambaud commented on src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_layout.html.twig
> +                    <input type="radio" name="form[{{ form.vars.id }}][tree]" value="{{ child.id_category }}" {{ checked }} class="category" {% if required %}required{% endif %}>
```suggestion
                    <input type="radio" name="form[{{ form.vars.id }}][tree]" value="{{ child.id_category }}" {{ checked }} class="category"{% if required %} required{% endif %}>
```

2021-02-08 15:27 UTC, PierreRambaud commented on src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/material.html.twig
> +  <div class="material-choice-tree-container js-choice-tree-container {% if required %}required{% endif %}" id="{{ form.vars.id }}">
```suggestion
  <div class="material-choice-tree-container js-choice-tree-container{% if required %} required{% endif %}" id="{{ form.vars.id }}">
```

2021-02-08 15:28 UTC, PierreRambaud requested changes
Just two comments :)

2021-02-09 08:03 UTC, PierreRambaud commented on src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_layout.html.twig
> +                  <input type="checkbox" name="{{ form.vars.full_name }}[tree][]" value="{{ child.id_category }}" class="category" {{ checked }}>
```suggestion
                    <input type="checkbox" name="{{ form.vars.full_name }}[tree][]" value="{{ child.id_category }}" class="category" {{ checked }}>
```

2021-02-09 08:04 UTC, PierreRambaud submitted a review, later dismissed

2021-02-09 08:51 UTC, Progi1984 approved these changes, later dismissed

2021-02-18 10:38 UTC, khouloudbelguith commented
Hi @NeOMakinG,

Using this PR: https://github.com/PrestaShop/prestashop-ui-kit/pull/137, I found only an error in the console
Steps to reproduce the issue:

1. Enable Multistore Context
2. Create a new shop
3. Go to BO > Catalog > Categories page
4. Add a new root category > Save
5. At this step, you are in the Root category list
6. Select all only the `first shop`/`second shop`
7. I have an error but it is only on the console
8. Add a new category > the Parent category is not selected
9. Set only the Name & save
10. See the error on the console

![image](https://user-images.githubusercontent.com/16067358/108342563-3a033f80-71db-11eb-923a-eb8242135d37.png)

What do you think?

Thank you!

2021-02-18 14:26 UTC, NeOMakinG commented
@khouloudbelguith 

Thanks a lot for testing.

I understand this error, it's due to radio elements which are inside a `display: none;` property. so the browser is unable to show the error message on an hidden element.

I think it's fine enough for this work, overwise it would need a lot of javascript in order to handle every forms, which could lead to side effects. Or a rework of radio buttons which is a BC...

2021-02-22 15:40 UTC, PierreRambaud approved these changes, later dismissed

2021-02-23 09:16 UTC, Progi1984 reviewed
Please fix review from @PierreRambaud

2021-02-23 09:26 UTC, NeOMakinG commented
@Progi1984 idk why it has been removed, but I fixed it again :)

2021-02-23 10:02 UTC, PierreRambaud approved these changes

2021-02-23 10:29 UTC, Progi1984 approved these changes

2021-02-23 16:44 UTC, khouloudbelguith commented
Hi @NeOMakinG,

An issue is created here: https://github.com/PrestaShop/PrestaShop/issues/23365

It is ok :heavy_check_mark: 

**With PR**
![image](https://user-images.githubusercontent.com/16067358/108876584-ab3d5b00-75fe-11eb-8884-cb2cc5c0f11a.png)
**Without PR**
![image](https://user-images.githubusercontent.com/16067358/108876735-d32cbe80-75fe-11eb-88bc-64ce7c7ed2ec.png)

Thank you!

2021-02-23 18:47 UTC, Progi1984 requested changes
## WAITING FOR RELEASE OF UIKit 1.2.2

2021-03-19 07:58 UTC, Progi1984 approved these changes

2021-03-19 07:58 UTC, merged

2021-03-19 07:58 UTC, Progi1984 commented
Thanks @NeOMakinG & @khouloudbelguith