Replaced hooks displayAdminList<Before|After> with displayAdminGridTable<Before|After>
PrestaShop/PrestaShop pull request #22980
Opened 2021-01-25 15:04 UTC by Progi1984

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Replaced hooks `displayAdminListBefore` with `displayAdminGridTableBefore` and `displayAdminListAfter` with `displayAdminGridTableAfter`<br> :heart_eyes_cat:@kpodemski for #22922
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #22910
| How to test?      | Use the ps_qualityassurance module and register for each hook:<br>* Hook name: `displayAdminListBefore` / `displayAdminListAfter` / `displayAdminGridTableBefore` / `displayAdminGridTableAfter`<br>* Content: `return '<h3>Order Hook</h3>';`

2021-01-26 13:43 UTC, atomiix commented on install-dev/upgrade/sql/1.7.7.2.sql
> +    (NULL, 'displayAdminGridTableAfter', 'Display after Grid table', 'This hook adds new blocks after Grid component table.', '1')
Shouldn't you add the aliases too?

2021-01-26 15:27 UTC, PierreRambaud requested changes
Could you please update the upgrade SQL script to update hooks on modules please like it has been done for the 1.7.7.0

Example:
```
UPDATE `PREFIX_hook_module` AS hm
INNER JOIN `PREFIX_hook` AS hfrom ON hm.id_hook = hfrom.id_hook AND hfrom.name = 'actionFrontControllerAfterInit'
INNER JOIN `PREFIX_hook` AS hto ON hto.name = 'actionFrontControllerInitAfter'
SET hm.id_hook = hto.id_hook;
DELETE FROM `PREFIX_hook` WHERE name = 'actionFrontControllerAfterInit';
```

And also update the hook_alias table?

2021-02-01 15:00 UTC, PierreRambaud approved these changes

2021-02-01 15:03 UTC, kpodemski approved these changes
Remember to update docs later 👍

2021-02-02 09:48 UTC, khouloudbelguith commented
Hi @Progi1984,

It is ok :heavy_check_mark: 
**Migrated pages**
![image](https://user-images.githubusercontent.com/16067358/106582058-dbd02e80-6543-11eb-9633-47a469ada0cd.png)
![image](https://user-images.githubusercontent.com/16067358/106582208-05895580-6544-11eb-9494-34f8f27e6f17.png)
**Legacy page**
![image](https://user-images.githubusercontent.com/16067358/106582227-0ae6a000-6544-11eb-8553-f3cb069a84f0.png)
![image](https://user-images.githubusercontent.com/16067358/106582279-1cc84300-6544-11eb-99e8-164907d335b2.png)

Thank you!

2021-02-02 09:54 UTC, merged

2021-02-02 09:54 UTC, Progi1984 commented
Thanks @khouloudbelguith