Rename addAnchor parameter in getProductLink method
PrestaShop/PrestaShop pull request #23017
Opened 2021-01-27 14:41 UTC by jonatanrs

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | @jonatanrs Rename addAnchor parameter in getProductLink method
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #{issue number here}.
| How to test?      | It is a simple renaming of a parameter to make it easier to understand what it does, since the current name is completely incorrect.
| Possible impacts? | No impact.

2021-01-27 20:08 UTC, kpodemski commented
Hello,

thank you but we refactored this method on develop branch already 👍 

take a look:
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Link.php#L143

also:
- remember that on 1.7.7.x branch (or current 1.7.X) version we should only target bugfixes and regressions
- target `develop` for improvements

If you think you'd like to improve method on `develop` you can rebase your branch on top of it or create a new PR 👍

2021-01-27 22:39 UTC, jonatanrs commented
Hello @kpodemski,

This is my first contribution to this repository and I am not very familiar with the pull request policy.

It seemed appropriate to make the pull request in the current version as it is a simple parameter rename, has no impact and improves the readability of the code. The current name (addAnchor) is wrong and causes confusion.

I have seen the refactoring that is in the development branch, but it adds a new parameter and still seems confusing. Maybe create a pull request in the development branch to improve it as well.

2021-01-28 08:34 UTC, kpodemski commented
Hello @jonatanrs 

you can read more about contributing to PrestaShop here:
 [https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/#choose-the-right-base-branch](https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/#choose-the-right-base-branch)

I suggest to create new PR on `develop` branch.

2021-01-28 09:40 UTC, Progi1984 approved these changes

2021-01-28 09:41 UTC, Progi1984 requested changes
Please target the `develop` branch.

2021-01-28 11:47 UTC, jonatanrs commented
I will create a pull request in the `develop` branch

2021-01-28 11:47 UTC, closed without merging