Fixes #23061
PrestaShop/PrestaShop pull request #23081
Opened 2021-02-01 16:58 UTC by fabiovannini

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 1.7.7.x
| Description?      | Remove combination from cart ONLY on delete. Before ,when web service update the combination, deleteAssociations method was called and that combination left the customer cart.
| Type?             | bug fix
| Category?         | WS
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23061
| How to test?      | Cf. #23061
| Possible impacts? | Check that this does not break the expected relational integrity and business rules.

2021-02-02 10:51 UTC, Progi1984 commented on classes/Combination.php
> +     * @return array Deletion result
```suggestion
     * @return bool```

2021-02-02 10:52 UTC, Progi1984 commented on classes/Combination.php
> +    public function deleteCartProductCombination()
```suggestion
    public function deleteCartProductCombination(): bool
```

2021-02-02 10:52 UTC, Progi1984 reviewed
Some feedbacks. Thanks :pray:

2021-02-02 11:43 UTC, fabiovannini commented
> Some feedbacks. Thanks 🙏

thank you too!

2021-02-05 14:20 UTC, PierreRambaud commented on classes/Combination.php
> +    public function deleteCartProductCombination(): bool
```suggestion
    protected function deleteCartProductCombination(): bool
```

I see no reason to have this method public.
Also, you should test if `$this->id` is correctly defined before running an SQL query for nothing.

2021-02-05 14:21 UTC, PierreRambaud commented on classes/Combination.php
> +        return Db::getInstance()->delete('cart_product', 'id_product_attribute = ' . (int) $this->id);
```suggestion
        if ((int) $this->id === 0) {
            return false;
        }

        return Db::getInstance()->delete('cart_product', 'id_product_attribute = ' . (int) $this->id);
```

2021-02-05 14:21 UTC, PierreRambaud requested changes
Hey, good job, few comments :)

2021-02-05 14:55 UTC, fabiovannini commented
> Hey, good job, few comments :)

Thanks Pierre, Icompletely agree with you. I have committed the changes.

2021-02-09 08:33 UTC, PierreRambaud approved these changes

2021-02-09 08:40 UTC, Progi1984 approved these changes

2021-02-11 13:30 UTC, SD1982 commented
LGTM
**Before PR**
https://www.awesomescreenshot.com/video/2722005?key=cfc3bf2458659b5fcbe92f9e77d82f21
**After PR**
https://www.awesomescreenshot.com/video/2722027?key=227852a406af2155b9321edb60d3b520
Thanks @fabiovannini !!

2021-02-11 13:31 UTC, matks commented
Thank you @fabiovannini !

2021-02-11 13:32 UTC, merged