Add cron GitHub Action to run security checks every day
PrestaShop/PrestaShop pull request #23143
Opened 2021-02-04 17:26 UTC by matks

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add cron GitHub Action to run security checks every day
| Type?             | new feature
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/21199 and https://github.com/PrestaShop/PrestaShop/issues/22924
| How to test?      | 
| Possible impacts? |

2021-02-04 17:26 UTC, matks commented
Run on push on my fork => https://github.com/matks/PrestaShop/runs/1832770712?check_suite_focus=true

(result is red... as expected 😅  we _really_ have unsecure dependencies)

2021-02-04 17:27 UTC, matks commented on .github/workflows/daily-checks.yml
> +name: Cron Daily Checks
I created a generic name as I think we can fit many of these checks in there. Like license headers check, security checks...

2021-02-04 21:22 UTC, PierreRambaud approved these changes

2021-02-08 08:01 UTC, Progi1984 requested changes
Can't be accepted without any definition of license for `pplotka/local-php-security-checker-github-actions`.

2021-02-08 08:17 UTC, matks commented
> Can't be accepted without any definition of license for `pplotka/local-php-security-checker-github-actions`.

Nice catch! I will ask the author if he's willing to add one. If he does not want I will do the necessary boilerplate for this to work

2021-02-09 13:50 UTC, paras-malhotra commented
@matks you can consider the [Enlightn Security Checker](https://github.com/enlightn/security-checker). It's almost a drop-in replacement and has no licensing issues (licensed under MIT). I'm the author of this package.

The issue with the Local PHP Security Checker is that it's licensed under AGPL, so I reckon even the Github action (that distributes the source) must be licensed under AGPL.

2021-04-20 16:25 UTC, matks commented
Hello, it seems this PR is now stale.

I close this PR, following our [review guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/) "Pull Requests may be closed after 30 days of inactivity".

2021-04-20 16:25 UTC, closed without merging