Update TinyMCE and some plugins to 4.9.11
PrestaShop/PrestaShop pull request #23223
Opened 2021-02-11 14:56 UTC by NeOMakinG

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | TinyMCE has an error on some plugins clicks
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23213.
| How to test?      | Go on /sell/catalog/categories/new?id_parent=2 for example, and try to use TinyMCE, it should work as on develop branch
| Possible impacts? | TinyMCE content editing

2021-02-11 15:33 UTC, NeOMakinG commented
@boubkerbribri could you take a look at this ? I can't find why the test fail, the selector looks fine to me and present :/

2021-02-15 10:00 UTC, Progi1984 requested changes
Please remove right changes about js/timy_mce/*.js

2021-02-17 09:02 UTC, PierreRambaud approved these changes

2021-02-17 10:12 UTC, Progi1984 approved these changes

2021-02-22 10:35 UTC, merged

2021-02-22 10:35 UTC, Progi1984 commented
Thanks @NeOMakinG & @sarahdib