Changelog 1.7.7.2
PrestaShop/PrestaShop pull request #23227
Opened 2021-02-11 17:03 UTC by sowbiba

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Changelog for 1.7.7.2
| Type?             | -
| Category?         | -
| BC breaks?        | -
| Deprecations?     | -

2021-02-12 07:58 UTC, Progi1984 reviewed
Missing #22528

2021-02-12 15:41 UTC, PululuK approved these changes, later dismissed

2021-02-12 16:51 UTC, PierreRambaud approved these changes

2021-02-15 07:31 UTC, Progi1984 requested changes
## Need to wait for QA Validation

2021-02-22 10:09 UTC, PululuK commented
See https://github.com/PrestaShop/PrestaShop/pull/23341

2021-02-22 10:09 UTC, closed without merging