Customization fields and its saved value shows HTML content in order confirmation mail.
PrestaShop/PrestaShop pull request #23263
Opened 2021-02-15 11:11 UTC by Amit-Kumar-Tiwari-Webkul

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Customization fields and their saved value shows HTML content in order confirmation mail.
<br>It must show formatted HTML content.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     |no
| Fixed ticket?     | Fixes #23261 .
| How to test?      | 1- Go to customizable product: https://prnt.sc/zl9oi5 <br>2- save your customization and place an order.<br>3- We received an order confirmation mail https://prnt.sc/zl9y6q<br>You will see that customization content shows in HTML.
| Possible impacts? | check the mail content of order confirmation mail.

2021-02-16 08:33 UTC, Progi1984 submitted a review, later dismissed

2021-02-17 09:05 UTC, matthieu-rolland reviewed
Hello, could you rebase your PR ?  Behat tests are broken, but it's probably not linked to your PR, it has been fixed on develop, if you rebase it should be fine.

2021-02-17 17:24 UTC, Amit-Kumar-Tiwari-Webkul commented
HI,
BEHAT test failure not related to this PR

2021-02-22 15:07 UTC, benbine commented
Hello,
You may have to add "nofilter" on line 50 too
Thanks

2021-02-24 15:34 UTC, matthieu-rolland reviewed
I restarted sanity tests, they tend to fail randomly lately 🤔

2021-02-25 08:52 UTC, Progi1984 approved these changes

2021-02-25 08:59 UTC, Progi1984 commented
@matthieu-rolland It's good

2021-02-25 18:28 UTC, PierreRambaud requested changes
IMHO, it's not the solution, the customization_text shouldn't contain the `<strong>` HTML tag.
What if the `customization_text` contains `I <3 you`? or `I love <HTML>`

By adding the nofilter attribute, you allow some mail to inject HTML code without any control

2021-02-26 05:54 UTC, Amit-Kumar-Tiwari-Webkul commented
@PierreRambaud , HTML fields are not allowed from the product page during the customization save.
Only a strong tag added to represent the label from this class https://github.com/PrestaShop/PrestaShop/blob/develop/classes/PaymentModule.php#L457
So there is the possibility of other HTML or any script code inside the customization because the customization table cannot accept HTML content.

2021-02-26 13:49 UTC, sowbiba commented
LGTM but I will wait @PierreRambaud to see if the answer given is enough. Maybe some security issues after order is placed that I can't see

2021-02-26 13:49 UTC, sowbiba reviewed
LGTM but I will wait @PierreRambaud to see if the answer given is enough. Maybe some security issues after order is placed that I can't see

2021-03-01 13:36 UTC, PierreRambaud commented
> @PierreRambaud , HTML tags are not allowed from the product page during the customization save.
> Only a strong tag added to represent the label from this class https://github.com/PrestaShop/PrestaShop/blob/develop/classes/PaymentModule.php#L457
> So there is no possibility of other HTML or any script code inside the customization because the customization table cannot accept HTML content.

I confirm the HTML shouldn't be added in the `customization_text` variable inside the `PaymentModule` but inside the template itself

2021-03-12 08:11 UTC, matks requested changes
Agreed with @PierreRambaud .

@Amit-Kumar-Tiwari-Webkul in current implementation maybe the only place where HTML is built into this field is PaymentModule.php line 457 but we cannot guarantee it will stay like this in the future.

So unless we _really_ want to allow HTML inside this field, adding the `nofilter` is a very dangerous move.

As said by @PierreRambaud, adding `nofilter` is a bit too much. It's like saying "I want to people to be able to enter my house so I will remove the door" 😅  . An alternative solution is to give the people you want to come a copy of your keys, not remove the door.

Here are some suggestions we could have a correct rendering:
1. replace the `nofilter` you added by a custom logic that parses `$customization['customization_text']` and extract the allowed HTML tags
2. modify how `$customization['customization_text']` is stored (maybe in JSON?) so that we can have the data structure on one hand, and render it as we want on the other hand

2021-04-20 16:24 UTC, matks commented
Hello, it seems this PR is now stale.

I close this PR, following our [review guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/) "Pull Requests may be closed after 30 days of inactivity". If however you are still interested in it, please ping us :) we can reopen. 😄

2021-04-20 16:24 UTC, closed without merging