Fix bug : Shop name not updating
PrestaShop/PrestaShop pull request #23377
Opened 2021-02-24 09:37 UTC by dreammeup

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 1.7.7.x
| Description?      | The shop name in the table ps_shop is not updating, and can't be updated when not in multishop enabled. The correction proposed : if we are not in multishop, we update the table with the value sended for PS_SHOP_NAME. This name is used in mails, maybe elsewhere.
| Type?             | bug fix
| Category?         | BO
| Deprecations?     | no
| How to test?      | Go in Admin tab "Stores", and edit the name of the shop, it won't change the name in "ps_shop" without this patch
| Possible impacts? | no

2021-02-24 09:56 UTC, Progi1984 commented
@dreammeup Could you run `./vendor/bin/php-cs-fixer fix` on your local for fixing PHPCSFixer Github Action ?

2021-02-24 14:44 UTC, matthieu-rolland reviewed
Thank you @dreammeup for your contribution  👍 

Could you create an issue and reference it in your PR description ? Or reference the issue if you are treating an issue, this is mandatory in every PR ;)

(So that our product team can validate the existence of the bug and the wanted behavior, it will also help the QA team.)

2021-02-25 09:45 UTC, dreammeup commented
Hello, the ticket was created and reviewed, I edited the pull request with the issue ticket number.

2021-02-25 12:48 UTC, PierreRambaud commented on controllers/admin/AdminStoresController.php
> +            Db::getInstance()->Execute(
```suggestion
            Db::getInstance()->execute(
```

2021-02-25 12:48 UTC, PierreRambaud commented on controllers/admin/AdminStoresController.php
> +                WHERE id_shop = ' . (int) $this->context->shop->id
```suggestion
                'UPDATE `' . _DB_PREFIX_ . 'shop` ' .
                'SET name = "' . pSQL($value) . '" ' .
                'WHERE id_shop = ' . (int) $this->context->shop->id
```

2021-02-26 13:41 UTC, sowbiba approved these changes, later dismissed

2021-03-01 08:36 UTC, matthieu-rolland reviewed
one small feedback

2021-03-01 08:36 UTC, matthieu-rolland commented on controllers/admin/AdminStoresController.php
> +    public function updateOptionPsShopName($value)
It would be nice to have the shop ID as an optional parameter and use the context shop id if it's not specified. 👍

2021-03-01 16:56 UTC, PierreRambaud commented on controllers/admin/AdminStoresController.php
> +    public function updateOptionPsShopName($value)
```suggestion
    /**
     * @var string $name
     */
    public function updateOptionPsShopName(string $name): void
```

Could you improve the docstring to explained what this method do? :)

2021-03-01 16:57 UTC, PierreRambaud commented on controllers/admin/AdminStoresController.php
> +                'SET name = "' . pSQL($value) . '" ' .
```suggestion
                'SET name = "' . pSQL($name) . '" ' .
```

Related to my previous comment

2021-03-01 16:57 UTC, PierreRambaud commented on controllers/admin/AdminStoresController.php
> +        if (!Shop::isFeatureActive() && !$this->errors && $value) {
```suggestion
        if (!Shop::isFeatureActive() && !$this->errors && $name) {
```
Related to my previous comment

2021-03-04 08:12 UTC, PierreRambaud requested changes
Hey, thanks for your contribution, could you please improve docstring and use latest PHP7 feature (hint typing) please?

2021-03-04 08:22 UTC, matthieu-rolland reviewed
@dreammeup 

I put back the waiting for author label, don't hesitate to ask if there's a feedback that you don't quite understand 👍

2021-03-04 09:15 UTC, PierreRambaud approved these changes
Thanks for your reactivity!

2021-03-17 16:29 UTC, Progi1984 approved these changes

2021-03-18 13:15 UTC, khouloudbelguith commented
Hi @dreammeup,

The shop name is well updated in the database `ps_shop`.
But this expression is not saved
Steps to reproduce the issue:
1. Go to BO > Shop Parameters > Contact > Stores page
2. Edit the shop name
3. Save => OK
4. Go to BO > Shop Parameters > Contact > Stores page again (Don't refresh the page)
5. Old value is still displayed
6. You can check BO (login page) / FO (contact information) / mails => old value is displayed

https://drive.google.com/file/d/1JM2iI4akgP6wY6cOQey8jHvCnayCWrd5/view?usp=sharing

Thank you!

2021-10-11 20:08 UTC, matks commented
Hello, it seems this PR is unfortunately stale. 😞 QA team reported something we believe is not right and no action has been done since this moment.

I close this PR, following our [review guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/) "Pull Requests may be closed after 30 days of inactivity". If however you are still interested in it, please ping us :) we can reopen.

Thank you for your contribution.

2021-10-11 20:08 UTC, closed without merging