Update Mail.php
PrestaShop/PrestaShop pull request #23417
Opened 2021-02-25 18:39 UTC by josemariagomezroncero

Bug,
Email fail when $fromName  is greater than 22 characters.

Thansk Antonio Gomariz Martínez

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 1.7.7.x
| Description?      | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?             | bug fix / improvement / new feature / refacto / critical
| Category?         | FO / BO / CO / IN / WS / TE / LO / ME / PM
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| Fixed ticket?     | Fixes #{issue number here}.
| How to test?      | Please indicate how to best verify that this PR is correct.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

2021-02-25 20:04 UTC, PierreRambaud requested changes
Hey, thanks for your contribution.
Would you like to follow our [contribution guidelines](https://devdocs.prestashop.com/1.7/contribute/documentation/how/) in order to understand why you make this change by using a proper title and correctly fill the table :)

2021-02-25 21:41 UTC, matks commented
> Hey, thanks for your contribution.
> Would you like to follow our [contribution guidelines](https://devdocs.prestashop.com/1.7/contribute/documentation/how/) in order to understand why you make this change by using a proper title and correctly fill the table :)

Done 😄 (yes, I've done it for this gentleman)

2021-02-26 11:48 UTC, sowbiba commented
Thanks for the contribution :+1: 
It's a technical limitation but It can give unexpected results for the merchant : "From" name can be not understandable.
The other way is to limit shop names to  22char. It's a bit too much I agree :D
So I'm OK with your modification but maybe @PrestaShop/product-team needs to be aware of that

2021-02-26 11:49 UTC, sowbiba submitted a review, later dismissed

2021-02-26 12:04 UTC, eternoendless requested changes
As far as I know the SMTP protocol does not impose a character length limit on the From field. Can you please give more information about the reasons behind this change? Why 22 characters?

2021-02-26 13:17 UTC, sowbiba commented
I tried this

![Capture d’écran de 2021-02-26 13-16-17](https://user-images.githubusercontent.com/7426640/109304927-e6c16a80-7834-11eb-880f-374415d72343.png)

And I received 

![Capture d’écran de 2021-02-26 13-16-23](https://user-images.githubusercontent.com/7426640/109304952-ede87880-7834-11eb-8f3d-ea983e9788c8.png)

So @eternoendless you're right, No limitation from SMTP or SwiftMailer

2021-02-26 15:56 UTC, josemariagomezroncero commented
I see that it is not exactly as I said, but if there is a problem if you try to write exactly this text it gives an error in sending "Rincón Home - Decoración - Iluminación - Ambientadores"

2021-02-26 22:09 UTC, matks commented
> I see that it is not exactly as I said, but if there is a problem if you try to write exactly this text it gives an error in sending "Rincón Home - Decoración - Iluminación - Ambientadores"

It could be related to the use of `ó` 😄 ? Some special chars?

Also maybe the 22 characters limit is related to the hosting or the mail provider?

2021-02-26 22:45 UTC, josemariagomezroncero commented
I can write  "Rincón Home - Decora", but i can not write "Rincón Home - Decora"  + more characters. I'm looking for the exact problem, excuse me

2021-02-27 01:39 UTC, josemariagomezroncero commented
Hi Again,

Work
Rincón óó ónnn

Not Work
Rincón óó ónnnnnn

Any ideas?

2021-02-27 13:22 UTC, matks commented
@josemariagomezroncero Can you remove the `ó` ? So write "Rincon Home - Decora" + more characters ?

`ó` is a bit unusual character, it might not fully supported by some systems involved in the mail delivery?

2021-03-03 09:32 UTC, eternoendless commented
`ó` is within the scope of the ANSI `latin1` charset, you can describe it in one byte so I'd certainly wouldn't describe at as unusual or rare. Shouldn't pose any problem. IMO the most likely reason behind this problem is an  SMTP service issue or misconfiguration.

Maybe @PierreRambaud knows something more about this, but either way we cannot accept this Pull Request. I suggest continuing the discussion in the issue to find the root problem, then creating a new PR.

2021-03-03 09:32 UTC, closed without merging