Set module instance in Module Adapter
PrestaShop/PrestaShop pull request #23553
Opened 2021-03-07 19:47 UTC by PululuK

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This change fixes minor code issues I found while working on another bug. Module instance in Module Adapter is always null.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| How to test?      | See description below 👇🏿
| Possible impacts? | N/A

## How to test

1 - Edit /[src/PrestaShopBundle/Resources/views/Admin/Module/updates.html.twig](https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Resources/views/Admin/Module/updates.html.twig)

2 - Dump modules var : `{{ dump(modules) }}`

## Before 

❌ - See module instance is null

![image](https://user-images.githubusercontent.com/16455155/110252092-fe5ec880-7f83-11eb-826f-6797af228bee.png)

## After

✔️ - See you can access module instance properties

![image](https://user-images.githubusercontent.com/16455155/110252136-38c86580-7f84-11eb-807a-b1bc264ab59e.png)

2021-03-08 08:21 UTC, matks approved these changes
It makes sense.

2021-03-08 08:23 UTC, matks commented
I did not know this `src/Adapter/Module/Module` but this is a very good example of what was wrong with the [Adapter](https://build.prestashop.com/news/new-architecture-1-6-1-0/) strategy: adapter classes slowly evolve into a wrapper copy of the legacy class, with same properties, same methods and same flaws.

2021-03-08 08:54 UTC, matthieu-rolland approved these changes

2021-03-08 09:14 UTC, PierreRambaud reviewed
Could you please check the performance? I'm afraid of side effects, it loads files and creates temporary content each time the class is loaded, even if it's not needed.

I think the solution is elsewhere. When you do
```twig
{{ dump(modules) }}
```
You're rendering the result of the module presenter, which can be extended
```php
        $modulePresenter = $this->get('prestashop.adapter.presenter.module');
        $modulesPresenterCallback = function (AddonsCollection &$modules) use ($modulePresenter) {
            return $modulePresenter->presentCollection($modules);
        };
```

We should also be able to add a hook if it's missing. But I'm quite sure we shouldn't load unneeded data here.

2021-03-08 09:16 UTC, PierreRambaud requested changes
Just notice in your image:
![image](https://user-images.githubusercontent.com/1462701/110300566-4b2fb700-7ff7-11eb-8526-b26c2dad36ab.png)
You have a Adapter Module instance, so if you need to retrieve the instance you can do `module.getInstance` which is public :)

2021-03-08 09:18 UTC, Quetzacoalt91 commented
FYI it was done this way to avoid loading modules in memory until it is necessary (like a lazy load).

Sometimes, when we are on the module manager, catalog and so, we don't always need the module instance, only its parameters stored on the marketplace or the database.

2021-03-12 14:17 UTC, matks commented
So what do we do now that we have the context provided by @Quetzacoalt91 ?

2021-10-11 20:06 UTC, matks commented
Hello everyone, it seems this PR is unfortunately stale. 😞 I see no activity since March on this PR.

I close this PR, following our [review guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/) "Pull Requests may be closed after 30 days of inactivity". If however you are still interested in it, please ping us :) we can reopen naturally.

Thank you for your contribution.

2021-10-11 20:06 UTC, closed without merging