Update Product.php
PrestaShop/PrestaShop pull request #23629
Opened 2021-03-12 19:18 UTC by KORCHID

some attributes return the default declared value
For example show_condition return 0 always
#23628

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 1.7.7.x
| Description?      | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?             | bug fix / improvement / new feature / refacto / critical
| Category?         | FO / BO / CO / IN / WS / TE / LO / ME / PM
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| Fixed ticket?     | Fixes #{issue number here}.
| How to test?      | Please indicate how to best verify that this PR is correct.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

2021-03-12 21:22 UTC, KORCHID reviewed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23629)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KORCHID)



<!-- Sent from Reviewable.io -->

2021-03-15 15:04 UTC, PierreRambaud requested changes
Hi, could you please correctly fill the description table?

2021-03-15 17:10 UTC, sowbiba reviewed
This is weird. Why some attributes are not retrieven from DB ?
Why show_condition and not unit_price_ratio for example ?

2021-03-15 18:11 UTC, jolelievre commented
@KORCHID are you sure about this behaviour, always returned 0 from product table. I'm not sure but the problem might come from the multi shop behaviour, There is a `product_shop` table which contains override of a few Product fields (including `show_condition`), maybe the 0 value actually comes from there

So the solution would not be to modify the way Product entity gets this data, but rather save the modification in the appropriate multishop table. If we integrate your fix as is, I think the multishop overrides won't work on this field any more.

2021-09-21 08:28 UTC, matks commented
Hello, it seems this PR is now stale.

I close this PR, following our [review guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/) "Pull Requests may be closed after 30 days of inactivity". If however you are still interested in it, please ping us :) we can reopen.

Thank you for your contribution.

2021-09-21 08:28 UTC, closed without merging