Update ProductLazyArray.php
PrestaShop/PrestaShop pull request #23623
Opened 2021-03-12 11:49 UTC by KORCHID

if (empty($this->product['show_condition'])) return '0'

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 1.7.7.x
| Description?      | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?             | bug fix / improvement / new feature / refacto / critical
| Category?         | FO / BO / CO / IN / WS / TE / LO / ME / PM
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| Fixed ticket?     | Fixes #{issue number here}.
| How to test?      | Please indicate how to best verify that this PR is correct.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

2021-03-12 13:18 UTC, KORCHID reviewed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23623)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KORCHID)



<!-- Sent from Reviewable.io -->

2021-03-12 14:14 UTC, matks requested changes
Hi can you fill the PR description table, explain us why you had this line and fix the phpstan warning ?😉

2021-03-12 15:53 UTC, KORCHID commented
> Hi can you fill the PR description table, explain us why you had this line and fix the phpstan warning ?

![Capture du 2021-03-12 16-49-05](https://user-images.githubusercontent.com/33570600/110964069-11daac80-8353-11eb-947a-79da63ba7d61.png)
![Capture du 2021-03-12 16-48-43](https://user-images.githubusercontent.com/33570600/110964070-12734300-8353-11eb-8883-21e051fd08b3.png)
in the function `getCondition()`, `product['show_condition']` returns 0 and therefore it will exit the function without displaying the condition

2021-03-12 16:20 UTC, KORCHID commented
if ($this->product['show_condition'] === "0" ) {
         return false;
        }

2021-03-15 15:06 UTC, PierreRambaud commented
> if ($this->product['show_condition'] === "0" ) {
> return false;
> }

He's talking about this one:
![image](https://user-images.githubusercontent.com/1462701/111175179-6fb40200-85a8-11eb-9271-bbb3e9f9eadc.png)

2021-10-11 20:07 UTC, matks commented
Hello, it seems this PR is unfortunately stale since March. 😞 

I close this PR, following our [review guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/) "Pull Requests may be closed after 30 days of inactivity". If however you are still interested in it, please ping us :) we can reopen.

Thank you for your contribution.

2021-10-11 20:07 UTC, closed without merging