Update product.js
PrestaShop/PrestaShop pull request #23681
Opened 2021-03-17 16:56 UTC by lyordey

Et voilà ! After changing the faulty variable by the new one, everything is working correctly again on the product page.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 1.7.7.x
| Description?      | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?             | bug fix / improvement / new feature / refacto / critical
| Category?         | FO / BO / CO / IN / WS / TE / LO / ME / PM
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| Fixed ticket?     | Fixes #{issue number here}.
| How to test?      | Please indicate how to best verify that this PR is correct.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

2021-03-17 17:03 UTC, NeOMakinG commented
Hello @lyordey, I completed your description (please do it next time :( )

Could you please create an issue and fill it in the description ? I really think you're PR is fine but it won't get accepted if no issue is linked to it!

2021-03-17 17:04 UTC, NeOMakinG approved these changes
Approving it, but please, create an issue ❤️

2021-03-17 17:20 UTC, lyordey reviewed
#23683

2021-03-18 04:58 UTC, lyordey reviewed
A closing parenthesis is missing at line 130.

2021-03-18 08:16 UTC, matthieu-rolland reviewed
Hi @lyordey , thank you for your contribution !

Someone will try to reproduce your issue, if you're issue is reproduced / validated, then we can send it in QA 8

2021-07-22 15:50 UTC, matks requested changes
Hi @lyordey I tried to reproduce your issue https://github.com/PrestaShop/PrestaShop/issues/23683 but I cant. What thumbnail are you talking about? I can click on all thumbnails I find and it works.

Without a bug we can reproduce we cannot validate this PR

2021-08-09 15:52 UTC, PierreRambaud commented
Hi @lyordey ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2021-08-09 15:52 UTC, closed without merging