Wrap playwright function waitForSelector
PrestaShop/PrestaShop pull request #23778
Opened 2021-03-25 12:30 UTC by boubkerbribri

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Wrap playwright function waitForSelector
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | no tests needed
| Possible impacts? | none

2021-03-25 15:48 UTC, NeOMakinG approved these changes

2021-03-26 08:59 UTC, matthieu-rolland approved these changes

2021-03-26 14:26 UTC, Progi1984 requested changes
WAIT FOR 1773 RELEASE

2021-03-31 07:37 UTC, Progi1984 approved these changes

2021-03-31 08:05 UTC, merged