Delete unused functions on common page
PrestaShop/PrestaShop pull request #23780
Opened 2021-03-25 15:28 UTC by boubkerbribri

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Delete unused functions on common page
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | no tests needed
| Possible impacts? | none

2021-03-25 15:40 UTC, matks approved these changes

2021-03-25 15:40 UTC, NeOMakinG approved these changes

2021-03-26 08:15 UTC, Progi1984 requested changes
## Need Release 1.7.7.3

2021-03-31 07:11 UTC, Progi1984 approved these changes

2021-03-31 07:36 UTC, merged

2021-04-06 12:37 UTC, SD1982 reviewed
LGTM