Fix enable demo mode on dashboard and trim the message set on contact us page
PrestaShop/PrestaShop pull request #23792
Opened 2021-03-26 15:16 UTC by boubkerbribri

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Fix enable demo mode on dashboard and trim the message set on contact us page
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | no tests needed
| Possible impacts? | none

2021-03-26 16:04 UTC, NeOMakinG approved these changes

2021-03-29 07:09 UTC, Progi1984 approved these changes

2021-03-29 07:10 UTC, PululuK approved these changes

2021-03-29 08:34 UTC, Progi1984 requested changes
WAIT FOR 1774 RELEASE

2021-03-31 06:47 UTC, Progi1984 approved these changes

2021-03-31 07:10 UTC, merged