Fix jquery selector warning with ps_currencyselector
PrestaShop/PrestaShop pull request #23802
Opened 2021-03-29 08:34 UTC by NeOMakinG

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 1.7.7.x
| Description?      | There was a warning when you've 2 currencies because the data-target of ps_currencyselector was useless but filled by a #
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #21228.
| How to test?      | You need to have 2 currencies, then go in FO and open a quickview of a product, the warning about jQuery selector '#' shouldn't be appearing
| Possible impacts? | Nothing

2021-03-30 07:23 UTC, Progi1984 approved these changes

2021-03-30 09:15 UTC, PierreRambaud approved these changes

2021-03-30 12:24 UTC, sowbiba approved these changes

2021-03-30 13:58 UTC, aDamelincourt commented
Thanks @NeOMakinG 
✔️ , verified on PS 1.7.7.3, with two or more currencies

2021-03-30 14:04 UTC, Progi1984 requested changes
## WAIT FOR 1774 RELEASE

2021-03-31 06:46 UTC, Progi1984 approved these changes

2021-03-31 06:47 UTC, merged

2021-03-31 06:47 UTC, Progi1984 commented
Thanks @NeOMakinG & @aDamelincourt

2023-02-15 13:20 UTC, lucasartsfr commented
Problem is Still here with 1.7.8.7

Wherever I click on the site, this message appear in console : 
![image](https://user-images.githubusercontent.com/26819739/219038578-2b58084d-b9f1-4351-a498-84c108f60349.png)

Tried Two currencies, disable plugin etc.. but it's not working