Open tracking url in a new tab and add the link to the order preview
PrestaShop/PrestaShop pull request #23819
Opened 2021-03-30 13:32 UTC by atomiix

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Tracking url links should open in a new tab. Also, there was no link in the order preview on the order list page. This PR fixes both issues.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23401
| How to test?      | Please see #23401
| Possible impacts? | 

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/23819)

2021-03-30 13:34 UTC, Progi1984 requested changes
Could you modify unit tests and add behat tests, please ?

2021-03-31 07:13 UTC, Progi1984 commented on tests/Integration/Behaviour/Features/Context/CarrierFeatureContext.php
> +     * @Given /^carrier "(.+)" uses "(.+)" as tracking url$/
```suggestion
     * @Given /^the carrier "(.+)" uses "(.+)" as tracking url$/
```

2021-03-31 07:14 UTC, Progi1984 commented on tests/Integration/Behaviour/Features/Context/CarrierFeatureContext.php
> +    public function setCarrierTrackingUrl($carrierName, $url)
```suggestion
    public function setCarrierTrackingUrl(string $carrierName, string $url): void
```

2021-03-31 07:14 UTC, Progi1984 commented on src/Adapter/Order/QueryHandler/GetOrderPreviewHandler.php
> +        $trackingUrl = null;
```suggestion
        $carrierName = $trackingUrl = null;
```

2021-03-31 07:14 UTC, Progi1984 reviewed
Some feedbacks

2021-04-07 15:16 UTC, PierreRambaud commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/shipping.html.twig
> +                <a href="{{ carrier.trackingUrl }}" target="_blank">{{ carrier.trackingNumber }}</a>
```suggestion
                <a href="{{ carrier.trackingUrl }}" target="_blank" rel="noopener noreferrer nofollow">{{ carrier.trackingNumber }}</a>
```

2021-04-07 15:16 UTC, PierreRambaud commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/preview.html.twig
> +                    <a href="{{ orderPreview.shippingDetails.trackingUrl }}" target="_blank">{{ orderPreview.shippingDetails.trackingNumber }}</a>
```suggestion
                    <a href="{{ orderPreview.shippingDetails.trackingUrl }}" target="_blank" rel="noopener noreferrer nofollow">{{ orderPreview.shippingDetails.trackingNumber }}</a>
```

2021-04-07 15:18 UTC, PierreRambaud requested changes
Sorry to block this PR, it's a great job, you even add test without waiting for @Progi1984 's comment :trollface: 
But I'm afraid there are security issue, you always have to set ` rel="noopener noreferrer nofollow"`when using `target="_blank"` to another website.

2021-04-07 15:37 UTC, PierreRambaud approved these changes

2021-04-08 07:15 UTC, Progi1984 approved these changes

2021-04-09 15:15 UTC, khouloudbelguith commented
Hi @atomiix,

It is Ok :heavy_check_mark: 
In the FO, I have the same behavior as PS1769.
I updated the tracking number from the BO and from API => ok :heavy_check_mark: 
https://drive.google.com/file/d/18icC7i_KO1aMuEhejHIN_8fFMftlxus0/view?usp=sharing

Thank you!

2021-04-12 06:58 UTC, merged

2021-04-12 06:58 UTC, Progi1984 commented
Thanks @atomiix & @khouloudbelguith

2021-05-04 11:45 UTC, kmorgen commented
Just updated a dev site to PS 1.7.7.4, and noticed the tracking url on the **Order List** page (dropdown) is incorrect.
It does not include the actual barcode number in the url like on the **Order details** page. 

Did nobody do any QA?

2021-05-04 12:25 UTC, matks commented
Hello @kmorgen 

Please remember this project follows a [Code of Conduct](https://github.com/PrestaShop/PrestaShop/blob/17196f515d27b02d9d8318f7da95e3907bde9d5d/CODE_OF_CONDUCT.md) that recommends

> Using welcoming and inclusive language
Being respectful of differing viewpoints and experiences
Gracefully accepting constructive criticism
Focusing on what is best for the community
Showing empathy towards other community members

> Did nobody do any QA?

If I am not wrong, this is [sarcasm](https://en.wikipedia.org/wiki/Sarcasm) and sarcasm is against our CoC.

This PR has been marked "QA ✔️ " as it was tested by someone. There is even a video record of what has been tested. If you think the topic can be improved, feel free to submit a Pull Request.

2021-05-04 14:08 UTC, kmorgen commented
> If I am not wrong, this is [sarcasm](https://en.wikipedia.org/wiki/Sarcasm) and sarcasm is against our CoC.
> 
> This PR has been marked "QA ✔️ " as it was tested by someone. There is even a video record of what has been tested. If you think the topic can be improved, feel free to submit a Pull Request.

I was not being sarcastic, but actually meant this as a question!

I was one of the original reporters of this issue, and it always takes a great effort to report and document new issues and to reproduce them. But when being fixed, the initial reporters seems not actively included as part of the QA process prior to release.

As a result of this many issues seem to need re-work for several updates over months/years, and often new issues are being introduced in the process.

It litterly took med 10 seconds to test the Order List page url was not working properly after updating to 1.7.7.4, as I already knew the issue. I really think you should consider to include the initial posters as part of the QA process somehow, as they are the ones dealing with the issues, so they can tell if the various fixes works as intended - even though they are not coders.

(How/where do I see this QA process and video records ect, When clicking the "QA ✔️ " image, I just end up here: https://github.com/PrestaShop/PrestaShop/labels/QA%20%E2%9C%94%EF%B8%8F

2021-05-04 15:40 UTC, kmorgen commented
Steps to reproduce the fix is not working as intended;

1. Add a Carrier tracking number to an order.
  (from a carrier with a pre-defined tracking URL containing the @ representing the tracking number part).
  
2. Compare the Carrier tracking url in **BO Order** page vs, the **Order List** page.
(the url on the Order List does not contain the tracking number, but only the raw pre-set url from Carrier settings. It should be identical to the Order details page)

2021-05-06 07:43 UTC, matks commented
> > If I am not wrong, this is [sarcasm](https://en.wikipedia.org/wiki/Sarcasm) and sarcasm is against our CoC.
> > This PR has been marked "QA ✔️ " as it was tested by someone. There is even a video record of what has been tested. If you think the topic can be improved, feel free to submit a Pull Request.
> 
> It was not meant as sarcastic, but actually as a question, as I don't understand the QA passing process.
> 
> I was one of the original reporters of this issue, and it always takes a great effort to report/document new issues and to reproduce them. But when being fixed, the initial reporters seems not actively included as part of the QA process prior to release.
> 
> As a result of this many issues seem to need re-work for several updates over months/years, and often new issues are being introduced in the process unfortunately.
> 
> It litterly took med 10 seconds to verify the Order List page url was not working properly after updating to 1.7.7.4, as I already knew about the issue. I really think you should consider to include the initial bug/feature reporters as a mandatory part of the QA process somehow. As they are the ones dealing with the issues, they can also verify if the various fixes works as intended - even if they might not be coders.
> 
> (How/where do I see this QA process and video records ect, When clicking the "QA ✔️ " image, I just end up here: https://github.com/PrestaShop/PrestaShop/labels/QA%20%E2%9C%94%EF%B8%8F
> Is i possible to be part of the QA process prior to releases, even if not a skilled coder?

Hello @kmorgen thank you for your answer it is very constructive.

I said "If I am not wrong, this is sarcasm and sarcasm is against our CoC." . It looks like I was wrong 😊  and I knew it could happen, which is why I made sure to include "If I am not wrong" at the beginning of the sentence.

> >Is i possible to be part of the QA process prior to releases, even if not a skilled coder

That is actually a very good idea 👍  although I am not sure a lot of people who report bugs will go as far as testing the bugfix. But we can try.

Thank you for your very good idea I will reach out to the team to see if we can improve our QA process to include the bug reporter.