Update state.xml - Distrito Federal changed to Ciudad de México
PrestaShop/PrestaShop pull request #23828
Opened 2021-03-30 23:28 UTC by rickygzz

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | There is a file named `install-dev/data/xml/state.xml` which is used when you first install the prestashop on the server. It is used to create the the database table `ps_states` with the states values for all the countries (when available). I am just suggesting an update to this file, since it has been several years since Distrito Federal changed its name to Ciudad de México.
| Type?             | improvement
| Category?         | LO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes # none.
| How to test?      | It just updates a city name in Mexico.
| Possible impacts? | Since everything is linked to the state_id and not to the state.name, I dont think it will impact anything.

Changed:

```javascript
-    <state id="DIF" id_country="MX" id_zone="North_America" iso_code="DIF" tax_behavior="0" active="1">
-      <name>Distrito Federal</name> 
+    <state id="CMX" id_country="MX" id_zone="North_America" iso_code="CMX" tax_behavior="0" active="1">
+      <name>Ciudad de México</name>
```

name tag Distrito Federal to Ciudad de México
and its state tag properties id= and iso_code= to "CMX" according to its iso3166-2 code.

On 29 January 2016, Mexico City ceased to be the Federal District (Spanish: Distrito Federal or D.F.), and was officially renamed "Ciudad de México" (or "CDMX")

Source:
https://www.iso.org/obp/ui/#iso:code:3166:MX
https://en.wikipedia.org/wiki/Mexico_City#20th_century_to_present

2021-03-31 07:32 UTC, Progi1984 approved these changes

2021-04-01 12:24 UTC, sowbiba commented
I approve the change but IMHO this must be validated by @PrestaShop/product-team

2021-04-01 12:25 UTC, sowbiba requested changes
I approve the change but IMHO this must be validated by @PrestaShop/product-team

Maybe you will have to create an issue to open the discussion if there is one

2021-04-01 12:48 UTC, MatShir commented
Looks good to me ! :)

2021-04-01 12:49 UTC, sowbiba approved these changes

2021-04-01 12:53 UTC, PululuK approved these changes

2021-04-01 16:01 UTC, Robin-Fischer-PS commented
Hello @rickygzz !

With your PR, the state is now OK (Ciudad de México) : 

![pr23828 mexico ok](https://user-images.githubusercontent.com/55688534/113321504-f50f1480-9313-11eb-81ab-093494c0e24c.png)

So it's QA :heavy_check_mark: !

Thanks for your PR :)

2021-04-01 16:02 UTC, PululuK commented
Thanks @rickygzz

2021-04-01 16:02 UTC, merged