Fixed cart not updated on voucher update
PrestaShop/PrestaShop pull request #23831
Opened 2021-03-31 06:37 UTC by SebBareyre

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Cart is not updated properly when there is a change in voucher 
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #19393 (#20009 is a duplicate)
| How to test?      | Create a cart rule auto applicable (without code) and set the cart rule inactive or with an  expired date or without quantity available. The cart rule will be applicated. Try again with the patch, it will fix that.
| Possible impacts? | No impacts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/23831)

2021-03-31 08:32 UTC, SebBareyre commented
For information, you need to update the pull request template ;) 
the "critical" PR type was in the proposals...

2021-03-31 08:37 UTC, PierreRambaud commented on classes/Cart.php
> +				AND cr.`quantity` > 0
```suggestion
                AND NOW() BETWEEN cr.date_from AND cr.date_to
                AND cr.`active` = 1
                AND cr.`quantity` > 0
```

But I'm afraid you break integration tests, you change is breaking something :)

2021-03-31 08:42 UTC, SebBareyre commented on classes/Cart.php
> +				AND cr.`quantity` > 0
@Progi1984  Ok, I let you have a look on a manually test ;)

2021-03-31 09:29 UTC, Progi1984 commented
@SebBareyre Could you fix Behat issues ?

I think your PR has a bigger impact because the command `AddCartRuleToOrderCommand` (in `src/Core/Domain/Order/Command/AddCartRuleToOrderCommand.php` file) needs to be improved with a check if the cart rule is active, has quantity and is in date.

2021-03-31 13:12 UTC, SebBareyre commented
@Progi1984 I let you do that 😉. I made the PR and I haven't more times to do that right now

2021-03-31 13:56 UTC, Progi1984 commented
@SebBareyre If #20009 is prioritzed by @PrestaShop/product-team, we work on it. It's why we are open to contributions and discussions to improve these contributions.

2021-08-04 13:17 UTC, matks requested changes
Hi, just like my maintainer peers said: the php class you are modifying is a critical piece of code, and modifying it could maybe solve one bug but introduce five others. This is why we need extra caution when we validate changes of this class, and the best extra caution we have as developers are tests.

Without tests, we cannot validate your changes in an automatic and long-term manner. Moreover the tests we already have are failing, which seems to indicate that indeed the changes of this PR introduce a buggy behavior.

Without tests acting like a safety net, I cannot approve this PR.

2021-10-11 13:37 UTC, PierreRambaud commented
Hi @SebBareyre ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2021-10-11 13:37 UTC, closed without merging