Fix nightly tests 09-04-2021
PrestaShop/PrestaShop pull request #23965
Opened 2021-04-09 13:01 UTC by boubkerbribri

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix nightly tests 09-04-2021
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | No tests needed
| Possible impacts? | none

2021-04-09 13:13 UTC, Progi1984 approved these changes

2021-04-09 13:13 UTC, nesrineabdmouleh submitted a review, later dismissed

2021-04-12 06:59 UTC, Progi1984 commented
@boubkerbribri "UI tests code checks / Checking doubles in steps identifiers" seems :red_circle:

2021-04-12 07:09 UTC, Progi1984 requested changes
CI is :red_circle:

2021-04-12 08:39 UTC, Progi1984 approved these changes

2021-04-12 08:40 UTC, nesrineabdmouleh approved these changes

2021-04-12 08:41 UTC, Progi1984 approved these changes

2021-04-12 08:54 UTC, merged

2021-04-12 08:54 UTC, Progi1984 commented
Thanks @boubkerbribri