Register feature flag page hooks
PrestaShop/PrestaShop pull request #24022
Opened 2021-04-13 09:30 UTC by matks

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Register feature flag page hooks
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| How to test?      | No need for QA I think 🤔  ?
| Possible impacts? | I modify hook configuration files to acknowledge hooks related to Feature Flags

2021-04-13 09:31 UTC, Progi1984 commented on install-dev/upgrade/sql/1.7.8.0.sql
> +(NULL,"actionFeatureFlagSave","Modify feature flag options form saved data","This hook allows to modify data of feature flag options form after it was saved",1);
Please move it to l.24

2021-04-13 09:32 UTC, Progi1984 requested changes
Please merge sql hooks query

2021-04-13 09:32 UTC, matthieu-rolland approved these changes, later dismissed

2021-04-13 09:32 UTC, eternoendless commented on install-dev/data/xml/hook.xml
> +      <description>This hook allows to modify feature flag page form FormBuilder</description>
```suggestion
      <description>This hook allows to modify the Feature Flag page form's FormBuilder</description>
```

2021-04-13 09:33 UTC, eternoendless commented on install-dev/data/xml/hook.xml
> +      <description>This hook allows to modify feature flag data being submitted through the form after it was saved</description>
```suggestion
      <description>This hook allows to modify the Feature Flag data being submitted through the form after it was saved</description>
```

2021-04-13 09:34 UTC, atomiix commented on install-dev/upgrade/sql/1.7.8.0.sql
> +(NULL,"actionFeatureFlagSave","Modify feature flag options form saved data","This hook allows to modify data of feature flag options form after it was saved",1);
```suggestion
(NULL, "actionFeatureFlagForm", "Modify feature flag options form content", "This hook allows to modify feature flag options form FormBuilder", 1),
(NULL, "actionFeatureFlagSave", "Modify feature flag options form saved data", "This hook allows to modify data of feature flag options form after it was saved", 1);
```

2021-04-13 09:38 UTC, matks commented
> Please merge sql hooks query

Euuuuuh 😅  ? I'm afraid I dont understand.

I'll be happy merging something but I dont see what you mean by SQL hooks query. Is that another PR?

2021-04-13 09:40 UTC, atomiix commented
@matks I think what @Progi1984 meant was to group the new sql queries with the already present in the 1.7.8.0.sql, line 24 😅

2021-04-13 09:41 UTC, atomiix approved these changes, later dismissed

2021-04-13 09:41 UTC, matks commented
> @matks I think what @Progi1984 meant was to group the new sql queries with the already present in the 1.7.8.0.sql file, line 24 😅

Aaaaaah 😛  the word "merge" has a very specific meaning for maintainers 😆  when you tell me to merge something I think about Pull Requests

2021-04-13 09:42 UTC, atomiix commented on install-dev/upgrade/sql/1.7.8.0.sql
> +  (NULL, 'actionFeatureFlagSave', 'Modify feature flag options form saved data', 'This hook allows to modify data of feature flag options form after it was saved', 1);
```suggestion
  (NULL, 'actionFeatureFlagSave', 'Modify feature flag options form saved data', 'This hook allows to modify data of feature flag options form after it was saved', 1)
```

2021-04-13 09:43 UTC, PululuK commented on install-dev/upgrade/sql/1.7.8.0.sql
> +  (NULL, 'actionFeatureFlagSave', 'Modify feature flag options form saved data', 'This hook allows to modify the Feature Flag data being submitted through the form after it was saved', 1);
```suggestion
  (NULL, 'displayAdminOrderCreateExtraButtons', 'Add buttons on the create order page dropdown', 'Add buttons on the create order page dropdown', '1'),
  (NULL, 'actionFeatureFlagForm', 'Modify feature flag options form content', 'This hook allows to modify the Feature Flag page form FormBuilder', 1),
  (NULL, 'actionFeatureFlagSave', 'Modify feature flag options form saved data', 'This hook allows to modify the Feature Flag data being submitted through the form after it was saved', 1)
```

2021-04-13 09:44 UTC, PululuK commented on install-dev/upgrade/sql/1.7.8.0.sql
> +  (NULL, 'actionFeatureFlagSave', 'Modify feature flag options form saved data', 'This hook allows to modify the Feature Flag data being submitted through the form after it was saved', 1);
oups .. @atomiix already catch ;)

2021-04-13 09:53 UTC, atomiix approved these changes

2021-04-13 09:53 UTC, PululuK approved these changes

2021-04-13 09:57 UTC, matks commented
@atomiix @PululuK @eternoendless @Progi1984 thank you for the very quick review !

2021-04-13 10:31 UTC, Progi1984 approved these changes

2021-05-04 12:39 UTC, boubkerbribri approved these changes
Tested on a fresh 1.7.8.x install and after an upgrade.
It's QA :heavy_check_mark: 
Thanks @matks

2021-05-04 12:42 UTC, merged

2021-05-04 12:42 UTC, PululuK commented
Thanks @matks