Improve Product.php MySQL 8 compatibility
PrestaShop/PrestaShop pull request #24089
Opened 2021-04-16 10:42 UTC by daresh

In MySQL 8 implicit and explicit sorting for GROUP BY is removed. This code relies on that sorting, so it should be improved by adding explicit ORDER BY. It does not break backward compatibility.
More about implicit and explicit sorting for GROUP BY removal: https://mysqlserverteam.com/removal-of-implicit-and-explicit-sorting-for-group-by/

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 1.7.7.x
| Description?      | Prestashop 1.7 still uses the getAttributesResume function, we isolated this function on a server with MySQL 8 and found it returning incorrect attributes resume, names of attributes don't match their ID's
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | yes 
| How to test?      | Create any test for the getAttributesResume function to find out it's returning incorrect results for MySQL 8.
| Possible impacts? | Probably back office, this function was more in use on Prestashop 1.6, when I can clearly observe the error for combination quantities. On 1.7 I don't see an error there, but it's good to make sure this function works correctly, since there is no backward compatibility break with this improvement.

2021-04-16 15:43 UTC, Arman-Hosseini approved these changes, later dismissed

2021-04-17 21:30 UTC, PierreRambaud submitted a review, later dismissed

2021-04-19 07:18 UTC, Progi1984 approved these changes, later dismissed

2021-04-28 06:49 UTC, sowbiba submitted a review, later dismissed

2021-04-28 09:29 UTC, Progi1984 commented
@daresh Could you give a real test scenario ?

2021-04-28 11:26 UTC, daresh commented
> @daresh Could you give a real test scenario ?

The situation looks like this - an easy to trace scenario can be observed in Prestashop 1.6, where on MySQL 8.0 the list of quantities for combinations in back office is incorrect. It's not the case for Prestashop 1.7, but that code seems to be still in use, so the error may occur in some other area.

2021-04-30 13:28 UTC, matks commented
https://github.com/PrestaShop/PrestaShop/issues/23973 seems to be a real test scenario

2021-05-04 14:46 UTC, jolelievre requested changes
Hi @daresh,

I'm requesting changes on this PR not because of its content but because of its target (the fix seems legitimate to me). We froze the 1.7.8 version a few weeks earlier and created a dedicated branch. Since this PR fixes a critical bug for 1.7.8 it needs to target the 1.7.8.x branch

Is it possible for you to, please, change the target of your PR and rebase your patch branch on 1.7.8.x ?

Thank you

2021-05-04 15:03 UTC, daresh commented
Hi @jolelievre 

Actually it's not me who added the target of this fix, but @atomiix, so I don't know what to do now :) And since I'm not an everyday github user, I have no problem if you guys continue on with this bugifx, since you already know what the problem and solution is.

2021-05-05 08:16 UTC, atomiix commented
Hi @daresh I only linked this PR to an issue but I don't think I changed the target branch 😄
But now, I changed it and it should be good 👍

2021-05-10 15:33 UTC, jolelievre approved these changes

2021-05-10 15:38 UTC, PierreRambaud approved these changes

2021-05-11 07:07 UTC, Progi1984 approved these changes

2021-05-17 13:37 UTC, boubkerbribri commented
Hello
Verified with automated tests : 

- BO -> Catalog -> Products
- BO -> Catalog -> Attributes
- BO -> Shop parameters -> products setting
- FO

And it fixes #23973 

So it's QA :heavy_check_mark:  
Thank you @daresh

2021-05-17 13:39 UTC, merged

2021-05-17 13:39 UTC, Progi1984 commented
Thanks @daresh & @boubkerbribri