Make multistore dropdown appear in group shop context
PrestaShop/PrestaShop pull request #24108
Opened 2021-04-19 10:02 UTC by matthieu-rolland

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 1.7.7.x
| Description?      | The multistore dropdown should appear in group shop context, this PR fixes this.
| Type?             | bug fix / improvement / new feature / refacto / critical
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24066
| How to test?      | The test procedure is described in the issue.
| Possible impacts? | no

2021-04-19 10:04 UTC, Progi1984 approved these changes, later dismissed

2021-04-20 15:44 UTC, matks approved these changes, later dismissed

2021-04-21 14:47 UTC, PierreRambaud approved these changes, later dismissed

2021-04-23 14:34 UTC, Progi1984 approved these changes, later dismissed

2021-04-23 14:37 UTC, PierreRambaud approved these changes, later dismissed

2021-04-23 14:59 UTC, Robin-Fischer-PS commented
Hi @matthieu-rolland ,

I have an issue with your PR : 

When I have 2 groups (group 1 and 2), if I customize a field in a shop in group 1, the dropdown is displayed also when in context "group 2". I think the dropdown should be only displayed when a shop in the group is customized.

See screenrecord : 

https://drive.google.com/file/d/1aMwHjvbGzUpYk3CnPzs15V-t-GUezCqD/view?usp=sharing

Thanks !

2021-04-26 08:53 UTC, Progi1984 requested changes
Your rebase is broken

2021-04-26 09:21 UTC, closed without merging

2021-04-26 09:22 UTC, matthieu-rolland commented
I closed the PR and made a new one