Added Basic Tests for WebService
PrestaShop/PrestaShop pull request #24162
Opened 2021-04-22 14:33 UTC by Progi1984

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Added Basic Tests for WebService
| Type?             | improvement
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Relative to #23100
| How to test?      | N/A
| Possible impacts? | N/A

2021-04-22 14:42 UTC, KminekMatej commented
Just what I needed to start with testing Webservice, thanks!

2021-04-22 16:07 UTC, matks reviewed
Hi !

Whao ! that is a great improvement 😊 

May I suggest 2 things? I would like to know what you think about it

1. Use Behat to introduce reader-friendly assertion steps
For example we could wrap
```
        self::assertEquals(1, $output->filter('prestashop > errors > error')->count());
```
inside a nice Behat step "Then I expect 1 error"
or
```
self::assertEquals(
            'No permission for this authentication key',
            $output->filter('prestashop > errors > error')->first()->filter('message')->text()
        );
```
by
```
THEN I expect the error message 'No permission for this authentication key' to be returned
```

2. I think webservice can return XML or JSON. You use the DOMCrawler to navigate into the output XML if I understand correctly.

If using the DOMCrawler makes the writing of the tests harder, maybe using JSON output will be easier? However I am not sure Webservice allows JSON input.

We could also think about enabling Webservice to return _something else_ than JSON and XML such as a serialized PHP object. It would then become a lot easier to assert and you would not need to parse the output. But that requires changing the implementation of the webservice and this could be complex and risky.

2021-04-22 16:07 UTC, matks commented on classes/webservice/WebserviceKey.php
> +     * @var int
Did you want to add param instead of `@var` ?

2021-04-22 16:07 UTC, matks commented on tests/Integration/Webservice/AddressesTest.php
> +        $data = '<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
In order to avoid repeating these custom XML document when you add more tests, maybe a function `generateInputXMLForAddress()` could be used?

2021-04-22 20:59 UTC, KminekMatej commented
@matks Prestashop currently supports output as XML **OR** JSON, and both of the outputs are being generated by different classes. So there should be one test for XML output (using DOMcrawler) and second test for JSON output (not done yet).

Webservice definitely doesnt allow JSON input, it takes only XML. Would be nice to have this feature in the future, as JSON is currently considered as standard for API.

About Webservice returning serialized object. You already have Webservice, capable of returning JSON or XML output. I really wouldn't recommend adding another output type, such as serialized object, since those two are more than enough to cover all customers needs. You would have just more code to maintain, not mentioning that JSON output is a standard nowadays and its super easy to decode /encode it into any structure of basically any language.

2021-04-23 07:24 UTC, matks commented
> @matks Prestashop currently supports output as XML **OR** JSON, and both of the outputs are being generated by different classes. So there should be one test for XML output (using DOMcrawler) and second test for JSON output (not done yet).

You can workaround this issue by splitting the Webservice in component.

Consider that the Webservice is a system that outputs data in a dedicated format. We could say it's built on 3 components
1. A component that fetches the data from database
2. A component that gathers, reworks, refines the data extracted from database like an ETL
3. A component that outputs the built data in wanted format

When you send a HTTP request to webservice
- component 1 does its job, outputs some raw data from MySQL
- component 2 does its job, transform raw data into structured data
- component 3 does its job, transform structured data into wanted format (JSON or XML)

If you are able to test very well each component, you do not need a full test coverage of all possible outputs for JSON and XML. If you can use tests to validate that component 2 works very well alone, then the tests for component 3 only need to verify "when I give it a data structure like A it should output format B". Component 3 is an encoder (see https://developer.apple.com/documentation/foundation/jsonencoder for example) and could actually be replaced by available encoders for PHP.

Nevertheless it would be important to have a few tests that run components 1, 2 and 3 together to make sure they are plugged to one another correctly 😄  . But you do not need to be exhaustive with this last set of tests.

So when I suggest to output PHP serialized objects, the idea behind (sorry if I did not explain it correctly) is "let's isolate components 2 and components 3, use a PHP object structure between the 2 of them as their way to communicate, and when we want to test component 2 we just need to serialize whatever comes out of it instead of performing encoding".

That, however, is a big work. I was just curious to see if @Progi1984 is interested in this for the future.

2021-04-23 07:40 UTC, KminekMatej commented
@matks Idea of splitting the Webservice into components is very good. That is actually exactly what I developed in my awaiting PR #23100 . There I am composing level 2 bz using PHP class ApiNode. After I compose all the structure in the ApiNode tree, I use either WebServiceOutputJSON or WebServiceOutputXML components to transform that tree structure into wanted format.

However, during autotesting, you should simulate real usage as much as you can. Process is, that user sends request, where he specifies wanted output in header (json/xml). Output that Webservice gives to him is already in wanted format. In my opinion, you should simulate this principle as much as you can, thats why you need to create two test, where you give as input some data and test if the XML answer is proper. Afterwards, you should test the same opration goes identically, also with JSON output (these two tests can share the same initial phase, no redundant code needed). 

I dont actually think, as you stated, that you are able to test very well each component. You can test the whole process at once. And I believe thats how you should test this.

2021-04-23 07:46 UTC, matks commented
> I dont actually think, as you stated, that you are able to test very well each component. You can test the whole process at once. And I believe thats how you should test this.

Each type of test brings value, but usually the low-level tests
- are easier to write
- catch issues at a deeper level
- are faster to run

You can see the great article [The Test Pyramid
](https://martinfowler.com/articles/practical-test-pyramid.html#TheTestPyramid) from MartinFowler about it

> * Write tests with different granularity
> * The more high-level you get the fewer tests you should have

> Stick to the pyramid shape to come up with a healthy, fast and maintainable test suite: Write lots of small and fast unit tests. Write some more coarse-grained tests and very few high-level tests that test your application from end to end. Watch out that you don't end up with a test ice-cream cone that will be a nightmare to maintain and takes way too long to run.

2021-04-26 08:18 UTC, sowbiba reviewed
Nice Job @Progi1984

2021-04-26 08:18 UTC, sowbiba commented on tests/Integration/Webservice/AbstractWebserviceTest.php
> +    protected const WS_KEY = 'ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEF';
Add a blank line between attributes

2021-04-26 08:18 UTC, sowbiba commented on tests/Integration/Webservice/AbstractWebserviceTest.php
> +class StreamWrapperPHP
Can't we separate this class into a different file ?

2021-04-26 08:18 UTC, sowbiba commented on tests/Integration/Webservice/AddressesTest.php
> +        self::assertEquals(21, $output->filter('prestashop > errors > error')->last()->filter('code')->text());
Some repetitions to crawl to the data we want to test. Can we have helpers for that
like 'getErrors', 'getCode' ...

2021-04-26 08:18 UTC, sowbiba commented on tests/Integration/Webservice/AddressesTest.php
> +        $output = $this->requestWebserviceXML($this->wsKey->key, 'DELETE', 'addresses/' . $id);
suggestion : Can we use constants like Symfony\Component\HttpFoundation\Request::METHOD_DELETE for HTTP verbs ?

2021-05-04 06:59 UTC, KminekMatej commented
+1 for merge, I am ready to create additional tests over WebService afterwards

2021-07-28 14:37 UTC, KminekMatej commented
Is there any progress in merging this so far?

2021-08-20 09:36 UTC, PierreRambaud commented on classes/webservice/WebserviceKey.php
> +     * @var int
I think yes ^^

2021-10-01 14:33 UTC, PierreRambaud commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +     * @Then /^I should get a number of ([0-9]+) item[s]{0,1} of type "(.+)"$/
```suggestion
     * @Then /^I should get a number of (\d+) items? of type "(.+)"$/
```

2021-10-01 14:33 UTC, PierreRambaud commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +     * @Then /^I should get a number of ([0-9]+) error([s]{0,1})$/
```suggestion
     * @Then /^I should get a number of (\d+) error?$/
```

2021-10-01 14:33 UTC, PierreRambaud commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +     * @Then /^I should get an error with code ([0-9]+) and message "(.+)"$/
```suggestion
     * @Then /^I should get an error with code (\d+) and message "(.+)"$/
```

2021-10-01 14:34 UTC, PierreRambaud commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +        $_SERVER['REQUEST_METHOD'] = $requestMethod;
Add a comment to explain why you have to set these variables :)

2021-10-01 14:34 UTC, PierreRambaud commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +class StreamWrapperPHP
Should be in another file don't use two classes in one file

2021-10-01 14:35 UTC, PierreRambaud commented on webservice/dispatcher.php
> +$request->errors = [];
This is already defined in WebserviceRequestCore

2021-10-01 15:03 UTC, PierreRambaud commented on classes/webservice/WebserviceRequest.php
> +        self::$_instance = null;
```suggestion
        static::$_instance = null;
```

2021-10-05 15:08 UTC, PierreRambaud approved these changes
Great job! I like it!

2021-10-05 15:46 UTC, sowbiba approved these changes, later dismissed
Great job. Thanks ;)

2021-10-06 08:05 UTC, Robin-Fischer-PS commented
Hi,

This should be tested by a dev.

2021-10-06 08:26 UTC, PierreRambaud commented on webservice/dispatcher.php
> +$request->clearInstance();
Just notice something, the clearInstance shouldn't be called here but here https://github.com/PrestaShop/PrestaShop/pull/24162/files#diff-18e4ef04b710a09044f70ca5f52bc8c1fd518a335177d776a9b3094c9b6eedfcR220

2021-10-06 08:26 UTC, PierreRambaud requested changes, later dismissed
Just a little thing I forget to check :sweat_smile:

2021-10-06 08:26 UTC, PierreRambaud commented on webservice/dispatcher.php
> +$request->clearInstance();
With this call here, you're getting the instance, then directly clear it,  which has no sense

2021-10-07 15:59 UTC, jolelievre commented on classes/webservice/WebserviceRequest.php
> +    public function clearInstance(): void
Hmm, if it's a static cache then the cleaning method should also be static logically (you don't need to instantiate an entity to clean a static class cache). And if you need a static method for this maybe you could instead use the `public static function resetStaticCache()` method which comes from the ObjectModel and is common to all entities.

It is used in behat tests a lot to clear static cache between features or scenarios, if we can keep using the same method it would be better for consistency.

2021-10-08 09:31 UTC, Progi1984 commented on classes/webservice/WebserviceRequest.php
> +    public function clearInstance(): void
Done

2021-10-08 09:31 UTC, Progi1984 commented on webservice/dispatcher.php
> +$request->clearInstance();
Fixed

2021-10-08 15:16 UTC, jolelievre reviewed
Thanks for the contribution @Progi1984 
It's really good that we start testing this part! However I see some flows in the previous implementation, that you used as a base for the new context I guess

basically relying on stateful stored data in behat tests is a bad practice, we already have lots of pain to test our code because of our steaful contexts, if we start adding some in the tests themselves we will soon start fighting with a three headed hydra 😅

It's not always easy for complex cases I know that, but I made a few suggestions which, I believe, will allow us to get rid of stateful test contexts

2021-10-08 15:16 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/Domain/WebserviceKeyFeatureContext.php
> +        $data = SharedStorage::getStorage()->exists($propertiesKey)
Mmmm, this is a very weird way to use behat... From what I understood, there are several sentences like:
`And I specify "View" permission for "addresses, carriers, carts" resources for new webservice key "key1"`

Which store the values in the SharedStorage, and finally one call to:
`When I add webservice key "key1" with specified properties`

That fetch all the data stored in the shared storage to create the webservice key.. This seems highly unstable as everything becomes stateful!!

And now you make it even more statefuil because you use the previously saved data for creation and merge them with the data for edition... So the parameters you provide in your scenario for the edit command do not reflect at all the expected result of the modification (it is merged with data from the past which you have few control on)

2021-10-08 15:16 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/Domain/WebserviceKeyFeatureContext.php
> +        $data = SharedStorage::getStorage()->exists($propertiesKey)
I would suggest refactoring both Add and Edit end points so that they can be used as one end point instead of multiple saved end points Especially since the data saved in SharedStorage seems to never be cleaned, so it impacts the scenario in the whole feature

What's worse is that the same "key1" reference is used multiple times so it's even more complicated to follow what's happening

2021-10-08 15:16 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/Domain/WebserviceKeyFeatureContext.php
> +        $data = SharedStorage::getStorage()->exists($propertiesKey)
We can change the format so the initial format:

```feature
  Scenario: Create Webservice key
    Given I specify following properties for new webservice key "key1":
      | key              | DFS51LTKBBMBGF5QQRG523JMQYEHU4X7 |
      | description      | Testing webservice key           |
      | is_enabled       | 1                                |
      | shop_association | shop1                            |
    And I specify "View" permission for "addresses, carriers, carts" resources for new webservice key "key1"
    And I specify "Add" permission for "orders, products, groups" resources for new webservice key "key1"
    And I specify "Modify" permission for "employees, customers, manufacturers" resources for new webservice key "key1"
    And I specify "Delete" permission for "suppliers, languages, countries" resources for new webservice key "key1"
    And I specify "Fast view" permission for "taxes, zones" resources for new webservice key "key1"
    When I add webservice key "key1" with specified properties
```

would become:

```feature
  Scenario: Create Webservice key
    When I add webservice key "key1" with following properties:
      | key              | DFS51LTKBBMBGF5QQRG523JMQYEHU4X7 |
      | description      | Testing webservice key           |
      | is_enabled       | 1                                |
      | shop_association | shop1                            |
      | view.            | addresses, carriers, carts       |
      | add              | orders, products, groups         |
      | modify           | employees, customers, manufacturers |
      | delete           | suppliers, languages, countries  |
      | fast_view        | taxes, zones                     |
```

It is easier to read and it gets rid of the unstable multi endpoints stateful creation workflow.

2021-10-08 15:16 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/Domain/WebserviceKeyFeatureContext.php
> +        $data = SharedStorage::getStorage()->exists($propertiesKey)
The edit would follow similar format, as for the assertion it could also be modified in such format but it's less critical As it doesn't create state in the tests, it simply separates the assertions

2021-10-08 15:16 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/Util/StreamWrapperPHP.php
> +class StreamWrapperPHP
Can you add a description as to what this class is supposed to do
I have a rough idea but it should be more descriptive of what it does (you can add a short example of code if the description is too complicated to write)

2021-10-08 15:16 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +        $this->webserviceKey = $webservice->key;
Here again saving the webservice key in a class field makes the tests stateful which is also unstable In this case it's easier to get rid of the state you can simply use the key in your endpoint:
`I request the Webservice using key "sfddsgf" with the method GET on the endpoint "addresses"`

2021-10-08 15:16 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +    public function whenRequest(string $method, string $endpoint, TableNode $rows = null): void
You should split this endpoint into several ones:
- one for read requests (GET, HEAD) which uses `TableNode` as the container for expected returns
- one for write requests (POST, PUT) which uses `TableNode` as the container for input data
- I guess DELETE is different and doesn't need any `TableNode`

2021-10-08 15:16 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +        $_SERVER['REQUEST_METHOD'] = $requestMethod;
Agreed, and maybe you should clean them after the feature is over They could have side effects on parts of code like `Tools::getValue` which read directly in `$_GET` for example (among many other things that could go wrong 😅 )

2021-10-08 15:16 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +    public function assertLastRequestHasValues(TableNode $rows): void
This should be part of the GET end point, assertion data are already present in the TableNode parameter thus all is handled in a single end point (no more need to store content in `$this->output`)

2021-10-08 15:16 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +    public function assertLastRequestHasValues(TableNode $rows): void
If you want to keep the listing simpler to test, maybe you'll need two endpoint for the list API and the entity API, one will use a big TableNode to assert each entity fields, the other can simply use two parameters inside the sentence itself:

```feature
    When I list "addresses" I should get 5 addresses
    When I get entity via "addresses/5" I should get following properties:
        | address_id | 42 |
        | first_name | jo |
```

2021-10-13 13:11 UTC, Progi1984 commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +    public function whenRequest(string $method, string $endpoint, TableNode $rows = null): void
Fixed.

2021-10-13 13:11 UTC, Progi1984 commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +    public function assertLastRequestHasValues(TableNode $rows): void
Fixed

2021-10-13 13:13 UTC, Progi1984 commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +        $_SERVER['REQUEST_METHOD'] = $requestMethod;
Fixed :)

2021-10-13 13:37 UTC, Progi1984 commented on tests/Integration/Behaviour/Features/Context/Util/StreamWrapperPHP.php
> +class StreamWrapperPHP
Fixed

2021-10-14 08:50 UTC, Progi1984 commented on tests/Integration/Behaviour/Features/Context/Domain/WebserviceKeyFeatureContext.php
> +        $data = SharedStorage::getStorage()->exists($propertiesKey)
Fixed

2021-10-14 08:50 UTC, Progi1984 commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +        $this->webserviceKey = $webservice->key;
Fixed

2021-10-21 14:50 UTC, jolelievre reviewed
Thanks @Progi1984 
It's much better now, I added a few comments and questions because I didn't fully understand everything

2021-10-21 14:50 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/Domain/WebserviceKeyFeatureContext.php
> +        $webserviceKey = new WebserviceKey($webserviceKeyId);
I don't think you need to fetch the object, since you only need the ID to create the command, which is already stored in `$webserviceKeyId`

2021-10-21 14:50 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/Domain/WebserviceKeyFeatureContext.php
>          $command = new EditWebserviceKeyCommand($webserviceKey->id);
```suggestion
        $command = new EditWebserviceKeyCommand($webserviceKeyId);
```

2021-10-21 14:50 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/Util/StreamWrapperPHP.php
> + * Permits to mock the php://input stream
```suggestion
 * Allows to mock the php://input stream
```

2021-10-21 14:50 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/Util/StreamWrapperPHP.php
> +class StreamWrapperPHP
Thanks, but I personnaly don't understand how this works 😅

Why do you need this wrapper and why do register it in place of the usual one? Isn't it enough to just use `ob_start` and `ob_get_clean` ?

2021-10-21 14:50 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +            stream_register_wrapper('php', StreamWrapperPHP::class);
```suggestion
            stream_wrapper_register('php', StreamWrapperPHP::class);
```

2021-10-21 14:50 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +            stream_register_wrapper('php', StreamWrapperPHP::class);
Seems like `stream_register_wrapper` is an alias (based on PHP doc)

2021-10-21 14:50 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +            stream_wrapper_unregister('php');
Do you need to always unregister/register it each time?
Since it's always the same one registering it only once should be enough no? 

It seems like you can check this via `in_array('php', stream_get_wrappers())`

2021-10-21 14:50 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +            stream_wrapper_unregister('php');
Or maybe you should call for `stream_wrapper_unregister` at the end of the method, so that it is always cleared and does not impact the following tests in the suite

2021-10-21 14:50 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +     * @When /^I use Webservice with key "(.*)" for removing "(.+)" with id ([0-9]+)$/
```suggestion
     * @When /^I use Webservice with key "(.*)" to remove "(.+)" with id ([0-9]+)$/
```

2021-10-21 14:50 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +     * @When /^I use Webservice with key "(.*)" for adding "(.+)"$/
```suggestion
     * @When /^I use Webservice with key "(.*)" to add "(.+)"$/
```

2021-10-21 14:50 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +     * @When /^I use Webservice with key "(.*)" for updating "(.+)"$/
```suggestion
     * @When /^I use Webservice with key "(.*)" to update "(.+)"$/
```

2021-10-21 14:50 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +     * @Then /^using Webservice with key "(.*)" for viewing "(.+)" with id ([0-9]+), I should get following properties\:$/
```suggestion
     * @Then /^using Webservice with key "(.*)" to view "(.+)" with id ([0-9]+), I should get following properties\:$/
```

2021-10-21 14:50 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +    protected $output;
```suggestion
    protected $lastOutput;
```

2021-10-21 14:50 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +        $this->output = $this->requestWebserviceXML($webserviceKey, $method, $endpoint, $postFields);
```suggestion
        return $this->requestWebserviceXML($webserviceKey, $method, $endpoint, $postFields);
```

2021-10-21 14:50 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +        $this->output = $this->requestWebserviceXML($webserviceKey, $method, $endpoint, $postFields);
Just a suggestion, but maybe it's cleaner if this method returns its output instead of storing + returning it

And in the behat endpoints you can always do `$this->output = $this->whenRequest(...)` but at least the storage is handled by the endpoint itself, not the sub method So the submethods could be called multiple times in the same test without storing the result for example

2021-10-21 14:50 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +     * @Then /^I should get a number of (\d+) errors?$/
```suggestion
     * @Then /^I should get (\d+) errors?$/
```

2021-10-21 14:50 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +     * @Then /^I should get a number of (\d+) items? of type "(.+)"$/
```suggestion
     * @Then /^I should get (\d+) items? of type "(.+)"$/
```

2021-10-21 14:50 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Scenario/Webservice/Endpoints/addresses.feature
> +    And using Webservice with key "ENABLEDENABLEDENABLEDENABLEDENAB" for viewing "addresses" with id 6, I should get following properties:
Where does this hard coded ID come from?

Ideally you should use a reference in the `And I use Webservice with key "ENABLEDENABLEDENABLEDENABLEDENAB" for adding "addresses"` sentence that is saved based on the API returned response

So that you can then reuse this ID via the reference in the following tests

2021-10-21 14:50 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Scenario/Webservice/Endpoints/addresses.feature
> +      | id              | 6              |
Same principle here, the id should be base on a reference (and your endpoint must be able to replace the id column by the appropriate ID saved by reference)

2021-10-21 14:50 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Scenario/Webservice/Endpoints/addresses.feature
> +    And I use Webservice with key "ENABLEDENABLEDENABLEDENABLEDENAB" for removing "addresses" with id 6
Same here, it should be based on a reference

2021-10-26 09:12 UTC, Progi1984 commented on tests/Integration/Behaviour/Features/Scenario/Webservice/Endpoints/addresses.feature
> +      | id              | 6              |
Fixed

2021-10-26 09:12 UTC, Progi1984 commented on tests/Integration/Behaviour/Features/Scenario/Webservice/Endpoints/addresses.feature
> +    And I use Webservice with key "ENABLEDENABLEDENABLEDENABLEDENAB" for removing "addresses" with id 6
Fixed

2021-10-26 09:13 UTC, Progi1984 commented on tests/Integration/Behaviour/Features/Scenario/Webservice/Endpoints/addresses.feature
> +    And using Webservice with key "ENABLEDENABLEDENABLEDENABLEDENAB" for viewing "addresses" with id 6, I should get following properties:
Fixed

2021-10-26 09:14 UTC, Progi1984 commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +     * @Then /^I should get a number of (\d+) items? of type "(.+)"$/
Fixed

2021-10-26 09:14 UTC, Progi1984 commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +     * @Then /^I should get a number of (\d+) errors?$/
Fixed

2021-10-26 09:16 UTC, Progi1984 commented on tests/Integration/Behaviour/Features/Context/Domain/WebserviceKeyFeatureContext.php
> +        $webserviceKey = new WebserviceKey($webserviceKeyId);
Fixed

2021-10-26 09:19 UTC, Progi1984 commented on tests/Integration/Behaviour/Features/Context/Util/StreamWrapperPHP.php
> +class StreamWrapperPHP
Without this stream, we can't write on the php://input stream because it's readyonly

2021-10-26 09:22 UTC, Progi1984 commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +            stream_wrapper_unregister('php');
That permits to reset all data send to php://input mock

I add a comment

2021-10-26 09:27 UTC, Progi1984 commented on tests/Integration/Behaviour/Features/Context/WebserviceEndpointFeatureContext.php
> +        $this->output = $this->requestWebserviceXML($webserviceKey, $method, $endpoint, $postFields);
Fixed

2021-10-26 13:06 UTC, PierreRambaud commented on tests/Integration/Behaviour/Features/Context/Util/StreamWrapperPHP.php
> +        return $this->index >= $this->length ? true : false;
```suggestion
        return $this->index >= $this->length;
```

2021-10-26 13:09 UTC, PierreRambaud submitted a review, later dismissed

2021-10-26 13:18 UTC, PierreRambaud approved these changes

2021-10-27 10:22 UTC, atomiix approved these changes

2021-10-27 13:20 UTC, jolelievre approved these changes
Thank you @Progi1984 all good for me too

Sorry for being such a pain on this 😅. I still think it is now more readable, usable, and stable I hope you share this feeling ^^

2021-10-27 13:20 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/Util/StreamWrapperPHP.php
> +class StreamWrapperPHP
OK, thanks, I didn't know and the comment is perfect now!

2021-10-27 13:20 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Scenario/Webservice/Endpoints/addresses.feature
> +    And I should get an error with code 18 and message "Invalid authentication key format"
I could be picky on this one and suggest using some humans readable strings instead of hard coded int code here
But I've already been enough of a PITA for you on this PR so I will stop here 😅

2021-10-27 13:20 UTC, merged

2021-10-27 13:40 UTC, Progi1984 commented
@KminekMatej :tada: It's a good news :)

2021-10-27 13:57 UTC, KminekMatej commented
@Progi1984 Such a great job! That completely unlocks my PR with API core refactoring. Thanks!

2021-11-02 16:14 UTC, Progi1984 commented
@KminekMatej Thank you for waiting.