Refacto / update FO tests pages for the js-doc
PrestaShop/PrestaShop pull request #24163
Opened 2021-04-22 15:05 UTC by SD1982

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x 
| Description?      | Refacto of the FO tests page for the js-doc
| Type?             | refacto
| Category?         | TE 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | any
| How to test?      | Nothing to test 
| Possible impacts? | any.

2021-04-22 15:55 UTC, matks requested changes, later dismissed
Hi @SD1982 I am sorry you have git conflicts. Can you please rebase?

2021-04-23 06:54 UTC, Progi1984 commented on tests/UI/pages/FO/contactUs/index.js
> +   * @param file
What is the type of `file` ?

2021-04-23 07:00 UTC, Progi1984 reviewed
I think you should remove `String of the`. We knew already that the type is `String`.

2021-04-23 08:39 UTC, SD1982 commented on tests/UI/pages/FO/contactUs/index.js
> +   * @param file
Oh i forgot this one Thanks Progi1984 !

2021-04-23 08:39 UTC, SD1982 commented
> I think you should remove `String of the`. We knew already that the type is `String`.

It's modified now :+1:

2021-04-23 10:35 UTC, boubkerbribri commented on tests/UI/pages/FO/cart/index.js
> +   * @param code {string} The promo code
```suggestion
   * @param code {string} The promo code to apply
```

2021-04-23 10:35 UTC, boubkerbribri commented on tests/UI/pages/FO/checkout/index.js
> +   * @param comment {string} String for the shipping comment
```suggestion
   * @param shippingMethod {number} Position of the shipping method
   * @param comment {string} Comment to add after selecting a shipping method
```

2021-04-23 10:35 UTC, boubkerbribri commented on tests/UI/pages/FO/checkout/index.js
> +   * @param shippingMethod {string} String of the shipping method
```suggestion
   * @param shippingMethod {number} Position of the shipping method
```

2021-04-23 10:35 UTC, boubkerbribri commented on tests/UI/pages/FO/checkout/index.js
> +   * @param customer {object} The customer infos
```suggestion
   * @param customer {object} Customer's information (email and password)
```

2021-04-23 10:35 UTC, boubkerbribri commented on tests/UI/pages/FO/checkout/index.js
> +   * @param address {object} The address infos
```suggestion
   * @param address {object} Address's information to add
```

2021-04-23 10:35 UTC, boubkerbribri commented on tests/UI/pages/FO/checkout/index.js
> +   * @param customerData {object} The customer data
```suggestion
   * @param customerData {object} Guest Customer's information to fill on form
```

2021-04-23 10:35 UTC, boubkerbribri commented on tests/UI/pages/FO/home/index.js
> +   * @param color {string} The color
```suggestion
   * @param page {Page} Browser tab
   * @param id {number} Id of the current product
   * @param color {string} The color to select
```

2021-04-23 10:35 UTC, boubkerbribri commented on tests/UI/pages/FO/home/index.js
> +   * @param socialSharing {string} The social link
```suggestion
   * @param socialSharing {string} The social network name
```

2021-04-23 10:35 UTC, boubkerbribri commented on tests/UI/pages/FO/home/index.js
> +   * @param email {string} The email
```suggestion
   * @param email {string} Email to set on input
```

2021-04-23 10:35 UTC, boubkerbribri commented on tests/UI/pages/FO/login/index.js
> +   * @param customer {object} Object of the customer infos (email, password, ....)
```suggestion
   * @param customer {object} Customer's information (email and password)
```

2021-04-23 10:35 UTC, boubkerbribri commented on tests/UI/pages/FO/myAccount/add.js
> +   * @param customer {object} Object of the customer infos (email, password, ....)
```suggestion
   * @param customer {object} Customer's information (email and password)
```

2021-04-23 10:35 UTC, boubkerbribri commented on tests/UI/pages/FO/myAccount/addAddress.js
> +   * @param addressData {object} Object for the address data (alias, firstname, lastname, company, address, city ...)
```suggestion
   * @param addressData {object} Address's information to fill on form

2021-04-23 10:35 UTC, boubkerbribri commented on tests/UI/pages/FO/myAccount/identity.js
> +   * @param customer {object} Object of the customer infos ( firstname, lastname, email, password)
```suggestion
   * @param customer {object} Customer's information to fill form

2021-04-23 10:35 UTC, boubkerbribri commented on tests/UI/pages/FO/passwordReminder/index.js
> +   * @param email {string} The email
```suggestion
   * @param email {string} Account's email to fill on input

2021-04-23 10:35 UTC, boubkerbribri commented on tests/UI/pages/FO/product/index.js
> +   * @param ulSelector {string} The selector
```suggestion
   * @param ulSelector {string} Selector to locate the element

2021-04-23 10:35 UTC, boubkerbribri commented on tests/UI/pages/FO/product/index.js
> +   * @param combination {object}  The product data
```suggestion
   * @param quantity {number} Quantity of the product that customer wants
   * @param combination {object}  Product's combination data to select
```

2021-04-23 10:35 UTC, boubkerbribri commented on tests/UI/pages/FO/product/index.js
> +   * @param proceedToCheckout {boolean} Boolean for proceed to checkout
```suggestion
   * @param quantity {number} Quantity of the product that customer wants
   * @param combination {object}  Product's combination data to add to cart
   * @param proceedToCheckout {boolean} True to click on proceed to checkout button on modal
```

2021-04-23 10:35 UTC, boubkerbribri commented on tests/UI/pages/FO/product/index.js
> +   * @param socialSharing {string} The social network
```suggestion
   * @param socialSharing {string} Social network's name to get link from
```

2021-04-23 10:35 UTC, boubkerbribri commented on tests/UI/pages/FO/product/index.js
> +   * @param color {string} The color
```suggestion
   * @param color {string} Product's color to check
```

2021-04-23 10:35 UTC, boubkerbribri commented on tests/UI/pages/FO/searchResults/index.js
> +   * @param id {number} Index of product in list of products
```suggestion
   * @param id {number} Index of product on the list
```

2021-04-23 10:35 UTC, boubkerbribri commented on tests/UI/pages/FO/searchResults/index.js
> +   * @param id {number} Product id
```suggestion
   * @param id {number} Index of product on the list
```

2021-04-23 10:35 UTC, boubkerbribri commented on tests/UI/pages/install/index.js
> +   * @param timeout {number} Timeout duration
```suggestion
   * @param timeout {number} Time to wait for step to finish
```

2021-04-26 09:49 UTC, Progi1984 approved these changes

2021-04-26 09:55 UTC, boubkerbribri approved these changes

2021-04-26 09:58 UTC, merged

2021-04-26 09:58 UTC, Progi1984 commented
Thanks @SD1982