Fix comma payment cart page
PrestaShop/PrestaShop pull request #24179
Opened 2021-04-23 11:56 UTC by prestaforum

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Change comma to dot for payment order
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24103
| How to test?      | See #24103
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

2021-04-27 13:32 UTC, sowbiba requested changes

2021-04-27 13:32 UTC, sowbiba commented on src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
> +                            str_replace(',', '.', $data['amount']),
The comma can have different meanings depending in the context
https://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html
replacing it like this is kinda ... rough

2021-04-27 13:32 UTC, sowbiba commented on src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
> +                            str_replace(',', '.', $data['amount']),
Maybe a DataTransformer in the form input which takes the context currency
Must be tried to know if it's possible

2021-04-27 13:50 UTC, sowbiba commented on src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
> +                            str_replace(',', '.', $data['amount']),
A discussion is in progress about this subject. I will let @PrestaShop/product-team give you the fix expected/planned

2021-05-03 10:06 UTC, marionf commented
@MatShir I think this PR should rather be on 1.7.8.x branch wdyt ?

2021-05-10 08:47 UTC, Progi1984 commented
@prestaforum Could you check the PR from @PierreRambaud : #24339 ?

2021-05-10 15:03 UTC, PierreRambaud commented
We will not merge a fix like that, we want to keep the backend safe and easy to maintain.
I'm closing it as we decided to do it only in FO.

2021-05-10 15:03 UTC, closed without merging