Update version to 1.7.9.0
PrestaShop/PrestaShop pull request #24172
Opened 2021-04-22 22:23 UTC by PululuK

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Update version to 1.7.9.0
| Type?             | improvement 
| Category?         | CO 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| How to test?      | ~
| Possible impacts? | ~

2021-04-30 13:53 UTC, matks submitted a review, later dismissed

2021-05-03 09:40 UTC, Progi1984 requested changes
An internal decision is in WIP about the next version

2021-07-21 08:16 UTC, marionf commented
Hello @PululuK 

The next version will be the V8 and it will be a major version. This is why: in an effort of innovation and technological attractiveness, the update of the techno (PHP8 and Symfony 4.4) imposes the passage to the numbering of version in 8.x.x. This is not a breakthrough version unlike passage 1.6 -> 1.7, but a version in the continuity of the work in progress on 1.7. Therefore, there will be no need for a complete overhaul to migrate. The version number changes, but the difficulty of upgrading to 1.7.8 and 8.0.0 will be as easy as upgrading from 1.7.7 to 1.7.8. We also take the opportunity to remove the 1 and respect Semver.

2021-07-21 08:18 UTC, Progi1984 commented on app/AppKernel.php
> +    const VERSION = '1.7.9.0';
```suggestion
    const VERSION = '8.0.0';
```

2021-07-21 08:18 UTC, Progi1984 commented on app/AppKernel.php
>      const MAJOR_VERSION_STRING = '1.7';
```suggestion
    const MAJOR_VERSION_STRING = '8';
```

2021-07-21 08:19 UTC, Progi1984 commented on app/AppKernel.php
>      const MAJOR_VERSION = 17;
```suggestion
    const MAJOR_VERSION = 8;
```

2021-07-21 08:19 UTC, Progi1984 commented on app/AppKernel.php
> +    const MINOR_VERSION = 9;
```suggestion
    const MINOR_VERSION = 0;
```

2021-07-21 08:19 UTC, Progi1984 commented on install-dev/install_version.php
> +define('_PS_INSTALL_VERSION_', '1.7.9.0');
```suggestion
define('_PS_INSTALL_VERSION_', '8.0.0');
```

2021-07-21 08:19 UTC, Progi1984 requested changes
Some feedbacks

2021-08-08 19:39 UTC, Progi1984 submitted a review, later dismissed

2021-08-08 19:40 UTC, Progi1984 commented
@PululuK Thank you for your contribution. Could you rebase your PR because some files are in conflict ?

2021-09-02 16:22 UTC, matks commented
@PululuK friendly reminder 😉

2021-10-01 11:06 UTC, PierreRambaud commented
PR rebased and squashed

2021-10-01 11:06 UTC, Progi1984 submitted a review, later dismissed

2021-10-01 11:21 UTC, jolelievre approved these changes, later dismissed

2021-10-01 12:59 UTC, NeOMakinG submitted a review, later dismissed

2021-10-01 15:04 UTC, PierreRambaud commented
This pr needs https://github.com/PrestaShop/TranslationFiles/pull/20 :)

2021-10-04 15:07 UTC, PierreRambaud commented
This PR also needs a change in the htaccess domain i18n.prestashop.com

2021-11-16 14:38 UTC, PierreRambaud commented
It's in Waiting for dev, the problem comes from the PrestaShop services (i18n.prestashop.com)

2021-11-19 07:35 UTC, PierreRambaud approved these changes

2021-11-19 07:53 UTC, Progi1984 approved these changes

2021-11-19 08:23 UTC, PierreRambaud requested changes
i18n.prestashop is in error now, I'm still on it :sweat_smile:

2021-11-19 14:12 UTC, PierreRambaud approved these changes
Everything is ok now with the server

2021-11-19 14:12 UTC, merged

2021-11-19 14:12 UTC, PierreRambaud commented
Thank you @PululuK