Update order_conf_product_list.tpl on $customization['customization_quantity'] HTML display
PrestaShop/PrestaShop pull request #24181
Opened 2021-04-23 12:35 UTC by caglarutkuguler

Customization text is HTML and is not parsed correctly on the order confirmation emails. 

It is diplayed like below:
<strong>Dimension</strong>:Weight 12.5 kg <br/>

Adding nofilter, the issue is solved and the customization text is parsed correctly.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 1.7.8.x / 1.7.7.x
| Description?      | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?             | bug fix / improvement / new feature / refacto / critical
| Category?         | FO / BO / CO / IN / WS / TE / LO / ME / PM
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| Fixed ticket?     | Fixes #{issue number here}.
| How to test?      | Please indicate how to best verify that this PR is correct.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

2021-04-23 12:43 UTC, PululuK commented
Hi @caglarutkuguler 
Thanks for your contribution !
Can you please follow the discussion here ? https://github.com/PrestaShop/PrestaShop/pull/23263/files

2021-04-30 13:53 UTC, matks requested changes
Hi, I agree with @PululuK : using `nofilter` must be avoided as much as possible

2021-05-12 14:57 UTC, PierreRambaud requested changes
Could you please correctly fill the form inside the PR description?
As @PululuK said, there is already a discussion about it

2021-10-25 09:35 UTC, PierreRambaud commented
Hi @caglarutkuguler ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2021-10-25 09:35 UTC, closed without merging