Allow orders with 0 amount
PrestaShop/PrestaShop pull request #24230
Opened 2021-04-27 10:26 UTC by theodiablo

When we make an order with discount codes, if the amount is 0 right you can't place the order.

We should be able to place it, this is because no payment method is shown when amount is 0, and in the template, the condition isn't correct.

------------------------------------------------------------------------------>

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | If you try to place an order with a discount code which makes the total amount = 0, the `Order with an obligation to pay` button will be disabled. This is a bug which should be fixed.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | No
| How to test?      | Try to place an order with 0 amount using discount codes, before this PR, the `Order with an obligation to pay` button is disabled, after, it should be enabled to allow placing this order.
| Possible impacts? | I don't know any

2021-04-28 09:59 UTC, Progi1984 commented
It seems UI tests are broken.

Ping @boubkerbribri for helping @theodiablo

2021-04-28 10:27 UTC, boubkerbribri commented
> It seems UI tests are broken.
> 
> Ping @boubkerbribri for helping @theodiablo

It seems that something is wrong with the checkout payment step. You can check the error here 
https://github.com/PrestaShop/PrestaShop/suites/2592661972/artifacts/56650013

2021-09-02 16:16 UTC, matks requested changes
Hello @theodiablo 

> I try to place an order with 0 amount using discount codes, before this PR, the `Order with an obligation to pay` button is disabled, after, it should be enabled to allow placing this order.

I just tried on `develop` branch: I was able to successfully order a 34,80€ item for free after using a voucher with 34,80€. So the above bug does not exist, or maybe some more conditions need to be met.

In the bug linked https://github.com/PrestaShop/PrestaShop/issues/9927 there are more conditions for the problem to be observed. But bug https://github.com/PrestaShop/PrestaShop/issues/9927 was solved by PR https://github.com/PrestaShop/PrestaShop/pull/22389

So it seems your PR does not solve the issue you mention and I fail to reproduce the issue you mention

With these items, I think this PR cannot be merged. I close it, feel free to ping me if you wish to continue I can reopen

2021-09-02 16:17 UTC, matks commented
For the record, here is a free order
![Capture d’écran 2021-09-02 à 18 14 00](https://user-images.githubusercontent.com/3830050/131880187-fa0fecf2-efdc-4dd1-ade5-1296be89503f.png)

2021-09-02 16:17 UTC, closed without merging