Fix for $id_lang variable in the Order::getHistory
PrestaShop/PrestaShop pull request #24362
Opened 2021-05-06 06:49 UTC by asf-harlock

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 1.7.8.x / 1.7.7.x
| Description?      | $id_lang was as required param, so I think it could have default value = 0, and then the checks on line 543 will work properly. Also, on line 549, *(int)* should be removed for $id_lang as we could receive a string or an int value.
| Type?             |  improvement
| Category?         | FO / BO / CO / IN / WS / TE / LO / ME / PM
| BC breaks?        | no
| Deprecations?     |  no
| Fixed ticket?     | Seems no
| How to test?      | Just use Order::getHistory method without id_lang as params
| Possible impacts? | Order::getHistory usage :)

2021-05-06 15:24 UTC, matks reviewed
Hello @asf-harlock if I understand you do not modify the behavior of this code, you only refactor it?

2021-05-06 15:48 UTC, asf-harlock commented
Yes, a little bit of refactor, id_lang in join was only as int, but on a couple lines before it could be as a string.

2021-07-16 09:46 UTC, matks requested changes
Hello again @asf-harlock I understand what you do, but I don't think this is the right way.

> $id_lang was as required param, so I think it could have default value = 0, and then the checks on line 543 will work properly. Also, on line 549, (int) should be removed for $id_lang as we could receive a string or an int value.

If $id_lang can be an integer or a string, that is an issue for me. I don't think the code should accept both usecases, [Type Juggling](https://www.php.net/manual/en/language.types.type-juggling.php) has proven source of a lot of bugs over the years.

The changes you submit do not improve the code I think, they rather work around it, but the root cause is that sometimes a bad `$id_lang` is given to `getHistory()`

2021-07-16 11:03 UTC, asf-harlock commented
Hello @matks, 

yes, you have a point here, my code it's a workaround. I can close this pull request, thanks anyway.

2021-07-16 11:03 UTC, closed without merging