Fix for product combination quantity change in rtl panel
PrestaShop/PrestaShop pull request #24473
Opened 2021-05-12 01:42 UTC by samberrry

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | In arabic version of BO (change your BO to arabic language) try to save a product which has combinations. After doing this all combination's quantities will set to "0". The problem is that in arabic numbers are different from english-based numbers. 
| Type?             | bug fix
| Category?         | BO 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #{12777}.
| How to test?      | 
| Possible impacts? | nothing

2021-05-12 06:55 UTC, Progi1984 commented
@samberrry Currently, the issue is not validated. Please validate the issue with @hibatallahAouadni

2021-05-12 14:34 UTC, PierreRambaud requested changes
I'm also not sure it's a regression for 1.7.7.x, could you target the develop branch please?

2021-05-12 14:51 UTC, samberrry commented
@PierreRambaud so, should not it be fixed in `1.7.7.x` version? 
I can create another PR for `develop`.

2021-05-12 15:03 UTC, PierreRambaud commented
> @PierreRambaud so, should not it be fixed in `1.7.7.x` version?
> I can create another PR for `develop`.

We accept only regression on this branch, or it must be defined by the @PrestaShop/product-team, so yes the develop branch must be targetted.

2021-05-18 17:30 UTC, samberrry commented
@PierreRambaud new PR craeted
https://github.com/PrestaShop/PrestaShop/pull/24555

2021-05-19 07:09 UTC, closed without merging