Issue24548
PrestaShop/PrestaShop pull request #24573
Opened 2021-05-19 16:07 UTC by NeOMakinG

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | The layout of the order view page title was broken
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24548.
| How to test?      | Go on order view page and see if the title is rightly aligned
| Possible impacts? | Not much

# Before
![image](https://user-images.githubusercontent.com/14963751/118846363-ec2ad000-b8cc-11eb-9b5a-a4875488e9cc.png)

# After
![image](https://user-images.githubusercontent.com/14963751/118846132-b38af680-b8cc-11eb-8321-dab4692e05f5.png)

2021-05-19 16:51 UTC, kpodemski approved these changes, later dismissed

2021-05-20 07:20 UTC, Progi1984 commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/header.html.twig
> +  <h1 class="d-inline">
@NeOMakinG The indentation is broken. Please fix it.

2021-05-20 07:20 UTC, Progi1984 requested changes
Broken indentation

2021-05-20 09:25 UTC, PierreRambaud commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/header.html.twig
> + <div class="title-content">
```suggestion
<div class="title-content">
```

2021-05-20 09:46 UTC, NeOMakinG commented
> Broken indentation

a.k.a the drunk guy

2021-05-20 09:48 UTC, Progi1984 approved these changes

2021-05-20 10:00 UTC, PierreRambaud approved these changes

2021-05-25 13:20 UTC, SD1982 commented
LGTM thanks @NeOMakinG !!
![image](https://user-images.githubusercontent.com/40635814/119504811-a064a480-bd6c-11eb-92b0-e9732b4d8ea9.png)
![image](https://user-images.githubusercontent.com/40635814/119504848-a6f31c00-bd6c-11eb-9426-a13158e9a158.png)

2021-05-25 13:21 UTC, merged

2021-05-25 13:22 UTC, Progi1984 commented
Thanks @NeOMakinG & @SD1982