Integration test for "category deletion and the impact on associated products"
PrestaShop/PrestaShop pull request #24668
Opened 2021-05-26 16:01 UTC by arouiadib

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      |  Integration test for category deletion and impact on associated products.
| Type?             | refacto 
| Category?         | TE 
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/prestashop-specs/issues/228
| How to test?      | run `php ./vendor/bin/behat -c tests/Integration/Behaviour/behat.yml --name="Delete category"`
| Possible impacts? | None

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/24668)

2021-06-10 12:50 UTC, PululuK commented on src/Adapter/Category/CommandHandler/AbstractDeleteCategoryHandler.php
> +    protected function getProductsWithoutCategory($categoryId)
Products without category or category without products ?
I feel like the name of the function doesn't really match what it does

2021-06-10 12:55 UTC, kpodemski requested changes

2021-06-10 12:55 UTC, kpodemski commented on src/Adapter/Category/CommandHandler/AbstractDeleteCategoryHandler.php
> +    protected function getProductsWithoutCategory($categoryId)
@arouiadib I think you meant `FromCategory`?

2021-06-10 12:55 UTC, kpodemski commented on src/Adapter/Category/CommandHandler/AbstractDeleteCategoryHandler.php
> +                        AND cp.`id_category` = ' . $categoryId . '
```suggestion
                        AND cp.`id_category` = ' . (int) $categoryId . '
```

2021-06-10 12:55 UTC, kpodemski commented on src/Adapter/Category/CommandHandler/AbstractDeleteCategoryHandler.php
> +    protected function getProductsWithoutCategory($categoryId)
```suggestion
    protected function getProductsWithoutCategory(int $categoryId): array
```

make sure to return empty array here if you don't have any results

2021-06-10 12:55 UTC, kpodemski commented on src/Adapter/Category/CommandHandler/AbstractDeleteCategoryHandler.php
> +    protected function getProductsWithoutCategory($categoryId)
I think this query belongs to the `Category.php`, not to handler

2021-06-10 12:55 UTC, kpodemski commented on src/Adapter/Category/CommandHandler/AbstractDeleteCategoryHandler.php
> -			WHERE NOT EXISTS (
And here there was `not exists` 🤔

2021-06-10 13:25 UTC, arouiadib commented on src/Adapter/Category/CommandHandler/AbstractDeleteCategoryHandler.php
> +    protected function getProductsWithoutCategory($categoryId)
Hi @kpodemski , @PululuK 
Thanks for CR, I will take them into account but not in this PR. 
Sorry I made mistake of pushing Fix+Test while the aim of this PR is only testing.
My goal is to provide with some tests that fails and have them green with the fix. I have separate PR for the fix where I will put your remarks.
:heart:

2021-06-12 00:30 UTC, arouiadib commented
@kpodemski @PululuK  Thanks a lot for your first feedback.
The PR now contains only tests and I would love to receive your CR.

The changes you already suggested will be taken into account in another PR (that contains the fix).

2021-11-15 15:00 UTC, PierreRambaud commented
Hi @arouiadib are you still working on it because CI is failing?

2021-11-16 14:01 UTC, closed without merging