Fix delete modal translation
PrestaShop/PrestaShop pull request #24696
Opened 2021-05-28 13:07 UTC by jolelievre

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | The delete wording in product page has been updated in this PR https://github.com/PrestaShop/PrestaShop/pull/21239 but they wording keys also changed in the translation wordings list but they were not updated in the typeahed template so the text was blank
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24142
| How to test?      | See issue (delete customer in specific price and delete pack)
| Possible impacts? | ~

2021-05-28 15:25 UTC, PierreRambaud approved these changes

2021-05-28 15:29 UTC, matks approved these changes

2021-05-28 15:30 UTC, PululuK approved these changes

2021-05-31 08:02 UTC, Julievrz reviewed
Hi, I can't see the domain of this wording in the code. :) It should be Admin.Notifications.Warning

Also, I couldn't find the wording in Crowdin. Is that new?

2021-05-31 08:07 UTC, Progi1984 commented
Ping @jolelievre

2021-05-31 08:16 UTC, jolelievre commented
@Julievrz the wording has been introduced in this PR https://github.com/PrestaShop/PrestaShop/pull/21239 and it indeed uses `Admin.Notifications.Warning`

It is a new wording in 178 (not pushed to crowdin yet), and this PR only updates the key used in javascript to get back the translated wording, that's why you don't see the namespace.

2021-05-31 08:24 UTC, Julievrz commented
> @Julievrz the wording has been introduced in this PR #21239 and it indeed uses `Admin.Notifications.Warning`
> 
> It is a new wording in 178 (not pushed to crowdin yet), and this PR only updates the key used in javascript to get back the translated wording, that's why you don't see the namespace.

Thanks @jolelievre, I knew this wording looked familiar! 😄 Perfect then.

2021-05-31 11:41 UTC, khouloudbelguith commented
Hi @jolelievre,

It is ok :heavy_check_mark: 
I checked:

1. Delete a related product
2. A product feature
3. A product brand
4. A product image
5. A product combination and bulk delete product combinations
6. A customization field
7. A virtual product associated file
8. A product in a pack
9. A specific price and a customer into specific price

Thanks!

2021-05-31 12:06 UTC, Progi1984 requested changes
WAIT FOR 1780 BETA RELEASE

2021-05-31 13:11 UTC, Progi1984 approved these changes

2021-06-01 09:41 UTC, merged

2021-06-01 09:41 UTC, PierreRambaud commented
Thank you @jolelievre