Correction for issues #24692
PrestaShop/PrestaShop pull request #24770
Opened 2021-06-02 14:57 UTC by olecorre

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x 
| Description?      | Need CurrencyCode for BYN
| Type?             | bug fix 
| Category?         | BO 
| BC breaks?        | no
| Deprecations?     | no 
| Fixed ticket?     | Fixes #24692
| How to test?      | Go to Localization -> currency and choose BYN
| Possible impacts? | Empty cache after update the file

2021-06-02 15:00 UTC, Progi1984 approved these changes

2021-06-02 15:05 UTC, PululuK approved these changes

2021-06-02 15:41 UTC, matks approved these changes

2021-06-03 08:13 UTC, PierreRambaud approved these changes

2021-06-04 07:39 UTC, Progi1984 requested changes
## Waiting for 1775 RELEASE

2021-06-14 10:13 UTC, Progi1984 approved these changes

2021-06-14 10:15 UTC, merged

2021-06-14 10:15 UTC, Progi1984 commented
Thanks @olecorre & @sarahdib