Fix missing product indexation after creation on product page V2
PrestaShop/PrestaShop pull request #24774
Opened 2021-06-02 16:14 UTC by matthieu-rolland

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Fix product not indexed after creation on product page V2 
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24460
| How to test?      | See steps described in issue #24460
| Possible impacts? |

2021-06-02 16:31 UTC, matks reviewed
Code seems OK but it would be amazing to have a test to verify indexation is correct after your changes

2021-06-03 07:57 UTC, PierreRambaud commented on src/Adapter/Product/Update/ProductIndexationUpdater.php
> +                    'An error occured while trying to update indexation data for product %s.',
```suggestion
                    'An error occured while trying to update indexation data for product %d.',
```

2021-06-03 07:59 UTC, PierreRambaud requested changes
I agree with @matks Could you please add tests? :heart:

2021-06-03 08:14 UTC, Progi1984 commented on src/Adapter/Product/CommandHandler/UpdateProductOptionsHandler.php
>       * @param ManufacturerRepository $manufacturerRepository
Please update phpdoc

2021-06-03 08:15 UTC, Progi1984 commented on src/Adapter/Product/Update/ProductIndexationUpdater.php
> +use PrestaShop\PrestaShop\Adapter\CoreException;
```suggestion
use PrestaShop\PrestaShop\Adapter\CoreException;
use PrestaShopException;
```

2021-06-03 08:17 UTC, Progi1984 reviewed
Some feedbacks & Could you add a behat test, please ?

2021-06-08 07:27 UTC, Progi1984 commented on src/Adapter/Product/Update/ProductIndexationUpdater.php
> +use PrestaShopException
```suggestion
use PrestaShopException;
```

2021-06-08 07:29 UTC, Progi1984 reviewed
A last bug and it's ok for me

2021-06-08 07:59 UTC, Progi1984 submitted a review, later dismissed

2021-06-08 13:58 UTC, PierreRambaud submitted a review, later dismissed

2021-06-10 12:19 UTC, khouloudbelguith commented
Hi @matthieu-rolland,

In the BO > Shop Parameters > Search page, we have an option  **Indexing** to enable or disable the indexing.
By default is enabled.
So I have an issue when we disable it following these steps:

1. BO > Shop Parameters > Search page
2. Disable Indexing and save 
![image](https://user-images.githubusercontent.com/16067358/121522883-df922700-c9f5-11eb-9eb4-e6fd3e375096.png)
3. Go to Advanced Parameters > Experimental features
4. Enable Experimental Product Page
5. Go to Catalog > Products, click on "New product on experimental page"
6. Fill all needed fields, save the product
7. Go to FO, search for the product: The product is well displayed in the search

https://drive.google.com/file/d/1rQyGTaIfj3HDQ9aYgBo5ieD4ya2VkH2V/view?usp=sharing

It shouldn't because the indexing feature is disabled

Thank you!

2021-06-17 14:46 UTC, matks approved these changes

2021-06-17 15:46 UTC, PierreRambaud approved these changes

2021-06-18 08:24 UTC, PierreRambaud approved these changes

2021-06-18 11:32 UTC, khouloudbelguith commented
Hi @matthieu-rolland,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1FYS_XQ7Qut-44hJ_zjX1S79GlEYvgzKm/view?usp=sharing

Thank you!

2021-06-18 12:09 UTC, merged

2021-06-18 12:10 UTC, Progi1984 commented
Thanks @matthieu-rolland & @khouloudbelguith