Fix pages name for link list module
PrestaShop/PrestaShop pull request #24783
Opened 2021-06-03 08:26 UTC by boubkerbribri

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Fix pages name for link list module
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | no tests needed
| Possible impacts? | none

2021-06-03 08:37 UTC, Progi1984 approved these changes

2021-06-03 10:08 UTC, atomiix approved these changes

2021-06-03 12:30 UTC, NeOMakinG approved these changes

2021-06-03 13:12 UTC, Progi1984 requested changes
## WAIT FOR 1775 RELEASE

2021-06-14 10:13 UTC, Progi1984 approved these changes

2021-06-14 10:13 UTC, merged

2021-06-14 10:14 UTC, Progi1984 commented
Thanks @boubkerbribri