Cache getProducts with parameters
PrestaShop/PrestaShop pull request #24825
Opened 2021-06-04 19:41 UTC by kpodemski

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Cache for `Cart::getProducts` wasn't precise, at all, I decided to cache it similar to `Product::getProductProperties`
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #22425.
| How to test?      | I believe we should see E2E tests failing if something would be wrong
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

2021-06-04 20:23 UTC, matks commented
@kpodemski some Behat tests fail
```
022 Scenario: I create a cart with a specific price, it should be present when order is created and stays present even if product price is modified # Features/Scenario/Order/order_specific_prices.feature:614
      And product "Mug The best is yet to come" in order "bo_order1" has following details:                                                         # Features/Scenario/Order/order_specific_prices.feature:627
        Invalid product detail field product_price for product Mug The best is yet to come, expected 15.00 instead of 11.9
        Failed asserting that 11.9 matches expected 15.0.
```
 
Behat tests perform each step of the scenario using objects in memory. This is different from regular web usage as, between each HTTP request, everything (including the cache you improved) is flushed.

You probably need to add some cache clear statements inside Behat tests to make sure data being tested is fresh and not cached. Or maybe the tests indicate one operation that needs to refresh the cached data but it's not 😉 (then the tests indicate an issue in the code)

2021-06-05 11:28 UTC, kpodemski commented
@matks tests saved me 😅 what's funny I ran tests locally but if I won't run `composer create-test-db` before each specific context run, results are different 🤔

2021-06-07 07:12 UTC, Progi1984 commented on classes/Cart.php
> +    protected static $cacheProducts = [];
```suggestion
    /**
     * @var array
     */
    protected static $cacheProducts = [];
```

2021-06-07 08:29 UTC, matthieu-rolland approved these changes

2021-06-07 08:37 UTC, Progi1984 commented
@kpodemski Sorry... But I'm not approving this PR. Why ? No tests, and you add cache in a legacy page with static variables...

2021-06-07 08:50 UTC, kpodemski commented
> @kpodemski Sorry... But I'm not approving this PR. Why ? No tests and you add cache in a legacy page with static variables...

Actually, in this PR, behat tests showed us an issue with code, there's plenty of tests related to Cart with `getProducts`, but I guess you'd like to see unit ones? with few queries to `getProducts` and a comparison to a predefined array? is that would be enough?

2021-06-07 09:30 UTC, PierreRambaud requested changes
I'm not sure adding static cache is a good idea :thinking: 
The object model aims to retrieve data as it is. Tu class using the object model, has to perform cache if needed.
What if a module use this method, then another one did something and call this method again :thinking:

2021-06-07 09:41 UTC, kpodemski commented
@PierreRambaud 

> What if a module use this method, then another one did something and call this method again 🤔

question is what exactly module is doing, in most common scenarios cache would be invalidated

what about having:

`$cart->_products`

and 

`$cart->_products_full_info`

would that be a better idea?

we need to cache `Cart::getProducts` somehow, it's basic optimization, this method is called many times to work with products from cart, the issue is that provided parameters are not respected

do we have any better ideas or we left this bug because there's no "safe" way of fixing it?

> The object model aims to retrieve data as it is.

well, not in legacy, due to many calls to static methods like `Product::getProductProperties` etc. PrestaShop is using static cache all over the core

2021-06-29 12:41 UTC, matks commented
Hello @kpodemski I'm sorry we are quite afraid of validating this PR 😅 

- static cache is a strategy that has been coming back to bite us many time
- here you replace one static cache that we don't really know exactly how many consequences it has by another static cache that we also are not sure of all the impacts
- we modify a key Class which is the cart

When analyzing this PR I feel like [trying to modify the very top card of a big house of cards](https://c8.alamy.com/comp/MMWYAK/a-man-placing-the-last-cards-on-a-house-of-cards-a-metaphor-for-a-complicated-plan-that-can-easily-go-wrong-MMWYAK.jpg) and I don't like this feeling 😅  .

Unfortunately, we know we're afraid of this change, but we have no alternative to suggest 😞  .

2021-06-29 12:48 UTC, kpodemski commented
@matks yeah I think we can live with this small problem related to `Cart::getProducts()`, entire code in this class needs to be re-worked anyway because it doesn't perform well with more carts and more products inside one cart 👍

2021-06-29 12:48 UTC, closed without merging