Update country.xml
PrestaShop/PrestaShop pull request #24866
Opened 2021-06-08 12:41 UTC by juraj1000

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 1.7.8.x / 1.7.7.x
| Description?      | Incorrect zone for the country GB defined as EU country
| Type?             | bug fix
| Category?         | LO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24842
| How to test?      | Install the new Prestashop > BO > Improve > International > Locations > Countries > fill ISO code = GB > check if Zone = Europe (non-EU)
| Possible impacts? | installation data

2021-06-08 13:49 UTC, PierreRambaud submitted a review, later dismissed

2021-06-08 13:55 UTC, PululuK submitted a review, later dismissed

2021-06-09 09:13 UTC, Robin-Fischer-PS commented
Hi !

Before testing and merging this PR, we need to investigate the possible impacts of switching the UK out of EU (ping @Julievrz ) !

Thanks :)

2021-06-10 10:06 UTC, Julievrz commented
I had a look at the BO and couldn't see any other places where the zone is specified. Otherwise, I agree that the UK's zone should be changed to "Europe (non-EU)" as it is no longer part of the EU anymore.

2021-06-10 10:14 UTC, Julievrz commented
However, I don't think this PR should be added to a patch version because it contains new wording.

2021-06-14 08:05 UTC, Robin-Fischer-PS commented
Hello @juraj1000 !

With your PR, UK is now in Europe (non-EU) zone.
Installation with UK selected (and not selected) works fine.

![pr24866 united kingdom UE](https://user-images.githubusercontent.com/55688534/121859447-00a98f00-ccf8-11eb-8760-3308672bee82.png)


So it's QA :heavy_check_mark: !

Thanks :)

2021-06-14 08:07 UTC, Progi1984 requested changes
Please target the `develop` branch ?

It's not the regression.

2021-06-14 12:33 UTC, Progi1984 submitted a review, later dismissed

2021-06-14 13:36 UTC, PierreRambaud commented
> Please target the `develop` branch ?
> 
> It's not the regression.

I'm afraid it's something we **must** merge on the 1.7.8.x branch.
ping @PrestaShop/product-team @marionf

2021-06-14 14:15 UTC, marionf commented
Yes, let's merge it for 1.7.8

2021-06-14 14:16 UTC, Progi1984 commented
Sorry @juraj1000. Could you rebase it in `1.7.8.x` branch ?

2021-06-14 16:05 UTC, matks approved these changes

2021-06-14 16:06 UTC, matks commented
@PrestaShop/qa-team the base branch has been changed (`develop` to `1.7.8.x`)

Do you want to test one more time or we can go forward?

2021-06-14 17:02 UTC, Robin-Fischer-PS commented
@matks No it's OK, I tested on 1.7.8.x (it was later changed to develop, then again changed to 1.7.8.x )

So it can be merged :)

2021-06-14 19:47 UTC, merged

2021-06-14 19:47 UTC, matks commented
Thank you @juraj1000