Add hooks 178
PrestaShop/PrestaShop pull request #24885
Opened 2021-06-09 09:45 UTC by matks

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Register new hooks for 1.7.8.0. This PR continues the work started in https://github.com/PrestaShop/PrestaShop/pull/24542 and submits all hooks (Grid, Settings form, CRUD form) for 1.7.8.0
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| How to test?      | No need to test, as agreed with QA in https://github.com/PrestaShop/PrestaShop/pull/24542
| Possible impacts? | ~

2021-06-09 09:50 UTC, Progi1984 commented on install-dev/data/xml/hook.xml
> +      </description>
```suggestion
      <description>This hook displays content in the middle of the window that appears after adding product to cart</description>
```

2021-06-09 09:51 UTC, Progi1984 commented on install-dev/data/xml/hook.xml
> +      </description>
```suggestion
      <description>This hook displays content in the bottom of window that appears after adding product to cart</description>
```

2021-06-09 09:51 UTC, Progi1984 commented on install-dev/data/xml/hook.xml
> +      </description>
```suggestion
      <description>This hook adds additional elements in the head section of your pages (head section of html)</description>
```

2021-06-09 09:51 UTC, Progi1984 commented on install-dev/data/xml/hook.xml
> +      </description>
```suggestion
      <description>This hook is displayed when a product is added to the cart or if the cart's content is modified</description>
```

2021-06-09 09:52 UTC, Progi1984 commented on install-dev/data/xml/hook.xml
> +      </description>
```suggestion
      <description>This hook launches modules when the AdminOrder tab is displayed in the Back Office and extends / override Order panel tabs</description>
```

2021-06-09 09:52 UTC, Progi1984 commented on install-dev/data/xml/hook.xml
> +      </description>
```suggestion
      <description>This hook launches modules when the AdminOrder tab is displayed in the Back Office and extends / override Shipping panel tabs</description>
```

2021-06-09 09:52 UTC, Progi1984 commented on install-dev/data/xml/hook.xml
> +      </description>
```suggestion
      <description>This hook launches modules when the AdminOrder tab is displayed in the Back Office and extends /override Order panel content</description>
```

2021-06-09 09:52 UTC, Progi1984 commented on install-dev/data/xml/hook.xml
> +      </description>
```suggestion
      <description>This hook launches modules when the AdminOrder tab is displayed in the Back Office and extends /override Shipping panel content</description>
```

2021-06-09 09:54 UTC, Progi1984 requested changes
Could your remove break lines in description tag ? It's not in the scope of the PR.

2021-06-09 09:55 UTC, matks commented
> Could your remove break lines in description tag ? It's not in the scope of the PR.

I was doing it right now. This is why I marked the PR with a WIP in the title.

2021-06-09 09:57 UTC, matks commented
Files have been cleaned, de-duplicated, reformatted and polished ; PR is no more in WIP

2021-06-09 09:58 UTC, Progi1984 approved these changes

2021-06-09 10:11 UTC, PululuK commented on install-dev/upgrade/sql/1.7.8.0.sql
> +  (NULL,'actionAfterCreateZoneFormHandler','Modify zone identifiable object data after creating it','This hook allows to modify zone identifiable object forms data after it was created','1')
```suggestion
  (NULL, 'actionAfterCreateProductFormHandler', 'Modify product identifiable object data after creating it', 'This hook allows to modify product identifiable object form data after it was created', '1'),
  (NULL, 'actionCustomerAddressGridDefinitionModifier', 'Modify customer address grid definition','This hook allows to alter customer address grid columns, actions and filters', '1'),
  (NULL, 'actionCartRuleGridDefinitionModifier', 'Modify cart rule grid definition','This hook allows to alter cart rule grid columns, actions and filters', '1'),
  (NULL, 'actionOrderStatesGridDefinitionModifier', 'Modify order states grid definition','This hook allows to alter order states grid columns, actions and filters', '1'),
  (NULL, 'actionOrderReturnStatesGridDefinitionModifier', 'Modify order return states grid definition','This hook allows to alter order return states grid columns, actions and filters', '1'),
  (NULL, 'actionOutstandingGridDefinitionModifier', 'Modify outstanding grid definition','This hook allows to alter outstanding grid columns, actions and filters', '1'),
  (NULL, 'actionCarrierGridDefinitionModifier', 'Modify carrier grid definition','This hook allows to alter carrier grid columns, actions and filters', '1'),
  (NULL, 'actionZoneGridDefinitionModifier', 'Modify zone grid definition','This hook allows to alter zone grid columns, actions and filters', '1'),
  (NULL, 'actionCustomerDiscountGridQueryBuilderModifier', 'Modify customer discount grid query builder','This hook allows to alter Doctrine query builder for customer discount grid', '1'),
  (NULL, 'actionCustomerAddressGridQueryBuilderModifier', 'Modify customer address grid query builder','This hook allows to alter Doctrine query builder for customer address grid', '1'),
  (NULL, 'actionCartRuleGridQueryBuilderModifier', 'Modify cart rule grid query builder','This hook allows to alter Doctrine query builder for cart rule grid', '1'),
  (NULL, 'actionOrderStatesGridQueryBuilderModifier', 'Modify order states grid query builder','This hook allows to alter Doctrine query builder for order states grid', '1'),
  (NULL, 'actionOrderReturnStatesGridQueryBuilderModifier', 'Modify order return states grid query builder','This hook allows to alter Doctrine query builder for order return states grid', '1'),
  (NULL, 'actionOutstandingGridQueryBuilderModifier', 'Modify outstanding grid query builder','This hook allows to alter Doctrine query builder for outstanding grid', '1'),
  (NULL, 'actionCarrierGridQueryBuilderModifier', 'Modify carrier grid query builder','This hook allows to alter Doctrine query builder for carrier grid', '1'),
  (NULL, 'actionZoneGridQueryBuilderModifier', 'Modify zone grid query builder','This hook allows to alter Doctrine query builder for zone grid', '1'),
  (NULL, 'actionCustomerDiscountGridDataModifier', 'Modify customer discount grid data','This hook allows to modify customer discount grid data', '1'),
  (NULL, 'actionCustomerAddressGridDataModifier', 'Modify customer address grid data','This hook allows to modify customer address grid data', '1'),
  (NULL, 'actionCartRuleGridDataModifier', 'Modify cart rule grid data','This hook allows to modify cart rule grid data', '1'),
  (NULL, 'actionOrderStatesGridDataModifier', 'Modify order states grid data','This hook allows to modify order states grid data', '1'),
  (NULL, 'actionOrderReturnStatesGridDataModifier', 'Modify order return states grid data','This hook allows to modify order return states grid data', '1'),
  (NULL, 'actionOutstandingGridDataModifier', 'Modify outstanding grid data','This hook allows to modify outstanding grid data', '1'),
  (NULL, 'actionCarrierGridDataModifier', 'Modify carrier grid data','This hook allows to modify carrier grid data', '1'),
  (NULL, 'actionZoneGridDataModifier', 'Modify zone grid data','This hook allows to modify zone grid data', '1'),
  (NULL, 'actionCustomerDiscountGridFilterFormModifier', 'Modify customer discount grid filters','This hook allows to modify filters for customer discount grid', '1'),
  (NULL, 'actionCustomerAddressGridFilterFormModifier', 'Modify customer address grid filters','This hook allows to modify filters for customer address grid', '1'),
  (NULL, 'actionCartRuleGridFilterFormModifier', 'Modify cart rule grid filters','This hook allows to modify filters for cart rule grid', '1'),
  (NULL, 'actionOrderStatesGridFilterFormModifier', 'Modify order states grid filters','This hook allows to modify filters for order states grid', '1'),
  (NULL, 'actionOrderReturnStatesGridFilterFormModifier', 'Modify order return states grid filters','This hook allows to modify filters for order return states grid', '1'),
  (NULL, 'actionOutstandingGridFilterFormModifier', 'Modify outstanding grid filters','This hook allows to modify filters for outstanding grid', '1'),
  (NULL, 'actionCarrierGridFilterFormModifier', 'Modify carrier grid filters','This hook allows to modify filters for carrier grid', '1'),
  (NULL, 'actionZoneGridFilterFormModifier', 'Modify zone grid filters','This hook allows to modify filters for zone grid', '1'),
  (NULL, 'actionCustomerDiscountGridPresenterModifier', 'Modify customer discount grid template data','This hook allows to modify data which is about to be used in template for customer discount grid', '1'),
  (NULL, 'actionCustomerAddressGridPresenterModifier', 'Modify customer address grid template data','This hook allows to modify data which is about to be used in template for customer address grid', '1'),
  (NULL, 'actionCartRuleGridPresenterModifier', 'Modify cart rule grid template data','This hook allows to modify data which is about to be used in template for cart rule grid', '1'),
  (NULL, 'actionOrderStatesGridPresenterModifier', 'Modify order states grid template data','This hook allows to modify data which is about to be used in template for order states grid', '1'),
  (NULL, 'actionOrderReturnStatesGridPresenterModifier', 'Modify order return states grid template data','This hook allows to modify data which is about to be used in template for order return states grid', '1'),
  (NULL, 'actionOutstandingGridPresenterModifier', 'Modify outstanding grid template data','This hook allows to modify data which is about to be used in template for outstanding grid', '1'),
  (NULL, 'actionCarrierGridPresenterModifier', 'Modify carrier grid template data','This hook allows to modify data which is about to be used in template for carrier grid', '1'),
  (NULL, 'actionZoneGridPresenterModifier', 'Modify zone grid template data','This hook allows to modify data which is about to be used in template for zone grid', '1'),
  (NULL, 'actionCustomerDiscountGridDefinitionModifier', 'Modify customer discount grid definition','This hook allows to alter customer discount grid columns, actions and filters', '1'),
  (NULL, 'actionPerformancePageSmartyForm', 'Modify performance page smarty options form content','This hook allows to modify performance page smarty options form FormBuilder', '1'),
  (NULL, 'actionPerformancePageDebugModeForm', 'Modify performance page debug mode options form content','This hook allows to modify performance page debug mode options form FormBuilder', '1'),
  (NULL, 'actionPerformancePageOptionalFeaturesForm', 'Modify performance page optional features options form content','This hook allows to modify performance page optional features options form FormBuilder', '1'),
  (NULL, 'actionPerformancePageCombineCompressCacheForm', 'Modify performance page combine compress cache options form content','This hook allows to modify performance page combine compress cache options form FormBuilder', '1'),
  (NULL, 'actionPerformancePageMediaServersForm', 'Modify performance page media servers options form content','This hook allows to modify performance page media servers options form FormBuilder', '1'),
  (NULL, 'actionPerformancePagecachingForm', 'Modify performance pagecaching options form content','This hook allows to mod [...]

2021-06-09 10:11 UTC, PululuK commented on install-dev/upgrade/sql/1.7.8.0.sql
> +  (NULL,'actionAfterCreateZoneFormHandler','Modify zone identifiable object data after creating it','This hook allows to modify zone identifiable object forms data after it was created','1')
```suggestion
  (NULL, 'actionAfterCreateProductFormHandler', 'Modify product identifiable object data after creating it', 'This hook allows to modify product identifiable object form data after it was created', '1'),
  (NULL, 'actionCustomerAddressGridDefinitionModifier', 'Modify customer address grid definition','This hook allows to alter customer address grid columns, actions and filters', '1'),
  (NULL, 'actionCartRuleGridDefinitionModifier', 'Modify cart rule grid definition','This hook allows to alter cart rule grid columns, actions and filters', '1'),
  (NULL, 'actionOrderStatesGridDefinitionModifier', 'Modify order states grid definition','This hook allows to alter order states grid columns, actions and filters', '1'),
  (NULL, 'actionOrderReturnStatesGridDefinitionModifier', 'Modify order return states grid definition','This hook allows to alter order return states grid columns, actions and filters', '1'),
  (NULL, 'actionOutstandingGridDefinitionModifier', 'Modify outstanding grid definition','This hook allows to alter outstanding grid columns, actions and filters', '1'),
  (NULL, 'actionCarrierGridDefinitionModifier', 'Modify carrier grid definition','This hook allows to alter carrier grid columns, actions and filters', '1'),
  (NULL, 'actionZoneGridDefinitionModifier', 'Modify zone grid definition','This hook allows to alter zone grid columns, actions and filters', '1'),
  (NULL, 'actionCustomerDiscountGridQueryBuilderModifier', 'Modify customer discount grid query builder','This hook allows to alter Doctrine query builder for customer discount grid', '1'),
  (NULL, 'actionCustomerAddressGridQueryBuilderModifier', 'Modify customer address grid query builder','This hook allows to alter Doctrine query builder for customer address grid', '1'),
  (NULL, 'actionCartRuleGridQueryBuilderModifier', 'Modify cart rule grid query builder','This hook allows to alter Doctrine query builder for cart rule grid', '1'),
  (NULL, 'actionOrderStatesGridQueryBuilderModifier', 'Modify order states grid query builder','This hook allows to alter Doctrine query builder for order states grid', '1'),
  (NULL, 'actionOrderReturnStatesGridQueryBuilderModifier', 'Modify order return states grid query builder','This hook allows to alter Doctrine query builder for order return states grid', '1'),
  (NULL, 'actionOutstandingGridQueryBuilderModifier', 'Modify outstanding grid query builder','This hook allows to alter Doctrine query builder for outstanding grid', '1'),
  (NULL, 'actionCarrierGridQueryBuilderModifier', 'Modify carrier grid query builder','This hook allows to alter Doctrine query builder for carrier grid', '1'),
  (NULL, 'actionZoneGridQueryBuilderModifier', 'Modify zone grid query builder','This hook allows to alter Doctrine query builder for zone grid', '1'),
  (NULL, 'actionCustomerDiscountGridDataModifier', 'Modify customer discount grid data','This hook allows to modify customer discount grid data', '1'),
  (NULL, 'actionCustomerAddressGridDataModifier', 'Modify customer address grid data','This hook allows to modify customer address grid data', '1'),
  (NULL, 'actionCartRuleGridDataModifier', 'Modify cart rule grid data','This hook allows to modify cart rule grid data', '1'),
  (NULL, 'actionOrderStatesGridDataModifier', 'Modify order states grid data','This hook allows to modify order states grid data', '1'),
  (NULL, 'actionOrderReturnStatesGridDataModifier', 'Modify order return states grid data','This hook allows to modify order return states grid data', '1'),
  (NULL, 'actionOutstandingGridDataModifier', 'Modify outstanding grid data','This hook allows to modify outstanding grid data', '1'),
  (NULL, 'actionCarrierGridDataModifier', 'Modify carrier grid data','This hook allows to modify carrier grid data', '1'),
  (NULL, 'actionZoneGridDataModifier', 'Modify zone grid data','This hook allows to modify zone grid data', '1'),
  (NULL, 'actionCustomerDiscountGridFilterFormModifier', 'Modify customer discount grid filters','This hook allows to modify filters for customer discount grid', '1'),
  (NULL, 'actionCustomerAddressGridFilterFormModifier', 'Modify customer address grid filters','This hook allows to modify filters for customer address grid', '1'),
  (NULL, 'actionCartRuleGridFilterFormModifier', 'Modify cart rule grid filters','This hook allows to modify filters for cart rule grid', '1'),
  (NULL, 'actionOrderStatesGridFilterFormModifier', 'Modify order states grid filters','This hook allows to modify filters for order states grid', '1'),
  (NULL, 'actionOrderReturnStatesGridFilterFormModifier', 'Modify order return states grid filters','This hook allows to modify filters for order return states grid', '1'),
  (NULL, 'actionOutstandingGridFilterFormModifier', 'Modify outstanding grid filters','This hook allows to modify filters for outstanding grid', '1'),
  (NULL, 'actionCarrierGridFilterFormModifier', 'Modify carrier grid filters','This hook allows to modify filters for carrier grid', '1'),
  (NULL, 'actionZoneGridFilterFormModifier', 'Modify zone grid filters','This hook allows to modify filters for zone grid', '1'),
  (NULL, 'actionCustomerDiscountGridPresenterModifier', 'Modify customer discount grid template data','This hook allows to modify data which is about to be used in template for customer discount grid', '1'),
  (NULL, 'actionCustomerAddressGridPresenterModifier', 'Modify customer address grid template data','This hook allows to modify data which is about to be used in template for customer address grid', '1'),
  (NULL, 'actionCartRuleGridPresenterModifier', 'Modify cart rule grid template data','This hook allows to modify data which is about to be used in template for cart rule grid', '1'),
  (NULL, 'actionOrderStatesGridPresenterModifier', 'Modify order states grid template data','This hook allows to modify data which is about to be used in template for order states grid', '1'),
  (NULL, 'actionOrderReturnStatesGridPresenterModifier', 'Modify order return states grid template data','This hook allows to modify data which is about to be used in template for order return states grid', '1'),
  (NULL, 'actionOutstandingGridPresenterModifier', 'Modify outstanding grid template data','This hook allows to modify data which is about to be used in template for outstanding grid', '1'),
  (NULL, 'actionCarrierGridPresenterModifier', 'Modify carrier grid template data','This hook allows to modify data which is about to be used in template for carrier grid', '1'),
  (NULL, 'actionZoneGridPresenterModifier', 'Modify zone grid template data','This hook allows to modify data which is about to be used in template for zone grid', '1'),
  (NULL, 'actionCustomerDiscountGridDefinitionModifier', 'Modify customer discount grid definition','This hook allows to alter customer discount grid columns, actions and filters', '1'),
  (NULL, 'actionPerformancePageSmartyForm', 'Modify performance page smarty options form content','This hook allows to modify performance page smarty options form FormBuilder', '1'),
  (NULL, 'actionPerformancePageDebugModeForm', 'Modify performance page debug mode options form content','This hook allows to modify performance page debug mode options form FormBuilder', '1'),
  (NULL, 'actionPerformancePageOptionalFeaturesForm', 'Modify performance page optional features options form content','This hook allows to modify performance page optional features options form FormBuilder', '1'),
  (NULL, 'actionPerformancePageCombineCompressCacheForm', 'Modify performance page combine compress cache options form content','This hook allows to modify performance page combine compress cache options form FormBuilder', '1'),
  (NULL, 'actionPerformancePageMediaServersForm', 'Modify performance page media servers options form content','This hook allows to modify performance page media servers options form FormBuilder', '1'),
  (NULL, 'actionPerformancePagecachingForm', 'Modify performance pagecaching options form content','This hook allows to mod [...]

2021-06-09 12:26 UTC, matks commented
Hi @PululuK what is the benefit of those blank spaces?

2021-06-10 07:26 UTC, matks commented
Closing and reopening to relauch CI

2021-06-10 08:57 UTC, matthieu-rolland approved these changes

2021-06-10 08:59 UTC, matthieu-rolland commented
(sorry @PululuK I "resolved" your code suggestion because it made the page very hard to scroll 😅 )

2021-06-10 09:01 UTC, merged

2021-06-10 09:02 UTC, matthieu-rolland commented
thank you @matks