Fixed default value for Currency after upgrade
PrestaShop/PrestaShop pull request #24908
Opened 2021-06-10 13:53 UTC by Progi1984

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Fixed default value for Currency after upgrade<br>From 1744, the upgrade in `1.7.6.0.sql` add a field `numeric_iso_code` not nullable (`ADD "numeric_iso_code" varchar(3) NOT NULL DEFAULT '0'`). But in `1.7.7.0`, the field became nullable (#14972 - Thanks @jolelievre :tada:) but without upgrade script.
| Type?             | bug fix
| Category?         | IN
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24871
| How to test?      | Cf. #24871

2021-06-10 14:22 UTC, PierreRambaud approved these changes, later dismissed

2021-06-11 12:35 UTC, matthieu-rolland submitted a review, later dismissed

2021-06-11 14:13 UTC, matks approved these changes, later dismissed
Nice catch

2021-06-16 13:21 UTC, atomiix commented
@Progi1984 maybe target 1.7.7.x branch?

2021-06-16 13:37 UTC, jolelievre requested changes
Oh thanks for the fix, my bad I didn't think of this one!!

But I agree with @atomiix that it should target 177x

2021-06-16 14:12 UTC, jolelievre approved these changes

2021-06-16 14:14 UTC, atomiix approved these changes

2021-06-16 14:16 UTC, jolelievre approved these changes

2021-06-16 14:16 UTC, matthieu-rolland approved these changes

2021-06-16 15:55 UTC, khouloudbelguith commented
Hi @Progi1984,

It is ok :heavy_check_mark: 
Upgrade from PS1724 to PS1776 => ok
Upgrade from PS16124 to PS1776 => ok
Upgrade from PS1744 to PS1776 => ok

I checked after upgrade:
- Create an official currency
- Create an unofficial currency
- Create an order with the unofficial currency and generate an invoice
- Update unofficial currency
- Delete the unofficial currency

https://drive.google.com/file/d/19yLLhNnsxLTX6azQwGyfhbkbJKm5Fb_j/view?usp=sharing

Thanks!

2021-06-16 15:55 UTC, merged

2021-06-16 15:56 UTC, atomiix commented
Thanks @Progi1984  & @khouloudbelguith !