Shop and shop group have now a color property.
PrestaShop/PrestaShop pull request #24948
Opened 2021-06-14 08:33 UTC by lmeyer1

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Fixes an issue in the sql upgrade script for 1.7.8.0 beta.1. Adds missing columns `color` on table shop and shop_group.
| Type?             | bug fix
| Category?         | IN
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24891.
| How to test?      | Run the upgrade script `1.7.8.0.sql` manually.
| Possible impacts? | A step closer to a working upgrade.

2021-06-14 08:35 UTC, Progi1984 approved these changes

2021-06-14 12:10 UTC, PierreRambaud requested changes
This part is managed by https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Entity/ShopGroup.php and it's automatically updated during the upgrade process.
ping @matthieu-rolland

2021-06-14 14:37 UTC, lmeyer1 commented
@PierreRambaud
>This part is managed by https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Entity/ShopGroup.php and it's automatically updated during the upgrade process.

OK, I wait for the next release, hoping manual update will work in beta.2 (see #24886) 😉.

2021-06-15 07:42 UTC, matthieu-rolland reviewed
these new fields are configured in doctrine entities `Shop` and `ShopGroup`, we shouldn't have to add them manually

2021-06-15 07:47 UTC, matthieu-rolland commented
I see you are updating your DB manually, not the upgrade module...  then for the doctrine part you can do:

`php bin/console doctrine:schema:update --dump-sql` to have a glance at what will be added

and `php bin/console doctrine:schema:update --force` to apply modifications in DB

(this will only take care of the doctrine part, you'll still have to apply the SQL update script)

2021-06-15 08:15 UTC, PierreRambaud commented
I'm closing it as we don't plan to merge it because these entities are managed by doctrine :)

2021-06-15 08:15 UTC, closed without merging

2021-06-15 08:16 UTC, lmeyer1 commented
@matthieu-rolland 
Thanks, this was really helpful.