Fèunctional tests - Refacto delivery slips tests
PrestaShop/PrestaShop pull request #25104
Opened 2021-06-23 14:39 UTC by nesrineabdmouleh

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Refacto delivery slips tests
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | no need
| Possible impacts? | no

2021-06-24 09:25 UTC, Progi1984 commented on tests/UI/campaigns/functional/BO/02_orders/04_deliverySlips/02_deliverySlipOptions/03_enableDisableProductImage.js
> +          await testContext.addContextItem(this, 'testIdentifier', `sighInFO${index}`, baseContext);
```suggestion
          await testContext.addContextItem(this, 'testIdentifier', `signInFO${index}`, baseContext);
```

2021-06-24 09:25 UTC, Progi1984 commented on tests/UI/campaigns/functional/BO/02_orders/04_deliverySlips/02_deliverySlipOptions/03_enableDisableProductImage.js
> +          await testContext.addContextItem(this, 'testIdentifier', `sighOutFO${index}`, baseContext);
```suggestion
          await testContext.addContextItem(this, 'testIdentifier', `signOutFO${index}`, baseContext);
```

2021-06-24 09:26 UTC, Progi1984 reviewed
Some feedbacks

2021-06-28 09:43 UTC, nesrineabdmouleh commented on tests/UI/campaigns/functional/BO/02_orders/04_deliverySlips/02_deliverySlipOptions/03_enableDisableProductImage.js
> +          await testContext.addContextItem(this, 'testIdentifier', `sighInFO${index}`, baseContext);
Done thx :+1:

2021-06-28 09:43 UTC, nesrineabdmouleh commented on tests/UI/campaigns/functional/BO/02_orders/04_deliverySlips/02_deliverySlipOptions/03_enableDisableProductImage.js
> +          await testContext.addContextItem(this, 'testIdentifier', `sighOutFO${index}`, baseContext);
Done thx :+1:

2021-06-28 09:44 UTC, Progi1984 approved these changes

2021-06-28 13:41 UTC, boubkerbribri approved these changes

2021-06-28 13:48 UTC, Progi1984 requested changes
## WAIT FOR 1780 RELEASE

2021-06-28 14:16 UTC, Progi1984 approved these changes

2021-06-28 14:16 UTC, merged

2021-06-28 14:16 UTC, Progi1984 commented
Thanks @nesrineabdmouleh & @boubkerbribri