Fix RTL issues on material icons on FO
PrestaShop/PrestaShop pull request #25101
Opened 2021-06-23 13:16 UTC by NeOMakinG

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | RTL had some problems mainly on slider icons and all product link icon
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25097.
| How to test?      | Use an RTL language and look at the issue
| Possible impacts? | FO icons on rtl

2021-06-24 09:53 UTC, Progi1984 approved these changes

2021-06-24 12:57 UTC, matks approved these changes

2021-06-25 09:49 UTC, florine2623 commented
Hello @NeOMakinG ,

If shop is installed in RTL language : **OK**
![pr25101](https://user-images.githubusercontent.com/16019289/123405569-3f69ff80-d5aa-11eb-8277-23d99f9f0eba.png)

If shop is installed in another language, then RTL language pack is added after : **NOK**
![prps178](https://user-images.githubusercontent.com/16019289/123406371-2150cf00-d5ab-11eb-9617-2cc800d787ee.png)

Thanks!

2021-06-25 12:51 UTC, NeOMakinG commented
@florine, when you do this, you've to rebuild the RTL stylesheet in Design => Theme & Logo on the top

![image](https://user-images.githubusercontent.com/14963751/123427389-d9d73c80-d5c4-11eb-8da6-5d217688d9f6.png)

2021-06-28 11:59 UTC, florine2623 commented
Hello @NeOMakinG ,

Looks perfect to me ! Thank you :)

2021-06-28 13:29 UTC, Progi1984 requested changes
## WAIT FOR 1780 RELEASE

2021-06-28 14:16 UTC, Progi1984 approved these changes

2021-06-28 14:16 UTC, merged

2021-06-28 14:16 UTC, Progi1984 commented
Thanks @NeOMakinG  & @florine2623