Fix pagination condition on shopping cart test
PrestaShop/PrestaShop pull request #25150
Opened 2021-06-29 08:55 UTC by boubkerbribri

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Fix pagination condition on shopping cart test
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | no tests needed
| Possible impacts? | none

2021-06-29 09:07 UTC, nesrineabdmouleh approved these changes

2021-06-29 09:36 UTC, Progi1984 approved these changes

2021-06-29 10:06 UTC, PierreRambaud approved these changes

2021-07-02 13:26 UTC, Progi1984 requested changes, later dismissed
## WAIT FOR 1780 RELEASE

2021-07-19 08:09 UTC, matks commented
QA has defined the scope of changes they want to embed inside 1.7.8.0 RC1 build 2. This PR is inside the list.

2021-07-19 08:09 UTC, matks commented
Thank you @boubkerbribri

2021-07-19 08:09 UTC, merged