Add option to duplicate images
PrestaShop/PrestaShop pull request #25159
Opened 2021-06-29 12:29 UTC by zuk3975

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | POC pr for this issue https://github.com/PrestaShop/PrestaShop/issues/13397
| Type?             | bug fix / improvement / new feature / refacto / critical
| Category?         | FO / BO / CO / IN / WS / TE / LO / ME / PM
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | https://github.com/PrestaShop/PrestaShop/issues/13397
| How to test?      | just a Proof of concept, nothing to test yet.
| Possible impacts? |

2021-08-09 08:26 UTC, Progi1984 requested changes
@zuk3975 Thank you for your contribution. Could you add behat tests for validating the new behavior in commandhandler ? Thanks

2021-11-10 12:21 UTC, zuk3975 commented
Closing as its only a draft/POC and is not a priority. The idea provided here is still valid, we can reopen if needed when (if ever) discussing this feature.

2021-11-10 12:21 UTC, closed without merging

2022-08-24 16:17 UTC, Hlavtox commented
Hi @zuk3975, do you think we are able to finish this PR? This is a feature some of my clients want. It's soooo annoying when you must delete 10 images after duplicating the product.

I thought about a switch in PS settings called "When duplicating products, also copy images".
OR
We could do it via a dynamic checkbox that would appear in a modal before duplicating the product(s).

2022-08-25 06:32 UTC, zuk3975 commented
> Hi @zuk3975, do you think we are able to finish this PR? This is a feature some of my clients want. It's soooo annoying when you must delete 10 images after duplicating the product.
> 
> I thought about a switch in PS settings called "When duplicating products, also copy images". OR We could do it via a dynamic checkbox that would appear in a modal before duplicating the product(s).

Yeah I could try. When doing POC it wasn't yet clear if this feature is accepted or not :man_shrugging: 
About the setting - IMO it should be in a modal before duplicating, because I think it would be used pretty often (like if you want to duplicate one product with images, but another without, it would be annoying to go back to the general settings every time)