Functional tests - CRUD cart rule with/without code
PrestaShop/PrestaShop pull request #25167
Opened 2021-06-30 09:05 UTC by nesrineabdmouleh

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Add test create cart rule with/without code
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | TEST_PATH="functional/BO/03_catalog/07_discounts/01_cartRules/01_CRUDCartRule/01_withAndWithoutCode.js" URL_FO=yourShopURL npm run specific-test
| Possible impacts? | no

2021-06-30 15:46 UTC, PierreRambaud approved these changes

2021-07-01 07:40 UTC, Progi1984 approved these changes

2021-07-01 07:53 UTC, matthieu-rolland approved these changes

2021-07-02 13:27 UTC, Progi1984 requested changes, later dismissed
## WAIT FOR 1780 RELEASE

2021-07-19 14:30 UTC, matks commented
QA team has defined the scope of changes that need to be embedded inside 1.7.8.0 RC1 build 2. This PR is inside the list.

2021-07-19 14:30 UTC, matks commented
Thank you @nesrineabdmouleh

2021-07-19 14:30 UTC, merged