Functional tests - Refacto login tests
PrestaShop/PrestaShop pull request #25171
Opened 2021-06-30 10:16 UTC by nesrineabdmouleh

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Refacto login tests
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | no need
| Possible impacts? | no

2021-06-30 11:20 UTC, boubkerbribri approved these changes

2021-06-30 14:50 UTC, PierreRambaud approved these changes

2021-06-30 15:27 UTC, NeOMakinG approved these changes

2021-07-02 13:27 UTC, Progi1984 requested changes, later dismissed
## WAIT FOR 1780 RELEASE

2021-07-19 08:07 UTC, matks commented
QA has defined the scope of changes they want to embed inside 1.7.8.0 RC1 build 2. This PR is inside the list.

2021-07-19 08:07 UTC, matks commented
Thank you @nesrineabdmouleh

2021-07-19 08:07 UTC, merged