Issue25133
PrestaShop/PrestaShop pull request #25192
Opened 2021-07-01 06:52 UTC by NeOMakinG

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Searchbar was full width on 1.7.7, it's a regression
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25133.
| How to test?      | Go on FO and see if searchbar is full width on tablet and mobiles
| Possible impacts? | FO Searchbar style

# How does it looks?
![image](https://user-images.githubusercontent.com/14963751/124079524-8e4fe300-da49-11eb-8f51-dbc4a414ea07.png)
![image](https://user-images.githubusercontent.com/14963751/124079563-990a7800-da49-11eb-9c13-4d7e62c2f1eb.png)

⚠️ Should probably be merged after 1.7.8 release

2021-07-01 07:16 UTC, Progi1984 approved these changes

2021-07-02 07:40 UTC, matthieu-rolland approved these changes

2021-07-02 16:09 UTC, hibatallahAouadni commented
Hello @NeOMakinG 

Thanks for your PR!
LGTM, QA :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/23308427/124301739-8171e300-db60-11eb-9da9-44dd1c857e45.png)

Thanks!

2021-07-02 19:12 UTC, Progi1984 requested changes, later dismissed
## WAIT FOR 1780 RELEASE

2021-07-06 15:17 UTC, PierreRambaud approved these changes

2021-08-17 10:24 UTC, merged