Deprecated id_tax_rules_group in carrier table.
PrestaShop/PrestaShop pull request #25207
Opened 2021-07-01 15:57 UTC by jf-viguier

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | id_tax_rules_group is not used anymore.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | read the carrier class
| Possible impacts? | none

2021-07-01 15:57 UTC, jf-viguier commented
Is this column can be deleted or it should be a bc break ?

2021-07-02 08:52 UTC, Progi1984 commented
@jf-viguier Sorry... But I have another parts in code linked to carriers :
* `admin-dev/themes/default/template/controllers/carriers/helpers/form/form.tpl` (l.37)
* `controllers/admin/AdminCarriersController.php` a lot of `id_tax_rules_group`
* `js/admin/carrier_wizard.js` l.197
* `UI/pages/BO/shipping/carriers/add.js` l.26

2021-07-02 14:32 UTC, jf-viguier commented
@Progi1984 id_tax_rules_group is stored for the carrier in another table than carrier table : 
 carrier_tax_rules_group_shop.id_tax_rules_group

2021-07-02 14:35 UTC, jf-viguier commented
@Progi1984 thanks to automatic tests, I've removed id_tax_rules_group from initial data

2021-07-08 12:54 UTC, jf-viguier commented
@Progi1984 all tests are ok now, please remove Waiting for author label as all id_tax_rules_group you founded are related to the other table, not carrier table.

2021-07-08 15:28 UTC, Progi1984 approved these changes, later dismissed

2021-07-08 15:51 UTC, jf-viguier commented
what's the problem with Integration tests (7.4) ?

2021-07-09 07:25 UTC, Progi1984 commented
@jf-viguier Restarted CI.

2021-07-09 09:14 UTC, PierreRambaud requested changes
Upgrade scripts need to be updated :)

2021-07-09 09:29 UTC, jf-viguier commented
@PierreRambaud nice catch, added in 1.7.9 upgrade

2021-07-12 08:21 UTC, PierreRambaud commented on install-dev/upgrade/sql/1.7.9.0.sql
> +ALTER TABLE `PREFIX_carrier` DROP COLUMN `id_tax_rules_group`;
```suggestion
ALTER TABLE `PREFIX_carrier` DROP COLUMN `id_tax_rules_group`;

```

2021-07-12 08:21 UTC, PierreRambaud approved these changes, later dismissed

2021-07-12 09:13 UTC, jf-viguier commented
Thanks @PierreRambaud

2021-07-16 12:39 UTC, matthieu-rolland approved these changes, later dismissed

2021-07-28 09:07 UTC, jolelievre requested changes, later dismissed
@jf-viguier there is still a reference to this DB field here
https://github.com/PrestaShop/PrestaShop/blob/7c005444cf00710a81149e6c5ca861f32c600ce6/classes/Carrier.php#L606

Even if the function doesn't seem to be used by the core, but it might be used by modules So either we remove it (which is a BC break) or we can update the query to rely on the other table `carrier_tax_rules_group_shop`

2021-07-28 17:20 UTC, jf-viguier commented
@jolelievre actually, id_tax_rules_group is always 0 in carrier table, so this method always return false.

2021-07-28 17:25 UTC, jf-viguier commented
@jolelievre I've fixed the getIdTaxRulesGroupMostUsed sql. It's used in AdminCarrierWizardController.php.

2021-07-28 17:34 UTC, jf-viguier commented
It's seems that I've fixed some CRLF in Carrier.php

2021-07-29 08:47 UTC, Progi1984 submitted a review, later dismissed

2021-09-02 09:28 UTC, matthieu-rolland reviewed
seems like there are conflicts to be solved, otherwise LGTM 👍

2021-09-02 14:59 UTC, jf-viguier commented
@matthieu-rolland conflicts resolved

2021-09-03 10:05 UTC, jf-viguier commented
@Progi1984 @matthieu-rolland what's wrong with tests ?

2021-09-03 10:07 UTC, matks commented
> @Progi1984 @matthieu-rolland what's wrong with tests ?

prestashop.com is down so tests are in another dimension 😅

2021-09-03 11:00 UTC, Julievrz commented
Looks like there's no wording in this PR, I'm removing the "waiting for wording" label. Feel free to ping me if needed. 🤗

2021-10-08 13:44 UTC, matks commented
Hi @jf-viguier sorry for coming back late. Unfortunately in September prestashop.com was down so it messed up the CI. I close and reopen the PR to reset the CI and know whether tests pass however you'll need to rebase the PR.

2021-10-22 07:19 UTC, jf-viguier commented
@matks rebase done, have a good friday.

2021-10-22 07:29 UTC, jf-viguier commented
@matks I've add the sql part also here https://github.com/jf-viguier/autoupgrade/pull/1

2021-10-22 07:52 UTC, PierreRambaud commented on classes/Carrier.php
>          );
Be careful, you replace all spaces with tabs for no reason.

2021-10-22 12:33 UTC, jf-viguier commented on classes/Carrier.php
>          );
@PierreRambaud it's fixed.

2021-10-25 08:47 UTC, Progi1984 submitted a review, later dismissed
@jf-viguier Could you move the SQL query to `autoupgrade` module ?

2021-12-03 10:19 UTC, PierreRambaud commented
Hi @jf-viguier ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2021-12-03 10:23 UTC, jf-viguier commented
@PierreRambaud what are you waiting for ? I've done the pr you asked ?
https://github.com/jf-viguier/autoupgrade/pull/1

2021-12-03 10:27 UTC, jf-viguier commented
@PierreRambaud my bad, the pr is there https://github.com/PrestaShop/autoupgrade/pull/437 (wrong depot)

2021-12-03 10:32 UTC, jf-viguier commented
@Progi1984 asked pr is done.

2021-12-03 10:34 UTC, PierreRambaud commented
I reopen this PR, but next time, don't forget to answer maintainers' messages and link to the right repository :wink:

2021-12-03 10:34 UTC, PierreRambaud commented
Anyway the PR still need to be rebased

2021-12-03 10:44 UTC, Progi1984 approved these changes

2021-12-03 16:56 UTC, matks approved these changes
Looks OK but we need to be extra careful about validating this change. PrestaShop is not friendly with such changes; we might break something in an unknown location.

@jf-viguier can you please provide a "How to test" a little bit more complete for QA team ? it could mention places in the software where id_tax_rules_group might be used. It must be for them a path they can follow to look for issues.

2021-12-04 12:16 UTC, jf-viguier commented
@matks this column is not used anymore since 1.7

2021-12-05 14:06 UTC, matks commented
@jf-viguier Do you mean there is, according to our knowledge, zero line of code that do use this column in prestashop ?

2021-12-05 15:20 UTC, jf-viguier commented
@matks yes this column is not used anymore since 1.7, The only place where it's used is in this stat method Carrier::getIdTaxRulesGroupMostUsed(). I've fixed it n the pr: this stat always return zero.
I've updated the "how to test".

2021-12-06 16:08 UTC, khouloudbelguith commented
Hi @jf-viguier,

It is ok :heavy_check_mark: 
1. I created some carriers with different ranges
2. I created a carrier with a tax breakdown
3. I created some orders from the FO & BO 
4. I created a cart rule "free shipping" & apply it
5. I edited some orders when "Recalculate shipping costs after editing the order" is enabled & disabled

=> ok :heavy_check_mark: 
https://watch.screencastify.com/v/7T2BNIjZYutavq0jQklP

**With PR**
![image](https://user-images.githubusercontent.com/16067358/144880542-048ab8d7-5805-4344-8e31-9aac7304db37.png)

**Without PR**
![image](https://user-images.githubusercontent.com/16067358/144880614-052eb4fd-c229-488c-a5aa-a19f5150ea5f.png)

Thanks!

2021-12-07 13:19 UTC, merged

2021-12-07 13:19 UTC, Progi1984 commented
Thanks @jf-viguier & @khouloudbelguith

2021-12-07 14:33 UTC, jf-viguier commented
Thanks @Progi1984, don't forget this related pr here to delete the column https://github.com/PrestaShop/autoupgrade/pull/437