Functional tests - Refacto products tests
PrestaShop/PrestaShop pull request #25219
Opened 2021-07-02 15:37 UTC by nesrineabdmouleh

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Refacto products tests
| Type?             | befacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | no need
| Possible impacts? | no

2021-07-05 07:54 UTC, NeOMakinG approved these changes

2021-07-05 08:44 UTC, boubkerbribri approved these changes

2021-07-05 08:45 UTC, boubkerbribri requested changes, later dismissed
Wait For 1.7.8.0 release

2021-07-19 08:03 UTC, matks approved these changes

2021-07-19 08:04 UTC, matks commented
@boubkerbribri Robin has defined the scope of changes the QA team want to embed inside 1.7.8.0 RC1 build 2. This PR is inside the list.

2021-07-19 08:04 UTC, matks commented
Thank you @nesrineabdmouleh

2021-07-19 08:04 UTC, merged