Use memcached.
PrestaShop/PrestaShop pull request #25217
Opened 2021-07-02 13:26 UTC by lmeyer1

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This override implements a working implementation of memcached database cache. 5 years + in production environment with PS 1.6.1.1, currently in dev and pre-prod environment PS 1.7.7.5.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | yes. The class `cache` is overridden. These changes are not intended to work with the other cache implementations.
| Deprecations?     | no
| Fixed ticket?     | Fixes #25185.
| How to test?      | Enable memcached and test on a shop instance with frequent database updates
| Possible impacts? | Improves performance. Thanks to a working cache invalidation system, there is no adverse impact whatsoever.

This is how cache invalidation is designed:
- Every DML query is scanned for table names. Cache is invalidated for all tables contained in the query.
- Every query result is stored alongside its timestamp in a key that consist of `md5($query)`and a prefix (to differentiate between different instances of PS (e.g. prod and dev environment).
- The cache is expired using a mysql table (`PREFIX_memcached`), that contains the table name and the timestamp of the last update. (I have chosen mysql for this, because each query is atomic, the order of execution is guaranteed and the operation is guaranteed to succeed. memcached does not guarantee any of these three requirements for a working cache invalidation).
- When a result is retrieved, its timestamp is compared to the expiry stamp stored in `PREFIX_memcached`. If the result proves to be outdated, the query is rerun and the cache is updated.
- Stale records in the memcached storage heap are not actively deleted, bu as they age they may be garbage collected by memcached.

There are the following missing pieces in this PR:
- In the BO, we need a separate button to flush memcached cache (currently ther is just one button `Clear cache`. For the use case, that we update a specific table directly in mysql, we need an option to invalidate only the cache of that table. I have this working in PS 1.6, but I did not yet have the time to port it to PS 1.7
- The class `Profiling` referenced stores statistics, that are graphed with cacti. This is out of scope, so I'll leave it out anyway.

2021-07-12 12:30 UTC, PierreRambaud requested changes
Hi and thanks for your proposal.
But regarding what you are trying to do is more a "module behavior" than a fix/feature for the Core.
if you want us to merge your pull request, you have to make the Cache class extendable or configurable.
Otherwise, you can add missing hooks in order to allow your own implementation to work. But we can't merge a pull request that added files in the `override` directory, as you said, your implementation will break all the others.

2021-07-12 12:34 UTC, kpodemski commented
Hey @PierreRambaud 

I suggested @lmeyer1 add his code as a pull request for me to review it, and make some tests whether it's helpful for Memcached in PrestaShop or not 👍 this is why I added a WIP label, I'll take on this PR later

2021-07-12 12:37 UTC, PierreRambaud commented
> Hey @PierreRambaud
> 
> I suggested @lmeyer1 add his code as a pull request for me to review it, and make some tests whether it's helpful for Memcached in PrestaShop or not  this is why I added a WIP label, I'll take on this PR later

Oh, I better understand now :sweat_smile: 
Have fun guys ;)

2021-07-12 12:41 UTC, matks commented
>  whether it's helpful for Memcached in PrestaShop 

That's actually a good question. There's a few systems implemented in PrestaShop to improve performance: multiple options for Smarty, CCC, and PHP cache (memcache, memcached, APC and XCache).

The year is 2021: I am sure some of them are outdated and not used anymore by the majority of people while other systems more recent are very popular. Should we refresh the list, and does memcached belongs to the list after it has been updated according to 2021 standards?

2021-07-12 12:49 UTC, lmeyer1 commented
> There's a few systems implemented in PrestaShop to improve performance: multiple options for Smarty, CCC, and PHP cache (memcache, memcached, APC and XCache).

While options for Smarty and CCC work well, I was not able to get to work any of the database cache options (memcache, memcached, APC and XCache).
memcache is overseded by memcached. memcached's implementation is fundamentally flawed (that's why I rewrote it). It didn't manage to get to work APC and XCache neither. Since it's some years ago, I don't recall the reason.

> The year is 2021: I am sure some of them are outdated and not used anymore by the majority of people

Yes, I think redis may be more used than memcached today. memcached is still working today, simple to set up and get running. I'm not sure APC and XCache are still useable today.

I think Prestashop really should invest in getting a PHP database cache running. It will lead to an important performance increase on many installations.

2021-07-12 13:25 UTC, PierreRambaud commented
> > There's a few systems implemented in PrestaShop to improve performance: multiple options for Smarty, CCC, and PHP cache (memcache, memcached, APC and XCache).
> 
> While options for Smarty and CCC work well, I was not able to get to work any of the database cache options (memcache, memcached, APC and XCache).
> memcache is overseded by memcached. memcached's implementation is fundamentally flawed (that's why I rewrote it). It didn't manage to get to work APC and XCache neither. Since it's some years ago, I don't recall the reason.
> 
> > The year is 2021: I am sure some of them are outdated and not used anymore by the majority of people
> 
> Yes, I think redis may be more used than memcached today. memcached is still working today, simple to set up and get running. I'm not sure APC and XCache are still useable today.
> 
> I think Prestashop really should invest in getting a PHP database cache running. It will lead to an important performance increase on many installations.

memcached has a lot of problems (performance, networks, ...) when using a web cluster, that's the reason why I use redis too.

>I think Prestashop really should invest in getting a PHP database cache running. It will lead to an important performance increase on many installations.


You're right, unfortunately, we have a lot of subjects with the same priority, and a lot of others, with higher priority, that's the reason we are waiting for contributions from the outside :sweat_smile:

2021-12-03 09:34 UTC, PierreRambaud commented
Hey @lmeyer1 
Still in WIP?

2021-12-03 09:44 UTC, lmeyer1 commented
@lmeyer1
No, not WIP, production-ready since 5 years.
As of my experience with PR, it would take 14 days of discussions and dozens of code reviews to get approved. I don't have so much spare time. 
I also notice, that the improvement with memcached in PS 1.7.8 is much lesser than what I experienced in 1.6.

IMHO, the current implementation in PS is not working at all
- it will increase page load time instead of reduce it
- it is not concurrency safe at all (at not point in time two request must run in parallel)
- cache invalidation is completely flawed

Therefore, I'd recommend to remove these options in the BO altogether (until there is a working solution, if there ever will be).

2021-12-03 09:56 UTC, PierreRambaud commented
> @lmeyer1 No, not WIP, production-ready since 5 years. As of my experience with PR, it would take 14 days of discussions and dozens of code reviews to get approved. I don't have so much spare time. I also notice, that the improvement with memcached in PS 1.7.8 is much lesser than what I experienced in 1.6.
> 
> IMHO, the current implementation in PS is not working at all
> 
> * it will increase page load time instead of reduce it
> * it is not concurrency safe at all (at not point in time two request must run in parallel)
> * cache invalidation is completely flawed
> 
> Therefore, I'd recommend to remove these options in the BO altogether (until there is a working solution, if there ever will be).

I understand your thought, unfortunately, we can't validate and merge a pull request which is playing with overrides.

Kind regards

2021-12-03 09:56 UTC, closed without merging

2021-12-03 09:58 UTC, lmeyer1 commented
@PierreRambaud 
No problem...

2021-12-03 10:03 UTC, kpodemski commented
Hello @lmeyer1 

I have your PR bookmarked, and I'm assigned to it. We are not throwing it in the trash. We appreciate the base you shared with us. We will try to improve Memcached support in PrestaShop.