Show error delete product on order page admin
PrestaShop/PrestaShop pull request #25291
Opened 2021-07-08 20:53 UTC by ytilotti

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 1.7.8.x / 1.7.7.x
| Description?      | The errors on action delete product in the admin page of an order were not showing. It's OK on update & add action.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Create an hookActionObjectOrderDetailDeleteBefore and throw an exception.

2021-07-09 09:15 UTC, PierreRambaud requested changes, later dismissed
Hi @ytilotti and thanks for your PR

Could you please create an issue in order to understand what's the issue and how we can reproduce it.

2021-07-09 10:27 UTC, ytilotti commented
The issue #25298

2021-07-09 12:04 UTC, Progi1984 submitted a review, later dismissed

2021-07-15 14:08 UTC, NeOMakinG approved these changes, later dismissed

2021-07-26 13:06 UTC, SD1982 commented
Hi @ytilotti I have applied this PR in combination with this one [18](https://github.com/PrestaShop/ps_qualityassurance/pull/18) and i still don't have the error notification ...
Did i miss something ?

2021-07-26 14:10 UTC, ytilotti commented
> Hi @ytilotti I have applied this PR in combination with this one [18](https://github.com/PrestaShop/ps_qualityassurance/pull/18) and i still don't have the error notification ...
> Did i miss something ?

Hi @SD1982, this PR [18](https://github.com/PrestaShop/ps_qualityassurance/pull/18) is just for testing withou

> Hi @ytilotti I have applied this PR in combination with this one [18](https://github.com/PrestaShop/ps_qualityassurance/pull/18) and i still don't have the error notification ...
> Did i miss something ?

Have you clear your cache browser? It's a javascript part. Have you Throw an exception in the hook actionObjectOrderDetailDleteBefore on the module ps_qualityassurance ?

2021-07-28 15:36 UTC, khouloudbelguith commented
Hi @PrestaShop/prestashop-core-developers,

The issue https://github.com/PrestaShop/PrestaShop/issues/25298 is a regression from PS177.
So this PR should be fixed in the 177x branch and not develop branch.
What do you think?

Thanks!

2021-09-14 08:27 UTC, PierreRambaud commented
> Hi @PrestaShop/prestashop-core-developers,
> 
> The issue #25298 is a regression from PS177.
> So this PR should be fixed in the 177x branch and not develop branch.
> What do you think?
> 
> Thanks!

Targetting 1.7.8. seems ok, but not the 1.7.7.x

2021-09-14 12:49 UTC, khouloudbelguith commented
Hi @PierreRambaud,

Thanks for the feedback.
@ytilotti, you need to change the target from develop to 1.7.8.x.

Thanks!

2021-09-14 12:53 UTC, PierreRambaud commented
PR has been rebased

2021-10-01 10:48 UTC, PierreRambaud approved these changes

2021-10-01 10:49 UTC, Progi1984 approved these changes

2021-10-01 13:05 UTC, NeOMakinG approved these changes

2021-10-08 12:36 UTC, florine2623 commented
Hello @ytilotti ,

Thanks for the PR !
Looks good to me.

https://watch.screencastify.com/v/11hRbYYcSXUOjLChOU9z

2021-10-08 13:14 UTC, merged

2021-10-08 13:14 UTC, Progi1984 commented
Thanks @ytilotti