Functional tests - Refacto customer service tests
PrestaShop/PrestaShop pull request #25307
Opened 2021-07-09 15:44 UTC by nesrineabdmouleh

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Refacto customer service tests
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | no need
| Possible impacts? | no

2021-07-13 15:56 UTC, boubkerbribri requested changes
There is a jpg file here that need to be deleted

2021-07-19 15:25 UTC, boubkerbribri approved these changes

2021-07-20 09:12 UTC, Progi1984 approved these changes

2021-07-21 08:59 UTC, matthieu-rolland approved these changes

2021-08-10 07:11 UTC, NeOMakinG approved these changes

2021-08-23 12:01 UTC, merged

2021-08-23 12:01 UTC, Progi1984 commented
Thank you @nesrineabdmouleh