Mcho/#13841 improve tooltip wording of the products settings option
PrestaShop/PrestaShop pull request #25462
Opened 2021-07-29 12:43 UTC by Mch0

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 

| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #13841
| How to test?      | Juste go in BO page to check the tooltip has been updated

2021-07-29 13:21 UTC, atomiix commented on translations/default/AdminShopparametersHelp.xlf
> +        <target>Enable this option if you want to activate by default all your manually created new products.</target>
This is not needed, translation files are exported later during the release process ;)

2021-07-29 13:22 UTC, atomiix requested changes
Thanks for your contribution @Mch0, just a file to revert and we should be good!

2021-07-29 16:09 UTC, atomiix approved these changes

2021-07-30 07:58 UTC, Julievrz approved these changes

2021-08-02 07:41 UTC, matthieu-rolland reviewed
hi @Mch0, thank you for your contribution :)

Seems like the CI is blocking your PR because it contains a merge commit, which is not authorized on the project

2021-08-02 08:48 UTC, Mch0 commented
Hum seem bad, can i change the branch to start from correct develop branch ? I am going to create a new branch who start from correct develop branch

2021-08-02 16:24 UTC, matks commented
> Hum seem bad, can i change the branch to start from correct develop branch ? I am going to create a new branch who start from correct develop branch

This PR is tied to your branch `mcho/#13841-improve-tooltip-wording-of-the-products-settings-option`

If you correct this branch, the PR will automatically update.
If you prefer to create a new branch, you will have to close this PR and open another PR.

2021-11-08 16:50 UTC, PierreRambaud commented
Hi @Mch0 ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2021-11-08 16:50 UTC, closed without merging