Move StockController into Admin/Sell/Catalog/
PrestaShop/PrestaShop pull request #25561
Opened 2021-08-10 13:53 UTC by eternoendless

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Moved StockController into the appropriate namespace
| Type?             | refacto
| Category?         | BO
| BC breaks?        | yes - The file changed its namespace and location
| Deprecations?     | no
| Fixed ticket?     | N/A
| How to test?      | The stock page loads
| Possible impacts? | This only impacts the page load because the content is handled by another controller

2021-08-11 06:44 UTC, Progi1984 reviewed
@eternoendless Thank you for your contribution. Could you fix PHPStan error ?

2021-08-12 10:17 UTC, matthieu-rolland reviewed
minor feedback and phpstan issue, otherwise lgtm 👍

2021-08-12 10:17 UTC, matthieu-rolland commented on tests/Resources/modules/ps_banner/config.xml
> +</module>
```suggestion
</module>

```

2021-08-12 12:46 UTC, matks submitted a review, later dismissed

2021-08-12 13:13 UTC, sowbiba reviewed
Approved as soon as phpstan error fixed. Maybe remove return annotation from FrameworkBundleAdminController::overviewAction ?

2021-09-02 09:51 UTC, matks requested changes
Need to fix PHPStan

2021-11-08 17:02 UTC, PierreRambaud commented
Hi @eternoendless ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2021-11-08 17:02 UTC, closed without merging

2021-12-02 12:00 UTC, eternoendless commented
Reopened here #26836