Refacto some sensible selectors and add some missing selectors to classic selector map
PrestaShop/PrestaShop pull request #25595
Opened 2021-08-13 13:29 UTC by NeOMakinG

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Some selectors were too sensible and some were missing in classic theme
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25583.
| How to test?      | Test if every pages concerned are working fine (View order with add product feature, View supplier, View brand, Classic theme cart) and run tests of Suppliers and Brands
| Possible impacts? | Global

2021-08-13 14:05 UTC, matthieu-rolland approved these changes, later dismissed

2021-08-17 07:57 UTC, PierreRambaud approved these changes, later dismissed

2021-08-25 08:00 UTC, sowbiba approved these changes, later dismissed

2021-08-25 08:05 UTC, Progi1984 submitted a review, later dismissed

2021-09-28 09:23 UTC, hibatallahAouadni commented
Ping @NeOMakinG could you please resolve the Conflicting files :pray: 
Thanks in advance!

2021-09-30 10:31 UTC, atomiix submitted a review, later dismissed

2021-10-07 06:23 UTC, PierreRambaud submitted a review, later dismissed

2021-11-25 09:52 UTC, khouloudbelguith commented
Hi @NeOMakinG,

thanks to check the Conflicting files.

Thank you!

2021-12-06 12:49 UTC, Progi1984 commented on src/PrestaShopBundle/Resources/views/\
> +{#**
@NeOMakinG It seems the file has a bad file name.

2021-12-06 12:49 UTC, Progi1984 requested changes
@NeOMakinG :warning: A file has a bad file name

2021-12-10 14:04 UTC, atomiix approved these changes

2021-12-13 14:07 UTC, Progi1984 approved these changes

2021-12-14 17:33 UTC, khouloudbelguith commented
Hi @NeOMakinG,

It is ok :heavy_check_mark: 
1. Classic theme cart:
- I check a product with customization (file or text)
- Increase/Decrease quantity => ok (a product will be out of stock / minimal quantity)
- Add a voucher / remove a voucher (with code & node_code)
- Remove a product
https://watch.screencastify.com/v/2OSGeHQBmFYWq7O0XuXD

2. run tests of Suppliers and Brands => ok 
[Mochawesome Report_brands&suppliers.pdf](https://github.com/PrestaShop/PrestaShop/files/7713573/Mochawesome.Report_brands.suppliers.pdf)

3. View order with add product feature
- I tried to add products to order (all types)
- Create an invoice when adding a product
- Add a product with a specific cart rule

4. View brand => ok and I reported this issue: https://github.com/PrestaShop/PrestaShop/issues/26985
5. View supplier  => ok
![image](https://user-images.githubusercontent.com/16067358/146049843-6aa94e4e-bb4e-4d8f-a478-0157f23aced9.png)


Thanks!

2021-12-15 07:53 UTC, merged

2021-12-15 07:53 UTC, Progi1984 commented
Thanks @NeOMakinG & @khouloudbelguith