Fix html lang attribute to use the locale instead of ISO code
PrestaShop/PrestaShop pull request #25635
Opened 2021-08-18 09:26 UTC by NeOMakinG

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | ISO Code is wrong because it only output the subtag instead of the main language, no we're using the full syntax using the locale variable, so it will output en-GB for great Britain for example
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25042.
| How to test?      | Go on the home page or anything, with English from GB, and use an SEO tool in order to find it en-GB is valid (see issue, @futurehousestore linked some SEO tools)
| Possible impacts? | SEO

2021-08-18 12:27 UTC, matthieu-rolland approved these changes

2021-08-19 14:09 UTC, eternoendless approved these changes

2021-08-19 14:09 UTC, eternoendless commented
If this is meant to go in 1.7.8.0 then it should target the `1.7.8.0-build` branch

2021-08-19 14:22 UTC, NeOMakinG commented
@eternoendless alright sorry, rebased it!

2021-08-19 14:36 UTC, eternoendless approved these changes

2021-08-19 14:37 UTC, eternoendless requested changes
Sorry, you need to rebase now

2021-08-20 08:15 UTC, NeOMakinG commented
@eternoendless good!

2021-08-20 08:52 UTC, PierreRambaud approved these changes

2021-08-20 13:16 UTC, hibatallahAouadni commented
Hello @NeOMakinG 

Thanks for your PR :rocket: 
LGTM, QA :heavy_check_mark: 
https://drive.google.com/file/d/1-3rvzGHsZlLpL5G04LJJ7m8wfj80-kOQ/view

Thanks!

2021-08-20 14:20 UTC, eternoendless commented
Thank you @NeOMakinG

2021-08-20 14:20 UTC, merged