Make Advanced Parameters > Logs configuration form multistore compatible
PrestaShop/PrestaShop pull request #25645
Opened 2021-08-19 08:23 UTC by ecomiz

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR add checkboxes and specifics settings drop-downs list to  BO > Advanced Parameters > Logs page to make it multistore compatible
| Type?             | new feature
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #19358 and #19311 
| How to test?      | See issue
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

2021-08-20 08:52 UTC, Julievrz commented
I don't think this PR changes or adds any wording. I remove the "waiting for wording" label but please put it back or ping me if necessary.

2021-08-20 09:05 UTC, PierreRambaud commented on admin-dev/themes/new-theme/public/logs.bundle.js
> +/*! For license information please see logs.bundle.js.LICENSE.txt */
This is has to be removed. The whole public directory is in the gitignore

2021-08-20 09:05 UTC, PierreRambaud commented on src/Adapter/Configuration/LogsConfiguration.php
> +
```suggestion
```

2021-08-20 09:05 UTC, PierreRambaud commented on src/Adapter/Configuration/LogsConfiguration.php
> +            $validate = new Validate();
The validator needs to be injected in the constructor

2021-08-20 09:05 UTC, PierreRambaud commented on src/Adapter/Configuration/LogsConfiguration.php
> +            $translator = $context->getTranslator();
Same for the translator

2021-08-24 15:49 UTC, matthieu-rolland commented on src/Adapter/Configuration/LogsConfiguration.php
> +            $translator = $context->getTranslator();
@ecomiz I think here you could declare a constructor in the class, taking the same parameters as `AbstractMultistoreConfiguration`, and add the translator.

I see the translator is already in the service definition, since you didn't remove it.

```php
public function __construct(
  Configuration $configuration,
  Context $shopContext,
  FeatureInterface $multistoreFeature,
  TranslatorInterface $translator,
  Validate $validate
)
{
      $this->configuration = $configuration;
      $this->shopContext = $shopContext;
      $this->multistoreFeature = $multistoreFeature;
      $this->translator = $translator;
      $this->validate = $validate;
}
```

If you don't need the `$validate` parameter, you can remove it from the constructor and from the service definition in `src/PrestaShopBundle/Resources/config/services/adapter/data_configuration.yml`

2021-08-24 15:51 UTC, matthieu-rolland commented on src/Adapter/Configuration/LogsConfiguration.php
> +                    $errors[] = $translator->trans(
Once you have injected the translator in your constructor (like it used to be), you can use `$this->translator` again 👍 

```suggestion
                    $errors[] = $this->translator->trans(
```

2021-08-24 15:52 UTC, matthieu-rolland commented on src/Adapter/Configuration/LogsConfiguration.php
> +                    $errors[] = $translator->trans(
(same everywhere you wrote `$translator->trans(` )

2021-08-24 15:53 UTC, matthieu-rolland requested changes
Thank you very much for your contribution @ecomiz 👍 

We have some feedback and requested changes, but this is looking quite good overall 🚀

2021-08-24 15:56 UTC, matthieu-rolland commented on src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/logs.yml
> +    methods: [PATCH, POST]
👍

2021-09-08 07:08 UTC, Progi1984 commented on src/Adapter/Configuration/LogsConfiguration.php
> +        $this->multistoreFeature = $multistoreFeature;
```suggestion
        parent::__construct($configuration, $shopContext, $multistoreFeature);
```

2021-09-08 07:09 UTC, Progi1984 commented on src/Adapter/Configuration/LogsConfiguration.php
> +        $this->multistoreFeature = $multistoreFeature;
You can remove attributes, too. They are all available in `abstract class AbstractMultistoreConfiguration`.

2021-09-08 07:10 UTC, Progi1984 reviewed
@ecomiz Good job. A last feedback fore removing duplicated code.

2021-09-08 14:51 UTC, Progi1984 approved these changes

2021-11-15 15:12 UTC, PierreRambaud commented
Hi @ecomiz 
are you able to rebase your PR?

2022-01-19 10:08 UTC, PierreRambaud commented
Hi @ecomiz ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2022-01-19 10:08 UTC, closed without merging