In BO > Order, fixed the bug when the bug is disabled in adding a vou…
PrestaShop/PrestaShop pull request #25692
Opened 2021-08-24 15:24 UTC by Progi1984

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | In BO > Order, fixed the bug when the bug is disabled in adding a voucher
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25627
| How to test?      | Cf. #25627
| Possible impacts? | N/A

2021-08-24 15:29 UTC, matthieu-rolland submitted a review, later dismissed

2021-08-25 07:56 UTC, sowbiba submitted a review, later dismissed

2021-08-25 09:58 UTC, PierreRambaud commented on admin-dev/themes/new-theme/js/pages/order/view.ts
> +        $(OrderViewPageMap.addCartRuleSubmit).attr('disabled', 'disabled');
```suggestion
        $(OrderViewPageMap.addCartRuleSubmit).prop('disabled', true);
```

2021-08-25 09:59 UTC, PierreRambaud commented on admin-dev/themes/new-theme/js/pages/order/view.ts
> +      }
```suggestion
      $(OrderViewPageMap.addCartRuleSubmit).prop('disabled', cartRuleName.trim().length === 0);
```

What about this?

2021-08-25 09:59 UTC, PierreRambaud requested changes, later dismissed
Simple question, should be easier to understand

2021-08-25 11:42 UTC, Progi1984 commented on admin-dev/themes/new-theme/js/pages/order/view.ts
> +      }
Better. Thanks.

2021-08-26 15:13 UTC, NeOMakinG submitted a review, later dismissed

2021-08-27 07:43 UTC, matthieu-rolland submitted a review, later dismissed

2021-08-30 09:51 UTC, matks submitted a review, later dismissed

2021-09-06 13:10 UTC, khouloudbelguith commented
Hi @Progi1984,

I have an issue following these steps:
1. Go to BO > Orders > Orders > Edit Order
2. Try to add a discount with type Amount
3. See error the Value is disabled 
![image](https://user-images.githubusercontent.com/16067358/132222450-fbf613bb-35da-4117-9ff2-c91b622937a5.png)

Thanks!

2021-09-06 14:23 UTC, PierreRambaud commented
> Hi @Progi1984,
> 
> I have an issue following these steps:
> 
> 1. Go to BO > Orders > Orders > Edit Order
> 2. Try to add a discount with type Amount
> 3. See error the Value is disabled
>    ![image](https://user-images.githubusercontent.com/16067358/132222450-fbf613bb-35da-4117-9ff2-c91b622937a5.png)
> 
> Thanks!

@Progi1984 You also have to change this part of code:
```js
    $modal.on('shown.bs.modal', () => {
      $(OrderViewPageMap.addCartRuleSubmit).attr('disabled', 'true');
    });
```
into

```js
    $modal.on('shown.bs.modal', () => {
      $(OrderViewPageMap.addCartRuleSubmit).prop('disabled', true);
    });
```

2021-09-06 15:01 UTC, sowbiba approved these changes, later dismissed

2021-09-08 08:50 UTC, atomiix approved these changes

2021-09-08 08:55 UTC, PierreRambaud approved these changes

2021-09-14 12:53 UTC, marwachelly commented
Hello,
I checked with @khouloudbelguith , The PR is OK :heavy_check_mark: 
Thanks,

2021-09-14 13:16 UTC, merged

2021-09-14 13:16 UTC, Progi1984 commented
Thanks @marwachelly & @khouloudbelguith