Remove "select" case and fix "editable" one in HelperList
PrestaShop/PrestaShop pull request #25770
Opened 2021-09-02 10:25 UTC by PrestaEdit

2021-09-02 10:29 UTC, Progi1984 commented
@PrestaEdit Hi! Thank you for your contribution. Could you fill the PR table, please ? You can find it here : https://raw.githubusercontent.com/PrestaShop/PrestaShop/develop/.github/PULL_REQUEST_TEMPLATE.md.

2021-09-02 10:29 UTC, PrestaEdit commented
Hi @Progi1984 , just done it ! I was making the PR with VS Code and it's created alone, sorry about it ;-)

2021-09-02 10:32 UTC, Progi1984 commented
@PrestaEdit I don't understand why we need to remove `select`.

2021-09-02 10:33 UTC, PrestaEdit commented
Because HelperList template doesn't handle them. It will just showing nothing.
As HelperList is not make to show this kind of data, the template don't have this type in it.

2021-09-08 09:06 UTC, Progi1984 approved these changes

2021-09-08 09:16 UTC, PierreRambaud requested changes
The select type is used, not only by the Core, but can also be used by developer in their modules: https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/default/template/helpers/list/list_header.tpl#L378

Same, text is the default behavior:
https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/default/template/helpers/list/list_header.tpl#L390

2021-09-08 09:29 UTC, PrestaEdit commented
You're right about the select type, it's - strangely - used to display the filter as a select on the HelperList header.

The text type is not used. It's editable. It's not the same thing, for informations.

2021-09-08 09:29 UTC, closed without merging