Fixed import of macros for infotip use in multistore mode
PrestaShop/PrestaShop pull request #25775
Opened 2021-09-02 13:01 UTC by Progi1984

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fixed import of macros for infotip use in multistore mode
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25703
| How to test?      | 1. Enable Multistore context<br>2. Create a new shop and configure it<br><br>**BEFORE** :<br>3. Go to BO > Advanced Parameters > Backup page & **ERROR**<br>4. Go to BO > Advanced Parameters > Employees page > Profile tab & **ERROR**<br>5. Go to BO > Advanced Parameters > Employees page > Profile tab & Click on "Add a new profile" & **ERROR**<br>6. Go to BO > Advanced Parameters > Database page & Click on "Add new SQL query" & **ERROR**<br>7. Go to BO > Shop Parameters > Traffic & SEO page > Meta tab & Click on "Add new Meta" & **ERROR**<br>8. Go to BO > Shop Parameters > Traffic & SEO page > Search Engine tab & Click on "Add new Search Engine" & **ERROR**<br>9. Go to BO > International page > Language tab  & **ERROR**<br>10. Go to BO > International page > Tax tab  & Click on "Add new tax" & **ERROR**<br>11. Go to BO > Customer Service > Order Message page & Click on "Add a new order message" & **ERROR**<br><br>**AFTER** :<br>3. Go to BO > Advanced Parameters > Backup page & **NO ERROR**<br>4. Go to BO > Advanced Parameters > Employees page > Profile tab & **NO ERROR**<br>5. Go to BO > Advanced Parameters > Employees page > Profile tab & Click on "Add a new profile" & **NO ERROR**<br>6. Go to BO > Advanced Parameters > Database page & Click on "Add new SQL query" & **NO ERROR**<br>7. Go to BO > Shop Parameters > Traffic & SEO page > Meta tab & Click on "Add new Meta" & **NO ERROR**<br>8. Go to BO > Shop Parameters > Traffic & SEO page > Search Engine tab & Click on "Add new Search Engine" & **NO ERROR**<br>9. Go to BO > International page > Language tab  & **NO ERROR**<br>10. Go to BO > International page > Tax tab  & Click on "Add new tax" & **NO ERROR**<br>11. Go to BO > Customer Service > Order Message page & Click on "Add a new order message" & **NO ERROR**<br>

2021-09-02 13:54 UTC, matthieu-rolland submitted a review, later dismissed

2021-09-07 10:04 UTC, atomiix approved these changes, later dismissed

2021-09-08 09:39 UTC, PierreRambaud requested changes
As I said earlier, I don't understand why this part has been copy & paste on many templates instead of putting it in a dedicated template.
It happens what I told, when you have to change something, you have to change all related file.
Could you please improve it, put it in a ` multistore-infotip.html.twig`  file and call the macros inside this one?


File mutlistore-infotip.html.twig
```
{% import '@PrestaShop/Admin/macros.html.twig' as ps %}
{% block multistore_infotip %}
  {% if multistoreIsUsed %}{{ ps.infotip(multistoreInfoTip, true) }}{% endif %}
{% endblock %}
```

and include this template instead of duplicate

2021-09-13 09:12 UTC, atomiix submitted a review, later dismissed

2021-09-13 14:45 UTC, PierreRambaud approved these changes, later dismissed

2021-09-20 14:30 UTC, florine2623 commented
Hello @Progi1984 ,

Thanks for the PR !

I'm facing the same issue in  :
1. BO > Design > Theme & Catalog > **ERROR**
2. BO > Advanced Parameters > Experimental features > **ERROR**

Could you check ?
Thanks !

2021-09-24 07:42 UTC, Progi1984 commented
@florine2623 Fixed

2021-09-24 09:11 UTC, florine2623 commented
Hello @Progi1984 ,

Works like a charm, thanks for the update !

2021-09-24 15:10 UTC, NeOMakinG approved these changes

2021-10-04 15:41 UTC, matks approved these changes

2021-10-04 16:52 UTC, sowbiba approved these changes

2021-10-05 08:39 UTC, NeOMakinG approved these changes

2021-10-08 13:29 UTC, florine2623 commented
Hello @Progi1984 ,

Perfect ! Thanks a lot ! It is QA approved

2021-10-08 13:30 UTC, merged

2021-10-08 13:30 UTC, Progi1984 commented
Thanks @florine2623