Add missing override subfolder
PrestaShop/PrestaShop pull request #25774
Opened 2021-09-02 12:48 UTC by micka-fdz

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR add missing `override/controllers/front/listing` empty folder. When a module try to add override file in this missing folder, an error is returned during installation.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #14948.
| How to test?      | see issue
| Possible impacts? | -

2021-09-02 12:51 UTC, Progi1984 approved these changes

2021-09-02 13:54 UTC, matthieu-rolland approved these changes

2021-09-06 09:10 UTC, micka-fdz commented
Hi @Progi1984 @matthieu-rolland, it seems some UI tests failed. What should I do?

2021-09-06 09:12 UTC, Progi1984 commented
@micka-fdz We have problems with prestashop.com. Need some waiting days. Sorry.

2021-09-06 09:17 UTC, micka-fdz commented
@Progi1984 no problem, I thought the problem was on my side.

2021-09-06 09:23 UTC, matks requested changes
Hi !

Although the change might be valid, I think we're taking the wrong approach here.

I don't think we should add more and more empty folders in `override` folder. I think that PrestaShop should be able to, at runtime, create the needed folders for modules rather than defining them hardcoded in the software sources.

This PR will only fix 1 issue for 1 folder, maybe we should rather fix the override folder logic to handle any folder? 😊

2021-09-06 09:26 UTC, PierreRambaud requested changes
Hi,
Unfortunately, I'm not in favor of doing it. Otherwise, we have to list all possibles directories.
The best way to handle this case should be to automatically create a missing directory. Regarding how the actual override system works, we should be able to override anything. The fix should be done in Module.php where it tries to install the override.

2021-09-06 10:37 UTC, micka-fdz commented
Hi @matks @PierreRambaud,

I agree with both of you but I think we can do this in another PR.

The `listing` empty subfolder is the only one missing in `override/controllers/`.
In the same way, all empty subfolders are already create in `override/classes/`.

2021-09-06 12:01 UTC, matks commented
> The `listing` empty subfolder is the only one missing in `override/controllers/`.

Until we find another 😄 

> In the same way, all empty subfolders are already create in `override/classes/`.

Yes, we should remove all of them and let the system create the folders it needs :)

2021-09-06 13:02 UTC, micka-fdz commented
@matks I agree but I can't do this change alone.

I guess we have to add the automatic subfolder creation in the `installOverrides()` function of `Module.php`.

My PR was about a concrete bug fix, I think it should be merged until we can do better...

2021-09-06 13:07 UTC, Progi1984 commented
@micka-fdz I will make the fix. ;)

2021-09-06 13:08 UTC, micka-fdz commented
Thanks @Progi1984, I close this PR.

2021-09-06 13:08 UTC, closed without merging

2021-09-06 13:16 UTC, jf-viguier commented
hi guys,
override folder doesn't have to be writable here :
https://github.com/PrestaShop/php-ps-info/blob/0b12099c8ed1ff6ff652492955f4cb51b58f7cc0/phppsinfo.php#L50
I can't find a doc where this folder has to be writable. So I prefer all classes and overrides folders created at install time.

2021-09-06 13:39 UTC, jf-viguier commented
I've posted a PR here in the php-ps-info tool https://github.com/PrestaShop/php-ps-info/pull/21

For the issue, why not accept both ? fix and new folder ?

2021-09-06 13:50 UTC, micka-fdz commented
For information, it seems that recursive folder creation is already here but not working.
https://github.com/PrestaShop/PrestaShop/blob/1c52cccb5ba87606a35b037ed721ff5625ffdb08/classes/module/Module.php#L3165