Changelog for 1.7.7.8
PrestaShop/PrestaShop pull request #25778
Opened 2021-09-02 20:28 UTC by sowbiba

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Changelog for 1.7.7.8
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | -
| How to test?      | -
| Possible impacts? | -

2021-09-06 14:14 UTC, PierreRambaud approved these changes, later dismissed

2021-09-07 08:08 UTC, Progi1984 requested changes
Remaing one issue : https://github.com/PrestaShop/PrestaShop/projects/19

2021-09-09 08:48 UTC, Progi1984 approved these changes

2021-09-10 08:29 UTC, NeOMakinG approved these changes

2021-09-14 12:19 UTC, merged