BO - Fix bug saving product with combination
PrestaShop/PrestaShop pull request #25815
Opened 2021-09-08 10:09 UTC by SebBareyre

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | This bug is only in 1.7.7.7. Product with combination cannot be saved with french language if mode debug is enabled (because of "," decimal separator in ecotax calculation
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25761 and Fixes #25797 
| How to test?      | Please indicate how to best verify that this PR is correct.
| Possible impacts? | No impact

2021-09-09 08:08 UTC, Progi1984 commented on src/Adapter/Product/AdminProductWrapper.php
> +            $combinationValues['attribute_ecotax'] = str_replace(',', '.', $combinationValues['attribute_ecotax']);
I think a better solution would be to cast the attribute ecotax in float before the if. Isn't it ?

2021-09-13 12:39 UTC, PierreRambaud requested changes
Hi and thanks for your contribution.
Unfortunately, if there is something to be done about commas and dots, it has to be done in the frontend, not in the backend. The value sent to the backend has to be always in the right format.

2021-10-18 12:40 UTC, MatShir commented
Hi @SebBareyre, 
I would be nice to see your contribution into the next patch 😍
The next patch build is planned for the 5th of novemeber.

2021-12-03 17:01 UTC, matks commented
Hi,

Since we had no news from you for more than 30 days, I will follow [our guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests) and I'll close this pull request as it seems stale. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2021-12-03 17:01 UTC, closed without merging