Allow OrderStates changes to send emails located in modules
PrestaShop/PrestaShop pull request #25861
Opened 2021-09-11 19:16 UTC by theodiablo

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch           | develop
| Description      | With this change, now emails located inside modules can be sent if they are referenced in the OrderState.

### Before
You have a module with a custom email template located in /modules/my_module/mails/en/my_email.html
You create a new OrderState having $order_state->name = "New State" send_email = true, template = my_email, module_name = my_module, if you try to send an email when changing the order status to "New State", the email won't be sent, you will have an error:  Error - The following e-mail template is missing: my_email

### Now
You repeat the same steps, but the email gets sent correctly

| Type             | bug fix
| Category         | BO
| BC breaks        | no
| Deprecations     | no
| Fixed ticket     | no
| How to test      | Repeat the steps indicated in the description.
| Possible impacts | It shouldn't impact anyting else. Ideally, the "templates" field shown when editing an OrderState should also include the templates located inside the modules as well. This isn't included in this PR.

2021-09-13 15:39 UTC, matthieu-rolland commented
hello, thank you for your contribution

Please create an issue and link it to your description, so that PM and QA teams can follow it easily, thank you

2021-09-14 10:11 UTC, matks requested changes

2021-09-14 10:11 UTC, matks commented on classes/order/OrderHistory.php
> +                    $result['module_name'] ? _PS_MODULE_DIR_ . $result['module_name'] . '/mails/' : _PS_MAIL_DIR_,
If you do this, you _force_ the email to be in the modules directory. But some modules use the Core templates. This is why the UI tests are failing.

The idea is good, but a module sending an order state email must be able to choose whether the mail folder should _PS_MAIL_DIR_ or its own mail module. Like a fallback.

2021-11-15 15:09 UTC, PierreRambaud commented
Hi @theodiablo ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2021-11-15 15:09 UTC, closed without merging