Update webpack, babel and others webpack dependencies of new-theme
PrestaShop/PrestaShop pull request #25936
Opened 2021-09-20 15:38 UTC by NeOMakinG

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Webpack had some updates needed
| Type?             |  improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Can be tested by a dev, it's all about building the new-theme folder
| Possible impacts? | New-theme pages

2021-09-21 06:19 UTC, PierreRambaud approved these changes, later dismissed

2021-09-21 07:53 UTC, matks requested changes
ESLint not happy on BO theme
```

Oops! Something went wrong! :(

ESLint: 7.29.0

TypeError: Cannot read property 'value' of null
Occurred while linting /home/runner/work/PrestaShop/PrestaShop/admin-dev/themes/new-theme/js/app/pages/stock/mixins/product-desc.js:29
```

2021-09-22 16:30 UTC, matthieu-rolland approved these changes
lgtm

I also tested the PR on my local environment, new-theme was built without failure 👍

2021-09-27 15:03 UTC, PierreRambaud approved these changes

2021-09-27 15:03 UTC, merged

2021-09-27 15:03 UTC, PierreRambaud commented
Thank you @NeOMakinG