Hook fix
PrestaShop/PrestaShop pull request #25995
Opened 2021-09-24 19:50 UTC by yo7hli

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix actionCategoryUpdate hook triggering twice on toggling category display status.
| Type?             | bug fix
| Category?         | BO / CO
| BC breaks?        |  no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25870
| How to test?      | See issue for testing
| Possible impacts? | no

2021-09-27 06:48 UTC, PierreRambaud requested changes
We can't remove function without any side effects, the method can be deprecated if really not needed, but I think the problem is elsewhere, maybe in the module because the Category is properly updated twice:
https://github.com/PrestaShop/PrestaShop/issues/25870#issuecomment-927579432

2021-09-27 10:49 UTC, yo7hli reviewed
the hook call in Category->toggleStatus() is redundant since it's already called by the ObjectModel.
I figured that by removing the second hook call there's no functionality left in the extended class so it can be safely removed without any side effects.

2021-09-27 13:19 UTC, kpodemski approved these changes, later dismissed
It makes sense as `Category::update` executes this hook too.

2021-09-27 13:22 UTC, kpodemski commented
@PierreRambaud 

I think we can remove this method. The behavior is identical as `ObjectModel::toggleStatus` and:
- overrides will still work
- `$category->toggleStatus()` of course will still work

WDYT?

2021-09-27 15:00 UTC, PierreRambaud commented
> @PierreRambaud
> 
> I think we can remove this method. The behavior is identical as `ObjectModel::toggleStatus` and:
> 
> * overrides will still work
> * `$category->toggleStatus()` of course will still work
> 
> WDYT?

You're right, I missed the hook call in the update method, my bad :(

2021-09-27 15:00 UTC, PierreRambaud approved these changes

2021-09-27 15:01 UTC, kpodemski approved these changes

2021-09-27 15:48 UTC, matthieu-rolland approved these changes

2021-09-28 10:11 UTC, khouloudbelguith commented
Hi @yo7hli,

It is ok :heavy_check_mark: 
I checked: 
1. Crud categories
2. Create a category from the product page
3. Change status from the categories page and monitoring page
4. Check categories when multistore enabled

https://watch.screencastify.com/v/QH1LlHfaEX4pWB5rRwCu

Thanks!

2021-09-28 12:14 UTC, merged

2021-09-28 12:14 UTC, Progi1984 commented
Thanks @yo7hli & @khouloudbelguith