Configuration::updateValue using pSQL change to allow html to keep full given value
PrestaShop/PrestaShop pull request #26000
Opened 2021-09-25 10:10 UTC by tswfi

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | 
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | maybe?
| Deprecations?     | no
| Fixed ticket?     | Fixes #25967
| How to test?      | Try to save string `asdf <= qwer` in Invoices => Legal free text. Check that the full value is saved.
| Possible impacts? | If `<=` is not correctly escaped somewhere this might have some side effects.

This changes Configuration::updateValue to always call pSQL with "htmlOK" regardless of "isHtml" so it wont do strip_tags for the configuration value.

See longer explanation here: https://github.com/PrestaShop/PrestaShop/issues/25967#issuecomment-925076608

2021-09-27 06:41 UTC, PierreRambaud requested changes
I'm afraid of side effect if you change the Whole configuration behaviour. The fix has to be done only when using the desired configuration key, not them all.

2021-09-27 06:45 UTC, tswfi commented
> I'm afraid of side effect if you change the Whole configuration behaviour. The fix has to be done only when using the desired configuration key, not them all.

That's kinda difficult as module developers can create new keys. Or are you suggesting a new argument `raw=false` for the updateValue?

I'm guessing test suite is not yet on a level that would find all the possible side effects?

2021-09-27 06:56 UTC, matks commented
> That's kinda difficult as module developers can create new keys. Or are you suggesting a new argument `raw=false` for the updateValue?
> 
> I'm guessing test suite is not yet on a level that would find all the possible side effects?

Indeed test suite is far from this :( . We have x400% its size in 3 years but there's a huge test debt to repay.

2021-09-27 07:02 UTC, tswfi commented
So a new argument (default to false) (and unit tests :) ?

2021-10-04 14:41 UTC, PierreRambaud commented
> So a new argument (default to false) (and unit tests :) ?

I don't know, but changing the whole behavior behind this without being able to be sure it will not break all the community module isn't something I'm ready to merge :sweat:

2021-10-09 13:19 UTC, tswfi commented
Adding a new parameter for the old configuration class is not worth it. 
Closing this and will close the issue also.

2021-10-09 13:19 UTC, closed without merging