replace die() with an Exception - fix #26113
PrestaShop/PrestaShop pull request #26114
Opened 2021-10-05 13:15 UTC by SebSept

more developer friendly when $module_name is empty.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch           | develop / 1.7.8.x / 1.7.7.x
| Description      | replace die() with an Exception
| Type             | improvement
| Category         | FO
| BC breaks        |  no
| Deprecations     |  no
| Fixed ticket     | Fixes #26113
| How to test      | Instanciate a Module Controller in command line or Admin context.
| Possible impacts | None I guess

2021-10-05 13:25 UTC, matks reviewed
Hello, I am 99% sure that QA team will need a scenario a bit more detailed to be able to explore the PR 😉  also can you fill all lines of the PR table?

Like `branch`

2021-10-05 14:14 UTC, SebSept commented
I can understand this.
"Branch" is completed since, I fixed it on an old 1.7.5 and the die() is still present on develop.

My scenario is a bit complex. I'll provide it if needed (100% ;) )
 
At this point, I search the error string then found this die(). I replaced it with an exception then I figured out my error. (then solved it easily thanks to the stack trace).

2021-10-05 14:15 UTC, kpodemski commented
@matks I think it's for the developer QA

2021-10-05 14:17 UTC, kpodemski commented on classes/module/Module.php
> +                throw new \Exception(Tools::displayError(Context::getContext()->getTranslator()->trans('%1$s is not a valid module name.', [Tools::safeOutput($module_name)], 'Admin.Modules.Notificati
```suggestion
                throw new \InvalidArgumentException(Tools::displayError(Context::getContext()->getTranslator()->trans('%1$s is not a valid module name.', [Tools::safeOutput($module_name)], 'Admin.Modules.Notification')));
```

2021-10-07 09:40 UTC, matthieu-rolland reviewed
one question

2021-10-07 09:40 UTC, matthieu-rolland commented on classes/module/Module.php
> +                throw new \InvalidArgumentException(Tools::displayError(Context::getContext()->getTranslator()->trans('%1$s is not a valid module name.', [Tools::safeOutput($module_name)], 'Admin.Mod
Is this exception caught somewhere in your use case ?

2021-10-07 10:21 UTC, SebSept commented on classes/module/Module.php
> +                throw new \InvalidArgumentException(Tools::displayError(Context::getContext()->getTranslator()->trans('%1$s is not a valid module name.', [Tools::safeOutput($module_name)], 'Admin.Mod
It's not catched.
And that's good for development, I can't miss it.

2021-10-07 10:26 UTC, SebSept commented
To add more context : 
In my use, I had a class that generate Context objects (*).
It should be instantiated with a front controller (Product)
My error was that I provided a ModuleController.
With this Exception instead of die() I can figure my error easily.

(*) :  for early caching smarty views, before a client browse the site + deletion on changes.

2021-10-07 12:35 UTC, matks requested changes
Hi @SebSept I agree this `die()` is nasty but your solution needs improvement for me.

- InvalidArgumentException is supposed to be thrown when an argument is not of the expected type, like PHP is given an integer instead of a float or a string.
- What should we do when `$module_name` is not valid? current code dies, and that's bad. But should we throw an exception or should we simply `return` silently or even something else?

2021-10-07 12:37 UTC, sowbiba commented on classes/module/Module.php
> +                throw new \InvalidArgumentException(Tools::displayError(Context::getContext()->getTranslator()->trans('%1$s is not a valid module name.', [Tools::safeOutput($module_name)], 'Admin.Mod
Just doing Tools::displayError is enough as it throws an PrestaShopException. However, I think you didn't choose the good exception type

2021-10-07 12:39 UTC, kpodemski commented on classes/module/Module.php
> +                throw new \InvalidArgumentException(Tools::displayError(Context::getContext()->getTranslator()->trans('%1$s is not a valid module name.', [Tools::safeOutput($module_name)], 'Admin.Mod
It was me. InvalidArgumentException seemed to be better.

I think that you're right, and `Tools::displayError` should be enough 🤔 

Didn't you see a stack trace with the debug mode @SebSept?

2021-10-07 12:49 UTC, kpodemski commented
> Hi @SebSept I agree this `die()` is nasty but your solution needs improvement for me.
> 
> * InvalidArgumentException is supposed to be thrown when an argument is not of the expected type, like PHP is given an integer instead of a float or a string.
> * What should we do when `$module_name` is not valid? current code dies, and that's bad. But should we throw an exception or should we simply `return` silently or even something else?

@matks maybe we should remove the `die`, leave the rest for the `Tools::displayPrice` and `return false;`

2021-10-14 15:58 UTC, SebSept commented
I just realized that the PrestaShop version I was working with had this code :
```die(Context::getContext()->getTranslator()->trans('%1$s is not a valid module name.', array(Tools::safeOutput($module_name)), 'Admin.Modules.Notification'));```
So no stack trace.

But the current develop branch has a Tool::displayError() inside the die(), so a stack trace is available.
So nothing needs to be fixed !
My bad, sorry the wast of time!

2021-10-14 15:58 UTC, closed without merging

2021-10-14 16:06 UTC, SebSept commented on classes/module/Module.php
> +                throw new \InvalidArgumentException(Tools::displayError(Context::getContext()->getTranslator()->trans('%1$s is not a valid module name.', [Tools::safeOutput($module_name)], 'Admin.Mod
I did not, it was because an oudated prestashop install.
it's ok on developp branch.