Fix currency error
PrestaShop/PrestaShop pull request #26180
Opened 2021-10-10 10:06 UTC by Gitdyr

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Do no include deleted currencies. A deleted entry may mess up the currency in 1.7.7.8
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | #26181
| How to test?      | Change a currency in an old version of PrestaShop. The shop was migrated from 1.2 -> 1.3 -> 1.4 -> 1.5 -> 1.6 -> 1.7.6 -> 1.7.7.8. E.g. changed the precision to 4. The old (deleted) precision will be used.
| Possible impacts? | It seem this has been changed earlier on. There was an option to include deleted entries but it has been removed. I wonder why the deleted entries were included.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/26180)

2021-10-17 20:05 UTC, matks commented on src/Adapter/Currency/CurrencyDataProvider.php
> -        $currencyId = Currency::getIdByIsoCode($isoCode, 0, false, true);
I see you modify `$includeDeleted` parameter value from true to false. (see https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Currency.php#L886)

I can see that indeed this solves your problem, because deleted currencies are ignored. But this change will affect **all code** in PrestaShop that uses `getCurrencyByIsoCode()` and today does not ignore deleted currencies.

This change seems too big for me. I wish we could rather ignore deleted currencies _only for the usecase related to your bug_. This function is very generic, probably used by a lot of other classes, so modifications will carry huge side-effects.

2021-10-22 06:03 UTC, Gitdyr commented on src/Adapter/Currency/CurrencyDataProvider.php
> -        $currencyId = Currency::getIdByIsoCode($isoCode, 0, false, true);
I agree. Apparently the integration tests failed.

I can see in the history that getCurrencyByIsoCode() was changed two years ago. Back then the parameters were:

` public function getCurrencyByIsoCode($isoCode, $idLang = null, $includeDeleted = false)`

which made sense. I wonder why it was changed?

2021-11-12 22:10 UTC, matks commented on src/Adapter/Currency/CurrencyDataProvider.php
> -        $currencyId = Currency::getIdByIsoCode($isoCode, 0, false, true);
Are you sure @Gitdyr ? I see a `$includeDeleted` parameter was added in commit https://github.com/PrestaShop/PrestaShop/commit/190a6f317bf5698cfee62e1fba6fd968e2a39159 but removed in the same PR in another commit https://github.com/PrestaShop/PrestaShop/commit/c5e2139102d7d97cdc5badd3b2f86fbba7b5e66e#diff-5dfa340dc558cffb271393845734445f9cf93c9217f5386d4785bcb2ef62852e

2021-11-13 17:35 UTC, Gitdyr commented on src/Adapter/Currency/CurrencyDataProvider.php
> -        $currencyId = Currency::getIdByIsoCode($isoCode, 0, false, true);
I do not have the overview of how getCurrencyByIsoCode() is used. My change was definitely not doable as it appears the regression test fails.

2021-12-03 10:55 UTC, matks requested changes

2021-12-03 10:55 UTC, matks commented on src/Adapter/Currency/CurrencyDataProvider.php
> -        $currencyId = Currency::getIdByIsoCode($isoCode, 0, false, true);
Hi @Gitdyr thanks for the answer.

As the CI is not happy and your change would affect all code in PrestaShop that uses `getCurrencyByIsoCode()` I think we cannot merge this as it is. I close the PR consequently.

If you find a better way to fix the issue - I think there must be one 😺  - and submit it in another PR I'll be happy to review it. Thank you!

2021-12-03 10:55 UTC, closed without merging