Be able to instantiate PDF renderer with different language than in Context
PrestaShop/PrestaShop pull request #26234
Opened 2021-10-13 12:20 UTC by Hlavtox

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | There was some smelly code that switched context language to generate a PDF. You can now generate PDFs in desired language configuration, if it's missing, it will still take the context config.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | Yes, for overrides - If somebody overrides PDFGenerator and does not have the third parameter in constructor.
| Deprecations?     | no
| Fixed ticket?     | - 
| How to test?      | Make an order and see that PDF generates fine.
| Possible impacts? | -

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/26234)

2021-10-13 13:12 UTC, kpodemski commented on classes/pdf/PDF.php
> +    public function __construct($objects, $template, $smarty, $orientation = 'P', $language = null)
@Hlavtox this is breaking change

2021-10-13 13:13 UTC, Hlavtox commented on classes/pdf/PDF.php
> +    public function __construct($objects, $template, $smarty, $orientation = 'P', $language = null)
@kpodemski I thought it won't be, if I fallback to the context language as before, no?

2021-10-13 13:19 UTC, kpodemski commented on classes/pdf/PDF.php
> +    public function __construct($objects, $template, $smarty, $orientation = 'P', $language = null)
@Hlavtox for overrides it is, just put it into the description, and edit the template 👍

2021-10-13 13:36 UTC, Hlavtox commented on classes/pdf/PDF.php
> +    public function __construct($objects, $template, $smarty, $orientation = 'P', $language = null)
Description updated :-)

2021-10-13 14:26 UTC, matthieu-rolland commented on classes/PaymentModule.php
> +                            $file_attachment['content'] = $pdf->render(false);
it's usually a good practice to declare an array before using it

```suggestion
                            $file_attachment = [];
                            $file_attachment['content'] = $pdf->render(false);
```

(or did I miss a previous declaration?)

2021-10-13 14:28 UTC, matthieu-rolland reviewed
I made a tiny improvement suggestion, but otherwise its' LGTM for me 👍

2021-10-13 15:50 UTC, Hlavtox commented on classes/PaymentModule.php
> +                            $file_attachment['content'] = $pdf->render(false);
@matthieu-rolland You didn't ;-)

2021-10-13 15:50 UTC, Hlavtox commented
@matthieu-rolland Suggestion applied, thanks! 🚀

2021-10-14 07:43 UTC, tegbessou commented
I can't approve, this PR. But I don't see any problem with this

2021-10-14 11:31 UTC, kpodemski commented on classes/PaymentModule.php
> -                            $this->context->language = $orderLanguage;
I'm not sure about this one. I would suggest checking value of `$this->context->language` in this hook:

`Hook::exec('actionPDFInvoiceRender', ['order_invoice_list' => $order_invoice_list]);`

before and after the change.

@jolelievre can probably confirm that dealing with the context is hard ;D

2021-10-25 14:44 UTC, PierreRambaud commented on classes/PaymentModule.php
> -                            $this->context->getTranslator()->setLocale($currentLanguage->locale);
I think this one needs to be moved inside the PDF class when a language is set. Or we have to be sure it's working as expected without locale settings.

2021-10-25 14:45 UTC, Progi1984 commented on classes/pdf/PDF.php
> +    public function __construct($objects, $template, $smarty, $orientation = 'P', $language = null)
```suggestion
    public function __construct($objects, $template, $smarty, $orientation = 'P', Language $language = null)
```

2021-10-25 14:46 UTC, Progi1984 commented on classes/pdf/PDF.php
> +    public function __construct($objects, $template, $smarty, $orientation = 'P', $language = null)
And could you add PHPDoc, please?

2021-10-25 14:46 UTC, Progi1984 commented on classes/pdf/PDFGenerator.php
> +    public function __construct($use_cache = false, $orientation = 'P', $language = null)
```suggestion
    public function __construct($use_cache = false, $orientation = 'P', Language $language = null)
```

And could you add PHPDoc, please ?

2021-10-25 14:47 UTC, Progi1984 reviewed
Two small comments for type hinting

2021-10-25 14:49 UTC, Hlavtox commented on classes/PaymentModule.php
> -                            $this->context->getTranslator()->setLocale($currentLanguage->locale);
@PierreRambaud I think it's not needed. If I didn't miss anything, the lang is passed to the class only because of these things.

```
$this->setRTL($language->is_rtl);
$this->setFontForLang($language->iso_code);
```

2021-10-25 15:08 UTC, PierreRambaud commented on classes/PaymentModule.php
> -                            $this->context->getTranslator()->setLocale($currentLanguage->locale);
It also depends if some templates are used inside the PDF and how modules are using it ^^
We can't "think", we have to be sure, otherwise, keep the old behavior by security ^^

2021-10-26 08:06 UTC, Hlavtox commented
@Progi1984 @PierreRambaud @matthieu-rolland 

I just checked all PDF templates and found following:
- No use of Context directly.
- All displayPrice functions use specified currency from order or from payment collection.
- Only problem I can see is dateFormat for example here. Tools gets the date format from context and id_lang is deprecated in that function. Is there a replacement? Or can we pass a presented order to the pdf template? 
https://github.com/PrestaShop/PrestaShop/blob/a464cdc48be8ed34983b4cc468a4845d6b1cbf06/pdf/invoice.summary-tab.tpl#L39

2021-11-17 16:22 UTC, Hlavtox commented
@Progi1984 @PierreRambaud @matthieu-rolland

Just found out that invoices contain nonsense characters when BO language is not correct and the issue is open 2018 (WTF?) - https://github.com/PrestaShop/PrestaShop/issues/9817 

However (although I opened this for completely different reason 😄) the issue should be fixed with my PR and just passing $order-currency.

Can we pls move it forward so the invoices are working correctly in v8? I think this is very important!

2021-11-17 16:28 UTC, Hlavtox commented
What to do in a case of collection generation where every credit slip could be in different language? https://github.com/PrestaShop/PrestaShop/blob/ad181f7fb89dea67dfebba779a6440854baa6d5b/src/Adapter/PDF/CreditSlipPdfGenerator.php#L94

2021-12-06 11:04 UTC, eternoendless requested changes

2021-12-06 11:04 UTC, eternoendless commented on classes/PaymentModule.php
> -                            $this->context->getTranslator()->setLocale($currentLanguage->locale);
If you don't change the global translator to the desired language using this:
```php
$this->context->getTranslator()->setLocale($currentLanguage->locale);
```
...then templates will continue being translated in the contextual language. The same goes for PDF, even if you provide a language, if the contextual translator is not switched to the target language, the generated content will be translated using the current language (as you can see, for example, [here](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/pdf/HTMLTemplateInvoice.php#L89))

2021-12-06 11:31 UTC, Hlavtox commented on classes/PaymentModule.php
> -                            $this->context->getTranslator()->setLocale($currentLanguage->locale);
@eternoendless Hmmm, you are right. 

So, the biggest hassle now -> Can we translate to different lang than in context? If not, is it hard to do?

Also, what about **getComputingPrecision()**? We need to get precision of the objects currency, not the one in context. 🤔

2021-12-06 15:02 UTC, eternoendless commented on classes/PaymentModule.php
> -                            $this->context->getTranslator()->setLocale($currentLanguage->locale);
> Can we translate to different lang than in context?

When talking Smarty, it can't be done without significant refactoring. The `l()` smarty function is [set up globally](https://github.com/PrestaShop/PrestaShop/blob/develop/config/smarty.config.inc.php#L85) to `smartyTranslate()`, which is defined [here](https://github.com/PrestaShop/PrestaShop/blob/develop/config/smartyfront.config.inc.php#L158) for FO and [here](https://github.com/PrestaShop/PrestaShop/blob/develop/config/smartyadmin.config.inc.php#L58) for the BO. As you can see, both use the contextual translator.

This can be worked around by changing the translator's locale for the duration of the process you need to perform in a different language (in this case, creating the PDF), and setting it back to the previous value afterwards. You can do the same with the context's locale so that you get the appropriate price formatting for the desired locale as well.

2022-02-02 10:52 UTC, PierreRambaud commented
Hi @Hlavtox ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2022-02-02 10:52 UTC, closed without merging

2022-03-02 04:14 UTC, woosa2020 commented
Hi All,
I am new to PrestaShop and facing the same issue with non-standard characters in invoice. I updated these 3 files however I am still seeing them as rectangles.  iso code for the language I am facing is 'my' which I added into PDFGenerator.php

Please help
Thank much in advance

2022-03-06 00:29 UTC, woosa2020 commented
> 

Any Suggestion? Appreciate your help. Thanks