Configuring issue templates for bugs
PrestaShop/PrestaShop pull request #26247
Opened 2021-10-14 09:40 UTC by marionf

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Configuring issue templates for bugs
| Type?             | improvement
| How to test?      | Try to create a new bug report

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/26247)

2021-10-14 09:50 UTC, Progi1984 submitted a review, later dismissed

2021-10-14 09:54 UTC, kpodemski commented on .github/ISSUE_TEMPLATE/1_bug_report.yml
> +description: Report an issue in PrestaShop or in one of the native modules. DO NOT disclose security issues here, contact security@prestashop.com instead!
```suggestion
description: Report an issue in PrestaShop or one of the native modules. DO NOT disclose security issues here, contact security@prestashop.com instead!
```

2021-10-14 09:54 UTC, kpodemski commented on .github/ISSUE_TEMPLATE/1_bug_report.yml
> +      description: Take a couple minutes to help our maintainers work faster.
```suggestion
      description: Take a couple of minutes to help our maintainers work faster.
```

2021-10-14 09:54 UTC, kpodemski commented on .github/ISSUE_TEMPLATE/1_bug_report.yml
> +          required: true
```suggestion
          required: true
```

2021-10-14 09:54 UTC, kpodemski commented on .github/ISSUE_TEMPLATE/1_bug_report.yml
> +      required: false
```suggestion
      required: false
```

2021-10-14 09:54 UTC, kpodemski commented on .github/ISSUE_TEMPLATE/1_bug_report.yml
> +      required: false
```suggestion
      required: false
```

2021-10-14 10:18 UTC, eternoendless commented
Could you please share a screenshot of what it looks like?

2021-10-14 11:35 UTC, kpodemski commented
@eternoendless you can preview it here: https://github.com/PrestaShop/PrestaShop/blob/1e6ed4c138e4f912796c24de6670ee529eb26f7c/.github/ISSUE_TEMPLATE/1_bug_report.yml

2021-10-14 12:17 UTC, marionf commented
![Capture d’écran 2021-10-14 à 14 36 06](https://user-images.githubusercontent.com/13449658/137318566-c5018189-1451-4560-b3ee-4b0b81a19674.png)

![Capture d’écran 2021-10-14 à 14 13 13](https://user-images.githubusercontent.com/13449658/137315442-1a821490-05d3-40fb-b005-0d413fc1bd0f.png)

2021-10-14 12:31 UTC, micka-fdz commented
Hi. Maybe we could replace `vX.X.X` with `X.X.X` in placeholders to simplify user process.

2021-10-14 12:48 UTC, marionf commented
@micka-fdz 
It's just a placeholder and an example, you can enter `vX.X.X` or `X.X.X`, it doesn't matter ;)

2021-10-14 14:11 UTC, micka-fdz commented
Yes @marionf but I think it's better to show an example of the simplest case.
Moreover, it allows to be uniform on all the fields (see last field placeholder).

2021-10-15 12:24 UTC, eternoendless commented on .github/ISSUE_TEMPLATE/1_bug_report.yml
> +        Thanks for taking the time to fill out this bug report!
```suggestion
        Thank you for taking the time to fill out this bug report. Please take the time to provide as much detail as possible. Following our [bug report guidelines](https://devdocs.prestashop.com/1.7/contribute/contribute-reporting-issues/#best-practices-for-writing-an-issue) will help maintainers qualify your report faster.
```

2021-10-15 12:25 UTC, eternoendless commented on .github/ISSUE_TEMPLATE/1_bug_report.yml
> +      description: Take a couple of minutes to help our maintainers work faster.
```suggestion
```
Hum, perhaps this part can be worded differently or left out?

2021-10-15 12:25 UTC, eternoendless commented on .github/ISSUE_TEMPLATE/1_bug_report.yml
> +          required: true
Is this really necessary?

2021-10-15 12:27 UTC, eternoendless commented on .github/ISSUE_TEMPLATE/1_bug_report.yml
> +        - label: I have [searched](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue) for duplicate or closed issues
```suggestion
        - label: I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue) and found no previous report of this bug.
```

2021-10-15 12:28 UTC, eternoendless commented on .github/ISSUE_TEMPLATE/1_bug_report.yml
> +      description: A clear and concise description of what went wrong.
```suggestion
      description: What went wrong?
```

2021-10-15 12:28 UTC, eternoendless commented on .github/ISSUE_TEMPLATE/1_bug_report.yml
> +      required: false
I'd put this part before steps to reprodue

2021-10-15 12:32 UTC, eternoendless commented on .github/ISSUE_TEMPLATE/1_bug_report.yml
> +      label: What version of PrestaShop are you using?
```suggestion
      label: PrestaShop version(s) where the bug happened
```

2021-10-15 12:32 UTC, eternoendless commented on .github/ISSUE_TEMPLATE/1_bug_report.yml
> +      required: false
IMO all these can be merged in a single field

2021-10-15 13:02 UTC, marionf commented on .github/ISSUE_TEMPLATE/1_bug_report.yml
> +          required: true
Yes, I think it's important to avoid aggressiveness

2021-10-15 13:04 UTC, marionf commented on .github/ISSUE_TEMPLATE/1_bug_report.yml
> +      required: false
I think it makes more sense to first describe the bug, then the steps to reproduce it, and lastly describe the expected behavior

2021-10-15 13:10 UTC, marionf commented on .github/ISSUE_TEMPLATE/1_bug_report.yml
> +      required: false
I find it more readable with different fields, it forces people to read and to put the right information in the right place
It will also be more readable when reproducing the issues

2021-10-15 14:06 UTC, eternoendless commented on .github/ISSUE_TEMPLATE/1_bug_report.yml
> +          required: true
In that case
```suggestion
        - label: I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
          required: true
```

2021-10-15 14:26 UTC, eternoendless commented on .github/ISSUE_TEMPLATE/1_bug_report.yml
> +      required: false
IMO it's more logical this way:

1. What happened (perhaps we should put screenshots here now that I think of it)
2. Why do you think it's the wrong behavior (what you expected to happen instead)
3. Details on how to reproduce (sometimes it's very straightforward)
4. Environment details

Example

1. The product price is X in these circumstances
2. The product price should be Y because X + Z = Y
3. Go to product page, see bad price
4. PrestaShop x.y.z (php version is irrelevant)

2021-10-15 14:26 UTC, eternoendless commented on .github/ISSUE_TEMPLATE/1_bug_report.yml
> +      required: false
Not all fields are valid all the time, but they will all be present in the bug report

2021-10-18 09:47 UTC, marionf commented on .github/ISSUE_TEMPLATE/1_bug_report.yml
> +      required: false
I am not convinced, I found it more logical this way: 
1. What happened 
2. Details on how to reproduce 
3. What you expected to happen
4. Environment details

But I don't want to lose time with such detail, so let's do as you suggested

2021-10-18 09:52 UTC, sowbiba commented on .github/ISSUE_TEMPLATE/1_bug_report.yml
> +        Thank you for taking the time to fill out this bug report. Please take the time to provide as much detail as possible. Following our [bug report guidelines](https://devdocs.prestashop.com/1.7
```suggestion
        Thank you for taking the time to fill out this bug report. Please take the time to provide as much details as possible. Following our [bug report guidelines](https://devdocs.prestashop.com/1.7/contribute/contribute-reporting-issues/#best-practices-for-writing-an-issue) will help maintainers qualify your report faster.
```

2021-10-18 10:04 UTC, PierreRambaud requested changes
Hi @marionf  and thanks for what you did.
But unfortunately, we have to close your pull request. 
Could you please use your fork instead?

2021-10-18 10:04 UTC, closed without merging