Fix language dropdown in attribute creation title creation
PrestaShop/PrestaShop pull request #26255
Opened 2021-10-14 13:29 UTC by marwachelly

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | when we resize the window the language dropdown is not well displayed
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/26252
| How to test?      | resize the window the language dropdown should be well displayed
| Possible impacts? | /

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/26253)

2021-10-15 05:57 UTC, Hlavtox commented on admin-dev/themes/default/scss/partials/_forms.scss
> +      min-width: 62px;
Please try to use `white-space: nowrap;`. If we change a font or it's size, your solution might no longer work.

2021-10-18 09:21 UTC, matthieu-rolland approved these changes
lgtm

2021-10-18 09:42 UTC, sowbiba commented
@marwachelly you are supposed to fork the repo and create a branch on your own fork

https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/

2021-10-18 09:47 UTC, sowbiba reviewed
Contribution seems good to me. Will approve it when you reopen the PR with a fork ;)

2021-10-18 10:02 UTC, PierreRambaud requested changes
Hi @marwachelly I'm sorry but we have to close your pull request.
Could you please use the fork process next time?

2021-10-18 10:02 UTC, closed without merging

2021-10-19 14:57 UTC, marwachelly commented
Hi @sowbiba, @PierreRambaud,

I added a new PR: https://github.com/PrestaShop/PrestaShop/pull/26328

Thanks!