Remove deprecated admin/ajax-tab.php
PrestaShop/PrestaShop pull request #26294
Opened 2021-10-18 15:36 UTC by eternoendless

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Removed deprecated admin-dev/ajax.php file
| Type?             | improvement
| Category?         | CO
| BC breaks?        | yes - the file has been deleted
| Deprecations?     | no
| Fixed ticket?     | N/A
| How to test?      | Quite a lot of requests have changed in obscure parts of the software that I'm unable to track, but they all changed the same per convention, so we can guess that if it works for 1, it works for N, right?
| Possible impacts? | This changes how some Ajax requests are made, so they either work, or they don't. Read below 

## Proof it works for 1!

Go to Customer Settings > Groups, edit one, then click on "add category discount". If the tree loads, then that's one request I didn't mess up!

<img width="1514" alt="Screenshot 2021-10-18 at 17 16 49" src="https://user-images.githubusercontent.com/1009343/137762112-17f41a21-2f01-4e14-9b57-9d31a73fdda3.png">

## Other impacted areas in BO that I didn't test but should be working

- Upload a logo in the carrier wizard
- Load stuff in the cart rules management part
- Mark customer thread as read
- Forgot password form in login can be sent
- Product category tree loads in... somewhere

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/26294)

2021-10-18 15:46 UTC, Progi1984 commented on js/admin/login.js
> +			url: 'index.php' + '?rand=' + new Date().getTime(),
```suggestion
			url: 'index.php?rand=' + new Date().getTime(),
```

2021-10-18 15:46 UTC, Progi1984 commented on js/admin/login.js
> +			url: 'index.php' + '?rand=' + new Date().getTime(),
```suggestion
			url: 'index.php?rand=' + new Date().getTime(),
```

2021-10-18 15:47 UTC, Progi1984 reviewed
A small feedback, my boss

2021-10-23 10:45 UTC, PierreRambaud submitted a review, later dismissed

2021-10-25 06:34 UTC, Progi1984 submitted a review, later dismissed

2021-10-26 15:45 UTC, atomiix commented
@eternoendless can you rebase your PR, please? :)

2021-10-27 13:03 UTC, eternoendless commented
Rebased

2021-10-27 13:49 UTC, matthieu-rolland submitted a review, later dismissed

2021-11-02 16:19 UTC, Progi1984 submitted a review, later dismissed

2021-11-16 16:54 UTC, khouloudbelguith commented
Hi @eternoendless,

Could you please check the Conflicting files?

Thanks!

2021-11-30 15:47 UTC, eternoendless commented
Rebased

2021-12-03 14:37 UTC, matks approved these changes
Change are OK for me.

ping @Quetzacoalt91 is this something that might be an issue for modules ?

2021-12-03 15:23 UTC, Quetzacoalt91 commented
> ping @Quetzacoalt91 is this something that might be an issue for modules ?

I don't have any example in mind but as this has been deprecated and you're going to remove it for the next major, I guess we're fine if the documentation remind the community about this deletion.

2021-12-06 16:30 UTC, Progi1984 requested changes
Could you document your BC Break, please ?

After that, it will be an approval for me.

2021-12-06 16:57 UTC, eternoendless commented
Done in description @Progi1984

2021-12-07 11:18 UTC, PierreRambaud approved these changes

2021-12-07 17:23 UTC, khouloudbelguith commented
Hi @eternoendless,

It is ok :heavy_check_mark: 
https://watch.screencastify.com/v/fW2K3ImV4mBfrEoIwgLq
https://watch.screencastify.com/v/5ZgBlZm6jBsBNy24IFtK

I tried to make different cases.

- Go to Customer Settings > Groups, edit one, then click on "add category discount".  => ok
- Upload a logo in the carrier wizard > ok (edit a carrier & add new carrier)
- Load stuff in the cart rules management part (create a cart rule from BO & from Order > Add new order)
- Mark customer thread as read (make a forward to another employee)
- Forgot password form in login can be sent (tested from BO & FO) 
- Product category tree loads in... somewhere (I checked FO > category page > category_tree module / BO > Catalog > Products > select & unselect a category)


Thanks!

2021-12-08 07:45 UTC, Progi1984 approved these changes

2021-12-08 07:46 UTC, merged

2021-12-08 07:46 UTC, Progi1984 commented
Thanks @eternoendless & @khouloudbelguith