Remove deprecated methods/params into Cart
PrestaShop/PrestaShop pull request #26302
Opened 2021-10-18 20:21 UTC by PrestaEdit

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove deprecated in Cart
| Type?             | improvement 
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #26293.
| How to test?      | Nothing to test.
| Possible impacts? | BC Break.

**:notebook: BC Breaks**
* Removed const : `Cart::ONLY_PRODUCTS_WITHOUT_SHIPPING`
* Removed method : `Cart::getTaxesAverageUsed()`
* Removed method : `Cart::containsProduct()`
* Removed method : `Cart::simulateCarriersOutput()`
* Removed method : `Cart::getOrderShippingCost()`
* Removed method : `Cart::checkDiscountValidity()`
* Removed method : `Cart::deletePictureToProduct()`
* Removed method : `Cart::addExtraCarriers()`
* Removed parameters : `$exclusive`, in `Cart::isAllProductsInStock()`

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/26302)

2021-10-19 09:01 UTC, tegbessou approved these changes
Thank you for your PR, nice work! Seems to be good IMO

2021-10-20 09:10 UTC, Progi1984 requested changes
@PrestaEdit Could you fix CI and PHPStan errors ?

2021-10-29 13:18 UTC, matthieu-rolland reviewed
one feedback

2021-10-29 13:18 UTC, matthieu-rolland commented on classes/Cart.php
> +    public function isAllProductsInStock($ignoreVirtual = false)
you remove this parameter but the variable is still used in the function

below there's a condition, `if (!$exclusive)` followed by `elseif ($exclusive)`, if this parameter must really disappear you need to remove these conditions and define what is the default behavior

2021-10-29 13:20 UTC, PrestaEdit commented on classes/Cart.php
> +    public function isAllProductsInStock($ignoreVirtual = false)
Good catch, don't know why I'm missing it.

Mmmmmh. As the default is "false" and it's deprecated, wdyt ? Do we need to keep only the false part, maybe ?

2021-11-03 09:18 UTC, matthieu-rolland commented on classes/Cart.php
> +    public function isAllProductsInStock($ignoreVirtual = false)
yes, if we remove this optional parameter, we snould keep the default behavior, which is `$eclusive = false` 👍

2021-12-03 10:22 UTC, PierreRambaud commented
Hi @PrestaEdit ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2021-12-03 10:22 UTC, closed without merging