Remove deprecated methods into taxes related classes
PrestaShop/PrestaShop pull request #26324
Opened 2021-10-19 09:18 UTC by PrestaEdit

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove deprecated in Tax related classes
| Type?             | improvement 
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #26293.
| How to test?      | Nothing to test.
| Possible impacts? | BC Break.

**:notebook: BC Breaks**
* Removed method : `Tax::getProductTaxRateViaRules()`
* Removed method : `TaxRule::deleteTaxRuleByIdCounty()`
* Removed method : `TaxRulesGroup::getTaxesRate()`
* Removed method : `TaxRulesGroup::getTaxes()`

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/26324)

2021-10-20 07:37 UTC, tegbessou approved these changes
Thank you for your PR! IMO all is good

2021-10-20 07:42 UTC, Progi1984 approved these changes

2021-10-20 08:51 UTC, Progi1984 requested changes
@PrestaEdit 

Use found in 
- https://github.com/PrestaShop/PrestaShop/blob/develop/classes/tax/Tax.php#L247
- https://github.com/PrestaShop/PrestaShop/blob/develop/classes/tax/TaxRulesGroup.php#L275
- https://github.com/PrestaShop/PrestaShop/blob/develop/controllers/admin/AdminTaxRulesGroupController.php#L327

2021-10-20 08:52 UTC, PrestaEdit commented
Hi @Progi1984 ,

Theses founds are also removed inside this PR, isn't it ?

2021-10-20 09:16 UTC, Progi1984 commented
@PrestaEdit You're right except the last one.

2021-10-20 09:17 UTC, PrestaEdit commented
But the last one use the Tax class, and it's not removed inside this one.

2021-10-20 10:02 UTC, matthieu-rolland approved these changes

2021-10-20 15:35 UTC, Progi1984 approved these changes

2021-11-08 13:55 UTC, PierreRambaud approved these changes

2021-11-15 15:58 UTC, merged

2021-11-15 15:58 UTC, Progi1984 commented
Thanks @PrestaEdit