Fixed Modern email theme for RTL languages
PrestaShop/PrestaShop pull request #26340
Opened 2021-10-20 13:59 UTC by mparvazi

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fixes text align and text direction in Modern email template for RTL languages.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26177
| How to test?      | Email template must be regenerate base on Modern theme and a RTL language.
| Possible impacts? | -

**Screenshots**

Generated email template:

<img src="https://user-images.githubusercontent.com/85633460/138106905-aa29820f-c6ee-4323-b571-99455f96c14b.png" width="600"/>

Expected email template:

<img src="https://user-images.githubusercontent.com/85633460/138106941-0ae75c86-23f1-49b5-8b02-876e2e91ff50.png" width="600"/>

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/26340)

2021-10-20 14:04 UTC, Progi1984 commented on mails/themes/modern/components/layout.html.twig
> +  {% if languageIsRTL|default(false) %}
@mparvazi Could you add the `style` tag in the `if` condition ?

2021-10-20 14:04 UTC, Progi1984 commented on mails/themes/modern/components/order_layout.html.twig
> +  {% if languageIsRTL|default(false) %}
@mparvazi Could you add the `style` tag in the `if` condition ?

2021-10-20 14:05 UTC, Progi1984 commented on mails/themes/modern/components/layout.html.twig
> +  {% if languageIsRTL|default(false) %}
Better remove the current style tag and move it to the tag `style` under this current one

2021-10-20 14:05 UTC, Progi1984 commented on mails/themes/modern/components/order_layout.html.twig
> +  {% if languageIsRTL|default(false) %}
Better remove the current style tag and move it to the tag `style` under this current one

2021-10-20 14:06 UTC, Progi1984 reviewed
@mparvazi Thank you for your contribution. I have brought you the same comment in two files. Could you check it ?

2021-10-20 14:14 UTC, Progi1984 commented on mails/themes/modern/components/layout.html.twig
> +    div {
```suggestion
  <style type="text/css">
  {% if languageIsRTL|default(false) %}
    div {
```

2021-10-20 14:15 UTC, Progi1984 commented on mails/themes/modern/components/layout.html.twig
>    <style type="text/css">
```suggestion
  {% endif %}
```

2021-10-20 14:15 UTC, Progi1984 commented on mails/themes/modern/components/order_layout.html.twig
> +    div {
```suggestion
  <style type="text/css">
  {% if languageIsRTL|default(false) %}
    div {
```

2021-10-20 14:15 UTC, Progi1984 commented on mails/themes/modern/components/order_layout.html.twig
>    <style type="text/css">
```suggestion
  {% endif %}
```

2021-10-20 14:15 UTC, Progi1984 reviewed
A last comment

2021-10-20 14:26 UTC, mparvazi commented
@Progi1984 Thanks!
I think it's good now.

2021-10-20 15:11 UTC, Progi1984 approved these changes

2021-10-26 10:33 UTC, atomiix requested changes
Changes on the email theme should be made in https://github.com/PrestaShop/mjml-theme-converter, then using mjml-theme-converter you can generate the .twig files for the core.

2021-10-26 10:44 UTC, mparvazi commented
@atomiix A new PR at https://github.com/PrestaShop/mjml-theme-converter ?

2021-10-26 12:34 UTC, atomiix commented
@mparvazi yes, please :)

2021-10-28 08:29 UTC, closed without merging