Remove Yoda conditions and legacy code
PrestaShop/PrestaShop pull request #26404
Opened 2021-10-25 10:02 UTC by 0dp

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | I have gone through `classes/Hooks.php` to change all yoda conditions. I have also removed `Hook::$_hook_modules_cache = $list;` and `static::$_hook_modules_cache_exec = $allHookRegistrations;` because they should've been removed in 1.6 (please correct me if I am wrong).
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | yes
| Fixed ticket?     | #26405 
| How to test?      | ~Please indicate how to best verify that this PR is correct.~
| Possible impacts? | ~Please indicate what parts of the software we need to check to make sure everything is alright.~

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/26404)

2021-10-25 12:26 UTC, matthieu-rolland reviewed
what's wrong with yoda conditions ? 😅

2021-10-25 14:02 UTC, 0dp commented
Please advice on failed check

2021-10-25 15:42 UTC, PierreRambaud requested changes
I see no reason to remove yoda conditions :thinking:

2021-10-25 18:42 UTC, 0dp commented
Any reason to keep them @PierreRambaud ?

2021-10-27 08:41 UTC, PierreRambaud commented
> Any reason to keep them @PierreRambaud ?

It currently works and changing it brings no value.
I can return your own question, why remove Yoda conditions?

2021-10-27 09:15 UTC, 0dp commented
> > Any reason to keep them @PierreRambaud ?
> 
> It currently works and changing it brings no value. I can return your own question, why remove Yoda conditions?

The same question is asked by @matks on the issue #26405 

Here you can see I argue why we should avoid them when they are not serving their intended purpose.

TLDR;
Readability and consistency

2021-10-27 20:44 UTC, PrestaEdit reviewed
Even if you change the condition, you can't delete this inside the same PR/commit.

2021-10-27 20:44 UTC, PrestaEdit commented on classes/Hook.php
> -        Hook::$_hook_modules_cache = $list;
Even if you change the condition, you can't delete this inside the same PR/commit.

2021-10-27 20:44 UTC, PrestaEdit commented on classes/Hook.php
> -            static::$_hook_modules_cache_exec = $allHookRegistrations;
Even if you change the condition, you can't delete this inside the same PR/commit.

2021-12-03 10:19 UTC, PierreRambaud commented
Hi @0dp 
Thanks for your contribution, but as we said in the issue, we will not accept your pull request without any good reason.
Kind regards

2021-12-03 10:19 UTC, closed without merging