Fix number of notifications
PrestaShop/PrestaShop pull request #26435
Opened 2021-10-26 17:41 UTC by AdrievandeVreede

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      |  Fix issue with the notifications total if you're not allowed to see them
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24777.
| How to test?      | View the number of notifications even if there is no haven't access to customers/order/messages and compare it with the actual notifications.
| Possible impacts? |

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/26435)

2021-10-26 18:26 UTC, alexandrebru83 commented
Wouldn't it be better to see if we can modify data from php `admin_common_notifications` route?

2021-10-26 19:55 UTC, AdrievandeVreede commented
I gave it a try.

2021-10-27 08:38 UTC, tegbessou reviewed
Thank you for your PR. I have one feedback

2021-10-27 08:38 UTC, tegbessou commented on classes/Notification.php
> +            (!(isset($accesses['AdminOrders']) && $accesses['AdminOrders']['view']) && $type == 'order') ||
Maybe you can move this check, in a private method because it's not the responsibility of the 'getLastElementsIdsByType ' to do this check

2021-10-27 09:15 UTC, AdrievandeVreede commented
Thank you for your comment 🙏. Therefore I created a new private function.
Please check and respond.

2021-10-27 09:27 UTC, tegbessou submitted a review, later dismissed
Thank you! It's good IMO

2021-10-27 09:45 UTC, PululuK commented on classes/Notification.php
> +        if (!Notification::checkAccess($type)) {
```suggestion
        if (!static::checkAccess($type)) {
```

2021-10-27 11:07 UTC, AdrievandeVreede commented
What means 'exit code 8' with problem by PHP CS Fixer?

2021-10-27 11:14 UTC, alexandrebru83 commented
> What means 'exit code 8' with problem by PHP CS Fixer?

8 - Some files need fixing 

Try to execute php-cs-fixer on this file

2021-10-27 12:35 UTC, alexandrebru83 submitted a review, later dismissed

2021-10-27 13:34 UTC, matthieu-rolland submitted a review, later dismissed

2021-10-27 14:27 UTC, AdrievandeVreede commented
What could be the problem with 'Integration tests (7.4)'?

2021-10-27 15:39 UTC, atomiix submitted a review, later dismissed

2021-10-27 19:47 UTC, matks commented on classes/Notification.php
> +        $accesses = Profile::getProfileAccesses(Context::getContext()->employee->id_profile, 'class_name');
What if `Context::getContext()->employee` is `null`?

2021-10-27 19:47 UTC, matks commented on classes/Notification.php
> +            (!(isset($accesses['AdminCustomers']) && $accesses['AdminCustomers']['view']) && $type == 'customer') ||
Could we reuse one function from Access?
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Access.php

I'm afraid we might duplicate some logic already written in Access and then we dont follow DRY

2021-11-02 15:34 UTC, Progi1984 commented on classes/Notification.php
> +    private static function checkAccess($type)
```suggestion
    private static function checkAccess(string $type): bool
```

2021-11-02 15:34 UTC, Progi1984 commented on classes/Notification.php
> +        }
```suggestion
        }

        return true;
```

2021-11-02 15:35 UTC, Progi1984 reviewed
@AdrievandeVreede Thank you for your contribution. I have brought you some suggestions to your PR.

2021-11-02 15:38 UTC, AdrievandeVreede commented
Thanks for the suggestion. I committed those.

2021-11-02 15:40 UTC, Progi1984 approved these changes, later dismissed

2021-11-02 20:22 UTC, AdrievandeVreede commented
PHP CS Fixer should work now

2021-11-03 14:41 UTC, atomiix submitted a review, later dismissed

2021-11-04 09:59 UTC, Progi1984 submitted a review, later dismissed

2021-11-04 16:48 UTC, khouloudbelguith commented
Hi @AdrievandeVreede,

I still have the same issue following these steps:

1. I created three profiles
- View Orders 
![image](https://user-images.githubusercontent.com/16067358/140380508-ac1423f6-2201-4a7b-bf5a-7d1fde194613.png)

- View customers 
![image](https://user-images.githubusercontent.com/16067358/140380584-4dfc39f5-4187-407b-a4f1-baf9f757da4f.png)

- View Messages 
![image](https://user-images.githubusercontent.com/16067358/140380643-46fb6ba5-915a-4cc9-b8d1-93c5b593cedd.png)

2. For each profile, I created an employee 
![image](https://user-images.githubusercontent.com/16067358/140380739-5b0f1239-1f76-4c4d-ac9f-f7458bf74df3.png)

3. Go to FO > Create a new order + send a message in delivery step + create new customer

=> in the BO > with three employees, I have number incorrect = 3 which should be 2

I attached a screen record
https://watch.screencastify.com/v/tHdVkQsll9ogyWubb2Qd

I tried with the salesman profile  => NOK
https://watch.screencastify.com/v/CYnb3ifCTaNpsZP9Xr2t

It is a fresh install of this PR
![image](https://user-images.githubusercontent.com/16067358/140382780-53aa5c74-a82c-4a21-ad08-cfcdf626233f.png)

Thanks to check!

2021-11-04 17:09 UTC, AdrievandeVreede commented
It should work now!

2021-11-08 15:54 UTC, PierreRambaud requested changes
Hi and thanks for your pull request, unfortunately, we are not accepting merge commits, could you please squash you commits: 
![image](https://user-images.githubusercontent.com/1462701/140774374-cfbee1f7-4eac-48d2-a0d5-7ae09ebab7fe.png)

2021-12-17 15:17 UTC, PierreRambaud commented
Hi @AdrievandeVreede ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2021-12-17 15:17 UTC, closed without merging