Fix theme preview image scale and margin problem
PrestaShop/PrestaShop pull request #26459
Opened 2021-10-27 22:14 UTC by SNor42

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      |  It can be found under BO/Multishop/Shop details. It fix the theme preview image scale and margin problem.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26385 .
| How to test?      | SCSS need to compile to see changes.
| Possible impacts? | Guess nothing

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/26459)

2021-10-28 08:25 UTC, NeOMakinG commented
@SNor42 we need to wait for the UX validation for the button style

If it's validated (on the issue), we also need to do it inside the UIKit and create a release + update the UIKit on PrestaShop

2021-10-28 08:35 UTC, NeOMakinG commented
@SNor42 Scott commented on the issue, it looks like we don't want to change switches, but the https://github.com/PrestaShop/PrestaShop/issues/26385 fix remain needed :)

2021-10-28 14:55 UTC, alexandrebru83 requested changes

2021-10-28 14:55 UTC, alexandrebru83 commented on admin-dev/themes/default/scss/partials/_switch-btn.scss
> +        background: $primary-color;
```suggestion
        background: $brand-success;
```

Can you commit this change ? 
Like @NeOMakinG said "it looks like we don't want to change switches"

Your PR will be approved to fix the issue about preview image theme

2021-10-28 15:08 UTC, matthieu-rolland reviewed
@NeOMakinG should we close this PR ?

2021-10-29 07:03 UTC, NeOMakinG submitted a review, later dismissed

2021-10-29 07:04 UTC, NeOMakinG commented
@matthieu-rolland no, one issue remains fixed in it :)

2021-10-29 07:15 UTC, alexandrebrubeyonds submitted a review, later dismissed

2021-10-29 07:58 UTC, matthieu-rolland reviewed
There's a linter issue it's blocking the CI, once it's fixed it's lgtm 👍

2021-10-29 08:14 UTC, NeOMakinG commented
@SNor42 could you pull, run `npm run scss-fix` and push please? :)

2021-10-29 13:09 UTC, matthieu-rolland reviewed
you should also rebase your PR, it will fix the phpstan issue

2021-10-29 14:57 UTC, SNor42 commented
Sorry Guys!
I'm noob on GitHub, will ask google. But maybe it's better if some pro will
do those steps.

Matthieu Rolland ***@***.***> ezt írta (időpont: 2021. okt.
29., P, 15:09):

> ***@***.**** commented on this pull request.
>
> you should also rebase your PR, it will fix the phpstan issue
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/PrestaShop/PrestaShop/pull/26459#pullrequestreview-793017084>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAKFYT7VNQ3N6CBIWVUCI7LUJKTI5ANCNFSM5G3NDNJQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-02 07:56 UTC, Progi1984 commented on admin-dev/themes/default/scss/controllers/_themes.scss
> +    margin-bottom: 0px;
```suggestion
    margin-bottom: 0;
```

2021-11-02 08:37 UTC, NeOMakinG approved these changes

2021-11-02 10:59 UTC, Progi1984 approved these changes

2021-11-03 11:21 UTC, florine2623 commented
Hello @SNor42 ,

Thanks for the PR !

With 2 templates added : OK
<img width="349" alt="Screenshot 2021-11-03 at 12 08 49" src="https://user-images.githubusercontent.com/16019289/140051468-c2313335-0928-449c-b4f9-787ddd7e1aed.png">

When I add multiple templates with different lengths, the design is not optimal :
<img width="559" alt="Screenshot 2021-11-03 at 12 19 00" src="https://user-images.githubusercontent.com/16019289/140051445-0506a2e3-8d86-4d0d-b2ac-b3738e11cf76.png">

Could you take a look ?
Thanks!

2021-11-17 15:23 UTC, florine2623 commented
Hello @SNor42 ,

Have you had the time to check this ? :)
It would be really great to be able to have a clean look when more than 4 templates are added !

Let me know if you have any questions.
Thanks!

2021-11-22 15:57 UTC, Progi1984 requested changes
@SNor42 Hi, Could you remove your merge commits ?

2021-11-22 16:02 UTC, SNor42 commented
@Progi1984: Sure, but i'm noob. How?

2021-11-23 08:40 UTC, NeOMakinG commented
@SNor42 I think if you do `git rebase upstream/develop` on your branch and `git push origin develop -f`, everything should be fine!

2021-11-23 16:58 UTC, SNor42 commented
Hi!
Thanks. I've tried and got these messages:
1) Current branch develop is up to date.
2) Everything up-to-date.
Are these okay?

2021-11-23 17:11 UTC, SNor42 commented
Hi!
I've tried. If it's not working, I could remove my repository. If that's help.

2021-11-24 08:28 UTC, closed without merging

2021-11-24 08:47 UTC, NeOMakinG commented
@SNor42 I did the rebase, but something went wrong and your commit disappeared.

I tried to add your work again, but I can't push to your fork 

I think it would be way easier if you created another branch before creating the PR :/

Could you push your changes again, but maybe on another branch? And change the branch of the PR! 

Tried to help but damn I was surprised that after the rebase, your commit disappeared...