[BO] Fixes missed linking of CSS bundles for RTL
PrestaShop/PrestaShop pull request #26451
Opened 2021-10-27 15:31 UTC by mparvazi

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | In BackOffice for each CSS file, a RTL version of CSS created automatically after PS build but these files didn't link to the corresponding pages.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     |no
| Fixed ticket?     | Fixes #26422
| How to test?      | Change employee's language to RTL and go to the pages that has been modified (Orders, Order page, Catalog, Product page and Stocks). See the Browser's inspector for CSS files. The RTL version of CSS linked to the page.
| Possible impacts? | -

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/26451)

2021-10-28 08:58 UTC, NeOMakinG submitted a review, later dismissed
Damn, you are so active man 🚀 

Don't see anything blocking this, well done :)

2021-10-28 15:09 UTC, matthieu-rolland submitted a review, later dismissed

2021-10-29 12:43 UTC, NeOMakinG commented
@mparvazi 

https://github.com/PrestaShop/PrestaShop/pull/26147#issuecomment-954708548

This comment made me think about this PR, what do you think about having one component making the switch itself?

This would avoid duplicating content and conditions!

2021-10-29 14:15 UTC, mparvazi commented
@NeOMakinG 

LayoutExtension.php
```
return [
    '_rtl' => $this->context->getContext()->language->is_rtl ? '_rtl' : '',
];
```

Templates:
```
{% block stylesheets %}
  <link rel="stylesheet" href="{{ asset('themes/new-theme/public/orders'~_rtl~'.css') }}" type="text/css" media="all">
{% endblock %}
```

2021-11-02 08:37 UTC, NeOMakinG approved these changes, later dismissed

2021-11-02 12:56 UTC, Progi1984 commented on src/PrestaShopBundle/Twig/LayoutExtension.php
> +            '_rtl' => $this->context->getContext()->language->is_rtl ? '_rtl' : '',
```suggestion
            'rtl_sufix' => $this->context->getContext()->language->is_rtl ? '_rtl' : '',
```

Please change the variable name, it's more understandable.

2021-11-02 12:56 UTC, Progi1984 reviewed
@mparvazi A small variable change and it's ok for me.

2021-11-02 13:09 UTC, Progi1984 approved these changes

2021-11-03 10:09 UTC, atomiix approved these changes

2021-11-03 10:13 UTC, NeOMakinG approved these changes

2021-11-04 14:10 UTC, NeOMakinG commented
@mparvazi I tested it, every rtl bundles are fine

I seen another RTL bug => 
![image](https://user-images.githubusercontent.com/14963751/140328773-e4758dfc-c2e7-421b-8667-888be779ae99.png)

It's not related to the PR so it can be fixed inside another one, it's QA ✅

2021-11-04 14:11 UTC, NeOMakinG requested changes
Just one thing

Do we want this PR on 1.7.8.x ?
@PrestaShop/product-team 

It looks like it's not a regression... 

That would be so bad, we validated everything... Damn!

2021-11-04 16:37 UTC, mparvazi commented
> 
> 
> @mparvazi I tested it, every rtl bundles are fine
> 
> I seen another RTL bug => ![image](https://user-images.githubusercontent.com/14963751/140328773-e4758dfc-c2e7-421b-8667-888be779ae99.png)
> 
> It's not related to the PR so it can be fixed inside another one, it's QA ✅

@NeOMakinG 
No problem! I'll add to rtlfix.

![Screenshot 2021-11-04 at 20-03-29 سفارش‌ها • ONE](https://user-images.githubusercontent.com/85633460/140380701-6d05eaa7-8f57-40aa-b591-cf015d89527d.png)

Fix:

```
.main-header #header-search-container .input-group:before {
    left: 0.563rem;
    right: auto !important;
}
.main-header #header-search-container form.collapsed input#bo_query {
    padding-left: 2rem;
}
```

2021-11-05 09:35 UTC, marionf commented
@NeOMakinG If it's not a regression nor critical or security topic, the PR should go into develop branch

2021-11-09 09:55 UTC, mparvazi commented
@marionf @NeOMakinG No problem, I can make a new PR with `base` branch.

2021-11-09 15:20 UTC, closed without merging