delete id_cart in cookie if this cart is deleted and a new cart is created
PrestaShop/PrestaShop pull request #26511
Opened 2021-11-03 13:27 UTC by cdcvince

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | If we have an id_cart set in the cookie associated to a deleted cart, it raises an error in context->updateCustomer(). So when we create a new cart, this old id_cart is now useless and can be deleted.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        |  no
| Deprecations?     |  no
| How to test?      | Delete an active cart in BO and add a product in this cart in the FO
| Possible impacts? | Cart

2021-11-08 15:33 UTC, PierreRambaud requested changes
Hi and thanks for your pull request, could you please create an issue?
We have to be sure we're able to reproduce it :)

2021-11-09 09:18 UTC, cdcvince commented
> Hi and thanks for your pull request, could you please create an issue? We have to be sure we're able to reproduce it :)

I have several shops and this error was detected only on one of them.
It will be hard to find exactly the difference in this shop (server configuration, modules ...), but this PR only delete the obsolete id_cart in the cookie if it exists. And even if it is "useless" in the nominal case, it is a double check to improve the resilience of Prestashop with edge cases.

2021-11-09 09:38 UTC, PierreRambaud commented
> > Hi and thanks for your pull request, could you please create an issue? We have to be sure we're able to reproduce it :)
> 
> I have several shops and this error was detected only on one of them. It will be hard to find exactly the difference in this shop (server configuration, modules ...), but this PR only delete the obsolete id_cart in the cookie if it exists. And even if it is "useless" in the nominal case, it is a double check to improve the resilience of Prestashop with edge cases.

The change is automatically done when the customer is updated `Context::updateCustomer`, without an issue and any way to reproduce it, we won't accept this chang :/

2021-11-09 14:39 UTC, cdcvince commented
> > > Hi and thanks for your pull request, could you please create an issue? We have to be sure we're able to reproduce it :)
> > 
> > 
> > I have several shops and this error was detected only on one of them. It will be hard to find exactly the difference in this shop (server configuration, modules ...), but this PR only delete the obsolete id_cart in the cookie if it exists. And even if it is "useless" in the nominal case, it is a double check to improve the resilience of Prestashop with edge cases.
> 
> The change is automatically done when the customer is updated `Context::updateCustomer`, without an issue and any way to reproduce it, we won't accept this chang :/

The problem happens when the cart is deleted and the customer is not updated by this method (hard delete a cart from BO or from a module).

Anyway, I'll try to reproduce it as soon as I can, in the meantime I'll have to keep this fix on my shop to avoid errors with cart deletion.

2021-11-15 09:48 UTC, PierreRambaud commented
> The problem happens when the cart is deleted and the customer is not updated by this method (hard delete a cart from BO or from a module).

It's up to the module to use the proper way, we can't predict all "hard ways"

2022-03-01 14:43 UTC, PierreRambaud commented
Hi @cdcvince ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2022-03-01 14:43 UTC, closed without merging