[FO] Fixed display html in order message
PrestaShop/PrestaShop pull request #26537
Opened 2021-11-06 08:27 UTC by alexandrebrubeyonds

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | HTML element `<br/>` is shown in the message section
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26532 and still fix #24901.
| How to test?      | How to test section
| Possible impacts? | Issue fixed that introduce this bug #24901

2021-11-06 08:28 UTC, alexandrebrubeyonds commented
Hello @okom3pom, can you have a look about this fix ? :)

2021-11-06 10:03 UTC, okom3pom commented
Hello @alexandrebrubeyonds 

The product team did not want html in the messages.

There are two solutions; delete the BR but it's not nice or use strip_tags like `{strip_tags($message.message,"<br>") nofilter}`

2021-11-06 10:11 UTC, alexandrebrubeyonds commented
Hi, why they don't want new lines like in BO ?

2021-11-06 10:19 UTC, okom3pom commented
With this `{strip_tags($message.message,"<br>") nofilter}` We have the new lines

Smarty and Twig do not work the same

2021-11-08 16:10 UTC, PierreRambaud requested changes
Watch out, it leads to XSS if you put nofilter. People can write messages with Html code.
The problem needs to be fixed above, then an nl2br can be used

2021-11-08 16:31 UTC, okom3pom commented
@PierreRambaud `nl2br` don't work nice with smarty i made test this week end :'(

2021-11-09 09:33 UTC, PierreRambaud commented
You have to find another way, we won't accept a `nofilter` usage without any controls from the user input

2021-11-09 10:17 UTC, okom3pom commented
`strip_tags` do the job no ?

2021-11-09 10:57 UTC, PierreRambaud commented
> `strip_tags` do the job no ?

Hell now, if I write `I <3 U`, the result will be `I`. We have to accept all characters.

2021-12-28 13:30 UTC, PierreRambaud commented
Hi @alexandrebrubeyonds ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2021-12-28 13:30 UTC, closed without merging