Fixed incompatibility of private property in PS 1.7.8.0
PrestaShop/PrestaShop pull request #26598
Opened 2021-11-14 16:21 UTC by AliShareei

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | This PR fix incompatibility of private property in PS 1.7.8.0
| Type?             | bug fix
| Category?         | FO / BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A.
| How to test?      | If a module inherited from the PDF class is incompatible with version 1.7.8.0, here we tried to fix the problem. 
| Possible impacts? | Nothing.

2021-11-14 16:24 UTC, kpodemski commented
I think this is very specific to your scenario. Please create an issue describing what problem you have 👍 Without it, it would be impossible for PrestaShop's QA team to test your change.

2021-11-14 16:32 UTC, AliShareei commented
> 
> 
> I think this is very specific to your scenario. Please create an issue describing what problem you have 👍 Without it, it would be impossible for PrestaShop's QA team to test your change.


Hi, The problem is so simple .
Before PS 1.7.8.0 property $smarty was not declared in the class which is considered as public property.

In this version, apparently, an attempt has been made to clean the code and due to uncertainty, the data type has changed from public to private, which has broken the compatibility. 

This problem is clearly seen in the modules that work with the PDF class, and the incompatibility is solved only by changing the type to a state that is available to other classes.

2021-11-15 09:36 UTC, Progi1984 commented
@AliShareei  Thank you for your contribution. :hugs: 

Could you explain in [an issue your initial bug for this PR](https://github.com/PrestaShop/PrestaShop/issues/new/choose) (or may be link to an issue) ?

Thanks :+1:

2021-11-16 10:09 UTC, matks approved these changes
As I stated in https://github.com/PrestaShop/PrestaShop/issues/26606 I think this change is valid 👍

2021-11-16 11:35 UTC, AliShareei commented
> 
> 
> As I stated in #26606 I think this change is valid 👍

Hi @matks , Thanks.

2021-11-18 15:02 UTC, jolelievre requested changes
The fix is totally legit!! However, I think this should target `1.7.8.x` branch as it is a regression

This needs to be confirmed with @PrestaShop/product-team though, but the initial issue should be moved to the 1.7.8.2 scope

2021-11-25 10:38 UTC, marionf commented
Sorry but this issue / PR is too technical and I am not sure I am the good person to decide if the issue is a regression or not and so if the PR should be on the develop or on the 1.7.8.x branch
I let you @PrestaShop/prestashop-core-developers discuss and decide on this one ;)

2021-12-13 16:09 UTC, sowbiba submitted a review, later dismissed

2022-03-01 14:42 UTC, PierreRambaud commented
Hi @AliShareei ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2022-03-01 14:42 UTC, closed without merging

2022-03-01 16:25 UTC, AliShareei commented
Hi @PierreRambaud 

I'm not sure why this PR is not done yet! I do my part and you just waiting for months for what?
I'm really disappointed with the PrestaShop team. This is not the first time and will never be the last.

2022-03-20 20:48 UTC, AliShareei commented
Hi guys,

Why is there so much pain in fixing small problems in PrestaShop even with available PR?

@PierreRambaud 
@jolelievre 
@sowbiba

2022-03-28 13:19 UTC, matks commented
> Why is there so much pain in fixing small problems in PrestaShop even with available PR?

Explained here: https://github.com/PrestaShop/PrestaShop/issues/22661#issuecomment-1075361733

This PR was closed because its target branch was not changed from `develop` to `1.7.8.x` and after multiple months it was stale.

2022-03-28 13:24 UTC, matks commented
@AliShareei I did the target branch change and recreated a new PR that contains your commit https://github.com/PrestaShop/PrestaShop/pull/28052

2022-03-31 11:01 UTC, AliShareei commented
@matks Thank you so much for following up. Maybe because no one mentioned me to retarget, so I did not know I had to do something. I mean I did not receive any notifications for this. Anyway, I'm glad the problem is solved and thank you.