PHPStan (Level 0+1) on tests/
PrestaShop/PrestaShop pull request #26592
Opened 2021-11-12 15:43 UTC by Progi1984

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | PHPStan (Level 0+1) on tests/
| Type?             | improvement
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Relative to  #16471 
| How to test?      | Github Actions are :green_circle:

2021-11-12 21:05 UTC, matks commented on tests/Integration/PrestaShopBundle/Command/GenerateMailTemplatesCommandTest.php
> +        $this->expectException(RuntimeException::class);
```suggestion
        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessage('Not enough arguments (missing: "theme, locale").');
```
I would think this was the code that was supposed to be run.

2021-11-12 21:05 UTC, matks commented on tests/Unit/Core/Data/AbstractTypedCollectionTest.php
> +        $this->expectException(TypeException::class);
Same here, I think a call `expectExceptionMessage` should make the assertion verified

2021-11-12 21:05 UTC, matks commented on tests/Unit/Core/Domain/ValueObject/MoneyTest.php
> -        $this->expectException(DomainConstraintException::class, 'Money amount cannot be lower than zero, -100 given');
Same here ▶️  `expectExceptionMessage`

2021-11-12 21:05 UTC, matks commented on tests/Unit/Core/MailTemplate/FolderThemeCatalogTest.php
> -        $this->expectException(InvalidArgumentException::class, 'Invalid requested theme "unknown", only available themes are: classic, modern');
Same here ▶️  `expectExceptionMessage`

2021-12-03 10:12 UTC, matks requested changes, later dismissed
Sorry @Progi1984 you need to rebase

2021-12-03 10:19 UTC, Progi1984 commented
@matks :heavy_check_mark: Done

2021-12-17 21:50 UTC, matks approved these changes

2021-12-20 10:51 UTC, PierreRambaud approved these changes

2021-12-20 10:52 UTC, merged

2021-12-20 10:52 UTC, PierreRambaud commented
Thank you @Progi1984