Bump version to 1.7.8.2
PrestaShop/PrestaShop pull request #26630
Opened 2021-11-16 13:58 UTC by Progi1984

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  1.7.8.x
| Description?      | Bump version to 1.7.8.2
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| How to test?      | N/A
| Possible impacts? | N/A

2021-11-16 14:08 UTC, matks approved these changes, later dismissed

2021-11-18 14:33 UTC, PierreRambaud requested changes
You forget to change: AppKernel::RELEASE_VERSION

2021-11-18 14:56 UTC, jolelievre commented on app/AppKernel.php
> +    const VERSION = '1.7.8.2';
Missing update on `RELEASE_VERSION`

2021-11-23 11:06 UTC, Progi1984 commented
@PierreRambaud @jolelievre @matks Fixed & Rebased

2021-11-23 15:26 UTC, PierreRambaud requested changes
It should be 1.7.8.2 :thinking:

2021-11-23 16:27 UTC, Progi1984 commented
@PierreRambaud No, the 1782 in on `1.7.8.x-build` by @matks. The next version in `1.7.8.x` will be 1783.

2021-11-23 17:13 UTC, PierreRambaud approved these changes

2021-11-23 17:19 UTC, atomiix approved these changes

2021-11-23 17:20 UTC, merged

2021-11-23 17:20 UTC, atomiix commented
Thanks @Progi1984!