Remove lazy load for logo
PrestaShop/PrestaShop pull request #26658
Opened 2021-11-17 21:09 UTC by iqit-commerce

Logo img is above a fold, so it should be not lazyloaded.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Images which are above a fold should not be lazyloaded, its bad for performance and pagespeed tools complain about that too.
| Type?             | bug fix 
| Category?         | FO
| BC breaks?        | no
| Deprecations?     |  no
| Fixed ticket?     | 
| How to test?      | 
| Possible impacts? |

2021-11-17 22:32 UTC, Hlavtox commented
@iqit-commerce I don't know, I think we can keep it man, logo is not important for the content. 🤔

For example, main product image will be considered LCP, so that should load the quickest and definitely shouldn't have lazy load. But what about the other items above fold? @NeOMakinG

2021-11-18 09:36 UTC, PierreRambaud commented
Could you please create an issue, I don't see how lazy loading is bad for performance :thinking:

2021-11-18 09:51 UTC, iqit-commerce commented
I agree that logo is small image without big impact, but still recommenadtions should be follow. 
I agree that first product image on product page should also be loaded instantly,
@PierreRambaud Please check
https://web.dev/browser-level-image-lazy-loading/#avoid-lazy-loading-images-that-are-in-the-first-visible-viewport

2021-11-18 10:58 UTC, PierreRambaud approved these changes, later dismissed

2021-11-18 10:58 UTC, PierreRambaud commented
> I agree that logo is small image without big impact, but still recommenadtions should be follow. I agree that first product image on product page should also be loaded instantly, @PierreRambaud Please check https://web.dev/browser-level-image-lazy-loading/#avoid-lazy-loading-images-that-are-in-the-first-visible-viewport

I approve the change, but please create an issue to be sure ;)

2021-11-18 11:08 UTC, iqit-commerce commented
Ok, Issue created #26666

2021-11-18 12:08 UTC, khouloudbelguith commented
Hi @iqit-commerce,

I think you need to change the base from develop to 1.7.8.x because it is a regression from PS1780.

Thanks!

2021-11-19 09:25 UTC, NeOMakinG requested changes
Needs to be rebased to 1.7.8.x, but I approve the PR anyway

2021-11-22 14:38 UTC, NeOMakinG commented
@iqit-commerce I did rebase your PR.

```
// Reset to 1.7.8.x
git reset --hard upstream/1.7.8.x

// Cherry pick your commit
git cherry-pick 344db778289691191dcd6f1b6d5281961bcf35bf

// Force push to the branch
git push iqit patch-1 -f
```

2021-11-22 14:38 UTC, NeOMakinG approved these changes
👍

2021-11-22 14:56 UTC, PierreRambaud approved these changes

2021-11-22 21:24 UTC, marwachelly commented
Hello,
PR is tested , lazy load of logo is removed and Just look if the logo is loaded properly
![image](https://user-images.githubusercontent.com/89604350/142937194-46a52a5d-fd84-4d81-a316-2fda31e72be6.png)
Thanks,

2021-11-23 08:09 UTC, merged

2021-11-23 08:09 UTC, Progi1984 commented
Thanks @iqit-commerce & @marwachelly

2022-05-12 15:33 UTC, leemyongpakvn commented
ping https://github.com/orgs/PrestaShop/teams/qa-functional as **Progi1984** suggested