Improve CMS edit page footer
PrestaShop/PrestaShop pull request #26704
Opened 2021-11-22 14:40 UTC by Hlavtox

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | This PR turns two buttons into btn group on smaller screens. Drops up and left.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26633
| How to test?      | Compare before and after.
| Possible impacts? | 

**Screenshot**
![Multimédia1](https://user-images.githubusercontent.com/6097524/142880614-7f73b53c-dc05-4fbe-9c54-648122dc99ae.gif)

2021-11-22 15:40 UTC, prestascott commented
Nice work @Hlavtox, LGTM!

2021-11-22 15:44 UTC, mparvazi commented
@Hlavtox Great job!

2021-11-23 08:37 UTC, NeOMakinG submitted a review, later dismissed

2021-11-23 10:46 UTC, Julievrz approved these changes, later dismissed
Wording ✅ Thank you

2021-11-24 15:48 UTC, Progi1984 approved these changes, later dismissed

2021-11-25 09:39 UTC, khouloudbelguith commented
Hi @Hlavtox,

When I resize the window or I use a mobile, the button is well displayed but the "Save and preview" is not working.
I attached a screen record
[prestashop_demo](https://watch.screencastify.com/v/WL8pEpAjUn7NM5YYcFxD)

Thanks!

2021-11-29 07:52 UTC, Hlavtox commented
@khouloudbelguith @NeOMakinG I need to see my eye doctor :-)))

`<btn type="submit" class="dropdown-item" name="save-and-preview" id="save-and-preview-button">{{ 'Save and preview'|trans({}, 'Admin.Actions') }}</btn>`

2021-11-29 09:36 UTC, NeOMakinG commented
> https://watch.screencastify.com/v/WL8pEpAjUn7NM5YYcFxD

I think it's because some JS are linked to this "Save and preview" button and it's not added to both buttons (responsive + desktop one), don't you think?

2021-11-29 20:28 UTC, Hlavtox commented
@NeOMakinG @khouloudbelguith It works fine now, it was just the element name wrong. ;-)

2021-11-30 08:42 UTC, NeOMakinG commented
> @NeOMakinG @khouloudbelguith It works fine now, it was just the element name wrong. ;-)

Holy, didn't even notice it...

2021-11-30 08:42 UTC, NeOMakinG approved these changes, later dismissed

2021-12-03 10:26 UTC, matks requested changes

2021-12-03 10:26 UTC, matks commented on src/PrestaShopBundle/Resources/views/Admin/Improve/Design/Cms/Blocks/form.html.twig
> +        <button type="submit" class="btn btn-primary" id="save-button">{{ 'Save'|trans({}, 'Admin.Actions') }}</button>
I think it's a bad practice to have duplicate ID, isn't it?

2021-12-03 10:27 UTC, PierreRambaud requested changes
There are duplicate ids :)

2021-12-03 15:10 UTC, Hlavtox commented
@PierreRambaud @matks Yes, you are right. IDs are not needed for the functionality, but are needed for tests.

@boubkerbribri How do you want me to alternatively target the buttons without using IDs? Add `js-` class, add `data-role`?

2021-12-03 16:25 UTC, boubkerbribri commented
> @boubkerbribri How do you want me to alternatively target the buttons without using IDs? Add `js-` class, add `data-role`?

For now, the Mobile views are not targeted by UI tests, I think you can delete the Mobile View buttons ids. We will find a solution when we will have to.

2021-12-18 15:44 UTC, Hlavtox commented
@matks @PierreRambaud Duplicate ids fixed

2021-12-20 08:01 UTC, PierreRambaud requested changes
`save-and-preview-button`  ids are still duplicate, watch out, you can see them in your browser developer tools :wink:

2022-01-05 16:16 UTC, closed without merging