Allow mails/partials_ template ovveride in theme
PrestaShop/PrestaShop pull request #26724
Opened 2021-11-24 09:56 UTC by M-t-t-h

add "_PS_THEME_DIR_ . 'mails/_partials' . DIRECTORY_SEPARATOR . $partialTemplateName,".
Prestashop will check if isset a ovrrider template in [myCustomTheme]/mails/partials_
before using common tpl.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 1.7.8.x
| Description?      | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?             | bug fix / improvement / new feature / refacto / critical
| Category?         | FO / BO / CO / IN / WS / TE / LO / ME / PM
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| Fixed ticket?     | Fixes #{issue number here}.
| How to test?      | Please indicate how to best verify that this PR is correct.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

2021-11-29 14:46 UTC, Progi1984 commented
@M-t-t-h  Thank you for your contribution. :hugs: 

Could you explain in [an issue your initial bug for this PR](https://github.com/PrestaShop/PrestaShop/issues/new/choose) (or may be link to an issue) ?
Could you give us a scenario which permits to test the bug before and after this PR ?

Thanks :+1:

2021-11-29 15:03 UTC, M-t-t-h commented
Hy,

Thanks for the return.
As it's my first commit... i did it wrong and github tag my commit as "debug".
I didn't find how to change thoses tag.

In Fact, my commit is not a debug, it's just an improve.
It's allow to custome, for each theme, the include part in order confirmation (include = [**myCustomTheme**]/mails/partials/order_conf_product_list.tpl")

Usefull in a multishop, not so much in the other case even if it's prevent override of source file in PS_DIRECTORY/mail/

BR,

2021-12-23 16:24 UTC, matks commented
Close and reopen to re-run CI

2021-12-23 16:27 UTC, matks requested changes
Hello @M-t-t-h I think your contribution is valuable but in order for us to be able to validate both the change and the consequences we need more context, like @Progi1984 mentioned. I can see ... approximately how this works but without the clear thing I cant review this.

Can you
- fill the PR table
- provide a list of clear steps to see what does not work NOW and what would work thanks to your Pull Request ? see example below

Example: I use [a_custom_theme_example] which contains an override of file [...] inside mails/_partial/... but it does not work without the PR, thanks to the PR the override is correctly used

2022-03-01 08:16 UTC, Progi1984 commented
Hi @M-t-t-h,
Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.
Thanks!

2022-03-01 08:16 UTC, closed without merging