Fix #16306
PrestaShop/PrestaShop pull request #26782
Opened 2021-11-27 23:32 UTC by alfonsolr09

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      |  We make the boxes are deactivated if we have not selected the characteristic. If we add a custom value, the value box is disabled. If we select a value in the list, the custom value box is deactivated and deletes the value (if there was something written)
| Type?             | bug fix 
| Category?         |  BO 
| BC breaks?        |  no
| Deprecations?     | no
| Fixed ticket?     | Fixes #16306
| How to test?      | See features in product page
| Possible impacts? | No

2021-11-27 23:42 UTC, alfonsolr09 commented
can we merge this into 1.7.8.x?

2021-11-28 18:39 UTC, Hlavtox commented
@alfonsolr09 It won't be accepted into 1.7.8, only regressions are in the patches.

2021-12-03 09:18 UTC, matks commented
I confirm @Hlavtox 

In the past we used to put a lot of bug fixes in patch version, including bugs "not a regression".

The consequences were
- big patches very long to validate for QA
- new issues (because the more code you ship the more bugs you add ! :trollface: )

So we dont do this anymore to have patch releases "as safe as possible".

2021-12-03 09:20 UTC, matks requested changes
ESLint rejects your changes please fix them 😉

2021-12-03 22:52 UTC, alfonsolr09 commented
do it

2021-12-06 10:43 UTC, Progi1984 commented on admin-dev/themes/default/js/bundle/product/form.js
> +  // we need to put in disabled the custom
```suggestion
    // we need to put in disabled the custom
```

2021-12-06 10:43 UTC, Progi1984 commented on admin-dev/themes/default/js/bundle/product/form.js
> +    const $featurevalueSelector = $newFormJquery.find('select');
```suggestion
```

2021-12-06 10:43 UTC, Progi1984 commented on admin-dev/themes/default/js/bundle/product/form.js
> +    // adding events to the preloaded features
```suggestion
      // adding events to the preloaded features
```

2021-12-06 10:44 UTC, Progi1984 reviewed
@alfonsolr09 Thank your contribution. Could you fix all ESLint errors, please ?

2021-12-11 00:25 UTC, alfonsolr09 commented
I have already solved all the errors you indicated to me, thank you

2021-12-13 14:17 UTC, Progi1984 commented on admin-dev/themes/default/js/bundle/product/form.js
```
```

2021-12-15 23:41 UTC, alfonsolr09 commented
check it now please @Progi1984

2021-12-23 13:57 UTC, atomiix commented
@alfonsolr09 looks like eslint is still not happy 😅

2021-12-23 14:09 UTC, alfonsolr09 commented
Can you solve it? @atomiix

2021-12-24 14:37 UTC, closed without merging

2021-12-24 14:47 UTC, atomiix commented
@alfonsolr09 I did a mistake while rebasing your PR and I cannot push on your develop branch anymore 🤦‍♂️. I pushed the changes on my repo: https://github.com/atomiix/PrestaShop/tree/alfonsolr09-develop, can you rebase your develop branch on this one so we can re-open your PR? Thanks

2021-12-24 20:34 UTC, alfonsolr09 commented
done??

2021-12-24 20:40 UTC, alfonsolr09 commented
check it please, i think i didn't get it right and corrupted the code ...

2021-12-27 09:29 UTC, atomiix commented
@alfonsolr09 You created a new PR from my own branch instead of rebasing yours from mine 😅  That being said, the new PR seems valid, I don't see any corrupted code. It would have been simpler to update the original PR (still not too late if you wanna try ;)) for reviewers, but we can keep the new one too ;)

2021-12-27 09:45 UTC, alfonsolr09 commented
> instead of rebasing yours from mine 

How can i do ?? I don't really understand GitHub ...

2021-12-28 09:31 UTC, matks commented
@alfonsolr09 we cannot teach you git neither github, you need to learn it if you want to contribute to a project hosted on github

Here are some nice doc
https://git-scm.com/docs/user-manual
https://docs.github.com/