Add redirect with notifications
PrestaShop/PrestaShop pull request #26791
Opened 2021-11-29 11:24 UTC by Lionel-dev

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 1.7.8.x
| Description?      | When you do a reorder with OOS products, there are too many redirects that you lose the error.  Indeed, the duplication of the basket generates an error in `$this-errors[] ` which is not displayed during the redirection on the index.
| Type?             | bug fix / improvement 
| Category?         | FO
| BC breaks?        |no
| Deprecations?     |no
| Fixed ticket?     |  ----
| How to test?      | Try to re-encode an order with 1 OOS products with a refusal on the add cart. You will be redirected to the index with no apparent error message. After the fix, you will see the message.
| Possible impacts? | I think everything is alright.

PrestaShop partnered : Wepika

2021-11-29 15:24 UTC, Progi1984 commented
@Lionel-dev  Thank you for your contribution. :hugs: 

Could you explain in [an issue your initial bug for this PR](https://github.com/PrestaShop/PrestaShop/issues/new/choose) (or may be link to an issue) ?
Could you give us a scenario which permits to test the bug before and after this PR ?

Thanks :+1:

2021-11-30 08:24 UTC, Lionel-dev commented
I have created a way out: https://github.com/PrestaShop/PrestaShop/issues/26804 please.

2021-12-06 14:49 UTC, Lionel-dev commented
@Progi1984 some news about this pull-request ? :)

2021-12-06 14:51 UTC, Progi1984 commented
@Lionel-dev It seems that your PR broke Sanity Tests & Integrations tests. Could you check it ?

2021-12-06 14:57 UTC, Lionel-dev commented
> @Lionel-dev It seems that your PR broke Sanity Tests & Integrations tests. Could you check it ?

I'll check, but I don't understand why it's broken ... My fixed haven't a big impact :/

2021-12-09 15:40 UTC, PierreRambaud commented
You have to rebase your pull request ;)

2021-12-23 16:17 UTC, matks requested changes, later dismissed

2021-12-23 16:17 UTC, matks commented on controllers/front/OrderController.php
> +            $this->redirectWithNotifications($cartLink)
The tests noticed a missing `;` 😉 
```
1) Tests\Integration\PrestaShopBundle\Controller\Admin\FrameworkBundleAdminControllerTest::testPagesAreAvailable with data set "admin_metas_create" ('Add new meta', 'admin_metas_create')
ParseError: syntax error, unexpected '}'
```

2021-12-23 17:06 UTC, Lionel-dev commented
I just add this ";", sry for this dumb mistake

2021-12-23 17:07 UTC, Lionel-dev commented on controllers/front/OrderController.php
> +            $this->redirectWithNotifications($cartLink)
I just change this. thx <3

2021-12-23 17:30 UTC, kpodemski approved these changes

2021-12-23 17:30 UTC, kpodemski commented
Nice catch 👍

2021-12-24 15:22 UTC, PierreRambaud approved these changes

2021-12-27 11:04 UTC, khouloudbelguith commented
Hi @Lionel-dev,

It is ok :heavy_check_mark: 
https://watch.screencastify.com/v/CQ9HeCBsbPyszfXjN3Xs

Thanks!

2021-12-27 13:10 UTC, merged

2021-12-27 13:11 UTC, Progi1984 commented
Thnaks @Lionel-dev & @khouloudbelguith