Add shop details support to classic
PrestaShop/PrestaShop pull request #26832
Opened 2021-12-02 09:45 UTC by Hlavtox

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Legal information is not displayed on contact page, while there is a field for that in Prestashop settings.
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26809
| How to test?      | Fill the legal info in BO, apply https://github.com/PrestaShop/ps_contactinfo/pull/43 and go to contact page.
| Possible impacts? | None.

2021-12-02 09:47 UTC, NeOMakinG submitted a review, later dismissed

2021-12-02 12:40 UTC, Julievrz commented
Hi @Hlavtox 

I've tried to test the PR to better understand the context of the wording. But the registration number doesn't appear on the front office with your PR. Is it just me?

![image](https://user-images.githubusercontent.com/70583503/144423399-6b63a60c-3ee3-474b-8a9b-ecebcae6356f.png)
![image](https://user-images.githubusercontent.com/70583503/144423449-9cfbb6ca-aa9b-47d7-a32d-dd026d2df336.png)

2021-12-02 12:45 UTC, Hlavtox commented
@Julievrz Hi, you must also apply PR from https://github.com/PrestaShop/ps_contactinfo/pull/43.

2021-12-02 13:40 UTC, Julievrz commented
Thanks!
So instead of having "Details:" what about having "Registration number:" like in the back office?

2021-12-02 16:04 UTC, Hlavtox commented
@Julievrz It can't be called "Registration number". For example, in Czech republic, you are required by the law to specify a lot more information, and Contact page is the best way to do it. We should also make line breaks working in this input, or just make it a free HTML.

- Registration number: 12345678
- Registration information: _The company is registered in the Commercial Register kept at the Regional Court in Prague in section C, insert 32726._
- VAT number: CZ12345678

2021-12-14 15:47 UTC, Julievrz commented
> @Julievrz It can't be called "Registration number". For example, in Czech republic, you are required by the law to specify a lot more information, and Contact page is the best way to do it. We should also make line breaks working in this input, or just make it a free HTML.
> 
> **On top of company name, address, phone, email also:**
> 
> * Registration number: 12345678
> * Registration information: _The company is registered in the Commercial Register kept at the Regional Court in Prague in section C, insert 32726._
> * VAT number: CZ12345678

Ok, I understand your point. However, when checking PrestaShop websites, it seems that merchants tend to use the "Legal notice" page to display these details.

https://www.lechocolatdesfrancais.fr/en/
![image](https://user-images.githubusercontent.com/70583503/146030700-48240703-d7e3-4cd4-b66a-b5ac35bfa46e.png)
https://www.poupadou.com/en/content/legal-notice-2
![image](https://user-images.githubusercontent.com/70583503/146030936-be992db9-17db-4377-89a9-edd1a325ca3a.png)
https://www.pylones.com/en/content/5-legal-notices
![image](https://user-images.githubusercontent.com/70583503/146031376-2156626b-4ec3-4ae9-9c10-2adde90efb07.png)

Anyway, I'm not against keeping "Details:". It's quite generic wording and merchants will still be able to modify it according to their needs. I'm just not sure to understand the difference between this and the legal notice. :-)

2021-12-18 15:59 UTC, Hlavtox commented
@Julievrz That field was definitely meant to contain more info. It's multiline. It's even written in the helpbox ("Registration information (company ID, VAT number)".

![reg](https://user-images.githubusercontent.com/6097524/146647400-ad5f5ea9-6e1f-4daa-9f9e-c156f7e4e35a.png)

I think that line break support or ability to enter HTML should be provided in a separate PR.
___________

Also, I randomly checked 4 stores I know from memory, where I buy stuff on regular basis. One of the best stores in their field. All have VAT number and registration info on their contact page. 👍

- https://www.ventilatory.cz/kontakt
- https://www.ahifi.cz/adresa-oteviraci-doba-a-kontakty/
- https://www.mall.cz/kontakt
- https://www.notino.cz/kontakt/

2021-12-20 14:19 UTC, Julievrz commented
> @Julievrz That field was definitely meant to contain more info. It's multiline. It's even written in the helpbox ("Registration information (company ID, VAT number)".
> 
> ![reg](https://user-images.githubusercontent.com/6097524/146647400-ad5f5ea9-6e1f-4daa-9f9e-c156f7e4e35a.png)
> 
> I think that line break support or ability to enter HTML should be provided in a separate PR.
> 
> Also, I randomly checked 4 stores I know from memory, where I buy stuff on regular basis. One of the best stores in their field. All have VAT number and registration info on their contact page. 👍
> 
> * https://www.ventilatory.cz/kontakt
> * https://www.ahifi.cz/adresa-oteviraci-doba-a-kontakty/
> * https://www.mall.cz/kontakt
> * https://www.notino.cz/kontakt/

Yes, I totally understand! I think the label in the BO is quite confusing though. We can go for "Company details:" if it suits you. ☺️

2021-12-20 14:19 UTC, Julievrz commented on themes/classic/modules/ps_contactinfo/ps_contactinfo-rich.tpl
> +        {l s='Details:' d='Shop.Theme.Global'}<br/>
```suggestion
        {l s='Company details:' d='Shop.Theme.Global'}<br/>
```

2021-12-21 12:13 UTC, Hlavtox commented
@Julievrz Wording applied, I also changed it in BO, can you check? :-)

2021-12-21 12:26 UTC, Hlavtox commented
Also, added support for line breaks.

2021-12-21 15:06 UTC, Julievrz commented on controllers/admin/AdminStoresController.php
> +                'hint' => $this->trans('Shop registration information (e.g. DNI, VAT number, SIRET or RCS).', [], 'Admin.Shopparameters.Help'),
```suggestion
                'hint' => $this->trans('Company's registration details (e.g. DNI, VAT, SIRET, RCS, etc.).', [], 'Admin.Shopparameters.Help'),
```

The last comment before I can approve wording. :-)

2021-12-23 14:17 UTC, matks submitted a review, later dismissed

2021-12-24 15:07 UTC, atomiix approved these changes

2021-12-27 13:16 UTC, Progi1984 approved these changes

2021-12-27 13:54 UTC, PierreRambaud approved these changes

2021-12-27 15:47 UTC, khouloudbelguith commented
Hi @Hlavtox,

I tested this PR using this [PR](https://github.com/PrestaShop/ps_contactinfo/pull/43).
The wording is ok in the BO 
![image](https://user-images.githubusercontent.com/16067358/147487038-c60ee5bd-81d1-45e6-b0a4-ab5dc0c9040f.png)
In the FO > in the footer => is not displayed
![image](https://user-images.githubusercontent.com/16067358/147487112-240a694f-2a1c-4cf6-8152-169d55ed33cd.png)

Thanks!

2022-01-05 15:49 UTC, Hlavtox commented
@khouloudbelguith I didn't implement it, I don't think it's needed there...

2022-01-24 12:54 UTC, khouloudbelguith requested changes
Hi @Hlavtox,

In fact, as you can see in this [comment](https://github.com/PrestaShop/PrestaShop/issues/26809#issuecomment-983481198)
`The registration number should be displayed in the contact page but also in the footer, under the email.`
This behavior is validated by the product team.

Thank you!

2022-03-07 11:33 UTC, Progi1984 commented
Hi @Hlavtox,
Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.
Thanks!

2022-03-07 11:33 UTC, closed without merging

2023-06-09 21:20 UTC, fabiocranchi commented
Solution:

Edit the file /modules/ps_contactinfo/ps_contactinfo.php
In array $contact_infos, add this line: 'regNumber' => Configuration::get('PS_SHOP_DETAILS'),
In the file just below the line 'company' => Configuration::get('PS_SHOP_NAME'),
Add: 'regNumber' => Configuration::get('PS_SHOP_DETAILS'),

Then, inside the theme, search for ps_contactinfo.tpl and add "
{$contact_infos.regNumber}" without quotes just below "{$contact_infos.address.formatted nofilter}"

tpl file location in classic theme:
themes/classic/modules/ps_contactinfo

Hope it helped =)

2023-06-09 21:23 UTC, fabiocranchi commented
> Hi @Hlavtox,
> 
> I tested this PR using this [PR](https://github.com/PrestaShop/ps_contactinfo/pull/43). The wording is ok in the BO ![image](https://user-images.githubusercontent.com/16067358/147487038-c60ee5bd-81d1-45e6-b0a4-ab5dc0c9040f.png) In the FO > in the footer => is not displayed ![image](https://user-images.githubusercontent.com/16067358/147487112-240a694f-2a1c-4cf6-8152-169d55ed33cd.png)
> 
> Thanks!

Solution:

Edit the file /modules/ps_contactinfo/ps_contactinfo.php
In array $contact_infos, add this line: 'regNumber' => Configuration::get('PS_SHOP_DETAILS'),
In the file just below the line 'company' => Configuration::get('PS_SHOP_NAME'),
Add: 'regNumber' => Configuration::get('PS_SHOP_DETAILS'),

Then, inside the theme, search for ps_contactinfo.tpl and add "
{$contact_infos.regNumber}" without quotes just below "{$contact_infos.address.formatted nofilter}"

tpl file location in classic theme:
themes/classic/modules/ps_contactinfo

Hope it helped =)