Update PS version in changelog
PrestaShop/PrestaShop pull request #26830
Opened 2021-12-02 08:13 UTC by matks

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Update PS version in changelog
| Type?             | improvement
| Category?         | PM
| BC breaks?        | no
| Deprecations?     | no

2021-12-03 09:27 UTC, sowbiba submitted a review, later dismissed

2021-12-03 11:01 UTC, PierreRambaud commented on docs/CHANGELOG.txt
> +Release Notes for PrestaShop 8
```suggestion
Release Notes for PrestaShop
```

2021-12-03 11:01 UTC, PierreRambaud requested changes
Two solutions imho:
- removing all 1.7 data in this file
- Ignore PrestaShop version

2021-12-03 13:20 UTC, matks commented
> * Ignore PrestaShop version

Simple and safe: let's do that

2021-12-03 15:28 UTC, sowbiba approved these changes

2021-12-06 15:54 UTC, PierreRambaud approved these changes

2021-12-06 15:54 UTC, merged

2021-12-06 15:54 UTC, PierreRambaud commented
Thank you @matks