Update Mexico unit settings
PrestaShop/PrestaShop pull request #27021
Opened 2021-12-18 03:20 UTC by rickygzz

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | There is a file called localization/mx.xml with Mexico's settings. I updated the units, since we use metric system.
| Type?             | improvement
| Category?         | LO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | [Fixes #{23848}] (https://github.com/PrestaShop/PrestaShop/issues/23848).
| How to test?      | Please indicate how to best verify that this PR is correct.
| Possible impacts? | I dont think there are any impacts.

The localization file `mx.xml` was updated. As explained in the provided ticket, Mexico uses metric system for the units. We expect to see short distance = cm, base distance = m and long distance = km (instead of in, ft, mi).

On March 30, 2020 I created pull request #23830 (https://github.com/PrestaShop/PrestaShop/pull/23830) and created ticket #23848 (https://github.com/PrestaShop/PrestaShop/issues/23848) explaining that in Mexico we use metric system, I provided sources so the team could validate my affirmation:

- http://www.diputados.gob.mx/LeyesBiblio/abro/lfmn/LFMN_abro.pdf
- http://chartsbin.com/view/d12
- https://www.quora.com/Which-countries-do-not-use-the-metric-system

On August 5, 2020 The information was validated by the PrestaShop team and I was suggested to update other repository

>Hi @rickygzz can you please submit your PR against https://github.com/PrestaShop/LocalizationFiles/blob/master/mx.xml ?
> 
> This file here is actually a copy of https://github.com/PrestaShop/LocalizationFiles/blob/master/mx.xml . https://github.com/PrestaShop/LocalizationFiles/blob/master/mx.xml is the reference and we keep a copy inside the software so that, upon install, user does not need to download all files from https://github.com/PrestaShop/LocalizationFiles

For which I created pull request in the mentioned repository #LocalizationFiles/12 https://github.com/PrestaShop/LocalizationFiles/pull/12

2021-12-18 03:48 UTC, rickygzz commented
Fixes #23848

2021-12-18 03:50 UTC, rickygzz commented
According to what it is stated in https://github.com/PrestaShop/LocalizationFiles/issues/9 

This pull request may not be needed.

I created another pull request in the other repository https://github.com/PrestaShop/LocalizationFiles/pull/12

2021-12-18 08:46 UTC, rickygzz commented
@PierreRambaud  hello,

I saw your coment edit. I created PR PrestaShop/LocalizationFiles#12 

Should I close this pull request?

2021-12-20 07:49 UTC, PierreRambaud commented
> @PierreRambaud hello,
> 
> I saw your coment edit. I created PR [PrestaShop/LocalizationFiles#12](https://github.com/PrestaShop/LocalizationFiles/pull/12)
> 
> Should I close this pull request?

My comment edit?
Do you mean the automatic reviewable edit part? Because I was in week-end and far away from my computer :sweat_smile:  
![image](https://user-images.githubusercontent.com/1462701/146731054-eeca1709-d83d-4241-93b1-4c14d3ee4430.png)

But I agree with you, I think only files in the LocalizationFiles repository should be edited.

2021-12-20 08:54 UTC, matthieu-rolland commented
hello, you have a merge commit that is blocking the CI

2021-12-20 08:55 UTC, matthieu-rolland reviewed
hello, you have a merge commit that is blocking the CI

2021-12-20 10:47 UTC, PierreRambaud requested changes, later dismissed
Could you please don't use merge commits and use rebase instead?

2021-12-21 03:34 UTC, rickygzz commented
@PierreRambaud @matthieu-rolland 
Sorry guys, I am getting used to git and github.

I think I successfully rebased the patch and got my commit to be ahead to the latest develop commit 7ad2478992499771065e587127a37d3cac78e28d (as at right now).

Also it passed the automatic 27 checks (2 skipped).

2021-12-21 13:45 UTC, matthieu-rolland approved these changes

2021-12-22 20:16 UTC, sowbiba approved these changes

2021-12-22 20:16 UTC, sowbiba commented
Do we need @PrestaShop/product-team validation ?

2021-12-23 09:42 UTC, MatShir commented
Thanks LGTM !

2021-12-23 09:43 UTC, MatShir approved these changes

2021-12-24 10:51 UTC, khouloudbelguith commented
Hi @rickygzz,

It is ok :heavy_check_mark: 
https://watch.screencastify.com/v/QImkzAGKeepx9OIMnov8

Thanks!

2021-12-24 12:44 UTC, PierreRambaud approved these changes

2021-12-24 12:44 UTC, merged

2021-12-24 12:44 UTC, PierreRambaud commented
Thank you @rickygzz