Add the required lenght to create a webservice key into form
PrestaShop/PrestaShop pull request #27108
Opened 2021-12-28 10:38 UTC by PrestaEdit

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      |  Add the constraints (32 characthers) into the help of the key creation form.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #n/d.
| How to test?      |  See that when you want to create a webservice key, the "key" help will say you the number of needed characthers.
| Possible impacts? | Nothing.

Wording needed:

- Key should be at least %length% characters long. (Admin.Notifications.Info)

2021-12-28 10:39 UTC, Progi1984 submitted a review, later dismissed

2021-12-28 10:42 UTC, PierreRambaud commented on src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Webservice/WebserviceKeyType.php
> +                    ),
```suggestion
                    )
```

Syntax error :)

2021-12-28 10:42 UTC, PierreRambaud requested changes
Syntax error with PHP 7.2

2021-12-28 10:44 UTC, Progi1984 approved these changes

2021-12-28 11:46 UTC, PierreRambaud approved these changes

2021-12-29 08:40 UTC, marwachelly commented
Hello,

PR is tested and the number of needed characthers in the key help is wel displayed :
![image](https://user-images.githubusercontent.com/89604350/147643170-37e57a12-a623-4a42-9aef-5a0a1b1af446.png)

PR ok also for Samsung Galaxy S7 v6.0 :
![image](https://user-images.githubusercontent.com/89604350/147643192-6c989d28-d84d-4286-ae46-9e1faf66db16.png)

Many thanks,

2021-12-29 09:08 UTC, merged

2021-12-29 09:08 UTC, PierreRambaud commented
Thank you @PrestaEdit

2021-12-29 09:16 UTC, PierreRambaud commented
Just notice there were a Waiting for Wording label :roll_eyes: 
We will improve it later, we can do it later :p

2022-01-03 10:14 UTC, Julievrz commented on src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Webservice/WebserviceKeyType.php
> +                        'Key should be at least %length% characters long.',
This is not the right translation domain. It should be Admin.Advparameters.Help

See => https://zeroheight.com/80a6c5a61/v/latest/p/738e72-manage-translation-domains

We also miss the article "The" before "key".