Update links to reach docs.prestashop-project.org instead of doc.prestashop.com
PrestaShop/PrestaShop pull request #27150
Opened 2021-12-30 13:03 UTC by PrestaEdit

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Update links to docs used by the cards into Back Office.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See that helper cards have the new links used.
| Possible impacts? | n/d.

2021-12-31 13:55 UTC, matthieu-rolland approved these changes, later dismissed
nice ! thank you

2022-01-04 09:25 UTC, PierreRambaud requested changes, later dismissed
I don't think it should target the 1.7.8.x branch.
Could you please target the develop branch?

2022-01-04 09:29 UTC, PrestaEdit commented
I could, but it's specific to 1.7 version here. We will need to update again the links for develop branch.

2022-01-07 15:41 UTC, sowbiba submitted a review, later dismissed

2022-01-15 11:47 UTC, PrestaEdit commented
Related to https://github.com/PrestaShop/PrestaShop/issues/24651

2022-01-18 09:09 UTC, PierreRambaud commented
> I could, but it's specific to 1.7 version here. We will need to update again the links for develop branch.

It's legit, but it hasn't been planned to integrate this in 1.7.8.4. Ping @MatShir

2022-01-18 09:14 UTC, MatShir commented
Nice catch, it would be nice to have it for the patch.

2022-01-18 09:14 UTC, MatShir requested changes
@Julievrz ping for a double check :)

2022-01-18 09:14 UTC, MatShir approved these changes

2022-01-18 09:15 UTC, MatShir requested changes
@Julievrz ping for a double check :)

2022-01-18 09:27 UTC, PierreRambaud submitted a review, later dismissed
The boss approves, I have to follow him!

2022-01-18 10:05 UTC, Julievrz commented on src/PrestaShopBundle/Resources/config/services/core/util/helper_card.yml
> +          '_fallback': 'hhttps://docs.prestashop-project.org/1.7-documentation/user-guide/improving-shop/customizing-store-design/pages-managing-static-content'
```suggestion
          '_fallback': 'https://docs.prestashop-project.org/1.7-documentation/user-guide/improving-shop/customizing-store-design/pages-managing-static-content'
```

2022-01-18 10:09 UTC, PrestaEdit commented on src/PrestaShopBundle/Resources/config/services/core/util/helper_card.yml
> +          '_fallback': 'hhttps://docs.prestashop-project.org/1.7-documentation/user-guide/improving-shop/customizing-store-design/pages-managing-static-content'
Nice catch.

2022-01-18 10:12 UTC, Julievrz commented on src/PrestaShopBundle/Resources/config/services/core/util/helper_card.yml
> +          'it': 'https://docs.prestashop-project.org/1.7-documentation/v/italian/guida-utente/configurare-negozio/parametri-avanzati/performance-prestazioni#performance-prestazioni-modalitadidebug'
```suggestion
          'it': 'https://docs.prestashop-project.org/1.7-documentation/v/italian/guida-utente/configurare-negozio/parametri-avanzati/performance-prestazioni#modalita-di-debug'
```

2022-01-18 10:17 UTC, Julievrz commented on src/PrestaShopBundle/Resources/config/services/core/util/helper_card.yml
> +          'fr': 'https://docs.prestashop-project.org/1.7-documentation/v/french/guide-utilisateur/optimiser-boutique/gerer-livraisons'
```suggestion
          'fr': 'https://docs.prestashop-project.org/1.7-documentation/v/french/guide-utilisateur/optimiser-boutique/gerer-livraisons/gerer-transporteurs'
```

2022-01-18 10:31 UTC, Julievrz commented
> @Julievrz ping for a double check :)

Done ✅

2022-01-18 11:15 UTC, MatShir approved these changes, later dismissed

2022-01-27 13:22 UTC, florine2623 commented
Hello @PrestaEdit ,

Could you create an issue  and link it in the PR please ?
Thanks!

2022-01-27 13:34 UTC, PrestaEdit commented
Hi,

There is really a need of ?

Also, I can see that this issue was mentionned by my own (https://github.com/PrestaShop/PrestaShop/issues/24651#ref-pullrequest-1091092616) but don't know when and how it's desapear from here...

2022-01-27 14:01 UTC, florine2623 commented
@PrestaEdit 

As discussed without with @Robin-Fischer-PS , an issue is needed. PM should go over the issue and approve it before we can test it ^^

Thanks!

2022-01-27 15:11 UTC, MatShir commented
Thanks @florine2623 for following the process, but for this PR an issue is not required here. The PR has been checked and approved 2 time by the product. All the information needed seems to be available on the PR description. Unless there is missing information, I think we can test it ;)

2022-01-27 17:14 UTC, florine2623 commented
Thanks for the details @MatShir

@PrestaEdit , thanks for the PR.
After some testing, all the links for "Full documentation" in Helper cards redirect to [doc.prestashop.com](https://doc.prestashop.com/)  :
<img width="432" alt="Screenshot 2022-01-27 at 17 44 28" src="https://user-images.githubusercontent.com/16019289/151404235-9ab951eb-c587-4fbb-ac44-3a344e0ddf37.png">

- In Dashboard
- In Orders > Shopping cart
- In Catalog > Attributes & Features > tab Attributes & In Catalog > Attributes & Features > tab Features
- In Catalog > Discounts > tab Cart Rules & In Catalog > Discounts > tab Catalog Price Rules
- In Customer Service > Customer Service
- In Customer Service > Merchandise Return
- Stats
- Design > Theme & Logo > Pages Configuration & Design > Theme & Logo > Advanced Parameters
- Design > Image Settings
- Shipping > Carriers
- International > Locations > Countries
- International > Taxes > Tax Rules
- Shop Parameters > Order Settings > Statuses
- Shop Parameters > Customer Settings > Groups
- Shop Parameters > Customer Settings > Titles
- Shop Parameters > Contact > Stores
- Shop Parameters > Traffic & SEO > Search Engines
- Shop Parameters > Traffic & SEO > Referrers
- Shop Parameters > Shop > Search & Shop Parameters > Shop > Tags
- Shop Parameters > Merchant Expertise
- Advanced Parameters > Team > Permissions
- Advanced Parameters > Multistore


Also, in search result, there is that :
<img width="262" alt="Screenshot 2022-01-27 at 18 06 45" src="https://user-images.githubusercontent.com/16019289/151408057-f432bd14-cb56-49b3-92e8-c5de59b8e887.png">
It should be updated with the new link

Could you take a look ?
Thanks!

2022-01-27 17:18 UTC, PrestaEdit commented
It's not the goal of this PR, it's about links into Helper Card on some pages.

2022-01-27 17:23 UTC, PrestaEdit commented
Like this one.

<img width="1502" alt="Capture d’écran 2022-01-27 à 18 23 31" src="https://user-images.githubusercontent.com/2631425/151410957-7a5ae07c-8b7d-4ed6-9a0e-8f1084ecccd2.png">

2022-01-27 19:51 UTC, PrestaEdit commented
I've try to add more replace  but there are 5 results that can't be changed, as it was 1.6 version and not available on the doc.

<img width="620" alt="Capture d’écran 2022-01-27 à 20 50 07" src="https://user-images.githubusercontent.com/2631425/151433066-59ce1fa6-4820-4a84-9519-b06eeb0de32e.png">
4

2022-01-28 10:49 UTC, MatShir commented
Oh nice! thanks for the extra work :)
For the rest, It looks like there is no doc as you mentionned it. I will created a dedicated issue. So with @Julievrz, we will see if we need to migrate the doc or use maybe the dev doc for some of it.
We will review your work on thuesday for a double check :)

2022-02-01 21:28 UTC, PrestaEdit commented
Is the waiting for author still available ?

2022-02-02 08:57 UTC, Robin-Fischer-PS commented
Hi,

I changed to Waiting for Dev because it needs review before getting back to QA.

2022-02-02 09:07 UTC, Progi1984 approved these changes

2022-02-02 16:01 UTC, Julievrz approved these changes
Thanks!

2022-02-11 11:05 UTC, florine2623 commented
Hello @PrestaEdit ,

LGTM, it is QA ✅ !

2022-02-11 13:04 UTC, merged

2022-02-11 13:04 UTC, Progi1984 commented
Thanks @PrestaEdit & @florine2623