Fix replaceAccentedChars function
PrestaShop/PrestaShop pull request #27176
Opened 2022-01-03 17:00 UTC by davidglezz

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix replaceAccentedChars by adding some missing accented chars.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | Check `testReplaceAccentedChars()`
| Possible impacts? | Now some characters that were not done before are unaccented.

My test function:
```php
    public function testReplaceAccentedChars(): void
    {
        // https://en.wikipedia.org/wiki/Tilde
        // https://en.wikipedia.org/wiki/List_of_Unicode_characters
        // https://graphemica.com/
        $testStrings = [
            'aáàäâAÁÀÄÂ' => 'aaaaaAAAAA',
            'eéèëêEÉÈËÊ' => 'eeeeeEEEEE',
            'iíìïîIÍÌÏÎĨ' => 'iiiiiIIIIII',
            'oóòöôOÓÒÖÔ' => 'oooooOOOOO',
            'uúùüûUÚÙÜÛ' => 'uuuuuUUUUU',
        ];

        foreach ($testStrings as $testString => $expected) {
            $actual = MotiveStrTools::replaceAccentedChars($testString);
            $this->assertEquals($expected, $actual);
        }
    }

```

2022-01-04 17:11 UTC, matks reviewed
@davidglezz as you have some clear usecases for this function, what about we add them inside a unit test 😉  ?

See https://github.com/PrestaShop/PrestaShop/blob/develop/tests/Unit/Classes/ToolsTest.php

2022-01-05 11:19 UTC, matthieu-rolland reviewed
lgtm, unit test welcome 👍

2022-01-06 09:50 UTC, matks requested changes, later dismissed
Still waiting for tests 😉

2022-01-06 23:11 UTC, davidglezz commented
Done!

2022-01-09 11:57 UTC, davidglezz commented
Regarding readability vs performance:
This is much more readable but 10% slower.
```php
    $patterns = [
        'a' => '/[ªàáâãäåāăąǎǻɑаạảấầẩẫậắằẳẵặ]/u',
        'b' => '/[б]/u',
        ...
    ];
    return preg_replace(array_values($patterns), array_keys($patterns), $str);
```

This only is 10% slower on first call.
```php
function replaceAccentedChars3($str)
{
    static $from = null;
    static $to = null;

    if ($from === null) {
        $patterns = [
            'a' => '/[ªàáâãäåāăąǎǻɑаạảấầẩẫậắằẳẵặ]/u',
            'b' => '/[б]/u',
            ...
        ];
        $from = array_values($patterns);
        $to = array_keys($patterns);
    }

    return preg_replace($from, $to, $str);
}
```

2022-02-07 14:15 UTC, atomiix commented on classes/Tools.php
> +            $transliterator = transliterator_create('Any-Latin; Latin-ASCII');
Maybe use the object oriented way?
```suggestion
            $transliterator = Transliterator::create('Any-Latin; Latin-ASCII');
```

2022-02-07 14:15 UTC, atomiix commented on classes/Tools.php
> +        return transliterator_transliterate($transliterator, $str);
```suggestion
        return $transliterator->transliterate($str);
```

2022-02-10 21:53 UTC, davidglezz commented
@atomiix done

2022-02-11 10:48 UTC, atomiix approved these changes

2022-02-28 22:58 UTC, davidglezz commented
Please remove "Waiting for author" label, or do you need something else?

2022-03-14 08:19 UTC, Progi1984 approved these changes

2022-03-15 13:31 UTC, PierreRambaud approved these changes

2022-03-18 09:40 UTC, AureRita commented
Hi @davidglezz ,

Thank you for you pr but can you create an issue or feature to allow to the QA team to have few steps to follow to test your pr please ? :) 

that will allow us to test it quickly

2022-03-19 11:43 UTC, davidglezz commented
This started as a simple bugfix, but now, it's so much more.
My start use case is as simple as: call `Tools::replaceAccentedChars($testString);` does not return expected string. (See the description). That's why I didn't create an issue and did a PR directly.

Well, looking for related issues I see that this PR fixes some of them:

## This PR Fixes
- My basic use case
- Allow friendly URLs to turn Greek into Latin characters #21978
   - Ελένη → Elene
- Many other scenarios! https://github.com/PrestaShop/PrestaShop/pull/27176#issuecomment-1008283735

```php
echo Tools::replaceAccentedChars('キャンパス  - Αλφαβητικός Κατάλογος - биологическом');
//> kyanpasu  - Alphabetikos Katalogos - biologiceskom
```

## Requires a decision: Locale dependent:
- Incorrect accented chars replacement for ö and ä #26157 #26160
This PR could also fix this, but it requires a decision, because they are locale-dependent transformations and might not be right for everyone.
  - https://github.com/PrestaShop/PrestaShop/issues/26157#issuecomment-1072994521

## Inconsistencies between js and php implementation
Can be solved in other PR. My proposal is to deprecate the current js function and add a new one that makes a ajax call to the backend that uses this PHP function `Tools::replaceAccentedChars()`.


## Unrelated issues:
- Bug on "reset url" button of the product pages when "Accented URLs" is enabled and there are special characters in the product name #21495
  - URL Rewrite problem #20090

2022-03-28 15:33 UTC, AureRita requested changes, later dismissed
Hi @davidglezz 

I tested your pr and : 

I tested your first lane (with a) with and without your pr ass you can see : 
![image](https://user-images.githubusercontent.com/100699445/160431619-f72ff028-0a10-4df9-9b97-1e92606bb60c.png)

that was the friendly url : 
![image](https://user-images.githubusercontent.com/100699445/160431730-f30b944f-c961-4970-b12f-5aa0fa73898d.png)

Moreover, I also test the issue you linked ( that why they are linked ) : 
for Ελένη that doesn't wirte "Elene", that write nothing, as you can see  : 
![image](https://user-images.githubusercontent.com/100699445/160433401-5ae05a40-b6dd-42d6-aec3-0c9118b6f92a.png)

For other characters that also change nothing : 
![image](https://user-images.githubusercontent.com/100699445/160433766-abff9ac0-c2fb-4798-b085-ce391631fc5b.png)

2022-04-03 18:48 UTC, davidglezz commented
@AureRita thanks for your time.
This PR is (depending on the point of view) an improvement or bugfix of `replaceAccentedChars` function.

This function is used by:
- Search & search alias
- `str2url` & `slugify`
- `smartyClassname`

I think you've tried to test it by using the `str2url` function, but doing it with the "Reset URL" button in the product page is using the similar `str2url` javascript function.

In another PR I want to modify that javascript function so that it uses the `str2url` function of the backend (PHP) so that there is consistency and there are no more issues regarding this topic.

2022-04-04 15:13 UTC, AureRita commented
hi @davidglezz, 

Thank you for your answer, Currently, I don't how to test these type of variable so can you explain to me how can i test 
Search & search alias
str2url & slugify
smartyClassname
with your pr to accept or not your pr,

2022-04-05 13:00 UTC, davidglezz commented
I have unlinked #21978 form the description table because does not fully fixes it, but I think this is the first step to fix it.

@AureRita I think that since it is a php function, it cannot be tested directly from the user interface, I suppose it is fine if the unit tests and the automated tests pass.

2022-04-07 09:10 UTC, AureRita commented
hi @davidglezz , 

Indeed, so we will run an automated test on it, 
can you @PrestaShop/prestashop-core-developers check for the unit test ? Thank you in advance

2022-04-12 15:31 UTC, AureRita commented
Hi @davidglezz ,

I ran an automated test on it, and it haven't issues, now we will wait the dev team

2022-04-13 14:52 UTC, atomiix commented
@AureRita the code has been approved with unit tests and the CI is green so I think it's okay

2022-04-14 09:02 UTC, AureRita approved these changes

2022-04-14 09:50 UTC, merged

2022-04-14 09:51 UTC, Progi1984 commented
Thanks @davidglezz & @AureRita