Add new hook `actionFilterDeliveryOptionList`
PrestaShop/PrestaShop pull request #27223
Opened 2022-01-05 15:30 UTC by PululuK

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Allow modules to modify delivery option list result.
| Type?             | new feature 
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/27222
| How to test?      | See https://github.com/PrestaShop/PrestaShop/issues/27222
| Possible impacts? | N/A

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/27223)

2022-01-06 09:47 UTC, matks requested changes, later dismissed
PHP CS fixer is not happy 😭

2022-01-12 16:07 UTC, atomiix approved these changes

2022-01-12 16:17 UTC, kpodemski approved these changes

2022-01-13 14:35 UTC, florine2623 commented
Hello @PululuK ,

Thanks for the PR, it is QA ✅ !

2022-01-13 15:40 UTC, merged

2022-01-13 15:40 UTC, Progi1984 commented
Thanks @PululuK & @florine2623