Improve CMS edit page footer
PrestaShop/PrestaShop pull request #27225
Opened 2022-01-05 16:21 UTC by Hlavtox

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | This PR turns two buttons into btn group on smaller screens. Drops up and left.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26633
| How to test?      | Compare before and after.
| Possible impacts? | 

**Screenshot**
![Multimédia1](https://user-images.githubusercontent.com/6097524/142880614-7f73b53c-dc05-4fbe-9c54-648122dc99ae.gif)

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/26704)

2022-01-05 16:23 UTC, Hlavtox commented
@PierreRambaud 
Replacement of https://github.com/PrestaShop/PrestaShop/pull/26704
I needed to redo it, I screwed up by branch by accidentaly rebasing it on develop.
There are no duplicate IDs, names can be duplicate.

Thanksssss.

2022-01-06 08:26 UTC, NeOMakinG approved these changes

2022-01-06 13:28 UTC, matthieu-rolland approved these changes

2022-01-06 21:04 UTC, matks approved these changes

2022-01-07 15:30 UTC, hibatallahAouadni commented
Hello @Hlavtox 

Thanks for your PR!
But it seems you foget the Cart Rules page, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/148566548-15b178d4-46cb-4f4e-ae37-9cb614d9dfac.png)

Please check and feedback.
Thanks!

2022-01-07 15:53 UTC, Hlavtox commented
@hibatallahAouadni :D
![Výstřižek](https://user-images.githubusercontent.com/6097524/148569646-6fec72a5-0c51-48d8-a7b1-f2f1e2797d29.JPG)

2022-01-07 16:02 UTC, hibatallahAouadni commented
@Hlavtox I know you're a generous :grin: so could you please fix it :pray:

2022-01-07 16:07 UTC, Hlavtox commented
@hibatallahAouadni We need to discuss payment details on Slack 💰

2022-01-07 19:49 UTC, hibatallahAouadni commented
@Hlavtox Well then as we discussed on Slack, I create a new issue for the cart rule bug #27277
So, this PR is QA :heavy_check_mark:

2022-01-10 07:11 UTC, Progi1984 requested changes
DON'T MERGE : WAIT FOR 1783 RELEASE

2022-01-27 10:09 UTC, Progi1984 approved these changes

2022-01-27 10:10 UTC, merged

2022-01-27 10:10 UTC, Progi1984 commented
Thanks @Hlavtox & @hibatallahAouadni