Fix customer grid data factory
PrestaShop/PrestaShop pull request #27236
Opened 2022-01-06 10:54 UTC by rsoulard-prolaser

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | An error occurson Customer view page when using the actionCustomerGridQueryBuilderModifier hook to add a field from another table.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27235.
| How to test?      | Install module https://github.com/PrestaShop/demo-cqrs-hooks-usage-module and go to the Customer view page
| Possible impacts? | Customer view page

2022-01-06 13:20 UTC, matthieu-rolland reviewed
LGTM

let's wait for the qa team to reproduce your issue before validation 👍

2022-01-06 21:06 UTC, matks submitted a review, later dismissed

2022-01-07 16:20 UTC, PululuK approved these changes, later dismissed

2022-01-10 09:30 UTC, MatShir submitted a review, later dismissed
Hi @rsoulard-prolaser, 
The bug fix from your PR is a regression, could you change the branch to `1.7.8.x` ? So users can benefit to your fix in the next patch release ;)

2022-01-10 09:48 UTC, rsoulard-prolaser commented
Hello @MatShir,
I'm not sure how I should proceed, can you help me?

2022-01-10 10:19 UTC, rsoulard-prolaser commented
Hi @MatShir,
It's done.

2022-01-10 10:19 UTC, kpodemski approved these changes

2022-01-10 15:00 UTC, atomiix approved these changes

2022-01-10 16:34 UTC, PululuK approved these changes

2022-01-12 10:12 UTC, florine2623 commented
Hello @rsoulard-prolaser ,

Thanks for the PR, it is QA ✅ !

2022-01-12 10:13 UTC, Progi1984 requested changes
WAIT FOR 1783 RELEASE

2022-01-28 20:48 UTC, Progi1984 approved these changes

2022-01-28 21:04 UTC, merged

2022-01-28 21:05 UTC, Progi1984 commented
Thanks @rsoulard-prolaser & @florine2623