Functional tests - Add new test 'Check multi invoice'
PrestaShop/PrestaShop pull request #27260
Opened 2022-01-07 10:05 UTC by nesrineabdmouleh

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add new test 'Check multi invoice'
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | no need
| Possible impacts? | no

2022-01-10 15:42 UTC, boubkerbribri commented on tests/UI/pages/BO/orders/view.js
> +    await page.waitForTimeout(2000);
We should find a solution to delete this.

2022-01-10 15:42 UTC, boubkerbribri commented on tests/UI/pages/BO/orders/view.js
> +  }
Can we create a more generic function to select from the option with the option by default is `'Create a new invoice'`

2022-01-11 12:21 UTC, boubkerbribri approved these changes, later dismissed

2022-01-19 10:27 UTC, PierreRambaud requested changes, later dismissed
Could you please fix conflicts? :)

2022-01-19 15:19 UTC, boubkerbribri approved these changes

2022-01-19 15:22 UTC, Progi1984 approved these changes

2022-01-19 16:15 UTC, merged

2022-01-19 16:15 UTC, Progi1984 commented
Thanks @nesrineabdmouleh