Fixed Product description block width.
PrestaShop/PrestaShop pull request #27279
Opened 2022-01-07 20:55 UTC by rickygzz

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 1.7.8.x
| Description?      | Fixes ticket, adding a new row for Product Description with one full size column.
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27278
| How to test?      | 1. Go to the FO.<br>2. Select any given product.<br>3. Watch for product description block. It should be full with for any width size (including greater than 767px)
| Possible impacts? | None.

2022-01-07 21:06 UTC, Hlavtox commented
LGTM

2022-01-07 21:06 UTC, Hlavtox commented on themes/classic/templates/catalog/product.tpl
> +{/block}
Add empty line to the end pls

2022-01-07 21:24 UTC, rickygzz commented on themes/classic/templates/catalog/product.tpl
> +{/block}
Perfect!

2022-01-10 09:05 UTC, matthieu-rolland reviewed
thank you for your contribution @rickygzz !

it's LGTM for me, but we must wait for the QA team to have tested your issue 👍

2022-01-10 10:46 UTC, sowbiba commented
> thank you for your contribution @rickygzz !
> 
> it's LGTM for me, but we must wait for the QA team to have tested your issue +1

QA reproduced it, we are waiting for @PrestaShop/product-team

2022-01-13 14:03 UTC, PierreRambaud requested changes
I'm not sure it should target the 1.7.8.x branch.
Please target the develop branch, and properly fill the description table ;)

2022-03-14 13:49 UTC, matks commented
It looks like this PR is stale for more than one month. I close it. If you wish to reopen just ping me ;)

2022-03-14 13:49 UTC, closed without merging