Set rightSidebar as global scoped
PrestaShop/PrestaShop pull request #27335
Opened 2022-01-13 02:57 UTC by Guisardo

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | PageSpeed mod for Apache server bundles the javascript for delivery optimization but that is not compatible with the new versions of file https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/default/js/bundle/default.js The incompatibility arises because an incorrect scope of a javascript declaration. That file loads the global rightSidebar using "const" but, as explained here: https://www.freecodecamp.org/news/var-let-and-const-whats-the-difference/#const , "const" is block scoped. If rightSidebaris going to be globally used, "var" should be used instead (https://www.freecodecamp.org/news/var-let-and-const-whats-the-difference/#var). Although global variables are discouraged, the rightSidebar is designed as a global variables, changing that behavior will require a refactor of the code.... rightSidebar was declared using "var" a few months ago. The change was introduced at this huge eslint PR: https://github.com/PrestaShop/PrestaShop/pull/22999/files#diff-652322c22d05461f6ff2962e23cceb8958b2d7cabbc2e2cc0485aefdd827eb13L21 Please, consider a rollback to "var" or assign it as a window property until a refactor of that code is applied.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27180.
| How to test?      | (in a server with PageSpeed JS optimizer enabled https://www.modpagespeed.com/doc/filter-js-combine, and with the PS experimental features disabled) 1.- Go to the products section of the BO 2.- Go to the details page of a specific product with combinations 3.- Go to the combinations section 4 .- Click on the pen icon of a combination 5 .- You will not be able to edit the combination
| Possible impacts? | There is no secondary impact.

2022-01-19 10:13 UTC, PierreRambaud approved these changes

2022-02-04 12:54 UTC, matks approved these changes
I think this PR should be tested by developers @Robin-Fischer-PS

2022-02-04 13:26 UTC, Robin-Fischer-PS commented
Agreed @matks , I add the Waiting for dev :)

2022-03-10 09:59 UTC, Progi1984 requested changes
@Guisardo I remove the label "Waiting for QA" as the issue has not been validated by the @PrestaShop/qa-functional team. Please validate with them the issue.

2022-04-19 10:02 UTC, matks commented
Hello,

It looks like this PR is now stale. I close it as our rules state it "Pull Requests may be closed after 30 days of inactivity following a request for modifications." (https://www.prestashop-project.org/maintainers-guide/reviewing-pull-requests/)

Thank you

2022-04-19 10:02 UTC, closed without merging