Fix default value for Jquery colorpicker
PrestaShop/PrestaShop pull request #27330
Opened 2022-01-12 13:35 UTC by sowbiba

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | 2 fixes done : <ul><li>Use element in forEach callback instead of this (which refer to parent component)</li><li>Use `$t.prop('tagName')` instead of `$t[0].nodeName` to get HTML element type</li></ul><br>We also replace `var` by `let` / `const` to declare variables
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27249
| How to test?      | Look at issue description
| Possible impacts? | Check colorpickers inside BO, including when multistore is enabled

2022-01-12 13:48 UTC, atomiix approved these changes, later dismissed

2022-01-12 14:01 UTC, PululuK approved these changes, later dismissed

2022-01-12 15:58 UTC, jolelievre reviewed
I'm not sure it's a good idea to modify code that was copied as external dependency Especially since you use ES6 code (let, const, ...) in a ES5 script that is not rebuilt by esbuild

But I may be wrong, maybe @NeOMakinG should confirm this?

2022-01-12 16:06 UTC, NeOMakinG requested changes
Please revert every `var` changed, just add the fix for the issue

I really think that except if you're using a preprocessor, don't use ES6+ features

Even if it's pretty supported now, we never know, and it's not transpiled to syntax < ES5 syntax

2022-01-12 16:16 UTC, NeOMakinG approved these changes, later dismissed

2022-01-12 16:27 UTC, saulaski commented on js/jquery/plugins/jquery.colorpicker.js
> +        $.fn.mColorPicker.setTextColor(input);
Warning: argument passed to `setTextColor(element)` method is treated as a jQuery object.
Here the input argument should be wrapped first : 
```suggestion
        $.fn.mColorPicker.setTextColor($(input));
```
Or even better, just wrap the argument of any type in `setTextColor(element)` method : 
```
        $.fn.mColorPicker.setTextColor = function(element) {
          element = $(element);
          // ...
```

2022-01-12 16:27 UTC, saulaski commented on js/jquery/plugins/jquery.colorpicker.js
> +    if ($t.prop('tagName').toLowerCase() != 'input') return false;
```suggestion
    if (!$t.is('input')) return false;
```

2022-01-12 16:40 UTC, saulaski commented on js/jquery/plugins/jquery.colorpicker.js
> +        $.fn.mColorPicker.setTextColor(input);
Forget my warning please : items in `inputs` array are jQuery objects already.

2022-01-13 09:26 UTC, NeOMakinG approved these changes

2022-01-14 11:01 UTC, jolelievre approved these changes

2022-01-17 12:54 UTC, PululuK approved these changes

2022-01-20 13:26 UTC, khouloudbelguith approved these changes
Hi @sowbiba,

It is ok :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/16067358/150346614-de47e3bb-517a-4c16-92eb-c8c7c24c842e.png)
![image](https://user-images.githubusercontent.com/16067358/150346680-7694143b-2477-4224-9d8a-35f2a27c997f.png)

https://user-images.githubusercontent.com/16067358/150347344-50d28ede-c873-45ab-9096-7eec8e48b31a.mp4

Thanks!

2022-01-20 13:33 UTC, Progi1984 requested changes
WAIT FOR 1783 RELEASE

2022-01-28 20:19 UTC, Progi1984 approved these changes

2022-01-28 20:19 UTC, merged

2022-01-28 20:19 UTC, Progi1984 commented
Thanks @sowbiba & @khouloudbelguith