Fix wrong array_slice arguments
PrestaShop/PrestaShop pull request #27374
Opened 2022-01-17 14:38 UTC by atomiix

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Because of wrong argument in the method `array_slice` in charge of getting the right amount of products when ordering by price, the list of product returned was wrong. This PR fixes it by using the right arguments.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27146
| How to test?      | Please see #27146
| Possible impacts? |

2022-01-18 08:58 UTC, PierreRambaud approved these changes

2022-01-18 09:04 UTC, saulaski approved these changes
Looks much better, thank you @atomiix

2022-01-18 10:24 UTC, sowbiba approved these changes

2022-01-19 13:38 UTC, marwachelly commented
Hello,

PR is tested and the issues are fixed.  Thanks @atomiix 
https://watch.screencastify.com/v/r3xHUmXtCJscjEJCGkDx

2022-01-19 14:09 UTC, Progi1984 requested changes
WAIT FOR 1783 RELEASE

2022-01-29 12:13 UTC, Progi1984 approved these changes

2022-01-29 12:29 UTC, merged

2022-01-29 12:29 UTC, Progi1984 commented
Thanks @atomiix & @marwachelly