Remove z-index and overflow of product description of product list
PrestaShop/PrestaShop pull request #27387
Opened 2022-01-18 13:31 UTC by NeOMakinG

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | There is a problem where you can't see the rating of productcomments because of some styles on product lists
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27252.
| How to test?      | To be tested with https://github.com/PrestaShop/productcomments/pull/130 at the same time, see issue in order to have some more test informations
| Possible impacts? | Product list description

2022-01-18 13:33 UTC, matthieu-rolland approved these changes

2022-01-19 09:18 UTC, saulaski approved these changes

2022-01-19 09:39 UTC, PierreRambaud approved these changes

2022-01-31 13:00 UTC, marwachelly requested changes
Hello, 

I tested this PR with [PrestaShop/productcomments#130](https://github.com/PrestaShop/productcomments/pull/130). The grade is now displayed in the Product list page but the following error exists 
![image](https://user-images.githubusercontent.com/89604350/151797449-3551a3a6-79cd-487d-b342-31f90ac868c7.png)
I noticed also the following error when I run the command npm install 
![image](https://user-images.githubusercontent.com/89604350/151797580-a3a50115-191c-4603-a04f-dcd0b596be1f.png)
Could you please check ? 

Thanks,

2022-02-01 09:02 UTC, NeOMakinG commented
@marwachelly https://github.com/PrestaShop/productcomments/pull/130#issuecomment-1026612137

2022-02-02 10:36 UTC, marwachelly approved these changes
PR is ok. Issue is fixed. Thanks @NeOMakinG
https://watch.screencastify.com/v/axqDIA9TxLhIi3wo5j0P

2022-02-02 12:03 UTC, merged

2022-02-02 12:03 UTC, Progi1984 commented
Thanks @NeOMakinG & @marwachelly