Add the minimum required to the error message, when trying to apply a cart rule with a minimum
PrestaShop/PrestaShop pull request #27397
Opened 2022-01-19 13:22 UTC by Prestaplugins

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add the minimum required to the error message, when trying to apply a cart rule with a minimum
| Type?             | improvement
| Category?         | FO / CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     |
| How to test?      | Create a voucher with a minimum, add some product to the cart but with a total lower than the minimum of the voucher, and try to apply the voucher to the cart. The error message should display the minimum amount.
| Possible impacts? |

2022-01-19 15:23 UTC, Julievrz commented on classes/CartRule.php
> +                return (!$display_error) ? false : $this->trans('You have not reached the %s minimum amount required to use this voucher', [$context->getCurrentLocale()->formatPrice($minimum_amount,
```suggestion
                return (!$display_error) ? false : $this->trans('The minimum amount to benefit from this promo code is %s.', [$context->getCurrentLocale()->formatPrice($minimum_amount, $context->currency->iso_code)], 'Shop.Notifications.Error');
```

This is a great idea to add the minimum amount. The error message is more useful to the user that way. I suggest using "promo code" to stay consistent with the wording used in the front office (see screenshot). I also tried to adopt a more positive tone. :-) See the Content style guide: https://zeroheight.com/80a6c5a61/v/latest/p/510e8a-components/b/2943bd 

![image](https://user-images.githubusercontent.com/70583503/150160776-3ed04f4d-2fd6-4f9d-9480-2124f4a2faf3.png)

2022-01-20 22:00 UTC, matks requested changes

2022-01-20 22:00 UTC, matks commented on classes/CartRule.php
> +                return (!$display_error) ? false : $this->trans('You have not reached the %s minimum amount required to use this voucher', [$context->getCurrentLocale()->formatPrice($minimum_amount,
The tests reported a usecase where this code fails

```
001 Scenario: cart rule with minimum amount doesn't apply if cart total is lower # Features/Scenario/Cart/Adding/CartRule/minimum_amount_cartrule.feature:12
      When I delete product "product1" from cart "dummy_custom_cart"             # Features/Scenario/Cart/Adding/CartRule/minimum_amount_cartrule.feature:42
        Fatal error: Call to a member function formatPrice() on null (Behat\Testwork\Call\Exception\FatalThrowableError)
```

`$context->getCurrentLocale()` can be null in some circumstances

2022-04-01 20:06 UTC, kpodemski commented on classes/CartRule.php
> +                return (!$display_error) ? false : $this->trans('You have not reached the %s minimum amount required to use this voucher', [$context->getCurrentLocale()->formatPrice($minimum_amount,
```suggestion
                return (!$display_error) ? false : $this->trans('You have not reached the %s minimum amount required to use this voucher', [Tools::getContextLocale($context)->formatPrice($minimum_amount, $context->currency->iso_code)], 'Shop.Notifications.Error');
```

2022-04-01 20:07 UTC, kpodemski commented
Hello @Prestaplugins 

Any chance for you to apply our feedback to your PR? It looks like a good improvement. It's worth having it in the core. Thank you.

2022-04-04 09:48 UTC, kpodemski commented
Hi @Prestaplugins 

You forgot to apply the wordings recommendation.
https://capture.dropbox.com/YpOXAE0IDXBaT6Qe

2022-04-11 06:49 UTC, Progi1984 approved these changes

2022-04-11 12:15 UTC, Julievrz approved these changes
Wording ✔️

2022-04-22 20:18 UTC, matks approved these changes

2022-04-22 20:19 UTC, matks commented
I improved a little the "How to test?"

2022-04-22 20:42 UTC, kpodemski approved these changes

2022-04-27 14:50 UTC, AureRita approved these changes
Hi @Prestaplugins 

Thank you for your PR, I tested it and it works, as you can see here :

https://user-images.githubusercontent.com/100699445/165546425-69bf6e47-77a2-482e-b46d-dc13c99880e5.mp4

2022-04-27 15:37 UTC, merged

2022-04-27 15:37 UTC, Progi1984 commented
Thanks @Prestaplugins & @AureRita