Don't fail when there are invalid id_order_state values on orders
PrestaShop/PrestaShop pull request #27403
Opened 2022-01-19 17:07 UTC by bogdanbeniaminb

Don't fail when there are invalid id_order_state values on orders (`null`, `0` or references to hard deleted order states).

This PR fixes issue https://github.com/PrestaShop/PrestaShop/issues/27402 and is somehow completing the work done with PR https://github.com/PrestaShop/PrestaShop/pull/19581. 

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 1.7.8.x
| Description?      | This PR fixes a bug that affects current the current develop branch, as well as older releases (1.7.7.0, 1.7.8.0). The bug is due to a logic flaw in handling null values (for more info, see [issue](https://github.com/PrestaShop/PrestaShop/issues/27402)).
| Type?             | bug fix / improvement / new feature / refacto / critical
| Category?         | FO / BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27402 .
| How to test?      | First case: Create a custom order state, assign it to an order, then delete it directly from the database. Try to access the order in the backoffice. Before the PR, you will receive a notice. After the PR, no notices are thrown. Second case: Set the `id_order_state` to `null` or `0` for an order. Again, try to access it from the backoffice.
| Possible impacts? | No impacts.

2022-01-19 17:11 UTC, bogdanbeniaminb commented
The PR affects both BO and FO, thus the BO/FO category. The `Order::getCustomerOrders` method can be called both in the backoffice (when viewing a customer) and on the frontend (when accessing the order details from the Account section).

2022-01-19 19:13 UTC, davidglezz requested changes

2022-01-19 19:13 UTC, davidglezz commented on classes/order/Order.php
> +            $res[$key]['order_state_color'] = $orderState['color'] ?? null ?: null;
Instead of having a bunch of conditionals and null coalescence , it can be as simple as an initial check:
```suggestion
            if (empty($val['id_order_state']) || empty($indexedOrderStates[$val['id_order_state']])) {
                continue;
            }
            
            $orderState = $indexedOrderStates[$val['id_order_state']];
            $res[$key]['order_state'] = $orderState['name'];
            $res[$key]['invoice'] = $orderState['invoice'];
            $res[$key]['order_state_color'] = $orderState['color'];
```
or if we need both `['order_state']` and `['order_state_color']` to be defined:

```suggestion
            if (empty($val['id_order_state']) || empty($indexedOrderStates[$val['id_order_state']])) {
                $res[$key]['order_state'] = $res[$key]['order_state_color'] = null;
                continue;
            }
            
            $orderState = $indexedOrderStates[$val['id_order_state']];
            $res[$key]['order_state'] = $orderState['name'];
            $res[$key]['invoice'] = $orderState['invoice'];
            $res[$key]['order_state_color'] = $orderState['color'];
```

2022-01-20 07:11 UTC, bogdanbeniaminb commented on classes/order/Order.php
> +            $res[$key]['order_state_color'] = $orderState['color'] ?? null ?: null;
Yes, you're right, @davidglezz. I applied your second suggestion. Thank you!

2022-01-24 10:37 UTC, davidglezz requested changes

2022-01-24 10:37 UTC, davidglezz commented on classes/order/Order.php
> +
```suggestion

```
To pass CI, I removed the unwanted spaces which is required by cs fixer

2022-01-24 10:38 UTC, bogdanbeniaminb commented on classes/order/Order.php
> +
Thank you, @davidglezz !

2022-01-24 21:25 UTC, matks approved these changes
Thank you for the very detailed explanations you wrote in https://github.com/PrestaShop/PrestaShop/issues/27402

I approve this code change

2022-01-25 17:57 UTC, davidglezz approved these changes

2022-02-02 11:24 UTC, atomiix approved these changes

2022-02-08 13:37 UTC, khouloudbelguith requested changes
Hi @bogdanbeniaminb,

I have an issue following these steps:
1. Create an order status
2. Create an order & change the status of this order to the last order status created
3. Delete the Order status from the database manually
4. Go to BO > Orders > View the last order created
5. See error 

![image](https://user-images.githubusercontent.com/16067358/152997862-ec16157a-e283-4b93-8635-9a506e3d9f5e.png)

I tried to view the customer => ok
![image](https://user-images.githubusercontent.com/16067358/152997979-63d68adb-886e-4ead-a183-ce24abe56645.png)

Thanks!

2022-02-08 23:20 UTC, davidglezz commented
> 3. Delete the Order status from the database manually

I would say that is easy to cause errors if someone manually modify the database.
managing these situations is the responsibility of the code?

2022-02-28 20:29 UTC, matks commented
> > 3. Delete the Order status from the database manually
> 
> I would say that is easy to cause errors if someone manually modify the database. managing these situations is the responsibility of the code?

This test was performed because the PR description states it:

```
First case: Create a custom order state, assign it to an order, then delete it directly from the database. Try to access the customer in the backoffice. Before the PR, you will receive a notice. After the PR, no notices are thrown. Second case: Set the id_order_state to null or 0 for an order. Again, try to access the customer from the backoffice.
```


<br class="Apple-interchange-newline">

2022-04-19 09:46 UTC, matks commented
Hello,

It looks like this PR is now stale. I close it as our rules state it "Pull Requests may be closed after 30 days of inactivity following a request for modifications." (https://www.prestashop-project.org/maintainers-guide/reviewing-pull-requests/)

If you come back, please ping me I can reopen the contribution 😄 

Thank you

2022-04-19 09:46 UTC, closed without merging

2022-04-19 10:07 UTC, davidglezz commented
@matks if this PR is usefull I can open a new PR

2022-04-19 11:54 UTC, matks commented
@davidglezz thank you for the suggestion 👍 

if you are able to find out why QA team found a problem and fix it it could be a very nice addition to the project