Update BO architecture in product settings page
PrestaShop/PrestaShop pull request #27440
Opened 2022-01-24 09:04 UTC by PierreRambaud

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Reorganize fields n BO > shop parameters > product settings page for a better architecture
| Type?             | improvement 
| Category?         | BO
| BC breaks?        | yes / no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24769.
| How to test?      | BO > shop parameters > product settings verify if fields are saved correctly 
| Possible impacts? | Product pages in FO

2022-01-31 11:13 UTC, nesrineabdmouleh commented
hello @PierreRambaud, @kevin-xtn
When updating UI tests, I found that the last label is missing on Product Settings block
=> See attached screenshot

![screenshot](https://user-images.githubusercontent.com/24647495/151781829-b2d7e65d-d595-45d7-b81b-4ebea9a47144.png)

Thank you
Nesrine

2022-01-31 15:56 UTC, jolelievre approved these changes
Thanks @PierreRambaud

2022-01-31 15:57 UTC, jolelievre reviewed
Oh actually there is a feedback from QA tests

2022-01-31 15:58 UTC, jolelievre requested changes, later dismissed
Seems like a label is missing

2022-02-15 09:29 UTC, atomiix approved these changes, later dismissed

2022-03-04 10:53 UTC, matthieu-rolland approved these changes, later dismissed

2022-03-07 16:58 UTC, florine2623 requested changes, later dismissed
Hello @PierreRambaud ,

I have some differences between the [mockup](https://github.com/PrestaShop/PrestaShop/issues/24769#issue-909577901) and the result with PR.

What I have :
<img width="211" alt="Screenshot 2022-03-07 at 16 23 46" src="https://user-images.githubusercontent.com/16019289/157074427-f83490ca-7821-4ac4-9b13-23d80e653098.png">
What I should have : 
<img width="211" alt="Screenshot 2022-03-07 at 16 23 51" src="https://user-images.githubusercontent.com/16019289/157074527-c90d99d7-9fc8-4ddf-a2af-fc7d1986e0e3.png">

Here are some changes to add in Product Stock block :
<img width="1125" alt="Screenshot 2022-03-07 at 17 46 40" src="https://user-images.githubusercontent.com/16019289/157080879-9676724a-93e9-4201-afbc-04887adbd5c8.png">


Could you check please ?
Thanks!

2022-03-18 14:12 UTC, PierreRambaud commented
> Hello @PierreRambaud ,
> 
> I have some differences between the [mockup](https://github.com/PrestaShop/PrestaShop/issues/24769#issue-909577901) and the result with PR.
> 
> What I have : <img alt="Screenshot 2022-03-07 at 16 23 46" width="211" src="https://user-images.githubusercontent.com/16019289/157074427-f83490ca-7821-4ac4-9b13-23d80e653098.png"> What I should have : <img alt="Screenshot 2022-03-07 at 16 23 51" width="211" src="https://user-images.githubusercontent.com/16019289/157074527-c90d99d7-9fc8-4ddf-a2af-fc7d1986e0e3.png">
> 
> Here are some changes to add in Product Stock block : <img alt="Screenshot 2022-03-07 at 17 46 40" width="1125" src="https://user-images.githubusercontent.com/16019289/157080879-9676724a-93e9-4201-afbc-04887adbd5c8.png">
> 
> Could you check please ? Thanks!

It's a first improvement.
I can't change all wordings as wordings has been accepted by @Julievrz and if we change them, we have to change a lot  of things.
I also can't remove the field at the bottom as it's a new field that has been added after mockup

2022-03-22 11:12 UTC, Julievrz commented
The thing is that, on the mockups, it's written "Stock management" because the toggle button indicates "Enabled/Disabled" instead of "Yes/No". It makes sense. But if the toggle button is "Yes/No" (and I think it can't be changed to "Enabled/Disabled" that easily*), then it's clearer to start with a verb "Enable stock management" (?) "Yes/No".

* An issue was opened about this: https://github.com/PrestaShop/PrestaShop/issues/19142

I agree with @PierreRambaud that wording improvements could be done later (linked to the issue I've just mentioned).

2022-03-22 11:17 UTC, Julievrz commented on src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/product_preferences_stock.html.twig
> +          {{ ps.label_with_help(('Order out-of-stock products'|trans), ('By default, the "%add_to_cart_label%" button is hidden when a product is unavailable. You can choose to have it displayed in a
Let's stick with the current wording. We'll change it later if necessary when the toggle buttons are modified. Thanks!

```suggestion
          {{ ps.label_with_help(('Allow ordering of out-of-stock products'|trans), ('By default, the "%add_to_cart_label%" button is hidden when a product is unavailable. You can choose to have it displayed in all cases.'|trans({'%add_to_cart_label%': 'Add to cart'|trans({}, 'Shop.Theme.Actions')}, 'Admin.Shopparameters.Help'))) }}
```

2022-03-22 11:28 UTC, Julievrz commented on src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/Blocks/product_preferences_general.html.twig
> +      {{ 'Products general settings'|trans }}
```suggestion
      {{ 'General product settings'|trans }}
```

Sorry I forgot to modify this one

2022-03-23 15:33 UTC, Progi1984 approved these changes

2022-04-01 20:12 UTC, kpodemski approved these changes

2022-04-07 08:21 UTC, florine2623 approved these changes
Hello @PierreRambaud ,

As seen with @MatShir , the wording is to be ignored.
The position of fields in all 4 blocks is correct. Editing and Saving the configuration in all blocks work well.

It is QA ✅ 
Thanks @PierreRambaud :)

2022-04-07 08:28 UTC, merged

2022-04-07 08:28 UTC, Progi1984 commented
Thanks @PierreRambaud & @florine2623