Add hook to allow adding extra buttons in module configure toolbar
PrestaShop/PrestaShop pull request #27461
Opened 2022-01-25 16:44 UTC by sowbiba

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | After removal of "module update" button in module configure page, we need to be able to add extra buttons in this page's toolbar
| Type?             | new feature
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | #27578
| How to test?      | Create a module, use the hook to add a buton in the toolbar.<br>Here is an example module [prestashopexamplemodule.zip](https://github.com/PrestaShop/PrestaShop/files/7936179/prestashopexamplemodule.zip)
| Possible impacts? | -

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/27461)

2022-01-25 20:08 UTC, matks submitted a review, later dismissed
I know the PR is in draft but in its current state it seems logic 👍

2022-01-26 10:04 UTC, Hlavtox commented
@sowbiba What about making these buttons universal and display this hook in all toolbars? The module can then check, if it should display it's stuff or not.

2022-01-26 17:04 UTC, PierreRambaud approved these changes, later dismissed

2022-01-26 17:04 UTC, PierreRambaud commented
> @sowbiba What about making these buttons universal and display this hook in all toolbars? The module can then check, if it should display it's stuff or not.
> 
> something like `displayBackofficeToolbarButtons`

Could be an idea, but not the scope of this PR and doesn't take the same amount of time to do ^^

2022-01-27 20:27 UTC, Hlavtox commented
@PierreRambaud I think its the same job, currently, with the second PR it's two new hooks already… More hooks, more processing power, more maintanance.

It could be a single hook that could be used everywhere. 🤔

2022-01-28 09:01 UTC, PululuK requested changes
`This hook allows to add toolbar's additional content on module configuration page`

So, it must be a module propriety not a hook ?

```php

<?php

abstract class ModuleCore {
    function getConfigExtraButtons(){
        // TODO : Implement 
    }
}

```

2022-01-28 09:01 UTC, PululuK commented on install-dev/data/xml/hook.xml
> +      <title>Module configuration - After toolbar butons</title>
```suggestion
      <title>Module configuration - After toolbar buttons</title>
```

2022-02-01 14:34 UTC, sowbiba commented
> ```
> getConfigExtraButtons
> ```

The toolbar display is managed by the core. I don't know how you want to act on it without a hook. If it's a module property, do you want to browse all the installed module to check which one is adding extra content ?
Can you explain more what you have in mind ?

2022-02-01 14:56 UTC, PululuK commented
@sowbiba can you please add a screen please ?

2022-02-01 15:33 UTC, sowbiba commented
> @sowbiba can you please add a screen please ?
![Capture d’écran de 2022-02-01 15-32-19](https://user-images.githubusercontent.com/7426640/151998707-d2e1bb50-4424-4d0f-9a48-eaca20eb13c8.png)

Added the "My module button" with the hook (use the example module in the PR description)

2022-02-01 15:45 UTC, PululuK commented
> > @sowbiba can you please add a screen please ?
> > ![Capture d’écran de 2022-02-01 15-32-19](https://user-images.githubusercontent.com/7426640/151998707-d2e1bb50-4424-4d0f-9a48-eaca20eb13c8.png)
> 
> Added the "My module button" with the hook (use the example module in the PR description)



> > ```
> > getConfigExtraButtons
> > ```
> 
> The toolbar display is managed by the core. I don't know how you want to act on it without a hook. If it's a module property, do you want to browse all the installed module to check which one is adding extra content ? Can you explain more what you have in mind ?

what will happen if multiple modules are hooked into **displayModuleConfigureExtraButtons** ? Have you tested this case?

2022-02-02 11:36 UTC, sowbiba commented
![Capture d’écran de 2022-02-02 11-34-43](https://user-images.githubusercontent.com/7426640/152146285-29aa6657-11b3-49db-b04c-19dd533803e8.png)

It works just as I expected it

But ... I see where the confusion can be. It's not about adding toolbar button to that specific module but for all the modules. If someone wants to be specific to a module, he can do the logic in the hook call

2022-02-03 10:14 UTC, PululuK approved these changes

2022-02-08 12:35 UTC, khouloudbelguith approved these changes
Hi @sowbiba,

I checked the database => table `Prefix_hook` => ok
![image](https://user-images.githubusercontent.com/16067358/152985531-9be65dac-1241-40de-813d-d856ea3bd9fc.png)
I checked the Position page => OK
![image](https://user-images.githubusercontent.com/16067358/152985580-1002063c-ce86-4317-a60d-04ae396b1268.png)
I checked the module configuration page => ok
![image](https://user-images.githubusercontent.com/16067358/152985626-5e49c794-5f88-4188-a465-c3177b997442.png)


I tried to use 3 modules with the same hook `displayModuleConfigureExtraButtons` => ok
![image](https://user-images.githubusercontent.com/16067358/152985741-f3b3b0f0-1324-441f-a170-cb7160fa515b.png)
![image](https://user-images.githubusercontent.com/16067358/152986670-ce1a5bd3-0368-4dff-917a-13ae87cf0058.png)

https://user-images.githubusercontent.com/16067358/152987840-a079b470-df9b-47b1-97b8-0d2602a94f19.mp4


Thanks!

2022-02-08 13:08 UTC, merged

2022-02-08 13:09 UTC, Progi1984 commented
Thanks @sowbiba & @khouloudbelguith