Remove call of action*ListingFieldsModifier hook inside processFilter()
PrestaShop/PrestaShop pull request #27463
Opened 2022-01-25 18:42 UTC by PrestaEdit

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This hook call is also made, with more parameters, inside https://github.com/PrestaShop/PrestaShop/blob/develop/classes/controller/AdminController.php#L3139 and inside `processFilter()`, there is no use of `$this->fields_list` at all..
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #{issue number here}.
| How to test?      | Not sure there is something to test here.
| Possible impacts? | Make module reliable on this hook without checking if it's a lite or advanced usage.

2022-01-25 20:06 UTC, matks approved these changes
It makes sense

2022-01-26 09:35 UTC, saulaski approved these changes

2022-01-26 09:39 UTC, kpodemski commented
@PrestaEdit 

> and inside processFilter(), there is no use of $this->fields_list at all..

Check the `AdminController::filterToField`

2022-02-04 12:53 UTC, matks requested changes
Hi @PrestaEdit did you see @kpodemski review ;) ? I think it's a good thing to explore that

2022-03-11 20:24 UTC, matks commented
Dear @PrestaEdit unfortunately this PR seems stale since more than 1 month. I close it, but as you know we can reopen. Please ping me if you wish to reopen this PR.

2022-03-11 20:24 UTC, closed without merging