Csv bom
PrestaShop/PrestaShop pull request #27495
Opened 2022-01-27 15:46 UTC by Hlavtox

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR adds a BOM to every CSV exported from backoffice, for software to properly recognize that it's using UTF-8 encoding. (0xEF,0xBB,0xBF)
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27483
| How to test?      | Get a Windows PC with Excel, open any backoffice listing (legacy and migrated) and try using the Export function. Before this change, the file is a mess.
| Possible impacts? | no

2022-02-02 10:48 UTC, matks approved these changes
I have no knowledge of UTF-8 encoding implementation but I read the documentation and this PR makes sense ... as far as I know 😅

2022-02-03 15:05 UTC, kpodemski approved these changes
I don't like extra comments like "/ Write first row of CSV - the header" but I know you like them very much, approval from me 😛

2022-02-05 10:59 UTC, davidglezz commented
I think it should be configurable.

In my experience, the BOM has always been a source of issues, for example, reading the csv with a PHP script will no longer be the same and you would have to delete those bytes manually (and by the time you realize it, you have already lost some hours).

This adds support for Excel, yes, but removes it for other software. I would like it to be tested with Libreoffice also.

PROS AND CONS: https://stackoverflow.com/questions/2223882/whats-the-difference-between-utf-8-and-utf-8-without-bom

> Use of a BOM is neither required nor recommended for UTF-8

2022-02-05 11:40 UTC, davidglezz commented
Like this
![image](https://user-images.githubusercontent.com/194784/152640556-12939b1c-eb2f-442d-b75f-88a8b0408ea8.png)

2022-03-02 08:10 UTC, Progi1984 requested changes
@Hlavtox Could you help the @PrestaShop/product-team to define specs on this point ?

2022-03-02 08:41 UTC, PierreRambaud approved these changes

2022-10-28 21:42 UTC, kpodemski commented
@Hlavtox 

I remember we discussed it some time ago, and the idea was to make it configurable?

2022-11-04 13:40 UTC, MatShir commented
Does your feature take this parameter in consideration ?

<img width="1217" alt="Capture d’écran 2022-11-04 à 14 40 03" src="https://user-images.githubusercontent.com/43613217/199986375-12ab9c5f-22fe-45e2-b74c-12c99f6b378b.png">

2023-09-12 19:38 UTC, matks commented
Hi @Hlavtox I believe this PR is now too stale. I close it for now, just to help navigating old PRs. But we can reopen it anytime you want 😉 obviously. A closed PR does not mean it has to stay closed forever 💪 ! I just do this to make it easier to distinguish old PRs that might be merged one day and PRs that - unfortunately - I think are too old and will never be merged.

Thank you anyway for submitting the PR 👍

2023-09-12 19:38 UTC, closed without merging