Check if id_lang exist before delete
PrestaShop/PrestaShop pull request #27507
Opened 2022-01-28 10:40 UTC by PrestaSafe

fix of issue https://github.com/PrestaShop/PrestaShop/issues/27506
develop / 1.7.8.x

2022-01-28 10:50 UTC, PrestaSafe commented
Update table: 
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | fix of issue https://github.com/PrestaShop/PrestaShop/issues/27506
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/27506
| How to test?      | see issue
| Possible impacts? | None

<!-- Reviewable:start -->
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/27507)
<!-- Reviewable:end -->

2022-01-28 11:26 UTC, PululuK submitted a review, later dismissed
LGTM !
Thanks @PrestaSafe :)

2022-01-28 11:26 UTC, PululuK commented on classes/Language.php
> +                    $columns =  Db::getInstance()->executeS('SHOW COLUMNS FROM `' . $row[$tableNameKey] . '` LIKE "id_lang" ');
```suggestion
                    $columns = Db::getInstance()->executeS('SHOW COLUMNS FROM `' . $row[$tableNameKey] . '` LIKE "id_lang" ');
```

2022-01-28 14:01 UTC, PululuK approved these changes

2022-01-28 18:47 UTC, PrestaEdit requested changes
As mention on the issue itself, I'm not sure that we need this.

Imho, creating a _lang table without id_lang and/or the _shop table without id_shop it's already a creation bug.

2022-01-29 09:19 UTC, PrestaSafe commented
I agree with you but for the final customer it can be complicated at the end. 

So a few more checking step is welcome 😬

2022-02-04 12:47 UTC, matks approved these changes
I think it's a good thing to always check that what you want to erase exists beforehands 👍  good idea @PrestaSafe

2022-02-08 08:44 UTC, florine2623 requested changes
Hello @PrestaSafe ,

Thanks for the PR !

I have some feedback.
I'm encountering an exception after testing your PR, here are the steps I followed :
- Added multiple languages in International > Translations
- Create this table for testing:
```
CREATE TABLE `ps_test_lang` (
  `id_test` int(10) unsigned NOT NULL,
  `lang` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id_test`,`lang`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
- Delete an installed language OK
- Try to add another language  from International > Translations NOK 🚫 
<img width="1050" alt="Screenshot 2022-02-08 at 09 40 30" src="https://user-images.githubusercontent.com/16019289/152950148-761f9127-559e-4d4a-a9e9-8ba1b2a695ab.png">

Could you check please ?
Thanks!

2022-03-10 10:02 UTC, Progi1984 commented
Hi @PrestaSafe,
Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.
Thanks!

2022-03-10 10:02 UTC, closed without merging