Refactore layout of add-to-cart modal
PrestaShop/PrestaShop pull request #27548
Opened 2022-01-31 22:51 UTC by saulaski

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | New responsive layout of add-to-cart modal with flex design. Checkout button is moved on top in mobile display.
| Type?             | improvement
| Category?         | FO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #26642.
| How to test?      | <ol><li>Open product page on mobile or dev tools responsive mode</li><li>Add product to cart and wait for the modal to pop up</li></ol>
| Possible impacts? | Cart modal and navigation to order page.

2022-02-01 08:12 UTC, saulaski commented
### Desktop layout
![desktop-flex-layout](https://user-images.githubusercontent.com/97030953/151933477-aa5160f2-63c3-451f-ac49-65ebb2fa1c2d.png)
### Mobile layout
![mobile-flex-layout](https://user-images.githubusercontent.com/97030953/151933497-d29b127f-0c6c-4805-9e1f-e233d75bb9cc.png)

2022-02-01 08:35 UTC, NeOMakinG commented on themes/classic/_dev/css/components/products.scss
> +      color: #353943;
```suggestion
      color: $gray-dark;
```

Please use SCSS variablese everywhere, the closest one, you can also play with `lighten` and `darken` when needed

2022-02-01 11:30 UTC, NeOMakinG commented on themes/classic/modules/ps_shoppingcart/modal.tpl
> +        {hook h='displayCartModalFooter' product=$product}
```suggestion
        <div class="cart-content-btn">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">{l s='Continue shopping' d='Shop.Theme.Actions'}</button>
        </div>
        <div class="cart-content-btn checkout-action">
          <a href="{$cart_url}" class="btn btn-primary"><i class="material-icons rtl-no-flip">&#xE876;</i>{l s='Proceed to checkout' d='Shop.Theme.Actions'}</a>
        </div>
        <div class="card-content-footer">
          {hook h='displayCartModalFooter' product=$product}
        </div>
```

I'm pretty sure you'll be able to have the same result with a markup like this, I don't really understand the need of some line-break element

2022-02-01 16:55 UTC, saulaski commented on themes/classic/modules/ps_shoppingcart/modal.tpl
> +        {hook h='displayCartModalFooter' product=$product}
I replaced the `break-line` markup with a recursive `flex-grid` behavior, where `flex-row` doesn't wrap content.
```
  .flex-grid {
    display: flex;
    flex-flow: row wrap;
    justify-content: space-between;
    padding: 0;

    @include media-breakpoint-down(sm) {
      flex-flow: column nowrap;
    }

    & > * {
      padding: 1rem;

      @include media-breakpoint-down(sm) {
        flex-basis: 100%;
        padding: 0.5rem 0;
      }
    }

    & > .flex-grid {
      padding: 0;
    }
  }

  .flex-row {
    flex-basis: 100%;
    flex-wrap: nowrap;
  }
```

2022-02-02 13:48 UTC, NeOMakinG approved these changes, later dismissed

2022-02-02 17:12 UTC, matks approved these changes, later dismissed

2022-02-08 09:53 UTC, Progi1984 commented
@saulaski Needs a rebase

2022-02-08 12:58 UTC, saulaski commented
Previous changes I did to fix version 1.7.8.x are now dismissed by the modal refactoring into flex layout.

2022-02-08 14:58 UTC, NeOMakinG submitted a review, later dismissed

2022-02-08 21:40 UTC, matks submitted a review, later dismissed

2022-02-09 08:59 UTC, NeOMakinG commented
@prestascott we need you to unblock this PR :)

2022-02-09 09:05 UTC, prestascott commented
Hi everyone,

@saulaski Please remove the check icon on the "Commander" button. 

Good to me for the desktop version.
Although, the "Commander" button needs to be placed just above the "Continuer mes achats" button, and not at the very top.

2022-02-09 11:51 UTC, saulaski commented
Hello @prestascott, layout have been fixed according to your directions.

### Desktop Layout
![desktop-flex-layout-2](https://user-images.githubusercontent.com/97030953/153194459-03e1a7cc-b5cc-4695-81a6-799585f869c1.png)

### Mobile Layout
![mobile-flex-layout-2](https://user-images.githubusercontent.com/97030953/153194519-2fe62be5-c01c-440c-a61e-b86b7f20fe7e.png)

2022-02-09 13:30 UTC, prestascott commented
Perfect, thanks! @saulaski 🎉

2022-02-09 15:17 UTC, NeOMakinG approved these changes

2022-02-09 16:08 UTC, saulaski commented
Please wait before merging, because the new theme should include this layout instead of "classic" theme.

2022-02-15 11:13 UTC, atomiix approved these changes

2022-02-15 11:42 UTC, NeOMakinG commented
> Please wait before merging, because the new theme should include this layout instead of "classic" theme.

Not both? The product team told you this? I think we didn't really work on the new theme add-to-cart modal yet so...

2022-02-15 12:25 UTC, saulaski commented
> > Please wait before merging, because the new theme should include this layout instead of "classic" theme.
> 
> Not both? The product team told you this? I think we didn't really work on the new theme add-to-cart modal yet so...

We both heard the same decision collectively taken in stand up meeting a week ago: this refactoring should go into the new theme. I can't recall if product manager was present, I ask.

2022-02-15 12:34 UTC, NeOMakinG commented
> > > Please wait before merging, because the new theme should include this layout instead of "classic" theme.
> > 
> > 
> > Not both? The product team told you this? I think we didn't really work on the new theme add-to-cart modal yet so...
> 
> We both heard the same decision collectively taken in stand up meeting a week ago: this refactoring should go into the new theme. I can't recall if product manager was present, I ask. Please note that I wasn't delighted by this decision, but decisions are decisions.

It depends on one thing: Is the classic theme currently in maintenance only? If yes, then we should work on bugs only, not improvements, but this is something the product team should be aware of too!

2022-02-15 15:09 UTC, eternoendless commented
Remember that themes from 1.7 must work with little or no changes in v8

2022-02-15 15:37 UTC, florine2623 commented
Hello all,

Thanks for the details !

I have tested this PR, LGTM QA ✅ .
I let you decide if you merge it or not. For now, it is blocked, we need Product team to approve it.

If another test is needed, please ping me and change QA label !

2022-02-15 16:13 UTC, NeOMakinG requested changes
Blocking it, waiting for a decision

2022-02-28 14:31 UTC, saulaski commented
> Remember that themes from 1.7 must work with little or no changes in v8

The new layout is reusing the exact same CSS selectors. Of course HTML structure has changed:
- Bootstrap 3 Grid is layed aside, replaced with a custom Flex grid closer to Boostrap 4
- This refactoring allows more freedom about blocks & buttons placement in mobile display

@NeOMakinG even suggested to include this custom grid as a global alternative wherever Boostrap 3 Grid gets too limited.

@prestascott @MatShir what dou you guys think ? should we include this refactoring in version 8 ?

2022-02-28 20:21 UTC, matks commented
@MatShir @fabienvallon this PR has been blocked for more than 12 days now 😭 can we speed things up?

2022-03-24 15:22 UTC, atomiix commented
@MatShir @fabienvallon friendly reminder ;)

2022-03-31 16:45 UTC, MatShir commented
Hi, 
We can't allow BC on the classic theme even for the v8.0, there are too many themes relying on it. 
Agreed with @matks, the refacto should be done on the new theme https://github.com/PrestaShop/hummingbird if you want to apply major improvement and features

2022-04-04 22:24 UTC, SharakPL commented
@MatShir this modal was broken by 1.7.8 so it should be fixed here

2022-04-06 10:58 UTC, MatShir commented
@SharakPL I believe, that the modal is fixed https://github.com/PrestaShop/PrestaShop/pull/27502. Here, it is an optimization/cleaning of the code, that can lead to BC for the classic theme.

2022-04-06 13:45 UTC, SharakPL commented
I know it's been fixed already, but there still hasn't been new version of this module released since May last year and shops still use broken messed up version. What's the hold up?

2022-04-06 13:49 UTC, SharakPL commented
Right. Sorry.

2022-04-19 09:42 UTC, matks commented
Hello everyone looks like this PR got stale.

Going back through the notifications, I tried to summarize the constraints:

- PrestaShop 8.0.0 will be shipped with Classic theme as default theme as far as I know (because Hummingbird theme is not complete yet)
- Classic theme must be kept backward compatible as much as possible in order to ease the upgrade from PrestaShop 1.7 to PrestaShop 8
- The PHP backend code on PrestaShop 8 must be compatible with both Classic theme and Hummingbird theme in order to allow, when Hummingbird is complete, people to switch

Also when this PR was constructed the Classic theme was a part of this repository. The theme has now been moved to its own repository.

I think @saulaski won't work on this PR anymore so I close it for now. When someone picks up this topic again, he'll be able to reuse this branch content and possibly @saulaski 's commits (it's important to acknowledge his work) as a base and submit a new refactoring Pull Request against hummingbird theme only.

Thank you @saulaski and everyone involved in this PR.

2022-04-19 09:42 UTC, closed without merging