Remove deprecated variable _PS_PRICE_COMPUTE_PRECISION_
PrestaShop/PrestaShop pull request #27630
Opened 2022-02-09 10:34 UTC by idnovate

Deprecated `_PS_PRICE_COMPUTE_PRECISION_` instead of `Context::getContext()->getComputingPrecision()` was used. This cause an error when value from the 2 variables didn't match.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | When the value from `_PS_PRICE_COMPUTE_PRECISION_` and `Context::getContext()->getComputingPrecision()` was different, the order was created as Payment Error
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no

2022-02-09 13:34 UTC, PierreRambaud requested changes
Hi and thanks for your contribution.
Could you please remove the define in config.inc.php as the constant has been tagged as deprecated in 1.7.7.
If you feel comfortable, you can also do it for `_PS_PRICE_DISPLAY_PRECISION_` which was also deprecated in the same version

2022-02-09 13:37 UTC, matthieu-rolland reviewed
thanks @idnovate , this is indeed deprecated and should be removed

@idnovate do you think we should have a reproducible step by step use case for the QA team, so that they can test it?

Since the PR is described as a bug fix...

2022-02-09 20:25 UTC, idnovate commented
> thanks @idnovate , this is indeed deprecated and should be removed
> 
> @idnovate do you think we should have a reproducible step by step use case for the QA team, so that they can test it?
> 
> Since the PR is described as a bug fix...

Ok

2022-02-14 11:24 UTC, idnovate commented
> Hi and thanks for your contribution. Could you please remove the define in config.inc.php as the constant has been tagged as deprecated in 1.7.7. If you feel comfortable, you can also do it for `_PS_PRICE_DISPLAY_PRECISION_` which was also deprecated in the same version

But this could be a BC break if modules or custom developments use this variable.

2022-02-14 11:32 UTC, idnovate commented
> thanks @idnovate , this is indeed deprecated and should be removed
> 
> @idnovate do you think we should have a reproducible step by step use case for the QA team, so that they can test it?
> 
> Since the PR is described as a bug fix...

How to reproduce it and test it?

Set `0` decimals for a currency:
![image](https://user-images.githubusercontent.com/15104724/153855790-cb401d41-c5e6-4a33-a61c-5ccf49db01f0.png)

Set `Order status` as logable:
![image](https://user-images.githubusercontent.com/15104724/153856555-9ff31e3a-082f-458f-8e06-360a13fc6e7a.png)

Place an order with a product **above 999€**:
![image](https://user-images.githubusercontent.com/15104724/153856597-a61a1f00-6581-489a-85fc-23ce65b82c9c.png)

Order is created with `Payment error`:
![image](https://user-images.githubusercontent.com/15104724/153856665-ee78edcf-6c66-464b-8b37-f7e2eba59755.png)

2022-03-10 10:36 UTC, Progi1984 commented
@idnovate Could you create a dedicated issue for validating it by the @PrestaShop/qa-functional team ?

2022-04-01 20:24 UTC, kpodemski requested changes
In the `createOrderCartRules` you have this variable already available.

In the first method, you could create if it's in a few places.

2022-04-01 20:24 UTC, kpodemski commented on classes/PaymentModule.php
> +            $remainingValue = Tools::ps_round($remainingValue, Context::getContext()->getComputingPrecision());
```suggestion
            $remainingValue = Tools::ps_round($remainingValue, $computingPrecision);
```

2022-04-01 20:25 UTC, kpodemski commented
Thanks @idnovate 

I added a little feedback.

Also, this is a duplication of:
https://github.com/PrestaShop/PrestaShop/pull/27436

But I see that you changed the variable in the remaining places, good 👍

2022-04-19 09:49 UTC, matks commented
Friendly reminder @idnovate 😉 also this PR requires a git rebase

2022-04-21 07:06 UTC, Progi1984 commented
@idnovate Could you rebase your PR and remove your merge commits, please ?

2022-04-27 08:11 UTC, idnovate commented
> @idnovate Could you rebase your PR and remove your merge commits, please ?

Is it OK now? :confused:

2022-05-02 08:27 UTC, Progi1984 commented
@idnovate No you have always merge commits. Check here : https://github.com/PrestaShop/PrestaShop/pull/27630/commits.

2022-05-02 08:48 UTC, idnovate commented
https://github.com/PrestaShop/PrestaShop/pull/28388

2022-05-02 08:48 UTC, closed without merging