Prestaplugins mail order comment
PrestaShop/PrestaShop pull request #27643
Opened 2022-02-10 17:30 UTC by Prestaplugins

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Add the {product_name} to the content of the mail, it's already loaded by the controller but missing in the mail and improve wording
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27581 .
| How to test?      | Send a mail from an order detail in front-end, check the message received by the admin
| Possible impacts? |

2022-02-14 08:36 UTC, matthieu-rolland reviewed
thank you @Prestaplugins !

looks good 👍 

@Julievrz [made a wording suggestion in the issue](https://github.com/PrestaShop/PrestaShop/issues/27581#issuecomment-1034652687), once this is implemented it's a LGTM

2022-02-14 08:39 UTC, matthieu-rolland approved these changes
(approved but waiting for wording review)

2022-02-14 08:47 UTC, NeOMakinG approved these changes
Looks fine to me, but waiting for @Julievrz review :p

2022-02-15 09:00 UTC, Julievrz reviewed
LGTM, thanks. But I couldn't see if this issue was resolved in this PR?
![image](https://user-images.githubusercontent.com/70583503/154027659-7c0d3258-415a-43f7-b189-92335f901dd7.png)

It should be "Hello," instead of "Hello %name of the customer%,"

2022-02-15 09:03 UTC, Prestaplugins commented
> LGTM, thanks. But I couldn't see if this issue was resolved in this PR? ![image](https://user-images.githubusercontent.com/70583503/154027659-7c0d3258-415a-43f7-b189-92335f901dd7.png)
> 
> It should be "Hello," instead of "Hello %name of the customer%,"

Hi Julie, it was already fixed, probably in another issue

2022-03-10 10:48 UTC, Progi1984 requested changes
Please make changes in the repo `mjml-theme-converter` : https://github.com/PrestaShop/mjml-theme-converter/blob/master/mails/themes/modern_mjml/core/order_customer_comment.mjml.twig

2022-06-16 22:50 UTC, kpodemski commented
@Progi1984 to unblock this PR I'm putting "Waiting for QA", I'll handle external repo myself after the QA Approved

2022-06-22 13:35 UTC, HanaRebaiQA approved these changes
Hello @Prestaplugins 

I have checked this PR. the issue is fixed. Here my tested cases : 

- Check the automatic tests : OK 
- Check with different email-theme (modern, classic) : OK
- Check with maildev : OK
- Check the different combinations with different translations and different email-theme : OK
- Check with different languages (RTL and no RTL) : OK
- Check with multistore : OK
- Check with different browsers : OK 

For the RTL with modern email-theme, it should be fixed with mjml-converter

![image](https://user-images.githubusercontent.com/92912932/175041710-0265ccff-9d1c-413a-8b9a-ada2cc48623b.png)
![image](https://user-images.githubusercontent.com/92912932/175040666-21c48147-d581-4e9b-b440-b183d18ab7bb.png)![image](https://user-images.githubusercontent.com/92912932/175040569-7011821f-baca-44d1-95ce-7a3203be6b29.png)!
![image](https://user-images.githubusercontent.com/92912932/175041528-15c30d49-97d6-4b99-93c2-1578d3ffc289.png)
[image](https://user-images.githubusercontent.com/92912932/175040470-795fea23-c367-45ed-9b61-80fb85a764f7.png)
![image](https://user-images.githubusercontent.com/92912932/175041171-18bc21a9-f1c8-4548-a4b4-2f547aaa1272.png)
![image](https://user-images.githubusercontent.com/92912932/175041291-45602ab7-cd10-4df0-8284-98fbaf3dd76a.png)


So, it's QA :heavy_check_mark: 

Thank You!

2022-06-22 13:36 UTC, Progi1984 approved these changes

2022-06-22 13:37 UTC, merged

2022-06-22 13:37 UTC, Progi1984 commented
Thanks @Prestaplugins & @HanaRebaiQA 

@kpodemski Ready for new PR :muscle: