Multistore - Payment > Payment methods - Do not display content and update message in all shops or in a group context
PrestaShop/PrestaShop pull request #27667
Opened 2022-02-14 15:56 UTC by Progi1984

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Multistore - Payment > Payment methods - Do not display content and update message in all shops or in a group context
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #19425
| How to test?      | Cf #19425

2022-02-23 08:57 UTC, Julievrz approved these changes, later dismissed
Wording ✔️

2022-02-24 10:41 UTC, atomiix submitted a review, later dismissed

2022-02-25 12:55 UTC, saulaski submitted a review, later dismissed

2022-02-28 08:39 UTC, matthieu-rolland approved these changes, later dismissed

2022-03-03 10:13 UTC, AureRita requested changes
Hello @Progi1984 ,

I tested your pr and I noticed the text are correctly changed but the info display (blue alert) is missing, as you can see on this screenshot

i should have the blue alert :
![Capture d’écran du 2022-03-03 11-08-58](https://user-images.githubusercontent.com/100699445/156543204-109abc39-1cef-41c1-aac7-3ca96d61ddee.png)

This is what I' have
![Capture d’écran du 2022-03-03 10-48-18](https://user-images.githubusercontent.com/100699445/156543241-ed82dfc8-810b-42bb-8234-b99377749516.png)

2022-03-03 10:34 UTC, Progi1984 commented
@AureRita It's a expected behavior as defined here : https://github.com/PrestaShop/PrestaShop/issues/19425#issue-625771996
> To avoid bad behaviors and for a better understanding, we should display **ONLY** the information message in these contexts and update the current message for the following one:
"Note that this page is available in a single shop context only. Switch context to work on it."

2022-03-03 11:23 UTC, AureRita reviewed
If I follow the spec, it's an information message so the block text's color should be blue with the information icon and not with yellow color and the warning icon

2022-03-03 13:19 UTC, Progi1984 commented
@AureRita Thanks :)

@atomiix & @matthieu-rolland Changed the `alert-warning` to `alert-info` class.

2022-03-04 08:57 UTC, matthieu-rolland approved these changes

2022-03-04 09:38 UTC, saulaski approved these changes

2022-03-04 10:07 UTC, atomiix approved these changes

2022-03-07 10:24 UTC, AureRita requested changes
I tested it and the message's type is correctly changed,

as we can see here :

On all shop, We have only the correct info message
![image](https://user-images.githubusercontent.com/100699445/157012642-9b517efa-e85f-417a-aa66-5a7430aa6dee.png)

On groupDefault, the information message is correct, but it's not the only one
![image](https://user-images.githubusercontent.com/100699445/157012858-d86f19d9-dce8-40f3-9921-f0a6eb2d8e34.png)

Hello, @PrestaShop/product-team ,
as you said here : https://github.com/PrestaShop/PrestaShop/issues/19425#issue-625771996
"To avoid bad behaviors and for a better understanding, we should display ONLY the information message in these contexts"
Here, we've two messages but it's not for the same infos, what do we do ?

2022-03-24 20:49 UTC, MatShir commented
From the spec here https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/back-office/multistoregeneralspecs.md and https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/broader-topics/multistorespecialsspecs.md, it seems to be the normal behavior if the color of the header is not set for the group shop.

2022-03-25 09:06 UTC, AureRita approved these changes
hi @MatShir , 

Thank you for your answer, and yes indeed, the PR is QA approved

2022-03-25 11:00 UTC, merged

2022-03-25 11:00 UTC, Progi1984 commented
Thanks @AureRita @florine2623 @MatShir