Add a warning log when a module registers to a hook but implements no hook listener
PrestaShop/PrestaShop pull request #27683
Opened 2022-02-15 13:23 UTC by Progi1984

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add a warning log when a module registers to a hook but implements no hook listener. Thanks @matthieu-rolland for the initial job
| Type?             | new feature
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #19230
| How to test?      | Cf. #19230

2022-02-15 13:43 UTC, matthieu-rolland approved these changes, later dismissed

2022-02-28 17:26 UTC, jolelievre reviewed
Except for other PHPStan errors it seems ok to me

It also seems like you'll need to fix the modules from test resources if you want integration tests to succeed

2022-03-07 16:49 UTC, saulaski requested changes

2022-03-07 16:49 UTC, saulaski commented on classes/Hook.php
> +            if (!Hook::isHookCallableOn($module_instance, $hook_name) && !($module_instance instanceof WidgetInterface)) {
```suggestion
            if (!static::isHookCallableOn($module_instance, $hook_name) && !($module_instance instanceof WidgetInterface)) {
```

2022-03-07 16:49 UTC, saulaski commented on classes/Hook.php
> +                    sprintf('hook%s', ucfirst($hook_name))
```suggestion
                    static::getMethodName($hook_name)
```

2022-03-07 16:49 UTC, saulaski commented on classes/Hook.php
> +                    throw new PrestaShopException($message);
More specific and appropriate ?
```suggestion
                    throw new PrestaShopModuleException($message);
```

2022-03-12 20:35 UTC, matks reviewed
PHP CS Fixer wants
```
/* @phpstan-ignore-next-line */
```
instead of
```
/** @phpstan-ignore-next-line */
```

2022-04-01 20:33 UTC, kpodemski submitted a review, later dismissed
PHP Stan is not happy.

2022-04-29 09:19 UTC, Progi1984 commented on classes/Hook.php
> +                    sprintf('hook%s', ucfirst($hook_name))
Fixed

2022-04-29 09:22 UTC, Progi1984 commented on classes/Hook.php
> +            if (!Hook::isHookCallableOn($module_instance, $hook_name) && !($module_instance instanceof WidgetInterface)) {
Fixed

2022-04-29 09:22 UTC, Progi1984 commented on classes/Hook.php
> +                    throw new PrestaShopException($message);
Fixed

2022-04-29 12:08 UTC, jolelievre approved these changes
Thanks @Progi1984

2022-04-29 12:47 UTC, matthieu-rolland approved these changes

2022-05-05 14:20 UTC, florine2623 reviewed
Hello @Progi1984 ,

As discussed, here's a recap of the things I tested.

> What should happen : 
> Uninstall one of these 3 modules BlockWishlist, Psgdpr ou Ps_EmailAlerts, then try to reinstall it in any version but the latest one.
> - mode debug ON, you will see an exception
> - mode debug OFF, you will see a Warning Log

In my case, tested on develop branch.
- I uninstalled blockwishlist module v2.1.0
- I refreshed my page
- I installed wishlist module in v2.0.1
- mode debug ON : I have an error ✔️  
<img width="621" alt="Screenshot 2022-05-05 at 16 02 40" src="https://user-images.githubusercontent.com/16019289/166943650-332c074c-e460-45a7-be7b-ca0b083934b9.png">

- mode debug OFF : the installation of blockwishlist module v2.1.0 works and I don't have any Warning Log only Informative Log :
<img width="1186" alt="Screenshot 2022-05-05 at 16 06 41" src="https://user-images.githubusercontent.com/16019289/166943710-a88d5ca6-b58b-4f5d-9fc6-3e0ce0576ccf.png">
<img width="1199" alt="Screenshot 2022-05-05 at 16 18 17" src="https://user-images.githubusercontent.com/16019289/166943729-53723550-e91c-4aa8-8488-c16866cdfbc3.png">

2022-05-05 15:45 UTC, florine2623 approved these changes
Thanks for the PR @Progi1984 ,

Here are the different steps I followed.

**Tested with [GDPR v1.4.0](https://github.com/PrestaShop/psgdpr/releases/tag/v1.4.0) :**
- simple uninstall of gdpr module v1.4.1
- refresh page
- reinstall of gdpr module v1.4.0
- error in modal is displayed
<img width="673" alt="Screenshot 2022-05-05 at 17 00 52" src="https://user-images.githubusercontent.com/16019289/166952818-9599db00-bef2-42ae-856c-734d8ddb55b7.png">

- debug mode : NO
- go to module > module manager > upload gdpr module v1.4.0
- install OK
-  configure module : error 500
- Advanced parameter > Logs : no Warning

=> Won't show any warnings because of https://github.com/PrestaShop/psgdpr/pull/161

**Tested with [GDPR v1.2.0](https://github.com/PrestaShop/psgdpr/releases/tag/v1.2.0) :**
- uninstall gdpr module with deletion of module folder
- refresh page
- reinstall of gdpr module v1.2.0 with mode prod
- Advanced parameter > Logs : Warning log is displayed :
<img width="1192" alt="Screenshot 2022-05-05 at 17 18 51" src="https://user-images.githubusercontent.com/16019289/166958393-19ee427f-1ece-4269-8a91-c2fb441869eb.png">

**Tested with [ps_emailalerts v2.3.2](https://github.com/PrestaShop/ps_emailalerts/releases/edit/v2.3.2) :**
The warning is displayed correctly with Prod mode :
<img width="1184" alt="Screenshot 2022-05-05 at 17 36 39" src="https://user-images.githubusercontent.com/16019289/166959905-915fc598-e323-4bf5-8314-cc6ed020ad25.png">


And error is displayed with debug mode :
<img width="596" alt="Screenshot 2022-05-05 at 17 34 33" src="https://user-images.githubusercontent.com/16019289/166959450-fb2b5318-a751-494c-bb1b-b80542715b71.png">

**Tested with [blockwishlist v2.0.1](https://github.com/PrestaShop/blockwishlist/releases/tag/v2.0.1) and [blockwishlist v2.0.0](https://github.com/PrestaShop/blockwishlist/releases/tag/v2.0.0) :**
Mode prod :
<img width="862" alt="Screenshot 2022-05-05 at 17 42 53" src="https://user-images.githubusercontent.com/16019289/166961094-b1102ed7-dc0d-4b68-95d6-b7de0f4409eb.png">
Mode debug :
<img width="606" alt="Screenshot 2022-05-05 at 17 44 57" src="https://user-images.githubusercontent.com/16019289/166961561-a2d424bf-24d3-4683-9d7b-94bb9d17cd3f.png">


It is working as expected !
It is QA ✅

2022-05-05 15:56 UTC, merged

2022-05-05 15:56 UTC, Progi1984 commented
Thanks @florine2623 & @matthieu-rolland