Better french translation for "new" product label
PrestaShop/PrestaShop pull request #27714
Opened 2022-02-17 15:08 UTC by pierre42100

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 1.7.8.x
| Description?      | The word "New" in english refers more naturally to the word "Nouveauté" rather than "Neuf" which could make think that the product not labelled as "New" could be repackaged
| Type?             | bug fix
| Category?         | LO
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | None.
| How to test?      | It is just a changed word. It should work immediatly.
| Possible impacts? | None.

2022-02-17 15:36 UTC, jolelievre requested changes
Thank you @pierre42100 your suggestion is interesting I would like @Julievrz opinion on this

However this is not the place to fix such wordings, the file you modified is only used in our tests so it has no impact on a real shop And all our translations are managed via crowdin based on the default XLF files We then generate language packs which are downloadable via our i18n.prestashop.com API

That's why I block this PR because the current modification will have no impact in real life use case

2022-03-07 14:12 UTC, saulaski approved these changes

2022-03-07 19:23 UTC, jolelievre requested changes
Still no reason to merge this PR it simply updates test resources It won't change the value from the translation packages which are downloaded via an API

So I suggest we close this PR @PrestaShop/prestashop-core-developers what di you think?

2022-03-08 06:54 UTC, pierre42100 commented
> Still no reason to merge this PR it simply updates test resources It won't change the value from the translation packages which are downloaded via an API
> 
> So I suggest we close this PR @PrestaShop/prestashop-core-developers what di you think?

As the change has been taken in account, if think too that this merge request should be closed.

2022-03-08 06:54 UTC, closed without merging