Debug multishop category
PrestaShop/PrestaShop pull request #27732
Opened 2022-02-18 15:55 UTC by tups

| Questions         | In the case of a Prestashop Multishop, with shared products, it is impossible to define a default store category per store
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | We should be able to define a default category for each shop and categories assigned to a store should not be accessible on FO.
| Type?             | bug fix
| Category?         | FO and BO 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27731 
| How to test?      | Steps to reproduce Create a Prestashop with two stores with shared stock <br>Create a category for each store <br>Create a product, assign it to the two shops, and to the two categories. <br>Try to put a default category for each store <br>On the detail of the product sheet on the Front Office side, in the store that does not have a default category, check the category link in the breadcrumb
| Possible impacts? | Default Category

2022-02-19 10:35 UTC, okom3pom requested changes

2022-02-19 10:35 UTC, okom3pom commented on src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_layout.html.twig
>                  <input type="radio" name="form[{{ form.vars.id }}][tree]" value="{{ child.id_category }}"{% if checked %} checked="checked"{% endif %} class="category"{% if required %} required{% end
Ident

2022-03-02 13:52 UTC, tegbessou approved these changes
IMO the code is good!

2022-03-03 08:40 UTC, Progi1984 commented on src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_layout.html.twig
>                  <input type="radio" name="form[{{ form.vars.id }}][tree]" value="{{ child.id_category }}"{% if checked %} checked="checked"{% endif %} class="category"{% if required %} required{% end
```suggestion
              <input type="radio" name="form[{{ form.vars.id }}][tree]" value="{{ child.id_category }}"{% if checked %} checked="checked"{% endif %} class="category"{% if required %} required{% endif %}>
```

2022-03-03 19:18 UTC, saulaski requested changes

2022-03-03 19:18 UTC, saulaski commented on src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_layout.html.twig
>                      {% if defaultCategory is defined %}
Next line indentation is wrong as well
```suggestion
                <label>
                    <input type="radio" name="form[{{ form.vars.id }}][tree]" value="{{ child.id_category }}"{% if checked %} checked="checked"{% endif %} class="category"{% if required %} required{% endif %} />
                    {{ child.name }}
                    {% if defaultCategory is defined %}
```

2022-03-11 20:17 UTC, matks requested changes
Hi @tups you received some nice feedback on your contribution. Could you please have a look 😉 ?

2022-04-19 10:05 UTC, matks commented
Hello,

It looks like this PR is now stale. I close it as our rules state it "Pull Requests may be closed after 30 days of inactivity following a request for modifications." (https://www.prestashop-project.org/maintainers-guide/reviewing-pull-requests/)

Thank you

2022-04-19 10:05 UTC, closed without merging