Add scrollbar when changelog is too long
PrestaShop/PrestaShop pull request #27750
Opened 2022-02-21 13:53 UTC by sowbiba

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Adds a max-height for the module changelog tab and scrollbar when content is too long
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #{issue number here}.
| How to test?      | Go to Modules catalog in the Admin, search for colissimo (just an example) and click on the changelog tab. You will have a scollbar because the content is too long
| Possible impacts? | -

2022-02-21 20:57 UTC, Hlavtox approved these changes

2022-02-24 16:14 UTC, NeOMakinG approved these changes

2022-02-25 08:15 UTC, Progi1984 requested changes
Please target the `develop` branch. The relative issue is not a regression.

2022-02-28 08:46 UTC, sowbiba commented
@Progi1984 This modal doesn't exist anymore in develop

2022-02-28 08:48 UTC, Progi1984 commented
@sowbiba In this situation, you can close the PR.

2022-02-28 09:07 UTC, sowbiba commented
I understand your answer, semVer etc. But ... this looong modal (and the order of its content which is not obvious sometimes) annoy some users. We wont fix it in 1.7.8 because it's not a regression ?

2022-03-01 08:27 UTC, Progi1984 commented
@sowbiba Affirmative. Rules are defined there : https://devdocs.prestashop.com/1.7/project/release/patch-release-lifecycle/

2022-03-01 09:19 UTC, sowbiba commented
Alright. I have my heart broken but I understand 😂  ❤️

2022-03-01 09:25 UTC, closed without merging