FO:  Remove Front controller deprecated properties
PrestaShop/PrestaShop pull request #27756
Opened 2022-02-21 19:45 UTC by nenes25

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Remove deprecated class attributes and global variables from front controller
| Type?             |  improvement
| Category?         | FO / BO / CO / IN / WS / TE / LO / ME / PM
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| Fixed ticket?     | 
| How to test?      |  Global tests should not fail
| Possible impacts? | Old modules relying on globals will not works anymore ( but usage is discouraged since the release of prestashop 1.5.0.1 ... )

2022-02-22 07:31 UTC, PrestaEdit requested changes
Regarding the remove of the $useSSL var into the global, you will need to assign is or make a test isset into the line 290 cause it's check the value of it.

2022-02-25 08:26 UTC, Progi1984 reviewed
@nenes25 Thank you for your contribution. Could you check the @PrestaEdit feedback ?

2022-02-25 09:41 UTC, nenes25 commented
Hello @PrestaEdit and @Progi1984,

Thanks for your feedback, i've updated and removed all references to the global $useSSL.

Initially i don't think that this PR will have a lot of impacts
But it seems that the remove of $useSSL can have significant ones.
Is it a better idea to split ? ( One PR for $useSSL and one for the others ? ) 

Regards,

2022-02-25 13:43 UTC, matks commented
> Hello @PrestaEdit and @Progi1984,
> 
> Thanks for your feedback, i've updated and removed all references to the global $useSSL.
> 
> Initially i don't think that this PR will have a lot of impacts But it seems that the remove of $useSSL can have significant ones. Is it a better idea to split ? ( One PR for $useSSL and one for the others ? )
> 
> Regards,

I think the split will be better because you will have 1 PR very easy to review and test and the other one, that concerns `$useSSL` that might require deep review and deep QA. So 2 different PRs -> better split 😄

2022-02-25 13:44 UTC, matks submitted a review, later dismissed
Also our Fixer of codestyle, PHP CS Fixer, mentions a little codestyle issue

2022-02-27 13:44 UTC, nenes25 commented
OK it's done :) , thanks all for the feedbacks ! :smile: 
I'll remove the $useSSL in another PR.
Let's wait to see if this one can be merged quickly.

Regards,

2022-03-02 11:00 UTC, atomiix approved these changes

2022-03-02 13:48 UTC, tegbessou approved these changes

2022-03-03 19:05 UTC, saulaski approved these changes

2022-03-04 07:52 UTC, Progi1984 requested changes
@nenes25 Thank you for your contribution. The code is correct (thanks for it). Could you document BC breaks, please ?

2022-03-07 08:44 UTC, nenes25 commented
@Progi1984 the PR description is updated with BC break 
Let me know if it's enough  :smile:

2022-03-07 11:23 UTC, Progi1984 approved these changes

2022-03-09 14:21 UTC, PierreRambaud approved these changes

2022-03-15 08:28 UTC, Progi1984 commented
@PrestaShop/qa-functional Do you think we need to test it ?

2022-03-15 14:49 UTC, Robin-Fischer-PS commented
@Progi1984 We should just pass the automated test campaign on this one, and it will be OK.

2022-03-22 10:42 UTC, HanaRebaiQA approved these changes
Hello @nenes25 

I have checked this PR.
All automated tests are passed :heavy_check_mark: 

So, it's QA :heavy_check_mark: 

Thanks!

2022-03-22 11:06 UTC, merged