issue #24583 : fix import / edit customer
PrestaShop/PrestaShop pull request #27781
Opened 2022-02-23 10:25 UTC by kgleizes

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch           | develop / 1.7.8.x
| Description      | Fix issue : https://github.com/PrestaShop/PrestaShop/issues/24583 - Add default value for customer 'date_upd' while importing new customers. - Please note that to reproduce this bug you must import customers and have "Registration date" in the columns.
| Type             | bug fix
| Category         | BO
| BC breaks        |  no
| Deprecations     | no
| Fixed ticket     | Fixes #24583
| How to test      | 1) Import customer(s) with "Registration date" filled.  <br /> 2) Edit customer in back office (with or without modification)<br />3) Save customer<br />-------------------------------------------------------<br />Before fix  : An unexpected error occurred. [CustomerException code 0]: Customer contains invalid field values<br />-------------------------------------------------------<br />After fix : Customer is saved without errors
| Possible impacts? | None : only one new default value for customer entity before import (date_upd)

2022-02-24 10:42 UTC, Progi1984 approved these changes

2022-02-24 11:11 UTC, atomiix approved these changes

2022-03-01 15:47 UTC, tegbessou approved these changes

2022-03-08 15:44 UTC, hibatallahAouadni commented
Hello @kgleizes 

Thanks for your PR!
Unfortunately, I didn't reproduce the issue in th first place with PS1767, PS1778, PS1780 and develop.
Please check my [comment](https://github.com/PrestaShop/PrestaShop/issues/24583#issuecomment-1061917116) :pray: 

Thanks!

2022-03-10 13:40 UTC, clotairer commented
@hibatallahAouadni 

@kgleizes answered you on https://github.com/PrestaShop/PrestaShop/issues/24583#issuecomment-1062687414 with a beautiful video. Let's us know !

Tx

2022-03-22 10:26 UTC, AureRita requested changes
Hi @kgleizes ,

Thank you for your first pr ! 

I tested your PR and I think i followed correctly the steps to reproduce and I've a great exception, it is showed with or without your pr 

You can see the process and the exceptions on this video : 
https://user-images.githubusercontent.com/100699445/159460631-cd5b9e23-0eee-4db6-9f59-ab473a4c4eb2.mp4

2022-03-22 11:35 UTC, kgleizes commented
Hi, 

This is an other problem not linked to the issue mentionned here.

It seems to be the same that : 
https://github.com/PrestaShop/blockwishlist/runs/3905021826?check_suite_focus=true

I made my tests on a "non-dev" version to fix this issue, and in the video made by @hibatallahAouadni 
we can see that there's not this problem (and not too in my video) : 
https://github.com/PrestaShop/PrestaShop/issues/24583#issuecomment-1061917116

Please try to see with Prestashop teams when this problem was solved or try with 1.7.6- versions.

Thank you.

2022-03-22 13:47 UTC, AureRita commented
I tested it in dev version following this commentary : 
https://github.com/PrestaShop/PrestaShop/issues/24583#issuecomment-845790979

but ok, I will test it on 1778 like Hiba to reproduce it and check your pr :)

2022-03-22 14:29 UTC, clotairer commented
Hi @AureRita @kgleizes 

The @kgleizes  PR fix https://github.com/PrestaShop/PrestaShop/issues/24583 and not an other bug.

Could you please respect the description of the bug or the comment of @hibatallahAouadni with the video https://github.com/PrestaShop/PrestaShop/issues/24583#issuecomment-1064360843

Thank you

2022-03-23 09:03 UTC, AureRita requested changes
Hi @kgleizes, 

So I test it like you and Hiba with your PR and not on develop but your issue is still here, as you can see on this video : 

issue with adding customers 
https://user-images.githubusercontent.com/100699445/159662247-c298003f-4366-4eb1-9648-e4b9761575e4.mp4

2022-03-24 19:48 UTC, kgleizes commented
Hi @AureRita, 

Please check that you have the correction in the file : 
[AdminImportController.php -  GitHub File Changed](https://github.com/PrestaShop/PrestaShop/pull/27781/files#diff-7d9a1a25c8bc7d5b8d5e6368443975f834a9cf26816836645223e49b8293f338R404)

This file is located in : 
{your_prestashop_path}/controllers/admin/AdminImportController.php
On line 404 i added 'date_upd' filled with the date and hour that should fix this error.

Please let us know if you found a case where this is not working.

Thank you.

2022-03-25 13:13 UTC, AureRita approved these changes
Hi @kgleizes, 

I check it and : 
when you test your pr on 1.7.8.x, the line doesn't change and it will doesn"t works 
when you test your pr on develop, the line is modified and your pr works 

as you can see here : 

https://user-images.githubusercontent.com/100699445/160127169-249527e3-8528-4870-bbb9-7e293cdacdd5.mp4

2022-03-25 13:22 UTC, merged

2022-03-25 13:22 UTC, Progi1984 commented
Thanks @kgleizes & @AureRita

2022-08-22 15:14 UTC, lionelJDN commented
> Hi @AureRita,
> 
> Please check that you have the correction in the file : [AdminImportController.php - GitHub File Changed](https://github.com/PrestaShop/PrestaShop/pull/27781/files#diff-7d9a1a25c8bc7d5b8d5e6368443975f834a9cf26816836645223e49b8293f338R404)
> 
> This file is located in : {your_prestashop_path}/controllers/admin/AdminImportController.php On line 404 i added 'date_upd' filled with the date and hour that should fix this error.
> 
> Please let us know if you found a case where this is not working.
> 
> Thank you.

Dear @kgleizes thank you for your help but your tips don't give me a solution for my Prestashop 1.7.8.6 version.
I can't update a customer in the BO after import by the webservice API with Postman.
Did you know if a update file exist for the webservice like to the import please?
Thank you very much and sorry for my poor English.

![image](https://user-images.githubusercontent.com/111759208/185956444-02750e26-c4ba-4307-881e-6b3afc91a145.png)



Best regards

2022-08-22 15:20 UTC, clotairer commented
Hello @lionelJDN 

This Pull Request is already merged. 
Your issue looks different than we fixed #24583.

You should of open a new issue here https://github.com/PrestaShop/PrestaShop/issues/new/choose

Thank you!