[Multistore] - Product on category page display out of stock flag ins…
PrestaShop/PrestaShop pull request #27841
Opened 2022-03-06 16:14 UTC by Rizzen59

…tead of availlable on order #27604

Adding shop group id on ProductSearchContext and update sql query on  ProductAssembler.php

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 1.7.8.x
| Description?      | Take account of the sharing stock in product assembler. Adding Shop Group Id and flag in SearchContext
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | yes / no
| Deprecations?     |  no
| Fixed ticket?     | Fixes #27604
| How to test?      | As indicated in ticket, in multistore with stock sharing enable, adding product with allow order, the flag is correctly displayed
| Possible impacts? | Few impact. two proprerties in Search Context only used in productAssembler.

2022-03-07 12:12 UTC, Progi1984 commented on src/Core/Product/Search/ProductSearchContext.php
> +        $this->idShopGroup = $idShopGroup;
```suggestion
    public function setIdShopGroup(int $idShopGroup): self
    {
        $this->idShopGroup = $idShopGroup;
        
        return $this;
```

2022-03-07 12:13 UTC, Progi1984 commented on src/Core/Product/Search/ProductSearchContext.php
> +        $this->stockSharingBetweenShopGroupEnabled = $stockSharingBetweenShopGroupEnabled;
```suggestion
    public function setStockSharingBetweenShopGroupEnabled(bool $stockSharingBetweenShopGroupEnabled): self
    {
        $this->stockSharingBetweenShopGroupEnabled = $stockSharingBetweenShopGroupEnabled;
        
        return $this;
```

2022-03-07 12:13 UTC, Progi1984 commented on src/Core/Product/Search/ProductSearchContext.php
> +     * @param bool $stockSharingBetweenShopGroupEnabled
```suggestion
     * @param bool $stockSharingBetweenShopGroupEnabled
     *
     * @return self
```

2022-03-07 12:13 UTC, Progi1984 commented on src/Core/Product/Search/ProductSearchContext.php
> +     * @param int $idShopGroup
```suggestion
     * @param int $idShopGroup
     *
     * @return self
```

2022-03-07 12:14 UTC, Progi1984 commented on classes/ProductAssembler.php
> +        $idProduct = (int)$rawProduct['id_product'];
```suggestion
        $idShop = (int)$this->searchContext->getIdShop();
        $idShopGroup = $this->searchContext->getIdShopGroup();
        $isStockSharingBetweenShopGroupEnabled = $this->searchContext->isStockSharingBetweenShopGroupEnabled();
        $idLang = (int) $this->searchContext->getIdLang();
        $idProduct = (int) $rawProduct['id_product'];
```

2022-03-07 12:14 UTC, Progi1984 commented on classes/ProductAssembler.php
> +        $nbDaysNewProduct = (int)Configuration::get('PS_NB_DAYS_NEW_PRODUCT');
```suggestion
        $nbDaysNewProduct = (int) Configuration::get('PS_NB_DAYS_NEW_PRODUCT');
```

2022-03-07 12:15 UTC, Progi1984 reviewed
@Rizzen59 Thank you for your contribution. I have brought you some comments but the bugfix logic is good.

2022-03-07 17:26 UTC, Rizzen59 commented on src/Core/Product/Search/ProductSearchContext.php
> +        $this->stockSharingBetweenShopGroupEnabled = $stockSharingBetweenShopGroupEnabled;
Done !

2022-03-07 17:26 UTC, Rizzen59 commented on src/Core/Product/Search/ProductSearchContext.php
> +     * @param bool $stockSharingBetweenShopGroupEnabled
Done !

2022-03-07 17:27 UTC, Rizzen59 commented on src/Core/Product/Search/ProductSearchContext.php
> +     * @param int $idShopGroup
Done

2022-03-07 17:38 UTC, Rizzen59 commented
> @Rizzen59 Thank you for your contribution. I have brought you some comments but the bugfix logic is good.

Thanks. I commit the suggestion.
I use phpStorm. Is there a specific formatter config ?

2022-03-09 10:40 UTC, matthieu-rolland reviewed
you have some linting issues but lgtm otherwise 👍

2022-03-12 11:45 UTC, Rizzen59 commented
> you have some linting issues but lgtm otherwise 👍

wich linter do you use ?

2022-03-16 08:35 UTC, Progi1984 reviewed
@Rizzen59 I think you don't push your last modifications. Could you check my comments ?

2022-03-20 17:00 UTC, Rizzen59 commented
I done a new pass. 

- I check all warning from phpstorm linter (I added type for all parameters and return values)
- i reintroduced space between type cast and parameters removed by phpstorm formatter

Just one point : all originals setters return "$this" so as to chain call. I don't understand why returning slef instead of $this on new setters. For me self is for static context.

Thank you for your time and advice. 
Please, let me know if there are specifics linters or formatters configuration to improve my contribution.

2022-03-21 08:56 UTC, NeOMakinG commented
Seems like it brokes something in the UI tests, except if it's not related

2022-03-23 08:55 UTC, Progi1984 commented on classes/ProductAssembler.php
> +        $sql .= "LEFT JOIN {$prefix}stock_available sa ";
```suggestion
                    AND pl.id_lang = $idLang ";

        $sql .= "LEFT JOIN {$prefix}stock_available sa ";
```
```suggestion
                    AND pl.id_lang = $idLang
                LEFT JOIN {$prefix}stock_available sa ";
```

2022-03-23 08:56 UTC, Progi1984 commented on src/Core/Product/Search/ProductSearchContext.php
> +    public function setIdShop(int $idShop): ProductSearchContext
```suggestion
    public function setIdShop($idShop)
```

2022-03-23 08:56 UTC, Progi1984 commented on src/Core/Product/Search/ProductSearchContext.php
> +    public function getIdShop(): int
```suggestion
    public function getIdShop()
```

2022-03-23 08:56 UTC, Progi1984 commented on src/Core/Product/Search/ProductSearchContext.php
> +    public function getIdLang(): int
```suggestion
    public function getIdLang()
```

2022-03-23 08:57 UTC, Progi1984 commented on src/Core/Product/Search/ProductSearchContext.php
> +    public function setIdLang(int $idLang): ProductSearchContext
```suggestion
    public function setIdLang($idLang)
```

2022-03-23 08:57 UTC, Progi1984 commented on src/Core/Product/Search/ProductSearchContext.php
> +    public function setIdCurrency(int $idCurrency): ProductSearchContext
```suggestion
    public function setIdCurrency($idCurrency)
```

2022-03-23 08:57 UTC, Progi1984 commented on src/Core/Product/Search/ProductSearchContext.php
> +    public function getIdCurrency(): int
```suggestion
    public function getIdCurrency()
```

2022-03-23 08:57 UTC, Progi1984 commented on src/Core/Product/Search/ProductSearchContext.php
> +    public function setIdCustomer(int $idCustomer): ProductSearchContext
```suggestion
    public function setIdCustomer($idCustomer)
```

2022-03-23 08:57 UTC, Progi1984 commented on src/Core/Product/Search/ProductSearchContext.php
> +    public function getIdCustomer(): int
```suggestion
    public function getIdCustomer()
```

2022-03-23 08:59 UTC, Progi1984 requested changes
Please remove all new type hint. It's BC so we can't embed that in patch version.

2022-03-26 12:54 UTC, Rizzen59 commented on classes/ProductAssembler.php
> +        $sql .= "LEFT JOIN {$prefix}stock_available sa ";
applied

2022-03-26 12:54 UTC, Rizzen59 commented on src/Core/Product/Search/ProductSearchContext.php
> +    public function setIdShop(int $idShop): ProductSearchContext
Done

2022-03-26 12:54 UTC, Rizzen59 commented on src/Core/Product/Search/ProductSearchContext.php
> +    public function getIdShop(): int
Done

2022-03-26 12:54 UTC, Rizzen59 commented on src/Core/Product/Search/ProductSearchContext.php
> +    public function setIdLang(int $idLang): ProductSearchContext
Done

2022-03-26 12:54 UTC, Rizzen59 commented on src/Core/Product/Search/ProductSearchContext.php
> +    public function getIdLang(): int
Done

2022-03-26 12:54 UTC, Rizzen59 commented on src/Core/Product/Search/ProductSearchContext.php
> +    public function setIdCurrency(int $idCurrency): ProductSearchContext
Done

2022-03-26 12:54 UTC, Rizzen59 commented on src/Core/Product/Search/ProductSearchContext.php
> +    public function getIdCurrency(): int
Done

2022-03-26 12:54 UTC, Rizzen59 commented on src/Core/Product/Search/ProductSearchContext.php
> +    public function setIdCustomer(int $idCustomer): ProductSearchContext
Done

2022-03-26 12:54 UTC, Rizzen59 commented on src/Core/Product/Search/ProductSearchContext.php
> +    public function getIdCustomer(): int
Done

2022-03-26 12:55 UTC, Rizzen59 commented
I updated code with you advice in review

2022-03-30 08:15 UTC, Progi1984 commented on src/Core/Product/Search/ProductSearchContext.php
> +    public function getIdShopGroup()
```suggestion
    public function getIdShopGroup(): int
```

2022-03-30 08:15 UTC, Progi1984 commented on src/Core/Product/Search/ProductSearchContext.php
> +    public function setIdShopGroup($idShopGroup)
```suggestion
    public function setIdShopGroup(int $idShopGroup): self
```

2022-03-30 08:16 UTC, Progi1984 commented on src/Core/Product/Search/ProductSearchContext.php
> +    public function isStockSharingBetweenShopGroupEnabled()
```suggestion
    public function isStockSharingBetweenShopGroupEnabled(): bool
```

2022-03-30 08:16 UTC, Progi1984 commented on src/Core/Product/Search/ProductSearchContext.php
> +    public function setStockSharingBetweenShopGroupEnabled($stockSharingBetweenShopGroupEnabled)
```suggestion
    public function setStockSharingBetweenShopGroupEnabled(bool $stockSharingBetweenShopGroupEnabled): self
```

2022-03-30 08:16 UTC, Progi1984 commented on src/Core/Product/Search/ProductSearchContext.php
> +            $this->stockSharingBetweenShopGroupEnabled = boolval($shopGroup->share_stock);
```suggestion
            $this->stockSharingBetweenShopGroupEnabled = (bool) $shopGroup->share_stock;
```

2022-03-30 08:17 UTC, Progi1984 reviewed
Small fixes on your PR. You can typehint new method but not old, else it's a BC.

2022-04-03 13:04 UTC, Rizzen59 commented
That should be ok :)

2022-04-05 08:18 UTC, Progi1984 commented on classes/ProductAssembler.php
> +     * @throws PrestaShopDatabaseException
```suggestion
     *
     * @throws PrestaShopDatabaseException
```

2022-04-05 08:19 UTC, Progi1984 commented on src/Core/Product/Search/ProductSearchContext.php
> +     * @var boolean if the sharing stock is enable
```suggestion
     * @var bool if the sharing stock is enable
```

2022-04-05 08:19 UTC, Progi1984 reviewed
Two last changes and the CI should be ok. Thanks

2022-04-10 13:21 UTC, Rizzen59 commented
I cmmited your review

2022-04-12 07:27 UTC, Progi1984 approved these changes, later dismissed

2022-04-18 13:55 UTC, Rizzen59 commented
PHP / PHP Coding Standards Fixer (pull_request)  -> there's no more explaination about error ? I have juste Error: Process completed with exit code 8

Do you have any idea ?

2022-04-19 09:31 UTC, Progi1984 commented
@Rizzen59 Check that error message : https://github.com/PrestaShop/PrestaShop/runs/5985623237?check_suite_focus=true#step:8:14

2022-04-21 07:38 UTC, matks requested changes, later dismissed
@Rizzen59 

```
un ./vendor/bin/php-cs-fixer fix --dry-run --diff
Loaded config default from "/home/runner/work/PrestaShop/PrestaShop/.php_cs.dist".
   1) /home/runner/work/PrestaShop/PrestaShop/classes/ProductAssembler.php
      ---------- begin diff ----------
--- Original
+++ New
@@ @@
      * @return mixed
+     *
```

PHP CS fixer wants an empty line between `return` and `throw` 😉

2022-04-21 07:38 UTC, matks commented on classes/ProductAssembler.php
> +     * @throws PrestaShopDatabaseException
```suggestion
     *
     * @throws PrestaShopDatabaseException
```

2022-04-21 16:54 UTC, Rizzen59 commented on classes/ProductAssembler.php
> +     * @throws PrestaShopDatabaseException
Thnaks it's fixed normally

2022-04-25 06:11 UTC, Rizzen59 commented
Hi someone can run worfkflow.
Thanks :)

2022-05-02 07:46 UTC, Progi1984 approved these changes

2022-06-16 22:43 UTC, kpodemski approved these changes

2022-06-27 10:18 UTC, sLorenzini approved these changes
hello @Rizzen59,

Thank you for this PR.
Tested on 1.7.8.x with PHP 7.2 version

1. Enable multistore.
2. Create a product on all shops.
- set quantity to 0 and use default behavior when out of stock (deny orders): on FO, out of stock label is well displayed ✅ 
- choose main shop on the default group
	- keep quantity to 0 and set allow orders when out of stock
	- go to FO on the shop (product page and category page), out of stock label is not displayed ✅ 
- choose the shop on the second group
	- keep quantity to 0 and set allow orders when out of stock
	- go to FO on the shop (product page and category page), out of stock label is not displayed ✅ 

QA approved ✅ 

Thanks

2022-06-27 11:38 UTC, merged

2022-06-27 11:38 UTC, Progi1984 commented
Thanks @Rizzen59 & @sLorenzini

2022-06-28 06:13 UTC, Rizzen59 commented
You're welcome. I was very busy last weeks. But il will try to find more time to help on Prestashop

2022-06-28 06:48 UTC, Progi1984 commented
@Rizzen59 Thanks to you for advance.