fix: login page float buggy on latest chrome version
PrestaShop/PrestaShop pull request #27843
Opened 2022-03-07 08:27 UTC by NeOMakinG

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Some floats on stay logged in and lost password were buggy on the latest chrome version, it can be replaced by a bootstrap column system
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27835.
| How to test?      | Update to chrome 99, then go on the BO login page, the layout should be finely displayed and the issue should be fixed
| Possible impacts? | Login BO page

2022-03-07 08:28 UTC, NeOMakinG commented
@Hlavtox feel free to review, if you find something strange

2022-03-07 08:35 UTC, Hlavtox approved these changes, later dismissed
All good!

2022-03-07 09:09 UTC, atomiix submitted a review, later dismissed

2022-03-07 12:07 UTC, Progi1984 submitted a review, later dismissed

2022-03-08 11:44 UTC, hibatallahAouadni requested changes
Hello @NeOMakinG 

Thanks for your PR!
It seems OK on Chrome v99 and v96, but I encounter this issue #27800 with your PR :disappointed: 
We use to encounter this issue only when we have long shop name, now with your fix the issue always persist, check the screen record below:

https://user-images.githubusercontent.com/23308427/157231746-ab41148e-6c6f-41c8-bf45-f2898d7e54ff.mp4

Should we wait till this PR #27812 is merged?
Waiting for your feedback.

Thanks!

2022-03-08 14:00 UTC, NeOMakinG commented
@hibatallahAouadni just wait for @Amoifr 's PR to be merged, this behavior will disappear afterwhile

2022-03-08 15:46 UTC, hibatallahAouadni commented
@NeOMakinG ok, thanks!
Blocked by this PR #27812

2022-03-08 17:35 UTC, PululuK submitted a review, later dismissed
My team noticed this issue too! Thank you @NeOMakinG

2022-03-09 09:34 UTC, Progi1984 approved these changes

2022-03-09 09:39 UTC, PululuK approved these changes

2022-03-09 09:49 UTC, NeOMakinG commented
@hibatallahAouadni It's fine now, this PR includes both long name fix and the chrome 99 fix

2022-03-09 14:05 UTC, PierreRambaud approved these changes

2022-03-10 17:56 UTC, hibatallahAouadni approved these changes
Hello @NeOMakinG 

It works like a charm :raised_hands: QA :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/23308427/157725398-1609d209-4461-44cd-bdaa-37b1e553c668.png)

Thanks!

2022-03-10 18:44 UTC, merged

2022-03-10 18:44 UTC, NeOMakinG commented
Thanks @hibatallahAouadni