Allows you to modify the csv generated by the order export in the adm…
PrestaShop/PrestaShop pull request #27886
Opened 2022-03-11 08:02 UTC by olecorre

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Allows you to modify the csv generated by the order export in the administration
| Type?             | new feature
| Category?         | BO 
| BC breaks?        | no
| Deprecations?     |  no
| Fixed ticket?     | Fixes #27885
| How to test?      | Add a column in the list of orders in the BO, make a csv export, the new column is missing. With this new hook, you can redefine the exported columns in the csv, the data is already the SQL query
| Possible impacts? | No impact

2022-03-11 10:04 UTC, olecorre commented
Exemple to use the new hook : 
public function hookactionExportOrder($params){
        $newheader = [];

        foreach($params['header'] as $key=>$head){
            if( $key=='new' || $key=='reference') continue;
            $newheader[$key] = $head;
            if($key=='customer'){
                $newheader['products'] = $this->trans('Products',  array(),'Modules.oh_extend.Admin');
                $newheader['store'] = $this->trans('Store',  array(),'Modules.oh_extend.Admin');
                $newheader['date_livraison'] = $this->trans('Date livraison',  array(),'Modules.oh_extend.Admin');
            }
        }
        $params['header'] = $newheader;

        $data = [];

        foreach ( $params['orderGrid']->getData()->getRecords()->all() as $record) {
            $item = [
                'id_order' => $record['id_order'],
                'country_name' => $record['country_name'],
                'customer' => $record['customer'],
                'products' => $record['products'],
                'store' => $record['store'],
                'date_livraison' => $record['date_livraison'],
                'total_paid_tax_incl' => $record['total_paid_tax_incl'],
                'payment' => $record['payment'],
                'osname' => $record['osname'],
                'date_add' => $record['date_add'],
            ];

            if ($params['isB2bEnabled']) {
                $item['company'] = $record['company'];
            }

            $data[] = $item;
        }
        $params['data'] = $data;
    }

2022-03-11 10:14 UTC, okom3pom commented
Nice hook, don't forget the PR in https://github.com/PrestaShop/autoupgrade

2022-03-11 12:49 UTC, saulaski requested changes

2022-03-11 12:49 UTC, saulaski commented on src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
> +        );
```suggestion
                'isB2bEnabled' => $isB2bEnabled,
            ]
        );

```

2022-03-11 13:25 UTC, saulaski requested changes

2022-03-11 13:25 UTC, saulaski commented on src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
> +        );
Please don't forget the extra line before the return statement. This is a code style rule.

You can test the code style yourself before you push with this command line:
`php vendor/bin/php-cs-fixer fix --dry-run --diff`

2022-03-14 08:52 UTC, saulaski commented
@olecorre Please rebase your commits: 1 commit / PR

2022-03-14 09:22 UTC, matthieu-rolland approved these changes, later dismissed

2022-03-14 10:08 UTC, okom3pom commented
I think if one PR = one commit we can [merge this PR](https://github.com/PrestaShop/traces/pull/24)

2022-04-22 19:59 UTC, matks submitted a review, later dismissed
@olecorre Apologies for the delay I have no idea why this PR was off the radar for so long.

2022-04-22 20:05 UTC, matks commented
@olecorre A git rebase was needed. As the review came very late I did it for you.

2022-04-22 20:57 UTC, kpodemski approved these changes

2022-04-26 12:38 UTC, khouloudbelguith reviewed
Hi @olecorre,

I followed these steps:
1. Create new table `app_order_table` with `id_order`
![image](https://user-images.githubusercontent.com/16067358/138904529-f6c4d729-779d-4beb-85e3-427af06eaab3.png)

2. Install the module [ps_qualityassurance](https://github.com/PrestaShop/ps_qualityassurance), add two hooks:

`actionOrderGridQueryBuilderModifier` with this content:
```php
$searchQueryBuilder = $params['search_query_builder'];
$countQueryBuilder = $params['count_query_builder'];

    $searchCriteria = $params['search_criteria'];

    $searchQueryBuilder->addSelect(
        'app.`id_order` IS NOT NULL AS `from_app`'
    );

    $searchQueryBuilder->leftJoin(
        'o',
        '`app_order_table`',
        'app',
        'app.`id_order` = o.`id_order`'
    );
	$countQueryBuilder->leftJoin(
        'o',
        '`app_order_table`',
        'app',
        'app.`id_order` = o.`id_order`'
    );

    if ('from_app' === $searchCriteria->getOrderBy()) {
        $searchQueryBuilder->orderBy('app.`id_order`', $searchCriteria->getOrderWay());
    }

    foreach ($searchCriteria->getFilters() as $filterName => $filterValue) {
        if ('from_app' === $filterName) {
            $searchQueryBuilder
              ->andWhere('app.`id_order` IS ' . ($filterValue ? 'NOT' : '') . ' NULL');
          $countQueryBuilder
              ->andWhere('app.`id_order` IS ' . ($filterValue ? 'NOT' : '') . ' NULL');
        }
    }
```
3. Install this module 
[testhookactionExportOrder.zip](https://github.com/PrestaShop/PrestaShop/files/8563177/testhookactionExportOrder.zip)
which uses this function 
```php
 public function hookactionExportOrder($params)
    {
        $newheader = [];

    foreach($params['header'] as $key=>$head){
        if( $key=='new' || $key=='reference') continue;
        $newheader[$key] = $head;
        if($key=='customer'){
            $newheader['products'] = $this->trans('Products',  array(),'Modules.oh_extend.Admin');
            $newheader['store'] = $this->trans('Store',  array(),'Modules.oh_extend.Admin');
            $newheader['date_livraison'] = $this->trans('Date livraison',  array(),'Modules.oh_extend.Admin');
        }
    }
    $params['header'] = $newheader;

    $data = [];

    foreach ( $params['orderGrid']->getData()->getRecords()->all() as $record) {
        $item = [
            'id_order' => $record['id_order'],
            'country_name' => $record['country_name'],
            'customer' => $record['customer'],
            'products' => $record['products'],
            'store' => $record['store'],
            'date_livraison' => $record['date_livraison'],
            'total_paid_tax_incl' => $record['total_paid_tax_incl'],
            'payment' => $record['payment'],
            'osname' => $record['osname'],
            'date_add' => $record['date_add'],
        ];

        if ($params['isB2bEnabled']) {
            $item['company'] = $record['company'];
        }

        $data[] = $item;
    }
    $params['data'] = $data;
    }
```
4. Go to BO > Orders > Orders list page
5. Click on export
6. See exception 
![image](https://user-images.githubusercontent.com/16067358/165301027-ab1e89ce-6d9e-47cb-baa2-e16aabdfc02b.png)

I tried to remove those lines
```php
            'country_name' => $record['country_name'],
            'customer' => $record['customer'],
            'products' => $record['products'],
```

I don't have any exceptions but the csv file is missing
![image](https://user-images.githubusercontent.com/16067358/165301195-7d122afc-fa76-4fcd-a96d-3b2c97998abb.png)

Can you please provide the exact steps to check that the issue is fixed?

Thanks!

2022-04-26 17:22 UTC, olecorre commented
My function :
public function hookactionExportOrder($params){
        $newheader = [];

        foreach($params['header'] as $key=>$head){
            if( $key=='new' || $key=='reference') continue;
            $newheader[$key] = $head;
            if($key=='customer'){
                $newheader['products'] = $this->trans('Products',  array(),'Modules.oh_extend.Admin');
                $newheader['store'] = $this->trans('Store',  array(),'Modules.oh_extend.Admin');
                $newheader['date_livraison'] = $this->trans('Date livraison',  array(),'Modules.oh_extend.Admin');
            }
        }
        $params['header'] = $newheader;

        $data = [];

        foreach ( $params['orderGrid']->getData()->getRecords()->all() as $record) {
            $item = [
                'id_order' => $record['id_order'],
                'country_name' => $record['country_name'],
                'customer' => $record['customer'],
                'products' => $record['products'],
                'store' => $record['store'],
                'date_livraison' => $record['date_livraison'],
                'total_paid_tax_incl' => $record['total_paid_tax_incl'],
                'payment' => $record['payment'],
                'osname' => $record['osname'],
                'date_add' => $record['date_add'],
            ];

            if ($params['isB2bEnabled']) {
                $item['company'] = $record['company'];
            }

            $data[] = $item;
        }
        $params['data'] = $data;
    }

2022-05-06 14:58 UTC, khouloudbelguith reviewed
Hi @olecorre,

Could you please check the Conflicting files?

Thanks!

2022-06-14 12:56 UTC, matks commented
Hi all,

Since this PR has been stale since May, I will follow [our guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests) and I'll close this pull request as it seems stale.

**Feel free to reopen or open another one if you think it's still relevant.** 😄 

Thanks!

2022-06-14 12:56 UTC, closed without merging