Set country from browser language, and then update currency if needed.
PrestaShop/PrestaShop pull request #27903
Opened 2022-03-14 14:36 UTC by goralczykmarcin

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | (Edited) In my opinion $has_currency prevent country update. Right now context->country is assigned before $has_currency variable condition checks. It solve the problem. 
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #18008.
| How to test?      | Issue scenario
| Possible impacts? | no

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/27903)

2022-03-14 16:47 UTC, MeKeyCool reviewed
I don't understand the link between your solution and the bug you mentioned : [ Set default country from browser language KO #18008 ](https://github.com/PrestaShop/PrestaShop/issues/18008)
What is th elink you made with currency and default country setup by admin ?

We try to keep style consistent. You changed style without clear reason please be careful.
(I don't know why CI didn't reject your modifications).

2022-03-14 16:47 UTC, MeKeyCool commented on classes/controller/FrontController.php
> +                    } catch (\GeoIp2\Exception\AddressNotFoundException$e) {
Why did you remove this space ? Looks an error for me.

2022-03-15 08:13 UTC, goralczykmarcin commented
@MeKeyCool Than you for review. 

"When in BO, "Set default country from browser language" is set to Yes, it does not work : On FO, when creating an address, the pre-filled country is the "Default country" set in BO instead of the country of the browser." 
It is a problem as far as I know.

I check variables on the front office, and all is working fine to the moment of creating object Country.
(375 line - $has_currency)

There is one link with currency. In my opinion wrong IF statemen. Previousely currency for some reaason blocks country assign to context cookie.

2022-03-15 08:42 UTC, MeKeyCool commented
> @MeKeyCool Than you for review.
> 
> "When in BO, "Set default country from browser language" is set to Yes, it does not work : On FO, when creating an address, the pre-filled country is the "Default country" set in BO instead of the country of the browser." It is a problem as far as I know.
> 
> I check variables on the front office, and all is working fine to the moment of creating object Country. (375 line - $has_currency)
> 
> There is one link with currency. In my opinion wrong IF statemen. Previousely currency for some reaason blocks country assign to context cookie.

Ok my question wasn't clear. According [ Set default country from browser language KO #18008 ](https://github.com/PrestaShop/PrestaShop/issues/18008) steps to reproduce, the bug isn't linked to currency. That's why i suspect at best you fixed another problem.
I'll try to reproduce in the day to understand better and if you found another bug maybe we will have to change the "fixed ticket" field.

Ps. thanks for style ;)

2022-03-15 13:47 UTC, goralczykmarcin commented
> > @MeKeyCool Than you for review.
> > "When in BO, "Set default country from browser language" is set to Yes, it does not work : On FO, when creating an address, the pre-filled country is the "Default country" set in BO instead of the country of the browser." It is a problem as far as I know.
> > I check variables on the front office, and all is working fine to the moment of creating object Country. (375 line - $has_currency)
> > There is one link with currency. In my opinion wrong IF statemen. Previousely currency for some reaason blocks country assign to context cookie.
> 
> Ok my question wasn't clear. According [ Set default country from browser language KO #18008 ](https://github.com/PrestaShop/PrestaShop/issues/18008) steps to reproduce, the bug isn't linked to currency. That's why i suspect at best you fixed another problem. I'll try to reproduce in the day to understand better and if you found another bug maybe we will have to change the "fixed ticket" field. If you follow [ Set default country from browser language KO #18008 ](https://github.com/PrestaShop/PrestaShop/issues/18008) steps to reproduce on your branch you don't reproduce explained problem ?
> 
> Ps. thanks for style ;)

In previouse for some reason currency check blocks assigning country to context.
I'm not change nothing about currency it is where it was. 
In this fix country is assigned if context country !== browser country and country is an object.

And after that I'm doing stuff with currency (it was before my fix, and is unchanged).

My fix add 2nd level of if/else statement to handle it. 

I'm not sure if we are understand each others :)

Please try to reproduce refered issue on my branch. 
You should have country in address step based on your browser language if you select this option in BO. 
Otherwise you will have default country.

Let me know after test please, maybe then it will be more clear, and you will have more specific conclusions for me that I will better understand.

2022-03-16 09:58 UTC, Julievrz commented
It doesn't seem to be any wording in this PR. I'm removing the waiting for wording label but feel free to put it pack or ping me if necessary.

2022-03-17 10:18 UTC, atomiix approved these changes

2022-03-17 17:48 UTC, MeKeyCool commented
Sorry @goralczykmarcin, I was focused on another bug that made me break all my setup during few days and i didn't take time to reproduce.

2022-03-22 08:32 UTC, Progi1984 approved these changes

2022-03-23 15:43 UTC, florine2623 requested changes
Hello @goralczykmarcin ,

Thanks for your PR !

I still have the issue after installing the PR.

My configuration looks like the following :
<img width="1110" alt="Screenshot 2022-03-23 at 16 34 41" src="https://user-images.githubusercontent.com/16019289/159737093-89971be8-abc4-4187-b17e-d3eb4f247038.png">

In FO, when I create an new address as a guest customer, I have the Country pre-filled with Spain ⛔  My browser is not in Spanish.
<img width="659" alt="Screenshot 2022-03-23 at 16 34 21" src="https://user-images.githubusercontent.com/16019289/159738648-4d138448-8573-42b3-a844-51df4b5ae0c9.png">

Here are the languages of my browser :
<img width="712" alt="Screenshot 2022-03-23 at 16 39 52" src="https://user-images.githubusercontent.com/16019289/159738193-bdfe8ee3-c5a1-4a36-8017-8f681760e3b3.png">

So in my case, I should have United-States as a country. In my FO, I should have :
<img width="487" alt="Screenshot 2022-03-23 at 16 41 13" src="https://user-images.githubusercontent.com/16019289/159738475-9693ab06-b38e-4213-82c0-60389ad5c11c.png">

Could you check please ?
Thanks !

2022-03-25 09:43 UTC, florine2623 reviewed
Hello @goralczykmarcin ,

Thanks again for your PR.
As seen with core dev, I will close your PR in favor of #27187 which corrects the same issue.

#27187 seems a bit better, it uses the visitor’s browser language as a fallback whereas your PR uses the shop’s default country which may not be adapted to the visitor.

You can follow the updates of the fix directly here : #27187

Thank you for your understanding.

2022-03-25 09:44 UTC, closed without merging

2022-03-25 12:38 UTC, goralczykmarcin commented
thank you. At least I configured development enviroment. 
This fox works for me at older prestashop 1.7.7. 
I'll be back If I could fixed it for 8.0, now I'm better prepared ;)

Thanks again!

2022-03-25 13:41 UTC, MeKeyCool commented
> thank you. At least I configured development enviroment. This fix works for me at older prestashop 1.7.7. I'll be back If I could fixed it for 8.0, now I'm better prepared ;)
> 
> Thanks again!

Thanks to you for contributions and positive attitude !! :)

2022-03-28 07:10 UTC, goralczykmarcin commented
Hi @florine2623 ,
could you please check it again on the same enviroment? 
When I set up test env. my fix wont work. But today when I run server and open incognioto mode, all works fine ... 
So my fix partially works, but there is something that stops it at fresh prestashop (freshly setted up)

Default country France
![image](https://user-images.githubusercontent.com/77669025/160343306-3a1348d1-08d7-4de7-b502-571d9be27b08.png)

France - ok
![image](https://user-images.githubusercontent.com/77669025/160343208-95767267-7bab-4100-8316-390e0ef06a37.png)

Default country from browser - UK
![image](https://user-images.githubusercontent.com/77669025/160343509-d33a1e59-ff6a-43ec-b14b-caeaa1a2dbc6.png)

Prove - chrome settings
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/77669025/160343775-ddfab234-30bf-489d-97d5-8deed5a2adf3.png">

New user + new address (also tested on existed email, twice)
![image](https://user-images.githubusercontent.com/77669025/160343984-41938524-6499-4ddc-a1f9-bc6bf7c9decd.png)

I have no idea why it start to work, but please check it again on the same enviroment, and let me know if is same for you

2022-03-28 09:54 UTC, MeKeyCool commented
> Hi @florine2623 , could you please check it again on the same environment? When I set up fresh test environment my fix wont work. But today when I run server and open incognioto mode, all works fine ... So my fix partially works, but there is something that stops it at fresh prestashop (freshly setted up)
> [...]
> I have no idea why it start to work, but please check it again on the same environment, and let me know if is same for you

Sorry @goralczykmarcin but if the problem is fixed by another PR, i don't think it is interesting to continue investigating your implementation.

I think you probably managed to fix a problem in a particular situation.
In old code with technical debts, it happens that you have several "hack" or "quick fix" that interfere to create final buggy behavior.

Has code development and validation processes are heavy,  i suggest to keep this issue closed and if you think you found some weird behavior link to your development you could : 
1. Reproduce what you found in a fresh install with up to date code (especially the code that fix initial problem)
2. If you reproduce it, create an issue with a maximum of details (as you added in this comment)
3. If you are really motivated you can propose a fix (maybe the same but you'll have to change your PR details I guess)
> :point_up: If you find a way to add some tests and ensure long term quality, it would be perfect !! :star_struck: 

> Consider that paying down technical debt will be managed by dedicated refactoring tasks ;)

2024-01-11 20:30 UTC, metacreo commented
@florine2623 
> Hello @goralczykmarcin ,
> 
> Thanks again for your PR. As seen with core dev, I will close your PR in favor of #27187 which corrects the same issue.
> 
> #27187 seems a bit better, it uses the visitor’s browser language as a fallback whereas your PR uses the shop’s default country which may not be adapted to the visitor.
> 
> You can follow the updates of the fix directly here : #27187
> 
> Thank you for your understanding.

#27187 not solve this issue with prices