Avoid Notice: Trying to access array offset on value of type bool
PrestaShop/PrestaShop pull request #27922
Opened 2022-03-15 15:43 UTC by danidomen

When you don't have a cart already yet, any module or script that uses this function raises a Notice: Trying to access array offset on value of type bool

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?          | 1.7.8.x
| Description?      | When you don't have a cart already yet, any module or script that uses this function raises a Notice: Trying to access array offset on value of type bool, because Address::getCountryAndState could return an array with the id_country, or if the cart is false, the address also and the function return a false, that is not correct evaluated into the next line (only take account that is returning an array)
| Type?           | bug fix
| Category         | FO
| BC breaks        |  no
| Deprecations     |  no
| Fixed ticket?    | Fixes #27774.
| How to test      | On the issue #27774 is explained how to test it.
| Possible impacts | None, with that simple behaviour is only applying more correctly the condition if the above function returns false when a cart doesn't have a address initialized.
| PR for develop | https://github.com/PrestaShop/PrestaShop/pull/27775

2022-03-16 14:31 UTC, eternoendless approved these changes

2022-03-17 09:57 UTC, atomiix approved these changes

2022-03-17 10:16 UTC, kpodemski approved these changes

2022-03-17 13:48 UTC, PierreRambaud approved these changes

2022-03-23 14:01 UTC, marwachelly requested changes
Hello,

It seems that your module has in impact on the FO when google analytic module is active. And even when your module is disabled there is the following exception in FO.
![image](https://user-images.githubusercontent.com/89604350/159716473-63b60811-3d37-4a54-86e3-2910d9b18792.png)

https://user-images.githubusercontent.com/89604350/159717607-4bcab1e9-dc65-48fb-b09d-94c4fe43261d.mp4



Could you please check ?

2022-03-26 01:26 UTC, danidomen commented
> Hello,
> 
> It seems that your module has in impact on the FO when google analytic module is active. And even when your module is disabled there is the following exception in FO. ![image](https://user-images.githubusercontent.com/89604350/159716473-63b60811-3d37-4a54-86e3-2910d9b18792.png)
> 
>  Untitled_.Mar.23.2022.2_53.PM.mp4 
> Could you please check ?

What do you mean?

2022-03-28 10:10 UTC, marwachelly approved these changes
Hello,
I tested the PR before the new release of google analytic module . Now I retested again with the new [release ](https://github.com/PrestaShop/ps_googleanalytics/pull/115) V4.1.2. It is ok now.
With PHP 7.4:

https://user-images.githubusercontent.com/89604350/160375767-3721dc2a-9d43-4a4a-ab83-abfc25f47632.mp4

With PHP 7.3

https://user-images.githubusercontent.com/89604350/160375979-1675c063-87f0-4d62-b14b-47f68d531aad.mp4

Thanks,

2022-03-28 11:07 UTC, merged

2022-03-28 11:07 UTC, Progi1984 commented
Thanks @danidomen & @marwachelly