Remove AdminController deprecated
PrestaShop/PrestaShop pull request #27959
Opened 2022-03-18 10:01 UTC by PierreRambaud

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | AdminController::initTabModuleList, AdminController::addPageHeaderToolBarModulesListButton, AdminController::addToolBarModulesListButton, AdminController::filterTabModuleList, AdminController::setDeprecatedMedia
| Type?             | improvement
| Category?         | CO
| BC breaks?        | yes - AdminController::initTabModuleList, AdminController::addPageHeaderToolBarModulesListButton, AdminController::addToolBarModulesListButton, AdminController::filterTabModuleList, AdminController::setDeprecatedMedia
| Deprecations?     | no
| Fixed ticket?     | Fixes #26293
| How to test?      | Tests are green.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

2022-03-18 10:03 UTC, kpodemski approved these changes

2022-03-21 07:59 UTC, Progi1984 requested changes, later dismissed
@PierreRambaud Thank you for your contribution. Could you add a PR on devdocs for this BC ? Thanks

2022-03-22 14:51 UTC, saulaski approved these changes

2022-03-22 15:08 UTC, matthieu-rolland approved these changes

2022-03-24 08:01 UTC, merged

2022-03-24 20:42 UTC, matks commented
I add label "Needs documentation". BC break needs to be documented https://devdocs.prestashop.com/8/modules/core-updates/8.0/