Remove Tools::display404Error
PrestaShop/PrestaShop pull request #27958
Opened 2022-03-18 09:57 UTC by PierreRambaud

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove Tools::display404Error
| Type?             | improvement
| Category?         | CO
| BC breaks?        | yes - Remove Tools::display404Error
| Deprecations?     | no
| Fixed ticket?     | Fixes #26293
| How to test?      | Tests are green.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

2022-03-18 09:59 UTC, kpodemski approved these changes

2022-03-21 08:46 UTC, Progi1984 requested changes, later dismissed
Hi @PierreRambaud, Thank you for your contribution.

Could you create a PR on devdocs for this BC ? and explain how migrate for this old method :)

2022-03-22 14:53 UTC, saulaski approved these changes

2022-03-22 15:08 UTC, matthieu-rolland approved these changes

2022-03-24 08:02 UTC, merged

2022-03-24 20:42 UTC, matks commented
I add label "Needs documentation". BC break needs to be documented https://devdocs.prestashop.com/8/modules/core-updates/8.0/