Remove getSafeModeStatus method
PrestaShop/PrestaShop pull request #27957
Opened 2022-03-18 09:53 UTC by PierreRambaud

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove getSafeModeStatus method
| Type?             | improvement
| Category?         | CO
| BC breaks?        | yes - Remove getSafeModeStatus method
| Deprecations?     | no
| Fixed ticket?     | Fixes #26293
| How to test?      | Tests are green.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

2022-03-18 10:04 UTC, kpodemski commented
@PierreRambaud, I'm not sure if we need 100 PRs to open to remove deprecated code? Maybe we could do it with 1 file per 1 PR?

2022-03-18 10:13 UTC, PierreRambaud commented
> @PierreRambaud, I'm not sure if we need 100 PRs to open to remove deprecated code? Maybe we could do it with 1 file per 1 PR?

Nope as deprecated are not always related

2022-03-18 10:37 UTC, PrestaEdit approved these changes

2022-03-21 21:56 UTC, matks approved these changes

2022-03-22 14:54 UTC, saulaski approved these changes

2022-03-29 07:18 UTC, Progi1984 requested changes
Hi Thank you for your contribution. Could you add a linked PR on the devdocs : https://devdocs.prestashop.com/8/modules/core-updates/8.0/#removals ?

2022-04-05 09:41 UTC, Progi1984 approved these changes

2022-04-06 14:41 UTC, matks approved these changes

2022-04-06 14:41 UTC, matks commented
Thank you @PierreRambaud

2022-04-06 14:41 UTC, merged