Option to configure displaying of copyright in the footer
PrestaShop/PrestaShop pull request #27963
Opened 2022-03-18 11:10 UTC by kpodemski

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This is a new option in the back office to allow merchants to hide PrestaShop copyright information from the footer
| Type?             | new feature
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Partially Fixes #9674. - PR for the theme and autoupgrade module are coming
| How to test?      | Install PrestaShop, use `{$configuration|dump}` somewhere in `footer.tpl`, you should see a configuration related to copyrights `display_footer_copyright`, hiding it will be implemented in the theme repository
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

2022-03-18 12:40 UTC, PierreRambaud requested changes
I don't think this one should be integrated in the Core as the theme can remove the copyright itself, or emails theme. Also, it can be done by a module if needed.

2022-03-18 12:56 UTC, kpodemski commented
@PierreRambaud Issue has been validated and accepted by PM. AFAIK there are no plans to have a module with a dedicated setting for a theme, especially classic.

2022-03-18 13:02 UTC, PierreRambaud commented
> @PierreRambaud Issue has been validated and accepted by PM. AFAIK there are no plans to have a module with a dedicated setting for a theme, especially classic.

Adding configuration per theme using the theme.yml is easier to maintain et really better :(

2022-03-18 13:11 UTC, kpodemski commented
@PierreRambaud 

Agree, but this configuration option is for the merchant :-) And theme authors can override this option with their .yml.

I would like to take this opportunity to ask what now. The Issue was discussed, the PM accepted it. I invested time, and it turns out that the maintainer disagrees with the PM. What now? It's a smaller contribution, and I'm not a first-timer here, but what about more extensive topics and new contributors? This is not encouraging further contributions.

cc @PrestaShop/prestashop-maintainers @PrestaShop/product-team

2022-03-18 13:31 UTC, PierreRambaud commented
> @PierreRambaud
> 
> Agree, but this configuration option is for the merchant :-) And theme authors can override this option with their .yml.
> 
> I would like to take this opportunity to ask what now. The Issue was discussed, the PM accepted it. I invested time, and it turns out that the maintainer disagrees with the PM. What now? It's a smaller contribution, and I'm not a first-timer here, but what about more extensive topics and new contributors? This is not encouraging further contributions.
> 
> cc @PrestaShop/prestashop-maintainers @PrestaShop/product-team

We can't follow all issues, this is not a reason why I have to approve all changes only because PM accepted it :thinking: 
Also, something that has been approved months ago doesn't mean it makes sense to integrate it now.
Anyway, I'll not approve this change as I don't think it's the right way to add this kind of feature :)

2022-03-18 13:35 UTC, kpodemski commented
This way, the validated issue has to be discussed again with every maintainer before starting work to make sure that it's worth investing time 🤔 I'm not sure if this is the proper process. I'm not sure what's the point of waiting for PMs in so many issues if, in the end, it's worthless.

2022-03-19 09:21 UTC, SharakPL commented
@kpodemski why `display_footer_copyright`? IMO it's too specific. Should be simply `display_copyright`

2022-03-21 12:51 UTC, kpodemski commented
I need help with this one @PrestaShop/prestashop-maintainers @PrestaShop/product-team 

If the issue is outdated and not really "Ready", I suggest improving it so I can continue or delete it if this feature is no longer needed.

2022-03-22 17:26 UTC, matks commented
@kpodemski did a discussion happen and solve this issue or is there still some uncertainty?

2022-03-22 17:28 UTC, kpodemski commented
@matks I still don't know what to do with this one, and my question about the process is still unanswered.

2022-03-23 07:28 UTC, PierreRambaud commented
> @matks I still don't know what to do with this one, and my question about the process is still unanswered.

You asked it only 2 days ago, I'm pretty sure you can wait a little bit more :p

2022-03-24 18:27 UTC, MatShir commented
I don't see why this PR is blocked if there is no module planned.
There are other features should also be in a module as well.

![Capture d’écran 2022-03-24 à 19 21 42](https://user-images.githubusercontent.com/43613217/159984726-52d9abf8-653f-4464-b82d-75c77adb68be.png)
![Capture d’écran 2022-03-24 à 19 20 32](https://user-images.githubusercontent.com/43613217/159984731-2b4d530d-9c24-4cc4-b056-9a69bf2ab048.png)

Maybe @eternoendless can clarify what are the requirement for the project ?

2022-03-25 23:02 UTC, Hlavtox commented
I don't think core should be cluttered with configurations like these. We could then have a million options built in - show this there, show this on left, show this on right, show purple elephant over there... meh. Deleting copyright from the theme is like 15 second work.

We had a call with @NeOMakinG today and we discussed something like an automatic theme configuration page, that could load theme options from YML. Something like Wordpress theme customization. No core options needed, no theme configurator modules needed. https://github.com/PrestaShop/hummingbird/issues/218

2022-03-25 23:31 UTC, kpodemski commented
I like the idea @Hlavtox but:

- yml is not suitable for it, it should be PHP file
- simple solution is probably not enough,because most themes will come up with their own configurators anyway, to have fields that depends on each other, etc.

of course, we could have something that powerful as theme customizer, but with so many things to do, (definitely more important for ecommerce software) I'm not sure if anyone will have time for this task 😐

2022-03-26 10:40 UTC, mparvazi commented
@Hlavtox 

The config rules in theme.yml must be converted to a css file (e.g. override.css)
But the styling rules have been implemented by scss, so it would be error prone.

Currently we have this problem in RTL for BO. The rules for fixing RTL issues are in css (theme.rtlfix) but BO theme styled by scss.

I mean, something like this makes it harder for theme maintainability.

2022-03-30 07:59 UTC, Progi1984 requested changes
I don't think this should be embed in the Core. It should be embed in a module in the theme.

2022-03-30 08:10 UTC, Hlavtox commented
There would be sooooo many things the customers would like to configure in a theme.... The copyright, quick view, manufacturer on product page, availability on product page, add to cart button on product lists and million other options. :-)

A configurator for this bundled with theme would be nice on one side (as 3rd party themes do it), but on the other side, it's always additional performance loss and complexity. Every configuration is just adding DB queries and if/else statements. With basic HTML skills, you can edit the theme to your liking, remove crap you don't need and keep the performance, maybe even improve it by not executing uneeded code and conditions.

2022-03-30 08:40 UTC, kpodemski commented
@Hlavtox 

Of course, but I don't see questions about this as often as I see questions about removing copyrights. That is a PR to solve a common issue/request, it's probably an overkill to create a module with only one option to configure footer copyrights :-)

Anyway, I'll let wait for what's next because it seems there's a gap in the process as in this PR @PrestaShop/product-team don't agree with @PrestaShop/prestashop-maintainers and I'm not sure what now ;-)

2022-04-04 06:18 UTC, closed without merging

2022-04-14 23:38 UTC, alfonsolr09 commented
I think that it is not a feature that I specifically need (since it can be removed with css for example in a simple way) but it is a useful feature for someone who wants to set up a store without knowledge