Option to duplicate profile with its permissions
PrestaShop/PrestaShop pull request #27966
Opened 2022-03-18 13:03 UTC by kpodemski

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Thanks to this PR, you can easily duplicate employee profiles
| Type?             | new feature
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #16290.
| How to test?      | Follow instructions from Issue
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

2022-03-22 11:08 UTC, PierreRambaud reviewed
Can we wait until the PR about the migrated page is merged?

2022-03-22 13:43 UTC, kpodemski commented
@PierreRambaud sure 👍

2022-03-29 07:08 UTC, Progi1984 commented on src/Adapter/Profile/CommandHandler/BulkDuplicateProfileHandler.php
> +namespace PrestaShop\PrestaShop\Adapter\Profile\CommandHandler;
```suggestion
 */

declare(strict_types=1);

namespace PrestaShop\PrestaShop\Adapter\Profile\CommandHandler;
```

2022-03-29 07:08 UTC, Progi1984 commented on src/Adapter/Profile/CommandHandler/BulkDuplicateProfileHandler.php
> +final class BulkDuplicateProfileHandler extends AbstractProfileHandler implements BulkDuplicateProfileHandlerInterface
```suggestion
class BulkDuplicateProfileHandler extends AbstractProfileHandler implements BulkDuplicateProfileHandlerInterface
```

2022-03-29 07:08 UTC, Progi1984 commented on src/Adapter/Profile/CommandHandler/BulkDuplicateProfileHandler.php
> + * @internal
```suggestion
 * Class BulkDuplicateProfileHandler
```

2022-03-29 07:09 UTC, Progi1984 commented on src/Adapter/Profile/CommandHandler/DuplicateProfileHandler.php
> +final class DuplicateProfileHandler extends AbstractProfileHandler implements DuplicateProfileHandlerInterface
```suggestion
 */
class DuplicateProfileHandler extends AbstractProfileHandler implements DuplicateProfileHandlerInterface
```

2022-03-29 07:09 UTC, Progi1984 commented on src/Core/Domain/Profile/Command/BulkDuplicateProfileCommand.php
> +    public function getProfileIds()
```suggestion
    public function getProfileIds(): array
```

2022-03-29 07:09 UTC, Progi1984 commented on src/Core/Domain/Profile/Command/BulkDuplicateProfileCommand.php
> +    private function setProfileIds(array $profileIds)
```suggestion
    private function setProfileIds(array $profileIds): void
```

2022-03-29 07:09 UTC, Progi1984 commented on src/Core/Domain/Profile/Command/BulkDuplicateProfileCommand.php
> +namespace PrestaShop\PrestaShop\Core\Domain\Profile\Command;
```suggestion
 */

declare(strict_types=1);

namespace PrestaShop\PrestaShop\Core\Domain\Profile\Command;
```

2022-03-29 07:10 UTC, Progi1984 commented on src/Core/Domain/Profile/Command/DuplicateProfileCommand.php
> +namespace PrestaShop\PrestaShop\Core\Domain\Profile\Command;
```suggestion
 */

declare(strict_types=1):

namespace PrestaShop\PrestaShop\Core\Domain\Profile\Command;
```

2022-03-29 07:10 UTC, Progi1984 commented on src/Core/Domain/Profile/Command/DuplicateProfileCommand.php
> +    public function __construct($profileId)
```suggestion
    public function __construct(int $profileId)
```

2022-03-29 07:10 UTC, Progi1984 commented on src/Core/Domain/Profile/Command/DuplicateProfileCommand.php
> +        $this->profileId = new ProfileId((int) $profileId);
```suggestion
        $this->profileId = new ProfileId($profileId);
```

2022-03-29 07:10 UTC, Progi1984 commented on src/Core/Domain/Profile/Command/DuplicateProfileCommand.php
> +    public function getProfileId()
```suggestion
    public function getProfileId(): ProfileId
```

2022-03-29 07:11 UTC, Progi1984 commented on src/Core/Domain/Profile/CommandHandler/BulkDuplicateProfileHandlerInterface.php
> +    public function handle(BulkDuplicateProfileCommand $command);
```suggestion
    public function handle(BulkDuplicateProfileCommand $command): void;
```

2022-03-29 07:11 UTC, Progi1984 commented on src/Core/Domain/Profile/CommandHandler/DuplicateProfileHandlerInterface.php
> +    public function handle(DuplicateProfileCommand $command);
```suggestion
    public function handle(DuplicateProfileCommand $command): void;
```

2022-03-29 07:11 UTC, Progi1984 commented on src/Core/Domain/Profile/Exception/FailedToDuplicateProfileException.php
> +namespace PrestaShop\PrestaShop\Core\Domain\Profile\Exception;
```suggestion
 */

declare(strict_types=1)

namespace PrestaShop\PrestaShop\Core\Domain\Profile\Exception;
```

2022-03-29 07:11 UTC, Progi1984 commented on src/Core/Grid/Definition/Factory/BulkDuplicateActionTrait.php
> +namespace PrestaShop\PrestaShop\Core\Grid\Definition\Factory;
```suggestion
 */

declare(strict_types=1)

namespace PrestaShop\PrestaShop\Core\Grid\Definition\Factory;
```

2022-03-29 07:12 UTC, Progi1984 commented on src/Core/Grid/Definition/Factory/BulkDuplicateActionTrait.php
> +    protected function buildBulkDuplicateAction(string $bulkDuplicateRouteName, array $options = [])
```suggestion
    protected function buildBulkDuplicateAction(string $bulkDuplicateRouteName, array $options = []): SubmitBulkAction
```

2022-03-29 07:12 UTC, Progi1984 commented on src/Core/Grid/Definition/Factory/BulkDuplicateActionTrait.php
> +    abstract protected function trans($id, array $options, $domain);
```suggestion
    abstract protected function trans(string $id, array $options, string $domain): string;
```

2022-03-29 07:12 UTC, Progi1984 commented on src/Core/Grid/Definition/Factory/DuplicateActionTrait.php
> + */
```suggestion
 */

```

2022-03-29 07:13 UTC, Progi1984 commented on src/Core/Grid/Definition/Factory/DuplicateActionTrait.php
> +    abstract protected function trans($id, array $options, $domain);
```suggestion
    abstract protected function trans(string $id, array $options, string $domain): string;
```

2022-03-29 07:13 UTC, Progi1984 commented on src/Core/Grid/Definition/Factory/DuplicateActionTrait.php
> +    ): RowActionInterface {
```suggestion
    ): SubmitRowAction {
```

2022-03-29 07:14 UTC, Progi1984 commented on src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ProfileController.php
> +    public function duplicateAction($profileId)
```suggestion
    public function duplicateAction(int $profileId): RedirectResponse
```

2022-03-29 07:14 UTC, Progi1984 commented on src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ProfileController.php
> +    public function bulkDuplicateAction(Request $request)
```suggestion
    public function bulkDuplicateAction(Request $request): RedirectResponse
```

2022-03-29 07:14 UTC, Progi1984 requested changes
@kpodemski Could you add Behat tests, please ?

2022-03-30 07:49 UTC, Julievrz commented
Wording suggestion:

**Modal**

Title: Duplicate selection?
Body: [No body]
Exit buttons: Cancel/Duplicate (Admin.Actions)

(Although I'm wondering if a modal is really necessary here. It's an additional step for the user when there's no big risk. It's not like he/she is about to delete a bunch of items for good.)

**Label**

About the label of the bulk action, I think the whole wording/design could be improved but in the meantime, I suggest keeping the existing string "Duplicate selection" in Admin.Actions, instead of creating the string "Duplicate selected". (It's also more consistent with other pages).

2022-04-25 09:07 UTC, kpodemski commented
@PierreRambaud can I continue with this one? :>

2022-05-02 07:53 UTC, Progi1984 requested changes
@kpodemski The migrated PR has been merged so you can continue this one (and rebase it).

2022-06-14 13:05 UTC, matks commented
@kpodemski do we keep this PR open or do we close? I'm a little sorry but it seems you could not find time to work on it

2022-06-14 13:10 UTC, kpodemski commented
@matks 

keep it open, please ;-)

2022-06-14 13:41 UTC, kpodemski commented
@Progi1984, would you like me to add a test if the permissions are the same between a source profile and a profile that has been cloned?

2022-06-14 13:44 UTC, Progi1984 commented
@kpodemski It should be perfect.

2023-09-12 19:44 UTC, matks commented
Hi @kpodemski I believe this draft PR is now too stale. I close it for now, just to help navigating old PRs. But we can reopen it anytime you want 😉 obviously. A closed PR does not mean it has to stay closed forever 💪 ! I just do this to make it easier to distinguish old PRs that might be merged one day and PRs that - unfortunately - I think are too old and will never be merged.

Thank you anyway for submitting the PR 👍

2023-09-12 19:44 UTC, closed without merging