Fixed a problem that prevent customer address save
PrestaShop/PrestaShop pull request #27976
Opened 2022-03-19 06:33 UTC by Danoosh

If the hook::exec method returns "null" value the customer address can't be saved.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 1.7.8.x
| Description?      | If the hook::exec method returns "null" value the customer address can't be saved.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | -
| How to test?      | Upgrade Prestashop from 1.6 to 1.7.8.4 and try to add a customer address. PHP version was 7.3.3 in my case if it is matters.
| Possible impacts? | Registered addresses  must be shown on addresses pages both BO and FO

2022-03-19 11:57 UTC, matks requested changes
Hello @Danoosh and thank you for this PR!


It looks like it is a bug fix. Do you think you could submit a bug report so that we can register, then label the bug and also explore it to see if we can find more bad behaviors?

↔️ https://github.com/PrestaShop/PrestaShop/issues/new?assignees=&labels=Bug%2CNew&template=1_bug_report.yml

You modify how a hook return is handled. So ... it seems the issue is related to having a module enabled and registered on this hook, right? Can you check? Maybe the issue is in the module?

2022-03-20 05:13 UTC, Danoosh commented
Hello @[matks](https://github.com/matks), I've checked the hook, and no module had been assigned to the hook.
I changed my code to be true for both null and empty to be safer.
This hook must returns "true" or "false" to affect $is_valid and I think now we do not need more checks, but if you think is needed, I can register a bug report.

2022-03-21 08:57 UTC, matks commented
> This hook must returns "true" or "false" to affect $is_valid and I think now we do not need more checks, but if you think is needed, I can register a bug report.

Bug reports are always great
- it allows someone searching for a bug to find it and know whether it's fixed or not, and which version (so it's like a documentation for PS users)
- it allows us to be aware how many bugs related to a topic to "estimate" the quality of a topic
- it allows us to track and re-verify a bug later if we modify again the zone of code you modify (so it's like a list of items to check when working on this code)
- and sometimes QA find even more bugs when exploring a bug report

2022-03-21 20:54 UTC, matks requested changes
@Danoosh it seems your second commit did introduce a breaking change that is catched by automated tests

See https://github.com/PrestaShop/PrestaShop/runs/5615537460?check_suite_focus=true

```
--- Failed steps:

001 Scenario: Clear outdated employee sessions # Features/Scenario/Security/security_configuration.feature:31
      Then there is 2 employee session left    # Features/Scenario/Security/security_configuration.feature:39
        Failed asserting that 1 is identical to 2.
```

```
$ php -d date.timezone=UTC ./vendor/bin/behat -c tests/Integration/Behaviour/behat.yml --format progress --no-snippets --strict
```

2022-04-05 08:24 UTC, kpodemski commented
@matks 

I had the same error yesterday, but I'm pretty sure it is something specific, not only related to the upgrade process itself.

About tests, it is a completely different part of the system. I think something is wrong there, maybe rebase is needed.

@Danoosh are you plan to work on this PR? :)

2022-04-11 08:02 UTC, Progi1984 commented on classes/form/CustomerAddressForm.php
> +        if (!is_null($hookReturn) && $hookReturn !== '') {
```suggestion
        if ($hookReturn !== null && $hookReturn !== '') {
```

2022-04-11 08:02 UTC, Progi1984 reviewed
@Danoosh For a better readibility.

2022-04-22 20:12 UTC, matks commented
> @Danoosh are you plan to work on this PR? :)

Friendly reminder 😄

2022-07-11 07:06 UTC, Danoosh commented
@marks sorry for the late response
I didn't see your mentions
I've submitted a bug report too.
https://github.com/PrestaShop/PrestaShop/issues/29030

2022-07-11 20:24 UTC, matks reviewed
Thank you @Danoosh 

I wait for issue https://github.com/PrestaShop/PrestaShop/issues/29030 to be confirmed before approving the pull request

2022-08-31 20:20 UTC, matks commented
Hi @Danoosh unfortunately we could not reproduce issue https://github.com/PrestaShop/PrestaShop/issues/29030 so we cannot fully check and review your contribution. You modify how a hook return is handled. Without the usecase related to having a module enabled and registered on this hook I cannot review 😞 .

I will follow [our guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests) and I'll close this pull request as it seems stale.

Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2022-08-31 20:20 UTC, closed without merging

2022-09-19 10:46 UTC, Danoosh commented
Hi @matks, 
I will try to investigate further and find the reason for this problem on some sites. However, I think the changes I suggested do not need to be reviewed and are just code improvements. If for any reason, the Hook::exec method returns a value other than Null and True, the value of $is_valid is changed to false and disrupts the address registration process. Therefore, this improvement is necessary.
Maybe an issue like a module remaining in the database (module files missing) can cause this problem.

2024-02-11 21:11 UTC, kpodemski commented
Fixed on the develop branch. Will be shipped inside v9.