Fix indent on state.yml
PrestaShop/PrestaShop pull request #27996
Opened 2022-03-21 20:52 UTC by matks

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix indent on state.yml
| Type?             | bug fix
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/27995
| How to test?      | CI should report no issue on given PR
| Possible impacts? | No

2022-03-22 13:36 UTC, PierreRambaud commented on src/PrestaShopBundle/Resources/config/routing/admin/improve/international/state.yml
> +    #_ legacy_link: AdminStates:deletestate
```suggestion
    # _legacy_link: AdminStates:deletestate
```

2022-03-22 13:37 UTC, PierreRambaud requested changes, later dismissed
Nice try! I know you try to break this project:
![image](https://user-images.githubusercontent.com/1462701/159494174-8e5555ad-6114-425f-b1d0-8006162264b5.png)

2022-03-22 14:14 UTC, saulaski approved these changes, later dismissed

2022-03-22 15:01 UTC, matthieu-rolland reviewed
Pierre's feedback is accurate, lgtm otherwise ;)

2022-03-22 21:22 UTC, matks commented on src/PrestaShopBundle/Resources/config/routing/admin/improve/international/state.yml
> +    #_ legacy_link: AdminStates:deletestate
Haha 😄 I fixed this yesterday evening but I forgot to push my latest change.

Too bad for me I apply your change then

2022-03-23 07:50 UTC, Progi1984 approved these changes

2022-03-23 15:11 UTC, MeKeyCool reviewed
Why don't you amend initial commit ?
Ps. there is a typo in first commit message.

2022-03-23 16:32 UTC, matthieu-rolland approved these changes

2022-03-23 16:33 UTC, matthieu-rolland commented
thank you @matks

2022-03-23 16:33 UTC, merged

2022-03-23 17:10 UTC, matks commented
> Why don't you amend initial commit ?

To give credit to @PierreRambaud

> Ps. there is a typo in first commit message.

Wooops now it's in prestashop git history forever 😄

2022-03-23 20:37 UTC, MeKeyCool commented
> > Why don't you amend initial commit ?
> 
> To give credit to @PierreRambaud
> 
> > Ps. there is a typo in first commit message.
> 
> Wooops now it's in prestashop git history forever smile

```sh
rm -rf .git
git init
```
:smiling_imp: