Remove useless `sslRedirection` function default behavior.
PrestaShop/PrestaShop pull request #28002
Opened 2022-03-22 11:33 UTC by MeKeyCool

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Double redirection called from server when you have ssl, specific language and `Friendly URL` configuration.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | yes
| Fixed ticket?     | Fixes #17095 .
| How to test?      | Fresh install; allow ssl; add language; configure `Friendly URL`; go to [http://{prestashop_hostname}]() with opened browser console and check that you have only one 302 redirection.
| Possible impacts? | Impacts may be observed on prestashop modules that inherit FrontController.

As we work on next major version, I recommend to remove sslRedirection method with proper comments and documentation to help modules maintainers to detect possible problems.

2022-03-22 13:34 UTC, PierreRambaud requested changes
I'm not sure it's the right way to do it.

Firstly, I'm not able to reproduce with my SSL configuration, when installing PrestaShop, if I go to the HTTP website: 
![image](https://user-images.githubusercontent.com/1462701/159492091-7bc2dec1-4345-4182-b8f1-264341ea7ab1.png)
Then the expected 200:
![image](https://user-images.githubusercontent.com/1462701/159492168-ec8e0695-d747-4dd5-b815-ea2839865e5a.png)


With your change:
![image](https://user-images.githubusercontent.com/1462701/159492286-0b0024b2-7c4f-4ba8-91d4-4febc280fd96.png)

Then a 200:
![image](https://user-images.githubusercontent.com/1462701/159492349-ae138bfa-41bd-4aeb-b1d8-310c7fff71a0.png)


Without your change and curl:
``` 
$ curl -I http://ps-develop.localhost/gb/
HTTP/1.1 301 Moved Permanently
Date: Tue, 22 Mar 2022 13:28:08 GMT
Server: Apache/2.4.52 (Debian)
Upgrade: h2
Connection: Upgrade
Cache-Control: no-cache
Location: https://ps-develop.localhost/gb/
X-XSS-Protection: 0
Content-Type: text/html; charset=utf-8
```

With your change:
```
$ curl -i http://ps-develop.localhost/gb/
HTTP/1.0 302 Moved
Date: Tue, 22 Mar 2022 13:30:32 GMT
Server: Apache/2.4.52 (Debian)
Upgrade: h2
Connection: Upgrade, close
Cache-Control: no-cache
Location: https://ps-develop.localhost/gb/
X-XSS-Protection: 0
Content-Length: 0
Content-Type: text/html; charset=utf-8
```

A 301 redirect means that the page has permanently moved to a new location. A 302 redirect means that the move is only temporary.
So, to conclude, the 301 is the right thing to do, then the check about SSL redirection has nothing in common with canonical URL :thinking:

2022-03-22 17:05 UTC, MeKeyCool commented
> Hello @MeKeyCool!
> 
> This is your first pull request on the PrestaShop project. Thank you, and welcome to this Open Source community!

To reproduce, you should run ```curl -I http://ps-develop.localhost/``` the double redirection happens when you configure your language and don't use it in the request.

The 302 redirection is from ``canonicalRedirection`` function (just above the function I emptyed). I think 302 is ok for language redirect but if you transform URL with 'https' and 'language', how to chose ? By default, i prefered to keep 302 cause i think it may cover other redirections.

2022-03-23 07:30 UTC, PierreRambaud commented
> > Hello @MeKeyCool!
> > This is your first pull request on the PrestaShop project. Thank you, and welcome to this Open Source community!
> 
> To reproduce, you should run `curl -I http://ps-develop.localhost/` the double redirection happens when you configure your language and don't use it in the request.
> 
> The 302 redirection is from `canonicalRedirection` function (just above the function I emptyed). I think 302 is ok for language redirect but if you transform URL with 'https' and 'language', how to chose ? By default, i prefered to keep 302 cause i think it may cover other redirections.

The double redirection is legit, firstly it redirects to the correct protocol, then to the correct canonical page. It's not a problem as HTTP headers are correctly set.
I really think it's bad for SEO to use a 302 instead of a 301 for the HTTPS redirect.

2022-03-23 08:28 UTC, MeKeyCool commented
> > > Hello @MeKeyCool!
> > > This is your first pull request on the PrestaShop project. Thank you, and welcome to this Open Source community!
> > 
> > 
> > To reproduce, you should run `curl -I http://ps-develop.localhost/` the double redirection happens when you configure your language and don't use it in the request.
> > The 302 redirection is from `canonicalRedirection` function (just above the function I emptyed). I think 302 is ok for language redirect but if you transform URL with 'https' and 'language', how to chose ? By default, i prefered to keep 302 cause i think it may cover other redirections.
> 
> The double redirection is legit, firstly it redirects to the correct protocol, then to the correct canonical page. It's not a problem as HTTP headers are correctly set. I really think it's bad for SEO to use a 302 instead of a 301 for the HTTPS redirect.

Ok then #17095 is not a bug. Who should close it ?

2022-03-29 14:04 UTC, matks commented
> Ok then https://github.com/PrestaShop/PrestaShop/issues/17095 is not a bug. Who should close it ?

Decision must be made by @PrestaShop/product-team -> I add the label "Waiting for PM"

2022-04-11 13:13 UTC, closed without merging