Fixed wording and color button on exit button for the bulk delete
PrestaShop/PrestaShop pull request #28003
Opened 2022-03-22 15:29 UTC by Progi1984

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fixed wording and color button on exit button for the bulk delete
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27836
| How to test?      | Cf #27836<br><br>Catalog > Products<br>![image](https://user-images.githubusercontent.com/1533248/159663614-b1b0ed35-c097-4f5f-a006-4c77caedfa8b.png)<br><br>Catalog > Categories<br>![image](https://user-images.githubusercontent.com/1533248/159663667-b4804a64-de15-41f7-b603-5af9b0db6460.png)<br><br>Customers > Customers<br>![image](https://user-images.githubusercontent.com/1533248/159663772-dc1faa2f-7c43-470b-9cd2-fdc30f38d0be.png)

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/28003)

2022-03-22 15:30 UTC, PierreRambaud submitted a review, later dismissed

2022-03-22 17:04 UTC, Julievrz commented
The strings are in the right translations domains. 👍 Could you please provide a screenshot to see the wording in context? :)

2022-03-22 17:35 UTC, matks approved these changes, later dismissed

2022-03-22 18:46 UTC, Progi1984 commented
@Julievrz It's a fix for #27836 (Replace Close by Cancel in some Bulk Delete Modals).

2022-03-23 08:33 UTC, Julievrz commented
> @Julievrz It's a fix for #27836 (Replace Close by Cancel in some Bulk Delete Modals).

Yep I know I just wanted to check that the replacement was done in the right place

2022-03-23 09:13 UTC, Progi1984 commented
@Julievrz Ok. I updated the PR.

2022-03-23 09:18 UTC, NeOMakinG submitted a review, later dismissed

2022-03-23 09:55 UTC, Julievrz commented
Thanks

2022-03-23 16:31 UTC, matthieu-rolland submitted a review, later dismissed

2022-03-23 16:32 UTC, florine2623 requested changes
Hello @Progi1984 ,

Thanks for the PR !

In BO > Catalog > Products, the wording of the button should be "Delete" instead of "Delete now" ⛔  (in FR it's OK)

<img width="634" alt="Screenshot 2022-03-23 at 17 25 08" src="https://user-images.githubusercontent.com/16019289/159749026-84fbeff1-a605-4985-b92e-61ce57cfd062.png">

Tested on all pages containing a bulk edit on migrated page. Looks great (colors and wording) ✅ 

Thanks!

2022-03-24 09:49 UTC, atomiix approved these changes

2022-03-24 09:49 UTC, Progi1984 commented
@florine2623 Fixed your wording issue.

2022-03-24 17:31 UTC, florine2623 approved these changes
@Progi1984 ,

Thanks, LGTM
QA ✅

2022-03-24 20:02 UTC, merged

2022-03-24 20:02 UTC, Progi1984 commented
Thanks @florine2623