BO Bugfix - Add new order - Cart rule description is not correct
PrestaShop/PrestaShop pull request #28012
Opened 2022-03-22 23:58 UTC by buggyzap

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR fix a bug in cart rule description field, was showed the same "name" value in the description field while you apply the rule during backoffice order creation.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27951 
| How to test?      | In the BO > Orders > Add new order > Voucher application, the description of the voucher is now correct.
| Possible impacts? | Backoffice order creation and cart rule application

BEFORE:

![158851555-67de363c-ff31-4d7b-ab1e-e35e43e8d72a](https://user-images.githubusercontent.com/14024456/159594716-a50699f1-a597-4c6a-b967-9b8142dbf552.png)

AFTER:

<img width="1049" alt="Schermata 2022-03-23 alle 00 42 05" src="https://user-images.githubusercontent.com/14024456/159594736-5d99b8ec-eea1-4b7d-841e-5431b242059d.png">

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/28011)

2022-03-23 07:18 UTC, PrestaEdit requested changes

2022-03-23 07:18 UTC, PrestaEdit commented on classes/Cart.php
> +            if(Tools::version_compare(_PS_VERSION_, '1.5.0.2', '<') === true){
Missing a space between if and the (.

Also, we will never been in this if statement.

2022-03-23 11:11 UTC, MeKeyCool approved these changes

2022-03-23 11:39 UTC, MeKeyCool reviewed
```Notice: Undefined index: id_discount in /home/runner/work/PrestaShop/PrestaShop/src/Adapter/Cart/CommandHandler/AddCartRuleToCartHandler.php line 121```

Then l.121 : ```Cache::clean('getContextualValue_' . $previousCartRule['id_discount'] . '_*');```

If `id_discount` key is used in cache key, impact should be reevaluated.

Please search `id_discount` usage in the project to evaluate impact of this removal.

2022-03-23 11:46 UTC, MeKeyCool requested changes
```Notice: Undefined index: id_discount in /home/runner/work/PrestaShop/PrestaShop/src/Adapter/Cart/CommandHandler/AddCartRuleToCartHandler.php line 121```

Then l.121 : ```Cache::clean('getContextualValue_' . $previousCartRule['id_discount'] . '_*');```

If `id_discount` key is used in cache key, impact should be reevaluated.

Please search `id_discount` usage in the project to evaluate impact of this removal.

2022-03-23 22:04 UTC, buggyzap commented
> `Notice: Undefined index: id_discount in /home/runner/work/PrestaShop/PrestaShop/src/Adapter/Cart/CommandHandler/AddCartRuleToCartHandler.php line 121`
> 
> Then l.121 : `Cache::clean('getContextualValue_' . $previousCartRule['id_discount'] . '_*');`
> 
> If `id_discount` key is used in cache key, impact should be reevaluated.
> 
> Please search `id_discount` usage in the project to evaluate impact of this removal.

It's better to keep id_discount to preserve possible bugs, we just need to don't override description property of cart rule.
Maked a new commit.

2022-03-24 09:21 UTC, MeKeyCool requested changes
Looking at the error messages you got in CI, it seems that having an empty description may induce an exception :
{repos}/tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php
```php
if (!isset($contextualReductionValues[$currentCartRule['description']])) {
    throw new \RuntimeException(sprintf('Cart rule %s was not expected.', $currentCartRule['description']));
}
```
You have to analyze deeper expected behavior.
Should we consider description optional ?
If not, maybe a database migration is required to ensure description isn't empty and set with name if not defined in db.
...
> :point_up: Don't hesitate to run tests on your side before pushing, it may help to save iterations time. (you can find commands in CI if you don't know them)


If i read this code from nowhere, i really don't understand why `id_discount = id_cart_rule`. "retro compatibility" comment helps me to understand. For me it would be interesting to keep some comments with your deep analysis of the situation (maybe not in this part of the code).

I don't like the idea to have 3 commits for such modifications. Imagine you introduce a bug i have to investigate on in 2 or 3 months. If i search for the commit which introduces it using a tool like [git bisect](https://git-scm.com/docs/git-bisect) those 3 commits may be really confusing.

2022-03-24 11:39 UTC, buggyzap commented
> Looking at the error messages you got in CI, it seems that having an empty description may induce an exception : {repos}/tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php
> 
> ```
> if (!isset($contextualReductionValues[$currentCartRule['description']])) {
>     throw new \RuntimeException(sprintf('Cart rule %s was not expected.', $currentCartRule['description']));
> }
> ```
> 
> You have to analyze deeper expected behavior. Should we consider description optional ? If not, maybe a database migration is required to ensure description isn't empty and set with name if not defined in db. ...
> 
> > ☝️ Don't hesitate to run tests on your side before pushing, it may help to save iterations time. (you can find commands in CI if you don't know them)
> 
> If i read this code from nowhere, i really don't understand why `id_discount = id_cart_rule`. "retro compatibility" comment helps me to understand. For me it would be interesting to keep some comments with your deep analysis of the situation (maybe not in this part of the code).
> 
> I don't like the idea to have 3 commits for such modifications. Imagine you introduce a bug i have to investigate on in 2 or 3 months. If i search for the commit which introduces it using a tool like [git bisect](https://git-scm.com/docs/git-bisect) those 3 commits may be really confusing.

Sorry, you are right.
It's the first time I collaborate in open source project and is all new for me, I never used this workflow in my projects and i'm just learning.

It's too frustrating even for me to find out these exceptions happen and waste your time.

I love Prestashop and work with it every day, developing new modules and adding new features for my projects.

Thanks for your time and your suggestions, next time i will do the CI tests on my side before make a commit.

Do you suggest creating a new PR with 1 commit to avoid this confusion about commits in the future? Or just create a last commit with the best solution?

2022-03-24 13:38 UTC, MeKeyCool commented
@buggyzap I percfectly understand you as I just joined prestashop team and I am completly lost with github workflow xD

It really great that you contribute and even if i have really cold or pragmatic comments sometimes I hope you won't take any of them personally ^^

The advantage I see with fork and pull request workflow is that you can easily rebase your branch ^^ 
So I think you can rebase your commits to merge them and force push on your own branch.
Once your branch is clean, you can use `commit --amend` command for next modifications ^^

If you are not sure how to contribute / add some information, you may check dev documentation. For exemple you can find some documentation about [writing a good commit message](https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/writing-a-good-commit-message/)

> :point_up: This documentation is also open source so if you find some lacks, mistakes, etc. Feel free to contribute as well ^^

2022-03-29 07:43 UTC, Progi1984 requested changes
@buggyzap Thank you for your contribution. Could you fix Integration Tests ?

2022-03-29 21:13 UTC, buggyzap commented
I'm get stuck with git and I created a slaughterhouse.. Opened new clean PR at #28070

I was no longer able to connect the new commit to the existing request after the rebase 😠 forgive me but I'm trying to understand...

2022-04-01 20:54 UTC, kpodemski commented
Hi @buggyzap 

We can close this PR then?

2022-04-01 21:08 UTC, closed without merging