Update config.yml to follow Symfony3.4+ syntax
PrestaShop/PrestaShop pull request #28046
Opened 2022-03-27 17:13 UTC by pajasry

Since Symfony 3.4, the YAML component uses the syntax without the colon.

https://symfony.com/doc/current/components/yaml.html#parsing-php-constants

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 1.7.8.x
| Description?      | Since Symfony 3.4, the YAML component uses the syntax without the colon.
| Type?             | bug fix
| Category?         | FO / BO
| BC breaks?        | yes
| Deprecations?     | yes
| Fixed ticket?     | Fixes #{26884}.
| How to test?      | There is no need to test as this is not a prestashop component and the syntax is already in use by prestashop code
| Possible impacts? | YAML parsing

2022-04-04 06:49 UTC, Progi1984 requested changes
@pajasry It seems that the issue is closed. Could you validate the issue with @PrestaShop/qa-functional before the review ?

2022-06-14 13:03 UTC, matks commented
Hi,

Since we had no news from you for more than 30 days, I will follow [our guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests) and I'll close this pull request as it seems stale. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2022-06-14 13:03 UTC, closed without merging

2022-09-26 15:49 UTC, Kerami82 commented
Hello. I had the same problem like author #26884, and this solution help me. Prestashop 1.7.8.7.

2024-01-26 18:08 UTC, pajasry commented
Hi it looks like the bug still persist. I ran in to it while updating to 1.7.8.8 today. Would it be possible take a look at it? This fix should still work