Fix iframe modal scrollbars
PrestaShop/PrestaShop pull request #28050
Opened 2022-03-28 09:16 UTC by jolelievre

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix scrollbars bug in IframeModal component
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25735
| How to test?      | Test that the iframe modal has no scrollbars anymore, mostly used on new product page (creation prudtc modal, attachment creation modal)
| Possible impacts? | ~

2022-03-28 09:42 UTC, NeOMakinG commented on admin-dev/themes/new-theme/js/components/modal/iframe-modal.ts
> +    // @ts-ignore
Wut? Why?

2022-03-28 09:46 UTC, NeOMakinG commented
@jolelievre could we plan a 1:1 about this? I'm not really understanding the need for this layer over HTML Events, I may miss something

Also, your `@ts-ignore` made me think that we should really dive into every `@ts-ignore` in the project, pretty sure most of these can be removed now

2022-03-28 10:41 UTC, NeOMakinG approved these changes

2022-03-29 08:45 UTC, matthieu-rolland approved these changes

2022-03-29 13:03 UTC, florine2623 requested changes
Hello @jolelievre ,

Thanks for the PR !

I have a scrollbar when I zoom to 200% or more on my browser :

https://user-images.githubusercontent.com/16019289/160616065-ccab1ceb-6a1b-4240-b4d1-24aa81dde042.mov

Also, I have a black border on that modal. I don't think it should be here as shown in this comment : https://github.com/PrestaShop/PrestaShop/pull/26024#issuecomment-998143843 :
<img width="1100" alt="Screenshot 2022-03-29 at 14 59 03" src="https://user-images.githubusercontent.com/16019289/160616697-affa2fb5-67e0-4bc6-8a4d-df18d9ee07ea.png">

Could you check ? 

Otherwise it looks good to me ! I checked on desktop as well as mobile. Files are well uploaded.

| <img width="860" alt="Screenshot 2022-03-29 at 14 53 33" src="https://user-images.githubusercontent.com/16019289/160617023-8e4e1786-8df4-469b-a7bb-f9d4f931b4f9.png"> | <img width="343" alt="Screenshot 2022-03-29 at 14 53 57" src="https://user-images.githubusercontent.com/16019289/160617101-23edf6b5-c360-4c9d-811e-ceab5a10fb6a.png"> |
| ------------- | ------------- |

Thanks!

2022-04-04 13:03 UTC, jolelievre commented
Hi @florine2623 

about the border it's not related to this PR As far as I can see it is from the boostrap scss https://github.com/twbs/bootstrap/blob/dca1ab7d877bc4b664b43604657a2b5fbe2b4ecb/scss/_modal.scss#L116 so it has always been there.

About the zoom, I tested it but I couldn't reproduce your issue. I'm not sure it's part of the PR either seems like an edge case I didn't know we were supposed to support all custom modifications made by the user on its own environment.

To confirm with @MatShir

2022-04-07 09:43 UTC, MatShir commented
The dark borderline wasn't introduced by this PR, and can be found it other modal in the back office in the develop branch. For this part, I suggest making a dedicated issue with the scroll bar behavior. So we can discuss it with @TristanLDD.

2022-04-07 09:44 UTC, MatShir commented
If it is the last bug from this PR, is the PR ready ? 😄

2022-04-07 11:26 UTC, florine2623 approved these changes
Hello @jolelievre & @MatShir ,

Thanks for your comments !
Then it looks good to me ^^
It is QA ✅

2022-04-07 11:32 UTC, merged