Remove special characters but keep accents with Accented URLs enabled
PrestaShop/PrestaShop pull request #28059
Opened 2022-03-29 12:19 UTC by AlexTechDev

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Description?      | Remove special characters but keep accents in the "reset url" button on products pages when "Accented URLs" is enabled 
| Type?             | bug fix 
| Category?         | BO 
| BC breaks?        | no
| Deprecations?     |  no
| Fixed ticket?     | Fixes PrestaShop/Prestashop#21495
| How to test?      | Enable Accented URLs, go to products and select a product then write a title with an accent and special character, e.g. Camión m² and then in SEO tab click on Reset URL.

We don't have Unicode range for special characters so we have to put unicode codes one by one (the most commons  ones)

2022-03-29 14:23 UTC, matks commented
A good first pull request @AlexTechDev 🎉

2022-03-29 14:26 UTC, matks reviewed
Hello, I think the code is working 👍 but I ask myself: will this line of code be easy to maintain in the next years?

Could we find a way to make sure that, if in 8 months, I need to explore a bug where a character is mistakenly modified by this line, I easily find the issue? One idea I have is to provide a quick list of target characters in a comment line. Maybe you have other ideas 😉

2022-03-29 14:32 UTC, AlexTechDev commented
Thanks @matks ! The first PR of many to come :) :)

About your question, I agree with you I can add the symbols in a comment line, this will also make it easier to see the symbols we currently have "controlled".

2022-03-30 06:34 UTC, kpodemski commented
@atomiix 

Hey Thomas, I think the latest changes to pr.yml fail with the content of this commit description.

2022-03-30 09:35 UTC, atomiix commented
@kpodemski fixed in #28078

2022-04-04 07:12 UTC, Progi1984 requested changes
@AlexTechDev Thank you for your contribution. Could you add a comment in your comment for a better and future readibility of the line ? Thanks for advance.

2022-04-06 14:12 UTC, AlexTechDev commented
@Progi1984 I just add one commented line with all the symbols.

@matks  Thanks for this idea!

2022-04-07 12:46 UTC, kpodemski requested changes
Unfortunately, there's something wrong with automated tests. Your change broke something, and tests are not passing. Make sure to check the tests report and try to follow the steps described in the test scenario.

2022-04-11 08:18 UTC, AlexTechDev commented
Hi @kpodemski  i will take a look. 
Looking the logs it seems that fails in "BO - Catalog - Products : Create, read, update and delete Standard product in BO"
But in local i can create, read and update without problem, maybe the commented line is the cause of the problem

2022-04-25 07:12 UTC, Progi1984 commented on js/admin.js
> +   str = str.replace(/[\u00AC\uFFE2\u00AE\u2122\u00A9\u20AC\u0024\uFF04\uFE69\u00B0\u00B2\u00B3\u00B9\u02AF\u0670\u0711\u2121\u213B\u2207\u29B5\u2070\u2071\u2074-\u208E\u2090-\u209C\u17D2\u1D62-\u1D6
```suggestion
    str = str.replace(/[\u00AC\uFFE2\u00AE\u2122\u00A9\u20AC\u0024\uFF04\uFE69\u00B0\u00B2\u00B3\u00B9\u02AF\u0670\u0711\u2121\u213B\u2207\u29B5\u2070\u2071\u2074-\u208E\u2090-\u209C\u17D2\u1D62-\u1D6A\u2A27]/g, '');
```

Fix indentation

2022-04-25 07:13 UTC, Progi1984 reviewed
A small comment for fixing the indentation

2022-06-16 21:40 UTC, kpodemski commented
Hello @AlexTechDev 

This PR is still failing on UI tests + there's a comment from Franck.

2022-08-31 20:13 UTC, matks commented
Hi,

Since we had no news from you for more than 30 days, I will follow [our guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests) and I'll close this pull request as it seems stale. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2022-08-31 20:13 UTC, closed without merging