BO Bugfix - Add new order - Cart rule description is not correct
PrestaShop/PrestaShop pull request #28070
Opened 2022-03-29 21:12 UTC by buggyzap

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR fix a bug in cart rule description field, was showed the same "name" value in the description field while you apply the rule during backoffice order creation. Old pull request #28012 
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27951 
| How to test?      | In the BO > Orders > Add new order > Voucher application, the description of the voucher is now correct.
| Possible impacts? | Backoffice order creation and cart rule application

BEFORE:

![158851555-67de363c-ff31-4d7b-ab1e-e35e43e8d72a](https://user-images.githubusercontent.com/14024456/159594716-a50699f1-a597-4c6a-b967-9b8142dbf552.png)

AFTER:

<img width="1049" alt="Schermata 2022-03-23 alle 00 42 05" src="https://user-images.githubusercontent.com/14024456/159594736-5d99b8ec-eea1-4b7d-841e-5431b242059d.png">

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/28011)

2022-04-04 06:09 UTC, PierreRambaud requested changes
Unfortunately, I don't know why, but tests are failing.
Maybe you could adapt tests in order to fix it

2022-04-05 08:25 UTC, Progi1984 requested changes
It seems that the description is used in Behat tests. Could you check it ?

2022-04-05 18:29 UTC, buggyzap commented
> It seems that the description is used in Behat tests. Could you check it ?

I'm trying. Really very frustrating 😞

2022-04-11 08:28 UTC, Progi1984 approved these changes

2022-04-11 15:17 UTC, atomiix commented on classes/Cart.php
> +            $row['description'] = $row['obj']->description;
I think you can simply remove this line
```suggestion
```

2022-04-14 08:15 UTC, buggyzap commented on classes/Cart.php
> +            $row['description'] = $row['obj']->description;
This may cause errors in CI/CD

2022-04-22 20:14 UTC, matks approved these changes

2022-04-22 20:14 UTC, matks commented on classes/Cart.php
> +            $row['description'] = $row['obj']->description;
I agree to keep it just in case it was used

2022-04-26 11:03 UTC, khouloudbelguith requested changes
Hi @buggyzap,

**First issue**
1. Create a cart rule with a description too long 
2. Go to BO > Orders > Add new Order > Choose a customer & choose a product
3. Search the cart rule & add it
4. See error

https://user-images.githubusercontent.com/16067358/165285299-d47ea4ba-dca3-4130-8d51-b237945994e5.mp4

**Second issue**
1. Create a cart rule with a description 
![image](https://user-images.githubusercontent.com/16067358/165285850-688a4af8-9328-4294-ad43-d297d7865dcf.png)
2. Go to FO > Sign in
3. Go to FO > Your account > Vouchers
4. See error  
![image](https://user-images.githubusercontent.com/16067358/165285985-23a520cd-855f-4f4b-8cc7-85eab4fb053e.png)

**Third issue**
Automatic tests are failed ping @PrestaShop/qa-automation 
[add_neworder_voucher.pdf](https://github.com/PrestaShop/PrestaShop/files/8562536/add_neworder_voucher.pdf)

Thanks!

2022-04-30 19:15 UTC, buggyzap commented
> Hi @buggyzap,
> 
> **First issue**
> 
>     1. Create a cart rule with a description too long
> 
>     2. Go to BO > Orders > Add new Order > Choose a customer & choose a product
> 
>     3. Search the cart rule & add it
> 
>     4. See error
> 
> 
> Create.order.PrestaShop.mp4
> 
> **Second issue**
> 
>     1. Create a cart rule with a description
>        ![image](https://user-images.githubusercontent.com/16067358/165285850-688a4af8-9328-4294-ad43-d297d7865dcf.png)
> 
>     2. Go to FO > Sign in
> 
>     3. Go to FO > Your account > Vouchers
> 
>     4. See error
>        ![image](https://user-images.githubusercontent.com/16067358/165285985-23a520cd-855f-4f4b-8cc7-85eab4fb053e.png)
> 
> 
> **Third issue** Automatic tests are failed ping @PrestaShop/qa-automation [add_neworder_voucher.pdf](https://github.com/PrestaShop/PrestaShop/files/8562536/add_neworder_voucher.pdf)
> 
> Thanks!

Hi,

these errors is not related to this PR but are present anyway. This PR fix a specific BUG in specific context, issue that you have mentioned is not related to that code edit.

2022-05-06 14:53 UTC, khouloudbelguith commented
Hi @buggyzap,

Thanks for your feedback.
ping @PrestaShop/product-team could you please confirm that we can accept this PR although we have the first issue & the second issue?

Thanks!

2022-06-14 13:02 UTC, matks commented
> ping https://github.com/orgs/PrestaShop/teams/product-team could you please confirm that we can accept this PR although we have the first issue & the second issue?

friendly reminder @PrestaShop/product-team

2022-10-07 08:35 UTC, khouloudbelguith commented
Hello :slightly_smiling_face: 

Ping @PrestaShop/product-team friendly reminder.

Thanks!

2022-10-07 09:04 UTC, camilleganzin commented
Hey there! 
The description of a cart rules is not public. It helps shop employees understand why the rule was created.
In that way, I think this PR is okay to be merged but the second issue about the FO is not an issue, because users don't have to see the cart rule description, only the name. (For this case, the right way to correct it would be to change the label "Description" to "Name").

2022-10-07 14:51 UTC, khouloudbelguith commented
Thanks @camilleganzin for your feedback.
Ping @buggyzap could you please try to fix the second issue
`(For this case, the right way to correct it would be to change the label "Description" to "Name").`

Thanks!

2022-10-09 13:27 UTC, buggyzap commented
> Thanks @camilleganzin for your feedback. Ping @buggyzap could you please try to fix the second issue `(For this case, the right way to correct it would be to change the label "Description" to "Name").`
> 
> Thanks!

Hi, I can't on this repo because is theme specific label content

themes/classic/templates/customer/discount.tpl
<img width="590" alt="Schermata 2022-10-09 alle 15 25 53" src="https://user-images.githubusercontent.com/14024456/194759457-0a176003-b974-4355-8b12-72234d9668ce.png">

If you merge this PR I will create a new issue and commit in classic theme linked to this PR.

2022-10-28 21:55 UTC, kpodemski commented
Hello @buggyzap 

You can create a PR here:
https://github.com/PrestaShop/classic-theme/pulls

And QA then can test this PR with theme PR together 👍 😄 Could you do that?

2022-11-02 22:34 UTC, buggyzap commented
> Hello @buggyzap
> 
> You can create a PR here: https://github.com/PrestaShop/classic-theme/pulls
> 
> And QA then can test this PR with theme PR together 👍 😄 Could you do that?

Sure! @khouloudbelguith 

Please check https://github.com/PrestaShop/classic-theme/pull/71

It's just a typo @kpodemski  :)

2022-12-19 17:32 UTC, matks approved these changes

2022-12-19 17:34 UTC, matks commented
Hello @buggyzap I'm sorry a little issue in process made this PR go stale. I fixed it by reading all comments, finding what happened, who asked for what and completed all this information in PR descriptions. It should now be OK.

We can ask QA team to test again this PR together with https://github.com/PrestaShop/classic-theme/pull/71 to confirm bug is fixed :) and have this PR merged

2022-12-20 09:36 UTC, HanaRebaiQA commented
Hello @matks 

If I understood correctly, we should test both two PRs ([The current one](https://github.com/PrestaShop/PrestaShop/pull/28070) and [#classic-theme/pull/71](https://github.com/PrestaShop/classic-theme/pull/71 ) in parallel, right?

If yes, could you please add the waiting for QA label for the classic theme [PR](https://github.com/PrestaShop/classic-theme/pull/71) ?

Thank You!

2022-12-20 16:08 UTC, HanaRebaiQA reviewed
Hello @buggyzap 

I have checked your PR. For the origin issue, it's OK. I have checked with : 

-With multistore : OK
-The cart rule in order page In BO : OK
-The cart rule in order page In FO : OK
-Check with different languages : OK
-Check with different browsers : OK
-Check with different php versions (7.3 and 8.1) : OK


But, I found this issue related to automated tests : 
![image](https://user-images.githubusercontent.com/92912932/208702057-e72cae20-d2c9-451d-9ac3-ea2edbccf94a.png)

https://github.com/HanaRebaiQA/testing_pr/actions/runs/3738788705/jobs/6349387247
ping @PrestaShop/qa-automation Could you please check this issue please? if it's related to this PR cause the nightly is all green!

Also for the issue of translation that I mentioned [here](https://github.com/PrestaShop/classic-theme/pull/71#pullrequestreview-1224757451) 

Thank you!

2023-01-12 22:02 UTC, SharakPL commented on classes/Cart.php
>              // Retro compatibility < 1.5.0.2
😱

2023-01-12 22:46 UTC, kpodemski commented
cc @PrestaShop/qa-automation - I think the tests have to be improved to respect this change

2023-01-19 14:29 UTC, florine2623 approved these changes
Hello @buggyzap ,

Cart rule description is correct in BO:
<img width="1207" alt="Screenshot 2023-01-19 at 11 31 25" src="https://user-images.githubusercontent.com/16019289/213419394-2aa83c88-7505-4cbb-a1fa-29f91d487133.png">

In FO, the column Name has been changed as well:
<img width="1130" alt="Screenshot 2023-01-19 at 11 24 46" src="https://user-images.githubusercontent.com/16019289/213418332-f5075d6e-79bc-4d3e-8bb3-d747e39eac56.png">

Although, automated tests are NOK : https://github.com/florine2623/testing_pr/actions/runs/3957130954/jobs/6780056954

I will ping @nesrineabdmouleh to check this part.

Other than that, it is QA ✅ let's wait @nesrineabdmouleh before merging this PR ^^

Thanks all !

2023-01-19 21:25 UTC, merged

2023-01-19 21:25 UTC, FabienPapet commented
Thank you [buggyzap](https://github.com/buggyzap) !