Update composer.json author
PrestaShop/PrestaShop pull request #28100
Opened 2022-04-01 08:27 UTC by le-melon

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | https://www.usine-digitale.fr/article/l-editeur-de-sites-e-commerce-prestashop-rachete-par-mbe-worldwide.N1163817
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| How to test?      | 
| Possible impacts? |

2022-04-01 08:31 UTC, PierreRambaud commented on composer.json
> +            "email": "contact@mbecorporate.com/"
```suggestion
            "email": "contact@mbecorporate.com"
```
sorry, incorrect email.

@matks wdyt?

2022-04-01 08:31 UTC, PierreRambaud requested changes
The email seems incorrect, dunno if we can accept it

2022-04-01 08:44 UTC, PrestaEdit requested changes
It's sill PrestaShop SA, as I know.
Also, it's maybe not more PrestaShop SA nor MBE, it's PrestaShop OS Project, imho.

2022-04-01 08:50 UTC, le-melon commented
Integration tests, PHP / PHP CS Fixer and Sanity failing

need to fix it I will open a not break PR

2022-04-01 11:59 UTC, closed without merging

2022-04-04 10:54 UTC, eternoendless commented
Ha ha, nice April fool's joke ;)