Update ProductLazyArray.php
PrestaShop/PrestaShop pull request #28110
Opened 2022-04-01 22:39 UTC by Amit-Kumar-Tiwari-Webkul

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop /1.7.8.5
| Description?      | out of stock" label displayed with stock management disabled
| Type?             | bug fix 
| Category?         | FO / BO / CO / IN / WS / TE / LO / ME / PM
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #28097 
| How to test?      | - Go to product configuration and disable stock management<br> - Go to Catalogue Stocks<br>- Put the stock of some product in 0 or a negative value for example, <br>- Go to FO and see the bug (the out of stock flag is displayed on the product page & category list page)

2022-04-02 09:00 UTC, kpodemski submitted a review, later dismissed

2022-04-02 19:55 UTC, matks requested changes
Dear @Amit-Kumar-Tiwari-Webkul I think this PR is valid but it needs to target branch `1.7.8.x` if you wish to deliver this in next patch version 1.7.8.6

2022-04-03 13:51 UTC, Amit-Kumar-Tiwari-Webkul commented
> Dear @Amit-Kumar-Tiwari-Webkul I think this PR is valid but it needs to target branch `1.7.8.x` if you wish to deliver this in next patch version 1.7.8.6

After Updating the base branch it shows several conflicts.
Should I open the new PR from 1.7.8.x branch?

2022-04-04 09:22 UTC, matks commented
> Should I open the new PR from 1.7.8.x branch?

yes it was the good thing to do and you did it in https://github.com/PrestaShop/PrestaShop/pull/28112 so I close this PR

2022-04-04 09:22 UTC, closed without merging