Migration - Adds commands for Store delete and bulk delete
PrestaShop/PrestaShop pull request #28143
Opened 2022-04-05 21:27 UTC by LouisAUTHIE

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Adds commands for Store delete and bulk delete
| Type?             | improvement
| Category?         | N/A
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| Related PRs       | N/A
| How to test?      | Run ./vendor/bin/behat -c tests/Integration/Behaviour/behat.yml -s store
| Possible impacts? | Nil

2022-04-06 06:35 UTC, LouisAUTHIE commented
Ping @Progi1984 !

2022-04-11 07:43 UTC, Progi1984 approved these changes, later dismissed

2022-04-11 09:48 UTC, LouisAUTHIE commented
Thx @Progi1984. Ping @jolelievre !

2022-04-11 09:49 UTC, LouisAUTHIE commented
Ping @saulaski if you want to flow me with this migration ! Thx to all the maintainers for their help

2022-04-11 14:19 UTC, jolelievre requested changes
Thanks @LouisAUTHIE 

just a few suggestions about typos and indentation.

But mainly the `GetStoreForDeleting` query seems overkill and could be removed.

2022-04-11 14:19 UTC, jolelievre commented on src/Core/Domain/Store/Command/DeleteStoreCommand.php
> +     * @var storeId
```suggestion
     * @var StoreId
```

2022-04-11 14:19 UTC, jolelievre commented on src/Adapter/Store/QueryHandler/GetStoreForDeletingHandler.php
> +class GetStoreForDeletingHandler implements GetStoreForDeletingHandlerInterface
This command is overkill, you only use it to assert the presence of the Store It is used for behat tests but it will likely never be used in any other use case We don't fetch the data before deleting it usually So I think this method should be removed

In the behat test you can use the existing `GetStoreForEditing` command instead, it's more than enough to assert the entity's presence (that's we did in all the other behat tests)

2022-04-11 14:19 UTC, jolelievre commented on src/Core/Domain/Store/Command/BulkDeleteStoreCommand.php
> +        foreach ($storeIds as $storeId) {
```suggestion
        $this->storeIds = [];
        foreach ($storeIds as $storeId) {
```

2022-04-11 14:19 UTC, jolelievre commented on src/Core/Domain/Store/Command/BulkDeleteStoreCommand.php
> +        foreach ($storeIds as $storeId) {
To be sure the array is always present. Or even better you should throw an exception when trying to construct this command with empty input array

2022-04-11 14:19 UTC, jolelievre commented on src/Core/Domain/Store/Query/GetStoreForDeleting.php
> +class GetStoreForDeleting
As I suggested above this command is overkill and not need IMHO

2022-04-11 14:19 UTC, jolelievre commented on src/PrestaShopBundle/Resources/config/services/adapter/store.yml
> +  prestashop.adapter.store.command_handler.delete_store:
```suggestion

  prestashop.adapter.store.command_handler.delete_store:
```

2022-04-11 14:19 UTC, jolelievre commented on src/PrestaShopBundle/Resources/config/services/adapter/store.yml
> +  prestashop.adapter.store.command_handler.bulk_delete_store_handler:
```suggestion

    prestashop.adapter.store.command_handler.bulk_delete_store_handler:
```

2022-04-11 14:19 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/Domain/StoreFeatureContext.php
> +        $query = new GetStoreForDeleting((int) $store->id);
```suggestion
        $query = new GetStoreForEditing((int) $store->id);
```

2022-04-11 14:19 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Context/Domain/StoreFeatureContext.php
> +    public function assertLastErrorStoreNotFound(string $storeReferences): void
I believe this one is not used and should be removed

2022-04-11 14:19 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Scenario/Store/store.feature
> +  When I add new store "StorePau" with following properties:
Please indent all the scenario content by two spaces

2022-04-11 14:19 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Scenario/Store/store.feature
> +  Then stores "StorePau, StoreSerresCastet" should exist
```suggestion
  And stores "StorePau, StoreSerresCastet" should exist
```

2022-04-11 14:19 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Scenario/Store/store.feature
> +  Then stores "StoreSerresCastet" should exist
```suggestion
  And stores "StoreSerresCastet" should exist
```

2022-04-11 19:52 UTC, LouisAUTHIE commented on tests/Integration/Behaviour/Features/Scenario/Store/store.feature
> +  Then stores "StoreSerresCastet" should exist
Done thanks

2022-04-11 19:53 UTC, LouisAUTHIE commented on tests/Integration/Behaviour/Features/Scenario/Store/store.feature
> +  Then stores "StorePau, StoreSerresCastet" should exist
Done thanks

2022-04-11 19:53 UTC, LouisAUTHIE commented on tests/Integration/Behaviour/Features/Scenario/Store/store.feature
> +  When I add new store "StorePau" with following properties:
Done sorry !

2022-04-11 19:53 UTC, LouisAUTHIE commented on tests/Integration/Behaviour/Features/Context/Domain/StoreFeatureContext.php
> +    public function assertLastErrorStoreNotFound(string $storeReferences): void
U're right ! Done

2022-04-11 19:54 UTC, LouisAUTHIE commented on src/PrestaShopBundle/Resources/config/services/adapter/store.yml
> +  prestashop.adapter.store.command_handler.delete_store:
Done for all the services, add a line break for readability

2022-04-11 19:54 UTC, LouisAUTHIE commented on src/Core/Domain/Store/Query/GetStoreForDeleting.php
> +class GetStoreForDeleting
Done

2022-04-11 19:54 UTC, LouisAUTHIE commented on src/Core/Domain/Store/Command/BulkDeleteStoreCommand.php
> +        foreach ($storeIds as $storeId) {
Yep, safer, done

2022-04-11 19:54 UTC, LouisAUTHIE commented on src/Core/Domain/Store/Command/DeleteStoreCommand.php
> +     * @var storeId
Well seen !

2022-04-12 06:53 UTC, Progi1984 approved these changes

2022-04-21 16:49 UTC, jolelievre approved these changes
Thanks @LouisAUTHIE 

All good!

2022-04-21 16:49 UTC, merged