Functional tests - Add new test 'Search, add and remove voucher from new order page'
PrestaShop/PrestaShop pull request #28159
Opened 2022-04-07 08:13 UTC by nesrineabdmouleh

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add new test 'Search, add and remove voucher from new order page'
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| Related PRs       | no
| How to test?      | no need
| Possible impacts? | no

2022-04-07 12:39 UTC, kpodemski requested changes
Hello, tests are red

2022-04-07 20:57 UTC, kpodemski approved these changes, later dismissed

2022-04-08 08:49 UTC, NeOMakinG approved these changes, later dismissed

2022-04-08 10:47 UTC, boubkerbribri commented on tests/UI/pages/BO/catalog/discounts/add.js
> +    return page;
```suggestion
    return null;
```

No need to return page, i think

2022-04-08 10:47 UTC, boubkerbribri commented on tests/UI/pages/BO/catalog/discounts/add.js
> +   * @returns {Promise<string|*>}
```suggestion
   * @returns {Promise<string|null>}
```

2022-04-08 11:22 UTC, boubkerbribri approved these changes

2022-04-08 13:20 UTC, PierreRambaud approved these changes

2022-04-08 14:03 UTC, merged

2022-04-08 14:03 UTC, Progi1984 commented
Thanks @nesrineabdmouleh