Remove deprecated method inside Adapter\Shop\Context
PrestaShop/PrestaShop pull request #28199
Opened 2022-04-08 18:47 UTC by PrestaEdit

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove deprecated method inside Adapter\Shop\Context
| Type?             | improvement 
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #26293.
| How to test?      | Nothing to test.
| Possible impacts? | BC Break.

**:notebook: BC Breaks**
* Removed method : `Adapter\Shop\Context::isShopGroupContext()`
* Removed method : `Adapter\Shop\Context::isAllContext()`

2022-04-11 08:22 UTC, jolelievre requested changes
Thanks @PrestaEdit 

You need to update `MultishopCommandListenerTest` which was still relying on `isShopGroupContext` (replace it with `isGroupShopContext`) Although I don't understand why this naming was considered better since the entity behind it is `ShopGroup` not `GroupShop` 🤔

And in many places we use `isShopGroup` included in the `ShopConstraint` object which is at the core of our most recent work on multishop:
https://github.com/PrestaShop/PrestaShop/blob/60a277fe63ecd464acb187953d373a19a08fd514/src/Core/Domain/Shop/ValueObject/ShopConstraint.php#L77

In my opinion it's the `isShopGroupContext` which has the correct naming, but I will need the option of other maintainers on this one @PrestaShop/prestashop-core-developers

2022-04-11 08:25 UTC, jolelievre commented
PIng @PrestaShop/prestashop-core-developers 

The renaming and deprecation of this group method was introduced in this PR https://github.com/PrestaShop/PrestaShop/pull/10790 The idea of introducing an interface was good I'm just not convinced about the `GroupShop` naming instead of the `ShopGroup` naming which is used everywhere else. SO I suggest to invert the deprecations notices:
- `isShopGroupContext` should be the correct naming
- `isGroupShopContext` should be deprecated and replaced (removed in next major v9)

2022-04-11 10:14 UTC, matthieu-rolland reviewed
> PIng @PrestaShop/prestashop-core-developers
> 
> The renaming and deprecation of this group method was introduced in this PR #10790 The idea of introducing an interface was good I'm just not convinced about the `GroupShop` naming instead of the `ShopGroup` naming which is used everywhere else. SO I suggest to invert the deprecations notices:
> 
> * `isShopGroupContext` should be the correct naming
> * `isGroupShopContext` should be deprecated and replaced (removed in next major v9)

I agree 👍  @PrestaEdit do you want to do it?

2022-05-11 12:18 UTC, matks commented
> isShopGroupContext should be the correct naming
> isGroupShopContext should be deprecated and replaced (removed in next major v9)

So we take the deprecated function and we keep it, but we deprecate what was supposed to be the replacement ?

As for me I am very tolerant with naming 😄 so I see no differences between the two. I don't think RedCar or CarRed is better. We just need one and only function.

2022-06-13 15:09 UTC, matthieu-rolland commented
> > isShopGroupContext should be the correct naming
> > isGroupShopContext should be deprecated and replaced (removed in next major v9)
> 
> So we take the deprecated function and we keep it, but we deprecate what was supposed to be the replacement ?
> 
> As for me I am very tolerant with naming 😄 so I see no differences between the two. I don't think RedCar or CarRed is better. We just need one and only function.

well the idea was to stay congruent with the existing naming (as much as possible, that is...)

@PrestaEdit do you think you will push this PR forward?  (we usually close them after 4 weeks of inactivity, what do you think?)

2022-06-13 15:11 UTC, PrestaEdit commented
I will try to, but I'm not sure to have the time of.
If someone here could adapt it as needed, no worries : make it, of course ! :)

2022-11-03 10:29 UTC, closed without merging