Remove deprecated method inside SearchProvider
PrestaShop/PrestaShop pull request #28197
Opened 2022-04-08 18:42 UTC by PrestaEdit

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove deprecated method inside SearchProvider
| Type?             | improvement 
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #26293.
| How to test?      | Nothing to test.
| Possible impacts? | BC Break.

**:notebook: BC Breaks**
* Removed method : `PrestaShopBundle\Translation\Provider\SearchProvider::getDomain()`
* Removed method : `PrestaShopBundle\Translation\Provider\SearchProvider::getModuleDirectory()`

2022-04-11 07:38 UTC, jolelievre reviewed
Thanks @PrestaEdit 

ok for the modification's intention However you also need to remove the now useless `$modulesDirectory` field, along with the constructor and service definition.

2022-04-11 10:18 UTC, matthieu-rolland reviewed
static analysis is failing, it expects `$modulesDirectory` to be removed... as @jolelievre you should also remove it from constructor and service definition 👍

2022-04-19 07:33 UTC, Progi1984 requested changes
@PrestaEdit Could you fix PHPStan errors ?

2022-04-21 06:59 UTC, Progi1984 commented on src/PrestaShopBundle/Translation/Provider/SearchProvider.php
> +        $resourceDirectory
Could you document the BC Break in the constructor ?

2022-04-21 07:00 UTC, Progi1984 reviewed
A small comment and it's OK.

2022-04-22 10:12 UTC, atomiix approved these changes

2022-04-22 10:15 UTC, jolelievre approved these changes
Thanks @PrestaEdit

2022-04-25 07:38 UTC, Progi1984 approved these changes

2022-04-25 07:38 UTC, Progi1984 commented
@PrestaShop/qa-team I think we can execute automated tests on this PR.

2022-04-25 09:12 UTC, HanaRebaiQA approved these changes
Hello @PrestaEdit 

I executed the automated tests. They are OK

So, it's QA :heavy_check_mark: 

Thanks!

2022-04-25 09:18 UTC, merged

2022-04-25 09:18 UTC, kpodemski commented
Thank you @PrestaEdit @HanaRebaiQA