L[POC] ight product list
PrestaShop/PrestaShop pull request #28352
Opened 2022-04-27 13:04 UTC by zuk3975

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | 
| Type?             | refacto
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | part of #10632
| Related PRs       | If theme, autoupgrade or other module change is needed, provide a link to related PRs here.
| How to test?      | TBD
| Possible impacts? | TBD

2022-04-27 13:08 UTC, zuk3975 commented
It is easy to show the list, but pagination seems to be the problem, we cannot simply use our dynamic paginator as it expects data as json array, but when using grid factory we provide full rendered html instead of json array.
Need to check how was the original quicknav pagination done, maybe its easy to implement that.
Or need to consider providing products list as json in controller and use similar approach as with combinations list.

Anyway this is not mandatory task, so I leave it for now.

2022-06-14 03:06 UTC, jolelievre approved these changes
Thanks @zuk3975

2022-06-14 07:44 UTC, zuk3975 commented on src/Adapter/Product/Grid/Data/Factory/ProductLightGridDataFactoryDecorator.php
> +    public function __construct(
@jolelievre missing docblock :smile:

2022-06-14 08:21 UTC, jolelievre commented on src/Adapter/Product/Grid/Data/Factory/ProductLightGridDataFactoryDecorator.php
> +    public function __construct(
Done 😛

2022-06-14 08:21 UTC, jolelievre approved these changes

2022-06-14 10:23 UTC, jolelievre submitted a review, later dismissed

2022-06-14 13:10 UTC, matks approved these changes, later dismissed

2022-06-16 09:24 UTC, NeOMakinG commented on admin-dev/themes/new-theme/scss/pages/product/_product_light_list.scss
> +    width: 235px;
```suggestion
    width: 100%;
```

2022-06-16 09:25 UTC, NeOMakinG commented on admin-dev/themes/new-theme/scss/pages/product/_product_light_list.scss
> +    width: 235px;
You should never set a `width` to any element because it makes your max-width useless, you should try to find another way, maybe this would be enough...

2022-06-16 10:15 UTC, florine2623 requested changes
Hello @zuk3975 ,

Thanks for the PR.

Here are my feedbacks :

- Would it be possible to center the pagination ?
<img width="325" alt="Screenshot 2022-06-16 at 12 09 51" src="https://user-images.githubusercontent.com/16019289/174047868-b4f56c79-226d-4f41-bcaa-498343874f97.png">

- I can't click on the ID column to go to a product :

| What I have | What I used to have |
| ------------- | ------------- |
| <img width="319" alt="Screenshot 2022-06-16 at 12 10 41" src="https://user-images.githubusercontent.com/16019289/174048068-aea9e0d0-21df-45b7-aba1-a18b77a28ef5.png">  | <img width="322" alt="Screenshot 2022-06-16 at 12 10 47" src="https://user-images.githubusercontent.com/16019289/174048093-aea83d2e-844e-40bf-b9b8-2cace005a110.png">  |

- I can't sort the product, it always displays the product in DESC.

Could you check ?
Thanks!

2022-06-20 15:31 UTC, jolelievre commented on admin-dev/themes/new-theme/scss/pages/product/_product_light_list.scss
> +    width: 235px;
We're in a table which is not able to adjust its size correctly that's why we need to limit the size explicitly here But I'll try with a set `max-width` instead of width

2022-06-20 16:33 UTC, jolelievre approved these changes, later dismissed

2022-06-20 16:33 UTC, jolelievre commented on admin-dev/themes/new-theme/scss/pages/product/_product_light_list.scss
> +    width: 235px;
@NeOMakinG it should be good now, can you please review it again, if it's ok for you it can go back to QA

2022-06-20 16:36 UTC, jolelievre approved these changes

2022-06-21 07:58 UTC, NeOMakinG approved these changes

2022-06-21 15:02 UTC, florine2623 approved these changes
Thanks @jolelievre for the updates.

Looking good to me !
It is QA ✅

2022-06-21 15:04 UTC, merged

2022-06-21 15:04 UTC, Progi1984 commented
Thanks @zuk3975 & @florine2623

2022-06-22 08:06 UTC, zuk3975 commented
> Thanks @zuk3975 & @florine2623

thanks @jolelievre !

2022-06-22 08:08 UTC, Progi1984 commented
Sorry, my @jolelievre. Thanks to you, too.