Add reset button to reset category filter in products list - fix #17942
PrestaShop/PrestaShop pull request #28375
Opened 2022-04-29 09:13 UTC by marsaldev

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Simply added a reset button to "exit" from the "filtered" status that allow you to rearrange the positions of products. Fix the issue #17942
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #17942
| Related PRs       | ~
| How to test?      | Edit the src/PrestaShopBundle/Resources/views/Admin/Product/CatalogPage/Blocks/filters.html.twig like the commit
| Possible impacts? | ~

2022-04-29 13:27 UTC, NeOMakinG requested changes

2022-04-29 13:27 UTC, NeOMakinG commented on src/PrestaShopBundle/Resources/views/Admin/Product/CatalogPage/Blocks/filters.html.twig
> +              onclick="productCategoryFilterReset($('div#product_catalog_category_tree_filter'));">
It's a no! Should be handled in a ts file

2022-04-29 18:21 UTC, marsaldev commented on src/PrestaShopBundle/Resources/views/Admin/Product/CatalogPage/Blocks/filters.html.twig
> +              onclick="productCategoryFilterReset($('div#product_catalog_category_tree_filter'));">
I can't figure out how 😅

2022-05-02 07:38 UTC, NeOMakinG approved these changes, later dismissed
I'm accepting it because we did it like this in the past and so it stick with the flow we used but I'll keep it in my mind, these onclick are really weird

2022-05-02 07:44 UTC, kpodemski submitted a review, later dismissed

2022-05-02 09:28 UTC, Progi1984 submitted a review, later dismissed

2022-05-02 09:35 UTC, Julievrz commented
I'm afraid this button is very long and it might look weird in a table, especially in other languages. Example with French: Could you please provide a screenshot? Wouldn't "Reset filter" or even "Reset" be enough? Maybe I'm missing something.

2022-05-02 09:37 UTC, mparvazi commented
My suggestion:

![Screenshot 2022-05-02 at 05-33-45 Products • develop](https://user-images.githubusercontent.com/85633460/166214349-e9f5b7fd-0121-4b79-b14f-5dcb778410d4.png)

![Screenshot from 2022-05-02 05-36-17](https://user-images.githubusercontent.com/85633460/166214641-62827516-269c-4043-a326-fc327a5b3b0c.png)

2022-05-04 07:42 UTC, Julievrz commented on src/PrestaShopBundle/Resources/views/Admin/Product/CatalogPage/Blocks/filters.html.twig
> +              {{ 'Reset categories filter'|trans({}, 'Admin.Actions') }}
```suggestion
              {{ 'Clear filter'|trans({}, 'Admin.Actions') }}
```

2022-05-06 07:42 UTC, marsaldev commented
Thanks @mparvazi and @Julievrz, I've applied your suggestion 😊

2022-05-06 08:10 UTC, Progi1984 approved these changes

2022-05-06 08:11 UTC, kpodemski approved these changes

2022-05-06 08:30 UTC, NeOMakinG approved these changes

2022-05-06 10:13 UTC, Julievrz approved these changes

2022-05-06 13:24 UTC, AureRita approved these changes
Hi @marsaldev 
Thank you for your PR, I tested it and it works, as you can see :

https://user-images.githubusercontent.com/100699445/167140091-9ca7ab42-f6b3-4829-b59c-1745c75fe9ec.mp4

2022-05-06 13:28 UTC, merged

2022-05-06 13:28 UTC, Progi1984 commented
Thanks @marsaldev & @AureRita