Functional tests - Add test 'Pagination of orders table'
PrestaShop/PrestaShop pull request #28370
Opened 2022-04-28 15:26 UTC by nesrineabdmouleh

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add test 'Pagination of orders table'
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| Related PRs       | no
| How to test?      | no need
| Possible impacts? | no

2022-04-29 09:03 UTC, matthieu-rolland approved these changes, later dismissed

2022-05-02 09:30 UTC, Progi1984 requested changes
@nesrineabdmouleh Could you remove `.github/workflows/myTesting.yml`, please ?

2022-05-03 07:05 UTC, Progi1984 commented on tests/UI/pages/BO/orders/index.js
> +   * @returns {Promise<*>}
```suggestion
   * @returns {Promise<number>}
```

2022-05-03 07:06 UTC, Progi1984 reviewed
@nesrineabdmouleh A small feedback

2022-05-03 09:13 UTC, nesrineabdmouleh commented on tests/UI/pages/BO/orders/index.js
> +   * @returns {Promise<*>}
Done thx :+1:

2022-05-04 07:34 UTC, Progi1984 approved these changes

2022-05-04 13:07 UTC, SD1982 approved these changes

2022-05-04 19:22 UTC, merged

2022-05-04 19:22 UTC, Progi1984 commented
Thanks @nesrineabdmouleh