Prevent using period, comma keys inside quantity input
PrestaShop/PrestaShop pull request #28510
Opened 2022-05-16 17:46 UTC by kpodemski

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | It's probably better to prevent using  these keys instead of forcing browser to validate fields
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #9616.
| How to test?      | Details in the issue. You shouldn't be able to use `,` or `.` inside qty field anymore
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

2022-05-16 20:40 UTC, matks reviewed
Logic is OK but ESlint complains

2022-05-17 08:18 UTC, Progi1984 requested changes
I don't think we should only take `,` & `.`. We should use CLDR because there exists many decimal separators : https://en.wikipedia.org/wiki/Decimal_separator.

2022-05-17 08:21 UTC, kpodemski commented
@Progi1984 I don't think you can use something else than a digit, `.` and `,` + `e` (which doesn't cause issues) inside `type="number"`

2022-05-17 08:26 UTC, Progi1984 commented
@kpodemski Mozilla & Google are based on WhatWG which defines it : 

> As described above, a user agent might support numeric input in the user's local format, converting it to the format required for submission as described above. This might include handling grouping separators (as in "872,000,000,000") and various decimal separators (such as "3,99" vs "3.99") or using local digits (such as those in Arabic, Devanagari, Persian, and Thai).

Source : https://html.spec.whatwg.org/multipage/input.html#number-state-(type=number)

2022-05-17 08:36 UTC, kpodemski commented
@Progi1984 

Sorry, I don't get your point. We want to prevent people from typing `1,23` `1.45`. That's it. CLDR could be useful for formatting output. In this scenario, what would you want me to do? Remember that we don't want to validate decimal values, we want to prevent typing decimal values.

2022-05-17 16:09 UTC, Hlavtox commented
@kpodemski Try to think about if we maybe want to allow decimal quantities at some point in future.

2022-05-17 16:30 UTC, kpodemski commented
@Hlavtox having this check there is the smallest problem we'd have 😜

2022-05-21 10:03 UTC, kpodemski commented
@NeOMakinG could you take a look? :>

2022-05-23 07:01 UTC, NeOMakinG reviewed
Added a small comment taking @Progi1984 feedback into consideration, it looks fine to me as we want to avoid floats there, not need to overengineer it

2022-05-23 07:01 UTC, NeOMakinG commented on admin-dev/themes/new-theme/js/app/pages/stock/components/overview/spinner.vue
> +      onKeydown(event: KeyboardEvent): void {
Can you add a comment there to explain why you added this? It will be clearer if we need to change it in the future

2022-05-31 08:19 UTC, MeKeyCool approved these changes, later dismissed

2022-05-31 08:26 UTC, MeKeyCool commented
@kpodemski and @Progi1984 , I think you don't really speak about the same thing.

@kpodemski is simply fixing the #9616 issue as it is described while @Progi1984 you are trying to define a better specification for the component. I think you both have some good points to bring to project but to avoid frustrations and misunderstanding we should separate approaches. With a good agile process it is not a problem to make a small enhancement based on simple specifications waiting for better specs.

So the question is, where should we enhance specifications you brought @Progi1984 ? And what is the process to discuss about them ?

2022-06-13 16:29 UTC, matks approved these changes, later dismissed
In my opinion that fix is valid. We can always do more but that is not a reason to reject bug fixes that fit current situation

@kpodemski check @NeOMakinG feedback ;)

2022-07-07 20:20 UTC, matks approved these changes

2022-07-08 08:09 UTC, NeOMakinG approved these changes

2022-07-12 13:40 UTC, AureRita approved these changes
Hi @kpodemski 

Thank you for your PR, I tested it and it works, as we can see here :

https://user-images.githubusercontent.com/100699445/178497713-57770d33-92c0-4b40-95b3-bcbfc39985ea.mp4

(currently, when I pressed the "," or the ".", they aren't write on the field)

2022-07-12 14:06 UTC, merged

2022-07-12 14:06 UTC, atomiix commented
Thanks @kpodemski & @AureRita