remove final class from attachment uploader
PrestaShop/PrestaShop pull request #28521
Opened 2022-05-18 07:19 UTC by integritty

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | After uploading files you need to do some actions with file, or do some modification. PrestaShop in version 1.7 / 8 doesn`t contain any hook for this operation and it is not needed. You can do it using services.yml but only if core class is not final & @internal. This change allows you to override this class using module services.yml.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | none
| Related PRs       | none
| How to test?      | Try to do symfony override from module using services.yml
| Possible impacts? | none

2022-05-18 07:21 UTC, integritty commented
This pull request following slack message
![Screenshot 2022-05-18 at 9 20 46](https://user-images.githubusercontent.com/71325559/168980833-7f324dd3-bb7e-46cb-8737-9a3507718a29.png)

2022-05-18 07:32 UTC, Progi1984 requested changes
@integritty Could you change `private` methods & properties to `protected` ?

2022-05-18 07:53 UTC, integritty commented
@Progi1984 Done.

2022-05-18 07:56 UTC, Progi1984 reviewed
@integritty Don't forget properties :wink:

2022-05-18 08:18 UTC, integritty commented
Its ok now?

2022-05-18 08:19 UTC, Progi1984 submitted a review, later dismissed

2022-05-31 07:22 UTC, MeKeyCool approved these changes, later dismissed
Thanks for your contribution ^^

2022-05-31 07:22 UTC, MeKeyCool commented on src/Adapter/File/Uploader/AttachmentFileUploader.php
> +        bool $throwExceptionOnFailure = true
:+1:

2022-05-31 13:04 UTC, Progi1984 submitted a review, later dismissed

2022-06-02 09:41 UTC, MeKeyCool approved these changes, later dismissed
You still have an error in CI :thinking: It looks linked to your PR comment.
Did you remove first comment ?
```
<!-----------------------------------------------------------------------------
Thank you for contributing to the PrestaShop project! 

Please take the time to edit the "Answers" rows below with the necessary information.

Check out our contribution guidelines to find out how to complete it:
https://devdocs.prestashop.com/8/contribute/contribution-guidelines/#pull-requests
------------------------------------------------------------------------------>
```
?

2022-06-02 10:08 UTC, integritty commented
> You still have an error in CI 🤔 It looks linked to your PR comment. Did you remove first comment ?
> 
> ```
> <!-----------------------------------------------------------------------------
> Thank you for contributing to the PrestaShop project! 
> 
> Please take the time to edit the "Answers" rows below with the necessary information.
> 
> Check out our contribution guidelines to find out how to complete it:
> https://devdocs.prestashop.com/8/contribute/contribution-guidelines/#pull-requests
> ------------------------------------------------------------------------------>
> ```
> 
> ?

I tried to remove this comment lines and force push the same changes

2022-06-02 12:13 UTC, MeKeyCool submitted a review, later dismissed

2022-06-13 16:30 UTC, matks commented
I close and reopen the PR to restart the CI

2022-06-13 16:31 UTC, matks approved these changes, later dismissed
Change is valid for me

2022-07-25 11:26 UTC, integritty commented
@matks Is everything ok with this pull request?

2022-07-25 14:59 UTC, NeOMakinG commented
@integritty I don't get why the CI is 🔴 , could you maybe try to rebase it?

2022-10-29 09:50 UTC, kpodemski approved these changes, later dismissed

2022-12-20 10:34 UTC, integritty commented
@NeOMakinG Its ok now?

2023-01-02 15:28 UTC, FabienPapet approved these changes

2023-01-02 17:07 UTC, NeOMakinG approved these changes

2023-01-12 21:36 UTC, kpodemski approved these changes

2023-01-12 21:36 UTC, merged

2023-01-12 21:36 UTC, kpodemski commented
Thank you, @integritty