Remove deprecated in Adapter namespace
PrestaShop/PrestaShop pull request #28564
Opened 2022-05-23 08:04 UTC by Progi1984

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove deprecated in Adapter namespace
| Type?             | refacto
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Relative to #26293 
| How to test?      | Automated Tests

2022-05-23 13:18 UTC, atomiix approved these changes, later dismissed

2022-06-13 15:52 UTC, matks requested changes, later dismissed
Dear @Progi1984 I'm really sorry but following the [8.0.0 freeze](https://build.prestashop.com/news/prestashop-feature-freeze-v8/) happened and now until further notice `develop` branch is going to become the branch for 8.1, which means we cannot accept BC breaks like this one 😞 I'm sorry

2023-02-01 09:26 UTC, Progi1984 commented
@PrestaShop/committers After 7 months, the PR is ready to review.

FYI : The PR has been tested on CI (Check PR Header)

2023-02-01 16:56 UTC, kpodemski approved these changes

2023-02-01 17:19 UTC, lartist approved these changes

2023-02-01 17:25 UTC, merged