Add actionLoggerLogMessage hook
PrestaShop/PrestaShop pull request #28563
Opened 2022-05-22 19:48 UTC by PrestaEdit

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add new hook `actionLoggerLogMessage`
| Type?             | new feature
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Related PRs       | autoupgrade: to make.

2022-05-23 07:13 UTC, matthieu-rolland reviewed
LGTM code wise

The goal is to allow customizing of a log message, right?

Also, can you explain how is this related to autoupgrade, is their an issue that should be linked in the description of this PR ?

2022-05-23 07:15 UTC, PrestaEdit commented
Hi,

The goal is to allow a third party module to send the log onto Sentry or another tool needed to make some debug if needed.

The autoupgrade PR will be to add the hook, as required.

2022-05-23 07:19 UTC, matthieu-rolland commented
> 

alright 👍

2022-05-23 07:20 UTC, matthieu-rolland approved these changes, later dismissed
lgtm

2022-05-23 14:25 UTC, Progi1984 commented on classes/log/AbstractLogger.php
> +                'logged' => $level >= $this->level,
```suggestion
                'isLogged' => $level >= $this->level,
```

2022-05-23 14:26 UTC, Progi1984 reviewed
A small feedback for naming.

2022-05-23 14:39 UTC, Progi1984 commented on install-dev/data/xml/hook.xml
> +      <title>Allows to make extra action while a log is logged</title>
```suggestion
      <title>Allows to make extra action while a log is triggered</title>
```

:warning: We can trigger a log without logging it (if `$level < $this->level`)

2022-05-23 14:40 UTC, Progi1984 commented on install-dev/data/xml/hook.xml
> +      <description>This hook allows to make an extra action while an exception is throw and the logger log it</description>
```suggestion
      <description>This hook allows to make an extra action while an exception is thrown and the logger logs it</description>
```

2022-05-23 14:40 UTC, Progi1984 reviewed
Last feedbacks

2022-05-23 14:43 UTC, Progi1984 submitted a review, later dismissed

2022-06-13 15:19 UTC, MeKeyCool submitted a review, later dismissed

2022-06-13 15:52 UTC, matks requested changes
Dear @PrestaEdit I'm sorry but there is git conflicts for hook.xml file can you please rebase and solve them?

2022-07-07 15:05 UTC, matks commented
@PrestaEdit I'm sorry :( you performed a `merge` not a `rebase` so now your branch contains a merge commit and is refused by CI tool Pull Request Validator

2022-07-07 15:58 UTC, closed without merging