Product list bulk delete and duplicate actions
PrestaShop/PrestaShop pull request #28584
Opened 2022-05-24 11:36 UTC by zuk3975

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add missing bulk actions: delete, duplicate in new product list.![Screenshot from 2022-05-24 15-32-27](https://user-images.githubusercontent.com/31609858/170035496-76229681-1809-43d8-a0aa-b1ce3df241a0.png)
| Type?             | refacto
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Related PRs       | ~
| How to test?      | Go to experimental product list, check that bulk delete and bulk duplicate actions work. To use bulk action you need to check checkboxes of products which should be affected, and use bulk action dropdown at the top of the list to select the action. Bulk deletion should delete selected products, bulk duplication should duplicate selected products (products with same name prefixed with "copy of .." will appear
| Possible impacts? | ~

2022-05-24 12:23 UTC, jolelievre requested changes

2022-05-24 12:23 UTC, jolelievre commented on src/Core/Grid/Definition/Factory/ProductGridDefinitionFactory.php
> +                'radio_button_unchecked',
```suggestion
                'radio_button_checked',
```

2022-05-24 12:23 UTC, jolelievre commented on src/Core/Grid/Definition/Factory/ProductGridDefinitionFactory.php
> +                'radio_button_unchecked'
```suggestion
                'content_copy'
```

2022-05-24 12:23 UTC, jolelievre commented on src/Core/Grid/Definition/Factory/ProductGridDefinitionFactory.php
> +                'radio_button_unchecked'
```suggestion
                'delete'
```

2022-05-24 12:33 UTC, jolelievre approved these changes
Thanks @zuk3975

2022-05-25 12:12 UTC, matks approved these changes

2022-05-25 12:12 UTC, merged