Add actionCartGetPackageShippingCost hook
PrestaShop/PrestaShop pull request #28603
Opened 2022-05-26 15:35 UTC by PrestaEdit

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Allow to edit the package shipping cost value.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Add a module with actionCartGetPackageShippingCost  hook and update shippingCost value.

2022-05-31 13:31 UTC, Progi1984 commented on classes/Cart.php
> +    public function getPackageShippingCostValue(
```suggestion
    protected function getPackageShippingCostValue(
```

2022-05-31 15:07 UTC, Progi1984 submitted a review, later dismissed

2022-06-01 06:07 UTC, Hlavtox commented
Good!!!

Needed this yesterday to add extra charge to shipping, had to use actionDeliveryPriceByPrice and recalculate the price again… 😬

2022-06-01 06:07 UTC, Hlavtox commented
Good!!!

Needed this yesterday to add extra charge to shipping, had to use actionDeliveryPriceByPrice and recalculate the price again… 😬

2022-06-29 13:37 UTC, atomiix commented
Thanks @PrestaEdit! Can you resolve the conflicted file?

2022-07-07 15:04 UTC, matks requested changes
@PrestaEdit I'm sorry :( you performed a `merge` not a `rebase` so now your branch contains a merge commit and is refused by CI tool Pull Request Validator

2022-07-07 16:04 UTC, closed without merging