[+] WS : Handle PATCH requests for attachments
PrestaShop/PrestaShop pull request #28747
Opened 2022-06-14 09:44 UTC by nsorosac

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 8.0.x / 1.7.8.x
| Description?      | https://github.com/PrestaShop/autoupgrade/pull/479#pullrequestreview-1004678171
| Type?             | bug fix
| Category?         | WS
| BC breaks?        | no
| Deprecations?     | no
| Related PRs       | https://github.com/PrestaShop/autoupgrade/pull/479
| How to test?      | https://github.com/PrestaShop/autoupgrade/pull/479#pullrequestreview-1004678171

2022-06-14 09:59 UTC, hibatallahAouadni commented
Ping @nsorosac thanks for your PR :rocket: 
Could you please change your base branch from `develop` to `8.0.x` :pray: 

Thanks in advance!

2022-06-14 10:15 UTC, Progi1984 requested changes
Could you target the `8.0.x` branch, please ?

2022-06-16 21:51 UTC, kpodemski requested changes, later dismissed
Thank you for your PR @nsorosac . Could you rebase it? There are some commits that are not relevant to your change.

2022-06-17 09:31 UTC, hibatallahAouadni commented on classes/webservice/WebserviceSpecificManagementAttachments.php
> +                case 'PATCH':
test review

2022-06-17 13:28 UTC, Progi1984 approved these changes

2022-06-28 12:57 UTC, matthieu-rolland approved these changes

2022-06-28 13:06 UTC, jolelievre approved these changes

2022-07-12 18:27 UTC, hibatallahAouadni commented
Hello @nsorosac 

Thanks again for your PR :rocket: 
But, I found a problem, when I try to modify the file of an attachment, it is modified fine :heavy_check_mark: but the file name and extension are saved as a random number, see the screenshot attached:

https://user-images.githubusercontent.com/23308427/178567156-e82ee460-2556-4ea4-b0a5-ccbb309d3fb7.mp4

Please check and feedback.
Thanks!

2022-07-19 13:17 UTC, jolelievre commented
Hi @nsorosac 

although it's not exactly the initial scope maybe it's worth fixing this. I guess the web service handles the PATCh like a POST and automatically fills the fields with random values without checking if they are already set. It's fine in a POST context, but for a patch that is supposed to allow partial update only not so much.

2022-08-31 20:22 UTC, matks commented
@kpodemski I think we maybe need to continue this PR to deliver a complete PATCH management of webservice request in PS 8.0.0

2022-09-13 15:07 UTC, matks commented
I checked the PR of @nsorosac about the latest issue found by QA team.

So what happens is that:
- PATCH HTTP request is made using `binary` input -> the file is simply piped into the http request 😄 
- PrestaShop Webservice handles incoming http request and we enter `executeFileAddAndEdit()` function https://github.com/PrestaShop/PrestaShop/blob/develop/classes/webservice/WebserviceSpecificManagementAttachments.php#L304
- in this function, PrestaShop uses a FileUploader to write the file binary content on the disk
- and the function actually retrieves the filename and filetype of ... the new file, written on disk 😄 
- naturally filename and filetype could not be retrieved from http request as file content was simply piped in as binary

And PrestaShop saves the persisted data, and modify the filename in SQL using the filename and filetype of the file written on disk. Not the one on the client computer.

Only thing I can imagine is transform
```
            $attachment->file = $file['id'];
            $attachment->file_name = $file['file_name'];
            $attachment->mime = $file['mime_type'];
            $attachment->name[Configuration::get('PS_LANG_DEFAULT')] = $_POST['name'] ?? $file['file_name'];
```
into
```
            $attachment->file = $file['id'];
            if ($this->getWsObject()->method !== 'PATCH') {
                $attachment->file_name = $file['file_name'];
                $attachment->mime = $file['mime_type'];
                $attachment->name[Configuration::get('PS_LANG_DEFAULT')] = $_POST['name'] ?? $file['file_name'];
            }
```

Not very pretty 🤷‍♂️

2022-09-14 16:02 UTC, matks commented
@nsorosac We want to complete this topic for 8.0.0 that is coming very soon so I fetched your commits and added them on a branch of mine, that I will submit for merge -> https://github.com/PrestaShop/PrestaShop/pull/29638

Your commits are still marked as authored by you and you will be credited ;)

2022-09-16 14:54 UTC, matks commented
Hello @nsorosac I close your Pull Request because I completed your work and got it merged in https://github.com/PrestaShop/PrestaShop/pull/29638

but your work and commit was preserved 😉

2022-09-16 14:54 UTC, closed without merging

2022-09-20 11:23 UTC, jolelievre commented
Closed in favor of https://github.com/PrestaShop/PrestaShop/pull/29638