Code duplicated in PaymentModule class
PrestaShop/PrestaShop pull request #28792
Opened 2022-06-20 08:13 UTC by AlexTechDev

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 8.0.x / 1.7.8.x
| Description?      | Duplicated code in PaymentModule
| Type?             |  improvement
| Category?         | FO / BO 
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | Fixes  #28645 .
| Possible impacts? | We have the same duplicate code (see issue) I decided to remove the code on line 363 because the assignment of the variable is done (if the condition is true) on line 234.

2022-06-20 08:29 UTC, ghost commented
Hello @AlexTechDev 

Can you edit the description with only develop branch for tags.

2022-06-20 08:34 UTC, AlexTechDev commented
> Hello @AlexTechDev
> 
> Can you edit the description with only develop branch for tags.

Done :) Thanks!

2022-06-20 08:43 UTC, okom3pom commented
For the code, I'm not sure : 

https://github.com/PrestaShop/PrestaShop/blob/develop/classes/PaymentModule.php#L234-L236

Is different from : 

https://github.com/PrestaShop/PrestaShop/blob/develop/classes/PaymentModule.php#L362-L365

If we apply your code `$context_country` is not used anymore

2022-06-20 08:44 UTC, okom3pom requested changes
For the code, I'm not sure :

https://github.com/PrestaShop/PrestaShop/blob/develop/classes/PaymentModule.php#L234-L236

Is different from :

https://github.com/PrestaShop/PrestaShop/blob/develop/classes/PaymentModule.php#L362-L365

If we apply your code `$context_country` is not used anymore

I am not sure it's a duplicate code, why not unuseful code but not duplicate.
We have to check if the context don't change.

2022-06-20 10:10 UTC, AlexTechDev commented
> For the code, I'm not sure :
> 
> https://github.com/PrestaShop/PrestaShop/blob/develop/classes/PaymentModule.php#L234-L236
> 
> Is different from :
> 
> https://github.com/PrestaShop/PrestaShop/blob/develop/classes/PaymentModule.php#L362-L365
> 
> If we apply your code `$context_country` is not used anymore
> 
> I am not sure it's a duplicate code, why not unuseful code but not duplicate. We have to check if the context don't change.

I like "unuseful" code :)
As I see it, if the condition is true $context_country will have a value on line 235 and the condition on line 363 will be skipped.
If the condition is not true it will not enter into either condition, so we could leave only one of the two conditions

2022-06-20 10:54 UTC, okom3pom commented
If you leave one of the two conditions it will be useless.
Either remove it all or leave it.
You can see why on the screenshot :  

![Capture d’écran de 2022-06-20 12-48-33](https://user-images.githubusercontent.com/5064590/174586641-a728339e-8d81-4ced-8ea7-d8fe6749cc64.png)

2022-06-20 14:02 UTC, AlexTechDev commented
I got your point, but I was a bit "afraid" to delete it completely in case other processes would use that variable. We can remove both lines of code and test that everything works. What do you think?

2022-07-04 10:22 UTC, MeKeyCool requested changes
@AlexTechDev , thanks for your efforts to improve our dear Prestashop,

The code you are interested on looks like a solution to keep state and reset it after some changes.

At this line, we can see that `context->country` is changed directly 
https://github.com/PrestaShop/PrestaShop/blob/b513bc9d769a28d672d7c8a653cd418fabd840d5/classes/PaymentModule.php#L963

And this code is called between the two code parts you mentioned @AlexTechDev .

I don't think it is a good idea to remove this code without further tests or clear issue.

2022-07-06 21:25 UTC, matks commented
Thanks for the very nice reviews @okom3pom and @MeKeyCool 👍

2022-09-05 07:51 UTC, matks commented
@AlexTechDev friendly reminder 😉

2022-09-06 14:09 UTC, AlexTechDev commented
> @AlexTechDev friendly reminder 😉

Thanks for the reminder!
So I think we don't have duplicate code as suggested by @MeKeyCool this code makes sense to be here

2023-01-12 21:49 UTC, closed without merging