Fix performances links spaces and URLs
PrestaShop/PrestaShop pull request #28829
Opened 2022-06-23 13:59 UTC by NeOMakinG

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | I added a small margin to links of the Performance page in order to have a space and fixed links
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #28227.
| How to test?      | See issue
| Possible impacts? | Performance page links and spaces

2022-06-23 16:19 UTC, okom3pom approved these changes, later dismissed
Nice catch for 404

2022-06-24 07:28 UTC, Progi1984 commented on src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/CachingType.php
> +                        '[a]' => '<a href="http://www.php.net/manual/en/memcached.installation.php" class="ml-1" target="_blank">',
```suggestion
                        '[a]' => '<a href="https://www.php.net/manual/en/memcached.installation.php" class="ml-1" target="_blank">',
```

2022-06-24 07:28 UTC, Progi1984 commented on src/PrestaShopBundle/Form/Admin/AdvancedParameters/Performance/CachingType.php
> +                        '[a]' => '<a href="http://www.php.net/manual/en/memcache.installation.php" class="ml-1" target="_blank">',
```suggestion
                        '[a]' => '<a href="https://www.php.net/manual/en/memcache.installation.php" class="ml-1" target="_blank">',
```

2022-06-24 07:28 UTC, Progi1984 reviewed
Two small changes

2022-06-24 07:43 UTC, Progi1984 submitted a review, later dismissed

2022-06-24 07:51 UTC, okom3pom approved these changes, later dismissed

2022-07-05 15:08 UTC, sLorenzini approved these changes, later dismissed
hello @NeOMakinG,

Thank you for this PR.
Tested on 1.7.8x branch, PHP 7.3

Links are good and wording have their margins.

QA approved ✅ 

Thanks

2022-07-05 19:55 UTC, kpodemski approved these changes

2022-07-05 19:56 UTC, kpodemski requested changes, later dismissed
Hi @NeOMakinG 

It's a regression, I think you wanted to target `1.7.8` branch?

2022-07-06 07:45 UTC, NeOMakinG commented
> Hi @NeOMakinG
> 
> It's a regression, I think you wanted to target `1.7.8` branch?

Fuck my life :p

Should we test it again? I think I used 1.7.8.x as a base branch so, the switch to 1.7.8.x doesn't cause any issue

2022-07-06 14:47 UTC, okom3pom approved these changes

2022-07-06 21:55 UTC, matks approved these changes

2022-07-06 21:56 UTC, matks commented
Thank you @NeOMakinG

2022-07-06 21:56 UTC, merged