Set $available_in_your_account as false by default, true on invoice
PrestaShop/PrestaShop pull request #29125
Opened 2022-07-21 12:08 UTC by PrestaEdit

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Display the 'An electronic version of this invoice is available in your account. To access it, log in to our website using your e-mail address and password (which you created when placing your first order).' only on invoice PDF.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #29123.
| How to test?      | See issue.

2022-07-29 16:10 UTC, matks approved these changes

2022-07-29 19:50 UTC, kpodemski requested changes
Hello @PrestaEdit 

QA categorized your Pull Request as a feature request. Could you check the Issue? If it's a feature request, it shouldn't go to 1.7.8.x branch.

2022-07-31 11:37 UTC, PrestaEdit commented
Hi @kpodemski ,

I'd just answer on the issue, about this.

2022-08-31 20:28 UTC, matks commented
I see the discussion in the issue got stale so I upped it

2022-10-18 20:22 UTC, PrestaEdit commented
Still "Waiting for author" even if I answer to the waiting message, here.

2022-10-18 20:27 UTC, matks commented
Thank you for ping. I think https://github.com/prestashop/prestonbot removes 'waiting for author' label when a new commit is added to a PR but if no new commit is added then the label remains. I removed the label.

2022-11-07 16:46 UTC, closed without merging