Fix: error when adding a product to an empty category I created using a web serviceDevelop
PrestaShop/PrestaShop pull request #29170
Opened 2022-07-26 12:42 UTC by Pask42

I'm trying to import some products to my prestashop using REST webservice. The problem is when I try to add a product to an empty category I created using webservice, I get the following response:

`<error>
<code><![CDATA[135]]></code>
<message><![CDATA[You cannot set a position greater than the total number of products in the category, minus 1 (position numbering starts at 0).]]></message>
</error>`

2022-07-29 06:29 UTC, Pask42 commented
How add description, type category ?

2022-07-29 07:08 UTC, okom3pom commented
When you create a PR you have a table to fill in but you have deleted it. 

I have just edited the description, please complete it.

2022-08-31 20:34 UTC, matks commented
@Pask42 sorry for late answer

Your contribution solves a bug. 

We can only validate your PR if we have a clear, reproducible scenario we can follow to observe the bug. In order to be able to explore your PR, to verify any side-effects, to make sure it is correct, we need a complete understanding of it, and so does the QA team. That's why a list of steps "1. do this 2. do then that 3. we should see ... but instead we should see ..." is a must-have needed for us to verify the bug 😉 . So before we review the PR we need the bug report confirmed.

Can you please create a bug report following this link https://github.com/PrestaShop/PrestaShop/issues/new?assignees=&labels=Bug%2CNew&template=1_bug_report.yml

2022-09-01 07:53 UTC, matks requested changes

2022-09-01 07:53 UTC, matks commented on classes/Product.php
> +        if (count($result)!= 0) {
```suggestion
        if (count($result)!= 0) {
        if (count($result) != 0) {
```

PHP CS Fixer needs this

2023-02-14 16:50 UTC, kpodemski commented
Since we have had no news from you for more than 20 days, I'm closing this PR. Feel free to re-open it if you find the motivation to finish it. Don't hesitate to ping me if you have any questions or doubts.

2023-02-14 16:50 UTC, closed without merging