Fix order payment currency unit
PrestaShop/PrestaShop pull request #29180
Opened 2022-07-27 09:15 UTC by FabienPapet

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x 
| Description?      | This PR adds currency unit if there is only one currency available, and a select if there are many. Validated with @MatShir 
| Type?             | bug fix
| Category?         | BO 
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | Fixes #29051.
| How to test?      | See #29051

## Behavior with single currencies

![image](https://user-images.githubusercontent.com/1446265/181210341-1d32de84-1853-4efd-8f87-2518b7b40c67.png)

## Behavior with many currencies

![image](https://user-images.githubusercontent.com/1446265/181210393-4e5988e3-814f-4c82-a885-4947c62b0398.png)

2022-07-27 12:37 UTC, zuk3975 commented
cs fixer failing

2022-07-27 13:03 UTC, zuk3975 approved these changes

2022-07-29 19:26 UTC, kpodemski commented
Maybe you should consider putting it in the `PrestaShopBundle\Form\Admin\Type` namespace. In the end, you've added the widget globally to the template + it is not strictly related to the Order page. It wouldn't be the first custom form type we provide for the community. What do you think?

2022-07-29 19:27 UTC, kpodemski requested changes
I'm requesting changes to make sure somebody will address my comment :-)

2022-08-01 11:19 UTC, zuk3975 commented
> Maybe you should consider putting it in the `PrestaShopBundle\Form\Admin\Type` namespace. In the end, you've added the widget globally to the template + it is not strictly related to the Order page. It wouldn't be the first custom form type we provide for the community. What do you think?

yes Indeed, I agree :+1:

2022-08-01 15:00 UTC, matthieu-rolland reviewed
I'm not aproving yet, @kpodemski 's feedback is interesting, wdyt @FabienPapet ?

2022-08-01 16:24 UTC, zuk3975 requested changes
@kpodemski comment is legit, we should move the type to more generic place, because it could be reused anywhere, not only in orders page.

2022-08-03 09:43 UTC, FabienPapet commented
@kpodemski Good idea, I've updated the PR and moved the form type.

2022-08-03 11:24 UTC, zuk3975 approved these changes, later dismissed

2022-08-03 11:31 UTC, kpodemski submitted a review, later dismissed

2022-08-08 09:33 UTC, florine2623 reviewed
Hello @FabienPapet ,

Thanks for the PR !

I have found a regression.

Without PR, if I don't fill all the fields in Order Payment, I have a warning :

https://user-images.githubusercontent.com/16019289/183386941-c8e7bb0c-ac3e-4876-af1c-3818fc9c2312.mov

With this PR, I don't have a warning, I have an exception:
<img width="1044" alt="Screenshot 2022-08-08 at 11 23 55" src="https://user-images.githubusercontent.com/16019289/183387032-5646d2c6-cbed-4af5-865e-029d8c671a52.png">

Tested with existing and custom currencies.

Could you check please ?
Thanks!

2022-08-08 11:54 UTC, kpodemski approved these changes

2022-08-08 11:56 UTC, okom3pom approved these changes

2022-08-08 12:20 UTC, florine2623 approved these changes
Thanks @FabienPapet ,

I don't have the exception anymore. It is working as expected.

It is QA ✅

2022-08-10 13:37 UTC, merged

2022-08-10 13:38 UTC, kpodemski commented
Thanks @FabienPapet