Move `copyImg` to `ImageManager` and make reusable
PrestaShop/PrestaShop pull request #29295
Opened 2022-08-09 19:37 UTC by PululuK

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Move `copyImg` to `ImageManager` to make it reusable.
| Type?             |  refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A.
| Related PRs       | N/A.
| How to test?      | Make sure that product import still work with images.
| Possible impacts? | Import with images link.

2022-08-10 20:15 UTC, matks requested changes

2022-08-10 20:15 UTC, matks commented on controllers/admin/AdminImportController.php
> +        return ImageManager::copyImg($$id_entity, $$id_image, $$url, $$entity, $$regenerate);
Too many dollar signs 😄 I guess

2022-08-10 20:36 UTC, PululuK commented on controllers/admin/AdminImportController.php
> +        return ImageManager::copyImg($$id_entity, $$id_image, $$url, $$entity, $$regenerate);
Money money money 😄 
Nice catch @matks

2022-08-22 15:57 UTC, matks approved these changes

2022-08-23 07:57 UTC, Amoifr reviewed
You're right these have no place in controller. And as you said they will reusable in this place. Thx

2022-08-23 15:10 UTC, PrestaEdit commented
Maybe we could deprecated theses two methods, there is no needs to call a method that call another one, especially while it's static: best will be to use it directly (even in the existing code, if possible).

2022-09-02 16:01 UTC, matks commented
@PrestaShop/committers I approved the PR but it is missing 1 approval :) if you want to look at it

2022-09-05 07:43 UTC, zuk3975 approved these changes

2022-09-05 07:50 UTC, kpodemski approved these changes

2022-11-14 10:28 UTC, FabienPapet approved these changes

2022-11-16 16:34 UTC, AureRita commented
Hi @PululuK 

Thank you for your PR, I tested it and it seems to works, as we can see here :

[Untitled_ Nov 16, 2022 5_01 PM.webm](https://user-images.githubusercontent.com/100699445/202233127-f4440556-7a69-413b-852f-4ee6d65aa466.webm)

Can you give me an example of module to let us test the extra code you provided? 

Waiting for your feedback

2022-11-18 16:11 UTC, AureRita commented
hi @PululuK 

After checking with you, I have create a php files with the code you've send and replace the id by a product without picture, 
I tested it and it works, as we can see : 

[Untitled_ Nov 18, 2022 5_07 PM.webm](https://user-images.githubusercontent.com/100699445/202749818-a4b0e483-eb3b-417b-aef9-46321dffde1e.webm)

just a little disclaimer, the link of the picture you send me don't work so I use another one

Thank you

2022-11-18 16:11 UTC, AureRita approved these changes

2022-11-18 16:53 UTC, matks commented
Thank you @PululuK

2022-11-18 16:54 UTC, merged