Fix apply new voucher to cart
PrestaShop/PrestaShop pull request #29362
Opened 2022-08-16 16:02 UTC by MeKeyCool

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | See below, #25579 and #25802 
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25579.
| Related PRs       | #25802
| How to test?      | See below and #25579
| Possible impacts? | All cart rules workflows may be impacted.

Thanks to @sowbiba that worked a lot on this issue in #25802.
> ## Description (copy of [#25579 (comment)](https://github.com/PrestaShop/PrestaShop/issues/25579#issuecomment-914269727))
> 
> Before, The modal was adding the cartRule to the cart in a fancyBox : we load the addCartRule page into an iframe. Nothing says that we want to link the cartRule added to the current cart https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/admin-dev/themes/new-theme/js/pages/order/create/create-order-page.js#L185
> 
> The totals are calculated first and then we get the discounts. When we get the discounts, we call `getCartRules` with `autoAdd = true`. This query adds all applicable cartRules to the cart given. In this way, the totals are wrong and the discounts correct https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Cart.php#L4010 https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Cart.php#L4047
> 
> One solution to avoid this is a BIG bandage : we first get the cartRules with autoAdd = true. That will apply all applicable cartRules to the cart and then we calculte the totals and the discounts
> 
> The ideal solution would be to have a specific modal to add cartRules to current cart. Doing this we will be able to perform 1 - create the cart Rule 2 - Try to apply created cart rule to the current cart (I say TRY because if the cart doesnt match the cartRule rules, it won't be applied) This solution will also allow us to use the commands AddCartRuleCommand and AddCartRuleToCartCommand instead of the legacy controller like it is now
> 
> This change is [<img alt="Reviewable" height="34" src="https://camo.githubusercontent.com/a8b5f6726de4903e6ce89df24ad596326aa4f49974dbb99137f93e280f30421c/68747470733a2f2f72657669657761626c652e696f2f7265766965775f627574746f6e2e737667">](https://reviewable.io/reviews/prestashop/prestashop/25802)

:point_up: I encountered some troubles to reproduce cause behavior isn't always consistent.
Some times, I add to apply a second voucher to the cart.

Fixing some weird 500 errors due to poor cart rules workflow management, I can't reproduce the problem anymore. I think the last problem that @sowbiba didn't solve was due to some concurrencies in cart/cart_rules associations.

2022-08-16 17:14 UTC, PrestaEdit requested changes

2022-08-16 17:14 UTC, PrestaEdit commented on src/Adapter/Cart/CommandHandler/AddCartRuleToCartHandler.php
> +            // @todo : should log an info message.
```suggestion
            Do it ! ;-)
```

2022-08-16 17:14 UTC, PrestaEdit commented on admin-dev/themes/default/template/controllers/cart_rules/form.tpl
> +            if (typeof window.parent.order_create !== "undefined") {
Indent issue, there.

2022-08-17 06:42 UTC, MeKeyCool commented on src/Adapter/Cart/CommandHandler/AddCartRuleToCartHandler.php
> +            // @todo : should log an info message.
Then I'll remove the comment ^^

2022-09-07 20:41 UTC, yanmakouf approved these changes
Seems ok to me :)

2022-11-18 17:25 UTC, matks commented
Apologies @MeKeyCool you opened this PR in August and we did not review it fast enough.

Now PrestaShop 1.7.8 has entered security-only phase so we don't merge bugfixes in it anymore :( . This bug should rather target branch 8.0.x .

I close the PR but if you are motivated to port this fix to 8.0.x you can reopen it (or ping me) 😉

2022-11-18 17:25 UTC, closed without merging