Allow blank value for mobile phone
PrestaShop/PrestaShop pull request #29381
Opened 2022-08-17 15:16 UTC by tom-combet

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Allow blank value for mobile phone in customer address
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #29379.
| Related PRs       | N/A
| How to test?      | Edit customer address with blank mobile phone
| Possible impacts? | None

2022-08-17 16:15 UTC, FabienPapet requested changes
IIRC when you do that, you are setting empty values in database instead of values. Empty phone numbers should IMO be saved as null.

I think the fix should focus constraint instead of editing submitted data. You can play with validation groups to allow null in bo, and disallow in front office.

2022-08-17 17:07 UTC, tom-combet commented
> I think the fix should focus constraint instead of editing submitted data.
Which constraint do you make reference to?
I don't think it's about constraints here, as null values are allowed in any case (required is equal to false). It's more about saving null values in the database indeed, but it would be a much larger issue since the empty_data property is a lot used in PrestaShop types...

> You can play with validation groups to allow null in bo, and disallow in front office.
The issue doesn't concern FO at all, the Symfony types are only used in BO. By the way, why should it be different in FO?

2022-08-17 17:33 UTC, FabienPapet commented
With the `empty_data` option, you'll replace a `null` value  **in database** by an empty string if you save your customer and it is not something you want.

Which constraint disallows null values ? If you want to allow `null` value, you'll need to find that constraint and either edit it or find a way to disable it with validation groups.

The `empty_data` option is working , but it has so much side effects and cannot be accepted.

2022-08-17 19:54 UTC, tom-combet commented
> Which constraint disallows null values ?

It's not a matter of constraints. If you look at the code, the mobile phone is updated only if the mobile phone is not null (see [here](https://github.com/PrestaShop/PrestaShop/blob/83079ee0c30a7aebe58086c9aef2022ff43203a9/src/Adapter/Address/CommandHandler/EditCustomerAddressHandler.php#L159)). This is why it's happening only with mobile phone, cause it's the only one non-required field which don't define `empty_data` option.

I was not aware of the empty_data debate though, so maybe it's better to open an other PR to remove completely empty_data everywhere?

2022-11-11 11:08 UTC, kpodemski approved these changes
I think we can accept it to fix the bug and think about other solutions later.

It shouldn't be any problem **for now**, as we have empty values in this field by default...

2022-11-11 11:57 UTC, FabienPapet commented
The problem for me is with the empty_data function , you'll never have null values, and this is a problem for me as when you are submitting a form, this field will always be updated.


> It shouldn't be any problem for now, as we have empty values in this field by default...
@kpodemski  what do you mean by empty ? `''` or `null` ?

2022-11-11 12:01 UTC, FabienPapet commented
I thinkl the correct fix here is to compare the value of the object, and the value in the command, if they are different, the we can trigger the update. The fix is for me not at the form level, but at the command level: we should allow to set null in the customer with the CQRS command

2022-11-11 18:58 UTC, tom-combet commented
> I thinkl the correct fix here is to compare the value of the object, and the value in the command, if they are different, the we can trigger the update. The fix is for me not at the form level, but at the command level: we should allow to set null in the customer with the CQRS command

I think it's a good idea, but maybe in an other PR? I can but doing it only for phone field is weird, isn't it?

2023-01-12 22:16 UTC, kpodemski commented
ping @FabienPapet - can we unblock this PR? It's a nasty bug that is easily solvable. It's not an ideal way of doing things, but it's the same for other fields too.

2023-01-12 22:49 UTC, FabienPapet approved these changes

2023-01-12 22:51 UTC, kpodemski commented
Thanks, @FabienPapet - I appreciate it. It would be great to have a PoC of how you'd like to see it solved the right way.

2023-01-13 14:32 UTC, djoelleuch approved these changes
Hello @tom-combet  ,

I've tested with PHP 7.4 / PHP 8.0 :heavy_check_mark: 
Automated tests => OK

[Untitled_ Jan 13, 2023 8_42 AM.webm](https://user-images.githubusercontent.com/115152460/212303534-85a580e4-8483-48d9-bcee-cdb5ad3036e8.webm)

It's QA approved :heavy_check_mark:  

thank you for your  PR  :rocket:

2023-01-13 14:39 UTC, merged

2023-01-13 14:39 UTC, kpodemski commented
Thank you, @tom-combet !