Bugfix for localization of messages with currencies that haven't cents
PrestaShop/PrestaShop pull request #29404
Opened 2022-08-21 19:17 UTC by kamilrafik

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Earlier, there was int type hint in this method; but in the process of developing one e-store with KRW currency that does not have analog of cents and does not need precision, it was found that sometimes null is passed to this method which causes some errors. Detailed testing is needed to reproduce errors, they were not logged fully; but this bugfix with replacing int type hint with intval() call worked fine and did not cause any visible issues. Obviously, the original issue and bugfix should be researched by some experienced PrestaShop core developer.
| Type?             | bug fix
| Category?         | LO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | not applicable
| Related PRs       | not applicable
| How to test?      | It requires research of the described issue by experienced PrestaShop core developer.
| Possible impacts? | Localization features may be impacted.

2022-08-22 15:51 UTC, matks requested changes
Dear @kamilrafik thank you for this contribution.

I understand you want to help by providing this bugfix however as you mentioned this is working in some usecase but you cannot guarantee it will have no side-effects.

Unless you can provide the detailed testing you mention, we cannot merge this.

The original issue and bugfix will not be researched by some experienced PrestaShop core developer 😅 this is now how open source works. If this bugfix is needed by someone it must be researched by this person.

Your bugfix will be useful for people looking for a workaround 👏 however we cannot merge it as it is not fully explored, understood and testable.

2022-08-22 19:14 UTC, kamilrafik commented
This PR was requested by company owner to minimize conflicts on upgrades in the future. If the company will decide to invest money into research of this bug, more details will be posted by me here or in the related issue. If not, it will stay as is.

2022-08-26 09:32 UTC, yanmakouf commented on src/Core/Localization/CLDR/ComputingPrecision.php
> +        // Earlier, there was int type hint in this method; but in the process of developing one e-store with KRW currency that does not have analog of cents and does not need precision, it was found
In order to have a proper fix, it should be investigated why sometimes null is passed. When adding KRW to the currencies the BD table entry  ps_currency.precision is indeed set to 0. So there must be somewhere in the flow where this is corrupted

2022-10-05 19:47 UTC, matks commented
> This PR was requested by company owner to minimize conflicts on upgrades in the future. If the company will decide to invest money into research of this bug, more details will be posted by me here or in the related issue. If not, it will stay as is.

Hey @kamilrafik looks like the chosen usecase was "it will stay as is" 😄 

No worries as I mentioned your bugfix will be useful for people looking for a workaround 👏 however we cannot merge it as it is not fully explored, understood and testable.

Since the PR did not moved for 30 days, I will follow [our guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests) and I'll close this pull request as it seems stale.

Best regards,

2022-10-05 19:47 UTC, closed without merging