Fix ps_facetedsearch - bad display after clearing a filter of no result
PrestaShop/PrestaShop pull request #29471
Opened 2022-08-30 00:44 UTC by leemyongpakvn

Seperate `renderedProducts` and `productSelectors`, then we are safe in case `productSelectors` is `Undefined` after the previous filter with _No product_

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Backport of https://github.com/PrestaShop/classic-theme/pull/43.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #28966.
| Related PRs       | If theme, autoupgrade or other module change is needed, provide a link to related PRs here.
| How to test?      | Please indicate how to best verify that this PR is correct.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

2022-08-30 08:37 UTC, NeOMakinG requested changes

2022-08-30 08:37 UTC, NeOMakinG commented on themes/classic/_dev/js/listing.js
> +  }
I guess the `if/else` is useless then?

2022-08-30 08:39 UTC, NeOMakinG submitted a review, later dismissed
🍬

2022-08-30 08:42 UTC, kpodemski approved these changes, later dismissed

2022-08-30 13:29 UTC, NeOMakinG approved these changes

2022-09-02 00:19 UTC, leemyongpakvn commented
@kpodemski In need of your approval after a small lint-fix

2022-09-02 08:06 UTC, kpodemski approved these changes

2022-09-08 14:45 UTC, sLorenzini approved these changes
hello @leemyongpakvn,

Thank you for this PR.
Tested on 1.7.8.x branch with PHP 7.3.

All products are well displayed after clearing the filter:

https://user-images.githubusercontent.com/2854834/189152641-40970163-3525-4910-a55a-5fd007756c1c.mp4

QA approved ✅ 

Thanks

2022-09-08 15:30 UTC, matks commented
Thank you @leemyongpakvn

2022-09-08 15:30 UTC, merged