BO - Modules - Bad display of the title after resizing the screen
PrestaShop/PrestaShop pull request #29489
Opened 2022-08-31 10:10 UTC by AlexTechDev

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  8.0.x 
| Description?      | With this pull request we change the .toolbar_btn padding from 16px to 13px. This change is not noticeable on large screens, but on small screens it is just enough for the buttons to be displayed correctly.
| Type?             | bug fix 
| Category?         |  BO 
| BC breaks?        | no
| Deprecations?     |  no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/26618
| How to test?      |
GO to BO>Modules>Module manager
Confugre ps_customtext module or other module like payments by check
Resize the screen to 425x878

**Before**
![image](https://user-images.githubusercontent.com/100702024/187654816-d5e85bf5-4786-4224-86a5-3201714c8034.png)

**After**
![image](https://user-images.githubusercontent.com/100702024/187654728-a7234497-b510-441a-8384-32e5615455e3.png)

2022-09-01 08:19 UTC, NeOMakinG commented
@AlexTechDev As this is a regression from 1.7.8, we should fix it on `1.7.8.x` branch

2022-09-06 14:08 UTC, AlexTechDev commented
Hi @NeOMakinG,
I try it on 1.7.8 branch and the same change fix it on these branch.
About  a module that hook here I don't test it, I can try to hook one module (or maybe we have one example module doing this) and try to solve it.

2022-09-06 15:21 UTC, NeOMakinG commented
> Hi @NeOMakinG, I try it on 1.7.8 branch and the same change fix it on these branch. About a module that hook here I don't test it, I can try to hook one module (or maybe we have one example module doing this) and try to solve it.

Then, go for a fix on `1.7.8.x`!

Yep we should try with a hooked module, and find a solution working in most of use case we can :)

I don't know any particular modules hooking there, I know `ps_mbo` is hooked there for example but this is really specific and not working on 1.7.8.x but more on 8.x, I guess if we want to test this, we will need to develop our own module, or just inject some buttons inside devtools directly, that would do the job as a monkey patch!

2022-09-23 10:10 UTC, kpodemski requested changes
@AlexTechDev 

This should go to the `1.7.8.x` branch, and make sure to follow @NeOMakinG suggestion :)

2022-09-26 22:18 UTC, AlexTechDev commented
Thank you @NeOMakinG and thank you @kpodemski for reminding me of this!

i will inject some buttons inside devtools directly and try it :)

2023-01-16 07:59 UTC, kpodemski commented
Hi @AlexTechDev 

I know you're enjoying new adventures now, so I close this PR! Thanks for contributing anyway!

2023-01-16 07:59 UTC, closed without merging