Use non-deprecated property
PrestaShop/PrestaShop pull request #29605
Opened 2022-09-10 09:17 UTC by PrestaEdit

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | `sign` is a deprecated property, `symbol` replace it.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no

2022-09-13 21:49 UTC, kpodemski submitted a review, later dismissed

2022-10-13 09:09 UTC, mflasquin approved these changes, later dismissed

2022-10-13 09:11 UTC, mflasquin reviewed
Thanks for the PR @PrestaEdit, maybe we can fix it on whole project ?

2022-10-13 09:21 UTC, mflasquin submitted a review, later dismissed

2022-10-13 09:23 UTC, atomiix approved these changes, later dismissed

2022-10-17 10:13 UTC, PululuK approved these changes

2022-10-17 12:10 UTC, FabienPapet approved these changes

2022-10-17 12:14 UTC, atomiix approved these changes

2022-10-17 12:16 UTC, atomiix commented
I think this needs a little QA as `->getSymbol()` doesn't behave exactly like `->sign`
@PrestaEdit maybe you can list the pages where this change can have an impact?

2022-10-17 13:26 UTC, FabienPapet requested changes
Can you please update `CurrencyCore::getSign` method as well ?

2022-11-07 16:46 UTC, closed without merging