Add GdImage to phpDoc
PrestaShop/PrestaShop pull request #29601
Opened 2022-09-10 08:45 UTC by PrestaEdit

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Since PHP 8.0.0, somes methods used with GD library returns GdImage instead of ressource. Somes inside this class have the GdImage mentionned, other not.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no

2022-09-10 08:50 UTC, PululuK approved these changes, later dismissed

2022-10-05 19:58 UTC, matks requested changes
@PrestaEdit I'm sorry but PHPStan disagrees with you 😅 are you sure?

Can you check PHPStan verifications?

2022-10-05 20:12 UTC, matks commented
I checked https://github.com/PrestaShop/PrestaShop/blame/develop/classes/ImageManager.php and I think I remember something like this in a PR of @atomiix

2022-10-06 06:20 UTC, PrestaEdit commented
Actually, the `GdImage` was added into PHP8. It was a `ressource`, before that.

I don't know what we need to do there. Maybe @Progi1984 - the master of PHPStan - could give us an advice on it ?

2022-10-06 06:22 UTC, Progi1984 commented on classes/ImageManager.php
> +     * @return false|resource|GdImage
```suggestion
     * @return false|resource|\GdImage
```

@PrestaEdit Could you try it ?

2022-10-06 06:42 UTC, PrestaEdit commented
https://github.com/phpstan/phpstan/issues/4060#issuecomment-723559902 :-/

2022-10-06 13:30 UTC, FabienPapet commented
I think we can ignore PHPStan ending with `has invalid return type GdImage`.

2022-11-03 10:29 UTC, closed without merging