Fix used static property name
PrestaShop/PrestaShop pull request #29606
Opened 2022-09-10 09:25 UTC by PrestaEdit

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | `$cache_modules_roles` doesn't exists. The used property is `$cache_lgc_access` inside this method and the one called if not yet setted.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no

2022-09-13 21:49 UTC, kpodemski requested changes
A little typo

2022-09-13 21:49 UTC, kpodemski commented on classes/module/Module.php
> +        if (empty(static::cache_lgc_access)) {
```suggestion
        if (empty(static::$cache_lgc_access)) {
```

2022-09-13 22:16 UTC, kpodemski approved these changes

2022-10-05 20:34 UTC, matks approved these changes
Looks good 👍

2022-10-05 20:35 UTC, matks commented
@Robin-Fischer-PS Another 'funny' bug fixed by @PrestaEdit : this code used to call a variable that... did not exist. So the condition was always false. I think no QA is needed, wdyt? Or automated tests, to look for regressions?

2022-10-12 06:16 UTC, kpodemski commented
ping @Robin-Fischer-PS

2022-11-07 16:46 UTC, closed without merging