Update InternationalizedDomainNameConverter.php
PrestaShop/PrestaShop pull request #29624
Opened 2022-09-13 14:51 UTC by javdome

Fix bugs when you only have support in INTL_IDNA_VARIANT_2003. Fix bugs like backoffice login (such as https://github.com/PrestaShop/PrestaShop/issues/29622)

2022-09-13 21:45 UTC, kpodemski requested changes
Thank you for your Pull Request. To validate it correctly, please follow our guidelines, and complete the table (Issue number, How to test, etc.) you see at the beginning of creating one.

2022-09-14 09:32 UTC, kpodemski commented
Thanks @javdome !

I think this PR could be validated by a dev. I see @matks actively discussed the issues you mentioned in the PR table.

2022-09-14 09:33 UTC, kpodemski approved these changes

2022-09-14 13:32 UTC, matks reviewed
Hello! It's been a long time we worked on this topic so my memory has nothing remaining.

However if I read [what I wrote 2 years ago](https://github.com/PrestaShop/PrestaShop/issues/22300#issuecomment-818708636) then it seems ICU < 4.6 means you are using an ICU component from 2009.

In 2022 I think it might not be useful to introduce code changes in PrestaShop that do allow backward compatibility with software that is more than 12 years old.

2022-09-14 13:55 UTC, kpodemski commented
@matks, this could fix some issues reported in recent months. If there's no way to show a proper error message to the end user, maybe it would be better to add these few lines. We did the same for the Mail class, right?

2022-09-14 13:57 UTC, kpodemski requested changes
@javdome I didn't notice it before. The function may not return anything, and you should have one value returned by default

2022-09-14 16:31 UTC, matks commented
> @matks, this could fix some issues reported in recent months. If there's no way to show a proper error message to the end user, maybe it would be better to add these few lines. We did the same for the Mail class, right?

If you think this is important, then I trust you 👍

2022-09-14 17:39 UTC, javdome commented
> @javdome I didn't notice it before. The function may not return anything, and you should have one value returned by default

Done!!

2022-09-15 16:32 UTC, matks submitted a review, later dismissed

2022-09-19 21:31 UTC, kpodemski requested changes, later dismissed
Hi @javdome 

You should definitely use `spaces` instead `tabs` because cs-fixer is not happy :D

2022-09-20 09:02 UTC, javdome commented
Hi @kpodemski

Done!! :+1:

2022-09-20 09:07 UTC, atomiix approved these changes, later dismissed

2022-09-20 09:15 UTC, matks approved these changes

2022-09-21 09:31 UTC, matks requested changes, later dismissed

2022-09-21 09:31 UTC, matks commented on src/Core/Util/InternationalizedDomainNameConverter.php
> +
```suggestion
```
PHP CS Fixer wants to remove this line, else it complains 😄 

https://github.com/PrestaShop/PrestaShop/actions/runs/3088783456/jobs/4995760254

2022-09-21 11:46 UTC, javdome commented
Hi @matks @kpodemski 
Done!!... fingers crossed :crossed_fingers:

2022-09-21 12:13 UTC, atomiix approved these changes

2022-09-21 13:04 UTC, kpodemski approved these changes

2022-09-21 13:05 UTC, kpodemski commented
Hello @PrestaShop/qa-team 

I think this issue is quite technical, but IMHO automated tests should be enough to validate this PR. What do you think?

2022-11-16 16:20 UTC, matthieu-rolland commented
thank you @javdome and @Progi1984

2022-11-16 16:20 UTC, merged