Upgrade Smarty to 3.1.47
PrestaShop/PrestaShop pull request #29636
Opened 2022-09-14 12:44 UTC by mflasquin

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Upgrade Smarty to 3.1.47 : <br>- Fixes illegal characters warning in math. <br>- Prevent PHP injection through malicious block name or include file name. This addresses https://github.com/advisories/GHSA-634x-pc3q-cf4c. <br>- Fixed replace modifier by converting encoding if needed. <br>- Fixed second param of unescape. <br>- Applied appropriate javascript and html escaping in mailto plugin to counter injection attacks <br>- Fixed use of rand() without a parameter in math function <br>- Fixed unselected year/month/day not working in html_select_date 
| Type?             | improvement
| Category?         | CO
| BC breaks?        |  no
| Deprecations?     | no
| Fixed ticket?     | 
| Related PRs       |
| How to test?      | CI is green
| Possible impacts? |

2022-09-14 12:57 UTC, matks requested changes
Thank you for this PR 👍 there is a little problem in composer.lock

2022-09-14 12:57 UTC, matks commented on composer.lock
> +    "plugin-api-version": "1.1.0"
Woups, please do not commit this line ;)

2022-09-14 16:30 UTC, matks approved these changes

2022-09-15 12:34 UTC, kpodemski approved these changes

2022-09-15 12:35 UTC, kpodemski commented
@PrestaShop/qa-team 

Hello QA Team! I think automatic tests should do the job for this one, right?

2022-09-15 12:37 UTC, Robin-Fischer-PS commented
@kpodemski Yes, indeed, only automated tests :) Thanks for the ping !

2022-10-26 07:43 UTC, boubkerbribri commented
Hello @PrestaShop/prestashop-core-developers  
Since this is not a regression, is the PR targeting the correct branch ?
Thank you

2022-10-26 07:47 UTC, matks commented
> Hello @PrestaShop/prestashop-core-developers Since this is not a regression, is the PR targeting the correct branch ? Thank you

@boubkerbribri It's for security 😉 the last version of smarty contains a vulnerability bugfix and must be included in 1.7.8

2022-10-26 07:48 UTC, boubkerbribri commented
> @boubkerbribri It's for security wink the last version of smarty contains a vulnerability bugfix and must be included in 1.7.8

Thanks, I'm taking it back

2022-10-26 08:59 UTC, boubkerbribri approved these changes
Tested with some UI tests : FO + some legacy pages.
=> QA :heavy_check_mark:

2022-10-26 13:32 UTC, matks commented
Thank you @mflasquin

2022-10-26 13:32 UTC, merged