make postcode field optional in BO
PrestaShop/PrestaShop pull request #29696
Opened 2022-09-20 07:27 UTC by panariga

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 8.0.x / 1.7.8.x
| Description?      |make postcode field optional in BO
| Type?             | bug fix 
| Category?         |BO 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #29625
| Related PRs       | 
| How to test?      | Try to edit customer Address in BO, postcode should not be required anymore
| Possible impacts? |

2022-09-20 09:59 UTC, okom3pom commented
PrestaShop should use the country data and the required field data. 

This is not the case.

Your PR solves your problem but adds to others. 

I will check the code to use the country datas first and after required flieds to fix the problem for all.

2022-09-21 07:40 UTC, ghost commented
Code is good but we can't force postcode with required fields, so we can remove 

https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/src/Core/Domain/Address/ValueObject/RequiredFields.php#L36

https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/src/Core/Domain/Address/ValueObject/RequiredFields.php#L49

And add a text to inform that it is in country that it must be defined.

2022-09-21 09:24 UTC, matks requested changes
As mentioned by @okom3pom we can't do this :( this is a change with a lot of impact

2022-09-21 09:36 UTC, okom3pom commented
@matks after check i see it's a regression and the branch is 1.7.8.x

Required field are used only in 8.1.0 so i think we can validate this PR.

2022-11-11 12:15 UTC, kpodemski commented
Hello 👋 

Thank you for the contribution, but since we have had no news from you for more than 30 days, I'll close this pull request as it seems stale. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2022-11-11 12:15 UTC, closed without merging