Add template country global vars
PrestaShop/PrestaShop pull request #29707
Opened 2022-09-20 14:31 UTC by PululuK

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      |  Add template country global vars.
| Type?             |improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| Related PRs       | N/A
| How to test?      | ```smarty  var_dump($country) ```
| Possible impacts? | N/A

2022-09-20 15:40 UTC, PrestaEdit requested changes
$this->objectPresenter->present($this->context->country)

2022-09-20 15:40 UTC, PrestaEdit commented on classes/controller/FrontController.php
> +            'country' => $this->getTemplateVarCountry(),
```suggestion
            'country' => $this->objectPresenter->present($this->context->country),
```

2022-09-20 20:29 UTC, PrestaEdit commented on classes/controller/FrontController.php
> +    public function getTemplateVarCountry()
No more needed.

2022-09-20 20:35 UTC, PrestaEdit approved these changes

2022-09-21 09:16 UTC, matks approved these changes
Makes sense for me 👍 

Do you have a specific usecase in mind?

2022-09-22 09:26 UTC, Hlavtox commented
`Do you have a specific usecase in mind?`

It's good to have everything ready in a template. ;-)

2022-10-05 20:41 UTC, matks commented
> `Do you have a specific usecase in mind?`
> 
> It's good to have everything ready in a template. ;-)

They say "don't be afraid of asking questions" so ... I might have missed the joke 😅  but what do you mean?

2022-10-10 23:27 UTC, FabienPapet approved these changes

2022-10-11 06:57 UTC, okom3pom approved these changes

2022-10-18 09:32 UTC, florine2623 reviewed
Hello @PululuK ,

I think I'm testing it wrong. Could you confirm a way to test it?

Here's what I'm doing, in `develop/themes/classic/templates/cms/stores.tpl` I added `{$country}` but the result is not as expected:
<img width="1426" alt="Screenshot 2022-10-18 at 11 31 29" src="https://user-images.githubusercontent.com/16019289/196393406-7c33b901-0cae-4558-8107-d7441d0e6402.png">

Tested with other global vars, same thing. In fact, I know I'm not testing it right 😅 

Waiting for your answer :)
Thanks!

2022-10-18 14:07 UTC, florine2623 approved these changes
Hello again,

Tested again with @Hlavtox 's tips! 😉 

I can access the variable easily just by `{dump($country)}` or adding `{$country.name}`.
Info was added in `MY_SHOP/themes/classic/templates/cms/stores.tpl`
<img width="371" alt="Screenshot 2022-10-18 at 16 00 49" src="https://user-images.githubusercontent.com/16019289/196452009-2ac14703-00ab-44ee-8458-6d243acb9455.png">
<img width="473" alt="Screenshot 2022-10-18 at 16 04 09" src="https://user-images.githubusercontent.com/16019289/196452497-62484331-2bc1-43f9-988f-5b9b56fe68ad.png">




Works like a charm.
It is QA ✅ !

2022-10-19 07:40 UTC, matks commented
Thank you @PululuK and @florine2623

2022-10-19 07:45 UTC, merged