29593: fixed issue where module would be overriden with test module
PrestaShop/PrestaShop pull request #29708
Opened 2022-09-20 14:55 UTC by margud

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  8.0.x 
| Description?      | Behavior tests would override few modules with old not working version from test folder, now if the module already exists its not overriden
| Type?             | bug fix 
| Category?         | TE
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | Fixes #29593 
| How to test?      | Running behavior test with ./vendor/bin/behat -c tests/Integration/Behaviour/behat.yml -s module --tags module will skip override of the module from test modules

2022-09-20 16:22 UTC, matks approved these changes
Good one @margud 😄 thanks

2022-10-17 12:54 UTC, jolelievre requested changes
HI @margud 

I'm not sure this is the appropriate solution 🤔 There's a deeper problem in the initial issue, the modules folder is supposed to be `ROOT/tests/Resources/modules` in test environment, not `ROOR/modules`

So something is wrongly configured here at some point and that's what causes the problem, your changes seem to be fixing the symptoms not the root cause So the problem will rise again at some point

2022-10-21 09:53 UTC, margud commented
> HI @margud
> 
> I'm not sure this is the appropriate solution thinking There's a deeper problem in the initial issue, the modules folder is supposed to be `ROOT/tests/Resources/modules` in test environment, not `ROOR/modules`
> 
> So something is wrongly configured here at some point and that's what causes the problem, your changes seem to be fixing the symptoms not the root cause So the problem will rise again at some point

I tried to change it but the issue is that most of PS uses the root dir const _PS_ROOT_DIR_ that cannot be changed. I tried to change it for the tests but with no success.

2022-11-11 12:18 UTC, kpodemski commented
@jolelievre, these tests are related to modules in general, I don't think we need to target "tests" directory

2022-11-11 12:18 UTC, kpodemski approved these changes, later dismissed

2022-12-19 14:40 UTC, matks submitted a review, later dismissed

2022-12-19 15:02 UTC, matks commented
Dear @PrestaShop/qa-team I think this PR should be tested by a developer as this is CI related. Can you confirm?

2022-12-19 15:37 UTC, MhiriFaten commented
@matks yes it should be tested by a developer.
I will add the `waiting for dev` label !

Thank you.

2023-01-12 16:38 UTC, jolelievre requested changes
I reaffirm I strongly disagree with this solution compared to the initial issue. This only hides the core problem, I opened the initial issue because this bug indicates a real problem in our test environment related to the modules directory. They shouldn't be the same as the shop folder we should always rely on the folder for modules in test environment and that's not the case.
That's what needs to be figured out.

2023-01-20 11:51 UTC, margud commented on tests/Integration/Behaviour/Features/Scenario/Profile/profile_permissions.feature
> +      | ps_emailsubscription | view,configure,uninstall |
Changed module to another one because now we are using test modules and ps_wirepayment doesnt exist there. So i just took another random one.

2023-01-20 11:54 UTC, zuk3975 commented on tests/Integration/Behaviour/bootstrap.php
> +define('_PS_MODULE_DIR_', __DIR__ . '/../..' . '/Resources/modules/');
```suggestion
define('_PS_MODULE_DIR_', __DIR__ . '/../../Resources/modules/');
```

2023-01-27 11:50 UTC, zuk3975 approved these changes

2023-03-24 07:40 UTC, closed without merging