Functional tests - Add new test 'FO > User account > Get GDPR data in csv'
PrestaShop/PrestaShop pull request #29726
Opened 2022-09-22 15:02 UTC by nesrineabdmouleh

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Add new test 'FO > User account > Get GDPR data in csv'
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| Related PRs       | no
| How to test?      | no
| Possible impacts? | no

2022-09-22 15:16 UTC, boubkerbribri commented on tests/UI/campaigns/functional/FO/03_userAccount/05_getGDPRDataInCSV.js
> +        // const age = await basicHelper.age(customerData.birthDate);
```suggestion
        // TODO
        // To replace isVisible after release of the module psgdpr
        // const age = await basicHelper.age(customerData.birthDate);
```

Adding maybe a `TODO` to not forget about this

2022-09-22 15:19 UTC, Progi1984 commented on tests/UI/utils/files.js
>     * @param ignoreTimeZone {boolean} True to delete timezone string added to some image url
```suggestion
   * @param ignoreTimeZone {boolean} True to delete timezone string added to some image url
   * @param encoding {string} Encoding for the file
```

2022-09-22 15:20 UTC, Progi1984 commented on tests/UI/campaigns/functional/FO/03_userAccount/05_getGDPRDataInCSV.js
> +  {
```suggestion
const contactUsData = new ContactUsFakerData({
```

2022-09-22 15:24 UTC, Progi1984 reviewed
Small feedback

2022-09-23 07:52 UTC, nesrineabdmouleh commented on tests/UI/utils/files.js
>     * @param ignoreTimeZone {boolean} True to delete timezone string added to some image url
Done thx :+1:

2022-09-23 07:55 UTC, Progi1984 approved these changes

2022-09-26 07:46 UTC, boubkerbribri commented on tests/UI/campaigns/functional/FO/03_userAccount/05_getGDPRDataInCSV.js
> +          '"MODULE:NEWSLETTERSUBSCRIPTION""Newslettersubscription:noemailtoexport,thiscustomerhasnotregistered.""',
Maybe we can create customizable functions (on a helper) to get what to check.

2022-09-27 07:11 UTC, Progi1984 requested changes
@nesrineabdmouleh Could you rebase your PR ? You have some conflicting files.

2022-09-27 12:16 UTC, Progi1984 approved these changes

2022-09-29 08:28 UTC, SD1982 approved these changes

2022-09-29 08:47 UTC, NeOMakinG approved these changes

2022-09-29 08:47 UTC, merged