Avoid adding multiple times the same product on the wishlist page
PrestaShop/PrestaShop pull request #29892
Opened 2022-10-05 14:52 UTC by 0x346e3730

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR fixes the products displaying multiple times in a customer's wishlist when he has multiple user groups.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/29043
| Related PRs       | N/A
| How to test?      | Create a Customer from the BackOffice (he will have 3 user groups), log-in as this customer on the Front Office, add a product to the wishlist, make sure it shows only once.
| Possible impacts? | Everything Product related

2022-10-05 15:00 UTC, matks commented
@0x346e3730 I suggest some improvements for your PR table:

`This PR fixes the products displaying multiple times in a customer's wishlist when he has multiple user groups.`
⬇️ 
`This PR fixes the products displaying multiple times in a customer's wishlist when he has multiple user groups by removing duplicate rows in the SQL data fetched`

This helps reviewers understand the "what did you do" in the PR for technical point of view

`Create a Customer from the BackOffice (he will have 3 user groups), log-in as this customer on the Front Office, add a product to the wishlist, make sure it shows only once.`
⬇️ 
When you fix a bug you can simply say "See ticket steps" 😄 as issue https://github.com/PrestaShop/PrestaShop/issues/29043 contains all needed information to reproduce the bug

`Everything Product related`
⬇️ 
That's a lot 😄 maybe we can reduce the scope. As you modified `Product::getProductsProperties()` I checked what part of the codebase it impacts and it seems it's used in multiple places on Front-Office to display products so maybe we can say
`Front-office pages where lists of products are displayed`

2022-10-05 15:00 UTC, matks approved these changes

2022-10-05 15:00 UTC, matks commented on classes/Product.php
> +                if ($row2 && !in_array($row2['id_product'], array_column($results_array, 'id_product'), true)) {
Smart thing to use `array_column` to de-duplicate `$row2`

2022-10-05 15:07 UTC, 0x346e3730 commented
@matks Thank you for the feedback, I'm updating the PR adequately and will try to keep that in mind for the next ones !

2022-10-06 11:21 UTC, Hlavtox requested changes
Code will not work with anything other than basic product.😐

2022-10-06 11:21 UTC, Hlavtox commented on classes/Product.php
> +                if ($row2 && !in_array($row2['id_product'], array_column($results_array, 'id_product'), true)) {
What if I pass different combinations of the same product to `$query_result`? They will have the same ID, but different id of combination.
What if I pass normal and customized products to this function? They will have the same ID but different prices and weights.

Unfortunately, I don't think this is a good place to fix things like this. Wishlist should not pass it to this function.

2022-10-07 08:22 UTC, matks commented
Thanks @Hlavtox 👍 it's important infos

2022-10-07 09:56 UTC, 0x346e3730 commented
Hey @Hlavtox I agree with you and that what I was actually thinking when I did the PR, there must be ways to limit the possible impacts and it should be doable on the wishlist side as the issue is only on the wishlist. That's why I'm closing this PR in favor of https://github.com/PrestaShop/blockwishlist/pull/192 which fixes the issue but does not impact the core Product class at all.

2022-10-07 09:56 UTC, closed without merging