Fix issue 29937 - Array to string conversion in information of cli installation command
PrestaShop/PrestaShop pull request #29938
Opened 2022-10-10 07:51 UTC by thomasnares

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 8.0.x
| Description?      | Fixes display of default array parameter in cli
| Type?             | bug fix
| Category?         | IN
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes issue #29937 
| How to test?      | Go to install-dev directory, run php index_cli.php

2022-10-10 08:29 UTC, mflasquin requested changes

2022-10-10 08:29 UTC, mflasquin commented on install-dev/classes/controllerConsole.php
> +                    . PHP_EOL;
Good but I think It's a little difficult to read (two ternary operator in one line), I purpose to transform the code like this :

```suggestion
$help = isset($arg['help']) ? $arg['help'] : '';
$default = '';

if(isset($arg['default'])) {
    if(is_array($arg['default'])) {
        $default = '(Default: [' . implode(',', $arg['default']) . '])';
    } else {
        $default = '(Default: ' . $arg['default'] . ')';
    }
}

echo '--' . $name . "\t" . $help . "\t" . $default . PHP_EOL;
```

What do you think about it ? :)

2022-10-10 17:35 UTC, thomasnares commented
thanks @mflasquin, looks better :)

2022-10-11 08:58 UTC, mflasquin commented
> thanks @mflasquin, looks better :)

You're welcome, but take care to the indentation I think my updates broked it ;)

2022-10-11 09:15 UTC, thomasnares commented
Fixed 👍

2022-10-11 09:16 UTC, atomiix approved these changes

2022-10-11 09:17 UTC, mflasquin approved these changes

2022-10-11 09:41 UTC, kpodemski approved these changes

2022-10-11 09:41 UTC, kpodemski commented
@thomasnares 💪 🎉

2022-10-18 07:58 UTC, paulnoelcholot commented
Hello @thomasnares , 

Thanks for your PR. The issue is welle fixed and I found no regression :tada: 

 
![image](https://user-images.githubusercontent.com/112863083/196371286-55d18144-1f83-4e09-a84d-123c4388f7cd.png)

2022-10-18 07:59 UTC, paulnoelcholot approved these changes

2022-10-18 10:35 UTC, jolelievre approved these changes

2022-10-18 10:35 UTC, jolelievre commented
Thanks @thomasnares and @paulnoelcholot

2022-10-18 10:36 UTC, merged