Remove unused "override" property in class index
PrestaShop/PrestaShop pull request #30047
Opened 2022-10-18 10:30 UTC by eternoendless

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Removed useless "override" property which was always set to false. It was only read [here](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.0/classes/PrestaShopAutoload.php#L135-L136), and it was clearly related to the obsolete `_PS_HOST_MODE` [removed in 8.0](https://github.com/PrestaShop/PrestaShop/commit/5aa6204f29aa3e4ca586e32d7623f6fed82cdc1a#diff-1623042d578cba742c76ebf0f8a3931c76932f9cc394247bdcfb71a4bca63af2)
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| Related PRs       | N/A
| How to test?      | Verified by automated tests
| Possible impacts? | Nothing that I can see

2022-10-18 10:34 UTC, kpodemski approved these changes

2022-10-18 11:54 UTC, kpodemski requested changes
It looks like you can delete `normalizeDirectory` function

2022-10-18 12:53 UTC, eternoendless commented
Fixed

2022-10-18 15:10 UTC, kpodemski approved these changes

2022-10-18 20:04 UTC, matks approved these changes

2022-10-25 09:19 UTC, florine2623 approved these changes
Hello @eternoendless ,

Launched automatic tests with PHP 7.4 and 8.1.

https://github.com/florine2623/testing_pr/actions/runs/3319080775/jobs/5483785489
https://github.com/florine2623/testing_pr/actions/runs/3319079267/jobs/5483781602

It is QA ✅ 
Thanks!

2022-10-25 16:27 UTC, jolelievre commented
Thanks @eternoendless and @florine2623 

Also @FabienPapet it will probably create some conflicts with your refacto PR

2022-10-25 16:27 UTC, merged