Add install fixtures for new registration page.
PrestaShop/PrestaShop pull request #30093
Opened 2022-10-21 15:33 UTC by Hlavtox

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add missing install fixtures for new registration page. This is needed so a friendly URL route is registered on install.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/pull/27755#issuecomment-1279942207
| Related PRs       | -
| How to test?      | -
| Possible impacts? | -

cc @Caleydon

2022-10-21 15:38 UTC, kpodemski commented
I think we need it on 8.0.1, right?

2022-10-24 07:43 UTC, nicosomb approved these changes, later dismissed

2022-10-28 21:25 UTC, kpodemski requested changes
Hi @Hlavtox 

Could you rebase to 8.0.x?

2022-11-09 15:04 UTC, Hlavtox commented
@kpodemski Done ✅

2022-11-09 16:12 UTC, kpodemski approved these changes

2022-11-10 08:55 UTC, zuk3975 approved these changes

2022-11-10 10:55 UTC, AureRita commented
Hello @Hlavtox !

Could you give us a How to test to let the QA test it ? =) 

Thank you

2022-11-10 10:59 UTC, Hlavtox commented
@AureRita Updated :-)

2022-11-16 10:57 UTC, HanaRebaiQA approved these changes
Hello @Hlavtox 

I have checked this PR. This is my checked list : 

1. Check the automated tests : OK
2. Check with multistore : OK
3. Check with different languages : OK
4. Check with different browsers : OK
5. Check when delete the registration : OK


https://user-images.githubusercontent.com/92912932/202162537-58baa39b-21a7-4d87-9fdf-94c6121af4b4.mp4

So, it's QA :heavy_check_mark: 

Thank You!

2022-11-16 11:11 UTC, merged

2022-11-16 11:11 UTC, zuk3975 commented
Thanks @Hlavtox & @HanaRebaiQA