Do not build a domain from the module name
PrestaShop/PrestaShop pull request #30114
Opened 2022-10-25 15:00 UTC by atomiix

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Cherry pick of #30080
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #30076
| Related PRs       | #27422
| How to test?      | Please see #30076 & #27422
| Possible impacts? |

2022-10-25 15:02 UTC, PrestaEdit approved these changes

2022-10-25 15:20 UTC, nicosomb approved these changes

2022-10-25 19:34 UTC, yanmakouf approved these changes

2022-10-26 05:50 UTC, kpodemski approved these changes

2022-10-26 21:37 UTC, FabienPapet approved these changes

2022-10-28 08:57 UTC, boubkerbribri requested changes, later dismissed
We have an linked to php7.1 and Addons.
I don't think its linked to this PR. But CI is failing and we can't merge unless it's green.
![image](https://user-images.githubusercontent.com/48441421/198547712-945f4861-f8f6-4c21-86cb-d61f848b01f5.png)

2022-11-07 12:25 UTC, khouloudbelguith approved these changes
Hi @atomiix,

I checked this PR, it is ok :heavy_check_mark: 

-Check the original issue (https://github.com/PrestaShop/PrestaShop/issues/30076) with the same module: OK
-Check both issues (https://github.com/PrestaShop/PrestaShop/issues/27410 & https://github.com/PrestaShop/PrestaShop/issues/26549)
-Check with different module updates by adding new translations files (Arabic, Italian, Japan) : OK
-Check when the underscore is in the different positions (First position, second..., last) : OK
-Check with other natives module configuration and translations update: OK (productcomments, newslettersubscription, contact us best-selling products)
-Check the automatic tests in the translation page: OK
-Check with different translation types :

- Back Office : OK
- Font Office :OK
- Email Translations (Subject + core) : OK
- Installed modules with native modules : OK
- Other : OK

-Check with multistore (second shop) : OK
-Check with different themes (Classic, customized themes) : OK

https://user-images.githubusercontent.com/16067358/200309594-297284ac-cec2-4f2f-8e1d-269ce1998097.mp4

Thanks!

2022-11-07 12:37 UTC, jolelievre commented
Thanks @atomiix and @khouloudbelguith

2022-11-07 12:37 UTC, merged