Fix potential warning on getPosition method of Module class
PrestaShop/PrestaShop pull request #30118
Opened 2022-10-26 09:31 UTC by hugofintecture

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      |  Fix potential warning on getPosition method of Module class - see details below
| Type?             | bug fix
| Category?         | don't know
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | No ticket
| Related PRs       | N/A
| How to test?      | Use the method getPosition with an invalid & valid hooks
| Possible impacts? | I chose to return `false` in this case but we could also choose to return `-1` for example to keep the int return type.

Today, if we call the method getPosition with an unregistered hook, we get this warning:

```
Warning à la ligne 2704 du fichier /var/www/html/classes/module/Module.php
[2] Trying to access array offset on value of type bool
```

So this PR just check the result from DB.

2022-10-27 12:51 UTC, lartist commented
Hello @hugofintecture, thanks for your PR. It seems like it solve the issue you had 
`Warning à la ligne 2704 du fichier /var/www/html/classes/module/Module.php
[2] Trying to access array offset on value of type bool`

However did you check places where `getPosition` is used. Maybe we can consider new return type (bool) since until now it was only an array.

2022-10-27 12:59 UTC, hugofintecture commented
The result of getPosition was `int` not an `array`.
I've just changed it to `int|false`. 

And here's my comment about this: 

> I chose to return false in this case but we could also choose to return -1 for example to keep the int return type.

But I'm not sure I understood your comment :)

2022-10-31 18:26 UTC, lartist commented
> The result of getPosition was `int` not an `array`. I've just changed it to `int|false`.
> 
> And here's my comment about this:
> 
> > I chose to return false in this case but we could also choose to return -1 for example to keep only the `int` return type.
> 
> But I'm not sure I understood your comment :)

I was asking myself where this function where used because no matter the return type you add (false or -1 or whichever we want), this is a new value we should manage when calling this function. However I didn't see this function in PrestaShop core so we don't have anything todo. And regarding module developper I am wondering which kind of side effect this PR could have. Because now instead of warning they will have a return value which they probably don't manage as things stand.

2022-11-22 09:25 UTC, hugofintecture commented
Ok I understand thanks! In my opinion even for a module developer, it's better to have a new return value than a PHP error (a warning in this case).

2022-11-22 09:57 UTC, hugofintecture commented
PR rebased and cleaned with PHP CS-Fixer

2023-01-08 23:58 UTC, FabienPapet submitted a review, later dismissed

2023-01-10 14:39 UTC, hugofintecture commented
Rebase done again. Sorry @FabienPapet this has canceled your approve :/

2023-01-10 16:01 UTC, FabienPapet submitted a review, later dismissed

2023-01-10 16:47 UTC, Hlavtox requested changes
We can do it like this:

```
    public function getPosition($id_hook)
    {
        return (int) Db::getInstance()->getValue('
            SELECT `position`
            FROM `' . _DB_PREFIX_ . 'hook_module`
            WHERE `id_hook` = ' . (int) $id_hook . '
            AND `id_module` = ' . (int) $this->id . '
            AND `id_shop` = ' . (int) Context::getContext()->shop->id);
    }
```

2023-01-10 17:18 UTC, hugofintecture commented
I can make the change. I let you decide :)

2023-01-10 17:41 UTC, FabienPapet commented
@Hlavtox code looks better IMO because it returns 0 if no results instead of false. Can you update your code ?

2023-01-11 08:36 UTC, hugofintecture commented
@Hlavtox @FabienPapet done ;)

2023-01-11 08:37 UTC, hugofintecture commented
Just a question. A position starts at 0 or at 1? If it starts at 0 we have a problem with this new approach I think.

2023-01-11 09:07 UTC, Hlavtox approved these changes

2023-01-11 13:10 UTC, FabienPapet approved these changes

2023-01-11 14:25 UTC, florine2623 commented
ping @PrestaShop/prestashop-core-developers should be tested by dev ?

2023-01-11 15:10 UTC, FabienPapet commented
QA Team can test by editing module positions. This should be enough.

2023-01-12 09:07 UTC, MhiriFaten reviewed
Hello @hugofintecture ,

Could you please provide us more details and an example about how testing the edit of module position?
Or could you please create a dedicate issue for that ?

Thank you.

2023-01-12 20:57 UTC, kpodemski commented
@MhiriFaten you can see @FabienPapet message:

> QA Team can test by editing module positions. This should be enough.

If you can manage module positions after this change - it's ok.

2023-01-13 10:55 UTC, MhiriFaten approved these changes
Hello @hugofintecture ,

I have checked your PR and here is my checklist : 

- Editing module positions -> OK.
- Testing with multi languages -> OK.
- Automated tests -> OK.

 So it's **QA approved** :heavy_check_mark: 

Thank you!

2023-01-13 10:59 UTC, merged

2023-01-13 11:00 UTC, Hlavtox commented
Thanks @hugofintecture and the rest of the team 🏎️

2023-01-13 11:17 UTC, kpodemski commented
@Hlavtox don't forget about milestones 👍🏻