Add an isset test on id_manufacturer while getting product properties
PrestaShop/PrestaShop pull request #30194
Opened 2022-11-03 09:02 UTC by PrestaEdit

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | If the properties doesn't have this index, it will throw a notice.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no

2022-11-03 09:22 UTC, nicosomb approved these changes, later dismissed
LGTM. No need to have an opened issue?

2022-11-03 09:27 UTC, Hlavtox requested changes
`$row['manufacturer_name'] = !empty((int) $row['id_manufacturer']) ? Manufacturer::getNameById((int) $row['id_manufacturer']) : null;`

2022-11-03 10:10 UTC, mflasquin commented
> `$row['manufacturer_name'] = !empty((int) $row['id_manufacturer']) ? Manufacturer::getNameById((int) $row['id_manufacturer']) : null;`

In the commit of @PrestaEdit there is an additional test to verify if $row['id_manufacturer'] > 0. I don't know if this check is really mandatory. What do you think about that @PrestaEdit ?

2022-11-03 10:14 UTC, PrestaEdit commented
As empty() will check if the var exists or it's falsey (0, '0', it's not needed).

2022-11-03 10:15 UTC, Hlavtox commented
@mflasquin That check is not needed. `!empty` returns true only if the variable exists, is not NULL, not zero, not string zero, not empty array, empty string. 👍

2022-11-03 10:18 UTC, mflasquin commented
> As empty() will check if the var exists or it's falsey (0, '0', it's not needed).

Ok so I think you can follow @Hlavtox 's suggestion :)

2022-11-03 10:20 UTC, mflasquin reviewed
I'm ok with the updated code but I think you maybe have to indicate how to test to help the QA to validate your PR :wink:

2022-11-03 10:21 UTC, mflasquin approved these changes

2022-11-03 12:54 UTC, kpodemski approved these changes

2022-11-03 12:55 UTC, kpodemski commented
IMHO it doesn't need QA.

2022-11-03 14:10 UTC, lartist commented on classes/Product.php
> +        $row['manufacturer_name'] = !empty((int) $row['id_manufacturer']) ? Manufacturer::getNameById((int) $row['id_manufacturer']) : null;
```suggestion
        $row['manufacturer_name'] = !empty($row['id_manufacturer']) ? Manufacturer::getNameById((int) $row['id_manufacturer']) : null;
```

2022-11-06 09:36 UTC, FabienPapet approved these changes

2022-11-10 08:25 UTC, kpodemski commented
@PrestaShop/qa-team IMHO it doesn't need QA, it's a safe change to avoid potential PHP notice, please confirm :-)

2022-11-10 10:19 UTC, hibatallahAouadni commented
Hello @kpodemski 

I just ran the auto test, if it's all green we can merge it :wink: 
Here's the link: https://github.com/hibatallahAouadni/testing_pr/actions/runs/3435876124

Thanks!

2022-11-10 10:23 UTC, merged

2022-11-10 10:23 UTC, kpodemski commented
Thanks @hibatallahAouadni :)

Thanks @PrestaEdit