Mail: add PS_MAIL_SUBJECT_PREFIX to control [Foo] subject prefix
PrestaShop/PrestaShop pull request #30277
Opened 2022-11-13 16:04 UTC by rmilecki

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Mail::send() was prefixing every e-mail subject with a shop name in<br>square brackets. A lot of shop owners look for a way of disabling that<br>behaviour. Most of them probably find it redundant since there is<br>already a sender in the From field.<br><br>Add PS_MAIL_SUBJECT_PREFIX config option and allow changing it in the<br>Advanced Parameters → E-mail<br><br>Make it enabled by default to avoid changing a long-known behaviour.
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24492
| Related PRs       |
| How to test?      | Disable "Prefix subject with shop name" and verify that outgoing e-mails don't have shop name as subject prefix
| Possible impacts? | Make sure that sending e-mails works

2022-11-13 20:56 UTC, FabienPapet submitted a review, later dismissed
LGTM

2022-11-13 21:45 UTC, matks reviewed
Code is OK 👍 please just let me check quickly with @PrestaShop/product-team to confirm behavior is good 😉 (I add the required label)

2022-11-14 14:41 UTC, marsaldev approved these changes, later dismissed

2022-11-14 14:46 UTC, marsaldev commented on src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Email/EmailConfigurationType.php
> +                'label' => $this->trans('Prefix subject with shop name', 'Admin.Advparameters.Feature'),
```suggestion
                'label' => $this->trans('Enable the shop name as a prefix in the emails subject', 'Admin.Advparameters.Feature'),
```

2022-11-14 14:48 UTC, MatShir commented
LGTM 🚀

2022-11-14 15:10 UTC, MatShir commented
I have updated some wording. Quick second validation before the QA comes ? @FabienPapet @matks 🙏

2022-11-14 15:20 UTC, matks approved these changes

2022-11-14 16:00 UTC, marsaldev approved these changes

2022-11-14 22:58 UTC, yanmakouf approved these changes

2022-11-15 22:43 UTC, Hlavtox requested changes
Wouldn't the current hook be sufficent? You can do what you want easily. :-)

```php
Hook::exec('actionMailAlterMessageBeforeSend', [
  'message' => &$message,
]);
```
And use it simply by:
```
$subject = $message->getSubject();
// do whatever you want, remove the prefix if wanted, like
$subject = str_replace(
  '[' . strip_tags(Configuration::get('PS_SHOP_NAME')) . '] ', 
  '', 
  $subject);
$message->setSubject($subject);
```

2022-11-15 22:47 UTC, kpodemski commented
@Hlavtox we can tell that about many things, but eventually this option is something what merchant are asking about quite often 👍🏻

2022-11-15 23:33 UTC, FabienPapet approved these changes

2022-11-16 08:16 UTC, MhiriFaten approved these changes
Hello @rmilecki 

The issue is well fixed and the square brackets are removed :tada: 

![image](https://user-images.githubusercontent.com/111756615/201956128-9b7c3cf4-4467-43ce-8247-bba9b9bec1ca.png)

The automated test are OK :heavy_check_mark: 

Thank you !

2022-11-16 10:32 UTC, merged

2022-11-16 10:34 UTC, marsaldev commented
Thanks @rmilecki !

2022-11-16 10:37 UTC, rmilecki commented
It's great to have some tiny contribution in this project, thanks for handling my pull request.

2022-11-16 10:42 UTC, kpodemski commented
Thank you, Rafał! I hope to see more from you in the future! Keep up the good work :)

2022-12-11 23:08 UTC, Hlavtox commented
@rmilecki Hello Rafał, please don't forget to create a PR for autoupgrade https://github.com/PrestaShop/autoupgrade/blob/dev/upgrade/sql/8.1.0.sql, or it will change default behavior for upgrading users. 👍