Functional Tests : `check:step-identifiers` : Improved error message
PrestaShop/PrestaShop pull request #30299
Opened 2022-11-15 16:32 UTC by Progi1984

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | `check:step-identifiers` : Improved error message
| Type?             | improvement
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| Related PRs       | N/A
| How to test?      | N/A
| Possible impacts? | N/A

2022-11-16 10:51 UTC, nesrineabdmouleh submitted a review, later dismissed

2022-11-17 10:45 UTC, Progi1984 commented on tests/UI/tools/stepIdentifiersChecker.js
> +        .replace('.js', ''))
```suggestion
        .replace('.js', ''))
        .replace('.ts', ''))
```

2022-11-17 10:45 UTC, boubkerbribri commented on tests/UI/tools/stepIdentifiersChecker.js
> +        .replace('.js', ''))
```suggestion
        .replace('.js', ''))
        .replace('.ts', ''))
```

2022-11-25 17:14 UTC, matks approved these changes

2022-11-25 17:16 UTC, matks requested changes
You have a git conflict :(

2022-11-28 08:04 UTC, Progi1984 commented
Thanks @matks. I rebased it :)

2022-11-28 09:07 UTC, matks approved these changes

2022-11-30 08:12 UTC, SD1982 approved these changes

2022-11-30 09:44 UTC, matks commented
Thank you @Progi1984

2022-11-30 09:44 UTC, merged