Customization field multishop
PrestaShop/PrestaShop pull request #30315
Opened 2022-11-17 10:41 UTC by jolelievre

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Handle multishop for customization field in product V2, the name can be edited differently on each shop however we don't handle the `Apply to all shops` checkbox
| Type?             | new feature
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| Related PRs       | ~
| How to test?      | ~
| Possible impacts? | ~

2022-11-18 17:15 UTC, matks approved these changes, later dismissed

2022-11-18 17:15 UTC, matks commented on src/Adapter/Product/Customization/Repository/CustomizationFieldRepository.php
> +     * In which case the shopId doesn't matter e don't care about multishop content since the entity is about to be deleted.
```suggestion
     * In which case the shopId doesn't matter we don't care about multishop content since the entity is about to be deleted.
```

2022-11-21 10:16 UTC, zuk3975 commented on src/Adapter/Product/Customization/Repository/CustomizationFieldRepository.php
> +     * @return array
psalm annotation missing

2022-11-21 10:16 UTC, zuk3975 commented on src/Adapter/Product/Customization/Repository/CustomizationFieldRepository.php
> +     * @return array
```suggestion
     * @return CustomizationFIeldId[]
```

2022-11-21 10:18 UTC, zuk3975 commented on src/Adapter/Product/Customization/Update/ProductCustomizationFieldUpdater.php
> +        // fields which are not, so all those fields must be synced on all associated shop
Kind of tthe same, but I think its clearer (was abit hard to understand from first look)
```suggestion
        // The modified fields are defined as multishop, but they depend on the association with customization
        // fields which are not multishop, so all those fields must be synced between all associated shops
```

2022-11-21 11:10 UTC, zuk3975 approved these changes

2022-11-25 08:56 UTC, zuk3975 commented on src/Core/Domain/Product/Customization/Command/SetProductCustomizationFieldsCommand.php
>       * @param array $customizationFields
could you define array structure here?

2022-11-25 08:56 UTC, zuk3975 commented on src/Core/Domain/Product/Customization/CustomizationShopConstraintTrait.php
> +    protected function checkShopConstraint(ShopCOnstraint $shopConstraint): void
```suggestion
    protected function checkShopConstraint(ShopConstraint $shopConstraint): void
```

2022-11-25 08:56 UTC, zuk3975 commented on src/Core/Domain/Product/Customization/CustomizationShopConstraintTrait.php
> +    protected function checkShopConstraint(ShopCOnstraint $shopConstraint): void
:smile:

2022-11-25 08:58 UTC, zuk3975 commented on tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateCustomizationFieldsFeatureContext.php
> +    private function assertCustomizability(string $productReference, string $customizability, int $shopId)
```suggestion
    private function assertCustomizability(string $productReference, string $customizability, int $shopId): void
```

2022-11-25 08:58 UTC, zuk3975 commented on tests/Integration/Behaviour/Features/Context/Domain/Product/UpdateCustomizationFieldsFeatureContext.php
> +    private function assertCustomizationOptions(string $productReference, int $expectedCount, string $customizationType, int $shopId)
```suggestion
    private function assertCustomizationOptions(string $productReference, int $expectedCount, string $customizationType, int $shopId); void
```

2022-11-25 09:00 UTC, zuk3975 requested changes
Some minor fixes needed

2022-11-25 12:43 UTC, zuk3975 approved these changes

2022-11-25 17:15 UTC, matks approved these changes

2022-11-28 14:53 UTC, AureRita commented
Hi @jolelievre 

Thank you for your PR, I tested it and the main feature works, even the modify for all shops checkbox, as we can see here :

[Untitled_ Nov 28, 2022 2_43 PM.webm](https://user-images.githubusercontent.com/100699445/204293667-cd4b5dd0-8b64-439c-92f4-b07d82307f37.webm)

But after checking some other tab I can see that we have some issues :

 on the UI as you can see.  

![image](https://user-images.githubusercontent.com/100699445/204293789-85dda85c-60d7-41ee-82a3-1008b7f94043.png)

---------------------------------

With combination ( we didn't check the modify for all shop and the reference change for all. Morevover, when we put the price for all, that didn't change for all but this one is maybe not implemented currently ) : 

[Untitled_ Nov 28, 2022 2_55 PM.webm](https://user-images.githubusercontent.com/100699445/204295210-44065c6e-0ed9-4a19-b48b-035514c70e89.webm)

---------------------------------
With tags (when you add a tags, it should be on the two shop and it seems to be only on the shop where you add it) 

[Untitled_ Nov 28, 2022 3_32 PM.webm](https://user-images.githubusercontent.com/100699445/204303936-215814dd-e783-4039-ad10-55ff59460b9b.webm)

-----------------------------------
With visibility (when you disable the view on the catalog or in the search it seems to disabled it on all shop but when you enable, no) 

[Untitled_ Nov 28, 2022 3_48 PM.webm](https://user-images.githubusercontent.com/100699445/204307393-1e061d5a-0a2e-49da-b9bd-117c2ce5b01f.webm)

Can you say me if one of them it's correct ? 

Waiting for your feedback

2022-11-30 17:02 UTC, jolelievre commented
Thanks @AureRita 

all your feedbacks are not in the scope of this PR at all.

I can still answer them though:
- combination multidhop edition has not been implemented yet so it's bound to have some issues
- for the tags we didn't focus on it yet, but I didn't think it was needed As you said the tags are common to all shops so if you add tags on a shop it will impact all the others I don't understand you bug report though because in your video it seems like the tag is indeed in the second shop so no bug in the BO apparently Or do you mean it doesn't work on the FO when you search the tag on the second shop? If so then please open a dedicated issue for this bug
- about the visibility, the for in the BO behaves as expected at least but it seems like the FO doesn't react appropriately I'm not sure if it's a bug from the BO (which doesn't index the products properly maybe) or from the FO (and maybe it's already an existing bug, did you test with page V1) But anyway it's not related to this PR either so it deserves a dedicated issue as well

TLDR; if you didn't find bugs related to customization field then I guess this PR is validated.

2022-12-01 16:54 UTC, florine2623 approved these changes
Hello @jolelievre ,

Tested on `develop`, check the customization field in product edition in PPV2.

Tested on different configurations of multishop:
- multishop disabled 
- multishop enabled 
- multishop enabled, multiple shops in 1 group
- multishop enabled, multiple shops in multiple group (some shops configured, some not)

Checked:
- with 1 customization, multiple customizations
- type file and type text
- required or not
- on different types of product (standard, combination, pack, virtual)

**Issues found:**

When adding a file in FO that is not .gif .jpg .jpeg .jpe .png .webp, Fatal error: :x:

https://user-images.githubusercontent.com/16019289/205095346-ca0d4a4b-a763-49c2-9b92-eefad63c2ea6.mov

It is a regression on 8.0.0, it should be like this:
![image (3)](https://user-images.githubusercontent.com/16019289/205101508-21546986-24d4-4b88-9ba8-38769fe08a78.png)


Notice is displayed when non-required customization fields are saved: :x:
Issue created by @paulnoelcholot : https://github.com/PrestaShop/PrestaShop/issues/30464

https://user-images.githubusercontent.com/16019289/205096328-1ef75284-cb3f-4e68-8cb2-b8d987923fc1.mov


**Second part:**

_I have also found the following, but I am unable to reproduce them on another shop with PR with the same steps. I'll have to have a look later._

- Exception displayed in alert:
<img width="1229" alt="Screenshot 2022-12-01 at 16 29 33" src="https://user-images.githubusercontent.com/16019289/205097534-3c79898c-323f-48f9-bce8-2fb0549107b1.png">

- Click on Select shops on the top-right corner, see that the shop info is not coherent
<img width="1229" alt="Screenshot 2022-12-01 at 16 30 44" src="https://user-images.githubusercontent.com/16019289/205097899-a6bb1483-a849-41bf-8d53-3953e9d99043.png">

- Display of the popup when creating a product is not shown correctly:
<img width="1439" alt="Screenshot 2022-12-01 at 16 28 09" src="https://user-images.githubusercontent.com/16019289/205098503-87f43d65-4497-4f0e-b2fd-61d57a73a71e.png">

It should be like this:
<img width="1433" alt="Screenshot 2022-12-01 at 16 51 40" src="https://user-images.githubusercontent.com/16019289/205098572-616259fb-76ca-4e15-9d28-e2d2c00b26a3.png">

I have also found this exception on one of my product, I couldn't find the root cause of it :/

<img width="1042" alt="Screenshot 2022-12-01 at 17 12 34" src="https://user-images.githubusercontent.com/16019289/205103462-46ccc102-db83-4309-b674-5dbfb0acc083.png">

https://user-images.githubusercontent.com/16019289/205105312-f97a599f-5ad3-41e3-95c4-281b3a04b49d.mov

Error message in alert is not clear. Even after adding a title and a refresh of the page, the message is not updated

https://user-images.githubusercontent.com/16019289/205106303-4ffe2f27-f190-47cc-880c-5dd6683a17f7.mov


I think all the bugs mentioned are non-blocking or not in this scope. So I validate the PR.
Please make other PRs for the 2 bugs that are easy to reproduce. 🙏 
For the second part, I'm sorry, I will check further and let you know if I can have some clear reproducible steps.

It is QA ✅

2022-12-02 08:43 UTC, merged

2022-12-02 08:43 UTC, nicosomb commented
Thank you @jolelievre !