[Merge] 8.0.x to develop
PrestaShop/PrestaShop pull request #30333
Opened 2022-11-17 17:03 UTC by matthieu-rolland

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Merge 8.0.x to develop 
| Type?             | improvement
| Category?         | ME 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| Related PRs       | ~
| How to test?      | 
| Possible impacts? |

2022-11-17 17:40 UTC, jolelievre approved these changes, later dismissed
Thanks @matthieu-rolland

2022-11-17 17:40 UTC, jolelievre commented on src/Adapter/Product/Combination/Repository/CombinationRepository.php
> +    public function getCombinationIdsByAttributes(ProductId $productId, array $attributeIds): array
This one is not used anymore, but we can clean it later

2022-11-17 17:40 UTC, jolelievre commented on src/Core/Repository/ShopConstraintTrait.php
> +trait ShopConstraintTrait
@zuk3975 the trait I mentioned will be be available on develop once this PR is merged

2022-11-17 17:41 UTC, jolelievre commented
Automatic campaigns are running here https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/3490649561

2022-11-18 08:37 UTC, matks submitted a review, later dismissed

2022-11-18 09:02 UTC, zuk3975 commented
note build is failing

2022-11-18 14:18 UTC, jolelievre submitted a review, later dismissed

2022-11-18 14:19 UTC, jolelievre commented
Auto campaign running here https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/3497637685

2022-11-18 15:21 UTC, jolelievre commented
The failing tests in auto campaign should be fixed by this PR https://github.com/PrestaShop/PrestaShop/pull/30326
I think we should still force merge this PR or the merge PR will keep growing week after week, and as soon as the bug fix PR is merged we can do another merge PR from 8.0.x to develop

@boubkerbribri would you be ok with that? And @matks if it's accepted could you force merge it please?

2022-11-18 16:03 UTC, matks commented
> The failing tests in auto campaign should be fixed by this PR #30326 I think we should still force merge this PR or the merge PR will keep growing week after week, and as soon as the bug fix PR is merged we can do another merge PR from 8.0.x to develop
> 
> @boubkerbribri would you be ok with that? And @matks if it's accepted could you force merge it please?

OK for me if @boubkerbribri is OK about this.

> UI tests code checks / Checking doubles in steps identifiers (pull_request)
Is this OK too?

2022-11-21 09:30 UTC, NeOMakinG submitted a review, later dismissed
front part LGTM

2022-11-22 08:37 UTC, Progi1984 commented on tests/UI/campaigns/functional/BO/02_orders/03_creditSlips/02_sortAndPaginationCreditSlips.js
> +    createOrderByCustomerTest(orderByCustomerData, `baseContext_${i}`);
```suggestion
    createOrderByCustomerTest(orderByCustomerData, `${baseContext}_${i}`);
```

2022-11-22 09:53 UTC, Progi1984 commented on tests/UI/campaigns/functional/BO/02_orders/03_creditSlips/02_sortAndPaginationCreditSlips.js
> +          baseContext,
```suggestion
          `${baseContext}_${i}`,
```

2022-11-22 09:53 UTC, Progi1984 commented on tests/UI/campaigns/functional/BO/02_orders/03_creditSlips/02_sortAndPaginationCreditSlips.js
> +          baseContext,
```suggestion
          `${baseContext}_${i}`,
```

2022-11-22 09:53 UTC, Progi1984 commented on tests/UI/campaigns/functional/BO/02_orders/03_creditSlips/02_sortAndPaginationCreditSlips.js
> +          baseContext,
```suggestion
          `${baseContext}_${i}`,
```

2022-11-22 09:53 UTC, Progi1984 commented on tests/UI/campaigns/functional/BO/02_orders/03_creditSlips/02_sortAndPaginationCreditSlips.js
> +          baseContext,
```suggestion
          `${baseContext}_${i}`,
```

2022-11-22 09:53 UTC, Progi1984 commented on tests/UI/campaigns/functional/BO/02_orders/03_creditSlips/02_sortAndPaginationCreditSlips.js
> +          baseContext,
```suggestion
          `${baseContext}_${i}`,
```

2022-11-23 17:18 UTC, matks requested changes
Argh :( now this PR has conflicts

And as this PR is a merge, you can't rebase so it means the process must be restarted from scratch :(

2022-11-23 20:48 UTC, zuk3975 commented
> Argh :( now this PR has conflicts
> 
> And as this PR is a merge, you can't rebase so it means the process must be restarted from scratch :(

wow this could get so frustrating :open_mouth: 
How do you guys usually handle such merges? :thinking:

2022-11-23 21:20 UTC, matks commented
> > Argh :( now this PR has conflicts
> > And as this PR is a merge, you can't rebase so it means the process must be restarted from scratch :(
> 
> wow this could get so frustrating 😮 How do you guys usually handle such merges? 🤔 (seems like a loop)

Any PR merge PR that stays for more than 2 or 3 days is likely to have git conflicts so we try to speed up the process and merge it during a short time window

This PR could not be done fast because UI tests are failing

2022-11-24 08:57 UTC, lartist commented
@Progi1984 got rid of the problem which causes the CI failling but unfortunately conflicts had already showed up.

2022-11-24 15:53 UTC, lartist commented
This PR can be closed. I opened a new one https://github.com/PrestaShop/PrestaShop/pull/30399

2022-11-24 16:49 UTC, zuk3975 commented
closing in favour of https://github.com/PrestaShop/PrestaShop/pull/30399

2022-11-24 16:49 UTC, closed without merging