Remove 1 million cap limit in the max field for the product ID (1.7.8.x)
PrestaShop/PrestaShop pull request #30355
Opened 2022-11-19 17:03 UTC by marsaldev

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Remove the 1 million (front end) limitation to search IDs greater than 1 million
| Type?             | bug fix / improvement / new feature / refacto
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| How to test?      | Open the product catalog list and type 1000001 in the max text field. Without the PR, you cannot do it. The PR allows it.
| Possible impacts? |  no

2022-11-19 19:35 UTC, FabienPapet approved these changes

2022-11-20 14:21 UTC, mflasquin approved these changes
@marsaldev, do you know why this limit was fixed ?

2022-11-21 08:15 UTC, nicosomb approved these changes

2022-11-21 08:21 UTC, kpodemski requested changes
Hello @marsaldev 👋 

Please rebase your Pull Request into develop. It's not a security fix or regression, and with a current strategy, it should go to the next minor release.

2022-11-21 12:14 UTC, marsaldev commented
Hi @kpodemski, there is already the PR for the develop branch, I'll close this one. 😉

2022-11-21 12:14 UTC, closed without merging