Remove 1 million cap limit in the max field for the product ID
PrestaShop/PrestaShop pull request #30352
Opened 2022-11-18 15:09 UTC by marsaldev

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove the 1 million (front end) limitation to search IDs greater than 1 million
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| How to test?      | Open the product catalog page list and type 1000001 in the max text field
| Possible impacts? | no

2022-11-18 19:59 UTC, matks commented
@marsaldev if PR https://github.com/PrestaShop/PrestaShop/pull/30351 is merged inside 8.0.x ; this bugfix will be backported from 8.0.x to develop by a merge

So I think this PR is maybe not useful

2022-11-21 12:22 UTC, marsaldev commented
@matks @jolelievre 
I've closed the other PR after a discussion with Maintainers/Committers, let's keep this one as the good one. 
Thanks 😊

2022-11-21 15:15 UTC, paulnoelcholot commented
Hello @marsaldev,

I have tested the PR and this PR didn't corrige all the issues. It's not possible to insert "1000001" in Price max field and in Quantity max field.

There is also a problem with the Price min and Quantity min fields, because "1000001" becomes "1000000".

https://watch.screencastify.com/v/EyjCIlKXD6Is40fWF0cA

2022-11-21 16:51 UTC, marsaldev commented
Hi @paulnoelcholot, I've never talked about "Price" field, but product ID field 😊

2022-11-21 16:52 UTC, marsaldev commented
I've update the description, maybe it was confusing because I wrote it only in the title 😊

2022-11-22 09:54 UTC, paulnoelcholot commented
My apologies ! And thanks you :)

2022-11-22 11:38 UTC, marsaldev commented
@paulnoelcholot no worries at all! 😉

2022-11-22 14:51 UTC, lartist approved these changes

2022-11-24 15:30 UTC, mflasquin requested changes, later dismissed
Maybe you can also remove the limitation for the fields price and quantity to fix this ticket ? https://github.com/PrestaShop/PrestaShop/issues/30374

2022-11-24 15:36 UTC, marsaldev commented
@mflasquin 
No problem for me 😉 

@MatShir what do you think? Could be helpful to remove this limit for price and quantity too?

I think it's hard to find a shop that sells products for 1million euros (but maybe could happen in another value?), or to search some products that have more than 1 million stock in the warehouse 🤔

2022-12-13 11:42 UTC, marsaldev commented
@mflasquin @matks 
Can we unblock this situation? 😊

2023-01-12 07:57 UTC, kpodemski approved these changes

2023-01-12 07:57 UTC, kpodemski commented
Ping @MatShir @mflasquin - I think we could keep the original scope of the PR and move with this.

2023-01-12 08:00 UTC, MatShir commented
Let's merge at it is now ! We can make another PR for the other one. They are legit bugs to fixed

2023-01-12 13:50 UTC, paulnoelcholot commented
Hello @marsaldev,

I have tested the PR and it's OK for me ! :tada: 

Thanks!

2023-01-12 13:50 UTC, paulnoelcholot approved these changes

2023-01-12 13:55 UTC, merged

2023-01-12 13:55 UTC, kpodemski commented
thank you @marsaldev :)