Remove suffix check when applying fields class
PrestaShop/PrestaShop pull request #30503
Opened 2022-12-06 12:19 UTC by JevgenijVisockij

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | I am not sure if we are applying fixes to old admin theme, but my collegue found that class param doesn't work for password type. After taking a quick look found that for some reason theme checks for suffix and only then adds div with input group and custom classes. This PR removes this strange if.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Can be tested by creating fields options form in module, before class attribute would be useless if you don't have suffix, with this PR it's actually applied

2022-12-06 13:54 UTC, kpodemski approved these changes

2022-12-06 14:56 UTC, mflasquin approved these changes, later dismissed

2022-12-06 15:23 UTC, zuk3975 commented
I've tested it on AdminCustomerThreads controller which has password field. Seems to be alright :heavy_check_mark: 
I added "class" option in field_options:
![Screenshot from 2022-12-06 17-19-18](https://user-images.githubusercontent.com/31609858/205951446-bf8acc1e-da4a-4bc2-879b-76fd6ddfa747.png)

Result without PR :x: :
![Screenshot from 2022-12-06 17-14-09](https://user-images.githubusercontent.com/31609858/205951576-493d0117-a4e9-4bb2-90d7-bec9a71e23f0.png)

Result with PR changes :heavy_check_mark: :
![Screenshot from 2022-12-06 17-20-48](https://user-images.githubusercontent.com/31609858/205951889-b4dbb5d3-018f-4e3d-8038-cb6220506979.png)

So the only question I have before merge, is it ok to have that extra "form-control" class? It wasn't there before, but it doesn't seem to cause any trouble. Seems like @JevgenijVisockij added it just to comply with other input like "text" type.
@kpodemski @mflasquin wdyt?

2022-12-07 11:41 UTC, mflasquin commented
> I've tested it on AdminCustomerThreads controller which has password field. Seems to be alright heavy_check_mark I added "class" option in field_options: ![Screenshot from 2022-12-06 17-19-18](https://user-images.githubusercontent.com/31609858/205951446-bf8acc1e-da4a-4bc2-879b-76fd6ddfa747.png)
> 
> Result without PR x : ![Screenshot from 2022-12-06 17-14-09](https://user-images.githubusercontent.com/31609858/205951576-493d0117-a4e9-4bb2-90d7-bec9a71e23f0.png)
> 
> Result with PR changes heavy_check_mark : ![Screenshot from 2022-12-06 17-20-48](https://user-images.githubusercontent.com/31609858/205951889-b4dbb5d3-018f-4e3d-8038-cb6220506979.png)
> 
> So the only question I have before merge, is it ok to have that extra "form-control" class? It wasn't there before, but it doesn't seem to cause any trouble. Seems like @JevgenijVisockij added it just to comply with other input like "text" type. @kpodemski @mflasquin wdyt?

@zuk3975 Is the class form-control is here if you don't set an extra class ?

2022-12-07 11:57 UTC, zuk3975 commented
@mflasquin 
> Is the class form-control is here if you don't set an extra class ?
yes, as you can see here https://github.com/PrestaShop/PrestaShop/pull/30503/files#diff-b90e12704e4bf3a49b19ea07803b186e33bb03e5621dc4055bf93b071a3bc982R197, @JevgenijVisockij added the class manually. To respect the scope and lower the impact chances we should probably get rid of :thinking:

2022-12-09 11:43 UTC, kpodemski commented
@JevgenijVisockij let's remove it, just to make sure

2022-12-09 11:45 UTC, kpodemski requested changes

2022-12-09 11:45 UTC, kpodemski commented on admin-dev/themes/default/template/helpers/options/options.tpl
> +											<input class="form-control {if isset($field['class'])}{$field['class']}{/if}" type="{$field['type']}"{if isset($field['id'])} id="{$field['id']}"{/if} size="{if isset($field['size'])}{$fie
```suggestion
											<input{if !empty($field['class'])} class="{$field['class']}"{/if} type="{$field['type']}"{if isset($field['id'])} id="{$field['id']}"{/if} size="{if isset($field['size'])}{$field['size']|intval}{else}5{/if}" name="{$key}" value=""{if isset($field['autocomplete']) && !$field['autocomplete']} autocomplete="off"{/if} />
```

2022-12-14 21:52 UTC, zuk3975 commented
removed the extra class added "form-control" just to make sure and retested.
QA :heavy_check_mark:

2022-12-14 21:54 UTC, zuk3975 commented
removed the extra class added "form-control" just to make sure and retested.
QA :heavy_check_mark: 
![Screenshot from 2022-12-14 23-51-38](https://user-images.githubusercontent.com/31609858/207722959-bc6321ad-fb25-4ad9-aeae-fea92ebd437a.png)
![Screenshot from 2022-12-14 23-51-13](https://user-images.githubusercontent.com/31609858/207722967-46790bae-68db-48ed-b325-34be9ac0af5b.png)

2022-12-14 21:54 UTC, zuk3975 approved these changes

2022-12-15 08:04 UTC, FabienPapet approved these changes

2022-12-15 09:33 UTC, kpodemski approved these changes

2022-12-15 09:34 UTC, merged

2022-12-15 09:34 UTC, kpodemski commented
Thanks @JevgenijVisockij and @zuk3975 for the tests 👍