Functional tests - Add new test 'CRUD pack of products' in product page V2
PrestaShop/PrestaShop pull request #30587
Opened 2022-12-15 18:30 UTC by nesrineabdmouleh

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add new test 'CRUD pack of products' in product page V2
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| Related PRs       | no
| How to test?      | no need
| Possible impacts? | no

2022-12-19 09:18 UTC, Progi1984 approved these changes

2022-12-19 09:19 UTC, Progi1984 requested changes
@nesrineabdmouleh Need a rebase

2022-12-20 08:34 UTC, SD1982 approved these changes, later dismissed

2022-12-20 08:38 UTC, boubkerbribri submitted a review, later dismissed

2022-12-20 08:43 UTC, Progi1984 commented on tests/UI/pages/FO/product/index.ts
> +   * @param productInList {object} Product in pack list
```suggestion
   * @param productInList {number} Product in pack list
```

2022-12-20 08:43 UTC, Progi1984 commented on tests/UI/pages/FO/product/index.ts
> +  async getProductInPackList(page: Page, productInList: number = 1) {
```suggestion
  async getProductInPackList(page: Page, productInList: number = 1): Promise<{image: string, quantity: number, price: string, name: string}> {
```

2022-12-20 08:44 UTC, Progi1984 reviewed
A last feedback @nesrineabdmouleh

2022-12-20 10:14 UTC, nesrineabdmouleh commented on tests/UI/pages/FO/product/index.ts
> +  async getProductInPackList(page: Page, productInList: number = 1) {
Done thx :)

2022-12-20 10:14 UTC, nesrineabdmouleh commented on tests/UI/pages/FO/product/index.ts
> +   * @param productInList {object} Product in pack list
Done :)

2022-12-20 10:50 UTC, Progi1984 approved these changes

2022-12-20 12:19 UTC, matthieu-rolland approved these changes

2022-12-20 12:46 UTC, boubkerbribri approved these changes

2022-12-20 12:46 UTC, merged

2022-12-20 12:46 UTC, boubkerbribri commented
Thanks @nesrineabdmouleh