Update last_passwd_gen when changing admin password from BackOffice
PrestaShop/PrestaShop pull request #30596
Opened 2022-12-18 16:52 UTC by maxime-morel

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Field `last_passwd_gen` in `ps_employee` was updated only when resetting the password  from the "password lost" fonction. For security reasons, we want the field to be updated as well when changing manually the password from the Employee page in the BO.
| Type?             | bug fix / improvement
| Category?         | BO
| BC breaks?        |  no
| Deprecations?     | no
| Fixed ticket?     | #30597
| Related PRs       | -
| How to test?      | Before the PR : Go to Employee section in BO and change your password or the password of another employee. `last_passwd_gen` wasn't updated. After the PR : `last_passwd_gen` is updated
| Possible impacts? | `last_passwd_gen` is used to limit the delay between password reset with the password lost function. So updating the field will prevent the Admin to reset is password again before `PS_PASSWD_TIME_BACK`, which is expected.

2022-12-18 18:42 UTC, Hlavtox requested changes
Not sure this is correct logic-wise due to reasons explained in https://github.com/PrestaShop/PrestaShop/issues/30597#issuecomment-1356851395.

Code is fine, although it should be done for customers also, if so.

Waiting for opinion of my peers. 👍

2022-12-19 14:34 UTC, hibatallahAouadni commented
**PS: this PR should be blocked till we've got the PM approval**

2023-09-01 08:43 UTC, RosaBenouamer commented
My idea on the PR : "What about change the name of last_passwd_gen by last_passwd and add a flag precising the source of the modification. It avoid to add as many fields as there are ways to update ?"

2023-09-01 08:43 UTC, RosaBenouamer commented
@Hlavtox

2023-09-01 08:58 UTC, Hlavtox commented
@RosaBenouamer Sorry, but I don't understand the previous comment... 

But if I guess and you want to change `last_passwd_gen` to `last_passwd`, it's just unnecessary breaking change that won't help anything.

I don't agree with changing anything because of reasons stated in https://github.com/PrestaShop/PrestaShop/issues/30597#issuecomment-1356851395, everything in the core works fine IMHO.

2023-09-01 09:10 UTC, RosaBenouamer commented
My idea was to be able to trace each change of password in one field and use another field to explain the origin of this change.
@Hlavtox you're right about breaking change so perhaps better to add another field for manually changes

2024-06-10 16:28 UTC, matks commented
Hello, I just read the whole discussion. I agree with what was said above: this field `last_passwd_gen` only purpose is to check interval between resets.

Changing the password from the backoffice is another action, which is not linked. Resetting password is one thing, changing it is another.

As the PR is opened since September 2023 with no other answer, I close it. Thank you for submitting the PR, it's just we want to keep the current behavior.

2024-06-10 16:28 UTC, closed without merging