Functional Tests : Migration TS (`commonTests/FO/login` & `commonTests/FO/createShoppingCart`)
PrestaShop/PrestaShop pull request #30661
Opened 2022-12-23 13:30 UTC by Progi1984

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Functional Tests : Migration TS (`commonTests/FO/login` & `commonTests/FO/createShoppingCart`)
| Type?             | improvement
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Relative to #30263 
| Related PRs       | N/A
| How to test?      | Nightly is :green_circle: : 
| Possible impacts? | N/A

2022-12-26 08:22 UTC, cfarhani06 approved these changes, later dismissed

2022-12-26 12:15 UTC, boubkerbribri approved these changes

2022-12-26 12:16 UTC, boubkerbribri requested changes
Nighlty run is failing, should be checked

2022-12-27 16:04 UTC, boubkerbribri approved these changes

2022-12-29 07:29 UTC, Progi1984 commented
@boubkerbribri It's fixed.

2023-01-02 11:11 UTC, NeOMakinG approved these changes

2023-01-02 11:12 UTC, merged