Functional tests - Add new test 'Duplicate product V2'
PrestaShop/PrestaShop pull request #30755
Opened 2023-01-06 16:47 UTC by nesrineabdmouleh

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add new test 'Duplicate product V2'
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| Related PRs       | no
| How to test?      | no need
| Possible impacts? | no

2023-01-09 08:11 UTC, Progi1984 commented on tests/UI/campaigns/productV2/functional/07_duplicateProduct.ts
> +
```suggestion
```

2023-01-09 08:12 UTC, Progi1984 submitted a review, later dismissed
A small comment

2023-01-09 10:19 UTC, boubkerbribri approved these changes

2023-01-11 08:15 UTC, Progi1984 approved these changes, later dismissed

2023-01-11 08:20 UTC, boubkerbribri requested changes
@nesrineabdmouleh please resolve conflicts

2023-01-12 08:22 UTC, boubkerbribri approved these changes

2023-01-13 09:50 UTC, SD1982 approved these changes

2023-01-14 09:04 UTC, kpodemski approved these changes

2023-01-14 09:04 UTC, merged

2023-01-14 09:04 UTC, kpodemski commented
thx @nesrineabdmouleh :)