Functional tests - Add new test 'FO > User account > Order history > Order details > Request merchandise return'
PrestaShop/PrestaShop pull request #30817
Opened 2023-01-11 16:23 UTC by nesrineabdmouleh

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add new test 'FO > User account > Order history > Order details > Request merchandise return'
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| Related PRs       | no
| How to test?      | no need
| Possible impacts? | no

2023-01-12 08:37 UTC, boubkerbribri approved these changes, later dismissed

2023-01-13 09:46 UTC, SD1982 approved these changes, later dismissed

2023-01-16 09:22 UTC, SD1982 commented on tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderDetails/03_requestMerchandiseReturn.ts
> +      const pageTitle = await foMerchandiseReturnsPage.getPageTitle(page);
Type of `const pageTitle` is missing

2023-01-16 09:23 UTC, SD1982 commented on tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderDetails/03_requestMerchandiseReturn.ts
> +      const result = await orderDetailsPage.isOrderReturnFormVisible(page);
type is missing

2023-01-16 09:24 UTC, SD1982 commented on tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderDetails/03_requestMerchandiseReturn.ts
> +      const result = await orderDetailsPage.isOrderReturnFormVisible(page);
Type is missing

2023-01-16 09:24 UTC, SD1982 commented on tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderDetails/03_requestMerchandiseReturn.ts
> +      const pageTitle = await foMerchandiseReturnsPage.getPageTitle(page);
Type is missing here too

2023-01-16 14:43 UTC, nesrineabdmouleh commented on tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderDetails/03_requestMerchandiseReturn.ts
> +      const result = await orderDetailsPage.isOrderReturnFormVisible(page);
Done thx :+1:

2023-01-17 08:58 UTC, boubkerbribri submitted a review, later dismissed

2023-01-20 07:54 UTC, Progi1984 commented on tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderDetails/03_requestMerchandiseReturn.ts
> +import {Statuses} from '@data/demo/orderStatuses';
```suggestion
```

2023-01-20 07:54 UTC, Progi1984 commented on tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderDetails/03_requestMerchandiseReturn.ts
> +import {PaymentMethods} from '@data/demo/paymentMethods';
```suggestion
import {Statuses} from '@data/demo/orderStatuses';
import {PaymentMethods} from '@data/demo/paymentMethods';
```

2023-01-24 11:36 UTC, nesrineabdmouleh commented on tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderDetails/03_requestMerchandiseReturn.ts
> +import {Statuses} from '@data/demo/orderStatuses';
Done thx :)

2023-01-24 11:36 UTC, nesrineabdmouleh commented on tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderDetails/03_requestMerchandiseReturn.ts
> +import {PaymentMethods} from '@data/demo/paymentMethods';
Done :+1:

2023-01-24 16:00 UTC, Progi1984 requested changes
Could you remove type inference declarations ;) ?

2023-01-27 08:22 UTC, Progi1984 commented on tests/UI/campaigns/functional/FO/03_userAccount/02_orderHistory/01_orderDetails/03_requestMerchandiseReturn.ts
> +  const orderData: OrderCreator = {
Could you use a `new OrderData`, plz ?

2023-01-27 08:22 UTC, Progi1984 reviewed
@nesrineabdmouleh A last feedback and it's ok. Sorry :pray:.

2023-01-31 08:24 UTC, Progi1984 approved these changes

2023-02-01 08:36 UTC, boubkerbribri approved these changes

2023-02-01 08:36 UTC, merged

2023-02-01 08:36 UTC, boubkerbribri commented
Thanks @nesrineabdmouleh

2023-02-01 08:40 UTC, cfarhani06 approved these changes