Functional Tests : Migration TS (`@commonTests/FO/*`)
PrestaShop/PrestaShop pull request #30826
Opened 2023-01-12 09:42 UTC by Progi1984

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Functional Tests : Migration TS (`@commonTests/FO/*`)
| Type?             | improvement
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Relative to #30263 
| Related PRs       | N/A
| How to test?      | Nightly is :green_circle: : 
| Possible impacts? | N/A

2023-01-12 13:30 UTC, NeOMakinG submitted a review, later dismissed

2023-01-12 13:37 UTC, boubkerbribri approved these changes
LGTM but a question : Why exporting as default while we could export function by function so we we could import only what we need and not all file ?

2023-01-13 08:39 UTC, boubkerbribri requested changes
could you resolve conflicts ?

2023-01-13 09:44 UTC, SD1982 approved these changes

2023-01-13 13:27 UTC, NeOMakinG approved these changes

2023-01-13 14:31 UTC, boubkerbribri approved these changes

2023-01-13 14:35 UTC, merged