check if feature['feature'] is empty when saving product in BO to avoid duplicate
PrestaShop/PrestaShop pull request #30882
Opened 2023-01-16 09:08 UTC by canardgonflable

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix the duplication issue when saving a product with features without feature selected. Check #16306 for more infos and videos.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | No
| Deprecations?     | No
| How to test?      | Try to save a product with features without any feature selected in the dropdown.
| Fixed ticket?     | Fixes #16306
| Related PRs       | None
| Sponsor company   | None

Tested in 1.7.8.7.

Note : it might be useful to update the deleteFeatures() function in Product class, to delete "empty features". Because of the LEFT JOIN with the ps_feature_shop table, they do not show up and therefore are not deleted. So when saving, it keep the old ones and add the new one as well.

I can update this PR if necessary.

Also, this fix should be deploy on other version of Prestashop, especially 1.7.8.x, 1.7.7.x and older.

2023-01-19 21:14 UTC, FabienPapet commented
Hey @canardgonflable (nice username btw),  thank you for the contribution.

Code looks ok for me, but I see that you are targeting the `develop` branch which is for the next version. Can you please rebase it onto the 1.7.8.X branch ? 

I think targeting develop is not possible as this page as been migrated. And this file will be removed in the next PS Version

Unfortunatly we won't backport this fix into the 1.7.7.X version, because it is no more maintained.

2023-01-19 21:21 UTC, FabienPapet requested changes
Hey @canardgonflable (nice username btw), thank you for the contribution.

Code looks ok for me, but I see that you are targeting the develop branch which is for the next version. Can you please rebase it onto the 1.7.8.X branch ?

I think targeting develop is not possible as this page as been migrated. And this file will be removed in the next PS Version

Unfortunatly we won't backport this fix into the 1.7.7.X version, because it is no more maintained (unless for security).

2023-01-20 08:20 UTC, kpodemski approved these changes

2023-01-20 08:46 UTC, canardgonflable commented
Hello @FabienPapet ,
A created another branch, it was the easiest way :  #30968

We can close this PR.

2023-01-20 08:47 UTC, kpodemski commented
Hi @canardgonflable 

This PR is valid. We don't accept fixes on 1.7.8.x anymore. It's all good 👍🏻

2023-01-23 20:48 UTC, jolelievre approved these changes
Thanks @canardgonflable

2023-01-23 20:50 UTC, jolelievre commented
Note for QA this PR only fixes the issue on product page V1 so it can be tested and merged if validated, but the issue must be kept open so that we handle a different fix for V2

2023-01-24 08:40 UTC, zuk3975 approved these changes

2023-01-24 09:49 UTC, HanaRebaiQA reviewed
Hello @canardgonflable 

I have checked your PR. As you can see in this screen record below the expected behavior mentioned in the issue is NOK with all these cases :  

_Case 1_ : _If you have not yet selected a feature, the “pre-defined value” drop-down is disabled and the “customized value” field should be also disabled_  : **NOK**

_Case 2 : If you select a pre-defined value, the customized value should be disabled because a feature can’t have both._ : **NOK**

_Case 3 : If you start enter a customized value, the pre-defined value drop-down should be disabled because a feature can’t have both._ : **NOK**

But, this is the result that we have when adding a new feature with these data : **The feature disappear after saving it and refresh the page**
`Feature : Choose a feature > Pre-defined value : Choose a value > OR Customized value : Set a value on it `

https://user-images.githubusercontent.com/92912932/214255216-2885401c-941d-4943-9d24-7c991ab39787.mp4

Could you please check it ?

Thank You!

2023-03-31 15:06 UTC, kpodemski commented
Since we have had no news from you for more than 20 days, I'm closing this PR. Feel free to re-open it if you find the motivation to finish it. Don't hesitate to ping me if you have any questions or doubts.

2023-03-31 15:06 UTC, closed without merging