Functional tests - Refacto 'Sort, pagination and bulk delete features test'
PrestaShop/PrestaShop pull request #30891
Opened 2023-01-16 16:58 UTC by nesrineabdmouleh

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Refacto 'Sort, pagination and bulk delete features test'
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | no need
| Fixed ticket?     | no
| Related PRs       | no
| Sponsor company   | no

2023-01-19 09:19 UTC, boubkerbribri approved these changes

2023-01-19 09:19 UTC, boubkerbribri requested changes
Some conflicts to resolve here

2023-01-24 15:53 UTC, Progi1984 commented on tests/UI/commonTests/BO/catalog/features.ts
> +      const pageTitle: string = await featuresPage.getPageTitle(page);
```suggestion
      const pageTitle = await featuresPage.getPageTitle(page);
```

2023-01-24 15:54 UTC, Progi1984 commented on tests/UI/commonTests/BO/catalog/features.ts
> +      const pageTitle: string = await addFeaturePage.getPageTitle(page);
```suggestion
      const pageTitle = await addFeaturePage.getPageTitle(page);
```

2023-01-24 15:54 UTC, Progi1984 commented on tests/UI/commonTests/BO/catalog/features.ts
> +      const textResult: string = await addFeaturePage.setFeature(page, createFeatureData);
```suggestion
      const textResult = await addFeaturePage.setFeature(page, createFeatureData);
```

2023-01-24 15:54 UTC, Progi1984 commented on tests/UI/commonTests/BO/catalog/features.ts
> +      const pageTitle: string = await attributesPage.getPageTitle(page);
```suggestion
      const pageTitle = await attributesPage.getPageTitle(page);
```

2023-01-24 15:54 UTC, Progi1984 commented on tests/UI/commonTests/BO/catalog/features.ts
> +      const pageTitle: string = await featuresPage.getPageTitle(page);
```suggestion
      const pageTitle = await featuresPage.getPageTitle(page);
```

2023-01-24 15:54 UTC, Progi1984 commented on tests/UI/commonTests/BO/catalog/features.ts
> +      const numberOfFeaturesAfterFilter: number = await featuresPage.getNumberOfElementInGrid(page);
```suggestion
      const numberOfFeaturesAfterFilter = await featuresPage.getNumberOfElementInGrid(page);
```

2023-01-24 15:55 UTC, Progi1984 commented on tests/UI/commonTests/BO/catalog/features.ts
> +      const deleteTextResult: string = await featuresPage.bulkDeleteFeatures(page);
```suggestion
      const deleteTextResult = await featuresPage.bulkDeleteFeatures(page);
```

2023-01-24 15:55 UTC, Progi1984 commented on tests/UI/commonTests/BO/catalog/features.ts
> +      const numberOfFeaturesAfterDelete: number = await featuresPage.resetAndGetNumberOfLines(page);
```suggestion
      const numberOfFeaturesAfterDelete = await featuresPage.resetAndGetNumberOfLines(page);
```

2023-01-24 15:55 UTC, Progi1984 reviewed
Some feedbacks

2023-01-27 15:44 UTC, nesrineabdmouleh commented on tests/UI/commonTests/BO/catalog/features.ts
> +      const numberOfFeaturesAfterDelete: number = await featuresPage.resetAndGetNumberOfLines(page);
Done thx :+1:

2023-01-31 08:24 UTC, Progi1984 approved these changes

2023-02-01 08:37 UTC, boubkerbribri approved these changes

2023-02-01 08:38 UTC, merged

2023-02-01 08:38 UTC, boubkerbribri commented
Thanks @nesrineabdmouleh