[wip] Remove invalid CartRules in front office
PrestaShop/PrestaShop pull request #30905
Opened 2023-01-17 09:46 UTC by kpodemski

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | follow issue
| Fixed ticket?     | Fixes #https://github.com/PrestaShop/PrestaShop/issues/19393
| Related PRs       | n/a
| Sponsor company   | PrestaShop SA

2023-01-17 15:59 UTC, zuk3975 approved these changes, later dismissed

2023-01-23 20:54 UTC, FabienPapet submitted a review, later dismissed

2023-01-24 13:22 UTC, MhiriFaten reviewed
Hello @kpodemski ,

I checked your PR and noticed that we can't apply the discount anymore!

**Apply a Percent discount** :x: 

[Untitled_ Jan 24, 2023 11_50 AM.webm](https://user-images.githubusercontent.com/111756615/214299175-3c96b93b-b58c-46f0-bb75-9037ea277242.webm)

**Apply an Amount discount** :x: 

[Untitled_ Jan 24, 2023 2_08 PM.webm](https://user-images.githubusercontent.com/111756615/214299143-05c28994-1d89-4db9-b1ae-f60b123f034c.webm)

Could you check it please?
waiting for your feedback.

Thank you !

2023-01-27 12:58 UTC, FabienPapet requested changes

2023-01-27 12:58 UTC, FabienPapet commented on controllers/front/CartController.php
> +        // CartRule::autoRemoveFromCart();
Useless change

2023-01-27 12:58 UTC, FabienPapet commented on classes/CartRule.php
> +            // if (!empty($errors)) {
Useless change

2023-01-27 12:58 UTC, FabienPapet commented on classes/CartRule.php
> +            if (!$cart_rule['obj']->active) {
useless checks

2023-01-27 12:58 UTC, FabienPapet commented on classes/CartRule.php
> +            if (strtotime($cart_rule['obj']->date_from) > time()) {
use the same `time()`  in all checks (maybe add this as a parameter)

2023-01-27 14:05 UTC, FabienPapet approved these changes, later dismissed

2023-01-27 14:11 UTC, Hlavtox approved these changes, later dismissed

2023-01-30 08:41 UTC, MhiriFaten reviewed
Hello @kpodemski ,

I have rechecked your PR and I noticed that the issue still exists.

I added two cart rules,
the 1st is named **test rule 1** which has as apply discount action '100% discount for cheapest product'
and the 2nd is called **test rule 2** which allows a reduction of 30 Eur of the total amount.

When I activate one of the two cart rules, the reduced amount is displayed but when I deactivate it amount remains reduced.

[Untitled_ Jan 30, 2023 9_06 AM.webm](https://user-images.githubusercontent.com/111756615/215424038-27b4bcf3-a450-44ee-b52b-6d1a4cf62791.webm)

When I activate one of the two cart rules, the amount is reduced by both of them. 

[Untitled_ Jan 30, 2023 9_08 AM.webm](https://user-images.githubusercontent.com/111756615/215424454-9cf24173-ccaf-41be-92e8-1a622432503b.webm)

Could you recheck it please?

2023-01-30 10:09 UTC, zuk3975 approved these changes, later dismissed

2023-01-30 10:18 UTC, Hlavtox approved these changes, later dismissed

2023-01-30 10:56 UTC, MhiriFaten reviewed
Hello @kpodemski ,

The issue still exists! 

[Untitled_ Jan 30, 2023 11_37 AM (1).webm](https://user-images.githubusercontent.com/111756615/215458403-ab52d6e7-9f20-44f2-bc03-f693a5ffa1a6.webm)

2023-01-30 13:15 UTC, Hlavtox approved these changes

2023-02-02 08:42 UTC, Daaaaad commented
@Hlavtox @kpodemski Any news about this? Could I use this patch in production on PS 1.7.8.7? 
Regards, David.

2023-06-08 08:10 UTC, idnovate commented
It would be great if this PR could be merged :)

2023-06-08 09:10 UTC, kpodemski commented
there are some troubles with behat tests that I have to solve first 🙄

2023-10-05 12:16 UTC, audebms commented on classes/CartRule.php
Why add checks in "autoRemoveFromCart" instead of "checkvalidity" method?
"checkvalidy" being dedicated to check a cart rule validity.

2023-11-02 13:56 UTC, Daaaaad commented
@kpodemski Do you have fresh news? I have multiple customers struggling with expired vouchers being used 👻

2024-02-25 19:55 UTC, closed without merging

2024-02-26 10:04 UTC, AudeC48 commented
Can you give a fix?

2024-02-26 10:10 UTC, kpodemski commented
@Daaaaad @AudeC48 there will be a new PR fixing this, we need to introduce a new method which will perform extra checks only in front office of PrestaShop, I'll let you guys know once it's ready