Add index on ps_orders.'invoice_date'
PrestaShop/PrestaShop pull request #30949
Opened 2023-01-19 11:09 UTC by AdrienPlx

| Branch?           |  8.0.x
| Description?      |  On AdminStatsController there is a request (BestCategory) taking huge time to execute (14s on my shop) when you have a consequent catalog. This request is executed in getKpi method in Category admin controller (ajax methods).  This index on ps_orders.'invoice_date' reduce this waiting time from 14s to 0s.
| Type?             | improvement
| Category?         | BO
| How to test?      | Go to categories listing page in BO and analyse network timing on this request : index.php?controller=AdminStats&ajax=1&action=getKpi&kpi=top_category. It will be significant if you have a shop with a lot of categories, orders and products. Add the index on ps_orders.'invoice_date' and see the difference 👍

2023-01-20 09:47 UTC, matks requested changes

2023-01-20 09:47 UTC, matks commented on install-dev/data/db_structure.sql
>    INDEX `date_add`(`date_add`)
Hi @AdrienPlx it's a nice idea but I think you forgort to modify above line to add the missing comma

2023-01-20 11:20 UTC, PululuK approved these changes

2023-01-22 14:54 UTC, kpodemski requested changes
Hello @AdrienPlx 

This should go to the `develop` branch. We'd also need an `autoupgrade` PR, so the change is available not only for the new installation but also for upgrades.

2023-02-06 10:41 UTC, AdrienPlx commented
I created pull request on develop branch : https://github.com/PrestaShop/PrestaShop/pull/31218

2023-02-06 14:24 UTC, closed without merging