Functional tests - Add new test 'Check notifications in BO'
PrestaShop/PrestaShop pull request #31011
Opened 2023-01-24 10:32 UTC by nesrineabdmouleh

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add new test 'Check notifications in BO'
| Type?             | brefacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | no
| Fixed ticket?     | no
| Related PRs       | no
| Sponsor company   | no

2023-01-24 10:40 UTC, Progi1984 commented on tests/UI/campaigns/functional/BO/15_header/08_notifications.ts
> +  const orderByCustomerData: Order = {
```suggestion
  const orderByCustomerData: OrderData = new OrderData({
```

2023-01-24 10:41 UTC, Progi1984 commented on tests/UI/campaigns/functional/BO/15_header/08_notifications.ts
> +    address: addressData,
I don't see where it is used

2023-01-24 10:41 UTC, Progi1984 requested changes
Some feedbacks

2023-01-24 10:59 UTC, nesrineabdmouleh commented on tests/UI/campaigns/functional/BO/15_header/08_notifications.ts
> +    address: addressData,
Thank you @Progi1984 :)
Done !
Yes I fixed the conflicting files after your modifications !

2023-01-24 15:38 UTC, Progi1984 approved these changes

2023-01-25 08:47 UTC, boubkerbribri approved these changes

2023-01-26 08:22 UTC, merged

2023-01-26 08:22 UTC, nicosomb commented
Thank you @nesrineabdmouleh !