Change limit of filed value on ps_customized_data so that it can accepts more than 255 characters
PrestaShop/PrestaShop pull request #31109
Opened 2023-01-30 16:25 UTC by lartist

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Change limit of filed value on ps_customized_data so that it can accepts more than 255 characters
| Type?             | new feature
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | https://github.com/PrestaShop/PrestaShop/issues/27579
| Fixed ticket?     | Fixes #27579
| Related PRs       | 
| Sponsor company   |

2023-01-30 20:31 UTC, mflasquin approved these changes, later dismissed

2023-01-30 21:22 UTC, FabienPapet submitted a review, later dismissed

2023-01-31 09:26 UTC, jolelievre approved these changes, later dismissed
Thanks @lartist

2023-01-31 09:28 UTC, jolelievre commented
Since your PR also depends on an update of the classic theme I think we need to explain how to use the proper branch to fully test this feature, by manually modifying the composer.json file.

2023-01-31 11:05 UTC, Progi1984 commented
It's a BC : https://github.com/PrestaShop/ADR/blob/master/0017-backward-compatibility-promise.md#database-structure

![image](https://user-images.githubusercontent.com/1533248/215743417-7a745041-8cd2-478c-869c-18a8f2f82f1c.png)

2023-01-31 14:41 UTC, jolelievre approved these changes, later dismissed

2023-01-31 14:43 UTC, jolelievre commented
@Progi1984 yep the PR was modified to keep the same type for the column, it's only been extended/increased so it's not a BC break anymore as it's the same as changing the column constraint which is accepted in the backward policy

2023-01-31 14:48 UTC, zuk3975 submitted a review, later dismissed

2023-01-31 14:51 UTC, Progi1984 commented
@jolelievre Totally agree ;)

2023-01-31 14:55 UTC, nicosomb reviewed
Do we need to update `autoupgrade` module?

2023-01-31 15:17 UTC, lartist commented
> Do we need to update `autoupgrade` module?

https://github.com/PrestaShop/autoupgrade/pull/556

2023-01-31 15:31 UTC, djoelleuch reviewed
Hello @lartist  ,
we can't check your PR because there is some checks were not successful .
![image](https://user-images.githubusercontent.com/115152460/215803762-e2f248f4-cbee-43e6-ad1f-06e9faf6e2ff.png)

Could you please resolve the problem .

Thank you !

2023-01-31 15:48 UTC, jolelievre commented
Hi @djoelleuch

it was just a random bug from the CI, I restarted it but it's green on all other PHP versions no reason that the last one should fail. It's under progress here https://github.com/PrestaShop/PrestaShop/actions/runs/4055061883/jobs/6979277814

2023-01-31 15:56 UTC, lartist commented
> Hello @lartist , we can't check your PR because there is some checks were not successful . ![image](https://user-images.githubusercontent.com/115152460/215803762-e2f248f4-cbee-43e6-ad1f-06e9faf6e2ff.png)
> 
> Could you please resolve the problem .
> 
> Thank you !

hi @djoelleuch I rerun it and all is green (sometimes random failures occur.

2023-01-31 16:57 UTC, nicosomb submitted a review, later dismissed

2023-02-01 12:51 UTC, paulnoelcholot commented
Hello @lartist,

I have tested your PR and I found somes bugs :

2023-02-01 12:54 UTC, paulnoelcholot commented
Hello @lartist,

I have tested your PR and I found some bugs : 

On FO product page : 
![image](https://user-images.githubusercontent.com/112863083/216048242-dd7c5148-6e97-43f7-95e7-060f3c050d10.png)

On FO checkout page : 
![image](https://user-images.githubusercontent.com/112863083/216048301-d92aa4f7-b7fe-47e0-80c4-ffc65ff1dd75.png)

On BO order : 
![image](https://user-images.githubusercontent.com/112863083/216048375-c321311c-1625-47de-b096-ab816cdd09c5.png)
if the text has spaces

On BO order : 
![image](https://user-images.githubusercontent.com/112863083/216048627-f3ac08d3-56c2-4e59-8223-336000abbe3f.png)
if the text hasn't spaces

2023-02-02 09:34 UTC, paulnoelcholot commented
Hello @lartist,

My apologies, after a second test, the problem was related to my environment.
Everything is ok for me :tada: 

Thanks!

2023-02-02 09:34 UTC, paulnoelcholot approved these changes

2023-02-02 10:08 UTC, jolelievre approved these changes

2023-02-02 10:09 UTC, jolelievre requested changes
Hi @lartist 

can you please rebase this one based on 8.1.x and change the target of the PR?

Thanks

2023-02-02 11:20 UTC, jolelievre approved these changes
Thanks @lartist 

This will be a new feature for v9

2023-02-02 11:20 UTC, jolelievre commented
Thanks @lartist

2023-02-02 11:20 UTC, merged