Fix a typo error in xml hook list
PrestaShop/PrestaShop pull request #31269
Opened 2023-02-08 08:15 UTC by thomasnares

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 8.1.x
| Description?      | Fixed a typo in the xml hook list. ps_contactinfo, hummingbird and classic_theme does not have the typo error. 
| Type?             | bug fix

2023-02-08 15:24 UTC, FabienPapet submitted a review, later dismissed

2023-02-09 10:43 UTC, kpodemski requested changes
Hi @thomasnares 

If this hook was introduced in 8.1, you should target the 8.1.x branch. Could you change the base branch and rebase if needed?

2023-02-14 17:02 UTC, kpodemski commented
Hi @thomasnares 

Could you rebase on 8.1.x? :)

2023-02-15 08:13 UTC, thomasnares commented
https://github.com/PrestaShop/PrestaShop/pull/31367

Reopened targeted on 8.1.x

2023-02-15 08:13 UTC, closed without merging