Fix blank schema with null values
PrestaShop/PrestaShop pull request #31272
Opened 2023-02-08 08:55 UTC by TomLorenzi

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | While trying to fetch a blank schema for products reference, you'll get a 500 error while trying to fill null association as example
| Type?             | bug fix
| Category?         | WS
| BC breaks?        | still don't know what it means sorry
| Deprecations?     | no
| How to test?      | Try to fetch `https://example.prestashop.com/api/products?schema=blank` route to get products blank schema
| Fixed ticket?     | Fixes #31263 
| Related PRs       | [If theme, autoupgrade or other module change is needed to make this change work, provide a link to related PRs here.](https://github.com/PrestaShop/PrestaShop/commit/26b6234c75e9fec8c4df8fb4ab11f826fc9f4429) for develop branch
| Sponsor company   | None

2023-02-08 08:58 UTC, kpodemski commented
Hello @TomLorenzi 

The fix is part of PrestaShop 8.0.1, already available:
https://github.com/PrestaShop/PrestaShop/releases/tag/8.0.1

2023-02-08 10:11 UTC, TomLorenzi commented
> Hello @TomLorenzi
> 
> The fix is part of PrestaShop 8.0.1, already available: https://github.com/PrestaShop/PrestaShop/releases/tag/8.0.1

Hi @kpodemski that's what I wrote here : https://github.com/PrestaShop/PrestaShop/issues/31263
Unfortunatly when you want to setup prestashop the download link give you a 1.7.8.8 ZIP containing that bug, it is planned to be fixed in this version as it still get updated ? Am I missing something ?

2023-02-09 10:36 UTC, kpodemski commented
Hi @TomLorenzi 

PrestaShop 1.7.8 is no longer supported in normal fixes or improvements. It is in the extended support phase, where only security or critical fixes are allowed.

You can download PrestaShop 8.0.1 from this link:
https://github.com/PrestaShop/PrestaShop/releases/tag/8.0.1

When will PrestaShop.com have its own PrestaShop 8 version available to download? That, I don't know.

2023-02-09 10:42 UTC, kpodemski commented
I'm reopening PR, as I'm not entirely sure if we're going to treat it as a critical bug or not.

2023-02-27 10:41 UTC, TomLorenzi commented
@kpodemski any update on this ? I can't use version 8.0 because there's too much bug currently and here I need to use this route, I think i will hardcode my blank schema but I don't really like that idea tbh

2023-03-03 20:42 UTC, matks requested changes
I am sorry guys :( but as the bug https://github.com/PrestaShop/PrestaShop/issues/26559 which describes this was flagged as `minor` I don't think this bug meets the requirements for 1.7.8.x bugfix.

1.7.8.x branch is now under extended support (https://build.prestashop-project.org/news/2023/178-in-extended-support-phase/): only critical bugs or security issues are fixed on it.

I understand it can be frustrating but it is actually very expensive to deploy a new 1.7.8.x release so we do it only for very important matters

2023-03-06 15:05 UTC, TomLorenzi commented
@matks 

Should I/you close that PR then ?

2023-03-07 08:46 UTC, closed without merging