Update sources.html.twig
PrestaShop/PrestaShop pull request #31303
Opened 2023-02-10 11:07 UTC by uguranium

On backend sources, it looks not good bottom of the page. Because the header takes over half of the page (col-md-6) and the other half is for sources. I think you can use card-header and card-body classes. If it's possible also can you add scroll for card-body for sources ( something like: overflow: auto; max-height: 40vh;). If the source is long then the admin order page is so long.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 8.1.x / 8.0.x
| Description?      |  Backend order sources are looks really bad. Header is taking over half of the page.
| Type?             | bug fix 
| Category?         |  BO
| BC breaks?        |  no
| Deprecations?     | no
| How to test?      | Please look the backend admin any order view sources tab before and after this changes
| Fixed ticket?     | I don't have ticket
| Related PRs       | No
| Sponsor company   | 4eck-Media

2023-02-14 09:30 UTC, Hlavtox requested changes
Wrong syntax, you can't have `col-md-6` without a `row`

2023-03-30 08:34 UTC, kpodemski commented
Hi @uguranium 

Could you fix what Hlavtox suggested?

2023-03-30 09:25 UTC, uguranium reviewed
Removed div with col-md-6 class

2023-03-30 09:26 UTC, uguranium commented
> Hi @uguranium
> 
> Could you fix what Hlavtox suggested?

Yes removed unneeded div. Please can you look my code?
Thank you.

2023-05-26 06:50 UTC, kpodemski approved these changes

2023-10-19 14:33 UTC, tleon approved these changes

2023-11-07 15:20 UTC, nicosomb commented
@uguranium could you please targer `8.1.x` branch?

2026-02-10 12:53 UTC, closed without merging