add license refacto
PrestaShop/PrestaShop pull request #31394
Opened 2023-02-16 07:24 UTC by lartist

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?             | new feature
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      |
| Fixed ticket?     | Fixes #31290
| Related PRs       |
| Sponsor company   |

2023-02-23 10:08 UTC, nicosomb commented on src/PrestaShopBundle/Command/AddLicensesCommand.php
> +                // versioning folders
Maybe it can be useful / cleaner to put this list in a config section (yml or whatever).

2023-02-23 16:00 UTC, lartist commented on src/PrestaShopBundle/Command/AddLicensesCommand.php
> +                // versioning folders
I had the same idea. This and the old license to remove 👍

2023-02-23 17:04 UTC, FabienPapet commented on src/PrestaShopBundle/Command/AddLicensesCommand.php
> +            ->in(_PS_ROOT_DIR_)
use DI for this :)

2023-02-23 17:05 UTC, FabienPapet commented on src/PrestaShopBundle/Resources/config/services_dev/bundle/command.yml
> +      - 'console.command'
```suggestion
    autoconfigure: true
```

2023-02-28 10:03 UTC, FabienPapet requested changes
This PR is nice and well tested 👍 , but I think this is the right place to merge it. We need to have a discussion about why we need it here, and why it should not be inside a separate tool.

- Do we really want to keep BC Promise on this ? 
- Isn't this pr just a licence fixer ? 
- Should we use this code inside modules for example ?

2023-02-28 10:03 UTC, FabienPapet commented on src/PrestaShopBundle/License/LicenseBuilder/AFLLicenseStrategy.php
> +namespace PrestaShopBundle\License\LicenseBuilder;
All these licence builders should not be placed inside the PrestaShop bundle Imo, because they are not related to Symfony.

2023-02-28 10:03 UTC, FabienPapet commented on tests/Unit/PrestaShopBundle/License/Specification/LicenseSpecificationInterface.php
> +interface LicenseSpecificationInterface
I think this is over engineered as we don't need an interface in test.

2023-02-28 10:03 UTC, FabienPapet commented on src/PrestaShopBundle/Resources/config/services_dev/bundle/licenses.yml
> +  PrestaShopBundle\License\LicenseAdder\CSSLicenseAdder: ~
Can you read the whole directory instead of creating the services one by one ?

2023-02-28 10:03 UTC, FabienPapet commented on src/PrestaShopBundle/Resources/config/services_dev/bundle/licenses.yml
> +    arguments:
use tagged services here

2023-02-28 10:03 UTC, FabienPapet commented on src/PrestaShopBundle/License/LicenseBuilder/LicenseStrategyInterface.php
> +interface LicenseStrategyInterface
Interface should be placed in core.

2023-02-28 10:03 UTC, FabienPapet commented on src/PrestaShopBundle/License/AddLicensesLoggerInterface.php
> +interface AddLicensesLoggerInterface
you can use Psr Logger instead of creating a new interface as I don't think this add any value. See my comment below

2023-02-28 10:03 UTC, FabienPapet commented on src/PrestaShopBundle/License/LicenseAdder/LicenseAdderInterface.php
> +    public function addLicenceToContent(LicenseStrategyInterface $licenseStrategy, string $contents): string;
```suggestion
    public function addLicenseToContent(LicenseStrategyInterface $licenseStrategy, string $contents): string;
```

2023-02-28 10:03 UTC, FabienPapet commented on src/PrestaShopBundle/License/LicenseAdder/LicenseAdderInterface.php
> +    public function removeLicencesNotAtTheBeginning(LicenseStrategyInterface $licenseStrategy, string $contents): string;
```suggestion
    public function removeLicensesNotAtTheBeginning(LicenseStrategyInterface $licenseStrategy, string $contents): string;
```

2023-02-28 10:03 UTC, FabienPapet commented on src/PrestaShopBundle/License/AddLicensesInterface.php
> +interface AddLicensesInterface
I'm not sure about this interface :
 
- It has a symfony dependency, which is weird IMO.
- It is located inside the PrestaShop Bundle, and has nothing to to here I think.

2023-02-28 10:03 UTC, FabienPapet commented on src/PrestaShopBundle/License/SymfonyIOAddLicensesLogger.php
> +class SymfonyIOAddLicensesLogger implements AddLicensesLoggerInterface
Maybe this should be merged with the Command itself, I'm not sure having a interface for something like IO is worth it, it may be over complicated things.

2023-03-01 08:39 UTC, lartist commented
Hi @FabienPapet, plz note that this PR is in draft. I think it's better I finish it first before discussing about improvement as things may be changed. :) If you want to suggest some things during draft developpment I would be glad to discuss with you in private 👍

2023-03-01 08:52 UTC, Quetzacoalt91 commented
> We need to have a discussion about why we need it here, and why it should not be inside a separate tool.

I have the same feedback. Modules & themes developers have the similar need before deploying a new version, and having this feature is useful for them. That's why we exported the first version of the core feature in https://github.com/PrestaShopCorp/header-stamp, and since that day @matks even added the dry-run mode in it (https://github.com/PrestaShopCorp/header-stamp/pull/14). Would it be interesting to switch on it?

2023-03-01 09:01 UTC, matks commented
From what I remember, unfortunately the license header stamp tool of https://github.com/PrestaShopCorp/header-stamp was not as capable for the license header stamp tool we have in the Core. There were some usecases https://github.com/PrestaShopCorp/header-stamp could not handle for the Core.

So a little work is needed to achieve the same level of capability between the two 😉

2023-03-16 12:08 UTC, closed without merging

2023-03-16 12:08 UTC, lartist commented
Closed in favour of using https://github.com/PrestaShopCorp/header-stamp/tree/master/bin that already implements dry-run