Failing ci
PrestaShop/PrestaShop pull request #31613
Opened 2023-03-02 19:30 UTC by jolelievre

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 8.1.x / 8.0.x / 1.7.8.x
| Description?      | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?             | bug fix / improvement / new feature / refacto
| Category?         | FO / BO / CO / IN / WS / TE / LO / ME / PM
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| How to test?      | Indicate how to verify that this change works as expected.
| Fixed ticket?     | Fixes #{issue number here}, Fixes #{another issue number here}
| Related PRs       | If theme, autoupgrade or other module change is needed to make this change work, provide a link to related PRs here.
| Sponsor company   | Your company or customer's name goes here (if applicable).

2023-03-02 19:44 UTC, kpodemski approved these changes

2023-03-02 20:05 UTC, Hlavtox approved these changes

2023-03-02 20:17 UTC, Hlavtox commented
@jolelievre Unfortunately, your CI is failing, you need to fix your PR. :(

2023-03-03 07:52 UTC, nicosomb requested changes
What is the purpose of this PR?

2023-03-08 18:26 UTC, closed without merging

2023-03-08 18:27 UTC, jolelievre commented
The purpose WAS to make the CI fail to check if it was correctly blocked