Add admin tabs hook
PrestaShop/PrestaShop pull request #31691
Opened 2023-03-09 08:15 UTC by cvng

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Hooks: Allow customizing the admin tabs for user menu
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | You can test it using `ps_qualityassurance` module, all the details available below
| Fixed ticket?     | N/A
| Related PRs       | N/A
| Sponsor company   | @PrestaShopCorp

1. Register the `adminTabs` hook and assign the `tabs` param:

```php
public function hookAdminTabs(array &$params): void
{
    array_pop($params['tabs']);
    array_pop($params['tabs']);
    array_pop($params['tabs']);
    array_pop($params['tabs']);
}
```

2. In the back-office, you should see only the `BIENVENUE` section

2023-03-09 08:41 UTC, matks approved these changes, later dismissed

2023-03-09 08:48 UTC, FabienPapet commented on classes/controller/AdminController.php
> +    public function getTabs($parentId = 0, $level = 0)
why is this needed ?

2023-03-09 08:54 UTC, Hlavtox approved these changes, later dismissed
Cool! Finally we can hide some things we don't use at all. 🚀

Please, create a PR for autoupgrade module and put a link to PR description. :-) (We already have a few blockers from people not responding.)

2023-03-09 08:58 UTC, kpodemski requested changes
Let's follow the naming from other places. You also need to create a PR against `autoupgrade` module, as @Hlavtox mentioned. Example: https://github.com/PrestaShop/autoupgrade/pull/564/files

2023-03-09 08:58 UTC, kpodemski commented on classes/controller/AdminController.php
> +        Hook::exec('adminTabs', ['tabs' => &$tabs], null, true);
```suggestion
        Hook::exec('actionAdminMenuTabsModifier', ['tabs' => &$tabs], null, true);
```

2023-03-09 08:58 UTC, kpodemski commented on install-dev/data/xml/hook.xml
> +      <name>adminTabs</name>
```suggestion
      <name>actionAdminMenuTabsModifier</name>
```

2023-03-09 08:58 UTC, kpodemski commented on install-dev/data/xml/hook.xml
> +      <title>Modify admin tabs</title>
```suggestion
      <title>Modify back office menu tabs</title>
```

2023-03-09 08:58 UTC, kpodemski commented on install-dev/data/xml/hook.xml
> +      <description>This hook allows to modify admin tabs which is about to be used in template for user menu</description>
```suggestion
      <description>This hook allows modifying back office menu tabs</description>
```

2023-03-09 10:01 UTC, jolelievre submitted a review, later dismissed
Thanks @cvng 

some legitimate improvement regarding the naming have been proposed. Also, you shouldn't change the visibility of the `getTabs` method in AdminController.

2023-03-09 10:01 UTC, jolelievre commented on classes/controller/AdminController.php
> +    public function getTabs($parentId = 0, $level = 0)
You should not change the visibility of this method indeed, that's why we introduce this hook

2023-03-09 11:25 UTC, kpodemski commented on classes/controller/AdminController.php
> +    public function getTabs($parentId = 0, $level = 0)
@cvng you forgot about this one :)

2023-03-09 12:10 UTC, kpodemski approved these changes

2023-03-09 12:11 UTC, cvng commented on classes/controller/AdminController.php
> +    public function getTabs($parentId = 0, $level = 0)
Sorry for the delay, we was discussing for a workaround with @jolelievre, revert done in 55679918e1135cc00d83019fa7445f9dfb2c6b30

2023-03-09 12:14 UTC, cvng commented
> Thanks @cvng
> 
> some legitimate improvement regarding the naming have been proposed. Also, you shouldn't change the visibility of the `getTabs` method in AdminController.

Thanks for the feedback! Naming and revert done in 55679918e1135cc00d83019fa7445f9dfb2c6b30

2023-03-09 12:25 UTC, Hlavtox approved these changes

2023-03-12 12:14 UTC, PrestaEdit commented
8.1 ? It's not in feature-freeze, right now ? 🤔

2023-03-12 13:52 UTC, FabienPapet commented
@PrestaEdit is right, this should target 9.0

2023-03-12 13:54 UTC, kpodemski commented
@FabienPapet no need, it was agreed to have it in 8.1

2023-03-12 13:57 UTC, Progi1984 commented
@kpodemski Isn't a Feature Freeze ? So everyone can add improvements ?

2023-03-12 14:03 UTC, kpodemski commented
@Progi1984 it's not like every change can be accepted, but the team of maintainers and the product team was asked for a green light and it was given

2023-03-13 21:09 UTC, matks approved these changes

2023-03-15 13:37 UTC, MhiriFaten reviewed
Hello @cvng ,

I have checked your PR and I noticed that after adding the hook, an error appeared at the top of the page and all the menu entries are visible.


![image](https://user-images.githubusercontent.com/111756615/225322979-5f451672-01d5-4298-81cb-02217defa461.png)


[Untitled_ Mar 15, 2023 2_35 PM.webm](https://user-images.githubusercontent.com/111756615/225324503-04976de9-7736-4cc3-9c5b-dca06c69f7df.webm)

Could you check it please?
Thank you :smile:

2023-03-15 13:43 UTC, kpodemski commented
Hi @MhiriFaten 

You should only use:

```
array_pop($params['tabs']);
array_pop($params['tabs']);
array_pop($params['tabs']);
array_pop($params['tabs']);
```

inside the quality assurance module. It runs inside the hook implementation, you can not redeclare a function inside a function like this.

2023-03-15 14:30 UTC, MhiriFaten commented
done :heavy_check_mark: ! Thanks @kpodemski 

> Hi @MhiriFaten
> 
> You should only use:
> 
> ```
> array_pop($params['tabs']);
> array_pop($params['tabs']);
> array_pop($params['tabs']);
> array_pop($params['tabs']);
> ```
> 
> inside the quality assurance module. It runs inside the hook implementation, you can not redeclare a function inside a function like this.

2023-03-15 14:30 UTC, MhiriFaten approved these changes
Hello @cvng ,

LGTM :heavy_check_mark: 
Thank you !

2023-03-15 15:32 UTC, merged

2023-03-15 15:33 UTC, nicosomb commented
Thank you @cvng !

2023-03-15 15:49 UTC, okom3pom commented
Hello, 

This modification without issue will cause a problem for the changelog can you assign an issue to this PR

2023-03-15 19:57 UTC, Hlavtox commented
@kpodemski Adding label, remove when the related PR is merged