Allow to override configuration with .env file or env variable
PrestaShop/PrestaShop pull request #31853
Opened 2023-03-20 15:51 UTC by mflasquin

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Allow to override configuration with .env file or env variable (https://devdocs.prestashop-project.org/8/development/components/configuration/#retrieve-configuration-data)
| Type?             | improvement
| Category?         | FO / BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Try to override configuration with env variable in .env file or in the system, for example PS_LANG_DEFAULT
| Fixed ticket?     | -
| Related PRs       | -
| Sponsor company   | Prestashop SA

2023-03-20 16:15 UTC, matks reviewed
With this PR you're going to face a problem

1. User sets configuration XYZ in database through BO interface to value `1` . Then prestashop fetches `1`
2. User sets env var XYZ to value `2` . Then prestashop fetches `2`
3. User sets configuration XYZ in database through BO interface to value `3` . Then he expects  prestashop to fetche `3`

There's the problem of "how to deal with system A overriding system B"?

We encountered the problem in https://github.com/PrestaShop/PrestaShop/issues/23242

2023-03-20 17:37 UTC, mflasquin commented
> With this PR you're going to face a problem
> 
> 1. User sets configuration XYZ in database through BO interface to value `1` . Then prestashop fetches `1`
> 2. User sets env var XYZ to value `2` . Then prestashop fetches `2`
> 3. User sets configuration XYZ in database through BO interface to value `3` . Then he expects  prestashop to fetche `3`
> 
> There's the problem of "how to deal with system A overriding system B"?
> 
> We encountered the problem in #23242

For me he has to know that there is a env var in his system. In magento, when a value exist in env var, the configuration field is not editable in BO.

2023-03-21 09:21 UTC, FabienPapet requested changes

2023-03-21 09:21 UTC, FabienPapet commented on composer.json
> +        "vlucas/phpdotenv": "^5.5"
use Symfony dotenv ?

2023-07-17 09:37 UTC, closed without merging