Fix display of category from other shop
PrestaShop/PrestaShop pull request #31876
Opened 2023-03-22 11:13 UTC by mkdgs

Display a 404 error page when another shop's category is called see #31797 was PR #31798 

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  8.0.x
| Description?      | Respect multi-store category activity state
| Type?             | bug fix
| Category?         | FO
| BC breaks?        |  no
| Deprecations?     |  no
| How to test?      | see issue related
| Fixed ticket?     | Closes #31797
| Related PRs       | 
| Sponsor company   |

2023-03-22 11:25 UTC, kpodemski approved these changes, later dismissed

2023-03-22 11:45 UTC, SharakPL approved these changes, later dismissed

2023-03-23 13:42 UTC, florine2623 reviewed
Hello @mkdgs ,

Thanks for the PR !

Here's what I have :
<img width="1435" alt="Screenshot 2023-03-23 at 14 41 25" src="https://user-images.githubusercontent.com/16019289/227222111-0a4b9ec7-4001-4dac-b2f0-60ce15af7868.png">


Multiple warnings, and I still have access to the category even though in BO the related shop is not checked.

<img width="805" alt="Screenshot 2023-03-23 at 14 42 28" src="https://user-images.githubusercontent.com/16019289/227222359-95637cfa-2574-4f7b-9b95-6b6c3fc684fd.png">

Could you check ? ^^
Thanks!

2023-03-24 11:16 UTC, mkdgs commented
@florine2623 this fix was initially made for 1.7.x the comportment seems different.
I've added a reset for category, that's fixed it.

Let me know if you see anything else :)

2023-03-29 06:15 UTC, kpodemski commented
Hi @mkdgs 

I don't know if getting an empty category instance is a good idea to solve the problem. It's more like a workaround. I think the problem is elsewhere, if the category shouldn't be displayed, why are there products displayed on the screenshot? It should return a 404 page.

2023-03-29 07:43 UTC, mkdgs commented
@kpodemski, i think is the best think to do, because this category don't exist on the shop and has no reasons to be set here. 
The products displayed was the products on this category, and are don't allowed to be seen on this shop. So no category, no products.

This appear to be the simplest and most effective way to get a correct 404 page :)

2023-04-12 09:58 UTC, matks requested changes
> I don't know if getting an empty category instance is a good idea to solve the problem. It's more like a workaround

I agree with @kpodemski : creating a new empty object just to make the page work is a workaround and I think it will bite us back in a few weeks/months 😅 

I think we need to find a better way to have a 404 page 😞

2023-04-12 11:05 UTC, mkdgs commented
damn .... this issue while be still open until the die of prestashop.
@matks It's not just making a new instance, it's resetting a previous instance.

This instance is already set with a wrong value !!!
This not a problem in weeks/months it's already a problem right now.

have you looked at the code ?
```php
public function init()
    {
        $id_category = (int) Tools::getValue('id_category');
        // this category is always set here !
        $this->category = new Category(
            $id_category,
            $this->context->language->id
        );

        parent::init();
        
        if (!Validate::isLoadedObject($this->category) || !$this->category->active || !$this->category->existsInShop($this->context->shop->id)) {
            header('HTTP/1.1 404 Not Found');
            header('Status: 404 Not Found');
            $this->setTemplate('errors/404');
            // there is no category available, but the instance is already defined. So we have to reset it ... 
            $this->category = new Category();
            $this->notFound = true;

2023-04-24 10:55 UTC, kpodemski commented
@mkdgs thing is that this instance should not be used at all on 404 page, right? if the category is inactive in the multi-store, we should be redirected to 404 page where nothing from the `Category` is required, am I right?

I'll investigate this issue today.

2023-04-25 11:51 UTC, kpodemski requested changes
In the `initContent` you need to add:

`&& $this->category->existsInShop($this->context->shop->id)` after:

`&& $this->category->checkAccess($this->context->customer->id)`

and it will work without hacky way of instantiating Category :)

2023-04-25 11:51 UTC, kpodemski commented on controllers/front/listing/CategoryController.php
> +            $this->category = new Category();
```suggestion
```

2023-04-25 12:46 UTC, mkdgs commented
@kpodemski  the category is already instantiated at this step. If you not reset it will stay instantiated with the wrong value.
I think checkAccess() must return a 403 error code, not a 404 
Not tested but i don't see how this can resolve the issue. 

Another "better" way to do it  is to set $this->category only if everything is OK.
But let $this->category with anything else other than an empty instance may throw error later (like for breadcrumbs) 
eg:

```php
public function init()
    {
        $id_category = (int) Tools::getValue('id_category');
        // this category is always set here !
        $tmp_category = new Category(
            $id_category,
            $this->context->language->id
        );

        parent::init();
        
        if (!Validate::isLoadedObject($tmp_category) || !$tmp_category->active || !$tmp_category->existsInShop($this->context->shop->id)) {
            header('HTTP/1.1 404 Not Found');
            header('Status: 404 Not Found');
            $this->setTemplate('errors/404');
            $this->notFound = true;
       }
       // check access...

// all is fine 
        $this->category = $tmp_category;

2023-04-25 13:46 UTC, kpodemski commented
@mkdgs if you do what I suggested we don't need to look for workarounds, we have to have this extra check in the initContent, otherwise the template tries to use category vars which should not be the case

2023-04-25 14:57 UTC, mkdgs commented
@kpodemski i got it, i misread and not see it's about init**Content**
But why not:
```php
 public function initContent()
    {
        parent::initContent();

        if (
            !$this->notFound
            && $this->category->checkAccess($this->context->customer->id)
        ) {
            $this->doProductSearch(
                'catalog/listing/category',
                [
                    'entity' => 'category',
                    'id' => $this->category->id,
                ]
            );
        }
    }
```
and what is the use of the properties $customer_access ? 
we can set it and use it ?

And i still think it's safer to reset $this->category, at least to NULL, both for the two check of existing and access

2023-04-25 15:01 UTC, kpodemski commented
@mkdgs I have no idea what is `$customer_access`, it seems like something abandoned

I'd suggest keeping this code:

```
public function initContent()
    {
        parent::initContent();

        if (
            Validate::isLoadedObject($this->category)
            && $this->category->active
            && $this->category->checkAccess($this->context->customer->id)
            && $this->category->existsInShop($this->context->shop->id)
        ) {
            $this->doProductSearch(
                'catalog/listing/category',
                [
                    'entity' => 'category',
                    'id' => $this->category->id,
                ]
            );
        }
    }
```

for now

2023-04-25 15:04 UTC, kpodemski commented
I agree that it's room for improvement there, but as this is quite a nasty bug, we should keep the simple way of fixing it.

2023-05-12 15:07 UTC, kpodemski commented
hi @mkdgs 👋🏻 

do you think you could finish the PR or shall I takeover?

2023-07-21 08:43 UTC, matks commented
Hi,

Since there was no activity since April, I will follow [our guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests) and I'll close this pull request as it seems stale. Feel free to reopen or open another one if you think it's still relevant.

@kpodemski you can also reopen it if you wish to finish it 😉 

Thanks!

2023-07-21 08:43 UTC, closed without merging