Update Validate.php
PrestaShop/PrestaShop pull request #31886
Opened 2023-03-23 08:03 UTC by fixo94

Change isPrestaShopVersion() for version 8 & 9.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 8.1.x / 8.0.x / 1.7.8.x
| Description?      | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?             | bug fix / improvement / new feature / refacto
| Category?         | FO / BO / CO / IN / WS / TE / LO / ME / PM
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| How to test?      | Indicate how to verify that this change works as expected.
| Fixed ticket?     | Fixes #{issue number here}, Fixes #{another issue number here}
| Related PRs       | If theme, autoupgrade or other module change is needed to make this change work, provide a link to related PRs here.
| Sponsor company   | Your company or customer's name goes here (if applicable).

2023-03-23 08:14 UTC, nicosomb approved these changes
good catch, it seems ok for me.

2023-03-23 08:40 UTC, matks reviewed
Hello there ✋ thank you for the PR

In order to be able to validate the PR and make the codebase more robust for future changes, I think it would be really cool to unit test this function 😉 

There is already one file for unit tests for Validate https://github.com/PrestaShop/PrestaShop/blob/develop/tests/Unit/Classes/ValidateCoreTest.php

2023-03-23 08:42 UTC, matks reviewed
Can you also fill the PR description table and provide a little better title ? 😉 

See https://devdocs.prestashop-project.org/8/contribute/contribution-guidelines/pull-requests/

2023-03-23 15:19 UTC, matthieu-rolland reviewed
LGTM :+1: 

@matks is right about unit test

2023-03-28 12:54 UTC, mflasquin requested changes

2023-03-28 12:54 UTC, mflasquin commented on classes/Validate.php
> +        return preg_match('/^[0-9]\.[0-9]{1,2}(\.[0-9]{1,2}){0,2}$/', $version) && ip2long($version);
```suggestion
        return preg_match('/^[0-9]{1,2}\.[0-9]{1,2}(\.[0-9]{1,2}){0,2}$/', $version) && ip2long($version);
```

For the future :smile:

2023-04-12 09:51 UTC, matks commented
@fixo94 Friendly reminder 😉

2023-04-24 09:09 UTC, fixo94 commented
> @fixo94 Friendly reminder 😉

ok thks, description edited.
For unit test sorry, have no really time soon ...

2023-05-09 10:30 UTC, tleon reviewed
I agree with @mflasquin and @matks. 

You should implement the request change for futur version 10.x 11.x ... . 

You should take a little time to write a unit test for this. It's a very short method and this will not be long to write. 

Once it's done you can have a complete work done. ;)

2023-05-26 06:47 UTC, kpodemski commented
Since we have had no news from you for more than 20 days, I'm closing this PR. Feel free to re-open it if you find the motivation to finish it. Don't hesitate to ping me if you have any questions or doubts.

2023-05-26 06:47 UTC, closed without merging