Functional tests - Refacto 'BO > Customer service'
PrestaShop/PrestaShop pull request #31895
Opened 2023-03-23 13:53 UTC by nesrineabdmouleh

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Refacto 'BO > Customer service'
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 
| Fixed ticket?     | no
| Related PRs       | no
| Sponsor company   |

2023-03-23 15:20 UTC, boubkerbribri requested changes
There is some conflicts to resolve

2023-03-27 08:37 UTC, Progi1984 commented on tests/UI/data/faker/message.ts
> +    this.employee = messageToCreate.employee || `${this.firstName.slice(0.1)}. ${this.lastName}`;
```suggestion
    /** @type {string} employee to forward the message */
    this.employeeName = messageToCreate.employee || `${this.firstName.slice(0.1)}. ${this.lastName}`;
```

I think you can rename the property or change the property with a EmployeeData type.

2023-03-27 08:43 UTC, Progi1984 reviewed
A small feedback about `message.d.ts`

2023-03-30 08:32 UTC, nesrineabdmouleh commented on tests/UI/data/faker/message.ts
> +    this.employee = messageToCreate.employee || `${this.firstName.slice(0.1)}. ${this.lastName}`;
Done :+1:

2023-03-30 08:41 UTC, Progi1984 approved these changes

2023-03-30 12:21 UTC, boubkerbribri approved these changes

2023-04-03 08:14 UTC, nicosomb approved these changes

2023-04-03 08:14 UTC, merged