Bug FIX - inline CSS
PrestaShop/PrestaShop pull request #31919
Opened 2023-03-24 17:20 UTC by martin-tuma

We need to modify file path from relative to full. Without this modification inline js not working.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 8.1.x / 8.0.x / 1.7.8.x
| Description?      | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?             | bug fix / improvement / new feature / refacto
| Category?         | FO / BO / CO / IN / WS / TE / LO / ME / PM
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| How to test?      | Indicate how to verify that this change works as expected.
| Fixed ticket?     | Fixes #{issue number here}, Fixes #{another issue number here}
| Related PRs       | If theme, autoupgrade or other module change is needed to make this change work, provide a link to related PRs here.
| Sponsor company   | Your company or customer's name goes here (if applicable).

2023-03-27 05:33 UTC, SharakPL commented
Thank you for the PR @martin-tuma 
Please provide as much details as possible in PR description table, including specific issue to fix (create one if it doesn't exist)

2023-03-27 09:40 UTC, martin-tuma commented
Hi,
I have install clean 1.7.8.8 and for a one of my modules I need to add "inline" JS. 
By the documentation I use registerJavascript() with relative file path.
Becouse it did not working I try to fix it and I find a problem in JavascriptManager::register().
If relative path stay relative in next step function could not to get content by file_get_contents(),
this function needs full path with root dir.

2023-03-27 10:46 UTC, Hlavtox commented
@martin-tuma Martin, what if we just improved the documentation and stated, that it's required to provide a full path to the file?

2023-03-27 11:00 UTC, martin-tuma commented
Unfortunately this is not the problem. 
If you try it yourself. Relative path ends with error, absolute do nothing, no error and no output.

2023-07-21 08:40 UTC, matks requested changes
Hello @martin-tuma apologies for late review

As mentioned by PHPStan, this code change cannot work on branch `develop` because the `add()` function needs 7 arguments, not 6. I think maybe you encountered the problem on an earlier version of PrestaShop

https://github.com/PrestaShop/PrestaShop/blob/develop/classes/assets/StylesheetManager.php#L113

2026-03-22 17:26 UTC, closed without merging