Bug FIX - inline js
PrestaShop/PrestaShop pull request #31917
Opened 2023-03-24 17:16 UTC by martin-tuma

Warning: file_get_contents(/modules/xxx/js/xxx.js): failed to open stream: No such file or directory We need to modify file path from relative to full. Without this modification inline js not working.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 8.1.x / 8.0.x / 1.7.8.x
| Description?      | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?             | bug fix / improvement / new feature / refacto
| Category?         | FO / BO / CO / IN / WS / TE / LO / ME / PM
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| How to test?      | Indicate how to verify that this change works as expected.
| Fixed ticket?     | Fixes #{issue number here}, Fixes #{another issue number here}
| Related PRs       | If theme, autoupgrade or other module change is needed to make this change work, provide a link to related PRs here.
| Sponsor company   | Your company or customer's name goes here (if applicable).

2023-03-27 05:38 UTC, SharakPL commented
Thank you for the PR @martin-tuma
Please provide as much details as possible in PR description table, including specific issue to fix (create one if it doesn't exist).

Which module are you referring to? Looks like it's the bug in the module itself.

2023-07-21 08:42 UTC, matks requested changes
Hello @martin-tuma apologies for late review

Similarly to https://github.com/PrestaShop/PrestaShop/pull/31919

This code change cannot work on branch develop because the add() function needs 8 arguments, not 7. I think maybe you encountered the problem on an earlier version of PrestaShop

2024-06-26 10:50 UTC, kpodemski commented
Since we have had no news from you for more than 20 days, I'm closing this PR. Feel free to re-open it if you find the motivation to finish it. Don't hesitate to ping me if you have any questions or doubts.

2024-06-26 10:50 UTC, closed without merging

2024-06-26 12:16 UTC, martin-tuma commented
> Since we have had no news from you for more than 20 days, I'm closing this PR. Feel free to re-open it if you find the motivation to finish it. Don't hesitate to ping me if you have any questions or doubts.



> Hello @martin-tuma apologies for late review
> 
> Similarly to #31919
> 
> This code change cannot work on branch develop because the add() function needs 8 arguments, not 7. I think maybe you encountered the problem on an earlier version of PrestaShop



> Since we have had no news from you for more than 20 days, I'm closing this PR. Feel free to re-open it if you find the motivation to finish it. Don't hesitate to ping me if you have any questions or doubts.

Hi,
I didn't notice your reply.

The whole problem that I solve with this fix is ​​the possibility of adding a .JS file as inline.
It's not that common, so it's possible that someone hasn't reported it yet or displayed this data via tpl content, which works.

But if you want to add on PS 1.7.8.8+ whole JS file as inline it didnt work.

### a part of module hookDisplayHeader()
```php
      $this->context->controller->registerJavascript(
        'b4n_popups', // Unique ID
        _MODULE_DIR_.$this->name.'/views/js/b4n_popups.js',
        [
          'position' => 'bottom',
          'inline' => true,
          'priority' => 10,
        ]
      );
```
With my fix it adds the js content to the thml code but without the fix the code is missing.

### a part of page content
```html
<script type="text/javascript">
/* ---- b4n_popups @ D:\www\prestashop-17/modules/b4n_popups/views/js/b4n_popups.js ---- */
console.log('ok');
</script>
```