An unexpected assignment in the CartPresenter method call in the front CartController::initContent
PrestaShop/PrestaShop pull request #32020
Opened 2023-04-03 11:05 UTC by asf-harlock

Removed an assignment from the CartPresenter method call in the front CartController::initContent.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | In the Front CartController::initContent method an unused assignment the CartPresenter method call.
| Type?             | refacto
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no

2023-04-03 16:01 UTC, FabienPapet submitted a review, later dismissed

2023-04-03 16:01 UTC, FabienPapet commented
Can you please target develop  branch ?

2023-04-03 16:58 UTC, kpodemski requested changes
It looks good, but as Fabien noticed, this should target `develop` branch. 1.7.8.x branch accepts only security fixes.

2023-04-03 17:28 UTC, asf-harlock commented
I have target it to develop version, but isn't develop version for version 8? And I don't see the same part of code there. Maybe I missed something?

2023-04-12 09:26 UTC, Hlavtox approved these changes

2023-04-12 12:59 UTC, matks commented
> I have target it to develop version, but isn't develop version for version 8? And I don't see the same part of code there. Maybe I missed something?

`develop` branch will become prestashop 9

2023-04-12 12:59 UTC, matks requested changes
I am sorry @asf-harlock :( you need to rebase the PR it has a git conflict

2023-05-02 06:21 UTC, closed without merging