Fix WS error: add product with empty unit-price
PrestaShop/PrestaShop pull request #32044
Opened 2023-04-04 16:42 UTC by boherm

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | If we add a new product with WS and set unit-price tag with no value on it, we throw an exception for empty string in a `new DecimalNumber()`. This PR fix simply this error.
| Type?             | bug fix
| Category?         | WS
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See #29315
| Fixed ticket?     | Fixes #29315 
| Related PRs       |
| Sponsor company   |

FYI, with `?:` instead of `??` and for each PHP version supported by PrestaShop: 
```php
<?php
var_export (false ?? 'value2');   // false
var_export (true  ?? 'value2');   // true
var_export (null  ?? 'value2');   // value2
var_export (''    ?? 'value2');   // ""
var_export (0     ?? 'value2');   // 0

var_export (false ?: 'value2');   // value2
var_export (true  ?: 'value2');   // true
var_export (null  ?: 'value2');   // value2
var_export (''    ?: 'value2');   // value2
var_export (0     ?: 'value2');   // value2
```

2023-04-04 17:22 UTC, mflasquin requested changes

2023-04-04 17:22 UTC, mflasquin commented on classes/Product.php
>              $price = $price->plus(new DecimalNumber((string) ($this->ecotax ?? 0)));
```suggestion
        $price = new DecimalNumber((string) ($this->price ?: 0));
        if ($ecotaxEnabled) {
            $price = $price->plus(new DecimalNumber((string) ($this->ecotax ?: 0)));
```

2023-04-05 13:54 UTC, mflasquin approved these changes

2023-04-05 15:27 UTC, matthieu-rolland approved these changes

2023-04-06 14:54 UTC, AureRita commented
Hi @boherm 

Thank you for your PR, I tested you PR and when you set an empty unit-price, It's works ! 
But when I set an empty price ( as you change it on the code ), that's return me an error. 

as you can see : 

[Untitled_ Apr 6, 2023 4_25 PM.webm](https://user-images.githubusercontent.com/100699445/230417482-efff0a55-d187-413b-9c15-f03ad6dfd46e.webm)

Thank you

2023-04-06 15:13 UTC, boherm commented
Thanks for your review @AureRita!

We have a rule in WS to avoid to add a new product if `price` is empty, but it wasn't the case for `unit_price`.
This error showed in your video, isn't a PHP Exception but a WS error, so I think that is ok for price!

2023-04-07 11:55 UTC, florine2623 approved these changes
Hello @boherm ,

Thanks for the PR !

It is indeed fixed. With or without unit_price, the POST method for products works as expected 👍 


https://user-images.githubusercontent.com/16019289/230604582-5c1a90c1-cd0e-40b8-9b1b-bac3229f86d4.mov



It is QA ✅

2023-04-07 12:36 UTC, merged

2023-04-07 12:36 UTC, nicosomb commented
Thank you @boherm !