Update CheckoutAddressesStep.php
PrestaShop/PrestaShop pull request #32067
Opened 2023-04-06 07:59 UTC by uguranium

Fix: If edit and save delivery address, invoice address is null

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 8.1.x / 8.0.x / 1.7.8.x
| Description?      | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?             | bug fix / improvement / new feature / refacto
| Category?         | FO / BO / CO / IN / WS / TE / LO / ME / PM
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| How to test?      | Indicate how to verify that this change works as expected.
| Fixed ticket?     | Fixes #{issue number here}, Fixes #{another issue number here}
| Related PRs       | If theme, autoupgrade or other module change is needed to make this change work, provide a link to related PRs here.
| Sponsor company   | Your company or customer's name goes here (if applicable).

2023-04-06 16:37 UTC, matthieu-rolland reviewed
Hello,

Please fill the PR description properly (the table), and if it's a bug fix, create a related issue linking your PR and a proper "how to test step by step" so that our QA team can test it. 

Thank you :+1:

2023-04-06 16:44 UTC, boherm commented
Hello @uguranium!
Thanks for your contribution!

Can you rewrite your description and fill the table properly please?
It's important for others contributors and others teams.

Btw, I've test your PR and it works well!

@matks Do you think that can be preferable to merge into 8.0.x instead of develop for this fix?

2023-04-17 14:04 UTC, kpodemski requested changes
Hello @uguranium 

Please fill in the table of your PR so that we can follow the steps you provided to:
- validate that the bug exists
- validate that your fix solves the issue

2023-07-21 08:09 UTC, matks commented
Hi,

Since we had no news from you for more than 30 days, I will follow [our guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests) and I'll close this pull request as it seems stale. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2023-07-21 08:09 UTC, closed without merging