Fix domain translation
PrestaShop/PrestaShop pull request #32154
Opened 2023-04-13 16:28 UTC by lartist

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Fix domain translation
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | auto tests 🟢 https://github.com/lartist/ga.tests.ui.pr/actions/runs/4697213600
| Fixed ticket?     | 
| Related PRs       | 
| Sponsor company   |

2023-04-13 16:41 UTC, FabienPapet submitted a review, later dismissed

2023-04-13 16:44 UTC, boherm commented on classes/lang/KeysReference/FeatureFlagLang.php
> +trans('States', 'Admin.Advprameters.Feature');
```suggestion
trans('States', 'Admin.Advparameters.Feature');
```
I think :-D

2023-04-14 06:54 UTC, jolelievre requested changes

2023-04-14 06:54 UTC, jolelievre commented on classes/lang/KeysReference/FeatureFlagLang.php
> +trans('States', 'Admin.Advprameters.Feature');
Indeed

2023-04-14 06:56 UTC, lartist commented on classes/lang/KeysReference/FeatureFlagLang.php
> +trans('States', 'Admin.Advprameters.Feature');
Thanks @boherm. Done

2023-04-14 07:02 UTC, nicosomb approved these changes

2023-04-14 07:25 UTC, boherm approved these changes

2023-04-14 07:28 UTC, jolelievre approved these changes
Thanks @lartist

2023-04-14 07:45 UTC, merged