FIX: SKIP resizing ORIGINAL product IMAGE on uploading
PrestaShop/PrestaShop pull request #32184
Opened 2023-04-17 11:42 UTC by stifler97

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | When uploading an image in product form, the original image must stay untouched, but prestashop uses resize methods and modifies the original image. This image is usable when using product image sliders and customer can take benefit of zooming in a high quality image.
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Check this issue #26111 for how to verify the issue exists. Then use this PR to verify uploaded original image is not modified at all.
| Fixed ticket?     | Fixes #26111 
| Related PRs       | I could not find any
| Sponsor company   | Beisat.com

2023-04-17 11:58 UTC, stifler97 commented
Here is the result:
The original image before upload
![paul-gaudriault-a-QH9MAAVNI-unsplash](https://user-images.githubusercontent.com/23106000/232476101-cfcc0a8b-bae1-42e4-8961-b63d09721076.jpg)

The original image after upload with out resizing
![image](https://user-images.githubusercontent.com/23106000/232475928-565fa978-7e26-42fb-9f2a-281a5d4546c7.png)

The original image after upload with resizing
![image](https://user-images.githubusercontent.com/23106000/232476293-084672c6-aaea-487c-b23a-f696ea150366.png)


If you save these files you will see that file size increases after resizing. First of all, we must not resize the original image. Other than that, we should avoid wasting storage.

2023-04-17 13:00 UTC, Hlavtox submitted a review, later dismissed

2023-04-17 14:00 UTC, kpodemski requested changes
If you change this code, there won't be `$error` other than `0`.

2023-04-18 04:49 UTC, stifler97 commented
> If you change this code, there won't be `$error` other than `0`.

you are right, I changed two files to keep errors and copy raw image only if needed

2023-04-18 05:58 UTC, Hlavtox commented
@stifler97 I don't think this is a correct solution. What's the point of adding a parameter to a resize function, that tells it **to not do** what it's supposed to do?

If the file should only be moved, then there certainly are examples in the code we shoud follow, with error handling. 👍

2023-04-18 06:06 UTC, stifler97 commented
> If the file should only be moved, then there certainly are examples in the code we shoud follow, with error handling. 👍

I could not find a method which only copies the image i

2023-04-18 10:27 UTC, Hlavtox commented
@stifler97 Search for `move_uploaded_file` in the codebase.

Also remember that this change would need to be done for all objecs - categories, manufacturers, stores etc.
Also, make sure to test it with all image formats supported.

If done properly, it should not be a problem. 👍 If Prestashop can regenerate the original image, it will be able to regenerate thumbnails.

2023-04-26 16:05 UTC, MatShir commented
FYI: If you guys find the right implementation, then ,remember, we can introduce the fix in the `8.1.x`. I would be nice to have your fix for the next minor release or the patches that will follow

2023-05-04 10:05 UTC, kpodemski requested changes
Hello @stifler97 

The next major version will remove this file and code related to the old product page.

If you want to apply such change, you would need to:
- target 8.1.x branch
- keep your modification as is
- check your modification against the new product page because it should work identically across the system

2023-07-21 08:07 UTC, matks commented
Hello everyone,

I'm sorry but it seems this PR did not move since May :/ . Apologies @stifler97 that your PR won't work on `develop`. As @kpodemski mentioned in 9.0.0 we are going to REMOVE these files so changing this code will not be useful.

Since no activity for more than 30 days, I will follow [our guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests) and I'll close this pull request.

Thanks!

2023-07-21 08:07 UTC, closed without merging