Bump psgdr
PrestaShop/PrestaShop pull request #32209
Opened 2023-04-19 16:10 UTC by lartist

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Bump psgdpr
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI and auto tests 🟢 
| Fixed ticket?     | 
| Related PRs       |
| Sponsor company   |

2023-04-19 16:20 UTC, FabienPapet approved these changes

2023-04-19 18:03 UTC, mflasquin approved these changes

2023-04-20 07:13 UTC, jolelievre approved these changes

2023-04-24 11:33 UTC, kpodemski requested changes
Tests are red.

2023-04-24 13:11 UTC, lartist commented
> Tests are red. Also, I think it'd be better to use the version pattern that supports patches automatically.

Hi @kpodemski . We already know that psgdpr 2.0.0 is unstable and it causes a lot of troubles during install or autoupgrade. That's why I decided to start from 2.0.1

2023-05-25 08:33 UTC, closed without merging