Fix: Setting DNI mandatory after address creation launches an exception during checkout
PrestaShop/PrestaShop pull request #32290
Opened 2023-04-21 16:03 UTC by Codencode

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  8.1.x
| Description?      | If for a country there is the mandatory CF field and try to make an order (in the front-office) with an address that has the DNI empty field, the system shows an error that I attach.
| Type?             | bug fix 
| Category?         | FO
| BC breaks?        | no
| Deprecations?     |  no
| Fixed ticket?     | Fixes #31908

2023-04-24 10:14 UTC, Hlavtox commented
I think that this is still not a good solution. With this, you are returning a simmilar checksum for all carts where there is no address valid.

As I said in your original PR:

> I think you should implement this check in AddressChecksumCore::generateChecksum and return sha1('No address set'); like it does if (!$address->id).

2023-04-24 11:00 UTC, Codencode commented
> I think that this is still not a good solution. With this, you are returning a simmilar checksum for all carts where there is no address valid.
> 
> As I said in your original PR:
> 
> > I think you should implement this check in AddressChecksumCore::generateChecksum and return sha1('No address set'); like it does if (!$address->id).


You mean it's better to replace
`return sha1('No address set');`

with something like this?
` return sha1('Invalid address set');`

2023-04-24 11:06 UTC, Hlavtox commented
@Codencode No, I would do it here - https://github.com/PrestaShop/PrestaShop/blob/develop/classes/AddressChecksumCore.php

But let's see what others think. Ping @kpodemski

2023-04-24 12:24 UTC, boherm commented
> @Codencode No, I would do it here - https://github.com/PrestaShop/PrestaShop/blob/develop/classes/AddressChecksumCore.php
> 
> But let's see what others think. Ping @kpodemski

I agree! It can be done here.

2023-04-24 13:03 UTC, Codencode commented
> Invalid address set

@Hlavtox @boherm 
So you would do it like this?
```
class AddressChecksumCore implements ChecksumInterface
{
    public const SEPARATOR = '_';

    /**
     * Generate a checksum.
     *
     * @param Address $address
     *
     * @return string SHA1 checksum for the Address
     */
    public function generateChecksum($address)
    {
        if (!$address->id) {
            return sha1('No address set');
        }

        // additional control *******************************************************
        if (Country::isNeedDniByCountryId($address->id_country) && !$address->dni) {
            return sha1('Dni is required'); 
        }
        //***************************************************************************

        $uniqId = '';
        $fields = $address->getFields();
        foreach ($fields as $name => $value) {
            $uniqId .= $value . self::SEPARATOR;
        }
        $uniqId = rtrim($uniqId, self::SEPARATOR);

        return sha1($uniqId);
    }
}
```

2023-04-24 13:31 UTC, boherm commented
@Codencode, it can be I think! 👍 
But instead of `Country::isNeedDniByCountryId` I would rather write `Address::dniRequired` to avoid use another ObjectModel than Address.

2023-04-24 13:35 UTC, Hlavtox commented
@Codencode Yeah that is much nicer dude. See, we still get a proper cart checksum if you do it like this. :-)

And @boherm also has a nice suggestion. There is a function like this.

```php
if (Address::dniRequired($address->id_country) && !$address->dni) {
    return sha1('Dni is required'); 
}
```

2023-04-24 13:40 UTC, Codencode commented
@boherm good idea!
@Hlavtox thank you for your suggestion!

Should I delete this PR and create a new one?
Sorry but I'm still unfamiliar with Github

2023-04-24 13:48 UTC, boherm commented
> Should I delete this PR and create a new one? Sorry but I'm still unfamiliar with Github

No need to create a new PR, you can add new commit with your new diff and rebase interactively your branch to remove your olders 2 commits, than push force your branch! With this method, after merging we only have one commit in PS history for your PR. :-)

2023-04-24 22:13 UTC, Codencode commented
> No need to create a new PR, you can add new commit with your new diff and rebase interactively your branch to remove your olders 2 commits, than push force your branch! With this method, after merging we only have one commit in PS history for your PR. :-)

I made the change, but I don't know if it's okay because I don't understand the "rebase" argument, I "reverted" the changes that are no longer needed.

I await feedback.

Thank you!

2023-04-25 13:39 UTC, boherm commented
Thanks for your changes @Codencode!
But I think we can have a git history cleaner, in fact only your last commit (465fcd1...) need to be in your PR! :D 
When you revert a commit, git create another commit in your history.

To clean your commits history, you can rewrite it like explain in https://www.atlassian.com/git/tutorials/rewriting-history#git-rebase-i. It could be cool if you do so, to avoid to add 7 commits into PrestaShop main history! :D

2023-04-26 14:23 UTC, Codencode commented
> Thanks for your changes @Codencode! But I think we can have a git history cleaner, in fact only your last commit ([465fcd1](https://github.com/PrestaShop/PrestaShop/commit/465fcd1bdc3e413b537dd086b5195dd2f69cab99)...) need to be in your PR! :D When you revert a commit, git create another commit in your history.
> 
> To clean your commits history, you can rewrite it like explain in https://www.atlassian.com/git/tutorials/rewriting-history#git-rebase-i. It could be cool if you do so, to avoid to add 7 commits into PrestaShop main history! :D

Thanks for the tips @boherm!
I followed the guide you linked to me and after several attempts I was able to clear the history.
I hope I did everything correctly.
Thanks again!

2023-04-26 14:27 UTC, boherm approved these changes, later dismissed
LGTM :)
Thanks @Codencode!

2023-04-26 19:13 UTC, Hlavtox commented
Now I am thinking.... The address validation could fail for many reasons. Since we have no way to tell object model not to die when something goes wrong.

What about doing this instead?
```php
try {
    $fields = $address->getFields();
} catch (Exception $e) {
    return sha1('Invalid address');
}
```

2023-04-27 07:22 UTC, Codencode commented
> Now I am thinking.... The address validation could fail for many reasons. Since we have no way to tell object model not to die when something goes wrong.
> 
> What about doing this instead?
> 
> ```
> try {
>     $fields = $address->getFields();
> } catch (Exception $e) {
>     return sha1('Invalid address');
> }
> ```
Indeed what you say is correct and your solution covers all cases.

@boherm what do you think?

2023-04-27 09:01 UTC, boherm commented
@Hlavtox, @Codencode, Yes, I agree with you guys.
With this way all cases can be covered and I think that is the best solution to fix this issue too.

2023-04-27 09:35 UTC, Codencode commented
> @Hlavtox

Okay,
then I proceed with the changes.
Thank you!

2023-04-27 10:37 UTC, Codencode commented
@boherm, @Hlavtox, I made the change, but PHPUnit (7.4) failed and I don't understand why.

Can you confirm that the modification is ok?

Thanks!

2023-04-27 13:12 UTC, boherm commented
@Codencode, Github Actions may fail sometime for obscur reasons. :-D 
It seems to be the case for `PHP / PHPUnit (7.4) (pull_request)` and I think if we relaunch this check it could be run with success.

2023-04-27 13:15 UTC, Codencode commented
> @Codencode, Github Actions may fail sometime for obscur reasons. :-D
> It seems to be the case for `PHP / PHPUnit (7.4) (pull_request)` and I think if we relaunch this check it could be run with success.

Ok, if I wanted to relaunch only this control how should I do?

2023-04-27 13:36 UTC, boherm commented
Good question, but I ask to restart this job and It's green! :-D
(thanks @jolelievre)

2023-04-27 13:36 UTC, boherm approved these changes, later dismissed

2023-04-27 19:54 UTC, Hlavtox approved these changes
Looks good, did not test it, but I think we found out a pretty neat solution guys!

2023-04-27 19:55 UTC, Hlavtox requested changes
Just remove the duplicate $uniqId = ''; :-)

2023-04-28 07:19 UTC, Codencode commented
> Just remove the duplicate $uniqId = ''; :-)

I hadn't really noticed the duplicate variable.
Do I rebase? so we have clean code?

Thank you!

2023-04-28 08:27 UTC, Codencode commented
> Just remove the duplicate $uniqId = ''; :-)

I hadn't noticed the duplicate variable.
I made the change and did the rebase so I have clean code, I hope I did it right.

Thanks @Hlavtox

2023-04-28 11:00 UTC, boherm approved these changes

2023-04-28 22:13 UTC, Hlavtox approved these changes

2023-05-03 16:56 UTC, Codencode commented
@Hlavtox @boherm, 
do i have to do anything else?

2023-05-04 05:39 UTC, Hlavtox commented
Ping @PrestaShop/committers

2023-05-04 09:51 UTC, kpodemski approved these changes

2023-05-05 15:32 UTC, djoelleuch approved these changes
Hello @Codencode  ,
I have checked your PR the issue is well fixed ,

[32290.webm](https://user-images.githubusercontent.com/115152460/236502221-f1ce9510-78f8-43a3-ace7-3ace5b10508b.webm)

It's QA approved :heavy_check_mark:
Thank you for you PR :rocket:

2023-05-06 06:53 UTC, merged

2023-05-06 06:53 UTC, nicosomb commented
Thank you @Codencode !