Add missing y to service name
PrestaShop/PrestaShop pull request #32340
Opened 2023-04-26 07:52 UTC by PrestaEdit

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Services name are the sames ; only this one missing an y on query name.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | yes ?
| Deprecations?     | no
| Sponsor company   | @Wepika.

2023-04-26 08:03 UTC, Hlavtox submitted a review, later dismissed

2023-04-26 08:03 UTC, boherm submitted a review, later dismissed

2023-04-26 15:29 UTC, lartist approved these changes, later dismissed

2023-04-30 21:27 UTC, FabienPapet requested changes

2023-04-30 21:27 UTC, FabienPapet commented on src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml
> +  prestashop.core.grid.query_.builder.language:
```suggestion
  prestashop.core.grid.query.builder.language:
```

2023-04-30 21:27 UTC, FabienPapet commented on src/PrestaShopBundle/Resources/config/services/core/grid/grid_data_factory.yml
> +      - '@prestashop.core.grid.query_.builder.language'
```suggestion
      - '@prestashop.core.grid.query.builder.language'
```

2023-04-30 23:31 UTC, SharakPL approved these changes

2023-05-01 13:14 UTC, FabienPapet approved these changes

2023-05-01 13:16 UTC, FabienPapet commented
Nothing to test by QA, as it is just a service naming fix. No functionnal change

2023-05-05 12:05 UTC, merged