Fix translation doesn't work for child theme
PrestaShop/PrestaShop pull request #32359
Opened 2023-04-27 09:12 UTC by ThomasDrd

Related to this issue https://github.com/PrestaShop/PrestaShop/issues/30716 Revert to previous version explained in this comment : https://github.com/PrestaShop/PrestaShop/issues/30716#issuecomment-1525153698

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.7
| Description?      | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?             | bug fix
| Category?         |  BO 
| Deprecations?     | yes
| How to test?      | Changing core traduction applied in child theme
| Fixed ticket?     | Fixes #{30716}

2023-05-04 09:45 UTC, kpodemski commented
Hi @ThomasDrd 

Thanks for the PR. I found a bit cleaner version of the fix, take a look:
https://capture.dropbox.com/ilxwKxmz4XRUzh7E

What do you think?

2023-05-05 08:53 UTC, arjan-designpro commented
> Hi @ThomasDrd
> 
> Thanks for the PR. I found a bit cleaner version of the fix, take a look: https://capture.dropbox.com/ilxwKxmz4XRUzh7E
> 
> What do you think?

Does nothing for me.

2023-05-05 12:42 UTC, kpodemski commented
@arjan-designpro have you cleared the cache? It does work for me.

2023-05-08 09:29 UTC, mariuszsienkiewicz commented
Yes, it does work. If someone wants to test it, here is the updated content of the variable instead of the screenshot:

```php
$selectTranslationsQuery = '
    SELECT `key`, `translation`, `domain`
    FROM `' . _DB_PREFIX_ . 'translation`
    WHERE `id_lang` = ' . $localeResults[$locale]['id_lang'] . '
    AND theme ' . ($this->theme !== null ? ' IN ("' . $this->theme->getName() . '"' . ($this->theme->get('parent') ? ',"' . $this->theme->get('parent') . '"' : '') . ')' : 'IS NULL');
```

2023-05-09 09:51 UTC, tleon commented
You also have some failing CI test to handle and maybe some refacto for the problem shown by the static analysis.

2023-05-09 09:53 UTC, tleon reviewed
You also have some failing CI test to handle and maybe some refacto for the problem shown by the static analysis.

2023-05-09 10:21 UTC, kpodemski commented
Hi @ThomasDrd 

What do you think about using proposed solution?

2023-05-15 14:51 UTC, ThomasDrd commented
Sorry for the response time.
I integrated the solution in my PR

2023-05-26 15:05 UTC, kpodemski commented on src/PrestaShopBundle/Translation/Loader/SqlTranslationLoader.php
> +
```suggestion
```

2023-05-26 15:05 UTC, kpodemski commented on src/PrestaShopBundle/Translation/Loader/SqlTranslationLoader.php
> +
```suggestion
```

2023-05-29 07:00 UTC, kpodemski commented on src/PrestaShopBundle/Translation/Loader/SqlTranslationLoader.php
>          $this->addTranslationsToCatalogue($translations, $catalogue);
```suggestion
        $this->addTranslationsToCatalogue($translations, $catalogue);

```

2023-05-29 09:08 UTC, kpodemski submitted a review, later dismissed

2023-06-02 08:05 UTC, nicosomb submitted a review, later dismissed

2023-06-02 14:48 UTC, hibatallahAouadni reviewed
Hello @ThomasDrd 

I still encounter the issue with your PR, see the attached screen record below:

[pr32359.webm](https://github.com/PrestaShop/PrestaShop/assets/23308427/4dcaae28-7837-45cd-91fb-7cd8d0dd52df)

Please check  and feedback.
Thanks!

2023-06-08 07:15 UTC, kpodemski commented
@hibatallahAouadni 

you need to add some custom phrases to your child theme, otherwise you have nothing to translate because translations are coming from the parent theme

2023-06-09 14:26 UTC, sallemiines commented
> @hibatallahAouadni
> 
> you need to add some custom phrases to your child theme, otherwise you have nothing to translate because translations are coming from the parent theme

Hello @kpodemski 

Could you please add custom phrases  to the classic child theme and sent it to the QA, so that we can check the PR ! 

Thank you !

2023-07-06 22:10 UTC, kpodemski commented
Hello all. This doesn't fix the problem fully if you have multistore and use child themes. I proposed a bit different solution, which should be better as it correctly generates a translations catalog for all the active themes.

https://github.com/PrestaShop/PrestaShop/pull/33133

@ThomasDrd could you let me know if that works for you?

2023-09-22 13:19 UTC, nicosomb requested changes
No more changes in your pull request 🤔 I don't think it's normal.

2023-09-24 09:19 UTC, closed without merging