Add phpmyadmin service as optional
PrestaShop/PrestaShop pull request #32474
Opened 2023-05-08 06:18 UTC by tesshsu

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 8.1.x / 8.0.x / 1.7.8.x
| Description?      | Add a phpMyAdmin service to Docker compose file in order to easily access BO from [ Idea] #32425
| Type?             | improvement
| Category?         | IN
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Indicated in document, run docker-compose -f docker-compose.yml -f docker-composer.override.yml up to check if prestashop is correctly installed with phpMyAdmin
| Fixed ticket?     | [ Idea] #32425

2023-05-08 14:11 UTC, FabienPapet requested changes, later dismissed
Thank you for the PR, nice work already, I addressed some comments

2023-05-08 14:11 UTC, FabienPapet commented on docker-composer.override.yml
> +version: '2.1'
Can you please rename this file to `docker-compose.override.yml.dist` ?

2023-05-08 14:11 UTC, FabienPapet commented on README.md
> +**Note:** To add a PHPMyAdmin service to your Docker Compose setup, start your Docker Compose setup with the -f flag to include both the docker-compose.yml and docker-compose.override.yml files:
```suggestion
**Note:** To add a PHPMyAdmin service to your Docker Compose setup, you can copy the existing `docker-compose.override.yml.dist` to `docker-compose.override.yml` and then start your Docker Compose setup (override file will be included as it is a convention)
```

2023-05-08 14:11 UTC, FabienPapet commented on README.md
> +docker-compose -f docker-compose.yml -f docker-composer.override.yml up
```suggestion
cp docker-compose.override.yml.dist docker-compose.override.yml
docker-compose up
```

2023-05-08 15:06 UTC, tesshsu commented
@FabienPapet
Thanks for the feedback, updated by your recommends, any further request let me know, thank you

2023-05-08 15:19 UTC, zuk3975 approved these changes

2023-05-09 05:19 UTC, tleon approved these changes

2023-05-09 09:17 UTC, kpodemski commented on docker-composer.override.yml
@tesshsu I think we don't need this file by default

2023-05-09 09:50 UTC, tesshsu commented on docker-composer.override.yml
Hi @kpodemski , yes, the file had been removed, check the commit
![1](https://user-images.githubusercontent.com/3927152/237060450-4b373188-8921-4865-870f-e8e624867506.png)

2023-05-09 10:47 UTC, kpodemski approved these changes

2023-05-09 10:47 UTC, kpodemski commented
This requires QA by a dev. @FabienPapet could you check?

2023-05-12 14:20 UTC, tleon commented
I tested it LGTM.

2023-05-12 14:54 UTC, matks approved these changes
Thank you @tesshsu nice contribution 😉

2023-05-13 13:47 UTC, merged

2023-05-13 13:47 UTC, FabienPapet commented
Thank you @tesshsu for the PR and @tleon for testing it.