Add of GeoCoordinates form type
PrestaShop/PrestaShop pull request #32494
Opened 2023-05-09 13:29 UTC by LouisAUTHIE

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add a new Form Type to add geolocation coordinates (lat/lon), will be used in the stores form migration to SF
| Type?             | new feature
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 
Add it to a buildForm method with 
->add('latlon', GeoCoordinatesType::class, [
                'label' => $this->trans('Position', 'Admin.Global'),
                'required' => false,
                'empty_data' => '',
                'label_latitude' => 'Latitude',
                'label_longitude' => 'Longitude',
                'attr' => ['class'=>'form-inline'],
            ])
| Fixed ticket?     | N/A
| Related PRs       | N/A
| Sponsor company   | N/A

2023-05-09 13:40 UTC, 0x346e3730 approved these changes, later dismissed

2023-05-09 13:50 UTC, FabienPapet requested changes
That looks nice, but I don't see any usage and it may become a form type that nobody uses. Can you update the code inside the admin to use it ?

2023-05-09 13:51 UTC, zuk3975 commented on src/PrestaShopBundle/Form/Admin/Type/GeoCoordinatesType.php
> +}
missing new line in the end of file

2023-05-09 13:55 UTC, LouisAUTHIE commented
> That looks nice, but I don't see any usage and it may become a form type that nobody uses. Can you update the code inside the admin to use it ?

It is for the Admin Store creation form migration. It could be used in a module...What do you exactly expect from me ? What action do I have to make ?

2023-05-09 13:56 UTC, FabienPapet requested changes

2023-05-09 13:56 UTC, FabienPapet commented on src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
> +        - "@translator"
```suggestion
```

This is not needed as we now use autowiring by default in all form types declared in this file

2023-05-09 13:56 UTC, FabienPapet commented on src/PrestaShopBundle/Form/Admin/Type/GeoCoordinatesType.php
> +        $resolver->setDefaults([
I think you can set  `'compound ' => true` and `'inherit_data' => true` as well. So we can use it without being forced to create an intermediate format.

example: 
```php 
<?php 
$data = [
	'name' => 'hello',
	'latitude' => 0,
	'longitude' => 0
];
```

The form type will then look like 

````
$builder->add('name', TextType::class)
$builder->add('coordinates', GeoCoordinate::class)

2023-05-09 19:10 UTC, LouisAUTHIE commented on src/PrestaShopBundle/Form/Admin/Type/GeoCoordinatesType.php
> +        $resolver->setDefaults([
Thanks, changed committed

2023-05-09 19:10 UTC, LouisAUTHIE commented on src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
> +        - "@translator"
Thanks committed too

2023-05-10 07:27 UTC, boherm submitted a review, later dismissed

2023-05-10 11:54 UTC, matks reviewed
> > That looks nice, but I don't see any usage and it may become a form type that nobody uses. Can you update the code inside the admin to use it ?
> 
> It is for the Admin Store creation form migration. It could be used in a module...What do you exactly expect from me ? What action do I have to make ?

We could expand https://github.com/PrestaShop/example-modules/tree/master/demosymfonyform to include that exemple in it
- it would demonstrate how to use it inside a SF form
- it would allow QA people to validate it

2023-05-10 20:48 UTC, LouisAUTHIE commented
> > > That looks nice, but I don't see any usage and it may become a form type that nobody uses. Can you update the code inside the admin to use it ?
> > 
> > 
> > It is for the Admin Store creation form migration. It could be used in a module...What do you exactly expect from me ? What action do I have to make ?
> 
> We could expand https://github.com/PrestaShop/example-modules/tree/master/demosymfonyform to include that exemple in it
> 
>     * it would demonstrate how to use it inside a SF form
> 
>     * it would allow QA people to validate it

Good idea, the test is available there : https://github.com/PrestaShop/example-modules/pull/144

2023-05-11 06:55 UTC, zuk3975 submitted a review, later dismissed

2023-05-11 15:47 UTC, matks approved these changes, later dismissed
Thank you @LouisAUTHIE I approve this PR. I improved a little the description to make it very clear how to use it with https://github.com/PrestaShop/example-modules/pull/144/ and now QA team will test it

2023-05-15 15:22 UTC, florine2623 commented
This PR is blocked by https://github.com/PrestaShop/example-modules/pull/144 for now. I'm taking off the WFQA label.

2023-05-15 15:59 UTC, kpodemski commented
@florine2623 @Robin-Fischer-PS 

this should be tested by a dev

2023-05-16 05:22 UTC, okom3pom commented
Blocked by an installation error the QA should be able to test well now

2023-05-16 07:09 UTC, kpodemski commented
@okom3pom there's no reason for example modules to be tested by a QA :D exactly for this reason you mentioned in your comment

2023-05-20 18:53 UTC, LouisAUTHIE commented
Where are we in the process. It is just a form type not a full product…

2023-06-17 13:32 UTC, LouisAUTHIE commented
Hi, any news about it ?

2023-06-17 13:34 UTC, kpodemski commented
It waited for a developer to test it, but now I see there's a conflicted file. If you could rebase, I'll ask devs for higher priority on this one :( Sorry.

2023-06-19 14:00 UTC, jolelievre approved these changes, later dismissed
Thanks @LouisAUTHIE

2023-06-19 14:29 UTC, FabienPapet commented on src/PrestaShopBundle/Form/Admin/Type/GeoCoordinatesType.php
> +        TranslatorInterface $translator
```suggestion
        private readonly TranslatorInterface $translator
```

2023-06-19 14:29 UTC, FabienPapet commented on src/PrestaShopBundle/Form/Admin/Type/GeoCoordinatesType.php
> +
```suggestion
```

2023-06-19 14:29 UTC, FabienPapet commented on src/PrestaShopBundle/Form/Admin/Type/GeoCoordinatesType.php
> +        $this->translator = $translator;
```suggestion
```

2023-06-19 14:29 UTC, FabienPapet commented on src/PrestaShopBundle/Form/Admin/Type/GeoCoordinatesType.php
> +    public function buildForm(FormBuilderInterface $builder, array $options)
```suggestion
    public function buildForm(FormBuilderInterface $builder, array $options): void
```

2023-06-19 14:29 UTC, FabienPapet commented on src/PrestaShopBundle/Form/Admin/Type/GeoCoordinatesType.php
> +    public function configureOptions(OptionsResolver $resolver)
```suggestion
    public function configureOptions(OptionsResolver $resolver): void
```

2023-06-19 14:29 UTC, FabienPapet commented on src/PrestaShopBundle/Form/Admin/Type/GeoCoordinatesType.php
> +    public function getBlockPrefix()
```suggestion
    public function getBlockPrefix(): string
```

2023-06-19 14:29 UTC, FabienPapet commented on src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
> +      - "@translator"
```suggestion
```

2023-06-19 19:01 UTC, FabienPapet approved these changes

2023-06-20 07:24 UTC, boherm approved these changes
LGTM, thanks @LouisAUTHIE!

2023-06-23 21:02 UTC, LouisAUTHIE commented
ping @jolelievre @kpodemski

2023-06-23 21:02 UTC, LouisAUTHIE commented
ping @matks @0x346e3730

2023-07-27 16:17 UTC, boherm commented
Hi @LouisAUTHIE!

On it for testing by dev ;) 
Sorry for the very long delay... 😅

2023-07-28 10:55 UTC, boherm commented
Hi @LouisAUTHIE!
After testing, your Type working well.

Some comments about it:
- When we set `required => true` in your GeoCoordinatesType, `latitude` and `longitude` must also be required. For now, the `latitude` and `longitude` fields aren't required by default. It could be nice to set `required => true` on theses fields when we need to in the `GeoCoordinatesType`!
- When we have set a value in `latitude`, we must have also a value on `longitude` field. And vice versa.
- We must also control the values of theses fields to avoid a values of latitude or longitude out of world bounds.

What do your think? :)

2023-07-28 13:19 UTC, LouisAUTHIE commented
I am not sure that it has to be checked there, it can be open in the form type and we can add more checks in the controller or in the parent type.

2023-07-28 13:42 UTC, boherm commented
I understand, but it sounds weird to me to let the user type a latitude without a longitude, or a latitude < -90 && latitude > 90 for instance 😅

2023-07-28 14:12 UTC, LouisAUTHIE commented
Depends on the units deg, min sec on decimal. Whatever the position, I don't want to add another commit leading to another review round, thats enought, I'm waiting for it since may, 9th, If it take as mush time for a little form type, what will happen for the migrated controller. The project is getting mad with those delays. Sorry for you guy who work hard for it, but I'm am a bit discouraged !!!

2023-07-28 14:20 UTC, matks commented
> The project is getting mad with those delays. Sorry for you guy who work hard for it, but I'm am a bit discouraged !!!


Hello @LouisAUTHIE I am sorry that you are disappointed however you must understand that if validation delays on the open source project are long, this is simply because the number of incoming contributions is too much compared to the project team available time. When there's too much work and not enough people, validation delays get longer. So the people in the project team, and this includes @boherm are already doing their best to _handle_ a workload that is way too big compared to what they can do.

So it's _also_ discouraging for us 😄 that we do our best and yet we hear it's not enough.

So if you really want things to improve, then the solution is quite easy: come help us 😉 and join the [Committer team](https://www.prestashop-project.org/maintainers-guide/how-to-become-a-committer/). Doing this you will be able to make it easier to deal with the workload, help other contributors have review faster, and help the project move forward.

2023-07-28 14:46 UTC, boherm commented
@LouisAUTHIE, to be clear, I didn't block your PR 🙂
So, we have 2 approvals and a Go from dev to merge.
Let's merge your work? 😉

2023-07-28 14:49 UTC, LouisAUTHIE commented
I know, in fact we often have a majority of approvals and a "upper quality" recommendation for a new reviewer. Even if we can elevate the cursor of quality sometimes, I think that we can let things a bit more open. Anyway thanks again for you help guys. I am sure that you will understand my little discouraging

2023-07-28 14:59 UTC, merged

2023-07-28 14:59 UTC, boherm commented
Thanks for your work @LouisAUTHIE 😉

2023-07-28 15:01 UTC, LouisAUTHIE commented
Thanks for your understanding and approval