Fix: When updating object images, old thumbnails are not deleted and updated
PrestaShop/PrestaShop pull request #32493
Opened 2023-05-09 13:18 UTC by Codencode

Delete all thumbnails of the given objects after uploading an image in backoffice.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      |
| Type?             | bug fix
| Category?         | FO / BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #31809

2023-05-09 13:42 UTC, 0x346e3730 approved these changes, later dismissed
lgtm 👍

2023-05-09 14:25 UTC, kpodemski commented on classes/ObjectModel.php
> +            $configuredImageFormats = $imageFormatConfiguration->getGenerationFormats();
```suggestion
            $configuredImageFormats = $imageFormatConfiguration->getGenerationFormats();
```

2023-05-09 14:48 UTC, Codencode commented on classes/ObjectModel.php
> +            $configuredImageFormats = $imageFormatConfiguration->getGenerationFormats();
> 
Thanks @kpodemski!

2023-05-10 07:01 UTC, kpodemski submitted a review, later dismissed

2023-05-10 07:28 UTC, boherm approved these changes, later dismissed
LGTM, thanks @Codencode!

2023-05-11 11:07 UTC, Codencode commented
Do I need to do anything else?
Thanks

2023-05-11 12:43 UTC, boherm commented
Hi @Codencode!
No, we waiting for QA team to process tests on your PR.
When we have a GO, we will merge your work on 8.1.x branch!

2023-05-11 13:08 UTC, Codencode commented
@boherm, ok thanks!

2023-05-17 09:21 UTC, hibatallahAouadni commented
This PR will be tested when the issue is verified

2023-05-26 06:44 UTC, kpodemski commented
@hibatallahAouadni why is it taking so long to validate this issue? 🤔

2023-06-01 08:30 UTC, M0rgan01 approved these changes

2023-06-26 09:58 UTC, florine2623 reviewed
Hello @Codencode ,

Thanks for the PR ^^

The auto tests are green : https://github.com/florine2623/testing_pr/actions/runs/5374939290

I still have the issue.
Here are the steps I followed :
1. Use 8.1 and enable new image system. Set up jpg and webp formats.
2. Visit manufacturer page in FO so that all thumbs are generated.
3. Check /img/m/ folder and see that manufacturer X has images in all formats. :x:
4. Go to Design > Image Settings > Regenerate thumbnails for Brands 
5. Check /img/m/ folder and see that manufacturer X has images in all formats. ✅ 
6. Now go to BO and change the image of this manufacturer.
7. Check /img/m/ again and see that only JPG thumbnails were updated. :x:
8. Go to Design > Image Settings > Regenerate thumbnails for Brands 
9. Check /img/m/ again and see that only JPG thumbnails were updated. :x: 

https://github.com/PrestaShop/PrestaShop/assets/16019289/c5ef4c63-3b2c-4735-bef6-11af806d1b31




Am I missing something ?
Thanks ^^

2023-06-30 09:03 UTC, Codencode commented
> Hello @Codencode ,
> 
> Thanks for the PR ^^
> 
> The auto tests are green : https://github.com/florine2623/testing_pr/actions/runs/5374939290
> 
> I still have the issue. Here are the steps I followed :
> 
> 1. Use 8.1 and enable new image system. Set up jpg and webp formats.
> 2. Visit manufacturer page in FO so that all thumbs are generated.
> 3. Check /img/m/ folder and see that manufacturer X has images in all formats. ❌
> 4. Go to Design > Image Settings > Regenerate thumbnails for Brands
> 5. Check /img/m/ folder and see that manufacturer X has images in all formats. ✅
> 6. Now go to BO and change the image of this manufacturer.
> 7. Check /img/m/ again and see that only JPG thumbnails were updated. ❌
> 8. Go to Design > Image Settings > Regenerate thumbnails for Brands
> 9. Check /img/m/ again and see that only JPG thumbnails were updated. ❌
> 
>  Screen.Recording.2023-06-26.at.11.55.43.mov 
> Am I missing something ? Thanks ^^

Hello @florine2623,

I made the changes to make the changes work even in case of new image system.

Thank You.

2023-07-10 19:25 UTC, kpodemski approved these changes

2023-07-11 09:09 UTC, matks approved these changes
Thank you for the code update @Codencode

2023-07-11 11:24 UTC, M0rgan01 approved these changes

2023-07-11 13:23 UTC, Hlavtox requested changes
Hey @Codencode, one tiny issue I see. Are you sure that there will always be image formats configured?

I think that during generating, you should check if the feature is enabled and fallback to JPG, like we do in other places in the code.
```
$sfContainer = SymfonyContainer::getInstance();
if ($sfContainer->get('prestashop.core.admin.feature_flag.repository')->isEnabled(FeatureFlagSettings::FEATURE_FLAG_MULTIPLE_IMAGE_FORMAT)) {
  $configuredImageFormats = $sfContainer->get(ImageFormatConfiguration::class)->getGenerationFormats();
} else {
  $configuredImageFormats = ['jpg'];
}
```

And for deleting, we should delete `['jpg']` + `ImageFormatConfiguration::SUPPORTED_FORMATS`.

2023-07-11 14:10 UTC, florine2623 approved these changes
Hello @Codencode 

Link to auto tests OK : https://github.com/MhiriFaten/testing_pr/actions/runs/5519198537

I tested the PR, it is working as expected.
All thumbnails are regenerated with new image ✅ 

Waiting for your answer for @Hlavtox 's comment https://github.com/PrestaShop/PrestaShop/pull/32493#pullrequestreview-1524269051 before validating the PR ^^

2023-07-11 14:10 UTC, Codencode commented
> configuredImageFormats

Hi @Hlavtox,
The configuration always returns at least the JPG type, in fact in the image configuration section it is not possible to remove the flag from the "Base JPEG/PNG" type

I am attaching screenshots of the image configuration section.

Thank You.

![Screenshot 2023-07-11 at 16-06-03 Image Settings • Codenshop](https://github.com/PrestaShop/PrestaShop/assets/2463965/eac8f3d3-e1f8-4f47-bd3f-9c82132f8773)

2023-07-19 10:04 UTC, Hlavtox approved these changes

2023-07-19 10:05 UTC, Hlavtox commented
@Codencode OK, the value SHOULD be there. :-)

2023-07-19 10:05 UTC, merged