refacto choice provider
PrestaShop/PrestaShop pull request #32524
Opened 2023-05-10 17:33 UTC by FabienPapet

- Remove arguments with on translator and autowire everything.
- Update service names
- Update services 1/x
- Update services 2/x
- Update services 3/x
- Update services 4/x

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 8.1.x / 8.0.x / 1.7.8.x
| Description?      | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?             | bug fix / improvement / new feature / refacto
| Category?         | FO / BO / CO / IN / WS / TE / LO / ME / PM
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| How to test?      | Indicate how to verify that this change works as expected.
| Fixed ticket?     | Fixes #{issue number here}, Fixes #{another issue number here}
| Related PRs       | If theme, autoupgrade or other module change is needed to make this change work, provide a link to related PRs here.
| Sponsor company   | Your company or customer's name goes here (if applicable).

2023-05-12 07:42 UTC, zuk3975 commented on src/Core/Form/ChoiceProvider/LanguageChoiceProvider.php
> +    public function __construct(LanguageDataProvider $languageDataProvider)
you are relying on service from Adapter namespace, maybe it have interface to rely on?

2023-05-12 07:44 UTC, zuk3975 commented on src/PrestaShopBundle/Resources/config/services/core/localization.yml
> +  PrestaShop\PrestaShop\Core\Localization\RTL\StyleSheetProcessorFactory:
I prefer having `~` as it seems to be more readable. But its just my preference, not requesting to change it :man_shrugging: 
```suggestion
  PrestaShop\PrestaShop\Core\Localization\Pack\Loader\LocalLocalizationPackLoader: ~
  PrestaShop\PrestaShop\Core\Localization\Pack\Loader\RemoteLocalizationPackLoader: ~
  PrestaShop\PrestaShop\Core\Localization\RTL\StyleSheetProcessorFactory: ~
```

2023-05-12 07:45 UTC, zuk3975 requested changes
https://github.com/PrestaShop/PrestaShop/pull/32524/files#r1192023327

2023-05-12 10:58 UTC, FabienPapet commented on src/Core/Form/ChoiceProvider/LanguageChoiceProvider.php
> +    public function __construct(LanguageDataProvider $languageDataProvider)
Unfortunatly, it has not, and it would require to create a specifc interface for every provider that has not. Maybe it is a little bit out of scope of this PR.

WDYT ?

2023-05-12 11:02 UTC, zuk3975 commented on src/Core/Form/ChoiceProvider/LanguageChoiceProvider.php
> +    public function __construct(LanguageDataProvider $languageDataProvider)
if its out of scope then I think you should leave the array $languages here until we introduce some kind of provider in core.

2023-05-16 08:18 UTC, tleon submitted a review, later dismissed

2023-05-16 15:54 UTC, FabienPapet commented on src/PrestaShopBundle/Resources/config/services/core/localization.yml
> +  PrestaShop\PrestaShop\Core\Localization\RTL\StyleSheetProcessorFactory:
I'll use service discovery in another PR as done in the form type PR, so this may not be needed right now. WDYT ?

2023-05-17 08:24 UTC, boherm approved these changes

2023-05-17 15:09 UTC, FabienPapet commented
@zuk3975 I reverted the changes, might be good now :)

2023-05-29 12:51 UTC, zuk3975 approved these changes

2023-05-29 13:56 UTC, FabienPapet commented
tests:
https://github.com/FabienPapet/ga.tests.ui.pr/actions/runs/5112590399

2023-05-30 11:46 UTC, FabienPapet commented
Tests auto ok the only one failing is not linked to this PR but this one : https://github.com/PrestaShop/PrestaShop/issues/32734

2023-05-30 11:47 UTC, merged