Update checkOrGenerateImageType $sourceFilePath
PrestaShop/PrestaShop pull request #32597
Opened 2023-05-16 15:50 UTC by M0rgan01

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Image generation always takes the original file (cover), regardless of the type of image
| Type?             | bug fix / improvement / new feature / refacto
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See #32404
| Fixed ticket?     | #32404
| Related PRs       | -
| Sponsor company   | -

2023-05-17 08:20 UTC, boherm approved these changes, later dismissed
LGTM, thanks @M0rgan01!

2023-05-17 09:04 UTC, mflasquin approved these changes, later dismissed
Seems good, but $originalImagePath variable defined in line 187 is not used anymore ?

2023-05-17 09:06 UTC, mflasquin commented
UI tests : https://github.com/mflasquin/ga.tests.ui.pr/actions/runs/5001392233

2023-05-17 12:26 UTC, M0rgan01 commented
> Seems good, but $originalImagePath variable defined in line 187 is not used anymore ?

@mflasquin you are right, it is no longer used. I removed it

2023-05-19 09:11 UTC, florine2623 reviewed
Hello @M0rgan01 ,

Tests autos are green : https://github.com/florine2623/testing_pr/actions/runs/5022232806

I have well installed your PR.
But when I check the category image folder, I don't have the right extension on the files.

I still have the following reported on the issue :
9. The `img/c/{idCategory}/{idCategory}-0_thumb.webp` doesn't exist => ERROR 

<img width="247" alt="Screenshot 2023-05-19 at 11 07 15" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/3108e686-7be6-4d7b-a730-f05500b30d33">

Here I should have one more file called `11-0_thumb.webp`

Am I missing something ?
Thanks^^

2023-05-19 13:36 UTC, M0rgan01 commented
Hi @florine2623 :smile:  Good remark ! 

Currently the generation of wepP images for categories is executed when displaying on FO.

If the FO does not display the image, it will not be generated! And this is the case for the thumbnails.

The issue https://github.com/PrestaShop/PrestaShop/issues/30520 talks about it

>  - Menu thumbnail
>    - Not used in classic theme right now at all.
>    - Not provided in FO $category object at all.

2023-05-20 08:16 UTC, Hlavtox commented
Yep, as @M0rgan01 says, there is no way to access the thumbnails in FO until that issue is resolved.

Wr don't even have a way of defining sizes for these images, unfortunately. image_type table structure needes to be modified.

2023-05-22 14:56 UTC, boherm submitted a review, later dismissed

2023-05-22 15:42 UTC, Hlavtox submitted a review, later dismissed
This is not correct fix, it generates a thumbnail from a thumbnail, completely breaking the logic.

It must use the original image to generate it.

Related issue is not caused by ImageRetriever but by some backoffice logic. ImageRetriever is used for FO and it can properly generate all images with a tiny modification.

2023-05-22 16:32 UTC, M0rgan01 commented
> This is not correct fix, it generates a thumbnail from a thumbnail, completely breaking the logic.
> It must use the original image to generate it.

If the Category cover image is totally different than the Category thumbnail image, we are not going to use the cover image to generate the thumbnail image?

2023-05-22 20:14 UTC, Hlavtox commented
@M0rgan01 No, they are a different image, we are currently discussing the best way to structure it.

It should look like this:

- Original image for cover - `/img/c/1.jpg`, working
- Original image for thumbnail - `/img/c/1_thumb.jpg`, working
- Resized image(s) for cover - `/img/c/1-category_default.jpg`, working
- Resized image(s) for thumbnail - `/img/c/1_thumb-category_default.jpg`. Currently broken, backoffice is generating it as `/img/c/3-small_default.jpg` overwriting the cover image miniature.

2023-05-23 07:39 UTC, M0rgan01 commented
@Hlavtox Yes I understood :smiley: 

The problem comes from the generation of webP files which systematically take the original cover image as a basis.

If my cover image is a :dog: , and my thumbnail is a :cat: , when I go to the FO, the webP generation of my cover will be good (:dog: ), but my thumbnail will also be a :dog: 

:crying_cat_face:

2023-05-23 08:55 UTC, Hlavtox commented
> The problem comes from the generation of webP files which systematically take the original cover image as a basis.

This is correct, it must use the original image.

> If my cover image is a 🐶 , and my thumbnail is a 🐱 , when I go to the FO, the webP generation of my cover will be good (🐶 ), but my thumbnail will also be a 🐶

Yes, but the solution is to use 🐱 (1_thumb.jpg), not a miniature of a 🐶(1-category_default.jpg) ;-)

2023-05-23 15:18 UTC, M0rgan01 commented
I was fooled... The base dataset does not create a `_thumb.jpg` file, so I did without

![image](https://github.com/PrestaShop/PrestaShop/assets/36233446/704a400b-b6bf-4548-905e-0d1f6844a16e)

I pushed new commit @Hlavtox :dog: Thank you for the explanations

2023-06-26 16:24 UTC, tleon submitted a review, later dismissed

2023-06-27 07:30 UTC, kpodemski submitted a review, later dismissed

2023-06-27 08:33 UTC, matthieu-rolland approved these changes, later dismissed

2023-06-27 10:01 UTC, boherm approved these changes, later dismissed

2023-06-28 15:27 UTC, florine2623 commented
Hello @M0rgan01 ,

Could you rebase your PR so that the automated tests can pass on it ?
Thanks!

2023-06-28 15:53 UTC, M0rgan01 commented
Auto tests https://github.com/M0rgan01/ga.tests.ui.pr/actions/runs/5403189587

2023-06-29 08:22 UTC, Progi1984 requested changes
@M0rgan01 Could you enable UI tests in `UI/campaigns/functional/BO/08_design/06_imageSettings/14_checkCategoryImageFormat.ts` ? It's commented. You can find them with `// @todo : https://github.com/PrestaShop/PrestaShop/issues/32404`

2023-06-29 09:32 UTC, M0rgan01 commented
Auto tests: https://github.com/M0rgan01/ga.tests.ui.pr/actions/runs/5410684680

2023-06-29 13:09 UTC, M0rgan01 commented
Tests: https://github.com/M0rgan01/ga.tests.ui.pr/actions/runs/5412404512

2023-06-29 13:47 UTC, Progi1984 commented on tests/UI/campaigns/functional/BO/08_design/06_imageSettings/14_checkCategoryImageFormat.ts
>            // Check the WebP file
```suggestion
          // @todo : https://github.com/PrestaShop/PrestaShop/issues/32404
          // Check the WebP file
```

2023-06-29 14:09 UTC, Progi1984 approved these changes, later dismissed

2023-07-05 06:41 UTC, mflasquin approved these changes, later dismissed

2023-07-05 07:09 UTC, Hlavtox reviewed
Are you sure this is going to work properly?

If I understand correctly, when image thumbnail name is `small_default`, it's gonna take `$id_image . '_thumb.jpg'` as a source.

So this will break `small_default` thumbnails for all other objects other than category, because only category has `ID_thumb.jpg` images. It was a hackjob before, but this is not better. All thumbnails MUST contain the same image.

2023-07-06 10:24 UTC, sallemiines reviewed
Hello @M0rgan01 
Thanx fo the PR 

[Tests autos](https://github.com/sallemiines/ga.tests.ui.pr/actions/runs/5464559945/jobs/9946757343) OK 

- The img/c/{idCategory}/{idCategory}-category_default.webp doesn't exist => ERROR (Cover)
- The img/c/{idCategory}/{idCategory}-0_thumb.webp doesn't exist => ERROR (Thumb)
- The img/c/{idCategory}/{idCategory}-small_default.webp doesn't exist => ERROR (Menu)

When I go on the front office

- The img/c/{idCategory}/{idCategory}-category_default.webp exist => OK 
- The img/c/{idCategory}/{idCategory}-0_thumb.webp doesn't exist => Nok
- The img/c/{idCategory}/{idCategory}-small_default.webp OK
- img/c/{idCategory}/{idCategory}-small_default.jpg => OK 



**Result of /img/c after creating a new Ctegory** 
![image](https://github.com/PrestaShop/PrestaShop/assets/31663369/22efb431-7f3d-41e5-9999-e66e1cc2d855)



**Result of img/c after going to FO** 

![image](https://github.com/PrestaShop/PrestaShop/assets/31663369/f1d20cb2-ee58-417d-b052-b6ff774fe1d1)

https://github.com/PrestaShop/PrestaShop/assets/31663369/c18a5640-1db3-430b-a360-fae76f4db87b

Please check and feedback ! 
Thank you !

2023-07-07 09:56 UTC, M0rgan01 commented
@Hlavtox I adjusted the condition for categories. I also think this should be made generic for all image types, but for now I have a quick fix for v8. We will be able to review the way to generate the images of the categories in FO and BO in v9.

@sallemiines As mentioned above, it is not possible to generate the image for the point "The img/c/{idCategory}/{idCategory}-0_thumb.webp doesn't exist => Nok". https://github.com/PrestaShop/PrestaShop/pull/32597#issuecomment-1554588279

2023-07-10 19:24 UTC, kpodemski approved these changes

2023-07-11 13:24 UTC, Hlavtox commented
@M0rgan01 This should be good brother, I think it's good enough for v8.1.

We can do it properly for v9. :-) https://github.com/PrestaShop/PrestaShop/issues/30520

Don't worry about the thumbnails, they never worked and not even accessible in FO.

2023-07-11 13:25 UTC, Hlavtox approved these changes

2023-07-11 13:25 UTC, Hlavtox commented
@sallemiines Ines, you can retest it. :-) 
Don't worry about `The img/c/{idCategory}/{idCategory}-0_thumb.webp doesn't exist => Nok`

2023-07-11 13:30 UTC, nesrineabdmouleh approved these changes

2023-07-18 14:16 UTC, florine2623 approved these changes
Hello @M0rgan01 ,

After regenerating the images in Design > Image Settings > Regenerate thumbnails > Categories

Here's what I have :
<img width="205" alt="Screenshot 2023-07-18 at 16 11 26" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/5e27d6a1-716e-4edf-9603-e63d7201d35e">

✅ The img/c/{idCategory}/{idCategory}-category_default.webp doesn't exist => ERROR (Cover)
✅ https://github.com/PrestaShop/PrestaShop/pull/32597#issuecomment-1630830849 The img/c/{idCategory}/{idCategory}-0_thumb.webp doesn't exist => ERROR (Thumb)
✅ The img/c/{idCategory}/{idCategory}-small_default.webp doesn't exist => ERROR (Menu)

✅ The img/c/{idCategory}/{idCategory}-category_default.webp exist => OK (Cover)
✅ https://github.com/PrestaShop/PrestaShop/pull/32597#issuecomment-1630830849 The ✅ img/c/{idCategory}/{idCategory}-0_thumb.webp doesn't exist => ERROR (Thumb)
✅ The img/c/{idCategory}/{idCategory}-small_default.webp exist but it's not the webp version of img/c/{idCategory}/{idCategory}-small_default.jpg => ERROR (Menu)

It is QA ✅ 
Thanks all for the details about the PR

2023-07-18 14:36 UTC, mflasquin commented
thanks @M0rgan01

2023-07-18 14:36 UTC, merged