fix(ci) backport fixes to github action template from develop
PrestaShop/PrestaShop pull request #32777
Opened 2023-05-31 15:31 UTC by tleon

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x 
| Description?      | This PR is fixing the table generated by the github action Cron Update PHP Modules.
| Type?             |  improvement 
| Category?         |  PM
| BC breaks?        |  no
| Deprecations?     |  no
| How to test?      | Restart the github action Cron Update PHP Modules and check the PR opened by the bot
| Fixed ticket?     | Fixes #32585
| Related PRs       | N/A
| Sponsor company   | Prestashop

2023-05-31 15:35 UTC, matks approved these changes

2023-05-31 15:36 UTC, matks requested changes
You have git conflicts :(

2023-05-31 15:45 UTC, kpodemski approved these changes

2023-05-31 16:02 UTC, M0rgan01 approved these changes

2023-05-31 16:03 UTC, M0rgan01 commented on .github/workflows/cron_update_modules/script.php
> +    $pullRequestBodyBumpModules .= 'Module `' . $moduleName. '`: Bump version from `' . $moduleVersion
It's automatic formatting ? Same question for the changes above

2023-06-01 06:34 UTC, tleon commented on .github/workflows/cron_update_modules/script.php
> +    $pullRequestBodyBumpModules .= 'Module `' . $moduleName. '`: Bump version from `' . $moduleVersion
yes

2023-06-01 06:36 UTC, merged