Changed error code when access token is invalid
PrestaShop/PrestaShop pull request #32842
Opened 2023-06-06 13:14 UTC by nicosomb

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x 
| Description?      | Replaced error code (`500` to `401`) when access token is invalid
| Type?             | bug fix 
| Category?         | BO 
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See #32768
| Fixed ticket?     | Fixes #32768
| Related PRs       | ~
| Sponsor company   | PrestaShop SA

2023-06-06 13:14 UTC, tleon approved these changes, later dismissed

2023-06-06 13:17 UTC, 0x346e3730 requested changes

2023-06-06 13:17 UTC, 0x346e3730 commented on app/config/api_platform/resources.yml
> +          Lcobucci\JWT\Token\InvalidTokenStructure: 401
It will only apply to `PrestaShopBundle\Api\Resource\HookStatus` and we don't want to repeat it everywhere

2023-06-06 13:32 UTC, 0x346e3730 approved these changes

2023-06-06 14:30 UTC, tleon approved these changes

2023-06-06 14:33 UTC, M0rgan01 approved these changes

2023-06-06 14:45 UTC, boherm approved these changes

2023-06-06 20:32 UTC, matks approved these changes

2023-06-09 10:10 UTC, djoelleuch approved these changes
Hello @nicosomb  , 

It's QA approved :heavy_check_mark:
Automated tests --> OK (https://github.com/djoelleuch/ga.tests.ui.pr/actions/runs/5220375254) 

![image](https://github.com/PrestaShop/PrestaShop/assets/115152460/bf1d7576-f313-409d-9d47-6550daa860e2)

Thank you for you PR :rocket:

2023-06-09 12:24 UTC, matthieu-rolland commented
thank you @nicosomb and @djoelleuch

2023-06-09 12:24 UTC, merged