feat(api-platform): api platform documentation spike
PrestaShop/PrestaShop pull request #32860
Opened 2023-06-07 16:23 UTC by tleon

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Spike for the api platform documentation.
| Type?             |  new feature 
| Category?         | BO 
| BC breaks?        |  no
| Deprecations?     |  no
| How to test?      | Install the assets with make assets > log in the BO > go to /new-api/docs
| Fixed ticket?     | Fixes #32581
| Related PRs       | N/A
| Sponsor company   | Prestashop

2023-06-09 07:48 UTC, matks reviewed
CI is red please fix it 😉

2023-06-13 11:33 UTC, M0rgan01 commented on tools/assets/build.sh
> +
No space needed here

2023-06-16 08:15 UTC, FabienPapet requested changes

2023-06-16 08:15 UTC, FabienPapet commented on .gitignore
> +# Api plateform assets
```suggestion
# Api platform assets
```

2023-06-16 08:15 UTC, FabienPapet commented on src/PrestaShopBundle/ApiPlatform/Resources/Hook.php
> +                        'description' => 'this is a description of the parameter',
👀

2023-06-20 14:14 UTC, FabienPapet approved these changes

2023-06-20 15:28 UTC, M0rgan01 approved these changes

2023-06-20 16:35 UTC, boherm approved these changes

2023-06-21 12:05 UTC, FabienPapet approved these changes

2023-06-21 12:07 UTC, paulnoelcholot commented
Hello @tleon,

I tested your PR and it's OK for me! :tada: 

Thanks!

2023-06-21 12:07 UTC, paulnoelcholot approved these changes

2023-06-21 12:17 UTC, merged