Fix invalid token in redirection after editing himself
PrestaShop/PrestaShop pull request #32861
Opened 2023-06-07 16:48 UTC by boherm

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix invalid token on redirection when we self editing in BO team page.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See #32734 
| Fixed ticket?     | Fixes #32734 
| Related PRs       | 
| Sponsor company   |

2023-06-07 19:55 UTC, matks submitted a review, later dismissed

2023-06-08 08:33 UTC, boherm commented
Autotests: https://github.com/boherm/ga.tests.ui.pr/actions/runs/5209127826

2023-06-08 08:34 UTC, matks approved these changes, later dismissed

2023-06-08 09:10 UTC, kpodemski approved these changes, later dismissed

2023-06-08 09:45 UTC, jolelievre requested changes
Blocked temporarily, we discussed a lot about this with boris just some important comments to add because this will need to be improved/refactored when we handle the authentication via Symfony

2023-06-09 07:51 UTC, jolelievre approved these changes
Thanks @boherm

2023-06-09 08:06 UTC, nicosomb approved these changes

2023-06-12 10:20 UTC, MhiriFaten approved these changes
Hello @boherm ,

I have checked your PR,
The issue is well resolved and the token has been fixed when changing email address in profile page.

Automated tests are OK.

It is QA approved :heavy_check_mark: 

Thank you !

2023-06-12 10:26 UTC, merged