Merge `8.1.x` into `develop`
PrestaShop/PrestaShop pull request #32870
Opened 2023-06-09 08:40 UTC by boherm

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Merge `8.1.x` into `develop`
| Type?             | improvement
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI ⏳ & Autotests ⏳
| Fixed ticket?     | n/a
| Related PRs       | n/a
| Sponsor company   | PrestaShopSA

2023-06-09 08:45 UTC, matks submitted a review, later dismissed

2023-06-09 08:47 UTC, nicosomb approved these changes, later dismissed

2023-06-09 09:18 UTC, tleon approved these changes, later dismissed

2023-06-15 08:38 UTC, nicosomb approved these changes, later dismissed

2023-06-15 15:00 UTC, nicosomb submitted a review, later dismissed

2023-06-15 17:35 UTC, mflasquin submitted a review, later dismissed

2023-06-16 09:52 UTC, jolelievre approved these changes, later dismissed

2023-06-16 12:39 UTC, matks submitted a review, later dismissed

2023-06-16 12:58 UTC, PululuK submitted a review, later dismissed

2023-06-16 13:27 UTC, Progi1984 requested changes
It seems autotests are :red_circle: 

Link : https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/5288724896

2023-06-28 15:31 UTC, jolelievre commented
This one must be re-made because of the recent fixes on UI/nightly tests

2023-06-28 15:31 UTC, closed without merging

2023-06-29 16:30 UTC, boherm commented
This PR is recreated https://github.com/PrestaShop/PrestaShop/pull/33053.