Added www-authenticate: bearer if the access token is invalid
PrestaShop/PrestaShop pull request #32885
Opened 2023-06-12 12:51 UTC by nicosomb

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x 
| Description?      | Returns a header WWW-Authenticate : Bearer if the access token is invalid
| Type?             | bug fix 
| Category?         | WS 
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | https://github.com/PrestaShop/PrestaShop/issues/32882
| Fixed ticket?     | Fixes #32882
| Related PRs       | ~
| Sponsor company   | PrestaShop SA

2023-06-12 13:01 UTC, nicosomb commented
Tests https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/5243891797

2023-06-12 13:02 UTC, Progi1984 commented on tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/02_externalAuthServer/02_resourceEndpoint.ts
>      // @todo : https://github.com/PrestaShop/PrestaShop/issues/32768
```suggestion
```

2023-06-12 17:19 UTC, mflasquin approved these changes, later dismissed

2023-06-12 18:38 UTC, Progi1984 requested changes
The CI is :red_circle:

2023-06-13 09:04 UTC, jolelievre approved these changes, later dismissed
Thanks @nicosomb

2023-06-14 14:45 UTC, M0rgan01 submitted a review, later dismissed

2023-06-15 14:54 UTC, boherm approved these changes, later dismissed

2023-06-15 14:54 UTC, nicosomb commented
Tests https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/5280351396

2023-06-15 15:20 UTC, nicosomb commented
Test https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/5280636880

2023-06-15 15:51 UTC, djoelleuch commented
Hello @nicosomb , 
some checks were not successful , could you please check it  .

2023-07-11 07:29 UTC, Progi1984 commented
UI Test : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/5517067057

2023-07-24 09:23 UTC, nicosomb commented
UI tests   https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/5643118513

2023-07-24 10:52 UTC, Progi1984 approved these changes
Approved for UI tests (Unskip the test as defined in Acceptance Test and UI tests are :green_circle:)

Ping @PrestaShop/ui-tests-maintainers

2023-07-24 11:12 UTC, nesrineabdmouleh approved these changes

2023-07-24 13:25 UTC, M0rgan01 approved these changes

2023-07-24 14:45 UTC, mflasquin approved these changes

2023-07-27 12:02 UTC, djoelleuch approved these changes
Hello @nicosomb , 

I have tested your PR and it's well fixed !

[Untitled_ Jul 27, 2023 1_57 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/0b5af7a3-ea7c-4ed2-8765-d8b0a5a2b302)


automated tests : OK 
It's QA approved :heavy_check_mark:
Thank you :rocket:

2023-07-27 12:05 UTC, Progi1984 commented
Congrats @nicosomb : Never give up ;)

2023-07-27 13:04 UTC, matthieu-rolland commented
thank you @nicosomb and @djoelleuch

2023-07-27 13:05 UTC, merged