Nightly : 1.7.8.x - Move to Github Actions
PrestaShop/PrestaShop pull request #32893
Opened 2023-06-13 09:59 UTC by Progi1984

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Nightly : 1.7.8.x - Move to Github Actions
| Type?             | improvement
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI is :green_circle: & Nightly is :green_circle: 
| Fixed ticket?     | N/A
| Related PRs       | N/A
| Sponsor company   | @PrestaShopCorp

2023-06-13 13:22 UTC, boubkerbribri commented on .docker/Dockerfile
>  FROM prestashop/prestashop-git:$VERSION
```suggestion
FROM prestashop/base:$VERSION
```

2023-06-13 13:22 UTC, boubkerbribri commented on .docker/Dockerfile
>  FROM prestashop/prestashop-git:$VERSION
to make it work on ga.ui.tests.pr

2023-06-14 09:14 UTC, Progi1984 commented on .docker/Dockerfile
>  FROM prestashop/prestashop-git:$VERSION
No need. That works.

2023-06-15 06:56 UTC, boubkerbribri requested changes
Need to remove files on UI tests folder :
- .docker
- scripts (gcp scripts)

2023-06-15 15:41 UTC, boubkerbribri approved these changes

2023-06-16 07:30 UTC, jolelievre approved these changes

2023-06-16 07:30 UTC, merged