Nightly : Move 1.7.8.x to Github Actions
PrestaShop/PrestaShop pull request #32891
Opened 2023-06-13 09:49 UTC by Progi1984

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Nightly : Move 1.7.8.x to Github Actions
| Type?             | improvement
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | N/A
| Fixed ticket?     | N/A
| Related PRs       | N/A
| Sponsor company   | @PrestaShopCorp

2023-06-14 09:54 UTC, boubkerbribri requested changes, later dismissed
Need to remove files on UI tests folder : 
- .docker
- scripts (gcp scripts)

2023-06-14 11:34 UTC, Progi1984 commented
@boubkerbribri Already removed in develop.

2023-06-15 06:57 UTC, boubkerbribri commented
> @boubkerbribri Already removed in develop.

Wrong PR commented

2023-06-15 15:46 UTC, boherm approved these changes

2023-06-16 07:29 UTC, jolelievre approved these changes

2023-06-16 07:29 UTC, merged