Fix disabling a module for a specific shop applied to all shops
PrestaShop/PrestaShop pull request #32938
Opened 2023-06-19 09:22 UTC by nicosomb

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | when disabling a module, the query must specify id shops if we don't want to disable the module for all shops
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      |  See steps in issue #30262 Also make sure that the change doesn't have side effects when the shop didn't enable multishop (enable/disable module feature should still work properly)
| Fixed ticket?     | Fixes #30262 / #32211 (to be verified)
| Related PRs       | none
| Sponsor company   | PrestaShop SA

2023-06-19 09:23 UTC, nicosomb commented
Tests https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/5310130831

2023-06-19 15:09 UTC, jolelievre requested changes
This should target the release branch

2023-06-19 16:22 UTC, nesrineabdmouleh approved these changes

2023-06-20 09:08 UTC, matthieu-rolland approved these changes

2023-06-20 10:14 UTC, closed without merging