getShopLogo remove hasKey usage
PrestaShop/PrestaShop pull request #32941
Opened 2023-06-19 12:10 UTC by cruftex

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Remove usage of `Configuraton::hasKey` in FrontController. This serves as a starting point for potentially remove this at other places as well
| Type?             | bug fix + refacto
| Category?         | FO / BO / CO / IN / WS / TE / LO / ME / PM
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | I hope that this is covered by automated tests
| Fixed ticket?     | partial, https://github.com/PrestaShop/PrestaShop/issues/30373
| Related PRs       | 
| Sponsor company   | headissue GmbH

2023-06-19 12:25 UTC, cruftex commented
I just realise that it should be:

````
        $logoFileName = Configuration::get('PS_LOGO');
        if (!$logoFileName) {
            return [];
        }
````

Since the default is `false` when the configuration is not present. That should be caught by the automated tests, let's see whether the tests are running without a logo at all.

The default being `false` is actually quite unexpected. For getting an arbitrary configuration item, I would expect the default being `null` if it is not present.

2023-06-19 12:35 UTC, Hlavtox submitted a review, later dismissed

2023-06-19 18:46 UTC, kpodemski submitted a review, later dismissed

2023-06-21 09:40 UTC, mflasquin reviewed
hasKey is also used in getTemplateVarShop function in FrontController. Maybe you can try to change also here.

2023-06-21 11:40 UTC, cruftex commented
@mflasquin
If someone actually intends to read the value, it is not effective to check first.

`hasKey` has two bugs: it does not load the configuration, it does not take into account the shop context. If `hasKey` would be fixed, it is basically doing almost the same as `get`.

The `FrontController` is basically the only user of `hasKey` and those usages can be easily removed. However, I wanted to start with an obvious and reasonable small change.

2023-06-22 13:21 UTC, mflasquin requested changes, later dismissed

2023-06-22 13:21 UTC, mflasquin commented on classes/controller/FrontController.php
> +    }
```suggestion
    private static function configuredImageUrl(string $configKey, $psImageUrl) 
    {
        $image = Configuration::get($configKey);
        
        return $image ? $psImageUrl . $image : '';
    }
```

2023-06-23 12:44 UTC, cruftex commented on classes/controller/FrontController.php
> +    }
This is fixed now.

2023-07-07 20:31 UTC, kpodemski approved these changes

2023-08-04 06:44 UTC, nicosomb approved these changes

2023-08-04 15:29 UTC, boherm approved these changes

2023-08-07 09:40 UTC, hibatallahAouadni commented
@PrestaShop/committers as the related issue to this PR need to be reproduced by a Developer, I will put the waiting for Dev to this PR, to be tested by a Dev 😉

2023-08-15 09:34 UTC, sallemiines approved these changes
Hello @cruftex 

Thanx for the PR ! LGTM QA :heavy_check_mark: 
[Tests](https://github.com/aniszr/ga.tests.ui.pr/actions/runs/5864903899) OK 

Thank you

2023-08-17 14:18 UTC, matks commented
Thank you @cruftex

2023-08-17 14:18 UTC, merged