Update changelog
PrestaShop/PrestaShop pull request #32957
Opened 2023-06-20 12:19 UTC by matthieu-rolland

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.0-build1
| Description?      | update changelog
| Type?             | improvement
| Category?         | 
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | no code modified, nothing to test
| Fixed ticket?     | 
| Related PRs       | 
| Sponsor company   | PrestaShop SA

2023-06-20 12:21 UTC, mflasquin approved these changes

2023-06-20 12:35 UTC, FabienPapet approved these changes

2023-06-20 14:11 UTC, jolelievre requested changes

2023-06-20 14:11 UTC, jolelievre commented on composer.json
> +        "prestashop/psgdpr": "^2",
No the version 2 is not ready yet and only has pre-releases!!!

2023-06-20 15:00 UTC, jolelievre approved these changes

2023-06-20 16:33 UTC, boherm approved these changes

2023-06-23 08:36 UTC, M0rgan01 approved these changes

2023-06-23 15:05 UTC, merged