Functional tests - Add new test 'Multistore > Edit url options'
PrestaShop/PrestaShop pull request #33105
Opened 2023-07-04 15:06 UTC by nesrineabdmouleh

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add new test 'Multistore > Edit url options'
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | UI tests => 
| Fixed ticket?     | no
| Related PRs       | 
| Sponsor company   |

2023-07-05 07:53 UTC, Progi1984 commented on tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/01_CRUDShopGroups.ts
> +import {disableMultiStoreTest, enableMultiStoreTest} from '@commonTests/BO/advancedParameters/multistore';
Change it by a `setMultiStoreStatus` (like `setWebserviceStatus`)

2023-07-05 07:54 UTC, Progi1984 requested changes
A important change for keeping consistency

2023-07-17 12:03 UTC, Progi1984 approved these changes, later dismissed

2023-07-17 12:59 UTC, boherm submitted a review, later dismissed

2023-07-18 07:53 UTC, boubkerbribri approved these changes, later dismissed

2023-07-18 13:06 UTC, Progi1984 approved these changes

2023-07-18 16:34 UTC, boherm approved these changes

2023-07-19 08:38 UTC, boubkerbribri approved these changes

2023-07-19 09:20 UTC, merged