Improve `Product::getPriceStatic` cache key
PrestaShop/PrestaShop pull request #33215
Opened 2023-07-11 15:16 UTC by PululuK

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Improve `Product::getPriceStatic` cache key.
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Test green
| Fixed ticket?     | N/A
| Related PRs       | N/A.
| Sponsor company   | Evolutive group

2023-07-11 15:33 UTC, kpodemski requested changes
Is it needed? The query below doesn't do anything with combinations.

2023-07-11 20:35 UTC, Hlavtox approved these changes, later dismissed

2023-08-09 13:44 UTC, matks requested changes
If I am not wrong, the parameter `$id_product_attribute` is not used at all inside `getPriceStatic()` ; it's a useless parameter 🤔

2024-02-25 19:31 UTC, kpodemski commented
Since we have had no news from you for more than 20 days, I'm closing this PR. Feel free to re-open it if you find the motivation to finish it. Don't hesitate to ping me if you have any questions or doubts.

2024-02-25 19:31 UTC, closed without merging