SymfonyContainer::getInstance() null in webservice Image/Product delete
PrestaShop/PrestaShop pull request #33226
Opened 2023-07-12 10:06 UTC by alexll

When deleting Image or Product with images using the webservice SymfonyContainer::getInstance() is null.

Commit solves issue #32897

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | SymfonyContainer::getInstance() is null in webservice Image delete and webservice Product delete. When deleting Image or Product with images using the webservice SymfonyContainer::getInstance() is null. Commit solves issue #32897
| Type?             | bug fix
| Category?         | WS
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Delete product image or product with images using the webservice
| Fixed ticket?     | Fixes #32897
| Related PRs       | 
| Sponsor company   |

2023-07-12 10:22 UTC, boherm requested changes
Hi @alexll! Thanks for you contribution!

I'm not really sure about your PR, I think we must find first of all why the `SymfonyContainer` is null before doing such conditions everywhere.
What do you think about it? :)

2023-07-12 10:22 UTC, boherm commented on classes/Image.php
> +	        $isMultipleImageFormatFeatureEnabled = false;
You must still use `FeatureFlagStateCheckerInterface` to retrieve the right state of the feature flag.
In fact, if you use the repository, you only retrieve the state in database, but now in `develop` branch, you can set feature flag states with env, dotenv or databse. So you must use the state checker to be sure to retrieve the right state.

2023-07-12 10:22 UTC, boherm commented on classes/Image.php
> +	        $configuration = $sfContainer->get('prestashop.adapter.legacy.configuration');
We are avoid this string to get service from the container.
For `prestashop.adapter.legacy.configuration`, you can use instead:
```suggestion
	        $configuration = $sfContainer->get(Configuration::class);
```
Don't forget to add `use PrestaShop\PrestaShop\Adapter\Configuration` at the top of this file.

2023-07-13 09:08 UTC, alexll commented
Thank's for the review @boherm!

SymfonyContainer is null due to that the call initiated form webservice and kernel is not loaded in this legacy system.

You can find more details in issue #20740 and a possible solution in the pull https://github.com/PrestaShop/PrestaShop/pull/26205 but seems it was dismissed in https://github.com/PrestaShop/PrestaShop/pull/26205#pullrequestreview-830170348

Maybe someone with more expertise in symfony services can contribute a better solution.

2023-08-01 05:04 UTC, Hlavtox requested changes
Hi, we cant just NOT delete the images if the container is not available, we must find another solution. :-)

2023-08-09 13:54 UTC, matks reviewed
For the record https://github.com/PrestaShop/PrestaShop/pull/24403 introduced a boot of the kernel for every Webservice request (I was not very happy about that 😄 ) and an optimization was added in https://github.com/PrestaShop/PrestaShop/pull/27766

But in this PR there is something that puzzles me 🤔 : is the container `every time` or are there usecases where it is null and usecases where it is not null?

2023-08-17 09:27 UTC, alexll commented
Container is only null when called from a webservice request. 

When functions are called using the back office it works as expected.

As you mentioned the kernel is not initialised when using webservices.

A similar fix like https://github.com/PrestaShop/PrestaShop/pull/27766 should be applied for Images .

2023-08-17 12:10 UTC, Hlavtox commented
The issue will be fixed by https://github.com/PrestaShop/PrestaShop/pull/33407, if somebody approves the PR and it gets merged

2024-01-03 11:15 UTC, closed without merging