Simplify `Cart::hasProducts` query
PrestaShop/PrestaShop pull request #33222
Opened 2023-07-11 18:28 UTC by PululuK

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Simplify `Cart::hasProducts` query.
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Test Green
| Fixed ticket?     | N/A
| Related PRs       | N/A
| Sponsor company   | Evolutive.

2023-07-11 19:28 UTC, Hlavtox requested changes
Behaviour change, blocking until investigated. It will now return true even if it contains a deleted product.

2023-07-12 11:33 UTC, FabienPapet approved these changes

2023-07-18 11:21 UTC, kpodemski requested changes
I agree with @Hlavtox. Imagine this scenario:
- you have a multishop with two shops
- you have a cart with Product A and Product B
- Product A and Product B are both available in two shops
- You can delete product B from some shop, this query will still return `true` whereas the previous one would return `false`

2024-02-25 19:31 UTC, kpodemski commented
Since we have had no news from you for more than 20 days, I'm closing this PR. Feel free to re-open it if you find the motivation to finish it. Don't hesitate to ping me if you have any questions or doubts.

2024-02-25 19:31 UTC, closed without merging