Module Status Button Not Reflecting Correct Status
PrestaShop/PrestaShop pull request #33289
Opened 2023-07-18 12:48 UTC by M0rgan01

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | To make the mobile labels appear correctly, you must change the order of the actions
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See  #33063, tests are green
| Fixed ticket?     | Fixes #33063
| Related PRs       | -
| Sponsor company   | -

2023-07-18 14:57 UTC, mflasquin approved these changes

2023-07-18 16:33 UTC, boherm approved these changes

2023-07-19 09:32 UTC, Hlavtox requested changes
This is a correct behavior that has been fixed on 8.1.
Enable on mobile/Disable on mobile should be in the dropdown.

Ping @kpodemski

2023-07-19 09:33 UTC, kpodemski commented
Yes, we're going back and forth with this + enable/disable on mobile is removed on v9.

2023-07-19 13:45 UTC, M0rgan01 commented
@kpodemski @Hlavtox Ok thanks, I didn't know, I saw the verified tag on the ticket so for me it was good ^^ I'll close

2023-07-19 13:45 UTC, closed without merging