Change translation key when enable/disable/delete product
PrestaShop/PrestaShop pull request #33296
Opened 2023-07-18 14:49 UTC by mflasquin

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Change translation key when enable/disable/delete product. Additional translation to finish to fix the issue #31778 after the PR https://github.com/PrestaShop/PrestaShop/pull/32993. Ping @MatShir 
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See https://github.com/PrestaShop/PrestaShop/issues/31778
| Fixed ticket?     | Fixes #31778 
| Related PRs       | https://github.com/PrestaShop/PrestaShop/pull/32993
| Sponsor company   | Prestasop SA

2023-07-18 14:58 UTC, MatShir requested changes, later dismissed
Could you target 8.1.x ? 🙏

2023-07-18 15:08 UTC, mflasquin commented
> Could you target 8.1.x ? pray

The last PR was targetting develop : https://github.com/PrestaShop/PrestaShop/pull/32993

2023-07-18 15:10 UTC, nicosomb submitted a review, later dismissed

2023-07-18 15:11 UTC, MatShir commented
The issue were milestone for the 8.1.x, for a wording it's sad to wait for the v9

2023-07-18 15:17 UTC, mflasquin commented
> The issue was milestone for the 8.1.x, for a wording it's sad to wait for the v9

Changed. The update alreay present on develop as been added on 8.1.x

2023-07-18 16:33 UTC, boherm approved these changes

2023-07-19 14:57 UTC, matthieu-rolland approved these changes

2023-07-21 14:58 UTC, MhiriFaten reviewed
Hello @mflasquin ,

I have checked your PR and I noticed the issue still exist : 

[Untitled_ Jul 21 2023 3_50 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/111756615/bb87e8d0-6b56-449e-8234-5c40247e1935)

And on the image of the copied product is not well displayed 

[Untitled_ Jul 21, 2023 3_51 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/111756615/b62dbfa4-52cd-4d85-96e0-8fa2d5649d14)

Could you check it please ?

2023-07-25 07:59 UTC, mflasquin commented
Hi @MhiriFaten can you check on develop, I think It's not linked to my PR (I just change 4 translations..)

2023-07-25 08:57 UTC, nesrineabdmouleh commented
UI tests => https://github.com/nesrineabdmouleh/testing_pr/actions/runs/5654729478

2023-07-25 09:51 UTC, nesrineabdmouleh approved these changes

2023-07-27 09:38 UTC, djoelleuch approved these changes
Hello @mflasquin  , 
the wording is OK :heavy_check_mark:  

[Untitled_ Jul 27, 2023 11_34 AM.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/14161641-d758-47df-aeda-d4c61a04cd8f)

Automated tests are OK  .
but the real [issue](https://github.com/PrestaShop/PrestaShop/issues/31778) is not fixing ! 
 
thank you for your PR  .

2023-07-27 10:51 UTC, merged

2023-07-27 10:51 UTC, kpodemski commented
thanks @mflasquin

2023-07-27 11:53 UTC, MatShir commented
Hi @djoelleuch, 
What is left to do to fix the issue? So I can update it accordingly