Deprecated SendCartToCustomer in v9
PrestaShop/PrestaShop pull request #33309
Opened 2023-07-19 11:42 UTC by Progi1984

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Deprecated SendCartToCustomer in v9 : These command & handler are not used.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | yes
| How to test?      | CI is :green_circle: & Nightly is :green_circle: : 
| Fixed ticket?     | N/A
| Related PRs       | N/A
| Sponsor company   | @PrestaShopCorp

2023-07-19 12:40 UTC, Hlavtox requested changes, later dismissed
This will be used, it's a migrated implementation of the logic.
It should be used on BO > Order > Create page to send order to customer.

Also, it will be used by abandoned cart modules.

2023-07-19 13:00 UTC, Progi1984 commented
The "BO > Order > Create" already exists and is already migrated.

2023-07-19 14:51 UTC, matthieu-rolland approved these changes

2023-07-20 09:10 UTC, Hlavtox approved these changes

2023-07-20 09:11 UTC, merged