Fix symfony legacy route configuration, PART 2
PrestaShop/PrestaShop pull request #33339
Opened 2023-07-21 15:52 UTC by M0rgan01

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Checking and updating the whitelist of legacy links
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | -
| Fixed ticket?     | Fixes #{32306}
| Related PRs       | -
| Sponsor company   | -

2023-07-24 08:34 UTC, matthieu-rolland reviewed
LGTM, nice job :+1:

2023-07-24 08:34 UTC, matthieu-rolland commented on src/PrestaShopBundle/Command/LegacyLinkLinterCommand.php
> +        'admin_features_horizontal_index'
```suggestion
        'admin_features_horizontal_index',
```

CS fixer is complaining about this missing comma :+1:

2023-07-26 09:27 UTC, boherm requested changes

2023-07-26 09:27 UTC, boherm commented on src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/products_v2/product.yml
> +      - AdminProducts:submitBulkdisableSelectionproduct
Maybe we can simplify this:
`_legacy_link: AdminProducts:submitBulkdisableSelectionproduct`

2023-08-22 16:10 UTC, matthieu-rolland approved these changes

2023-08-23 09:39 UTC, boherm approved these changes

2023-08-28 08:44 UTC, matthieu-rolland commented
QA dev ok ! treated routes are not appearing anymore when executing the command 👍

2023-08-28 08:44 UTC, merged