Update Link.php to fix an issue with invalid URLs
PrestaShop/PrestaShop pull request #33342
Opened 2023-07-23 16:50 UTC by CrochetFeve0251

| Questions         | Answers|
| ----------------- | -------------------------------------------------------|
| Branch?           | 8.1.x
| Description?      | Inside the method `getLanguageLink` the check for the `$params` is always done wrong as the key is present when a page is not found but the actual value is `false` on the key corresponding to the ID.<br>That makes the application raise a fatal later on when it search for the link:<br> `Invalid product vars at line 174 in file classes/Link.php`<br> `category vars at line 405 in file classes/Link.php`|
| Type?             | bug fix|
| Category?         | FO|
| BC breaks?        | no|
| Deprecations?     | no|
| How to test?      | The easiest way I found to test this is to install [`SEO Friendly URL Module](https://github.com/softwaremistri/smseourl)` which gonna remove the behavior on top of that method to redirect the user and makes it complex to reproduce the issue.<br>Then you can enter any wrong URL in category or product and problem gonna show up.|
| Fixed ticket?     | Fixes #33258, #33306|
| Sponsor company   | MBS Design|

2023-07-23 16:54 UTC, CrochetFeve0251 commented
Logic from #33257 based on 8.1 as requested by @M0rgan01

2023-07-24 06:54 UTC, Hlavtox requested changes
Hi, several issues:

1) Bad branch in description
2) Does not fix https://github.com/PrestaShop/PrestaShop/issues/33306, did you test it?
3) As discussed in https://github.com/PrestaShop/PrestaShop/pull/33257 - I am not sure this is a correct fix, because this should return a language variant of the current URL, and even if the current is invalid, it should return it, not suddenly return a link to 404 page or some nonsense link to product controller without a product.

I think that a correct behavior should be that this method should not crash, but return a null.
If the object doesn't exist, the validation should be done earlier.

2023-07-24 18:29 UTC, CrochetFeve0251 commented
> Hi, several issues:
> 
>     1. Bad branch in description
> 
>     2. Does not fix [FO - Error 500 URL with product id = 0 #33306](https://github.com/PrestaShop/PrestaShop/issues/33306), did you test it?
> 
>     3. As discussed in [Update Link.php to fix an issue with invalid URLs #33257](https://github.com/PrestaShop/PrestaShop/pull/33257) - I am not sure this is a correct fix, because this should return a language variant of the current URL, and even if the current is invalid, it should return it, not suddenly return a link to 404 page or some nonsense link to product controller without a product.
> 
> 
> I think that a correct behavior should be that this method should not crash, but return a null. If the object doesn't exist, the validation should be done earlier.

@Hlavtox Look like on 8.1 the issue is different so I removed my old code and added a new one fixing the #33306 issue with a  more consistent solution.

2024-02-25 19:38 UTC, kpodemski commented on controllers/front/ProductController.php
> +
```suggestion
```

There is no need to have this check twice.

2024-02-25 19:39 UTC, kpodemski commented
Hello @CrochetFeve0251 

Sorry for the late reply, but we didn't get any notification after you sent the new changes. There's no need to double-check here.

2024-08-26 13:53 UTC, matks commented
I close this PR as it has been stale for a long time. Thank you for submitting the PR

2024-08-26 13:53 UTC, closed without merging

2025-12-05 15:00 UTC, pelopinxu commented
It looks that someone make a fix for this. I tried and works but I know that needs more than this to be merged. 
https://github.com/PrestaShop/PrestaShop/issues/33306#issuecomment-3571675374