Allow importing guests, prevent duplicate customer import
PrestaShop/PrestaShop pull request #33384
Opened 2023-07-26 08:25 UTC by Hlavtox

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Checks and prevents importing duplicate customers. Add a functionality that allows to import guest customers.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Try importing duplicate customer, it will fail. It will work if you specify that it's a guest.
| Fixed ticket?     | Fixes #21937
| Related PRs       | 
| Sponsor company   |

2023-07-26 09:25 UTC, boherm submitted a review, later dismissed

2023-07-31 21:42 UTC, kpodemski commented on src/Core/Import/EntityField/Provider/CustomerFieldsProvider.php
> +            new EntityField('newsletter', $this->trans('Guest customer (0/1)', 'Admin.Advparameters.Feature')),
It looks like a mistake

2023-07-31 21:42 UTC, kpodemski requested changes
I think the EntityField argument is wrong

2023-08-01 05:56 UTC, Hlavtox commented on src/Core/Import/EntityField/Provider/CustomerFieldsProvider.php
> +            new EntityField('newsletter', $this->trans('Guest customer (0/1)', 'Admin.Advparameters.Feature')),
@kpodemski It is indeed, fixed. :-)

2023-08-01 07:21 UTC, kpodemski approved these changes, later dismissed

2023-08-01 13:07 UTC, closed without merging