make search_form twig component independant
PrestaShop/PrestaShop pull request #33463
Opened 2023-07-27 16:15 UTC by matthieu-rolland

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | 
| Type?             | refacto
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Search form in the header still works as expected when feature flag is activated.
| Fixed ticket?     | Fixes #33177
| Related PRs       | 
| Sponsor company   | PrestaShop SA

2023-07-28 08:26 UTC, mflasquin approved these changes, later dismissed

2023-07-28 08:59 UTC, boherm submitted a review, later dismissed

2023-07-31 04:27 UTC, lartist commented on src/PrestaShopBundle/Twig/Component/SearchForm.php
> +        $this->boQuery = $request->query->get(self::BO_QUERY_PARAM) ?: '';
```suggestion
        $this->boQuery = $request->query->get(self::BO_QUERY_PARAM, '');
```

2023-07-31 04:27 UTC, lartist commented on src/PrestaShopBundle/Twig/Component/SearchForm.php
> +        $this->searchType = (int) $request->query->get(self::BO_SEARCH_TYPE_PARAM) ?: 0;
```suggestion
        $this->searchType = (int) $request->query->getInt(self::BO_SEARCH_TYPE_PARAM, 0);
```

2023-07-31 04:34 UTC, lartist requested changes
Please remove the following lines of phpstan-tmp-legacy-layout-baseline.neon
```neon
		-
			message: "#^Class Link is forbidden, No legacy calls inside the prestashop bundle\\. Please create an interface and an adapter if you need to\\.$#"
			count: 1
			path: src/PrestaShopBundle/Twig/Component/SearchForm.php

		-
			message: "#^Namespace Link is forbidden, No legacy calls inside the prestashop bundle\\. Please create an interface and an adapter if you need to\\.$#"
			count: 1
			path: src/PrestaShopBundle/Twig/Component/SearchForm.php
```

And also in admin-dev/themes/new-theme/template/layout.tpl please remove unused variables:
              {render_template
                smarty_template="components/layout/search_form.tpl"
                twig_template="@PrestaShop/Admin/Layout/search_form.html.twig"
                ~~bo_query=$bo_query
                link=$link
                show_clear_btn= $show_clear_btn|default:null
                search_type= $search_type|default:null~~
              }

2023-08-01 09:48 UTC, M0rgan01 commented on src/PrestaShopBundle/Resources/views/Admin/Layout/search_form.html.twig
> -}) }}
You can also remove them in layout.tpl

2023-08-01 16:01 UTC, boherm approved these changes, later dismissed

2023-08-02 05:05 UTC, lartist commented
@matthieu-rolland I think you forget this in your last commit:
> And also in admin-dev/themes/new-theme/template/layout.tpl please remove unused variables:
{render_template
smarty_template="components/layout/search_form.tpl"
twig_template="@PrestaShop/Admin/Layout/search_form.html.twig"
bo_query=$bo_query
link=$link
show_clear_btn= $show_clear_btn|default:null
search_type= $search_type|default:null
}

2023-08-02 16:26 UTC, boherm submitted a review, later dismissed

2023-08-02 16:35 UTC, M0rgan01 approved these changes, later dismissed

2023-08-03 12:42 UTC, lartist approved these changes, later dismissed

2023-08-03 13:07 UTC, aniszr approved these changes, later dismissed
Hello @matthieu-rolland 

I have checked your PR and I noticed this issue :x: 

- After activating the Symfony layout option, the access to some pages became impossible  :x: 

1. Orders > Orders : See attached screen-record:

https://github.com/PrestaShop/PrestaShop/assets/92626242/9c25316d-35a4-4146-bd11-5dc4af62ba7c

2.Modules > Modules  Manager

![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/dab98be5-f6c6-4e27-b09f-fe8b4a913342)

3. Catalog > Categories
4. Catalog > Brands & Suppliers
5. Catalog > Files

6. Customers > Customers
7. Customers > Addresses

8. Customer Service > Order Messages

9.Design > Theme & Logo
10.Email Theme
11. Design > Pages  
![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/d67b7246-1c53-4e6c-8420-b3c780472a75)

12.Design > Positions
13.Design > Link List

14. International > Localization
15. International > Locations
16. International > Taxes

17. Shop Parameters > General
18. Shop Parameters >Order Setings
19. Shop Parameters > Customer Settings
20. Shop Parameters >Contact
21. Shop Parameters >Traffic & SEO

22. Advanced Parameters > Performance

![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/fb31da16-8ba5-4266-a2a7-a67a8cfc4afc)

23.Advanced Parameters > Team
24.Advanced Parameters > Database
25.Advanced Parameters > Webservice
26.Advanced Parameters > Security

Auto Test :heavy_check_mark:  : https://github.com/aniszr/ga.tests.ui.pr/actions/runs/5748987216

Could you please check and feed-back!

Thanks!

2023-08-09 08:28 UTC, matthieu-rolland commented
@aniszr I have been told that this PR should not be tested by QA because it's behind a feature flag, I didn't know sorry about that 😓 

About your findings, I couldn't reproduce them, it's strange 🤔 

**EDIT**: I just reproduced it, not sure why I didn't have them at first, maybe some cache, I'll look into it

**EDIT 2:** Seems like this issue is also on develop branch.

2023-08-09 09:00 UTC, matthieu-rolland commented
> QA OK without required approvals !? :trollface:

whatcha gonna do ?

2023-08-09 09:07 UTC, boherm approved these changes

2023-08-09 09:07 UTC, kpodemski approved these changes

2023-08-09 09:09 UTC, merged