Update Keycloak module URL in tests
PrestaShop/PrestaShop pull request #33468
Opened 2023-07-28 06:58 UTC by nicosomb

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Update Keycloak module URL in tests
| Type?             | improvement
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | UI tests 🟢 
| Fixed ticket?     | 
| Related PRs       | 
| Sponsor company   | PrestaShop SA

2023-07-28 07:08 UTC, mflasquin submitted a review, later dismissed

2023-07-28 09:33 UTC, Progi1984 commented
With dev mode : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/5690473110

2023-07-28 13:20 UTC, matthieu-rolland approved these changes, later dismissed

2023-07-29 07:22 UTC, Progi1984 requested changes
The nightly is :red_circle:. It's a partial fix.

2023-08-02 09:25 UTC, Progi1984 approved these changes

2023-08-02 09:27 UTC, boubkerbribri approved these changes

2023-08-02 09:27 UTC, Progi1984 commented
The API campaign is now :green_circle: : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/5731292322

:muscle: @nicosomb & @mflasquin

2023-08-02 09:28 UTC, mflasquin approved these changes

2023-08-02 09:48 UTC, merged