Avoid html code in order conf email
PrestaShop/PrestaShop pull request #33471
Opened 2023-07-28 09:08 UTC by NicolasCador

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | avoid html code in order confirmation email when customization
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | make a PO with a product with customization, check order confirmation email : you don't have any html code
| Fixed ticket?     | Fixes #{issue number here}, Fixes #{another issue number here}
| Related PRs       | 
| Sponsor company   |

2023-07-28 09:12 UTC, NicolasCador commented
Before:
<img width="293" alt="Before" src="https://github.com/PrestaShop/PrestaShop/assets/96910631/f420feea-1d3c-4917-b1e1-48c31cfb5eb4">

After:
<img width="287" alt="After" src="https://github.com/PrestaShop/PrestaShop/assets/96910631/5c6c6ad4-0455-4c07-bcf1-1a3b97999858">

2023-07-28 10:46 UTC, Hlavtox requested changes
Warning - this is customer entered data. It may allow starting injected javascript. 

It should be validated during customization creation, but better check it. Customizations are also displayed in BO though, so we would have much bigger problem than launching it in email client. :-)

Ping @matthieu-rolland - dismiss the review if it's OK.

2023-07-28 14:01 UTC, NicolasCador commented
Hi @Hlavtox,

yes you're right, we have to be careful with these kind of data.

Fortunately, it's Validated at creation:
<img width="904" alt="ProductController" src="https://github.com/PrestaShop/PrestaShop/assets/96910631/c36a4334-5043-4aaf-a990-69db85ba2736">

2023-08-04 06:40 UTC, nicosomb commented
@NicolasCador Is `textRecord` the only way to add data into database? 
Just to be sure that all data is validated.

2023-08-17 09:51 UTC, NicolasCador commented
Hi @nicosomb,

when we search for 'customized_data`, we find only 3 ways to record in the database:
<img width="1088" alt="Cart" src="https://github.com/PrestaShop/PrestaShop/assets/96910631/5d743ae7-ad1b-4abb-a467-08f5e3e6b13a">
<img width="1308" alt="Customization" src="https://github.com/PrestaShop/PrestaShop/assets/96910631/4faf073e-bcd4-490d-a7c7-2dfc977c9f3b">
<img width="959" alt="Cart_duplicate" src="https://github.com/PrestaShop/PrestaShop/assets/96910631/e26bfcc9-488b-476b-be8d-46e098b11f36">


and another one when we duplicate product, with data already in the database:
<img width="958" alt="Cart_duplicateProduct" src="https://github.com/PrestaShop/PrestaShop/assets/96910631/38d6b1dd-18f9-4c62-aefe-c122905176ef">

But you're right it should be double-checked.

2024-09-03 10:34 UTC, Codencode commented
Hi @NicolasCador,

have also encountered this issue, but I hadn't seen your PR, so I created a PR for this problem as well.

I also added the validation for the value entered in the field during the order creation in the admin.

This is my PR: #36796.

2024-09-03 16:47 UTC, NicolasCador commented
Hi @Codencode,

ok, thank you for message.

I think the XSS risk is already mitigated by pSQL function to put data in DataBase. But with your proposition, we are sure.

Let's hope your PR will be merged for next Release, today, I modify manually the file after each update...

2025-10-19 10:03 UTC, kpodemski commented
Work continues in https://github.com/PrestaShop/PrestaShop/pull/36796

2025-10-19 10:03 UTC, closed without merging

2026-11-07 16:50 UTC, NicolasCador commented
Hi, 
very happy to have contributed to #36796 for https://github.com/PrestaShop/PrestaShop/releases/tag/9.0.2