Secure table name with bqsql in DB and DBQuery
PrestaShop/PrestaShop pull request #33539
Opened 2023-08-03 13:51 UTC by jf-viguier

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Secure table name with bqsql in DB and DBQuery
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | o
| How to test?      | ask a dev
| Fixed ticket?     | n/a
| Sponsor company   | Friends of Presta

2023-08-03 13:55 UTC, touchweb-vincent commented
+1

2023-08-03 13:57 UTC, nicosomb approved these changes, later dismissed
Nice catch!

2023-08-03 14:11 UTC, jf-viguier commented
@nicosomb CI/CD bug ?

2023-08-03 14:20 UTC, LouisAUTHIE approved these changes
well done

2023-08-03 14:23 UTC, nicosomb commented
@jf-viguier I relaunched failed tests.

2023-08-03 14:36 UTC, LouisAUTHIE commented on classes/db/DbQuery.php
> -                $query = '`' . _DB_PREFIX_ . $table . '`';
This is this one that creates the UNIT test failure

2023-08-03 14:37 UTC, LouisAUTHIE commented on classes/db/DbQuery.php
> -                $query = '`' . _DB_PREFIX_ . $table . '`';
Maybe replace '`' by '\`' ?

2023-08-03 14:44 UTC, LouisAUTHIE commented on classes/db/DbQuery.php
> -                $query = '`' . _DB_PREFIX_ . $table . '`';
But I don't know why specifically in this case it causes a pb, I'll let you know if I find it

2023-08-03 19:38 UTC, kpodemski requested changes
Blocking this PR because tests are red.

2023-08-03 20:04 UTC, LouisAUTHIE commented on classes/db/DbQuery.php
> -                $query = '`' . _DB_PREFIX_ . $table . '`';
The crash comes from the use of the Db Singleton in the pSQL function used itself by bqSQL().
The declaration of a Db class in the tests/Unit/Classes/RequestSqlTest.php file is not compliant with it. Why not considering a revision of this Test File ?

2023-08-03 20:05 UTC, LouisAUTHIE requested changes, later dismissed
Changes requested as commented before

2023-08-04 08:08 UTC, jf-viguier commented
@kpodemski I'd like some help instead of a bloking. It's a security PR.
Renaming Fake DB class doesn't work. I don't know how to fix this.

2023-08-04 08:10 UTC, kpodemski commented
@jf-viguier I had to block it because it got Waiting for QA :)

2023-08-04 09:32 UTC, jf-viguier commented
I can't figure out how to fix the test, feel free maintainers & committers to help.

2023-08-07 08:25 UTC, matthieu-rolland commented
I will have a look when I can (soon) :+1:

2023-08-14 11:50 UTC, LouisAUTHIE commented
@atomiix do you have any idea of how to fix this test ? It seems that you have contributed to this file and you may know much more than I do with the fake DB class. Thanks in advance for you great help !

2023-08-14 21:10 UTC, LouisAUTHIE commented
The problem is that the pSQL function in config/alias.php calls for the singleton Db, and the RequestSqlTest.php file recreates a new Db class for it's own needs. That leads to get 2 Db objects. I think that the problem comes from this commit https://github.com/PrestaShop/PrestaShop/commit/27809281f05e1ae45a0d1e2fa304e64130e0db9b where this Db Object should have been coded differently so as not to create a conflit like this in other tests using pSQL.

2023-09-13 13:50 UTC, jf-viguier commented
I still need some help on this unit tests.
Is there a "waiting for maintainer" tag ?

2023-10-05 08:30 UTC, jf-viguier commented
2 months :birthday:

2023-10-11 15:43 UTC, matks commented
Hey everyone, I know some people looked at this problem and encountered more issues ; so some time has been spent on this topic ; however these people did not leave behind a message with their findings 😅 so little reminder: on GitHub, if you spend 4 hours on a thing but don't write about it (or push a git commit), it is invisible

2023-12-20 08:05 UTC, jf-viguier commented
@matks can you tell me who has worked on it to avoid facing the same problems ?

2024-06-27 09:46 UTC, amine-O commented
@matthieu-rolland could you please check this PR if it's a security issue ?

2025-02-21 09:07 UTC, jf-viguier commented
I've rebased this old pr that is still relevant, just a mock issue.

2025-11-06 17:17 UTC, Progi1984 approved these changes

2025-11-06 19:18 UTC, jf-viguier commented
Tx @Progi1984 for the approve.
@matthieu-rolland @kpodemski I've suceeded in fixing unit tests, can you please review ?

2025-11-13 19:47 UTC, kpodemski approved these changes

2025-11-13 19:48 UTC, kpodemski commented
thank you @jf-viguier 

I think it looks good now after adjusting the tests

2025-11-18 20:35 UTC, kpodemski commented
@PrestaShop/qa-functional 

I added labels so developers can test these changes.

2025-11-18 20:36 UTC, kpodemski commented
@jf-viguier let's make sure to run&add e2e tests to the PR description

2026-01-30 10:35 UTC, jf-viguier commented
@kpodemski I've added the ui tests.

2026-02-10 08:14 UTC, Touxten commented
@kpodemski && @PrestaShop/qa-functional 

QA by dev ? 

Edit : Oups sorry it's already say in the topic

2026-02-10 08:55 UTC, Touxten commented
I forked the branch, the shop is installed correctly, I tested SELECT INSERT UPDATE and no problem, it's OK for me.

CI and UI are Green

2026-02-10 09:12 UTC, jf-viguier commented
thanks @Touxten

2026-02-11 08:50 UTC, matthieu-rolland approved these changes

2026-02-11 15:08 UTC, jolelievre approved these changes

2026-02-11 15:08 UTC, merged