Fix tax detail in invoice
PrestaShop/PrestaShop pull request #33561
Opened 2023-08-07 12:31 UTC by idnovate

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Check https://github.com/PrestaShop/PrestaShop/issues/33543
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Check https://github.com/PrestaShop/PrestaShop/issues/33543
| Fixed ticket?     | Fixes #33543
| Sponsor company   | idnovate.com

2023-08-07 12:46 UTC, LouisAUTHIE approved these changes

2023-08-07 15:17 UTC, boherm commented
Hi @idnovate, thanks for your contribution! 😉
As I can see, you have merge on your forked 8.1.x branch your fix and ask to merge your 8.1.x branch with our 8.1.x, that cause the error on the CI. Can you fix this? 😀

2023-08-09 13:30 UTC, matks requested changes
As said by @boherm the CI is unfortunately red because of merge commits in the branch

2023-08-10 20:53 UTC, closed without merging

2023-08-10 20:55 UTC, idnovate commented
Let's try again https://github.com/PrestaShop/PrestaShop/pull/33597 :)