Get the right list of carriers before entering an address
PrestaShop/PrestaShop pull request #33707
Opened 2023-08-24 08:12 UTC by olecorre

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | When you activate geolocation, before entering an address, the system displays the delivery costs from the default country. The purpose of geolocation is to retrieve the visitor's country. You therefore need to display the delivery charges according to this country.
| Type?             | bug fix
| Category?         | FO 
| BC breaks?        |  no
| Deprecations?     | no
| How to test?      | Activate geolocation, Configure a carrier specific to this country with its own zone.Use a VPN to simulate a visit to the site from this country (other than your own country). Add a product to the basket, you will need to have the shipping costs for the country in question and not those for the default country.
| Fixed issue or discussion?     | Fixes #33709
| Related PRs       | 
| Sponsor company   | Ohweb.

2023-08-24 08:23 UTC, jf-viguier approved these changes

2023-08-24 08:30 UTC, kpodemski requested changes
Could you please format your code to respect the coding standards used in the project? You can use PHP CS fixer to do that for you.

2023-08-24 10:28 UTC, Hlavtox requested changes
I think it should not be a resposibility of a carrier class to get default country. It should be properly assigned in one place, during initialization of the FrontController.

2023-08-24 10:54 UTC, kpodemski commented
@Hlavtox what do you mean? as of right now Carrier class ignores the default country set by the geolocation in FrontController, this change seems to be legit 🤔 what would you to do? `Configuration::set` in FrontController? that'd be risky

2023-08-24 11:11 UTC, Hlavtox commented
@olecorre Can you do this instead, it's simplier.

```php
if (!empty(Context::getContext()->cookie->iso_code_country)) {
    $ps_country_default = Country::getByIso(Context::getContext()->cookie->iso_code_country);
} else {
    $ps_country_default = Configuration::get('PS_COUNTRY_DEFAULT');
}
```

2023-08-24 12:31 UTC, olecorre commented
@Hlavtox This is what I did at first, but if the country is not active, Country::getByIso will return False.
$ps_country_default after cannot be null or false

2023-08-24 13:18 UTC, LouisAUTHIE submitted a review, later dismissed

2023-08-25 12:44 UTC, mflasquin commented on classes/Carrier.php
> +            }
```suggestion
            $ps_country_default = Configuration::get('PS_COUNTRY_DEFAULT');
            if (!empty(Context::getContext()->cookie->iso_code_country) && (int) Country::getByIso(Context::getContext()->cookie->iso_code_country) > 0) {
    $ps_country_default = Country::getByIso(Context::getContext()->cookie->iso_code_country);
            }
```

2024-04-30 12:37 UTC, nicosomb commented
@olecorre could you please run php cs fixer?

2024-05-02 13:43 UTC, momo1240 commented
hello guys,
I was looking for this for a while cause until now I'm using a module to set carrier based on guest IP.
I made the change suggested by @olecorre. it works when we first add the product to cart.
but I noticed that when we reload the page, it keeps showing "free" for shipping.
Shouldn't we also update class/Cart.php
thanks

2025-04-18 10:40 UTC, closed without merging