Independent toolbar buttons twig component
PrestaShop/PrestaShop pull request #33739
Opened 2023-08-28 10:13 UTC by boherm

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Try to add independent behaviour on toolbar twig component.<br/>We can't add title to this because of the order of procesesing the BO render.<br/>When we drop the smarty way, this could be improved this component.
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI 🟢 & Tests 🟢
| Fixed issue or discussion?     | Fixes #33604
| Related PRs       | 
| Sponsor company   | PrestaShop SA

2023-08-28 11:57 UTC, mflasquin submitted a review, later dismissed

2023-08-30 09:57 UTC, M0rgan01 commented on src/PrestaShopBundle/Twig/Component/Toolbar.php
> +    }
I think we can remove the class variables `$toolbarBtn` `$enableSidebar` `$helpLink`

2023-08-30 20:38 UTC, jolelievre requested changes
To discuss tomorrow but I'm not sure we should introduce this intermediate DTO accessible via the legacy context just so that the Twig component can access them differently via a legacy context service as well

Seems more like we are in the situation we discussed previously with variables injected by the controller that can't be fetched automatically by the components, so we should wait for the global layout to handle them and pass them down to the components

2023-08-31 12:58 UTC, M0rgan01 commented
tests: https://github.com/M0rgan01/ga.tests.ui.pr/actions/runs/6037635048

2023-08-31 15:06 UTC, boherm commented
@jolelievre I agree with you about it :)
So we must close this PR for now.

2023-08-31 15:06 UTC, closed without merging