Update classname regex to allow FQDN
PrestaShop/PrestaShop pull request #33771
Opened 2023-08-30 12:14 UTC by gross-nvs

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 8.1.x
| Description?      | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Install the following test module, then click on 'Configure' to trigger the test case. If no error message is displayed and a log line is properly added to the log list (Advances parameters > Logs) then the fix works. [test_33590.zip](https://github.com/PrestaShop/PrestaShop/files/12475413/test_33590.zip)
| Fixed issue or discussion?     | Fixes #33590
| Related PRs       | 
| Sponsor company   |

2023-08-30 13:21 UTC, matthieu-rolland approved these changes, later dismissed
👍

2023-08-30 13:23 UTC, kpodemski requested changes
Could you target 8.1.x branch?

2023-08-30 19:42 UTC, kpodemski approved these changes

2023-08-31 15:02 UTC, boherm approved these changes

2023-09-04 13:50 UTC, kpodemski commented
@PrestaShop/qa-functional I restarted the tests but feel free to test the PR anyway, I'm positive they'll be green ;-)

2023-09-04 14:50 UTC, paulnoelcholot commented
@kpodemski They are not green ^^ Someone, but not all ;p

2023-09-05 08:11 UTC, paulnoelcholot commented
Hello @gross-nvs,

Some checks were not successful, can you look into that? :)

Thanks!

2023-09-05 15:26 UTC, gross-nvs commented
Hi @paulnoelcholot 

By looking the details, I'm afraid I'm not qualified to fix those problems, nor are they related to the code change.

2023-09-05 15:27 UTC, kpodemski commented
@gross-nvs no worries, it's the issue on our side - or rather a GH side :D

2023-09-06 09:42 UTC, MhiriFaten approved these changes
Hello @gross-nvs ,

I have checked the PR, no error message is displayed and a log line is properly added to the log list.
But I noticed that the autolated tests failed in [test (functional:productV2, 8.1.x)](https://github.com/MhiriFaten/testing_pr/actions/runs/6093831359/job/16538450337#logs)

@PrestaShop/qa-automation is this failure related to the PR ?

2023-09-07 19:41 UTC, merged

2023-09-07 19:41 UTC, nicosomb commented
Thank you @gross-nvs !