Update ProductController.php
PrestaShop/PrestaShop pull request #33798
Opened 2023-09-01 12:20 UTC by josemariagomezroncero

Bug filteredproduct hook

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 8.1.x
| Description?      | If the value of chain is true or array_return false when the hook:exec( method is executed, the value of $hook_args will become a string after executing the first module, because the condition if (0 !=) exists within the exec method. = $key && true === $chain) {
                    $hook_args = $output;
                } which will give $hook_args the value of $output and this will be a string.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | yes 
| Deprecations?     | no
| How to test?      | Install several modules in hook filterProductContent.
| Fixed issue or discussion?    return string and it must return array
| Related PRs       | 
| Sponsor company   |

2023-09-01 12:21 UTC, josemariagomezroncero commented
If the value of chain is true or array_return false when the hook:exec( method is executed, the value of $hook_args will become a string after executing the first module, because the condition if (0 !=) exists within the exec method. = $key && true === $chain) {
                    $hook_args = $output;
                } which will give $hook_args the value of $output and this will be a string.

2023-09-07 16:13 UTC, matks reviewed
Hello @josemariagomezroncero and thank you for the PR

I am sorry I see you tried to explain the PR behavior but I do not fully understand it. I understand there's a problem when multiple modules are hooked on `hookFilterProductContent` but I dont understand the actual problem.

- what is the problem? what are the consequences of the bug you observed? PHP fatal error? warning? without the PR, what would we see? with the PR, what should we see?
- why does your change fix the problem?

2023-09-07 16:55 UTC, josemariagomezroncero commented
If we hook two modules to this hook we will get a 500 error when the second module is executed.

2023-09-20 16:21 UTC, matks requested changes
Hello @josemariagomezroncero you are right.

I have tested to plug 2 modules on hook "filterProductContent" and it crashes, because the code does not expect multiple modules to be called. And your PR avoids the crash.

However your PR is not complete.

If you look at line 436, the code expects the result of the hook to be an array which contains an object `filteredProduct`.

But with your PR, the result we get is actually an array in which each module has been able to return an item. For example if module A and B are plugged on hook `filterProductContent` then $filteredProduct will be
```
[
   'A' => ...
   'B' => ...
]
```

So in your PR you need to _adapt_ the code at line 436 to manage this new output. If we simply accept your PR it does not crash but it becomes unusable with 2 hooks.

2025-10-19 10:15 UTC, kpodemski commented
Since we have had no news from you for more than 20 days, I'm closing this PR. Feel free to re-open it if you find the motivation to finish it. Don't hesitate to ping me if you have any questions or doubts.

2025-10-19 10:15 UTC, closed without merging