Comment hooks with special calls, fix extra chain
PrestaShop/PrestaShop pull request #33883
Opened 2023-09-08 12:32 UTC by Hlavtox

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | I wrote a script and checked all hook calls through the codebase that have some special parameters. Commented them all out. Removed extra parameters in some hook calls. Fixed an extra chaining I added by accident - there is a reference.
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | No QA needed if @PrestaShop/qa-functional approves.
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   |

2023-09-08 14:16 UTC, nicosomb commented
@Hlavtox you have a conflict

2023-09-08 14:17 UTC, Hlavtox commented
@nicosomb Fixed ;-)

2023-09-10 17:30 UTC, LouisAUTHIE requested changes

2023-09-10 17:30 UTC, LouisAUTHIE commented on classes/Hook.php
> +        // If we in installation phase OR the hook is disabled, it won't be executed
If we **are**

2023-09-10 17:30 UTC, LouisAUTHIE commented on classes/Hook.php
> +        // Get hook register to collect debug information
Hook **registry**

2023-09-11 07:55 UTC, Hlavtox commented on classes/Hook.php
> +        // If we in installation phase OR the hook is disabled, it won't be executed
Fixed :-)

2023-09-11 07:55 UTC, Hlavtox commented on classes/Hook.php
> +        // Get hook register to collect debug information
Fixed :-)

2023-09-11 07:55 UTC, Hlavtox commented
@LouisAUTHIE Can you recheck please? :-)

2023-09-11 08:05 UTC, LouisAUTHIE approved these changes

2023-09-11 08:06 UTC, LouisAUTHIE approved these changes

2023-09-11 16:06 UTC, matks approved these changes
Thank you it will be useful for module developers 👍

2023-09-11 16:08 UTC, matks commented
@prestonBot I'm afraid there's a little problem 😅

2023-09-11 16:09 UTC, matks commented
@Hlavtox Would you please run the UI Tests?

https://devdocs.prestashop-project.org/8/contribute/contribution-guidelines/ui-tests/

2023-09-12 07:36 UTC, Hlavtox commented
@matks Done

2023-09-12 07:51 UTC, matks commented
CI is broken we have lost MySQL
![Capture d’écran 2023-09-12 à 09 50 51](https://github.com/PrestaShop/PrestaShop/assets/3830050/83786b99-580e-44f8-82a9-44ac620c048c)

2023-09-12 15:03 UTC, Hlavtox commented
@matks All green! :-)

2023-09-12 15:46 UTC, matks approved these changes
This PR does not modify any behavior 👍

2023-09-12 15:47 UTC, matks commented
As the [UI Tests](https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/6156339419) are green and no behavior has been modified I think we can merge it

2023-09-12 15:47 UTC, merged

2023-09-12 15:48 UTC, matks commented
@Hlavtox Argh I just realized that was for 8.1.x and not develop although it is not a bugfix. Why submit this PR for patch version 😞 ?

2023-09-12 15:58 UTC, Hlavtox commented
@matks It is a bugfix, I added extra chain that should not be there as it has no effect. ;-)

2023-09-12 15:59 UTC, Hlavtox commented
And comments can go to 8.1.x, when somebody will dig in the current version, make it easier for him.

2023-09-12 16:00 UTC, matks commented
> @matks It is a bugfix, I added extra chain that should not be there as it has no effect. ;-)

You did not solve a bug 😛 . You solved improveable code. It's different 😆