Cannot set specific price with currency filter
PrestaShop/PrestaShop pull request #33930
Opened 2023-09-13 10:06 UTC by M0rgan01

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See #33285 / CI and tests UI are green
| UI Tests          | -
| Fixed issue or discussion?     | Fixes #33285
| Related PRs       | -
| Sponsor company   | -

2023-09-13 15:42 UTC, matthieu-rolland approved these changes, later dismissed
LGTM 👍 

Maybe we should update the comment above ?  `// convert only if the specific price is in the default currency (id_currency = 0)`

I'm not sure what `id_currency = 0` means here... 

For context, here's the PR implementing this condition (it was a bug fix at the time it seems): https://github.com/PrestaShop/PrestaShop/pull/18456

2023-09-13 15:51 UTC, M0rgan01 commented
@matthieu-rolland for `id_currency = 0`, I'm also not sure. I will update the comment to clarify the condition

2023-09-13 16:23 UTC, matthieu-rolland approved these changes, later dismissed

2023-09-14 06:51 UTC, nicosomb requested changes
Could you target `8.1.x` branch please?

2023-09-14 07:13 UTC, M0rgan01 commented
@nicosomb Done, thanks

2023-09-14 07:25 UTC, nicosomb approved these changes

2023-09-14 14:14 UTC, nicosomb commented
@M0rgan01 could you relaunch UI tests on with this branch please?

2023-09-14 14:17 UTC, tleon approved these changes

2023-09-18 13:03 UTC, aniszr approved these changes
Hello @M0rgan01 

I tested your PR and checked the improvement when adding specific price for a currency and the impact on product pricing in FO !

LGTM :heavy_check_mark: 

See attached screenshots:

![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/0aaa1b4e-eeb8-4fc5-8a5c-91e0eec95b03)

![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/37c7fe84-3ce8-4b42-9ab3-9efb99ba85b2)

Auto Test : https://github.com/aniszr/ga.tests.ui.pr/actions/runs/6220279757 :heavy_check_mark: 

Thanks!

2023-09-18 14:19 UTC, merged

2023-09-18 14:19 UTC, nicosomb commented
Thank you @M0rgan01 !