Add time selector to date_format
PrestaShop/PrestaShop pull request #33943
Opened 2023-09-14 11:37 UTC by Gerardlc

**Branch**
develop / 8.1.x

**Description**
When adding or editing a specific price from the edit product page date picker is not showing hour, minutes and seconds options.
If cart rule date picker allows to set hour, minute and second we should allow it in product specific price too.

Original:
![specific_price_time_v1](https://github.com/PrestaShop/PrestaShop/assets/5434642/e0035972-03ca-4e8d-9ebb-aa669b2c1f68)

After changes:
![specific_price_time_v2](https://github.com/PrestaShop/PrestaShop/assets/5434642/059b0ae3-644a-4449-8c94-570f6e4e1406)
If cart rule date picker allows to set hour, minute and second we should allow it in product specific price too.

**Type**
improvement 

**Category** 
BO 

**BC breaks**
no

**Deprecations**
no

**How to test**
Try to edit or add a product specific price from the backoffice

2023-09-14 11:41 UTC, Hlavtox commented
@PrestaShop/committers I think we can target 8.1.x? It's easy to review and can be merged today.

2023-09-14 16:08 UTC, Hlavtox commented
@Gerardlc Can you rebase it to 8.1.x and change the target branch?

2023-09-14 16:29 UTC, matks commented
> @Gerardlc Can you rebase it to 8.1.x and change the target branch?

I disagree 😉 .

@Hlavtox I know what you mean: "If we push this to 8.1.x branch then people will be able to use it from PrestaShop 8.1.2 in September 2023! And if we push this to `develop` then people will only be able to use it in 2024 when PrestaShop 9.0.0 is released"

But if we start pushing too many things into patch versions like 8.1.2, we might bloat patch versions, introduce bugs, introduce regressions, make it harder to deliver these versions.

By harder I mean this worst case scenario:

1. We put a lot of PRs inside PrestaShop 8.1.2
2. We build PS 8.1.2 and deliver it to QA team, that needs one week to test it all.
3. But because we put too many PRs into 8.1.2 we actually introduce 5 blocker bugs.
4. We have to deliver 5 bug fixes for these 5 blocker bugs.
5. Then we need to test these 5 PRs, and then we need to redo a 8.1.2 build. It's build 2.
6. And then we need QA team to again test this build 2.
7. Oh no! One of the 5 bug fixes introduced another blocker bug and now we have one more blocker bug to fix and one more PR to submit and to review and to test.
8. Finally we can create a build 3, deliver it to QA team who tests it (so it's now the 3rd time we request QA team time to test a release and even though the tests for build 3 will probably be less extensive than builds 2 and 1 it's still going to be expensive)
9. Finally we can deliver PS 8.1.2 2 or 3 weeks after we started the release process.

And here is a safe road scenario

1. We put only regression bug fixes inside PrestaShop 8.1.2 like we have been doing for years
2. We build PS 8.1.2 and deliver it to QA team, that needs one week to test it all.
3. QA finds 1 blocker bugs (less PRs merged in 8.1.2 = probability of introducing a blocker bug is lower)
4. We have to deliver 1 bug fixes for this blocker bugs. It's reviewed and tested and merged.
5. We need to redo a 8.1.2 build. It's build 2. And then we need QA team to again test this build 2 but as only 1 PR is different between build1 and build2 then test campaign is a lot lighter.
6. Finally we can deliver PS 8.1.2 1.5 week after we started the release process.

If you compare the 2 scenarios, you can see the "price" we have paid for the extra PRs merged in 8.1.2 . It's not just that it's released later. It's paid in developer and QA time, and this time could have been spent on other topics and bugs and features that are awaited in PrestaShop 9

So my conclusion is: if we include PRs in 8.1.2 that are not regression bug fixes, then they should be high value PRs that are worth the risk. This PR is a nice improvement but from my point of view it's not a game changer PR (no offense @Gerardlc 😅 it's still a nice contribution) and it should not be included in 8.1.2.

And 😱 I've only been talking about blocker bugs that QA team will find! The more PRs we merge in `8.1.x` the more we also increase the possibility we introduce a major blocker bug that will not be detected. Introducing a major bug in a patch version is a terrible scenario as a patch release is supposed to bring stability, not instability 😅 it creates confusion and loss of trust.

I hope you'll understand what I mean 😉 it's not to annoy you, it's to preserve the easy deliverability of our patch releases. If releasing a patch version becomes hard and too expensive we won't be able to do it regularly like we've been doing it so far. I would be very sad to see our lightweight patch release process becomes a time-consuming nightmares.

This PR should target `develop` in my opinion and not `8.1.x`

2023-09-14 16:33 UTC, Hlavtox requested changes
It will need more work > https://github.com/PrestaShop/PrestaShop/pull/33945

2023-09-14 16:33 UTC, matks reviewed
Regardless of the target branch, @Gerardlc I have tested your change and
- it works correctly in the Product backoffice page
- data is correctly persisted in database

But is this data correctly acknowledged when the Specific price is used?

Because in the past, as users could not use minutes and hours for specific prices, I am not sure at all that in the front-office this data is used.

The scenario I am afraid of is:
1. We merge your PR and deliver it in PS 9.0.0
2. A PS user creates a 9.0.0 shop and creates specific price that start at 9am and finishes at 9am15
3. But when customer makes a purchase at 9am16 the specific price is applied nonetheless because the PHP code that verifies "is the specific price applicable" simply ignores the minutes/hour/seconds part.

Could you please verify?

2023-09-16 10:15 UTC, Gerardlc commented
I agree with all @matks 

I tested, and found that was "partially" working actually because seconds didn't work properly.
Found out that SpecificPrice class was not using seconds, committed the change needed already.

I drop here the video testing a specific price with end date "2023-09-16 12:05:30" printing the current timestamp:


https://github.com/PrestaShop/PrestaShop/assets/5434642/5b112191-65e6-427c-8430-60b770cd0629

2023-09-28 06:06 UTC, Gerardlc commented
@Hlavtox @matks Can we we merge it to develop then?

2023-09-28 07:36 UTC, matks commented
@Gerardlc the PR will have to go through the [validation process](https://devdocs.prestashop-project.org/8/contribute/contribution-process/how-pull-requests-are-processed/)

2023-09-28 13:35 UTC, boherm approved these changes

2023-09-28 14:36 UTC, Hlavtox commented
@Gerardlc Please check the draft I made, your PR is still missing some things. Also, the second input needs to be initialized with correct format, now its filled with date only.

2023-11-23 13:36 UTC, tleon approved these changes

2023-11-23 13:47 UTC, Hlavtox commented
PR that fixes it on all pages here ➡️ https://github.com/PrestaShop/PrestaShop/pull/33945
In QA already, this can be closed.

2023-12-06 09:53 UTC, jolelievre commented
Thanks @Gerardlc but it seems lie @Hlavtox was faster ^^
I close this PR in favor of already merged https://github.com/PrestaShop/PrestaShop/pull/33945
The fix will be available in 8.1.3

2023-12-06 09:53 UTC, closed without merging