fix(form): same group prevent duplication
PrestaShop/PrestaShop pull request #34238
Opened 2023-10-10 20:46 UTC by buggyzap

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Exception is displayed when I change my context shop while editing a product
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Follow same steps described in #34197
| UI Tests          | Please run UI tests and paste here the link to the run. [Read this page to know why and how to use this tool.](https://devdocs.prestashop-project.org/8/contribute/contribution-guidelines/ui-tests/).
| Fixed issue or discussion?     | Fixes #34197 
| Related PRs       | If theme, autoupgrade or other module change is needed to make this change work, provide a link to related PRs here.
| Sponsor company   | Your company or customer's name goes here (if applicable).

2023-10-11 15:22 UTC, matthieu-rolland reviewed
hello, could you please explain the fix ? I don't get how it fixes the exception 🤔

2023-10-11 17:34 UTC, buggyzap commented
> hello, could you please explain the fix ? I don't get how it fixes the exception 🤔

Ok I’ll try to explain how I achieved this.

Starting from the exception, I have been noticed that symfony are trying to render a component of the form that is already rendered and this is not permitted as the component is a widget. Widget can’t be rendered 2 times because they have an unique ID so symfony prevent this render and create an exception.

Commenting the exception will result in a double render of buttons “cancel” and “submit” as mentioned in open issue, commented with a screenshot.

To find out which parts of the rendering process are involved I have spent hours of debugging and at the end I figured out that the different “group” in the options of Button class will cause a double render so will create the exception, changing the group in “left” fix the issue, render the correct buttons and doesn’t trigger any exception, we are all happy 😂

If needed I can explain the entire process, with screenshots, which files are involved, etc… It took me a lot of time to understand how this process works and a specific part that cause the bug.

2023-10-16 16:03 UTC, matthieu-rolland commented
> 
> Ok I’ll try to explain how I achieved this.
> 

thank you for the explanation 👍 it's clear

2023-10-16 17:52 UTC, jolelievre requested changes
Sorry @buggyzap 

but the fix here is not enough, it does prevent the bug presented in the related issue but it doesn't fix the root problem which is a bug in `ButtonCollectionType` that is supposed to display the two buttons in different groups/divs

Changing the group options here hides the root problem, this form that is a bit complex to explain and fix so I took the liberty to prepare a PR that fixes the root problem https://github.com/PrestaShop/PrestaShop/pull/34305

I don't intend to steal your contribution so free to copy the fix in your PR if you wnt, then I'll close mine

2023-10-16 19:15 UTC, buggyzap commented
> Sorry @buggyzap
> 
> but the fix here is not enough, it does prevent the bug presented in the related issue but it doesn't fix the root problem which is a bug in `ButtonCollectionType` that is supposed to display the two buttons in different groups/divs
> 
> Changing the group options here hides the root problem, this form that is a bit complex to explain and fix so I took the liberty to prepare a PR that fixes the root problem #34305
> 
> I don't intend to steal your contribution so free to copy the fix in your PR if you wnt, then I'll close mine

Hi, thanks for your interest!

Are you sure that your changes doesn’t impact in all other forms of Prestashop and have a potential introduction of news bugs related to fact that this forms are created with this method too many times ago?  I’m happy if you fix current and future issues, but with my commit we have a very limited impact that changing the entire Prestashop ui kit? What do you think, devs? 

Ps. It’s not necessary that I copy your PR, if we decide to keep your PR the final result is more important of who have contributed 🤞🏻

2023-10-17 12:31 UTC, jolelievre commented
@buggyzap you're right my fix has more impacts, but I checked the different usages we have of this form type in the core to make sure they all work as expected, I was the one that introduced this form type initially (along with the UI kit theme integration) and also the one who added the recent feature of dropdown that broke the initial usage. I just didn't test all of them back in the day and I forgot about the group splitting

The form type is already buggy in 8.1 we just don't realize it because I think Symfony failed more silently, I actually think it should also be fixed in 8.1 although since it's a production release it would imply more risk so this is debatable. But for this fix targeting the develop branch we should have enough time to detect if something is wrong, and I can provide more details to QA about what needs to be tested so that nothing is forgotten.

2023-10-20 09:17 UTC, jolelievre commented
Thanks @buggyzap 
the alternative solution has been validated and merged https://github.com/PrestaShop/PrestaShop/pull/34305

So as we discussed I close this one 😉

2023-10-20 09:17 UTC, closed without merging