FIX: Combinations dropdown list on Specific Prices window, not loading all combinations on new product page. Combinations dropdown list on Specific Prices window, not loading all combinations on new product page.
PrestaShop/PrestaShop pull request #34250
Opened 2023-10-11 16:15 UTC by Naprosnia

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Only 10 combinations are displayed in the specific price section of a combination products on PPv2 of PS 8.1.2. This straightforward fix will eliminate this limit.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | 1. Go to BO > Create a combination product<br>2. Generate more than 20 combinations <br>3.Go to Pricing > Specific price block > Add a specific price <br>4. See in "All combinations" : All combinations should be visible now.
| Fixed issue or discussion?     | Fixes #34203, Fixes #34229

2023-10-13 15:26 UTC, matks requested changes
Hello @Naprosnia this is done on purpose 😄 this is not a bug.

It is important to limit the number of results displayed on a page to avoid crashing the page if there is a high number of items. The product page v1 did not limit the number of combinations displayed... and people would open products with hundred of combinations and their browser would freeze then crash.

2023-10-13 15:27 UTC, matks commented
Similar to https://github.com/PrestaShop/PrestaShop/pull/34244/

2023-10-15 16:07 UTC, Naprosnia commented
> Hello @Naprosnia this is done on purpose 😄 this is not a bug.
> 
> It is important to limit the number of results displayed on a page to avoid crashing the page if there is a high number of items. The product page v1 did not limit the number of combinations displayed... and people would open products with hundred of combinations and their browser would freeze then crash.

Hello @matks, I understand that using a large number of combinations may cause the browser to freeze. However, as you've noticed, we require the ability to select any combination in order to add specific prices. For now, this is the only option.

2023-10-16 06:21 UTC, Hlavtox commented
@matks What? How is that a solution? So you will just randomly only allow choosing the first 20 combinations?

2023-10-16 07:49 UTC, matks commented
> @matks What? How is that a solution? So you will just randomly only allow choosing the first 20 combinations?

See https://github.com/PrestaShop/PrestaShop/pull/34244#pullrequestreview-1676747688

2023-12-06 09:52 UTC, jolelievre commented
Hi @Hlavtox and @Naprosnia 

this bug has been fixed by this PR https://github.com/PrestaShop/PrestaShop/pull/34715
There was an issue with the join in the SQL query that prevented getting all the expected combinations (10) and if the total was not met the component considered it had it all and did not display the search input. Actually the component was smarter than the SQL query 😅

It should all be good now and be part of the 8.1.3, I will close this PR as the problem has been solved in a more performant way.

2023-12-06 09:52 UTC, closed without merging