Protect js folder from dangerous files
PrestaShop/PrestaShop pull request #34435
Opened 2023-11-01 13:50 UTC by ShaiMagal

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | There were several attacks where the attacker stored some PHP files into js folder. This PR prevents this and allows only selected files. Exceptions are two native files there. (jquery.noConflict, retro-compat)
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Tests green, try to put some PHP file in /js directory and try to access it from your browser.
| UI Tests          | 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   | https://www.openservis.cz/

2023-11-01 13:50 UTC, Hlavtox approved these changes

2023-11-01 14:57 UTC, kpodemski approved these changes, later dismissed
Makes sense. I'm pinging @matthieu-rolland for a final say.

2023-11-01 22:04 UTC, Hlavtox requested changes
@ShaiMagal One modification - I did a file scan of the folder and I found that we should also allow these files/extensions, can you check and add the extensions or specific files please?

```
/js/tiny_mce/skins/prestashop/fonts/tinymce.eot
/js/tiny_mce/skins/prestashop/fonts/tinymce-small.eot
/js/tiny_mce/plugins/colorpicker/index.html
/js/jquery/plugins/jstree/themes/apple/bg.jpg
/js/jquery/jquery-1.11.0.min.map
/js/tiny_mce/skins/prestashop/fonts/tinymce.svg
/js/tiny_mce/skins/prestashop/fonts/tinymce-small.svg
/js/tiny_mce/plugins/media/moxieplayer.swf
/js/tiny_mce/skins/prestashop/fonts/tinymce.ttf
/js/tiny_mce/skins/prestashop/fonts/tinymce-small.ttf
/js/tiny_mce/skins/prestashop/fonts/tinymce.woff
/js/tiny_mce/skins/lightgray/fonts/tinymce-mobile.woff
/js/tiny_mce/skins/prestashop/fonts/tinymce-small.woff
/js/tiny_mce/skins/prestashop/fonts/tinymce-mobile.woff
```

2023-11-01 22:37 UTC, Hlavtox approved these changes

2023-11-01 22:37 UTC, ShaiMagal commented
@Hlavtox Sorry, my fault. Fixed.

2023-11-02 10:14 UTC, M0rgan01 commented
Tests ui: https://github.com/M0rgan01/ga.tests.ui.pr/actions/runs/6731139006

2023-11-02 14:56 UTC, tleon approved these changes

2023-11-02 15:07 UTC, matthieu-rolland approved these changes
Looks good to me, thank you @ShaiMagal 👍

2023-11-02 15:09 UTC, matthieu-rolland commented
I'll do the QA dev

2023-11-02 15:27 UTC, matthieu-rolland commented
All good, php files inside the js folder are not accessible anymore 👍 

it's QA-dev aproved

2023-11-02 15:28 UTC, merged