Fixed SQL apostrophe (') incompatibility
PrestaShop/PrestaShop pull request #34441
Opened 2023-11-01 20:25 UTC by Lunyyx

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Fixed the problem that was caused by apostrophes in SQL queries, this problem happened when the user write something like "Merci d'insérer votre personnalisation" as the apostrophe (') was considered as the end of the string.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Try to duplicate an item with a apostrophe (') in the customization field

2023-11-01 20:39 UTC, Lunyyx commented
> Hi, thanks for this contribution!
> 
> I found some issues with the Pull Request description:
> 
> * Your pull request does not seem to fix any issue, consider [creating one](https://github.com/PrestaShop/PrestaShop/issues/new/choose) (see note below) and linking it by writing `Fixes #1234`.
> 
> Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!
> 
> ### About linked issues
> Please consider opening an issue before submitting a Pull Request:
> 
> * If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
> * It can help trigger a discussion about the best implementation path before a single line of code is written.
> * It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.
> 
> (Note: this is an automated message, but answering it will reach a real human)

Fixed the old pull request

2023-11-01 21:43 UTC, Hlavtox commented on src/Adapter/Product/Update/ProductDuplicator.php
> +                if (gettype($columnValue) == 'string') {
```suggestion
                if (is_string($columnValue)) {
```

2023-11-01 22:21 UTC, Hlavtox approved these changes
I think it's OK. :-)

Some prepared statement or built in escape method would probably be better, but given the scope of that method and how it manually builds the query by joining the fields, it should work just fine. There should be no other possible fails that it could encounter, the rest of the query is not dynamic.

2023-11-02 10:02 UTC, M0rgan01 commented
Tests ui: https://github.com/M0rgan01/ga.tests.ui.pr/actions/runs/6730992569

2023-11-02 10:05 UTC, Hlavtox commented
@M0rgan01 I think you ran the tests on develop instead of 8.1.x ;-)

2023-11-02 10:14 UTC, Lunyyx commented
> I think it's OK. :-)
> 
> Some prepared statement or built in escape method would probably be better, but given the scope of that method and how it manually builds the query by joining the fields, it should work just fine. There should be no other possible fails that it could encounter, the rest of the query is not dynamic.

Perfect ! :)

Yes, I think it's weird that there isn't any buildt in functions to do this, but anyway, it should work without any problem yes

2023-11-02 10:28 UTC, M0rgan01 approved these changes

2023-11-02 10:51 UTC, florine2623 approved these changes
Hello @Lunyyx ,

The field is not duplicated anymore. The process to checkout is working as expected.

It is QA ✅ 
Thanks!

2023-11-02 10:52 UTC, Hlavtox commented
@florine2623 I'm not sure I understand the message. :-)

This issue was about an error when duplicating a product in BO.
It didn't work before, now it should work with this PR.

2023-11-02 10:56 UTC, Hlavtox requested changes
Block to avoid accidental merge

2023-11-02 11:01 UTC, Lunyyx commented
> @florine2623 I'm not sure I understand the message. :-)
> 
> This issue was about an error when duplicating a product in BO. It didn't work before, now it should work with this PR.

Yes it is, maybe I didn't explained correctly, it's just about duplication of products in the BO.
Do I need to do something, or I just need to wait for someone to accept it ?

2023-11-02 14:06 UTC, matthieu-rolland approved these changes

2023-11-02 14:08 UTC, matthieu-rolland commented
why shouldn't the PR be merged @Hlavtox  ?

2023-11-02 14:19 UTC, florine2623 commented
Hello @Hlavtox ,

The field was duplicated here in FO :
<img width="1128" alt="Screenshot 2023-11-02 at 15 17 07" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/85bc88fe-9b98-4f45-a644-04f316ed3208">

And with the PR, the problem does not show up anymore ^^

<img width="1160" alt="Screenshot 2023-11-02 at 15 18 51" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/bfb9c4ae-a031-4da6-a73f-6d4761307cda">

2023-11-02 14:29 UTC, Hlavtox commented
@florine2623 OK, but the problem was in the backoffice, as you can see on video from @paulnoelcholot here - https://github.com/PrestaShop/PrestaShop/issues/34442#issuecomment-1790449698

![Snímek obrazovky 2023-11-02 152831](https://github.com/PrestaShop/PrestaShop/assets/6097524/3a34932b-dd7e-48cb-a73d-d98d7ac373e4)

2023-11-02 14:42 UTC, florine2623 commented
Hello again @Hlavtox and @Lunyyx ,

Indeed, well it seems that 2 problems are fixed then !
No duplication in FO and no error while duplicating a product in BO, when using an apostrophe ✅ 

Although, now, I have a deprecation alert in FO whenever I duplicate a product. Whether there's an apostrophe or not :
`Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /my_shop/classes/Validate.php on line 683`


<img width="1319" alt="Screenshot 2023-11-02 at 15 36 23" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/71e3ef7b-da8f-411a-a4c6-5c6b573d0f31">

Could you check ?

2023-11-02 15:08 UTC, kpodemski commented
@florine2623 is it really because of this PR? did you check it on installation without it?

2023-11-02 15:09 UTC, florine2623 commented
Hi again ^^

This PR can be merged as seen with @Hlavtox .
The other problem that I have is related to https://github.com/PrestaShop/PrestaShop/issues/33492 and can be fixed later on !

2023-11-02 15:10 UTC, Hlavtox commented
We checked with florine privately and the issue is not related. So all good. :) Thanks everyone!

2023-11-02 15:10 UTC, Hlavtox approved these changes

2023-11-02 15:10 UTC, merged