Add primary key to DB table accessory
PrestaShop/PrestaShop pull request #34530
Opened 2023-11-11 11:31 UTC by ShaiMagal

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Every DB table should have PRIMARY index. But DB table accessorry doesn't have. There is problem with Percona as well "Percona-XtraDB-Cluster prohibits use of DML command on a table (prestashop_41c9cd86_mysql.ps_accessory) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER" (check related issue below) - after/if this PR will be merged to 8.1.3, I will make commit this to module "autoupgrade" as well.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 
| UI Tests          | 
| Fixed issue or discussion?     | Fixes #30022
| Related PRs       | 
| Sponsor company   | https://www.openservis.cz/

2023-11-20 15:05 UTC, jolelievre requested changes
Definitely not in a patch version

2023-11-20 15:08 UTC, Hlavtox commented
@ShaiMagal Let's do it for develop, it's safer. There can be a major fuckup we can miss. :D

2023-11-20 15:10 UTC, ShaiMagal commented
@Hlavtox How can I change the branch to develop? I must close this and make new PR?

2023-11-20 15:15 UTC, Hlavtox commented
@ShaiMagal Rebase it onto develop, then change the branch here on GH, I will show you privately.

2023-11-20 15:19 UTC, ShaiMagal commented
@Hlavtox OK, after my vacation next week bro.

2023-11-25 11:48 UTC, Hlavtox approved these changes

2023-11-26 08:30 UTC, ShaiMagal commented
@jolelievre moved to develop

2023-11-27 10:10 UTC, mflasquin approved these changes

2023-11-27 10:33 UTC, florine2623 commented
This should be QAed by dev ^^

2024-01-11 10:53 UTC, jolelievre approved these changes
Thanks @ShaiMagal

2024-01-11 10:56 UTC, Hlavtox commented
@florine2623 Test run - https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/7487740011

2024-01-11 11:20 UTC, M0rgan01 approved these changes

2024-01-11 14:14 UTC, boherm approved these changes

2024-04-03 21:49 UTC, ShaiMagal commented
What is this PR waiting for ...? :-) (not sure to be honest)
@florine2623 @Hlavtox

2024-04-18 13:45 UTC, tleon commented
I tested this and it's ok for me the ps_accessory is now on a dual primary key.

2024-04-18 13:47 UTC, tleon commented
OK for merge if the tests are green.

2024-04-19 12:56 UTC, merged