SF6 - Remove deprecated code from TwigBundle
PrestaShop/PrestaShop pull request #34764
Opened 2023-12-04 14:30 UTC by M0rgan01

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Twig service is now private in sf 6
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Test UI and CI are green
| UI Tests          | https://github.com/M0rgan01/ga.tests.ui.pr/actions/runs/7128788665
| Fixed issue or discussion?     | Fixes #34005 
| Related PRs       | -
| Sponsor company   | -

2023-12-04 15:50 UTC, boherm approved these changes, later dismissed

2023-12-04 19:43 UTC, FabienPapet requested changes, later dismissed

2023-12-04 19:43 UTC, FabienPapet commented on src/PrestaShopBundle/Resources/config/services/bundle/twig.yml
> +    arguments: [ "@router" ]
autowire: true

2023-12-05 08:45 UTC, M0rgan01 commented on src/PrestaShopBundle/Resources/config/services/bundle/twig.yml
> +    arguments: [ "@router" ]
redundant thanks to _defaults.

2023-12-05 14:29 UTC, boherm approved these changes

2023-12-07 09:41 UTC, jolelievre approved these changes
Thanks @M0rgan01

2023-12-07 11:04 UTC, paulnoelcholot commented
Hello @M0rgan01,

2 test failling in the CI : https://github.com/paulnoelcholot/testing_pr/actions/runs/7126989453

2023-12-07 15:07 UTC, merged

2023-12-07 15:07 UTC, jolelievre commented
Thanks @M0rgan01