Fix img .htaccess
PrestaShop/PrestaShop pull request #34825
Opened 2023-12-13 08:36 UTC by metacreo

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop, 8.1.x
| Description?      | This fix 403 on img folder. Look to apache error log on production. You will see many 403 from googlebot and others. If image changed or deleted, bot give 403 instead of 404.
In access log: GET /8888-cart_default/product-999-title.jpg or webp (getting deleted or changed image)
In error log: Client denied for serverconf... /img/p/8/8/8/8
.htaccess for mod_php
.user.ini for php-fpm
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no

2023-12-13 08:52 UTC, kpodemski commented on img/.user.ini
@metacreo I think it is server-specific and won't work on some configurations. Better not to add this file.

2023-12-13 08:55 UTC, metacreo commented on img/.user.ini
Most of servers runs with php-fpm!!! No ability to turn off engine via htaccess on servers with fpm. user.ini is necessary in this situation

2023-12-13 09:10 UTC, kpodemski commented on img/.user.ini
I tested it on my server where I use php-fpm and it has no effect.

You really don't need to use three exclamation marks to prove your point :) If you want to help, that's fine, that's great, but please refrain from such behavior.

2023-12-13 09:22 UTC, metacreo commented on img/.user.ini
In general, I think that this is an error, the htaccess file should be removed from img directory altogether. The only thing it does is create a problem.
There is no code in the img directory. And if an attacker has the opportunity to place it there, then he can certainly do it in another place.

> I tested it on my server where I use php-fpm and it has no effect.
> 
> You really don't need to use three exclamation marks to prove your point :) If you want to help, that's fine, that's great, but please refrain from such behavior.

What the ttl time for user ini in your cfg ? Or your fpm configured to prevent user.ini 
I tested on my php82-fpm+apache24 is works fine

2023-12-13 10:39 UTC, Hlavtox commented
Ping @ShaiMagal

2023-12-13 11:03 UTC, metacreo commented on img/.user.ini
> You really don't need to use three exclamation marks to prove your point :) If you want to help, that's fine, that's great, but please refrain from such behavior.

Sorry, I didn’t think that three exclamation marks would offend you so much. :) In fact, I didn’t want to convey anything bad. It's just symbolic.

2023-12-13 16:14 UTC, kpodemski commented
I think it looks good, but I pinged our security guy @matthieu-rolland to take a look :)

2023-12-15 15:19 UTC, ShaiMagal requested changes
A) I can't agree with this edit.

It will allow malicious JS files there for example.

B) This is code only for apache 2.2, not apache 2.4

At apache 2.4 it will NOT block php files!

Incorrect usage of .htaccess.

Check original version. Your PR is dangerous.
No, No, No.

2023-12-15 15:21 UTC, ShaiMagal commented
@kpodemski Very dangerous PR, really not looks good... :)
This PR totally disables protection for apache 2.4... And for apache 2.2 it's only "half solution"...

2023-12-15 15:23 UTC, Hlavtox requested changes
I am not against changing exclusion to inclusion, but it must cover all dangerous files and work on all apache versions. 👍

2023-12-15 15:32 UTC, ShaiMagal commented
btw, on my testing PS (8.1.2) if I access to nonexistent image I got 404, not 403....
So, I can't reproduce your issue btw.
Example of nonexisting file:
https://demo80.psmoduly.cz/34343434-cart_default/product-999-title.jpg

2023-12-15 16:55 UTC, metacreo commented
> btw, on my testing PS (8.1.2) if I access to nonexistent image I got 404, not 403.... So, I can't reproduce your issue btw. Example of nonexisting file: https://demo80.psmoduly.cz/34343434-cart_default/product-999-title.jpg

https://demo80.psmoduly.cz/207-large_default/sifonove-saty-s-potiskem.jpg

2023-12-15 16:59 UTC, metacreo commented
> A) I can't agree with this edit.
> 
> It will allow malicious JS files there for example.
> 
> B) This is code only for apache 2.2, not apache 2.4
> 
> At apache 2.4 it will NOT block php files!
> 
> Incorrect usage of .htaccess.
> 
> Check original version. Your PR is dangerous. No, No, No.

this works both on 2.2 and 2.4  On my server latest 2.4 and worked

2023-12-16 01:57 UTC, metacreo commented
> It will allow malicious JS files there for example.

:) show example please. where should the malicious code come from? do you know about checking files when uploading to the server? or it doesn't work here? Do you know what the index files in the img directory are for?
if you are paranoid about executing code in the img directory, then why are there a bunch of index.php files there?
Have you seen servers that work from version 1.5 and with the number of images 20k, 50k and more... how many files are there index.php
And for 15 years, no one has executed any code in the img directory.

I’ll tell you more... You not find a production with at least 1k clients per day that would have this file in the image directory. Therefore, sensible admins will delete it.

The main problem with the PS team at the moment is that you are not paying attention to the real working projects. These projects are carried out by people with experience and knowledge. They do not need the help of the PS team, since they independently correct and supplement the PS engine.
At this time, the PS team has a new release, one test client, one test order, and the team is happy. But on real servers with a heavy load, with thousands of clients, with tens of thousands of products and with even more orders, where Google simply doesn’t come out and constantly re-crawls the site, the story is completely different than in your tests.

2023-12-17 19:40 UTC, matks commented
> The main problem with the PS team at the moment is that you are not paying attention to the real working projects.

Sorry @ShaiMagal and @Hlavtox it looks like you are not running real working projects :/

2023-12-17 19:49 UTC, matks commented
(I removed my previous joke message because I realize this topic has a serious probability to go overboard)

I am very happy to see constructive discussions about what to run in production and what not, but I insist discussion goes according to our [Code of Conduct](https://github.com/PrestaShop/PrestaShop/blob/a9bf43ba8c151333b4580293877188b9cbf8347d/CODE_OF_CONDUCT.md).

> Examples of behavior that contributes to creating a positive environment include:
>
> Using welcoming and inclusive language
Being respectful of differing viewpoints and experiences
Gracefully accepting constructive criticism
Focusing on what is best for the community
Showing empathy towards other community members

It's completely possible to discuss things that have been done in the past, demonstrate they are good or bad choices, discuss their strengths and weaknesses, without going into the judgement argument. I'm talking about this:

> The main problem with the PS team at the moment is that you are not paying attention to the real working projects.

This is completely useless and detrimental to this discussion @metacreo. You don't know us. Some people in the PrestaShop project, including @ShaiMagal and @Hlavtox are running PrestaShop websites for a living for many years now, please don't discard them.

Discussing about good points and bad points about this PR? I think this is very good for the project. Even if this PR is not merged at the end, it will allow anybody who read it to be able to understand the pros and cons and choose whether or not to apply this change to its own shop.

In the end if we don't agree on this topic, it's OK, software development and running live websites is a complex topic and landscape, we can't agree on everything.

But please don't go into the "people in PS team are like this or like that", else the discussion will be over soon :/

2023-12-18 05:58 UTC, metacreo commented
@matks By real projects I mean huge, popular sites with thousands of potential buyers per day. For sites with 1-10 visitors this does not cause any serious problems at all.

I respect the opinions of @ShaiMagal and @Hlavtox as well as any other participant. But excuse me, my own experience of 12 years and the experience of my colleagues, as well as the experience of hosting system administrators and the experience of working with top projects on PrestaShop is still a little more of a priority for me (us).

I just want prestashop not to go into a black hole, and this is really the case now. If you search, you not find popular sites that run on stock code, like it was before. It looks like presta have a serious problem with the developers, or rather a lack of them. To my great regret, the circle of people I know with experience no longer choose PrestaShop as a platform, and if they do, they either seriously modify it or move to another platform when the project becomes popular.

Sorry, no flood anymore

2023-12-19 06:54 UTC, ChillCode commented
Hi @metacreo 

Had the exact same issue while ago and ended  up modifying the .htaccess.

The real issue here came when Googlebot crawled an image and then customer removed it from BO so that bot started getting a 403 because it's trying to access a folder, as we ca see on the following link:

https://demo80.psmoduly.cz/207-large_default/sifonove-saty-s-potiskem.jpg

And what can happen if Googlebot receives a 403 on a server with fail2ban configured to block three 403 attempts? The server will start banning Googlebot IP addresses and that is not what we want.

Also detected that this file bypasses AUTH, and this is not right IMHO, because a PrestaShopCorp IP is connecting every since and then to get the logo.jpg bypassing mod_auth.

But I understand that this is not a major issue for many.

2023-12-19 08:46 UTC, metacreo commented
@ChillCode That's right. This is all already described here. What I’m writing about is that the admins fix it themselves and don’t bother with the PS team, they don’t have any problems on the test servers at all))).

In fact, I haven’t even seen such a “blocking” of the IMG directory in any project; this is a special feature of modern PrestaShop. )))

2024-01-16 05:49 UTC, closed without merging