Remove unused templates
PrestaShop/PrestaShop pull request #34933
Opened 2023-12-29 14:29 UTC by Hlavtox

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Read below
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Auto tests are sufficient.
| UI Tests          | 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   | 

### Description
- Made a tool that will list all twig templates in the source code and check if the template is used at least once. [usageChecker.zip](https://github.com/PrestaShop/PrestaShop/files/13794205/usageChecker.zip)
- After manual check, the result is about 15 templates that are unused.
- I also changed the paths to some templates, so it's unified with other paths.

2023-12-29 15:30 UTC, ShaiMagal approved these changes

2024-01-02 07:48 UTC, FabienPapet approved these changes

2024-01-02 08:48 UTC, matks requested changes
Even if these templates are not used in the software, it's a BC break 😉 

I would suggest checking git history for each of these files to make sure they are not being included using dynamic template naming (= we compute the name of the template at runtime)

2024-01-02 09:33 UTC, kpodemski commented on src/PrestaShopBundle/Resources/views/Admin/Helpers/dropdown_menu.html.twig
@Hlavtox what's the point of removing something that is treated as a helper? If it's a helper, it means that there's a chance somebody from the ecosystem uses it. Removing it for nothing is not worth it

2024-01-02 09:35 UTC, Hlavtox commented on src/PrestaShopBundle/Resources/views/Admin/Helpers/dropdown_menu.html.twig
That's what reviews are for. :-) Tell me what files you think are good to keep and I will remove them from the PR.

2024-01-02 09:41 UTC, Hlavtox commented
@matks

> I would suggest checking git history for each of these files to make sure they are not being included using dynamic template naming (= we compute the name of the template at runtime)

Yes, that is the case for unused templates in these paths.
- Common/Grid/Blocks/EmptyState
- Common/Grid/Actions
- Common/Grid/Columns

2024-01-24 14:58 UTC, M0rgan01 approved these changes

2024-03-27 08:09 UTC, closed without merging