Functional tests : Email subscription - Add some steps to check validation email
PrestaShop/PrestaShop pull request #35039
Opened 2024-01-12 17:00 UTC by nesrineabdmouleh

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Email subscription - Add some steps to check validation email
| Type?             | refacto
| Category?         | TE
| BC breaks?        |  no
| Deprecations?     | no
| How to test?      | CI and nightly are :green_apple: 
| UI Tests          | 
| Fixed issue or discussion?     | no
| Related PRs       | no
| Sponsor company   |

2024-01-16 09:03 UTC, Progi1984 requested changes
Please don't remove `img/tmp/CACHEDIR.TAG`

2024-01-16 09:33 UTC, Progi1984 commented on img/tmp/CACHEDIR.TAG
> -
It seems that it miss one line in file.

2024-01-16 09:35 UTC, Progi1984 reviewed
A last comment

2024-01-16 09:41 UTC, nesrineabdmouleh commented on img/tmp/CACHEDIR.TAG
> -
Done

2024-01-17 07:52 UTC, Progi1984 approved these changes

2024-01-18 17:56 UTC, boubkerbribri approved these changes

2024-01-18 17:56 UTC, merged

2024-01-18 17:56 UTC, boubkerbribri commented
Thanks @nesrineabdmouleh