Fix: Cannot install Prestashop 8.1.3 on Windows
PrestaShop/PrestaShop pull request #35052
Opened 2024-01-16 11:27 UTC by Codencode

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | When trying to install a new copy of Prestashop 8.1.3 on Windows, the system throws an error and crashes.
| Type?             | bug fix
| Category?         |  IN
| BC breaks?        |  no
| Deprecations?     | no
| Fixed issue or discussion?     | Fixes #35044

2024-01-16 11:48 UTC, Hlavtox commented
Maybe I am wrong, but does it make sense to first warmup the cache and then clean it?

@PrestaShop/committers Guys could you please check it out? Installer doesn't work on Windows at all, it would be good if it was fixed. Maybe there are some other issues also.

2024-01-16 11:52 UTC, Codencode commented
> Maybe I am wrong, but does it make sense to first warmup the cache and then clean it?
> 
> @PrestaShop/committers Guys could you please check it out? Installer doesn't work on Windows at all, it would be good if it was fixed. Maybe there are some other issues also.



> Maybe I am wrong, but does it make sense to first warmup the cache and then clean it?
> 
> @PrestaShop/committers Guys could you please check it out? Installer doesn't work on Windows at all, it would be good if it was fixed. Maybe there are some other issues also.

In fact it doesn't make much sense, but if you first clear the cache with the "cache:clear" command, when the system tries to execute the "cache:warmup" command it generates an error because it is not found, I think precisely because it is the cache has been emptied and therefore also all connected services.

2024-01-16 14:16 UTC, Codencode commented
### Original
![Original](https://github.com/PrestaShop/PrestaShop/assets/2463965/fff77c3f-c4d2-4436-a0d7-51ecf1f4e703)

https://github.com/PrestaShop/PrestaShop/assets/2463965/1ad8ffea-710d-40a9-8114-97b6571cf5b6

### With modification
![With modification](https://github.com/PrestaShop/PrestaShop/assets/2463965/87a0d0a9-7bee-460e-9656-9f4a0540d7f6)

https://github.com/PrestaShop/PrestaShop/assets/2463965/c3421011-d3de-4d0d-a9a3-36421902925f

2024-01-16 17:39 UTC, matks reviewed
I understand that changing the code this way seems to fix the situation but I think this patch is wrong. Because SymfonyCacheClearer is called from many places, for example when in the backoffice you upload a new module, and performing the warmup before the clearing is indeed not correct.

**What I understand is**: on Windows, when the warmup attempts to run, it fails because something is missing. No idea what, and as I am not running Windows, I can't verify.

**My suggestion**: I believe we should maybe change the logic inside `installer()`.

Can you check @Codencode when the function SymfonyCacheClear::clear() is called, by monitoring the stack trace? My guess is that it is called when installing modules.

In PR https://github.com/PrestaShop/PrestaShop/pull/29695/ was introduced a little setting ModuleManager::$systemClearCache that, when turned off, prevents the cache from being cleared.

Here is my suggestion to try:
1. Set ModuleManager::$systemClearCache to false -> this will avoid calling the cache clearing step when modules are installed
2. After all modules are installed, perform a clean cache clear then warmup

2024-01-17 10:12 UTC, Codencode commented
Hi @matks,
You're right, in fact it doesn't make much sense to reverse the instructions.
The error that is generated is the following:

**ERROR**:
"Failed opening required 'D:\cms\Prestashop\Site\prestashop813\var\cache\prod\ContainerA8Cu5F9\getConsole_Command_CacheWarmupService.php' (include_path='D:\cms\Prestashop\Site\prestashop813\vendor/pear/pear_exception;D :\cms\Prestashop\Site\prestashop813\vendor/pear/console_getopt;D:\cms\Prestashop\Site\prestashop813\vendor/pear/pear-core-minimal/src;D:\cms\Prestashop\Site\prestashop813\ vendor/pear/archive_tar;C:\xampp\8.1\php\PEAR')"

**CALL STACK**:
- Symfony\Component\Console\Application->doRun (d:\cms\Prestashop\Site\prestashop813\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:240)
- Symfony\Bundle\FrameworkBundle\Console\Application->doRun (d:\cms\Prestashop\Site\prestashop813\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php:83)
- PrestaShop\PrestaShop\Adapter\Cache\Clearer\SymfonyCacheClearer->PrestaShop\PrestaShop\Adapter\Cache\Clearer\{closure:D:\cms\Prestashop\Site\prestashop813\src\Adapter\Cache\Clearer\SymfonyCacheClearer.php: 63-109} (d:\cms\Prestashop\Site\prestashop813\src\Adapter\Cache\Clearer\SymfonyCacheClearer.php:103)

I also attach a debug video

https://github.com/PrestaShop/PrestaShop/assets/2463965/5249bf2c-e5d6-48ab-9dca-cccb70ebb1f0



Regarding the suggestion regarding ModuleManager::$systemClearCache, I couldn't find this attribute, in fact if you check here https://github.com/PrestaShop/PrestaShop/blob/8.1.x/src/Core/Module/ ModuleManager.php you will see that it is not there, so I was not able to do the test you suggested.

Thank you.

2024-01-17 12:12 UTC, Hlavtox commented
Yeah it's buggy when deleting it from admin also. Always some cache stub errors, lock files not existing etc.

2024-01-17 15:40 UTC, Codencode commented
A different solution from the one I proposed is the one proposed by @ChillCode here https://github.com/PrestaShop/PrestaShop/issues/35044#issuecomment-1895903686 which consists in modifying the AppKernel::getContainerClearCacheLockPath() method like this:

**original method**
```
    protected function getContainerClearCacheLockPath(): string
    {
        $class = $this->getContainerClass();
        $cacheDir = $this->getCacheDir();

        return sprintf('%s/%s.php.cache_clear.lock', $cacheDir, $class);
    }
```
**updated method**
```
    protected function getContainerClearCacheLockPath(): string
    {
        $class = $this->getContainerClass();;
        $cacheDir = sys_get_temp_dir();

        return sprintf('%s/%s.php.cache_clear.lock', $cacheDir, $class);
    }
```
I have tested it and it works both in case of installation and in case of deletion of the cache by the admin.

@Hlavtox @matks what do you think?

2024-01-26 07:57 UTC, Codencode commented
I removed the previous change as it was incorrect and made the change proposed by @ChillCode.

2024-03-14 11:50 UTC, Codencode commented
> A different solution from the one I proposed is the one proposed by @ChillCode here [#35044 (comment)](https://github.com/PrestaShop/PrestaShop/issues/35044#issuecomment-1895903686) which consists in modifying the AppKernel::getContainerClearCacheLockPath() method like this:
> 
> **original method**
> 
> ```
>     protected function getContainerClearCacheLockPath(): string
>     {
>         $class = $this->getContainerClass();
>         $cacheDir = $this->getCacheDir();
> 
>         return sprintf('%s/%s.php.cache_clear.lock', $cacheDir, $class);
>     }
> ```
> 
> **updated method**
> 
> ```
>     protected function getContainerClearCacheLockPath(): string
>     {
>         $class = $this->getContainerClass();;
>         $cacheDir = sys_get_temp_dir();
> 
>         return sprintf('%s/%s.php.cache_clear.lock', $cacheDir, $class);
>     }
> ```
> 
> I have tested it and it works both in case of installation and in case of deletion of the cache by the admin.
> 
> @Hlavtox @matks what do you think?

@Hlavtox @matks have you had a chance to check this out?

2024-03-18 16:55 UTC, SharakPL commented
> In PR #29695 was introduced a little setting ModuleManager::$systemClearCache that, when turned off, prevents the cache from being cleared.
> 
> Here is my suggestion to try:
> 
> 1. Set ModuleManager::$systemClearCache to false -> this will avoid calling the cache clearing step when modules are installed
> 2. After all modules are installed, perform a clean cache clear then warmup

@matks trying this on PS 8.1.5, but can't find `systemClearCache` anywhere in the files

2024-04-11 12:52 UTC, jolelievre requested changes
You can't do this, the cache dir of Symfony is not the tmp directory, it depends on the environment and the debug mode This modification ould certainly have huge negative impacts in all environments (including windows)

2024-04-11 13:04 UTC, Codencode commented
> You can't do this, the cache dir of Symfony is not the tmp directory, it depends on the environment and the debug mode This modification ould certainly have huge negative impacts in all environments (including windows)

Ok, so during the installation phase we could prevent the execution of the `cache:warmup` command which is what generates the problem.

We can edit the `src/Adapter/Cache/Clearer/SymfonyCacheClearer.php` file like this:
```php
if (!defined('PS_INSTALLATION_IN_PROGRESS')) { // The warmup should not be run during installation
    // Warmup prod environment only (not needed for dev since many things are dynamic)
    $application = new Application($kernel);
    $application->setAutoExit(false);
    $input = new ArrayInput([
        'command' => 'cache:warmup',
        '--no-optional-warmers' => true,
        '--env' => 'prod',
        '--no-debug' => true,
    ]);

    $output = new NullOutput();
    $application->doRun($input, $output);
}
```

2024-04-11 14:48 UTC, ChillCode commented
Now installation fails because it tries to copy the only locked file `(appAppKernelProdContainer.php.cache_clear.lock)` that is used precisely to block the current process, so not performing any action just to the this locked file is the other workaround to handle this for every system.

Don't know if using Symfony locking is plausible, at the end the issue will only occur when locked files are to be copied in this case.

Also when you have issues with WIN, get rid of the issue....but is an unpopular opinion, mine is that WSL or a cheap remote VM is a next step for any dev/maintainer and your computer will be safe.

2024-04-11 15:02 UTC, ChillCode commented
Hi @jolelievre 

> You can't do this, the cache dir of Symfony is not the tmp directory, it depends on the environment and the debug mode This modification ould certainly have huge negative impacts in all environments (including windows)

That change doesn't affect Symfony cachedir I think. only where `appAppKernelProdContainer.php.cache_clear.lock` will be stored during the current process.

My workaround only changes were that file resides even works when I apply on a clean PS 8.1.5 installation on a Debian VM, because my /tmp works and that file is not accessed during the clear process and deleted ate the end.

But as said before, some systems fake sys_get_temp_dir() or /tmp is just not set and can cause other issues.

2024-08-26 13:55 UTC, matks commented
Hi, I have changed the target branch to 8.2.x because of https://github.com/PrestaShop/PrestaShop/issues/36758

2025-04-18 14:29 UTC, kpodemski commented
hello @Codencode 

I like your suggestion to distinguish the code between the installer and the regular app state

2025-04-18 15:35 UTC, Codencode commented
Hello @kpodemski,

I think it could be an idea, but we should consider that the issue no longer occurs in PrestaShop version 9.
Maybe it's better to ignore this problem?

2025-04-20 06:57 UTC, Codencode commented
@kpodemski,

Would you perform the code check between the 2 environments in the method `SymfonyCacheClearer::clear() `https://github.com/PrestaShop/PrestaShop/blob/e94033735318d78ba5e43283f7bd1bf2094c081b/src/Adapter/Cache/Clearer/SymfonyCacheClearer.php#L92-L100,
or in `AppKernel::getContainerClearCacheLockPath() `https://github.com/PrestaShop/PrestaShop/blob/e94033735318d78ba5e43283f7bd1bf2094c081b/app/AppKernel.php#L269-L275?

In the first case, it would be:
```php
# src/Adapter/Cache/Clearer/SymfonyCacheClearer.php file like this:

if (!defined('PS_INSTALLATION_IN_PROGRESS')) { // The warmup should not be run during installation
    // Warmup prod environment only (not needed for dev since many things are dynamic)
    $application = new Application($kernel);
    $application->setAutoExit(false);
    $input = new ArrayInput([
        'command' => 'cache:warmup',
        '--no-optional-warmers' => true,
        '--env' => 'prod',
        '--no-debug' => true,
    ]);

    $output = new NullOutput();
    $application->doRun($input, $output);
}
```


In the second case, it would look like this:

```php
# app/config/AppKernel.php

if (defined('PS_INSTALLATION_IN_PROGRESS')) {
    $cacheDir = sys_get_temp_dir();
} else {
    $cacheDir = $this->getCacheDir();
}
```

2025-10-19 10:12 UTC, kpodemski commented
@Codencode does the new v9 cause errors when installing on Windows after recent changes from @jolelievre ?

if not, let's close this PR 👍🏻

2025-10-20 15:23 UTC, Codencode commented
@kpodemski with version 9 this problem never occurred.
So yes, you're right and I'll close the PR

2025-10-20 15:23 UTC, closed without merging