avoid dashactivity, dashproduct - module can't be configured
PrestaShop/PrestaShop pull request #35102
Opened 2024-01-18 17:23 UTC by NicolasCador

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop & 8.1.x
| Description?      | Following lines 82, 85 and 89 of admin-dev/themes/default/template/controllers/dashboard/helpers/view/view.tpl ; and following line 227 of js/admin/dashboard.js ; and following lines 425 and 428 of controllers/admin/AdminDashboardController.php : DASHBOARD_ALLOWED_HOOKS must be with hook*
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Go to BO<br>
In Activity overview > Click on the configure button<br>
Edit any of the parameters<br>
See NO error This hook is not allowed here.<br>
Refresh the page > See that the edition IS taken into account<br>

| UI Tests          | No
| Fixed issue or discussion?     | Fixes #34326
| Related PRs       | No
| Sponsor company   | No

2024-01-18 17:29 UTC, Hlavtox requested changes
This doesn't seem right, the hook prefix is only in method name. Also, you only changed half of the hooks.

Ping @matthieu-rolland, can you check?

2024-01-18 17:36 UTC, NicolasCador commented
Hi @Hlavtox, today, there is that in

2024-02-11 20:44 UTC, kpodemski approved these changes

2024-02-11 20:47 UTC, kpodemski commented
@Hlavtox It is a legit fix because in the payload, I see `hookDashboardZoneOne`, and `hookDashboardZoneTwo ` not `dashboardZoneOne`. We could either change the array values or introduce bc breaks by changing the payload, so it removes `hook` prefix. I think proposed fix should be ok.

2024-02-25 17:20 UTC, Hlavtox approved these changes

2024-02-26 10:38 UTC, florine2623 reviewed
Hello @NicolasCador ,

I have no more error.

But on Activity overview block, the changes are not saved after a refresh of the page :x:

https://github.com/PrestaShop/PrestaShop/assets/16019289/83800381-07cc-44c9-a009-e73d751d8e8e


On the block Products and Sales, the modifications are well saved. ✅ 

https://github.com/PrestaShop/PrestaShop/assets/16019289/02be1788-d5b8-40a3-a516-ec6bb94af439


Could you check ?
Thanks! :)

2024-04-03 14:20 UTC, NicolasCador commented
Hello @florine2623,
thank you for the bug report of dashactivity parameters saving.
I found the problem: the saving function is missing in dashactivity module.
I proposed another PR: https://github.com/PrestaShop/dashactivity/pull/46 to solve the other problem.
Ok, good to know that my proposition in this PR is OK, thanks!

2024-04-04 09:14 UTC, paulnoelcholot commented
Hello @NicolasCador,

For https://github.com/PrestaShop/dashactivity/pull/46 Some checks were not successful

2024-04-04 09:26 UTC, NicolasCador commented
Hello @paulnoelcholot,
yes you're right. But there is a problem, the error is:
 ------ ---------------------------------------------------------------------- 
  Line   dashactivity.php                                                      
 ------ ---------------------------------------------------------------------- 
  443    Parameter #1 **$variable** of method ModuleCore::getPermission() expects  
         array, string given.                                                  
 ------ ---------------------------------------------------------------------- 

It really expects a string, and not an array:
- in PS 8.0.x and 8.1.x it has been corrected: @param string $variable (action)
- in PS 1.7.7.x and 1.7.8, getPermission() just calls getPermissionStatic(), expecting a string:
    /**
     * Check employee permission for module.
     *
     * **@param _array_ $variable (action)**
     * @param Employee $employee
     *
     * @return bool if module can be transplanted on hook
     */
    public function getPermission(**$variable**, $employee = null)
    {
        return Module::**getPermissionStatic**($this->id, **$variable**, $employee);
    }

    /**
     * Check employee permission for module (static method).
     *
     * @param int $id_module
     * **@param _string_ $variable (action)**
     * @param Employee $employee
     *
     * @return bool if module can be transplanted on hook
     */
    public static function **getPermissionStatic**($id_module, **$variable**, $employee = null)
    {...

So how to do?

2024-06-20 16:00 UTC, NicolasCador commented
Hello all, how to move on?

2024-10-06 16:45 UTC, NicolasCador commented
Has been solved by #36521

2024-10-06 16:45 UTC, closed without merging