Remove another batch of deprecations
PrestaShop/PrestaShop pull request #35273
Opened 2024-02-06 08:54 UTC by Hlavtox

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Removes another big batch of deprecations, finalizes the removal of ASM.
| Type?             | refacto
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | Tests green, full test.
| UI Tests          | 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   |

2024-02-06 18:44 UTC, FabienPapet submitted a review, later dismissed
Less code, less bugs, nice work 😊

2024-02-06 19:21 UTC, matks requested changes
Disagree with this PR.

1. Some of the things you removed are marked `@deprecated since 9.0 and will be removed in 10.0, stock is now managed by new logic` and there is reason why. Why do you just ignore that.
2. You remove things without checking further whether or not they are being used. See `ajaxDie()` https://github.com/search?q=org%3APrestaShop%20ajaxDie&type=code

I might be wrong but it feels like this PR is just a throw-away PR where you thought "today I feel like I could clean some code" and you go here and there, removing things, without worrying about the impact, confident that nothing could go wrong :/

No jeopardizing the project because "it feels cleaner" please :/

2024-02-06 19:24 UTC, matks commented
@FabienPapet @FabienPapet Did you really review the PR :/ ? Because you approve a PR where multiple files marked `@deprecated since 9.0 and will be removed in 10.0` are deleted in the `develop` branch. Yes I guess you can miss one or two, but there are more than ten files like this

2024-02-06 19:47 UTC, Hlavtox commented
@matks I removed them because I was the one who put the deprecated notice. The ASM stuff was deprecated and non functional for the whole lifetime of 1.7, so I said that it's better to remove it fully instead of having non working object model and tables there. 🤷‍♂️

Regarding the ajaxDie and all other methods - I have checked for usage of EVERYTHING I removed and it's not used by the core. The usages in native modules will be fixed in time. The SA developer team does the same things - remove first and then fix the usages.

2024-02-07 08:59 UTC, Hlavtox commented
Update - I have extracted the ajax related things to separate PR.

2024-06-19 12:01 UTC, jolelievre requested changes
I didn't review everything but you are removing some classes/code that are not deprecated

Can you please revert those changes? I'll review again when the PR is a bit cleaner

2024-06-19 12:01 UTC, jolelievre commented on classes/ObjectModel.php
> +     * @deprecated since 1.5.0.1 Define property using $definition['table'] property instead.
Why not remove it then?

2024-06-19 12:01 UTC, jolelievre commented on classes/Product.php
> +             * @deprecated since 8.0 this DB column will be removed in a future version
Same here maybe it's time to remove it? Maybe in a dedicated PR though because there are other places that need to be clean (where we update this value in some arrays for example)

2024-06-19 12:01 UTC, jolelievre commented on classes/controller/FrontController.php
> +     * @deprecated since 1.7 This function shouldn't be used, use $this->registerStylesheet() instead
Oh I didn't know this one had been deprecated 🤔
It's surprising because it's still used a lot, we even have an issue to fix this in BO because of modification related to the Symfony layout

2024-06-19 12:01 UTC, jolelievre commented on classes/pdf/HTMLTemplateSupplyOrderForm.php
> - * @deprecated since 9.0 and will be removed in 10.0, stock is now managed by new logic
It's been deprecated in 9.0 only, so it shouldn't be removed now but in 10.0 as written in the comment

2024-06-19 12:01 UTC, jolelievre commented on classes/pdf/PDF.php
> -    /** @deprecated since 9.0 and will be removed in 10.0 **/
Too soon

2024-06-19 12:01 UTC, jolelievre commented on classes/stock/Stock.php
> - * @deprecated since 9.0 and will be removed in 10.0, stock is now managed by new logic
Too soon

2024-06-19 12:01 UTC, jolelievre commented on classes/stock/StockManager.php
> - * @deprecated since 9.0 and will be removed in 10.0, stock is now managed by new logic
Too soon

2024-06-19 12:01 UTC, jolelievre commented on classes/stock/StockManagerFactory.php
> - * @deprecated since 9.0 and will be removed in 10.0, stock is now managed by new logic
Too soon

2024-06-19 12:01 UTC, jolelievre commented on classes/stock/StockManagerInterface.php
> - * @deprecated since 9.0 and will be removed in 10.0, stock is now managed by new logic
Too soon

2024-06-19 12:01 UTC, jolelievre commented on classes/stock/StockManagerModule.php
> - * @deprecated since 9.0 and will be removed in 10.0, stock is now managed by new logic
Too soon

2024-06-19 12:01 UTC, jolelievre commented on classes/stock/StockMvt.php
> -class StockMvtCore extends ObjectModel
Hmm no I think it makes sense to extend ObjectModel, this way the override feature allows to override the base class of all object models Although it's not recommended it still makes sense for this override feature

2024-06-19 12:01 UTC, jolelievre commented on classes/stock/StockMvt.php
> -    public $id_supply_order = null;
Why remove those particular fields? They were not marked as deprecated

2024-06-19 12:01 UTC, jolelievre commented on classes/stock/StockMvt.php
> -    public static function getNegativeStockMvts($id_order, $id_product, $id_product_attribute, $quantity, $id_warehouse = null)
SAme here why remove this code?

2024-06-19 12:01 UTC, jolelievre commented on classes/stock/StockMvtReason.php
> - * @deprecated since 9.0 and will be removed in 10.0, this object model is no longer needed
So it's not deprecated anymore?

2024-06-19 12:01 UTC, jolelievre commented on classes/stock/StockMvtWS.php
> - * @deprecated since 9.0 and will be removed in 10.0, this object model is no longer needed
Too soon

2024-06-19 12:01 UTC, jolelievre commented on classes/stock/SupplyOrder.php
> - * @deprecated since 9.0 and will be removed in 10.0
Too soon

2024-06-19 12:01 UTC, jolelievre commented on classes/stock/SupplyOrderDetail.php
> - * @deprecated since 9.0 and will be removed in 10.0
Too soon

2024-06-21 09:53 UTC, Hlavtox commented on classes/ObjectModel.php
> +     * @deprecated since 1.5.0.1 Define property using $definition['table'] property instead.
I just wanted to make searching for `deprecated since` easier. :-)

2024-06-21 09:53 UTC, Hlavtox commented on classes/Product.php
> +             * @deprecated since 8.0 this DB column will be removed in a future version
I just wanted to make searching for `deprecated since` easier. :-)

2024-06-21 09:54 UTC, Hlavtox commented on classes/controller/FrontController.php
> +     * @deprecated since 1.7 This function shouldn't be used, use $this->registerStylesheet() instead
Yep, for 1.7, you need to use a different method.
However, in the controller parent and BO, it's not marked as deprecated and actively used.

2024-06-21 09:54 UTC, Hlavtox commented on classes/pdf/HTMLTemplateSupplyOrderForm.php
> - * @deprecated since 9.0 and will be removed in 10.0, stock is now managed by new logic
Yes

2024-06-21 09:54 UTC, Hlavtox commented on classes/pdf/PDF.php
> -    /** @deprecated since 9.0 and will be removed in 10.0 **/
Yes

2024-06-21 09:54 UTC, Hlavtox commented on classes/stock/Stock.php
> - * @deprecated since 9.0 and will be removed in 10.0, stock is now managed by new logic
Agree

2024-06-21 09:54 UTC, Hlavtox commented on classes/stock/StockManager.php
> - * @deprecated since 9.0 and will be removed in 10.0, stock is now managed by new logic
Agree

2024-06-21 09:54 UTC, Hlavtox commented on classes/stock/StockManagerFactory.php
> - * @deprecated since 9.0 and will be removed in 10.0, stock is now managed by new logic
Agree

2024-06-21 09:54 UTC, Hlavtox commented on classes/stock/StockManagerInterface.php
> - * @deprecated since 9.0 and will be removed in 10.0, stock is now managed by new logic
Agree

2024-06-21 09:54 UTC, Hlavtox commented on classes/stock/StockManagerModule.php
> - * @deprecated since 9.0 and will be removed in 10.0, stock is now managed by new logic
Agree

2024-06-21 09:55 UTC, Hlavtox commented on classes/stock/StockMvt.php
> -    public $id_supply_order = null;
Because id_supply_order is related to supply orders / advanced stock management, that was removed long time ago. This is just cleaning more remains.

2024-06-21 09:56 UTC, Hlavtox commented on classes/stock/StockMvt.php
> -    public static function getNegativeStockMvts($id_order, $id_product, $id_product_attribute, $quantity, $id_warehouse = null)
Whole class is to be removed, unused.

2024-06-21 09:57 UTC, Hlavtox commented on classes/stock/StockMvtReason.php
> - * @deprecated since 9.0 and will be removed in 10.0, this object model is no longer needed
Yes, I marked it as deprecated by accident I think.

2024-06-21 09:57 UTC, Hlavtox commented on classes/stock/StockMvtWS.php
> - * @deprecated since 9.0 and will be removed in 10.0, this object model is no longer needed
Agree

2024-06-21 09:57 UTC, Hlavtox commented on classes/stock/SupplyOrder.php
> - * @deprecated since 9.0 and will be removed in 10.0
Agree

2024-06-21 09:57 UTC, Hlavtox commented on classes/stock/SupplyOrderDetail.php
> - * @deprecated since 9.0 and will be removed in 10.0
Agree

2024-07-22 13:47 UTC, closed without merging