feat(infos): added hostname in system information
PrestaShop/PrestaShop pull request #35380
Opened 2024-02-15 17:25 UTC by Dreimus

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | When I have Prestashop in a load-balancing system, I can see the database name, but not the server hostname to identify on which server I am. This feature display the hostname on backoffice
| Type?             | new feature
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Go into System Information Tab in backoffice and see the hostname
| Fixed issue or discussion?     | Fixes https://github.com/PrestaShop/PrestaShop/discussions/33941
| Sponsor company   | Evolutive

2024-02-16 09:52 UTC, Hlavtox commented
@Dreimus Code style ;-)

2024-02-16 13:37 UTC, kpodemski commented on src/Adapter/Hosting/HostingInformation.php
> +
```suggestion

```

2024-02-22 00:27 UTC, FabienPapet approved these changes

2024-03-02 02:51 UTC, TheoAlloin approved these changes

2024-03-03 23:39 UTC, FabienPapet requested changes, later dismissed

2024-03-03 23:39 UTC, FabienPapet commented on src/Adapter/Hosting/HostingInformation.php
> +    /**
```suggestion
    }

    /**
```

2024-03-04 11:03 UTC, kpodemski approved these changes

2024-03-18 22:07 UTC, FabienPapet approved these changes

2024-03-19 08:20 UTC, nicosomb approved these changes

2024-03-20 16:27 UTC, boherm approved these changes

2024-03-25 10:36 UTC, florine2623 approved these changes
Hello @Dreimus ,

<img width="588" alt="Screenshot 2024-03-25 at 11 27 09" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/71f443d8-1a35-4d6f-b057-595531c7d9cf">


LGTM ✅ 
Thanks!

2024-03-25 10:45 UTC, merged