API Access Info endpoint
PrestaShop/PrestaShop pull request #35397
Opened 2024-02-16 17:04 UTC by M0rgan01

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | API Access Info endpoint
| Type?             | improvement
| Category?         | BO 
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI / tests UI are green
| UI Tests          | Please run UI tests and paste here the link to the run. [Read this page to know why and how to use this tool.](https://devdocs.prestashop-project.org/8/contribute/contribution-guidelines/ui-tests/).
| Fixed issue or discussion?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/34844
| Related PRs       | -
| Sponsor company   | -

2024-02-16 17:12 UTC, M0rgan01 commented on tests/Integration/ApiPlatform/EndPoint/ApiAccessTest.php
> +        $this->assertEquals('No Authorization header provided', $content);
waiting for https://github.com/PrestaShop/PrestaShop/pull/35368

2024-02-23 15:24 UTC, jolelievre submitted a review, later dismissed
Thanks @M0rgan01

2024-02-23 15:27 UTC, tleon requested changes

2024-02-23 15:27 UTC, tleon commented on src/PrestaShopBundle/ApiPlatform/Resources/ApiClient.php
> +            provider: QueryProvider::class,
you can remove this I think

2024-02-23 16:01 UTC, jolelievre commented on src/PrestaShopBundle/ApiPlatform/Resources/ApiClient.php
> +            provider: QueryProvider::class,
a nice cacth!

2024-02-23 16:03 UTC, jolelievre approved these changes, later dismissed

2024-02-23 16:04 UTC, tleon submitted a review, later dismissed

2024-02-23 16:18 UTC, jolelievre approved these changes

2024-02-23 16:33 UTC, tleon approved these changes

2024-02-23 17:17 UTC, merged