Functioanl tests - Add new test 'FO > Hummingbird > Change quantity in cart page'
PrestaShop/PrestaShop pull request #35440
Opened 2024-02-21 14:12 UTC by nesrineabdmouleh

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add new test 'FO > Hummingbird > Change quantity in cart page'
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI and nightly are :green_apple: 
| UI Tests          | 
| Fixed issue or discussion?     | no
| Related PRs       | no
| Sponsor company   | no

2024-02-21 15:46 UTC, Progi1984 approved these changes, later dismissed

2024-02-22 08:38 UTC, Progi1984 commented on admin-dev/hummingbird.zip
@nesrineabdmouleh To remove ?

2024-02-22 08:39 UTC, Progi1984 requested changes
Need to remove a file

2024-02-22 08:58 UTC, Progi1984 approved these changes

2024-02-22 10:34 UTC, boubkerbribri approved these changes

2024-02-22 14:23 UTC, merged