Order accessories by name
PrestaShop/PrestaShop pull request #35465
Opened 2024-02-25 21:18 UTC by Hlavtox

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Accessories in FO now show up in completely random order. Now they will be always ordered at least by name.
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | No need to test. Just accept by @kpodemski and @ShaiMagal
| UI Tests          | 
| Fixed issue or discussion?     |
| Related PRs       | 
| Sponsor company   |

2024-02-25 22:18 UTC, ShaiMagal commented
@Hlavtox 
Change this PR to develop branch my bro.
It could be better :)

2024-02-26 17:00 UTC, matthieu-rolland reviewed
Did you put this on 8.1.x on purpose ?
If it's not a regression fix it should go on develop 👍  (and have a related issue ideally ;) )

2024-02-26 19:44 UTC, LouisAUTHIE commented
Ok for the code, holding for the issue linked and it will be ok

2024-03-05 09:54 UTC, FabienPapet approved these changes, later dismissed

2024-03-05 10:23 UTC, SharakPL approved these changes, later dismissed

2024-03-08 09:12 UTC, paulnoelcholot commented
Hello @Hlavtox,

There is no issue related to this PR, need a PM approve.

@PrestaShop/product-council

2024-03-08 09:46 UTC, MatShir commented
No need for the issue, the enhancement is very minor.
But develop is required 🙏 

I don't want to have surprised pikachu 😮 I have been like this for a longtime. 
PM ✅ when the branch will be switched

2024-03-08 10:05 UTC, kpodemski requested changes, later dismissed
Approved by @MatShir if on `develop` 👍🏻 Blocking until the branch will be switched :D

2024-06-19 10:03 UTC, kpodemski approved these changes

2024-06-19 11:40 UTC, jolelievre approved these changes
Thanks @Hlavtox

2024-06-19 12:02 UTC, boherm approved these changes

2024-06-19 16:09 UTC, SharakPL approved these changes

2024-06-25 12:17 UTC, florine2623 reviewed
Hello @Hlavtox ,

Thanks for the PR !

Works like a charm.
Before:
<img width="1128" alt="Screenshot 2024-06-25 at 13 59 33" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/4b48455b-146e-4fac-a9f8-45d559cbc05a">

After, ordered in alphabetical order:
<img width="1133" alt="Screenshot 2024-06-25 at 13 59 26" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/248ba356-1db1-4de2-a088-c562cc64047f">

There's just a deprecation notice displayed on the FO. Also reproduced without this PR.
Do you think you can fix it here ?

<img width="1279" alt="Screenshot 2024-06-25 at 13 59 20" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/2d0caeba-dcf1-4d9f-8ebb-093534ac6d50">

`Warning: Undefined array key "id_product" in /my_shop/controllers/front/ProductController.php on line 1231`

2024-06-25 12:22 UTC, ps-jarvis commented
<!-- PR_TABLE_DESCRIPTION_ERROR -->
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

2024-06-27 13:34 UTC, florine2623 commented
This issue is linked to debug mode not to your PR.
It is QA ✅ 
Thanks!

2024-06-27 14:52 UTC, merged