Add Export button missing on new Product Page V2
PrestaShop/PrestaShop pull request #35488
Opened 2024-02-26 19:33 UTC by ChronoBrake

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 8.1.x
| Description?      | This PR introduces the much-requested "Export" button to the new Product Page V2 in PrestaShop, addressing a significant gap in the platform's functionality. Previously, users experienced a workflow interruption due to the absence of an export feature directly from the product list, which is essential for exporting data to CSV or Excel formats for various operational needs. This update brings consistency across the platform's interfaces, significantly enhances operational efficiency, enables seamless data integration with external systems, supports advanced reporting and analytics, and meets user expectations for feature parity with previous versions. By reinstating the export feature, this PR ensures that PrestaShop remains a comprehensive tool for e-commerce businesses, catering to their evolving needs and maintaining its utility and user satisfaction.
| Type?             | improvement / new feature
| Category?         | BO
| BC breaks?        | no
| How to test?      | Turn new product page -> Go to the product list -> click config icon -> click "Export"
| Fixed issue or discussion?     | #35485
| Sponsor company   | Code Olympus

2024-03-05 00:56 UTC, OrionCodeDev commented
I must do something else or ping somebody for show ready state of this pull? Sorry, but it's my first pull request.

2024-03-05 15:43 UTC, boherm commented
> I must do something else or ping somebody for show ready state of this pull? Sorry, but it's my first pull request.

Hi @ChronoBrake! Thanks for your first contribution! ;)
No, we just need to review it and test it before merging.

Some steps could take some times, but we will check your PR as soon as possible!

2024-03-05 15:51 UTC, boherm requested changes
LGTM, thanks @ChronoBrake!
Just a little comment about the `_legacy_link` ;)

2024-03-05 15:51 UTC, boherm commented on src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/products_v2/product.yml
> +    _legacy_link: AdminProducts:exportproduct
The `exportproduct` doesn't seems to be in the legacy `controllers/admin/AdminProductsController.php`.
Maybe, we can simply do this:

```suggestion
    _legacy_link: AdminProducts
```

2024-03-05 20:23 UTC, OrionCodeDev commented on src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/products_v2/product.yml
> +    _legacy_link: AdminProducts:exportproduct
@boherm yeah, it's will be better. Commited

2024-03-05 20:26 UTC, OrionCodeDev commented
Added @boherm suggestion.

2024-03-06 10:17 UTC, boherm approved these changes

2024-03-15 11:45 UTC, OrionCodeDev commented
@boherm i must do anything else or it's need time for devs to verify?

2024-03-20 08:17 UTC, boherm commented
Hi @ChronoBrake, yes for now we just need some time on our side to review your PR.
I've start the CI, to make a little check about coding standard on your work ;)

2024-04-08 09:12 UTC, OrionCodeDev commented
Okay, so i will be here if you wanna ask for repair or changing something. All checks green, so i think it's good. @boherm

2024-04-30 12:53 UTC, nicosomb approved these changes

2024-06-05 08:45 UTC, florine2623 approved these changes
Hello @ChronoBrake ,

Auto test ✅ : https://github.com/florine2623/testing_pr/actions/runs/9369588578

Export is working as expected.
Tested with all products.
Tested with filtered list of products (one and multiple filters).
Tested with no products.

It is QA ✅ 
Thanks!

2024-06-05 09:49 UTC, merged

2024-06-26 14:39 UTC, PascalB67 commented
Hello it's ok for this version (8.17), 
In the middle of developing a tool processing "data export", ... my heart rate increased significantly ... :)
The export limit seems to be based on the display of the page... ORDER BY id_product asc LIMIT 100. (In parentheses it is no longer possible to display more than 100 products per page... oops, bad idea). 
I will use another interface to export
Thanks