Don't show PrestaShop version on PrestaShop login screen
PrestaShop/PrestaShop pull request #35518
Opened 2024-02-28 22:04 UTC by ShaiMagal

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | 
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 
| UI Tests          | 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   | https://www.openservis.cz/

2024-02-28 22:23 UTC, Hlavtox approved these changes
OK for me, do you know of other ways to detect prestashop version?

2024-02-29 08:47 UTC, matks requested changes, later dismissed
> Please, skip comments like "Attacker doesn't know BO URL location" or "Attacker can have other options how to get PS version"

Nice try but actually I think they are very valid arguments 😛 

Having the version number here can be useful and I don't think it is a security issue. I think this PR provides zero additional security. I have been helping running the security bug bounty for 4 years and no ethical hacker ever reported that problem, so I think it is not a security issue.

2024-02-29 09:03 UTC, matks commented
To explain better my comment:

This information could be harmful if it was exposed to an attacker. This would help the attacker because using the version number he could browse known security vulnerabilities and use them against the version, when vulnerable.

However this login page is indeed supposed to be random. Moreover if you are very afraid that someone could guess its location, you can add more protections such as IP whitelisting for the admin URL pattern. You have multiple means to secure that login page.

So for me this login page is a "safe place" just like all of the back-office. Then we can put there useful informations for the shop admin, for developers working on the shop, and so on.

For example I think displaying the version number here is useful for people who login into their backoffice after performing an upgrade.

2024-03-04 21:00 UTC, FabienPapet approved these changes

2024-03-04 21:05 UTC, FabienPapet commented
IMO This should be removed or at least configurable. Hiding the version of the software you are using is a valid use case. considering the number pf attacks coming from 3rd party modules.

2024-03-05 15:36 UTC, boherm commented
Sorry but I think that a prefer to hide this information too 🤔
This information could be critical and very interesting for attackers.
And yeah, ok this login page is supposed to be in a random url, but... it could be easily find by an attacker anyway. 💁‍♂️
I agree, that it's the merchant responsibility to keep the server secure, but we must do also our part of the job in certain way.

2024-03-07 17:40 UTC, matthieu-rolland approved these changes
I can't see a usecase in which it is useful to display the PS version on the login page (even after an upgrade, the user will see the PS version once he is logged in... or worse case scenario, he will have to check in the code base)

@matks I agree that this page has a random url, which makes this "security issue" not critical at all, but removing this information is still a small step in the right direction imho

That being said, hackers specialized in PrestaShop probably know how to find the broad PS version from the FO anyway.

2024-03-13 09:30 UTC, matks commented
Guys I'm still not convinced by this change

But you know what else I'm convinced about? The importance of compromises and trust in each other 😉 so I remove my "request changes"

2024-03-13 09:31 UTC, matks commented
@ShaiMagal That being said you still need to explain "how to test" this PR 😛

2024-03-14 15:15 UTC, florine2623 approved these changes
Thanks for all the feedback.

The version number is well removed.

<img width="178" alt="Screenshot 2024-03-14 at 16 13 59" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/9af63bdb-26ec-4d00-89c5-31d94ebc0a2a">

2024-03-15 08:10 UTC, merged

2024-03-20 11:12 UTC, ShaiMagal commented
Thank you for cooperation of all members.

This is small PR, but every small step is important for future of PrestaShop.

More PR in future will come soon.