Fix strstr modifier
PrestaShop/PrestaShop pull request #35705
Opened 2024-03-21 07:59 UTC by Hlavtox

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Fixes issue `PHP Deprecated:  Using php-function "strstr" as a modifier is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier.`
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 
| UI Tests          | 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   |

2024-03-21 11:56 UTC, SharakPL approved these changes

2024-03-21 12:00 UTC, SharakPL requested changes

2024-03-21 12:00 UTC, SharakPL commented on config/smarty.config.inc.php
> +smartyRegisterFunction($smarty, 'modifier', 'strstr', 'strstr');
```suggestion
smartyRegisterFunction($smarty, 'modifier', 'strstr', 'strstr');
smartyRegisterFunction($smarty, 'modifier', 'strtolower', 'strtolower');
```
Let's keep it in order this time to avoid further duplications ;)

2024-03-21 12:03 UTC, Hlavtox commented on config/smarty.config.inc.php
> +smartyRegisterFunction($smarty, 'modifier', 'strstr', 'strstr');
HA :D I swear to god I had you in mind :D I said "Sharak is working on making it alphjabetical, let's not mess it up".

I need to buy glasses :D

2024-03-21 12:03 UTC, SharakPL approved these changes

2024-03-21 22:57 UTC, FabienPapet approved these changes

2024-03-25 09:07 UTC, boherm approved these changes

2024-03-25 10:20 UTC, florine2623 commented
Hello @Hlavtox ,

Could you share the How to test steps please ? :)

Thanks!

2024-04-02 09:16 UTC, Hlavtox commented
@florine2623 I think that green UI tests suffice, it's the same as all of the other modifiers

2024-04-03 12:34 UTC, florine2623 reviewed
The auto tests are broken : https://github.com/florine2623/testing_pr/actions/runs/8523037501/job/23383999023

@PrestaShop/qa-automation do you think this is related to this PR ?

Thanks!

2024-04-03 12:36 UTC, Progi1984 commented
> The auto tests are broken : https://github.com/florine2623/testing_pr/actions/runs/8523037501/job/23383999023
> 
> @PrestaShop/qa-automation do you think this is related to this PR ?
> 
> Thanks!

No, it's not linked.

2024-04-03 12:37 UTC, florine2623 commented
Thanks, so I can approve @Hlavtox 's PR ^^

2024-04-03 13:40 UTC, merged

2024-04-03 13:54 UTC, SharakPL commented
@florine2623 since I don't see this modifier used anywhere in the PS, you may want to create a test case. For example change **themes/classic/templates/index.tpl** like so:

![obraz](https://github.com/PrestaShop/PrestaShop/assets/5007456/edde7161-ed67-4fe2-89bc-061fc3f259ce)

and then open the front page. It should show `@domain.com` text right before imageslider, but without this PR it will also throw a deprecation notice

![obraz](https://github.com/PrestaShop/PrestaShop/assets/5007456/9a47080d-7e0b-4820-8c8b-3cbfa9fbe898)