Merge `8.1.x` into  `develop`
PrestaShop/PrestaShop pull request #35893
Opened 2024-04-11 08:41 UTC by tleon

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Merge `8.1.x` into `develop`
| Type?             | improvement
| Category?         | ME
| BC breaks?        |  no
| Deprecations?     | no
| How to test?      | CI & tests 🟢
| UI Tests          | Please run UI tests and paste here the link to the run. [Read this page to know why and how to use this tool.](https://devdocs.prestashop-project.org/8/contribute/contribution-guidelines/ui-tests/).
| Sponsor company   | PrestaShop SA

2024-04-11 09:41 UTC, jolelievre requested changes

2024-04-11 09:41 UTC, jolelievre commented on src/PrestaShopBundle/Form/Admin/Product/ProductQuantity.php
I think this file has been removed along with the old product page, it should be cleaned and not be reintroduced in the develop branch

2024-04-11 13:12 UTC, Progi1984 approved these changes, later dismissed
Ok for UI Tests

2024-04-11 13:20 UTC, nicosomb submitted a review, later dismissed

2024-04-11 14:40 UTC, jolelievre submitted a review, later dismissed

2024-04-12 07:25 UTC, boherm approved these changes, later dismissed

2024-04-12 15:48 UTC, M0rgan01 submitted a review, later dismissed

2024-04-16 07:09 UTC, nicosomb commented
Don't merge, UI tests are red.

2024-04-16 10:57 UTC, nicosomb commented
UI tests: https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/8702817085

2024-04-16 14:58 UTC, nesrineabdmouleh approved these changes

2024-04-17 07:14 UTC, boherm approved these changes

2024-04-17 08:22 UTC, matthieu-rolland approved these changes

2024-04-17 12:58 UTC, merged