Add new condition types
PrestaShop/PrestaShop pull request #35919
Opened 2024-04-15 10:07 UTC by Hlavtox

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Adds three new conditon types to account for common business scenarios.
| Type?             | new feature
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Try to use those new conditions.
| UI Tests          | 
| Fixed issue or discussion?     | 
| Related PRs       | Autoupgrade PR must come.
| Sponsor company   | 

### New conditions
- Damaged - slight item damage, from shipping for example, but can be sold just fine.
- Open package - items returned in 14 day period, but new apart from having opened packaging.
- B grade - items that have some slight manufacturing defects, but can be sold just fine.

2024-04-17 07:16 UTC, kpodemski commented
Hi @Hlavtox 

Could you create [an idea](https://github.com/PrestaShop/PrestaShop/discussions/categories/ideas) here just for other members of @PrestaShop/product-council to confirm it is valid and get it done?

2024-04-17 07:43 UTC, Hlavtox commented
@kpodemski I created an idea there - https://github.com/PrestaShop/PrestaShop/discussions/35945

2024-04-17 11:35 UTC, ShaiMagal approved these changes, later dismissed

2024-04-17 13:35 UTC, jf-viguier commented
it's ok for me

2024-04-25 06:50 UTC, Hlavtox commented
@kpodemski As one member of product council approved and no others commented, I am putting the PM flag.

2024-04-25 12:11 UTC, MatShir commented
IMO this improvement is specific to your uses cases. 
We should either leave that way and let the user update the DB for their personal use or make it dynamic.

2024-04-25 12:12 UTC, MatShir requested changes
IMO this improvement is specific to your uses cases. 
We should either leave that way and let the user update the DB for their personal use or make it dynamic (core or native module)
I don't see why it should be one part of the core project.

2024-04-25 12:19 UTC, Hlavtox commented
@MatShir It's not specific to my usecase, its a fairly common request from my clients.
Making it dynamic is much more work. This works and gets the job done for minimal effort, with no BC breaks.

2024-04-25 12:30 UTC, kpodemski commented
> IMO this improvement is specific to your uses cases.

I also disagree. It's not a specific use case but a set of different, industry-standard conditions added to a selection.

While I agree that this could be configurable, I don't see it as something half-baked, it can be safely implemented since it is backward compatible, and provides extra option for a user.

2024-04-25 12:48 UTC, MatShir commented
I agree there is a lack of labels available. There are so many different from depending on the businesses (https://www.amazon.com/gp/help/customer/display.html?nodeId=201889720).
It has never been a bug issue on since I think people feature to bypass it. 
So adding new inputs that don't fit all the needs IMO is not worth it.

Or we should a bunch more, so people can change by changing the translation 🤔

2024-04-25 12:52 UTC, Hlavtox commented
Nobody will program this to be dynamic, it's just too much work. Creating database tables, providers, controllers, forms. Also, we would need to prevent people deleting the default ones. Also, now it would be possible to map the condition to other modules. Many caveeats for small value.

If somebody has very specific business, he can modify the core more to add his own conditions. These ones are general ones that can be applied to every business. Every merchant in EU sells returned open box items once in a while.

2024-04-25 14:51 UTC, MatShir commented
I agree that making a dynamic fields would be quite expensive and not really worth it. I suggest only removing **B grade** which is a repetition from the damaged and opened.

2024-04-26 08:59 UTC, Julievrz commented on src/Adapter/Presenter/Product/ProductLazyArray.php
> +                    'label' => $this->translator->trans('Opened package', [], 'Shop.Theme.Catalog'),
You mentionned in the description that the product is still new. We could specify that in the label. For example, Amazona and Ebay use "New - Open box" which I think is very clear.

2024-04-26 08:59 UTC, Julievrz commented on src/Adapter/Presenter/Product/ProductLazyArray.php
> +                    'label' => $this->translator->trans('B grade', [], 'Shop.Theme.Catalog'),
What about "New with defects". This way we understand the product is new but could have small imperfections.

2024-04-26 09:01 UTC, Julievrz commented
Also I don't understand the difference between "Damage" and "B-grade", I think we would have only 1 label like "New with defects"

2024-04-26 09:06 UTC, Hlavtox commented
@Julievrz
Damaged - dents, scratches from shipping or bad handling
B - grade/Second - items with manufacturing defects, bad paint, misaligned parts that didn't pass inspection as good quality items (https://en.wikipedia.org/wiki/Factory_second)

2024-04-26 09:07 UTC, Hlavtox commented
OK, so final list?
- New
- New, open box
- New, minor defects
- Used
- Refurbished
- Damaged

2024-04-26 09:19 UTC, MatShir commented
So Damaged is not a new product ? 
Damaged and new with defects/minor defects kind of look very similar. From your description the damages, one comes from the factory and the other from the last shipment, but the defects are the same. So why make a difference for the consumer?

2024-04-26 09:19 UTC, Julievrz commented
> @Julievrz Damaged - dents, scratches from shipping or bad handling B - grade/Second - items with manufacturing defects, bad paint, misaligned parts that didn't pass inspection as good quality items (https://en.wikipedia.org/wiki/Factory_second)

I understand but for the final customer, the result seems to be the same: the product is slightly imperfect. Why do we need to have 2 different labels?

Also "Damaged" could be confused with "For parts" or "Not working" when a product is damaged and needs repair.

2024-04-26 09:30 UTC, Hlavtox commented
@Julievrz @MatShir The merchants usually always specify what is wrong with the product by photos and descriptions, showing the damage, imperfections. The conditions are only for general classification.

2024-04-26 11:38 UTC, Julievrz commented
> @Julievrz @MatShir The merchants usually always specify what is wrong with the product by photos and descriptions, showing the damage, imperfections. The conditions are only for general classification.

I think this is another reason not to get too specific. There are many other conditions we could add but if we want to keep it simple, I think one condition "New, minor defects" could work for both use cases. Especially if there are pictures.

2024-05-07 12:52 UTC, Hlavtox commented
@jf-viguier @ShaiMagal @kpodemski Can you state your opinion here?

A)
New
New, open box
New, minor defects
Used
Refurbished
Damaged

or

B)
New
New, open box
New, minor defects
Used
Refurbished

I don't think it's such an issue to have 6 options instead of 5. :-)))

2024-05-07 12:54 UTC, FabienPapet submitted a review, later dismissed

2024-05-08 11:17 UTC, kpodemski commented
@Hlavtox 

New, minor defects to me sound good enough to describe "New, open box"; the details could be in the description.

2024-05-08 11:42 UTC, Hlavtox commented
@kpodemski Thats not what was questioned, @Julievrz was asking of we want to merge `Damaged` and `New, minor defects` together.

2024-05-08 11:45 UTC, kpodemski commented
@Hlavtox 

ahh, all right, Damaged sounds more serious than New, minor defects 🤔 but then it's about how damaged is minor and major, soooo, I don't know, I feel like we definitely spend too much time on this PR, maybe keeping more options would be easier for end user to decide what they feel is ok for them :)

2024-05-08 11:50 UTC, Hlavtox commented
@kpodemski Yeah, it could be merged 3 weeks ago with 1 hour spent...

Users open this box only for items with some non standard condition, and if we want to please more of the merchants, 6 options instead of 5 has no harm. Certainly it won't endanger the business of Prestashop SA. :-)

So, this is the time I want to spend on it.

@MatShir @Julievrz If you disagree, I will just close it.

2024-05-08 11:52 UTC, kpodemski approved these changes

2024-05-14 15:47 UTC, Julievrz commented
> @kpodemski Yeah, it could be merged 3 weeks ago with 1 hour spent...
> 
> Users open this box only for items with some non standard condition, and if we want to please more of the merchants, 6 options instead of 5 has no harm. Certainly it won't endanger the business of Prestashop SA. :-)
> 
> So, this is the time I want to spend on it.
> 
> @MatShir @Julievrz If you disagree, I will just close it.

Hello Daniel,

Actually, my recommendation was "New, with defects" (not "minor defects").

In my opinion, the problem is not to have 6 options instead of 5. The problem is to have 2 options that mean the same thing.

2024-05-14 18:13 UTC, Hlavtox commented
@Julievrz `Manufacturing defects` (manufacturer second) is not the same thing as `scratch and dent`. Source - my work for 15 years.

2024-05-15 18:34 UTC, closed without merging

2024-05-15 18:36 UTC, Hlavtox commented
Closing this as we are unable to find consensus with Prestashop SA employees.