Update redirect_type enum values
PrestaShop/PrestaShop pull request #35996
Opened 2024-04-23 09:14 UTC by M0rgan01

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove unnecessary redirect_type in product and product_shop tables, see https://github.com/PrestaShop/PrestaShop/blob/ada985284ce331b28539adfc3b374879e1749b2c/src/Core/Domain/Product/ValueObject/RedirectType.php
| Type?             | improvement
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | Check that the redirection feature of a product has not changed
| UI Tests          | https://github.com/M0rgan01/ga.tests.ui.pr/actions/runs/8797906754
| Fixed issue or discussion?     | -
| Related PRs       | https://github.com/PrestaShop/autoupgrade/pull/689
| Sponsor company   | -

### BC breaks

Empty string is no longer valid in `redirect_type` for `product` and `product_shop` tables

2024-04-23 09:58 UTC, Hlavtox requested changes
As we talked in https://github.com/PrestaShop/autoupgrade/pull/689/, I think that we should not do this in 8.1.x branch, because it would be a BC break for modules that still insert the default string as the default value.

2024-04-23 13:09 UTC, Hlavtox approved these changes

2024-04-23 14:21 UTC, ga-devfront approved these changes

2024-04-23 14:48 UTC, florine2623 commented
@M0rgan01 could you relaunch the auto tests please ? :D

2024-04-23 15:11 UTC, boherm approved these changes

2024-04-23 16:26 UTC, M0rgan01 commented
Done @florine2623 :)

2024-04-24 08:01 UTC, jolelievre approved these changes

2024-04-26 13:59 UTC, florine2623 approved these changes
Hello @M0rgan01 ,

Tested all the types of redirection.
Tested this feature on all types of products.
Tested on existing products/newly created products.
Feature redirection works as before ✅ 

Thanks!

2024-04-28 09:18 UTC, merged