fix flag new traduction
PrestaShop/PrestaShop pull request #36067
Opened 2024-05-01 22:14 UTC by medMethnani

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 8.1.x
| Description?      | Fix the **New** flag on product image translation from back office.
| Type?             | bug fix
| Category?         | FO / BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | The traduction will now show correctly on front page on the **New** products with badge **New** well translated if its French langue it show **Nouveau**,...
| UI Tests          | Please run UI tests and paste here the link to the run. [Read this page to know why and how to use this tool.](https://devdocs.prestashop-project.org/8/contribute/contribution-guidelines/ui-tests/).
| Fixed issue or discussion?     | NONE
| Related PRs       | NONE
| Sponsor company   | Med METHNANI.

2024-05-02 07:18 UTC, Hlavtox requested changes
This has been changed back and forth many times. Before changing anything, we need to analyze the situation.

2024-05-02 08:11 UTC, medMethnani commented
Hello, this is my first contribution on Prestashop if you can help me what should i do next ? 
Because there is a bug i'm sure 100% on the prestashop Backoffice related to the translation.
Thanks.

2024-05-02 13:38 UTC, matthieu-rolland reviewed
@medMethnani hello, and thank you for your contribution 👍 

You should create an issue, with steps to reproduce it, then the QA team will try to reproduce it, and from there we'll see what must be done.

Then you can like the issue in your PR's description, so that next reviewers can check it out

2024-05-02 20:24 UTC, medMethnani commented
Hello @matthieu-rolland , thanks for your answer this is the bug link: https://github.com/PrestaShop/PrestaShop/issues/36076
What to do next :)

2026-03-11 22:17 UTC, kpodemski commented
This should be fixed in v9.

2026-03-11 22:17 UTC, closed without merging