Availability in structured data for products that are not available to order
PrestaShop/PrestaShop pull request #36124
Opened 2024-05-09 21:36 UTC by webeshop

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | If stock management is turned off and the product is not available for ordering, InStock availability is displayed in structured data. This pull request fixes this problem.
| Type?             | bug fix 
| Category?         | FO 
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Stock management must be turned off, create a new product, turn off available_for_order and see what the structured data looks like

2024-05-10 12:39 UTC, nicosomb commented on src/Adapter/Presenter/Product/ProductLazyArray.php
> +        // if it's not avaiblable for order
```suggestion
        // if it's not available for order
```

2024-05-10 14:02 UTC, Hlavtox requested changes
I don't think it's a correct change, because `available_for_order` is not related to stock.

Product can be in stock, but doesn't have to be available for order, it can be only for ordering by request or something.

Also, google can complain that the structured data on the website is not correct, if the export module does it a different way.

What is the use case specifically?

2024-05-10 14:51 UTC, webeshop commented
Here you can see the problem.
https://www.web-eshop.cz/demo/prestashop8/home-accessories/19-customizable-mug.html

It's a specific situation, but I've been dealing with this issue at a client store.

The product cannot be ordered, but the availability is InStock.
Maybe it could be solved somehow better.

![obrazek](https://github.com/PrestaShop/PrestaShop/assets/32673480/d28fb424-7f11-4fb9-9b31-70df86632b98)

2024-05-10 14:53 UTC, webeshop commented
The second option is to hide "offers" structured data when the product cannot be ordered.

2024-05-13 15:55 UTC, matthieu-rolland reviewed
Hello and thank you for your contribution 👍 

Can you please [create an issue](https://github.com/PrestaShop/PrestaShop/issues/new?assignees=&labels=Bug%2CNew&projects=&template=1_bug_report.yml) so that this bug can be reproduced by the QA team, it will make it easier for QA teams and others to track this

2024-07-26 10:09 UTC, kpodemski commented
Since we have had no news from you for more than 20 days, I'm closing this PR. Feel free to re-open it if you find the motivation to finish it. Don't hesitate to ping me if you have any questions or doubts.

2024-07-26 10:09 UTC, closed without merging