Add pastetext to TinyMCE configuration
PrestaShop/PrestaShop pull request #36151
Opened 2024-05-14 13:47 UTC by PrestaEdit

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add the paste text (paste text without formatting) in TinyMCE toolbar buttons.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Edit a product or a CMS page and see that a new button is now enabled.
| Fixed issue or discussion?     | Fixes #36150

2024-05-14 15:08 UTC, jf-viguier approved these changes

2024-05-14 15:26 UTC, nicosomb approved these changes

2024-05-14 17:42 UTC, Touxten approved these changes

2024-05-15 10:31 UTC, boherm approved these changes

2024-05-15 14:49 UTC, paulnoelcholot commented
Hello @PrestaEdit,

I tested your PR but I haven't the same behavior like you :/ Did I miss something?

Thanks for your feedback

![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/ad63ff4f-9fa6-4a5e-9ee8-70efe0480e62)

2024-05-28 17:23 UTC, PrestaEdit commented
It's like the icon is not shown as needed ; could I ask you to empty your cache to remake a test, maybe ?

2024-06-12 11:11 UTC, florine2623 reviewed
Hello @PrestaEdit ,

I tested on my end, I still can't see the new icon.
I deleted cache from PS, and emptied cache and hard reloaded from my browser. I still can't see the icon :/

2024-06-12 12:23 UTC, PrestaEdit commented
There is a regression since this : https://github.com/PrestaShop/PrestaShop/pull/33587

On the Product page, it will not work anymore. Or a least with the ProductPage v2.

2024-06-12 12:25 UTC, kpodemski commented
@PrestaEdit the old product page doesn't exist anymore, so I guess this PR is not relevant anymore for the product page, but it is still relevant for the CMS pages?

2024-06-12 12:31 UTC, PrestaEdit commented
It's not only for product page, but for every page having the TinyMCE.

I wrote this issue, If you can confirm it : https://github.com/PrestaShop/PrestaShop/issues/36351

2024-07-03 12:38 UTC, florine2623 commented
This should be checked by a dev as it requires a module creation.

Here are the steps to reproduce provided by @matks https://github.com/PrestaShop/PrestaShop/issues/36351#issuecomment-2201030986

It seems to not be a bug.

2024-07-03 13:41 UTC, kpodemski requested changes
I did check this, and I see that `tinymce.inc.js` is not loaded anymore.I t is only loaded where `HelperForm,` and `HelperOptions` are used or on the translations screen.

It seems TinyMCE is rendered differently on the new product page.

Do you want to investigate this @PrestaEdit ?

2024-07-08 18:50 UTC, matks commented
> I did check this, and I see that `tinymce.inc.js` is not loaded anymore.I t is only loaded where `HelperForm,` and `HelperOptions` are used or on the translations screen.
> 
> It seems TinyMCE is rendered differently on the new product page.
> 
> Do you want to investigate this @PrestaEdit ?

Confirmed: this file js/admin/tinymce.inc.js only controls tinyMCE configuration on pages where a Form is built using HelperForm

On migrated backoffice pages, we created a JS component: admin-dev/themes/new-theme/js/components/tinymce-editor.js

You need to submit code changes against this component

2024-07-22 12:18 UTC, tleon approved these changes

2024-11-17 02:51 UTC, kpodemski commented
Since we have had no news from you for more than 20 days, I'm closing this PR. Feel free to re-open it if you find the motivation to finish it. Don't hesitate to ping me if you have any questions or doubts.

2024-11-17 02:51 UTC, closed without merging