Follow symlinks for traductions - Deployer best practice
PrestaShop/PrestaShop pull request #36160
Opened 2024-05-14 16:12 UTC by Jeremie-Kiwik

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 8.1.x
| Description?      | The Finder used to search translation files does not follow symlinks by default. This is a major issue when working with modern and robust solutions like Deployer. On these environments, each GIT release is in a specific folder, and the "living" files (traductions, images...) are in a common shared folder. Symlinks are then created to point to the shared folder. Currently, all translation files are ignored by PrestaShop, as they are symlinks. This PR aims to integrate them.
| Type?             | bug fix
| Category?         | FO / BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Move a traduction file from app/Resources/translations or from your theme to somewhere else, and make a symlink to it (ie: ln -fs /moved_file /original/location)
| UI Tests          | 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   | KIWIK (kiwik.com)

2024-05-15 11:48 UTC, kpodemski requested changes
Thanks @Jeremie-Kiwik 

To respect coding standards of the project you should use spaces instead of tabs ;-)

2024-05-15 14:21 UTC, Jeremie-Kiwik commented
You're right. Here it is!

2024-05-16 08:31 UTC, PrestaEdit approved these changes

2024-05-20 21:28 UTC, PululuK approved these changes

2024-06-06 14:26 UTC, ivan-kiwik commented
Hi @kpodemski 

Can this merge be validated ?

Thanks !

2024-06-06 14:27 UTC, kpodemski approved these changes

2024-06-13 14:17 UTC, matks approved these changes
Tested and validated 😉 thank you

2024-06-13 14:18 UTC, merged