input type "number" is not styled properly
PrestaShop/PrestaShop pull request #36172
Opened 2024-05-15 20:37 UTC by ShaiMagal

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Check issue #36164 
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 
| UI Tests          | https://github.com/florine2623/testing_pr/actions/runs/9694646890 ✅ 
| Fixed issue or discussion?     | Fixes #36164 
| Related PRs       | 
| Sponsor company   | https://www.openservis.cz/

2024-05-15 20:49 UTC, Hlavtox commented on admin-dev/themes/default/scss/partials/_forms.scss
> +input[type="number"]:hover,
Duplicate hard

2024-05-15 20:50 UTC, Hlavtox commented on admin-dev/themes/default/scss/vendor/bootstrap-sass/_forms.scss
> +// input[type="number"]
Duplicate hard

2024-05-16 10:04 UTC, mflasquin approved these changes

2024-05-16 15:37 UTC, boherm approved these changes

2024-05-20 10:31 UTC, kpodemski requested changes
Could you provide a simple module to allow QA to perform tests?

2024-06-19 10:07 UTC, ShaiMagal commented
@kpodemski OK, attaching.
[shaim_number_test.zip](https://github.com/user-attachments/files/15899049/shaim_number_test.zip)
![Untitled](https://github.com/PrestaShop/PrestaShop/assets/8518736/d95b8155-24f2-4692-abe1-444330d70473)

2024-06-19 10:12 UTC, ShaiMagal commented
@kpodemski Here
[shaim_number_test.zip](https://github.com/user-attachments/files/15899104/shaim_number_test.zip)

2024-06-19 10:13 UTC, kpodemski approved these changes

2024-06-19 10:18 UTC, Hlavtox approved these changes

2024-06-27 10:06 UTC, ps-jarvis commented
<!-- PR_TABLE_DESCRIPTION_ERROR -->
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

2024-06-27 10:14 UTC, florine2623 reviewed
Hello @ShaiMagal ,

I installed your module in a shop with your PR and in another shop (fresh install); but I see no difference between the 2 inputs.

In both cases, I have :
<img width="510" alt="Screenshot 2024-06-27 at 12 13 46" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/fce32b18-8a29-4bc3-af27-0c26acbcb801">

Am I missing something ?
Waiting for your feedback ^^

2024-07-01 16:39 UTC, ShaiMagal commented
@florine2623 
If we only change SCSS files it's without impact, there is necessary to compile SCSS to CSS.
It is in file theme.css, but I don't know how is it realized while installing fresh PS. So compilacted to QA I think:

But maybe I am missing something.

2024-07-02 09:16 UTC, florine2623 commented
@ShaiMagal ,
I understand your point.
In the PR, the design is not correct. It is not what you put in the issue.

The borders should be rounded and grey, as it is in your issue.

With the module and the PR installed, I have black borders and angled corners.

**What I should have :**
![test](https://github.com/PrestaShop/PrestaShop/assets/16019289/0f761dd8-bf0e-45d4-807c-0a21ef50a2ba)


**What I have :**
<img width="170" alt="Screenshot 2024-07-02 at 11 14 43" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/d393c55b-a346-442d-8895-d4548d754328">

2024-07-17 15:18 UTC, tleon approved these changes

2024-07-26 09:51 UTC, kpodemski commented
@florine2623 Dominik forgot to put `$this->bootstrap = true;` to his module, correct module attached below.
[shaim_number_test 2.zip](https://github.com/user-attachments/files/16390000/shaim_number_test.2.zip)

2024-08-01 14:11 UTC, florine2623 approved these changes
Hello @ShaiMagal and @kpodemski !

Thanks for the update !

Indeed, with the latest module it works as expected.

Before :
<img width="1433" alt="Screenshot 2024-08-01 at 16 02 23" src="https://github.com/user-attachments/assets/46ae5311-e94a-46cb-a253-6d7d4416c3a4">


After :
<img width="1440" alt="Screenshot 2024-08-01 at 16 08 38" src="https://github.com/user-attachments/assets/9d9eaf90-a6ac-4c70-a765-2c21da01a07e">

It is QA ✅ 


Thanks!

2024-08-01 15:16 UTC, merged

2024-08-03 15:42 UTC, ShaiMagal commented
@kpodemski uh, sorry, my fault ... missing line. Thank you for correction :)