Update iframe-modal.ts
PrestaShop/PrestaShop pull request #36236
Opened 2024-05-25 13:15 UTC by Shivam7-1

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | PBy using innerText, it will avoid the risk of HTML injection, as these properties automatically escape any HTML special characters in the provided text. This helps prevent cross-site scripting (XSS) vulnerabilities by treating the input as plain text rather than interpreted HTML.
| Type?             | bug fix / improvement 
| Category?         | FO / BO / CO / IN / WS / TE / LO / ME / PM / see explanations at https://devdocs.prestashop-project.org/8/contribute/contribution-guidelines/pull-requests/#type--category
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| How to test?      | Indicate how to verify that this change works as expected.
| UI Tests          | Please run UI tests and paste here the link to the run. [Read this page to know why and how to use this tool.](https://devdocs.prestashop-project.org/8/contribute/contribution-guidelines/ui-tests/).
| Fixed issue or discussion?     | Fixes #{issue number here}, Fixes #{another issue number here}, Fixes https://github.com/PrestaShop/PrestaShop/discussions/ {discussion number here}
| Related PRs       | If theme, autoupgrade or other module change is needed to make this change work, provide a link to related PRs here.
| Sponsor company   | Your company or customer's name goes here (if applicable).

2024-05-31 09:08 UTC, Shivam7-1 commented
Hi @nesrineabdmouleh Could You Please Review This PR 
Thanks

2024-05-31 09:53 UTC, nesrineabdmouleh commented
> Hi @nesrineabdmouleh Could You Please Review This PR Thanks

Hello @Shivam7-1, 

Thank you for your first contribution, your fix is not related to UI tests!
@PrestaShop/committers need a review please

2024-05-31 18:29 UTC, Shivam7-1 commented
Hi @nesrineabdmouleh Thanks You For Responding 
But I think it looks like PrestaShop/committers haven't Got Notified For Review PR ?
Thanks

2024-06-01 16:48 UTC, Shivam7-1 commented
Hi @nesrineabdmouleh Thanks You For Responding
But I think it looks like @PrestaShop/committers haven't Got Notified For Review This PR ?
Thanks

2024-06-04 14:07 UTC, Shivam7-1 commented
> > Hi @nesrineabdmouleh Could You Please Review This PR Thanks
> 
> Hello @Shivam7-1,
> 
> Thank you for your first contribution, your fix is not related to UI tests! @PrestaShop/committers need a review please

Hi @nesrineabdmouleh Thanks You For Responding
But I think it looks like @PrestaShop/committers haven't Got Notified For Review This PR ?
Thanks

2024-06-04 14:43 UTC, nicosomb commented
@Shivam7-1 Hello. The committers team has been notified, don't worry. 

We'll have a look to your pull request when we'll find time to review it.

2024-07-01 20:00 UTC, matks reviewed
Hello @Shivam7-1 apologies for late answer.

Could you fill in the PR template, especially the "How to test"?

Did you verify your code changes do not break any behavior?

2024-07-02 02:17 UTC, Shivam7-1 commented
Hi @matks Thanks For Your Response 
I had edited PR Template But I don't Know what to write in how to test as it was run locally and also all test was passed in GitHub automatic PR Testing 

Thanks & regards

2024-07-09 02:44 UTC, Shivam7-1 commented
Hi @matks Could You Please Review This PR 
Thanks

2024-07-26 09:54 UTC, kpodemski commented
@matthieu-rolland do you think this PR is relevant?

2024-07-27 09:19 UTC, Shivam7-1 commented
Hi @matks Could You Please Review This PR
Thanks

2024-07-29 10:46 UTC, Shivam7-1 commented
Hi @matthieu-rolland Could You Please Review This PR 
Thanks

2024-07-29 10:58 UTC, matthieu-rolland reviewed
Using .innerText is indeed safer in general 👍

Could you please write the "how to test" ? 

What should the qa team check to verify that you didn't break anything ?
What page, what action? Where did you spot the xss risk ?

2024-07-29 17:36 UTC, Shivam7-1 commented
Hi @matthieu-rolland Thanks For Reviewing 
I had updated things in above 
Regards

2024-07-29 17:36 UTC, Shivam7-1 commented
Hi @matks Could You Please Review This PR
Thanks

2024-07-30 07:44 UTC, boherm approved these changes, later dismissed

2024-07-30 10:39 UTC, Shivam7-1 commented
Hi @boherm Thanks For Reviewing 
Is there Anything Else is Required From My Side to get this Merged in Project?

Regards

2024-07-31 06:15 UTC, Shivam7-1 commented
Hi @boherm Thanks For Reviewing
Is there Anything Else is Required From My Side to get this Merged in Project?

Regards

2024-07-31 06:45 UTC, boherm commented
> Hi @boherm Thanks For Reviewing Is there Anything Else is Required From My Side to get this Merged in Project?
> 
> Regards

No, just to wait a second approval and an approval by QA team! :)

2024-08-06 15:12 UTC, Shivam7-1 commented
Hi @matthieu-rolland Could You Please Review This PR 
Thanks

2024-08-06 16:27 UTC, jolelievre requested changes
Sorry @Shivam7-1 

although I understand the purpose of your modification but this component is supposed to be able to render HTML as well

2024-08-06 16:27 UTC, jolelievre commented on admin-dev/themes/new-theme/js/components/modal/iframe-modal.ts
> +    this.modal.message.innerText = content;
Except the purpose of this render method is also to render HTML, it extends the base method from the `ModalType` and has a few use cases already where it renders HTML code:
https://github.com/PrestaShop/PrestaShop/blob/3a0ae040c5642364f0d1535bd5769dcbdd31f8d5/admin-dev/themes/new-theme/js/pages/product/combination/combination-modal/CombinationModal.vue#L270
https://github.com/PrestaShop/PrestaShop/blob/9541a5198c41a2723abec7d431525e8d030d83d2/admin-dev/themes/new-theme/js/pages/product/category/category-tree-selector.ts#L91

Even if those examples are concrete implementation of a `Modal` and not an `IframeModal` they still share the same base type and so must respect the same contract/behaviour

2024-08-06 17:08 UTC, Shivam7-1 commented
Hi
Thanks For Reviewing is there Any changes is Required 
Thanks

2024-08-06 17:22 UTC, jolelievre commented
> Hi Thanks For Reviewing is there Any changes is Required Thanks

I don't think there's much to change, the very principle of your modification is to prevent displaying HTML code, but the feature is made precisely to display HTML code. So your purpose doesn't meet with the expected behaviour

The only alternative I could see would be to add a configuration in the modal, or an additional parameter to the method (less fan) that would indicate if the modal is supposed to protect/prevent HTML code or not

2024-08-06 18:20 UTC, Shivam7-1 commented
Hi @jolelievre @boherm @matks @matthieu-rolland 
Thanks For Replying According to Feedback I had Tried to make changes 
Could You please Review This Again 

Thanks

2024-08-18 18:15 UTC, Shivam7-1 commented
Hi 
Is there any Update on This ?
Thanks

2024-08-20 12:13 UTC, Shivam7-1 commented
Hi 
Is there Any Update on this ?
Thanks

2024-08-21 10:43 UTC, jolelievre approved these changes, later dismissed
Thanks @Shivam7-1 

Now the component is more versatile and can handle both use cases

2024-08-21 12:16 UTC, Shivam7-1 commented
Hi @boherm 
Could You Please Review This PR Again ?
Thanks

2024-08-22 11:00 UTC, Shivam7-1 commented
Hi @matthieu-rolland 
Could You Please Re-Review This PR Again
Thanks

2024-08-22 11:01 UTC, kpodemski approved these changes

2024-08-22 11:02 UTC, kpodemski requested changes
Hello @Shivam7-1 

As you can see, our CI is red because of the errors reported by ESLint:
https://capture.dropbox.com/OgOfcBaye37ELG4f

2024-08-22 15:55 UTC, matthieu-rolland reviewed
@Shivam7-1 in CLI, launch this command from the root of your project:

`php vendor/bin/php-cs-fixer fix admin-dev/themes/new-theme/js/components/modal/iframe-modal.ts`

then commit the modified file, it will fix your CI issue

2024-08-22 15:58 UTC, matthieu-rolland commented
LGTM for me once you've made this last little fix 👍

2024-08-23 05:19 UTC, Shivam7-1 commented
Hii @matthieu-rolland 
I had Tried this CLI But There is No Change has been Performed BY CLI I had Attached Below Screenshot 
Could You Please Check it 
![Screenshot_20240823-104547_1](https://github.com/user-attachments/assets/c8436451-36fb-42ce-8271-a965313a3003)

2024-08-23 08:10 UTC, jolelievre commented
@Shivam7-1 the linter failing is for JS code CS fixer is for PHP, sorry

To check the error go to `admin-dev/themes/new-theme` and run `npm run lint` To fix it automatically you can run `npm run lint-fix` but depending on the complexity of the error you may have to fix it manually

2024-08-23 08:20 UTC, Shivam7-1 commented
Hii @jolelievre @matthieu-rolland 
Still it not Got Run

Could You Please Let me know if there anything I am missing here ?
 
![Screenshot_20240823-134826](https://github.com/user-attachments/assets/7050eb85-2d65-475b-bc94-87148697fb38)

2024-08-23 11:03 UTC, jolelievre commented
@Shivam7-1 did you run `npm ci` or `npm install` before?

2024-08-23 11:51 UTC, Shivam7-1 commented
Hii @jolelievre  @matthieu-rolland 
Thanks For Replying `npm ci` worked here 
and i had done all ci fix 
Could You Please Again Review This 
Thanks

2024-08-23 12:07 UTC, jolelievre approved these changes

2024-08-23 12:21 UTC, Shivam7-1 commented
Hi @kpodemski 
Could You Please Review This PR Again?
Thanks

2024-08-23 12:27 UTC, kpodemski approved these changes

2024-08-23 12:39 UTC, kpodemski commented
@PrestaShop/qa-functional I think this change doesn't require functional tests and CI is ok

2024-08-23 12:53 UTC, Shivam7-1 commented
Hii
Is there Anything Else is Required From My Side to get this PR merge?
Thanks

2024-08-23 12:55 UTC, kpodemski commented
@Shivam7-1 yes: be patient :D

2024-08-26 15:00 UTC, Shivam7-1 commented
Hii
Is there Anything Else is Required From My Side to get this PR merge?
Thanks :D

2024-08-28 08:34 UTC, florine2623 approved these changes
Hello @Shivam7-1 and @kpodemski ,

Automated tests are OK ✅ 

It can be merged.

2024-08-29 07:40 UTC, merged