Fix: Pass correct language ID to getAttributesName instead of hardcoded 1
PrestaShop/PrestaShop pull request #36457
Opened 2024-06-28 15:23 UTC by mouleeg

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | The language id param is set to 1 by default. This causes an issue in fetching the good name when changing the language in BO -> product page -> Prix tab -> Specific price list. Using the language id in context should fix the issue.  
| Type?             | bug fix 
| Category?         | BO 
| BC breaks?        |  no
| Deprecations?     | no
| How to test?      |  BO -> product page -> Prix tab -> Specific price list. Create a specific price for a declinaison.  In the list, the name of declinaison will be displayed well with this fix. Before that only the name in english language will be displayed.
| UI Tests          | Please run UI tests and paste here the link to the run. As we support MySQL and MariaDB in our tests, you have to launch 2 campaigns (by choosing both). [Read this page to know why and how to use this tool](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/ui-tests/).
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   |

2024-06-28 15:24 UTC, ps-jarvis commented
<!-- PR_TABLE_DESCRIPTION_ERROR -->
Hi, thanks for this contribution!

Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

2024-06-28 15:39 UTC, ps-jarvis commented
<!-- PR_WELCOME -->
Hello @mouleeg!

This is your first pull request on [PrestaShop](https://github.com/PrestaShop/PrestaShop/) repository of the PrestaShop project.

Thank you, and welcome to this Open Source community!

2024-06-28 15:41 UTC, Hlavtox approved these changes
LGTM, good catch 👍

2024-07-01 06:50 UTC, boherm approved these changes

2024-07-01 08:59 UTC, PululuK approved these changes

2024-07-01 13:50 UTC, florine2623 approved these changes
Hello @mouleeg ,

Thanks for the PR !

Tested for new product page and old product page.
Tested with one/multiple combinations.

New : 

https://github.com/PrestaShop/PrestaShop/assets/16019289/464c62f5-05cb-4d7d-982d-9fedc9ef2a17

Old :

https://github.com/PrestaShop/PrestaShop/assets/16019289/7ab94ae3-ce54-47e7-aa46-d634a77dc981

LGTM, it is QA ✅

2024-07-01 13:51 UTC, florine2623 commented
Please, wait before merging.

@PrestaShop/qa-automation 
Auto tests are failing, is it related to this PR ?

2024-07-01 13:54 UTC, Hlavtox requested changes, later dismissed
Block until QA reply to avoid accidental merge.

Dismiss this and merge it after. :-)

2024-07-02 09:43 UTC, florine2623 commented
Tests are green now ^^

2024-07-02 09:47 UTC, merged

2024-07-02 09:48 UTC, Hlavtox commented
Thanks @mouleeg and @florine2623! :-)
The fix will be available in 8.1.8.