add currency context for new admin API
PrestaShop/PrestaShop pull request #36484
Opened 2024-07-02 19:28 UTC by clement-hvt

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add currency context for new admin API
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Create a new API ressource who need the currency context in its CQRSQuery, e.g.: GetOrderForViewing and call the endpoint.
| UI Tests          | 
| Fixed issue or discussion?     | Fixes #{issue number here}
| Related PRs       |
| Sponsor company   |

2024-07-02 19:28 UTC, ps-jarvis commented
<!-- PR_TABLE_DESCRIPTION_ERROR -->
Hi, thanks for this contribution!

Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

2024-07-02 19:28 UTC, ps-jarvis commented
<!-- PR_WELCOME -->
Hello @clement-hvt!

This is your first pull request on [PrestaShop](https://github.com/PrestaShop/PrestaShop/) repository of the PrestaShop project.

Thank you, and welcome to this Open Source community!

2024-07-11 15:07 UTC, tleon requested changes
Hello, 
Could you add a unit test for this new context ? 
The other liseners' tests can be a good example ( e.g Tests/Unit/PrestaShopBundle/EventListener/Admin/Context/LanguageContextListenerTest.php ) .

Thx for the contribution.

2024-07-17 06:44 UTC, clement-hvt commented
> Hello, Could you add a unit test for this new context ? The other liseners' tests can be a good example ( e.g Tests/Unit/PrestaShopBundle/EventListener/Admin/Context/LanguageContextListenerTest.php ) .
> 
> Thx for the contribution.

Unit test added :white_check_mark:

2024-07-17 08:42 UTC, tleon submitted a review, later dismissed
you need to fix the ci but it's ok for me when it's done

2024-07-17 09:07 UTC, boherm submitted a review, later dismissed
Thanks for your contribution @clement-hvt!
LGTM too, it's ok after fixing the CI 🙂

2024-07-17 12:07 UTC, boherm approved these changes, later dismissed

2024-07-17 15:16 UTC, tleon submitted a review, later dismissed

2024-07-18 12:01 UTC, florine2623 commented
@tleon ,
Could this be QA by dev ?
It hasn't been Verified on the issue yet ^^

2024-07-22 12:16 UTC, tleon commented
Yes this should be QA by dev since you need to create a new test endoint unsing the new context.
I don't know maybe @clement-hvt will propose a PR on the ps_apiressource module that implement such context. If so we could be using this PR as a test.

2024-07-26 09:59 UTC, kpodemski commented
@tleon he provided example in the issue, you can use it

2024-10-01 16:25 UTC, boherm commented
Hi @clement-hvt! I've just test your PR, and it's ok! :)

2024-10-01 16:27 UTC, boherm commented
Can you please rebase to develop and restart UI tests?
Then, we could merge!

2024-10-02 07:41 UTC, clement-hvt commented
@boherm [https://github.com/clement-hvt/ga.tests.ui.pr/actions/runs/11139148202](https://github.com/clement-hvt/ga.tests.ui.pr/actions/runs/11139148202)

2024-10-02 11:38 UTC, nicosomb commented
@clement-hvt you added a merge commit in your PR and our CI is not happy with that 🙂

2024-10-03 07:19 UTC, boherm approved these changes

2024-10-03 09:14 UTC, nicosomb approved these changes

2024-10-03 09:15 UTC, merged

2024-10-03 09:15 UTC, ps-jarvis commented
<!-- PR_MISSING_MILESTONE -->
PR merged, well done!

Message to @PrestaShop/committers: do not forget to milestone it before the merge.