migrate "abstract lazy array for cart presenter + improvements" from develop to 8.1.x
PrestaShop/PrestaShop pull request #36575
Opened 2024-07-19 15:18 UTC by matthieu-rolland

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | the cart presenter lazy array and lazy array new features were introduced in develop but we actually want it on 8.1.x, this PR applies it on 8.1.x, adapting the code so that it's compatible with PHP 7.2 
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI green
| UI Tests          | 
| Fixed issue or discussion?     | 
| Related PRs       | #36408 #36477 #36501 #36528
| Sponsor company   | Your company or customer's name goes here (if applicable).

2024-07-19 15:37 UTC, kpodemski commented
I don't think such a complex refacto belongs to a patch version 🤔

2024-07-19 15:40 UTC, matthieu-rolland commented
> I don't think such a complex refacto belongs to a patch version 🤔

that's why I did it on develop at first, but at the company level I had other instructions (enterprise etc...)

2024-07-19 15:41 UTC, matthieu-rolland commented
hmm phpstan gives some stuff to fix, on it

2024-07-19 19:23 UTC, Hlavtox requested changes
I love performace gains, but this is a dangerous change I think. We don't know it's effects yet. 🤷‍♂️

2024-07-22 08:05 UTC, jolelievre requested changes
I also agree this change should not be part of a patch version

2024-08-26 14:01 UTC, ps-jarvis commented
<!-- PR_TABLE_DESCRIPTION_ERROR -->
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `branch` should be `develop` or `8.1.x`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

2024-08-26 14:01 UTC, matks commented
Following feedbacks regarding the content, I have changed the target branch to 8.2.x ; more details on 
 https://github.com/PrestaShop/PrestaShop/issues/36758

2024-09-02 12:57 UTC, jolelievre approved these changes
Thanks @matthieu-rolland

2024-09-02 13:27 UTC, Hlavtox approved these changes

2024-09-02 13:31 UTC, kpodemski approved these changes

2024-09-03 08:05 UTC, florine2623 approved these changes
No need for manual test on this one ^^
CI is green ✅

2024-09-03 08:11 UTC, ps-jarvis commented
<!-- PR_TABLE_DESCRIPTION_ERROR -->
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `deprecations` should be `yes` or `no`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#deprecations))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

2024-09-03 08:12 UTC, merged