Add a condition for handling errors from hook actionModuleInstallBefore
PrestaShop/PrestaShop pull request #36612
Opened 2024-07-25 14:07 UTC by JohnPAfr

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | This condition allow the display of an error if the hook actionModuleInstallBefore add errors to the context.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Create a module that use the hook actionModuleInstallBefore (check example bellow). Install the module. Finally upload another module to see the error in the install modal.
| UI Tests          | 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   | Prestashop SA

```
public function hookActionModuleInstallBefore($params)
    {
        $params["object"]->_errors[] = "Test";
    }
```

2024-07-25 14:21 UTC, kpodemski approved these changes, later dismissed

2024-07-25 14:29 UTC, matthieu-rolland approved these changes, later dismissed

2024-07-25 14:55 UTC, florine2623 commented
Hello @JohnPAfr ,

Could you provide the modules example so we can follow the steps to reproduce your gave ?

2024-07-25 14:56 UTC, kpodemski commented
@florine2623 can we agree for "waiting for a dev" to let developers test it?

2024-07-25 15:19 UTC, florine2623 commented
@kpodemski alright, good for me :)

2024-07-26 06:53 UTC, boherm submitted a review, later dismissed

2024-07-26 07:57 UTC, JohnPAfr commented
@florine2623 Hello, I've added a zip for testing purpose.

2024-08-26 14:02 UTC, ps-jarvis commented
<!-- PR_TABLE_DESCRIPTION_ERROR -->
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `branch` should be `develop` or `8.1.x`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

2024-08-26 14:02 UTC, matks commented
Hi, I have changed the target branch to 8.2.x because of https://github.com/PrestaShop/PrestaShop/issues/36758

2024-08-26 14:48 UTC, matks approved these changes

2024-09-02 09:56 UTC, boherm approved these changes

2024-11-17 09:17 UTC, Hlavtox requested changes
I agree with this PR, just want to confirm one thing.

@ShaiMagal Dominik, what is the way that 3rd party modules show update alerts? Isnt this using the errors array? Cannot it colllide?

2024-11-17 09:20 UTC, kpodemski commented
@Hlavtox look at the code, there are other returns as well, but it never returns errors array, for example

2024-11-17 11:53 UTC, Hlavtox approved these changes
I checked it, the modules are using `$this->warning`. :-)

2024-11-25 10:13 UTC, merged