Debug classic ui tests
PrestaShop/PrestaShop pull request #36673
Opened 2024-08-05 21:45 UTC by jolelievre

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 8.1.x
| Description?      | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?             | bug fix / improvement / new feature / refacto
| Category?         | FO / BO / CO / IN / WS / TE / LO / ME / PM / see explanations at https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#type--category
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| How to test?      | Indicate how to verify that this change works as expected.
| UI Tests          | Please run UI tests and paste here the link to the run. As we support MySQL and MariaDB in our tests, you have to launch 2 campaigns (by choosing both). [Visit the UI Tests repo and follow instructions](https://github.com/PrestaShop/ga.tests.ui.pr/).
| Fixed issue or discussion?     | Fixes #{issue number here}, Fixes #{another issue number here}, Fixes https://github.com/PrestaShop/PrestaShop/discussions/ {discussion number here}
| Related PRs       | If theme, autoupgrade or other module change is needed to make this change work, provide a link to related PRs here.
| Sponsor company   | Your company or customer's name goes here (if applicable).

2024-08-26 08:02 UTC, Progi1984 commented on .github/actions/ui-test/action.yml
> +  SCREENSHOT_EACH_STEP:
```suggestion
  TAKE_SCREENSHOT_AFTER_EACH_STEP:
```

2024-08-26 08:04 UTC, Progi1984 commented on tests/UI/package.json
> +    "lodash": "^4.17.21",
Remove this dependency, please

2024-08-26 08:06 UTC, Progi1984 commented on tests/UI/utils/setup.ts
> +    const screenshotPath = `${global.SCREENSHOT.FOLDER}${folderPath}/${_.kebabCase(this.currentTest?.title)}.png`;
Add a function `kebabCase` to the `ui-testing-library` And update the library in the Core

2024-08-26 08:07 UTC, Progi1984 requested changes
Some feedbacks

2024-08-29 11:26 UTC, Progi1984 commented on .github/actions/ui-test/action.yml
> +        cat .env
```suggestion
```

2024-08-29 11:27 UTC, Progi1984 reviewed
A small feedback and it's ok

2024-08-29 12:04 UTC, jolelievre commented
Thanks for the review @Progi1984 
Everything should be fixed now, and I see you already merged the PR on UI tests pr repo, only this one missing for the feature to work 😉

2024-08-29 12:09 UTC, Progi1984 commented
@jolelievre I fixed `ga.tests.ui.pr`. Sorry, i misread.

2024-08-29 12:57 UTC, jolelievre commented
> @jolelievre I fixed `ga.tests.ui.pr`. Sorry, i misread.

Ah you're right, I forgot to remove the last cat that was meant for debug initially, no PR though 😅

2024-08-29 13:24 UTC, Progi1984 approved these changes

2024-08-29 16:10 UTC, matthieu-rolland approved these changes

2024-08-29 19:13 UTC, merged