Fix: Product customization text appears as raw HTML in order confirmation email (order_conf)
PrestaShop/PrestaShop pull request #36796
Opened 2024-09-02 14:46 UTC by Codencode

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.2.x
| Description?      | When a customer places an order for a customized product in Prestashop, the order confirmation email (order_conf) displays the product customization text as raw HTML rather than showing the text formatted correctly.
| Type?             | bug fix
| Category?         | FO 
| BC breaks?        | no
| Deprecations?     | no
| Fixed issue or discussion?     | Fixes #36795
| Sponsor company   | Codencode

2024-09-02 14:46 UTC, ps-jarvis commented
<!-- PR_TABLE_DESCRIPTION_ERROR -->
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!
### About linked issues
Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

2024-09-03 09:01 UTC, kpodemski commented
Hello @Codencode 

There's a similar PR already:
https://github.com/PrestaShop/PrestaShop/pull/33471

But it wasn't clear whether the change was safe or whether there was a risk of XSS inside this HTML.

2024-09-03 10:24 UTC, Codencode commented
> Hello @Codencode
> 
> There's a similar PR already: #33471
> 
> But it wasn't clear whether the change was safe or whether there was a risk of XSS inside this HTML.

Hello @kpodemski,

I hadn't found this PR; indeed, the field validation is missing when creating the order in the admin panel.

I will now add the code to address this case as well.

Thank you!

2024-09-03 10:30 UTC, ps-jarvis commented
<!-- PR_WORDING -->
This pull request seems to contain new translation strings. I have summarized them below to ease up review:

- `Admin.Notifications.Error`
    - [ ] `Custom field text is invalid.`

(Note: this is an automated message, but answering it will reach a real human)

2024-09-13 13:30 UTC, Prestaworks commented
> Hello @Codencode
> 
> There's a similar PR already: #33471
> 
> But it wasn't clear whether the change was safe or whether there was a risk of XSS inside this HTML.

I think there is a risk for xss with this PR, maybe using strip_tags before passing the values to the template instead?

2024-09-13 14:28 UTC, Codencode commented
> I think there is a risk for xss with this PR, maybe using strip_tags before passing the values to the template instead?

The system validates the value entered in the customization using the `Validate::isMessage()` method. Therefore, if you try to insert a string with HTML or malicious code, the system will display an error.

https://github.com/PrestaShop/PrestaShop/blob/c6cf71fb6e8363b0b25fcbc450e25f7ae4cb0ced/controllers/front/ProductController.php#L981-L983


--- 
Here is an example with debugging not enabled:
[without debug enable.webm](https://github.com/user-attachments/assets/46cc3efd-5870-4328-a154-73177693c651)

---
Here is an example with debugging enabled

[with debug enable.webm](https://github.com/user-attachments/assets/5ed2693d-a39f-4b5d-9937-db5182b40f1b)

---
The system performs the validation, but a second issue arises: when setting the error with `$this->errors[] = $this->trans('Invalid message.', [], 'Shop.Notifications.Error');`, the method `ProductController::initContent()` does not load the product, and as a result, the view generates a series of errors.

https://github.com/PrestaShop/PrestaShop/blob/c6cf71fb6e8363b0b25fcbc450e25f7ae4cb0ced/controllers/front/ProductController.php#L312-L315

2024-09-13 14:33 UTC, Prestaworks commented
> > I think there is a risk for xss with this PR, maybe using strip_tags before passing the values to the template instead?
> 
> The system validates the value entered in the customization using the `Validate::isMessage()` method. Therefore, if you try to insert a string with HTML or malicious code, the system will display an error.
> 

Yes, but there are as you have noticed with the issue report, modules that inserts directly in the database. So you can't really trust that validation.

2024-09-13 14:41 UTC, Codencode commented
> > > I think there is a risk for xss with this PR, maybe using strip_tags before passing the values to the template instead?
> > 
> > 
> > The system validates the value entered in the customization using the `Validate::isMessage()` method. Therefore, if you try to insert a string with HTML or malicious code, the system will display an error.
> 
> Yes, but there are as you have noticed with the issue report, modules that inserts directly in the database. So you can't really trust that validation.

Ok, so we could do it this way, as you suggested:

https://github.com/PrestaShop/PrestaShop/blob/c6cf71fb6e8363b0b25fcbc450e25f7ae4cb0ced/classes/PaymentModule.php#L466-L469

```
$customization_text .= '<strong>' . $text['name'] . '</strong>: ' . strip_tags($text['value']) . '<br />';
```

We run `strip_tags` on the value and in the template we run:
```
{foreach $product['customization'] as $customization}
    {$customization['customization_text'] nofilter}
{/foreach}
````

2024-09-13 19:23 UTC, Codencode commented
I thought it would be better to remove the tags only if the value does not pass the validation through `Validate::isCleanHtml()`.
This way, if non-malicious HTML code is intentionally saved in the value (through external modules), it will continue to work.
However, if the content does not pass validation, we remove the tags.

So we could modify the following code
https://github.com/PrestaShop/PrestaShop/blob/c6cf71fb6e8363b0b25fcbc450e25f7ae4cb0ced/classes/PaymentModule.php#L466-L469

```php
foreach ($customization['datas'][Product::CUSTOMIZE_TEXTFIELD] as $text) {
    if (!Validate::isCleanHtml($text['value'])) {
        $text['value'] = strip_tags($text['value']);
    }
    $customization_text .= '<strong>' . $text['name'] . '</strong>: ' . $text['value'] . '<br />';
}
```

2024-09-16 08:30 UTC, Prestaworks commented
> I thought it would be better to remove the tags only if the value does not pass the validation through `Validate::isCleanHtml()`. This way, if non-malicious HTML code is intentionally saved in the value (through external modules), it will continue to work. However, if the content does not pass validation, we remove the tags.
> 
> So we could modify the following code
> 
> https://github.com/PrestaShop/PrestaShop/blob/c6cf71fb6e8363b0b25fcbc450e25f7ae4cb0ced/classes/PaymentModule.php#L466-L469
> 
> ```
> foreach ($customization['datas'][Product::CUSTOMIZE_TEXTFIELD] as $text) {
>     if (!Validate::isCleanHtml($text['value'])) {
>         $text['value'] = strip_tags($text['value']);
>     }
>     $customization_text .= '<strong>' . $text['name'] . '</strong>: ' . $text['value'] . '<br />';
> }
> ```

That would make it open to iframe injections if the "allow iframes" is set to Yes.

2024-09-16 09:08 UTC, Codencode commented
> > I thought it would be better to remove the tags only if the value does not pass the validation through `Validate::isCleanHtml()`. This way, if non-malicious HTML code is intentionally saved in the value (through external modules), it will continue to work. However, if the content does not pass validation, we remove the tags.
> > So we could modify the following code
> > https://github.com/PrestaShop/PrestaShop/blob/c6cf71fb6e8363b0b25fcbc450e25f7ae4cb0ced/classes/PaymentModule.php#L466-L469
> > 
> > ```
> > foreach ($customization['datas'][Product::CUSTOMIZE_TEXTFIELD] as $text) {
> >     if (!Validate::isCleanHtml($text['value'])) {
> >         $text['value'] = strip_tags($text['value']);
> >     }
> >     $customization_text .= '<strong>' . $text['name'] . '</strong>: ' . $text['value'] . '<br />';
> > }
> > ```
> 
> That would make it open to iframe injections if the "allow iframes" is set to Yes.

Yes, I know that.
Normally, as already said, the system performs input validation, so for the default operation we are fine.

In the case of modules that valorize the customization fields, they should perform validation upstream of the entered value.

I believe that as it works now it is not the best for users who download Prestahsop and using the customizations see the html code in the email.

2024-09-16 09:20 UTC, Codencode commented
> That would make it open to iframe injections if the "allow iframes" is set to Yes.


The `PS_ALLOW_HTML_IFRAME` configuration concerns the validation of the fields in the ObjectModel.

We would directly execute the method `Validate::Validate::isCleanHtml()` whose second parameter `$allow_iframe` is set to `false` by default, so iframes are not allowed

https://github.com/PrestaShop/PrestaShop/blob/c6cf71fb6e8363b0b25fcbc450e25f7ae4cb0ced/classes/Validate.php#L516-L542

2024-09-16 09:35 UTC, Prestaworks commented
> > That would make it open to iframe injections if the "allow iframes" is set to Yes.
> 
> The `PS_ALLOW_HTML_IFRAME` configuration concerns the validation of the fields in the ObjectModel.
> 
> We would directly execute the method `Validate::Validate::isCleanHtml()` whose second parameter `$allow_iframe` is set to `false` by default, so iframes are not allowed
> 
> https://github.com/PrestaShop/PrestaShop/blob/c6cf71fb6e8363b0b25fcbc450e25f7ae4cb0ced/classes/Validate.php#L516-L542
> 
> We could pass the second parameter explicitly, so:
> 
> ```
> foreach ($customization['datas'][Product::CUSTOMIZE_TEXTFIELD] as $text) {
>     if (!Validate::isCleanHtml($text['value'], false)) {
>         $text['value'] = strip_tags($text['value']);
>     }
>     $customization_text .= '<strong>' . $text['name'] . '</strong>: ' . $text['value'] . '<br />';
> }
> ```

ok, sounds good to me. Maybe do the same for the name field also just in case?

2024-09-16 10:47 UTC, Codencode commented
> customization['datas'][Product::CUSTOMIZE_TEXTFIELD] as $text

Ok, I'll make the changes then.

2024-10-25 20:05 UTC, kpodemski submitted a review, later dismissed

2024-10-25 20:05 UTC, kpodemski commented
cc @PrestaShop/committers

2024-11-17 09:11 UTC, Hlavtox requested changes
If I understand correctly, we are running the raw html in front office? I can't agree with this. Dangerous and unexpected.

We should support html in the text field, but treat it as text. For example, if someone wants to have </head><body> on his tshirt.

So - I think we should save it to database normally and output it escaped, so you see the html tags.

2024-11-17 12:28 UTC, Codencode commented
> If I understand correctly, we are running the raw html in front office? I can't agree with this. Dangerous and unexpected.
> 
> We should support html in the text field, but treat it as text. For example, if someone wants to have on his tshirt.
> 
> So - I think we should save it to database normally and output it escaped, so you see the html tags.

Hi @Hlavtox ,

The issue concerns the order confirmation email in the case of a product with customization, where the HTML defining the "strong" tag for the customization "name" is displayed.

Additionally, we added a check on the "name" and "value" to ensure that if the value does not pass validation using `Validate::isCleanHtml()`, the HTML is removed.

2025-01-25 21:08 UTC, Hlavtox commented
@Codencode @kpodemski I stand my ground here. If the user enters something that looks like HTML tags as a customization, it must stay that way - properly escaped everywhere.

`<strong>test</strong>` must be displayed as `<strong>test</strong>`, NOT **test**,

2025-01-26 11:08 UTC, Codencode commented
Hi @Hlavtox,
In my opinion, the issue also occurs when plain text is entered in the customization field.
Assuming the user inputs "text" in the customization field, in the order confirmation email **order_conf** (https://github.com/PrestaShop/PrestaShop/blob/8.2.x/mails/themes/modern/core/order_conf.html.twig) that the user receives, for the customized item, the following is displayed:
`<strong>Type your text here</strong>: text<br />`.
### Example of simple customization -  product page
![Product-page](https://github.com/user-attachments/assets/c6c83759-badf-4259-8dca-9014f8decad4)
### Example of simple customization - cart page
![cart-page](https://github.com/user-attachments/assets/b4b0c465-4d5f-4d37-9aa8-7ca16d499173)
### Example of simple customization - email (order_conf)
![mail](https://github.com/user-attachments/assets/95b1d41d-7246-4c04-b552-baa06b731f04)


This happens because the `PaymentModule::validateOrder()` method includes the following instruction, which adds HTML formatting:
https://github.com/PrestaShop/PrestaShop/blob/3d237dcfc00e3a19fff321165071db601c1cc426/classes/PaymentModule.php#L465-L469

If you try to input text with HTML formatting, for example: `<strong>text</strong>`, the system shows an error because HTML is not allowed. You can see an example in the videos I uploaded in this comment: https://github.com/PrestaShop/PrestaShop/pull/36796#issuecomment-2349094983

Therefore, the issue also occurs in normal use, and my modification aims to avoid the problem in the simple case, i.e., with non-HTML text.

2025-09-19 08:08 UTC, Codencode commented
Are there any updates on this issue?
Could we consider resolving the issue another way, such as performing PHP-side escaping on individual fields while obviously adding "nofilter" in the tpl?
What do you think?
Should I create a new PR, perhaps directly on the 9.0.x branch?

2025-09-19 08:17 UTC, Hlavtox commented
@Codencode Can you try this?

`$customization_text .= '<strong>' . $text['name'] . '</strong>: ' . htmlspecialchars($text['value'], ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') . '<br />';
`

and keep

`{$customization['customization_text'] nofilter}
`

Should work. It will keep <> in the text, display it in a safe way and fix the HTML tags in the email.

2025-09-19 08:39 UTC, Codencode commented
> @Codencode Can you try this?
> 
> `$customization_text .= '\<strong\>' . $text['name'] . '\</strong\>: ' . htmlspecialchars($text['value'], ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') . '<br />'; `
> 
> and keep
> 
> `{$customization['customization_text'] nofilter} `
> 
> Should work. It will keep <> in the text, display it in a safe way and fix the HTML tags in the email.

Excellent, that's exactly what I had in mind as an alternative and "less" impactful solution!
I'll try it and update you!

2025-09-19 09:00 UTC, Codencode commented
@Hlavtox 
It works!
<img width="720" height="432" alt="Senza nome-1" src="https://github.com/user-attachments/assets/5e834d0f-56b1-4538-8b57-88f59ebb2737" />

Do you think it's better if I update this PR, or should I create one directly for the 9.0.x branch?

2025-09-19 15:17 UTC, Hlavtox commented
@Codencode I would rebase it, so we keep the github clean :-)

2025-09-19 15:40 UTC, Codencode commented
@Hlavtox  So I'll rebase it to update to the latest 8.2.x commit, or should I target 9.0.x?
Of course, I'll make the change first.

2025-09-19 16:27 UTC, Codencode commented
@Hlavtox

- I made the change
- I deleted the previous commits
- I rebased onto the latest commit of the 8.2.0 branch

Then if we want to point the 9.0.x branch directly there, I can perform the rebase again.

2025-09-20 12:25 UTC, Hlavtox submitted a review, later dismissed

2025-10-08 11:45 UTC, Codencode commented
ping @PrestaShop/committers

2025-10-19 10:05 UTC, kpodemski commented
I asked @matthieu-rolland for the final review.

2025-11-13 09:43 UTC, kpodemski commented
@Codencode could you rebase onto `9.0.x`?

2025-11-13 09:56 UTC, Hlavtox submitted a review, later dismissed

2025-11-13 09:57 UTC, Codencode commented
> @Codencode could you rebase onto `9.0.x`?

Done

2025-11-13 10:03 UTC, Codencode commented
@Hlavtox sorry, I had to remove an extra space 🙏

2025-11-13 10:08 UTC, Hlavtox approved these changes

2025-11-13 10:10 UTC, kpodemski approved these changes

2025-11-24 08:27 UTC, paulnoelcholot commented
Hello @Codencode,

I tested your PR and it's good for me! :tada: 

Thanks!

<img width="566" height="376" alt="image" src="https://github.com/user-attachments/assets/b51e511c-d194-42d6-b94c-a2945e789914" />

2025-11-24 08:30 UTC, paulnoelcholot approved these changes

2025-11-24 08:31 UTC, merged

2025-11-24 08:32 UTC, Touxten commented
Thank's you @paulnoelcholot && @Codencode