fix: add attr_stringify_fetches to PDO init config
PrestaShop/PrestaShop pull request #36875
Opened 2024-09-10 08:00 UTC by fox-john

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix Incompatibility Issue with PDO Returning Integer Values with PHP 8.1
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | dump a response from database returned by PDO, and check type of values.
| Fixed issue or discussion?     | Fix #36836
| Sponsor company   | PrestaShop

2024-09-10 08:00 UTC, ps-jarvis commented
<!-- PR_TABLE_DESCRIPTION_ERROR -->
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `type` should be one of these: `new feature`, `improvement`, `bug fix` or `refacto`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

2024-09-10 08:00 UTC, ps-jarvis commented
<!-- PR_WELCOME -->
Hello @fox-john!

This is your first pull request on [PrestaShop](https://github.com/PrestaShop/PrestaShop/) repository of the PrestaShop project.

Thank you, and welcome to this Open Source community!

2024-09-10 08:01 UTC, kpodemski approved these changes, later dismissed

2024-09-10 08:10 UTC, matks approved these changes, later dismissed

2024-09-10 08:11 UTC, matks commented
@fox-john I remove the "BC Break" label because IMO we are fixing an unwanted BC Break. We are restoring Backward Compatibility

2024-09-10 08:13 UTC, fox-john commented
@matks That's ok for me. I just didn't know if I should consider it a BC break of a BC break! 😅

2024-09-10 08:55 UTC, jolelievre approved these changes

2024-09-10 08:56 UTC, jolelievre requested changes

2024-09-10 08:56 UTC, jolelievre commented on classes/db/DbPDO.php
> +                PDO::ATTR_STRINGIFY_FETCHES => true
```suggestion
                PDO::ATTR_STRINGIFY_FETCHES => true,
```
You need to add this coma to respect coding style (or the CI will remain blocked)

2024-09-10 09:10 UTC, kpodemski approved these changes

2024-09-10 09:34 UTC, jolelievre approved these changes

2024-09-10 19:23 UTC, kpodemski commented
We've got the confirmation that thanks to this change it's been possible to also fix this issue:
https://github.com/PrestaShop/PrestaShop/issues/36844

All tests are green: https://github.com/kpodemski/ga.tests.ui.pr/actions/runs/10793751569

@PrestaShop/qa-functional can we merge this? it doesn't require manual functional tests

2024-09-11 13:50 UTC, florine2623 reviewed
Hello @fox-john ,

Thanks for the PR !

It fixes the issue mentioned in the PR.

**Without the PR :**
In PHP 7.4, I have a `string` for id_shop_group
In PHP 8.1, I have an `int` for id_shop_group


![image (1)](https://github.com/user-attachments/assets/649870e3-73df-4a35-85aa-425f14002d77)
![image](https://github.com/user-attachments/assets/7b63f6be-191d-4e8e-bfa2-cbac874a5b02)

**With PR :**
Now with PHP 7.4 or PHP 8.1, I have the same result. As you can see id_shop_group is always considered as a string: ✅ 

<img width="167" alt="Screenshot 2024-09-11 at 15 34 01" src="https://github.com/user-attachments/assets/b8f9caa1-9eec-4639-822e-79d76544fc3f">
<img width="173" alt="Screenshot 2024-09-11 at 15 35 11" src="https://github.com/user-attachments/assets/33f4ba42-2ed4-44ac-ab54-4c969c3a6bc3">

The issue that I have is that the automated tests are totally broken : 
https://github.com/florine2623/testing_pr/actions/runs/10812222129

So this PR cannot be merged.

@PrestaShop/qa-automation , what should we do about that ?

Thanks!

2024-09-13 10:33 UTC, kpodemski commented
Fresh tests: https://github.com/kpodemski/ga.tests.ui.pr/actions/runs/10847556664

2024-09-13 11:27 UTC, florine2623 commented
@jolelievre 's tests are green 💪 
https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/10845473917

2024-09-13 11:42 UTC, merged

2024-12-15 20:17 UTC, panariga commented
well, now there is new breaks
$cart = new Cart(928);
var_dump($cart->id_lang);
string(1) "1"

how in the world id_lang can be string in Object?
so all modules which rely on types in ObjectModel now failing

2024-12-15 20:35 UTC, kpodemski commented
@panariga 

that should not be the case because this change simply put back the same behavior as in PHP lower than 8.1

2024-12-15 21:00 UTC, panariga commented
This is a case for someone who has already written modules in PHP 8.1+))

But seriously, it's incorrect.
Objects should have types specified in annotations. So, these castings should be done when the object is fetched from the database. It's also a performance issue. Furthermore, declare(strict_types=1) is becoming a bug.

2024-12-15 21:06 UTC, kpodemski commented
I'm afraid introduced change should be considered as a lesser evil because it works the same as in previous versions. ObjectModel never returned typed properties before PHP 8.1 and change in this behavior, unfortunately, caused some issues in the core.