Database connection - usage of "localhost" is about 3% faster than "127.0.0.1"
PrestaShop/PrestaShop pull request #36912
Opened 2024-09-13 16:12 UTC by ShaiMagal

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Check issue 36909
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Ïnstall PrestaShop. Default "database server address" will be "localhost" (not "127.0.0.1")
| UI Tests          | 
| Fixed issue or discussion?     | #36909 
| Related PRs       | 
| Sponsor company   | https://www.openservis.cz/

2024-09-16 14:04 UTC, tleon approved these changes

2024-09-17 07:40 UTC, kpodemski requested changes
127.0.0.1 almost always works as expected, localhost sometimes doesn't, and when I look at the added value vs potential problems with installation, I'm more in favor of keeping the current default value

2024-09-17 16:26 UTC, ShaiMagal commented
@kpodemski Why localhost doesn't work? any what cases? localhost is "alias" to 127.0.0.1, but it's faster.
So, if you don't agree with this change, we should at least:
A) give HINT about localhost is faster than 127.0.0.1
B) set default "localhost" and white hint "If you have problems with localhost, use 127.0.0.1".

What do you think @kpodemski ?

And WDYT @Hlavtox ?

2024-09-18 09:49 UTC, Hlavtox commented
My opinion that we should put `localhost` there, with a hint.

I never saw a case when localhost would not work.

2024-10-07 11:10 UTC, ShaiMagal commented
@Hlavtox me same, never saw problem with localhost. Can someone show real example when localhost isn't working?

2024-11-09 18:59 UTC, ShaiMagal commented
How we will finish this? Will we use any text message at least?

2024-11-10 11:02 UTC, SharakPL commented
> Can someone show real example when localhost isn't working?

Sure! Just map localhost to different IP :)
Can you show an example where 127.0.0.1 isn't working?

2024-11-10 11:23 UTC, Hlavtox commented
@SharakPL The point is, that localhost is faster sometimes, because it doesn't do some logic and works a bit differently. :-)

2024-11-10 18:01 UTC, SharakPL commented
IMO the IP is safer to always work. Besides it seems to me this is only relevant (barely) for development since a user installing the shop can pick a host name provided by the server configuration anyway. Right?

2024-11-16 18:35 UTC, ShaiMagal commented
@SharakPL check related issue ans benchmark provided.

2025-02-04 16:46 UTC, ShaiMagal commented
Bump

2025-08-20 12:43 UTC, kpodemski commented
https://github.com/PrestaShop/PrestaShop/issues/36909#issuecomment-3206168584

2025-08-20 12:43 UTC, closed without merging