Deprecate separate search tag methods
PrestaShop/PrestaShop pull request #36940
Opened 2024-09-17 14:14 UTC by Hlavtox

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.2.x
| Description?      | Searching products by tags is already included in Search::find method, they are normally indexed and searched with other data. This is a code that is unused for a long time and there is no way to use it, unless you change the URL. Will be removed in 9.0.0. Discussed with @kpodemski.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | yes
| How to test?      | No need to test, only comments.
| UI Tests          | 
| Fixed issue or discussion?     |
| Related PRs       | 
| Sponsor company   |

2024-09-17 14:14 UTC, ps-jarvis commented
<!-- PR_TABLE_DESCRIPTION_ERROR -->
Hi, thanks for this contribution!

Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

2024-09-17 14:58 UTC, kpodemski commented
Hi @Hlavtox 

Now that I'm thinking about it, I'm not sure if we want to delete it. I think searching by the tag, even if we don't promote the URL to this kind of the search, will output completely different results and is more precise than searching by a phrase. What dod you think?

2024-09-18 07:37 UTC, PrestaEdit approved these changes
For information.
Theses was used within the blocktags module, that is not handled since 1.7 versions.

2024-09-19 08:36 UTC, kpodemski requested changes
I tested it, and using tags can allow us to target products better than via regular search. I would keep it.

2024-09-27 09:26 UTC, Hlavtox commented
@kpodemski Where exactly do you use it? 🤔

2024-10-21 09:42 UTC, closed without merging