Merge `8.2.x` into `develop`
PrestaShop/PrestaShop pull request #37039
Opened 2024-09-27 10:35 UTC by boherm

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Merge `8.2.x` into `develop`
| Type?             | improvement
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI + Tests UI
| UI Tests          | https://github.com/boherm/ga.tests.ui.pr/actions/runs/11103487385
| Sponsor company   | PrestaShop SA

2024-09-27 10:35 UTC, ps-jarvis commented
<!-- PR_WORDING -->
This pull request seems to contain new translation strings. I have summarized them below to ease up review:

- `Admin.Modules.Notification`
    - [ ] `The override file %1$s conflicts with an existing override in %2$s.`
- `Admin.Orderscustomers.Feature`
    - [ ] `Abandoned Carts`
    - [ ] `Average Order Value`
    - [ ] `Net Profit per Visitor`
- `Admin.Catalog.Notification`
    - [ ] `Invalid product`
    - [ ] `Invalid combination`
    - [ ] `An error occurred during the image upload process.`
    - [ ] `Invalid quantity`
    - [ ] `This product cannot be added to the cart.`
    - [ ] `You already have the maximum quantity available for this product.`
    - [ ] `Invalid voucher.`
- `Admin.Notifications.Error`
    - [ ] `Invalid message.`
- `Admin.Orderscustomers.Notification`
    - [ ] `Invalid order`
    - [ ] `The order cannot be renewed.`

(Note: this is an automated message, but answering it will reach a real human)

2024-09-27 12:43 UTC, nicosomb approved these changes

2024-09-27 12:45 UTC, nicosomb submitted a review, later dismissed
CI is 🔴

2024-09-27 13:36 UTC, jolelievre requested changes

2024-09-27 13:36 UTC, jolelievre commented on controllers/admin/AdminCartsController.php
This controller has been migrated so this file should not be integrated back in the develop branch and must be deleted

2024-09-27 13:36 UTC, jolelievre commented on src/PrestaShopBundle/Resources/config/services/core/module.yml
> +    deprecated: ~
We should keep the 8.1 indication to know when this was deprecated, so we can remove it in the next version
Actually, this should be removed in the v9.0 but in a dedicated PR probably

2024-09-27 13:36 UTC, jolelievre commented on translations/default/ModulesBlockreassuranceAdmin.xlf
> -  <file original="modules/blockreassurance/views/templates/admin/tabs/content/config_elements/cms.tpl" source-language="en-US" target-language="en" datatype="plaintext">
You should modify absolutely NO translation files, you can revert the changes on all those files

2024-09-30 09:30 UTC, Hlavtox commented on classes/Customer.php
> +        /** @var \PrestaShop\PrestaShop\Core\Crypto\Hashing $crypto */
Please don't merge anything in this method, it's already fixed on develop branch.

2024-09-30 09:31 UTC, Hlavtox requested changes
See comment, please do not change Customer.php.

2024-09-30 09:42 UTC, Hlavtox approved these changes, later dismissed
All good now. :-) thanks @boherm

2024-09-30 09:46 UTC, matthieu-rolland approved these changes, later dismissed
thanks @boherm 👍

2024-09-30 12:58 UTC, jolelievre approved these changes

2024-09-30 12:58 UTC, jolelievre commented on src/PrestaShopBundle/Controller/Admin/Improve/Design/CmsPageController.php
> +        $viewData = $this->get('prestashop.core.cms_page.data_provider.cms_page_view')->getView($cmsCategoryParentId);
Lucky for you it was not refactored yet ^^

2024-09-30 12:58 UTC, jolelievre commented on tests/Integration/Core/Addon/Module/ModuleManagerBuilderTest.php
> +            'AdminProductsController.php file different'
```suggestion
            'DummyAdminController.php file different'
```

2024-09-30 13:03 UTC, matthieu-rolland approved these changes

2024-09-30 13:41 UTC, merged

2024-09-30 13:41 UTC, ps-jarvis commented
<!-- PR_MISSING_MILESTONE -->
PR merged, well done!

Message to @PrestaShop/committers: do not forget to milestone it before the merge.