Implement feature value positions to core and back office
PrestaShop/PrestaShop pull request #37042
Opened 2024-09-27 18:00 UTC by ks129

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add a new field to feature value table/model - position. Add it to feature value grid and implement route to change positions.
| Type?             | new feature
| Category?         | BO + CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Check the linked issue.
| UI Tests          | Please run UI tests and paste here the link to the run. As we support MySQL and MariaDB in our tests, you have to launch 2 campaigns (by choosing both). [Visit the UI Tests repo and follow instructions](https://github.com/PrestaShop/ga.tests.ui.pr/).
| Fixed issue or discussion?     | Fixes #35499 , Fixes https://github.com/PrestaShop/PrestaShop/discussions/32267
| Related PRs       | ps_facetedsearch + autoupgrade PRs coming
| Sponsor company   | -

2024-09-27 18:00 UTC, ps-jarvis commented
<!-- PR_TABLE_DESCRIPTION_ERROR -->
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `category` should be one of these: `FO`, `BO`, `CO`, `IN`, `WS`, `TE`, `LO`, `ME` or `PM`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!
### About linked issues
Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

2024-10-02 15:29 UTC, jolelievre reviewed
Thanks you @ks129 

That's a perfect contribution, you anticipated all the side changes. Great job!

I just had one suggestion in the grid definition, but you couldn't be aware of this new UX we want to uniformize on all the positionable grids.

I also have a small request, if you can add it in this PR it would be perfect, if you prefer to handle it separately it's understandable.

The list of features in the product page should also reflect this change, from what I found it seems to be handled in the [ProductLazyArray](https://github.com/PrestaShop/PrestaShop/blob/892b08345199708351fe5854ee855ddd1fff9864/src/Adapter/Presenter/Product/ProductLazyArray.php#L421) or in the [Product ObjectModel](https://github.com/PrestaShop/PrestaShop/blob/564dbcc461aabf2165da30ad8270a1101ae499a5/classes/Product.php#L5715), the idea would be to be able to sort feature values by position as well, and the tip top feature would be to have a configuration to choose between Alphabetical or Position order like you did in faceted search.

In a nutshell it would mean:
- add a configuration value in Product settings > Product page form
- adapt the order by in FO depending on this configuration

Would you accept to add this in the PR please?

2024-10-02 15:29 UTC, jolelievre commented on src/Core/Grid/Definition/Factory/FeatureValueGridDefinitionFactory.php
> +                ->setAssociatedColumn('position')
```suggestion
            ->add((new Filter('position', ReorderPositionsButtonType::class))
                ->setAssociatedColumn('position')
            )
```

2024-10-02 15:29 UTC, jolelievre commented on src/Core/Grid/Definition/Factory/FeatureValueGridDefinitionFactory.php
> +                ->setAssociatedColumn('position')
We made some changes in all the grids that handle position, we removed the filter by position (which is not very useful) and instead we use this dedicated type that helps to set up the grid in a "positionable state"

A grid can only be ordered when it is sorted by position, and this custom type adds a button that helps the user understand this.

2024-10-02 15:29 UTC, jolelievre commented on src/PrestaShopBundle/Controller/Admin/Sell/Catalog/FeatureValueController.php
> +    public function updatePositionAction(
You don't seem shaken at all by the new `PrestaShopAdminController` even without the doc being updated yet, great job!

2024-10-04 12:14 UTC, ps-jarvis commented
<!-- PR_WORDING -->
This pull request seems to contain new translation strings. I have summarized them below to ease up review:

- `Admin.Shopparameters.Feature`
    - [ ] `Order of feature values`
- `Admin.Shopparameters.Help`
    - [ ] `In the product page, feature values can be sorted alphabetically by value or by position.`

(Note: this is an automated message, but answering it will reach a real human)

2024-10-14 12:29 UTC, gericfo commented
Hello @ks129 
Please note that the **“Needs autoupgrade PR”** label has been automatically added to your Pull Request. This means that the changes made in your PR must also be reported in the **Autoupgrade module**, responsible for running the update process of PrestaShop stores. 
When there's a modification to the `db-structure.sql` file or if a Doctrine entity has been modified, added, or deleted, it impacts the database structure. Modifying the list of hooks and feature flags has consequences on the update process as well. These changes can affect how the application interacts with the database and how update procedures are handled. It's important to consider these aspects when contributing to ensure a smooth update experience for users. 
That's why this contribution should be backported, with another corresponding PR, on the **Autoupgrade module's GitHub repository** which is available here: [link](https://github.com/PrestaShop/autoupgrade). 
Don't forget to add a comment in this current thread with the link to this PR once it has been created. 
Thank you.

2024-10-18 10:44 UTC, jolelievre reviewed
Thanks @ lot @ks129 

Only one remaining comment, and the I'll push for this to go quickly to QA so that it's included in v9

2024-10-18 10:44 UTC, jolelievre commented on src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/PageType.php
> +                    'Position' => 1,
Can you use string values instead please? so we understand the meaning of each config
If you prefer to keep the int value it's fine but then we'd need some const matching these values for better understanding (which is why I suggested the string instead: `name`, `position`)

2024-10-21 07:52 UTC, kpodemski requested changes
Hello

We recently introduced the 9.0.x branch, which will be the base for PrestaShop 9.0. If you want to see your change in this version, please rebase your PR onto 9.0.x. The `develop` will be used for PrestaShop 9.1, so you need to decide what to do.

Please rebase onto `9.0.x` or let me know your decision if you don't need to have it there so I can unblock the pull request.

2024-10-21 11:03 UTC, ks129 commented
@kpodemski @jolelievre Both things are done now. However, I have a little problem with UI tests as I don't understand why they aren't working.

2024-10-21 11:32 UTC, jolelievre submitted a review, later dismissed

2024-10-21 11:33 UTC, jolelievre commented
@ks129 we have issues with the test workflow you used, it's planned to be fixed but I don't have time for it right now

You can use this workflow instead https://github.com/ks129/ga.tests.ui.pr/actions/workflows/pr_test_one.yml which is not buggy in theory

2024-10-23 21:33 UTC, jolelievre approved these changes, later dismissed

2024-10-23 21:40 UTC, jolelievre commented
Hi @ks129 

I allowed myself to rebase your PR, and made some small modifications in UI tests to match some recent changes in them.

2024-10-24 06:46 UTC, Progi1984 approved these changes
Ok for UI Tests

2024-10-24 06:52 UTC, kpodemski submitted a review, later dismissed

2024-10-24 06:52 UTC, kpodemski commented
well done @ks129 👏🏻

2024-11-06 16:38 UTC, florine2623 reviewed
Hello @ks129 ,

Regarding the [specs](https://github.com/PrestaShop/PrestaShop/issues/35499), I checked the following :
- Add position column on the feature value page. New db filed. ✅ 
- Drag and drop row like on feature group page
Sort by position is selected by default ✅ 

Drag and drop from BO works as expected. Database is filed with position in feature_value table.

**In BO :**
<img width="1210" alt="Screenshot 2024-11-06 at 16 49 57" src="https://github.com/user-attachments/assets/e56569a2-d86e-4720-bd71-e4e6b2fce824">

**In DB :**
<img width="392" alt="Screenshot 2024-11-06 at 16 48 40" src="https://github.com/user-attachments/assets/ac388ed8-7c0e-48d3-b525-db2b99a2e4db">

Button Rearrange will rearrange the Position if the grid is sorted by ID or value. Position can be sorted with the arrow button too.

Nothing is changed on FO as this PR only tacles BO part..
The acceptance test is not completed for the FO section only the BO section.

> Acceptance test
> Go on composition
> Drag Polyester below Wool
> Check FO Wool is before Polyester

I can't validate it as automated tests are broken : https://github.com/florine2623/testing_pr/actions/runs/11706411660/job/32607716941#step:10:309 :x:

@PrestaShop/qa-automation & @ks129 could you check please ?

Thanks!

2024-11-07 07:51 UTC, Progi1984 commented on tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/02_features/02_changePosition.ts
> +import attributesPage from '@pages/BO/catalog/attributes';
```suggestion
```

2024-11-07 07:51 UTC, Progi1984 commented on tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/02_features/02_changePosition.ts
> +    expect(pageTitle).to.contains(attributesPage.pageTitle);
```suggestion
    const pageTitle = await boAttributesPage.getPageTitle(page);
    expect(pageTitle).to.contains(boAttributesPage.pageTitle);
```

2024-11-07 07:51 UTC, Progi1984 commented on tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/02_features/02_changePosition.ts
> +    await attributesPage.goToFeaturesPage(page);
```suggestion
    await boAttributesPage.goToFeaturesPage(page);
```

2024-11-07 07:52 UTC, Progi1984 commented on tests/UI/campaigns/functional/BO/03_catalog/04_attributesAndFeatures/02_features/02_changePosition.ts
> +  boDashboardPage,
```suggestion
  boAttributesPage,
  boDashboardPage,
```

2024-11-07 07:53 UTC, Progi1984 requested changes
@ks129 Small changes in UI Tests after move to the ui testling library

2024-11-07 07:54 UTC, Progi1984 commented
@ks129 I have added some changes for validating UI Tests

2024-11-07 14:26 UTC, jolelievre approved these changes

2024-11-07 14:34 UTC, Progi1984 approved these changes
OK for UI Tests

2024-11-07 14:56 UTC, jolelievre commented
@florine2623 I just update the Acceptance test, actually for the position to be used in FO you need to update a configuration in Shop Parameters > Product Settings > Order of feature values => select position

2024-11-08 10:32 UTC, tleon approved these changes

2024-11-12 18:14 UTC, florine2623 approved these changes
Hello all,

Tested again this feature with correct configuration of `Order of feature values`. It works as expected in the FO.

The automated tests are green : https://github.com/florine2623/testing_pr/actions/runs/11801417927

Thanks! It is QA ✅

2024-11-12 19:21 UTC, merged