http code 403 for non existent image (not 404)
PrestaShop/PrestaShop pull request #37058
Opened 2024-09-30 20:21 UTC by ShaiMagal

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Check below
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | TODO
| UI Tests          | 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   | https://www.openservis.cz/

2024-09-30 22:04 UTC, Hlavtox reviewed
I like this, but proper response for not found content is 404, that's what should be returned.

2024-10-01 06:36 UTC, nicosomb commented
Just my two cents. 

if a media doesn't exist, it **should** return a 404, not a 403. 

I understand the bot problem, but if you want to block bots, you have to block them via your server configuration. 

PrestaShop should respect web standards. 

I don't block your PR because I know that we'll discuss and discuss about that, we'll have pros and cons, and we won't go forward ...

2024-10-01 07:41 UTC, nicosomb requested changes
I changed my mind 🔴

2024-10-01 07:57 UTC, matks commented
> If bots are accessing your website, they will get 404 on non existent image, this load whole website, content and modules. If bot is spamming (for example Facebook) - check access log below. This can cause the site to slow down significantly as it loads X pages per second as it only expects images. It is possible to totally crash whole website. But since the http code is 404, the entire site will be displayed. 403 will not do this and there is a big performance impact.

@ShaiMagal if I understand, your reasoning is:

- there are bots crawling a website, generating lot of requests
- returning a 404 loads the website, consuming server resources
- then you switch to 403 to avoid loading the website, avoiding resources over-consumption

But as mentioned by @nicosomb and @Hlavtox and the 404 is correct, the 403 is not. You are changing a correct behavior in the software to patch a situation that is unrelated, by side-effect. We can't accept that 😄 these code changes are not correct.

Problem is relevant, solution is not 😉 .

I can suggest 3 ways to fix the problem better:
1. Find a way to return a 404 while loading less resources
2. You say loading the 404 response page is too big, what about creating a new 404 ultra-fast page? And merchants could choose between the "pretty 404 page, but kinda expensive" and the "ultra-fast but ultra thin 404 page with no dynamic content"
3. I am not even sure this should be done by PrestaShop : as you mentioned "best way not to consume resources is to NOT load the software at all". A reverse proxy could do the job so much better, don't you think? It's 100% within its pool of features.

When possible, the software should not attempt to add features that are better handled by other layers of the web stack 😉

2024-10-01 08:36 UTC, Hlavtox commented
@ShaiMagal I agree with @matks and @nicosomb bro. 👍 Kill it in htaccess, OK, but with a 404.

2024-10-01 08:51 UTC, Touxten commented
For me 404 and even why not a 410.
The 410 is why the person isn't going to modify his database to give the old id_image back to an image, so it's 410 for me :wink:
https://developer.mozilla.org/fr/docs/Web/HTTP/Status/410

2024-10-01 08:56 UTC, Hlavtox commented
@Touxten 410 is a response for objects where you declare that the object was removed intentionally. You don't know this in case of random spamming of image URLs.

2024-10-01 09:01 UTC, Touxten commented
@Hlavtox 

I think sending a sitemap overwrites the 410, SEO questions are fun.
I understand when you say that a malicious person could spam urls on another site and that google bing ... take them into account but it really exists and for me the sitemap overwrites 410

2024-10-01 09:08 UTC, jolelievre commented
Yep, 410 is meant for a resource that did exist in the past but not anymore. For a made up URL it should be a 404, the resource never existed.

Also, this force 404 should not be global, depending on your use case you may favor the visitor to reach a page that allows him to browse back to your website instead of a blank error page. So this feature should be configurable (with a config in the `Traffic & SEO` section), we could keep the current behaviour by default but allow a forced 404. If you want to go further the configuration could even propose alternative behaviour (similar to the setting on product page), so if you really want a 410 you can still choose it, but I'd recommend 404 in the options or in a help message.

2024-10-01 09:27 UTC, Touxten commented
For the greatest number of sites, the @jolelievre  solution seems to me to be the best.
On the other hand, it doesn't really solve the problem.

Another solution is to send a 410 if the image_id is between 0 and the max image_id.
This SEO stuff really isn't easy  

Am I the only one to send an image sitemap?

2024-10-01 15:19 UTC, ShaiMagal commented
@Hlavtox @matks @nicosomb 
I don't have problem to choose another solution :)

If we use 404, it will show website content.

So, how we should use 404 for .htaccess to **not** display the content of website but only 404?

2024-10-02 13:40 UTC, jolelievre commented
We could have a rule that doesn't pass via the `index.php` when an image URL matches, and I'm not a pro at `.htaccess` but I believe you can even detect if the targeted file exists or not and redirect accordingly

But the problem here is that all images URLs are redirected to the index.php on purpose because there is a controller in charge of dynamically generate them when they don't exist I don't know which controller handles this part but I guess this should be the one that handles a simple 404 response

So the dispatcher would still be used and it prevents an instant response by apache but at least it doesn't execute the whole FO rendering

2024-10-02 14:51 UTC, Hlavtox commented
@jolelievre It's not the dispatcher that generates them, it's done in presenters.

Image URLs are instantly rewritten in the htaccess and they don't initialize index.php at all.

2024-10-03 07:47 UTC, jolelievre commented
@Hlavtox you're probably right, I'm not very familiar with the FO
But I though there was a feature that generates them on the fly when they don't exist, no?

2024-10-03 08:11 UTC, Hlavtox commented
@jolelievre Yes, there is, but the feature exists in `ProductLazyArray` and `ImageRetriever` classes. Simple visiting the image URL does not regenerate it.

2024-10-03 08:40 UTC, Hlavtox commented
@ShaiMagal 

```
ErrorDocument 404 /404.html
<If "%{REQUEST_URI} =~ m#^/ru/#">
    ErrorDocument 404 /ru/404.html
</If>
```

2024-10-04 12:53 UTC, metacreo commented
everything is much simpler PR #37086
I once shouted about this (bots, SEO) but everything was ok with you. Has the time for enlightenment come?

2024-10-07 11:31 UTC, ShaiMagal commented
@Hlavtox not sure how to implement correctly. For me 403 working well. I prefer 404 as well. But not sure, how to do this.
Main point of this is not to render whole FO. This is necessarry.
Now it's working for 403, is someone able to rewrite this to 404?

**Now situation:**
This show 404 with content.
**PR apply:**
This show 403 without content.
**ideal condition:**
This show 404 without content

@metacreo why you open new PR, when we already are solving this here and making duplicites?
I came with this idea, so we should finish it here.
Your PR isn't solving problem. It show 404 buth WITH content. And we don't want it. So nothing helpful.

2024-10-07 11:34 UTC, ShaiMagal commented
I found solution. Changed my PR. But it must be **DETAILED** tested to be sure we didn't broke something!

2024-10-07 13:08 UTC, nicosomb commented
> Changed my PR.

I don't see where is the new commit.

2024-10-07 13:10 UTC, ShaiMagal commented
@nicosomb Problem exists between chair and keyboard (my fault) :-D
In progress :)

2024-10-07 13:15 UTC, ShaiMagal commented
@nicosomb commit done. But it must be tested very thoroughly. To be sure I didn't miss something...

2024-10-08 10:40 UTC, metacreo commented
@ShaiMagal  maybe this solve:
```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_URI} !((?i)^.*\.(jpg|jpeg|gif|png|bmp|tiff|svg|pdf|mov|mpeg|mp4|avi|mpg|wma|flv|webm|ico|webp|avif)$) [NC]
    RewriteRule .* [R=404]
</IfModule>
ErrorDocument 404 /img/404.gif
```
Only 1kb native ps gif.  As you can see, the PrestaShop developers have already provided this for you. 😆
#37086

2024-10-08 17:13 UTC, Hlavtox commented
@ShaiMagal I have an idea.

We can use conditions in htaccess. What if we just set a different 404 page (simple error) if user agent is a bot? And load the nice page for real users.

2024-10-08 22:05 UTC, ShaiMagal commented
@Hlavtox Too complicated to maintenance bot user agents. You don't aggree with IP's for bots in geolocation (https://github.com/PrestaShop/PrestaShop/pull/36261) and you agree with hosts. You should be constant in your mindset :-D
Of course, we can make rule for specific known bots like Google for example, but there are more bots, not only Google, a lot of "small bots", what are not major... I think, we should use it globally, because it's best practices.

Every big eshop (amazon for example), serve 404 for not found image and don't show content.
Amazon don't care about bots, they do this globally and I would like to make similar PR for PrestaShop ;)
_https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Events/2023/asddsadsaasd/Fuji_Desktop_Single_image_EBF_1x_v5._SY304_CB573698005_.jpg_

What other think?
@nicosomb @matks @kpodemski 

My new edited PR now should work good, but need to be tested detailed

2024-10-09 04:45 UTC, metacreo commented
@Hlavtox  **real** normal users do not parse the site for images. in this case the only problem is bots.

2024-10-09 05:08 UTC, metacreo commented
I don't understand. Is it a habit or a great intellect? Why do you always solve the problem by twisting the whole essence. This is a local problem of the img directory. The problem appeared in 2017 from here:
https://github.com/PrestaShop/PrestaShop/pull/7678 
The problem is only related to bots and access to the img directory.
Why do you change the main .htaccess?
There is a good proverb: It works? - don't touch it.

2024-10-09 05:54 UTC, Hlavtox commented
@metacreo We don't merge anything yet, don't worry. Let's find the best solution. :-)

- Bots are bombarding the site.
- We want to show 404 response for this, not 403.
- Ideally, we want to show simple 404 message to bots, nice 404 for people. If we can't, let's just do simple 404 for all images.

2024-10-21 07:52 UTC, kpodemski requested changes
Hello

We recently introduced the 9.0.x branch, which will be the base for PrestaShop 9.0. If you want to see your change in this version, please rebase your PR onto 9.0.x. The `develop` will be used for PrestaShop 9.1, so you need to decide what to do.

Please rebase onto `9.0.x` or let me know your decision if you don't need to have it there so I can unblock the pull request.

2024-10-27 09:18 UTC, ShaiMagal commented
@nicosomb is my updated PR working for you well?

@kpodemski I can't rebase.

@Hlavtox Can you do this, please?

Guys, to all maintainers -> How we will get continue in this PR?
Can we prioritize this? I don't insist on my solution, it's just that we serve 403 and not 404 for images. That's what we're dealing with here. If there is another solution, give suggestions and we can try another solution than mine.

2024-11-09 18:59 UTC, ShaiMagal commented
Any news here? Its important PR.

2024-11-15 14:10 UTC, jolelievre commented
Hi @ShaiMagal 

I think the 404 approach is correct, and as @Hlavtox reassured me about this automatic generation (that doesn't happen when the URL is access but when it's generated, why not 😅). So we can have the same 404 rule for everyone without the need to configure it I guess

However I agree with @metacreo that his solution seems simpler and more efficient no? The generation of the root htaccess is IMHO already complex enough so if we can avoid relying on a programmatic generation it would be more stable. Since in this case the rul is always the same there's no need to dynamically create, and since there is already a .htaccess in the `img` folder why not rely on it?

However, I noticed a small issue in this PR https://github.com/PrestaShop/PrestaShop/pull/37086 it is that the `Deny all` rule are removed. These rules are important for security reasons, it aims at only allowing access to image files in the image folder. I believe this is mostly to avoid executing a PHP file that would have fraudulently been added in the img folder by some unknown way.

Currently we have:
- any file in this folder is denied access
- however we do grant an exception for image files that can be accessed

We should update the htaccess to keep a similar behaviour except for non existent files:
- any file in this folder is denied access
- however we do grant an exception for image files that can be accessed
- but if the image file doesn't exist then we return a simple 404 response

Do you think this covers everyone's needs?

2024-11-16 18:39 UTC, ShaiMagal commented
@jolelievre i am not sure if i understand this well.
In every case
@metacreo is repeately making PR what broke security btw.

@jolelievre i think we should finish this problem in this PR when i do a lot of time in this investigating.
So, what do you prefer? Finish my PR in this way? Or try change my PR to .htaccess only in img folder?

Let me know, i will try to refacto this.

2024-11-16 21:08 UTC, Hlavtox commented
Yep, I think it must be handled in the main htaccess, because I tried to set custom 404 in the `/img/.htaccess` and it didn't do anything.

2024-11-18 06:16 UTC, metacreo commented
@jolelievre This is not issue... I removed `Deny from all` intentionally. Because I think it's paranoid and unnecessary. All files uploaded to the server must be checked, including by mime. Right here, for some reason everyone wants to load everything onto Apache. This is bad practice, but here it is considered the norm not to do it yourself but to use a third-party solution.

I consider this PR, as well as mine, temporary. Since the correct solution should be absolutely independent of the web server.

@ShaiMagal  Can you give more details? About what security are there? You about Preventing code execution?
But in my opinion it is paranoia. Why not protect all directories with webserver instructions like "Deny from all". 🙂

2024-11-18 06:34 UTC, metacreo commented
Precisely because this solution is temporary, it should be simple and maximally independent. Here they are going to complicate everything, increase the main htaccess, which will lead to additional (albeit insignificant) load on the web server. My PR in this case has an undeniable advantage - it is that htaccess is processed by the web server only when accessing the img directory. In your case Apache will always do this.

2024-11-20 12:48 UTC, jolelievre commented
Sorry I don't have much time to emphasize but TLDR:
- NO we won't remove the protection of denying access in the img folder, even if it's only protecting Apache at least we have this, we're not gonna worsen security just to optimize a 404 page on an image
- ideally, if all can be done in the img .htaccess it would be best, I thought apache htacess files override themselves in subfolders so it should work no? 🤔
- if it doesn't work and we have no other choice we'll go with the solution in the main file, that's unfortunate but if there's no other solution let's go with it
- the response code should be a 404 not a 403

2024-11-20 14:28 UTC, metacreo commented
_I thought apache htacess files override themselves in subfolders so it should work no?_
@jolelievre  Yes it is. apache read every one htaccess

you should move in the direction of abandoning htaccess altogether. Such solutions rigidly bind the code to the web server. What will you do if Apache stops developing. There are already solutions that work many times faster than Apache.

2025-01-02 13:29 UTC, ShaiMagal commented
@jolelievre 
 - "img .htaccess it would be best" - it can't be like already wrote me and @Hlavtox 
 - My last PR is 404 :)
 So, can someone test? :)

2025-02-04 16:46 UTC, ShaiMagal commented
Bump

2025-02-04 16:46 UTC, ShaiMagal commented
@Hlavtox @kpodemski @jolelievre @matks

2025-04-09 10:46 UTC, ShaiMagal commented
Any movement forward? Someone can test this? (except me)
This PR is very important for performance.
@kpodemski @Hlavtox @jolelievre @matks @M0rgan01

2025-08-21 19:06 UTC, ShaiMagal commented
@kpodemski @jolelievre @Hlavtox @nicosomb @PrestaShop/prestashop-core-developers 
Its already one year old and no movement.
Today one of our customers had problems with FB bot who scraping "images" 20/s and images were already dead, so fb bot was loading customers website and totally flood it (website was totally unusable)

After we use this PR to customer, problem disappeared immediatelly.

I think, we should move this forward to PS 9.1.0.
Without this PR its wasting webhosting resources and there can be impact of not working website when any bot is aggresivelly accesing images. (Bots have higher limit for images)
And actual state is, its not correct. We should return only 404. No website content with 404 for non existent images.

2025-08-21 19:48 UTC, Hlavtox commented
@ShaiMagal I suggest recreating this PR with a clear description.

There is million offtopic messages here and bland comments that it will never get merged. :-)

2025-09-10 22:43 UTC, closed without merging