Fix apache error.log filler on active sites
PrestaShop/PrestaShop pull request #37086
Opened 2024-10-04 12:09 UTC by metacreo

When a search engine requests a non-existent image, it should receive a 404 response instead of 403. If the site is not dead and there are constant changes, the search engine gets 403 too often. Many servers have programs installed, such as fail2ban, and for too frequent 403, they issue a ban on the IP. This is normal, because if there is a 403, then there is no need to go there. This is my last attempt to fix this stupidity in /img/.htaccess

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 8.x / 1.7.x
| Description?      | When a search engine requests a non-existent image, it should receive a 404 response instead of 403. If the site is not dead and there are constant changes, the search engine gets 403 too often. Many servers have programs installed, such as fail2ban, and for too frequent 403, they issue a ban on the IP. This is normal, because if there is a 403, then there is no need to go there.
| Type?             | bug fix 
| Category?         | FO 
| BC breaks?        | no
| Deprecations?     | yes
| How to test?      | look a logs on active sites.
| UI Tests          | apache22/24 mod_rewrite
| Fixed issue or discussion?     | 
| Related PRs       |
| Sponsor company   |

2024-10-04 12:09 UTC, ps-jarvis commented
<!-- PR_TABLE_DESCRIPTION_ERROR -->
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `branch` should be `develop` or `8.2.x`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!
### About linked issues
Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

2024-10-04 12:09 UTC, ps-jarvis commented
<!-- PR_WELCOME -->
Hello @metacreo!

This is your first pull request on [PrestaShop](https://github.com/PrestaShop/PrestaShop/) repository of the PrestaShop project.

Thank you, and welcome to this Open Source community!

2024-10-07 11:31 UTC, ShaiMagal requested changes
This PR will show 404 **with** content and we don't want to this.

We want 404 **without** content.

Anyway little "duplicite" to PR #37058 (in progress)

This PR does not even follow the semantics according to other .htaccess of PrestaShop.

2024-10-08 10:23 UTC, metacreo commented
@ShaiMagal What other semantics? is htaccess :)
"We want 404 without content." ))) maybe with no server response? :)
We can add ErrorDocument 404 /img/404.gif to /img/.htaccess 
showing 404.gif is a big load to site ? 😂

2024-10-08 17:14 UTC, Hlavtox commented
@metacreo There is no need to return a gif, just a regular simple 404 message.

2026-09-04 10:58 UTC, closed without merging