Add new version in workflows
PrestaShop/PrestaShop pull request #37188
Opened 2024-10-18 08:49 UTC by tleon

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | Add changes in workflow for 9.0.x
| Type?             |new feature 
| Category?         | BO 
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI green
| UI Tests          | 
| Sponsor company   | PrestaShop SA

2024-10-18 08:49 UTC, ps-jarvis commented
<!-- PR_TABLE_DESCRIPTION_ERROR -->
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `branch` should be `develop` or `8.2.x`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!
### About linked issues
Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

2024-10-18 08:53 UTC, matks commented on .github/workflows/cron_nightly_tests_9.0.x.yml
> +  test_8_2_x:
```suggestion
  test_9_0_x:
```

2024-10-18 08:53 UTC, matks commented on .github/workflows/cron_js_routing.yml
> +#          - 8.2.x missing 8.2.x here ?
Yes 👍

2024-10-18 08:53 UTC, matks commented on .github/workflows/cron_js_routing.yml
> +            node: 16 # node 20 ?
Yes 👍

2024-10-18 08:53 UTC, matks commented on .github/workflows/cron_js_routing.yml
> +#          - BRANCH: 8.2.x missing 8.2.x here ?
Yes 👍

2024-10-18 08:53 UTC, matks commented on .github/workflows/cron_js_routing.yml
> +#          - BRANCH: 8.2.x missing 8.2.x here ?
Actually I think we could remove 8.1.x and 8.0.x because these branches don't move anymore

2024-10-18 10:25 UTC, jolelievre requested changes

2024-10-18 10:25 UTC, jolelievre commented on .github/workflows/cron_nightly_build.yml
Hmm, this one is ok but as @matks I wonder if it will be correctly handled as is since it's not on the develop branches (develop)

Unless this workflow is triggered on multiple branch (8.1.x, 8.2.x, 9.0.x, develop) but it means we have duplicate workflows 🤔 @Progi1984 can we talk about this quickly to be sure?

2024-10-18 10:25 UTC, jolelievre commented on .github/workflows/cron_nightly_tests_9.0.x.yml
Same as previous comment

2024-10-18 10:25 UTC, jolelievre commented on .github/workflows/cron_nightly_tests_reusable.yml
> +            CAMPAIGN: 'functional:BO:advanced-parameters:11-12'
```suggestion
```
You need to use develop as the reference not 8.2.x

2024-10-18 10:25 UTC, jolelievre commented on .github/workflows/cron_nightly_tests_reusable.yml
> +            CAMPAIGN: 'functional:FO:hummingbird:08-12'
```suggestion
          - BRANCH: 9.0.x
            CAMPAIGN: 'sanity:productV2'
          - BRANCH: 9.0.x
            CAMPAIGN: 'functional:productV2'
```

2024-10-18 11:39 UTC, Progi1984 commented on .github/workflows/cron_nightly_tests_reports.yml
> +            database: mysql
```suggestion
          - branch: 9.0.x
            database: mysql
          - branch: 9.0.x
            database: mariadb
```

2024-10-18 11:40 UTC, Progi1984 commented on .github/workflows/cron_nightly_tests_reusable.yml
> +            CAMPAIGN: 'functional:BO:advanced-parameters:11-12'
I approve what @jolelievre said,  @tleon

2024-10-18 11:40 UTC, Progi1984 commented on .github/workflows/cron_nightly_tests_reusable.yml
> +          CP_API_CONFIG: ${{ (env.GH_BRANCH == '8.1.x' || env.GH_BRANCH == '8.2.x' || env.GH_BRANCH == '9.0.x') && 'true' || 'false' }}
```suggestion
          CP_API_CONFIG: ${{ (env.GH_BRANCH == '8.1.x' || env.GH_BRANCH == '8.2.x') && 'true' || 'false' }}
```

2024-10-18 11:41 UTC, Progi1984 commented on .github/workflows/cron_nightly_tests_9.0.x.yml
@tleon Remove this file, and duplicate the two files of develop (linked to :dolphin: mysql & :seal: mariadb).

2024-10-18 11:42 UTC, Progi1984 commented on .github/workflows/cron_nightly_build.yml
Yes, we have nightly on multiples branches, so this change is ok with this.

2024-10-18 11:42 UTC, Progi1984 reviewed
Some feedbacks

2024-10-18 13:52 UTC, Progi1984 approved these changes

2024-10-19 10:04 UTC, jolelievre approved these changes
Thanks @tleon

2024-10-19 10:04 UTC, merged