fix: prevent user saving form with empty value or negative number
PrestaShop/PrestaShop pull request #37185
Opened 2024-10-17 13:27 UTC by Nakahiru

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 8.2.x
| Description?      | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?             | bug fix / improvement / new feature / refacto
| Category?         | FO / BO / CO / IN / WS / TE / LO / ME / PM / see explanations at https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#type--category
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| How to test?      | Indicate how to verify that this change works as expected.
| UI Tests          | Please run UI tests and paste here the link to the run. As we support MySQL and MariaDB in our tests, you have to launch 2 campaigns (by choosing both). [Visit the UI Tests repo and follow instructions](https://github.com/PrestaShop/ga.tests.ui.pr/).
| Fixed issue or discussion?     | Fixes #{issue number here}, Fixes #{another issue number here}, Fixes https://github.com/PrestaShop/PrestaShop/discussions/ {discussion number here}
| Related PRs       | If theme, autoupgrade or other module change is needed to make this change work, provide a link to related PRs here.
| Sponsor company   | Your company or customer's name goes here (if applicable).

2024-10-17 13:33 UTC, ps-jarvis commented
<!-- PR_TABLE_DESCRIPTION_ERROR -->
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `type` should be one of these: `new feature`, `improvement`, `bug fix` or `refacto`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

2024-10-17 13:51 UTC, jolelievre commented on admin-dev/themes/new-theme/js/pages/carrier/form/components/CarrierRangesModal.vue
> +          if (range.from === null || typeof range.from === 'string' || range.from < 0) {
Early comment, I know it's a WIP, it's good to have JS validation, but I think we also should add:
- constraints on the Symfony form
- checks in the CQRS commands

2024-10-17 13:54 UTC, Nakahiru commented on admin-dev/themes/new-theme/js/pages/carrier/form/components/CarrierRangesModal.vue
> +          if (range.from === null || typeof range.from === 'string' || range.from < 0) {
Thanks for the feedback :) If you read the associated issue, there is already a CarrierConstraintException thrown. It was already handled on the "server" side but not handled on the "client" side. If I am not mistaken 🤔

2024-10-17 14:08 UTC, jolelievre commented on admin-dev/themes/new-theme/js/pages/carrier/form/components/CarrierRangesModal.vue
> +          if (range.from === null || typeof range.from === 'string' || range.from < 0) {
Ah ok my bad, do you think it would be interesting to have a custom constraint in the form though?

2024-10-21 07:48 UTC, kpodemski requested changes
Hello @Nakahiru 

We recently introduced the `9.0.x` branch, which will be the base for PrestaShop 9.0. If you want to see your change in this version, please rebase your PR onto `9.0.x`. Branch `develop` will be used for PrestaShop 9.1, so you need to decide what to do.

Please let me know your decision so I can unblock the pull request.

2024-10-28 15:40 UTC, tleon commented
https://github.com/PrestaShop/PrestaShop/pull/37271

2024-10-28 15:40 UTC, closed without merging