Take environment into account in LoadServicesFromModulesPass
PrestaShop/PrestaShop pull request #37223
Opened 2024-10-23 09:23 UTC by maxime-aknin

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch           | develop
| Description      | Add environment parameter to the config loaders, to be able to use when@<env> syntax
| Type             |  improvement
| Category        | CO
| BC breaks       | no
| Deprecations     | no
| How to test      | Use when@ syntax in a module service file
| UI Tests          |  ~
| Fixed issue or discussion     |  ~
| Related PRs       |  ~
| Sponsor company   | ~

2024-10-23 09:35 UTC, matks requested changes
Hello @maxime-aknin and thank you for the PR. Can I guess that you would like use `@when` in a module for symfony config loading, so this change would allow you to do?

2024-10-23 12:22 UTC, maxime-aknin commented
> Hello @maxime-aknin and thank you for the PR. Can I guess that you would like use `@when` in a module for symfony config loading, so this change would allow you to do?

Hi @matks yes exactly, I encountered an issue tinkering with this compiler pass, a `when@` section in a module config file was not loaded (see `YamlFileLoader::load`). Adding the env parameters solves this.

2024-10-24 06:53 UTC, kpodemski commented
@maxime-aknin, could you provide us with an example module? :)

2024-10-24 06:53 UTC, kpodemski commented
also, you may consider rebasing your PR onto `9.0.x` branch, so that your change will be part of the upcoming PrestaShop 9

2024-10-24 07:52 UTC, ps-jarvis commented
<!-- PR_WORDING -->
This pull request seems to contain new translation strings. I have summarized them below to ease up review:

- `Admin.Notifications.Error`
    - [ ] `The selected default page is not accessible by the selected profile.`
    - [ ] `%s: %s`
- `Admin.Advparameters.Feature`
    - [ ] `This value for "%field%" is already used and must be unique.`
    - [ ] `The %s field is invalid.`
    - [ ] `The field "%field%" cannot be longer than %limit% characters.`
    - [ ] `Select your default file separator`
- `Admin.Global`
    - [ ] `The %s field is invalid.`
    - [ ] `The field "%field%" cannot be longer than %limit% characters.`
- `Admin.International.Feature`
    - [ ] `The %s field is not valid`
    - [ ] `The %s field is invalid.`

(Note: this is an automated message, but answering it will reach a real human)

2024-10-24 08:05 UTC, maxime-aknin commented
hi @kpodemski, that's ok for the rebase 👍

For the module sadly I can't provide you with the full module I'm using since it's an internal one, but this simple service config should do the trick with any module:
```yaml
# add new logger
monolog:
  channels:
    - payments
  handlers:
    payments:
      type: stream
      channels: [ payments ]
      path: "%kernel.logs_dir%/payments.log"

# use different log level based on env
when@dev:
  monolog:
    handlers:
      payments:
        level: debug
when@prod:
  monolog:
    handlers:
      payments:
        level: info
```

Also I'm on a custom setup, I noticed I don't have the [code](https://github.com/PrestaShop/PrestaShop/blob/9883ee742443d9242fd53ebf56ef742fb1ef9e57/app/AppKernel.php#L170) in `AppKernel.php` that also seems to load modules config files. But I guess now that this compiler pass exists this code is redundant and should be removed sooner or later ? Anyway I figured adding the environment in the compiler pass could only be a good option.

2024-10-25 07:42 UTC, maxime-aknin commented
> Also I'm on a custom setup, I noticed I don't have the [code](https://github.com/PrestaShop/PrestaShop/blob/9883ee742443d9242fd53ebf56ef742fb1ef9e57/app/AppKernel.php#L170) in `AppKernel.php` that also seems to load modules config files. But I guess now that this compiler pass exists this code is redundant and should be removed sooner or later ? Anyway I figured adding the environment in the compiler pass could only be a good option.

My bad, after more tinkering I realized that the code in `AppKernel::registerContainerConfiguration` is indeed usefull, especially with my example setting up an addtional monolog channel, this wouldn't work with just the `LoadServicesFromModulesPass`, because the merge pass `MergeExtensionConfigurationPass` is always called first... 

Anyway I don't really know if there's a redundancy here or if the duplication is intented / mandatory, but still I think it's relevant to add the environnement to the config loaders

2024-10-31 08:41 UTC, gericfo commented
Hello @maxime-aknin 
Please note that the “Needs autoupgrade PR” label has been automatically added to your Pull Request. This means that the changes made in your PR must also be reported in the Autoupgrade module, responsible for running the update process of PrestaShop stores.
When there's a modification to the db-structure.sql file or if a Doctrine entity has been modified, added, or deleted, it impacts the database structure. Modifying the list of hooks and feature flags has consequences on the update process as well. These changes can affect how the application interacts with the database and how update procedures are handled. It's important to consider these aspects when contributing to ensure a smooth update experience for users.
That's why this contribution should be backported, with another corresponding PR, on the Autoupgrade module's GitHub repository which is available here: [link](https://github.com/PrestaShop/autoupgrade).
Contribution to the Autouograde module doc - [link](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/upgrade-module/ )
Don't forget to add a comment in this current thread with the link to this PR once it has been created.
Thank you.

2024-10-31 10:17 UTC, jolelievre requested changes
Thanks @maxime-aknin,

good call!!

However, I recommend changing the way the environment is passed.
Instead of fetching it from the container parameters please add a mandatory `string $environment` parameter in the constructor (so before `$containerName`)

This means you'll have to update the three places the class is instanciated (two in `PrestaShopBundle` and one in `PrestaShop\PrestaShop\Adapter\ContainerBuilder`) where you'll have to force this new parameter. The advantage is that we make sure this value is up to date even in case `$container->getParameter('kernel.environment')` is not correct yet (which can be the case especially in the legacy container builder used for front)

2024-10-31 10:18 UTC, jolelievre commented
@maxime-aknin also I think you need to rebase your branch (only changing the target branch is not enough) because it contains some merge commits, so you probably are still based on the develop branch and have too many commits in your history

2024-11-17 03:05 UTC, kpodemski commented
ping @maxime-aknin :)

2026-03-25 09:53 UTC, Progi1984 commented
Hello @maxime-aknin ,

Thank you for your contribution to PrestaShop!

We would like to inform you that **PrestaShop 9.1 has been officially released**. You can find the full announcement at the following link:
👉 https://build.prestashop-project.org/news/2026/prestashop-9-1-0-available/

Following this release, **9.0.x** is no longer the active development branch. To ensure your changes can be reviewed and merged, please **rebase this pull request onto the `9.1.x` branch**.

> ⚠️ **Important:** the `9.0.x` branch will be **permanently deleted on April 6, 2026**. Please make sure to rebase before that date.

If you have any questions or need assistance with the rebase process, do not hesitate to ask.

Thank you for your understanding and continued support!

2026-04-07 08:15 UTC, closed without merging