Prevent carrier negative range
PrestaShop/PrestaShop pull request #37271
Opened 2024-10-28 15:38 UTC by tleon

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Prevent the user to add a range with a negative number or an empty field.
| Type?             | bug fix / improvement / new feature / refacto
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Describe in the associated issue
| UI Tests          | 
| Fixed issue or discussion?     | #37154
| Sponsor company   | PrestaShop SA

2024-10-28 15:38 UTC, ps-jarvis commented
<!-- PR_TABLE_DESCRIPTION_ERROR -->
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `type` should be one of these: `new feature`, `improvement`, `bug fix` or `refacto`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

2024-10-30 12:55 UTC, jolelievre reviewed
Thanks @tleon 

I think we could add one last constraint in the Symfony form type here:
https://github.com/PrestaShop/PrestaShop/blob/68b96d005e02ebebf05cae6f518a17a02a2a313a/src/PrestaShopBundle/Form/Admin/Improve/Shipping/Carrier/Type/CostsRangeType.php#L49-L50

Both from and to fields should have a constraint that forces minimum value to 0

2024-10-30 12:55 UTC, jolelievre commented on src/Core/Domain/Carrier/ValueObject/CarrierRangeZone.php
> +            if ($range['range_from'] < 0) {
You should check range_to as well no?

2024-10-30 12:55 UTC, jolelievre commented on tests/Integration/Behaviour/Features/Scenario/Carrier/Ranges/carrier_ranges.feature
> +    Then I set ranges for carrier "carrier1" with specified properties for all shops:
If a rule is added on the ranges you should add another error check with range_to negative

2024-10-31 10:58 UTC, ps-jarvis commented
<!-- PR_WORDING -->
This pull request seems to contain new translation strings. I have summarized them below to ease up review:

- `Admin.Shipping.Feature`
    - [ ] `Range`
    - [ ] `Price (VAT excl.)`

(Note: this is an automated message, but answering it will reach a real human)

2024-11-04 08:42 UTC, jolelievre approved these changes
Thanks @tleon

2024-11-04 08:42 UTC, jolelievre commented on src/PrestaShopBundle/Form/Admin/Improve/Shipping/Carrier/Type/CostsRangeType.php
> +                    new PositiveOrZero([
I wonder if this one should be strictly positive, but that's just a suggestion/question I'm asking myself I guess QA or user feedback will let us know

2024-11-05 08:44 UTC, nicosomb approved these changes, later dismissed

2024-11-05 09:06 UTC, boherm approved these changes, later dismissed

2024-11-05 14:57 UTC, florine2623 reviewed
Hello @tleon ,

Following the steps to reproduce in the issue, I have a big exception at step 2.

<img width="1430" alt="Screenshot 2024-11-05 at 15 54 49" src="https://github.com/user-attachments/assets/11f8de6f-16a7-4e13-bbb5-a66403cd49f9">

```
HTTP 500 Internal Server Error
An error has occurred resolving the options of the form "Symfony\Component\Form\Extension\Core\Type\HiddenType": The option "constrains" does not exist. Defined options are: "action", "alert_message", "alert_position", "alert_title", "alert_type", "allow_extra_fields", "allow_file_upload", "attr", "attr_translation_parameters", "auto_initialize", "block_name", "block_prefix", "by_reference", "column_breaker", "columns_number", "compound", "constraints", "csrf_field_name", "csrf_message", "csrf_protection", "csrf_token_id", "csrf_token_manager", "data", "data_class", "default_empty_data", "disabled", "disabled_value", "disabling_switch", "disabling_switch_event", "empty_data", "empty_view_data", "error_bubbling", "error_mapping", "external_link", "extra_fields_message", "form_attr", "form_theme", "getter", "help", "help_attr", "help_html", "help_translation_parameters", "hint", "inherit_data", "invalid_message", "invalid_message_parameters", "is_empty_callback", "label", "label_attr", "label_format", "label_help_box", "label_html", "label_subtitle", "label_tab", "label_tag_name", "label_translation_parameters", "mapped", "method", "modify_all_shops", "multistore_configuration_key", "multistore_dropdown", "post_max_size_message", "priority", "property_path", "required", "row_attr", "setter", "switch_state_on_disable", "translation_domain", "trim", "upload_max_size_message", "use_default_themes", "validation_groups".
```

Am I missing something ?
Thanks!

2024-11-06 22:38 UTC, jolelievre requested changes

2024-11-06 22:38 UTC, jolelievre commented on src/PrestaShopBundle/Form/Admin/Improve/Shipping/Carrier/Type/CostsRangeType.php
> +                'constrains' => [
```suggestion
                'constraints' => [
```

2024-11-06 22:38 UTC, jolelievre commented on src/PrestaShopBundle/Form/Admin/Improve/Shipping/Carrier/Type/CostsRangeType.php
> +                'constrains' => [
```suggestion
                'constraints' => [
```

2024-11-06 22:38 UTC, jolelievre commented on src/PrestaShopBundle/Form/Admin/Improve/Shipping/Carrier/Type/CostsRangeType.php
> +                'constrains' => [
This should fix the bug detected by QA

2024-11-08 10:39 UTC, tleon commented
@florine2623 should be fixed now. Tests are running

2024-11-12 17:25 UTC, florine2623 reviewed
Hello @tleon ,

No more exception is displayed. I can't Save a range with a minus sign ✅ 

Although, I don't have any clear error message. Maybe a message can be added in the general warning and displayed when I enter the incorrect data ?

<img width="688" alt="Screenshot 2024-11-12 at 17 19 00" src="https://github.com/user-attachments/assets/7c517ed9-ca6d-487c-8eee-601ad6f766bd">

I have relaunch the automated test with the latest modifications of the PR : 
https://github.com/florine2623/testing_pr/actions/runs/11799652362 ✅ 

Thanks!

2024-11-14 15:38 UTC, tleon commented
Added an error message when trying to submit a negative range 
![image](https://github.com/user-attachments/assets/c0c5fc48-4f42-4785-ae1c-15fe81adcfbc)
Can change wording if it's not ok like this.

2024-11-15 16:41 UTC, jolelievre approved these changes

2024-11-19 14:21 UTC, florine2623 approved these changes
Thanks ! The error message error is well displayed when a negative range is typed.

It is QA ✅

2024-11-19 14:58 UTC, merged