Fixed documentation URL for PrestaShop 9.0.x
PrestaShop/PrestaShop pull request #37312
Opened 2024-11-04 10:08 UTC by nicosomb

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x 
| Description?      | Fixed documentation URL for PrestaShop 9.0.x
| Type?             | bug fix 
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | N/A
| UI Tests          | N/A
| Fixed issue or discussion?     | Fixes #37119
| Related PRs       | N/A
| Sponsor company   | PrestaShop SA

2024-11-04 17:47 UTC, boherm requested changes
LGTM, but just one comment about `buildLock` file in your PR ;)

2024-11-04 17:47 UTC, boherm commented on admin-dev/themes/new-theme/buildLock
I don't thing that we need this file 🤔

2024-11-04 18:25 UTC, nicosomb commented on admin-dev/themes/new-theme/buildLock
Don't know why this file was here.

2024-11-04 18:49 UTC, jolelievre approved these changes

2024-11-05 09:06 UTC, boherm approved these changes

2024-11-05 09:10 UTC, tleon approved these changes

2024-11-05 10:45 UTC, nicosomb commented
No QA needed.

2024-11-05 10:45 UTC, merged