New FO hook displayOrderSummaryTable - add custom row to OrderSummary
PrestaShop/PrestaShop pull request #37334
Opened 2024-11-07 00:35 UTC by ShaiMagal

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Details in #37333. This is only 1 PR from 2. We need add this hook to order-confirmation-table.tpl as well.
| Type?             | new feature
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Indicate how to verify that this change works as expected.
| UI Tests          | 
| Fixed issue or discussion?     | Fixes #37333 
| Related PRs       | 
| Sponsor company   | https://www.openservis.cz/

2024-11-07 00:35 UTC, ps-jarvis commented
<!-- PR_TABLE_DESCRIPTION_ERROR -->
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!
### About linked issues
Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

2024-11-07 00:51 UTC, ps-jarvis commented
<!-- PR_TABLE_DESCRIPTION_ERROR -->
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!
### About linked issues
Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

2024-11-07 07:29 UTC, Hlavtox requested changes
I think that it's a bit short scoped. You can already use actionPresentOrder hook to alter the totals. We could modify the theme to display the totals dynamically. WDYT?

2024-11-09 21:05 UTC, ShaiMagal commented
@Hlavtox Via hook hookactionPresentCart you are able to change right side of cart - there is no problem.
But there is problem with change values  for Order Summary.
**Every module developer with module of type "Cash on delivery" is hardcoding this in template!** (or putting their own hooks there to file)
With hook hookactionPresentCart you are not able to do all job unfortunatelly.
Because, this hook is "static".
It not depends on what method you choose, there will be surcharge for all payment methods. But we want it only for specific payment method.

Now it is impossible to do that with native hookactionPresentCart..
There is added surgarge, great, but it's for ALL payment methods..:

It is possible to do this now only by any javascript way (but it's complicated to be compatible with all) or adding hook manually or hardcode template... I don't see better option, so I am suggesting adding a new hook to solve this problem...

If you have better option, let me know :)
Now I have same problem in right panel, but I am solving this via javascript, but order summary is more complicated.

OK, there is possiblity to do javascript way, but we must add CLASSES to themes (https://github.com/PrestaShop/classic-theme/pull/158)... To be targeted and then tell all theme developers to do same..

**Show me better way, I appreciate it, if we found any better way :)**
I am open to discussion or a better solution.

2024-11-11 08:32 UTC, Hlavtox commented
@ShaiMagal I think we both mean different thing. Try checking out `actionPresentOrder`. :-)

2024-11-16 18:41 UTC, ShaiMagal commented
@Hlavtox actionPresentOrder dont solve nothing. We are solving cart, not order. And there is no possibility how to do this dynamicaly based on choose payment method.

2024-11-17 02:03 UTC, kpodemski requested changes
what about order presenter? have you tried to check how to implement it inside it? not by using what it is now, but how to improve it

i think that there should be a way to override but i'm not sure i understand adding a hook but not implementation

2024-11-17 08:48 UTC, Hlavtox commented
@kpodemski I misunderstood Dominik. The problem is that COD modules need to add a charge to the cart totals.

But, the cart is not refreshed when changing payment method. So the modules do it by JS.

This is possible on cart summary on top right, but not in the optional bottom summary before confirmation, there are no selectors.

I also auggested to replace the whole summary html by ajax call to the core, but the problem is that prestashop does not remember selected payment method in the checkou.

2024-11-25 21:27 UTC, ShaiMagal commented
@kpodemski order presenter is not solution, we need to solve in cart, not in finalized order. cart presenter isn't solving issue. This is not updated, when you change payment method.

2024-12-08 01:17 UTC, kpodemski requested changes
Two things:

1. This should probably target `9.0.x`
2. We will need to have an example of implementation.

2025-01-02 13:31 UTC, ShaiMagal commented
@kpodemski 
1) so can someone rebase this to 9.x? I dont know how this is doing.

2) What do you mean exactly?

2025-02-04 16:46 UTC, ShaiMagal commented
Bump

2025-02-13 20:55 UTC, kpodemski commented
Hello @ShaiMagal 

I’m afraid that either you learn how to rebase the PR or it will get stale. Here’s a tutorial: https://build.prestashop-project.org/howtos/misc/rebasing-your-git-branch/

regarding the example implementation, you added a new hook, but when it will be implemented? didn’t you forget to create a PR in the theme?

2025-04-08 10:16 UTC, kpodemski commented
Hello @ShaiMagal 

Any news about this PR?

2025-04-09 10:43 UTC, ShaiMagal commented
@kpodemski I changed my priorities. So I'm closing the PR for now.

2025-04-09 10:43 UTC, closed without merging