getCustomerOrders - in specific case incorrect sorting by date_add DESC
PrestaShop/PrestaShop pull request #37332
Opened 2024-11-07 00:14 UTC by ShaiMagal

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Function Order::getCustomerOrders is returning orders for customer, BUT, there is one specific case. If customer make order and it's splitter, there is same date_add, so there is "RANDOM" sort (@Hlavtox  already reported this feature in his other PR, it's same here). So we change date_add DESC to id_order DESC - it is working well.
| Type?             | bug fix
| Category?         | CO 
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | make an order that splits into 2, then both have the same date. Then call the function OrdeR::getCustomerOrders and depending on different mysql settings, randomness and other phenomena, you will get a different order every time. In my case, for example, see the screen below. After applying PR, it will already sort correctly as it should.
| UI Tests          | 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   | https://www.openservis.cz/

2024-11-07 00:16 UTC, ps-jarvis commented
<!-- PR_TABLE_DESCRIPTION_ERROR -->
Hi, thanks for this contribution!

Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

2024-11-07 00:18 UTC, ps-jarvis commented
<!-- PR_TABLE_DESCRIPTION_ERROR -->
Hi, thanks for this contribution!

Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

2024-11-07 07:27 UTC, Hlavtox requested changes
Two things Dominik:
- You are changing the behavior by this, the ID will probably be ascending, but you can't be sure. This method is used in many places even in front office. So please use `o.`date_add` DESC, o.`id_order` ASC`.
- Please target 8.2.x branch, this is a safe fix.

2024-11-09 18:56 UTC, ShaiMagal commented
@Hlavtox i dont believe my pr will break something "behaviour". But up to you, i changed code and change to 8.2

But i cant rebase it. Can you do it for me? If not, we will leave this for develop.

2024-11-11 08:39 UTC, ps-jarvis commented
<!-- PR_WORDING -->
This pull request seems to contain new translation strings. I have summarized them below to ease up review:

- `Admin.Modules.Notification`
    - [ ] `The override file %1$s conflicts with an existing override in %2$s.`

(Note: this is an automated message, but answering it will reach a real human)

2024-11-11 08:39 UTC, Hlavtox approved these changes

2024-11-11 08:40 UTC, Hlavtox commented
@kpodemski Can this be QAd by dev? It's a safe change and hard to test.

2024-11-17 03:09 UTC, kpodemski approved these changes

2024-11-17 03:09 UTC, kpodemski commented
@Hlavtox yep

2025-01-02 13:30 UTC, ShaiMagal commented
@Hlavtox @kpodemski can we merge this?

2025-01-09 09:48 UTC, Betafer commented
Hello, when will this version be released?

2025-01-11 11:50 UTC, Hlavtox commented
Works fine, dev by QA.

2025-01-11 11:50 UTC, merged