Ensure consistent default combination ID
PrestaShop/PrestaShop pull request #37359
Opened 2024-11-12 13:29 UTC by Hlavtox

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.2.x
| Description?      | Ensures that default combination ID on product list is always consistent by adding an ORDER BY clause to the query. Should fix the related issue. Also, makes the code to fetch the default combination a bit more readable. I can then just copy paste it to a better place.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | This feature is used so much, that tests would reveal any issue. @Progi1984 can check if it fixed his issue.
| UI Tests          | 
| Fixed issue or discussion?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/36356
| Related PRs       | 
| Sponsor company   |

2024-11-12 13:33 UTC, Progi1984 commented
@Hlavtox You can unskip the test : https://github.com/PrestaShop/PrestaShop/blob/9.0.x/tests/UI/campaigns/functional/FO/classic/06_homePage/05_selectColor.ts#L61-L64

2024-11-12 14:32 UTC, nicosomb approved these changes, later dismissed

2024-11-12 14:35 UTC, Progi1984 commented
@Hlavtox Ping me when CI & UI Tests are :green_circle:

2024-11-13 11:40 UTC, Hlavtox commented
mysql: https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/11816500269
mariadb: https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/11816508011

2024-11-17 03:08 UTC, kpodemski submitted a review, later dismissed

2024-11-22 08:20 UTC, kpodemski approved these changes

2024-11-22 08:47 UTC, Hlavtox commented
The tests still fail, there is Size-M for some reason on one db query, and I don't know where the logic comes from.

2024-11-22 08:48 UTC, kpodemski requested changes
ok, blocking this for now

2025-01-09 13:58 UTC, closed without merging