EAN13/GTIN14 - better validation
PrestaShop/PrestaShop pull request #37381
Opened 2024-11-14 23:43 UTC by ShaiMagal

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | Now GTIN/EAN pattern accept string with for example length 5, but this is not valid EAN/GTIN. This PR make preg_match for 8 characters minimum and fix Validate.php, where is duplicate preg_match, but we would use Ean13::VALID_PATTERN to prevent duplicates. Same like for Gtin::VALID_PATTERN. Maybe there can be another validation method to specific number, but actual length 8 is better than 0 validate.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 
| UI Tests          | 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   | https://www.openservis.cz/

2024-11-14 23:43 UTC, ps-jarvis commented
<!-- PR_TABLE_DESCRIPTION_ERROR -->
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

2024-11-14 23:49 UTC, Hlavtox commented
@ShaiMagal Does it work with empty ean?

2024-11-15 07:39 UTC, nicosomb requested changes

2024-11-15 07:39 UTC, nicosomb commented on classes/Validate.php
> +        return !$ean13 || preg_match(Ean13::VALID_PATTERN, $ean13);
Namespace import is missing

2024-11-15 08:26 UTC, Hlavtox commented on classes/Validate.php
> +        return !$ean13 || preg_match(Ean13::VALID_PATTERN, $ean13);
Fixed

2024-11-15 08:36 UTC, nicosomb submitted a review, later dismissed

2024-11-15 11:43 UTC, Hlavtox commented
@ShaiMagal Doesn't seem to work, please try to re-test when editing a combination. (new product page)

Throws `Invalid GTIN "". It should match pattern "/^[0-9]{8,14}$/" and cannot exceed 14 symbols (PrestaShop\PrestaShop\Core\Domain\Product\Exception\ProductConstraintException)`

2024-11-15 11:45 UTC, Hlavtox commented
@jolelievre @tleon @FabienPapet Guys, should the regex be modified to allow for empty value, or the application SHOULD NOT construct the value object?

2024-11-16 20:52 UTC, ShaiMagal commented
@Hlavtox I edited 'only for testing) regexp and we will see, what tests will tell us now...

2024-11-18 09:01 UTC, jolelievre commented
@Hlavtox ideally I guess the VO should only be created when you set a valid input So not empty and with the minimum amount of characters. But it may imply more modifications:
- the command must have nullable/optional values for these VOs, but it's already possible in the two places where it's used But then it also raises the question about how to reset a value (set it back to empty value) Since the null value means no modifications (partial update), and the VO would not allow empty value we'd be stuck with an unremovable value Unless we introduce a `NoGtin` special class/value for the VO like we did for some VO IDs but it's maybe overkill
- the simpler alternative is to authorize empty value in the VO I guess, you could keep the regexp as you did with minimum 8 characters and it's only used when the value is not empty

2024-11-18 09:09 UTC, Hlavtox commented
@jolelievre Thank you Jo. :-) Ok, for now, @ShaiMagal have used your second suggestion, let's see if the test will work. 👍

2025-01-02 13:32 UTC, ShaiMagal commented
@Hlavtox @jolelievre what are the next steps now? :)

2025-02-04 16:46 UTC, ShaiMagal commented
Bump

2025-02-04 16:48 UTC, FabienPapet approved these changes

2025-04-09 10:44 UTC, ShaiMagal commented
@Hlavtox can you check it please?

2025-07-16 14:20 UTC, ShaiMagal commented
@kpodemski do you see where is the problem please?

2025-08-20 12:18 UTC, kpodemski requested changes
Hey @ShaiMagal 

I suggest revisiting this subject for PrestaShop 10. We cannot change validation methods for minor and patch versions, and we didn't manage to have this PR finished for 9.0.

2025-08-20 14:12 UTC, ShaiMagal commented
@kpodemski OK, so I will close this PR and make new one for "develop" branch? Or what is correct step now?

2025-08-20 14:19 UTC, kpodemski commented
@ShaiMagal 

We have to put this subject aside.

Develop branch is for PrestaShop 9.1.

2025-08-21 19:10 UTC, ShaiMagal commented
@kpodemski sad :(
Ok. Maybe we can think about any possibility how to directly (from now) target to branch10?  Than use draft and wait?

2026-03-25 09:53 UTC, Progi1984 commented
Hello @ShaiMagal ,

Thank you for your contribution to PrestaShop!

We would like to inform you that **PrestaShop 9.1 has been officially released**. You can find the full announcement at the following link:
👉 https://build.prestashop-project.org/news/2026/prestashop-9-1-0-available/

Following this release, **9.0.x** is no longer the active development branch. To ensure your changes can be reviewed and merged, please **rebase this pull request onto the `9.1.x` branch**.

> ⚠️ **Important:** the `9.0.x` branch will be **permanently deleted on April 6, 2026**. Please make sure to rebase before that date.

If you have any questions or need assistance with the rebase process, do not hesitate to ask.

Thank you for your understanding and continued support!

2026-03-25 10:49 UTC, kpodemski commented
hey @ShaiMagal 

Let's close this PR for now. v10 is not on the radar for now, we can get back to it when the time comes, your work won't be lost.

2026-03-25 10:49 UTC, closed without merging