Add 'product Sales' to default product sort parameter
PrestaShop/PrestaShop pull request #37430
Opened 2024-11-21 18:07 UTC by jf-viguier

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | Add 'product Sales' to default product sort parameter
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Go to product settings : choose Sales product
| UI Tests          | 
| Fixed issue or discussion?     | no
| Sponsor company   | Creabilis.com

2024-11-21 18:07 UTC, ps-jarvis commented
<!-- PR_TABLE_DESCRIPTION_ERROR -->
Hi, thanks for this contribution!

Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

2024-11-21 19:42 UTC, Hlavtox requested changes
I think you cant do this, because its not supported by default category search provider I think.

2024-11-21 20:03 UTC, kpodemski commented
I think this should be configurable, not everyone wants to allow people to show bestsellers and imagine showing products sorted by sales... :)

2024-11-22 07:37 UTC, jf-viguier commented
@Hlavtox this setting is not about default category search, it should allow all sort orders supported by SrestaShop.
Take a look at the brand or stock quantity sort order : it not il the default category search either.

2024-11-22 07:41 UTC, jf-viguier commented
Sanity 8.3 fail because of a timeout.

2024-11-22 08:20 UTC, jolelievre approved these changes, later dismissed
Thanks @jf-viguier 

Seems good to know, we should just be warry about Daniel's warning during QA

2024-11-26 10:34 UTC, jf-viguier commented
Can I have your warning @Hlavtox ? for me the bo should suggest all supported sorting

2024-11-26 10:37 UTC, Hlavtox commented
@jf-viguier Yes, but this sort order is supported ONLY by ps_facetedsearch module. In all other cases, it will fail. You disable faceted search, you don't have a sort, you install other search module, you don't have sort. You don't have faceted search enabled for certain pages, you don't have a sort.

I know, the sorting sucks, but it needs a deeper thought.

2024-11-26 14:53 UTC, jolelievre commented
I just tested the PR and indeed when the ps_facetedsearch module is uninstalled there is an exception thrown:
![Capture d’écran 2024-11-26 à 15 49 30](https://github.com/user-attachments/assets/a3af9c45-142d-4ebf-bcc3-a7d4da6c8416)

The core most be robust enough to at least not bug because of this setting, but mostly be able to handle it appropriately. The feature is legit it's just that the PR is missing something, maybe some modifications in the product list controller?

Also, I tested with the faceted search module, and although there is no exception the product On sales are not sorted in first so there is maybe something to handle also in the faceted search module?

2024-11-26 14:59 UTC, Hlavtox commented
@jolelievre Yes. :-)

`Best sales` is not `On sale`.
Sorting by sales is sorting by the amount of sold products.
On sale is a checkbox in BO that marks the product as "On sale" (last chance).

2024-11-26 16:32 UTC, jf-viguier commented
@jolelievre I can add a test if ps_facetedsearch is installed but it's dirty. 
Why not adding sorting by sales in the core ?

2024-11-26 16:45 UTC, Hlavtox commented
@jf-viguier You could, that would be a proper solution. :-)

2024-11-26 18:13 UTC, ps-jarvis commented
<!-- PR_WORDING -->
This pull request seems to contain new translation strings. I have summarized them below to ease up review:

- `Shop.Theme.Catalog`
    - [ ] `Best sales`

(Note: this is an automated message, but answering it will reach a real human)

2024-11-26 18:15 UTC, jf-viguier commented
@jolelievre @Hlavtox I've add sorting by best sales in front category, that solve the error.
I think that faceted search module should car about facets, not sorting order.

2024-11-27 17:38 UTC, jolelievre commented on src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/PaginationType.php
> +                    'Product sales' => 8,
```suggestion
                    'Product best sales' => 8,
```
The options are passed hard-coded, does it mean they are never translated?

2024-11-27 17:38 UTC, jolelievre commented on src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/PaginationType.php
> +                    'Product sales' => 8,
Ah they are thanks to the `translation_domain` option below But there's another problem then if this wording is not used somewhere else when used with the `trans` method it will never be extracted

2024-11-27 17:38 UTC, jolelievre commented on src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/PaginationType.php
> +                    'Product sales' => 8,
To make sure all these wordings are correctly scanned you should use `$this->trans` to generate each key

2024-12-04 13:08 UTC, Hlavtox commented on src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/PaginationType.php
> +                    'Product sales' => 8,
@jolelievre It will work, the scan tool somehow discovers these. I checked the other options and the are in the XLF files just fine. :-)

2024-12-04 13:09 UTC, Hlavtox approved these changes
I think it's ready, but please:

Make sure to check if it works on all other listings with faceted search uninstalled - manufacturer, new products, best sale products, prices drop, search.

2024-12-04 13:24 UTC, jf-viguier commented
sort order is not configurable in manufacturer, new products, best sale products, prices drop, search, so I don't add my sorting here

2024-12-04 17:37 UTC, jolelievre commented on src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/PaginationType.php
> +                    'Product sales' => 8,
I think they are in the XLF because they are used somewhere else, but we'll see ^^

2024-12-04 18:03 UTC, Hlavtox commented on src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/PaginationType.php
> +                    'Product sales' => 8,
@jolelievre I hope! If it doesn't work, VS code is messing with me. :D

![Snímek obrazovky 2024-12-04 190250](https://github.com/user-attachments/assets/686b4c86-d7ed-4864-ae2d-f4d2bfcfd11c)

2024-12-05 08:00 UTC, jf-viguier commented
"Product sales" is in this file, should be ok
vendor/prestashop/translationtools-bundle/Tests/Translation/Extractor/PhpExtractorTest.php

2024-12-05 08:24 UTC, jf-viguier commented
I've rebased @Hlavtox @jolelievre

2024-12-05 12:07 UTC, jolelievre approved these changes

2024-12-05 13:16 UTC, Hlavtox approved these changes

2024-12-10 13:34 UTC, jf-viguier commented
failed test on a webkit timeout, can someone relauch tests please ?

2024-12-10 14:31 UTC, boherm approved these changes

2024-12-11 15:55 UTC, florine2623 commented
https://github.com/florine2623/testing_pr/actions/runs/12280062961

2024-12-17 11:04 UTC, florine2623 approved these changes
Hello @jf-viguier ,

Thanks for the PR ^^

I checked the standard case, it works as expected :

https://github.com/user-attachments/assets/4365e8c5-1b94-430d-b6d5-0daf52bd36a9

I tested the other settings on BO and FO, it works like usual.
It is QA ✅ 
Thanks!

2024-12-17 12:49 UTC, merged

2024-12-17 13:08 UTC, Hlavtox commented
@florine2623 @jf-viguier @nicosomb This must be tested WITHOUT ps_facetedsearch installed, that was the whole point of implementing the listing. Can you please re-test it?