SEO delete categorie in URL during installation
PrestaShop/PrestaShop pull request #37467
Opened 2024-11-25 13:59 UTC by jeckyl

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | Removal of category reference in product URLs during PrestaShop installation.
This has no effect on PrestaShop updates.
It simplifies product URLs, allowing you to simply add the category if you wish without any further action, and avoids the need to redirect old URLs including categories to 301 if the user wishes to remove this data.
| Type?             | improvement
| Category?         | FO / BO / CO / IN
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | This change modifies the structure of product URLs when PrestaShop is installed, and only when it's installed. It doesn't change anything when you upgrade, or at least it shouldn't modify the information when you upgrade.
| Fixed issue or discussion?     | Fixes https://github.com/PrestaShop/PrestaShop/discussions/37437
| Sponsor company   | Mediacom87.fr

2024-11-25 13:59 UTC, ps-jarvis commented
<!-- PR_TABLE_DESCRIPTION_ERROR -->
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `category` should be one of these: `FO`, `BO`, `CO`, `IN`, `WS`, `TE`, `LO`, `ME` or `PM`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

2024-11-25 14:11 UTC, jf-viguier approved these changes

2024-11-25 14:13 UTC, kpodemski commented
ping @PrestaShop/product-council @ibahloul-ps

2024-11-25 14:27 UTC, Hlavtox requested changes
I would personally go for `domain.com/product/1-product.html` or `domain.com/p/1-product.html`

That will allow us to also get rid of the `.html` suffix that's there.

2024-11-25 14:53 UTC, jeckyl commented
> I would personally go for `domain.com/product/1-product.html` or `domain.com/p/1-product.html`
> 
> That will allow us to also get rid of the `.html` suffix that's there.

Except that doing so would break PrestaShop's native functionality, since you'd have to modify htaccess to manage the old form of product URLs.
What I'm proposing, on the other hand, is a simple way of implementing your URL structure if you wish.

2024-11-25 15:20 UTC, kpodemski commented
> I would personally go for `domain.com/product/1-product.html` or `domain.com/p/1-product.html`
> 
> 
> 
> That will allow us to also get rid of the `.html` suffix that's there.

That's not what has been agreed

2024-11-25 15:39 UTC, Hlavtox commented
@kpodemski If we are changing default product route, let's think for one more minute, that's all. I am not dwelling on anything, just a suggestion.

@jeckyl Why do you think it will need htaccess change?

2024-11-25 15:43 UTC, jeckyl commented
> @jeckyl Why do you think it will need htaccess change?

If you base the creation of a store on a sub-folder in the URL, whatever it may be, if you want to remove it later, the old URLs will be in 404 error mode, just like when the URLs included the category.
It's better to leave it up to users to add whatever they want.

2024-11-25 17:29 UTC, Touxten approved these changes
I also like Daniel's idea, surely in a future Major or we could also remove the ean13 ( NPM ) in new version

2024-11-25 19:55 UTC, LouisAUTHIE commented
I would be in favor of a ean13 removal that leads to useless and very long urls

2024-11-25 19:56 UTC, LouisAUTHIE requested changes
Maybe go further and remove the ean13. But the rest is clear and great thanks @jeckyl

2024-11-26 07:36 UTC, jeckyl commented
> Maybe go further and remove the ean13. But the rest is clear and great thanks @jeckyl

The removal or presence of the EAN13 in the URL only affects a redirection automatically handled by PrestaShop and doesn't require any technical expertise to intervene on this change, so I haven't bothered to broaden the discussion on this subject.
The discussion is interesting and can be opened on the subject to gather as many opinions as possible and make the best decision as to whether to remove it or keep it.

2024-11-26 14:20 UTC, Touxten approved these changes

2024-11-26 14:39 UTC, LouisAUTHIE approved these changes, later dismissed
Great job @jeckyl

2024-11-26 14:45 UTC, Hlavtox commented
Guys, suggestion. I just tested dropping the .html at the end and it works perfectly.

See - `https://dev.trendo.cz/product/2-osklivy-produkt`.

WDYT about this last change?

2024-11-26 14:48 UTC, jeckyl commented
> Guys, suggestion. I just tested dropping the .html at the end and it works perfectly.
> 
> See - https://dev.trendo.cz/product/2-osklivy-produkt
> 
> WDYT about this last change?

Please open a discussion on this point to really explain the interest and benefits of changing URLs for this form.

2024-11-26 14:53 UTC, Touxten commented
Hello Daniel!

I agree with you it would be necessary to check the bugs if there are with the category and cms urls.

This Pr is part of the Friends of Presta academy to have new contributors.

What do you think about validating it and we open a new discussion and @jeckyl can make a new PR

Regards

2024-11-26 14:58 UTC, jeckyl commented
The real question is what's the difference and what's the point of replacing .html with /product/, an English term that can't be translated, and which will therefore potentially penalize all stores in other languages if the URLs had any importance at all.
Hence the interest in seriously starting a new discussion on this subject, as another person has opened a discussion about moving the ID into the URL.
If my PR is mainly technical and not SEO, any other changes are just cosmetics that can and should be discussed.

2024-11-26 15:00 UTC, Hlavtox submitted a review, later dismissed

2024-11-26 15:00 UTC, Hlavtox commented
I don't want to block it, I will open a new discussion about my proposed change. :-)

I want to remove the .html for the sake of consistency. It's just a leftover from old times.

2024-11-29 08:17 UTC, florine2623 reviewed
Hello @Progi1984 ,

The auto tests needs to be updated right ?

https://github.com/florine2623/testing_pr/actions/runs/12070989574

It seems like there's an issue in the Home Page.

Waiting for your feedback, thanks!

2024-11-29 10:09 UTC, Progi1984 commented
Discussed with @Touxten for fixing UI tests :)

2024-11-29 10:25 UTC, Progi1984 approved these changes
OK for UI Tests

2024-11-29 10:26 UTC, Progi1984 commented
@florine2623 COuld you restart only failed tests, please ?

2024-11-29 15:09 UTC, florine2623 approved these changes
Hello @Touxten ,

The URL is well updated. The category is not displayed anymore.

I can still add it if I want to in SEO & URL in the BO.

LGTM ✅ 
Thanks!

**PS : Before merging, it needs some more approvals.**

2024-11-29 15:31 UTC, Hlavtox approved these changes

2024-11-29 15:44 UTC, kpodemski requested changes
let's wait for @ibahloul-ps for the final approval

2024-11-30 07:28 UTC, LouisAUTHIE approved these changes

2024-12-02 10:48 UTC, ibahloul-ps approved these changes

2024-12-02 10:50 UTC, kpodemski approved these changes

2024-12-02 10:51 UTC, merged

2024-12-02 10:51 UTC, kpodemski commented
thank you @jeckyl

2025-11-21 18:22 UTC, Hlavtox commented
This PR causes a pretty serious SEO issue. Fixed by https://github.com/PrestaShop/autoupgrade/pull/1535.