Minor order page UX improvements
PrestaShop/PrestaShop pull request #37482
Opened 2024-11-26 13:46 UTC by Hlavtox

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | This slightly improves the UX of the order detail page and adds more data.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Check order detail page in BO.
| UI Tests          | https://github.com/florine2623/testing_pr/actions/runs/12177912859
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   | 

### Changes
1. Removed the UX disaster in the header.
2. Added a basic information block with ID, reference, link to cart this order was created from, date, price, payment and delivery. Uses the same design as basic information block on customer detail page.
3. Improved the block with customer details - more data, same space, better responsivity.
4. Changed the link to customer details - more visible, same space.
5. Added MPN to product list.
6. Change button to resend status email - more visible, same space.
7. Specified what is customer and what is order private note, my clients were confused.

_In another PR, I will add tax excl and tax incl totals also._

![changes](https://github.com/user-attachments/assets/561ee6a4-ec17-4caf-aa99-e41458e792e7)

2024-11-26 13:46 UTC, ps-jarvis commented
<!-- PR_WORDING -->
This pull request seems to contain new translation strings. I have summarized them below to ease up review:

- `Admin.Orderscustomers.Feature`
    - [ ] `ID:`
    - [ ] `Customer private note`
    - [ ] `Order private note`
    - [ ] `MPN:`
- `Admin.Global`
    - [ ] `Basic information`

(Note: this is an automated message, but answering it will reach a real human)

2024-11-26 13:49 UTC, Hlavtox commented
Ping @jf-viguier @LouisAUTHIE

2024-11-27 12:15 UTC, SharakPL approved these changes

2024-11-27 12:19 UTC, ShaiMagal approved these changes
I think all clients would welcome this change 👍

2024-11-27 12:33 UTC, kpodemski requested changes, later dismissed
I haven't checked it yet because of a lack of time, but I think such a last-minute change should be approved by @ibahloul-ps first 👍🏻 I'm blocking it so it doesn't get merged accidentally.

2024-11-29 10:05 UTC, ibahloul-ps commented
Hello @Hlavtox 
Thanks for your contribution!

1 =>  it's a personal opinion, but I think our product designers should remain responsible of the UI and the UX or the BO 👍 
2 et 3 => I would like to understand what's the problem you're trying to solve before adding a new block because I can see that there's a looooot of information and CTA on this page. Your clients think there's too much information? and that the important ones aren't visible?
4 et 6 => I agree, the links aren't visible, but it seems to me that it's not a best practice to have too many CTAs on the same page either 🤷 
5 =>  It seems a relevant information to display, but from what I understand, there are several ref for a product. Shouldn't we let the merchant choose which one to display?
7 => what confuses them? we could change the placeholder as well 👍

2024-11-29 10:24 UTC, Hlavtox commented
@ibahloul-ps 

> 1 => it's a personal opinion, but I think our product designers should remain responsible of the UI and the UX or the BO 👍

Well, having one sentence in 4 different fonts, colors and widths is really a prime example of amazing design. 🤣 It's also a personal opinion, but many of the pages are completely unusable in real life, and all of my clients say this before I made at least basic changes to my shops.

> 2 et 3 => I would like to understand what's the problem you're trying to solve before adding a new block because I can see that there's a looooot of information and CTA on this page. Your clients think there's too much information? and that the important ones aren't visible?

Yes, it's a basic overview of the order. Right now, you can't see method of payment, you can't see the cart that was used. Plus, it contains the data from the header in a readable format.

> 4 et 6 => I agree, the links aren't visible, but it seems to me that it's not a best practice to have too many CTAs on the same page either 🤷

Working with orders and ecommerce brings MANY actions to do. And it must be clearly seen what is clickable or not. Right now, there is a button which is not underlined and not looking like a button. Put it to google web vitals and it will complain about it's accesibility.

> 5 => It seems a relevant information to display, but from what I understand, there are several ref for a product. Shouldn't we let the merchant choose which one to display?

The employeees must see maximmum product identifiers to fulfil the order. See our packing interface for our warehouse workers. Sometime you use the product reference, sometimes you need to check the MPN or EAN on the packaging.

![Snímek obrazovky 2024-11-29 112231](https://github.com/user-attachments/assets/5b446b05-af42-475c-84ad-947576c92f09)

> 7 => what confuses them? we could change the placeholder as well 👍

It went exactly this way:
"Guys what do you think about the new look after upgrade, all good?"
"I don't want to feel like an old person hating changes, but right now it's slowing us down. Everything is in different place, we are searching for things, you don't know what private note is for customer, what is for order. Just weird"

2024-12-02 09:42 UTC, FabienPapet commented
Nice work @Hlavtox , 

Some suggestions: 

- I'd remove the customer id and put it next to the customer name in the previous section
- I'd also merge the custimer information block with the previous one, makes more sense to me

2024-12-02 09:46 UTC, FabienPapet commented on src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/basic_information.html.twig
> +    <h3 class="card-header-title">
This cause double margin
IIRC, there is a default margin inside the card-header, no need to have an extra one

2024-12-03 13:19 UTC, ibahloul-ps approved these changes

2024-12-04 09:06 UTC, FabienPapet approved these changes

2024-12-04 15:40 UTC, florine2623 commented
Some checks were not successful, could you check @Hlavtox ? :)

2024-12-04 15:44 UTC, Hlavtox commented
@florine2623 False alarm, rerunning. :-) Should be good now.

2024-12-05 13:11 UTC, florine2623 reviewed
Hello @Hlavtox ! Thanks for the details.

Here are my 3 requests : 

- I have an issue on the UX, the button View details is not at the right place :

<img width="1440" alt="Screenshot 2024-12-05 at 14 06 23" src="https://github.com/user-attachments/assets/71242ec6-ec17-46db-8c54-00cf69b1c2c5">

- Also, it seems like you have not taken into account the following comment : https://github.com/PrestaShop/PrestaShop/pull/37482#issuecomment-2511035317

- And I need to make sure @ibahloul-ps has approved it by putting the label PM ✅ on the PR ^^

Waiting for those elements to be checked before retesting the PR ^^

Thanks!

2024-12-05 13:21 UTC, Hlavtox commented
@florine2623 

> I have an issue on the UX, the button View details is not at the right place :

Well, your screen is too small, that's why it goes to a second line. :-)

> Also, it seems like you have not taken into account the following comment : https://github.com/PrestaShop/PrestaShop/pull/37482#issuecomment-2511035317

I did, but chose not to implement them. I like it better this way.

> And I need to make sure @ibahloul-ps has approved it by putting the label PM ✅ on the PR ^^

He approved, we talked about it. cc @ibahloul-ps

2024-12-05 13:32 UTC, florine2623 commented
My screen is very very small then x) to have it I had to hide the menu and de-zoom my browser 😅 
<img width="1440" alt="Screenshot 2024-12-05 at 14 31 18" src="https://github.com/user-attachments/assets/ce7a6313-7386-4a83-bba8-9fdbcdbad356">

2024-12-05 13:36 UTC, Hlavtox commented
@florine2623 I can improve everything in another PR, make the gap between two columns smaller, move the button, add icons, whatever. But I need to be sure I am not wasting time and it won't be declined because it doesn't align with a vision of how a designer woke up one morning. :D

2024-12-05 13:36 UTC, merged