Add idShop cache value for getLinkRewrite Category and Category CMS
PrestaShop/PrestaShop pull request #37496
Opened 2024-11-27 04:34 UTC by Touxten

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | Category link cache doesn't take shopId as a parameter
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See issue
| Fixed issue or discussion?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/36794
| Sponsor company   | @friends-of-presta

2024-11-27 05:41 UTC, Hlavtox commented
CS fixer will 100% fail, after you fix it, I will approve. Good job. :-)

2024-11-27 06:48 UTC, Touxten commented
Done @Hlavtox

2024-11-27 07:24 UTC, Hlavtox approved these changes, later dismissed
Thanks @Touxten!

2024-11-28 12:46 UTC, StoreCommanderDev reviewed
I think there are some little optimizations todo :)

2024-11-28 12:46 UTC, StoreCommanderDev commented on classes/CMSCategory.php
>          $result = Db::getInstance()->getRow('
Why using getRow for only one value ? (even if it was always like that before)

`$linkRewrite = Db::getInstance()->getValue`

2024-11-28 12:46 UTC, StoreCommanderDev commented on classes/CMSCategory.php
> +        self::$_links[$idCMSCategory . '-' . $idLang . '-' . $idShop] = $result['link_rewrite'];
`self::$_links[$idCMSCategory . '-' . $idLang . '-' . $idShop] = $linkRewrite;`

2024-11-28 12:46 UTC, StoreCommanderDev commented on classes/CMSCategory.php
>          return $result['link_rewrite'];
return $linkRewrite;

2024-11-28 12:46 UTC, StoreCommanderDev commented on classes/CMSCategory.php
> +     * @return bool|mixed
sql will return false or string. So function must return bool or string

`* @return bool|string`

2024-11-28 12:48 UTC, StoreCommanderDev commented on classes/Category.php
>       * @return bool|mixed
Same here. bool|string

2024-11-28 12:48 UTC, StoreCommanderDev commented on classes/Category.php
> +        return self::$_links[$idCategory . '-' . $idLang . '-' . $idShop];
I think the code style of this function can be used on CMScategory file

2024-11-30 11:12 UTC, Hlavtox submitted a review, later dismissed
LGTM, restart the webkit tests, they fail like every time... sometimes I have to restart them even 5 times :-)))

2024-11-30 12:46 UTC, LouisAUTHIE submitted a review, later dismissed
Nice one !

2024-11-30 15:46 UTC, Touxten commented
@Hlavtox i can't restart test only pepople in https://github.com/PrestaShop

Regards 

![Screenshot (20)](https://github.com/user-attachments/assets/38b38d2c-71c3-45ea-9423-ed35a6c48252)

2024-11-30 17:05 UTC, Touxten commented
@kpodemski like ping commiter

2024-12-02 12:23 UTC, florine2623 reviewed
Hello @Touxten ,

I can't reproduce the issue as you can see from my answer here : https://github.com/PrestaShop/PrestaShop/issues/36794#issuecomment-2511394472

As the issue can't be reproduced, I cannot validate the PR.

2024-12-02 12:41 UTC, Touxten commented
Hello @florine2623 

It's not easy to test, as it will depend on the store and options.
@matks @kpodemski @Hlavtox what do you think ?
For your tests you should add the cache.

2024-12-02 12:50 UTC, FabienPapet commented on classes/CMSCategory.php
> +     * @param int $idShop Shop ID
```suggestion
     * @param int|null $idShop Shop ID
```

2024-12-02 12:50 UTC, FabienPapet commented on classes/Category.php
> +     * @param int $idShop Shop ID
```suggestion
     * @param int|null $idShop Shop ID
```

2024-12-05 11:06 UTC, florine2623 reviewed
Hello all,

I have relaunched the auto tests after latest edits : https://github.com/florine2623/testing_pr/actions/runs/12178457924 ✅ 

Can I get approvals before testing the PR please ?
Also, some checks were not successful, could you check @Touxten ?

Thanks!

2024-12-06 09:02 UTC, Touxten commented
@florine2623 i think you can restart the test for me it's impossible :'(

2024-12-06 11:33 UTC, SharakPL commented
@Touxten tests still failing

2024-12-06 11:34 UTC, kpodemski commented
@SharakPL you can restart the tests, you have the rights to do it, those are only false-positives

2024-12-06 11:36 UTC, SharakPL commented
I know @kpodemski and I did restart it. Still ended up failing.

2024-12-06 11:40 UTC, kpodemski requested changes
Hello @Touxten 

You can simplify the code a bit, no need to cast to `(int)` if you validated inputs already, etc.

Please adjust the other method as well 👍🏻 

I see that the issue hasn't been validated, but I understand the need for this change from the code point of view.

2024-12-06 11:40 UTC, kpodemski commented on classes/CMSCategory.php
> +    public static function getLinkRewrite($idCMSCategory, $idLang, $idShop = null)
```suggestion
    public static function getLinkRewrite($idCMSCategory, $idLang, ?int $idShop = null)
```

2024-12-06 11:40 UTC, kpodemski commented on classes/CMSCategory.php
>          }
```suggestion
        $idShop = $idShop ?? Context::getContext()->shop->id;
```

2024-12-06 11:40 UTC, kpodemski commented on classes/CMSCategory.php
> +    		' . Shop::addSqlRestrictionOnLang(null, (int) $idShop) . '
```suggestion
    		' . Shop::addSqlRestrictionOnLang(null, $idShop) . '
```

2024-12-06 11:40 UTC, kpodemski commented on classes/CMSCategory.php
> +    		AND `id_cms_category` = ' . (int) $idCMSCategory);
```suggestion
    		AND `id_cms_category` = ' . $idCMSCategory);
```

2025-06-27 07:17 UTC, Touxten commented
New PR https://github.com/PrestaShop/PrestaShop/pull/39016

2025-06-27 07:17 UTC, closed without merging