Do not populated Features Form with custom values
PrestaShop/PrestaShop pull request #37577
Opened 2024-12-05 06:25 UTC by Touxten

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.2.x
| Description?      | In product Page v2, the Pre-defined feature values are populated with custom values associated with other products
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See issue
| UI Tests          | Please run UI tests and paste here the link to the run. As we support MySQL and MariaDB in our tests, you have to launch 2 campaigns (by choosing both). [Visit the UI Tests repo and follow instructions](https://github.com/PrestaShop/ga.tests.ui.pr/).
| Fixed issue or discussion?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/37543
| Sponsor company   | @friends-of-presta

2024-12-09 10:12 UTC, jolelievre approved these changes

2024-12-09 10:46 UTC, jolelievre requested changes
Thanks @Touxten 

Ac actually I didn't see the integration tests are failing because of this change You also need to update the tests related to this listener in https://github.com/PrestaShop/PrestaShop/blob/8.2.x/tests/Integration/PrestaShopBundle/Form/Admin/Sell/Product/EventListener/FeatureValueListenerTest.php

Be sure that this modification doesn't create other bugs because the select won't have the expected choices correctly updated including the custom value ID that will not be in the allowed choices

2025-02-07 10:50 UTC, Prestaplugins commented
Incredible, my product page v2 was loading in around 30 seconds, due to a large number of features with custom values, it's now loading immediately !!
Thanks a lot @Touxten

2025-07-25 10:14 UTC, Touxten commented
No more support for 8.2 i close the PR

2025-07-25 10:14 UTC, closed without merging