[feat] Add hook to customize ajax refreshed data on product page
PrestaShop/PrestaShop pull request #37596
Opened 2024-12-06 09:07 UTC by web-cooking-factory

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Adds a hook to add custom data in ajax refreshed data on the product page
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Install the test module, go to a product page with combinations, open console > Network, filter by Fetch/XHR, change an attribute in the product page, locate the ajax request, the response should include evo_actionproductcontrollerajaxrefresh data (lorem 
[evo_actionproductcontrollerajaxrefresh.zip](https://github.com/user-attachments/files/18035497/evo_actionproductcontrollerajaxrefresh.zip)
![hook](https://github.com/user-attachments/assets/69466353-2117-4dad-af63-47df791e047b)
> ipsum)
| UI Tests          | (https://github.com/PrestaShop/ga.tests.ui.pr/).
| Fixed issue or discussion?     | https://github.com/PrestaShop/PrestaShop/discussions/37595
| Related PRs       | 
| Sponsor company   | Evolutive

2024-12-06 09:23 UTC, PululuK submitted a review, later dismissed

2024-12-06 09:51 UTC, Hlavtox requested changes
There is a hook for years that serves this purpose:

Hook::exec('actionAjaxDie' . $controller . $method . 'Before', ['value' => &$value]);

2024-12-06 10:20 UTC, web-cooking-factory commented
> There is a hook for years that serves this purpose:
> 
> Hook::exec('actionAjaxDie' . $controller . $method . 'Before', ['value' => &$value]);

Yeah, like said in the related discussion, this hook seems kinda low level. And it doesn't send the product.

2024-12-06 10:55 UTC, SharakPL commented
@web-cooking-factory could you share an example of usage of this hook? What data would you like to add to a product page on ajax refresh? Just wondering...

2024-12-06 11:18 UTC, web-cooking-factory commented
> @web-cooking-factory could you share an example of usage of this hook? What data would you like to add to a product page on ajax refresh? Just wondering...

Any data you could add directly to the tpl ^^ Especially data depending on an combination. A simple use case: you want to put the product reference (which is combination dependent) at the top of the page, not inside a js-* block (refreshed by ajax) because you can't for any reason.

2024-12-06 13:31 UTC, ps-jarvis commented
<!-- PR_WORDING -->
This pull request seems to contain new translation strings. I have summarized them below to ease up review:

- `Admin.Notifications.Error`
    - [ ] `Link to database cannot be established: %s`
    - [ ] `PrestaShop Fatal error: no utf-8 support. Please check your server configuration.`
    - [ ] `Graph module could not be loaded.`
    - [ ] `Grid module could not be loaded.`

(Note: this is an automated message, but answering it will reach a real human)

2025-01-20 13:50 UTC, jolelievre commented on controllers/front/ProductController.php
> +        }
I don't understand why you need this? since you pass the data by reference the module hook should modify it directly no?

2025-02-27 08:31 UTC, jolelievre commented on controllers/front/ProductController.php
> +        }
@web-cooking-factory still no answer for this question, can you please give use more details or this PR status won't change

2025-04-08 10:11 UTC, kpodemski requested changes
Hello @web-cooking-factory 

In order to continue with this pull request, we will need your answer to the question from Jonathan.

2025-04-15 06:54 UTC, kpodemski commented
Hello @web-cooking-factory 

yet another reminder

2025-04-25 15:11 UTC, kpodemski commented
Hello @web-cooking-factory 

Since we haven't had any news from you for a long time, I am closing this pull request. You are free to reopen it and continue working on your contribution. If you have any questions, let me now.

2025-04-25 15:11 UTC, closed without merging