Nicohery patch tinymce
PrestaShop/PrestaShop pull request #37590
Opened 2024-12-05 16:56 UTC by nicohery

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | Fix tinymce fullscreen plugin. Increase z-index and disable max-height to display the editor above the header and nav-bar.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Enable the tinymce fullscreen plugin. The tinymce editor is now displayed above the header and the nav-bar. cf #37588 
| UI Tests          | 
| Fixed issue or discussion?     | Fixes #37588
| Related PRs       | 
| Sponsor company   | @friends-of-presta

2024-12-05 16:56 UTC, ps-jarvis commented
<!-- PR_WELCOME -->
Hello @nicohery!

This is your first pull request on [PrestaShop](https://github.com/PrestaShop/PrestaShop/) repository of the PrestaShop project.

Thank you, and welcome to this Open Source community!

2024-12-05 16:56 UTC, ps-jarvis commented
<!-- PR_WORDING -->
This pull request seems to contain new translation strings. I have summarized them below to ease up review:

- `Admin.Notifications.Error`
    - [ ] `Link to database cannot be established: %s`
    - [ ] `PrestaShop Fatal error: no utf-8 support. Please check your server configuration.`
    - [ ] `Graph module could not be loaded.`
    - [ ] `Grid module could not be loaded.`

(Note: this is an automated message, but answering it will reach a real human)

2024-12-05 17:33 UTC, nicosomb requested changes
You source branch seems to be not up to date.

2024-12-06 21:15 UTC, nicosomb approved these changes, later dismissed

2024-12-06 21:22 UTC, kpodemski approved these changes

2024-12-08 00:47 UTC, kpodemski requested changes
Hello @nicohery 

Please see the details of reported errors in our CI, the one related to linting SCSS files. You have to adjust the coding style.

2025-07-17 04:11 UTC, cnnewin commented
`.mce-fullscreen {
  z-index: 1100;
  height: 100%;
  padding: 0;
  margin: 0;
  overflow: hidden;
  background: white; /* Replaced $white with its CSS equivalent */
  border: 0;
}

.mce-fullscreen .mce-edit-area {
  max-height: inherit !important;
}`
Prestashop9.0 product editor can achieve full screen according to the above modifications, but there is no slider for overflow content, but the cursor can move downward to display the overflow content. How to modify it?

2025-07-18 09:36 UTC, jf-viguier commented on admin-dev/themes/new-theme/scss/components/_tinymce.scss
> +  .mce-edit-area{
```suggestion
  .mce-edit-area {
```

2025-07-18 09:55 UTC, jf-viguier commented
@kpodemski can you relaunch CICD please ? I think i've found the bug

2025-08-20 12:12 UTC, kpodemski submitted a review, later dismissed

2025-08-20 12:33 UTC, Touxten submitted a review, later dismissed

2025-08-20 13:10 UTC, kpodemski approved these changes, later dismissed

2025-08-20 13:10 UTC, kpodemski commented
@Touxten I fixed one issue with Eslint in the meantime

2025-08-20 13:15 UTC, Touxten submitted a review, later dismissed

2025-08-20 13:25 UTC, Touxten commented
I wait CI this time

2025-08-20 13:26 UTC, kpodemski approved these changes

2025-08-20 14:00 UTC, Touxten approved these changes

2025-08-21 15:16 UTC, SiraDIOP reviewed
qa by dev

2025-08-22 06:27 UTC, Touxten commented
Hello,

It's ok for me.

[screen-capture (3).webm](https://github.com/user-attachments/assets/4ba1cb14-c924-43e5-a6ba-6a1a9e821089)

2025-08-22 08:00 UTC, merged

2025-09-10 14:46 UTC, cnnewin commented
> Hello, @Touxten @jf-viguier 
> 
> It's ok for me.
> 
>  screen-capture.3.webm

My PrestaShop 9.0 installation doesn't have admin-dev/themes/new-theme/scss/components/_tinymce.scss, but rather admin-dev/themes/new-theme/public/theme.css.

This CSS configuration enables full-screen viewing. While short content appears to display normally, long content overflows without a scrollbar.

I haven't resolved this issue yet.

2025-09-10 14:58 UTC, Touxten commented
Hey @cnnewin

This is normal. At the moment, there is no new version of version 9.0.x. You can fix the problem yourself or wait for a new version.