Functional Tests : Audit - BO - Payment
PrestaShop/PrestaShop pull request #37619
Opened 2024-12-09 16:37 UTC by florine2623

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Functional Tests : Audit - BO - Payment
| Type?             | improvement
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI is :green_circle: 
| UI Tests          | :dolphin: : <br/>:seal: :
| Fixed issue or discussion?     | N/A
| Related PRs       | N/A
| Sponsor company   | @PrestaShopCorp

2024-12-09 16:39 UTC, Progi1984 commented on tests/UI/campaigns/audit/BO/10_payment.ts
> +describe('BO - Payment methods', async () => {
```suggestion
describe('BO - Payment', async () => {
```

2024-12-09 16:40 UTC, Progi1984 commented on tests/UI/campaigns/audit/BO/10_payment.ts
> +      it('should go to \'Preferences\' page', async function () {
```suggestion
      it('should go to \'Payment > Preferences\' page', async function () {
```

2024-12-09 16:40 UTC, Progi1984 commented on tests/UI/campaigns/audit/BO/10_payment.ts
> +        await testContext.addContextItem(this, 'testIdentifier', 'goToPaymentMethodsPage', baseContext);
```suggestion
        await testContext.addContextItem(this, 'testIdentifier', 'goToPaymentPreferencesPage', baseContext);
```

2024-12-09 16:40 UTC, Progi1984 commented on tests/UI/campaigns/audit/BO/10_payment.ts
> +});
```suggestion
});

```

2024-12-09 16:40 UTC, Progi1984 commented on tests/UI/campaigns/audit/BO/10_payment.ts
> +
```suggestion
```

2024-12-09 16:40 UTC, Progi1984 requested changes
Some feedbacks

2024-12-09 17:01 UTC, Progi1984 submitted a review, later dismissed

2024-12-09 19:13 UTC, nesrineabdmouleh commented
Please fix eslint errors

2024-12-10 09:16 UTC, Progi1984 approved these changes

2024-12-11 09:16 UTC, nesrineabdmouleh approved these changes

2024-12-11 09:18 UTC, merged