Fix issue with count on string
PrestaShop/PrestaShop pull request #37641
Opened 2024-12-11 09:50 UTC by pszostok

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop, 9.0.x, 8.2.x
| Description?      | In this [commit](https://github.com/PrestaShop/PrestaShop/commit/d3729d73e76cfbcd8a286f01c24e1a8eb4e7aeda), we addressed an issue where `attributes` could sometimes be a string instead of an array. This caused problems because, in the `ProductListingLazyArray`, we were treating `attributes` as if it were always an array. This led to a `TypeError`. To make the code more robust, we replaced `count() > 0` with `empty()`. However, we first need to understand why `attributes` is sometimes an array and other times a string. From what I can tell, the issue stems from the caching mechanism in `Product.php`, specifically in the `getProductProperties` function. Here, `$row` is cached regardless of whether `attributes` is a string or an array. In the `FrontController`, the `assignGeneralPurposeVariables` function sends `$cart` to the cart presenter. In turn, the presenter’s `applyProductCalculations` function sets `attributes` as a string. This works correctly because the `FrontController` and view templates don’t seem to call functions in the `ProductListingLazyArray`. However, when the `getProductProperties` function is called again, the cached version of `$row` is returned, and `attributes` remains a string (since the cache key hasn’t changed). This suggests that the root cause of this issue lies deeper and should be addressed at its source. Nonetheless, this fix should still be applied to ensure the `ProductListingLazyArray.php` handles cases where `attributes` is a string. 
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Run the cart presenter with a product in it (adding a product to the cart should suffice). After that, run the ProductPresenter with the same product, so it will be retrieved directly from the cache. This behavior can be observed, for example, in the [ets_crossell](https://addons.prestashop.com/en/cross-selling-product-bundles/28596-cross-selling-pro-upsell-shopping-cart-all-pages.html) module. In the module controller, this occurs in the `productsForTemplate` function.
| UI Tests          | Please run UI tests and paste here the link to the run. As we support MySQL and MariaDB in our tests, you have to launch 2 campaigns (by choosing both). [Visit the UI Tests repo and follow instructions](https://github.com/PrestaShop/ga.tests.ui.pr/).
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   |

2024-12-11 09:50 UTC, ps-jarvis commented
<!-- PR_TABLE_DESCRIPTION_ERROR -->
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `branch` should be `develop`, `9.0.x` or `8.2.x`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!
### About linked issues
Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

2024-12-11 09:50 UTC, ps-jarvis commented
<!-- PR_WELCOME -->
Hello @pszostok!

This is your first pull request on [PrestaShop](https://github.com/PrestaShop/PrestaShop/) repository of the PrestaShop project.

Thank you, and welcome to this Open Source community!

2024-12-11 10:38 UTC, Hlavtox approved these changes, later dismissed

2024-12-11 10:39 UTC, Hlavtox commented
@pszostok You are right, see my comment here - https://github.com/PrestaShop/PrestaShop/blob/3c99e86a7ab78c7814fd31c624b01ba09fff9ac4/src/Adapter/Presenter/Product/ProductLazyArray.php#L696

It's a bit weird to have to different data structures, but it's a historic thing, will be fixed some day.

Your fix is valid. :-)

2024-12-12 14:38 UTC, nicosomb commented
@pszostok if this bug is present in 8.2 (as you said in your post), could you please target the 8.2 branch?

2025-01-07 11:10 UTC, kpodemski requested changes
Hello @pszostok 

A little reminder that this change has to target `8.2.x` branch, if you cannot rebase your PR, you can create a new one targeting `8.2.x` branch.

2025-01-17 13:49 UTC, pszostok commented
@kpodemski @nicosomb 
Sorry for late response. I've created separate PR for [8.2.x](https://github.com/PrestaShop/PrestaShop/pull/37849)

2025-08-15 15:47 UTC, Touxten commented
Il close this Pr; a new one in favor https://github.com/PrestaShop/PrestaShop/pull/37849

2025-08-15 15:47 UTC, closed without merging