Apply backoffice optimizations
PrestaShop/PrestaShop pull request #37667
Opened 2024-12-14 16:01 UTC by Hlavtox

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | These are some minor styling changes after discussion with @kpodemski, mostly only optimizes spacing. Read below.
| Type?             | refacto
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See if nothing is out of ordinary in backoffice.
| UI Tests          | 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   |

### Changes
- Optimized spacing of cards, card headers, card footers.
- Fixed wrong classes here and there, margin tops, margin bottoms, some extra margins of last elements in a card.
- Optimized spacing of grid rows.
- Refactored the terrible source list on order page into a table.
- Added icons to order page cards to be consistent with customer detail.
- On customer page, modified the basic info block slightly to be more consistent.
- Brought back the customer name in order header, but in the same font, after discussion with Krystian.

### How does it look
Customer page
![before_customer](https://github.com/user-attachments/assets/8117892c-cabb-452b-8cc0-5b6410a64d39)
![after_customer](https://github.com/user-attachments/assets/dcdab428-34ab-455c-a186-77a5ff59f590)

Order page
![before_order_1](https://github.com/user-attachments/assets/93faa12a-c7a9-470d-8115-d816099837b6)
![after_order_1](https://github.com/user-attachments/assets/6108f504-f9a2-4f23-810e-115045e42e02)
![before_order_2](https://github.com/user-attachments/assets/67374994-fe69-45cb-b8cb-a6433352fbaa)
![after_order_2](https://github.com/user-attachments/assets/cfb94802-b635-4dee-9212-1c13d747b6bb)

Product list
![before_product](https://github.com/user-attachments/assets/180b8ad6-cee9-4ac4-a5fe-ba829b635a20)
![after_product](https://github.com/user-attachments/assets/5f0becd6-af74-48e6-9f50-977d852ddd97)

2024-12-14 16:01 UTC, ps-jarvis commented
<!-- PR_WORDING -->
This pull request seems to contain new translation strings. I have summarized them below to ease up review:

- `Admin.Global`
    - [ ] `Basic information`
    - [ ] `ID:`

(Note: this is an automated message, but answering it will reach a real human)

2024-12-16 10:10 UTC, kpodemski commented
Thank you Daniel. Make sure to add "Before", "After" above your screenshots, or focus only how it is "now", because you showed the look of the old order page on one screenshot.

# Order page

https://www.dropbox.com/s/qlnno04g8zggdmo/Zrzut%20ekranu%202024-12-16%20o%2011.04.01.png?dl=0

I’m still unsure about this part, there is so much space left there. 

Also, I think it would be good to add [max-height to the wrapper](https://www.dropbox.com/s/m6syq2jx1qavjks/Zrzut%20ekranu%202024-12-16%20o%2011.08.01.png?dl=0) for the sources, so the table is not that high, especially if there's a lot of connection sources like on this example.

[This part](https://www.dropbox.com/s/hhozrixhhkn3cp4/Zrzut%20ekranu%202024-12-16%20o%2011.07.18.png?dl=0) looks like there's some double margin somewhere.

Also, it would be good to see what @prestascott thinks about those changes. I think the idea of having a more compact BO is a good idea, everything has a lot of spacing but it doesn't make it more readable 🤷🏻‍♂️

2024-12-16 11:14 UTC, Hlavtox commented
@kpodemski Thanks! :-)

The space on the cards with tables is mostly caused by both header and body having a padding, which wasn't a problem when the header was separated, but is more visible now. I think the first card-body of each card could have it's padding top reduced.

The sources are the last element of the page, so I just made it a table for now, but yeah, we can do overflow-y: auto and a max height. :-)

I did not change anything on the product grid width-wise, it must be some styling currently there. Or, my screen is just wide, so it auto-adjusts things.

2024-12-16 14:53 UTC, Hlavtox commented
@kpodemski Regarding the whitespace on the basic information block, I don't know how to help you, sorry. :D

On 13" MBP, you complain that it jumps to mobile view, on my 27" screen, you complain that there is too much white space. :D

2025-01-03 16:51 UTC, Hlavtox commented
Ping @kpodemski

2025-02-21 12:03 UTC, Hlavtox commented
OK, let's try to see. @tblivet @kpodemski guys can you check again? :-)

2025-02-24 13:12 UTC, tblivet requested changes
Hi @Hlavtox 👋 thank you for the PR.
- To maintain consistency with the rest, I think we should use `var(--#{$cdk}size-xx)` wherever we apply size or spacing.
- These modifications (cards/grids) should also be applied to the BO theme "default," as there are still some pages using this theme, and we want to make both themes as similar as possible in terms of look.

2025-02-24 13:12 UTC, tblivet commented on admin-dev/themes/new-theme/scss/components/_grid.scss
> +  padding-bottom: var(--cdk-size-8);
```suggestion
  padding-block: var(--#{$cdk}size-8);
```

2025-02-24 13:12 UTC, tblivet commented on admin-dev/themes/new-theme/scss/components/_grid.scss
> +        padding: .2rem;
```suggestion
        padding: var(--#{$cdk}size-4);
```

2025-02-24 13:12 UTC, tblivet commented on admin-dev/themes/new-theme/scss/components/_grid.scss
> +        padding: .2rem;
Avoid using **rem** values that result in decimal pixel equivalents, e.g., 0.2rem = 3.2px.

2025-03-10 08:26 UTC, tblivet submitted a review, later dismissed

2025-05-12 09:12 UTC, Betafer commented
Thanks for this optimizations !

2025-06-24 12:10 UTC, ShaiMagal approved these changes, later dismissed

2025-06-24 13:04 UTC, kpodemski requested changes
CI is 🔴 

I'm also pinging @ibahloul-ps so he can validate UX, himself or with the help of @PrestaShop/ux-team

2025-06-24 13:20 UTC, Hlavtox commented
@kpodemski Can somebody who actually uses the software validate it instead?

2025-06-25 09:19 UTC, Hlavtox commented
@tblivet Hi, please, do you know some variables I can use instead of 1rem? How to adapt the card spacer variables?

2025-06-30 07:45 UTC, ShaiMagal approved these changes, later dismissed

2025-07-07 09:04 UTC, tblivet commented
> @tblivet Hi, please, do you know some variables I can use instead of 1rem? How to adapt the card spacer variables?

Hi @Hlavtox, you can find here all the CSS variables defined in the BO if this is what you were looking for ?
https://github.com/PrestaShop/prestashop-ui-kit/blob/1c255d96d79c69e2d3e0dd1712f76379941c06bb/scss/_root.scss#L74

2025-10-30 11:32 UTC, kpodemski commented
@Hlavtox could you address @tblivet suggestions? I think this still can be incorporated to the patch version

2025-10-31 13:17 UTC, Hlavtox commented
@kpodemski @tblivet Should be ready guys! :-)

2025-10-31 13:21 UTC, kpodemski approved these changes

2025-11-01 18:27 UTC, Codencode approved these changes

2025-11-03 13:33 UTC, tblivet approved these changes
👍

2025-11-03 15:46 UTC, boherm approved these changes

2025-11-03 20:36 UTC, ibahloul-ps commented
> CI is 🔴
> 
> I'm also pinging @ibahloul-ps so he can validate UX, himself or with the help of @PrestaShop/ux-team

Hello guys,

I have no expertise in UI.
PrestaShop designers design interfaces. If you think that this degrades the UX to such an extent that hte changes you propose need to be made, I have no opinion.

However, if you have any information about merchants who do not use PrestaShop (or no longer use it) because of the new UI, I would be interested to hear their feedback!

2025-11-03 21:57 UTC, Hlavtox commented
@ibahloul-ps Yes, it is, I’m afraid. It would be enough if your designers actually tried to use the software with the UX they created. We can start by removing basically all colors from the back office.

**And it’s not only my POV. Let’s ask ChatGPT. Clean thread, neutral question:**

> Is it a good idea for a primary color of (buttons etc.) an ecommerce administration to be black?

**Reply:**

> Good question — and the short answer is: usually not, unless you’re intentionally going for a very specific aesthetic.
> 
> Here’s a breakdown of why:
> 
> 🧠 Usability and UX
> - Black buttons have low affordance — they don’t look “clickable” unless paired with strong contrast (e.g. white text, shadow, or hover animation).
> - In admin panels, you want clear visual hierarchy: actions (e.g. Save, Delete, Publish) should stand out from neutral UI elements. Black tends to flatten everything visually.
> - Accessibility: Black on white is fine for contrast, but black as a background with white text can cause visual strain, especially with dense admin screens used for long periods.
> 
> 🎨 Design and Aesthetics
> - Black can look elegant and minimal, but it often feels heavy and aggressive for admin UIs, which are supposed to feel light and efficient.
> - Most modern admin interfaces use:
> - A primary color (blue, teal, or green) for key actions
> - Neutral grays for backgrounds and borders
> - Accent colors for status or feedback (red for errors, green for success)
> 
> ⚙️ When black can work
> - If you still want a dark, high-end look:
> - Use a dark theme overall (black or charcoal backgrounds with white/gray text).
> - Use white or bright accent colors (e.g. cyan, orange) as the primary color for buttons.
> - Or, keep black only for secondary buttons or icons, not the main call-to-action.
> 
> ✅ Better Alternatives
> - Blue (#007bff, #0d6efd, etc.) – standard, familiar, and safe.
> - Green (#28a745, #22c55e) – good for “confirm” or “save.”
> - Charcoal/dark gray works as a secondary or neutral color without the harshness of true black.

💡 Guess what color Prestashop used for years before?

Then we’re fighting with the lack of usable space in the back office. Unless you’re on at least 2560×1440, even basic listings don’t fit the screen and remain non-responsive. And somehow, the 9.0 “improvement” is to make everything larger. Impressive direction.

To be fair, @tblivet did an amazing job on consistency and cleaning up tons of visual glitches, bugs, and CSS nonsense that had piled up over the years — that deserves real credit. :-)

2025-11-17 18:31 UTC, Hlavtox commented
Ping @SiraDIOP for QA 🙏

2025-11-18 11:19 UTC, Betafer commented
> Then we’re fighting with the lack of usable space in the back office. Unless you’re on at least 2560×1440, even basic listings don’t fit the screen and remain non-responsive. And somehow, the 9.0 “improvement” is to make everything larger. Impressive direction.

👏 
same problem with 4k and 5k Imacs

2025-11-21 09:03 UTC, SiraDIOP reviewed
Hello @Hlavtox, 

Thanks for your PR, The automated tests are red. I have restarted them several times, but they are still red. Could you take a look? https://github.com/SiraDIOP/ga.tests.ui.pr/actions/runs/19495922552


Thanks

2025-11-21 10:23 UTC, kpodemski commented
Maybe @Progi1984 could take a look because changes from this PR don't seem to be impactful for the failing tests 🤔

2025-11-21 13:34 UTC, Hlavtox commented
Hello @SiraDIOP, not related I think. :-)

2025-11-24 08:39 UTC, tleon approved these changes

2025-11-24 09:31 UTC, SiraDIOP reviewed
Hello @Hlavtox ,
<img width="1901" height="930" alt="Capture d’écran 2025-11-24 à 10 23 22" src="https://github.com/user-attachments/assets/7685bde9-92bc-4eaf-a6e1-5bbc999d18f7" />
<img width="1903" height="939" alt="Capture d’écran 2025-11-24 à 10 23 51" src="https://github.com/user-attachments/assets/8dce4c3d-522f-4058-9903-2199aa4d778d" />
<img width="1906" height="932" alt="Capture d’écran 2025-11-24 à 10 24 15" src="https://github.com/user-attachments/assets/b9f04f21-536f-4d68-ba39-f89a5f200bc9" />
<img width="1913" height="890" alt="Capture d’écran 2025-11-24 à 10 25 03" src="https://github.com/user-attachments/assets/0e034b47-e888-498b-8716-ce77091f6024" />


There is an issue with the automated tests https://github.com/SiraDIOP/ga.tests.ui.pr/actions/runs/19495922552, so I will not be able to validate the PR.

I have discussed this with @Progi1984 , and he will look into it, but given his schedule, it will not be included in **release 9.0.2**.

Thank you for your understanding.

FYI @Robin-Fischer-PS  and @Progi1984

2025-11-24 09:36 UTC, Hlavtox commented
@SiraDIOP @Robin-Fischer-PS @Progi1984

> I have discussed this with @Progi1984 , and he will look into it, but given his schedule, it will not be included in release 9.0.2.

I understand, but given that I am waiting for almost a year to merge this PR and 3 weeks waiting for QA, and given the PR works as it should, @Progi1984 could make his fixes after this is merged.

2025-11-26 12:21 UTC, Progi1984 commented
@Hlavtox Could you rebase your PR ? You have 191 commits behind the 9.0.x branch.
I will restart E2E Tests after that.

2025-11-26 12:50 UTC, Hlavtox commented
@Progi1984 Rebased thank you! :-)

2025-11-27 10:06 UTC, Progi1984 commented
@Hlavtox I understand why E2E Tests are :red_circle: (all :red_circle: have the same error).

It seems there is a problem with tooltip in grid.

<img width="1680" height="936" alt="fail_test_1" src="https://github.com/user-attachments/assets/5ef2f44b-b44c-48bd-85b4-0ef84e26812f" />
<img width="1680" height="900" alt="fail_test_1" src="https://github.com/user-attachments/assets/a71f4ca7-9c11-44c3-939f-96cf3d064a4e" />

2025-11-27 10:24 UTC, Hlavtox commented
@Progi1984 I don't understand what is the problem with the tooltip?

If there is a problem, it's a problem of tests, not mine. :-D

2025-11-27 10:37 UTC, Progi1984 commented
@Hlavtox I reproduce it in local, too (and without E2E Tests). My mouse is on an another position of the page. 

<img width="228" height="246" alt="image" src="https://github.com/user-attachments/assets/cb10d4db-30bb-4753-b66e-c66f1cadd84f" />

2025-11-27 22:46 UTC, Hlavtox commented
Ping @tblivet @ga-devfront guys, any idea what is happening with the labels? :-)

2025-11-28 08:33 UTC, tblivet commented
@Hlavtox I’ve tried, but I’m not able to reproduce it 😕

2025-11-28 09:02 UTC, Hlavtox commented
@tblivet Thank you, me neither.

@Progi1984 I can't reproduce it. Whatever I do, I have no tooltip displayed when it should not. Tried different resolutions, using keyboard only, using mouse. It works properly.

<img width="1021" height="613" alt="Snímek obrazovky 2025-11-28 100146" src="https://github.com/user-attachments/assets/0a909e77-12a7-4891-918c-2d599918e4fd" />

2025-12-01 15:46 UTC, Hlavtox commented
@PrestaShop/qa-automation
@PrestaShop/qa-functional
@PrestaShop/committers 

What should I do about this PR? I would like to get a PR with few padding changes merged after a year.

2025-12-02 20:58 UTC, kpodemski commented
@Hlavtox If @Progi1984 reproduced the issue best would be if he could let us know what browser he used and what to do to reproduce it, you can also try to rebase your PR and run the auto tests again - if there's an error on your PR only then something **is** wrong

2025-12-02 21:11 UTC, Hlavtox commented
@kpodemski I completely rebased it and it did not help. And both me and @tblivet cannot reproduce it. :-)

2025-12-02 21:37 UTC, kpodemski commented
then let's wait for @Progi1984 

he leads auto tests and we need his help

2025-12-25 18:34 UTC, Hlavtox commented
Ping @PrestaShop/qa-functional again 🙏

2025-12-31 12:20 UTC, Hlavtox commented
Pinging @PrestaShop/qa-automation last time, I will merge it next week

2025-12-31 12:28 UTC, kpodemski commented
@Hlavtox 

Daniel, most people are on vacation now, that's the first thing. The second thing is that the team's focus is on Beta for PrestaShop 9.1 and adjustments of the UI tests to Hummingbird. Be patient.

2025-12-31 12:39 UTC, Hlavtox commented
@kpodemski That's why I will merge it after some time at work. A year to merge a PR that reduces padding.

> The second thing is that the team's focus is on Beta for PrestaShop 9.1 and adjustments of the UI tests to Hummingbird. Be patient.

We still don't have usable 9.0, translations are fucked up but the team is focused on 9.1 beta - could not care less.

2025-12-31 12:42 UTC, kpodemski submitted a review, later dismissed
Blocking.

2025-12-31 16:06 UTC, ShaiMagal commented
@kpodemski @Progi1984 Openservis customers who already upgrade to 9.0 are complaining about this. :(

2026-01-05 09:48 UTC, Robin-Fischer-PS commented
Hi @Hlavtox (and everyone else),

I'll ask the @PrestaShop/qa-functional to test it this week, and we'll see if we can reproduce the E2E bug (@Progi1984 is not available now), we'll keep you updated as soon as we can about the result and what should be done after that.

Thanks for your patience :)

2026-01-06 14:36 UTC, SiraDIOP reviewed
Hello @Hlavtox, 

Thanks for your PR
I retested the ticket and cannot reproduce the bug, so QA is OK.

Thanks ^^

FYI @Robin-Fischer-PS

2026-01-06 14:49 UTC, merged

2026-01-06 14:49 UTC, Hlavtox commented
THANK YOU!!!