Refactored Hooks API
PrestaShop/PrestaShop pull request #37699
Opened 2024-12-19 09:31 UTC by nicosomb

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x 
| Description?      | Refactored Hooks API: delete hook-status endpoint and change /hooks/id to /hook/id
| Type?             | improvement 
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI is green
| UI Tests          | 
| Fixed issue or discussion?     | N/A
| Related PRs       | https://github.com/PrestaShop/ps_apiresources/pull/43
| Sponsor company   | PrestaShop SA

2024-12-19 09:56 UTC, Progi1984 commented on tests/UI/campaigns/functional/API/01_basicTest.ts
> -    it('should request the endpoint /hook-status', async function () {
Please replace hook-status by hooks

(We don't test the endpoint but the access)

2024-12-19 09:56 UTC, Progi1984 commented on tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/01_internalAuthServer/02_resourceEndpoint.ts
> -      const apiResponse = await apiContext.get('hook-status/1');
Please replace hook-status by hooks

(We don't test the endpoint but the access)

2024-12-19 09:57 UTC, Progi1984 requested changes
Please don't remove UI Tests but change the called endpoint

2024-12-19 12:32 UTC, Hlavtox requested changes, later dismissed
You cannot do this, this command and handler is used to control hook status in backoffice > module positions page.

2024-12-19 13:00 UTC, Progi1984 submitted a review, later dismissed
Approved for UI Tests

2024-12-20 08:09 UTC, boherm submitted a review, later dismissed

2024-12-20 08:25 UTC, Progi1984 commented on tests/UI/campaigns/functional/API/01_basicTest.ts
> +    it('should request the endpoint /hook', async function () {
```suggestion
    it('should request the endpoint /hooks', async function () {
```

2024-12-20 08:25 UTC, Progi1984 commented on tests/UI/campaigns/functional/API/01_basicTest.ts
> +      const apiResponse = await apiContext.get('hook');
```suggestion
      const apiResponse = await apiContext.get('hooks');
```

2024-12-20 09:29 UTC, Progi1984 commented on tests/UI/campaigns/functional/API/01_basicTest.ts
> +      const apiResponse = await apiContext.get('hooks');
```suggestion
      const apiResponse = await apiContext.put('hooks');
```

2024-12-20 09:30 UTC, Progi1984 commented on tests/UI/campaigns/functional/API/01_basicTest.ts
>        await testContext.addContextItem(this, 'testIdentifier', 'requestNewApiHookStatus', baseContext);
```suggestion
      await testContext.addContextItem(this, 'testIdentifier', 'requestMethodNotAllowed', baseContext);
```

2024-12-20 09:31 UTC, nicosomb commented
@Progi1984 🫶

2024-12-20 13:26 UTC, boherm approved these changes

2024-12-20 13:39 UTC, Progi1984 approved these changes

2024-12-20 13:40 UTC, merged