Further improve URL structure
PrestaShop/PrestaShop pull request #37695
Opened 2024-12-18 16:56 UTC by Hlavtox

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | Extension of https://github.com/PrestaShop/PrestaShop/pull/37467/, see more below.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Test that everything works normally.
| UI Tests          | 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   | 

This builds upon https://github.com/PrestaShop/PrestaShop/pull/37467/ where we removed the category and ean from default URL structure. For the sake of consistency, I proposed to alter the URL futher a tiny bit, when we are changing it. But let's do it in another PR.

So, most other URLs are `/something/XX-rewrite` and only the product is now `/XX-rewrite.html`. The `.html` is there because of conflict with category URLs.

**Example:**
`supplier/{id}-{rewrite}`
`brand/{id}-{rewrite}`
`content/{id}-{rewrite}`

So, this PR changes the structure from:
`www.domain.com/123-perfect-product.html`
to:
`www.domain.com/product/123-perfect-product`

So, we get rid of the `.html` historic remain and make it consistent with other URLs.

2024-12-18 16:57 UTC, Hlavtox commented
Ping @jeckyl @LouisAUTHIE @jf-viguier @kpodemski

2024-12-18 17:03 UTC, jeckyl commented
product/ being untranslatable, this will affect the completeness of all URLs in a different language.
either use only p/ or nothing as applied now.
In this case, we also change all the other brand URLs, forunisseurs, ...
Where we put in place the translation on this element, which I think is a big job.

2024-12-18 17:27 UTC, jf-viguier commented
ok for me.

2024-12-18 17:28 UTC, jf-viguier approved these changes

2024-12-18 17:30 UTC, jeckyl commented
So if you want to modify this URL structure to remove the product/ directory and add the html, you'll have to modify htaccess to redirect the old URLs, which isn't the case if you want to add the product directory and remove the .html.

2024-12-18 17:38 UTC, jeckyl commented
To follow the URL structure consistency argument, we'd have to add category/ to category URLs.

2024-12-18 17:53 UTC, Hlavtox commented
> product/ being untranslatable, this will affect the completeness of all URLs in a different language.

No default routes are currently translatable.
But, it would not be hard to achieve. :-)

2024-12-18 18:13 UTC, jeckyl commented
This new structure will have the same shortcomings as the old one, namely that without touching the .htaccess file, it's impossible to remove product/ from URLs if you wish, whereas there's nothing to stop you from implementing this structure after the fact with the modification I proposed and which was accepted.

2024-12-19 12:34 UTC, Hlavtox commented
@jeckyl I don't see a single reason to keep this `.html` suffix only in product URLs.

2024-12-19 13:47 UTC, jeckyl commented
The only reason is to differentiate product and category URLs.
What I don't understand is why make this PR when the discussion was settled earlier?
What I don't understand is why change product URLs to an untranslatable English term.
What I don't understand, then, is why not take the opportunity to redo all the URL structures and think about the best solution for everyone, since for years everyone has been wondering how to get rid of this conttent/ from the page URLs, or why use English terms instead of simple letters.
In any case, this choice seems to me to require some thought: the PR I've pushed is designed to avoid a 301 redirect problem every time you change categories, which your structure also does, but without fully meeting users' real needs.

2024-12-19 19:34 UTC, ShaiMagal reviewed
OK for me

2024-12-19 19:34 UTC, ShaiMagal approved these changes

2024-12-19 19:54 UTC, kpodemski requested changes
I don't see it as an improvement, but rather a personal preference.

2024-12-20 10:53 UTC, Hlavtox commented
@kpodemski @jeckyl Yes, it's a personal preference, but when we are changing the URLs one time in the previous PR, it's a perfect time to change it.

**Tell me one reason how my proposal is not better:**
- It gets rid of the `.html` suffix finally.
- It aligns the URL structure with the rest of prestashop and unifies it.

I will react to some arguments here:

> What I don't understand is why make this PR when the discussion was settled earlier?
I can open whatever PR I want? :D

> What I don't understand is why change product URLs to an untranslatable English term.
ALL OTHER URLs are like this, an english term.

> What I don't understand, then, is why not take the opportunity to redo all the URL structures and think about the best solution for everyone, since for years everyone has been wondering how to get rid of this conttent/ from the page URLs, or why use English terms instead of simple letters.
ALL OTHER URLs are like this, an english term. Redoing whole URL structure is not in a scope of this PR.

> In any case, this choice seems to me to require some thought: the PR I've pushed is designed to avoid a 301 redirect problem every time you change categories, which your structure also does, but without fully meeting users' real needs.
How this is not meeting real users needs? It meets them exactly the same.

2024-12-20 11:05 UTC, jeckyl commented
> ALL OTHER URLs are like this, an english term. Redoing whole URL structure is not in a scope of this PR.

Wouldn't it be better to open a discussion to redefine URL structures in their entirety?

> How this is not meeting real users needs? It meets them exactly the same.

La PR que j'ai proposé et qui fut validé, sert à corriger un problème, à savoir l'impossibilité de modifier facilement la structure des URL produits sans devoir mettre en place une redirection 301 complexe pour beaucoup d'utilisateurs.
Ma correction te permet justement de pouvoir mettre en place la structure d'URL que tu proposes juste en changeant celle-ci dans la configuration de PrestaShop.

> ALL OTHER URLs are like this, an english term.

Here again, it seems to me that a little more thought would make it possible to do away with this inconsistency and propose the best URL structure for everyone, and correct the errors of the past by allowing greater flexibility in the uses we might wish to make of it.

URL structure isn't really important either in terms of SEO or in terms of usage, since browsers are gradually eliminating this information.
However, it is of vital importance to the long-term SEO stability of a store, as it needs to be as unchanging as possible and not cause repeated, untimely 301 redirects.

To achieve this, it would be preferable to work on the product configuration page to remove the automatic update of product URL rewrites and only do so on direct user request, as was done for category URLs. Something I haven't had time to look into yet.

2024-12-20 13:40 UTC, jf-viguier commented
WDYT of this : 
product : p123rewrite
category : c123rewrite
cms : ct123rewrite
manufacturer : m123rewrite

The idea is to have shortest url everywhere

2024-12-24 14:05 UTC, gs2k84 commented
Hello,

what if you did it this way?

the first letter or 2 letters if it gets repeated (category and content) /{rewrite}-{id}

Rewrite before ID because when you read the page address you have

page_name/p/product-name-ID

It doesn't work so well when there is an attribute but it is legible, especially in the address on the phone.

You see the name of the page and immediately the name of the product (category, etc.)

Path to products
p/{rewrite}-{id}{-:id_product_attribute}

p - product

Here I wonder whether to do without /p/ for the product

Path to category
c/{rewrite}-{id}

c - category

Path to supplier
s/{rewrite}-{id}

s - supplier

Path to brand
b/{rewrite}-{id}

b - brand

Path to page
ct/{rewrite}-{id}

ct - content

Path to category page
cp{rewrite}-{id}

cp - category page

Path to modules
m/{module}{/:controller}

Possibly as jf-viguier suggested

but in this order

produkt: rewrite-p123
category: rewrite-c123
cms: rewrite-ct123

2025-01-09 13:57 UTC, closed without merging