[BO] - Fix unsecure payment request link
PrestaShop/PrestaShop pull request #37707
Opened 2024-12-20 09:48 UTC by SebBareyre

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | the order link in the backoffice_order mail template is always unsecure
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Create a new order in backoffice and send payment request email
| UI Tests          | 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   | ohmyweb!

2024-12-20 09:48 UTC, ps-jarvis commented
<!-- PR_TABLE_DESCRIPTION_ERROR -->
Hi, thanks for this contribution!

Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

2024-12-20 11:34 UTC, kpodemski commented
Hello @SebBareyre 

Your fix makes sense! Could you rebase onto `9.0.x` or `8.2.x` branch, so it could part of one of the next versions?

2024-12-20 12:22 UTC, SebBareyre commented
hello @kpodemski 
I don't know how to do that.. sorry

2025-08-05 13:59 UTC, jf-viguier approved these changes
It's ok for me. Changing $ssl front false to null for getPageLink tell PrestaShop to use SSL configuration instead of http://

2025-08-05 14:01 UTC, kpodemski submitted a review, later dismissed

2025-08-05 14:30 UTC, Hlavtox commented
@kpodemski I can rebase it

2025-08-14 13:40 UTC, Hlavtox requested changes
Reabse needed

2025-08-20 09:34 UTC, jf-viguier approved these changes

2025-08-20 09:39 UTC, Hlavtox approved these changes

2025-08-20 10:07 UTC, Touxten approved these changes

2025-08-20 10:51 UTC, Touxten commented
@PrestaShop/qa-functional i am not sure youn can test with a shop with an certificat SSL ?

2025-08-20 10:53 UTC, kpodemski commented
@PrestaShop/qa-functional @Touxten 

I don't think it requires manual tests. Please confirm @PrestaShop/qa-functional :)

2025-09-09 08:55 UTC, merged