Update LegacyUrlConverter.php
PrestaShop/PrestaShop pull request #37714
Opened 2024-12-20 17:38 UTC by Codencode

For the conversion of a URL, only the GET parameters must be taken into account

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | see #37687 
| Type?             | bug fix / improvement / new feature / refacto
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | see #37687 
| UI Tests          | 
| Fixed issue or discussion?     | Fixes #37687 
| Related PRs       | If theme, autoupgrade or other module change is needed to make this change work, provide a link to related PRs here.
| Sponsor company   | @Codencode

2024-12-20 17:38 UTC, ps-jarvis commented
<!-- PR_TABLE_DESCRIPTION_ERROR -->
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `type` should be one of these: `new feature`, `improvement`, `bug fix` or `refacto`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

2024-12-20 17:38 UTC, Hlavtox approved these changes

2024-12-20 17:39 UTC, Hlavtox requested changes
@Codencode 9.0.x please

2024-12-20 17:40 UTC, Codencode commented
> @Codencode 9.0.x please

"You're right!
Should I close it and create a new one?"

2024-12-20 20:15 UTC, Hlavtox commented
@Codencode You must rebase the PR.

➡️ If you are not familiar with CLI, use https://tortoisegit.org/ on windows or https://www.git-tower.com/mac on mac.

2024-12-21 14:24 UTC, Codencode commented
@Hlavtox,
I did the rebase, but I'm not sure if it's okay.
Unfortunately, I'm not very experienced with GitHub.
If it's not okay, I'll close this and create a new PR.

Thanks for your patience!

2025-01-16 08:34 UTC, closed without merging

2025-01-16 08:40 UTC, Codencode commented
PR closed because I used the wrong branch.