Fix: Problem with shop association component
PrestaShop/PrestaShop pull request #37717
Opened 2024-12-21 15:24 UTC by Codencode

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | see https://github.com/PrestaShop/PrestaShop/issues/37442
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | see https://github.com/PrestaShop/PrestaShop/issues/37442
| UI Tests          |
| Fixed issue or discussion?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/37442
| Related PRs       |
| Sponsor company   | @Codencode

2025-01-13 16:53 UTC, jolelievre requested changes
Thanks @Codencode 

Just one suggestion for simplification/improvement of the fix

2025-01-13 16:53 UTC, jolelievre commented on src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
> +      $stringArrayToIntegerArrayDataTransformer: '@PrestaShopBundle\Form\DataTransformer\StringArrayToIntegerArrayDataTransformer'
Wow great catch @Codencode 
I searched for the PR that modified this and found it here https://github.com/PrestaShop/PrestaShop/pull/31391/files#diff-ce2d57a2ac02f46a9cd2eea65b89142c51e7df0a68afc4f9d1e9e01a53999f75L351

So actually your PR should be even simpler, it's just that the wrong transformer was assigned during the refacto, the ShopChoiceTreeType has nothing to do with multi lang values so `DefaultLanguageToFilledArrayDataTransformer` shouldn't be passed at all

```suggestion
      $stringArrayToIntegerArrayDataTransformer: '@PrestaShopBundle\Form\DataTransformer\StringArrayToIntegerArrayDataTransformer'
```

2025-01-14 08:48 UTC, Codencode commented on src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
> +      $stringArrayToIntegerArrayDataTransformer: '@PrestaShopBundle\Form\DataTransformer\StringArrayToIntegerArrayDataTransformer'
Hello @jolelievre,
thank you for the suggestion, but if I apply this change, I get the following error:
```php
Cannot autowire service "PrestaShopBundle\Form\Admin\Type\ShopChoiceTreeType":
argument "$defaultLanguageToFilledArrayDataTransformer" of method "__construct()"
 references interface "Symfony\Component\Form\DataTransformerInterface" but no such service exists.
  You should maybe alias this interface to one of these existing services:
 "PrestaShopBundle\Form\Admin\Sell\Product\DataTransformer\RedirectionTargetTransformer",
 "PrestaShopBundle\Form\Admin\Sell\Product\DataTransformer\SpecificPriceFixedPriceTransformer", 
 "PrestaShopBundle\Form\Admin\Type\ApeType", "PrestaShopBundle\Form\Admin\Type\IpAddressType", 
 "PrestaShopBundle\Form\Admin\Type\TextPreviewType", 
 "PrestaShopBundle\Form\DataTransformer\ArabicToLatinDigitDataTransformer", 
 "PrestaShopBundle\Form\DataTransformer\DefaultEmptyDataTransformer", 
 "PrestaShopBundle\Form\DataTransformer\DefaultLanguageToFilledArrayDataTransformer", 
 "PrestaShopBundle\Form\DataTransformer\IDNConverterDataTransformer", 
 "PrestaShopBundle\Form\DataTransformer\StringArrayToIntegerArrayDataTransformer".
```
This happens because the class `PrestaShopBundle\Form\Admin\Type\ShopChoiceTreeType` expects `$defaultLanguageToFilledArrayDataTransformer`.

Am I missing something?

2025-01-14 08:53 UTC, Codencode commented on src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml
> +      $stringArrayToIntegerArrayDataTransformer: '@PrestaShopBundle\Form\DataTransformer\StringArrayToIntegerArrayDataTransformer'
@jolelievre,
sorry, the issue was due to the fact that I "obviously" need to remove the instructions related to the `defaultLanguageToFilledArrayDataTransformer` attribute in the `PrestaShopBundle\Form\Admin\Type\ShopChoiceTreeType` class.

2025-01-14 09:01 UTC, Codencode commented
@jolelievre,
I have made the changes, and of course, I also had to update the `PrestaShopBundle\Form\Admin\Type\ShopChoiceTreeType` class, which has returned to its original state.

Thank you!

2025-01-14 09:47 UTC, jolelievre approved these changes
Thanks @Codencode 

perfect this way 😉

2025-01-14 09:50 UTC, Codencode commented
Thank you, @jolelievre, for the suggestion!

2025-01-14 09:54 UTC, kpodemski approved these changes

2025-01-14 09:54 UTC, boherm approved these changes

2025-01-15 09:54 UTC, paulnoelcholot commented
Hello @Codencode,


Autotest failed :/ 

https://github.com/paulnoelcholot/testing_pr/actions/runs/12768589163

2025-01-15 10:04 UTC, paulnoelcholot commented
FYI @Progi1984

2025-01-15 10:45 UTC, Codencode commented
I don't understand why this change should impact the "Stocks" page.
If I filter by categories: "Art" and "Accessories" on this page, I get 35 results instead of 47, which is what the test expects.

Am I missing something?

2025-01-15 11:24 UTC, kpodemski commented
Hello @Codencode 

Let's wait for an opinion from @Progi1984.

2025-01-16 08:53 UTC, Progi1984 commented
@paulnoelcholot Sorry for UI Tests. They can be unstable like any server. We have a lot of problems due to page Stock Movements. We write on other improvements.

2025-01-16 09:08 UTC, jolelievre commented
@Progi1984 @paulnoelcholot so I guess we just need to restart UI tests until they succeed no? Or do we assume it's ok?

2025-01-16 09:14 UTC, Progi1984 commented
@jolelievre Restart failed jobs max 3-4 times (and after that contact me).

2025-01-16 14:49 UTC, paulnoelcholot commented
@Progi1984 
I have reloaded many time the automated tests and it's always failed :/ https://github.com/paulnoelcholot/testing_pr/actions/runs/12804510938

2025-01-17 15:21 UTC, paulnoelcholot commented
Hello @Codencode 

I tested your PR and it's good for me! :tada: 

Thanks!

https://www.loom.com/share/df9a4b2fe0214554a1fe3ed93c5a49b2?sid=9abd02c5-6516-427d-b217-6dfb62eb4c24
https://github.com/paulnoelcholot/testing_pr/actions/runs/12804510938/job/35779146869#step:10:378

2025-01-17 15:21 UTC, paulnoelcholot approved these changes

2025-01-17 15:24 UTC, merged

2025-01-17 15:24 UTC, kpodemski commented
awsome, thank you @Codencode 🎉