Wrong variables in installer's strings.
PrestaShop/PrestaShop pull request #6148
Opened 2016-09-01 09:06 UTC by xBorderie

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Typos!
| Type?         | improvement
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | Read the page, see if the variables work!

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

2016-09-12 13:44 UTC, AlexEven commented on install-dev/controllers/http/configure.php
> +            $this->errors['admin_firstname'] = $this->translator->trans('The field %field% is limited to %limit% characters', array('field' => $this->translator->trans('firstname', array(), 'Install'
%field% and %limit% in the array too ;)

2016-09-12 13:45 UTC, AlexEven commented
Wording ok! Thank you :)

2016-09-12 15:24 UTC, xBorderie commented
Thank you @AlexEven ! Done in https://github.com/PrestaShop/PrestaShop/pull/6148/commits/908167d4b70df5e50f1cecce56527880a1a67661 (with one additional change, plz chk).

2016-09-16 15:22 UTC, maximebiloe commented on install-dev/controllers/http/configure.php
> +            $this->errors['shop_name'] = $this->translator->trans('The field %field% is limited to %limit% characters', array('limit' => 64, '%field%' => $this->translator->trans('shop name', array()
Still need a little update here :) `limit` => `%limit%`

2016-09-16 15:23 UTC, maximebiloe requested changes

2016-09-22 12:05 UTC, maximebiloe commented
@xBorderie could you update according to comment please?

2016-10-10 13:27 UTC, xBorderie commented
@maximebiloe Done! Sorry for the delay!

2016-10-10 13:34 UTC, maximebiloe approved these changes

2016-10-10 13:52 UTC, merged