Use symfony translator for controllers - part 1
PrestaShop/PrestaShop pull request #6255
Opened 2016-09-09 10:39 UTC by firstred

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | `develop`
| Description?  | Use Symfony translator for several controllers
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  |

2016-09-09 11:55 UTC, julienbourdeau commented
Thanks! @AlexEven will be back on Monday, she'll check your PR, especially the domains.

2016-09-09 12:11 UTC, maximebiloe commented
For consistency purpose, why don't you use `$this->trans()` all the time?
Sometimes you use `$this->translator->trans()`

2016-09-09 12:12 UTC, firstred commented
Working on it right now. Just half way through I learned that you could use `$this->trans()` instead haha

2016-09-12 12:27 UTC, firstred commented
Is it good?

2016-09-12 12:30 UTC, mickaelandrieu commented on controllers/admin/AdminCmsController.php
> +                    'label' => $this->trans('Meta description', array(), 'Admin.Parametes.Feature'),
```diff
- Admin.Parametes.Feature
+ Admin.Parameters.Feature
```

2016-09-12 12:31 UTC, firstred commented on controllers/admin/AdminCmsController.php
> +                    'label' => $this->trans('Meta description', array(), 'Admin.Parametes.Feature'),
Gracias!

2016-09-12 12:53 UTC, AlexEven commented on controllers/admin/AdminCmsCategoriesController.php
> +                    'hint' => $this->trans('Invalid characters:', array(), 'Admin.Notifications.Error').' &lt;&gt;;=#{}'
Can you please change the domain to Admin.Notifications.Info?
As it's a help text it's not technically saying a error message. Thanks :)

2016-09-12 12:54 UTC, AlexEven commented on controllers/admin/AdminCmsCategoriesController.php
> +                    'hint' => $this->trans('Invalid characters:', array(), 'Admin.Global').' &lt;&gt;;=#{}'
Same here, you can use Admin.Notifications.Info.

2016-09-12 12:54 UTC, AlexEven commented on controllers/admin/AdminCmsCategoriesController.php
> +                    'hint' => $this->trans('Invalid characters:', array(), 'Admin.Global').' &lt;&gt;;=#{}'
Here as well - Admin.Notifications.Info

2016-09-12 12:55 UTC, AlexEven commented on controllers/admin/AdminCmsCategoriesController.php
> +                    'label' => $this->trans('Meta description', array(), 'Admin.Parameters.Feature'),
You can use Admin.Global for this one too, it's already existing within this domain!

2016-09-12 12:55 UTC, AlexEven commented on controllers/admin/AdminCmsCategoriesController.php
> +                    'hint' => $this->trans('Invalid characters:', array(), 'Admin.Global').' &lt;&gt;;=#{}'
Admin.Notifications.Info

2016-09-12 12:56 UTC, AlexEven commented on controllers/admin/AdminCmsCategoriesController.php
> +                    'label' => $this->trans('Meta keywords', array(), 'Admin.Parameters.Feature'),
Admin.Global

2016-09-12 12:56 UTC, AlexEven commented on controllers/admin/AdminCmsCategoriesController.php
> +                    'hint' => $this->trans('Invalid characters:', array(), 'Admin.Global').' &lt;&gt;;=#{}'
Admin.Notifications.Info

2016-09-12 12:56 UTC, firstred commented on controllers/admin/AdminCmsCategoriesController.php
> +                    'hint' => $this->trans('Invalid characters:', array(), 'Admin.Notifications.Error').' &lt;&gt;;=#{}'
Are you sure?

Usually these are what the levels mean:
- info, verbose stuff, can be ignored
- warning, can be ignored for now but you should do something
- error, can't go on and you must do something

PrestaShop isn't able to process the form, so looks like an error to me.

Do you agree this should be an error notification after this explanation? ^^

2016-09-12 12:57 UTC, AlexEven commented on controllers/admin/AdminCmsCategoriesController.php
> +                    'label' => $this->trans('Friendly URL', array(), 'Admin.Parameters.Feature'),
You can have Admin.Global too, as it's used in several places in the BO

2016-09-12 12:59 UTC, AlexEven commented on controllers/admin/AdminCmsCategoriesController.php
> +                    'hint' => $this->trans('Only letters and the minus (-) character are allowed.', array(), 'Admin.Global')
I'd say Admin.Design.Help as it's a help text and this sentence has only two occurences in PrestaShop. Even better, Admin.Catalog.Help, to match the other occurence and avoid duplicates (though it's not in a Catalog files exactly speaking).

2016-09-12 13:00 UTC, AlexEven commented on controllers/admin/AdminCmsCategoriesController.php
> +                'label' => $this->trans('Shop association', array(), 'Admin.Parameters.Feature'),
Admin.Global - quite a few occurrences across the whole content.

2016-09-12 13:01 UTC, AlexEven commented on controllers/admin/AdminCmsContentController.php
> +                $this->toolbar_title[] = $this->trans('Add new', array(), 'Admin.Global');
Admin.Actions?

2016-09-12 13:01 UTC, mickaelandrieu commented on controllers/admin/AdminCmsCategoriesController.php
> +                    'hint' => $this->trans('Only letters and the minus (-) character are allowed.', array(), 'Admin.Global')
It's ok, cause the system have been created to **not** rely anymore on files location :)

2016-09-12 13:02 UTC, AlexEven commented on controllers/admin/AdminCmsContentController.php
> +                $this->toolbar_title[] = $this->trans('Add new', array(), 'Admin.Global');
And Admin.Actions too

2016-09-12 13:03 UTC, firstred commented on controllers/admin/AdminCmsCategoriesController.php
> +                    'hint' => $this->trans('Only letters and the minus (-) character are allowed.', array(), 'Admin.Global')
Nice. How about modules? How can I add Symfony translations from module folders? Or has it not been implemented, yet?

2016-09-12 13:06 UTC, AlexEven commented on controllers/admin/AdminCmsContentController.php
> +                $this->toolbar_title[] = $this->trans('Edit: %meta_title%', array('%meta_title%' => $cms_page->meta_title[$this->context->employee->id_lang]), 'Admin.Parameters.Feature');
I'd use Admin.Design wherever you used Admin.Parameters: this is CMS/Pages related, it's part of the Design section, not in the Parameters.

Also, former Admin.Parameters domain has been divided in Admin.ShopParam. and Admin.AdvParam to be more specific about the sections it relates too. So Admin.Parameters should no longer be used. I will publish an article on Build to let people know about these updates ^^

2016-09-12 13:08 UTC, AlexEven commented on controllers/admin/AdminCmsController.php
> +                    'label' => $this->trans('Meta title', array(), 'Admin.Parameters.Feature'),
Admin.Global

2016-09-12 13:08 UTC, AlexEven commented on controllers/admin/AdminCmsController.php
> +                    'hint' => $this->trans('Invalid characters:', array(), 'Admin.Global').' &lt;&gt;;=#{}'
Admin.Notifications.Info

2016-09-12 13:08 UTC, AlexEven commented on controllers/admin/AdminCmsController.php
> +                    'label' => $this->trans('Meta description', array(), 'Admin.Parameters.Feature'),
Admin.Global

2016-09-12 13:08 UTC, AlexEven commented on controllers/admin/AdminCmsController.php
> +                    'hint' => $this->trans('Invalid characters:', array(), 'Admin.Global').' &lt;&gt;;=#{}'
Admin.Notifications.Info

2016-09-12 13:09 UTC, AlexEven commented on controllers/admin/AdminCmsController.php
> +                    'label' => $this->trans('Meta keywords', array(), 'Admin.Parameters.Feature'),
Admin.Global

2016-09-12 13:09 UTC, AlexEven commented on controllers/admin/AdminCmsController.php
> +                        $this->trans('To add "tags" click in the field, write something, and then press "Enter."', array(), 'Admin.Parameters.Feature'),
Admin.Design.Help

It's a hint text + it's in the design section

2016-09-12 13:14 UTC, AlexEven commented on controllers/admin/AdminCmsController.php
> +                        $this->trans('Invalid characters:', array(), 'Admin.Global').' &lt;&gt;;=#{}'
Admin.Notifications.Info

2016-09-12 13:14 UTC, AlexEven commented on controllers/admin/AdminCmsController.php
> +                    'label' => $this->trans('Friendly URL', array(), 'Admin.Parameters.Feature'),
Admin.Global

2016-09-12 13:15 UTC, AlexEven commented on controllers/admin/AdminCmsController.php
> +                    'hint' => $this->trans('Only letters and the hyphen (-) character are allowed.', array(), 'Admin.Parameters.Feature')
See previous comment, Admin.Design.Help or Admin.Catalog.Help

2016-09-12 13:15 UTC, AlexEven commented on controllers/admin/AdminCmsController.php
> +                    'hint' => $this->trans('Invalid characters:', array(), 'Admin.Global').' <>;=#{}'
Admin.Notifications.Info

2016-09-12 13:15 UTC, AlexEven commented on controllers/admin/AdminCmsController.php
> +                    'title' => $this->trans('Save and preview', array(), 'Admin.Global'),
Admin.Actions

2016-09-12 13:15 UTC, AlexEven commented on controllers/admin/AdminCmsController.php
> +                'label' => $this->trans('Shop association', array(), 'Admin.Parameters.Feature'),
Admin.Global

2016-09-12 13:16 UTC, AlexEven commented on controllers/admin/AdminCmsController.php
> +            'desc' => $this->trans('Add new', array(), 'Admin.Global')
Admin.Actions

2016-09-12 13:17 UTC, AlexEven commented on controllers/admin/AdminCmsController.php
> +            echo '<tr><td class="center" colspan="'.(count($this->fields_list) + 2).'">'.$this->trans('No items found', array(), 'Admin.Global').'</td></tr>';
I think it's the only occurence, so it can be Admin.Design.Notification for instance.

2016-09-12 13:18 UTC, AlexEven commented on controllers/admin/AdminCountriesController.php
> +                'title' => $this->trans('ISO code', array(), 'Admin.Global'),
You can use Admin.International.Feature, it can be found on several pages, but all are from the International section.

2016-09-12 13:19 UTC, AlexEven commented on controllers/admin/AdminCountriesController.php
> +                    'label' => $this->trans('ISO code', array(), 'Admin.Global'),
Admin.International.Feature

2016-09-12 13:19 UTC, AlexEven commented on controllers/admin/AdminCountriesController.php
> +                    /* @TODO - add two lines for the hint? */
Admin.International.Help, as it's a hint.

2016-09-12 13:19 UTC, AlexEven commented on controllers/admin/AdminCountriesController.php
> +                    'hint' => $this->trans('International call prefix, (e.g. 1 for United States).', array(), 'Admin.International.Feature')
Admin.International.Help

2016-09-12 13:20 UTC, AlexEven commented on controllers/admin/AdminCountriesController.php
> +                    'hint' => $this->trans('Geographical region.', array(), 'Admin.International.Feature')
Admin.International.Help (hint)

2016-09-12 13:21 UTC, AlexEven commented on controllers/admin/AdminCountriesController.php
> +                'label' => $this->trans('Shop association', array(), 'Admin.Parameters.Feature'),
Admin.Global

2016-09-12 13:26 UTC, AlexEven commented
Hello @firstred 

Thanks a lot for this!!

A made "a few" comments on the domains ^^ --- it's not easy when you get started on this, but don't hesitate if you have a question. It's mostly to avoid duplicates as these strings already have a domain somewhere else.

Also, we're trying to avoid the "CMS" mention, instead we just use "Pages" (and no longer "CMS pages"), so whenever you can remove CMS, don't hesitate. Obviously I still have some work to do on the strings, I'm not done yet!

Thank you :smile:

2016-09-12 13:30 UTC, AlexEven commented on controllers/admin/AdminCmsCategoriesController.php
> +                    'hint' => $this->trans('Invalid characters:', array(), 'Admin.Notifications.Error').' &lt;&gt;;=#{}'
I see it as an hint and not a DisplayError or something error-related, to me it's an indication to let you know which characters you should avoid (we agreed the wording is not the best).

2016-09-12 14:17 UTC, firstred commented
Thanks so much for the comments and insights. This'll definitely help contributors pick the right domains.

2016-09-16 14:18 UTC, maximebiloe commented on controllers/admin/AdminCmsCategoriesController.php
> +                    'hint' => $this->trans('Invalid characters:', array(), 'Admin.Global').' &lt;&gt;;=#{}'
Still need a little update here

2016-09-16 14:20 UTC, maximebiloe requested changes

2016-09-22 12:41 UTC, maximebiloe approved these changes

2016-09-22 12:42 UTC, maximebiloe commented
Thank you @firstred and also @AlexEven for review.

2016-09-22 12:42 UTC, merged