Doc + cleanup Hook class
PrestaShop/PrestaShop pull request #6291
Opened 2016-09-12 01:03 UTC by firstred

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | `develop`
| Description?  | Upgrading the PHPDoc comments of this class, using the latest PS standards and also applying the PS standards to some of the code. Also getting the Franglais out of the comments, getting rid of things the Symfony code sniffer nags about, etc. It might have some additional `todo` tags, depending on whether the code was comprehensible or not.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | N/A
| How to test?  | N/A

Warning: this PR also has a code cleanup. Please check this first before merging!

2016-09-16 12:15 UTC, mickaelandrieu commented
Would you mind to rebase it against develop branch ?

2016-09-20 13:44 UTC, thierrymarianne commented on classes/Hook.php
> +     * @param string     $hookName
It appears $hookName could be passed as an array.

2016-09-20 13:46 UTC, thierrymarianne requested changes
Please see minor change requested.

2016-10-02 21:54 UTC, firstred commented
Updated

2016-11-29 22:44 UTC, closed without merging