Doc + cleanup Pack class
PrestaShop/PrestaShop pull request #6298
Opened 2016-09-12 01:45 UTC by firstred

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | `develop`
| Description?  | Upgrading the PHPDoc comments of this class, using the latest PS standards and also applying the PS standards to some of the code. Also getting the Franglais out of the comments, getting rid of things the Symfony code sniffer nags about, etc. It might have some additional `todo` tags, depending on whether the code was comprehensible or not.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | N/A
| How to test?  | N/A

Warning: this PR also has a code cleanup. Please check this first before merging!

2016-09-16 12:07 UTC, mickaelandrieu commented on classes/Pack.php
> +*@return bool
you may have forgot some extra space, isn't it ?

2016-09-16 12:07 UTC, mickaelandrieu commented on classes/Pack.php
> +*@return bool
same here

2016-09-16 12:08 UTC, mickaelandrieu commented on classes/Pack.php
> +     * @param integer $idItem          Product item id that could be contained in a|many pack(s)
I think it's "int", not "integer"

2016-09-16 12:09 UTC, mickaelandrieu commented on classes/Pack.php
> +     * @param $idProduct
```diff
- * @param $idProduct
+ * @param int $idProduct
``

2016-09-16 12:09 UTC, mickaelandrieu commented on classes/Pack.php
> +     * @param $idProduct
same here, would you mind to add some type information ?

2016-09-16 12:09 UTC, mickaelandrieu requested changes
Good job! Some comments need to be adressed before :ship:

2016-09-28 17:24 UTC, firstred commented on classes/Pack.php
> +*@return bool
Hey, that's a PhpStorm bug haha

2016-10-02 21:53 UTC, firstred commented
Fixed

2016-11-29 22:44 UTC, closed without merging