FO: Responsive layout for customer area
PrestaShop/PrestaShop pull request #6308
Opened 2016-09-12 10:03 UTC by ishcherbakov

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Resposive layout - Customer area
| Type?         | new feature
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | -

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

2016-09-12 12:20 UTC, maximebiloe commented
Thank you!
@AlexEven could you check the domains, please?

2016-09-15 09:06 UTC, AlexEven requested changes
Thanks Ivan!

2016-09-15 09:48 UTC, ishcherbakov commented
@AlexEven Done !

2016-09-15 13:25 UTC, maximebiloe commented on themes/classic/assets/js/theme.js
> +	 * Bootstrap v4.0.0-alpha.3 (http://getbootstrap.com)
You need to run `npm update` before compiling your assets. You're downgrading Bootstrap 😢

2016-09-15 13:26 UTC, maximebiloe commented on themes/classic/templates/customer/_partials/order-detail-return.tpl
> +                    <div>{l s='Returned' d='Shop.Theme.Catalog'}: {$product.qty_returned}</div>
@ishcherbakov You need to update the domain here

2016-09-15 13:26 UTC, maximebiloe requested changes

2016-09-15 15:03 UTC, maximebiloe approved these changes

2016-09-15 15:06 UTC, AlexEven approved these changes

2016-09-15 15:29 UTC, merged

2016-09-15 15:29 UTC, maximebiloe commented
Thank you!