Fix the 'View less/View all images' button on the product page
PrestaShop/PrestaShop pull request #6348
Opened 2016-09-14 15:51 UTC by antoin-m

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Please be specific when describing the PR. <br/> Every detail helps: versions, browser/server configuration, specific module/theme, etc.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1252
| How to test?  | <ul><li>BO: Create a new poduct</li><li>You should not see the 'View less/View all images' button</li><li>Add a lot of images</li><li>You should see the 'View less/View all images' button</li></ul>

2016-09-14 16:34 UTC, mickaelandrieu commented
<!--
Status: 'Code reviewed'
-->

2016-09-14 16:44 UTC, mickaelandrieu commented
<!--
Status: 'Code reviewed'	
-->

2016-09-16 12:30 UTC, mickaelandrieu commented on admin-dev/themes/default/js/bundle/product/form.js
> +  const dropZoneElem = $('#product-images-dropzone');
you cant use ES6 stuff in this file, because it's not transpiled.

2016-09-16 12:31 UTC, mickaelandrieu commented on admin-dev/themes/default/js/bundle/product/form.js
> +      const oldHeight = dropZoneElem.css('height');
same here

2016-09-16 12:31 UTC, mickaelandrieu commented on admin-dev/themes/default/js/bundle/product/form.js
> +      const realHeight = dropZoneElem[0].scrollHeight;
same here

```diff
- const
+ var
```

2016-09-16 12:31 UTC, mickaelandrieu commented on admin-dev/themes/default/js/bundle/product/form.js
> +          expanderElem.addClass('expand').click();
:+1:

2016-09-16 12:32 UTC, mickaelandrieu requested changes
Some comments to adress, else this wont work anymore on IE11+

2016-09-19 08:58 UTC, antoin-m commented
@mickaelandrieu I removed the ES6 code :)

2016-09-19 09:05 UTC, mickaelandrieu approved these changes

2016-09-19 09:05 UTC, merged

2016-09-19 09:05 UTC, mickaelandrieu commented
thank you @antoin-m !