Raise errors when theme can't be enabled
PrestaShop/PrestaShop pull request #6380
Opened 2016-09-16 11:41 UTC by aleeks

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Raise errors when theme can't be enabled. Before page reload, theme wasn't enabled and we have no error
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Install a theme with a missing template (form-fields.tpl) for example

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

2016-09-16 11:43 UTC, kpodemski commented on controllers/admin/AdminThemesController.php
> +            $themeHasEnabled = $this->theme_manager->enable(Tools::getValue('theme_name'));
isThemeEnabled wouldn't be better?

2016-09-16 11:45 UTC, mickaelandrieu approved these changes

2016-09-16 11:46 UTC, mickaelandrieu commented on src/Core/Addon/Theme/ThemeValidator.php
> +                $this->errors[$themeName] = $translator->trans('An error occurred. The information "%s" is missing.', array($prop), 'Admin.Design.Notification');
ping the other Alex :p /c @AlexEven

2016-09-16 11:48 UTC, aleeks commented on src/Core/Addon/Theme/ThemeValidator.php
> +                $this->errors[$themeName] = $translator->trans('An error occurred. The information "%s" is missing.', array($prop), 'Admin.Design.Notification');
It's ok for @AlexEven !

2016-09-16 11:52 UTC, aleeks commented on controllers/admin/AdminThemesController.php
> +            $themeHasEnabled = $this->theme_manager->enable(Tools::getValue('theme_name'));
Done! Thanks @kpodemski

2016-09-16 13:44 UTC, AlexEven commented on src/Core/Addon/Theme/ThemeValidator.php
> +                $this->errors[$themeName] = $translator->trans('An error occurred. The information "%s" is missing.', array($prop), 'Admin.Design.Notification');
Yes, seen with @aleeks :)
Thanks!

2016-09-19 07:46 UTC, mickaelandrieu commented on src/Core/Addon/Theme/ThemeManager.php
> +    public function getErrors($theme_name)
$themeName

2016-09-19 07:46 UTC, mickaelandrieu commented on src/Core/Addon/Theme/ThemeManager.php
> +        return $this->themeValidator->getErrors($theme_name);
$themeName

2016-09-19 07:46 UTC, mickaelandrieu commented on src/Core/Addon/Theme/ThemeValidator.php
> +    public function getErrors($theme_name) {
$themeName

2016-09-19 07:46 UTC, mickaelandrieu commented on src/Core/Addon/Theme/ThemeValidator.php
> +        return array_key_exists($theme_name, $this->errors) ? $this->errors[$theme_name] : false;
$themeName

2016-09-19 07:47 UTC, mickaelandrieu requested changes

2016-09-22 09:03 UTC, mickaelandrieu approved these changes

2016-09-22 09:03 UTC, merged

2016-09-22 09:03 UTC, mickaelandrieu commented
Thank you @aleeks !