Fixed 'installed modules' tab if no shop selected (multishop)
PrestaShop/PrestaShop pull request #6440
Opened 2016-09-22 08:48 UTC by aleeks

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | 'Installed modules' tab on module page was broken if you have multistore enabled & no shop selected (all, or group shop selected).
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1526
| How to test?  | Enable multistore, select "all shop" or a "group" and go to "installed modules" tab (modules page), it's not broken anymore

@Quetzacoalt91 tell me if it's ok for you ?

2016-09-22 14:28 UTC, Quetzacoalt91 commented on src/PrestaShopBundle/Controller/Admin/ModuleController.php
> +            $modulesTheme = false;
Why don't you just initialize this variable as an empty array ? You won't have to change the test later l.157

2016-09-22 14:29 UTC, Quetzacoalt91 commented on src/PrestaShopBundle/Controller/Admin/ModuleController.php
> +            if (is_array($modulesTheme) && in_array($installedProduct->attributes->get('name'), $modulesTheme)) {
Could be reverted if the default value of `$modulesTheme` is an empty array

2016-09-22 14:29 UTC, Quetzacoalt91 requested changes

2016-09-22 14:45 UTC, Quetzacoalt91 approved these changes

2016-09-23 11:43 UTC, merged

2016-09-23 11:44 UTC, mickaelandrieu commented
Thank you @aleeks  and @Quetzacoalt91 for review :)