IN
PrestaShop/PrestaShop pull request #6471
Opened 2016-09-25 20:49 UTC by Casper-O

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | Develop
| Description?  | Adding Danish translation for installer + fixing a few typo
| Type?         |  improvement
| Category?     | IN
| BC breaks?    | No
| Deprecations? | No
| Fixed ticket? | 
| How to test?  | Ask someone that knows danish

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

2016-09-26 07:16 UTC, aleeks approved these changes

2016-09-27 09:02 UTC, AlexEven commented
Hello @Casper-O, 

Thank you for this!!
We've done as you suggested and we're waiting for the feedback of someone who speaks Danish :)
Shouldn't long before we can merge your PR!

Kind regards,

2016-09-27 10:24 UTC, Casper-O commented
No Problem. I asked a Danish Prestashop Community to help with the translations. I don't know ho many of them have experience with Github, but hopefully more can help with translation or at least confirming what have been translated

2016-09-27 10:54 UTC, mowol requested changes
Customer må skulle oversættes til ental "Kunde".

2016-09-27 10:57 UTC, mowol requested changes
Sorry for the double post. I have two small change requests to the translation. Otherwise it looks good. Good job Casper!

2016-09-27 10:57 UTC, mowol commented on install-dev/langs/da/data/group.xml
> +  <group id="Customer" name="Kunder"/>
bør være Kunde

2016-09-27 10:57 UTC, mowol commented on install-dev/langs/da/data/meta.xml
> +    <description>Brug din formular til at kontakte os</description>
Brug vores formular til at kontakte os

2016-09-27 17:24 UTC, tobleronealfen commented on install-dev/langs/da/data/contact.xml
> +  <contact id="Customer_service" name="Kunde service">
Kundeservice
Et ord

2016-09-27 17:25 UTC, tobleronealfen commented on install-dev/langs/da/data/contact.xml
> +    <description>For alle spørgsmål om et produkt eller en ordre</description>
Kan gøres mere simpel/meneskeligt med f.eks.
"Spørgsmål vedrørende en vare eller en ordre."

2016-09-27 17:32 UTC, tobleronealfen commented on install-dev/langs/da/data/contact.xml
> +    <description>For alle spørgsmål om et produkt eller en ordre</description>
eller "et produkt"

2016-09-27 19:15 UTC, Casper-O reviewed
with help from @tobleronealfen

2016-09-29 09:00 UTC, maximebiloe commented
Thank you for this PR!

For your future contributions could look at our [guidelines](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message) for your commit messages, please?

For this one, I'll squash your commits.

Regards

2016-09-29 09:02 UTC, merged

2016-09-30 08:02 UTC, Casper-O commented
Hi @maximebiloe what part of my commit message was not following the guideline? I have been trying to follow the guidelines for all my Commits, but often someone change them, and don't mention why they did it.

My own guess its my naming was not following the guideline this time. But as I said, it often happens that other change it and removing the Category shortcode from it, thats why i did not add it this time

2016-09-30 08:14 UTC, maximebiloe commented
For example you commit message was "Update contact.xml" whereas it should be something link "IN: Danish translation for contact fixtures"