CO: Add new hook displayFullWidthTop
PrestaShop/PrestaShop pull request #6500
Opened 2016-09-27 09:59 UTC by iqit-commerce

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | Use the "develop" branch if you target PrestaShop 1.7; use the "1.6.1.x" branch if you target PrestaShop 1.6 (bugfixes only).
| Description?  | Please be specific when describing the PR. <br/> Every detail helps: versions, browser/server configuration, specific module/theme, etc.
| Type?         | bug fix / improvement / new feature
| Category?     | See [the Category list](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message#Howtowriteacommitmessage-Category), i.e.: BO
| BC breaks?    | Does it break backward compatibility? yes/no
| Deprecations? | Does it deprecate an existing feature? yes/no
| Fixed ticket? | (optional) If this PR fixes a [Forge](http://forge.prestashop.com/) ticket, please add its complete Forge URL.
| How to test?  | Please indicate how to best verify that this PR is correct.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

2016-09-29 09:15 UTC, xBorderie commented
Checks have failed. Could you rebase your PR in order to restart the tests?

2016-10-15 22:14 UTC, firstred commented
Almost same PR as https://github.com/PrestaShop/PrestaShop/pull/6500

2016-10-17 13:14 UTC, aleeks requested changes

2016-10-17 13:14 UTC, aleeks commented on install-dev/data/xml/hook.xml
> +    </hook>
Hello @iqit-commerce 

Missing sql update into 1.7.0.0.sql nop ?

INSERT INTO PREFIX_hook(name,title,description,position) VALUES ('displayFullWidthTop', 'Top of pages without width limitation.', 'This hook displays additional elements at the top of your pages without width limitation.', '1');

2016-10-18 12:51 UTC, Shudrum commented
Hi, thank you for your contribution.

I close as the #6691 is more useful for the same idea.

2016-10-18 12:51 UTC, closed without merging