Install emails pack
PrestaShop/PrestaShop pull request #6511
Opened 2016-09-28 08:01 UTC by maximebiloe

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | From now, we have email packs for 1.7 and no more using of 1.6 packs
| Type?         | improvement
| Category?     | 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1489
| How to test?  | Install in different languages and check for the presence of the right folder into `mails`. It should be okay when you import a language from your backoffice too. And finally, you should be able to change the order state when you're using french for example.

2016-09-28 11:49 UTC, PrestaEdit commented on classes/Language.php
> +    const EMAILS_LANGUAGE_PACK_URL = 'http://translate.prestashop.com/TEMP/TEMP/TEMP/TEMP/emails/%s.zip';
"TEMP/TEMP/TEMP/TEMP/" :laughing:

2016-09-28 12:09 UTC, maximebiloe commented on classes/Language.php
> +    const EMAILS_LANGUAGE_PACK_URL = 'http://translate.prestashop.com/TEMP/TEMP/TEMP/TEMP/emails/%s.zip';
Yeah we know. We are preparing the server to host the translation packs but it's not ready yet

2016-09-28 14:31 UTC, mickaelandrieu requested changes
More Symfony, less Legacy my friend :)

2016-09-28 14:31 UTC, mickaelandrieu commented on classes/Language.php
> +            $modules = scandir($folder.'/modules');
really ? can you use Finder component or `DirectoryIterator` please ?

```php
$finder = \Symfony\Component\Finder\Finder::create();
```

2016-09-28 14:31 UTC, mickaelandrieu commented on classes/Language.php
> +                        rename(
same for rename and mkdir stuff use Filesystem component :)

2016-09-28 14:31 UTC, mickaelandrieu commented on classes/Language.php
> +            Tools::deleteDirectory($folder);
same (Filesyystem)

2016-09-28 16:26 UTC, maximebiloe commented
@mickaelandrieu Thanks for the review. I've made the modifications

2016-09-28 22:41 UTC, mickaelandrieu commented on classes/Language.php
> +                        dump($moduleEmail->getRealpath(), $moduleDestPath.'/'.$moduleEmail->getFileName());
dump ? :)

2016-09-29 06:48 UTC, maximebiloe commented on classes/Language.php
> +                        dump($moduleEmail->getRealpath(), $moduleDestPath.'/'.$moduleEmail->getFileName());
😊

2016-09-29 06:50 UTC, maximebiloe commented on classes/Language.php
> +                        dump($moduleEmail->getRealpath(), $moduleDestPath.'/'.$moduleEmail->getFileName());
I don't know what you're talking about ^^

2016-09-30 14:53 UTC, aleeks commented
Goood gooood gooooood job !!!!! Thanks @maximebiloe

2016-09-30 14:53 UTC, merged