Check parent permissions when not ticked
PrestaShop/PrestaShop pull request #6539
Opened 2016-09-30 10:02 UTC by AntoineMille

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Check parent permissions when not ticked
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-871
| How to test?  | Tick a permission box and check if its unchecked parents get checked as well.

2016-09-30 15:23 UTC, maximebiloe requested changes

2016-09-30 15:23 UTC, maximebiloe commented on admin-dev/themes/default/template/controllers/access/helpers/form/form.tpl
> +      $('div.productTabs').find('a').each(function() {
Why are you adding the same above there is above?

2016-10-06 07:38 UTC, AntoineMille commented on admin-dev/themes/default/template/controllers/access/helpers/form/form.tpl
> +      $('div.productTabs').find('a').each(function() {
It's good now.

2016-10-07 06:42 UTC, maximebiloe approved these changes

2016-10-07 06:43 UTC, merged

2016-10-07 06:43 UTC, maximebiloe commented
Thank you!