CO : uninstall now can remove properties on multiple lines
PrestaShop/PrestaShop pull request #6541
Opened 2016-09-30 11:36 UTC by pkshetlie

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | ModuleCore::uninstall can now remove properties on multilines
| Type?         | bug fix / improvement / new feature (don't know the type)
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1596
| How to test?  | create a module who override a class and keep $definition property, install module, and next uninstall it.

Sorry, code is not realy sexy :(

2016-09-30 11:50 UTC, pkshetlie commented
edited

2016-10-12 22:00 UTC, firstred requested changes

2016-10-12 22:00 UTC, firstred commented on classes/module/Module.php
> +                        if(!preg_match("/(.*);$/i",trim($line_content))){
It seems that this does not match with the current coding standards: http://doc.prestashop.com/display/PS16/Coding+Standards

Would you mind changing it to:
`if (!preg_match("/(.*);$/i", trim($line_content))) {`

2016-10-12 22:00 UTC, firstred commented on classes/module/Module.php
> +                    }else if($multiline_property_deletion){
`} elseif ($multiline_property_deletion) {

2016-10-12 22:00 UTC, firstred commented on classes/module/Module.php
> +                        if(!$multiline_property_deletion) {
`if (!$multiline_property_deletion) {`

2016-10-17 09:44 UTC, pkshetlie reviewed
If you think it's better I agree.

2020-11-17 20:14 UTC, Arman-Hosseini commented
It has been a long time since the last update.

2020-11-18 15:24 UTC, PierreRambaud commented
This pull request is too old and has no activity for years
Feel free to reopen it if you think it's still relevant.
Kind regards

2020-11-18 15:24 UTC, closed without merging