CO: Add new hook displayAfterProductThumb
PrestaShop/PrestaShop pull request #6588
Opened 2016-10-05 09:58 UTC by iqit-commerce

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | There was 0 hooks on left side of product page. This PR change that
| Type?         |  improvement 
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | This PR requires a module hooked on displayAfterProductThumbs.

2016-10-05 10:47 UTC, PrestaEdit requested changes

2016-10-05 10:47 UTC, PrestaEdit commented on install-dev/data/xml/hook.xml
> +      <name>displayAfterProductThumbs</name><title>Display extra content below product thums</title><description>This hook displays new elements below product images ex. additonal media</description>
thums => thumbs

2016-10-15 21:50 UTC, firstred commented
Hi, could you please add the hook to the upgrade script, like: https://github.com/PrestaShop/PrestaShop/pull/6691/commits/729d221d0652493a11b9a0ef40280d80d1d6cb93

Thank you!

2017-02-01 15:13 UTC, julienbourdeau commented
I think it should be moved after the closing div tag.

2017-02-03 16:50 UTC, aleeks commented
Hello @iqit-commerce 
I'm closing your PR because your job has been merged on the other PR.
Thank you for your contribution!

2017-02-03 16:50 UTC, closed without merging