Move facets update behaviour
PrestaShop/PrestaShop pull request #6609
Opened 2016-10-07 13:59 UTC by nihco2

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Move facets update behaviour
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | (optional)
| How to test?  | Check if facets filter works properly

2016-10-07 14:01 UTC, nihco2 commented
ping @julienbourdeau

2016-10-10 12:15 UTC, maximebiloe requested changes

2016-10-10 12:15 UTC, maximebiloe commented on themes/classic/_dev/js/product.js
> +  $('body').on(
This code has been removed here: https://github.com/PrestaShop/PrestaShop/pull/6605
I think you have failed a rebase 😉

2016-10-10 15:18 UTC, maximebiloe approved these changes

2016-10-10 15:30 UTC, merged