Do not fallback on english value on translation page and tokenize the edit URL
PrestaShop/PrestaShop pull request #6658
Opened 2016-10-11 15:33 UTC by maximebiloe

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Do not fallback on english value on translation page when the string is not translated and display a warning. Also tokenize the URL to edit the translations.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1632
| How to test?  | Just check the forge ticket

2016-10-12 07:08 UTC, aleeks commented on src/PrestaShopBundle/Twig/TranslationsExtension.php
> +    public function __construct($container, $router)
Can you add a type to your `$container` and `$router` ?

2016-10-12 14:52 UTC, mickaelandrieu requested changes

2016-10-12 14:52 UTC, mickaelandrieu commented on src/PrestaShopBundle/Twig/TranslationsExtension.php
> +    private $container;
This should be templating

2016-10-12 14:52 UTC, mickaelandrieu commented on src/PrestaShopBundle/Translation/Factory/ThemeTranslationsFactory.php
> +                    'xlf' => $translationKey != $translationValue ? $translations[$domain][$translationKey] : '',
If we do that, there is no more value to load the default catalogue

2016-10-12 14:52 UTC, mickaelandrieu commented on src/PrestaShopBundle/Translation/Factory/TranslationsFactory.php
> +                            'xlf' => $translationKey != $translationValue ? $translations[$domain][$translationKey] : '',
Ok, but this behavior need to be unit tested

2016-10-12 14:55 UTC, aleeks commented on src/PrestaShopBundle/Twig/TranslationsExtension.php
> +    private $container;
Oh yep, I forget that. Nice said! @mickaelandrieu

2016-10-12 15:58 UTC, thierrymarianne commented on src/PrestaShopBundle/Twig/TranslationsExtension.php
> +    private $container;
@mickaelandrieu It can not be as it would introduce a circular dependency exception (in the context of a Twig extension).

2016-10-12 16:20 UTC, maximebiloe commented on src/PrestaShopBundle/Translation/Factory/ThemeTranslationsFactory.php
> +                    'xlf' => $translationKey != $translationValue ? $translations[$domain][$translationKey] : '',
Yes, we need the default catalogue in case we have set custom translations and we want to reset to the default ones.

2016-10-13 09:54 UTC, mickaelandrieu commented on src/PrestaShopBundle/Twig/TranslationsExtension.php
> +    private $container;
fair enough ;)

2016-10-13 09:54 UTC, mickaelandrieu approved these changes

2016-10-13 09:56 UTC, merged

2016-10-13 09:56 UTC, thierrymarianne commented
Thank you @maximebiloe