Fixed minimal quantity check in cart
PrestaShop/PrestaShop pull request #6660
Opened 2016-10-11 16:17 UTC by thierrymarianne

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | The minimal product quantity in cart is not always applied
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1640
| How to test?  | Update the minimal quantity of a product and check it is properly applied in cart

2016-10-11 16:26 UTC, maximebiloe requested changes

2016-10-11 16:26 UTC, maximebiloe commented on controllers/front/CartController.php
> +                'quantity' => $productQuantity
Missing the last comma

2016-10-11 16:26 UTC, maximebiloe commented on controllers/front/CartController.php
> +                'quantity' => $productQuantity
Same here

2016-10-12 07:17 UTC, thierrymarianne commented on controllers/front/CartController.php
> +                'quantity' => $productQuantity
Fixed. Thanks.

2016-10-12 07:17 UTC, thierrymarianne commented on controllers/front/CartController.php
> +                'quantity' => $productQuantity
Fixed

2016-10-12 09:40 UTC, dSkrbic commented
Q&A test: 
Not fully correct, see added video in LaForge BOOM-1306
Suppressing Q&A approbation label

2016-10-14 12:55 UTC, aleeks commented
Maxime's requests are ok!

Thank you @thierrymarianne !

2016-10-14 12:56 UTC, merged