Fix ajax refresh for listing pages
PrestaShop/PrestaShop pull request #6674
Opened 2016-10-13 07:28 UTC by julienbourdeau

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Some data weren't updated properly + markup was in core.js instead of theme.js
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? |
| How to test?  | Use the faceted search in the sidebar and see if it works

2016-10-14 13:36 UTC, aleeks commented
@julienbourdeau can you rebase please, i'm sorry!

2016-10-17 07:30 UTC, maximebiloe commented
Don't forget to report it on `StarterTheme` please

2016-10-17 12:16 UTC, aleeks requested changes

2016-10-17 12:16 UTC, aleeks commented on themes/classic/templates/catalog/_partials/products.tpl
> +      Back to top
@julienbourdeau  Where is my translation! :smiling_imp:

2016-10-17 12:21 UTC, mickaelandrieu commented on themes/classic/templates/catalog/_partials/products.tpl
> +      Back to top
Shame on you 😈 !

2016-10-17 13:58 UTC, aleeks approved these changes

2016-10-17 14:45 UTC, aleeks commented
thank you @julienbourdeau  !

2016-10-17 14:45 UTC, merged