Provided with theme translations and overrides
PrestaShop/PrestaShop pull request #6690
Opened 2016-10-14 14:11 UTC by thierrymarianne

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Theme translations lack messages from Shop* and Module* domains and should not be removed and replaced with extractions from templates.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1633
| How to test?  | Translations should contain messages from default catalogues, Shop*, Module* domains, parsed templates and theme translations directory in this order

2016-10-17 07:58 UTC, mickaelandrieu requested changes
Some things are totaly NOT required, let's discuss :)

2016-10-17 07:58 UTC, mickaelandrieu commented on src/PrestaShopBundle/Translation/Loader/SqlTranslationLoader.php
> +        $translations = Db::getInstance()->executeS($selectTranslationsQuery);
it's probably too late, but any chance to drop ``Db`` from any "Symfony" classes ? Maybe using DBAL ?

2016-10-17 07:58 UTC, mickaelandrieu commented on src/PrestaShopBundle/Translation/Provider/FrontOfficeProvider.php
> +        return parent::getDatabaseCatalogue('classic');
Isn't risky to rely on a string instead on ``\Adapter\Theme``  class ?

2016-10-17 07:58 UTC, mickaelandrieu commented on src/PrestaShopBundle/Translation/Provider/ThemeProvider.php
> +    public function getDatabaseCatalogue($theme = null)
same as before ... but very weird (you dont use ``$theme``), you should rely on Objects instead of strings

2016-10-17 07:58 UTC, mickaelandrieu commented on src/PrestaShopBundle/Translation/Provider/ThemeProvider.php
> +    public function synchronizeTheme()
👍 thank you for this little refactoring

2016-10-17 07:58 UTC, mickaelandrieu commented on src/PrestaShopBundle/Twig/TranslationsExtension.php
> +    public function getTranslationsTree(array $translationsTree, $theme = null)
ok, I think I can be more easy with theme as a string **if** we call it ``$themeName``: WDYT ?

2016-10-17 07:58 UTC, mickaelandrieu commented on src/PrestaShopBundle/Translation/Provider/ThemeProvider.php
> +        if (!$this->filesystem->exists($resourceDirectory)) {
You don't need to do the check http://symfony.com/doc/current/components/filesystem.html#mkdir :)

2016-10-17 08:49 UTC, thierrymarianne commented on src/PrestaShopBundle/Translation/Provider/ThemeProvider.php
> +    public function getDatabaseCatalogue($theme = null)
Signatures of methods should be the same for classes extending one another.

2016-10-17 08:53 UTC, thierrymarianne commented on src/PrestaShopBundle/Translation/Provider/FrontOfficeProvider.php
> +        return parent::getDatabaseCatalogue('classic');
I don't need an instance of Theme but I will replace it with `_PS_DEFAULT_THEME_NAME_`

2016-10-17 09:10 UTC, mickaelandrieu commented on src/PrestaShopBundle/Translation/Provider/ThemeProvider.php
> +    public function getDatabaseCatalogue($theme = null)
fair enough

2016-10-17 09:19 UTC, thierrymarianne commented on src/PrestaShopBundle/Translation/Loader/SqlTranslationLoader.php
> +        $translations = Db::getInstance()->executeS($selectTranslationsQuery);
Instances of `SqlTranslationLoader` being also required in legacy `Context`, DBAL would not always be available to execute these queries.

2016-10-17 12:16 UTC, mickaelandrieu commented on src/PrestaShopBundle/Translation/Loader/SqlTranslationLoader.php
> +        $translations = Db::getInstance()->executeS($selectTranslationsQuery);
hmmm ... :(

2016-10-17 12:16 UTC, mickaelandrieu approved these changes

2016-10-18 15:40 UTC, mickaelandrieu commented
@thierrymarianne tests dont pass :p

2016-10-19 07:31 UTC, thierrymarianne commented
@mickaelandrieu They require https://github.com/PrestaShop/TranslationToolsBundle/pull/21

2016-10-19 09:43 UTC, merged

2016-10-19 09:43 UTC, aleeks commented
Thank you @thierrymarianne !