Rename the productDisplayButtons hook to productDisplayExtra
PrestaShop/PrestaShop pull request #6712
Opened 2016-10-18 13:47 UTC by antoin-m

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Rename the productDisplayButtons hook to productDisplayExtra
| Type?         | improvment
| Category?     | BO & FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  |

2016-10-18 13:52 UTC, aleeks requested changes

2016-10-18 13:52 UTC, aleeks commented on install-dev/data/xml/hook.xml
> +    <hook id="displayProductExtra">
Need to 1.7.0.0 sql 

UPDATE `PREFIX_hook` SET `name` = 'displayProductExtra' WHERE `name` = 'displayProductButtons';

!

2016-10-18 13:53 UTC, aleeks requested changes
Need to report on StarterTheme ?

2016-10-18 13:55 UTC, Quetzacoalt91 commented
Maybe it would be better to find another hook name.

On the PR #6216, we introduced a new hook  displayProductExtra**Content**, which has almost the same description. 😉

2016-10-18 14:00 UTC, antoin-m commented
@Quetzacoalt91 the name is the result of a long brainstorming with @julienbourdeau and @maximebiloe . :stuck_out_tongue: 

Do you have something to propose?

2016-10-18 15:09 UTC, Quetzacoalt91 commented
I don't know for the moment, you made the brainstorming 😆 .

As far as I understand, you modified the hook to make it generic.
However, I almost had this discussion with both @maximebiloe and @julienbourdeau a month ago, which brought the hook I just talked about. And they are almost the same! The only difference is the place where we display it.

Guys, did you already forget ?

2016-10-18 17:09 UTC, maximebiloe commented
To be honest, yeah I had forget the hook name 🐟 
@antoin-m & @Quetzacoalt91 what do you think of `displayProductAdditionalInfos`? It's similar with the hook previously added by @Quetzacoalt91 but a little bit more different.

2016-10-18 17:20 UTC, Quetzacoalt91 commented
Yeah, `displayProductAdditionalInfos`, is okay! Or we just need something after the Extra word. We could try `displayProductExtraSummary` ...

2016-10-24 14:25 UTC, Quetzacoalt91 commented
Was the hook `displayProductButtons` existing on PS 1.6 ? I think we should  add an alias displayProductButtons -> displayProductAdditionalInfos

2016-10-24 14:34 UTC, antoin-m commented
@Quetzacoalt91 done :alien:

2016-10-24 15:11 UTC, Quetzacoalt91 approved these changes

2016-10-27 07:06 UTC, maximebiloe commented
Okay for me. Need to be reported on `debug`

2016-10-27 07:07 UTC, aleeks approved these changes

2016-11-02 13:14 UTC, aleeks commented
When this PR will be merge, please, change hook on ps_viewedproduct module!

2017-01-10 17:22 UTC, maximebiloe commented
Thank you @antoin-m 
We finally merge it!

2017-01-10 17:22 UTC, merged