Integrate edit translations view
PrestaShop/PrestaShop pull request #6724
Opened 2016-10-19 16:22 UTC by thierrymarianne

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Integrate edit translations view
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | N/A
| How to test?  | Go to translation > international page

2016-10-19 16:43 UTC, aleeks reviewed
All your px value in rem() ?

2016-10-19 16:48 UTC, maximebiloe requested changes

2016-10-19 16:48 UTC, maximebiloe commented on admin-dev/themes/new-theme/scss/pages/_translation_page.scss
> +    cursor: pointer;
isn't any helper in the ui-kit to display buttons?

2016-10-19 16:48 UTC, maximebiloe commented on admin-dev/themes/new-theme/scss/pages/_translation_page.scss
> +    font-size: 14px;
why don't you use the defined variables for font-size?

2016-10-19 16:48 UTC, maximebiloe commented on src/PrestaShopBundle/Controller/Admin/TranslationsController.php
> +                'theme' => $theme
Missing the last comma 😉

2016-10-19 16:48 UTC, maximebiloe commented on src/PrestaShopBundle/Controller/Admin/TranslationsController.php
> +                'theme' => $theme
idem

2016-10-19 16:48 UTC, maximebiloe commented on src/PrestaShopBundle/Controller/Admin/TranslationsController.php
> +            'translations_tree' => $translationsTreeView
idem

2016-10-19 16:48 UTC, maximebiloe commented on src/PrestaShopBundle/Resources/views/Admin/Translations/include/translations-tree.html.twig
> +    <span>Expand all</span>
Missing `trans`, no?

2016-10-19 16:48 UTC, maximebiloe commented on src/PrestaShopBundle/Resources/views/Admin/Translations/include/translations-tree.html.twig
> +    <span>Reduce all</span>
Same here

2016-10-19 16:48 UTC, maximebiloe commented on src/PrestaShopBundle/Resources/views/Admin/Translations/list.html.twig
> +        <span class="name">Translation domain</span>
Missing `trans` also

2016-10-20 07:47 UTC, thierrymarianne commented on src/PrestaShopBundle/Resources/views/Admin/Translations/list.html.twig
> +        <span class="name">Translation domain</span>
This one is only placeholder. I'll remove the default text

2016-10-20 08:47 UTC, AlexEven commented on src/PrestaShopBundle/Resources/views/Admin/Translations/include/translations-tree.html.twig
> +    <span>{{ 'Expand all'|trans({}, 'Admin.International.Feature') }}</span>
Please use "Admin.Actions" for the domain

2016-10-20 08:48 UTC, AlexEven commented on src/PrestaShopBundle/Resources/views/Admin/Translations/include/translations-tree.html.twig
> +    <span>{{ 'Reduce all'|trans({}, 'Admin.International.Feature') }}</span>
My mistake I gave the wrong wording, we use "Collapse all" in other pages.
Can you please change and use "Admin.Actions"? Thanks.

2016-10-20 09:34 UTC, AlexEven commented on src/PrestaShopBundle/Resources/views/Admin/Translations/list.html.twig
> +  <h2>{{ 'Search translation key or value'|trans({}, 'Admin.Actions') }}</h2>
Content isn't matching the one from the mock-ups and domain should be Admin.International.Feature
Admin.Actions is to be used for actions that you can find on others pages. This one is specific to the translation page.

Should be
{{ 'Search translations:'|trans({}, 'Admin.International.Feature') }}

2016-10-20 09:34 UTC, AlexEven commented on src/PrestaShopBundle/Resources/views/Admin/Translations/list.html.twig
> +  <h2>{{ 'Search translations'|trans({}, 'Admin.Actions') }}</h2>
Admin.International.Feature

Admin.Actions is for general actions that can be found on every pages. This is specific to translations.

2016-10-20 09:34 UTC, AlexEven commented on src/PrestaShopBundle/Resources/views/Admin/Translations/list.html.twig
> +             placeholder="{{ 'Search a word or expression, e.g.: \"Order confirmation\"'|trans({}, 'Admin.International.Feature') }}"
Admin.International.Help

(placeholder are considered help text)

2016-10-20 09:34 UTC, AlexEven commented on src/PrestaShopBundle/Resources/views/Admin/Translations/list.html.twig
> +    <span>{{ '0 result found'|trans({}, 'Admin.Notifications.Error') }}</span>
'No results found'

2016-10-20 09:34 UTC, AlexEven commented on src/PrestaShopBundle/Twig/TranslationsExtension.php
> +                $this->translator->trans('{{ translations }} missing',
why not using %variable% ?
I'm afraid it will be confusing to translators.
I'd use something like %nb_translations%

2016-10-20 09:34 UTC, AlexEven commented on src/PrestaShopBundle/Twig/TranslationsExtension.php
> +                        $this->translator->trans('Show messages', array(), 'Admin.International.Feature') .
Where is the "Hide messages"?

2016-10-20 09:36 UTC, thierrymarianne commented on src/PrestaShopBundle/Twig/TranslationsExtension.php
> +                        $this->translator->trans('Show messages', array(), 'Admin.International.Feature') .
There is no `Hide messages`, moreover the `Show messages` button is not visible anymore even though it is used under the hood.

2016-10-20 09:39 UTC, AlexEven commented
Thank you Thierry!
I have other comments ^^

1 - We have only two domains levels, I think we mentioned 3 levels.
Ex. In BO, Admin, today we have

Admin > AdvParametersFeature
Admin > AdvParametersHelp
Admin > AdvParametersNotifications

We should have

Admin > AdvParameters > Feature
Admin > AdvParameters > Help
Admin > AdvParameters > Notifications.

Like we had before I think.

2 - I have a weird display for Back Office > Modules > CheckPaymentAdmin - when I click twice on the category

<img width="787" alt="2016-10-20_1127" src="https://cloud.githubusercontent.com/assets/7910738/19554575/8935509a-96b9-11e6-98ff-46b1e0328257.png">

3. Why not using the full page?
<img width="1056" alt="2016-10-20_1138" src="https://cloud.githubusercontent.com/assets/7910738/19554640/d408cdc2-96b9-11e6-99b7-ff42ba3168e7.png">


I haven't tested if translations are still saved etc, but as it's not the purpose of the PR, we'll say it's ok :)
Thanks!

2016-10-20 09:47 UTC, thierrymarianne commented
Going from two levels to three levels can't be done with ease at this point. 
I will fix 2.

2016-10-20 09:59 UTC, thierrymarianne commented on src/PrestaShopBundle/Resources/views/Admin/Translations/list.html.twig
> +             placeholder="{{ 'Search a word or expression, e.g.: \"Order confirmation\"'|trans({}, 'Admin.International.Feature') }}"
Fixed

2016-10-20 09:59 UTC, thierrymarianne commented on src/PrestaShopBundle/Resources/views/Admin/Translations/list.html.twig
> +  <h2>{{ 'Search translations'|trans({}, 'Admin.Actions') }}</h2>
Fixed

2016-10-20 09:59 UTC, thierrymarianne commented on src/PrestaShopBundle/Resources/views/Admin/Translations/list.html.twig
> +    <span>{{ '0 result found'|trans({}, 'Admin.Notifications.Error') }}</span>
Fixed

2016-10-20 10:00 UTC, thierrymarianne commented on src/PrestaShopBundle/Twig/TranslationsExtension.php
> +                $this->translator->trans('{{ translations }} missing',
Fixed

2016-10-20 10:00 UTC, AlexEven commented on src/PrestaShopBundle/Twig/TranslationsExtension.php
> +                        $this->translator->trans('Show messages', array(), 'Admin.International.Feature') .
I meant this "Hide messages" - I couldn't see it, only "Show messages"

![image](https://cloud.githubusercontent.com/assets/7910738/19555323/a32925e6-96bc-11e6-9334-afd6cb0eba6c.png)

Thanks!

2016-10-20 10:06 UTC, maximebiloe approved these changes

2016-10-20 10:08 UTC, thierrymarianne commented on src/PrestaShopBundle/Twig/TranslationsExtension.php
> +                        $this->translator->trans('Show messages', array(), 'Admin.International.Feature') .
Ok, thanks.

2016-10-20 13:07 UTC, aleeks commented
Big thanks! @thierrymarianne

2016-10-20 13:07 UTC, merged