Add multiple feature with the same type but different values to product
PrestaShop/PrestaShop pull request #6888
Opened 2016-11-02 16:45 UTC by fatmaBouchekoua

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | If you create a product which has the same feature twice when you reload the page the first one disappears. This PR add the possibility to create feature more than once.
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-858
| How to test?  | Reinstall Prestashop, then add the same feature to a product more than once in the BO, Go to the FO and check the product details you will see all features in the same table line.

2016-11-02 18:48 UTC, aleeks requested changes

2016-11-02 18:48 UTC, aleeks commented on controllers/admin/AdminProductsController.php
> +                        dump($this->checkFeatures($languages, $match[1]));
Hello, dump here!

2016-11-02 18:49 UTC, aleeks requested changes

2016-11-02 18:49 UTC, aleeks commented on install-dev/data/db_structure.sql
> +  PRIMARY KEY (`id_feature`,`id_product`,`id_feature_value`),
Need to update in 1.7.0.0.sql file

2016-11-03 10:34 UTC, xBorderie commented
I think you should try and remove the Merge commit -- maybe git-squash it?

2016-11-04 09:13 UTC, fatmaBouchekoua commented
See #6907

2016-11-04 09:13 UTC, closed without merging