Add missing hook actionDeleteProductInCartAfter
PrestaShop/PrestaShop pull request #6965
Opened 2016-11-14 10:45 UTC by antoin-m

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | The hook 'actionDeleteProductInCartAfter' didn't exist in the database
| Type?         | bug fix
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1801
| How to test?  | Hook a module on 'actionDeleteProductInCartAfter' and remove a product from your cart.

Since actionDeleteProductInCartAfter is called [here](https://github.com/PrestaShop/PrestaShop/blob/develop/controllers/front/CartController.php#L245) but is never created via hook.xml and is not a generated one (like actionDeleteProductAfter) then it can't be called.

2016-11-14 12:58 UTC, aleeks requested changes

2016-11-14 12:58 UTC, aleeks commented on install-dev/upgrade/sql/1.7.0.1.sql
> +  ('actionDeleteProductInCartAfter', 'Cart product removal', 'This hook is called when a product is removed from a cart', '1'),
Need ; at the end, not a coma!

2016-11-14 13:02 UTC, antoin-m commented on install-dev/upgrade/sql/1.7.0.1.sql
> +  ('actionDeleteProductInCartAfter', 'Cart product removal', 'This hook is called when a product is removed from a cart', '1'),
:chicken:

2016-11-15 08:11 UTC, aleeks approved these changes

2016-12-16 09:16 UTC, aleeks commented
@antoin-m, please rebase Rebase :scream:

2017-01-11 19:36 UTC, aleeks commented
Hello @antoin-m 
Can you rebase this ?

@vincentbz can you check if this BOOM is ok  please ?!

Thanks both of you!

2017-01-11 19:42 UTC, antoin-m commented
I'll do it tomorrow. Please go home now :)

2017-01-13 15:51 UTC, xBorderie commented
![captureghtomorrow](https://cloud.githubusercontent.com/assets/2833749/21936054/1886ecf2-d9b0-11e6-908c-6169e793d31d.PNG)

ಠ~ಠ

2017-01-13 15:54 UTC, aleeks commented
ahah

2017-01-13 15:55 UTC, antoin-m commented
On Wednesdays "tomorrow" means Monday! :P

2017-01-16 15:28 UTC, antoin-m commented
MERGE IT WHILE IT'S GREEN! @aleeks

2017-01-16 15:58 UTC, aleeks commented
Thank you bro !

2017-01-16 15:58 UTC, merged

2018-10-16 15:07 UTC, musaffar-patel commented
Was this ever fixed?  The hook "actionDeleteProductInCartAfter" still does not seem to be getting triggered when a product is deleted from the cart.  Testing in Prestashop 1.7.4.0