Fixed product permissions
PrestaShop/PrestaShop pull request #7024
Opened 2016-11-17 15:36 UTC by thierrymarianne

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.0.x
| Description?  | Fix product permissions 
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1840
| How to test?  | Try to create, edit, delete, duplicate, deactivate, activate product in bulk mode or not without having been granted the "add", "modify", "delete" permissions. Those actions should fail for employees without required permissions.

2016-11-17 16:40 UTC, mickaelandrieu commented on src/PrestaShopBundle/Controller/Admin/ProductController.php
> +            $translator = $this->container->get('translator');
```diff
- $this->container->get(
+ $this->get(
```

2016-11-18 08:34 UTC, AlexEven commented on src/PrestaShopBundle/Controller/Admin/ProductController.php
> +            $errorMessage = $translator->trans(
Do you we need the trans method here?
What will be sent to Crowdin?

2016-11-18 08:35 UTC, AlexEven commented on src/PrestaShopBundle/Controller/Admin/ProductController.php
> +                'You do not have permission to modify this.',
Could it be "You do not have permission to edit this."?
(to avoid creating a new string)
Thanks!

2016-11-18 08:36 UTC, AlexEven commented
Hello, I've left a few comments. Domains are ok. Thanks!

2016-11-18 15:10 UTC, aleeks commented
See : https://github.com/PrestaShop/PrestaShop/pull/7030

2016-11-23 12:44 UTC, aleeks requested changes

2016-11-23 12:44 UTC, aleeks commented on src/PrestaShopBundle/Controller/Admin/ProductController.php
> +                $this->getForbiddenActionMessage($action),
Hello problem here. I put it on WIP, see with you

2016-12-02 09:55 UTC, aleeks approved these changes

2016-12-05 14:39 UTC, merged

2016-12-05 14:40 UTC, maximebiloe commented
Thank you @thierrymarianne! 🎅🏻