Add translation domains to Adv. param controllers 2
PrestaShop/PrestaShop pull request #7025
Opened 2016-11-17 17:23 UTC by AlexEven

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop.
| Description?  | Adding translation domains.
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | NA
| How to test?  | Check translation catalog export.

2016-11-17 17:38 UTC, mickaelandrieu requested changes
Some little typos to address, good job @AlexEven :)

2016-11-17 17:38 UTC, mickaelandrieu commented on controllers/admin/AdminEmployeesController.php
> +                            '%email%' => $obj->email
comma is missing :)

```diff
- '%email%' => $obj->email
+ '%email%' => $obj->email,
```

2016-11-17 17:38 UTC, mickaelandrieu commented on controllers/admin/AdminEmployeesController.php
> +                        'Admin.AdvParameters.Help'
Same here

2016-11-17 17:38 UTC, mickaelandrieu commented on controllers/admin/AdminEmployeesController.php
> +                        'label' => $this->trans('-- Choose --', array(), 'AdvParameters.Help')
Same here (for every item of an array, you need to finish by a comma)

2016-11-17 17:38 UTC, mickaelandrieu commented on controllers/admin/AdminRequestSqlController.php
> +            'sql' => array('title' => $this->trans('SQL query', array(), 'Admin.AdvParameters.Feature'))
```diff
- 'Admin.AdvParameters.Feature'))
+ 'Admin.AdvParameters.Feature')),
```

2016-11-18 09:52 UTC, AlexEven commented
Thanks for the review @mickaelandrieu!

2016-11-18 12:52 UTC, mickaelandrieu approved these changes

2016-12-20 13:40 UTC, aleeks commented
Thank you @AlexEven :bouquet:

2016-12-20 13:41 UTC, merged