Fix sprintf call in AdminCustomers
PrestaShop/PrestaShop pull request #7122
Opened 2016-11-29 19:59 UTC by prestamodule

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | As now, the %s is replaced with "htmlspecialchars"
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Check the Pull Request and edit a customer.

2016-11-30 09:06 UTC, xBorderie commented
Thanks! It seems to also happen in the Theme page :/
http://forge.prestashop.com/browse/BOOM-1896
ping @AlexEven

2016-11-30 15:41 UTC, antoin-m requested changes

2016-11-30 15:41 UTC, antoin-m commented on controllers/admin/AdminCustomersController.php
> +                    $this->toolbar_title[] = sprintf($this->trans('Information about customer %s', array('%s' => Tools::substr($customer->firstname, 0, 1).'. '.$customer->lastname), 'Admin.OrdersCust
You may want to remove the call to `sprintf` if there is no need for it.

2016-11-30 15:41 UTC, antoin-m commented on controllers/admin/AdminCustomersController.php
> +                    $this->toolbar_title[] = sprintf($this->trans('Editing customer %s.', array('%s' => Tools::substr($customer->firstname, 0, 1).'. '.$customer->lastname), 'Admin.OrdersCustomers.Fea
You may want to remove the call to `sprintf` if there is no need for it.

2016-11-30 15:41 UTC, antoin-m commented on controllers/admin/AdminCustomersController.php
> +                        sprintf($this->trans('Password should be at least %s characters long.', array('%s' => Validate::PASSWORD_LENGTH), 'Admin.OrdersCustomers.Help')))
You may want to remove the call to `sprintf` if there is no need for it.

2016-12-05 15:47 UTC, maximebiloe commented
Same as here: https://github.com/PrestaShop/PrestaShop/pull/7124

Could you test this one? https://github.com/PrestaShop/PrestaShop/pull/7087

2016-12-05 16:52 UTC, PrestaEdit commented
Hi @maximebiloe 

It's seems not working with the PR you mention...

2017-01-16 15:41 UTC, maximebiloe commented
Hello @prestamodule,

The PR https://github.com/PrestaShop/PrestaShop/pull/7194 solve the "htmlspecialchars" issue, so this one is no longer needed.
Thank you for your help.

Regards

2017-01-16 15:41 UTC, closed without merging