BO: fix sprintf call in AdminThemesController
PrestaShop/PrestaShop pull request #7124
Opened 2016-11-30 09:11 UTC by prestamodule

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | As now, the %s is replaced with "htmlspecialchars"
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1896
| How to test?  | Check the Pull Request and select a theme.

2016-11-30 15:44 UTC, antoin-m requested changes

2016-11-30 15:44 UTC, antoin-m commented on controllers/admin/AdminThemesController.php
> +                'title' => sprintf($this->trans('Select a theme for the "%s" shop', array('%s' => $this->context->shop->name), 'Admin.Design.Feature')),
You may want to remove the call to `sprintf` if there is no need for it.

2016-12-05 15:44 UTC, maximebiloe commented
Hello @prestamodule,

The PR https://github.com/PrestaShop/PrestaShop/pull/7087 should solve issue more globally.
Could you test it and let us know?

Regards

2016-12-05 16:52 UTC, PrestaEdit commented
Hi @maximebiloe 

It's seems not working with the PR you mention...

2017-01-16 15:40 UTC, maximebiloe commented
Hello @prestamodule,

The PR https://github.com/PrestaShop/PrestaShop/pull/7194 solve the "htmlspecialchars" issue, so this one is no longer needed.
Thank you for your help.

Regards

2017-01-16 15:40 UTC, closed without merging