FO: Fix send to multiple addresses with different names
PrestaShop/PrestaShop pull request #7148
Opened 2016-12-02 16:17 UTC by Flowster

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | In the foreach loop the array $toName is reaffected with its first value on the first pass. On the second pass it is reaffected with the second character of this value. Solved by changing the name of the value inside the loop.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? |
| How to test?  | use the Mail::Send function with an array for the $to parameter and another array for $toName parameter

2016-12-02 16:21 UTC, Flowster commented
Should I PR this change to 1.6 branch too?

2016-12-06 14:23 UTC, maximebiloe commented
1.6 PR here: https://github.com/PrestaShop/PrestaShop/pull/7152

2017-02-07 14:36 UTC, antoin-m requested changes

2017-02-07 14:36 UTC, antoin-m commented on classes/Mail.php
> +                $addrName = (($toName == null || $toName == $addr) ? '' : self::mimeEncode($toName));
How come you reassign `$addrName` here? The above if doesn't do anything if the variable isn't used between 2 assignments?

2017-02-07 15:08 UTC, Flowster commented
@antoin-m you're right I forgot to change some lines. Here is a new commit.

2017-02-07 15:10 UTC, antoin-m commented
@Flowster Great! Could you squash your commits? We don't like having duplicates :smile: 

@maximebiloe What do you think about it?

2017-02-07 15:11 UTC, antoin-m approved these changes

2017-02-07 16:34 UTC, merged

2017-02-07 16:34 UTC, antoin-m commented
Great! Thank you @Flowster ! :koala: