Add error message when ordering number of item greater than quantity
PrestaShop/PrestaShop pull request #7162
Opened 2016-12-05 14:17 UTC by fatmaBouchekoua

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | When ordering a number of item greater than quantity, there is no error message
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1965
| How to test?  | Go to product detail page and add to card a number of item grater than quantity.

2016-12-05 15:05 UTC, maximebiloe requested changes

2016-12-05 15:05 UTC, maximebiloe commented on themes/classic/templates/catalog/_partials/product-add-to-cart.tpl
> +              {else}
Shouldn't be done in the presenter?
No more calculation into templates :wink:

2016-12-07 15:51 UTC, maximebiloe requested changes

2016-12-07 15:51 UTC, maximebiloe commented on src/Core/Product/ProductPresenter.php
> +                        $presentedProduct['availability_message'] = 'Out of stock';
It's not really the same thing that "out of stock", it's more something like "we don't have enough products in stock".
Also, you forgot to make the string translatable.

2016-12-07 15:57 UTC, fatmaBouchekoua commented on src/Core/Product/ProductPresenter.php
> +                        $presentedProduct['availability_message'] = 'Out of stock';
Done, Thanks!

2016-12-07 16:46 UTC, maximebiloe approved these changes

2016-12-29 13:58 UTC, merged

2016-12-29 13:58 UTC, maximebiloe commented
Thank you @fatmaBouchekoua

2017-02-14 16:40 UTC, zapto commented
Doesnt work if stock management disabled. You cant add products...