BO: Add counter to the inputs
PrestaShop/PrestaShop pull request #7287
Opened 2016-12-30 13:06 UTC by AntoineMille

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add counter to the inputs
| Type?         | new feature
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-962
| How to test?  | Go to the product page, in the seo category and see if there is the counter on the inputs meta-title and meta-description.

2016-12-30 13:13 UTC, mickaelandrieu commented on src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/form_div_layout.html.twig
> +  {% if attr.counter is defined %}
You may use a macro for it: http://twig.sensiolabs.org/doc/tags/macro.html#macro

2016-12-30 13:15 UTC, mickaelandrieu commented on admin-dev/themes/new-theme/js/product-page/attributes.js
> +      if (typeof attr === typeof undefined || attr === false) {
```diff
- typeof attr === typeof undefined
+ typeof attr === "undefined"
```

2017-01-02 08:08 UTC, aleeks commented on admin-dev/themes/new-theme/scss/pages/_product_page.scss
> +    font-size: 10px;
10px is very very small nope ?
![lea](https://cloud.githubusercontent.com/assets/9074610/21585967/e0b4b180-d0ca-11e6-92bf-d5e5bced061d.png)

ping @Leadesign

2017-01-02 08:12 UTC, aleeks requested changes

2017-01-02 08:12 UTC, aleeks commented on admin-dev/themes/new-theme/js/product-page/attributes.js
> +      if (typeof attr === typeof undefined || attr === false) {
Why not an each on `.form-control input[counter=*]` or something like that ? because, some page have so mush form-control... ? WDYT

2017-01-02 09:29 UTC, aleeks commented on admin-dev/themes/new-theme/scss/pages/_product_page.scss
> +    font-size: 10px;
Ok for 12px @AntoineMille , thanks to change it. @Leadesign is ok.

2017-01-05 12:24 UTC, aleeks approved these changes

2017-01-05 16:53 UTC, basma-yangui-prestashop commented
@AntoineMille 
According to @vincentbz , the number of characters of the meta title input should be 70 and not 60.
Could you please correct it?

2017-01-05 17:13 UTC, mickaelandrieu commented
@basma-yangui-prestashop done ;)

2017-01-05 17:32 UTC, basma-yangui-prestashop commented
Thank you @mickaelandrieu !

2017-01-05 18:44 UTC, merged