CO: Changed Tools::displayError to $this->trans
PrestaShop/PrestaShop pull request #7288
Opened 2016-12-31 10:47 UTC by psandmore

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Changed Tools::displayError to $this->trans
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | check code

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

2017-01-02 13:58 UTC, mickaelandrieu commented
C'mon @psandmore, take a look to the screenshot :/

2017-01-02 14:19 UTC, psandmore commented
Mickaël, what screenshot?

2017-01-17 16:13 UTC, antoin-m commented
@psandmore I think @mickaelandrieu is talking about @prestonBot 's screenshot

2017-01-17 16:14 UTC, antoin-m requested changes

2017-01-17 16:14 UTC, antoin-m commented on controllers/admin/AdminCartsController.php
> +                    $errors[] = sprintf($this->trans('You must add a minimum quantity of %d', array(), 'Admin.Catalog.Notification'), $minimal_qty);
You shouldn't keep a `sprintf` around a `$this->trans`. Please use the second parameter of `$this->trans`

2017-01-17 17:29 UTC, psandmore commented on controllers/admin/AdminCartsController.php
> +                    $errors[] = sprintf($this->trans('You must add a minimum quantity of %d', array(), 'Admin.Catalog.Notification'), $minimal_qty);
There is a lot of code that keeps a sprintf around a $this->trans in many places. If it is not allowed, please give me a link to the correct rules. Also PrestaShop team should correct many other places and stop using the code incorrectly. People are looking on PS code.

2017-01-18 08:57 UTC, closed without merging