FO: Add smarty blocks everywhere
PrestaShop/PrestaShop pull request #7362
Opened 2017-01-18 15:25 UTC by julienbourdeau

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add a lot more Smarty blocks in template (see https://github.com/PrestaShop/StarterTheme/pull/167)
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/STAB-65
| How to test?  | You can't, just read the code. Although you can make sure it didnt break any style if you want.

2017-01-18 15:52 UTC, maximebiloe commented on themes/classic/templates/checkout/_partials/cart-detailed.tpl
> +{block name='cart_detailed_product_line'}
block name already define inside the tpl included line 30

2017-01-18 16:34 UTC, maximebiloe requested changes

2017-01-18 16:34 UTC, maximebiloe commented on themes/classic/templates/checkout/_partials/cart-detailed.tpl
> +{block name='cart_detailed_product_line'}
block name already define inside the tpl included line 30

2017-02-01 10:09 UTC, aleeks commented
Hello @julienbourdeau, you need: 

1. Change
2. Fix for tests
3. Rebase

Hihi, good luck!

2017-02-01 16:54 UTC, maximebiloe approved these changes

2017-02-01 16:54 UTC, maximebiloe commented
Yeaaah, everything is green.
Seems good to me, thanks @julienbourdeau

2017-02-01 16:54 UTC, merged