Deprecate Tools::displayError()
PrestaShop/PrestaShop pull request #7393
Opened 2017-01-24 17:07 UTC by antoin-m

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Deprecate Tools::displayError()
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  |

See https://github.com/PrestaShop/PrestaShop/pull/7288

2017-01-25 09:20 UTC, aleeks commented
Hello @antoin-m 
have you tried all case ? :smirk:

2017-01-25 09:21 UTC, antoin-m commented
OFC I did but since you're the one assign you should do too :)

2017-01-25 10:02 UTC, aleeks requested changes
Hihi !

2017-01-25 10:02 UTC, aleeks commented on classes/LocalizationPack.php
> +                $this->_errors[] = Context::getContext()->getTranslator()->trans('Cannot load country : %1d',
sure about %1d ?

2017-01-25 10:02 UTC, aleeks commented on classes/LocalizationPack.php
> +                        'Cannot enable the associated country: %1s',
sure about %1s ?

2017-01-25 10:02 UTC, aleeks commented on classes/LocalizationPack.php
> +                            $this->_errors[] = Context::getContext()->getTranslator()->trans('Cannot update the associated country: ', array(), 'Admin.International.Notification').$country->name;
maybe include country on the trans with %s ?

2017-01-25 10:02 UTC, aleeks commented on classes/LocalizationPack.php
> +                    $this->_errors[] = Context::getContext()->getTranslator()->trans('An error occurred while importing the tax: ', array(), 'Admin.International.Notification').(string)$attributes['n
maybe include the tax on the trans ?

2017-01-25 10:02 UTC, aleeks commented on classes/LocalizationPack.php
> +                        $this->_errors[] = Context::getContext()->getTranslator()->trans('An error occurred while importing the currency: ', array(), 'Admin.International.Notification').strval($attri
maybe include the currency on the trans ?

2017-01-25 10:02 UTC, aleeks commented on classes/LocalizationPack.php
> +                                $this->_errors[] = Context::getContext()->getTranslator()->trans('An error occurred while installing the module:', array(), 'Admin.International.Notification').$name;
maybe include the module on the trans ?

2017-01-25 10:02 UTC, aleeks commented on classes/LocalizationPack.php
> +                            $this->_errors[] = Context::getContext()->getTranslator()->trans('An error occurred while uninstalling the module:', array(), 'Admin.International.Notification').$name;
maybe include the module on the trans ?

2017-01-25 10:02 UTC, aleeks commented on classes/LocalizationPack.php
> +                    $this->_errors[] = Context::getContext()->getTranslator()->trans('An error has occurred, this module does not exist:', array(), 'Admin.International.Error').$name;
maybe include the module on the trans ?

2017-01-25 10:02 UTC, aleeks commented on classes/Mail.php
> +                    PrestaShopLogger::addLog(Context::getContext()->getTranslator()->trans('Error - The following e-mail template is missing:', array(), 'Admin.Advparameters.Notification').' '.$templ
maybe include the template on the trans ?

2017-01-25 10:02 UTC, aleeks commented on classes/Mail.php
> +                    PrestaShopLogger::addLog(Context::getContext()->getTranslator()->trans('Error - The following e-mail template is missing:', array(), 'Admin.Advparameters.Notification').' '.$templ
maybe include the template on the trans ?

2017-01-25 10:02 UTC, aleeks commented on classes/Mail.php
> -                Tools::dieOrLog(Tools::displayError('Error - The following e-mail template is missing:').' '.$template, $die);
maybe include the template on the trans ?

2017-01-25 10:02 UTC, aleeks commented on classes/webservice/WebserviceSpecificManagementImages.php
> +                                    $this->_errors[] = Context::getContext()->getTranslator()->trans('An error occurred while copying image:', array(), 'Admin.Notifications.Error').' '.stripslashes($
maybe include image on the trans ?

2017-01-25 10:02 UTC, aleeks commented on classes/webservice/WebserviceSpecificManagementImages.php
> +                                $this->_errors[] = Context::getContext()->getTranslator()->trans('An error occurred while copying this image:', array(), 'Admin.Notifications.Error').' '.stripslashes(
maybe include image on the trans ?

2017-01-25 10:02 UTC, aleeks commented on controllers/admin/AdminLoginController.php
> +                $warningSslMessage = Translate::ppTags(
sure here ?

2017-01-25 10:02 UTC, aleeks commented on src/Core/Shop/LogoUploader.php
> +use PrestaShop\PrestaShop\Adapter\Shop\Context;
sure ? I think is not the same isn't ?

2017-01-25 10:02 UTC, aleeks commented on classes/module/Module.php
> +                    $module_errors[] = $this->trans(
$this on static context

2017-01-25 10:06 UTC, xBorderie commented
A 🏅 for @aleeks :D

2017-01-25 10:07 UTC, antoin-m commented
![image](https://cloud.githubusercontent.com/assets/3316447/22286158/80e95cde-e2ee-11e6-9d43-998f6b647e92.png)

2017-01-25 14:37 UTC, aleeks approved these changes

2017-01-25 14:49 UTC, AlexEven commented on classes/CartRule.php
> +            return (!$display_error) ? false : $this->trans('This voucher is disabled', array(), 'Admin.Orderscustomers.Notification');
I'm so sorry but I think I made a mistake for this file, it seems it's all front messages, so the domain should be Shop.Notifications.Error

"oups"

2017-01-25 15:24 UTC, AlexEven reviewed
I haven't reviewed all the lines, but it should be good to go ^^
Thanks for this huge work :)

2017-01-25 15:24 UTC, AlexEven commented on classes/webservice/WebserviceSpecificManagementImages.php
> +                                $this->_errors[] = Context::getContext()->getTranslator()->trans('An error occurred while copying this image:', array(stripslashes($imageType['name'])), 'Admin.Notific
Since the meaning is close, we could replace by 'An error occurred while copying this image: %s' maybe?

2017-01-25 15:24 UTC, AlexEven commented on classes/webservice/WebserviceSpecificManagementImages.php
> +                        $this->errors[] = Context::getContext()->getTranslator()->trans('An error occurred while copying this image:', array(), 'Admin.Notifications.Error');
Should be "An error occurred while uploading the image."

2017-01-25 15:24 UTC, AlexEven commented on classes/webservice/WebserviceSpecificManagementImages.php
> +                                    $this->_errors[] = Context::getContext()->getTranslator()->trans('An error occurred while copying image: %s', array(stripslashes($imageType['name'])), 'Admin.Notif
this image: %s

2017-01-25 15:24 UTC, AlexEven commented on controllers/admin/AdminCartsController.php
> +                    $errors[] = $this->trans('You must add a minimum quantity of %d', array($minimal_qty), 'Admin.Orderscustomers.Notification');
Shop.Notifications.Error if displayed in front.
My bad ^^

2017-01-25 15:24 UTC, AlexEven commented on controllers/admin/AdminCartsController.php
> +                    $errors[] = $this->trans('Can\'t add the voucher.', array(), 'Admin.Advparameters.Notification');
same - Shop.Notifications.Error

2017-01-25 15:24 UTC, AlexEven commented on controllers/admin/AdminOrdersController.php
> +                                $this->errors[] = $this->trans('An error occurred while sending an email to the customer.', array(), 'Admin.Notifications.Error');
Admin.Orderscustomers.Notification?

2017-01-25 15:24 UTC, AlexEven commented on controllers/admin/AdminProductsController.php
> +                        $this->errors[] = $this->trans('An error occurred while copying this image:', array(), 'Admin.Notifications.Error').' '.stripslashes($image_type['name']);
Add %s for consistency :)

2017-01-25 15:56 UTC, AlexEven approved these changes
Thanks :)

2017-01-25 16:09 UTC, aleeks commented
Thank you. If develop is not working, it's now your fault....

2017-01-25 16:09 UTC, merged

2017-01-25 16:20 UTC, xBorderie commented on classes/controller/FrontController.php
> +                    'Current theme unavailable "%s". Please check your theme directory name and permissions.',
Suggestion: `Current theme is unavailable. Please check your theme's directory name ("%s") and permissions.`

2017-01-25 16:20 UTC, xBorderie commented on classes/helper/HelperImageUploader.php
> +            $file['error'] = Context::getContext()->getTranslator()->trans('File (size: %1s) is too big (max: %2s)', array($file['size'], $this->getMaxSize()), 'Admin.Notifications.Error');
Here again: `File is too big. Current size is %1s, maximum size is %2s`.

2017-01-25 16:20 UTC, xBorderie commented on classes/order/OrderHistory.php
> +                        $links .= '&nbsp;'.$this->trans('expires on ', array($product['deadline']), 'Admin.Orderscustomers.Notification');
Should be `expires on %s`.

2017-01-25 16:20 UTC, xBorderie commented on classes/stock/SupplyOrderDetail.php
> +                                .'</b> '.$this->trans('is required.', array(), 'Shop.Notifications.Error');
`%s is required`?

2017-01-25 16:20 UTC, xBorderie commented on controllers/admin/AdminImagesController.php
> +                    $this->errors[] = $this->trans('Cannot write images for this type: %s. Please check the %s folder\'s writing permissions.', array($proc['type'], $proc['dir']), 'Admin.Design.Notif
Transform the %s into %1$s and %2$s for easier translation?

2017-01-25 16:20 UTC, xBorderie commented on controllers/admin/AdminImagesController.php
> +                        $this->errors[] = $this->trans('Cannot write "No picture" image to (%s) images folder. Please check the folder\'s writing permissions.', array($proc['type']), 'Admin.Design.No
`to "%s" images`, rather?

2017-01-25 16:20 UTC, xBorderie commented on controllers/admin/AdminImportController.php
> +                '%1$s (ID: %2$s) cannot be %3$s',
Easier to translate: `Email address %1$s (ID: %2$s) cannot be %3$s`.

In fact, this should split into two strings:
* `Email address %1$s (ID: %2$s) cannot be validated`.
* `Email address %1$s (ID: %2$s) cannot be saved`.

`($validateOnly?'validated':'saved')` was _really_ a bad idea :)

2017-01-25 16:20 UTC, xBorderie commented on controllers/admin/AdminImportController.php
> +                        '%1$s does not exist in database %2$s (ID: %3$s), and therefore cannot be %4$s',
This should also be split into two strings:
* `%1$s does not exist in database %2$s (ID: %3$s), and therefore cannot be validated`
* `%1$s does not exist in database %2$s (ID: %3$s), and therefore cannot be saved`

Also, it seems that:
* %1$s is a DB error message: `Db::getInstance()->getMsgError()`
* %2$s is the customer's email: `$address->customer_email`

Does the generated result even make sense?

2017-01-25 16:20 UTC, xBorderie commented on controllers/admin/AdminImportController.php
> +                        '%1$s does not exist in database %2$s (ID: %3$s), and therefore cannot be %4$s',
As above: This should also be split into two strings:
* `%1$s does not exist in database %2$s (ID: %3$s), and therefore cannot be validated`
* `%1$s does not exist in database %2$s (ID: %3$s), and therefore cannot be saved`

Also, it seems that:
* %1$s is a DB error message: `Db::getInstance()->getMsgError()`
* %2$s is the customer's email: `$address->customer_email`

Does the generated result even make sense?

2017-01-25 16:20 UTC, xBorderie commented on controllers/admin/AdminImportController.php
> +                    'The customer ID #%d does not exist in the database, and therefore cannot be %2$s',
Again, this should also be split into two strings:
* `The customer ID #%d does not exist in the database, and therefore cannot be validated`
* `The customer ID #%d does not exist in the database, and therefore cannot be saved`

2017-01-25 16:20 UTC, xBorderie commented on controllers/admin/AdminPerformanceController.php
> +                        $message = $this->trans('Before being able to use this tool, you need to:', array(), 'Admin.Advparameters.Notification');
Can't all this be merged into a single string, with &lt;br/>s inside?

2017-01-25 16:20 UTC, xBorderie commented on controllers/admin/AdminPerformanceController.php
> +                        $message = $this->trans('Before being able to use this tool, you need to:', array(), 'Admin.Advparameters.Notification');
Same here: one string instead of three?

2017-01-25 16:20 UTC, xBorderie commented on controllers/front/CartController.php
> +                            $this->errors[] = $this->trans('This voucher does not exists.', array(), 'Shop.Notifications.Error');
Typo: `This voucher does not exist` (no final S).

2017-01-25 16:22 UTC, xBorderie commented
As a final note: for consistency's sake, could all strings end with a `.`? :)
(ping @AlexEven for opinion, as this idea might turn many Crowdin-translated strings into untranslated strings...)

2017-01-25 16:48 UTC, antoin-m commented on controllers/admin/AdminImportController.php
> +                        '%1$s does not exist in database %2$s (ID: %3$s), and therefore cannot be %4$s',
Oh yeah you're right, the message doesn't make sense at all!

2017-01-25 16:50 UTC, antoin-m commented on controllers/admin/AdminImportController.php
> +                        '%1$s does not exist in database %2$s (ID: %3$s), and therefore cannot be %4$s',
This one doesn't make sense either

2017-01-25 17:11 UTC, AlexEven commented on classes/helper/HelperImageUploader.php
> +            $file['error'] = Context::getContext()->getTranslator()->trans('File (size: %1s) is too big (max: %2s)', array($file['size'], $this->getMaxSize()), 'Admin.Notifications.Error');
There's another occurrence of this sentence which should be updated too. (classes/Uploader.php)

2017-01-26 17:29 UTC, biomassives commented
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (101/100 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:58882 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cWnrb-003gBH-PB
	for greg@biomassiv.es; Thu, 26 Jan 2017 11:29:35 -0600
Date: Wed, 25 Jan 2017 08:50:51 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1485363051;
	bh=TVsqZLImC1oclTmqi15zJ5O2QpfM4t4NF+WTi1I+k90=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Oq2jRmleZrvQR80+2x7Zx2Cg5XD1HUxBCSAQj3U0rZWf5CAIje9zGNnwIzKA0Aw/L
	 iPJzbr191BadaVmViC82jKoxw3aWw/OZhlW0TrBLhOQLi95EZzuTCPcDufXaQa+WPU
	 cZE9RpazID/xl25KLS1xA14f6YWsN5Nrd1kwzyaU=
From: antoin_m <notifications@github.com>
Reply-To: PrestaShop/PrestaShop <reply@reply.github.com>
To: PrestaShop/PrestaShop <PrestaShop@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Message-ID: <PrestaShop/PrestaShop/pull/7393/review/18446377@github.com>
In-Reply-To: <PrestaShop/PrestaShop/pull/7393@github.com>
References: <PrestaShop/PrestaShop/pull/7393@github.com>
Subject: Re: [PrestaShop/PrestaShop] Deprecate Tools::displayError() (#7393)
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_5888d76b436b4_1743e3fe164b1d138817451";
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Precedence: list
X-GitHub-Sender: antoin-m
X-GitHub-Recipient: biomassives
X-GitHub-Reason: subscribed
List-ID: PrestaShop/PrestaShop <PrestaShop.PrestaShop.github.com>
List-Archive: https://github.com/PrestaShop/PrestaShop
List-Post: <mailto:reply@reply.github.com>
List-Unsubscribe: <mailto:unsub+0042d4e229db3851b6691bfb4ad781de58b23c41f0cc6f2592cf0000000114a0996b92a169ce0c17b6c7@reply.github.com>,
 <https://github.com/notifications/unsubscribe/AELU4tpF1TR89zyhdNuXeVVruSE9vgtmks5rV31rgaJpZM4Lsh16>
X-Auto-Response-Suppress: All
X-GitHub-Recipient-Address: greg@biomassiv.es


----==_mimepart_5888d76b436b4_1743e3fe164b1d138817451
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

antoin-m commented on this pull request.



> @@ -3146,15 +3164,26 @@ protected function addressImportOne($info, $force_ids, $validateOnly = false)
                 $customer_list = Customer::getCustomersByEmail($customer->email);
 
                 if (count($customer_list) == 0) {
-                    $this->errors[] = sprintf(
-                        Tools::displayError('%1$s does not exist in database %2$s (ID: %3$s), and therefore cannot be '.($validateOnly?'validated':'saved')),
-                        Db::getInstance()->getMsgError(),
-                        $customer->email,
-                        (int)$address->id_customer
+                    $this->errors[] = $this->trans(
+                        '%1$s does not exist in database %2$s (ID: %3$s), and therefore cannot be %4$s',

This one doesn't make sense either

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/PrestaShop/PrestaShop/pull/7393
----==_mimepart_5888d76b436b4_1743e3fe164b1d138817451
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<p><b>@antoin-m</b> commented on this pull request.</p>

<hr>

<p>In <a href="https://github.com/PrestaShop/PrestaShop/pull/7393">controllers/admin/AdminImportController.php</a>:</p>
<pre style='color:#555'>&gt; @@ -3146,15 +3164,26 @@ protected function addressImportOne($info, $force_ids, $validateOnly = false)
                 $customer_list = Customer::getCustomersByEmail($customer-&gt;email);
 
                 if (count($customer_list) == 0) {
-                    $this-&gt;errors[] = sprintf(
-                        Tools::displayError(&#39;%1$s does not exist in database %2$s (ID: %3$s), and therefore cannot be &#39;.($validateOnly?&#39;validated&#39;:&#39;saved&#39;)),
-                        Db::getInstance()-&gt;getMsgError(),
-                        $customer-&gt;email,
-                        (int)$address-&gt;id_customer
+                    $this-&gt;errors[] = $this-&gt;trans(
+                        &#39;%1$s does not exist in database %2$s (ID: %3$s), and therefore cannot be %4$s&#39;,
</pre>
<p>This one doesn't make sense either</p>

<p style="font-size:small;-webkit-text-size-adjust:none;color:#666;">&mdash;<br />You are receiving this because you are subscribed to this thread.<br />Reply to this email directly, <a href="https://github.com/PrestaShop/PrestaShop/pull/7393">view it on GitHub</a>, or <a href="https://github.com/notifications/unsubscribe-auth/AELU4v5dXLXdU8MCqgByrIvHkYv0IElfks5rV31rgaJpZM4Lsh16">mute the thread</a>.<img alt="" height="1" src="https://github.com/notifications/beacon/AELU4uYNujhEPqBdA64mAYKfKtYg6slxks5rV31rgaJpZM4Lsh16.gif" width="1" /></p>
<div itemscope itemtype="http://schema.org/EmailMessage">
<div itemprop="action" itemscope itemtype="http://schema.org/ViewAction">
  <link itemprop="url" href="https://github.com/PrestaShop/PrestaShop/pull/7393"></link>
  <meta itemprop="name" content="View Pull Request"></meta>
</div>
<meta itemprop="description" content="View this Pull Request on GitHub"></meta>
</div>

<script type="application/json" data-scope="inboxmarkup">{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/PrestaShop/PrestaShop","title":"PrestaShop/PrestaShop","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/PrestaShop/PrestaShop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@antoin-m commented on #7393"}],"action":{"name":"View Pull Request","url":"https://github.com/PrestaShop/PrestaShop/pull/7393"}}}</script>
----==_mimepart_5888d76b436b4_1743e3fe164b1d138817451--

2017-01-26 17:40 UTC, biomassives commented
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (111/100 (111%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 24390 characters long; only the first
------ 5000 or so are included here.
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:38971 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cWo1Y-003lgX-TZ
	for greg@biomassiv.es; Thu, 26 Jan 2017 11:39:52 -0600
Date: Wed, 25 Jan 2017 02:02:16 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1485338537;
	bh=lNT2/2GUjvWkgs7IaepKOHuFgAdESETDwqmgTI0keBg=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Hq5Ycg0e1tCZEA1MlEFv1XpsIqjYUUEH0HEIWi/Dg1aT4Hytdnq+LQMNq9TGcFvT2
	 REs804ohGnQ4SMLZVO2RXJRNNerTQ7FkMjuTJd8WYTXdoswUMDEoMk5ekZkIngzWyW
	 tLcfTFwvaXGmDYbjNPEds1NqvDFf/pBGoVBOlSCE=
From: Alex Sampaio <notifications@github.com>
Reply-To: PrestaShop/PrestaShop <reply@reply.github.com>
To: PrestaShop/PrestaShop <PrestaShop@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Message-ID: <PrestaShop/PrestaShop/pull/7393/review/18356788@github.com>
In-Reply-To: <PrestaShop/PrestaShop/pull/7393@github.com>
References: <PrestaShop/PrestaShop/pull/7393@github.com>
Subject: Re: [PrestaShop/PrestaShop] Deprecate Tools::displayError() (#7393)
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_588877a8ed12b_cb83f969751b1304680a1";
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Precedence: list
X-GitHub-Sender: aleeks
X-GitHub-Recipient: biomassives
X-GitHub-Reason: subscribed
List-ID: PrestaShop/PrestaShop <PrestaShop.PrestaShop.github.com>
List-Archive: https://github.com/PrestaShop/PrestaShop
List-Post: <mailto:reply@reply.github.com>
List-Unsubscribe: <mailto:unsub+0042d4e2f80be514cdef57497241bb45c7b95b7754eded9f92cf0000000114a039a892a169ce0c17b6c7@reply.github.com>,
 <https://github.com/notifications/unsubscribe/AELU4ny6bqACXvkNEBNV4U3Ge0rnAIGOks5rVx2ogaJpZM4Lsh16>
X-Auto-Response-Suppress: All
X-GitHub-Recipient-Address: greg@biomassiv.es


----==_mimepart_588877a8ed12b_cb83f969751b1304680a1
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

aleeks requested changes on this pull request.

Hihi !

> @@ -52,13 +52,20 @@ public function loadLocalisationPack($file, $selection, $install_mode = false, $
                 $country = new Country($id_country);
             }
             if (!$id_country || !Validate::isLoadedObject($country)) {
-                $this->_errors[] = Tools::displayError(sprintf('Cannot load country : %1d', $id_country));
+                $this->_errors[] = Context::getContext()->getTranslator()->trans('Cannot load country : %1d',

sure about %1d ?

>                  return false;
             }
             if (!$country->active) {
                 $country->active = 1;
                 if (!$country->update()) {
-                    $this->_errors[] = Tools::displayError(sprintf('Cannot enable the associated country: %1s', $country->name));
+                    $this->_errors[] = Context::getContext()->getTranslator()->trans(
+                        'Cannot enable the associated country: %1s',

sure about %1s ?

>                          return false;
                     }
 
                     $country = new Country($state->id_country);
                     if (!$country->contains_states) {
                         $country->contains_states = 1;
                         if (!$country->update()) {
-                            $this->_errors[] = Tools::displayError('Cannot update the associated country: ').$country->name;
+                            $this->_errors[] = Context::getContext()->getTranslator()->trans('Cannot update the associated country: ', array(), 'Admin.International.Notification').$country->name;

maybe include country on the trans with %s ?

>                      return false;
                 }
 
                 if (!$tax->add()) {
-                    $this->_errors[] = Tools::displayError('An error occurred while importing the tax: ').(string)$attributes['name'];
+                    $this->_errors[] = Context::getContext()->getTranslator()->trans('An error occurred while importing the tax: ', array(), 'Admin.International.Notification').(string)$attributes['name'];

maybe include the tax on the trans ?

>                      return false;
                 }
                 if (!Currency::exists($currency->iso_code)) {
                     if (!$currency->add()) {
-                        $this->_errors[] = Tools::displayError('An error occurred while importing the currency: ').strval($attributes['name']);
+                        $this->_errors[] = Context::getContext()->getTranslator()->trans('An error occurred while importing the currency: ', array(), 'Admin.International.Notification').strval($attributes['name']);

maybe include the currency on the trans ?

> @@ -420,18 +427,18 @@ protected function installModules($xml)
                     if ($install) {
                         if (!$moduleManager->isInstalled($name)) {
                             if (!$module->install()) {
-                                $this->_errors[] = Tools::displayError('An error occurred while installing the module:').$name;
+                                $this->_errors[] = Context::getContext()->getTranslator()->trans('An error occurred while installing the module:', array(), 'Admin.International.Notification').$name;

maybe include the module on the trans ?

>                              }
                         }
                     } elseif ($moduleManager->isInstalled($name)) {
                         if (!$module->uninstall()) {
-                            $this->_errors[] = Tools::displayError('An error occurred while uninstalling the module:').$name;
+                            $this->_errors[] = Context::getContext()->getTranslator()->trans('An error occurred while uninstalling the module:', array(), 'Admin.International.Notification').$name;

maybe include the module on the trans ?

>                          }
                     }
 
                     unset($module);
                 } else {
-                    $this->_errors[] = Tools::displayError('An error has occurred, this module does not exist:').$name;
+                    $this->_errors[] = Context::getContext()->getTranslator()->trans('An error has occurred, this module does not exist:', array(), 'Admin.International.Error').$name;

maybe include the module on the trans ?

> @@ -303,17 +303,17 @@ public static function Send(
                 }
 
                 if (!file_exists($templatePath.$isoTemplate.'.txt') && ($configuration['PS_MAIL_TYPE'] == Mail::TYPE_BOTH || $configuration['PS_MAIL_TYPE'] == Mail::TYPE_TEXT)) {
-                    PrestaShopLogger::addLog(Tools::displayError('Error - The following e-mail template is missing:').' '.$templatePath.$isoTemplate.'.txt');
+                    PrestaShopLogger::addLog(Context::getContext()->getTranslator()->trans('Error - The following e-mail te

2017-01-26 17:44 UTC, biomassives commented
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (117/100 (117%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:44500 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cWo5v-003oaK-Sb
	for greg@biomassiv.es; Thu, 26 Jan 2017 11:44:23 -0600
Date: Wed, 25 Jan 2017 08:48:55 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1485362935;
	bh=DjZFkGQKJxwCyhgMoPTX4Tbpj7tl3FHZVZP0OlO1JUA=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Ul99uy6zPRyCKv/xoi2krZ40BbZuTJDy9xZK1UUp15sWWJ+Ryy11JziqZ1oCwAtDO
	 JEeJ82EX2PAitJmGhvy0Ewbggriq2AcdsM5jYOonpO+a8L4p8PkLJ1Csswp2KFpDkY
	 tXOMKkmnBZpXyylct3KZmZeb+nOdQoLEGADT5fss=
From: antoin_m <notifications@github.com>
Reply-To: PrestaShop/PrestaShop <reply@reply.github.com>
To: PrestaShop/PrestaShop <PrestaShop@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Message-ID: <PrestaShop/PrestaShop/pull/7393/review/18445866@github.com>
In-Reply-To: <PrestaShop/PrestaShop/pull/7393@github.com>
References: <PrestaShop/PrestaShop/pull/7393@github.com>
Subject: Re: [PrestaShop/PrestaShop] Deprecate Tools::displayError() (#7393)
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_5888d6f7b88ac_11bf3f87026bf13416297";
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Precedence: list
X-GitHub-Sender: antoin-m
X-GitHub-Recipient: biomassives
X-GitHub-Reason: subscribed
List-ID: PrestaShop/PrestaShop <PrestaShop.PrestaShop.github.com>
List-Archive: https://github.com/PrestaShop/PrestaShop
List-Post: <mailto:reply@reply.github.com>
List-Unsubscribe: <mailto:unsub+0042d4e2a8c8f212aa95d24e8ca231d2826c164511a4fe5a92cf0000000114a098f792a169ce0c17b6c7@reply.github.com>,
 <https://github.com/notifications/unsubscribe/AELU4iKq7-Wnok5VeLHSy9P2utxN0p-jks5rV3z3gaJpZM4Lsh16>
X-Auto-Response-Suppress: All
X-GitHub-Recipient-Address: greg@biomassiv.es


----==_mimepart_5888d6f7b88ac_11bf3f87026bf13416297
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

antoin-m commented on this pull request.



> @@ -3127,11 +3141,15 @@ protected function addressImportOne($info, $force_ids, $validateOnly = false)
                 $customer_list = Customer::getCustomersByEmail($address->customer_email);
 
                 if (count($customer_list) == 0) {
-                    $this->errors[] = sprintf(
-                        Tools::displayError('%1$s does not exist in database %2$s (ID: %3$s), and therefore cannot be '.($validateOnly?'validated':'saved')),
-                        Db::getInstance()->getMsgError(),
-                        $address->customer_email,
-                        (isset($info['id']) && !empty($info['id']))? $info['id'] : 'null'
+                    $this->errors[] = $this->trans(
+                        '%1$s does not exist in database %2$s (ID: %3$s), and therefore cannot be %4$s',

Oh yeah you're right, the message doesn't make sense at all!

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/PrestaShop/PrestaShop/pull/7393
----==_mimepart_5888d6f7b88ac_11bf3f87026bf13416297
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<p><b>@antoin-m</b> commented on this pull request.</p>

<hr>

<p>In <a href="https://github.com/PrestaShop/PrestaShop/pull/7393">controllers/admin/AdminImportController.php</a>:</p>
<pre style='color:#555'>&gt; @@ -3127,11 +3141,15 @@ protected function addressImportOne($info, $force_ids, $validateOnly = false)
                 $customer_list = Customer::getCustomersByEmail($address-&gt;customer_email);
 
                 if (count($customer_list) == 0) {
-                    $this-&gt;errors[] = sprintf(
-                        Tools::displayError(&#39;%1$s does not exist in database %2$s (ID: %3$s), and therefore cannot be &#39;.($validateOnly?&#39;validated&#39;:&#39;saved&#39;)),
-                        Db::getInstance()-&gt;getMsgError(),
-                        $address-&gt;customer_email,
-                        (isset($info[&#39;id&#39;]) &amp;&amp; !empty($info[&#39;id&#39;]))? $info[&#39;id&#39;] : &#39;null&#39;
+                    $this-&gt;errors[] = $this-&gt;trans(
+                        &#39;%1$s does not exist in database %2$s (ID: %3$s), and therefore cannot be %4$s&#39;,
</pre>
<p>Oh yeah you're right, the message doesn't make sense at all!</p>

<p style="font-size:small;-webkit-text-size-adjust:none;color:#666;">&mdash;<br />You are receiving this because you are subscribed to this thread.<br />Reply to this email directly, <a href="https://github.com/PrestaShop/PrestaShop/pull/7393">view it on GitHub</a>, or <a href="https://github.com/notifications/unsubscribe-auth/AELU4n1VsDpPJIBxlNExo_dTnwf35pVcks5rV3z3gaJpZM4Lsh16">mute the thread</a>.<img alt="" height="1" src="https://github.com/notifications/beacon/AELU4r5g9923cnUYoG2L4yd2mUriX-trks5rV3z3gaJpZM4Lsh16.gif" width="1" /></p>
<div itemscope itemtype="http://schema.org/EmailMessage">
<div itemprop="action" itemscope itemtype="http://schema.org/ViewAction">
  <link itemprop="url" href="https://github.com/PrestaShop/PrestaShop/pull/7393"></link>
  <meta itemprop="name" content="View Pull Request"></meta>
</div>
<meta itemprop="description" content="View this Pull Request on GitHub"></meta>
</div>

<script type="application/json" data-scope="inboxmarkup">{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/PrestaShop/PrestaShop","title":"PrestaShop/PrestaShop","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/PrestaShop/PrestaShop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@antoin-m commented on #7393"}],"action":{"name":"View Pull Request","url":"https://github.com/PrestaShop/PrestaShop/pull/7393"}}}</script>
----==_mimepart_5888d6f7b88ac_11bf3f87026bf13416297--