BO: Refresh forms for specific price
PrestaShop/PrestaShop pull request #7513
Opened 2017-02-09 14:30 UTC by kompilorb

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Forms in product details, for add special prize are not initialize after validation. Any actualisation on this.  
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-2195
| How to test?  | In BO, catalogs, products. Edit products after go in prizing. Then add a specific prize. Then add the prize, click an other time, the forms must be initialize.

2017-02-09 17:41 UTC, vincentbz commented
Hi, 

thanks !
I just have two boxes when validate the specific price
![image](https://cloud.githubusercontent.com/assets/7567060/22795506/351a75c6-eef7-11e6-9448-ce90198ba2b5.png)
![image](https://cloud.githubusercontent.com/assets/7567060/22795516/3c5ac9f8-eef7-11e6-93d8-a78bdb288b88.png)

But it works, I can create specific prices in a raw without refreshing the page.

2017-02-09 17:53 UTC, aleeks requested changes
See comment

2017-02-09 17:53 UTC, aleeks commented on admin-dev/themes/default/js/bundle/product/form.js
> +        alert(initSpecificPriceForm[$(this).attr('id')]);
Can you remove your trace please ? 😀

2017-02-10 08:25 UTC, kompilorb commented
Correction done on incorrect forms popup

2017-02-10 08:32 UTC, aleeks approved these changes

2017-02-10 08:32 UTC, aleeks commented
@vincentbz can you check again please ?

2017-02-10 10:10 UTC, maximebiloe requested changes

2017-02-10 10:10 UTC, maximebiloe commented on admin-dev/themes/default/js/bundle/product/form.js
> +        initSpecificPriceForm[$(this).attr('id')]=$(this).val();
I know it's not causing trouble but for the readability could you add spaces around the `=`, please?
It's the same for all the ones you add.

Thank you

2017-02-10 10:10 UTC, vincentbz commented
Tested and ok, thanks !

<!--
status: 'QA approved'
-->

2017-02-10 10:13 UTC, xBorderie commented on admin-dev/themes/default/js/bundle/product/form.js
> +        initSpecificPriceForm[$(this).attr('id')]=$(this).val();
It's even [part of the JS styleguide we use](https://github.com/airbnb/javascript#whitespace--infix-ops) :)

2017-02-10 10:17 UTC, kompilorb commented
Add space around "=" done !

2017-02-10 10:30 UTC, kompilorb commented
New commit.  Place no space between the argument list and the function name in function calls and declarations.

2017-02-10 10:52 UTC, aleeks commented
Thank you @kompilorb

2017-02-10 10:52 UTC, merged