BO: Employee permissions not saved
PrestaShop/PrestaShop pull request #7584
Opened 2017-02-20 14:30 UTC by kompilorb

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.1.x
| Description?  | Problems when select checkbox in administration permission. Child of Menu is not saved. 
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-2451
| How to test?  | In BO, select on permission the hight menu "Sell" all submenu is checked. When you reload the page, before the submenu (like Catalog or Product) is not saved. Now when you reload all information is the same.

2017-02-20 14:43 UTC, aleeks commented on classes/Access.php
> +            FROM `'._DB_PREFIX_.'tab` t
can you remove the alias if you don't use it ? if someday, we make a join.. it can be problematic!

2017-02-20 14:45 UTC, aleeks commented on classes/Access.php
> +    public function updateLgcAccess($idProfile, $idTab, $lgcAuth, $enabled, $addFromParent)
Hello @kompilorb,
Can you add a default parameters please ?! in order to keep retro-compat!

2017-02-20 14:52 UTC, kompilorb commented
Correction on function parameters default and alias for table is done.

2017-02-20 16:57 UTC, thierrymarianne requested changes

2017-02-20 16:57 UTC, thierrymarianne commented on classes/Access.php
> +        $result = Db::getInstance()->executeS('
Can you please return the result without intermediate variable?

2017-02-20 17:03 UTC, kompilorb commented on classes/Access.php
> +        $result = Db::getInstance()->executeS('
Done :)

2017-02-21 01:51 UTC, Shudrum commented on classes/Access.php
> +     *
Too many empty comment lines :)

2017-02-21 01:54 UTC, Shudrum commented on classes/Access.php
> +
Sorry to not explained it sooner, but we follow the PSR rules.

So please update your code like this:

```php
if ($addFromParent == 1) {
    foreach (self::findSlugByIdParentTab($idTab) as $child) {
        $child = self::sluggifyTab($child);
        foreach ((array) self::getAuthorizationFromLegacy($lgcAuth) as $auth) {
            $slugLike = Db::getInstance()->escape($child.$auth);
            $whereClauses[] = ' `slug` LIKE "'.$slugLike.'"';
        }
    }
}
```

Thank you!

2017-02-21 08:16 UTC, kompilorb commented on classes/Access.php
> +     *
Done, and I have put right the other function who have the same space.

2017-02-21 08:16 UTC, kompilorb commented on classes/Access.php
> +
Done.

2017-02-21 08:35 UTC, thierrymarianne approved these changes

2017-02-21 08:39 UTC, Shudrum commented on classes/Access.php
> +
👍

2017-02-21 08:40 UTC, merged