Add displayProductPageDrawer hook
PrestaShop/PrestaShop pull request #7596
Opened 2017-02-22 16:40 UTC by antoin-m

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.1.x
| Description?  | Add displayProductPageDrawer hook
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  |

The module has to return something like 

```
    public function hookDisplayProductPageDrawer($params)
    {
        return [
            'title' => 'stats',
            'link' => 'http://localhost/index.html',
            'id' => 'ps_banner',
            'icon' => 'label',
        ];
    }
```
or
```
    public function hookDisplayProductPageDrawer($params)
    {
        return [[
            'title' => 'stats',
            'link' => 'http://localhost/index.html',
            'id' => 'ps_banner',
            'icon' => 'label',
        ], [
            'title' => 'plan',
            'link' => 'http://localhost/index.html',
            'id' => 'ps_plan',
            'icon' => 'input',
        ]];
    }
```

2017-02-23 09:12 UTC, aleeks requested changes
See comment

2017-02-23 09:12 UTC, aleeks commented on install-dev/upgrade/sql/1.7.1.1.sql
> +  (NULL, 'displayProductPageDrawer', 'Product Page Drawer', 'This hook displays content in the right sidebar of the product page', '1');
If it's for 1.7.1.0, it's not good

2017-02-23 09:14 UTC, antoin-m commented on install-dev/upgrade/sql/1.7.1.1.sql
> +  (NULL, 'displayProductPageDrawer', 'Product Page Drawer', 'This hook displays content in the right sidebar of the product page', '1');
Didn't we say 1.7.1.1 ? @vincentbz

2017-02-23 10:04 UTC, aleeks commented on install-dev/upgrade/sql/1.7.1.1.sql
> +  (NULL, 'displayProductPageDrawer', 'Product Page Drawer', 'This hook displays content in the right sidebar of the product page', '1');
Don't know :'(

2017-02-24 15:47 UTC, vincentbz commented on install-dev/upgrade/sql/1.7.1.1.sql
> +  (NULL, 'displayProductPageDrawer', 'Product Page Drawer', 'This hook displays content in the right sidebar of the product page', '1');
Na, we said 1.7.1.0 as addons needs it :p

2017-02-24 15:52 UTC, aleeks requested changes
According with @vincentbz

2017-02-24 15:52 UTC, aleeks commented on install-dev/upgrade/sql/1.7.1.1.sql
> +  (NULL, 'displayProductPageDrawer', 'Product Page Drawer', 'This hook displays content in the right sidebar of the product page', '1');
So 1.7.1.0 baby !

2017-03-06 08:44 UTC, Quetzacoalt91 commented
Hoy,

I see we expect a specific structure here.
If you want to be sure a module developer will follow it, it would be better to create a class in which you write all the properties available, and then you use `PrestaShopBundle\Service\Hook\HookFinder` to get an array of them.

Why would you do that ? It would prevent you to check again if the properties exists, and the module id will be auto-populated when you get the presented data (https://github.com/PrestaShop/PrestaShop/blob/d9c37b1bfff26e43ea9df3728fdeca4041c47c84/src/PrestaShopBundle/Service/Hook/HookFinder.php#L112). :)

2017-03-06 08:45 UTC, Quetzacoalt91 submitted a review, later dismissed
Hoy,

I see we expect a specific structure here.
If you want to be sure a module developer will follow it, it would be better to create a class in which you write all the properties available, and then you use `PrestaShopBundle\Service\Hook\HookFinder` to get an array of them.

Why would you do that ? It would prevent you to check again if the properties exists, and the module id will be auto-populated when you get the presented data (https://github.com/PrestaShop/PrestaShop/blob/d9c37b1bfff26e43ea9df3728fdeca4041c47c84/src/PrestaShopBundle/Service/Hook/HookFinder.php#L112). :)

2017-03-13 09:12 UTC, aleeks commented
I think, we have to do another PR, @antoin-m is so busy at this time :cry: 
I'm closing this one... :(

2017-03-13 09:13 UTC, antoin-m commented
Hahaha sorry 😥

2017-03-13 09:22 UTC, Quetzacoalt91 commented
@aleeks If we close this PR, we will forget the feature we want to add to the software.

Of course @antoin-m may be too busy to update the pull-request, but we can do it ... if the feature worth it. :)

2017-03-13 09:26 UTC, kpodemski commented
It's worth it

2017-03-13 16:07 UTC, aleeks submitted a review, later dismissed

2017-03-13 17:26 UTC, Quetzacoalt91 commented
The pull-request has been updated to use the class `HookFinder`.

2017-03-15 13:16 UTC, vincentbz commented
Thanks @Quetzacoalt91 !
I test it and then we can merge it ?

2017-03-15 14:16 UTC, Quetzacoalt91 commented
Yep we can if a code review pass

2017-03-17 08:06 UTC, maximebiloe commented
Everything looks fine to me.
Thanks guys!

2017-03-17 08:06 UTC, merged

2017-03-17 08:16 UTC, antoin-m commented
![image](https://cloud.githubusercontent.com/assets/3316447/24034631/69419570-0af2-11e7-9b99-bc7a4a224e2f.png)

2017-03-17 09:31 UTC, xBorderie commented
@antoin-m Tut tut tut, don't forget the last one: https://github.com/PrestaShop/PrestaShop/pulls/antoin-m :)

2017-03-17 09:34 UTC, antoin-m commented
![image](https://cloud.githubusercontent.com/assets/3316447/24037180/336b86da-0afd-11e7-9c13-c6153f2070db.png)

The ball is in your court 🥇