Fix Combinaition filter in stock management section
PrestaShop/PrestaShop pull request #7658
Opened 2017-03-10 14:36 UTC by fatmaBouchekoua

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | When you do a search by name or by reference, or sort combinations it shows "No records found".
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-8859
| How to test?  | In the Stock > Stock Management, view details of product that have combinations and use search and sort options.

2017-04-06 15:50 UTC, maximebiloe requested changes

2017-04-06 15:50 UTC, maximebiloe commented on controllers/admin/AdminStockManagementController.php
> +            $this->fields_list ['name'] =
Could you remove the space between `fields_list` and `['name']`, please?

2017-04-06 15:50 UTC, maximebiloe commented on controllers/admin/AdminStockManagementController.php
> +        if(Tools::isSubmit('submitFilter') && Tools::getIsset('detailsproduct')){
A little space here, please

2017-04-06 15:50 UTC, maximebiloe commented on controllers/admin/AdminStockManagementController.php
> +        if(Tools::getIsset('detailsproduct')) {
A space here too 😉

2017-04-10 08:37 UTC, fatmaBouchekoua commented
Hello @maximebiloe , Done !
Thank you

2017-04-10 09:23 UTC, maximebiloe approved these changes

2017-04-10 09:23 UTC, merged

2017-04-10 09:23 UTC, maximebiloe commented
Thank you @fatmaBouchekoua