FO: Save zero to id_state if country has no states
PrestaShop/PrestaShop pull request #7689
Opened 2017-03-22 14:30 UTC by martinfojtik

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | This will fix problems which can happen when switching between a country with/without states.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  |

2017-03-22 15:01 UTC, aleeks commented
Hello @martinfojtik 
Is it for 1.6.1.x or 1.7.1.x ?
Regards

2017-03-22 15:06 UTC, martinfojtik commented
Hi @aleeks , its for 1.7.1.x .

2017-03-23 09:20 UTC, aleeks requested changes

2017-03-23 09:20 UTC, aleeks commented on classes/form/CustomerAddressForm.php
> +        if( !isset( $this->formFields['id_state'] ) ) {
Hello @martinfojtik 
Can you edit like that please ?

``` php 
if (!isset($this->formFields['id_state'])) {
```

Regards

2017-03-23 17:28 UTC, martinfojtik commented on classes/form/CustomerAddressForm.php
> +        if( !isset( $this->formFields['id_state'] ) ) {
of course

2017-03-24 19:12 UTC, aleeks approved these changes

2017-03-24 19:13 UTC, aleeks commented
Thank you @martinfojtik 
It will be merged asap!

Regards

2017-04-05 09:41 UTC, merged

2017-04-05 09:41 UTC, maximebiloe commented
Thank you @martinfojtik