Fix displaying product thumbnails
PrestaShop/PrestaShop pull request #7716
Opened 2017-03-29 17:34 UTC by molka

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.1.x
| Description?  | When i clicked on the "quick view" link and the modal is opened, the product thumbnails was not displayed correctly.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-2739
| How to test?  | On small devices (nearly between 1040px and 768px ), Click on "quick view" link, you can see that the product thumbnails are displayed correctly

2017-03-30 09:27 UTC, vincentbz commented
Hi @molka 

Could you move your PR to the 1.7.1.x branch please ? so that it will be released in the next patch version (1.7.1.1) and not 1.7.2.0.

Thanks !

2017-03-30 09:29 UTC, kpodemski commented
@vincentbz this can be done by maintainer, @aleeks or someone else

2017-03-30 11:50 UTC, aleeks commented
All svg are needed ?! :open_mouth:

2017-03-30 11:56 UTC, maximebiloe commented
@aleeks: Yes they are

2017-06-22 09:51 UTC, Quetzacoalt91 commented
The pull-request was outdated, I've just rebased it on `develop` to remove conflicts.

2017-06-22 09:52 UTC, Quetzacoalt91 submitted a review, later dismissed

2017-07-24 13:27 UTC, eternoendless submitted a review, later dismissed
Code looks good!

2017-07-27 08:51 UTC, eternoendless requested changes

2017-07-27 08:51 UTC, eternoendless commented on themes/classic/assets/css/theme.css
> -/*! normalize.css v4.2.0 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;line-height:1.15;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,
This merge conflict *must* be addressed

2017-07-27 09:11 UTC, maximebiloe commented on themes/classic/assets/css/theme.css
> -/*! normalize.css v4.2.0 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;line-height:1.15;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,
It should be okay now 😉

2017-07-27 09:40 UTC, eternoendless approved these changes
Thanks @maximebiloe :)

2017-07-27 10:02 UTC, aleeks commented
Thank you @molka & @maximebiloe

2017-07-27 10:02 UTC, merged