Fixed Terms and conditions popup on mobile not possible to close
PrestaShop/PrestaShop pull request #7726
Opened 2017-03-31 15:17 UTC by aleeks

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.1.x
| Description?  | Fixed Terms and conditions popup on mobile not possible to close
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-2583
| How to test?  | ping @vincentbz 

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

2017-04-03 07:15 UTC, maximebiloe requested changes

2017-04-03 07:15 UTC, maximebiloe commented on themes/classic/templates/checkout/_partials/steps/payment.tpl
> +        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
A little translatable string over here?

2017-04-03 08:07 UTC, aleeks commented
Done bro!

2017-04-03 08:55 UTC, maximebiloe approved these changes

2017-04-05 09:23 UTC, merged

2017-04-05 09:23 UTC, maximebiloe commented
Thanks @aleeks