Doctrine without foreign for autoupgrade backup
PrestaShop/PrestaShop pull request #7746
Opened 2017-04-06 09:12 UTC by aleeks

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.1.x
| Description?  | Doctrine without foreign for autoupgrade backup
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-2779
| How to test?  | Do a rollback

Thanks to @jocel1 , see: https://github.com/PrestaShop/PrestaShop/pull/7620

This PR will works on release+1 backup.
**If it merged on 1.7.1.2, autoupgrade backup will works on 1.7.1.3.**

2017-04-06 09:38 UTC, jocel1 requested changes

2017-04-06 09:38 UTC, jocel1 commented on src/PrestaShopBundle/Command/UpdateSchemaCommand.php
> +                throw($e);
You should perhaps write the exception message in $output instead of throwing the exception?

2017-04-06 09:38 UTC, jocel1 commented on src/PrestaShopBundle/Command/UpdateSchemaCommand.php
> +            ->setName('prestashop:schema:update-without-foreign')
do we really need to specify "-without-foreign" ?

2017-04-06 11:39 UTC, aleeks commented on src/PrestaShopBundle/Command/UpdateSchemaCommand.php
> +            ->setName('prestashop:schema:update-without-foreign')
Just to be explicit regarding symfony doctrine command

2017-04-06 12:17 UTC, aleeks commented on src/PrestaShopBundle/Command/UpdateSchemaCommand.php
> +                throw($e);
and continue the script ?

2017-04-06 12:55 UTC, jocel1 commented on src/PrestaShopBundle/Command/UpdateSchemaCommand.php
> +                throw($e);
no exit after printing the exception message

2017-04-06 13:49 UTC, jocel1 approved these changes

2017-04-06 13:50 UTC, aleeks commented on src/PrestaShopBundle/Command/UpdateSchemaCommand.php
> +                throw($e);
See with @jocel1 , ok like that.

2017-04-07 11:39 UTC, aleeks commented
See: https://github.com/PrestaShop/autoupgrade/pull/62

2017-04-07 11:45 UTC, aleeks commented
See: https://github.com/PrestaShop/autoupgrade/pull/63

2017-04-07 12:02 UTC, merged

2017-04-07 12:02 UTC, maximebiloe commented
Thank you @aleeks & @jocel1

2017-04-10 09:19 UTC, vincentbz commented
![banane](https://cloud.githubusercontent.com/assets/7567060/24854673/97dd00fe-1ddf-11e7-8666-c40c7fd81dd6.gif)