Fix allow order value
PrestaShop/PrestaShop pull request #7795
Opened 2017-04-17 17:54 UTC by fatmaBouchekoua

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.1.x
| Description?  | In the category page, "allow_oosps" variable returns zero with the option enabled.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-2757
| How to test?  | Go to BO and enable the option allow order when out of stock. And test it in both new products and category pages in FO.

2017-04-18 07:13 UTC, maximebiloe requested changes

2017-04-18 07:13 UTC, maximebiloe commented on classes/ProductAssembler.php
> +                LEFT JOIN {$prefix}stock_available stock
In PrestaShop, table aliases are named with the first letter of each word of the table name. So, it should be `sa` for `stock_available`

2017-04-18 11:57 UTC, aleeks requested changes

2017-04-18 11:57 UTC, aleeks commented on classes/ProductAssembler.php
> +			        AND sa.id_shop = $idShop  ";
Here, some extra spaces !

2017-04-19 12:01 UTC, aleeks commented on classes/ProductAssembler.php
> +                LEFT JOIN {$prefix}stock_available sa
If we are on GSA mode, we use ps_stock or not ?

2017-04-19 12:01 UTC, aleeks approved these changes

2017-04-21 16:07 UTC, fatmaBouchekoua commented on classes/ProductAssembler.php
> +                LEFT JOIN {$prefix}stock_available sa
There's no out no stock information in the ps_stock.

2017-04-21 16:07 UTC, fatmaBouchekoua commented on classes/ProductAssembler.php
> +                LEFT JOIN {$prefix}stock_available sa
There's no out no stock information in the ps_stock.

2017-05-09 08:39 UTC, maximebiloe approved these changes

2017-05-09 08:39 UTC, merged

2017-05-09 08:39 UTC, maximebiloe commented
Thank you @fatmaBouchekoua