New currency format
PrestaShop/PrestaShop pull request #7823
Opened 2017-04-26 13:42 UTC by idnovate

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | New currency format
| Type?         | New feature
| Category?     | CO
| BC breaks?    | N
| Deprecations? | N
| Fixed ticket? |
| How to test?  | Please indicate how to best verify that this PR is correct.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

2017-04-27 07:51 UTC, maximebiloe commented
Thanks for this contribution.
@AlexEven what do you think about this?

2017-06-23 14:45 UTC, eternoendless requested changes
Thanks for this contribution! We just need a small change.

2017-06-23 14:45 UTC, eternoendless commented on controllers/admin/AdminCurrenciesController.php
> +			    array('key' => 6, 'name' => '0.000,00X')
Please use four spaces instead of tabs for indentations.

2017-06-26 09:26 UTC, idnovate reviewed
Tabs to spaces in controllers/admin/AdminCurrenciesController.php

2017-06-26 14:05 UTC, AlexEven commented
@maximebiloe Can we add this in 1.6?
And is it that we need a new format, or should the "Euro" format be updated to include a dot as a thousand separator instead?
I don't know what's best / has the least impact for the version and users.

2017-06-27 08:24 UTC, eternoendless approved these changes
Thanks!

2017-06-27 08:28 UTC, idnovate commented
:simple_smile::simple_smile:

2017-09-01 09:40 UTC, eternoendless commented
@AlexEven I think it doesn't hurt to add it. Anyway, this will be better handled in 1.7.

2018-07-03 19:26 UTC, mickaelandrieu commented
Except if I'm wrong we don't accept any new features on `1.6.1.x` branch which is in maintenance mode until the end of the year.

Ping @eternoendless

2018-07-09 16:42 UTC, eternoendless commented
You are right @mickaelandrieu 

Unfortunately we cannot accept new features to the 1.6 branch. Sorry @idnovate!

2018-07-09 16:42 UTC, closed without merging