BO: Fix Stock cover report stock out calculation
PrestaShop/PrestaShop pull request #7844
Opened 2017-04-30 06:52 UTC by marksull

When running the Stock Cover Report from the Back Office > Stock > Stock Cover, the data in the field "Quantity Sold" is displaying either no value ("--") or an incorrect value.

In AdminStockCoverController.php in the getList method the quantity sold is calculated TWICE, in TWO different ways, resulting in two different results.

The first time quantity sold is calculated is getList in the following call:
$coverage = StockManagerFactory::getManager()->getProductCoverage.

StockManagerFactory::getManager()->getProductCoverage is used to determine the amount of stock sold over the coverage period specified then uses this value to calculate the amount of coverage required based on the amount of physical stock available.

The second time quantity sold is calculated in getList in the following call:
$qty_sold = $this->getQuantitySold($item['id_product'], $item['id'], $this->getCurrentCoveragePeriod());

Unfortunately this method performs a different query compared to that in StockManagerFactory::getManager()->getProductCoverage and yields different results to the value used in the first coverage calculation.

Based on my analysis the results reported by getQuantitySold can be significantly different (reporting no results), close or accurate depending on a variety of situations.

This fix creates a new method in StockManager with the query extracted from getProductCoverage to calculate the Product Out over the coverage period so it can be reused by AdminStockCoverController and hence return a consistent result.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | Done
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | No
| Deprecations? | No
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-6674
| How to test?  | Run the Stock Coverage Report

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

2017-05-02 08:43 UTC, xBorderie commented
Thanks for this one too :) Expect a review soon!

2017-09-01 10:05 UTC, eternoendless requested changes
Some small cosmetic changes are needed, but code looks good for me

2017-09-01 10:05 UTC, eternoendless commented on classes/stock/StockManagerInterface.php
> +     * @return int time
The return hint "time" doesn't match the description. You can simply copy-paste the description on the implementation: "Number of products sold over the coverage period`.

2017-09-01 10:05 UTC, eternoendless commented on classes/stock/StockManagerInterface.php
> +     * @param int $id_warehouse Optional
This should be int|null

2017-09-01 10:05 UTC, eternoendless commented on classes/stock/StockManager.php
> +    public function getProductOutForCoverage($id_product, $id_product_attribute, $coverage, $id_warehouse = null) {
Please add PHPDoc for the parameters, or simply use `@inheritdoc`

2017-09-01 10:05 UTC, eternoendless commented on classes/stock/StockManager.php
> +            ($id_warehouse ? ' AND s.`id_warehouse` = '.(int)$id_warehouse : '').'
This line is misaligned, it should be indented using tabs

2017-09-08 11:44 UTC, marksull commented on classes/stock/StockManagerInterface.php
> +     * @param int $id_warehouse Optional
Done

2017-09-08 11:44 UTC, marksull commented on classes/stock/StockManagerInterface.php
> +     * @return int time
Done

2017-09-08 11:44 UTC, marksull commented on classes/stock/StockManager.php
> +            ($id_warehouse ? ' AND s.`id_warehouse` = '.(int)$id_warehouse : '').'
Done

2017-09-08 11:45 UTC, marksull commented on classes/stock/StockManager.php
> +    public function getProductOutForCoverage($id_product, $id_product_attribute, $coverage, $id_warehouse = null) {
Don't understand what you are asking for here..feel free to commit the change

2017-09-22 15:33 UTC, eternoendless approved these changes

2017-12-18 14:41 UTC, eternoendless commented
Thank you @marksull

2017-12-18 14:41 UTC, merged