Fix price display in case of quantity specific price
PrestaShop/PrestaShop pull request #7869
Opened 2017-05-07 05:53 UTC by erouvier29

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | Fix price display when quantity discount on combination
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-7797
| How to test?  | 

Additional commit to #7644:
Fixes quantity discount on all combinations case
Fixes alternate currency case

2017-05-08 12:42 UTC, kmorgen commented
This fix the quantity discount listing on the product pages again, thanks!
However will still be messed up if changing currency. Also if using discount amount/percentage to make and quantity discount for a specific group, it will display correct values (for default currency), but calculate wrong in cart. Seem to deduct the discount from the retail price, not the 1pcs price for that particular group.

Please refer to: http://forge.prestashop.com/browse/PSCSX-9037

2017-07-24 10:05 UTC, marionf commented
Hello @erouvier29 
Can you please complete the "how to test" section with the steps ?
Thanks

2017-07-25 05:38 UTC, erouvier29 commented
@marionf: done
Regards

2017-07-25 09:30 UTC, marionf commented
Hello @erouvier29 

I think the price isn't good when there is a fixed specific price.
1) I import the united states pack localization (exchange rate 1.1639)
2) I create a product with a price of 100€ tax included.
3) I create a fixed specific price of 50€ tax included discount from quantity 2
4) The price displayed on the product page is 58.19 USD tax included instead of 58.20
![pr7869](https://user-images.githubusercontent.com/13449658/28565242-ea351342-712b-11e7-9235-4cd52b04c703.png)

In the cart the price displayed is well 58.20 USD tax included
![pr7869-5](https://user-images.githubusercontent.com/13449658/28565249-edd1afc4-712b-11e7-8835-155af6666b08.png)



The same scenario with a specific price of 50% discount from quantity 2 is good, the price displayed on the product page is well 58.20 USD tax included
![pr7869-4](https://user-images.githubusercontent.com/13449658/28565218-dd1860b0-712b-11e7-9a27-1fa24d6fad4a.png)

![pr7869-2](https://user-images.githubusercontent.com/13449658/28565214-d5b7d1de-712b-11e7-8e3f-33da2b103dbf.png)

2017-08-28 09:33 UTC, maximebiloe requested changes

2017-08-28 09:33 UTC, maximebiloe commented on controllers/front/ProductController.php
> +        	if ($quantity_discount['id_product_attribute']) {
There is an extra tab here. Can you remove it, please?

2017-08-28 09:33 UTC, maximebiloe commented on themes/default-bootstrap/js/product.js
> +});
Missing a tab here

2017-09-07 05:00 UTC, erouvier29 commented
Indentation corrected.
Rounding issue reported by @marionf still present.

2017-09-26 15:50 UTC, hibatallahAouadni commented
@erouvier29 could you please rebase it and resolve the conflits. 
Thanks in advance.

2020-01-24 10:25 UTC, closed without merging