[bug fix]  attribute color list  doen't show on product list if turning on smarty cache
PrestaShop/PrestaShop pull request #7876
Opened 2017-05-10 05:17 UTC by iTiaNex

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.x
| Description?  | attribute color list  doen't show on product list if turning on smarty cache 
| Type?         | bug fix 
| Category?     |  BO
| BC breaks?    | yes
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-6778
| How to test?  | turn on smarty cache

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

2017-05-10 06:17 UTC, jocel1 requested changes

2017-05-10 06:17 UTC, jocel1 commented on classes/controller/FrontController.php
> +                $tpl = $this->context->smarty->createTemplate(_PS_THEME_DIR_.'product-list-colors.tpl', $this->getColorsListCacheId($product['id_product']));
move this line inside the if() condition below

2017-05-10 06:17 UTC, jocel1 commented on classes/controller/FrontController.php
> +                if (isset($colors[$product['id_product']])) {
this if() is the same than the previous one, remove it and move the $product['color_list'] assignation

2017-05-10 06:17 UTC, jocel1 commented on classes/controller/FrontController.php
> +        Tools::restoreCacheSettings();
remove extra spaces

2017-05-10 06:43 UTC, TiaNex-Com reviewed
OK,thank you

2017-05-10 06:43 UTC, iTiaNex commented on classes/controller/FrontController.php
> +                if (isset($colors[$product['id_product']])) {
yes,thank you

2017-05-10 08:10 UTC, closed without merging

2017-05-10 08:37 UTC, iTiaNex commented
sorry,it seems it still didn't fix the bug,

2018-03-16 11:02 UTC, Casper-O commented
thanks @iTiaNex I first tested your PR but that quickly showed not to work (as you said), now i'm testing your code from your comment and so far it has been keeping the colors for the last 5 mins (and still counting). I am testing it on a 1.6.1.16 where colors disappear from the product-list in categories and manufacturer list of products.