Fix min width to select filters
PrestaShop/PrestaShop pull request #7916
Opened 2017-05-24 07:32 UTC by fatmaBouchekoua

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Labels in status filter are not shown correctly.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1655
| How to test?  | Go to product page and select active or inactive filter.

2017-06-01 14:21 UTC, maximebiloe requested changes

2017-06-01 14:21 UTC, maximebiloe commented on admin-dev/themes/new-theme/scss/theme.scss
> +#product_filter_column_active span.select2{
Please add a space between `select2` and `{` and don't put the `span` as a selector. According to our standards, we shouldn't target directly html element for CSS.

2017-06-06 12:50 UTC, vincentbz commented
Tested and ok, thanks !

<!--
status: 'QA approved'
-->

2017-06-06 14:46 UTC, maximebiloe approved these changes

2017-06-06 14:47 UTC, merged

2017-06-06 14:47 UTC, maximebiloe commented
Thanks @fatmaBouchekoua