Reuse symfony translator in legacy context if instantiated
PrestaShop/PrestaShop pull request #7919
Opened 2017-05-24 15:40 UTC by Quetzacoalt91

- [ ] https://github.com/PrestaShop/ps_linklist/pull/36 must be merged first!

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Prevent multiple loads of the translator if Symfony did the job.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | Check of `Context::getTranslator()` type must be compared to `Symfony\Component\Translation\TranslatorInterface`
| Deprecations? | Nope
| Fixed ticket? | /
| How to test?  | You can add a dump() in the constructor of Translator, and check it is not called two times.

2017-07-19 14:23 UTC, eternoendless submitted a review, later dismissed

2017-07-19 14:23 UTC, eternoendless commented on classes/Context.php
> +        if ($kernel instanceof Symfony\Component\HttpKernel\HttpKernelInterface) {
`HttpKernelInterface` doesn't guarantee the presence of a `getContainer()` method.
You should use `Symfony\Component\HttpKernel\KernelInterface` instead.

2017-07-19 14:24 UTC, eternoendless commented
Actually, I wonder if there's a way to inject the dependencyContainer on the context instance. It would make it available everywhere.

2017-07-19 14:44 UTC, Quetzacoalt91 commented on classes/Context.php
> +        if ($kernel instanceof Symfony\Component\HttpKernel\HttpKernelInterface) {
That's true, and because I copy pasted this code, we have other occurrences to modify!

2017-07-19 14:46 UTC, Quetzacoalt91 commented
@mickaelandrieu tried this 1 year ago with https://github.com/PrestaShop/PrestaShop/pull/4915, I guess you'd be interested in what he tried.

2017-07-28 16:15 UTC, eternoendless submitted a review, later dismissed
Code looks good.

I still think we should find a way to inject the kernel instead of using `global`, though.

2017-08-03 16:58 UTC, aleeks commented on classes/Context.php
> +            $this->translator = $sfContainer->get('translator');
I juste remove $sfContainer->getContainer because it was already container hihi :smile:

2017-08-04 09:05 UTC, eternoendless requested changes

2017-08-04 09:05 UTC, eternoendless commented on classes/Context.php
> +            $this->translator = $kernel->getContainer()->get('translator');
You need to change `$kernel` into `$container` and then replace `$kernel->getContainer()` by `$container`

2017-08-04 09:05 UTC, eternoendless submitted a review, later dismissed

2017-08-04 09:06 UTC, eternoendless commented on classes/Context.php
> +            $this->translator = $kernel->getContainer()->get('translator');
Disregard that, old patchset

2017-08-04 14:09 UTC, closed without merging