Fix displayed price on card (HT/TTC)
PrestaShop/PrestaShop pull request #7923
Opened 2017-05-26 10:24 UTC by fatmaBouchekoua

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | In the order process, the subtotal is shown Tax Incl and should be Tax Excl when customer group is set to "display prices in Tax Excl".
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-2140
| How to test?  | Set customer group to "display prices in Tax Excl" and go to card in FO.

2017-05-26 10:49 UTC, Quetzacoalt91 requested changes
I just made a quick review of the modified code, and this can be simpler! :wink:

2017-05-26 10:49 UTC, Quetzacoalt91 commented on src/Adapter/Cart/CartPresenter.php
> +            'amount' => $this->includeTaxes() ? $cart->getOrderTotal(true, Cart::ONLY_PRODUCTS) : $cart->getOrderTotal(false, Cart::ONLY_PRODUCTS),
Wow, keep it simple!

```php
'amount' => $cart->getOrderTotal($this->includeTaxes(), Cart::ONLY_PRODUCTS),
```

2017-05-26 10:49 UTC, Quetzacoalt91 commented on src/Adapter/Cart/CartPresenter.php
> +            'value' => $this->includeTaxes() ? $this->priceFormatter->format(($cart->getOrderTotal(true, Cart::ONLY_PRODUCTS))) : $this->priceFormatter->format(($cart->getOrderTotal(false, Cart::ONLY
Same comment as above:

```php
'value' => $this->priceFormatter->format(($cart->getOrderTotal($this->includeTaxes(), Cart::ONLY_PRODUCTS))),
```

2017-05-26 10:53 UTC, Quetzacoalt91 commented
This is not related to the fix you look for, but interesting to take in account.
It seems we can reduce a little bit more the execution time of this function, if we store the result of `$cart->getOrderTotal($this->includeTaxes(), Cart::ONLY_PRODUCTS)` in a variable.

You could reuse it with `'amount'` and `'value'` then.

2017-05-30 14:44 UTC, Quetzacoalt91 approved these changes

2017-05-30 14:47 UTC, Quetzacoalt91 commented on src/Adapter/Cart/CartPresenter.php
> +        $totalCardAmount = $cart->getOrderTotal($this->includeTaxes(), Cart::ONLY_PRODUCTS);
Even if it won't break anything, I guess you meant `$totalCartAmount` instead of `$totalCardAmount`

2017-06-07 08:03 UTC, aleeks commented
Hello @fatmaBouchekoua 
Oups, we merged this https://github.com/PrestaShop/PrestaShop/pull/7521/files yesetday.. but looks like incomplete compared to you. Can you rebase and adapt your PR please ?

2017-06-07 09:53 UTC, aleeks commented
Done!

2017-06-12 13:54 UTC, aleeks commented
Thank you @fatmaBouchekoua

2017-06-12 13:54 UTC, merged