Add amount discount on product thumbnails
PrestaShop/PrestaShop pull request #7924
Opened 2017-05-26 13:55 UTC by fatmaBouchekoua

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Discounts shown on thumbnails for percentage, and not for amount
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-3030
| How to test?  | Add a specific price to a product, an amount discount, and visualize the product on FO.

2017-06-08 12:51 UTC, vincentbz commented
Hi @fatmaBouchekoua 

Thanks for that PR, the discount is now shown.
But behind the discount, the product name is also shown 😄 is it possible to remove it please ? 

![image](https://user-images.githubusercontent.com/7567060/26929397-d563623a-4c59-11e7-963d-692e4c4ae252.png)
![image](https://user-images.githubusercontent.com/7567060/26929409-e75695ca-4c59-11e7-9661-246039bd9e6d.png)

2017-06-09 10:47 UTC, fatmaBouchekoua commented
Hello @vincentbz ,
The product name is shown because this product doesn't have image ( the alt attribute of the img tag)

2017-06-20 16:29 UTC, maximebiloe requested changes

2017-06-20 16:29 UTC, maximebiloe commented on themes/classic/templates/catalog/_partials/miniatures/product.tpl
> +                  <span class="discount-amount discount-product">-{$product.discount_amount}</span>
Could you please remove this "calculation" from the template to do it in the presenter like we do it for the percentage discount here: https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Product/ProductPresenter.php#L159

2017-06-21 14:16 UTC, fatmaBouchekoua commented on themes/classic/templates/catalog/_partials/miniatures/product.tpl
> +                  <span class="discount-amount discount-product">-{$product.discount_amount}</span>
Done Thanks !

2017-06-29 06:53 UTC, maximebiloe submitted a review, later dismissed

2017-07-21 12:26 UTC, maximebiloe commented
Hello @fatmaBouchekoua,

Could you rebase you PR and make the changes on the `StarterTheme` too, please?

Regards

2017-09-19 12:55 UTC, mickaelandrieu approved these changes

2017-09-19 14:16 UTC, merged

2017-09-19 14:16 UTC, Quetzacoalt91 commented
Thank you @fatmaBouchekoua