Code Optimization
PrestaShop/PrestaShop pull request #7942
Opened 2017-05-31 07:42 UTC by kompilorb

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Comments from other PR : https://github.com/PrestaShop/PrestaShop/pull/7816
| Type?         | improvement
| Category?     |  BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/pull/7816
| How to test?  | Create in BO a voucher (the problems is for all type or rules). After create a customers, and create you cart, if the first product does not in condition for rules, if after you add product corresponding to a rules, voucher must can be applicable.

2017-05-31 07:43 UTC, kompilorb commented
@eternoendless

2017-05-31 08:41 UTC, eternoendless requested changes
Thanks for this PR! There are still two or three small things to fix.

2017-05-31 08:41 UTC, eternoendless commented on classes/CartRule.php
> +    /* @var array $only_one_gift
Don't forget that in order for a comment to be a valid PHPDoc it must start with `/**` and not `/*` (see [the proposed standard](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#3-definitions)).

Also, keep in mind that when documenting class properties, you don't need to write the property name again.

In addition, I think that for properties it is common practice to write the description before the `@var` statement.

Here's my proposal:

```php
    /**
     * This variable controls that a free gift is offered only once, even when multi-shippping is activated
     * and the same product is delivered in both addresses
     *
     * @var array
     */
```

2017-05-31 08:41 UTC, eternoendless commented on classes/CartRule.php
> +            if (in_array($products, $eligibleProducts)) {
I think you mean `$product` instead of `$products` here, don't you?

2017-05-31 08:41 UTC, eternoendless commented on classes/CartRule.php
> +            );
Whoops, I think this block needs to be indented one step to the left.

2017-05-31 08:41 UTC, eternoendless commented on classes/CartRule.php
> +    protected function filterProducts($products, $eligibleProducts, $ruleType)
Thank you for changing the method signature, but it looks like you forgot to change the method calls!

Also, please remember to make them instance calls if you don't need them to be static.

2017-05-31 08:57 UTC, Shudrum commented on classes/CartRule.php
> +            if (in_array($products, $eligibleProducts)) {
+1
How can it just works? 🤕

2017-05-31 10:03 UTC, eternoendless approved these changes
Thanks!

2017-06-01 07:25 UTC, maximebiloe requested changes

2017-06-01 07:25 UTC, maximebiloe commented on classes/CartRule.php
> +    protected function filterProducts($products, $eligibleProducts, $ruleType)
We can't simply delete a public method like this. Please, deprecate it first for `1.7.2`, then we'll be able to delete it.

2017-06-01 07:59 UTC, Shudrum commented on classes/CartRule.php
> +    protected function filterProducts($products, $eligibleProducts, $ruleType)
This method added on a PR just before. No problem, this is just to avoid this kind of problem!

2017-06-01 08:00 UTC, Shudrum commented on classes/CartRule.php
> +    protected function filterProducts($products, $eligibleProducts, $ruleType)
+was -_-

2017-06-01 08:06 UTC, maximebiloe approved these changes

2017-06-01 08:06 UTC, maximebiloe commented on classes/CartRule.php
> +    protected function filterProducts($products, $eligibleProducts, $ruleType)
Ok :wink:

2017-06-01 11:08 UTC, Quetzacoalt91 requested changes
Sorry dude, the previous reviews brought you new changes to apply :stuck_out_tongue:

2017-06-01 11:08 UTC, Quetzacoalt91 commented on classes/CartRule.php
> +        $i18n, $offset = null,
If you wanted to write param perline, maybe you would like to separate `$i18n` from `$offset` ?

2017-06-01 11:08 UTC, Quetzacoalt91 commented on classes/CartRule.php
>              return $arrayProduct;
Now you renamed the parameter, `$arrayProduct` is undefined

2017-06-01 11:08 UTC, Quetzacoalt91 commented on classes/CartRule.php
> +            $productsList = $arrayProduct;
`$arrayProduct` is undefined

2017-06-01 11:08 UTC, Quetzacoalt91 commented on classes/CartRule.php
> +                $return[] = $arrayProduct[$k];
`$arrayProduct` is undefined

2017-06-06 15:28 UTC, Quetzacoalt91 approved these changes

2017-06-08 10:07 UTC, merged