TE: Add PHP CodeSniffer to travis, check only modified files
PrestaShop/PrestaShop pull request #7979
Opened 2017-06-08 10:30 UTC by eternoendless

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Travis now runs PHP CodeSniffer on the modified files in order to enforce PSR-2 rules (except the namespace on non-namespaced legacy files).<br>Also, the PHP linter is now executed on modified files only.
| Type?         | improvement
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  |  Fork this branch, introduce problems in your PHP files, commit, see the build fail 💥<br>Commit a fix, see the build pass ✅

2017-06-09 12:49 UTC, aleeks submitted a review, later dismissed
Looks like ok, as we said, we need to clean all file before merge it!

2017-06-12 14:49 UTC, eternoendless commented
Here's the PR for the cleanup: https://github.com/PrestaShop/PrestaShop/pull/7997

2017-06-19 08:38 UTC, Soullivaneuh commented
You can also configure this one: http://cs.sensiolabs.org/

It's more a fixer than a sniffer with additional functionalities and rules which may interest you.

You can also run it on Travis with the `--dry-run` option to have the diff and a return code if code differs.

I could provide a PR if you are interested.

2017-06-19 13:18 UTC, eternoendless commented
Hi @Soullivaneuh

Thanks for this suggestion, I'll look into it and see how it can be integrated.

2017-07-17 09:36 UTC, Quetzacoalt91 commented
Can you please rebase in order to fix the conflicts in  composer.lock please ?

2017-07-25 16:10 UTC, Quetzacoalt91 approved these changes

2017-07-26 08:33 UTC, Quetzacoalt91 commented
Seen with @eternoendless, we also want to check if there are other solutions to check the standards on each PR. T=That's why this PR is not merged yet.

2017-07-26 08:39 UTC, soullivaneuh requested changes

2017-07-26 08:39 UTC, Soullivaneuh commented on tests/phpcs-ignore
> +modules/*
A new line at end of file may be added.

2017-08-29 15:19 UTC, Quetzacoalt91 commented
@eternoendless, if I remember well, you wanted to go back on the standard verification, and only check the syntax on modified files.

Could you please update your PR for this purpose?

2018-09-04 15:53 UTC, Quetzacoalt91 commented
This PR is now a duplicate of https://github.com/PrestaShop/PrestaShop/pull/9468

I'm closing it. Feel free to reopen it if something still needs to be brought to the repository.

2018-09-04 15:53 UTC, closed without merging