No permissions filled
PrestaShop/PrestaShop pull request #7982
Opened 2017-06-08 12:25 UTC by djbuch

When getProfileAccesses was requested for an idProfile different than super admin profile and for type class_name, no permissions where filled.
This was causing notification icon never to be displayed for non super admin employees for example.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | When getProfileAccesses was requested for an idProfile different than super admin profile and for type class_name, no permissions where filled.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | For a non super admin employee the notification icon does not display until you apply this fix

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

2017-08-08 14:56 UTC, Quetzacoalt91 commented
For this PR review, I dumped a variable in classes/controllers/AdminController.php

l. 1871
```php
            $accesses = Profile::getProfileAccesses($this->context->employee->id_profile, 'class_name');
            dump($accesses);
```

## Before

![capture du 2017-08-08 15-52-49](https://user-images.githubusercontent.com/6768917/29078280-cbd11564-7c51-11e7-9449-7a00168a9685.png)
[...]
![capture du 2017-08-08 15-53-00](https://user-images.githubusercontent.com/6768917/29078286-cecb8a2e-7c51-11e7-8540-bd011ee6086c.png)

## After

![capture du 2017-08-08 15-52-31](https://user-images.githubusercontent.com/6768917/29078297-d766b578-7c51-11e7-8337-62326535db35.png)

2017-08-08 15:03 UTC, Quetzacoalt91 requested changes

2017-08-08 15:03 UTC, Quetzacoalt91 commented on classes/Profile.php
>                      self::$_cache_accesses[$idProfile][$type][$idTab][array_search('1', $row)] = '1';
Can you please refacto this function in order to replace `$idTab` with `$tab`? We don't always deal with IDs so this name is now a non-sense.

2017-08-08 15:03 UTC, Quetzacoalt91 commented on classes/Profile.php
> +        ');
This part is duplicated from `function findIdTabByAuthSlug($authSlug)`.
Please write a common function used by `findIdTabByAuthSlug()` and `findClassNameByAuthSlug()`

We should get something like this:

```php

    private static function findByAuthSlug($authSlug)
    {
        preg_match(
            '/ROLE_MOD_[A-Z]+_(?P<classname>[A-Z]+)_(?P<auth>[A-Z]+)/',
            $authSlug,
            $matches
        );
        $result = Db::getInstance()->getRow('
            SELECT `id_tab`, `class_name`
            FROM `'._DB_PREFIX_.'tab` t
            WHERE UCASE(`class_name`) = "'.$matches['classname'].'"
        ');
        return $result;
    }

    /**
     *
     * @param string $authSlug
     * @return int
     */
    private static function findIdTabByAuthSlug($authSlug)
    {
        $tab = $this->findByAuthSlug();
        return $tab['id_tab'];
    }
    
    /**
     *
     * @param string $authSlug
     * @return string
     */
    private static function findClassNameByAuthSlug($authSlug)
    {
        $tab = $this->findByAuthSlug();
        return $tab['class_name'];
    }
```

2019-10-22 08:53 UTC, marionf commented
Hello @djbuch 

Since we have not had answer for more than 30 days and the PR isn't acceptable as is, I close it
Feel free to open a new one if needed

2020-05-06 09:39 UTC, closed without merging