Pass param content_only param to overrideLayoutTemplate call
PrestaShop/PrestaShop pull request #8048
Opened 2017-06-26 09:14 UTC by prestamodule

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Pass the content only param to the hook call.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | It's just an easy way to get the params "content_only" inside the hook call.

2017-06-26 09:34 UTC, xBorderie commented
I restarted the PHP 7.1 test, just in case.

2017-06-27 12:38 UTC, aleeks requested changes
Hello,
Just 2 fix to add
Regards

2017-06-27 12:38 UTC, aleeks commented on classes/controller/FrontController.php
> +                'content_only' => (int) $content_only,
(int) not needed here

2017-06-27 12:38 UTC, aleeks commented on classes/controller/FrontController.php
> +        if ((int) $content_only) {
(int) not needed here

2017-06-27 12:42 UTC, aleeks approved these changes

2017-07-21 09:47 UTC, maximebiloe commented
Thank you @prestamodule

2017-07-21 09:47 UTC, merged