Display new link widget blocs
PrestaShop/PrestaShop pull request #8051
Opened 2017-06-27 13:34 UTC by fatmaBouchekoua

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | When you add a new link widget, you get only the title displayed in the FO.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-3180
| How to test?  | Create a new block in Link Widget panel, apply the new block to "DisplayFooterBefore" and check if it's been well displayed in the FO

2017-06-27 14:02 UTC, maximebiloe requested changes

2017-06-27 14:02 UTC, maximebiloe commented on themes/classic/modules/ps_linklist/views/templates/hook/linkblock.tpl
> +      <ul id="footer_sub_menu_{$_expand_id}" {if $linkBlock.hook == 'displayFooter' }class="collapse"{/if}>
If there is a different behavior depending on hook, it's better to use two templates. We absolutely want to avoid if statement in templates

2017-10-03 14:35 UTC, mickaelandrieu approved these changes

2017-10-04 16:01 UTC, Quetzacoalt91 requested changes
Hello,

No need to duplicate the content of the module in order to fix that issue.
The content is here, but hidden by the theme CSS. Instead of duplicating the templates, the design must be fixed in order to show the list outside the footer. This seems simpler that we could think.

2017-10-18 15:27 UTC, Quetzacoalt91 commented
I disapproved this PR, and suggested another change which does not imply a new template. Closed and replaced by https://github.com/PrestaShop/PrestaShop/pull/8416

2017-10-18 15:27 UTC, closed without merging