Make the store email clickable in the footer
PrestaShop/PrestaShop pull request #8060
Opened 2017-06-28 13:32 UTC by fatmaBouchekoua

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | The store email is not clickable in the footer
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-3181
| How to test?  | Check if the store email can be clickable in the FO footer.

2017-06-28 13:52 UTC, xBorderie commented
This introduces HTML tags in a translatable strings, which we are trying to prevent (hence the [1][/1] pseudp-tags, which are replaced by <span></span>). So, isn't there a solution which would avoid introducing HTML tags?

ping @AlexEven

2017-07-11 09:30 UTC, vincentbz commented
Hi @fatmaBouchekoua 

Could you move it to 1.7.2.x branch please ?
So that it can be taken in 1.7.2.1 version.

Thanks !

2017-07-21 08:14 UTC, maximebiloe requested changes

2017-07-21 08:14 UTC, maximebiloe commented on themes/classic/modules/ps_contactinfo/ps_contactinfo.tpl
> +          s='Email us: <a href="mailto:%email%" class="dropdown">[1]%email%[/1]</a>'
No HTML tags into translated strings.
Please, make the same as the `<span>` tag.

2017-08-03 08:30 UTC, fatmaBouchekoua commented on themes/classic/modules/ps_contactinfo/ps_contactinfo.tpl
> +          s='Email us: <a href="mailto:%email%" class="dropdown">[1]%email%[/1]</a>'
Done. Thanks!

2017-08-03 08:38 UTC, maximebiloe submitted a review, later dismissed

2017-08-03 08:38 UTC, maximebiloe commented on themes/classic/modules/ps_contactinfo/ps_contactinfo.tpl
> +            '[1]' => '<a href="mailto:%email%" class="dropdown">',
And, how the %email% will be replaced? 🤔

2017-08-03 09:30 UTC, aleeks commented on themes/classic/modules/ps_contactinfo/ps_contactinfo.tpl
> +            '[1]' => '<a href="mailto:%email%" class="dropdown">',
![email](https://user-images.githubusercontent.com/9074610/28915362-2c769400-783f-11e7-9489-a80a81f7438b.png)

2017-08-03 09:30 UTC, aleeks commented on themes/classic/modules/ps_contactinfo/ps_contactinfo.tpl
> +            '[1]' => '<a href="mailto:%email%" class="dropdown">',
nope

2017-08-03 09:41 UTC, aleeks commented
done ;)

![email](https://user-images.githubusercontent.com/9074610/28915812-9eb4772a-7840-11e7-8526-590ad0f4cbb2.png)

2017-08-03 09:42 UTC, fatmaBouchekoua commented
Thank you @aleeks

2017-08-04 09:27 UTC, Quetzacoalt91 approved these changes

2017-08-04 09:28 UTC, merged

2017-08-04 09:29 UTC, Quetzacoalt91 commented
Thanks @fatmaBouchekoua