Add ids to recommended-payment & carriers & others
PrestaShop/PrestaShop pull request #8096
Opened 2017-07-06 08:24 UTC by aleeks

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.2.x
| Description?  | Add ids to recommended-payment & carriers & others
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | -

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

2017-07-06 14:13 UTC, hibatallahAouadni requested changes

2017-07-06 14:13 UTC, hibatallahAouadni commented on admin-dev/themes/default/template/controllers/employees/helpers/form/form.tpl
> +		<div id="addons-connexion-container" ="col-lg-{if isset($input.col)}{$input.col|intval}{else}9{/if} {if !isset($input.label)}col-lg-offset-3{/if}">
@aleeks you delete the attribute class by mistake ;)

2017-07-06 14:17 UTC, aleeks commented on admin-dev/themes/default/template/controllers/employees/helpers/form/form.tpl
> +		<div id="addons-connexion-container" ="col-lg-{if isset($input.col)}{$input.col|intval}{else}9{/if} {if !isset($input.label)}col-lg-offset-3{/if}">
thank you !

2017-07-12 08:58 UTC, eternoendless commented on admin-dev/themes/default/template/controllers/employees/helpers/form/form.tpl
> +		<div id="addons-connexion-container" class="col-lg-{if isset($input.col)}{$input.col|intval}{else}9{/if} {if !isset($input.label)}col-lg-offset-3{/if}">
`id="addons-connexion-container"`

If possible, please change "connexion" to "connection"

2017-07-12 09:09 UTC, aleeks commented on admin-dev/themes/default/template/controllers/employees/helpers/form/form.tpl
> +		<div id="addons-connexion-container" class="col-lg-{if isset($input.col)}{$input.col|intval}{else}9{/if} {if !isset($input.label)}col-lg-offset-3{/if}">
ooooooooooooooh sh**t :( yes

2017-07-12 09:24 UTC, aleeks commented
Done

2017-07-12 10:10 UTC, Quetzacoalt91 approved these changes

2017-07-12 12:02 UTC, eternoendless approved these changes
Code looks good to me! Thanks @aleeks

2017-07-12 12:04 UTC, aleeks commented
You can merge it btw! :smile:

2017-07-12 12:43 UTC, merged