Fix save carrier with invalid ranges
PrestaShop/PrestaShop pull request #8097
Opened 2017-07-06 10:52 UTC by Azouz-Jribi

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | When you create or edit a carrier with invalid ranges, you should be not able to save it.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-3155
| How to test?  | Go to BO > shipping > carrier > Edit , add a new range and fill its input with incorrect values. Then, try to click another input field, the incorrect fields will be red, error will be displayed and the submit button will be disabled.

2017-07-11 09:20 UTC, vincentbz commented
Hi @Azouz-Jribi 

Could you move it to 1.7.2.x branch please ? 
So that it can be taken in 1.7.2.1 version.

Thanks !

2017-07-13 07:08 UTC, maximebiloe requested changes

2017-07-13 07:08 UTC, maximebiloe commented on js/admin/carrier_wizard.js
> +	{
Please, put the bracket on the previous line

2017-07-13 08:41 UTC, Azouz-Jribi commented on js/admin/carrier_wizard.js
> +	{
Hi @maximebiloe 
Correction is done

regards

2017-07-13 08:42 UTC, maximebiloe submitted a review, later dismissed

2017-07-13 09:02 UTC, marionf commented
Hello @Azouz-Jribi 
There is a problem when I try to change a range or when I click several times in the different fields.
The page freezes.

![pr8097](https://user-images.githubusercontent.com/13449658/28158660-bdd85dc4-67ba-11e7-85ff-c19eb900137a.png)

2017-07-21 13:18 UTC, vincentbz commented
Hi @Azouz-Jribi 

could you check this with @marionf  please ? 

Thanks !

2017-07-21 14:38 UTC, Azouz-Jribi commented
Hi @marionf,
This bug was already exist from the beginning, but with the new modification will be more reproducible.

![bug js](https://user-images.githubusercontent.com/17438504/28468045-b808e7b8-6e29-11e7-9b86-9db57c44086b.gif)

After some change the page crashes, see the GIF.

2017-07-24 13:58 UTC, eternoendless commented on js/admin/carrier_wizard.js
> +	$('tr.range_sup td input:text, tr.range_inf td input:text').blur(function () {
This selector is written at least twice elsewhere (lines 410 and 569). Please consider writing an encapsulating function somewhere else:
```js
var carrier = {
  getRangeBoundaryInputs: function() {
     return $('tr.range_sup td input:text, tr.range_inf td input:text');
  }
};
```
and then
```js
var rangeBoundaryInputs = carrier.getRangeBoundaryInputs();
rangeBoundaryInputs
  .blur(...)
  .typeWatch(...);

2017-07-24 13:58 UTC, eternoendless commented on js/admin/carrier_wizard.js
> +			$('tr.range_inf td input:text').closest('div.input-group').removeClass('has-error');
You can merge these two lines into one using the function I suggested.

2017-07-24 13:58 UTC, eternoendless commented on js/admin/carrier_wizard.js
> +}
All new methods should be "namespaced" (that is, not in the global scope).

One "namespacing" technique is to make functions be properties of a namespace variable (see the example I provided before).

2017-07-25 08:43 UTC, marionf commented
Hello @Azouz-Jribi
I can't validate your PR, the page freezes to easily.
Also, some fields are disabled and I can't enter the price for the range.
I attached a new screenrecord on the forge ticket to show you.

2017-07-27 10:31 UTC, Azouz-Jribi commented
Hi @marionf 
i will try to fix it, but it will take some time

2017-08-24 17:23 UTC, Azouz-Jribi commented
Hello @marionf 
Correction is done.
Can you retest it please ?

Thanks ;)

2017-08-25 08:26 UTC, eternoendless submitted a review, later dismissed
@Azouz-Jribi QA needs to wait for code review before they can verify tickets.

2017-08-25 08:26 UTC, eternoendless commented on js/admin/carrier_wizard.js
> +const checkCarriersRangeInput = function checkCarriersRangeInput() {
We cannot use `const` in legacy ES5 files, ES6 features can only be used in "babelized" files.

2017-08-25 08:26 UTC, eternoendless commented on js/admin/carrier_wizard.js
> +const checkCarriersRangeInput = function checkCarriersRangeInput() {
The whole block for this function is wrongly intended. You should use two spaces for indents.

2017-08-25 08:26 UTC, eternoendless commented on js/admin/carrier_wizard.js
> +		}
You can avoid repeating yourself:

```js
if ($range.closest('div.input-group.has-error').length === 0)) {
  if (is_valid) {
    // ...
  } else {
    // ..
  }
}

2017-08-25 15:47 UTC, Azouz-Jribi commented
Hi @eternoendless 
Correction is done, can you check it ?

Thanks

2017-08-28 08:41 UTC, marionf commented
Hello @Azouz-Jribi
When I try to change a range, even if the range isn't overlapping anymore, the fields stay in red and there is an error message. I have to click several time in the fields to make it disappear.
I attached a new screenrecord on the forge ticket.

2017-09-18 10:32 UTC, Azouz-Jribi commented
Hello @marionf 
Correction is done.

@eternoendless can you check it ?

2017-10-03 14:33 UTC, mickaelandrieu submitted a review, later dismissed

2017-10-04 08:55 UTC, marionf commented
Hello @Azouz-Jribi 
I still can save the carrier if the range are overlaping.
You should see the screenrecord11.mkv on the forge ticket.

2017-10-09 15:03 UTC, Azouz-Jribi commented
Hello @marionf
Correction is done.

2017-10-09 15:52 UTC, marionf commented
Thank you @Azouz-Jribi, I will re-test after the code review

2017-10-13 14:46 UTC, Azouz-Jribi commented
Hi @eternoendless 
Rebase is done ;)

2017-10-16 15:08 UTC, eternoendless commented
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[js/admin/carrier_wizard.js, line 766 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8097#-KwFleDl62IvGMwcR9FP:-KwFleDl62IvGMwcR9FQ:bpsqz7m) ([raw file](https://github.com/prestashop/prestashop/blob/72e9eb92685bd875b7c55987d0417d4b8852fb6d/js/admin/carrier_wizard.js#L766)):*
> ```JavaScript
> var carriersRangeInputs = {
> 	/** Check the carriers range inputs after each change */
> 	'checkCarriersRangeInput': function() {
> ```

It's not necessary to add single quotes to object property names.

---

*[js/admin/carrier_wizard.js, line 766 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8097#-KwFlggycUkbdzmwbFYk:-KwFlggycUkbdzmwbFYl:b-3a396x) ([raw file](https://github.com/prestashop/prestashop/blob/72e9eb92685bd875b7c55987d0417d4b8852fb6d/js/admin/carrier_wizard.js#L766)):*
> ```JavaScript
> var carriersRangeInputs = {
> 	/** Check the carriers range inputs after each change */
> 	'checkCarriersRangeInput': function() {
> ```

I think the name of this method is misleading. The way it is now, it would make you believe it actually performs the validation, but it actually initializes the watch on inputs in order to validate them on change.

Method names should be an abstraction of what the method actually does.

---

*[js/admin/carrier_wizard.js, line 790 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8097#-Kw_epkzvWYijPGaiJ27:-Kw_epkzvWYijPGaiJ28:b-frgh1f) ([raw file](https://github.com/prestashop/prestashop/blob/72e9eb92685bd875b7c55987d0417d4b8852fb6d/js/admin/carrier_wizard.js#L790)):*
> ```JavaScript
> 			$(this).off();
> 			if ($('.wizard_error').length === 0) {
> 				index = $(this).closest('td').index();
> ```

Missing `var` before `index` here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8097)*
<!-- Sent from Reviewable.io -->

2017-10-17 08:43 UTC, Azouz-Jribi commented
Hello @eternoendless 
Can you check it ?

Thanks ;)

2017-10-17 10:20 UTC, eternoendless commented
Looks good to me

The code has grown too complex and needs refactoring though.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8097#-:-Kwdq4mkwvMp3yox9bn4:b-u6jjo9)*
<!-- Sent from Reviewable.io -->

2017-10-17 10:20 UTC, eternoendless submitted a review, later dismissed

2017-10-19 11:35 UTC, prasanthSelvar commented
Hello @Azouz-Jribi,
I can still save carrier when I have the warning message "the range is not valid".
Especially in the case where the first value is greater than the second value.
See range.gif on the JIRA ticket [BOOM-3155](http://forge.prestashop.com/browse/BOOM-3155).

2017-10-19 16:20 UTC, Azouz-Jribi commented
Hello @prasanthSelvar 
Correction is done ;)

2017-10-20 14:52 UTC, eternoendless commented
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8097)*
<!-- Sent from Reviewable.io -->

2017-10-20 14:53 UTC, eternoendless approved these changes

2017-10-23 10:04 UTC, eternoendless commented
Thank you @Azouz-Jribi

2017-10-23 10:04 UTC, merged

2019-06-12 10:42 UTC, marzenarog commented
> Questions	Answers
> Branch?	develop
> Description?	When you create or edit a carrier with invalid ranges, you should not be able to save it.
> Type?	bug fix
> Category?	BO
> BC breaks?	no
> Deprecations?	no
> Fixed ticket?	http://forge.prestashop.com/browse/BOOM-3155
> How to test?	Go to BO > shipping > carrier > Edit , add a new range and fill its input with incorrect values. Then, try to click another input field, the incorrect fields will be red, error will be displayed and the submit button will be disabled.
> This change is [<img alt="Reviewable" height="34" src="https://camo.githubusercontent.com/0210135a140627a19496177795afadacb8502c1f/68747470733a2f2f72657669657761626c652e696f2f7265766965775f627574746f6e2e737667">](https://reviewable.io/reviews/prestashop/prestashop/8097)

Hello  guys!
I have same problem, could someone help me pls ( ranges are overlapping)  ?????   marzenarogus@gmail.com