WIP: DB connections migration
PrestaShop/PrestaShop pull request #8115
Opened 2017-07-10 12:05 UTC by Quetzacoalt91

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR migrates all DB connections to the existing DBAL library. `DBCore` is kept for backward compatibity and is used as a proxy.
| Type?         | new feature
| Category?     | CO
| BC breaks?    | Yes, all subclasses of DBCore
| Deprecations? | Yes, all subclasses of DBCore
| Fixed ticket? | /
| How to test?  | Use your shop

2017-07-10 13:14 UTC, jocel1 requested changes

2017-07-10 13:14 UTC, jocel1 commented on classes/db/Db.php
> +        return str_replace($search, $replace, $str);    }
better use $this->link->quote();

2017-07-10 13:14 UTC, jocel1 commented on classes/db/Db.php
> +        throw new Symfony\Component\Serializer\Exception\UnsupportedException();
$this->query("use ".$dbName); ?

2017-07-10 13:14 UTC, jocel1 commented on classes/db/Db.php
> +    public function set_db($db_name)
camelCase ?

2017-07-10 13:14 UTC, jocel1 commented on classes/db/Db.php
> +     * @return PDO|mysqli|resource Resource
@return \Doctrine\DBAL\Connection ?

2017-07-10 13:14 UTC, jocel1 commented on classes/db/Db.php
> +    public static function tryToConnect($server, $user, $pwd, $db, $new_db_link = true, $engine = null, $timeout = 5)
camelCase for new variables

2017-07-10 13:14 UTC, jocel1 commented on classes/db/Db.php
> +        $sql = 'SHOW ENGINES';
FYI SELECT ENGINE FROM INFORMATION_SCHEMA.ENGINES; covers MySQL >= 5.0.
Not needed anymore if SHOW VARIABLES LIKE 'innodb_%'; is used

2017-07-10 13:14 UTC, jocel1 commented on classes/db/Db.php
> +        $sql = 'SHOW VARIABLES WHERE Variable_name = \'have_innodb\'';
SHOW VARIABLES LIKE 'innodb_%'; to cover old version ?

2017-07-14 14:55 UTC, Quetzacoalt91 commented on classes/db/Db.php
> +    public function set_db($db_name)
For backward compatibility reasons, I won't change the function name.

2017-07-14 14:55 UTC, Quetzacoalt91 commented on classes/db/Db.php
> +        throw new Symfony\Component\Serializer\Exception\UnsupportedException();
Yeah obviously. Will be updated.

2017-07-14 15:04 UTC, Quetzacoalt91 commented on classes/db/Db.php
> +        return str_replace($search, $replace, $str);    }
It seems quote() is used for a specific variable before being inserted in a sql request. With _escape, we search in the  whole sql request .

2017-07-25 09:27 UTC, Quetzacoalt91 commented
To be done later, when we will be able to have the symfony kernel during Db class instanciation.

One of the objective of this PR is to share the DB connection between Symfony and the legacy. This requires the Symfony kernel to be initialized BEFORE the legacy one. Actually, this is not possible even in the back-office, so I lose this performance gain.

I close this PR until we get a Symfony kernel available earlier, and this must be done somewhere else.

2017-07-25 09:27 UTC, closed without merging