Fix the style of product reference in the stock management page
PrestaShop/PrestaShop pull request #8160
Opened 2017-07-19 14:04 UTC by Azouz-Jribi

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.2.x
| Description?  | When creating a product with a reference longer than 24 characters, we have a bad display in stock page.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-3489
| How to test?  | Create a product reference with more than 24 characters, go to BO > Catalog > Stock and check in reference column that it is displayed correctly (in two lines).

2017-07-19 14:43 UTC, aleeks requested changes

2017-07-19 14:43 UTC, aleeks commented on admin-dev/themes/new-theme/public/theme.css
> +.stock-app table td {
Hello @Azouz-Jribi 
It's not here to change the css to the vue application. It's directly in the vue file. 
@nihco2, can you explain better please!
Regards

2017-07-19 14:50 UTC, Azouz-Jribi commented on admin-dev/themes/new-theme/public/theme.css
> +.stock-app table td {
Hi @aleeks 
I know ;) 
But when i generate the assets, the "theme.css" file is modified.

Regards

2017-07-20 10:25 UTC, Azouz-Jribi commented
Hello @aleeks 
Thank you for the information, I was not aware with the vue file.
Correction is done.

Regards

2017-07-20 15:52 UTC, aleeks submitted a review, later dismissed

2017-07-21 10:01 UTC, aleeks commented
Thank you @Azouz-Jribi 
Maybe, you will have to rebase when yours others PR will be merged :smile:

2017-07-27 08:54 UTC, eternoendless approved these changes

2017-07-27 12:56 UTC, aleeks commented
Thank you @Azouz-Jribi

2017-07-27 12:56 UTC, merged