Secure the contact_form from spammers
PrestaShop/PrestaShop pull request #8168
Opened 2017-07-20 16:46 UTC by hibatallahAouadni

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | I adopt the solution in this [link](http://www.nfriedly.com/techblog/2009/11/how-to-build-a-spam-free-contact-forms-without-captchas/) to solve the problem of spamming the contact form
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-9132
| How to test?  |

2017-07-20 17:10 UTC, xBorderie commented on controllers/front/ContactController.php
> +            $saveContactKey = $this->context->cookie->formCleContact;
Could you remove the French? `formCleContact` is not really international ;)

2017-07-21 08:06 UTC, hibatallahAouadni commented on controllers/front/ContactController.php
> +            $saveContactKey = $this->context->cookie->formCleContact;
thanks @xBorderie ;)

2017-07-24 14:07 UTC, LittleBigDev requested changes

2017-07-24 14:07 UTC, LittleBigDev commented on controllers/front/ContactController.php
> +            'contactKey' => $contactKey
Please add a comma even after the last array item

2017-07-26 08:17 UTC, hibatallahAouadni commented on controllers/front/ContactController.php
> +            'contactKey' => $contactKey
@LittleBigDev done ;)

2017-07-26 09:06 UTC, LittleBigDev approved these changes

2017-08-28 13:39 UTC, marionf commented
Hello @hibatallahAouadni 

I can't send message anymore

![capture du 2017-08-28 15-38-34](https://user-images.githubusercontent.com/13449658/29775854-0429dfb2-8c07-11e7-887e-3f2044017c9d.png)

2017-08-28 14:11 UTC, hibatallahAouadni commented
Hello @marionf 
I'm really sorry but I didn't manage to reproduce your issue, I send 3 mails just right now and all have been successfully sent (see screenshots) and I tried it with customers and visitors.
- success message:
![contactanos buen gusto](https://user-images.githubusercontent.com/23308427/29777163-e8252a82-8c02-11e7-9b81-a8bc59853dab.png)
- received mails (BO):
![sav buen gusto](https://user-images.githubusercontent.com/23308427/29777193-08847cf6-8c03-11e7-8fb3-30960aadab07.png)

2017-08-29 12:06 UTC, marionf commented
Hello @hibatallahAouadni 
It's ok, it's working.
Thanks!

2017-08-29 15:26 UTC, merged

2017-08-29 15:26 UTC, maximebiloe commented
Thanks @hibatallahAouadni

2017-10-08 02:13 UTC, yaya85 commented
Verry good solotion, but in the  1.6.1.17 version it seems to give an error on the contact page when you try to send >http://prntscr.com/gumu69

I added the 2 rows to the contact page form, but still having an error.
When i add the ContactController.php from 1.6.1.16 it seems to work.

Do i need to change or add something to make it work in 1.6.1.17 ?

2017-10-08 07:54 UTC, bumarius commented
Hello,

please DO NOT forget also to modify contact.tpl

best regards

2017-10-08 18:18 UTC, yaya85 commented
Hi Bumarius,

You mean contact-form.tpl right? I already added this 2 lines of code. 

Is there anything else what we have to change?

Thanks!

2018-02-17 17:40 UTC, gregzawadzki commented
I developed module for this today using reCaptcha "I'm not a robot" : https://github.com/seigieu/seigisecurecontact
You can get it from git or there is link where you can download redy-to-install zip.

2018-02-21 10:12 UTC, PrestaShark commented
Same thing as @marionf mentioned. 
An error occurred while sending the message in FO, but message is available in BO.
Presta 1.6.1.10

@seigieu thanks for module but reCaptcha will not work in this case. Spammers will pass through reCaptcha validation...

2018-02-21 12:55 UTC, seigieu commented
@PrestaShark Which "case" you mean? What does not work?

2018-02-25 16:31 UTC, crsisti1 reviewed
what changes do i have to make?i don't understand

2018-03-12 18:07 UTC, DaoPuig commented
I used another solution and works for me.
 
ContactController.php inside the PostProcess function after the first if (Tools::isSubmit('sumbitMessage'))

// Get contact email 
$em = trim(Tools::getValue('from'));
// We will use it to check russian mails
$length = strlen('.ru');
$message = Tools::getValue('message');

// Check if the mail contact is a russian email
if (substr($em, -$length) === '.ru') {
   $this->errors[] = Tools::displayError('Invalid email address.');
// Check if content is written in russian
} elseif ($this->isRussian($message)) {
     $this->errors[] = Tools::displayError('Invalid content.');
} .....
// Function to check if the message is written in russian
private function isRussian($text) {
                return preg_match('/[А-Яа-яЁё]/u', $text);
        }

2018-03-12 23:44 UTC, seigieu commented
@DaoPuig That's putting all russians in one bag. And I had problems with Chinese spam, so if you want to generalize protection, add chinese letters also. And would also add checking for links and domains in message :)

2018-03-13 06:07 UTC, DaoPuig commented
@seigieu You are right, my bad. I came from that thread [link](http://forge.prestashop.com/browse/PSCSX-9781?focusedCommentId=163967&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-163967) about **Russian messages spamming.**
Actually, I had only spam from Russians and I tried to help with a fast hack :D

2018-03-13 17:10 UTC, seigieu commented
@DaoPuig think fastest and best solution is one I posted above. No generalization and no spam. Almost cannot be bypassed, since google updates it on regular basis.

2018-03-14 11:27 UTC, PrestaShark commented
Guys. Just for mention. Solution posted in this pull request failed to block russian spammers. Upgraded ContactController and tpl file and mail.ru spam pass through contact form easily even paired with ReCaptcha. WTF

2018-03-14 13:39 UTC, alegout commented
Hi @PrestaShark, i'm currently working on a PR to limit these spams issues on the contactform. 
For a robust solution, consider using a captcha solution like ReCaptcha (We can not add one because we can not require users to install FreeType). 
If you are on 1.6, please disable sendtofriends module. 
If the problem's not solved, are on 1.7 and have Recaptcha running, please create an issue and give us more details please, we'll check ASAP. 

Best regards

2018-03-14 14:37 UTC, PrestaShark commented
Hi. Details are clear. Changes in this pull request not work anymore. Spamers rebuild their scripts.
1.6.1.14 with pull fixes = failed to stop mail.ru spam

2018-03-14 14:52 UTC, alegout commented
You said that you have a ReCaptcha module, can you please test with javascript disabled if your module is working?

Thank you

2018-03-14 14:57 UTC, DaoPuig commented
@PrestaShark My solution is still working at least in my shop, as a fast hack you can try it.

2018-03-14 15:14 UTC, PrestaShark commented
@DaoPuig yes i trying it too but with Your hack no email are send anymore and notifications in BO are not work. Messages are saved in DB. Any ideas?

`if (Tools::isSubmit('submitMessage')) {
            $saveContactKey = $this->context->cookie->contactFormKey;
            $extension = array('.txt', '.rtf', '.doc', '.docx', '.pdf', '.zip', '.png', '.jpeg', '.gif', '.jpg');
            $file_attachment = Tools::fileAttachment('fileUpload');
			$em = trim(Tools::getValue('from'));
			$length = strlen('.ru');
            $message = Tools::getValue('message'); // Html entities is not usefull, iscleanHtml check there is no bad html tags.
            $url = Tools::getValue('url');
            if (!($from = trim(Tools::getValue('from'))) || !Validate::isEmail($from)) {
                $this->errors[] = Tools::displayError('Invalid email address.');
			} elseif (substr($em, -$length) === '.ru') {
				$this->errors[] = Tools::displayError('Invalid email address.');
			} elseif ($this->isRussian($message)) {
				$this->errors[] = Tools::displayError('Invalid content.');
			} elseif (!$message) {
                $this->errors[] = Tools::displayError('The message cannot be blank.');
            } elseif (!Validate::isCleanHtml($message)) {
                $this->errors[] = Tools::displayError('Invalid message');
            } elseif (!($id_contact = (int)Tools::getValue('id_contact')) || !(Validate::isLoadedObject($contact = new Contact($id_contact, $this->context->language->id)))) {
                $this->errors[] = Tools::displayError('Please select a subject from the list provided. ');
            } elseif (!empty($file_attachment['name']) && $file_attachment['error'] != 0) {
                $this->errors[] = Tools::displayError('An error occurred during the file-upload process.');
            } elseif (!empty($file_attachment['name']) && !in_array(Tools::strtolower(substr($file_attachment['name'], -4)), $extension) && !in_array(Tools::strtolower(substr($file_attachment['name'], -5)), $extension)) {
                $this->errors[] = Tools::displayError('Bad file extension');
            } elseif ($url === false || !empty($url) || $saveContactKey != (Tools::getValue('contactKey'))) {
                $this->errors[] = Tools::displayError('An error occurred while sending the message.');
            } else {`

2018-03-14 15:26 UTC, seigieu commented
@alegout If you mean my module... then no. Can see no point in no-javascript support. It's like 0.001% of users. Javascript is everywhere (fix me, if I'm wrong).

2018-03-14 16:27 UTC, jchelink commented
@DaoPuig Hi, your solution works for me for now :) Thanks
v1.6.1.1

2018-03-14 16:46 UTC, alegout commented
yes you are right, but a bot just call the url, do not even see your recaptcha :)

2018-03-14 17:31 UTC, alegout commented
ok @seigieu my bad, i saw that you valid the captcha in back-end, so 👍 i tought that is was only a javascript validation like another module i saw. sorry :)

2018-03-15 17:23 UTC, CrimsonLockhart commented
For those who have no idea what they are doing like me, there were a few syntax errors that kept the form from opening on 1.6.1.7.  Here is the copy of DaoPuigs deal that I fixed.  It got the form to open again and I am waiting to see if it gets these mfers to stop for now.  I have tried captcha, and pretty much every other solution on here but this one.  Looking promising.  :)

//Start russian bs
			// Get contact email
$em = trim(Tools::getValue('from'));
// We will use it to check russian mails
$length = strlen('.ru');
$message = Tools::getValue('message');

// Check if the mail contact is a russian email
if (substr($em, -$length) === '.ru') {
$this->errors[] = Tools::displayError('Invalid email address.');
// Check if content is written in russian
} elseif ($this->isRussian($message)) {
$this->errors[] = Tools::displayError('Invalid content.');
}
// Function to check if the message is written in russian
function isRussian($text) {
return preg_match('/[А-Яа-яЁё]/u', $text);
}
			//End russian bs

2018-03-15 18:07 UTC, jocel1 commented
FYI https://github.com/nenes25/eicaptcha seems to work quite well to prevent spam by using recaptcha (0.4.x branch for prestashop 1.6.x, 2.x for prestashop 1.7.x)

2018-03-19 13:24 UTC, mittermichal commented
FYI this commit breaks all older 1.6 custom templates since they miss 
`+				<input type="text" name="url" value="" class="hidden" />
+				<input type="hidden" name="contactKey" value="{$contactKey}" />`

2018-04-17 23:42 UTC, fire2 commented
I updated PS to 1.6.1.18 (from 1.6.1.16) and this change was included. So I updated my theme and added those 2 hidden inputs to the contact form. However I still get an error when trying to send the form because the submitted contactkey and the key in the form do not match. I added a die() with both values in that validation check and it fails, I really don't understand why. 

You can check there: tienda(dot)deflamenco(dot)com/en/contact-us 

What could be happening?

2018-06-13 23:58 UTC, tzak902 commented
Hi guys, what about 1.7.2.5 branch

2019-04-24 14:19 UTC, mhd6 commented
Hello my friend, I did not understand or put the secret key ? Thanks you

https://github.com/PrestaShop/PrestaShop/pull/8168/files/1482acec6e91a6e694b9638d42ac69be391dd7fc

2020-06-26 09:43 UTC, mkinternet reviewed
This fix is not good enough. Cookie has to be erased every time form submit is confirmed. Spam bot can use created cookie many times.

Add to the 211 line
$this->context->cookie->__unset('contactFormKey');

before:
$this->context->smarty->assign('confirmation', 1);