CO: Fixed a trouble in SpecificPrice when the shop has more than 1000…
PrestaShop/PrestaShop pull request #8174
Opened 2017-07-22 17:34 UTC by prestaquality

… different entries

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | Use the "develop" branch if you target PrestaShop 1.7; use the "1.6.1.x" branch if you target PrestaShop 1.6 (bugfixes only).
| Description?  | Please be specific when describing the PR. <br/> Every detail helps: versions, browser/server configuration, specific module/theme, etc.
| Type?         | bug fix / improvement / new feature
| Category?     | See [the Category list](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message#Howtowriteacommitmessage-Category), i.e.: BO
| BC breaks?    | Does it break backward compatibility? yes/no
| Deprecations? | Does it deprecate an existing feature? yes/no
| Fixed ticket? | (optional) If this PR fixes a [Forge](http://forge.prestashop.com/) ticket, please add its complete Forge URL.
| How to test?  | Please indicate how to best verify that this PR is correct.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

2017-08-01 11:16 UTC, LittleBigDev requested changes
Hello @prestaquality , thank you for this PR.
Some changes are needed (about Codacy review, you can ignore NPath and cyclomatic complexity warnings as this is legacy code).

2017-08-01 11:16 UTC, LittleBigDev commented on classes/SpecificPrice.php
> +            if($check_dates) {
please add a space after `if`

2017-08-01 11:16 UTC, LittleBigDev commented on classes/SpecificPrice.php
> +            if($threshold <= 0) //If it is inccorrect, set the default value
please add a space after `if`

2017-08-01 11:16 UTC, LittleBigDev commented on classes/SpecificPrice.php
> +    protected static function filterOutField($field_name, $field_value, $threshold = 1000, $check_dates = true)
For new variables and method parameters, please use the camelCase notation.

2017-08-01 11:16 UTC, LittleBigDev commented on classes/SpecificPrice.php
> +            $base_sql = ' FROM `'._DB_PREFIX_.'specific_price` WHERE `'.$name.'` != 0';
For new variables and method parameters, please use the camelCase notation.

2017-08-01 11:16 UTC, LittleBigDev commented on classes/SpecificPrice.php
> +            $query_count    = 'SELECT COUNT(DISTINCT `'.$name.'`)'.$base_sql;
For new variables and method parameters, please use the camelCase notation.

2017-08-01 11:16 UTC, LittleBigDev commented on classes/SpecificPrice.php
> +            if($threshold <= 0) //If it is inccorrect, set the default value
Typo in your comment ;)

2017-08-01 11:16 UTC, LittleBigDev commented on classes/SpecificPrice.php
> +
Please configure your IDE to trim leading white spaces at saving.

2017-08-01 11:16 UTC, LittleBigDev commented on classes/SpecificPrice.php
> +            $threshold = (int)$threshold;
I suggest you sanitize `$threshold` at the very top of the method instead of here (like `$name` is escaped at the very top)

2017-08-01 11:16 UTC, LittleBigDev commented on classes/SpecificPrice.php
> +            if($threshold <= 0) //If it is inccorrect, set the default value
Please use `if` statements with curly brackets. Always.

2017-08-01 11:16 UTC, LittleBigDev commented on classes/SpecificPrice.php
> +            if($threshold <= 0) //If it is inccorrect, set the default value
This could stick with `(int)` casting at the very top of the method.

2017-08-01 11:16 UTC, LittleBigDev commented on classes/SpecificPrice.php
> +            } while(!empty($tmp_specific_list));
Please add a space after `while` statement.

2017-08-01 13:11 UTC, prestaquality commented on classes/SpecificPrice.php
> +    protected static function filterOutField($field_name, $field_value, $threshold = 1000, $check_dates = true)
Sorry, and thanks for your test, we are fixing it now

2017-08-08 16:41 UTC, bertoferrero reviewed
Please, recheck the code mistakes ;)

2017-08-09 07:01 UTC, LittleBigDev requested changes
Hello @prestaquality, we're almost there !
Still few changes requested though.

2017-08-09 07:01 UTC, LittleBigDev commented on classes/SpecificPrice.php
> +        if ($threshold <= 0) //If it is incorrect, set the default value
Please add curly brackets to your `if` statements. Always.

2017-08-09 07:01 UTC, LittleBigDev commented on classes/SpecificPrice.php
> +     *
Please configure your IDE to remove all trailing white spaces.

2017-08-23 17:50 UTC, prestaquality commented
Please, check if it is right now :)

2017-08-25 07:30 UTC, LittleBigDev requested changes
Last microscopic typo to fix and we are done.

Then please squash all these commits into a single unique commit (for history sake).

2017-08-25 07:30 UTC, LittleBigDev commented on classes/SpecificPrice.php
> +		}
Indentation problem

2017-08-25 07:38 UTC, jocel1 commented
@prestaquality 
Hi!
What's the exact purpose of the fix? I mean the $threshold is here to avoid creating a big $specific_list array which would lower the performance (the whole purpose of filterOutField is to try to speed up the performances!). With the do { } while(), you're filling the specific_list array with all the entries from the DB.

2017-08-25 08:20 UTC, prestaquality commented
@jocel1 
I found that problem on a real client website. He has more than 1000 products and one specific price per product, with the original code each specificprice higher than the threshold value will not be in the $specific_list array and will not take effect

2017-08-25 08:25 UTC, jocel1 commented
@prestaquality: yes but there were a bug in 1.7.1.x:
at the end of filterOutField(), the test was
```if (in_array($field_value, $specific_list)) {```
instead of
```if (empty($specific_list) || in_array($field_value, $specific_list)) {```
This is fixed in the dev branch and the current 1.7.2.x branches

2017-08-25 08:39 UTC, prestaquality commented
@joce1 I aplogize I understand threshold as a tool to avoid not overload mysql with a huge query. To avoid this problems in the future and avoid to make new job and throw it to the bin, how can I solve my doubts about any code porpouse? In order to understand first the propouse the code and then think for a solution.

2017-08-25 08:45 UTC, jocel1 commented
@prestaquality: I think most of the work needs to be done on our side by improve the function comments / code quality (I've already tried to improve a bit the comment of SpecificPrice, but this function filterOutField definitely needs more comments). More generally for questions on specificPrices, you can ping me directly :)

2017-08-30 14:43 UTC, jocel1 commented
I'm closing this PR since the fix is already present in the 1.7.2.x branch

2017-08-30 14:43 UTC, closed without merging