BO: Categories breadcrumbs optimization for Large Category Tree
PrestaShop/PrestaShop pull request #8179
Opened 2017-07-25 16:55 UTC by AntoInta

We tested the original solution in a tree with more than 350 categories and result is an Out Of Memory (PHP 7.1, memory_limit = 2G).

The proposed solution redefine the getCategoriesWithBreadCrumb() method in order to retrieve all the breadcrumbs for every category directly from a query, thanks to the binary search attributes.

Every suggestion is really appreciated ;)

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | "develop"
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Is it possible to compare the current  and the proposed solution with a large Category Tree, accessing in the BackOffice in Product Info page.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

2017-07-26 07:39 UTC, christianverardi approved these changes

2017-10-09 14:15 UTC, LittleBigDev requested changes
Hello,
Thanks for this improvement !
Though, some changes need to be done :

2017-10-09 14:15 UTC, LittleBigDev commented on src/Adapter/Category/CategoryDataProvider.php
> +        return \DbCore::getInstance()->executeS('SELECT cl.`id_category` as "id", cl.`name`, (SELECT GROUP_CONCAT(cl.name ORDER BY c.`nleft` SEPARATOR "'.$delimiter.'")
Adapters are not model objects. They cannot build nor execute SQL queries. Please move this code in a model class.
For instance, previous version of this code was calling `Category::getAllCategoriesName()`. You need to provide a similar implementation.

2017-10-09 14:15 UTC, LittleBigDev commented on src/Adapter/Category/CategoryDataProvider.php
> +                                WHERE 1 AND c.id_category IS NOT NULL AND c.`level_depth` > 0 AND c2.`id_category` = X.`id_category`) AS "breadcrumb"
Is there a specific reason for using `WHERE 1 AND` ?

2017-10-10 01:55 UTC, AntoInta commented on src/Adapter/Category/CategoryDataProvider.php
> +        return \DbCore::getInstance()->executeS('SELECT cl.`id_category` as "id", cl.`name`, (SELECT GROUP_CONCAT(cl.name ORDER BY c.`nleft` SEPARATOR "'.$delimiter.'")
Hi, may thank for your reply. 
I'll try to analyze and propose an extension of Category::getAllCategoriesName() if we want to retrieve the path of the category, in order to clean the Adapter.

2017-10-10 07:21 UTC, LittleBigDev commented on src/Adapter/Category/CategoryDataProvider.php
> +        return \DbCore::getInstance()->executeS('SELECT cl.`id_category` as "id", cl.`name`, (SELECT GROUP_CONCAT(cl.name ORDER BY c.`nleft` SEPARATOR "'.$delimiter.'")
Yeah, sorry about the delay. I know this makes it harder to fix when it's cold and old in your memories...

2017-11-23 09:19 UTC, marionf commented
Changes are requested, so I remove the Waiting for QA label for now.
Please add it when the code review will be ok

2020-05-06 09:39 UTC, PierreRambaud commented
Hi @AntoInta ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2020-05-06 09:39 UTC, closed without merging