BO: add active filter in stock management
PrestaShop/PrestaShop pull request #8208
Opened 2017-08-01 10:01 UTC by aleeks

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | BO: add active filter in stock management
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/FF-17
| How to test?  | play with filters in stock management

2017-08-01 16:03 UTC, AlexEven commented
Wording:
I'm not comfortable with "Filter by enable status".

We should have something like

Filter by enable status => Filter by status
Disable => Disabled
Enable => Enabled
Enable Status => Status (like on Product page) or Enabled (like on 1.6 page)

Ping @xBorderie for a second opinion?

Thanks!

2017-08-01 16:20 UTC, xBorderie commented
100% agreed with @AlexEven 's comment.

2017-08-03 08:22 UTC, nihco2 commented
@AlexEven @xBorderie Thanks, we change that

2017-08-03 09:08 UTC, aleeks commented on admin-dev/themes/new-theme/js/app/widgets/ps-radio.vue
> +    <div class="radio">
Maybe this file hasn't the good indentation!

2017-08-03 09:13 UTC, maximebiloe requested changes
For the indent, please make sure to have the editorconfig plugin enable and the ESLint

2017-08-03 09:13 UTC, maximebiloe commented on admin-dev/themes/new-theme/js/app/pages/stock/components/header/filters.vue
> +                :label="trans('filter_status_enable')"
Check the indent

2017-08-03 09:13 UTC, maximebiloe commented on admin-dev/themes/new-theme/js/app/pages/stock/components/overview/products-table.vue
> +           {{trans('title_status')}}
Check the indent

2017-08-03 09:13 UTC, maximebiloe commented on admin-dev/themes/new-theme/js/app/widgets/ps-radio.vue
> +    <div class="radio">
Yes, all the file is missindented

2017-08-03 09:13 UTC, maximebiloe commented on src/PrestaShopBundle/Api/QueryParamsCollection.php
> +        if ($column === 'active') {
Yoda condition 😉

2017-08-03 09:13 UTC, maximebiloe commented on src/PrestaShopBundle/Translation/Api/StockApi.php
> +            'filter_status_disable' => $this->translator->trans('Disable', array(), 'Admin.Catalog.Feature'),
Admin.Actions

2017-08-03 09:13 UTC, maximebiloe commented on src/PrestaShopBundle/Translation/Api/StockApi.php
> +            'filter_status_all' => $this->translator->trans('All', array(), 'Admin.Catalog.Feature'),
Admin.Actions

2017-08-03 09:13 UTC, maximebiloe commented on src/PrestaShopBundle/Translation/Api/StockApi.php
> +            'filter_status_enable' => $this->translator->trans('Enable', array(), 'Admin.Catalog.Feature'),
Admin.Actions

2017-08-03 09:14 UTC, aleeks commented on admin-dev/themes/new-theme/js/app/pages/stock/components/header/filters.vue
> +    width: 150%;
sure about this ?

2017-08-03 09:19 UTC, aleeks commented
done @maximebiloe

2017-08-03 10:03 UTC, maximebiloe submitted a review, later dismissed

2017-08-03 14:26 UTC, manushhhh commented
Ok on my side

2017-08-09 13:15 UTC, eternoendless approved these changes

2017-08-09 13:16 UTC, eternoendless commented
Thank you @aleeks and @nihco2!

2017-08-09 13:16 UTC, merged