Change the price display method based on the feature Customer_Group
PrestaShop/PrestaShop pull request #8229
Opened 2017-08-07 16:15 UTC by hibatallahAouadni

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | I made a test in getPriceDisplayMethod function to take into consideration the value of the feature "Customer Groups".
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-9196
| How to test?  | Enable the feature "Customer Groups" (BO->Advanced Parameters−>Performance->Optional Features::Customer Groups) BO -> Customer -> Groups -> edit "Visitor" -> choose "Tax excluded" as value for "Price display method" then "save". Access to FO, while you're connected all prices are "tax included". Then, disconnect (access to the FO as visitor), you will see that all prices are displayed "tax excluded". If you disable the "Customer Groups" feature, whatever you're connected or no, all the price will be displayed "tax included".

2017-08-07 16:19 UTC, hibatallahAouadni commented on classes/Group.php
> +        }
@LittleBigDev the Problem is solved ;)

2017-08-08 10:00 UTC, LittleBigDev requested changes
Thanks for the PR Hiba.
Still some changes are requested though.

2017-08-08 10:00 UTC, LittleBigDev commented on classes/Group.php
> +            $id_group = (int)Configuration::get('PS_CUSTOMER_GROUP');
This method is meant  to return the display method for a given group. The code asking for it WANTS the display method for THIS given group. If the method internally changes `$id_group` and returns display method for this new group, then the code asking for if cannot trust the method anymore.
Determining the group id should be done before calling `getPriceDisplayMethod()`. First, you find the correct group id, and then you ask for its display method.

2017-08-08 12:05 UTC, hibatallahAouadni commented
Closing this one cause I open another PR [#8231](https://github.com/PrestaShop/PrestaShop/pull/8231)

2017-08-08 12:05 UTC, closed without merging