Display the price based on the feature Customer_Groups
PrestaShop/PrestaShop pull request #8231
Opened 2017-08-08 12:03 UTC by hibatallahAouadni

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | I made a test in getPriceDisplayMethod function to take into consideration the value of the feature "Customer Groups".
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-9196
| How to test?  | Enable the feature "Customer Groups" (BO->Advanced Parameters−>Performance->Optional Features::Customer Groups) BO -> Customer -> Groups -> edit "Visitor" -> choose "Tax excluded" as value for "Price display method" then "save". Access to FO, while you're connected all prices are "tax included". Then, disconnect (access to the FO as visitor), you will see that all prices are displayed "tax excluded". If you disable the "Customer Groups" feature, whatever you're connected or not, all the price will be displayed "tax included".

2017-08-08 12:06 UTC, LittleBigDev requested changes

2017-08-08 12:06 UTC, LittleBigDev commented on classes/Group.php
> +        } else {
You can just remove the `else`

2017-08-08 12:12 UTC, hibatallahAouadni commented on classes/Group.php
> +        } else {
done ;)

2017-08-08 12:15 UTC, LittleBigDev approved these changes
🎉

2017-08-10 10:18 UTC, hibatallahAouadni commented
@LittleBigDev could you please put the milestone 1.6.1.17, thnaks in advance :)

2017-08-10 15:55 UTC, marionf commented
Hello @hibatallahAouadni 
1) I enable the feature "Customer Groups" 
2) I edit the "Customer" group and define "Price display method" for "Tax excluded".
When I am logged, I see the prices tax excluded and when I am not logged, I see the prices tax included -> It's working.

3) I disable the feature "Customer Groups" 
When I am logged, I see the prices tax excluded and when I am not logged, I see the prices tax excluded -> It's not working, I think the prices should be tax included whatever you're logged or not.

2017-08-11 15:57 UTC, hibatallahAouadni commented on classes/Group.php
> +    }
Hello @marionf the default behavior is PS_CUSTOMER_GROUP, so if the customer group display the prices with tax excluded, then you will see all prices tax excluded whatever you're logged or not ;)

2017-08-17 08:12 UTC, hibatallahAouadni commented on classes/Group.php
> +    }
ping @marionf

2017-08-17 08:14 UTC, hibatallahAouadni commented
ping @marionf

2017-08-17 09:47 UTC, marionf commented
Hello @hibatallahAouadni 
The problem is when I disable the feature "Customer Groups" in the BO->Advanced Paramters->Performances.
Currently what is configured in the group is taken into account even when the feature is disabled. It will not.

2017-08-17 09:56 UTC, hibatallahAouadni commented
@marionf how is that? could you please provide some screenshots to better understand the problem.
Thanks in advance :)

2017-08-17 10:19 UTC, marionf commented
@hibatallahAouadni yes sure :)

1) I configure a discount and to display the prices tax excluded for the group "Customer"

![pr8231-2](https://user-images.githubusercontent.com/13449658/29407803-fd240284-8345-11e7-849f-3174e0ec80c2.png)

2) I disable the feature customer group

![pr8231-1](https://user-images.githubusercontent.com/13449658/29407816-0f1d4bc6-8346-11e7-9b20-c6d3515d8f39.png)

3) What is configured in the group is taken into account even when the feature is disabled

![pr8231-3](https://user-images.githubusercontent.com/13449658/29407835-296a9c04-8346-11e7-9d58-dca4fdba7c49.png)

2017-08-17 10:28 UTC, hibatallahAouadni commented
@marionf even you're not logged, you will see the same (25,50 HT). Cause the default behavior ,when the feature is disabled, is to apply the configuration made for the customer_group, and that's what I found in the code (see the screenshot below).
![customer_groups](https://user-images.githubusercontent.com/23308427/29408197-34a1f7f4-833f-11e7-9d64-30c79fc1ca94.png)

2017-08-17 12:11 UTC, marionf commented
Yes, I think there is a problem. I will see this with @vincentbz

2017-08-17 15:00 UTC, marionf commented
@hibatallahAouadni I have seen with @vincentbz and we will not change the behavior for 1.6 version.
I'm sorry there was a misunderstanding.
I have just discovered that making a change in a client group enables the feature in advanced parameters if it was disabled before.
Your PR is working well, thanks !

2017-08-28 09:49 UTC, merged

2017-08-28 09:49 UTC, maximebiloe commented
Thank you @hibatallahAouadni