CO: Fixed bug in AdminCartRulesController when limiting the validity …
PrestaShop/PrestaShop pull request #8232
Opened 2017-08-08 14:57 UTC by christianverardi

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fixed bug in AdminCartRulesController when limiting the validity of a CartRule for a specific Customer in Multishop context. If you have a PrestaShop installation configured with more than one shop that does not share customers and you try to create a new CartRule for a specific shop and you look for a specific customer by typing its name inside the input, you will see results coming from all the shops. This solution filters the results based on the SHARE CUSTOMERS option.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | 1. Log-in the Back-office and enable the Multishop feature
||2. create a new Shop in the same Shop Group
||3. disable the Share Customers option on the Shop Group
||4. create two customers with similar names or e-mails (one per shop)
||5. select a specific shop
||6. create a new CartRule and limit its validity on a specific customer by start typing the customer name. 
||7. You should see the results for the specific shop you are creating the cart rule for.

2017-08-08 15:40 UTC, vincentbz commented
Hi @christianverardi ,

Thanks for that PR. We need to review and test it but that's an important fix, right :)

2017-09-22 06:58 UTC, tomlev requested changes

2017-09-22 06:58 UTC, tomlev commented on controllers/admin/AdminCartRulesController.php
> +			'.Shop::addSqlRestriction(true).'
hi @christianverardi 
this should be Shop::addSqlRestriction(Shop::SHARE_CUSTOMER)
Could you please fix this argument ?

2017-09-22 07:23 UTC, tomlev approved these changes

2017-09-22 14:07 UTC, eternoendless commented
Thank you @christianverardi

2017-09-22 14:07 UTC, merged