BO: Fixed bug in AdminGroupsController when adding ModulesRestriction…
PrestaShop/PrestaShop pull request #8237
Opened 2017-08-10 13:15 UTC by christianverardi

…s to group in multishop configuration

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | The issue is that when you are in a multishop context and you try to revoke to a user's group the access to a module, Prestashop will save the information for both the shops (even if the ps_module_group is shop dependent).
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Set up a multishop installation, edit one Group for a single shop and disable some modules for that group. Then change shop and check that those modules are still enabled for the edited group.

2017-10-12 14:46 UTC, eternoendless requested changes
Looks good to me! Only one small change is needed

2017-10-12 14:46 UTC, eternoendless commented on controllers/admin/AdminOrdersController.php
> +        $modules = Module::getAuthorizedModules($customer->id_default_group, [$customer->id_shop]);
Could you please change `[$customer->id_shop]` to `array($customer->id_shop)`?

2018-04-13 12:42 UTC, eternoendless commented
I'd like to push some changes to your PR in order to be able to approve it.

Could you please activate the option "Allow edits from maintainers" on your PR?

You can find it at the bottom of the right column:

![image](https://user-images.githubusercontent.com/1009343/31622102-c2fb4330-b29b-11e7-93e7-9e77a65fb081.png)

Thanks!

2018-04-13 12:46 UTC, christianverardi commented
@eternoendless Done! ;)

2018-04-13 16:24 UTC, eternoendless submitted a review, later dismissed

2018-05-07 09:40 UTC, marionf commented
Hello @christianverardi 

You are talking of modules in customers" group ?

![capture du 2018-05-07 11-39-41](https://user-images.githubusercontent.com/13449658/39695588-7355f0ec-51eb-11e8-98bf-6d7332e0a704.png)

2018-05-07 09:56 UTC, christianverardi commented
@marionf yes I'm talking about enabled modules for a customer group and a specific shop.
Sorry, I updated the PR's description to be more clear ;)

2018-05-09 09:28 UTC, marionf commented
Thank you @christianverardi

2018-06-05 01:38 UTC, mickaelandrieu commented
Tests are failing; the best you can do here is try to rebase develop branch and hope for the best :)

2018-07-05 14:51 UTC, PierreRambaud submitted a review, later dismissed
Need rebase for travis

2018-08-17 09:26 UTC, eternoendless commented
Rebased... let's cross fingers now :)

2018-09-18 15:55 UTC, eternoendless commented
Rebased again

2018-09-20 13:20 UTC, Quetzacoalt91 commented
Just applied CS fixer to make the tests pass.

2018-09-20 13:34 UTC, eternoendless approved these changes

2018-09-20 15:55 UTC, merged

2018-09-20 15:55 UTC, Quetzacoalt91 commented
Thank you @christianverardi