Update the encrypt and decrypt functions to support all PHP versions
PrestaShop/PrestaShop pull request #8256
Opened 2017-08-17 17:01 UTC by hibatallahAouadni

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | Please be specific when describing the PR. <br/> Every detail helps: versions, browser/server configuration, specific module/theme, etc.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-9164
| How to test?  | Please indicate how to best verify that this PR is correct.

2017-08-17 17:06 UTC, jocel1 requested changes

2017-08-17 17:06 UTC, jocel1 commented on classes/Rijndael.php
> +        } elseif (function_exists('openssl_encrypt') && version_compare(phpversion(), '7.1', '>=')) {
why not testing first openssl_encrypt? you'd not need the version_compare part anymore
e.g:
if (function_exists('openssl_encrypt')) {

} elseif (function_exists('mcrypt_encrypt')) {

} else {
  throw new runtimeException(...);
}

2017-08-17 17:06 UTC, jocel1 commented on classes/Rijndael.php
> +            } elseif (function_exists('openssl_decrypt') && version_compare(phpversion(), '7.1', '>=')) {
same here

2017-08-17 17:06 UTC, jocel1 commented on classes/Rijndael.php
> +            } elseif (function_exists('openssl_decrypt') && version_compare(phpversion(), '7.1', '>=')) {
same here

2017-08-17 17:10 UTC, hibatallahAouadni commented on classes/Rijndael.php
> +        } elseif (function_exists('openssl_encrypt') && version_compare(phpversion(), '7.1', '>=')) {
you got a point :+1:
I'll do it, thanks :)

2017-08-18 08:01 UTC, eternoendless requested changes

2017-08-18 08:01 UTC, eternoendless commented on classes/Rijndael.php
> +        } elseif (function_exists('openssl_encrypt') && version_compare(phpversion(), '7.1', '>=')) {
Why test for PHP 7.1 ? From the looks of it you should only check for PHP 5.3.3 in order to make sure that openssl_encrypt has the $iv parameter

> 5.3.3 | The iv parameter was added.

2017-08-18 08:30 UTC, hibatallahAouadni commented
@jocel1 @eternoendless done :+1:

2017-08-18 08:34 UTC, jocel1 commented on classes/Rijndael.php
> +        } elseif (function_exists('mcrypt_encrypt') && version_compare(phpversion(), '5.3.3', '<')) {
version_compare is not needed here

2017-08-18 14:55 UTC, hibatallahAouadni commented on classes/Rijndael.php
> +        } elseif (function_exists('mcrypt_encrypt') && version_compare(phpversion(), '5.3.3', '<')) {
@jocel1 you're right I'll change it :+1: 
sorry for the late response :/ I didn't get the notification.

2017-08-18 15:24 UTC, hibatallahAouadni commented
@jocel1 @eternoendless thanks guys :)

2017-08-21 08:06 UTC, eternoendless approved these changes

2017-08-24 09:13 UTC, jocel1 approved these changes

2017-08-28 12:02 UTC, merged

2017-08-28 12:02 UTC, maximebiloe commented
Thank you @hibatallahAouadni

2018-10-10 08:34 UTC, hakeryk2 commented
@eternoendless or @jocel1  Is this will be implemented in 1.6.1.23? It was merged for 1.6.1.17 but it didn't made up to the final  version and it's realy important for 7.2 and security.

2018-10-18 15:54 UTC, eternoendless commented
@hakeryk2 This has changed since 1.6.1.20, see: https://github.com/PrestaShop/PrestaShop/pull/9218

2019-04-08 09:35 UTC, NoZTurn commented
when using php7.3 with prestashop 1623,we can install normally,but cann't visit index.php and admin index, the error message is: Fatal error: Uncaught RuntimeException: Either Mcrypt or OpenSSL extension is required to run Prestashop in D:\wamp\www\prestashop1623\classes\Rijndael.php:68