IN: add a new quick access
PrestaShop/PrestaShop pull request #8306
Opened 2017-09-05 09:27 UTC by vincentbz

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | As the catalog evaluation has been hugely improved, it adds a new quick link to easier push this feature
| Type?         | improvement
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-3783
| How to test?  | Install and see if the Catalog Evaluation is in the new quick access

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

2017-09-05 10:09 UTC, eternoendless requested changes

2017-09-05 10:09 UTC, eternoendless commented on install-dev/data/xml/quick_access.xml
> +      <link>index.php?controller=AdminStats&amp;&amp;module=statscheckup</link>
There's an extra `&amp;` in your URL

2017-09-05 14:12 UTC, aleeks submitted a review, later dismissed

2017-09-05 14:15 UTC, eternoendless submitted a review, later dismissed

2017-09-06 13:55 UTC, maximebiloe approved these changes

2017-09-06 13:56 UTC, merged

2017-09-06 13:56 UTC, maximebiloe commented
Thank you @vincentbz