CO: Added redirect type in AdminImportController
PrestaShop/PrestaShop pull request #8345
Opened 2017-09-18 10:28 UTC by luigimassa

Added new fileds in AdminImportController to import redirect

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | added fileds redirect_type and id_type_redirected in AdminImportController
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? |  no
| How to test?  | import csv

2017-09-25 08:33 UTC, mickaelandrieu commented
Hello @luigimassa,

it should work... but I'm wondering why do you need it?

Mickaël

2017-09-28 13:10 UTC, luigimassa commented
Hi Mickaël
this is the use case 
I created a new products version
I have to deactivate products of previous version, but I don't want lost my seo
So I want to redirect deactivated products to the new products.
With this change I can do a massive update

2017-11-22 16:33 UTC, Quetzacoalt91 requested changes

2017-11-22 16:33 UTC, Quetzacoalt91 commented on controllers/admin/AdminImportController.php
> +                    'id_type_redirected' =>   array('label' => $this->trans('Product ID', array(), 'Admin.Advparameters.Feature')),
Be careful, this label is confusing with the ID column and should be something like "Target product / category ID".

2017-11-22 16:33 UTC, Quetzacoalt91 commented
It seems you added by mistake an additional commit to the PR, making the review difficult. Would you mind removing it?

2018-11-29 15:41 UTC, Quetzacoalt91 commented
Because the Import controller being currently migrated on Symfony (see #11561), the improvement should be brought on the new version when done.

The changes won't be applied to the legacy content, I have no other choice than closing it.

Regards

2018-11-29 15:41 UTC, closed without merging