TE: test cart
PrestaShop/PrestaShop pull request #8364
Opened 2017-09-25 09:16 UTC by tomlev

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.2.x
| Description?  | this PR adds some tests on cart add and calculation
| Type?         | tests
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | run unit tests

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

2017-10-13 14:58 UTC, LittleBigDev commented
Review status: 0 of 5 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[tests/Unit/Core/Cart/AbstractCartTest.php, line 93 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwL9GDFvdxzs8tUdRWF:-KwL9GDFvdxzs8tUdRWG:b-3jwas5) ([raw file](https://github.com/prestashop/prestashop/blob/6aa7c10606ea23e860d955cd28e442471d0f17f1/tests/Unit/Core/Cart/AbstractCartTest.php#L93)):*
> ```PHP
>         $this->contextMocker = new ContextMocker();
>         $this->contextMocker->mockContext();
>         $this->cart              = new \Cart();
> ```

Please Import all the classes you use (I won't spam the whole review with this request)

---

*[tests/Unit/Core/Cart/AbstractCartTest.php, line 107 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwL2K3GwhFNqAkayqVV:-KwL2K3HPQRysQQYGizw:b1lu6pv) ([raw file](https://github.com/prestashop/prestashop/blob/6aa7c10606ea23e860d955cd28e442471d0f17f1/tests/Unit/Core/Cart/AbstractCartTest.php#L107)):*
> ```PHP
>         parent::tearDown();
> 
>         $this->resetCart();
> ```

Why reset cart in `tearDown()` if you do it  in `setUp()` anyway ?

---

*[tests/Unit/Core/Cart/AbstractCartTest.php, line 120 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwL4SiViaUXvPrdOYhl:-KwL4SiWyVl8iKFOOlxJ:b4wlxfp) ([raw file](https://github.com/prestashop/prestashop/blob/6aa7c10606ea23e860d955cd28e442471d0f17f1/tests/Unit/Core/Cart/AbstractCartTest.php#L120)):*
> ```PHP
> 
>         // delete cart
>         $this->cart->delete();
> ```

If cart is deleted here, why reset it just before ?

---

*[tests/Unit/Core/Cart/AbstractCartTest.php, line 139 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwL50qQnfZtbMeDcpUr:-KwL50qR0CWpZdOrCHTn:b346e0u) ([raw file](https://github.com/prestashop/prestashop/blob/6aa7c10606ea23e860d955cd28e442471d0f17f1/tests/Unit/Core/Cart/AbstractCartTest.php#L139)):*
> ```PHP
>         $productDatas = $this->cart->getProducts(true);
>         foreach ($productDatas as $productData) {
>             $this->cart->updateQty(0, $productData['id_product']);
> ```

`Cart::updateQty()` instantiates a bunch of objects and triggers a hook (but maybe this is intended ?).
`Cart::deleteProduct()` though, only removes product from cart.

---

*[tests/Unit/Core/Cart/AbstractCartTest.php, line 165 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwL7M4ZcDVXdwVathhm:-KwL7M4ZcDVXdwVathhn:bn3v67f) ([raw file](https://github.com/prestashop/prestashop/blob/6aa7c10606ea23e860d955cd28e442471d0f17f1/tests/Unit/Core/Cart/AbstractCartTest.php#L165)):*
> ```PHP
>     }
> 
>     protected function addProductsToCart($productDatas)
> ```

"data" is already a plural world. No "s" needed.

---

*[tests/Unit/Core/Cart/Adding/CartRule/AddRuleTest.php, line 42 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwLDbe9z-RZ70KCOHRr:-KwLDbe9z-RZ70KCOHRs:b-ngkbmt) ([raw file](https://github.com/prestashop/prestashop/blob/6aa7c10606ea23e860d955cd28e442471d0f17f1/tests/Unit/Core/Cart/Adding/CartRule/AddRuleTest.php#L42)):*
> ```PHP
>      * @param $expectedProductCountAfterRules
>      */
>     public function testCartRuleValidity(
> ```

Please add a description here (Given - When - Then). I had a very hard time understanding what this test does (and I'm still unsure).

---

*[tests/Unit/Core/Cart/Adding/CartRule/AddRuleTest.php, line 43 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwLAHUuwwYj2MZMKq4c:-KwLAHUvReTgEvP8KRL8:bfyuukw) ([raw file](https://github.com/prestashop/prestashop/blob/6aa7c10606ea23e860d955cd28e442471d0f17f1/tests/Unit/Core/Cart/Adding/CartRule/AddRuleTest.php#L43)):*
> ```PHP
>      */
>     public function testCartRuleValidity(
>         $productDatas,
> ```

`$productData`

---

*[tests/Unit/Core/Cart/Adding/CartRule/AddRuleTest.php, line 44 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwLAKZUEZ3PTpwuoCEf:-KwLAKZUEZ3PTpwuoCEg:b-3dbufj) ([raw file](https://github.com/prestashop/prestashop/blob/6aa7c10606ea23e860d955cd28e442471d0f17f1/tests/Unit/Core/Cart/Adding/CartRule/AddRuleTest.php#L44)):*
> ```PHP
>     public function testCartRuleValidity(
>         $productDatas,
>         $cartRuleDatas,
> ```

`$cartRuleData`

---

*[tests/Unit/Core/Cart/Calculation/Products/CartProductTest.php, line 37 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwLEHVIGzCdCIE7nBI0:-KwLEHVIGzCdCIE7nBI1:bby407v) ([raw file](https://github.com/prestashop/prestashop/blob/6aa7c10606ea23e860d955cd28e442471d0f17f1/tests/Unit/Core/Cart/Calculation/Products/CartProductTest.php#L37)):*
> ```PHP
>      * @dataProvider cartWithoutCartRulesProvider
>      */
>     public function testCartWithoutCartRules($productDatas, $expectedTotal, $cartRuleDatas)
> ```

"data"

---

*[tests/Unit/Core/Cart/Calculation/Products/CartProductTest.php, line 42 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwLETBHV2sO6jGU1c3h:-KwLETBI6rBlCxyBWeKz:b-1wac5o) ([raw file](https://github.com/prestashop/prestashop/blob/6aa7c10606ea23e860d955cd28e442471d0f17f1/tests/Unit/Core/Cart/Calculation/Products/CartProductTest.php#L42)):*
> ```PHP
>         $this->addCartRulesToCart($cartRuleDatas);
>         $this->compareCartTotal($expectedTotal);
>     }
> ```

No assertions ? The test will be flagged as risky.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8364)*
<!-- Sent from Reviewable.io -->

2017-10-13 15:04 UTC, LittleBigDev commented
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8364)*
<!-- Sent from Reviewable.io -->

2017-10-13 15:05 UTC, LittleBigDev requested changes
See Reviewable comments

2017-10-19 15:27 UTC, tomlev commented
Review status: 0 of 24 files reviewed at latest revision, 10 unresolved discussions.

---

*[tests/Unit/Core/Cart/AbstractCartTest.php, line 93 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwL9GDFvdxzs8tUdRWF:-KwpEfcwtBPwOssasXxc:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/6aa7c10606ea23e860d955cd28e442471d0f17f1/tests/Unit/Core/Cart/AbstractCartTest.php#L93)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Please Import all the classes you use (I won't spam the whole review with this request)
</blockquote></details>

Done.

---

*[tests/Unit/Core/Cart/AbstractCartTest.php, line 107 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwL2K3GwhFNqAkayqVV:-KwpAyunUslF9zjomgk3:bpa43g2) ([raw file](https://github.com/prestashop/prestashop/blob/6aa7c10606ea23e860d955cd28e442471d0f17f1/tests/Unit/Core/Cart/AbstractCartTest.php#L107)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Why reset cart in `tearDown()` if you do it  in `setUp()` anyway ?
</blockquote></details>

because some other tests dont sanitize the data they use

---

*[tests/Unit/Core/Cart/AbstractCartTest.php, line 120 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwL4SiViaUXvPrdOYhl:-KwpBCuRhT_ZKoxcxxAw:bpinx46) ([raw file](https://github.com/prestashop/prestashop/blob/6aa7c10606ea23e860d955cd28e442471d0f17f1/tests/Unit/Core/Cart/AbstractCartTest.php#L120)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

If cart is deleted here, why reset it just before ?
</blockquote></details>

reset is emptying cart, delete drop it

---

*[tests/Unit/Core/Cart/AbstractCartTest.php, line 139 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwL50qQnfZtbMeDcpUr:-KwpBiGE9whaY8KJP384:b-d89hil) ([raw file](https://github.com/prestashop/prestashop/blob/6aa7c10606ea23e860d955cd28e442471d0f17f1/tests/Unit/Core/Cart/AbstractCartTest.php#L139)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

`Cart::updateQty()` instantiates a bunch of objects and triggers a hook (but maybe this is intended ?).
`Cart::deleteProduct()` though, only removes product from cart.
</blockquote></details>

it  is intended as it is the method used by cart update

---

*[tests/Unit/Core/Cart/AbstractCartTest.php, line 165 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwL7M4ZcDVXdwVathhm:-KwpEeiSyu2JE1jSSNbI:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/6aa7c10606ea23e860d955cd28e442471d0f17f1/tests/Unit/Core/Cart/AbstractCartTest.php#L165)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

"data" is already a plural world. No "s" needed.
</blockquote></details>

Done.

---

*[tests/Unit/Core/Cart/Adding/CartRule/AddRuleTest.php, line 42 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwLDbe9z-RZ70KCOHRr:-KwpEh08C1km9lO34Qxo:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/6aa7c10606ea23e860d955cd28e442471d0f17f1/tests/Unit/Core/Cart/Adding/CartRule/AddRuleTest.php#L42)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Please add a description here (Given - When - Then). I had a very hard time understanding what this test does (and I'm still unsure).
</blockquote></details>

Done.

---

*[tests/Unit/Core/Cart/Adding/CartRule/AddRuleTest.php, line 43 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwLAHUuwwYj2MZMKq4c:-KwpEhJoPYOde7O2qGXH:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/6aa7c10606ea23e860d955cd28e442471d0f17f1/tests/Unit/Core/Cart/Adding/CartRule/AddRuleTest.php#L43)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

`$productData`
</blockquote></details>

Done.

---

*[tests/Unit/Core/Cart/Adding/CartRule/AddRuleTest.php, line 44 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwLAKZUEZ3PTpwuoCEf:-KwpEhmqNq2oEAtMmPJ_:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/6aa7c10606ea23e860d955cd28e442471d0f17f1/tests/Unit/Core/Cart/Adding/CartRule/AddRuleTest.php#L44)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

`$cartRuleData`
</blockquote></details>

Done.

---

*[tests/Unit/Core/Cart/Calculation/Products/CartProductTest.php, line 37 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwLEHVIGzCdCIE7nBI0:-KwpEdZvlvx-jrXojcQ9:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/6aa7c10606ea23e860d955cd28e442471d0f17f1/tests/Unit/Core/Cart/Calculation/Products/CartProductTest.php#L37)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

"data"
</blockquote></details>

Done.

---

*[tests/Unit/Core/Cart/Calculation/Products/CartProductTest.php, line 42 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwLETBHV2sO6jGU1c3h:-KwpCPTkDzXyaA95mc3p:b98v09t) ([raw file](https://github.com/prestashop/prestashop/blob/6aa7c10606ea23e860d955cd28e442471d0f17f1/tests/Unit/Core/Cart/Calculation/Products/CartProductTest.php#L42)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

No assertions ? The test will be flagged as risky.
</blockquote></details>

assertions are in the methods (code factorization)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8364)*
<!-- Sent from Reviewable.io -->

2017-10-20 09:02 UTC, LittleBigDev commented
Reviewed 24 of 24 files at r2.
Review status: all files reviewed at latest revision, 27 unresolved discussions.

---

*[classes/Product.php, line 3638 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsvRnI9uxVPcoPNioG:-KwsvRnJw9kC_Vmvg_qz:b-ambwr6) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/classes/Product.php#L3638)):*
> ```PHP
>         if (!$ps_stock_management) {
>             return true;
>         } else {
> ```

the `else` statement can be removed because of the `return true` just above

---

*[tests/Integration/ProductURLsTest.php, line 40 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsxqzRFWGyh9f4qMH7:-KwsxqzRFWGyh9f4qMH8:b74mjm5) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/ProductURLsTest.php#L40)):*
> ```PHP
>     private $language;
> 
>     protected function setup()
> ```

did you mean `setUp()` ?

---

*[tests/Integration/ProductURLsTest.php, line 42 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsxrOk0olG4gBOjoy6:-KwsxrOk0olG4gBOjoy7:b74mjm5) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/ProductURLsTest.php#L42)):*
> ```PHP
>     protected function setup()
>     {
>         parent::setup();
> ```

did you mean `setUp()` ?

---

*[tests/Integration/SmartySettingsTest.php, line 36 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-Kwsxq4DWJW9MpjIY5DP:-Kwsxq4DWJW9MpjIY5DQ:b74mjm5) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/SmartySettingsTest.php#L36)):*
> ```PHP
>     private $smarty;
> 
>     public function setup()
> ```

did you mean `setUp()` ?

---

*[tests/Integration/SmartySettingsTest.php, line 38 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsxqTWNHYLPwjDxRlt:-KwsxqTWNHYLPwjDxRlu:b74mjm5) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/SmartySettingsTest.php#L38)):*
> ```PHP
>     public function setup()
>     {
>         parent::setup();
> ```

did you mean `setUp()` ?

---

*[tests/Integration/Adapter/AdapterDatabaseTest.php, line 34 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-Kwsxoq464RbNVpSQ8eC:-Kwsxoq464RbNVpSQ8eD:b74mjm5) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/Adapter/AdapterDatabaseTest.php#L34)):*
> ```PHP
> class AdapterDatabaseTest extends IntegrationTestCase
> {
>     public function setup()
> ```

did you mean `setUp()` ?

---

*[tests/Integration/Adapter/AdapterDatabaseTest.php, line 36 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsxpGzHFA76ZpNT_NO:-KwsxpGzHFA76ZpNT_NP:b74mjm5) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/Adapter/AdapterDatabaseTest.php#L36)):*
> ```PHP
>     public function setup()
>     {
>         parent::setup();
> ```

did you mean `setUp()` ?

---

*[tests/Integration/classes/CartGetOrderTotalTest.php, line 371 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsxKwnSpuhOcoYqvGP:-KwsxKwnSpuhOcoYqvGQ:b74mjm5) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/classes/CartGetOrderTotalTest.php#L371)):*
> ```PHP
>     public function setUp()
>     {
>         parent::setup();
> ```

did you mean `setUp()` ?

---

*[tests/Integration/classes/ConfigurationCoreTest.php, line 39 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsxQpc34EGZ5cfl5xM:-KwsxQpc34EGZ5cfl5xN:b74mjm5) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/classes/ConfigurationCoreTest.php#L39)):*
> ```PHP
>     protected function setUp()
>     {
>         parent::setup();
> ```

did you mean `setUp()` ?

---

*[tests/Integration/classes/ShopCoreTest.php, line 37 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsxTgtOCTfzOLv6NW4:-KwsxTgtOCTfzOLv6NW5:b74mjm5) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/classes/ShopCoreTest.php#L37)):*
> ```PHP
>     protected $context;
> 
>     protected function setup()
> ```

did you mean `setUp()` ?

---

*[tests/Integration/classes/ShopCoreTest.php, line 39 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsxUagVqxL1HiTcCGg:-KwsxUagVqxL1HiTcCGh:b74mjm5) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/classes/ShopCoreTest.php#L39)):*
> ```PHP
>     protected function setup()
>     {
>         parent::setup();
> ```

did you mean `setUp()` ?

---

*[tests/Integration/Core/Foundation/Entity/EntityManagerTest.php, line 47 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsxXJdwWLwkg20eWym:-KwsxXJeSmOa3EOV5dKs:b74mjm5) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/Core/Foundation/Entity/EntityManagerTest.php#L47)):*
> ```PHP
>     protected $contextMocker;
> 
>     protected function setup()
> ```

did you mean `setUp()` ?

---

*[tests/Integration/Core/Foundation/Entity/EntityManagerTest.php, line 49 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsxY0gSe2jbqzWNRtb:-KwsxY0gSe2jbqzWNRtc:b74mjm5) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/Core/Foundation/Entity/EntityManagerTest.php#L49)):*
> ```PHP
>     protected function setup()
>     {
>         parent::setup();
> ```

did you mean `setUp()` ?

---

*[tests/Integration/Core/Foundation/Entity/EntityTest.php, line 41 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsxZ9tlBUk7BVeA_Ir:-KwsxZ9tlBUk7BVeA_Is:b74mjm5) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/Core/Foundation/Entity/EntityTest.php#L41)):*
> ```PHP
>     protected $contextMocker;
> 
>     protected function setup()
> ```

did you mean `setUp()` ?

---

*[tests/Integration/Core/Foundation/Entity/EntityTest.php, line 43 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsxZk35xXpa8uadHdk:-KwsxZk35xXpa8uadHdl:b74mjm5) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/Core/Foundation/Entity/EntityTest.php#L43)):*
> ```PHP
>     protected function setup()
>     {
>         parent::setup();
> ```

did you mean `setUp()` ?

---

*[tests/Integration/Core/Module/HookRepositoryTest.php, line 46 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsxaEWHWeM91sVyxEs:-KwsxaEWHWeM91sVyxEt:b74mjm5) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/Core/Module/HookRepositoryTest.php#L46)):*
> ```PHP
>     protected $contextMocker;
> 
>     protected function setup()
> ```

did you mean `setUp()` ?

---

*[tests/Integration/Core/Module/HookRepositoryTest.php, line 48 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-Kwsxb_cIG7D7SSRCTGS:-Kwsxb_cIG7D7SSRCTGT:b74mjm5) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/Core/Module/HookRepositoryTest.php#L48)):*
> ```PHP
>     protected function setup()
>     {
>         parent::setup();
> ```

did you mean `setUp()` ?

---

*[tests/TestCase/IntegrationTestCase.php, line 40 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsxcqoUHDoMK6CWtH4:-KwsxcqoUHDoMK6CWtH5:b74mjm5) ([raw file](https://github.com/prestashop/ [...]

2017-10-20 09:03 UTC, LittleBigDev requested changes
Thanks for the hard work.
Still some changes are missing tho. (see reviewable comments)

2017-10-20 09:13 UTC, tomlev commented
Review status: 11 of 41 files reviewed at latest revision, 27 unresolved discussions.

---

*[classes/Product.php, line 3638 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsvRnI9uxVPcoPNioG:-Kwt1poV11mSw0jB0Hs4:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/classes/Product.php#L3638)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

the `else` statement can be removed because of the `return true` just above
</blockquote></details>

Done.

---

*[tests/Integration/ProductURLsTest.php, line 40 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsxqzRFWGyh9f4qMH7:-Kwt1qrUuBkv3mNinfNH:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/ProductURLsTest.php#L40)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

did you mean `setUp()` ?
</blockquote></details>

Done.

---

*[tests/Integration/ProductURLsTest.php, line 42 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsxrOk0olG4gBOjoy6:-Kwt1rExlUoxnF6GxoR_:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/ProductURLsTest.php#L42)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

did you mean `setUp()` ?
</blockquote></details>

Done.

---

*[tests/Integration/SmartySettingsTest.php, line 36 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-Kwsxq4DWJW9MpjIY5DP:-Kwt1s5mxPQF7fGq-4CA:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/SmartySettingsTest.php#L36)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

did you mean `setUp()` ?
</blockquote></details>

Done.

---

*[tests/Integration/SmartySettingsTest.php, line 38 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsxqTWNHYLPwjDxRlt:-Kwt1sRHEuuIPsFDvaCa:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/SmartySettingsTest.php#L38)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

did you mean `setUp()` ?
</blockquote></details>

Done.

---

*[tests/Integration/Adapter/AdapterDatabaseTest.php, line 34 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-Kwsxoq464RbNVpSQ8eC:-Kwt1u3bcnzBgxRXU4sN:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/Adapter/AdapterDatabaseTest.php#L34)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

did you mean `setUp()` ?
</blockquote></details>

Done.

---

*[tests/Integration/Adapter/AdapterDatabaseTest.php, line 36 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsxpGzHFA76ZpNT_NO:-Kwt1uQhKaPwNHJI--Oj:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/Adapter/AdapterDatabaseTest.php#L36)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

did you mean `setUp()` ?
</blockquote></details>

Done.

---

*[tests/Integration/classes/CartGetOrderTotalTest.php, line 371 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsxKwnSpuhOcoYqvGP:-Kwt1vL1AaPT-TKPW519:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/classes/CartGetOrderTotalTest.php#L371)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

did you mean `setUp()` ?
</blockquote></details>

Done.

---

*[tests/Integration/classes/ConfigurationCoreTest.php, line 39 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsxQpc34EGZ5cfl5xM:-Kwt1wJYzSXzvCfsluJF:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/classes/ConfigurationCoreTest.php#L39)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

did you mean `setUp()` ?
</blockquote></details>

Done.

---

*[tests/Integration/classes/ShopCoreTest.php, line 37 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsxTgtOCTfzOLv6NW4:-Kwt1wvLAkrFFT_DdoCb:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/classes/ShopCoreTest.php#L37)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

did you mean `setUp()` ?
</blockquote></details>

Done.

---

*[tests/Integration/classes/ShopCoreTest.php, line 39 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsxUagVqxL1HiTcCGg:-Kwt1xDcc64h1zHRhn08:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/classes/ShopCoreTest.php#L39)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

did you mean `setUp()` ?
</blockquote></details>

Done.

---

*[tests/Integration/Core/Foundation/Entity/EntityManagerTest.php, line 47 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsxXJdwWLwkg20eWym:-Kwt1y02jxIj0dPgrZSl:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/Core/Foundation/Entity/EntityManagerTest.php#L47)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

did you mean `setUp()` ?
</blockquote></details>

Done.

---

*[tests/Integration/Core/Foundation/Entity/EntityManagerTest.php, line 49 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsxY0gSe2jbqzWNRtb:-Kwt1ybPpjGLSKIevYkJ:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/Core/Foundation/Entity/EntityManagerTest.php#L49)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

did you mean `setUp()` ?
</blockquote></details>

Done.

---

*[tests/Integration/Core/Foundation/Entity/EntityTest.php, line 41 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsxZ9tlBUk7BVeA_Ir:-Kwt2ETQz0sNtVKt1ks5:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/Core/Foundation/Entity/EntityTest.php#L41)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

did you mean `setUp()` ?
</blockquote></details>

Done.

---

*[tests/Integration/Core/Foundation/Entity/EntityTest.php, line 43 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsxZk35xXpa8uadHdk:-Kwt2En4APk-AUbGMVkV:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/Core/Foundation/Entity/EntityTest.php#L43)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

did you mean `setUp()` ?
</blockquote></details>

Done.

---

*[tests/Integration/Core/Module/HookRepositoryTest.php, line 46 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-KwsxaEWHWeM91sVyxEs:-Kwt2FRvxy5u03XCp2yD:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/9a55ec51d93bb3445fd4ce63dfd203b3ff185823/tests/Integration/Core/Module/HookRepositoryTest.php#L46)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

did you mean `setUp()` ?
</blockquote></details>

Done.

-- [...]

2017-10-20 09:31 UTC, LittleBigDev commented
Reviewed 30 of 30 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/Unit/classes/module/ModuleCoreTest.php, line 51 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-Kwt5O8cH6Rux0jXLyBh:-Kwt5O8cH6Rux0jXLyBi:b-hgarxv) ([raw file](https://github.com/prestashop/prestashop/blob/1bcba9e3e17fe01485883233002b932ebd03e83f/tests/Unit/classes/module/ModuleCoreTest.php#L51)):*
> ```PHP
> 										<ul><li>Error 1</li><li>Error 2</li><li>Error 3</li></ul>
> 									</div>
> 								</div>';
> ```

Care about tabulations

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8364)*
<!-- Sent from Reviewable.io -->

2017-10-20 09:32 UTC, LittleBigDev requested changes
Almost there !

2017-10-20 15:36 UTC, tomlev commented
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/Unit/classes/module/ModuleCoreTest.php, line 51 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-Kwt5O8cH6Rux0jXLyBh:-KwuQEpRpQIaCDgmXiNS:b-k6ewjt) ([raw file](https://github.com/prestashop/prestashop/blob/1bcba9e3e17fe01485883233002b932ebd03e83f/tests/Unit/classes/module/ModuleCoreTest.php#L51)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Care about tabulations
</blockquote></details>

these lines were not modified in this PR ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8364)*
<!-- Sent from Reviewable.io -->

2017-10-24 07:17 UTC, LittleBigDev commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8364#-:-KxCEZCmmlFW6lvf1-Mh:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2017-10-24 07:18 UTC, LittleBigDev approved these changes

2017-10-30 16:02 UTC, eternoendless commented
Thank you @tomlev ! 🍰

2017-10-30 16:02 UTC, merged