Cart getOrderTotal refact
PrestaShop/PrestaShop pull request #8411
Opened 2017-10-11 14:01 UTC by tomlev

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | totaly refact cart getOrderTotal algotythm
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Some tests were added, need to test all cart impacts

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

2017-12-13 17:46 UTC, Quetzacoalt91 commented on src/Core/Cart/Amount.php
> +    public function __construct($taxIncluded = 0, $taxExcluded = 0)
Do you want the same value & type on the default values?

I don't know how deep you go in your tests, but your float values will be overridden by the integer ones if nothing is sent to the constructor. :)

2017-12-14 09:34 UTC, tomlev commented on src/Core/Cart/Amount.php
> +    public function __construct($taxIncluded = 0, $taxExcluded = 0)
bull eyes !

2017-12-14 15:42 UTC, LittleBigDev commented
Reviewed 5 of 12 files at r1, 4 of 16 files at r2, 20 of 21 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 27 unresolved discussions, some commit checks failed.

---

*[classes/Cart.php, line 2038 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L0FRsalScVjw8EJfakS:-L0FRsalScVjw8EJfakT:b-o4x3lf) ([raw file](https://github.com/prestashop/prestashop/blob/0573f4fb60b2370b8088f8ef3ddb34453b24f4cb/classes/Cart.php#L2038)):*
> ```PHP
>         if ($type == Cart::ONLY_PRODUCTS_WITHOUT_SHIPPING) {
>             $type = Cart::ONLY_PRODUCTS;
>         }
> ```

Maintainability suggestion (if more deprecated types might appear later) :
```php
$type = $this->mapDeprecatedCartType($type)

/* ... */

protected function mapDeprecatedCartType($type)
{
    $map = [
        Cart::ONLY_PRODUCTS_WITHOUT_SHIPPING => Cart::ONLY_PRODUCTS,
    ];

    if (!empty($map[$type])) {
        return $map[$type];
    }

    return $type;
}
```

---

*[classes/Cart.php, line 2052 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L0FV075Ib75JbcbnblE:-L0FV076O8eI8BfqrWzY:b-s4xxex) ([raw file](https://github.com/prestashop/prestashop/blob/0573f4fb60b2370b8088f8ef3ddb34453b24f4cb/classes/Cart.php#L2052)):*
> ```PHP
>         );
>         if (!in_array($type, $allowedTypes)) {
>             die(\Tools::displayError());
> ```

Fore single responsibility principle, it's better to throw an exception here and handle it outside the method.
Also, `die`'ing an error message is kinda savage !

---

*[classes/Cart.php, line 2108 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L0FUMjuU-SnTok_Y3dp:-L0FUMjuU-SnTok_Y3dq:b25b9xh) ([raw file](https://github.com/prestashop/prestashop/blob/0573f4fb60b2370b8088f8ef3ddb34453b24f4cb/classes/Cart.php#L2108)):*
> ```PHP
>                 throw new \Exception('unknown cart calculation type : ' . $type);
>         }
> ```

The whole `$type` manipulation (if statements, switch statement, value changes, class behavior depending on this value...) is smelly.
Based on [this article](https://sourcemaking.com/refactoring/smells/switch-statements) , maybe the Cart class is a good candidate for refactoring : [Replace Type Code with Subclasses](https://sourcemaking.com/refactoring/replace-type-code-with-subclasses) or [Replace Type Code with State/Strategy](https://sourcemaking.com/refactoring/replace-type-code-with-state-strategy)
What do you think ?

---

*[classes/Cart.php, line 2116 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L0FYQ_pkNQdzEsSYjo6:-L0FYQ_pkNQdzEsSYjo7:b-1v8top) ([raw file](https://github.com/prestashop/prestashop/blob/0573f4fb60b2370b8088f8ef3ddb34453b24f4cb/classes/Cart.php#L2116)):*
> ```PHP
> 
>         $compute_precision = $this->configuration->get('_PS_PRICE_COMPUTE_PRECISION_');
>         return Tools::ps_round($value, $compute_precision);
> ```

I think we should start using PrestaShop/Decimal for rounding

---

*[src/Core/Cart/Amount.php, line 29 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L0F_aOkf0s8dMRIVLmr:-L0F_aOlhKZ7zzOW0NnM:bf401wv) ([raw file](https://github.com/prestashop/prestashop/blob/0573f4fb60b2370b8088f8ef3ddb34453b24f4cb/src/Core/Cart/Amount.php#L29)):*
> ```PHP
> namespace PrestaShop\PrestaShop\Core\Cart;
> 
> class Amount
> ```

Can you please add a doc block to explain the role and/or behavior of this class ?

---

*[src/Core/Cart/Amount.php, line 62 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L0F_tfD5VEvICq2XdK1:-L0F_tfD5VEvICq2XdK2:b-x08lun) ([raw file](https://github.com/prestashop/prestashop/blob/0573f4fb60b2370b8088f8ef3ddb34453b24f4cb/src/Core/Cart/Amount.php#L62)):*
> ```PHP
>     public function setTaxIncluded($taxIncluded)
>     {
>         $this->taxIncluded = $taxIncluded;
> ```

I suggest casting it as a float here

---

*[src/Core/Cart/Amount.php, line 82 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L0FanAKDXPswaYb3zQZ:-L0FanAKDXPswaYb3zQ_:b-w7f4s2) ([raw file](https://github.com/prestashop/prestashop/blob/0573f4fb60b2370b8088f8ef3ddb34453b24f4cb/src/Core/Cart/Amount.php#L82)):*
> ```PHP
>     public function setTaxExcluded($taxExcluded)
>     {
>         $this->taxExcluded = $taxExcluded;
> ```

I suggest casting it as float

---

*[src/Core/Cart/Amount.php, line 87 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L0FbJMqhqaPMYrw6tlP:-L0FbJMqhqaPMYrw6tlQ:b-ybvgwg) ([raw file](https://github.com/prestashop/prestashop/blob/0573f4fb60b2370b8088f8ef3ddb34453b24f4cb/src/Core/Cart/Amount.php#L87)):*
> ```PHP
>     }
> 
>     public function add(Amount $amount)
> ```

Needs doc

---

*[src/Core/Cart/Amount.php, line 93 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L0FbKYCVQqKTLFBx5j_:-L0FbKYCVQqKTLFBx5ja:b-ybvgwg) ([raw file](https://github.com/prestashop/prestashop/blob/0573f4fb60b2370b8088f8ef3ddb34453b24f4cb/src/Core/Cart/Amount.php#L93)):*
> ```PHP
>     }
> 
>     public function sub(Amount $amount)
> ```

Needs doc

---

*[src/Core/Cart/Calculator.php, line 29 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L0FbdEshBt-n6lpNYoa:-L0FbdEtreLpILW8rWNi:b-ybvgwg) ([raw file](https://github.com/prestashop/prestashop/blob/0573f4fb60b2370b8088f8ef3ddb34453b24f4cb/src/Core/Cart/Calculator.php#L29)):*
> ```PHP
> namespace PrestaShop\PrestaShop\Core\Cart;
> 
> class Calculator
> ```

Needs doc

---

*[src/Core/Cart/Calculator.php, line 42 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L0Fh5Nn3k8Vthr7w3TW:-L0Fh5Nn3k8Vthr7w3TX:b4x711z) ([raw file](https://github.com/prestashop/prestashop/blob/0573f4fb60b2370b8088f8ef3ddb34453b24f4cb/src/Core/Cart/Calculator.php#L42)):*
> ```PHP
>      * @var CartRowCollection
>      */
>     protected $cartRows;
> ```

What is a cart row ?

---

*[src/Core/Cart/Calculator.php, line 68 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L0FhDXCh9U9yz8hs7f0:-L0FhDXCh9U9yz8hs7f1:bps2ve0) ([raw file](https://github.com/prestashop/prestashop/blob/0573f4fb60b2370b8088f8ef3ddb34453b24f4cb/src/Core/Cart/Calculator.php#L68)):*
> ```PHP
>     }
> 
>     public function addCartRow(CartRow $cartRow)
> ```

Please add doc

---

*[src/Core/Cart/Calculator.php, line 75 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L0FhEw2eH1ICARXGTx_:-L0FhEw2eH1ICARXGTxa:bps2ve0) ([raw file](https://github.com/prestashop/prestashop/blob/0573f4fb60b2370b8088f8ef3ddb34453b24f4cb/src/Core/Cart/Calculator.php#L75)):*
> ```PHP
>     }
> 
>     public function addCartRule(CartRuleData $cartRule)
> ```

Please add doc

---

*[src/Core/Cart/Calculator.php, line 82 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L0FhFeslC3FoKrB1L6L:-L0FhFeslC3FoKrB1L6M:bps2ve0) ([raw file](https://github.com/prestashop/prestashop/blob/0573f4fb60b2370b8088f8ef3ddb34453b24f4cb/src/Core/Cart/Calculator.php#L82)):*
> ```PHP
>     }
> 
>     public function processCalculation()
> ```

Please add doc

---

*[src/Core/Cart/CartRow.php, line 31 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L0Fjx2R8n8znm6BfVQa:-L0Fjx2SDxXzKkBeNDxX:b-gtjuqd) ([raw file](https://github.com/prestashop/prestashop/blob/0573f4fb60b2370b8088f8ef3ddb34453b24f4cb/src/Core/Cart/CartRow.php#L31)):*
> ```PHP
> use PrestaShop\PrestaShop\Adapter\ServiceLocator;
> 
> class CartRow
> ```

Incomplete doc (class, attributes, methods)

---

*[src/Core/Cart/CartRow.php, line 187 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L0JJICJwcjjRX9GlE1U:-L0JJICJwcjjRX9GlE1V:b-k104nt) ([raw file](https://github.com/prestashop/prestashop/blob/0573f4fb60b2370b8088f8ef3ddb34453b24f4cb/src/Core/Cart/CartRow.php#L187)):*
> ```PHP
>         if ($taxExcluded < 0) {
>             $taxExcluded = 0;
>         }
> ```

don't forget to explain this behavior in doc block (if result is negative t [...]

2017-12-29 11:35 UTC, eternoendless commented
Reviewed 1 of 6 files at r7, 6 of 12 files at r8.
Review status: 28 of 35 files reviewed at latest revision, 70 unresolved discussions, some commit checks failed.

---

*[classes/Cart.php, line 2052 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L0FV075Ib75JbcbnblE:-L1X-q_p0Yko7eltNpHF:bgja2jk) ([raw file](https://github.com/prestashop/prestashop/blob/0573f4fb60b2370b8088f8ef3ddb34453b24f4cb/classes/Cart.php#L2052)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Fore single responsibility principle, it's better to throw an exception here and handle it outside the method.
Also, `die`'ing an error message is kinda savage !
</blockquote></details>

This should throw an Exception... code should never EVER `die` unless it's a CLI script!

---

*[classes/Cart.php, line 2116 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L0FYQ_pkNQdzEsSYjo6:-L1X0FODzGQXqm5facFY:bv3zxqf) ([raw file](https://github.com/prestashop/prestashop/blob/0573f4fb60b2370b8088f8ef3ddb34453b24f4cb/classes/Cart.php#L2116)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

I think we should start using PrestaShop/Decimal for rounding
</blockquote></details>

As we discussed, we will, but on a second pass.
First we need to make sure this refactoring doesn't create regressions, and that includes keeping the current rounding errors.

---

*[classes/Cart.php, line 1762 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1WzsUaKKmfJix40j-2:-L1WzsUaKKmfJix40j-3:bxgsfw1) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/classes/Cart.php#L1762)):*
> ```PHP
>     ) {
>         $t=Configuration::get('_PS_PRICE_COMPUTE_PRECISION_');
>         $b=$t;
> ```

Looks like dead code

---

*[classes/Cart.php, line 1813 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1WzuiRmWDuzji0GTwK:-L1WzuiRmWDuzji0GTwL:b-ezkb6d) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/classes/Cart.php#L1813)):*
> ```PHP
>         }
> 
>         //$tutu = $this->getTotalShippingCost(null, (bool)$with_taxes);
> ```

To delete

---

*[classes/Cart.php, line 1956 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X-GKeXSCFBLpzNwo-:-L1X-GKeXSCFBLpzNwo0:b-wv6885) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/classes/Cart.php#L1956)):*
> ```PHP
>             $flag = false;
>             foreach ($cart_rules as $cart_rule) {
>                 /** @var \CartRule $cartRule */
> ```

Could you please rename `$cart_rule` to `$item` so that there's no confusion with `$cartRule`?

---

*[classes/Cart.php, line 2027 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X-W03tVPB1O1oZHxh:-L1X-W03tVPB1O1oZHxi:b-3fu64g) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/classes/Cart.php#L2027)):*
> ```PHP
>      *
>      */
>     public function getOrderTotalV2(
> ```

Please add a space before `(`

---

*[classes/Cart.php, line 2028 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X-ZH5lf75mi7-ITbC:-L1X-ZH5lf75mi7-ITbD:b-iotug4) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/classes/Cart.php#L2028)):*
> ```PHP
>      */
>     public function getOrderTotalV2(
>         $with_taxes = true,
> ```

Please use camelCase

---

*[classes/Cart.php, line 2121 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X0a05JCgWvpeTFMu-:-L1X0a05JCgWvpeTFMu0:bu5vygp) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/classes/Cart.php#L2121)):*
> ```PHP
>     }
> 
>     public function newCalculator($products, $cartRules, $id_carrier)
> ```

Missing doc

---

*[classes/Cart.php, line 2121 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X0oHOPYiDvgdy16Iv:-L1X0oHOPYiDvgdy16Iw:b-3fu64g) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/classes/Cart.php#L2121)):*
> ```PHP
>     }
> 
>     public function newCalculator($products, $cartRules, $id_carrier)
> ```

Please add a space before `(`

---

*[classes/Cart.php, line 2123 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X0bTnmQNTBRTNixPW:-L1X0bTnmQNTBRTNixPX:b4mb5g5) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/classes/Cart.php#L2123)):*
> ```PHP
>     public function newCalculator($products, $cartRules, $id_carrier)
>     {
>         $calculator         = new \PrestaShop\PrestaShop\Core\Cart\Calculator();
> ```

That `=` must feel lonely, being so far away from its variable

---

*[classes/Cart.php, line 2129 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X0q0Yj91BaCpU_XFJ:-L1X0q0Yj91BaCpU_XFK:bzbwo7m) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/classes/Cart.php#L2129)):*
> ```PHP
> 
>         // set cart rows (products)
>         foreach($products as $product){
> ```

Spaces

---

*[classes/Cart.php, line 2130 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X0ri7UGwfxm88Mtkq:-L1X0ri7UGwfxm88Mtkr:b84jx8x) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/classes/Cart.php#L2130)):*
> ```PHP
>         // set cart rows (products)
>         foreach($products as $product){
>             $calculator->addCartRow(new \PrestaShop\PrestaShop\Core\Cart\CartRow($product));
> ```

Please don't use FQCN, use imports

---

*[classes/Cart.php, line 2130 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X0ylj8NGj-CxR9HmG:-L1X0ylj8NGj-CxR9HmH:bmfaa75) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/classes/Cart.php#L2130)):*
> ```PHP
>         // set cart rows (products)
>         foreach($products as $product){
>             $calculator->addCartRow(new \PrestaShop\PrestaShop\Core\Cart\CartRow($product));
> ```

Maybe we should consider passing cartRows and cartRules to the `Calculator` constructor, so we can skip the foreach's and function calls.

---

*[classes/Cart.php, line 2210 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X2GuW3P3w3cbIKi7x:-L1X2GuW3P3w3cbIKi7y:b-gspmfu) ([raw file](https://github.com/prestashop/prestashop/blob/7a90eaee84326aa359c9aa02b11847191c38d1c3/classes/Cart.php#L2210)):*
> ```PHP
> 
>         if (!isset($nb_packages[$this->id])) {
>             $nb_packages[$this->id] = 0;
> ```

Did you take into account the performance impact of this removal?

---

*[classes/Cart.php, line 2239 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X29WPe8v0eOqG68AG:-L1X29WPe8v0eOqG68AH:b-gspmfu) ([raw file](https://github.com/prestashop/prestashop/blob/7a90eaee84326aa359c9aa02b11847191c38d1c3/classes/Cart.php#L2239)):*
> ```PHP
>         if (isset($cache[$cache_key]) && $cache[$cache_key] !== false && !$flush) {
>             return $cache[$cache_key];
>         }
> ```

Did you take into account the performance impact of this removal?

---

*[classes/Cart.php, line 2531 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X2Ncoj3bRkzwkOuCT:-L1X2Ncoj3bRkzwkOuCU:b-gspmfu) ([raw file](https://github.com/prestashop/prestashop/blob/7a90eaee84326aa359c9aa02b11847191c38d1c3/classes/Cart.php#L2531)):*
> ```PHP
>             return $cache[$this->id];
>         }
> ```

Did you take into account the performance impact of this removal?

---

*[classes/Cart.php, line 2970 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X2Psh-Se4in2ys5wb:-L1X2Psh-Se4in2ys5wc:b-gspmfu) ([raw file](https://github.com/prestashop/prestashop/blob/7a90eaee [...]

2018-01-02 09:57 UTC, LittleBigDev commented
Reviewed 2 of 12 files at r8.
Review status: 30 of 35 files reviewed at latest revision, 76 unresolved discussions, some commit checks failed.

---

*[tests/Unit/Core/Cart/Calculation/Modes/RoundingModeTest.php, line 50 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1qH5wYxL-rmdSRANel:-L1qH5wYxL-rmdSRANem:b3bi6v) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/tests/Unit/Core/Cart/Calculation/Modes/RoundingModeTest.php#L50)):*
> ```PHP
>     public function setUp()
>     {
>         $this->defaultRoundingMode = Configuration::get('PS_PRICE_ROUND_MODE');
> ```

You should use `PrestaShop\PrestaShop\Adapter\Configuration`

---

*[tests/Unit/Core/Cart/Calculation/Modes/RoundingModeTest.php, line 57 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1qHDL-PzSR3vcJdtSq:-L1qHDL-PzSR3vcJdtSr:b3bi6v) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/tests/Unit/Core/Cart/Calculation/Modes/RoundingModeTest.php#L57)):*
> ```PHP
>     public function tearDown()
>     {
>         Configuration::set('PS_PRICE_ROUND_MODE', $this->defaultRoundingMode);
> ```

You should use `PrestaShop\PrestaShop\Adapter\Configuration`

---

*[tests/Unit/Core/Cart/Calculation/Modes/RoundingModeTest.php, line 69 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1qHhHddQj4DwO-xsmF:-L1qHhHeQBJHUjYqcWBS:b3bi6v) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/tests/Unit/Core/Cart/Calculation/Modes/RoundingModeTest.php#L69)):*
> ```PHP
>     protected function setRoundingMode($roundingMode)
>     {
>         Configuration::set('PS_PRICE_ROUND_MODE', $roundingMode);
> ```

You should use `PrestaShop\PrestaShop\Adapter\Configuration`

---

*[tests/Unit/Core/Cart/Calculation/Modes/RoundingTypeTest.php, line 48 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1qIFEZDCgs117bbW38:-L1qIFEZDCgs117bbW39:b3bi6v) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/tests/Unit/Core/Cart/Calculation/Modes/RoundingTypeTest.php#L48)):*
> ```PHP
>     public function setUp()
>     {
>         $this->defaultRoundingType = Configuration::get('PS_ROUND_TYPE');
> ```

You should use `PrestaShop\PrestaShop\Adapter\Configuration`

---

*[tests/Unit/Core/Cart/Calculation/Modes/RoundingTypeTest.php, line 55 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1qIGiNIbXKYBWtcosX:-L1qIGiNIbXKYBWtcosY:b3bi6v) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/tests/Unit/Core/Cart/Calculation/Modes/RoundingTypeTest.php#L55)):*
> ```PHP
>     public function tearDown()
>     {
>         Configuration::set('PS_ROUND_TYPE', $this->defaultRoundingType);
> ```

You should use `PrestaShop\PrestaShop\Adapter\Configuration`

---

*[tests/Unit/Core/Cart/Calculation/Modes/RoundingTypeTest.php, line 67 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1qIHRAxtudIsrMS887:-L1qIHRAxtudIsrMS888:b3bi6v) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/tests/Unit/Core/Cart/Calculation/Modes/RoundingTypeTest.php#L67)):*
> ```PHP
>     protected function setRoundingType($roundingType)
>     {
>         Configuration::set('PS_ROUND_TYPE', $roundingType);
> ```

You should use `PrestaShop\PrestaShop\Adapter\Configuration`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8411)*
<!-- Sent from Reviewable.io -->

2018-01-02 09:58 UTC, LittleBigDev requested changes
cf. comments above (including @eternoendless' ones)

2018-01-02 14:01 UTC, eternoendless commented
Reviewed 1 of 21 files at r3, 1 of 6 files at r7, 6 of 12 files at r8.
Review status: all files reviewed at latest revision, 78 unresolved discussions, some commit checks failed.

---

*[classes/Cart.php, line 2108 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L0FUMjuU-SnTok_Y3dp:-L1r9m0EqHkqSYkhLH8G:bba3665) ([raw file](https://github.com/prestashop/prestashop/blob/0573f4fb60b2370b8088f8ef3ddb34453b24f4cb/classes/Cart.php#L2108)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

The whole `$type` manipulation (if statements, switch statement, value changes, class behavior depending on this value...) is smelly.
Based on [this article](https://sourcemaking.com/refactoring/smells/switch-statements) , maybe the Cart class is a good candidate for refactoring : [Replace Type Code with Subclasses](https://sourcemaking.com/refactoring/replace-type-code-with-subclasses) or [Replace Type Code with State/Strategy](https://sourcemaking.com/refactoring/replace-type-code-with-state-strategy)
What do you think ?
</blockquote></details>

I think it might be overkill, but your remark is pertinent because it points a finger to the fact that `$type` seems to be a code smell

---

*[classes/Cart.php, line 2030 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1r9-PhTAaXNyFu70zB:-L1r9-PhTAaXNyFu70zC:b-hbrs0) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/classes/Cart.php#L2030)):*
> ```PHP
>         $with_taxes = true,
>         $type = Cart::BOTH,
>         $products = null,
> ```

Why should a cart be able to calculate the total of a different set of products than the ones already in the cart?
It should either:
- Depend exclusively on its products
- Be extracted (and receive a Cart or a list of products, but not both)

---

*[tests/Unit/Core/Cart/Calculation/Currencies/CurrencyTest.php, line 220 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1r5Keut8E_dVmoSiGv:-L1r5Keut8E_dVmoSiGw:bps0qip) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/tests/Unit/Core/Cart/Calculation/Currencies/CurrencyTest.php#L220)):*
> ```PHP
>             $rate = 1;
>         } else {
>             $rate = 1 * static::CURRENCY_FIXTURES[$currencyId]['changeRate'];
> ```

The `1 *` isn't very useful, isn't it ?

```php
$rate = ($defaultCurrencyId != $currencyId) ? static::CURRENCY_FIXTURES[$currencyId]['changeRate'] : 1;
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8411)*
<!-- Sent from Reviewable.io -->

2018-01-09 15:11 UTC, tomlev commented
Review status: 22 of 36 files reviewed at latest revision, 78 unresolved discussions.

---

*[classes/Cart.php, line 2038 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L0FRsalScVjw8EJfakS:-L2KLydHNxHjR4IhWd1N:b8u4b5x) ([raw file](https://github.com/prestashop/prestashop/blob/0573f4fb60b2370b8088f8ef3ddb34453b24f4cb/classes/Cart.php#L2038)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Maintainability suggestion (if more deprecated types might appear later) :
```php
$type = $this->mapDeprecatedCartType($type)

/* ... */

protected function mapDeprecatedCartType($type)
{
    $map = [
        Cart::ONLY_PRODUCTS_WITHOUT_SHIPPING => Cart::ONLY_PRODUCTS,
    ];

    if (!empty($map[$type])) {
        return $map[$type];
    }

    return $type;
}
```
</blockquote></details>

as discussed, this is out of scope for this refact

---

*[classes/Cart.php, line 2052 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L0FV075Ib75JbcbnblE:-L2KM7NiFg_MhNrE_oHC:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/0573f4fb60b2370b8088f8ef3ddb34453b24f4cb/classes/Cart.php#L2052)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

This should throw an Exception... code should never EVER `die` unless it's a CLI script!
</blockquote></details>

Done.

---

*[classes/Cart.php, line 2108 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L0FUMjuU-SnTok_Y3dp:-L2KMVDLPK2zD2TQlNKf:b-lgafoh) ([raw file](https://github.com/prestashop/prestashop/blob/0573f4fb60b2370b8088f8ef3ddb34453b24f4cb/classes/Cart.php#L2108)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

I think it might be overkill, but your remark is pertinent because it points a finger to the fact that `$type` seems to be a code smell
</blockquote></details>

probably out of scope for this refact

---

*[classes/Cart.php, line 1762 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1WzsUaKKmfJix40j-2:-L2KKg_tXm24QrmHksm5:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/classes/Cart.php#L1762)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Looks like dead code
</blockquote></details>

Done.

---

*[classes/Cart.php, line 1813 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1WzuiRmWDuzji0GTwK:-L2KKy-ZTUAj6BmcHrei:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/classes/Cart.php#L1813)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

To delete
</blockquote></details>

Done.

---

*[classes/Cart.php, line 1956 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X-GKeXSCFBLpzNwo-:-L2KLFfPFI9op7a74JGM:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/classes/Cart.php#L1956)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Could you please rename `$cart_rule` to `$item` so that there's no confusion with `$cartRule`?
</blockquote></details>

Done.

---

*[classes/Cart.php, line 2027 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X-W03tVPB1O1oZHxh:-L2L7rePdqLQOb2BZOM0:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/classes/Cart.php#L2027)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Please add a space before `(`
</blockquote></details>

Done.

---

*[classes/Cart.php, line 2028 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X-ZH5lf75mi7-ITbC:-L2KLaabKe5gWkYJngWV:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/classes/Cart.php#L2028)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Please use camelCase
</blockquote></details>

Done.

---

*[classes/Cart.php, line 2030 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1r9-PhTAaXNyFu70zB:-L2KLnAlvCSInNVW-cct:bja1wwt) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/classes/Cart.php#L2030)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Why should a cart be able to calculate the total of a different set of products than the ones already in the cart?
It should either:
- Depend exclusively on its products
- Be extracted (and receive a Cart or a list of products, but not both)
</blockquote></details>

I think this discussion is out of scope for this refact

---

*[classes/Cart.php, line 2121 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X0a05JCgWvpeTFMu-:-L2KMiYH6nkC05eI8u6C:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/classes/Cart.php#L2121)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Missing doc
</blockquote></details>

Done.

---

*[classes/Cart.php, line 2121 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X0oHOPYiDvgdy16Iv:-L2KMk8ZFfQGA3BiAHzS:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/classes/Cart.php#L2121)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Please add a space before `(`
</blockquote></details>

Done.

---

*[classes/Cart.php, line 2123 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X0bTnmQNTBRTNixPW:-L2KMtR7ho5-ostTXgQL:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/classes/Cart.php#L2123)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

That `=` must feel lonely, being so far away from its variable
</blockquote></details>

Done.

---

*[classes/Cart.php, line 2129 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X0q0Yj91BaCpU_XFJ:-L2KOG-UNLNiZpot5sxY:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/classes/Cart.php#L2129)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Spaces
</blockquote></details>

Done.

---

*[classes/Cart.php, line 2130 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X0ri7UGwfxm88Mtkq:-L2KMv973JLCzAAJC5fa:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/classes/Cart.php#L2130)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Please don't use FQCN, use imports
</blockquote></details>

Done.

---

*[classes/Cart.php, line 2130 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X0ylj8NGj-CxR9HmG:-L2KNLADKkn8A_PkpES9:b-lw1mdd) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/classes/Cart.php#L2130)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Maybe we should consider passing cartRows and cartRules to the `Calculator` constructor, so we can skip the foreach's and function calls.
</blockquote></details>

since we do not inject products or cartRule here, but decorated-like objects, I dont think using the list of product or cart rule could be maintenable

---

*[classes/Cart.php, line 2210 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X2GuW3P3w3cbIKi7x:-L2L7w9DK6ScP5CVgggi:bs5iezc) ([raw file](https://github.co [...]

2018-01-09 17:48 UTC, eternoendless commented
Reviewed 6 of 15 files at r9.
Review status: 27 of 36 files reviewed at latest revision, 33 unresolved discussions.

---

*[src/Core/Cart/Calculator.php, line 194 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1Ws7Zxrl1GDH7QklpV:-L2QsgzvDG1CjHWUvq25:b-f52cs2) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/src/Core/Cart/Calculator.php#L194)):*
<details><summary><i>Previously, tomlev (Thomas LEVIANDIER) wrote…</i></summary><blockquote>

infortunately cart is currently required by calculator, but it should not. We should be able to calculate all data without a cart object, but it will be done later.
</blockquote></details>

After discussion, we settled that it's better to set it in the constructor

---

*[src/Core/Cart/Calculator.php, line 211 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1WspvxOwxlceUT4Bxk:-L2Qu1KLxPD2qiScMWb6:b2z22zm) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/src/Core/Cart/Calculator.php#L211)):*
<details><summary><i>Previously, tomlev (Thomas LEVIANDIER) wrote…</i></summary><blockquote>

infortunately cart is currently required by calculator, but it should not. We should be able to calculate all data without a cart object, but it will be done later.
</blockquote></details>

This should also be set in the constructor

---

*[src/Core/Cart/CartRow.php, line 139 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1Wv8ItzJSvRcjcC4ad:-L2QuklaBzEKcXwM-O4o:b-jo0d0g) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/src/Core/Cart/CartRow.php#L139)):*
<details><summary><i>Previously, tomlev (Thomas LEVIANDIER) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant the value of PS_USE_ECOTAX :grin: 

---

*[src/Core/Cart/CartRow.php, line 144 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1WvMnnQb_IaiyFLfiO:-L2QwtK0xX1Xam_7zsxB:b-2ts3di) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/src/Core/Cart/CartRow.php#L144)):*
<details><summary><i>Previously, tomlev (Thomas LEVIANDIER) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still missing the Adapter part

---

*[src/Core/Cart/CartRow.php, line 214 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1Wwh-sqVvjR5favFTD:-L2Qxc85uRUGmXTmWOj1:b-imj1fh) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/src/Core/Cart/CartRow.php#L214)):*
<details><summary><i>Previously, tomlev (Thomas LEVIANDIER) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant the values!

---

*[src/Core/Cart/CartRow.php, line 29 at r9](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L2QvBkkVouc_v2TLy2a:-L2QvBkkVouc_v2TLy2b:b-k1kil3) ([raw file](https://github.com/prestashop/prestashop/blob/743112f86feb3a628a435d4eb8cfccbb9320fbd0/src/Core/Cart/CartRow.php#L29)):*
> ```PHP
> namespace PrestaShop\PrestaShop\Core\Cart;
> 
> use Context;
> ```

You should avoid using Context, can't you inject Cart?

---

*[src/Core/Cart/CartRow.php, line 33 at r9](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L2QwRz9s7PVh03kfspe:-L2QwRz9s7PVh03kfspf:b-6alfzx) ([raw file](https://github.com/prestashop/prestashop/blob/743112f86feb3a628a435d4eb8cfccbb9320fbd0/src/Core/Cart/CartRow.php#L33)):*
> ```PHP
> use PrestaShop\PrestaShop\Adapter\Product\PriceCalculator;
> use PrestaShop\PrestaShop\Core\ConfigurationInterface;
> use Tools;
> ```

You should use Adapter\Tools (remember, no legacy calls in Core / PrestaShopBundle)

---

*[src/Core/Cart/CartRowCollection.php, line 37 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1WyjHrVTApb0adVDzC:-L2Qy0lOD-fvEuwmUPRu:b1nhayb) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/src/Core/Cart/CartRowCollection.php#L37)):*
<details><summary><i>Previously, tomlev (Thomas LEVIANDIER) wrote…</i></summary><blockquote>

too much inception, could you use Array constructor by passing an Array parameter ?
</blockquote></details>

Regardless, I think you can't beat
```php
new CartRowCollection($rows);
```
...it's better than:
```php
$cartRows = new CartRowCollection;
foreach ($rows as $row) {
  $cartRows->add($row);
}
```


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8411)*
<!-- Sent from Reviewable.io -->

2018-01-10 10:20 UTC, eternoendless commented
Reviewed 9 of 15 files at r9.
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[classes/Cart.php, line 2210 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X2GuW3P3w3cbIKi7x:-L2UV756aE3F_sRUOPLJ:btub9hk) ([raw file](https://github.com/prestashop/prestashop/blob/7a90eaee84326aa359c9aa02b11847191c38d1c3/classes/Cart.php#L2210)):*
<details><summary><i>Previously, tomlev (Thomas LEVIANDIER) wrote…</i></summary><blockquote>

this was a wrong use of cache
</blockquote></details>

As discussed, we need to be very careful when removing caches. We agree in that this is not the best way of doing it, but there are performance impacts that we need to keep in mind. In time, refactoring will allow removal of static caches.

Each removal needs to be analyzed carefully. Unless the cache is really useless, it's preferable to implement a cleaning method and invoke it in the right places.

---

*[classes/Cart.php, line 2239 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X29WPe8v0eOqG68AG:-L2UWKTPMRITqlQxChfI:b-bmv9cn) ([raw file](https://github.com/prestashop/prestashop/blob/7a90eaee84326aa359c9aa02b11847191c38d1c3/classes/Cart.php#L2239)):*
<details><summary><i>Previously, tomlev (Thomas LEVIANDIER) wrote…</i></summary><blockquote>

this kind of static cache usage is bad. It shows uncontrolled development and I dont think we must rely on this. If it trigger performance issues we should have a design discussion, not implement dirty cache everywhere
</blockquote></details>

I agree, but as discussed, that's out of the scope of this refactor :wink:

---

*[classes/Cart.php, line 2531 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X2Ncoj3bRkzwkOuCT:-L2UWTxJKd5nGd5IiOV-:bf68xcn) ([raw file](https://github.com/prestashop/prestashop/blob/7a90eaee84326aa359c9aa02b11847191c38d1c3/classes/Cart.php#L2531)):*
<details><summary><i>Previously, tomlev (Thomas LEVIANDIER) wrote…</i></summary><blockquote>

dirty cache should not be the answer to design mistakes
</blockquote></details>

Same comment as before

---

*[classes/Cart.php, line 2970 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X2Psh-Se4in2ys5wb:-L2UWa2sZOLwcQOgFCHg:bf68xcn) ([raw file](https://github.com/prestashop/prestashop/blob/7a90eaee84326aa359c9aa02b11847191c38d1c3/classes/Cart.php#L2970)):*
<details><summary><i>Previously, tomlev (Thomas LEVIANDIER) wrote…</i></summary><blockquote>

dirty cache usage should be simply removed
</blockquote></details>

Same comment as before

---

*[classes/Cart.php, line 3081 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1X2QnYz1PviFRetoUR:-L2UWbOxn2NTlHwkesSr:bf68xcn) ([raw file](https://github.com/prestashop/prestashop/blob/7a90eaee84326aa359c9aa02b11847191c38d1c3/classes/Cart.php#L3081)):*
<details><summary><i>Previously, tomlev (Thomas LEVIANDIER) wrote…</i></summary><blockquote>

dirty cache should not be the answer to design mistakes
</blockquote></details>

Same comment as before

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8411)*
<!-- Sent from Reviewable.io -->

2018-01-10 10:44 UTC, LittleBigDev commented
Review status: 31 of 36 files reviewed at latest revision, 16 unresolved discussions.

---

*[classes/Cart.php, line 2038 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L0FRsalScVjw8EJfakS:-L2UbKEr6louvX6t0Y2J:b-w9sxr8) ([raw file](https://github.com/prestashop/prestashop/blob/0573f4fb60b2370b8088f8ef3ddb34453b24f4cb/classes/Cart.php#L2038)):*
<details><summary><i>Previously, tomlev (Thomas LEVIANDIER) wrote…</i></summary><blockquote>

as discussed, this is out of scope for this refact
</blockquote></details>

Ok then

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8411)*
<!-- Sent from Reviewable.io -->

2018-01-10 22:01 UTC, tomlev commented
Review status: 30 of 36 files reviewed at latest revision, 15 unresolved discussions, some commit checks pending.

---

*[src/Core/Cart/Calculator.php, line 194 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1Ws7Zxrl1GDH7QklpV:-L2X0vK7-c5Pt4CGxauJ:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/src/Core/Cart/Calculator.php#L194)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

After discussion, we settled that it's better to set it in the constructor
</blockquote></details>

Done.

---

*[src/Core/Cart/Calculator.php, line 211 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1WspvxOwxlceUT4Bxk:-L2X1Hv5-NcW05fzFT3V:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/src/Core/Cart/Calculator.php#L211)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

This should also be set in the constructor
</blockquote></details>

Done.

---

*[src/Core/Cart/CartRow.php, line 139 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1Wv8ItzJSvRcjcC4ad:-L2X2BEcp8VPZFPqdbAQ:b-m6as4p) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/src/Core/Cart/CartRow.php#L139)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

I meant the value of PS_USE_ECOTAX :grin: 
</blockquote></details>

well, I think injecting global configuration like that is not a bad idea ?

---

*[src/Core/Cart/CartRow.php, line 144 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1WvMnnQb_IaiyFLfiO:-L2X2QzkZs9paiIYFsXR:b-854cdx) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/src/Core/Cart/CartRow.php#L144)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Still missing the Adapter part
</blockquote></details>

what is the corresponding adapter for context ?

---

*[src/Core/Cart/CartRow.php, line 214 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1Wwh-sqVvjR5favFTD:-L2X2boVoaiFJsZ1pwwP:b-djrokj) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/src/Core/Cart/CartRow.php#L214)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

I meant the values!
</blockquote></details>

is it ok with all configuration service injected ?

---

*[src/Core/Cart/CartRow.php, line 29 at r9](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L2QvBkkVouc_v2TLy2a:-L2X1cim7vMn_FEKv91X:b-3surge) ([raw file](https://github.com/prestashop/prestashop/blob/743112f86feb3a628a435d4eb8cfccbb9320fbd0/src/Core/Cart/CartRow.php#L29)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

You should avoid using Context, can't you inject Cart?
</blockquote></details>

unfortunately no, this is used at line 206

---

*[src/Core/Cart/CartRow.php, line 33 at r9](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L2QwRz9s7PVh03kfspe:-L2X20ealg7wn2u1c0ys:bpg68i4) ([raw file](https://github.com/prestashop/prestashop/blob/743112f86feb3a628a435d4eb8cfccbb9320fbd0/src/Core/Cart/CartRow.php#L33)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

You should use Adapter\Tools (remember, no legacy calls in Core / PrestaShopBundle)
</blockquote></details>

PrestaShop\PrestaShop\Adapter\Tools does not provide ps_round method. Where can I find it ?

---

*[src/Core/Cart/CartRowCollection.php, line 37 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1WyjHrVTApb0adVDzC:-L2X3iCBNjkqqc2e5SKD:b-90i5no) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/src/Core/Cart/CartRowCollection.php#L37)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Regardless, I think you can't beat
```php
new CartRowCollection($rows);
```
...it's better than:
```php
$cartRows = new CartRowCollection;
foreach ($rows as $row) {
  $cartRows->add($row);
}
</blockquote></details>

to discuss, I found no usage where it can be useful

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8411)*
<!-- Sent from Reviewable.io -->

2018-01-11 16:03 UTC, eternoendless commented
Reviewed 1 of 13 files at r1, 3 of 21 files at r3, 3 of 5 files at r10, 2 of 2 files at r11, 5 of 5 files at r12.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[classes/SpecificPrice.php, line 135 at r11](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L2ZhlY9YhpYHQtHXXCc:-L2ZhlYAkXbv-kPwtenP:bfex96n) ([raw file](https://github.com/prestashop/prestashop/blob/19a3734a69d1e4e2eee3bd85d43bfbc5878d2cc0/classes/SpecificPrice.php#L135)):*
> ```PHP
>     protected static $_no_specific_values = array();
> 
>     static $psQtyDiscountOnCombination = null;
> ```

Missing visibility here

---

*[src/Core/Cart/Calculator.php, line 211 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1WspvxOwxlceUT4Bxk:-L2ZlcGUDfWFwNSJrX9I:b1ko7cl) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/src/Core/Cart/Calculator.php#L211)):*
<details><summary><i>Previously, tomlev (Thomas LEVIANDIER) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The method should now be protected now, shouldn't it?

---

*[src/Core/Cart/CartRow.php, line 139 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1Wv8ItzJSvRcjcC4ad:-L2Zst-r5pc_1D1MwFQe:b-kd13t) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/src/Core/Cart/CartRow.php#L139)):*
<details><summary><i>Previously, tomlev (Thomas LEVIANDIER) wrote…</i></summary><blockquote>

well, I think injecting global configuration like that is not a bad idea ?
</blockquote></details>

It's easier to mock a value than an object. Either way, the key word here is "global" [state]

---

*[src/Core/Cart/CartRow.php, line 144 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1WvMnnQb_IaiyFLfiO:-L2_KvpZnUswdLPDyD56:b-gxpg55) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/src/Core/Cart/CartRow.php#L144)):*
<details><summary><i>Previously, tomlev (Thomas LEVIANDIER) wrote…</i></summary><blockquote>

what is the corresponding adapter for context ?
</blockquote></details>

As discussed, see if you can find out what you really need it for and inject those values instead

---

*[src/Core/Cart/CartRow.php, line 214 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1Wwh-sqVvjR5favFTD:-L2_t8Vmaz0r7DVih1i2:b-kxwyxb) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/src/Core/Cart/CartRow.php#L214)):*
<details><summary><i>Previously, tomlev (Thomas LEVIANDIER) wrote…</i></summary><blockquote>

is it ok with all configuration service injected ?
</blockquote></details>

It will be harder to override the configuration if the code depends on a global configuration object

---

*[src/Core/Cart/CartRow.php, line 29 at r9](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L2QvBkkVouc_v2TLy2a:-L2ZmHm4trXhhjMJP3ur:bt53ozn) ([raw file](https://github.com/prestashop/prestashop/blob/743112f86feb3a628a435d4eb8cfccbb9320fbd0/src/Core/Cart/CartRow.php#L29)):*
<details><summary><i>Previously, tomlev (Thomas LEVIANDIER) wrote…</i></summary><blockquote>

unfortunately no, this is used at line 206
</blockquote></details>

See if you can extract that dependency

---

*[src/Core/Cart/CartRow.php, line 33 at r9](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L2QwRz9s7PVh03kfspe:-L2Zm8FLxETBqGUG7xTS:b-e6rj72) ([raw file](https://github.com/prestashop/prestashop/blob/743112f86feb3a628a435d4eb8cfccbb9320fbd0/src/Core/Cart/CartRow.php#L33)):*
<details><summary><i>Previously, tomlev (Thomas LEVIANDIER) wrote…</i></summary><blockquote>

PrestaShop\PrestaShop\Adapter\Tools does not provide ps_round method. Where can I find it ?
</blockquote></details>

Just create a new method `round` that internally calls `Tools::ps_round`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8411)*
<!-- Sent from Reviewable.io -->

2018-02-08 13:42 UTC, eternoendless commented
Reviewed 1 of 13 files at r1, 9 of 9 files at r13.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/Adapter/Product/PriceCalculator.php, line 75 at r13](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L4p_WK5-YUaVjyHfI0N:-L4p_WK5-YUaVjyHfI0O:b-n3ly84) ([raw file](https://github.com/prestashop/prestashop/blob/24c5fd7125152a36d7154a10f9d157d680fc3042/src/Adapter/Product/PriceCalculator.php#L75)):*
> ```PHP
>     }
> 
>     public function priceCalculation(
> ```

:scream: 

Please add some phpdoc for this method :sweat_smile: 

---

*[src/Core/Cart/Calculator.php, line 115 at r13](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L4p_nl44d5W3hRluRVZ:-L4p_nl44d5W3hRluRV_:bb7bkwi) ([raw file](https://github.com/prestashop/prestashop/blob/24c5fd7125152a36d7154a10f9d157d680fc3042/src/Core/Cart/Calculator.php#L115)):*
> ```PHP
>      * run the whole calculation process: calculate rows, discounts, fees
>      *
>      * @param $computePrecision
> ```

I suppose this is an int?

---

*[src/Core/Cart/Calculator.php, line 251 at r13](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L4p_xmM8SxY1lZirn-K:-L4p_xmM8SxY1lZirn-L:bb7bkwi) ([raw file](https://github.com/prestashop/prestashop/blob/24c5fd7125152a36d7154a10f9d157d680fc3042/src/Core/Cart/Calculator.php#L251)):*
> ```PHP
>      * calculate wrapping and shipping fees
>      *
>      * @param $computePrecision
> ```

I suppose this is an int?

---

*[src/Core/Cart/CartRow.php, line 35 at r13](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L4pabId2WYb6E-jTxHU:-L4pabId2WYb6E-jTxHV:bbpk4bn) ([raw file](https://github.com/prestashop/prestashop/blob/24c5fd7125152a36d7154a10f9d157d680fc3042/src/Core/Cart/CartRow.php#L35)):*
> ```PHP
> use Db;
> use Group;
> use Order;
> ```

Too many legacy dependencies.
They need to be adapted and injected, or else this class needs to be moved into the `Adapter` namespace

---

*[src/Core/Cart/CartRow.php, line 83 at r13](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L4paRXD4WZjruoP5IfS:-L4paRXD4WZjruoP5IfT:b-sq0gyy) ([raw file](https://github.com/prestashop/prestashop/blob/24c5fd7125152a36d7154a10f9d157d680fc3042/src/Core/Cart/CartRow.php#L83)):*
> ```PHP
>      * @param                 $useEcotax
>      * @param                 $precision
>      * @param                 $roundType
> ```

Missing types here

---

*[src/Core/Cart/CartRow.php, line 217 at r13](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L4pbTM21TXhspPEnxE8:-L4pbTM21TXhspPEnxE9:bpjnwae) ([raw file](https://github.com/prestashop/prestashop/blob/24c5fd7125152a36d7154a10f9d157d680fc3042/src/Core/Cart/CartRow.php#L217)):*
> ```PHP
>                 $cartQuantity = Cache::retrieve($cacheId);
>             }
>         }
> ```

I suppose this part is still a WIP? :grin: 

---

*[tests/Unit/Core/Cart/Calculation/AbstractCartCalculationTest.php, line 46 at r13](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L4pcw8o3hX7qhTSONRN:-L4pcw8o3hX7qhTSONRO:bk16hek) ([raw file](https://github.com/prestashop/prestashop/blob/24c5fd7125152a36d7154a10f9d157d680fc3042/tests/Unit/Core/Cart/Calculation/AbstractCartCalculationTest.php#L46)):*
> ```PHP
>         //$totalV1       = round($totalV1, 1);
>         if (!$knownToFailOnV1) {
>             //$this->assertEquals($expectedTotal, $totalV1, 'V1 fail (tax incl)');
> ```

Commented code here

---

*[tests/Unit/Core/Cart/Calculation/AbstractCartCalculationTest.php, line 64 at r13](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L4pcroF1-oqv9hMv7fP:-L4pcroF1-oqv9hMv7fQ:bk16hek) ([raw file](https://github.com/prestashop/prestashop/blob/24c5fd7125152a36d7154a10f9d157d680fc3042/tests/Unit/Core/Cart/Calculation/AbstractCartCalculationTest.php#L64)):*
> ```PHP
>         }
>         $totalV2 = round($totalV2, 1);
>         $this->assertEquals($expectedTotal, $totalV2, 'V2 fail (tax excl)');*/
> ```

Commented code here

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/prestashop/prestashop/8411)*
<!-- Sent from Reviewable.io -->

2018-02-12 14:58 UTC, tomlev commented
Review status: 33 of 43 files reviewed at latest revision, 10 unresolved discussions.

---

*[classes/SpecificPrice.php, line 135 at r11](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L2ZhlY9YhpYHQtHXXCc:-L3gfv2enX0ZJ-6D_HQP:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/19a3734a69d1e4e2eee3bd85d43bfbc5878d2cc0/classes/SpecificPrice.php#L135)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Missing visibility here
</blockquote></details>

Done.

---

*[src/Adapter/Product/PriceCalculator.php, line 75 at r13](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L4p_WK5-YUaVjyHfI0N:-L59UB9-zi9WaINW8Dfw:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/24c5fd7125152a36d7154a10f9d157d680fc3042/src/Adapter/Product/PriceCalculator.php#L75)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

:scream: 

Please add some phpdoc for this method :sweat_smile: 
</blockquote></details>

Done.

---

*[src/Core/Cart/Calculator.php, line 211 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1WspvxOwxlceUT4Bxk:-L3gg6FcphcsA1IpwGfc:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/src/Core/Cart/Calculator.php#L211)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

The method should now be protected now, shouldn't it?
</blockquote></details>

Done.

---

*[src/Core/Cart/Calculator.php, line 115 at r13](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L4p_nl44d5W3hRluRVZ:-L59Ub1I400512CG1_oH:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/24c5fd7125152a36d7154a10f9d157d680fc3042/src/Core/Cart/Calculator.php#L115)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

I suppose this is an int?
</blockquote></details>

Done.

---

*[src/Core/Cart/Calculator.php, line 251 at r13](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L4p_xmM8SxY1lZirn-K:-L59UtZB1rUjH0H9HKez:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/24c5fd7125152a36d7154a10f9d157d680fc3042/src/Core/Cart/Calculator.php#L251)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

I suppose this is an int?
</blockquote></details>

Done.

---

*[src/Core/Cart/CartRow.php, line 139 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1Wv8ItzJSvRcjcC4ad:-L44z5Gj4-ry3m-qOsIz:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/src/Core/Cart/CartRow.php#L139)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

It's easier to mock a value than an object. Either way, the key word here is "global" [state]
</blockquote></details>

Done.

---

*[src/Core/Cart/CartRow.php, line 144 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1WvMnnQb_IaiyFLfiO:-L59VEBp2NftWEkr7zSU:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/src/Core/Cart/CartRow.php#L144)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

As discussed, see if you can find out what you really need it for and inject those values instead
</blockquote></details>

Done.

---

*[src/Core/Cart/CartRow.php, line 214 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L1Wwh-sqVvjR5favFTD:-L46H5vP6SS4GRjg6Sgv:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/15f8945aabdfd4d5546f155d375ed60197a3191c/src/Core/Cart/CartRow.php#L214)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

It will be harder to override the configuration if the code depends on a global configuration object
</blockquote></details>

Done.

---

*[src/Core/Cart/CartRow.php, line 29 at r9](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L2QvBkkVouc_v2TLy2a:-L59UyG5hTYMAssVtGqx:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/743112f86feb3a628a435d4eb8cfccbb9320fbd0/src/Core/Cart/CartRow.php#L29)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

See if you can extract that dependency
</blockquote></details>

Done.

---

*[src/Core/Cart/CartRow.php, line 33 at r9](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L2QwRz9s7PVh03kfspe:-L3ghV7-sBHqYdm0RK8T:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/743112f86feb3a628a435d4eb8cfccbb9320fbd0/src/Core/Cart/CartRow.php#L33)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Just create a new method `round` that internally calls `Tools::ps_round`
</blockquote></details>

Done.

---

*[src/Core/Cart/CartRow.php, line 35 at r13](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L4pabId2WYb6E-jTxHU:-L59UzAwW-ZYWmfosFpX:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/24c5fd7125152a36d7154a10f9d157d680fc3042/src/Core/Cart/CartRow.php#L35)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Too many legacy dependencies.
They need to be adapted and injected, or else this class needs to be moved into the `Adapter` namespace
</blockquote></details>

Done.

---

*[src/Core/Cart/CartRow.php, line 83 at r13](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L4paRXD4WZjruoP5IfS:-L59V8Qrtr5RYb3nq_Np:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/24c5fd7125152a36d7154a10f9d157d680fc3042/src/Core/Cart/CartRow.php#L83)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Missing types here
</blockquote></details>

Done.

---

*[src/Core/Cart/CartRow.php, line 217 at r13](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L4pbTM21TXhspPEnxE8:-L59VHEnyaU3zs64bocW:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/24c5fd7125152a36d7154a10f9d157d680fc3042/src/Core/Cart/CartRow.php#L217)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

I suppose this part is still a WIP? :grin: 
</blockquote></details>

Done.

---

*[tests/Unit/Core/Cart/Calculation/AbstractCartCalculationTest.php, line 46 at r13](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L4pcw8o3hX7qhTSONRN:-L59VQdeNziTI5udxPkt:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/24c5fd7125152a36d7154a10f9d157d680fc3042/tests/Unit/Core/Cart/Calculation/AbstractCartCalculationTest.php#L46)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Commented code here
</blockquote></details>

Done.

---

*[tests/Unit/Core/Cart/Calculation/AbstractCartCalculationTest.php, line 64 at r13](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L4pcroF1-oqv9hMv7fP:-L59VS-DeFMgGHNSoOxb:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/24c5fd7125152a36d7154a10f9d157d680fc3042/tests/Unit/Core/Cart/Calculation/AbstractCartCalculationTest.php#L64)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Commented code here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8411)*
<!-- Sent from Reviewable.io -->

2018-02-13 10:55 UTC, eternoendless commented
Reviewed 1 of 21 files at r3, 10 of 10 files at r14, 3 of 3 files at r15.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[classes/Cart.php, line 2169 at r14](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L5DSQWi03QQY4_nv-Hy:-L5DSQWi03QQY4_nv-Hz:b-1xwh4t) ([raw file](https://github.com/prestashop/prestashop/blob/143d2a2fcadefae2bb07a23af4c411b5beb37471/classes/Cart.php#L2169)):*
> ```PHP
>             $roundType = CartRow::ROUND_MODE_ITEM;
>                 break;
>         }
> ```

Another way of doing it would be like this:

```php
$roundTypes = [
    Order::ROUND_TOTAL => CartRow::ROUND_MODE_TOTAL,
    Order::ROUND_LINE  => CartRow::ROUND_MODE_LINE,
    Order::ROUND_ITEM  => CartRow::ROUND_MODE_ITEM,
];
$roundType = (isset($roundTypes[$configRoundType])) ? $roundTypes[$configRoundType] : CartRow::ROUND_MODE_ITEM
```

---

*[src/Adapter/Database.php, line 65 at r14](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L5DTLdN_2IvXJaJ7E_H:-L5DTLdN_2IvXJaJ7E_I:b-24l2u7) ([raw file](https://github.com/prestashop/prestashop/blob/143d2a2fcadefae2bb07a23af4c411b5beb37471/src/Adapter/Database.php#L65)):*
> ```PHP
>      * @return string|false|null
>      */
>     public function getValue($useMaster, $sql, $use_cache = true)
> ```

Maybe it would be better to put `$useMaster = true` as a second parameter?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8411)*
<!-- Sent from Reviewable.io -->

2018-03-27 12:11 UTC, tomlev commented
Review status: 23 of 46 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[classes/Cart.php, line 2169 at r14](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L5DSQWi03QQY4_nv-Hy:-L8apMSngQn3Ar0iNHf3:b-vezzgy) ([raw file](https://github.com/prestashop/prestashop/blob/143d2a2fcadefae2bb07a23af4c411b5beb37471/classes/Cart.php#L2169)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Another way of doing it would be like this:

```php
$roundTypes = [
    Order::ROUND_TOTAL => CartRow::ROUND_MODE_TOTAL,
    Order::ROUND_LINE  => CartRow::ROUND_MODE_LINE,
    Order::ROUND_ITEM  => CartRow::ROUND_MODE_ITEM,
];
$roundType = (isset($roundTypes[$configRoundType])) ? $roundTypes[$configRoundType] : CartRow::ROUND_MODE_ITEM
```
</blockquote></details>

Done. (with if/else for default value)

---

*[src/Adapter/Database.php, line 65 at r14](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L5DTLdN_2IvXJaJ7E_H:-L8aq4FjMqQ_PqV8uFli:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/143d2a2fcadefae2bb07a23af4c411b5beb37471/src/Adapter/Database.php#L65)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Maybe it would be better to put `$useMaster = true` as a second parameter?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8411)*
<!-- Sent from Reviewable.io -->

2018-03-27 12:33 UTC, LittleBigDev commented
Reviewed 1 of 2 files at r11, 1 of 5 files at r12, 8 of 15 files at r16, 4 of 13 files at r17, 1 of 1 files at r18.
Review status: 35 of 46 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[classes/Cart.php, line 2140 at r12](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L2_td1LcN5YgIUvdhpQ:-L2_td1LcN5YgIUvdhpR:b-9ylrhl) ([raw file](https://github.com/prestashop/prestashop/blob/eedde1c414ac41b700516ccf080f18d6b8b49d7a/classes/Cart.php#L2140)):*
> ```PHP
>      * @param $products
>      * @param $cartRules
>      * @param $id_carrier
> ```

Missing details on `@param`

---

*[classes/Cart.php, line 1890 at r18](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L8bOiiy3XgOnJMl1WLq:-L8bOiiy3XgOnJMl1WLr:bit5vl6) ([raw file](https://github.com/prestashop/prestashop/blob/fd5adabe8b7be0355199378597d6f54e805b93ec/classes/Cart.php#L1890)):*
> ```PHP
> 
>     /**
>      * get the populated cart calculator
> ```

Maybe there should be 2 methods for these 2 different tasks

---

*[src/Adapter/Tools.php, line 115 at r18](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L8bQ0HN8dCy9OcXLv5T:-L8bQ0HN8dCy9OcXLv5U:b-90ecw8) ([raw file](https://github.com/prestashop/prestashop/blob/fd5adabe8b7be0355199378597d6f54e805b93ec/src/Adapter/Tools.php#L115)):*
> ```PHP
>     public function round($value, $precision = 0, $round_mode = null)
>     {
>         return LegacyTools::ps_round($value, $precision, $round_mode);
> ```

We have `PrestaShop/Decimal` for that :thinking: 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/prestashop/prestashop/8411)*
<!-- Sent from Reviewable.io -->

2018-03-27 12:35 UTC, tomlev commented
Review status: 35 of 46 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[classes/Cart.php, line 2140 at r12](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L2_td1LcN5YgIUvdhpQ:-L8bS52JzZRVKKlisNAI:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/eedde1c414ac41b700516ccf080f18d6b8b49d7a/classes/Cart.php#L2140)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Missing details on `@param`
</blockquote></details>

Done.

---

*[classes/Cart.php, line 1890 at r18](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L8bOiiy3XgOnJMl1WLq:-L8bS-Ow3odhbSBSaosO:bmuri8x) ([raw file](https://github.com/prestashop/prestashop/blob/fd5adabe8b7be0355199378597d6f54e805b93ec/classes/Cart.php#L1890)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Maybe there should be 2 methods for these 2 different tasks
</blockquote></details>

I just splitted this ;)

---

*[src/Adapter/Tools.php, line 115 at r18](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-L8bQ0HN8dCy9OcXLv5T:-L8bSAcKvtwvaNvyMjpF:b-pm5748) ([raw file](https://github.com/prestashop/prestashop/blob/fd5adabe8b7be0355199378597d6f54e805b93ec/src/Adapter/Tools.php#L115)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

We have `PrestaShop/Decimal` for that :thinking: 
</blockquote></details>

I did not want to change any behaviour here, it will be part of next refact

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8411)*
<!-- Sent from Reviewable.io -->

2018-03-27 12:43 UTC, LittleBigDev commented
Reviewed 1 of 13 files at r17.
Review status: 36 of 46 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/Core/Cart/CartRow.php, line 107 at r18](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L8bS6fD3-9JmIl5dqUg:-L8bS6fD3-9JmIl5dqUh:bmn22vq) ([raw file](https://github.com/prestashop/prestashop/blob/fd5adabe8b7be0355199378597d6f54e805b93ec/src/Core/Cart/CartRow.php#L107)):*
> ```PHP
>      */
>     protected $isProcessed = false;
> ```

Missing doc for all the classe's attributes (description, usage, whatever is useful to understand it...)

---

*[src/Core/Cart/CartRow.php, line 165 at r18](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L8bSl914YSQIaux5Ao9:-L8bSl914YSQIaux5AoA:bu924hs) ([raw file](https://github.com/prestashop/prestashop/blob/fd5adabe8b7be0355199378597d6f54e805b93ec/src/Core/Cart/CartRow.php#L165)):*
> ```PHP
> 
>     /**
>      * @return \PrestaShop\PrestaShop\Core\Cart\AmountImmutable
> ```

Please import this class

---

*[src/Core/Cart/CartRow.php, line 168 at r18](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L8bSM_w4OGBfaQEvb3Q:-L8bSM_w4OGBfaQEvb3R:b-modro9) ([raw file](https://github.com/prestashop/prestashop/blob/fd5adabe8b7be0355199378597d6f54e805b93ec/src/Core/Cart/CartRow.php#L168)):*
> ```PHP
>      * @throws \Exception
>      */
>     public function getInitialUnitPrice()
> ```

Doc is incomplete

---

*[src/Core/Cart/CartRow.php, line 181 at r18](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L8bSq0B1kEYeVGo_nyH:-L8bSq0B1kEYeVGo_nyI:bx8nhj3) ([raw file](https://github.com/prestashop/prestashop/blob/fd5adabe8b7be0355199378597d6f54e805b93ec/src/Core/Cart/CartRow.php#L181)):*
> ```PHP
>      *
>      * @return \PrestaShop\PrestaShop\Core\Cart\AmountImmutable
>      * @throws \Exception
> ```

Please import these classes

---

*[src/Core/Cart/CartRow.php, line 196 at r18](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L8bSsF36xhU3lQHkc22:-L8bSsF36xhU3lQHkc23:bx8nhj3) ([raw file](https://github.com/prestashop/prestashop/blob/fd5adabe8b7be0355199378597d6f54e805b93ec/src/Core/Cart/CartRow.php#L196)):*
> ```PHP
>      *
>      * @return \PrestaShop\PrestaShop\Core\Cart\AmountImmutable
>      * @throws \Exception
> ```

Please import these classes

---

*[src/Core/Cart/CartRow.php, line 212 at r18](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L8bSuIREzWtsm1RGj0d:-L8bSuIREzWtsm1RGj0e:bu924hs) ([raw file](https://github.com/prestashop/prestashop/blob/fd5adabe8b7be0355199378597d6f54e805b93ec/src/Core/Cart/CartRow.php#L212)):*
> ```PHP
>      * @param Cart $cart
>      *
>      * @throws \PrestaShop\PrestaShop\Adapter\CoreException
> ```

Please import this class

---

*[src/Core/Cart/CartRow.php, line 326 at r18](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L8bTL5i6bh_s5VNtEiR:-L8bTL5i6bh_s5VNtEiS:bu5vygp) ([raw file](https://github.com/prestashop/prestashop/blob/fd5adabe8b7be0355199378597d6f54e805b93ec/src/Core/Cart/CartRow.php#L326)):*
> ```PHP
>     }
> 
>     protected function applyRound()
> ```

Missing doc

---

*[src/Core/Cart/CartRow.php, line 333 at r18](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L8bTeEB5QqOjZCbOOpj:-L8bTeEB5QqOjZCbOOpk:b-oaiiwf) ([raw file](https://github.com/prestashop/prestashop/blob/fd5adabe8b7be0355199378597d6f54e805b93ec/src/Core/Cart/CartRow.php#L333)):*
> ```PHP
>         $rowData  = $this->getRowData();
>         $quantity = (int) $rowData['cart_quantity'];
>         $tools    = new Tools;
> ```

Shouldn't we use `PrestaShop/Decimal` for rounding ?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/prestashop/prestashop/8411)*
<!-- Sent from Reviewable.io -->

2018-03-27 12:49 UTC, LittleBigDev commented
Reviewed 2 of 15 files at r16, 8 of 13 files at r17.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[tests/Unit/Core/Cart/Calculation/CartOld.php, line 351 at r18](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L8bUZuF9-xN1AADjt2W:-L8bUZuF9-xN1AADjt2X:b-txmfbu) ([raw file](https://github.com/prestashop/prestashop/blob/fd5adabe8b7be0355199378597d6f54e805b93ec/tests/Unit/Core/Cart/Calculation/CartOld.php#L351)):*
> ```PHP
>     }
> 
> }
> ```

Missing single blank line at the end

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/prestashop/prestashop/8411)*
<!-- Sent from Reviewable.io -->

2018-03-27 14:48 UTC, tomlev commented
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[src/Core/Cart/CartRow.php, line 107 at r18](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L8bS6fD3-9JmIl5dqUg:-L8bX1ctEc1KXSYzH_s-:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/fd5adabe8b7be0355199378597d6f54e805b93ec/src/Core/Cart/CartRow.php#L107)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Missing doc for all the classe's attributes (description, usage, whatever is useful to understand it...)
</blockquote></details>

Done.

---

*[src/Core/Cart/CartRow.php, line 165 at r18](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L8bSl914YSQIaux5Ao9:-L8buen0-AqADFF8GMtL:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/fd5adabe8b7be0355199378597d6f54e805b93ec/src/Core/Cart/CartRow.php#L165)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Please import this class
</blockquote></details>

Done.

---

*[src/Core/Cart/CartRow.php, line 168 at r18](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L8bSM_w4OGBfaQEvb3Q:-L8bum8O59WL6CK1XNEs:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/fd5adabe8b7be0355199378597d6f54e805b93ec/src/Core/Cart/CartRow.php#L168)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Doc is incomplete
</blockquote></details>

Done.

---

*[src/Core/Cart/CartRow.php, line 181 at r18](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L8bSq0B1kEYeVGo_nyH:-L8buvsU20z496Ji_7Aw:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/fd5adabe8b7be0355199378597d6f54e805b93ec/src/Core/Cart/CartRow.php#L181)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Please import these classes
</blockquote></details>

Done.

---

*[src/Core/Cart/CartRow.php, line 196 at r18](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L8bSsF36xhU3lQHkc22:-L8buwxv-5C87Lh0z3zm:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/fd5adabe8b7be0355199378597d6f54e805b93ec/src/Core/Cart/CartRow.php#L196)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Please import these classes
</blockquote></details>

Done.

---

*[src/Core/Cart/CartRow.php, line 212 at r18](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L8bSuIREzWtsm1RGj0d:-L8bv1Gj6C_u65Ou-K4z:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/fd5adabe8b7be0355199378597d6f54e805b93ec/src/Core/Cart/CartRow.php#L212)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Please import this class
</blockquote></details>

Done.

---

*[src/Core/Cart/CartRow.php, line 326 at r18](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L8bTL5i6bh_s5VNtEiR:-L8bvGGR3X9umJMWrW-J:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/fd5adabe8b7be0355199378597d6f54e805b93ec/src/Core/Cart/CartRow.php#L326)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Missing doc
</blockquote></details>

Done.

---

*[src/Core/Cart/CartRow.php, line 333 at r18](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L8bTeEB5QqOjZCbOOpj:-L8bvJVU9m01EGLHDYlp:b5vxx8k) ([raw file](https://github.com/prestashop/prestashop/blob/fd5adabe8b7be0355199378597d6f54e805b93ec/src/Core/Cart/CartRow.php#L333)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Shouldn't we use `PrestaShop/Decimal` for rounding ?
</blockquote></details>

I didn't want to change previous behaviour here : will be part of next refact

---

*[tests/Unit/Core/Cart/Calculation/CartOld.php, line 351 at r18](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-L8bUZuF9-xN1AADjt2W:-L8bvaF5EXBiRLY2aXMt:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/fd5adabe8b7be0355199378597d6f54e805b93ec/tests/Unit/Core/Cart/Calculation/CartOld.php#L351)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Missing single blank line at the end
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/prestashop/prestashop/8411)*
<!-- Sent from Reviewable.io -->

2018-03-27 14:52 UTC, LittleBigDev commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Reviewed 2 of 2 files at r19.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8411#-:-L8bwX2drcwBaNRDWKpZ:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2018-03-27 14:53 UTC, LittleBigDev submitted a review, later dismissed
Thx @tomlev

2018-03-27 14:55 UTC, LittleBigDev commented
As this PR is HUGE, I'd recommend another review from someone else before merging.
That's why I won't change the PR's labels nor Jira issue status.

2018-03-28 14:13 UTC, LittleBigDev commented
Reviewed 3 of 3 files at r20.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/prestashop/prestashop/8411)*
<!-- Sent from Reviewable.io -->

2018-03-28 14:36 UTC, LittleBigDev commented
Reviewed 1 of 13 files at r8, 7 of 16 files at r9, 1 of 10 files at r14, 1 of 1 files at r21.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/prestashop/prestashop/8411)*
<!-- Sent from Reviewable.io -->

2018-03-28 14:36 UTC, LittleBigDev submitted a review, later dismissed

2018-03-28 14:48 UTC, LittleBigDev commented
Reviewed 1 of 1 files at r22.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/prestashop/prestashop/8411)*
<!-- Sent from Reviewable.io -->

2018-03-28 14:49 UTC, LittleBigDev approved these changes

2018-03-28 14:53 UTC, eternoendless commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Reviewed 9 of 15 files at r16, 5 of 13 files at r17, 2 of 2 files at r19, 1 of 3 files at r20, 1 of 1 files at r21, 1 of 1 files at r22.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/prestashop/prestashop/8411#-:-L8h5G391kKBEYZ88hLi:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2018-03-29 09:43 UTC, tomlev commented
try to trigger a new travis build

2018-04-04 16:26 UTC, eternoendless commented
Thank you @tomlev 🎉

2018-04-04 16:26 UTC, merged

2019-01-16 17:10 UTC, EgamiCreation commented
Bonsoir, nous rencontrons un problème de calcul du code promotion suite à un bug que nous n'arrivons à tracer.

https://github.com/PrestaShop/PrestaShop/issues/12173

Merci d'avance de votre retour