Remove product description length limit
PrestaShop/PrestaShop pull request #8415
Opened 2017-10-13 12:53 UTC by maxime-aknin

Do not limit product description's length

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch       | 1.7.x
| Description  | Product description length limit is hard coded to 6000 characters.
| Type         |  improvement
| Category     | CO
| BC breaks    | no
| Deprecations | no
| Fixed ticket | --
| How to test  | Try to save a description with more than 6000 characters.

2017-10-16 08:22 UTC, xBorderie commented
Hey @maxime-aknin, thanks for the PR!
I'm unsure about the implications of such a change, none the less with the database. 
@eternoendless, what do you think?

2017-10-19 14:50 UTC, eternoendless commented
Thanks for this contribution, however we cannot merge it as-is. You can learn more about why this limit was introduced here: https://github.com/PrestaShop/PrestaShop/pull/7817

This limit can (and should) be upped to 21844 – the maximum safe limit for the TEXT field on MySQL using UTF-8 characters. Anything longer than that may be truncated by MySQL, depending on the characters used.

2017-10-19 14:51 UTC, eternoendless requested changes
The limit needs to be kept

2017-10-19 16:04 UTC, eternoendless approved these changes

2017-10-20 14:47 UTC, eternoendless commented
Thank you @maxime-aknin

2017-10-20 14:47 UTC, merged