Fix the name validator
PrestaShop/PrestaShop pull request #8430
Opened 2017-10-20 11:16 UTC by Azouz-Jribi

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | When creating a new account, we can save it into the DB even the last name or the first name are just a whitespace.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-7423
| How to test?  | FO > account creation > fill the first name or the last name with whitespace and "Register", check if the error message is displayed.

2017-11-07 14:05 UTC, LittleBigDev commented
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[classes/Validate.php, line 160 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8430#-KyLmts49MxYjwpETgTI:-KyLmts5ROBmKaWvJhFQ:b-ytv2hx) ([raw file](https://github.com/prestashop/prestashop/blob/8baba2da2759f21c5729ad03a49efb466fd31d2a/classes/Validate.php#L160)):*
> ```PHP
>     {
>         $name = trim($name);
>         
> ```

Please configure your IDE to strip trailing white spaces.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8430)*
<!-- Sent from Reviewable.io -->

2017-11-07 14:05 UTC, LittleBigDev requested changes
See comment above

2017-11-08 11:19 UTC, Azouz-Jribi commented
Hello @LittleBigDev 
Can you check it ?

Thanks ;)

2017-11-08 11:26 UTC, LittleBigDev commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8430#-:-KyQNSXStUTo70Amgkf1:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2017-11-08 11:27 UTC, LittleBigDev approved these changes

2019-09-19 14:10 UTC, matks commented
Ported to 1.7 with https://github.com/PrestaShop/PrestaShop/pull/15616. Author is mentioned and credited 😉

2019-09-19 14:10 UTC, closed without merging