CO: fix empty module return on actionEmailSendBefore breaks all email…
PrestaShop/PrestaShop pull request #8462
Opened 2017-11-02 14:54 UTC by MDWeb-Lille

… send

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | At the start of Mail::Send, the actionEmailSendBefore hook allowing for module override of emails blocks PS emails in case of a false-ish return. Modules like multiblocks break all emails send being hooked on this hook and not returning anything. This commit expects a strict false to block emails.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Create a module hooked on actionEmailSendBefore returning a false-ish value but not false (not returning anything for example). Without this commit, no email can go through. With this commit, emails are fine.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

2017-11-03 07:42 UTC, MDWeb-Lille commented
Updated for quality

2017-11-07 10:09 UTC, LittleBigDev commented
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[classes/Mail.php, line 112 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8462#-KyKwxTR3WCKYLJhpm8V:-KyKt2kP5xEoO38rGwp7:b-7bhjit) ([raw file](https://github.com/prestashop/prestashop/blob/b389fb88502c5f2888a9b0dcf0ea61ac4afb72ed/classes/Mail.php#L112)):*
> ```PHP
>         }
> 
>         $skip = array_reduce(Hook::exec(
> ```

While we are here, I suggest you rename this variable. It should actually be named `$keepGoing` or something equivalent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8462)*
<!-- Sent from Reviewable.io -->

2017-11-07 10:10 UTC, LittleBigDev requested changes
Hello @MDWeb-Lille, thanks for your contribution.
Your code looks good to me. But could you please add the small change I requested ?

Thanks a lot.

2017-11-07 10:58 UTC, MDWeb-Lille commented
Thanks for your review @LittleBigDev !
Change added!

2017-11-07 11:12 UTC, LittleBigDev commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8462#-:-KyLAc57CRCp5pNNzv3F:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2017-11-07 11:12 UTC, LittleBigDev submitted a review, later dismissed

2017-11-17 17:00 UTC, tomlev submitted a review, later dismissed

2017-11-20 08:27 UTC, LittleBigDev commented
Restarted the failing Travis job. Looks like the fail was not due to your PR. We'll see !

2017-11-20 09:13 UTC, LittleBigDev commented
Green, as expected !

2018-03-06 14:09 UTC, eternoendless approved these changes

2018-03-07 15:30 UTC, eternoendless commented
Thank you @MDWeb-Lille

2018-03-07 15:30 UTC, merged