add a few optimisations to speed up the display of the order history …
PrestaShop/PrestaShop pull request #8469
Opened 2017-11-06 16:51 UTC by jocel1

…page and to allow potential override to skip unneeded costly informations

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Speed up order page. Allow more efficient override
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Check the order history page still work properly

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

2017-11-06 16:55 UTC, jocel1 commented
I don't have the blackfire profile anymore, but it helps a customer reducing the order history load page from well.. a timeout to a few second for a specific profile loaded with orders. So I would say the gain is 90%+ for them

2017-11-15 14:06 UTC, LittleBigDev commented
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[controllers/front/HistoryController.php, line 47 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8469#-Kyzyzgh4mogB32dvU_G:-Kyzyzgi6GPVbbUZ6T24:belup5u) ([raw file](https://github.com/prestashop/prestashop/blob/94bd16b082475a3684fe7254971461c6863c001c/controllers/front/HistoryController.php#L47)):*
> ```PHP
>         }
> 
>         if ($this->order_presenter === null) {
> ```

Yoda condition ?
Personal taste, I would rather use `isset()` (basically the same, but easier to read)

---

*[src/Adapter/Order/OrderPresenter.php, line 295 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8469#-KyzynFSNtnh2UVF_wXk:-KyzynFSNtnh2UVF_wXl:ba4lkro) ([raw file](https://github.com/prestashop/prestashop/blob/94bd16b082475a3684fe7254971461c6863c001c/src/Adapter/Order/OrderPresenter.php#L295)):*
> ```PHP
>     /**
>      * @param Order $order
>      * @param bool  $getShippingInfos
> ```

Not matching the real parameter name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8469)*
<!-- Sent from Reviewable.io -->

2017-11-15 14:06 UTC, LittleBigDev requested changes
Thank you @jocel1 !
See my (few) comments above.

2017-11-28 16:39 UTC, jocel1 commented
fixed!

2017-11-29 09:19 UTC, LittleBigDev commented
Nice
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8469#-:-L-63fLG9vY4bxpjsrd8:b5w74d0)*
<!-- Sent from Reviewable.io -->

2017-11-29 10:04 UTC, LittleBigDev commented
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8469)*
<!-- Sent from Reviewable.io -->

2017-11-29 10:04 UTC, LittleBigDev submitted a review, later dismissed

2018-01-10 10:58 UTC, marionf commented
Hi @jocel1 

I have a notice on the order confirmation step 
![capture du 2018-01-10 11-50-35](https://user-images.githubusercontent.com/13449658/34769033-e4d99fa2-f5fc-11e7-86c5-45d86e311895.png)

The same notice on the order history
![capture du 2018-01-10 11-52-35](https://user-images.githubusercontent.com/13449658/34769040-f105e4de-f5fc-11e7-85d2-d9df775b32f0.png)

Another notice on the order detail page
![capture du 2018-01-10 11-57-03](https://user-images.githubusercontent.com/13449658/34769242-7fa2ec28-f5fd-11e7-9ba7-afb9c624093f.png)

2018-03-26 13:21 UTC, jocel1 commented
@marionf this should be fixed now, thanks!

2018-03-27 08:58 UTC, LittleBigDev commented
Reviewed 4 of 5 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/prestashop/prestashop/8469)*
<!-- Sent from Reviewable.io -->

2018-03-27 08:59 UTC, LittleBigDev submitted a review, later dismissed

2018-03-27 16:47 UTC, mickaelandrieu commented on classes/Cart.php
> +            $isVirtual = true;
How about ...

```php
$isVirtual = !$this->hasRealProducts();
```

2018-03-27 17:09 UTC, jocel1 commented on classes/Cart.php
> +            $isVirtual = true;
brilliant! 👍

2018-03-27 17:34 UTC, mickaelandrieu approved these changes

2018-03-27 17:34 UTC, merged

2018-03-27 17:34 UTC, mickaelandrieu commented
Thanks @jocel1 !