Adjust the quantity of packs after creating order
PrestaShop/PrestaShop pull request #8482
Opened 2017-11-08 17:30 UTC by Azouz-Jribi

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | When ordering a pack, the quantity of other packs with the same items is not reduced.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-8367
| How to test?  | BO > Create product (P1)[quantity = 10], create tow packs (C1 , C2) that contains the product (P1) with quantity (C1 [quantity P1= 2], C2 [quantity P1= 5]),  FO > ordered pack (C1) and check in the BO > catalog > products, if the quantity of the other pack (C2) is adjust.

2017-11-15 13:39 UTC, LittleBigDev commented
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[classes/order/OrderDetail.php, line 475 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8482#-KyztuZqQezpNLHdE45y:-KyztuZqQezpNLHdE45z:b7zf2ir) ([raw file](https://github.com/prestashop/prestashop/blob/82b123e441ad9f191ac8e869f6cf71207d72ed3c/classes/order/OrderDetail.php#L475)):*
> ```PHP
>                 $update_quantity = StockAvailable::updateQuantity($product['id_product'], $product['id_product_attribute'], -(int)$product['cart_quantity']);
>             }
>             
> ```

Trailing white spaces

---

*[classes/order/OrderDetail.php, line 476 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8482#-Kyzrl6z92AX-FRl6h8m:-Kyzrl7-rqYSOkdu7QM-:bc3ttsr) ([raw file](https://github.com/prestashop/prestashop/blob/82b123e441ad9f191ac8e869f6cf71207d72ed3c/classes/order/OrderDetail.php#L476)):*
> ```PHP
>             }
>             
>             $update_quantity = StockAvailable::checkPacksQuantity($product['id_product'], $product['id_product_attribute']);
> ```

Be careful, you are ignoring the previous value of `$update_quantity`. You should combine both results.

---

*[classes/stock/StockAvailable.php, line 808 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8482#-KyzsU6aZxeshPDAxxBO:-KyzsU6aZxeshPDAxxBP:b-rp7pce) ([raw file](https://github.com/prestashop/prestashop/blob/82b123e441ad9f191ac8e869f6cf71207d72ed3c/classes/stock/StockAvailable.php#L808)):*
> ```PHP
>     /**
>      * Check the quantity of packets if it is adjusted
>      *
> ```

Describe the utility of this method, and/or maybe the situation when we need it.

---

*[classes/stock/StockAvailable.php, line 810 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8482#-Kyzs8vNM7XSi_5qLuJJ:-Kyzs8vQOqp0zH0vDV5K:b-4wtx4t) ([raw file](https://github.com/prestashop/prestashop/blob/82b123e441ad9f191ac8e869f6cf71207d72ed3c/classes/stock/StockAvailable.php#L810)):*
> ```PHP
>      *
>      * @param int $idProduct
>      * @param int $idProductAttribute
> ```

Explain what are `$idProduct` and `$idProductAttribute`
Also, I recommend naming them `$productId' and `$productAttributeId`

---

*[classes/stock/StockAvailable.php, line 811 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8482#-KyzsdMSzjjQDAbqujUQ:-KyzsdMSzjjQDAbqujUR:b-kg8yht) ([raw file](https://github.com/prestashop/prestashop/blob/82b123e441ad9f191ac8e869f6cf71207d72ed3c/classes/stock/StockAvailable.php#L811)):*
> ```PHP
>      * @param int $idProduct
>      * @param int $idProductAttribute
>      * @return bool
> ```

Explain why it returns true (or false if it's more relevant)

---

*[classes/stock/StockAvailable.php, line 827 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8482#-Kyzt3OEbhvgbSpCDsgU:-Kyzt3OEbhvgbSpCDsgV:bfvf6uj) ([raw file](https://github.com/prestashop/prestashop/blob/82b123e441ad9f191ac8e869f6cf71207d72ed3c/classes/stock/StockAvailable.php#L827)):*
> ```PHP
>             foreach ($items as $item) {
>                 $stockAvailable = $stockManager->getStockAvailableByProduct($item, (int)$item->id_pack_product_attribute);
>                 $businessStockManager->updatePacksQuantityContainingProduct($item, (int)$item->id_pack_product_attribute, $stockAvailable);
> ```

Looks like this is updating a quantity. A validation method should have validation responsibility only.
Single Responsibility Principle ("S" of "SOLID").
You should use the result of validation to decide whether you need to update something or not. But don't do it in the same method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8482)*
<!-- Sent from Reviewable.io -->

2017-11-15 13:40 UTC, LittleBigDev requested changes
Thank you @Azouz-Jribi. See my comments above.

2017-11-20 17:17 UTC, Azouz-Jribi commented
Hi @LittleBigDev 
Correction is done, can you check it ?

Thanks ;)

2017-11-21 08:23 UTC, LittleBigDev commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8482#-:-KzSfAPqvo1bM4QwoA2q:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2017-11-21 08:23 UTC, LittleBigDev approved these changes

2020-01-24 10:25 UTC, closed without merging