CO: fixed bug when reorder with free gift in the cart
PrestaShop/PrestaShop pull request #8497
Opened 2017-11-15 05:09 UTC by blueshadow2911

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x (and also applicable for develop)
| Description?  | based on what's written in the code, it's supposed to remove free gift from previous order in current new cart (re-order), but it's currently not doing its job because SQL selector is using wrong variable (id_cart instead of id_order).
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Make any order with free gift inside it. Then go to "My Order History" and do "Re-order"

2017-11-15 10:03 UTC, LittleBigDev commented
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[classes/Cart.php, line 3525 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8497#-Kyz7D1LmSsHc30BzUNv:-Kyz7D1LmSsHc30BzUNw:btdfu2o) ([raw file](https://github.com/prestashop/prestashop/blob/893b95edf01faa3f752114d71c20bcee499fbb87/classes/Cart.php#L3525)):*
> ```PHP
>         $products = Db::getInstance(_PS_USE_SQL_SLAVE_)->executeS('SELECT * FROM `'._DB_PREFIX_.'cart_product` WHERE `id_cart` = '.(int)$this->id);
> 
>         $id_order = Order::getOrderByCartId((int)$this->id);
> ```

`$orderId`

---

*[classes/Cart.php, line 3530 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8497#-Kyz7FZ1Y2cNQrpUVj7G:-Kyz7FZ1Y2cNQrpUVj7H:b-xwfxaf) ([raw file](https://github.com/prestashop/prestashop/blob/893b95edf01faa3f752114d71c20bcee499fbb87/classes/Cart.php#L3530)):*
> ```PHP
>         }
>         else {
>             $product_gift = array();
> ```

Please init `$product_gift ) array()` before the `if` and get rid of this `else`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8497)*
<!-- Sent from Reviewable.io -->

2017-11-15 10:04 UTC, LittleBigDev requested changes
Hello @blueshadow2911, as this is the exact same code from your other PR (base branch 1.7), I was less verbose.
Though, thank you again for your time :)

2017-11-15 15:53 UTC, hitasukha commented
Hi @LittleBigDev, I have done changes as requested.

2017-11-15 16:35 UTC, LittleBigDev commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8497#-:-Kz-XAvOObJ2nJXojued:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2017-11-15 16:35 UTC, LittleBigDev approved these changes

2017-11-23 15:18 UTC, mickaelandrieu approved these changes

2018-02-12 03:41 UTC, blueshadow2911 commented
@Quetzacoalt91 

Hi, I think, this is wrongly put into 1.7.x milestone, because it's being tagged at 1.6.1.x.

2018-02-13 13:10 UTC, Quetzacoalt91 commented
You're totally right. Thanks for noticing. :)

2019-09-06 14:24 UTC, matks commented
Hello,

I'm sorry but PrestaShop 1.6 support ended on June 30, 2019, consequently this PR will not be merged into the project.
Thank you for your contribution, I have checked and on 1.7 the bug is already fixed ✅ 

Please note that if a critical issue is discovered, there is a dedicated GitHub repository: https://github.com/PrestaShop/PrestaShop-1.6 maintained by a team of volunteers.
From this repository, it will be possible to submit pull requests in order to fix critical issues.

You can read more about it on http://build.prestashop.com/news/1.6.1.x-what-s-next/

2019-09-06 14:24 UTC, closed without merging