CO: fixed bug when reorder with free gift in the cart (1.7)
PrestaShop/PrestaShop pull request #8498
Opened 2017-11-15 05:17 UTC by blueshadow2911

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | based on what's written in the code, it's supposed to remove free gift from previous order in current new cart (re-order), but it's currently not doing its job because SQL selector is using wrong variable (id_cart instead of id_order).
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Make any order with free gift inside it. Then go to "My Order History" and do "Re-order"

2017-11-15 09:58 UTC, LittleBigDev commented
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[classes/Cart.php, line 4083 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8498#-Kyz53eXPOrO-HWM4ET-:-Kyz53eXPOrO-HWM4ET0:bn7vtiw) ([raw file](https://github.com/prestashop/prestashop/blob/c60fc2df31e289c8a9ab8f6e9c5e0b7fef83e391/classes/Cart.php#L4083)):*
> ```PHP
>         $products = Db::getInstance(_PS_USE_SQL_SLAVE_)->executeS('SELECT * FROM `'._DB_PREFIX_.'cart_product` WHERE `id_cart` = '.(int)$this->id);
> 
>         $id_order = Order::getIdByCartId((int)$this->id);
> ```

Please use camelCase notation for new variables. Also, I would rather name it `$orderId`.

---

*[classes/Cart.php, line 4087 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8498#-Kyz42qnd0LRATz_Ts7P:-Kyz42qnd0LRATz_Ts7Q:bpwrolg) ([raw file](https://github.com/prestashop/prestashop/blob/c60fc2df31e289c8a9ab8f6e9c5e0b7fef83e391/classes/Cart.php#L4087)):*
> ```PHP
>             $product_gift = Db::getInstance(_PS_USE_SQL_SLAVE_)->executeS('SELECT cr.`gift_product`, cr.`gift_product_attribute` FROM `'._DB_PREFIX_.'cart_rule` cr LEFT JOIN `'._DB_PREFIX_.'order_cart_rule` ocr ON (ocr.`id_order` = '.(int)$id_order.') WHERE ocr.`id_cart_rule` = cr.`id_cart_rule`');
>         }
>         else {
> ```

Please avoid `else` when it is not ABSOLUTELY necessary.
Here, you can init `$product_gift = array();` before the `if ($id_order) {`.

---

*[classes/Cart.php, line 4090 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8498#-Kyz4LCoxwnomMvWe4zj:-Kyz4LCoxwnomMvWe4zk:b-1ku7gz) ([raw file](https://github.com/prestashop/prestashop/blob/c60fc2df31e289c8a9ab8f6e9c5e0b7fef83e391/classes/Cart.php#L4090)):*
> ```PHP
>             $product_gift = array();
>         }
>         
> ```

Please do not leave trailing white spaces. Modern IDEs can be configured to strip them automatically.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8498)*
<!-- Sent from Reviewable.io -->

2017-11-15 09:59 UTC, LittleBigDev requested changes
Hello @blueshadow2911, thank you for spotting this !
Your fix is correct, but I have some best practices requests. See my comment above.

2017-11-15 15:51 UTC, blueshadow2911 commented
Hi @LittleBigDev, I have done changes as requested.

2017-11-15 16:33 UTC, LittleBigDev commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8498#-:-Kz-Wmhoagmi6Qc8a0En:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2017-11-15 16:33 UTC, LittleBigDev submitted a review, later dismissed
Thank you !

2018-03-07 15:43 UTC, eternoendless commented
Thank you @blueshadow2911

2018-03-07 15:45 UTC, eternoendless approved these changes

2018-03-16 14:22 UTC, merged