Added GroupBy option for actionAdminProductsListingFieldsModifier hook
PrestaShop/PrestaShop pull request #8514
Opened 2017-11-18 21:48 UTC by astterx

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop.
| Description?  | Added group by for sql query to be used with actionAdminProductsListingFieldsModifier hook
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | (optional) If this PR fixes a [Forge](http://forge.prestashop.com/) ticket, please add its complete Forge URL.
| How to test?  | Please indicate how to best verify that this PR is correct.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

2017-11-18 21:58 UTC, kpodemski commented
Hey @astterx 

you can't just additional parameter inside the function before the previous ones as this is breaking change

2017-11-22 15:00 UTC, Quetzacoalt91 commented on src/Adapter/Product/AdminProductDataProvider.php
> +        $total = \Db::getInstance()->executeS('SELECT FOUND_ROWS();', true, false);
No need to replace `Db` with `\Db`, as we declared the class at the top of the file with 

```php
use Db;
```

2017-11-22 15:03 UTC, Quetzacoalt91 commented
Do you have a use case to share with that PR @astterx?

2017-11-23 09:31 UTC, astterx commented
For a shop with car parts, I created a module to assign every product to a compatible car. A product can be compatible to multiple cars so using hookActionAdminProductsListingFieldsModifier to retrieve also car model for each product, method getCatalogProductList() will return duplicated products, because now is not possible to group by.
![image](https://user-images.githubusercontent.com/7818358/33166093-b4ab2566-d041-11e7-8276-b02589e5e242.png)

2017-11-23 09:40 UTC, astterx commented
Hi @kpodemski,

> Hey @astterx
> 
> you can't just additional parameter inside the function before the previous ones as this is breaking change

Method is used only once, just in location where I modified.

2017-11-23 10:00 UTC, Quetzacoalt91 requested changes
Just some changes to bring and we should be good.

About the method signature, I decided to not ask for anything as we deal with a protected one. Overrides are also not available for this part of the code, so broken code should not occur here.

2017-11-23 10:00 UTC, Quetzacoalt91 commented on src/Adapter/Admin/AbstractAdminQueryBuilder.php
> +            $sql[] = 'GROUP BY '. implode(', ', $groupBy) . PHP_EOL;
I feel we may probably handle user data here, and we need to add some sanitization here with

```php
array_map('pSQL', $groupBy);
```

Can you please replace this line with this one:
```php
$sql[] = 'GROUP BY '. implode(', ', array_map('pSQL', $groupBy)) . PHP_EOL;
```

<!-- ping @rGaillard -->

2017-11-23 10:00 UTC, Quetzacoalt91 commented on src/Adapter/Product/AdminProductDataProvider.php
> +        $sqlGroupBy = [];
Currently, we initialize arrays with the long syntax form. `[]` should be `array()`

2017-11-23 10:12 UTC, Quetzacoalt91 submitted a review, later dismissed

2017-11-23 10:12 UTC, Quetzacoalt91 commented
Thank you @astterx

2017-11-23 15:11 UTC, mickaelandrieu commented
@mbadrani what do you think about this improvement? Can we accept it?

Thanks for your contribution @astterx

2017-12-04 10:30 UTC, astterx commented
Hi @Quetzacoalt91 ,

Any update?

2017-12-04 10:34 UTC, Quetzacoalt91 commented on install-dev/data/db_structure.sql
> +  `id_word` bigint(20) unsigned NOT NULL auto_increment,
New changes were brought to this PR but are unrelated to the original su

2017-12-04 10:36 UTC, Quetzacoalt91 commented
Hello @astterx, we were waiting for the QA team before further action.
In the meantime, would you mind removing the additional commit not related to the groupBy parameter?

Thank you

2017-12-04 10:57 UTC, astterx commented
I removed additional commit.

2017-12-04 10:59 UTC, Quetzacoalt91 submitted a review, later dismissed
Thank you. Now, this is in the hands of the QA team. ;)

2017-12-05 09:32 UTC, marionf commented
Hello @astterx & @Quetzacoalt91 
What are the functional tests to do ?

2017-12-06 11:43 UTC, astterx commented
Hi @marionf 
You should do a regression testing on admin product list.

2018-02-28 15:19 UTC, astterx commented
Hi. Any update here?

2018-03-13 08:20 UTC, marionf commented
ping @Quetzacoalt91 can you review it before I test ?

2018-03-13 08:57 UTC, Quetzacoalt91 approved these changes
Still fine for me.

2018-03-27 16:43 UTC, mickaelandrieu commented
Thanks @astterx !

2018-03-27 16:43 UTC, merged