Fix the display of the specific price in the product page FO
PrestaShop/PrestaShop pull request #8538
Opened 2017-11-23 12:02 UTC by Azouz-Jribi

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | When you try to order a product with (ordered quantity > than the quantity of volume discount), the unit price become  0.00€
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-9383
| How to test?  | BO > create a product with specific price, FO > try to set (the ordered quantity >  than the quantity of volume discount) in the product page, check if the unit price is displayed correctly.

2018-02-07 08:04 UTC, hakeryk2 commented
@LittleBigDev and @Quetzacoalt91 I saw a few forum issues in polish section and users who applied this solution reported that this fix was salvation for them. I think this is pretty common bug.

2018-02-09 09:32 UTC, LittleBigDev commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8538#-:-L4tu7xBh8mqo0cYXSqP:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2018-02-09 09:33 UTC, LittleBigDev submitted a review, later dismissed
Thank you @Azouz-Jribi

2018-02-27 15:47 UTC, kmorgen commented
**Fixed amount discounts** are now shown correct in FO with this fix. However at other currencies than the shop default, the price will be shown incorrect when changing to the discounted quantity. It seem to show the shop default currency instead (but correct amount added to cart though).

For **percentage** discounts the shown prices also appear to show more correct (for default currency), but the actual amount added to the cart is wrong.

In both cases the 'You Save' amount is only shown correct with the shop default currency.

![wrong prices shown in fo with other currencies](https://user-images.githubusercontent.com/4300688/36738497-eb5082f4-1bdd-11e8-87f9-4e1956de047b.jpg)

2018-02-28 15:56 UTC, LittleBigDev approved these changes
Oops I dismissed my approval by mistake. Still we need to reproduce the currency switch issue with @prasanthSelvar help

2018-03-02 14:11 UTC, prasanthSelvar commented
Hello @kmorgen ,

Thank you for your feedback but I can't reproduce your currency switch issue with this fix.
I added an attachment **currency.gif** to your forge ticket [PSCSX-9037](http://forge.prestashop.com/browse/PSCSX-9037) and it seems to work good for me.
Could you please recheck and feedback in the JIRA ticket ?

Thanks

2018-03-08 13:08 UTC, kmorgen commented
Helle @prasanthSelvar 

Thank you for response!

I can see my issue / screenshot was produced for a customer group with 'Tax excl.' view. So not sure if this affect results.

However I also notice your quantity discount is shown as a percentage, and here it show as the value (despite we make a % discount).  Not sure if this is somwhat theme related. Will check.

2018-06-15 08:41 UTC, themella commented
not fixed! cause if you have price without tax new price will be dispayed with tax!

2018-11-21 10:41 UTC, tanzo commented
@themella 
Fix applied on fresh installation and on the default-bootstrap template (without changing nothing in the template), the fix works with and without taxes displaying.
Here you can see the fix applied:
http://ps16123.tanzows.it/en/home/8-test-prodotto.html

2018-11-21 10:49 UTC, tanzo requested changes
Fix applied on fresh installation (default template). Works with and without taxes displaying with a discount in percentage, didn't works with a different base price setted.

2019-01-18 18:45 UTC, SharakPL commented
https://github.com/PrestaShop/PrestaShop/blob/7a12373c2cb2c574d82bcd50fe778f89cefd1d14/controllers/front/ProductController.php#L337-L339 Why not set this straight to
`$quantity_discount['base_price'] = $this->product->getPrice(Product::$_taxCalculationMethod == PS_TAX_INC);`

Main bug here is that base_price is set to 0 instead of actual product's main price so the final price is counted as ( 0 - discount ). That is with amount discounts used. When percentages are used conditions in product.tpl are counted as ( 0 * (1 - reduction) ) so basically it's always 0.
https://github.com/PrestaShop/PrestaShop/blob/9d2d6396987c9cf070557605179f9fd959950e45/themes/default-bootstrap/product.tpl#L418-L423

Problem is only on product page:

![psqdbug_p](https://user-images.githubusercontent.com/5007456/51406455-72964200-1b59-11e9-9688-904b1ffd82e0.gif)

The same functionality in order page works perfectly fine:

![psqdbug_c](https://user-images.githubusercontent.com/5007456/51406465-7aee7d00-1b59-11e9-9750-c1565dd4d12b.gif)

2019-09-12 19:23 UTC, matks commented
Hello,

I'm sorry but PrestaShop 1.6 support ended on June 30, 2019, consequently this PR will not be merged into the project.
Thank you for your contribution.

Please note that if a critical issue is discovered, there is a dedicated GitHub repository: https://github.com/PrestaShop/PrestaShop-1.6 maintained by a team of volunteers.
From this repository, it will be possible to submit pull requests in order to fix critical issues.

You can read more about it on http://build.prestashop.com/news/1.6.1.x-what-s-next/

2019-09-12 19:23 UTC, closed without merging