Notifs dropdown open/close is bugged on SF pages
PrestaShop/PrestaShop pull request #8552
Opened 2017-11-27 14:31 UTC by LittleBigDev

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.3.x
| Description?  | Impossible to close the notif dropdown on SF pages. More : code was obsolete and there was a much cleaner way to handle the same (supposed) behavior.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | [BOOM-4378](http://forge.prestashop.com/browse/BOOM-4378)
| How to test?  | Go to an SF page (e.g. : modules list) and mess around with notif dropdown (clicks inside, outside, tabs display, etc.).

2017-11-27 17:18 UTC, eternoendless commented
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[admin-dev/themes/new-theme/js/header.js, line 102 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8552#-KzyTvvJvUo3DfsLanoC:-KzyTvvJvUo3DfsLanoD:bi9j847) ([raw file](https://github.com/prestashop/prestashop/blob/3e4cd5fd0655d97f2fab2154338c07df6eafe038/admin-dev/themes/new-theme/js/header.js#L102)):*
> ```JavaScript
>   }
> 
>   initNotificationsToggle() {
> ```

We should write a comment explaining why this is handled manually

---

*[admin-dev/themes/new-theme/js/header.js, line 105 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8552#-KzyRv-0iGk_V7iJB15S:-KzyRv-0iGk_V7iJB15T:bkr8oeb) ([raw file](https://github.com/prestashop/prestashop/blob/3e4cd5fd0655d97f2fab2154338c07df6eafe038/admin-dev/themes/new-theme/js/header.js#L105)):*
> ```JavaScript
>     $('#notif').on({
>       "shown.bs.dropdown": function() { $(this).attr('closable', false); },
>       'hide.bs.dropdown': function () { return $(this).attr('closable') == 'true';}
> ```

Please mind the formatting.

* Prefer single quote strings, unless you really need double quotes.
* Don't write single line functions.

---

*[admin-dev/themes/new-theme/js/header.js, line 105 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8552#-KzySOyk2dW4qYVtv-hg:-KzySOyk2dW4qYVtv-hh:b-lxe70i) ([raw file](https://github.com/prestashop/prestashop/blob/3e4cd5fd0655d97f2fab2154338c07df6eafe038/admin-dev/themes/new-theme/js/header.js#L105)):*
> ```JavaScript
>     $('#notif').on({
>       "shown.bs.dropdown": function() { $(this).attr('closable', false); },
>       'hide.bs.dropdown': function () { return $(this).attr('closable') == 'true';}
> ```

I think it would be better to use a data-attribute instead of an attribute, because `closable` is not a valid attribute.
You just need to replace `attr` by `data`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8552)*
<!-- Sent from Reviewable.io -->

2017-11-27 17:18 UTC, eternoendless requested changes
Nice solution! We need to address some small issues though

2017-11-28 08:38 UTC, LittleBigDev commented
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[admin-dev/themes/new-theme/js/header.js, line 102 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8552#-KzyTvvJvUo3DfsLanoC:-L-0ic7ccs1SoUxiEfW0:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/3e4cd5fd0655d97f2fab2154338c07df6eafe038/admin-dev/themes/new-theme/js/header.js#L102)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

We should write a comment explaining why this is handled manually
</blockquote></details>

Done.

---

*[admin-dev/themes/new-theme/js/header.js, line 105 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8552#-KzyRv-0iGk_V7iJB15S:-L-0isK6I28nsA4F34ei:bqe9yop) ([raw file](https://github.com/prestashop/prestashop/blob/3e4cd5fd0655d97f2fab2154338c07df6eafe038/admin-dev/themes/new-theme/js/header.js#L105)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Please mind the formatting.

* Prefer single quote strings, unless you really need double quotes.
* Don't write single line functions.
</blockquote></details>

Wild copy pasta...

---

*[admin-dev/themes/new-theme/js/header.js, line 105 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8552#-KzySOyk2dW4qYVtv-hg:-L-0jCUj4sZBtTrvoFgC:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/3e4cd5fd0655d97f2fab2154338c07df6eafe038/admin-dev/themes/new-theme/js/header.js#L105)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

I think it would be better to use a data-attribute instead of an attribute, because `closable` is not a valid attribute.
You just need to replace `attr` by `data`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8552)*
<!-- Sent from Reviewable.io -->

2017-11-28 10:18 UTC, eternoendless commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Reviewed 1 of 5 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8552#-:-L-17cSUSlqxZiFzENdk:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2017-11-28 10:18 UTC, eternoendless approved these changes

2017-11-28 10:38 UTC, eternoendless commented
Thank you @LittleBigDev

2017-11-28 10:38 UTC, merged