WIP : pushing for checkout purpose
PrestaShop/PrestaShop pull request #8581
Opened 2017-12-05 09:46 UTC by LittleBigDev

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | See Jira issue
| Type?         | new feature
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | [FF-137](http://forge.prestashop.com/browse/FF-137)
| How to test?  | See Jira issue

2017-12-08 09:37 UTC, LittleBigDev commented
Needs unit tests.

2017-12-11 15:06 UTC, eternoendless commented
Reviewed 2 of 7 files at r1, 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[src/PrestaShopBundle/Localization/Exception/Exception.php, line 29 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L050dBnKows1yevF6p0:-L050dBonJMgB4fT2TNg:b9nhq0) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/src/PrestaShopBundle/Localization/Exception/Exception.php#L29)):*
> ```PHP
> namespace PrestaShopBundle\Localization\Exception;
> 
> class Exception extends \Exception
> ```

While this is correct, I think that "LocalizationException" would be better.

I find that using simply "Exception" has two disadvantages:

1) When you read "throw Exception" in the code, you cannot know right away which kind of exception is being thrown.
2) When you start typing "throw Exc|" you'll have dozens of Exception on your autocomplete list.

---

*[src/PrestaShopBundle/Localization/Exception/InvalidArgumentException.php, line 29 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L051TL2mdzXrdzcqoe4:-L051TL2mdzXrdzcqoe5:b-eh02ed) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/src/PrestaShopBundle/Localization/Exception/InvalidArgumentException.php#L29)):*
> ```PHP
> namespace PrestaShopBundle\Localization\Exception;
> 
> class InvalidArgumentException extends \InvalidArgumentException
> ```

1) Unless you are targeting to catch a specific type of exception, don't over specify.
2) This exception does not extend `Localization\Exception\Exception`, which means that if you want to catch all exceptions thrown by Localization you need two separate `catch`.

The way I see it, typed exceptions should be used ONLY for targeted catching. If you want to send information, you should use the exception message.

---

*[src/PrestaShopBundle/Localization/Specification/Number.php, line 64 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L053vn4oKziEDnnsyAF:-L053vn4oKziEDnnsyAG:bck5hbp) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/src/PrestaShopBundle/Localization/Specification/Number.php#L64)):*
> ```PHP
> 
>     /**
>      * @var NumberSymbolList[]
> ```

Missing description. You should say that this is indexed by numbering system

---

*[src/PrestaShopBundle/Localization/Specification/Number.php, line 116 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L052yiPH5aoEn2i63Zw:-L052yiPH5aoEn2i63Zx:b-lwcom6) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/src/PrestaShopBundle/Localization/Specification/Number.php#L116)):*
> ```PHP
>      *  The symbols list to use when formatting in this numbering system
>      */
>     public function addSymbols($numberingSystem, NumberSymbolList $symbolList)
> ```

Why not set everything in the constructor?
In which use case this class should be mutated?

---

*[src/PrestaShopBundle/Localization/Specification/Number.php, line 132 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L053R4yvIo4pGu9WBPv:-L053R4yvIo4pGu9WBPw:b-kkw5bn) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/src/PrestaShopBundle/Localization/Specification/Number.php#L132)):*
> ```PHP
>      *  The fallback symbols list
>      */
>     public function hydrateSymbols($numberingSystem, NumberSymbolList $fallbackSymbolList)
> ```

Why is this public?

---

*[src/PrestaShopBundle/Localization/Specification/NumberSymbolList.php, line 30 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L053hopR4mYYu38xk3i:-L053hopR4mYYu38xk3j:b-uzli18) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/src/PrestaShopBundle/Localization/Specification/NumberSymbolList.php#L30)):*
> ```PHP
> 
> /**
>  * Class NumberSymbolList
> ```

Redundant information

---

*[src/PrestaShopBundle/Localization/Specification/NumberSymbolList.php, line 173 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L054BQlXMfZChSQYqt1:-L054BQlXMfZChSQYqt2:b-sku855) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/src/PrestaShopBundle/Localization/Specification/NumberSymbolList.php#L173)):*
> ```PHP
>      *   Fluent interface
>      */
>     public function hydrate(NumberSymbolList $defaultList)
> ```

Why not set in the constructor?

---

*[src/PrestaShopBundle/Localization/Specification/Percentage.php, line 37 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L054MWwkW07O4mWNgAN:-L054MWwkW07O4mWNgAO:bfagg1o) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/src/PrestaShopBundle/Localization/Specification/Percentage.php#L37)):*
> ```PHP
>  * system (latin, arab, ...).
>  */
> class Percentage extends NumberSpecification
> ```

Is this a placeholder or is it supposed to be the same as NumberSpecification?

---

*[src/PrestaShopBundle/Tests/Localization/Specification/CurrencyTest.php, line 40 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L054iK5fNsH-f4b5Oet:-L054iK5fNsH-f4b5Oeu:b-c36m3w) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/src/PrestaShopBundle/Tests/Localization/Specification/CurrencyTest.php#L40)):*
> ```PHP
>     {
>         $this->numberSpec = new Currency();
>     }
> ```

There are no tests in this file

---

*[src/PrestaShopBundle/Tests/Localization/Specification/NumberTest.php, line 53 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L0556JoqiUgSHIiR4SQ:-L0556JoqiUgSHIiR4SR:bbjdzr2) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/src/PrestaShopBundle/Tests/Localization/Specification/NumberTest.php#L53)):*
> ```PHP
>      * (also tests addSymbols() at the same time)
>      */
>     public function testGetAllSymbols()
> ```

Try to name the test the same as the thing that you are asserting, so that makes a logical phrase. For example: "testGetAllSymbolsReturnsAListOfSymbols" -> "test get all symbols returns a list of symbols"

---

*[src/PrestaShopBundle/Tests/Localization/Specification/NumberTest.php, line 61 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L054tJYlnrbB3NJQTSw:-L054tJYlnrbB3NJQTSx:bufoe8w) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/src/PrestaShopBundle/Tests/Localization/Specification/NumberTest.php#L61)):*
> ```PHP
> 
>         $this->numberSpec->addSymbols('latin', $latinList);
>         $this->numberSpec->addSymbols('arab', $arabList);
> ```

I don't think specifications should be mutable

---

*[src/PrestaShopBundle/Tests/Localization/Specification/NumberTest.php, line 68 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L054z5hRvkpFZ4lNMFH:-L054z5hRvkpFZ4lNMFI:b-5y8d2l) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/src/PrestaShopBundle/Tests/Localization/Specification/NumberTest.php#L68)):*
> ```PHP
>                 'arab'  => $arabList,
>             ],
>             $this->numberSpec->getAllSymbols()
> ```

Is there a use case for getting all symbols at once?

---

*[src/PrestaShopBundle/Tests/Localization/Specification/PercentageTest.php, line 40 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L055gbnLryCOCJ4LhXh:-L055gbnLryCOCJ4LhXi:b-c36m3w) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/src/PrestaShopBundle/Tests/Localization/Specification/PercentageTest.php#L40)):*
> ```PHP
>     {
>         $this->numberSpec = new Percentage();
>     }
> ```

There are no tests in this file

---

*[tests/sf-tests.xml, line 26 at r3](https://reviewable.io: [...]

2017-12-11 15:51 UTC, LittleBigDev commented
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[src/PrestaShopBundle/Localization/Exception/Exception.php, line 29 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L050dBnKows1yevF6p0:-L05BJxkttO5ezT433GI:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/src/PrestaShopBundle/Localization/Exception/Exception.php#L29)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

While this is correct, I think that "LocalizationException" would be better.

I find that using simply "Exception" has two disadvantages:

1) When you read "throw Exception" in the code, you cannot know right away which kind of exception is being thrown.
2) When you start typing "throw Exc|" you'll have dozens of Exception on your autocomplete list.
</blockquote></details>

Done.

---

*[src/PrestaShopBundle/Localization/Exception/InvalidArgumentException.php, line 29 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L051TL2mdzXrdzcqoe4:-L05BL736ecrg6HnW0OY:b-2yptwh) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/src/PrestaShopBundle/Localization/Exception/InvalidArgumentException.php#L29)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

1) Unless you are targeting to catch a specific type of exception, don't over specify.
2) This exception does not extend `Localization\Exception\Exception`, which means that if you want to catch all exceptions thrown by Localization you need two separate `catch`.

The way I see it, typed exceptions should be used ONLY for targeted catching. If you want to send information, you should use the exception message.
</blockquote></details>

I'll simplify exceptions usage

---

*[src/PrestaShopBundle/Localization/Specification/Number.php, line 64 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L053vn4oKziEDnnsyAF:-L05BeQnu69678ZD5zxP:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/src/PrestaShopBundle/Localization/Specification/Number.php#L64)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Missing description. You should say that this is indexed by numbering system
</blockquote></details>

Done.

---

*[src/PrestaShopBundle/Localization/Specification/Number.php, line 116 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L052yiPH5aoEn2i63Zw:-L05BfzxClT6FEJz0iQv:b-eolvas) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/src/PrestaShopBundle/Localization/Specification/Number.php#L116)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Why not set everything in the constructor?
In which use case this class should be mutated?
</blockquote></details>

Number specification is built aggregating data from multiple sources. I think using yet another data object dedicated to aggregation would be overkill.
So, I implemented a way to extend / hydrate missing data inside this class (and also inside `NumberSymbolList` class, for the same reason).

---

*[src/PrestaShopBundle/Localization/Specification/Number.php, line 132 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L053R4yvIo4pGu9WBPv:-L05Ce64zEeqceOuqlTR:b6pfomm) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/src/PrestaShopBundle/Localization/Specification/Number.php#L132)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Why is this public?
</blockquote></details>

The factory / builder / manager class in charge for building the spec object will need to inject data for extension / hydration.

---

*[src/PrestaShopBundle/Localization/Specification/NumberSymbolList.php, line 173 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L054BQlXMfZChSQYqt1:-L05DBKFcn3a2IfShokc:b-j4l6qq) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/src/PrestaShopBundle/Localization/Specification/NumberSymbolList.php#L173)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Why not set in the constructor?
</blockquote></details>

Same reason as for `Number` spec class

---

*[src/PrestaShopBundle/Localization/Specification/Percentage.php, line 37 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L054MWwkW07O4mWNgAN:-L05DHdCC3VLoI8hOeRX:b-pn7fad) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/src/PrestaShopBundle/Localization/Specification/Percentage.php#L37)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Is this a placeholder or is it supposed to be the same as NumberSpecification?
</blockquote></details>

For business reason, I thought having a specific name for percentage spec was a good idea. But it works exactly the same. I didn't see anything different from vanilla number spec (only the number patterns are different because they contain an additional character : "%")

---

*[src/PrestaShopBundle/Tests/Localization/Specification/CurrencyTest.php, line 40 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L054iK5fNsH-f4b5Oet:-L05DlWhfrA4O0xqnRX4:b31c2dd) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/src/PrestaShopBundle/Tests/Localization/Specification/CurrencyTest.php#L40)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

There are no tests in this file
</blockquote></details>

As `CurrencyTest` extends `NumberTest`, the tests are ran again but this time with a Currency spec object. I want those tests to be green with any Number specification class.

---

*[src/PrestaShopBundle/Tests/Localization/Specification/NumberTest.php, line 61 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L054tJYlnrbB3NJQTSw:-L05EAaRa_-WPt8XgO9S:bhg08ek) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/src/PrestaShopBundle/Tests/Localization/Specification/NumberTest.php#L61)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

I don't think specifications should be mutable
</blockquote></details>

@see comments above addressing the same subject

---

*[src/PrestaShopBundle/Tests/Localization/Specification/NumberTest.php, line 68 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L054z5hRvkpFZ4lNMFH:-L05F9QNPgNS0xn-Fvjg:bpysaia) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/src/PrestaShopBundle/Tests/Localization/Specification/NumberTest.php#L68)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Is there a use case for getting all symbols at once?
</blockquote></details>

Sometimes when writing in a given language and expecting a specific numbering system, this numbering system is not available in CLDR data. I wanted to make sure there is a way to list all available symbol lists and pick one of them.
Though, this is very unlikely.... I think removing the method would be harmless. Your call.

---

*[src/PrestaShopBundle/Tests/Localization/Specification/PercentageTest.php, line 40 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L055gbnLryCOCJ4LhXh:-L05FqqS9QiGY7zhO0Yy:b1t8dg0) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/src/PrestaShopBundle/Tests/Localization/Specification/PercentageTest.php#L40)):*
<details><summary><i>Previously, eternoen [...]

2017-12-11 15:52 UTC, LittleBigDev commented
Review status: 5 of 9 files reviewed at latest revision, 14 unresolved discussions.

---

*[src/PrestaShopBundle/Localization/Specification/NumberSymbolList.php, line 30 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L053hopR4mYYu38xk3i:-L05Gj3Se3q2GyibnR8_:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/src/PrestaShopBundle/Localization/Specification/NumberSymbolList.php#L30)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Redundant information
</blockquote></details>

Done.

---

*[src/PrestaShopBundle/Tests/Localization/Specification/NumberTest.php, line 53 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L0556JoqiUgSHIiR4SQ:-L05GhsfP7szg_Te64jL:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/src/PrestaShopBundle/Tests/Localization/Specification/NumberTest.php#L53)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Try to name the test the same as the thing that you are asserting, so that makes a logical phrase. For example: "testGetAllSymbolsReturnsAListOfSymbols" -> "test get all symbols returns a list of symbols"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8581)*
<!-- Sent from Reviewable.io -->

2017-12-13 09:12 UTC, eternoendless commented
Reviewed 2 of 6 files at r4, 6 of 6 files at r5.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/PrestaShopBundle/Localization/Specification/Currency.php, line 58 at r5](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L0E7RuXbPTTL3ofW4z1:-L0E7RuXbPTTL3ofW4z2:b-1rkpuj) ([raw file](https://github.com/prestashop/prestashop/blob/15bf4096ac62f18cbbda77cdcbdd68c10287c332/src/PrestaShopBundle/Localization/Specification/Currency.php#L58)):*
> ```PHP
>     protected $currencyDisplay;
> 
>     public function __construct(
> ```

Missing parameters description

---

*[src/PrestaShopBundle/Localization/Specification/Currency.php, line 68 at r5](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L0E71jqgUrIVwQV4ufT:-L0E71jrvf9fh4llYzMl:b27b7bm) ([raw file](https://github.com/prestashop/prestashop/blob/15bf4096ac62f18cbbda77cdcbdd68c10287c332/src/PrestaShopBundle/Localization/Specification/Currency.php#L68)):*
> ```PHP
>         $secondaryGroupSize = null,
>         $currencyDisplay = null
>     ) {
> ```

You shouldn't use defaults on mandatory fields, otherwise you make it possible to create an incomplete entity

---

*[src/PrestaShopBundle/Localization/Specification/Number.php, line 39 at r5](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L0E7Txe_N6epT0wE1Gb:-L0E7Txe_N6epT0wE1Gc:b-1rkpuj) ([raw file](https://github.com/prestashop/prestashop/blob/15bf4096ac62f18cbbda77cdcbdd68c10287c332/src/PrestaShopBundle/Localization/Specification/Number.php#L39)):*
> ```PHP
> class Number
> {
>     public function __construct(
> ```

Missing parameters description

---

*[src/PrestaShopBundle/Localization/Specification/Number.php, line 48 at r5](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L0E7N2qlviL_r3Yskeu:-L0E7N2qlviL_r3Yskev:bxua2ae) ([raw file](https://github.com/prestashop/prestashop/blob/15bf4096ac62f18cbbda77cdcbdd68c10287c332/src/PrestaShopBundle/Localization/Specification/Number.php#L48)):*
> ```PHP
>         $primaryGroupSize = null,
>         $secondaryGroupSize = null
>     ) {
> ```

Same comment here, don't use default values on mandatory parameters

---

*[src/PrestaShopBundle/Localization/Specification/NumberSymbolList.php, line 149 at r5](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L0E7_RxRxKysI_dAdJb:-L0E7_RxRxKysI_dAdJc:b-1rkpuj) ([raw file](https://github.com/prestashop/prestashop/blob/15bf4096ac62f18cbbda77cdcbdd68c10287c332/src/PrestaShopBundle/Localization/Specification/NumberSymbolList.php#L149)):*
> ```PHP
>     protected $currencyGroup;
> 
>     public function __construct(
> ```

Missing parameters description

---

*[src/PrestaShopBundle/Localization/Specification/NumberSymbolList.php, line 161 at r5](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L0E7bye1WPAPIadXcAb:-L0E7bye1WPAPIadXcAc:b-6gcld2) ([raw file](https://github.com/prestashop/prestashop/blob/15bf4096ac62f18cbbda77cdcbdd68c10287c332/src/PrestaShopBundle/Localization/Specification/NumberSymbolList.php#L161)):*
> ```PHP
>         $infinity = null,
>         $nan = null
>     ) {
> ```

Same comment about mandatory parameters

---

*[src/PrestaShopBundle/Tests/Localization/Specification/NumberTest.php, line 68 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L054z5hRvkpFZ4lNMFH:-L05KKGukhLRIcr1OqYz:b-lzlhhz) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/src/PrestaShopBundle/Tests/Localization/Specification/NumberTest.php#L68)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Sometimes when writing in a given language and expecting a specific numbering system, this numbering system is not available in CLDR data. I wanted to make sure there is a way to list all available symbol lists and pick one of them.
Though, this is very unlikely.... I think removing the method would be harmless. Your call.
</blockquote></details>

I guess we can keep it

---

*[tests/sf-tests.xml, line 26 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L055vEevfcUP70SGzqn:-L0E8NXXJFmeIRBIKM-C:b-b30g73) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/tests/sf-tests.xml#L26)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

I agree. But I didn't dare touching it. We could give it a try, but is this the good moment to do it ?
</blockquote></details>

Please try in a separate PR and eventually rebase this one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8581)*
<!-- Sent from Reviewable.io -->

2017-12-13 09:13 UTC, eternoendless requested changes
Some changes required

2017-12-13 11:31 UTC, LittleBigDev commented
Here are my changes

---

Review status: 3 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/PrestaShopBundle/Localization/Specification/Currency.php, line 58 at r5](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L0E7RuXbPTTL3ofW4z1:-L0EPPCEZQ6lYtgGTj-9:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/15bf4096ac62f18cbbda77cdcbdd68c10287c332/src/PrestaShopBundle/Localization/Specification/Currency.php#L58)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Missing parameters description
</blockquote></details>

Done.

---

*[src/PrestaShopBundle/Localization/Specification/Currency.php, line 68 at r5](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L0E71jqgUrIVwQV4ufT:-L0EPNtL35Hu0UBl_A1R:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/15bf4096ac62f18cbbda77cdcbdd68c10287c332/src/PrestaShopBundle/Localization/Specification/Currency.php#L68)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

You shouldn't use defaults on mandatory fields, otherwise you make it possible to create an incomplete entity
</blockquote></details>

Done.

---

*[src/PrestaShopBundle/Localization/Specification/Number.php, line 39 at r5](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L0E7Txe_N6epT0wE1Gb:-L0EPR8pCiHMAd-26Mxp:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/15bf4096ac62f18cbbda77cdcbdd68c10287c332/src/PrestaShopBundle/Localization/Specification/Number.php#L39)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Missing parameters description
</blockquote></details>

Done.

---

*[src/PrestaShopBundle/Localization/Specification/Number.php, line 48 at r5](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L0E7N2qlviL_r3Yskeu:-L0EPSYYJLIF9ybYyvwT:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/15bf4096ac62f18cbbda77cdcbdd68c10287c332/src/PrestaShopBundle/Localization/Specification/Number.php#L48)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Same comment here, don't use default values on mandatory parameters
</blockquote></details>

Done.

---

*[src/PrestaShopBundle/Localization/Specification/NumberSymbolList.php, line 149 at r5](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L0E7_RxRxKysI_dAdJb:-L0EQU5IDVaONeh3Dten:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/15bf4096ac62f18cbbda77cdcbdd68c10287c332/src/PrestaShopBundle/Localization/Specification/NumberSymbolList.php#L149)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Missing parameters description
</blockquote></details>

Done.

---

*[src/PrestaShopBundle/Localization/Specification/NumberSymbolList.php, line 161 at r5](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L0E7bye1WPAPIadXcAb:-L0EUEPDhexqKQ56RlT0:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/15bf4096ac62f18cbbda77cdcbdd68c10287c332/src/PrestaShopBundle/Localization/Specification/NumberSymbolList.php#L161)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Same comment about mandatory parameters
</blockquote></details>

Done.

---

*[tests/sf-tests.xml, line 26 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L055vEevfcUP70SGzqn:-L0EUQ0ph9IxVDCpl4ls:b-2imphg) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/tests/sf-tests.xml#L26)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Please try in a separate PR and eventually rebase this one
</blockquote></details>

I tried and faced a lot of autoloading issues. I think we should think about moving the old "PrestaShop Bundle Test Suite" only for branches depending on the current develop branch (containing sf files migration, new files structure etc)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-:-L0Ed90tHcAdAORHFMoy:b2eyt8m)*
<!-- Sent from Reviewable.io -->

2017-12-14 15:28 UTC, eternoendless commented
Reviewed 6 of 6 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tests/sf-tests.xml, line 26 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L055vEevfcUP70SGzqn:-L0KcmbskNetiF8bdzQj:b-8yazjl) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/tests/sf-tests.xml#L26)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

I tried and faced a lot of autoloading issues. I think we should think about moving the old "PrestaShop Bundle Test Suite" only for branches depending on the current develop branch (containing sf files migration, new files structure etc)
</blockquote></details>

I'd prefer not to merge this until it's changed and this PR is rebased

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8581)*
<!-- Sent from Reviewable.io -->

2017-12-14 15:50 UTC, LittleBigDev commented
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tests/sf-tests.xml, line 26 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L055vEevfcUP70SGzqn:-L0Ki-Kn7G75mllpRNv1:b-b3zde6) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/tests/sf-tests.xml#L26)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

I'd prefer not to merge this until it's changed and this PR is rebased
</blockquote></details>

Ok, incomming.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8581)*
<!-- Sent from Reviewable.io -->

2018-01-03 10:38 UTC, eternoendless commented
Reviewed 6 of 6 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tests/sf-tests.xml, line 26 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L055vEevfcUP70SGzqn:-L1vaMDGXiJvBCmZmctH:bru8dc3) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/tests/sf-tests.xml#L26)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Ok, incomming.
</blockquote></details>

You forgot to delete this part which is no longer valid

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8581)*
<!-- Sent from Reviewable.io -->

2018-01-03 10:40 UTC, LittleBigDev commented
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tests/sf-tests.xml, line 26 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-L055vEevfcUP70SGzqn:-L1vaz-IjCtk-rdPN71c:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/a9e86aaadd3f3b19b3dffed45e7d1222cda0e050/tests/sf-tests.xml#L26)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

You forgot to delete this part which is no longer valid
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8581)*
<!-- Sent from Reviewable.io -->

2018-01-03 10:42 UTC, eternoendless commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8581#-:-L1vbFGKJmWwtqpyw720:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2018-01-03 10:42 UTC, eternoendless approved these changes

2018-01-03 13:20 UTC, eternoendless commented
Thank you @LittleBigDev

2018-01-03 13:20 UTC, merged