Fix the redirection after saving and deleting a features value
PrestaShop/PrestaShop pull request #8603
Opened 2017-12-11 11:30 UTC by Azouz-Jribi

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | When you try to edit or delete a feature value in the feature values list page , you will be redirected to the features list instead of the feature values list .
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-9639
| How to test?  | BO > Catalog > Product Features > View a feature and try to **edit** or **delete**, check if you will be redirected to the right list.

2017-12-11 13:17 UTC, metacreo approved these changes
Thank You! Good Work!

2017-12-11 15:15 UTC, LittleBigDev commented
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[controllers/admin/AdminFeaturesController.php, line 468 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8603#-L0581zYNwT6hYkoT8Xh:-L0581zZCcoVd1n6IbRZ:b-bvfsrd) ([raw file](https://github.com/prestashop/prestashop/blob/52afcb50c0f5fb37e7a4e6faa808a1ce3503c350/controllers/admin/AdminFeaturesController.php#L468)):*
> ```PHP
> 
>             if (Tools::getIsset('deletefeature_value')) {
>                 self::$currentIndex = self::$currentIndex . '&id_feature=' . (int)Tools::getValue('id_feature') . '&viewfeature';
> ```

Can't you use `Link::getAdminLink()` method when you need to add some parameters ?

---

*[controllers/admin/AdminFeaturesController.php, line 488 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8603#-L058FgQgzbIm5tOZVrf:-L058FgRgOGdNyAIXjKR:bnipkwr) ([raw file](https://github.com/prestashop/prestashop/blob/52afcb50c0f5fb37e7a4e6faa808a1ce3503c350/controllers/admin/AdminFeaturesController.php#L488)):*
> ```PHP
>             Hook::exec('displayFeatureValuePostProcess',
>                 array('errors' => &$this->errors));
>             $this->redirect_after = self::$currentIndex . '&id_feature=' . (int)Tools::getValue('id_feature') . '&viewfeature' . '&token=' . $this->token;
> ```

Same comment : please consider using `Link::getAdminLink()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8603)*
<!-- Sent from Reviewable.io -->

2017-12-11 15:16 UTC, LittleBigDev requested changes
Thanks @Azouz-Jribi. Please have a look at my comments above.

2017-12-11 15:58 UTC, Azouz-Jribi commented
*[controllers/admin/AdminFeaturesController.php, line 468 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8603#-L0581zYNwT6hYkoT8Xh:-L05HmWnFBbq4yh0FyH8:b4kr5st) ([raw file](https://github.com/prestashop/prestashop/blob/52afcb50c0f5fb37e7a4e6faa808a1ce3503c350/controllers/admin/AdminFeaturesController.php#L468)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Can't you use `Link::getAdminLink()` method when you need to add some parameters ?
</blockquote></details>

We can not use the `Link::getAdminLink()` when we need to add params, but we can redefine the method to accept parameters.
`Link :: getAdminLink ($ controller, $ with_token = true, params = array ())`

What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8603)*
<!-- Sent from Reviewable.io -->

2017-12-11 16:28 UTC, LittleBigDev commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[controllers/admin/AdminFeaturesController.php, line 468 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8603#-L0581zYNwT6hYkoT8Xh:-L05OgKXxRn_EFy6dFPO:b-dw842u) ([raw file](https://github.com/prestashop/prestashop/blob/52afcb50c0f5fb37e7a4e6faa808a1ce3503c350/controllers/admin/AdminFeaturesController.php#L468)):*
<details><summary><i>Previously, Azouz-Jribi wrote…</i></summary><blockquote>

We can not use the `Link::getAdminLink()` when we need to add params, but we can redefine the method to accept parameters.
`Link :: getAdminLink ($ controller, $ with_token = true, params = array ())`

What do you think?
</blockquote></details>

Sorry, I thought 1.6 version of `Link::getAdminLink()` was able to handle a `$params`.  If not, then your solution is ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8603#-:-L05Ozz-JU-K2DYV-opJ:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2017-12-11 16:28 UTC, LittleBigDev approved these changes
Thank you @Azouz-Jribi

2018-02-05 10:47 UTC, prasanthSelvar commented
Hello @Azouz-Jribi,

I still have the issue with your fix.
When I save I am still redirect to features list.

2018-02-06 13:56 UTC, Azouz-Jribi commented
Hi @prasanthSelvar 
It works well for me, try to clear cache please.

The steps to test it : 
1- BO > Catalog > Product Features.
2- Selecte the **Styles** list for example.
3- Try to edit the **Classic** value.
4- Save and check if if you will be redirected to the **Styles** values list.

Thanks ;)

2018-02-06 14:12 UTC, prasanthSelvar commented
@Azouz-Jribi it's works when I clear cache.
Thank you!

2019-09-05 15:58 UTC, matks commented
Hello,

I'm sorry but PrestaShop 1.6 support ended on June 30, 2019, consequently this PR will not be merged into the project.
Thank you for your contribution.

Please note that if a critical issue is discovered, there is a dedicated GitHub repository: https://github.com/PrestaShop/PrestaShop-1.6 maintained by a team of volunteers.
From this repository, it will be possible to submit pull requests in order to fix critical issues.

You can read more about it on http://build.prestashop.com/news/1.6.1.x-what-s-next/

2019-09-05 15:58 UTC, closed without merging