Prevent iframe embedding by default
PrestaShop/PrestaShop pull request #8807
Opened 2018-02-26 16:05 UTC by eternoendless

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.3.x
| Description?  | Currently it's possible to embed a PrestaShop instance in an iframe, which exposes it to click-jacking attacks. This PR makes iframe embedding from another domain disabled by default.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-4917
| How to test?  | Put your shop's URL here: http://savanttools.com/test-frame/

2018-02-26 16:08 UTC, pehelwan commented
Can you request a CVE or I shall do the same ?

2018-03-05 13:07 UTC, LittleBigDev commented
Something is wrong with travis. Missing html elements.

2018-03-05 13:09 UTC, LittleBigDev commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8807#-:-L6qGsB3niCH1s16F8ve:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2018-03-14 13:51 UTC, LittleBigDev commented
Rebase needed

2018-03-14 14:10 UTC, kpodemski commented
hey @eternoendless 

what about all demos on Addons? :P

2018-03-14 14:25 UTC, eternoendless commented
Oh thanks @kpodemski I hadn't thought of that 

🤔 

Maybe we shoud add an option to configure the allowed domains somewhere in the BO.

2018-08-21 14:38 UTC, jolelievre commented
has this been forgotten? or is it purposely ignored?

2018-08-21 14:40 UTC, pehelwan commented
I have blogged about it on Dzone go ahead and read it. I will push a commit
soon, thereby avoiding this scenario

On Tue, 21 Aug 2018, 8:09 pm jolelievre, <notifications@github.com> wrote:

> has this been forgotten? or is it purposely ignored?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/PrestaShop/PrestaShop/pull/8807#issuecomment-414697550>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgQoVCT5BUld8HFP2nEp1tz6UJkSwIPJks5uTBuHgaJpZM4STfEW>
> .
>

2018-08-21 14:43 UTC, payloadartist approved these changes
The CSP and X-Frame-Options headers successfully block this attack from happening.

2018-08-21 14:53 UTC, jolelievre commented
yes but from what I understand it is not that simple as the demos on Addons need to display PrestaShop in a frame, so we can't block it all the time

2018-08-21 14:55 UTC, pehelwan commented
Can you elaborate?

On Tue, 21 Aug 2018, 8:24 pm jolelievre, <notifications@github.com> wrote:

> yes but from what I understand it is not that simple as the demos on
> Addons need to display PrestaShop in a frame, so we can't block it all the
> time
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/PrestaShop/PrestaShop/pull/8807#issuecomment-414703254>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgQoVKrIcShq2eM6C_xrTSp5AVrZ52VEks5uTB8MgaJpZM4STfEW>
> .
>

2018-08-21 14:56 UTC, pehelwan commented
Or you might as well want to implement a back end functionality which might
allow the Administrator user to change the frame or CSP permissions as per
feasibility if that's what you hinted at?

On Tue, 21 Aug 2018, 8:24 pm A Khan, <durgapurite@gmail.com> wrote:

> Can you elaborate?
>
> On Tue, 21 Aug 2018, 8:24 pm jolelievre, <notifications@github.com> wrote:
>
>> yes but from what I understand it is not that simple as the demos on
>> Addons need to display PrestaShop in a frame, so we can't block it all the
>> time
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/PrestaShop/PrestaShop/pull/8807#issuecomment-414703254>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AgQoVKrIcShq2eM6C_xrTSp5AVrZ52VEks5uTB8MgaJpZM4STfEW>
>> .
>>
>

2018-08-21 15:00 UTC, jolelievre commented
Yes, I think that's what @eternoendless suggested, it should be configurable it the BO
Maybe the default value would be to block any frame, but this could be overriden by a specified allowed domain
I lack knowledge about the addons platform actually, so I am not totally sure

2018-08-21 15:03 UTC, pehelwan commented
Sure , the Administrator can simply change the nginx conf just for that ,
generally speaking things or frameworks as well as applications come out of
the box with this security feature enabled by default which should be done
in case of prestashop as well. That again emphasises on security by default
and enforced strictly.

On Tue, 21 Aug 2018, 8:30 pm jolelievre, <notifications@github.com> wrote:

> Yes, I think that's what @eternoendless <https://github.com/eternoendless>
> suggested, it should be configurable it the BO
> Maybe the default value would be to block any frame, but this could be
> overriden by a specified allowed domain
> I lack knowledge about the addons platform actually, so I am not totally
> sure
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/PrestaShop/PrestaShop/pull/8807#issuecomment-414705691>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgQoVLCyQbJIoBCKSlbZKQBEg21iyJCAks5uTCCYgaJpZM4STfEW>
> .
>

2018-11-26 10:14 UTC, Quetzacoalt91 requested changes

2018-11-26 10:14 UTC, Quetzacoalt91 commented on classes/Tools.php
> +        fwrite($write_fd, "Header append X-Frame-Options SAMEORIGIN\n\n");
This should be surrounded by `<IfModule mod_headers.c>`, which already exist in this .htaccess.

Please move these lines further in the method, as all environment does not have the "header" module enabled (for instance, the docker images).

2018-12-17 11:10 UTC, molearnik commented
I'd strongly recommend to think about adding "Security Enhancements" link to e.g. BO/Configure/Advanced Parameters/Security Enhancements where Administrator could enable HTTP response headers like:
```
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff 
X-XSS-Protection: "1; mode=block" 
Strict-Transport-Security "max-age=31536000; includeSubDomains" 
Cache-Control: no-cache='set-cookie'
```
Vulnerability scanners complain about omission of these headers by default. 
Sure, PrestaShop Administrators could do that by tweaking their web servers configurations.
However, 
1. That requires some technical knowledge and it is less convenient
2. .htaccess mechanism is not recommended for performance reasons (https://www.nginx.com/resources/wiki/start/topics/examples/likeapache-htaccess/#)
3. Adding these optional headers from PrestaShop code would be cleaner and web server agnostic.
4. You could turn this into advantage over competition.
5. You could add additional security enhancement to the prestashop pages e.g. this script fragment:
https://www.owasp.org/index.php/Clickjacking_Defense_Cheat_Sheet#Best-for-now_Legacy_Browser_Frame_Breaking_Script

Regarding demonstrating AddOns: PrestaShop websites used for demonstration purposes could have some security options disabled (should the "X-Frame-Options: SAMEORIGIN" break the demo).

2019-10-22 08:55 UTC, marionf commented
@eternoendless 

Does this PR is still relevant ?

2020-04-08 12:59 UTC, matks commented
@PierreRambaud I think we should update this PR in the scope of our security reinforcement for PrestaShop

2021-03-02 15:54 UTC, PierreRambaud commented
> @PierreRambaud I think we should update this PR in the scope of our security reinforcement for PrestaShop

Woot didn't see this notification.
I'm not sure it should be handle by PrestaShop installation, but why the host configuration. Otherwise we will not be able to use demo.prestashop.com anymore :roll_eyes:

2021-03-12 16:34 UTC, eternoendless commented
Like [I said before](https://github.com/PrestaShop/PrestaShop/pull/8807#issuecomment-373039420):

> Maybe we should add an option to configure the allowed domains somewhere in the BO.

I'm closing this PR out of staleness, but @PierreRambaud as @matks said, this is something that could be done as a security feature.

2021-03-12 16:34 UTC, closed without merging