Replace Open Sans font with Vazir font for Farsi (BO default theme)
PrestaShop/PrestaShop pull request #8836
Opened 2018-03-10 16:11 UTC by mehrshadz

Replace Open Sans font with Vazir font (v18.0.0) for Farsi language + copyright licence (Apache v2)

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Replace Open Sans font with Vazir font (v18.0.0) for Farsi language + copyright licence (Apache v2).
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | https://trello.com/c/FI0ri5Ev/1-fonts
| How to test?  | Install a fresh PrestaShop with this RTL Fix file and check BO (default theme)

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

2018-03-13 13:52 UTC, eternoendless requested changes
Same comments as https://github.com/PrestaShop/PrestaShop/pull/8837#pullrequestreview-103435605

2018-03-26 06:47 UTC, mehrshadz reviewed
CDN urls changed and copyrights removed

2018-04-05 09:48 UTC, eternoendless submitted a review, later dismissed

2018-04-13 09:28 UTC, eternoendless approved these changes

2018-04-13 13:24 UTC, eternoendless commented
Thank you @mehrshadz

2018-04-13 13:25 UTC, merged