Add new hook actionModuleUninstall before and after module uninstall
PrestaShop/PrestaShop pull request #8868
Opened 2018-03-22 10:01 UTC by Nermendis

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add new hook actionModuleUninstall before and after module uninstall
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -

2018-03-22 13:49 UTC, mickaelandrieu commented
Hi @Nermendis,

thanks for your contribution!

I'm not opposed to the addition of new hooks. What is your need? What problems can be solved with this new hooks? Also, they need to be registered both in `hooks.xml` and `1.7.4.sql` files.

You can take a look at this [commit](https://github.com/PrestaShop/PrestaShop/pull/8368/commits/de53956a7e69795a84b365272a0a42af23040ee0) for an example.

Mickaël

2018-03-22 13:50 UTC, mickaelandrieu requested changes
Need update of both xml and sql files

2018-03-22 13:50 UTC, mickaelandrieu commented on classes/module/Module.php
> +        Hook::exec('actionModuleUninstallBefore', array('object' => $this));
new hooks need to be registered in hooks.xml and 1.7.4.0.sql file

2018-03-28 16:08 UTC, Quetzacoalt91 commented
Hmm, I added Symfony events after these actions on modules, I wonder if we should add hooks as well.

It depends if the module can use the Symfony events. @mickaelandrieu?

2018-03-28 16:43 UTC, mickaelandrieu commented
@Quetzacoalt91 not for now, as during the build of container Symfony may not be aware of classes autoloaded by your modules.

It will be available in 1.7.5 maybe.

2018-09-04 16:26 UTC, Quetzacoalt91 commented
Okay, let's do this like the hooks related to module installation.

@Nermendis can you please take some time to add the new hooks to the list as @mickaelandrieu requested?

2020-05-06 09:14 UTC, matks commented
@Nermendis Sorry for late answer. It seems you have deleted your repository so I cannot retrieve the branch, but I have re-created a PR for you https://github.com/PrestaShop/PrestaShop/pull/18997

I will credit you

2020-05-06 09:14 UTC, closed without merging