Check the pagination of product in the Front Office
PrestaShop/PrestaShop pull request #8881
Opened 2018-03-26 13:21 UTC by hadrich-hatem

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.3.x
| Description?  | This PR allows to : Edit the number of product per page. Disable the friendly URL in the Back Office. Check the pagination of product in the Front Office. Enable the friendly URL in the Back Office.
| Type?         | improvement
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-4847
| How to test?  | Run this script path=full/02_product/10_check_pagination_of_product_in_FO.js npm run specific-test -- --URL=BackOfficeURL

2018-03-26 14:05 UTC, fatmaBouchekoua requested changes

2018-03-26 14:05 UTC, fatmaBouchekoua commented on tests/E2E/test/campaigns/common_scenarios/product.js
> +    let selectorButton = buttonName === 'Next'? productPage.pagination_next : productPage.pagination_previous;
A little space after 'Next'

2018-03-26 14:41 UTC, hadrich-hatem commented on tests/E2E/test/campaigns/common_scenarios/product.js
> +    let selectorButton = buttonName === 'Next'? productPage.pagination_next : productPage.pagination_previous;
I added a space after 'Next'

2018-03-26 15:21 UTC, fatmaBouchekoua submitted a review, later dismissed

2018-03-28 15:24 UTC, Quetzacoalt91 commented on tests/E2E/test/campaigns/common_scenarios/product.js
> +        .then(() => client.clickPageNextOrPrevious(selectorButton))
Reported by Codacy, a `;` is missing here.

2018-03-30 13:45 UTC, hadrich-hatem commented
Hello @Quetzacoalt91,
I have added the missing semicolon.
Thanks for your review.

2018-04-03 11:16 UTC, mickaelandrieu approved these changes

2018-04-03 11:16 UTC, merged

2018-04-03 11:16 UTC, mickaelandrieu commented
Thanks @hadrich-hatem !