Improve PrestaShopBundle config structure
PrestaShop/PrestaShop pull request #8885
Opened 2018-03-26 18:54 UTC by sarjon

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR aims to improve structure of PrestaShopBundle config
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | Everything should work the same as it was before this PR.

When working on migration I noticed that it is kind of a mess in config/ directory.
Example: 
_admin/_  directory - has admin routing + services + application config  (navigation.yml).
_api/_  directory - again routing configuration, but for api only
_adapter/_  directory - adapter services only

This can still be improved by grouping services into related files.

Root config before:
![before](https://user-images.githubusercontent.com/15143151/37926428-00d823ee-3140-11e8-97fe-d8d6096ad376.png)

Root config after:
![after](https://user-images.githubusercontent.com/15143151/37926439-07f756b8-3140-11e8-966c-e9cdc0b4b901.png)

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/8885)

2018-03-26 18:54 UTC, sarjon commented
what do you think @mickaelandrieu ?

2018-03-26 19:21 UTC, mickaelandrieu commented
I think I wanted to do it since months :)

2018-03-26 19:23 UTC, mickaelandrieu requested changes
only 1 comment then LGTM

2018-03-26 19:23 UTC, mickaelandrieu commented on src/PrestaShopBundle/Resources/config/services/form_services.yml
> +    - { resource: form/form_extension.yml }
misses an extra line at the end of file :)

2018-03-27 06:30 UTC, sarjon commented
done @mickaelandrieu :)

2018-03-27 06:30 UTC, sarjon commented on src/PrestaShopBundle/Resources/config/services/form_services.yml
> +    - { resource: form/form_extension.yml }
done @mickaelandrieu

2018-03-27 08:42 UTC, mickaelandrieu approved these changes

2018-03-27 08:43 UTC, mickaelandrieu commented
Thank you @sarjon,

ping @PrestaShop/prestashop-core-dev for information :)

2018-03-27 08:43 UTC, merged

2018-03-27 09:10 UTC, LittleBigDev commented
:+1: