Create missing subfolders in folder override/classes
PrestaShop/PrestaShop pull request #8998
Opened 2018-04-27 11:20 UTC by dariusakafest

Overload does not work for classes from a folder checkout

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Overload does not work for classes from a folder
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Add override class from folder checkout in module, install module

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/8998)

2018-05-02 15:41 UTC, Quetzacoalt91 requested changes

2018-05-02 15:41 UTC, Quetzacoalt91 commented on override/classes/checkout/index.php
> +
Be careful, the PHP file must start with `<?php`, here we have an empty line

2018-05-02 16:04 UTC, Quetzacoalt91 submitted a review, later dismissed

2018-05-02 16:24 UTC, Quetzacoalt91 commented
Hi @dariusakafest,

Some of your `index.php` files needed to be modified. I decided to merge all your different PRs in one to trigger only one build and accelerate the whole validation process.

Thanks for your understanding.

2018-05-02 16:25 UTC, Quetzacoalt91 approved these changes

2018-05-02 17:06 UTC, merged

2018-05-04 10:17 UTC, dariusakafest commented
@Quetzacoalt91 good)