FO : Compare rewrite to link_rewrite + ean13 if present
PrestaShop/PrestaShop pull request #9015
Opened 2018-04-30 13:49 UTC by MatthieuMota

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | If we define ean13 for product, it is added to url so change combination with select for example, query to product with attribute redirect to default attribute because compare rewrite and link_rewrite from product. But we need to merge link_rewrite + ean13 in case of.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Just add a product with EAN13 and combination and try to change combination, not work.

2018-05-03 08:22 UTC, mickaelandrieu requested changes

2018-05-03 08:22 UTC, mickaelandrieu commented on controllers/front/ProductController.php
> +            if ($this->product->ean13) {
I'd prefer:

```diff
- if ($this->product->ean13) {
+ if (!empty($this->product->ean13)
```
The result is the same, but for the people who read this code the first time, they understand that "ean" is not a boolean but probably a string.

2018-05-03 16:49 UTC, MatthieuMota commented on controllers/front/ProductController.php
> +            if ($this->product->ean13) {
I agree with that. I've edited file.

2018-05-03 18:46 UTC, mickaelandrieu commented
Thanks @MatthieuMota

2018-05-03 18:47 UTC, mickaelandrieu approved these changes

2018-05-04 12:55 UTC, marionf commented
Hello @MatthieuMota 
In which version do you have this issue ?
It has been solved in 1.7.3.1 by this PR: https://github.com/PrestaShop/PrestaShop/pull/7775
And I can't reproduce this issue in develop branch

2018-05-05 09:32 UTC, MatthieuMota commented
Hey @marionf 
Indeed, I confirm that it work's when I update Prestashop :)

2018-05-07 07:31 UTC, marionf commented
Ok, thanks for your feedback @MatthieuMota 
I am closing this PR

2018-05-07 07:31 UTC, closed without merging