Fix HookConfigurator: Filter certain non-arrays from theme.yml
PrestaShop/PrestaShop pull request #9050
Opened 2018-05-10 20:15 UTC by jsshandle

Themes created with PrestaBuilder can lead to the following errors:

```
PHP Warning:  array_merge(): Argument #1 is not an array in /var/www/html/src/Core/Module/HookConfigurator.php on line 115
PHP Warning:  in_array() expects parameter 2 to be array, null given in /var/www/html/src/Core/Module/HookConfigurator.php on line 67
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/src/Core/Module/HookConfigurator.php on line 80
```

This is caused by certain empty properties in the related ``theme.yml``, which might look like this:

```
  hooks:
    modules_to_hook:
      ...
      displayFooterBefore:
        - ps_emailsubscription
        - ps_socialfollow
      displayAfterBodyOpeningTag:
      displayBeforeBodyClosingTag:
      displayFooter:
        - ps_linklist
      ...
```

This pull request fixes the issue by filtering the offending items from ``modules_to_hook``. 

Possibly related forum post: https://www.prestashop.com/forums/topic/667167-template-install-error/.

2018-05-10 20:50 UTC, PierreRambaud commented on src/Core/Module/HookConfigurator.php
> +        $hooks = array_filter($hooks, "is_array");
Can you use single quote instead of double :)

2018-05-10 21:19 UTC, PierreRambaud approved these changes

2018-05-15 15:38 UTC, mickaelandrieu commented
I'm more in favor of fixing the `theme.yml` than hide the error.

How about:

```yaml
# theme.yml
  hooks:
    modules_to_hook:
      ...
      displayFooterBefore:
        - ps_emailsubscription
        - ps_socialfollow
      displayAfterBodyOpeningTag: []
      displayBeforeBodyClosingTag: []
      displayFooter:
        - ps_linklist
      ...
```

2018-05-15 15:41 UTC, mickaelandrieu requested changes
Let's add a validator of theme configuration instead, and throw an exception if a hook is declared in `hook_to_modules` section without any modules hooked.

2018-05-16 15:48 UTC, jsshandle commented
In principal, I agree with you @mickaelandrieu. Definitely, PrestaBuilder needs a fix and should omit the offending empty properties in the ``theme.yml``.
However, the idea behind this pull request is to let PrestaShop handle existing malformed ``theme.yml`` more graciously. The suggested validator is pointing in the opposite direction and would enforce a stricter handling of the theme configuration, which can be a valid approach. The gracious equivalent of a validator would be a theme configuration loader which ensures that the ``theme.yml`` is loaded digestible for the components further down the line.
What are your thoughts @mickaelandrieu? Grace or strictness?

2018-05-16 15:55 UTC, mickaelandrieu commented
> What are your thoughts @mickaelandrieu? Grace or strictness?

Difficult choice... I'd say strictness "but" give meaningful information to allow developers to fix it.

There is so much "grace" in PrestaShop already, so many bugs we hide to ease the experience, I can tell this is not the right choice.

In an ideal world, I'd have time to provide one right now... but now, I don't have the time and this contribution is better than letting a useless error (for PrestaShop developers) being thrown.

So I'm changing my mind, and I'll try to have more time to think about it later :)

2018-05-16 15:55 UTC, mickaelandrieu approved these changes

2018-05-16 16:41 UTC, jsshandle commented
The error is reproducable with the following change in the classic ``theme.yml``:

Replace

```
      displaySearch:
        - ps_searchbar
      displayProductAdditionalInfo:
        - ps_sharebuttons
```

with

```
      displaySearch:
      displayProductAdditionalInfo:
        - ps_sharebuttons
```

For reference see [error.log.zip](https://github.com/PrestaShop/PrestaShop/files/2010001/error.log.zip) and [theme.yml.zip](https://github.com/PrestaShop/PrestaShop/files/2010002/theme.yml.zip).

2018-05-21 21:08 UTC, mickaelandrieu commented
@jsshandle also, shouldn't you inform PrestaBuilder that the YAML configuration file they generate is wrong? It's not up to the core to fix errors from 3rd party software.

2018-05-21 21:09 UTC, merged

2018-05-25 01:28 UTC, jsshandle commented
Thanks for merging @mickaelandrieu.

I just informed PrestaBuilder about this issue.

2018-05-25 09:54 UTC, andrejstas commented
@jsshandle Thank you for pointing out this problem! :)

I just fixed it on Prestabuilder