Bad link in breadcrumbs in symfony pages
PrestaShop/PrestaShop pull request #9051
Opened 2018-05-11 07:19 UTC by PierreRambaud

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.4.x
| Description?  | Some pages migrated on symfony, have parent breadcrumbs who are returning 404
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-5504
| How to test?  | Go to symfony pages and navigate with breadcrumb..

2018-05-11 07:42 UTC, jocel1 commented
why not adding an extra schema.org markup as well? (see example 2: https://developers.google.com/search/docs/data-types/breadcrumb)

2018-05-11 07:56 UTC, PierreRambaud commented
It's a little overkill for a backoffice, only administrators can access this part, so google search will never parse this one.

2018-05-11 07:57 UTC, jocel1 commented
ah yes, that's true symfony page are backoffice only right now =)

2018-05-11 10:21 UTC, eternoendless requested changes

2018-05-11 10:21 UTC, eternoendless commented on admin-dev/themes/new-theme/template/page_header_toolbar.tpl
> +    <ol class="breadcrumb">
While I think that making the breadcrumb an `<ol>` is a good idea, I think it should still be surrounded by a `<nav>` tag.

I'll [update the UI kit](https://cdn.rawgit.com/PrestaShop/prestashop-ui-kit/master/index.html#breadcrumb) accordingly.

2018-05-14 15:12 UTC, eternoendless approved these changes

2018-05-14 15:12 UTC, eternoendless commented
Note to QA: disregard style issues (if any), I'm on it

2018-05-14 17:23 UTC, eternoendless commented
Thank you @PierreRambaud

2018-05-14 17:23 UTC, merged