Dispatcher: Get request URI from Symfony's Request
PrestaShop/PrestaShop pull request #9065
Opened 2018-05-13 11:12 UTC by michaelKaefer

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Refactored method and mainly: get request URI from Symfony's request object. It's more reliable and future proof. I really like the idea to "get rid of the home-made framework which is not our core business features" from http://build.prestashop.com/news/prestashop-1-7-and-symfony/. Hope this is ok. Are there plans to rebuild the Dispatcher class with Symfony components by the way?
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | -

2018-05-15 08:19 UTC, mickaelandrieu commented on classes/Dispatcher.php
> -    protected function setRequestUri()
we can't change the definition and visibility of a function if it can be used/reused by another piece of code, this would force us to release PrestaShop 1.8 :trollface: 

This is what you can do when you want to improve a function:
* create your own - let's say `setRequestUriFromGolbals` (and you can inject Symfony Request as dependency, good idea!)
* use this function instead of the current one everywhere in PrestaShop code
* deprecate the current one for the latest release

This is boring work, but this ensure we don't break nothing for 1.7 users and developers :)

Let me know if you need more information, I agree for the changes you want to introduce and we will merge it if we can ;)

Good job!

2018-05-15 08:20 UTC, mickaelandrieu requested changes
minor changes to keep backward compatibility

2018-05-15 12:54 UTC, michaelKaefer commented on classes/Dispatcher.php
> -    protected function setRequestUri()
@mickaelandrieu Thanky you ver much for your information! I will do it the next time :)

2018-05-15 18:12 UTC, michaelKaefer commented
@mickaelandrieu It took me quite some hours to think about about your points Thanks again! Is it better now? I took your approach but added some things. The old method is still used but as a wrapper around the new one which collects the dependencies (which now gets all dependencies injected and is easy to test for the most part). And the Request now is available to the whole dispatcher (which could be really cool for other things).

2018-05-15 22:40 UTC, mickaelandrieu approved these changes

2018-05-15 22:44 UTC, mickaelandrieu commented
Thanks, it's good to me.

I have the feeling you really enjoy to contribute, if you want I can help/mentor you on something really great we are working on, like migrate pages from back office in Symfony or refactoring of some parts.

You'll learn a lot if you plan to make PrestaShop 1.7 websites/modules/themes.

Let me know if you're interested, we can talk about it when you're available for 👍

2018-05-15 22:44 UTC, merged

2018-05-16 19:46 UTC, michaelKaefer commented
@mickaelandrieu Thanks for merging! - And, yes, definitly, of course I am interested :+1: But how does it work? What can I do?

2018-05-16 22:44 UTC, mickaelandrieu commented
you can contact me using the gitter of PrestaShop in general channel and talk about what you may want to do https://gitter.im/PrestaShop/General

2018-05-18 13:27 UTC, mickaelandrieu commented
or by mail mickael [dot ] andrieu [at] prestashop [dot] com