Check if key exists before checking the value
PrestaShop/PrestaShop pull request #9105
Opened 2018-05-22 13:48 UTC by andypieters

Got some complaints from our customers about this.
Our plugin manages a 'fee'  product, but when we try to delete the product, a notice is show.
It seems like you should check if the value is set before checking what the value is.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | Use the "develop" branch if you target the next major version of PrestaShop 1.7, "1.7.4.x" for 1.7 bug fixes, and "1.6.1.x" for PrestaShop 1.6 (bugfixes only).
| Description?  | Please be specific when describing the PR. <br/> Every detail helps: versions, browser/server configuration, specific module/theme, etc.
| Type?         | bug fix / improvement / new feature
| Category?     | See [the Category list](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message#Howtowriteacommitmessage-Category), i.e.: BO
| BC breaks?    | Does it break backward compatibility? yes/no
| Deprecations? | Does it deprecate an existing feature? yes/no
| Fixed ticket? | (optional) If this PR fixes a [Forge](http://forge.prestashop.com/) ticket, please add its complete Forge URL.
| How to test?  | Please indicate how to best verify that this PR is correct.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!

2018-05-22 13:56 UTC, Quetzacoalt91 approved these changes

2018-05-22 14:00 UTC, Quetzacoalt91 commented
Hi @andypieters,

Would you mind filling the description table? They are used to classify the contributions on the project.
Thanks!

2018-05-22 14:15 UTC, PierreRambaud submitted a review, later dismissed

2018-05-24 14:20 UTC, Quetzacoalt91 requested changes
@andypieters it seems your fix may hide another issue. Can you please have a look at my code and confirm it also fixes the issue?

Thanks

2018-05-24 14:20 UTC, Quetzacoalt91 commented on classes/Cart.php
> +        if (isset($preservedGifts[$id_product.'-'.$id_product_attribute]) && $preservedGifts[$id_product.'-'.$id_product_attribute] > 0) {
Actually, a better would be a integer cast of the variable $id_product_attribute. The `isset()` here may prevent us to get the gifts in some case, although it exists.

```php
        $preservedGifts = $this->getProductsGifts($id_product, $id_product_attribute);
        if ($preservedGifts[$id_product.'-'. (int)$id_product_attribute] > 0) {
            return Db::getInstance()->execute(
                'UPDATE `'._DB_PREFIX_.'cart_product`
                SET `quantity` = '.(int)$preservedGifts[$id_product.'-'.(int)$id_product_attribute].'
                WHERE `id_cart` = '.(int)$this->id.'
                AND `id_product` = '.(int)$id_product.
                ($id_product_attribute != null ? ' AND `id_product_attribute` = '.(int)$id_product_attribute : '')
            );
        }
```

This caused by the default value `NULL` in the function parameters, although we expect a integer...
BTW, why the method `getProductsGifts` return an array while a integer would be enough.

2018-05-25 09:16 UTC, andypieters commented
@Quetzacoalt91 Yes this fixes it too.
I've updated the pull request

2018-05-25 09:46 UTC, Quetzacoalt91 approved these changes

2018-05-28 16:21 UTC, marionf commented
@eternoendless 1.7.4.1 ?

2018-06-05 01:32 UTC, mickaelandrieu commented
Thanks @andypieters !

Ping @eternoendless, let me know if this need to be cherry-picked

2018-06-05 01:32 UTC, merged