Restructure and rename admin controller
PrestaShop/PrestaShop pull request #9159
Opened 2018-06-02 07:40 UTC by michaelKaefer

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Rename and restructure according to https://github.com/PrestaShop/prestafony-project/blob/master/docs/migration-guide.md under headline "Modern/Symfony Controllers"
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | -

2018-06-04 00:36 UTC, mickaelandrieu commented
You're right... but as we have already published this page in 1.7.3 (I guess?) I don't know if we have the right to move the classes this way

2018-06-04 14:41 UTC, mickaelandrieu submitted a review, later dismissed

2018-06-04 19:02 UTC, michaelKaefer commented
@mickaelandrieu thank you!

2018-06-06 06:26 UTC, PierreRambaud requested changes
The new name is redundant, `Modules\ModuleCatalog`, can be a simple `Modules\Catalog`. It's like having `Grid\GridRow`, `Grid\GridColumn` which can be renamed in `Grid\Row` and `Grid\Column`.
But I approved the restructuring! :+1:

2018-06-06 08:23 UTC, mickaelandrieu commented
@PierreRambaud make sense! One more update @michaelKaefer :) 2 things are really hard in programming: managing the cache, and naming things 🤣

2018-06-06 21:02 UTC, mickaelandrieu commented
Edit: thinking about it, should we update [ThemeCatalogController](https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeCatalogController.php) to CatalogController into "Design" namespace @PierreRambaud?

2018-06-07 07:51 UTC, PierreRambaud commented
Yep good idea :)

2018-06-07 08:21 UTC, mickaelandrieu commented
One more "First contribution" issue then, don't do it!

2018-06-07 11:02 UTC, michaelKaefer commented
@mickaelandrieu What is a "First contribution" issue?

2018-06-17 12:48 UTC, michaelKaefer commented
@PierreRambaud @mickaelandrieu I removed the redundant name, thank you

2018-06-18 07:56 UTC, PierreRambaud commented on src/PrestaShopBundle/Controller/Admin/Improve/Modules/ModuleCatalogController.php
> +namespace PrestaShopBundle\Controller\Admin\Improve\Modules;
You forgot to rename file name :) still ModuleCatalogController.php :)

2018-06-18 20:29 UTC, michaelKaefer commented
@PierreRambaud Thank you! I fixed this stupid mistake of mine!

2018-06-18 20:51 UTC, PierreRambaud submitted a review, later dismissed

2018-06-26 07:18 UTC, PierreRambaud commented
Hum, look like there is something weird with commits list. Did you target the good branch?

2018-06-27 07:06 UTC, michaelKaefer commented
That was me. Hope I can fix it next monday!

2019-07-11 15:07 UTC, PierreRambaud commented
I'm closing this Pull request since the source is an unknow repository and this is in waiting for rebase since one year.

2019-07-11 15:07 UTC, closed without merging