add casting operation because of scalar / array casting error
PrestaShop/PrestaShop pull request #9217
Opened 2018-06-26 15:09 UTC by Shopmonauten

We got an error with current PS Version 1.7.3.3:
"Cannot use a scalar value as an array" in line 3948 of the Tools.php
the values were

array('amount' => '2.2204460492503E-16', 
	'precision' => '2', 
	'rows' => array('0.95'), 
	'column' => 'id_tax', 
	'sort_function' => 'lambda_1', 
	'unit' => '100', 
	'int_amount' => '0', 
	'remainder' => '0', 
	'amount_to_spread' => '0', 
	'sign' => '1', 
	'position' => '0', 
	'row' => '0.95', 
	'adjustment_factor' => '0')

with this float cast, the error was gone.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Trying to place an order with bankwire module, an error "Cannot use a scalar value as an array." occured pointing to this line in the Tools.php class. Customers couldn't finish the order.
| Type?         | bug fix 
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no tickets found only similar entry: https://www.prestashop.com/forums/topic/635593-contexterrorexception%C2%A0in%C2%A0toolsphp-line-3780/
| How to test?  | Place an order with above values.

2018-06-26 17:17 UTC, PierreRambaud commented
Not sure it really fixed the problem. The real problem is why there is a scalar value instead of an array here? Can you display the value of `$row` and `$column` where it fails? 
Regards

2018-06-27 08:45 UTC, Shopmonauten commented
Sure:
it fails with this:
array('amount' => '2.2204460492503E-16',
'precision' => '2',
'rows' => array('0.95'),
'column' => 'id_tax',
'sort_function' => 'lambda_1',
'unit' => '100',
'int_amount' => '0',
'remainder' => '0',
'amount_to_spread' => '0',
'sign' => '1',
'position' => '0',
'row' => '0.95',
'adjustment_factor' => '0')

2018-06-27 16:09 UTC, PierreRambaud commented
I can't reproduce bug in version 1.7.4.x and develop and 1.7.3.x, can you send us a video or a couple of sreenshot about what you did? When you say Bankwire module you talk about `ps_wirepayment`?

More casting a not scalar value like this can introduce another bug:

```php
var_dump((float)['6.65']); //double(1) and not double(6.65)
var_dump((float)[6.65]); //double(1)
```

We really need to find the real bug :)

2018-06-27 18:49 UTC, PierreRambaud requested changes
See my latest comment

2019-10-22 09:21 UTC, marionf commented
Hello @Shoprunners 

Since we can't reproduce the issue and we have not had news for more than 30 days, I close it.
Feel free to open an issue and describe the steps to reproduce it if you still have it with the last version

2019-10-22 09:21 UTC, closed without merging