CO: Missing call of ObjectModel hooks in CMSCategory delete function
PrestaShop/PrestaShop pull request #9231
Opened 2018-06-28 12:21 UTC by Matt75

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | In CMSCategory class, the delete method doesn't call to parent ObjectModel delete method so any hook is called.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-5847
| How to test?  | Create a module and try to retrieve ID of CMSCategory deleted, you can't because there are any hook for that.

2018-07-03 07:01 UTC, mickaelandrieu requested changes
Some changes, mostly related to the fact we don't want to add new public API to object models.

Good job so far

2018-07-03 07:01 UTC, mickaelandrieu commented on classes/CMSCategory.php
> +    public function deleteLite()
would you mind to make this function private?

2018-07-03 07:01 UTC, mickaelandrieu commented on classes/CMSCategory.php
> +        $objects = $this->getAllChildren();
I don't like `objects` as the variable name, we are manipulating CMS categories here, right?

So I'd like to the see `$cmsCategories` instead.

2018-07-03 07:01 UTC, mickaelandrieu commented on classes/CMSCategory.php
> +    public function deleteCMS()
would you mind to make this function private?

2018-07-03 07:01 UTC, mickaelandrieu commented on classes/CMSCategory.php
> +        $cms = new PrestaShopCollection('CMS');
smart refactoring :+1:

2018-07-03 07:01 UTC, mickaelandrieu commented on classes/CMSCategory.php
> +    public function getAllChildren()
make this function private please

2018-07-04 08:06 UTC, mickaelandrieu approved these changes

2018-07-04 14:22 UTC, marionf commented
Hello @Matt75 
Could you provide a module allowing to test your PR ?

2018-07-05 08:44 UTC, Matt75 commented
Hi @marionf 
You can find a test module here : https://github.com/Matt75/testhookcmscategories

2018-07-06 12:49 UTC, marionf commented
It's ok, thank you for the module @Matt75 :)

2018-07-06 12:56 UTC, Matt75 commented
@marionf @mickaelandrieu Same PR for 1.6.1.x here https://github.com/PrestaShop/PrestaShop/pull/8295 😇

2018-07-06 13:08 UTC, mickaelandrieu approved these changes

2018-07-18 09:48 UTC, eternoendless commented
Thank you @Matt75

2018-07-18 09:48 UTC, merged