Update Controller name for link generation to modules catalog
PrestaShop/PrestaShop pull request #9261
Opened 2018-07-04 15:24 UTC by Quetzacoalt91

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.4.x
| Description?  | With the new module controller links, the "Recommended modules" link wasn't redirecting the merchant to the catalog anymore.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | Nope
| Deprecations? | Nope
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-5704
| How to test?  | Click on recommended modules

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/9261)

2018-07-04 15:39 UTC, mickaelandrieu commented
Hello,

in system information page, the link still redirect to modules page.

2018-07-04 16:11 UTC, mickaelandrieu requested changes
imo, the way we retrieve this link is different in modern pages, maybe in FrameworkAdminController

2018-07-04 16:24 UTC, Quetzacoalt91 commented
The issue asked to redirect to the module catalog instead of the module management page. If we have to deal with a popup instead, then the description original description is incomplete :thinking:

2018-07-04 16:27 UTC, mickaelandrieu commented
aww I believe we wanted to have the same behavior on legacy and modern pages.

But on legacy pages, you still have the poppin: wdyt @colinegin?

2018-07-04 17:16 UTC, Quetzacoalt91 commented
I've just tried on PS 1.7.1.0, the modal is absent on symfony pages (= product page).
Adding a modal will not be done on this PR, as it seems we deal with a new feature.

2018-07-04 18:49 UTC, mickaelandrieu approved these changes

2018-07-04 18:49 UTC, mickaelandrieu commented
ok then :)

2018-07-05 15:32 UTC, mbadrani commented
Not fine for me

2018-07-05 15:50 UTC, mbadrani commented
I approve, It resolve the bug

2018-07-05 15:54 UTC, merged

2018-07-05 15:54 UTC, PierreRambaud commented
Thanks @Quetzacoalt91

2018-07-05 16:27 UTC, marionf commented
With MBO installed, if I click on "Recommanded modules" on a symfony page, I am well redirected to the "Module Catalog" tab but it is not selected

![capture d ecran_13](https://user-images.githubusercontent.com/13449658/42335557-0af9871a-8081-11e8-8aee-39a6e5f0c4c4.png)

@Quetzacoalt91 I don't know if it should be corrected in the Core or in the MBO module ?