Add free shipping info in cart vouchers on FO
PrestaShop/PrestaShop pull request #9346
Opened 2018-07-18 13:36 UTC by tonyyb

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Currently on FO we can't know if added voucher is of type "free shipping"
| Type?         |  improvement 
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | Create a cart rule with Free shipping offer. On FO add the voucher code to get it. In `templates/checkout/_partials/cart-voucher.tpl` you have `$cart.vouchers.added` variable but you can't know if voucher is of type "Free shipping". It would be useful to be able to do specific things.

2018-07-18 13:54 UTC, Quetzacoalt91 commented
Hi @tonyyb,

I wonder if we did not already merge another PR about that specific issue. Can you check you still have the issue with https://github.com/PrestaShop/PrestaShop/pull/9295?
ping @tomlev

2018-07-18 14:03 UTC, tonyyb commented
Hi,
Yes I still have the issue with #9295 changes. 
My PR concerns presented data only.

2019-07-11 16:34 UTC, PierreRambaud commented
Really sorry for the delay. Could you please rebase your branch please?
We will do our best to merge as fast as possible after the rebase.

2019-07-17 06:01 UTC, tonyyb commented
Rebase done.

2019-07-17 08:46 UTC, PierreRambaud approved these changes

2019-07-17 08:47 UTC, PierreRambaud commented on src/Adapter/Presenter/Cart/CartPresenter.php
> +            $vouchers[$cartVoucher['id_cart_rule']]['free_shipping'] = $cartVoucher['free_shipping'];
Could you please move this line on line 491?

2019-07-17 08:47 UTC, PierreRambaud requested changes
See comments. Sorry :/

2020-09-15 16:11 UTC, matks commented
Hi, [following our review guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/) "Pull Requests may be closed after 30 days of inactivity following a request for modifications".

Since we did not get answer from author I close this PR.

Please note this does not mean it's a final "won't merge" 😉 if you come back we can reopen it

Thank you for the contribution

2020-09-15 16:11 UTC, closed without merging