[CO] Prevent malformed URL like /fr/index.php?
PrestaShop/PrestaShop pull request #9367
Opened 2018-07-23 13:52 UTC by SebBareyre

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This modification prevents the language from being added for URLs that start with `/index.php?`
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | Visit the page "Order history" and clic on "Details" on one of your order. Finally, check the URL

2018-07-23 14:07 UTC, SebBareyre reviewed
add missing space

2018-07-23 14:55 UTC, PierreRambaud commented on classes/Link.php
> +        } else {
else is useless because of returns statements :)

2018-07-23 14:58 UTC, SebBareyre reviewed
remove else

2018-07-30 09:01 UTC, SebBareyre commented
@PierreRambaud : Any news for this PR ?

2018-07-30 09:55 UTC, PierreRambaud submitted a review, later dismissed

2018-07-30 09:55 UTC, PierreRambaud commented
Sorry for the delay :)

2018-07-30 09:59 UTC, SebBareyre commented
No problem @PierreRambaud :)

2018-07-30 13:10 UTC, ntiepresta commented
Hi, @SebBareyre 

Could you please provide us with more info? We need more details to understand how we can reproduce your issue.
- screenshots for exemple

Best regards, Reddy

2018-07-30 13:23 UTC, SebBareyre commented
[Here](https://pasteboard.co/HwR6ydt.jpg) you'll find a screenshot that shows how you will reproduce the bug. This bug occurs each time a URL called is not rewritten on nginx...

2018-07-30 13:45 UTC, ntiepresta commented
Thank you @SebBareyre

2018-07-30 14:13 UTC, PierreRambaud commented
Hum look like E2E tests are broken :/

2018-07-30 14:21 UTC, SebBareyre commented
@PierreRambaud how can I re-run E2E tests please ?

2018-07-30 14:26 UTC, PierreRambaud commented
@SebBareyre If you wait for #9301 it will be easier to execute E2E tests :)

2018-08-01 13:26 UTC, mickaelandrieu commented
Looking at stack trace, I've found this error in logs:

[01-Aug-2018 15:02:45 Europe/Paris] PHP Warning:  Base directory /home/travis/build/PrestaShop/PrestaShop/var/cache/prod/purifier does not exist,
                    please create or change using %Cache.SerializerPath in /home/travis/build/PrestaShop/PrestaShop/tools/htmlpurifier/HTMLPurifier.standalone.php on line 15280


This may not be related at all.

Also @PierreRambaud, how can we access the screenshots on travis? I've looked at all builds and I can't manage to get the base64 strings of captures.

Still investigating on this, wait and chill fellows :sunglasses:

2018-08-01 15:03 UTC, PierreRambaud commented
@mickaelandrieu You can add a parameter `PRESTASTHOP_SCREENHOST` while building.

2018-08-06 00:16 UTC, mickaelandrieu commented
> You can add a parameter PRESTASTHOP_SCREENHOST while building

I don't build anything as the docker image to run e2e tests is broken :(

2018-08-13 15:27 UTC, mickaelandrieu commented
Hello @PierreRambaud, would you like to take a closer look at it if you are now able to launch e2e tests using docker.

I still can't :/

2018-08-14 15:14 UTC, PierreRambaud commented
@mickaelandrieu You have now the capability to reproduce in local with latest commits.

2018-08-14 15:55 UTC, mickaelandrieu commented
@PierreRambaud I guess the docker image forgot some scenarios, isn't it?

>  99 passing (40s) on Docker

> 121 passing (80.50s) on Travis
   1 failing

2018-08-14 19:10 UTC, PierreRambaud commented
It run the documented command `npm run test`. But you can run the test you want to execute inside the docker container.

2018-09-03 15:44 UTC, Quetzacoalt91 commented
Squashed & rebased

2018-09-04 10:20 UTC, Quetzacoalt91 requested changes
Hmm, it appears after a quick test that we cannot change the language anymore once we are on the order history. This is probably what's making the E2E test failing.

Removing QA :heavy_check_mark:

2018-09-19 10:07 UTC, SebBareyre commented
@Quetzacoalt91 I just test to change language on an order history page and it works... what did not work for you ?

2018-09-19 10:57 UTC, Quetzacoalt91 commented
With your PR, URLs like

```
http://ip6-localhost/PrestaShop/fr/index.php?controller=order-detail&id_order=6
```

becomes

```
http://ip6-localhost/PrestaShop/index.php?controller=order-detail&id_order=6
```

We loose the reference to a language in the URL, and this prevents the customer to use another language.
To reproduce the issue, go to a order history then try to switch language. You'll see that whatever the language you choose, the URL will be the same.

![capture du 2018-09-19 11-56-15](https://user-images.githubusercontent.com/6768917/45749294-21a22b80-bc03-11e8-99f0-bff88ef90e5b.png)

2021-08-11 16:26 UTC, matks commented
Hi everyone !

I'm sorry I dont know why this one went under the radar for so long.

@SebBareyre In 2018 ( 😅  ) Quetzacoalt91 reported an issue in how the logic behaves, which introduces an issue. Do you feel like getting back to this PR or should I close it?

2021-10-01 07:55 UTC, PierreRambaud commented
Hi @SebBareyre ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

2021-10-01 07:55 UTC, closed without merging