Fix label "Use this address for invoice too'"
PrestaShop/PrestaShop pull request #9381
Opened 2018-07-26 10:44 UTC by iqit-commerce

Label was not clickable

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | fix not clickable label of "use same addres for invoice".
| Type?         | bug fix 
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | 

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!

2018-07-26 11:53 UTC, PierreRambaud requested changes
It's a partial and this template is used twice in `addresses.tpl`, you can see a html error in your browser developer toolbar.
Maybe move `<input />` in `<label>` instead of setting an id.

2018-07-26 12:10 UTC, iqit-commerce commented
@PierreRambaud Yes it used twice, but checkbox is showed once only becouse there is if statment
{if $type === "delivery"}
show invoice
{/if}

and becouse of that it is showed once only so there is no duplicated id

2018-07-26 12:37 UTC, PierreRambaud approved these changes

2018-07-26 12:37 UTC, PierreRambaud commented
@iqit-commerce My bad, didn't see one conditions in parent template :D

2018-07-30 08:35 UTC, merged

2018-07-30 08:35 UTC, PierreRambaud commented
Thanks @iqit-commerce