Fix reduction exclude special feature
PrestaShop/PrestaShop pull request #9383
Opened 2018-07-27 06:42 UTC by kpodemski

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.4.x
| Description?  | before this fix you can use voucher on cart containing products with reduction even tho back-office option is checked to "yes" for excluding this scenario
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | i guess
| How to test?  | Instruction below

1. Add two products, for 100 EUR, one with 10% discount.
2. Add these two products to cart, you should have two products in cart for a total amount of 180 EUR, (100 + 80)
3. Add voucher for an order without shipping, 10%, exclude special products.
4. Result? Order is worth 162 EUR which shouldn't be a case as this coupon shouldn't be valid
5. Apply fix
6. Test again

2018-07-27 09:26 UTC, PierreRambaud submitted a review, later dismissed

2018-07-27 09:26 UTC, PierreRambaud commented
Hi and thanks for the feedback.
Can you please target the develop branch? :)

2018-07-27 09:34 UTC, PrestaShark commented
This is milestone bug fix. Should be applied also for 1.6 branch!
WELL DONE KRYSTIAN

2018-07-27 11:57 UTC, kpodemski commented
Hey @PierreRambaud 

i'm pretty sure that you can easily click it on github, right?

2018-07-27 12:00 UTC, kpodemski commented
btw. @mickaelandrieu @PierreRambaud @Quetzacoalt91 

we still don't know which branch to choose if we're making pull request... 

if that's a bugfix i was thinking that it should go to 1.7.4.x to path version as develop is 1.7.5... right?

2018-07-27 12:05 UTC, PierreRambaud commented
@kpodemski Totally agreed with you, we are currently talking about that :)

2018-08-03 15:20 UTC, eternoendless commented
We have clarified the [target branches to use for Pull Requests](https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/#target-branch).

In short, if it's not a regression of critical bug fix -> develop.

2018-08-03 15:25 UTC, kpodemski commented
@eternoendless hey, please don't only think as a developer here ok? what's not critical? merchants losing their money? imagine setting up new voucher, big one, and people can still use it with the other ones combining them, results are very bad for people running online stores

2018-08-03 17:01 UTC, eternoendless commented
It's not about the bug not being important to merchants. I explained this decision in this comment: https://github.com/PrestaShop/PrestaShop/pull/9387#issuecomment-410310634

We just can't push patch releases every other week. It's bad for quality, and it's bad for the whole project in the long run.

Let's look at it this way: you didn't include a test with your PR. Why do you think that is? What impact do you think it will have in the project? Why do you think bugs like this happen again and again?

I'm not saying you are at fault here - I really appreciate your involvement on the project. But we can't expect getting a different outcome if we keep making the same mistakes.

2018-08-03 17:30 UTC, kpodemski commented
I'm all in for writing tests, just make proper documentation of how to make them, or - because most of developers know how to do that - best practices or something like that, just to follow some standard methods

About this bug... it's simple fix which you can say by reading a code, the thing is that people are scared to upgrade from 1.7.X to 1.7.Y, very often people stay on 1.7.X branch and just update 1.7.0.X to 1.7.0.Y, why? because of years of problems with auto upgrade module - and yes, I know, there's a new version and all that... the thing is that even tho auto upgrade module is ok, some things are still not tested manually, for few days we couldn't install 1.7.4 in Polish version because ps_mbo module was badly created :) Now tell all people who tried to upgrade to 1.7.4 with all these problems to try again with 1.7.5 just to fix one important bug which saves them money :)

2018-08-06 12:19 UTC, eternoendless commented
I'd very much like to be able to say "here, just read this doc and add a test there, it's easy"... but unfortunately it's not 😢 

I actually did think about asking you to add a test, then had a look at the cart tests, and concluded that we can't realistically ask people to add test cases there, it's just too complicated. Check it out: https://github.com/PrestaShop/PrestaShop/tree/develop/tests/Unit/Core/Cart/Calculation/CartRules

I have started considering Behat for this kinds of tests. It will be much, much easier to add test cases if they are written using Gherkin language.

2018-08-07 06:01 UTC, kpodemski commented
@eternoendless i can add tests to https://github.com/PrestaShop/PrestaShop/tree/develop/tests/Unit/Core/Cart/Calculation/CartRules

no problem :)

i don't think that we need Behat, we have e2e tests right? i think that unit + e2e should be enough, correct me if i'm wrong

2018-08-07 07:36 UTC, matks commented
Behat is just a gateway to ease a lot the process of writing test cases as users can describe their testable scenario in meaningful sentences and not (sometimes obscure) php statements. You might be able to add e2e and unit tests, but maybe not everyone who contributes to Prestashop :) .

And behat can act as a useful middle test layer between unit tests (single focus, php-oriented) and e2e tests (application focus, JS and frontend oriented) that allows to provide test coverage for parts of prestashop, not either a class or the full app.

2018-08-10 09:47 UTC, eternoendless commented
As @matks said, even though Behat _can_ be used for E2E tests, that's not what I had in mind.

There are three kinds of tests: Unit, Integration and End to End (E2E).

**Unit tests** are meant to test an isolated class, that is, make sure that a class does what it is expected to do, by testing its methods one by one. All dependencies of the tested class must be mocked. PhpUnit was made for this kind of tests.

**E2E tests** are used to automate manual tests that go through a user interface, typically a browser. They test user-cases just as the user would experience them. We currently use Mocha and Selenium for this.

**Integration tests** verify a subsystem, that is, a number of objects working together with minimal or no mocking. Price calculation using vouchers, etc. would be tested using these kinds of tests. We currently use PhpUnit for this, but it's clear that it's not the right tool for the job as tests are very hard to set up and understand. This is where I think Behat would help us write more understandable and maintainable tests.

@kpodemski If you feel comfortable adding tests to CartRules, by all means, please do!

2018-08-22 21:11 UTC, mickaelandrieu commented
ping @eternoendless: what do we do for this pull request? LGTM/ no-go / waiting for QA?

2018-09-05 15:40 UTC, tomlev requested changes
these changes seems to not correctly fix the bug : 
you changed the check to know if the cart rule can be applied or not. In this context previous code seems to be valid : cart rule can be applied if one product or more do not have reduction. With your changes, cart rule will not be applied if one product has a reduction.

So I think the fix should be in the class CartRuleCalculator, around line 177, when retrieving concerned products to calculate cart rule discount amount

I think something like following should do the job : 

            } elseif ($cartRule->reduction_product == 0) {
                if ($cartRule->reduction_exclude_special){
                    foreach ($this->cartRows as $cartRow) {
                        if (!$cartRow->getRowData()['reduction_applies']) {
                            $concernedRows->addCartRow($cartRow);
                        }
                    }
                } else {
                    // Discount (¤) on the whole order
                    $concernedRows = $this->cartRows;
                }
            }

2018-09-05 15:51 UTC, kpodemski commented
@tomlev with this change you'll alter behavior, not fix bug, by reading original code it was never meant  to calculate only products without discounts, although i can agree with you that this should work in a way you describe

but... you know what? at this moment i don't care about this PR, as we can all see team is more focused on Symfony back-office than default features working is expected, we don't even have stable product combinations, translations, we can't even save products in some scenarios... ;)

2018-09-05 16:03 UTC, tomlev commented
@kpodemski thanks for your support. I referenced the issue here to get our team test expected behaviour : https://github.com/PrestaShop/PrestaShop/issues/10300

2018-09-05 16:06 UTC, eternoendless commented
> we can all see team is more focused on Symfony back-office than default features working as expected (...) we don't even have stable product combinations, translations, we can't even save products in some scenarios

I suppose you're talking about the problem with too many combinations. It has been discussed several times now. It's very hard to solve because of design constraints. The form grows too big, so it fails to be handled by PHP. To fix it we need to completely change the structure of the Product page to break it down in pieces. We'll get there sooner than later.

But this is exactly the reason why we need to press on with the Symfony migration. The longer we drag on with legacy code, the harder it is to fix bugs. I thought you knew that already.

2018-09-05 17:01 UTC, kpodemski commented
@eternoendless 

i'm talking about this issue: https://github.com/PrestaShop/PrestaShop/issues/9954

this has nothing to do with combination but it's extremely annoying, for some reason product informations are not correctly updated in few scenarios and PrestaShop does not handle these scenarios correctly

2018-09-06 13:29 UTC, eternoendless commented
Oh, I wasn't aware of that particular issue. Thanks for bringing it up @kpodemski

2020-06-18 21:17 UTC, closed without merging