FO: override a method uses private variable when you inheritance CustomerAddressFormatterCore
PrestaShop/PrestaShop pull request #9420
Opened 2018-08-08 11:55 UTC by azisyus

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | this PR  solves same thing in different class, check #9417  
| Type?         | improvement
| Category?     | FO 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | these access modifiers cant break anything

2018-08-08 12:48 UTC, Quetzacoalt91 approved these changes

2018-08-13 08:42 UTC, mickaelandrieu requested changes
For me it's wrong to do this, and this will encourage class overriding, what we don't want (plus, this class have an interface so people are already able to create their own implementation the right way).

2018-08-13 08:42 UTC, mickaelandrieu commented on classes/form/CustomerAddressFormatter.php
> +    protected $country;
you don't need this as you have getter and setter for these properties

2018-08-13 08:50 UTC, mickaelandrieu commented on classes/form/CustomerAddressFormatter.php
> +    protected $country;
The only boring thing is this line:

```php
         $this->definition = Address::$definition['fields'];
```

We may inject definition instead ...

2018-08-13 08:50 UTC, mickaelandrieu requested changes
I understand the need, but not the way to do it.

2018-08-13 09:35 UTC, mickaelandrieu commented
Hello @azisyus,

can we discuss a Hook that can help you with what you want to do?

2018-08-13 14:45 UTC, azisyus commented
@mickaelandrieu actually and basically i need 2 different address form, i mean in original definition of address form 

`Address::$definition['fields'];`

 has company and vat_number fields and in my country while buying new things from ecom sites we dont need these fields for **delivery address** form but same time i need these fields for **invoice address** form because of laws then i though, there is only one table i can store addresses so i can show different parts of address form in different places and it will look like a 2 different form :D it was tricky and disgusting way and end of the week i just rolled back many commit and put the original form to everywhere and i need a hook way to do it or i need to override all classes got relation with addresses

2018-08-13 15:02 UTC, mickaelandrieu commented
maybe this demonstration module can help? https://github.com/mickaelandrieu/products/blob/master/products.php#L110

Basically, you can alter an Object Model definition without an override or update its file, then you could use a hook and decide in which cases you want specific extra fields or not: wdyt?

2018-08-13 16:04 UTC, azisyus commented
@mickaelandrieu adding new fields to address form is easy part, hard part is i need to show them in templates/customer/addresses.tpl as separated columns i mean delivery addresses will be list in left side and  invoice addresses will be list in right side, in crud page they should show their own form and i dont think we can put this kind of feature that easily with this architecture because there is only one form and we choose delivery and invoice addresses between all  in checkoutAddressStep and everything is turning around of this
![step0001](https://user-images.githubusercontent.com/26818892/44042698-9b4e5a9a-9f29-11e8-82ce-00afef527712.png)

2018-08-13 16:38 UTC, mickaelandrieu commented
I'm not really an expert of legacy form rendering, but I can we can override the template for a specific form.

I guess @Quetzacoalt91 or @rGaillard are far better than me at answering this :+1:

2020-05-20 07:31 UTC, matks requested changes
I agree with @mickaelandrieu. Most of the time, modifying the scope of a variable from private to protected is a bad solution to a good problem. We should not merge this PR like this, but rather consider a better solution.

2020-05-20 08:11 UTC, PierreRambaud commented
Hi @azisyus ,

This kind of change is already being discussed in #11910. As this one is a duplicate of the second link, I'm closing it as a duplicate. I let you participate in the debate if needed.

Regards

2020-05-20 08:11 UTC, closed without merging